"""
Authoritative Pedagogical Specification for B1 Section 02: Part 3 (Units 130 - 132)
Units 130 (4 lessons), 131 (4 lessons), 132 (5 lessons) -> 13 lessons
"""

from typing import List, Dict, Any

def get_sec02_part3_lessons() -> List[Dict[str, Any]]:
    lessons = []

    # =========================================================================
    # UNIT 130: Limiting & Incidental Converb: Suffixes -нгаа/-нгээ
    # Budget: (22, 15, 6, 4) across 4 lessons -> (6,4,2,1), (6,4,2,1), (5,4,1,1), (5,3,1,1)
    # =========================================================================
    uid_130 = "unit_b1_130_limiting_incidental_converb_suffixe"
    lessons.extend([
        {
            "lessonId": "les_b1_130_01_limiting_converb_morphosyntax_intro",
            "unitId": uid_130, "cefrLevel": "B1", "sequenceWithinUnit": 1,
            "title": "Incidental Simultaneity: The Limiting Converb -нгаа/-нгээ (Multitasking & Secondary Actions)",
            "lessonType": "grammar_introduction",
            "primaryPurpose": "Introduce the limiting/incidental converb suffix -нгаа⁴ expressing: 1) doing a secondary action concurrently while primarily engaged in another ('while doing X, on the way, simultaneously'), and 2) taking advantage of an opportunity to perform an incidental task (далимдуулан).",
            "communicativeOutcome": "Formulate compound sentences describing multitasking, concurrent activities, and opportunistic secondary tasks in daily life and work.",
            "objectivesIntroduced": ["obj_b1_130_01_form_limiting_converb"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_b1_129_01_form_modal_converb_n"],
            "grammarIntroduced": ["gram_b1_converb_limiting_ngaa"],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_verb_aspect_progressive_j_baina", "gram_b1_converb_modal_manner_n"],
            "phonologyIntroduced": ["phono_b1_velar_nasal_ng_glide"],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_vowel_harmony_basic"],
            "communicativeFunctionsIntroduced": ["comm_b1_02_sequencing_past_chronology"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 4, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_opinion_argumentation_rhetoric", "lex_b1_education_career_workplace"],
            "previousVocabularyReused": ["явах", "хийх", "унших", "уух", "сонирхох", "уулзах"],
            "readingObjective": "", "listeningObjective": "",
            "writingObjective": "Transform 8 verb stems into limiting converbs and construct sentences describing concurrent work and study habits.",
            "spokenProductionObjective": "Explain two activities you regularly conduct simultaneously during your morning commute or lunch hour.",
            "registerTarget": "Conversational and professional everyday workflow register",
            "pragmaticTarget": "Highlighting time efficiency and multitasking capability in daily routines.",
            "prerequisiteLessonIds": ["les_b1_129_04_narrating_character_anecdote_spoken"],
            "reviewsLessonIds": ["les_b1_129_01_modal_converb_n_morphology_intro"],
            "reviewsUnitIds": ["unit_b1_129_modal_converb_of_manner_suffix_"],
            "reviewReason": "Expands simultaneous manner (-н) to concurrent incidental secondary actions (-нгаа).",
            "audioSuitability": "standard_speech_synthesis_acceptable",
            "audioPurpose": "Model clean articulation of the velar nasal /ŋ/ before long vowels in -нгаа/-нгээ/-нгоо/-нгөө.",
            "successCriteria": [
                "Selects proper harmonic suffix variant (-нгаа⁴) based on verbal root vocalism",
                "Constructs sentences where the subject performs both actions concurrently"
            ],
            "masteryEvidence": "Produces 'Би кофе уунгаа сонин уншив' and 'Хөдөө явангаа олон сайхан зураг авав' accurately.",
            "recommendedExerciseModalities": ["suffix_transformation", "multitasking_pairing", "sentence_completion"]
        },
        {
            "lessonId": "les_b1_130_02_opportunistic_action_lexicon",
            "unitId": uid_130, "cefrLevel": "B1", "sequenceWithinUnit": 2,
            "title": "Opportunistic Actions Lexicon: Taking Advantage of Situations & Incidental Chores",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Acquire vocabulary denoting seizing opportunities, incidental errands, multi-purpose travel, and sideline tasks (далимдуулах, дашрамд дурдахад, зам зуураа, амжуулах, хажуугаар нь).",
            "communicativeOutcome": "Explain how you combine business trips with leisure, run incidental errands on commutes, and seize opportune moments.",
            "objectivesIntroduced": ["obj_b1_130_02_opportunistic_action_lexicon"],
            "objectivesPracticed": ["obj_b1_130_01_form_limiting_converb"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_converb_limiting_ngaa"],
            "grammarReviewed": ["gram_a1_case_ablative_origin"],
            "phonologyIntroduced": [], "phonologyPracticed": [], "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_02_sequencing_past_chronology"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 4, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_opinion_argumentation_rhetoric", "lex_b1_travel_transport_tourism"],
            "previousVocabularyReused": ["боломж", "ажил", "зам", "хэрэгцээ", "амжих"],
            "readingObjective": "", "listeningObjective": "",
            "writingObjective": "Draft 4 sentences explaining how you plan to accomplish 2 errands along the route of an official meeting.",
            "spokenProductionObjective": "Use 'дашрамд дурдахад' and 'зам зуураа' naturally in a spoken conversation regarding weekend plans.",
            "registerTarget": "Pragmatic conversational and workplace planning register",
            "pragmaticTarget": "Using discourse markers like 'дашрамд дурдахад' to introduce relevant secondary points politely.",
            "prerequisiteLessonIds": ["les_b1_130_01_limiting_converb_morphosyntax_intro"],
            "reviewsLessonIds": ["les_b1_130_01_limiting_converb_morphosyntax_intro"],
            "reviewsUnitIds": ["unit_b1_130_limiting_incidental_converb_suffixe"],
            "reviewReason": "Supplies opportunistic action vocabulary to complement incidental converbial syntax.",
            "audioSuitability": "standard_speech_synthesis_acceptable",
            "audioPurpose": "Pronounce idiomatic opportunism phrases in authentic Mongolian contexts.",
            "successCriteria": [
                "Pairs incidental adverbs with limiting converbs (зам зуураа явангаа ажил амжуулах)",
                "Uses 'дашрамд хэлэхэд' correctly to pivot to secondary topics in discourse"
            ],
            "masteryEvidence": "Produces 'Би хуралд суунгаа далимдуулан төслийн санаагаа танилцуулчихлаа' fluently.",
            "recommendedExerciseModalities": ["idiom_matching", "errand_scheduling_task", "dialogue_cloze"]
        },
        {
            "lessonId": "les_b1_130_03_travelogue_errands_reading",
            "unitId": uid_130, "cefrLevel": "B1", "sequenceWithinUnit": 3,
            "title": "Reading Analysis: Travelogues of Field Expeditions & Incidental Discoveries",
            "lessonType": "reading_development",
            "primaryPurpose": "Deconstruct authentic Mongolian travel writings, field notebooks of researchers, and journalist diaries combining primary missions with incidental cultural encounters.",
            "communicativeOutcome": "Comprehend complex multi-layered narratives where primary scientific goals and incidental cultural observations intertwine.",
            "objectivesIntroduced": ["obj_b1_130_03_read_field_travelogues"],
            "objectivesPracticed": ["obj_b1_130_01_form_limiting_converb"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_converb_limiting_ngaa"],
            "grammarReviewed": ["gram_a2_verb_future_deductive_kh_bolno", "gram_b1_converb_contemporaneous_magts"],
            "phonologyIntroduced": [], "phonologyPracticed": [], "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_02_sequencing_past_chronology"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 4, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_opinion_argumentation_rhetoric", "lex_b1_environment_geography_climate"],
            "previousVocabularyReused": ["аялал", "хээрийн шинжилгээ", "нутгийн иргэд", "соёл", "байгаль"],
            "readingObjective": "Read a 280-word excerpt from a botanical field diary and identify 3 incidental discoveries made while traveling between research plots.",
            "listeningObjective": "", "writingObjective": "", "spokenProductionObjective": "",
            "registerTarget": "Scientific field expedition journal register",
            "pragmaticTarget": "Differentiating primary methodological protocols from opportunistic field discoveries.",
            "prerequisiteLessonIds": ["les_b1_130_01_limiting_converb_morphosyntax_intro"],
            "reviewsLessonIds": ["les_b1_127_03_memoir_journalism_reading"],
            "reviewsUnitIds": ["unit_b1_127_contemporaneous_converb_suffixes_"],
            "reviewReason": "Extends travel reading from dramatic eyewitness crisis to methodical exploratory journals.",
            "audioSuitability": "standard_speech_synthesis_acceptable",
            "audioPurpose": "Narration of botanical field notes with descriptive atmospheric pacing.",
            "successCriteria": [
                "Identifies limiting converb clauses describing concurrent research activities",
                "Separates primary itinerary checkpoints from spontaneous stops and meetings"
            ],
            "masteryEvidence": "Identifies that the botanist documented a rare medicinal herb while surveying pasture degradation.",
            "recommendedExerciseModalities": ["field_log_analysis", "converb_highlighting", "multiple_choice"]
        },
        {
            "lessonId": "les_b1_130_04_workplace_multitasking_dialogue",
            "unitId": uid_130, "cefrLevel": "B1", "sequenceWithinUnit": 4,
            "title": "Interactive Dialogue: Coordinating Concurrent Deliverables with a Colleague",
            "lessonType": "dialogue_work",
            "primaryPurpose": "Simulate an interactive planning discussion between two project coordinators synchronizing upcoming conference logistics while preparing financial audits.",
            "communicativeOutcome": "Negotiate who will handle which secondary tasks while executing primary operational commitments.",
            "objectivesIntroduced": ["obj_b1_130_04_coordinate_concurrent_tasks"],
            "objectivesPracticed": [
                "obj_b1_130_01_form_limiting_converb",
                "obj_b1_130_02_opportunistic_action_lexicon"
            ],
            "objectivesReviewed": ["obj_b1_120_03_mediate_stakeholder_disputes"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_converb_limiting_ngaa"],
            "grammarReviewed": ["gram_a1_verb_aspect_progressive_j_baina"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_b1_velar_nasal_ng_glide"],
            "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_02_sequencing_past_chronology"],
            "communicativeFunctionsReviewed": ["comm_b1_18_delegating_tasks_causative"],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_opinion_argumentation_rhetoric", "lex_b1_education_career_workplace"],
            "previousVocabularyReused": ["төлөвлөгөө", "хамтран ажиллах", "хуваарилах", "хугацаа", "үүрэг"],
            "readingObjective": "", "listeningObjective": "",
            "writingObjective": "",
            "spokenProductionObjective": "Enact an 8-turn dialogue coordinating two overlapping project workstreams using -нгаа converbs.",
            "registerTarget": "Dynamic collaborative professional register",
            "pragmaticTarget": "Proposing helpful efficiencies ('Би банк орохдоо таны бичгийг аваачаад өгчихье') to foster team synergy.",
            "prerequisiteLessonIds": ["les_b1_130_02_opportunistic_action_lexicon", "les_b1_130_03_travelogue_errands_reading"],
            "reviewsLessonIds": ["les_b1_118_03_bilateral_negotiation_dialogue"],
            "reviewsUnitIds": ["unit_b1_118_reciprocal_collaborative_voice_suff"],
            "reviewReason": "Applies collaborative teamwork dynamics to efficient multi-task coordination.",
            "audioSuitability": "mongolian_voice_required",
            "audioPurpose": "Realistic office dialogue between two busy Mongolian project managers.",
            "successCriteria": [
                "Maintains rapid, natural turn-taking exchanging task assignments",
                "Integrates -нгаа converbial clauses to combine logistical errands smoothly"
            ],
            "masteryEvidence": "Negotiates 'Чи хэвлэх үйлдвэр орохдоо наад урилгуудыг аваад ирж амжих уу? Би энд тайлангаа бичингээ хүлээж байя' flawlessly.",
            "recommendedExerciseModalities": ["branching_dialogue", "task_allocation_simulation", "spoken_roleplay"]
        }
    ])

    # =========================================================================
    # UNIT 131: Abnutative Converb: Suffix -лгүй
    # Budget: (22, 15, 6, 4) across 4 lessons -> (6,4,2,1), (5,4,2,1), (6,4,1,1), (5,3,1,1)
    # =========================================================================
    uid_131 = "unit_b1_131_abnutative_converb_suffix_"
    lessons.extend([
        {
            "lessonId": "les_b1_131_01_abnutative_converb_morphosyntax_intro",
            "unitId": uid_131, "cefrLevel": "B1", "sequenceWithinUnit": 1,
            "title": "Negative Concomitance: The Abnutative Converb -лгүй (Without Doing)",
            "lessonType": "grammar_introduction",
            "primaryPurpose": "Introduce the abnutative converb suffix -лгүй indicating: 1) doing an action without performing another expected action ('without eating, without stopping, without hesitation'), and 2) double negative emphasis of certainty (-лгүй яах вэ / байж болохгүй).",
            "communicativeOutcome": "Formulate negative concomitant clauses expressing omissions, non-actions, and emphatic affirmations in connected discourse.",
            "objectivesIntroduced": ["obj_b1_131_01_form_abnutative_converb"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_b1_130_01_form_limiting_converb"],
            "grammarIntroduced": ["gram_b1_converb_abnutative_lgui"],
            "grammarPracticed": [], "grammarReviewed": ["gram_b1_reported_speech_indirect_tense_shift", "gram_b1_converb_durative_saar"],
            "phonologyIntroduced": ["phono_b1_lateral_fricative_lgui_assimilation"],
            "phonologyPracticed": [], "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": ["comm_b1_05_making_causal_arguments"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 4, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_opinion_argumentation_rhetoric"],
            "previousVocabularyReused": ["зогсох", "идэх", "хэлэх", "бодох", "мэдэх", "эргэлзэх"],
            "readingObjective": "", "listeningObjective": "",
            "writingObjective": "Transform 8 verbs into abnutative converbs and construct complex sentences describing non-stop effort or action without hesitation.",
            "spokenProductionObjective": "Explain an urgent action you took immediately without waiting for official confirmation.",
            "registerTarget": "Standard formal spoken and written discourse register",
            "pragmaticTarget": "Using -лгүй to emphasize decisiveness, omission, or absolute necessity.",
            "prerequisiteLessonIds": ["les_b1_130_04_workplace_multitasking_dialogue"],
            "reviewsLessonIds": ["les_b1_130_01_limiting_converb_morphosyntax_intro"],
            "reviewsUnitIds": ["unit_b1_130_limiting_incidental_converb_suffixe"],
            "reviewReason": "Contrasts positive concomitance (-нгаа) with negative privative concomitance (-лгүй).",
            "audioSuitability": "standard_speech_synthesis_acceptable",
            "audioPurpose": "Demonstrate the lateral cluster /lg/ in -лгүй without vowel separation.",
            "successCriteria": [
                "Attaches -лгүй correctly to verbal stems without vowel insertion",
                "Distinguishes between privative manner ('without doing') and emphatic consent (-лгүй яах вэ)"
            ],
            "masteryEvidence": "Produces 'Тэр юу ч бодолгүй шууд зөвшөөрөв' and 'Бид огт амарч суух завгүй ажиллав' flawlessly.",
            "recommendedExerciseModalities": ["suffix_transformation", "privative_clause_pairing", "sentence_completion"]
        },
        {
            "lessonId": "les_b1_131_02_omission_and_decisiveness_lexicon",
            "unitId": uid_131, "cefrLevel": "B1", "sequenceWithinUnit": 2,
            "title": "Decisiveness & Omission Lexicon: Unhesitating Resolve & Inadvertent Overlook",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Acquire specialized vocabulary denoting bold unhesitating action, inadvertent neglect, bypassing protocol, and unwavering determination (тээнэгэлзэлгүй, завсарлагагүй, үл тоон, анзааралгүй, алгасалгүй).",
            "communicativeOutcome": "Describe decisive personal choices, thorough inspections without omission, and accidental oversights.",
            "objectivesIntroduced": ["obj_b1_131_02_decisiveness_omission_lexicon"],
            "objectivesPracticed": ["obj_b1_131_01_form_abnutative_converb"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_converb_abnutative_lgui"],
            "grammarReviewed": ["gram_b1_converb_limiting_ngaa"],
            "phonologyIntroduced": [], "phonologyPracticed": [], "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_05_making_causal_arguments"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 4, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_opinion_argumentation_rhetoric", "lex_b1_education_career_workplace"],
            "previousVocabularyReused": ["шийдвэр", "айдас", "шалгалтын ажил", "анхаарал", "дутагдал"],
            "readingObjective": "", "listeningObjective": "",
            "writingObjective": "Formulate 4 sentences describing an exhaustive quality audit where no detail was overlooked using targeted abnutative adverbs.",
            "spokenProductionObjective": "Describe a crisis situation where you acted decisively without hesitating for a second.",
            "registerTarget": "High professional and psychological narrative register",
            "pragmaticTarget": "Projecting professional competence through thoroughness and absence of hesitation.",
            "prerequisiteLessonIds": ["les_b1_131_01_abnutative_converb_morphosyntax_intro"],
            "reviewsLessonIds": ["les_b1_131_01_abnutative_converb_morphosyntax_intro"],
            "reviewsUnitIds": ["unit_b1_131_abnutative_converb_suffix_"],
            "reviewReason": "Supplies vocabulary expressing omission and resolute non-action to pair with -лгүй.",
            "audioSuitability": "standard_speech_synthesis_acceptable",
            "audioPurpose": "Pronunciation of complex compound adverbs formed with -лгүй.",
            "successCriteria": [
                "Uses 'тээнэгэлзэлгүйгээр' and 'алгасалгүй' correctly in professional and narrative sentences",
                "Distinguishes deliberate omission from accidental oversight"
            ],
            "masteryEvidence": "Produces 'Аудитор баримтуудыг нэг ч алгасалгүй нарийвчлан шалгажээ' accurately.",
            "recommendedExerciseModalities": ["adverb_matching", "contextual_cloze", "sentence_reconstruction"]
        },
        {
            "lessonId": "les_b1_131_03_crisis_investigation_reports_reading",
            "unitId": uid_131, "cefrLevel": "B1", "sequenceWithinUnit": 3,
            "title": "Reading Analysis: Safety Incident Reviews & Failure-to-Act Findings",
            "lessonType": "reading_development",
            "primaryPurpose": "Analyze official investigative findings into industrial safety breaches or transportation failures examining what protocols operators failed to follow (-лгүй орхигдуулсан).",
            "communicativeOutcome": "Extract critical operational failures, skipped safety checks, and regulatory omissions from technical investigative reports.",
            "objectivesIntroduced": ["obj_b1_131_03_read_safety_investigations"],
            "objectivesPracticed": ["obj_b1_131_01_form_abnutative_converb"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_converb_abnutative_lgui"],
            "grammarReviewed": ["gram_b1_reported_speech_indirect_tense_shift"],
            "phonologyIntroduced": [], "phonologyPracticed": [], "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_05_making_causal_arguments"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 4, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_opinion_argumentation_rhetoric", "lex_b1_education_career_workplace"],
            "previousVocabularyReused": ["осол", "шалгалт", "дүрэм", "хариуцлага", "зөрчил"],
            "readingObjective": "Read a 300-word industrial inspection report and list 3 mandatory safety steps the crew bypassed before the machine failed.",
            "listeningObjective": "", "writingObjective": "", "spokenProductionObjective": "",
            "registerTarget": "Technical regulatory and legalistic investigative report register",
            "pragmaticTarget": "Identifying explicit liability rooted in procedural non-compliance and omissions.",
            "prerequisiteLessonIds": ["les_b1_131_01_abnutative_converb_morphosyntax_intro"],
            "reviewsLessonIds": ["les_b1_126_03_socio_economic_causality_reading"],
            "reviewsUnitIds": ["unit_b1_126_causal_conjunctions_connectors_"],
            "reviewReason": "Connects causal explanations with specific procedural omissions and violations.",
            "audioSuitability": "standard_speech_synthesis_acceptable",
            "audioPurpose": "Narration of technical investigative findings.",
            "successCriteria": [
                "Identifies negative converb clauses indicating bypassed safety checks",
                "Connects procedural omissions directly to subsequent mechanical failures"
            ],
            "masteryEvidence": "Identifies that the operator started the generator without checking the oil pressure level.",
            "recommendedExerciseModalities": ["incident_timeline", "omission_detection", "multiple_choice"]
        },
        {
            "lessonId": "les_b1_131_04_critical_post_mortem_debrief_spoken",
            "unitId": uid_131, "cefrLevel": "B1", "sequenceWithinUnit": 4,
            "title": "Spoken Production: Delivering a Post-Mortem Debrief on Preventable Failures",
            "lessonType": "spoken_production",
            "primaryPurpose": "Deliver an oral post-mortem debrief presentation identifying what crucial actions a project team failed to execute, substantiating how future recurrences can be eliminated.",
            "communicativeOutcome": "Deliver an objective, actionable critique of team performance focusing constructively on omitted steps and preventative safeguards.",
            "objectivesIntroduced": ["obj_b1_131_04_deliver_post_mortem_debrief"],
            "objectivesPracticed": [
                "obj_b1_131_01_form_abnutative_converb",
                "obj_b1_131_02_decisiveness_omission_lexicon"
            ],
            "objectivesReviewed": ["obj_b1_126_05_deliver_causal_briefing"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_converb_abnutative_lgui"],
            "grammarReviewed": ["gram_b1_converb_durative_saar"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_b1_lateral_fricative_lgui_assimilation"],
            "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_05_making_causal_arguments"],
            "communicativeFunctionsReviewed": ["comm_b1_20_clarifying_misunderstandings"],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_opinion_argumentation_rhetoric", "lex_b1_education_career_workplace"],
            "previousVocabularyReused": ["дүгнэлт", "алдаа", "засах", "цаашид", "арга хэмжээ"],
            "readingObjective": "", "listeningObjective": "", "writingObjective": "",
            "spokenProductionObjective": "Deliver a 2-minute oral presentation outlining 3 omissions that led to project failure and recommending corrective protocols.",
            "registerTarget": "Objective professional debrief and quality control register",
            "pragmaticTarget": "Framing procedural omissions objectively to prevent defensiveness and encourage reform.",
            "prerequisiteLessonIds": ["les_b1_131_02_omission_and_decisiveness_lexicon", "les_b1_131_03_crisis_investigation_reports_reading"],
            "reviewsLessonIds": ["les_b1_126_05_explaining_systemic_causes_spoken"],
            "reviewsUnitIds": ["unit_b1_126_causal_conjunctions_connectors_"],
            "reviewReason": "Synthesizes systemic causal explanations with precise omission analysis in spoken debrief.",
            "audioSuitability": "mongolian_voice_required",
            "audioPurpose": "Benchmark model of a constructive executive post-mortem presentation.",
            "successCriteria": [
                "Delivers a 2-minute structured debrief using at least 3 abnutative converbs (-лгүй)",
                "Proposes concrete preventative solutions for every identified omission"
            ],
            "masteryEvidence": "Delivers 'Бид хэрэглэгчийн санал хүсэлтийг сонсолгүйгээр шинэ хувилбарыг гаргасан нь том алдаа боллоо' persuasively.",
            "recommendedExerciseModalities": ["post_mortem_monologue", "peer_critique", "solution_proposal"]
        }
    ])

    # =========================================================================
    # UNIT 132: Epistemic Probability: Particles Бололтой vs Магадгүй
    # Budget: (22, 15, 6, 4) across 5 lessons -> (6,4,2,1), (5,4,1,1), (5,3,1,1), (6,4,2,1), (0,0,0,0)
    # =========================================================================
    uid_132 = "unit_b1_132_epistemic_probability_particles_vs_"
    lessons.extend([
        {
            "lessonId": "les_b1_132_01_epistemic_particles_morphosyntax_intro",
            "unitId": uid_132, "cefrLevel": "B1", "sequenceWithinUnit": 1,
            "title": "Evidential Inference vs Pure Chance: Particles Бололтой vs Магадгүй",
            "lessonType": "grammar_introduction",
            "primaryPurpose": "Introduce epistemic probability markers distinguishing: 1) Sensory evidential inference based on visible/tangible evidence (бололтой / шинжтэй 'it appears that, seemingly'), and 2) Abstract hypothetical possibility (магадгүй / байж мэднэ 'perhaps, possibly, maybe').",
            "communicativeOutcome": "Express carefully calibrated speculation differentiating what is inferred from visual signs versus what is hypothetical.",
            "objectivesIntroduced": ["obj_b1_132_01_differentiate_epistemic_modals"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_b1_131_01_form_abnutative_converb"],
            "grammarIntroduced": ["gram_b1_epistemic_probability_bololtoi_magadgui"],
            "grammarPracticed": [], "grammarReviewed": ["gram_b1_converb_modal_manner_n", "gram_b1_converb_abnutative_lgui"],
            "phonologyIntroduced": ["phono_b1_speculative_rising_terminal_tone"],
            "phonologyPracticed": [], "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": ["comm_b1_08_speculating_visual_evidence"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 4, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_opinion_argumentation_rhetoric"],
            "previousVocabularyReused": ["магадгүй", "болох", "харагдах", "шинж", "магадлал"],
            "readingObjective": "", "listeningObjective": "",
            "writingObjective": "Compose 6 sentences distinguishing visual evidence deductions (бололтой) from statistical probabilities (магадгүй).",
            "spokenProductionObjective": "Speculate on why the streets are empty this morning using evidential particles.",
            "registerTarget": "Standard conversational and analytical speculative register",
            "pragmaticTarget": "Restricting бололтой to observed perceptual evidence to maintain epistemic truthfulness.",
            "prerequisiteLessonIds": ["les_b1_131_04_critical_post_mortem_debrief_spoken"],
            "reviewsLessonIds": ["les_b1_124_01_opinion_epistemic_stance_lexicon"],
            "reviewsUnitIds": ["unit_b1_124_formulating_nuanced_personal_stance"],
            "reviewReason": "Deepens stance calibration with grammatical epistemic particles.",
            "audioSuitability": "standard_speech_synthesis_acceptable",
            "audioPurpose": "Model subtle rising terminal tone indicating uncertainty and evidential deduction.",
            "successCriteria": [
                "Applies 'бололтой' after participial stems (-сан бололтой, -х бололтой) to denote sensory evidence",
                "Uses 'магадгүй' as a sentence-initial or medial adverbial of theoretical likelihood"
            ],
            "masteryEvidence": "Produces 'Гадаа бороо орсон бололтой, зам нойтон байна' vs 'Маргааш цас орж магадгүй' correctly.",
            "recommendedExerciseModalities": ["particle_selection", "contextual_deduction", "sentence_completion"]
        },
        {
            "lessonId": "les_b1_132_02_visual_clues_speculation_lexicon",
            "unitId": uid_132, "cefrLevel": "B1", "sequenceWithinUnit": 2,
            "title": "Evidential Clues Lexicon: Perceptual Traces, Symptoms & Forensics",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Acquire sensory vocabulary describing visual traces, atmospheric indicators, forensic clues, and diagnostic signs (ул мөр, шинж тэмдэг, байдал, төлөв, хандлага).",
            "communicativeOutcome": "Formulate detailed deductions from physical signs in everyday, scientific, and forensic contexts.",
            "objectivesIntroduced": ["obj_b1_132_02_evidential_clues_lexicon"],
            "objectivesPracticed": ["obj_b1_132_01_differentiate_epistemic_modals"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_epistemic_probability_bololtoi_magadgui"],
            "grammarReviewed": ["gram_b1_converb_modal_manner_n"],
            "phonologyIntroduced": [], "phonologyPracticed": [], "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_08_speculating_visual_evidence"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 4, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_opinion_argumentation_rhetoric", "lex_b1_environment_geography_climate"],
            "previousVocabularyReused": ["шинж", "мөр", "байдал", "үзэгдэх", "илрэх"],
            "readingObjective": "", "listeningObjective": "",
            "writingObjective": "Draft 4 diagnostic statements interpreting physical signs of wear on an engine or weather symptoms.",
            "spokenProductionObjective": "Explain what physical tracks in the snow tell about an animal's movements.",
            "registerTarget": "Analytical observation and forensic inquiry register",
            "pragmaticTarget": "Substantiating every speculative claim with a concrete perceptual observation.",
            "prerequisiteLessonIds": ["les_b1_132_01_epistemic_particles_morphosyntax_intro"],
            "reviewsLessonIds": ["les_b1_132_01_epistemic_particles_morphosyntax_intro"],
            "reviewsUnitIds": ["unit_b1_132_epistemic_probability_particles_vs_"],
            "reviewReason": "Supplies perceptual evidence vocabulary to substantiate epistemic probability markers.",
            "audioSuitability": "standard_speech_synthesis_acceptable",
            "audioPurpose": "Pronounce scientific and observational terminology in Mongolian.",
            "successCriteria": [
                "Pairs physical clue nouns with evidential predicates (ул мөрөөс харахад ... бололтой)",
                "Distinguishes between conclusive proof and suggestive evidence"
            ],
            "masteryEvidence": "Produces 'Хөлийн мөрнөөс харахад энд чоно өнгөрсөн бололтой байна' flawlessly.",
            "recommendedExerciseModalities": ["clue_deduction_matching", "forensic_description", "sentence_expansion"]
        },
        {
            "lessonId": "les_b1_132_03_weather_forecasting_meteorology_reading",
            "unitId": uid_132, "cefrLevel": "B1", "sequenceWithinUnit": 3,
            "title": "Reading Analysis: Meteorological Bulletins & Weather Anomaly Forecasts",
            "lessonType": "reading_development",
            "primaryPurpose": "Deconstruct authentic seasonal weather outlooks from the National Agency for Meteorology and Environmental Monitoring (ЦАГИЙН МЭНД), evaluating probability percentages and cyclone tracks.",
            "communicativeOutcome": "Extract probabilistic climate forecasts, storm risk levels, and seasonal precipitation predictions from official meteorological bulletins.",
            "objectivesIntroduced": ["obj_b1_132_03_read_weather_forecasts"],
            "objectivesPracticed": ["obj_b1_132_01_differentiate_epistemic_modals"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_epistemic_probability_bololtoi_magadgui"],
            "grammarReviewed": ["gram_b1_converb_abnutative_lgui"],
            "phonologyIntroduced": [], "phonologyPracticed": [], "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_08_speculating_visual_evidence"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_opinion_argumentation_rhetoric", "lex_b1_environment_geography_climate"],
            "previousVocabularyReused": ["цаг агаар", "шуурга", "хүйтрэх", "температур", "салхи"],
            "readingObjective": "Read a 250-word meteorological seasonal bulletin and extract the risk probabilities for early autumn frost across 4 central aimags.",
            "listeningObjective": "", "writingObjective": "", "spokenProductionObjective": "",
            "registerTarget": "Scientific meteorological broadcast register",
            "pragmaticTarget": "Interpreting probability hedging formulas in public safety forecasting.",
            "prerequisiteLessonIds": ["les_b1_132_01_epistemic_particles_morphosyntax_intro"],
            "reviewsLessonIds": ["les_b1_126_03_socio_economic_causality_reading"],
            "reviewsUnitIds": ["unit_b1_126_causal_conjunctions_connectors_"],
            "reviewReason": "Expands technical reading into environmental and probabilistic meteorological domains.",
            "audioSuitability": "standard_speech_synthesis_acceptable",
            "audioPurpose": "Narration of meteorological forecast with official broadcast cadence.",
            "successCriteria": [
                "Identifies probability markers indicating storm likelihood",
                "Extracts specific temperature anomalies and snowfall projections from meteorological text"
            ],
            "masteryEvidence": "Identifies that blizzards are probable in the northern provinces while eastern areas remain dry.",
            "recommendedExerciseModalities": ["forecast_data_extraction", "risk_mapping", "multiple_choice"]
        },
        {
            "lessonId": "les_b1_132_04_forensic_case_deduction_dialogue",
            "unitId": uid_132, "cefrLevel": "B1", "sequenceWithinUnit": 4,
            "title": "Interactive Dialogue: Deductive Mystery Solving from Physical Evidence",
            "lessonType": "dialogue_work",
            "primaryPurpose": "Engage in an interactive deductive mystery dialogue with an investigative partner reconstructing what transpired at a deserted campsite or disrupted office based on physical clues.",
            "communicativeOutcome": "Formulate speculative hypotheses, counter with alternative visual interpretations, and synthesize a coherent theory of events.",
            "objectivesIntroduced": ["obj_b1_132_04_solve_mystery_from_clues"],
            "objectivesPracticed": [
                "obj_b1_132_01_differentiate_epistemic_modals",
                "obj_b1_132_02_visual_clues_speculation_lexicon"
            ],
            "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_epistemic_probability_bololtoi_magadgui"],
            "grammarReviewed": ["gram_b1_converb_modal_manner_n"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_b1_speculative_rising_terminal_tone"],
            "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_08_speculating_visual_evidence"],
            "communicativeFunctionsReviewed": ["comm_b1_03_expressing_opinions_agreements"],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 4, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_opinion_argumentation_rhetoric"],
            "previousVocabularyReused": ["сэжиглэх", "баримт", "нууц", "тайлбарлах", "магадлал"],
            "readingObjective": "", "listeningObjective": "",
            "writingObjective": "",
            "spokenProductionObjective": "Conduct an 8-turn deductive exchange debating what happened to an abandoned vehicle based on tire marks and scattered luggage.",
            "registerTarget": "Investigative collaborative speculative register",
            "pragmaticTarget": "Testing hypotheses cooperatively through calibrated epistemic hedging.",
            "prerequisiteLessonIds": ["les_b1_132_02_visual_clues_speculation_lexicon", "les_b1_132_03_weather_forecasting_meteorology_reading"],
            "reviewsLessonIds": ["les_b1_125_03_structured_oxford_debate_simulation"],
            "reviewsUnitIds": ["unit_b1_125_respectful_disagreement_constructiv"],
            "reviewReason": "Applies polite debate rebuttal strategies to investigative deductive hypotheses.",
            "audioSuitability": "mongolian_voice_required",
            "audioPurpose": "Authentic dialogue between two inquisitive investigators examining clues.",
            "successCriteria": [
                "Sustains multi-turn dialogue formulating deductions with бололтой and магадгүй",
                "Counters rival hypotheses citing specific visible anomalies"
            ],
            "masteryEvidence": "Negotiates 'Эндээс харахад тэд яарч явсан бололтой, учир нь чухал бичиг баримтаа мартаад орхичихсон байна' fluently.",
            "recommendedExerciseModalities": ["branching_investigation", "clue_debate_simulation", "spoken_deduction"]
        },
        {
            "lessonId": "les_b1_132_05_investigative_forensic_report_writing",
            "unitId": uid_132, "cefrLevel": "B1", "sequenceWithinUnit": 5,
            "title": "Writing Workshop: Authoring a 150-Word Investigative Inference Report",
            "lessonType": "writing",
            "primaryPurpose": "Synthesize observed physical clues into a formal 150-word written investigative assessment outlining findings, inferred timeline, probable causality, and remaining uncertainties.",
            "communicativeOutcome": "Produce an authoritative written speculative briefing that carefully distinguishes observed facts from probabilistic inferences.",
            "objectivesIntroduced": ["obj_b1_132_05_write_investigative_report"],
            "objectivesPracticed": [
                "obj_b1_132_01_differentiate_epistemic_modals",
                "obj_b1_132_02_evidential_clues_lexicon"
            ],
            "objectivesReviewed": ["obj_b1_131_04_deliver_post_mortem_debrief"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_epistemic_probability_bololtoi_magadgui"],
            "grammarReviewed": ["gram_b1_converb_abnutative_lgui"],
            "phonologyIntroduced": [], "phonologyPracticed": [], "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_08_speculating_visual_evidence"],
            "communicativeFunctionsReviewed": ["comm_b1_05_making_causal_arguments"],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_b1_opinion_argumentation_rhetoric"],
            "previousVocabularyReused": ["дүгнэлт", "нотолгоо", "шалтгаан", "магадлал", "илрэх"],
            "readingObjective": "", "listeningObjective": "",
            "writingObjective": "Author a 150-word investigative report detailing 3 observable clues and 2 probable conclusions regarding an equipment breakdown.",
            "spokenProductionObjective": "",
            "registerTarget": "Formal administrative investigative report register",
            "pragmaticTarget": "Maintaining rigorous epistemic modesty to prevent premature legal conclusions.",
            "prerequisiteLessonIds": ["les_b1_132_03_weather_forecasting_meteorology_reading", "les_b1_132_04_forensic_case_deduction_dialogue"],
            "reviewsLessonIds": ["les_b1_125_04_formal_rebuttal_letter_writing"],
            "reviewsUnitIds": ["unit_b1_125_respectful_disagreement_constructiv"],
            "reviewReason": "Synthesizes formal evidentiary writing with epistemic probability calibration.",
            "audioSuitability": "standard_speech_synthesis_acceptable",
            "audioPurpose": "Provide audio playback of the finalized investigative report.",
            "successCriteria": [
                "Accurately separates Section 1: Facts from Section 2: Evidential Inferences",
                "Integrates бололтой and магадгүй with strict adherence to evidence-based constraints"
            ],
            "masteryEvidence": "Submits a report stating 'Хөдөлгүүрийн дулаан хэт өссөн бололтой бөгөөд тос гоожсоноос шалтгаалсан байж магадгүй юм' without error.",
            "recommendedExerciseModalities": ["guided_report_writing", "fact_inference_sorting", "peer_critique"]
        }
    ])

    return lessons
