"""
Authoritative Pedagogical Specification for B1 Section 03: Part 2 (Units 138 - 140)
Units 138 (5 lessons), 139 (4 lessons), 140 (4 lessons) -> 13 lessons
"""

from typing import List, Dict, Any

def get_sec03_part2_lessons() -> List[Dict[str, Any]]:
    lessons = []

    # =========================================================================
    # UNIT 138: Subordinate Subject Genitive Case Marking
    # Budget: (22, 15, 6, 4) across 5 lessons -> (6,4,2,1), (5,4,1,1), (5,3,1,1), (6,4,2,1), (0,0,0,0)
    # =========================================================================
    uid_138 = "unit_b1_138_subordinate_subject_genitive_case_m"
    lessons.extend([
        {
            "lessonId": "les_b1_138_01_subordinate_subject_genitive_syntax_intro",
            "unitId": uid_138, "cefrLevel": "B1", "sequenceWithinUnit": 1,
            "title": "Subordinate Subject Marking: The Genitive Case in Embedded Clauses",
            "lessonType": "grammar_introduction",
            "primaryPurpose": "Introduce the mandatory syntactic rule of Mongolian complex clauses: when an embedded participial clause has a subject distinct from the matrix clause subject, that embedded subject must be marked in the Genitive case (Миний бичсэн захидал, Багшийн тайлбарласан дүрэм, Чиний ирэхийг би мэдсэнгүй).",
            "communicativeOutcome": "Construct grammatically sound complex relative clauses and embedded complement clauses with non-identical subjects.",
            "objectivesIntroduced": ["obj_b1_138_01_mark_subordinate_subject_genitive"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_b1_137_01_decline_nominalized_participles"],
            "grammarIntroduced": ["gram_b1_subordinate_subject_marking_genitive"],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_genitive_possession", "gram_b1_nominalization_participles_cases"],
            "phonologyIntroduced": ["phono_b1_genitive_subject_clitic_reduction"],
            "phonologyPracticed": [], "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": ["comm_b1_06_stating_purpose_long_term_goals"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 4, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_education_career_workplace", "lex_b1_opinion_argumentation_rhetoric"],
            "previousVocabularyReused": ["багш", "сурагч", "хэлэх", "хийх", "бичих", "ойлгох"],
            "readingObjective": "", "listeningObjective": "",
            "writingObjective": "Convert 8 pairs of simple independent sentences into complex subordinate clauses requiring Genitive case marking on the embedded subject.",
            "spokenProductionObjective": "Explain an action that a colleague took that influenced your personal project timeline.",
            "registerTarget": "Standard formal written and conversational syntactic register",
            "pragmaticTarget": "Eliminating nominative interference in subordinate clauses to sound natural and native-like.",
            "prerequisiteLessonIds": ["les_b1_137_05_advocating_conservation_goals_spoken"],
            "reviewsLessonIds": ["les_b1_137_01_participle_oblique_nominalization_intro"],
            "reviewsUnitIds": ["unit_b1_137_nominalization_of_participles_in_ob"],
            "reviewReason": "Complements participial case declension by establishing proper subject case marking inside embedded clauses.",
            "audioSuitability": "standard_speech_synthesis_acceptable",
            "audioPurpose": "Model subtle prosodic reduction of genitive subject clitics in spoken subordinate clauses.",
            "successCriteria": [
                "Marks embedded subjects with genitive suffixes (-ын/-ийн/-ний/-ны) whenever they differ from matrix subject",
                "Applies genitive pronouns (миний, чиний, түүний, манай, танай, тэдний) correctly in relative clauses"
            ],
            "masteryEvidence": "Produces 'Багшийн заасан хичээл маш сонирхолтой байв' and 'Чиний хийсэн ажлыг захирал сайшаав' without error.",
            "recommendedExerciseModalities": ["sentence_combining", "genitive_subject_insertion", "error_correction"]
        },
        {
            "lessonId": "les_b1_138_02_subject_switch_contrastive_guided_practice",
            "unitId": uid_138, "cefrLevel": "B1", "sequenceWithinUnit": 2,
            "title": "Guided Practice: Subject Coreference vs Subject Disjointness in Subordination",
            "lessonType": "grammar_guided_practice",
            "primaryPurpose": "Master the structural contrast between: 1) Same-subject clauses utilizing converbs or reflexive-possessive marking (-аад, -нгаа, -хаараа), and 2) Different-subject clauses demanding Genitive subject marking + non-reflexive participial complementation.",
            "communicativeOutcome": "Seamlessly switch between coreferential and disjoint-subject sentence patterns without syntactic confusion.",
            "objectivesIntroduced": ["obj_b1_138_02_master_subject_disjointness"],
            "objectivesPracticed": ["obj_b1_138_01_mark_subordinate_subject_genitive"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_subordinate_subject_marking_genitive"],
            "grammarReviewed": ["gram_a1_case_nominative_unmarked", "gram_b1_converb_limiting_ngaa"],
            "phonologyIntroduced": [], "phonologyPracticed": [], "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_06_stating_purpose_long_term_goals"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 4, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_education_career_workplace"],
            "previousVocabularyReused": ["өөрийн", "бусдын", "туслах", "хүлээх", "дуусгах"],
            "readingObjective": "", "listeningObjective": "",
            "writingObjective": "Differentiate 8 sentences by marking subject coreference (reflexive) vs subject switch (genitive noun + agreement).",
            "spokenProductionObjective": "Contribute 3 rapid spoken responses contrasting what you did versus what someone else's actions caused.",
            "registerTarget": "Syntactic precision training register",
            "pragmaticTarget": "Avoiding ambiguous actor attribution in complex collaborative workflow descriptions.",
            "prerequisiteLessonIds": ["les_b1_138_01_subordinate_subject_genitive_syntax_intro"],
            "reviewsLessonIds": ["les_b1_138_01_subordinate_subject_genitive_syntax_intro"],
            "reviewsUnitIds": ["unit_b1_138_subordinate_subject_genitive_case_m"],
            "reviewReason": "Intensive structural drill solidifying subject switch mechanics.",
            "audioSuitability": "standard_speech_synthesis_acceptable",
            "audioPurpose": "Synthesize sentences contrasting coreferential vs disjoint subject intonation patterns.",
            "successCriteria": [
                "Applies reflexive-possessive (-аа⁴) exclusively when the subject is identical to the matrix subject",
                "Applies genitive marking exclusively when the embedded subject is distinct from matrix subject"
            ],
            "masteryEvidence": "Contrasts 'Би өөрийн хийсэн ажлыг шалгав' with 'Би түүний хийсэн ажлыг шалгав' with 100% accuracy.",
            "recommendedExerciseModalities": ["reflexive_vs_genitive_sorting", "syntax_transformation", "cloze_drill"]
        },
        {
            "lessonId": "les_b1_138_03_biographical_memoir_reading",
            "unitId": uid_138, "cefrLevel": "B1", "sequenceWithinUnit": 3,
            "title": "Reading Analysis: Mentorship Chronicles & Influential Historical Figures",
            "lessonType": "reading_development",
            "primaryPurpose": "Deconstruct authentic excerpts from Mongolian autobiographies chronicling the pivotal impact of teachers, elders, and mentors (Багшийн минь захисан үг, Эцгийн минь сургасан ухаан).",
            "communicativeOutcome": "Comprehend multi-clause biographical literature rich in complex relative clauses with genitive subjects.",
            "objectivesIntroduced": ["obj_b1_138_03_read_mentorship_memoirs"],
            "objectivesPracticed": ["obj_b1_138_01_mark_subordinate_subject_genitive"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_subordinate_subject_marking_genitive"],
            "grammarReviewed": ["gram_a2_converb_purposive_khaar"],
            "phonologyIntroduced": [], "phonologyPracticed": [], "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_06_stating_purpose_long_term_goals"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_education_career_workplace", "lex_b1_culture_traditions_heritage"],
            "previousVocabularyReused": ["багш", "сургааль", "өвөг дээдэс", "захиас", "амьдралын зам"],
            "readingObjective": "Read a 300-word memoir passage by an academician and trace 3 core lessons their mentors imparted through genitive-marked relative clauses.",
            "listeningObjective": "", "writingObjective": "", "spokenProductionObjective": "",
            "registerTarget": "High literary biographical memoir register",
            "pragmaticTarget": "Interpreting cultural respect (ахмадаа хүндэтгэх) encoded through formal syntactic deference.",
            "prerequisiteLessonIds": ["les_b1_138_01_subordinate_subject_genitive_syntax_intro"],
            "reviewsLessonIds": ["les_b1_128_03_biographical_narrative_reading"],
            "reviewsUnitIds": ["unit_b1_128_durative_converb_suffixes_"],
            "reviewReason": "Expands biographical reading by incorporating advanced disjoint-subject relative clauses.",
            "audioSuitability": "standard_speech_synthesis_acceptable",
            "audioPurpose": "Narration of mentorship memoir excerpt.",
            "successCriteria": [
                "Identifies genitive-marked subjects within complex nested relative clauses",
                "Extracts specific life advice and moral teachings credited to elders"
            ],
            "masteryEvidence": "Identifies that 'Өвөөгийн минь хэлж сургасан үгс одоо ч миний амьдралын луужин болдог' attributes core values to grandfather's counsel.",
            "recommendedExerciseModalities": ["relative_clause_mapping", "mentorship_extraction", "multiple_choice"]
        },
        {
            "lessonId": "les_b1_138_04_collaborative_workflow_listening",
            "unitId": uid_138, "cefrLevel": "B1", "sequenceWithinUnit": 4,
            "title": "Acoustic Comprehension: Team Handoffs & Inter-Departmental Dependencies",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop listening comprehension for workplace standup meetings where engineers and project leads report what their colleagues delivered and what dependencies remain.",
            "communicativeOutcome": "Understand rapid spoken accounts of multi-person tasks where outcomes depend upon another person's prior actions.",
            "objectivesIntroduced": ["obj_b1_138_04_comprehend_team_dependencies"],
            "objectivesPracticed": ["obj_b1_138_01_mark_subordinate_subject_genitive"],
            "objectivesReviewed": ["obj_b1_130_04_coordinate_concurrent_tasks"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_subordinate_subject_marking_genitive"],
            "grammarReviewed": ["gram_b1_verb_derivation_denominal_lakh"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_b1_genitive_subject_clitic_reduction"],
            "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_06_stating_purpose_long_term_goals"],
            "communicativeFunctionsReviewed": ["comm_b1_18_delegating_tasks_causative"],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 4, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_education_career_workplace"],
            "previousVocabularyReused": ["баг", "гүйцэтгэл", "хүлээлгэн өгөх", "шалгах", "хамаарах"],
            "readingObjective": "",
            "listeningObjective": "Listen to a 2.5-minute agile team scrum audio and map out 3 workflow dependencies between designers, developers, and testers.",
            "writingObjective": "", "spokenProductionObjective": "",
            "registerTarget": "Modern tech-workplace collaborative register",
            "pragmaticTarget": "Tracking disjoint-subject attribution in fast-moving workplace task updates.",
            "prerequisiteLessonIds": ["les_b1_138_02_subject_switch_contrastive_guided_practice", "les_b1_138_03_biographical_memoir_reading"],
            "reviewsLessonIds": ["les_b1_130_04_workplace_multitasking_dialogue"],
            "reviewsUnitIds": ["unit_b1_130_limiting_incidental_converb_suffixe"],
            "reviewReason": "Expands workplace multitasking dialogue into complex multi-actor dependency listening.",
            "audioSuitability": "mongolian_voice_required",
            "audioPurpose": "Authentic audio of three software professionals giving scrum updates with natural conversational pacing.",
            "successCriteria": [
                "Identifies who is responsible for each completed component based on genitive subject markers",
                "Maps dependencies where Team Member B cannot begin until Team Member A submits deliverables"
            ],
            "masteryEvidence": "Correctly transcribes that the frontend developer is waiting for the designer's updated wireframes.",
            "recommendedExerciseModalities": ["dependency_flowchart_audio", "actor_action_matching", "summary_completion"]
        },
        {
            "lessonId": "les_b1_138_05_mentorship_tribute_spoken",
            "unitId": uid_138, "cefrLevel": "B1", "sequenceWithinUnit": 5,
            "title": "Spoken Production: Delivering a Tribute Speech Honoring a Mentor's Guidance",
            "lessonType": "spoken_production",
            "primaryPurpose": "Deliver an articulate 2-minute tribute speech honoring a teacher, supervisor, or parent, detailing specific wisdom and principles they instilled using complex relative clauses with genitive subjects.",
            "communicativeOutcome": "Deliver a moving, culturally resonant ceremonial tribute in formal spoken Mongolian.",
            "objectivesIntroduced": ["obj_b1_138_05_deliver_mentor_tribute"],
            "objectivesPracticed": [
                "obj_b1_138_01_mark_subordinate_subject_genitive",
                "obj_b1_138_02_master_subject_disjointness"
            ],
            "objectivesReviewed": ["obj_b1_137_05_deliver_advocacy_address"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_subordinate_subject_marking_genitive"],
            "grammarReviewed": ["gram_a1_verb_volitional_intention_ya"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_b1_genitive_subject_clitic_reduction"],
            "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_06_stating_purpose_long_term_goals"],
            "communicativeFunctionsReviewed": ["comm_b1_01_narrating_personal_anecdotes"],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_b1_education_career_workplace", "lex_b1_culture_traditions_heritage"],
            "previousVocabularyReused": ["багш", "хүндэтгэл", "ач гавьяа", "ухаарал", "баярлалаа"],
            "readingObjective": "", "listeningObjective": "", "writingObjective": "",
            "spokenProductionObjective": "Deliver a 2-minute tribute speech honoring a mentor using at least 4 genitive-subject subordinate clauses.",
            "registerTarget": "High ceremonial tribute and formal celebratory register",
            "pragmaticTarget": "Expressing deep gratitude (ач санах) through elevated syntax and warm affective tone.",
            "prerequisiteLessonIds": ["les_b1_138_03_biographical_memoir_reading", "les_b1_138_04_collaborative_workflow_listening"],
            "reviewsLessonIds": ["les_b1_128_04_personal_transformation_anecdote_spoken"],
            "reviewsUnitIds": ["unit_b1_128_durative_converb_suffixes_"],
            "reviewReason": "Synthesizes personal storytelling and grammatical subordination into formal ceremonial oratory.",
            "audioSuitability": "mongolian_voice_required",
            "audioPurpose": "Benchmark audio recording of an elegant tribute speech delivered at an academic jubilee.",
            "successCriteria": [
                "Delivers a 2-minute speech with correct genitive marking on all third-person embedded subjects",
                "Integrates cultural expressions of gratitude with dignified oratorical cadence"
            ],
            "masteryEvidence": "Delivers 'Багшийн маань надад заасан зарчимч чанар өнөөдөр миний ажлын амжилтын үндэс болж байна' with moving eloquence.",
            "recommendedExerciseModalities": ["timed_tribute_monologue", "peer_critique", "ceremonial_speech_rubric"]
        }
    ])

    # =========================================================================
    # UNIT 139: Purposive Clauses: Conjunctions Тулд and Төлөө
    # Budget: (22, 15, 6, 4) across 4 lessons -> (6,4,2,1), (6,4,2,1), (5,4,1,1), (5,3,1,1)
    # =========================================================================
    uid_139 = "unit_b1_139_purposive_clauses_conjunctions_and_"
    lessons.extend([
        {
            "lessonId": "les_b1_139_01_purposive_postpositions_morphosyntax_intro",
            "unitId": uid_139, "cefrLevel": "B1", "sequenceWithinUnit": 1,
            "title": "Morphosyntax of Purpose: Postpositions Тулд (In Order To) vs Төлөө (For the Sake Of)",
            "lessonType": "grammar_introduction",
            "primaryPurpose": "Introduce formal purposive postpositional syntax: 1) Future participle in -х + тулд (action-oriented teleological purpose: амжилтад хүрэхийн тулд, ойлгохын тулд), and 2) Genitive noun/pronoun + төлөө (altruistic, beneficiary-oriented dedication: эх орныхоо төлөө, гэр бүлийнхээ төлөө).",
            "communicativeOutcome": "Formulate complex goal-oriented sentences clearly distinguishing pragmatic instrumentality (-хын тулд) from moral/beneficiary commitment (-ын төлөө).",
            "objectivesIntroduced": ["obj_b1_139_01_form_purposive_clauses"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_b1_138_01_mark_subordinate_subject_genitive"],
            "grammarIntroduced": ["gram_b1_clause_purposive_tuld_tuloo"],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_verb_dictionary_infinitive_kh", "gram_b1_subordinate_subject_marking_genitive"],
            "phonologyIntroduced": ["phono_b1_purposive_postposition_stress"],
            "phonologyPracticed": [], "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": ["comm_b1_06_stating_purpose_long_term_goals"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 4, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_education_career_workplace", "lex_b1_opinion_argumentation_rhetoric"],
            "previousVocabularyReused": ["зорилго", "төлөө", "тулд", "хийх", "амжилт", "ирээдүй"],
            "readingObjective": "", "listeningObjective": "",
            "writingObjective": "Draft 6 sentences distinguishing between technical operational objectives (-хын тулд) and ideological causes (-ын төлөө).",
            "spokenProductionObjective": "Explain why you are studying Mongolian and who or what inspires your dedication.",
            "registerTarget": "Formal rhetorical, academic, and aspirational register",
            "pragmaticTarget": "Distinguishing pragmatic instrumental goals from altruistic and moral life causes.",
            "prerequisiteLessonIds": ["les_b1_138_05_mentorship_tribute_spoken"],
            "reviewsLessonIds": ["les_b1_126_01_causal_connectors_morphosyntax_intro"],
            "reviewsUnitIds": ["unit_b1_126_causal_conjunctions_connectors_"],
            "reviewReason": "Pairs backward-looking causal explanations (тул/учраас) with forward-looking purposive drivers (тулд/төлөө).",
            "audioSuitability": "standard_speech_synthesis_acceptable",
            "audioPurpose": "Model proper stress and pauses separating the purposive clause from matrix action.",
            "successCriteria": [
                "Combines future participle -х with genitive -ын before тулд (-хын тулд)",
                "Uses -ын төлөө with nouns/pronouns denoting the beneficiary or noble cause"
            ],
            "masteryEvidence": "Produces 'Монгол хэлийг сайн сурахын тулд өдөр бүр хичээллэж байна' and 'Эх орныхоо хөгжлийн төлөө зүтгэнэ' accurately.",
            "recommendedExerciseModalities": ["postposition_selection", "clause_combining", "sentence_completion"]
        },
        {
            "lessonId": "les_b1_139_02_strategic_mission_vision_lexicon",
            "unitId": uid_139, "cefrLevel": "B1", "sequenceWithinUnit": 2,
            "title": "Strategic Mission & Vision Lexicon: Institutional Mandates & Long-Term Objectives",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Acquire formal organizational vocabulary for mission statements, strategic visions, socio-economic goals, and civic aspirations (эрхэм зорилго, алсын хараа, зорилт, тууштай тэмцэх, хувь нэмэр оруулах).",
            "communicativeOutcome": "Articulate organizational missions, corporate social responsibility pledges, and personal career visions in elevated Mongolian.",
            "objectivesIntroduced": ["obj_b1_139_02_strategic_mission_lexicon"],
            "objectivesPracticed": ["obj_b1_139_01_form_purposive_clauses"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_clause_purposive_tuld_tuloo"],
            "grammarReviewed": ["gram_b1_converb_abnutative_lgui"],
            "phonologyIntroduced": [], "phonologyPracticed": [], "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_06_stating_purpose_long_term_goals"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 4, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_education_career_workplace", "lex_b1_opinion_argumentation_rhetoric"],
            "previousVocabularyReused": ["байгууллага", "зорилго", "төлөвлөгөө", "хөгжил", "үнэ цэнэ"],
            "readingObjective": "", "listeningObjective": "",
            "writingObjective": "Author a 4-sentence institutional mission statement for a sustainable energy startup using purposive constructions.",
            "spokenProductionObjective": "Explain your personal 5-year career vision at a graduate school admissions interview.",
            "registerTarget": "High corporate strategic planning and NGO advocacy register",
            "pragmaticTarget": "Projecting high-level vision and purposeful institutional leadership.",
            "prerequisiteLessonIds": ["les_b1_139_01_purposive_postpositions_morphosyntax_intro"],
            "reviewsLessonIds": ["les_b1_139_01_purposive_postpositions_morphosyntax_intro"],
            "reviewsUnitIds": ["unit_b1_139_purposive_clauses_conjunctions_and_"],
            "reviewReason": "Supplies elevated strategic vocabulary to embed within purposive grammatical clauses.",
            "audioSuitability": "standard_speech_synthesis_acceptable",
            "audioPurpose": "Pronounce formal organizational and aspirational collocations.",
            "successCriteria": [
                "Pairs strategic mission nouns with purposive postpositions correctly",
                "Forms inspiring, coherent mission and vision statements"
            ],
            "masteryEvidence": "Produces 'Манай компани байгаль орчныг хамгаалахын тулд сэргээгдэх эрчим хүчийг түгээх эрхэм зорилготой' fluently.",
            "recommendedExerciseModalities": ["vision_statement_assembly", "collocation_drill", "contextual_cloze"]
        },
        {
            "lessonId": "les_b1_139_03_ngo_charter_mission_reading",
            "unitId": uid_139, "cefrLevel": "B1", "sequenceWithinUnit": 3,
            "title": "Reading Analysis: NGO Charters & Community Development Grant Proposals",
            "lessonType": "reading_development",
            "primaryPurpose": "Deconstruct authentic charters of prominent Mongolian non-governmental organizations (e.g., child welfare, environmental preservation, rural education) and international donor project goals.",
            "communicativeOutcome": "Extract target beneficiary groups, project deliverables, and strategic aims from institutional charters and grant proposals.",
            "objectivesIntroduced": ["obj_b1_139_03_read_ngo_charters"],
            "objectivesPracticed": ["obj_b1_139_01_form_purposive_clauses"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_clause_purposive_tuld_tuloo"],
            "grammarReviewed": ["gram_a2_reported_speech_gej_kheleh"],
            "phonologyIntroduced": [], "phonologyPracticed": [], "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_06_stating_purpose_long_term_goals"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 4, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_education_career_workplace", "lex_b1_opinion_argumentation_rhetoric"],
            "previousVocabularyReused": ["төрийн бус байгууллага", "төсөл", "дэмжлэг", "нийгэм", "хэрэгжүүлэх"],
            "readingObjective": "Read a 300-word NGO charter for rural girl education and list 2 overarching goals (-ын төлөө) and 3 specific intervention mechanisms (-ын тулд).",
            "listeningObjective": "", "writingObjective": "", "spokenProductionObjective": "",
            "registerTarget": "Formal non-profit and developmental funding register",
            "pragmaticTarget": "Identifying measurable project outputs vs aspirational social missions.",
            "prerequisiteLessonIds": ["les_b1_139_01_purposive_postpositions_morphosyntax_intro"],
            "reviewsLessonIds": ["les_b1_137_03_environmental_legislation_reading"],
            "reviewsUnitIds": ["unit_b1_137_nominalization_of_participles_in_ob"],
            "reviewReason": "Expands formal reading from legal statutory prohibitions to developmental purposive mandates.",
            "audioSuitability": "standard_speech_synthesis_acceptable",
            "audioPurpose": "Narration of non-profit organizational charter.",
            "successCriteria": [
                "Accurately separates overarching moral missions from specific technical intervention targets",
                "Identifies purposive clauses marking donor funding conditions"
            ],
            "masteryEvidence": "Identifies that the grant funds mobile libraries in order to improve literacy in remote aimags.",
            "recommendedExerciseModalities": ["grant_goal_matrix", "purpose_mechanism_sorting", "multiple_choice"]
        },
        {
            "lessonId": "les_b1_139_04_grant_proposal_pitch_spoken",
            "unitId": uid_139, "cefrLevel": "B1", "sequenceWithinUnit": 4,
            "title": "Spoken Production: Delivering an Elevator Pitch for a Social Impact Project",
            "lessonType": "spoken_production",
            "primaryPurpose": "Deliver a 2-minute elevator pitch to a panel of philanthropic donors requesting support for a community initiative, passionately detailing who the initiative serves (-ын төлөө) and what specific activities will be funded (-ын тулд).",
            "communicativeOutcome": "Persuade stakeholders and secure buy-in for a social or environmental venture through compelling purposive rhetoric.",
            "objectivesIntroduced": ["obj_b1_139_04_pitch_social_impact_project"],
            "objectivesPracticed": [
                "obj_b1_139_01_form_purposive_clauses",
                "obj_b1_139_02_strategic_mission_vision_lexicon"
            ],
            "objectivesReviewed": ["obj_b1_137_05_deliver_advocacy_address"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_clause_purposive_tuld_tuloo"],
            "grammarReviewed": ["gram_a1_verb_imperative_polite_aarai"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_b1_purposive_postposition_stress"],
            "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_06_stating_purpose_long_term_goals"],
            "communicativeFunctionsReviewed": ["comm_b1_03_expressing_opinions_agreements"],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_education_career_workplace", "lex_b1_opinion_argumentation_rhetoric"],
            "previousVocabularyReused": ["хандив", "дэмжих", "үр нөлөө", "иргэд", "өөрчлөлт"],
            "readingObjective": "", "listeningObjective": "", "writingObjective": "",
            "spokenProductionObjective": "Deliver a 2-minute oral pitch proposing a community greenhouse project to improve winter food security in ger districts.",
            "registerTarget": "Persuasive entrepreneurial and social venture pitch register",
            "pragmaticTarget": "Balancing emotional resonance for the beneficiary with practical operational feasibility.",
            "prerequisiteLessonIds": ["les_b1_139_02_strategic_mission_vision_lexicon", "les_b1_139_03_ngo_charter_mission_reading"],
            "reviewsLessonIds": ["les_b1_137_05_advocating_conservation_goals_spoken"],
            "reviewsUnitIds": ["unit_b1_137_nominalization_of_participles_in_ob"],
            "reviewReason": "Synthesizes environmental advocacy with structured purposive project pitching.",
            "audioSuitability": "mongolian_voice_required",
            "audioPurpose": "Provide benchmark audio recording of a charismatic Mongolian social entrepreneur delivering a pitch.",
            "successCriteria": [
                "Delivers a 2-minute structured pitch utilizing -ын тулд and -ын төлөө at least 2 times each",
                "States clear problem, proposed intervention, beneficiary impact, and specific funding request"
            ],
            "masteryEvidence": "Delivers 'Хүүхдүүдийнхээ эрүүл ирээдүйн төлөө, тэдэнд шинэ ногоо нийлүүлэхийн тулд энэхүү хүлэмжийг байгуулах гэж байна' persuasively.",
            "recommendedExerciseModalities": ["pitch_presentation", "donor_q_and_a_simulation", "peer_critique"]
        }
    ])

    # =========================================================================
    # UNIT 140: Agentive Participle: Nominal Derivation Suffix -гч
    # Budget: (22, 15, 6, 4) across 4 lessons -> (6,4,2,1), (6,4,2,1), (5,4,1,1), (5,3,1,1)
    # =========================================================================
    uid_140 = "unit_b1_140_agentive_participle_nominal_derivat"
    lessons.extend([
        {
            "lessonId": "les_b1_140_01_agentive_participle_morphology_intro",
            "unitId": uid_140, "cefrLevel": "B1", "sequenceWithinUnit": 1,
            "title": "Professional Agents & Doers: The Agentive Participle Suffix -гч",
            "lessonType": "grammar_introduction",
            "primaryPurpose": "Introduce the productive agentive nominalizer -гч (attached directly to verbal stems with connective vowels: -агч/-эгч/-огч/-өгч after consonants) denoting: 1) professional practitioners (судлаач/судлагч, орчуулагч, хөтлөгч, хамгаалагч), 2) transactional roles (худалдан авагч, хэрэглэгч, зээлдэгч), and 3) dynamic participial agents in syntax.",
            "communicativeOutcome": "Formulate professional titles, legal role designations, and actor definitions systematically from action verbs.",
            "objectivesIntroduced": ["obj_b1_140_01_form_agentive_participles"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_b1_139_01_form_purposive_clauses"],
            "grammarIntroduced": ["gram_b1_participle_agentive_gch"],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_sov_word_order", "gram_b1_voice_causative_uul_lga"],
            "phonologyIntroduced": ["phono_b1_agentive_gch_connective_vowels"],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_vowel_harmony_basic"],
            "communicativeFunctionsIntroduced": ["comm_b1_24_discussing_education_career_path"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 4, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_education_career_workplace"],
            "previousVocabularyReused": ["сурах", "заах", "хөтлөх", "хамгаалах", "орчуулах", "авах"],
            "readingObjective": "", "listeningObjective": "",
            "writingObjective": "Derive 10 professional and institutional titles by attaching -гч to verbal roots with correct connective vowels.",
            "spokenProductionObjective": "Explain the role and responsibilities of 3 different professional positions in your industry.",
            "registerTarget": "Standard formal professional and occupational register",
            "pragmaticTarget": "Deriving occupational titles on the fly when describing specialized workflows.",
            "prerequisiteLessonIds": ["les_b1_139_04_grant_proposal_pitch_spoken"],
            "reviewsLessonIds": ["les_b1_112_01_career_qualifications_lexicon"],
            "reviewsUnitIds": ["unit_b1_112_job_searching_cv_preparation_qualif"],
            "reviewReason": "Formalizes the morphological derivation of professional titles introduced lexically in Unit 112.",
            "audioSuitability": "standard_speech_synthesis_acceptable",
            "audioPurpose": "Demonstrate the short connective vowel before -гч (-агч/-эгч/-огч/-өгч) in spoken Mongolian.",
            "successCriteria": [
                "Selects appropriate connective vowel adhering to 4-fold vowel harmony",
                "Distinguishes -гч from other nominalizers (-ч, -чин) in occupational contexts"
            ],
            "masteryEvidence": "Produces 'хөтлөгч', 'орчуулагч', 'судлаач', and 'худалдан авагч' with flawless morphological accuracy.",
            "recommendedExerciseModalities": ["suffix_derivation", "verb_to_occupation_matching", "sentence_completion"]
        },
        {
            "lessonId": "les_b1_140_02_occupational_specializations_lexicon",
            "unitId": uid_140, "cefrLevel": "B1", "sequenceWithinUnit": 2,
            "title": "Occupational Specializations Lexicon: Modern Technologists, Creators & Regulators",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Acquire modern professional and institutional designations formed with -гч across modern technology, healthcare, environmental science, and legal compliance (хөгжүүлэгч, судлаач, хянагч, шинжээч, зохион байгуулагч, нийлүүлэгч).",
            "communicativeOutcome": "Discuss modern 21st-century job titles, career specializations, and departmental functions in Mongolian.",
            "objectivesIntroduced": ["obj_b1_140_02_occupational_specializations_lexicon"],
            "objectivesPracticed": ["obj_b1_140_01_form_agentive_participles"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_participle_agentive_gch"],
            "grammarReviewed": ["gram_b1_nominalization_participles_cases"],
            "phonologyIntroduced": [], "phonologyPracticed": [], "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_24_discussing_education_career_path"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 4, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_education_career_workplace", "lex_b1_media_digital_society"],
            "previousVocabularyReused": ["мэргэжил", "салбар", "хариуцах", "систем", "технологи"],
            "readingObjective": "", "listeningObjective": "",
            "writingObjective": "Draft job descriptions for 3 modern roles (e.g. программ хангамж хөгжүүлэгч, байгаль орчны шинжээч, чанарын хянагч).",
            "spokenProductionObjective": "Explain your daily responsibilities using modern occupational agentive titles.",
            "registerTarget": "Modern high-tech and corporate human resources register",
            "pragmaticTarget": "Navigating modern digital and professional labor market terminology in Mongolian.",
            "prerequisiteLessonIds": ["les_b1_140_01_agentive_participle_morphology_intro"],
            "reviewsLessonIds": ["les_b1_140_01_agentive_participle_morphology_intro"],
            "reviewsUnitIds": ["unit_b1_140_agentive_participle_nominal_derivat"],
            "reviewReason": "Supplies modern occupational vocabulary to enrich agentive morphology.",
            "audioSuitability": "standard_speech_synthesis_acceptable",
            "audioPurpose": "Pronunciation of modern corporate job titles and professional designations.",
            "successCriteria": [
                "Uses modern occupational terms accurately in professional contexts",
                "Explains the operational scope of different specialist titles"
            ],
            "masteryEvidence": "Produces 'Программ хангамж хөгжүүлэгчид системийн аюулгүй байдлыг хангах үүрэгтэй' without error.",
            "recommendedExerciseModalities": ["job_title_matching", "career_role_definition", "contextual_cloze"]
        },
        {
            "lessonId": "les_b1_140_03_labor_market_trends_reading",
            "unitId": uid_140, "cefrLevel": "B1", "sequenceWithinUnit": 3,
            "title": "Reading Analysis: National Labor Market Trends & Future of Work Reports",
            "lessonType": "reading_development",
            "primaryPurpose": "Deconstruct authentic labor market reports from the Ministry of Labor and Social Protection analyzing high-demand occupations, STEM sector deficits, and green economy jobs.",
            "communicativeOutcome": "Comprehend workforce analytics, employment demand forecasts, and vocational skill shortage assessments in formal Mongolian.",
            "objectivesIntroduced": ["obj_b1_140_03_read_labor_market_reports"],
            "objectivesPracticed": ["obj_b1_140_01_form_agentive_participles"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_participle_agentive_gch"],
            "grammarReviewed": ["gram_a2_verb_past_resultative_zhee", "gram_b1_clause_purposive_tuld_tuloo"],
            "phonologyIntroduced": [], "phonologyPracticed": [], "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_24_discussing_education_career_path"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 4, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_education_career_workplace", "lex_b1_opinion_argumentation_rhetoric"],
            "previousVocabularyReused": ["хөдөлмөрийн зах зээл", "эрэлт", "нийлүүлэлт", "ур чадвар", "цалин"],
            "readingObjective": "Read a 300-word excerpt from a national labor review and identify the 3 fastest growing professions and their required educational qualifications.",
            "listeningObjective": "", "writingObjective": "", "spokenProductionObjective": "",
            "registerTarget": "Formal socio-economic statistical and labor policy register",
            "pragmaticTarget": "Interpreting workforce metrics and supply/demand projections.",
            "prerequisiteLessonIds": ["les_b1_140_01_agentive_participle_morphology_intro"],
            "reviewsLessonIds": ["les_b1_126_03_socio_economic_causality_reading"],
            "reviewsUnitIds": ["unit_b1_126_causal_conjunctions_connectors_"],
            "reviewReason": "Connects macroeconomic demographic trends with labor market occupational demands.",
            "audioSuitability": "standard_speech_synthesis_acceptable",
            "audioPurpose": "Narration of labor market analysis.",
            "successCriteria": [
                "Identifies agentive occupational titles across growth industries",
                "Extracts salary benchmarks and technical certification prerequisites"
            ],
            "masteryEvidence": "Identifies that data analysts (өгөгдлийн шинжээч) and renewable engineers (сэргээгдэх эрчим хүчний инженер) face acute supply shortages.",
            "recommendedExerciseModalities": ["labor_table_extraction", "demand_ranking", "multiple_choice"]
        },
        {
            "lessonId": "les_b1_140_04_career_counseling_panel_discussion",
            "unitId": uid_140, "cefrLevel": "B1", "sequenceWithinUnit": 4,
            "title": "Discussion: Career Paths, Educational Pathways & Future-Proof Skills",
            "lessonType": "discussion",
            "primaryPurpose": "Participate in a university career development panel debating which professional paths offer greatest long-term stability and social impact in developing Mongolia.",
            "communicativeOutcome": "Evaluate educational trajectories, debate the merits of technical vocational trades versus academic credentials, and counsel peers.",
            "objectivesIntroduced": ["obj_b1_140_04_debate_career_pathways"],
            "objectivesPracticed": [
                "obj_b1_140_01_form_agentive_participles",
                "obj_b1_140_02_occupational_specializations_lexicon"
            ],
            "objectivesReviewed": ["obj_b1_133_01_professional_advisory_formulas"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_participle_agentive_gch"],
            "grammarReviewed": ["gram_b1_epistemic_probability_bololtoi_magadgui"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_b1_agentive_gch_connective_vowels"],
            "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_24_discussing_education_career_path"],
            "communicativeFunctionsReviewed": ["comm_b1_16_giving_advice_recommendations"],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_education_career_workplace"],
            "previousVocabularyReused": ["ирээдүй", "сонголт", "боловсрол", "мэргэжил эзэмших", "амжилт"],
            "readingObjective": "", "listeningObjective": "",
            "writingObjective": "",
            "spokenProductionObjective": "Contribute 4 speaking turns comparing the employment prospects of traditional livestock agronomy versus AI technology.",
            "registerTarget": "Mentorship and career guidance panel register",
            "pragmaticTarget": "Balancing personal passion with empirical labor market viability.",
            "prerequisiteLessonIds": ["les_b1_140_02_occupational_specializations_lexicon", "les_b1_140_03_labor_market_trends_reading"],
            "reviewsLessonIds": ["les_b1_133_03_executive_advisory_consultation_dialogue"],
            "reviewsUnitIds": ["unit_b1_133_giving_professional_advice_actionab"],
            "reviewReason": "Synthesizes professional advisory dialogue with specific occupational career trajectory analysis.",
            "audioSuitability": "mongolian_voice_required",
            "audioPurpose": "Provide discussion prompts and contrasting viewpoints by experienced career mentors.",
            "successCriteria": [
                "Contributes 4 analytical turns integrating agentive occupational titles fluently",
                "Weighs educational costs, market demand, and societal contribution realistically"
            ],
            "masteryEvidence": "Articulates 'Орчин үед программ хөгжүүлэгч төдийгүй байгаль орчны шинжээчдийн үүрэг нийгэмд улам бүр өсөн нэмэгдэж байна' persuasively.",
            "recommendedExerciseModalities": ["career_roundtable", "pathway_evaluation", "peer_critique"]
        }
    ])

    return lessons
