"""
Authoritative Pedagogical Specification for B1 Section 04: Part 3 (Units 151 - 153)
Units 151 (4 lessons), 152 (5 lessons), 153 (4 lessons) -> 13 lessons
"""

from typing import List, Dict, Any

def get_sec04_part3_lessons() -> List[Dict[str, Any]]:
    lessons = []

    # =========================================================================
    # UNIT 151: Traditional Blessing Poetry: Reciting Ерөөл
    # Budget: (20, 14, 6, 4) across 4 lessons -> (5,4,2,1), (5,4,1,1), (6,3,2,1), (4,3,1,1)
    # =========================================================================
    uid_151 = "unit_b1_151_traditional_blessing_poetry_recitin"
    lessons.extend([
        {
            "lessonId": "les_b1_151_01_yrool_magtaal_poetic_lexicon",
            "unitId": uid_151, "cefrLevel": "B1", "sequenceWithinUnit": 1,
            "title": "Blessing & Praise Poetry Lexicon: Alliterative Formulas of Well-Wishing",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Acquire the rhythmic, alliterative vocabulary of traditional blessing poetry (ерөөл) and praise odes (магтаал) recited at weddings, child hair-cutting rituals (даахь үргээх), yurt-raisings, and Tsagaan Sar feasts (дэлгэрэх, дэвжих, өлзий хутаг орших, түмэн олон, үр хүүхэд өнөр өтгөн болох).",
            "communicativeOutcome": "Recite and construct traditional Mongolian poetic well-wishes adhering to classical alliterative rhyming structures.",
            "objectivesIntroduced": ["obj_b1_151_01_yrool_poetic_formulas_lexicon"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_b1_150_01_zolgokh_greeting_formulas_lexicon"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_clause_causal_uchir_uchraas_tul"],
            "grammarReviewed": ["gram_a1_spatial_postpositions_deeree_door", "gram_a1_pronouns_personal_oblique_stems"],
            "phonologyIntroduced": ["phono_b1_alliterative_verse_meter"],
            "phonologyPracticed": [], "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": ["comm_b1_14_traditional_celebrations_tsagaan_sar"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 4, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_culture_traditions_heritage"],
            "previousVocabularyReused": ["ерөөл", "магтаал", "шүлэг", "жаргал", "хүсэл", "өлзий"],
            "readingObjective": "", "listeningObjective": "",
            "writingObjective": "Compose a 4-line traditional alliterative blessing quatrain for a family moving into a new home (гэрийн ерөөл).",
            "spokenProductionObjective": "Recite a traditional Tsagaan Sar blessing wished upon children and elders.",
            "registerTarget": "High traditional folkloric, ceremonial, and poetical blessing register",
            "pragmaticTarget": "Understanding that words carry generative spiritual power (үгийн билиг) in nomadic culture.",
            "prerequisiteLessonIds": ["les_b1_150_04_zolgokh_etiquette_roleplay_spoken"],
            "reviewsLessonIds": ["les_b1_141_01_similative_postpositions_morphosyntax_intro"],
            "reviewsUnitIds": ["unit_b1_141_similative_postpositions_"],
            "reviewReason": "Deepens figurative poetic language into ceremonial oral blessing genres.",
            "audioSuitability": "standard_speech_synthesis_acceptable",
            "audioPurpose": "Pronounce alliterative blessing couplets with traditional head-rhyme emphasis.",
            "successCriteria": [
                "Constructs 4-line verses with matching head-consonant alliteration (толгой холболт)",
                "Uses traditional optative and desiderative blessing verbs (болтугай, оршиг, дэлгэртүгэй)"
            ],
            "masteryEvidence": "Produces 'Эрдэм номдоо шамдаж, Эх орондоо тустай, Аав ээждээ ачтай, Ажил үйлс нь бүтэмжтэй байх болтугай' with flawless poetic meter.",
            "recommendedExerciseModalities": ["alliterative_rhyme_matching", "verse_completion_cloze", "poetic_composition"]
        },
        {
            "lessonId": "les_b1_151_02_ceremonial_yroolch_reading",
            "unitId": uid_151, "cefrLevel": "B1", "sequenceWithinUnit": 2,
            "title": "Reading Analysis: The Oral Heritage of Master Bards & Ritual Orators (Ерөөлч)",
            "lessonType": "reading_development",
            "primaryPurpose": "Deconstruct authentic ethnographic treatises profiling the role of master ritual orators (ерөөлч, магтаалч) who hold encyclopedic repertoires of ceremonial praise poems for horses, yurts, silver cups, and wrestling champions.",
            "communicativeOutcome": "Comprehend formal cultural analyses of Mongolian oral epic poetry, memory traditions, and rhyming improvisation.",
            "objectivesIntroduced": ["obj_b1_151_02_read_bardic_oral_traditions"],
            "objectivesPracticed": ["obj_b1_151_01_yrool_poetic_formulas_lexicon"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_clause_causal_uchir_uchraas_tul"],
            "grammarReviewed": ["gram_a1_pronouns_personal_oblique_stems"],
            "phonologyIntroduced": [], "phonologyPracticed": [], "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_14_traditional_celebrations_tsagaan_sar"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 4, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_culture_traditions_heritage"],
            "previousVocabularyReused": ["аман зохиол", "өв", "цээжлэх", "найр", "мөнгөн аяга"],
            "readingObjective": "Read a 300-word ethnographic profile of a Western Mongolian bard and identify 3 distinct occasions demanding a specialized blessing ode.",
            "listeningObjective": "", "writingObjective": "", "spokenProductionObjective": "",
            "registerTarget": "High ethnographic and literary oral history register",
            "pragmaticTarget": "Appreciating oral improvisation within strict traditional metric boundaries.",
            "prerequisiteLessonIds": ["les_b1_151_01_yrool_magtaal_poetic_lexicon"],
            "reviewsLessonIds": ["les_b1_141_03_mongolian_poetry_lyrics_reading"],
            "reviewsUnitIds": ["unit_b1_141_similative_postpositions_"],
            "reviewReason": "Expands literary poetry reading from modern written lyrics to ancient oral epic bards.",
            "audioSuitability": "standard_speech_synthesis_acceptable",
            "audioPurpose": "Narration of ethnographic bardic treatise.",
            "successCriteria": [
                "Identifies traditional ceremonial genres (Мөнгөн аяганы ерөөл, Гэрийн магтаал, Уяачийн ерөөл)",
                "Understands causal clauses explaining why blessings are recited at transitional milestones"
            ],
            "masteryEvidence": "Identifies that bards recite blessing odes to invite good fortune and ward off misfortune at pivotal life milestones.",
            "recommendedExerciseModalities": ["ceremonial_genre_matching", "poetic_function_extraction", "multiple_choice"]
        },
        {
            "lessonId": "les_b1_151_03_morin_khuur_blessing_listening",
            "unitId": uid_151, "cefrLevel": "B1", "sequenceWithinUnit": 3,
            "title": "Acoustic Comprehension: Live Recitation of a Blessing Ode Accompanied by Morin Khuur",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop auditory listening comprehension for an authentic, unhurried recitation of an elaborate blessing ode performed to the resonant, soaring accompaniment of the horsehead fiddle (морин хуур).",
            "communicativeOutcome": "Understand chanted oral poetry, track alliterative head-rhymes through musical accompaniment, and comprehend high ceremonial vocabulary.",
            "objectivesIntroduced": ["obj_b1_151_03_comprehend_chanted_blessing_odes"],
            "objectivesPracticed": ["obj_b1_151_01_yrool_poetic_formulas_lexicon"],
            "objectivesReviewed": ["obj_b1_146_03_comprehend_zasuul_chant"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_clause_causal_uchir_uchraas_tul"],
            "grammarReviewed": ["gram_a1_spatial_postpositions_deeree_door"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_b1_alliterative_verse_meter"],
            "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_14_traditional_celebrations_tsagaan_sar"],
            "communicativeFunctionsReviewed": ["comm_b1_17_expressing_emotional_reactions"],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_culture_traditions_heritage"],
            "previousVocabularyReused": ["морин хуур", "эгшиг", "цоглог", "найрын жаргал", "хүндэтгэх"],
            "readingObjective": "",
            "listeningObjective": "Listen to a 2.5-minute audio performance of a blessing ode with morin khuur and transcribe the 4 primary wishes offered to the hosts.",
            "writingObjective": "", "spokenProductionObjective": "",
            "registerTarget": "Elevated musical bardic performance register",
            "pragmaticTarget": "Tracking spoken poetry layered over complex string overtone accompaniment.",
            "prerequisiteLessonIds": ["les_b1_151_01_yrool_magtaal_poetic_lexicon", "les_b1_151_02_ceremonial_yroolch_reading"],
            "reviewsLessonIds": ["les_b1_146_03_zasuul_heraldic_praise_listening"],
            "reviewsUnitIds": ["unit_b1_146_mongolian_wrestling_titles_garudas_"],
            "reviewReason": "Expands ceremonial listening from solo heraldic shouting to musical morin khuur bardic recitation.",
            "audioSuitability": "mongolian_voice_required",
            "audioPurpose": "Authentic studio performance of an elder bard chanting with live acoustic morin khuur bowing.",
            "successCriteria": [
                "Identifies the rhythmic meter connecting the morin khuur rhythm with poetic verses",
                "Transcribes archaic blessing formulas and traditional optative verbal endings"
            ],
            "masteryEvidence": "Transcribes 'Айл гэрт тань амгалан жаргалан дэлгэрч, Адуу мал тань түм түмээр өсөх болтугай' accurately from audio.",
            "recommendedExerciseModalities": ["audio_verse_transcription", "rhyme_tracking_exercise", "multiple_choice"]
        },
        {
            "lessonId": "les_b1_151_04_toast_blessing_recitation_spoken",
            "unitId": uid_151, "cefrLevel": "B1", "sequenceWithinUnit": 4,
            "title": "Spoken Production: Delivering a Traditional Feast Toast & Formal Blessing",
            "lessonType": "spoken_production",
            "primaryPurpose": "Deliver an articulate 2-minute ceremonial banquet toast (ерөөлийн үг) at a formal family gathering or community feast, reciting an alliterative quatrain and blessing the health, unity, and prosperity of all present.",
            "communicativeOutcome": "Deliver poised, culturally impressive ceremonial toasts and formal oral blessings in public gatherings.",
            "objectivesIntroduced": ["obj_b1_151_04_deliver_ceremonial_toast"],
            "objectivesPracticed": [
                "obj_b1_151_01_yrool_poetic_formulas_lexicon",
                "obj_b1_151_03_comprehend_chanted_blessing_odes"
            ],
            "objectivesReviewed": ["obj_b1_138_05_deliver_mentor_tribute"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_clause_causal_uchir_uchraas_tul"],
            "grammarReviewed": ["gram_a1_pronouns_personal_oblique_stems"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_b1_alliterative_verse_meter"],
            "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_14_traditional_celebrations_tsagaan_sar"],
            "communicativeFunctionsReviewed": ["comm_b1_06_stating_purpose_long_term_goals"],
            "newProductiveLemmaTarget": 4, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_culture_traditions_heritage"],
            "previousVocabularyReused": ["хундага өргөх", "ерөөл", "эрүүл энх", "амжилт", "баярын ширээ"],
            "readingObjective": "", "listeningObjective": "", "writingObjective": "",
            "spokenProductionObjective": "Deliver a 2-minute ceremonial toast holding a symbolic cup, opening with personal gratitude and culminating in a traditional 4-line alliterative blessing.",
            "registerTarget": "High ceremonial celebratory toast and banquet oratorical register",
            "pragmaticTarget": "Projecting warmth, gravitas, and communal well-wishing without reading from notes.",
            "prerequisiteLessonIds": ["les_b1_151_02_ceremonial_yroolch_reading", "les_b1_151_03_morin_khuur_blessing_listening"],
            "reviewsLessonIds": ["les_b1_138_05_mentorship_tribute_spoken"],
            "reviewsUnitIds": ["unit_b1_138_subordinate_subject_genitive_case_m"],
            "reviewReason": "Synthesizes mentorship tribute speech skills with classical alliterative blessing poetry.",
            "audioSuitability": "mongolian_voice_required",
            "audioPurpose": "Provide benchmark audio recording of an elegant feast toast delivered by a respected guest.",
            "successCriteria": [
                "Delivers a 2-minute fluent toast opening with host appreciation and culminating in an alliterative quatrain",
                "Applies elevated vocabulary and traditional optative verbal endings (-болтугай, -өгтүгэй)"
            ],
            "masteryEvidence": "Delivers 'Хуран цугласан олондоо эрүүл энх, аз жаргалын дээдийг хүсэн ерөөж, энэхүү мөнгөн хундгыг өргөн барья' with poised eloquence.",
            "recommendedExerciseModalities": ["banquet_toast_monologue", "peer_evaluation", "ceremonial_speech_rubric"]
        }
    ])

    # =========================================================================
    # UNIT 152: Hearsay Evidentiality: Particles Гэнэ and Сурагтай
    # Budget: (22, 15, 6, 4) across 5 lessons -> (6,4,2,1), (5,4,1,1), (5,3,1,1), (6,4,2,1), (0,0,0,0)
    # =========================================================================
    uid_152 = "unit_b1_152_hearsay_evidentiality_particles_and"
    lessons.extend([
        {
            "lessonId": "les_b1_152_01_hearsay_particles_morphosyntax_intro",
            "unitId": uid_152, "cefrLevel": "B1", "sequenceWithinUnit": 1,
            "title": "Hearsay Evidentiality: Distinguishing Гэнэ (They Say) vs Сурагтай (Rumored)",
            "lessonType": "grammar_introduction",
            "primaryPurpose": "Introduce the B1 hearsay evidentiality system: 1) Quotative/hearsay particle гэнэ (reporting second-hand information, rumors, or unverified claims: маргааш цас орно гэнэ, тэр их сайн ажилладаг гэнэ), and 2) Inferential hearsay/news particle сурагтай (distant rumor or widespread hearsay: хөдөө өвөлжилт хүндрэх сурагтай, шинэ төсөл эхлэх сурагтай).",
            "communicativeOutcome": "Communicate reported information, relay news, and report unverified gossip without claiming direct personal eyewitness authority.",
            "objectivesIntroduced": ["obj_b1_152_01_use_hearsay_particles"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_b1_151_01_yrool_poetic_formulas_lexicon"],
            "grammarIntroduced": ["gram_b1_evidentiality_hearsay_gene_suragtai"],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_ablative_comparative", "gram_b1_converb_contemporaneous_magts"],
            "phonologyIntroduced": ["phono_b1_hearsay_particle_intonation"],
            "phonologyPracticed": [], "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": ["comm_b1_07_relaying_hearsay_news"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 4, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_opinion_argumentation_rhetoric", "lex_b1_media_digital_society"],
            "previousVocabularyReused": ["сонсох", "хэлэх", "сураг", "мэдээ", "үнэн", "цуурхал"],
            "readingObjective": "", "listeningObjective": "",
            "writingObjective": "Convert 8 direct declarative statements into indirect hearsay statements using гэнэ and сурагтай.",
            "spokenProductionObjective": "Relay a piece of news you heard on social media to a friend, framing it explicitly as unverified hearsay.",
            "registerTarget": "Standard conversational and informational news relay register",
            "pragmaticTarget": "Epistemic responsibility: avoiding making factual claims about events you did not personally witness.",
            "prerequisiteLessonIds": ["les_b1_151_04_toast_blessing_recitation_spoken"],
            "reviewsLessonIds": ["les_b1_132_01_epistemic_particles_morphosyntax_intro"],
            "reviewsUnitIds": ["unit_b1_132_epistemic_probability_particles_vs_"],
            "reviewReason": "Complements epistemic probability (бололтой/магадгүй) with grammatical hearsay evidentiality (гэнэ/сурагтай).",
            "audioSuitability": "standard_speech_synthesis_acceptable",
            "audioPurpose": "Demonstrate the sentence-final descending intonation of гэнэ and сурагтай.",
            "successCriteria": [
                "Applies гэнэ directly to inflected verbs and nominal predicates",
                "Applies сурагтай to participial stems (-х сурагтай, -сан сурагтай) to indicate rumors"
            ],
            "masteryEvidence": "Produces 'Энэ жил өвөл маш хүйтэн болох сурагтай' and 'Түүнийг гадаад руу суралцахаар явсан гэнэ' accurately.",
            "recommendedExerciseModalities": ["hearsay_conversion", "particle_selection", "sentence_completion"]
        },
        {
            "lessonId": "les_b1_152_02_evidentiality_contrastive_guided_practice",
            "unitId": uid_152, "cefrLevel": "B1", "sequenceWithinUnit": 2,
            "title": "Guided Practice: Direct Witness (-лаа) vs Inferential (-жээ) vs Hearsay (гэнэ)",
            "lessonType": "grammar_guided_practice",
            "primaryPurpose": "Master the three-way evidential contrast fundamental to Mongolian epistemology: 1) Direct personal observation (-лаа/-лоо/-в), 2) Post-facto perceptual deduction (-жээ/-чээ, бололтой), and 3) Second-hand reported hearsay (гэнэ, сурагтай, сураг дуулдсан).",
            "communicativeOutcome": "Select precise epistemic and evidential markers based on whether you saw the event yourself, deduced it from clues, or heard about it from others.",
            "objectivesIntroduced": ["obj_b1_152_02_contrast_evidential_tiers"],
            "objectivesPracticed": ["obj_b1_152_01_use_hearsay_particles"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_evidentiality_hearsay_gene_suragtai"],
            "grammarReviewed": ["gram_a1_pronouns_demonstrative_case_declension", "gram_a1_interrogatives_case_declension"],
            "phonologyIntroduced": [], "phonologyPracticed": [], "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_07_relaying_hearsay_news"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 4, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_opinion_argumentation_rhetoric"],
            "previousVocabularyReused": ["үзэх", "сонсох", "баттай", "эргэлзэх", "мэдэгдэх"],
            "readingObjective": "", "listeningObjective": "",
            "writingObjective": "Given 6 scenarios with differing knowledge sources, select and write sentences with the correct evidential marker.",
            "spokenProductionObjective": "Explain what happened to a mutual acquaintance, contrasting what you saw directly with what others told you.",
            "registerTarget": "Epistemic calibration and communication precision register",
            "pragmaticTarget": "Never claiming direct witness for secondhand hearsay, which compromises credibility in Mongolian society.",
            "prerequisiteLessonIds": ["les_b1_152_01_hearsay_particles_morphosyntax_intro"],
            "reviewsLessonIds": ["les_b1_152_01_hearsay_particles_morphosyntax_intro"],
            "reviewsUnitIds": ["unit_b1_152_hearsay_evidentiality_particles_and"],
            "reviewReason": "Intensive structural drill contrasting direct, deductive, and hearsay epistemic modes.",
            "audioSuitability": "standard_speech_synthesis_acceptable",
            "audioPurpose": "Synthesize sentences contrasting evidential verb endings.",
            "successCriteria": [
                "Selects -лаа only when direct eyewitness verification is present",
                "Selects гэнэ/сурагтай whenever knowledge originates from third-party reports"
            ],
            "masteryEvidence": "Contrasts 'Би өөрийн нүдээр харлаа' with 'Тэр тэгсэн гэнэ' without epistemic confusion.",
            "recommendedExerciseModalities": ["knowledge_source_matching", "evidential_triad_sorting", "error_correction"]
        },
        {
            "lessonId": "les_b1_152_03_breaking_news_investigative_reading",
            "unitId": uid_152, "cefrLevel": "B1", "sequenceWithinUnit": 3,
            "title": "Reading Analysis: Journalistic Sourcing, Press Dispatches & Rumor Verification",
            "lessonType": "reading_development",
            "primaryPurpose": "Deconstruct authentic investigative journalism dispatches and news reports reporting on government reshuffles, market mergers, or weather warnings where journalists cite anonymous sources using hearsay markers (эх сурвалжийн мэдээлснээр, ...гэнэ, ...сурагтай байна).",
            "communicativeOutcome": "Evaluate journalistic credibility, identify anonymous sourcing formulas, and distinguish verified facts from reported claims in news media.",
            "objectivesIntroduced": ["obj_b1_152_03_read_journalistic_hearsay"],
            "objectivesPracticed": ["obj_b1_152_01_use_hearsay_particles"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_evidentiality_hearsay_gene_suragtai"],
            "grammarReviewed": ["gram_a1_case_ablative_comparative"],
            "phonologyIntroduced": [], "phonologyPracticed": [], "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_07_relaying_hearsay_news"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_media_digital_society", "lex_b1_opinion_argumentation_rhetoric"],
            "previousVocabularyReused": ["сэтгүүлч", "мэдээлэл", "эх сурвалж", "нотлох", "албан бус"],
            "readingObjective": "Read a 300-word news dispatch reporting on a sudden regulatory tax change and categorize statements into verified government facts versus unconfirmed industry rumors.",
            "listeningObjective": "", "writingObjective": "", "spokenProductionObjective": "",
            "registerTarget": "Journalistic investigative media register",
            "pragmaticTarget": "Distinguishing objective verified facts from reported source allegations.",
            "prerequisiteLessonIds": ["les_b1_152_01_hearsay_particles_morphosyntax_intro"],
            "reviewsLessonIds": ["les_b1_134_02_film_reviews_reading"],
            "reviewsUnitIds": ["unit_b1_134_film_literary_criticism_evaluating_"],
            "reviewReason": "Expands journalistic reading from arts reviews to hard news and investigative reporting.",
            "audioSuitability": "standard_speech_synthesis_acceptable",
            "audioPurpose": "Narration of news dispatch.",
            "successCriteria": [
                "Identifies sourcing formulas (албаны эх сурвалж хэлснээр, ...гэж мэдээлэв, ...гэнэ)",
                "Differentiates confirmed factual assertions from speculative rumors"
            ],
            "masteryEvidence": "Identifies that the tax rate change was rumored (сурагтай) but not officially confirmed by the ministry.",
            "recommendedExerciseModalities": ["fact_vs_rumor_table", "sourcing_attribution_exercise", "multiple_choice"]
        },
        {
            "lessonId": "les_b1_152_04_grapevine_rumors_listening",
            "unitId": uid_152, "cefrLevel": "B1", "sequenceWithinUnit": 4,
            "title": "Acoustic Comprehension: Community Grapevine & Passing Along Spoken Rumors",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop auditory listening comprehension for casual neighborhood and workplace conversations where speakers exchange rumors about upcoming price hikes, neighborhood renovations, and office relocations.",
            "communicativeOutcome": "Understand rapid, informal colloquial speech heavy with evidential hearsay particles, hedges, and expressions of skepticism.",
            "objectivesIntroduced": ["obj_b1_152_04_comprehend_spoken_hearsay"],
            "objectivesPracticed": ["obj_b1_152_01_use_hearsay_particles"],
            "objectivesReviewed": ["obj_b1_143_03_comprehend_pasture_council_meeting"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_evidentiality_hearsay_gene_suragtai"],
            "grammarReviewed": ["gram_b1_converb_contemporaneous_magts"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_b1_hearsay_particle_intonation"],
            "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_07_relaying_hearsay_news"],
            "communicativeFunctionsReviewed": ["comm_b1_03_expressing_opinions_agreements"],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 4, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_opinion_argumentation_rhetoric", "lex_b1_media_digital_society"],
            "previousVocabularyReused": ["яриа", "сонссон", "үнэн үү", "магадгүй", "хүмүүс ярих"],
            "readingObjective": "",
            "listeningObjective": "Listen to a 2-minute conversation between colleagues discussing office relocation rumors and transcribe who claims what.",
            "writingObjective": "", "spokenProductionObjective": "",
            "registerTarget": "Informal workplace grapevine and conversational hearsay register",
            "pragmaticTarget": "Tracking hearsay claims through rapid conversational turns.",
            "prerequisiteLessonIds": ["les_b1_152_02_evidentiality_contrastive_guided_practice", "les_b1_152_03_breaking_news_investigative_reading"],
            "reviewsLessonIds": ["les_b1_143_03_herder_community_roundtable_listening"],
            "reviewsUnitIds": ["unit_b1_143_environmental_conservation_pasture_"],
            "reviewReason": "Expands conversational listening to informal rumor circulation and skepticism.",
            "audioSuitability": "mongolian_voice_required",
            "audioPurpose": "Authentic conversational audio of two colleagues whispering about rumors over tea.",
            "successCriteria": [
                "Identifies hearsay particles гэнэ and сурагтай in colloquial rapid speech",
                "Extracts speaker attitudes toward the veracity of the rumors"
            ],
            "masteryEvidence": "Summarizes that Person A heard the company might relocate to Zaisan, but Person B doubts it.",
            "recommendedExerciseModalities": ["hearsay_attribution_audio", "skepticism_detection", "multiple_choice"]
        },
        {
            "lessonId": "les_b1_152_05_investigative_debrief_spoken",
            "unitId": uid_152, "cefrLevel": "B1", "sequenceWithinUnit": 5,
            "title": "Spoken Production: Debriefing a Complex News Investigation to Colleagues",
            "lessonType": "spoken_production",
            "primaryPurpose": "Deliver an articulate 2-minute oral debrief summarizing a developing news story, clearly distinguishing what has been officially verified from what remains unconfirmed hearsay using гэнэ, сурагтай, and source attribution phrases.",
            "communicativeOutcome": "Present nuanced, responsible spoken briefings on ambiguous, rapidly unfolding events.",
            "objectivesIntroduced": ["obj_b1_152_05_debrief_news_investigation"],
            "objectivesPracticed": [
                "obj_b1_152_01_use_hearsay_particles",
                "obj_b1_152_02_contrast_evidential_tiers"
            ],
            "objectivesReviewed": ["obj_b1_148_04_report_archery_tournament"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_evidentiality_hearsay_gene_suragtai"],
            "grammarReviewed": ["gram_a1_case_ablative_comparative"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_b1_hearsay_particle_intonation"],
            "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_07_relaying_hearsay_news"],
            "communicativeFunctionsReviewed": ["comm_b1_05_making_causal_arguments"],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_b1_opinion_argumentation_rhetoric", "lex_b1_media_digital_society"],
            "previousVocabularyReused": ["мэдээлэл", "баталгаатай", "сураг", "гэнэ", "дүгнэлт"],
            "readingObjective": "", "listeningObjective": "", "writingObjective": "",
            "spokenProductionObjective": "Deliver a 2-minute spoken briefing on a developing public infrastructure project, using гэнэ and сурагтай to delineate unconfirmed reports.",
            "registerTarget": "Professional investigative and news briefing register",
            "pragmaticTarget": "Maintaining rigorous intellectual honesty regarding information provenance.",
            "prerequisiteLessonIds": ["les_b1_152_03_breaking_news_investigative_reading", "les_b1_152_04_grapevine_rumors_listening"],
            "reviewsLessonIds": ["les_b1_148_04_marksman_tournament_report_spoken"],
            "reviewsUnitIds": ["unit_b1_148_archery_ankle_bone_shooting_"],
            "reviewReason": "Synthesizes field sports reporting with rigorous epistemic hearsay news debriefing.",
            "audioSuitability": "mongolian_voice_required",
            "audioPurpose": "Provide benchmark audio recording of a professional news analyst delivering a debrief.",
            "successCriteria": [
                "Delivers a 2-minute cohesive oral debrief clearly differentiating confirmed facts from rumors",
                "Applies гэнэ and сурагтай accurately at clause boundaries"
            ],
            "masteryEvidence": "Delivers 'Албаны эх сурвалж зам засварыг аравдугаар сард дуусна гэж байгаа ч ирэх хавар хүртэл хойшлогдох сурагтай байна' with professional poise.",
            "recommendedExerciseModalities": ["investigative_briefing_monologue", "peer_critique", "epistemic_accuracy_rubric"]
        }
    ])

    # =========================================================================
    # UNIT 153: Expressing Deep Emotional Reactions in Festivities
    # Budget: (20, 14, 6, 4) across 4 lessons -> (5,4,2,1), (5,4,1,1), (6,3,2,1), (4,3,1,1)
    # =========================================================================
    uid_153 = "unit_b1_153_expressing_deep_emotional_reactions"
    lessons.extend([
        {
            "lessonId": "les_b1_153_01_festive_affect_exclamations_lexicon",
            "unitId": uid_153, "cefrLevel": "B1", "sequenceWithinUnit": 1,
            "title": "Emotional Resonance Lexicon: Exclamations, Awe, Nostalgia & Jubilation",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Acquire expressive affective vocabulary and idiomatic exclamations for intense emotional experiences during cultural festivities (самсаа шархирах - tearful joy/pride, огших - chest swelling with emotion, бахдах - admiring awe, сэтгэл уярах - heart softening with nostalgia, хайлж урсах, баяр бахдал, өөрийн эрхгүй).",
            "communicativeOutcome": "Articulate nuanced, profound emotional reactions, nostalgic stirrings, and heartfelt patriotism in rich affective Mongolian.",
            "objectivesIntroduced": ["obj_b1_153_01_festive_affect_lexicon"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_b1_152_01_use_hearsay_particles"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_converb_durative_saar"],
            "grammarReviewed": ["gram_a2_numerals_ordinal", "gram_b1_evidentiality_hearsay_gene_suragtai"],
            "phonologyIntroduced": ["phono_b1_affective_exclamatory_lengthening"],
            "phonologyPracticed": [], "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": ["comm_b1_17_expressing_emotional_reactions"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 4, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_opinion_argumentation_rhetoric", "lex_b1_culture_traditions_heritage"],
            "previousVocabularyReused": ["сэтгэл", "баярлах", "уйлах", "хайрлах", "бахархах", "догдлох"],
            "readingObjective": "", "listeningObjective": "",
            "writingObjective": "Draft 5 sentences describing the physical sensation of national pride when hearing the state anthem or morin khuur.",
            "spokenProductionObjective": "Describe an unforgettable moment during a festival that moved you to tears.",
            "registerTarget": "Expressive affective, introspective, and emotional register",
            "pragmaticTarget": "Using culturally unique somatic idioms (самсаа шархирах, цээж огших) to capture profound feelings.",
            "prerequisiteLessonIds": ["les_b1_152_05_investigative_debrief_spoken"],
            "reviewsLessonIds": ["les_b1_145_01_naadam_cultural_pageantry_lexicon"],
            "reviewsUnitIds": ["unit_b1_145_national_pride_the_three_manly_game"],
            "reviewReason": "Deepens festival pageantry into intimate somatic and affective psychological reactions.",
            "audioSuitability": "standard_speech_synthesis_acceptable",
            "audioPurpose": "Model warm, emotionally resonant intonation and affective vowel lengthening.",
            "successCriteria": [
                "Uses somatic emotional idioms accurately (цээж огших, самсаа шархирах, сэтгэл уярах)",
                "Forms cohesive sentences connecting cultural sights with internal affective resonance"
            ],
            "masteryEvidence": "Produces 'Төрийн дуулал эгшиглэж, Есөн хөлт цагаан тугаа залах үед өөрийн эрхгүй самсаа шархирч, сэтгэл огшсон' with authentic emotion.",
            "recommendedExerciseModalities": ["affective_collocation_matching", "somatic_idiom_cloze", "sentence_expansion"]
        },
        {
            "lessonId": "les_b1_153_02_patriotic_memoir_reading",
            "unitId": uid_153, "cefrLevel": "B1", "sequenceWithinUnit": 2,
            "title": "Reading Analysis: Literary Memoirs on Festival Nostalgia & Homeland Longing",
            "lessonType": "reading_development",
            "primaryPurpose": "Deconstruct authentic literary essays and diaspora memoirs (e.g., essays on celebrating Tsagaan Sar abroad or hearing morin khuur in distant lands) reflecting on homeland yearning (нутаг сэтгэл) and festival memories.",
            "communicativeOutcome": "Comprehend deeply introspective literary non-fiction exploring cultural identity, homesickness, and festive nostalgia.",
            "objectivesIntroduced": ["obj_b1_153_02_read_festive_memoirs"],
            "objectivesPracticed": ["obj_b1_153_01_festive_affect_lexicon"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_converb_durative_saar"],
            "grammarReviewed": ["gram_a2_numerals_ordinal"],
            "phonologyIntroduced": [], "phonologyPracticed": [], "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_17_expressing_emotional_reactions"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 4, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_culture_traditions_heritage", "lex_b1_opinion_argumentation_rhetoric"],
            "previousVocabularyReused": ["дурсамж", "харь газар", "нутаг", "ээж аав", "уярах"],
            "readingObjective": "Read a 300-word memoir passage about a student celebrating Tsagaan Sar away from home and trace 3 distinct emotional transitions.",
            "listeningObjective": "", "writingObjective": "", "spokenProductionObjective": "",
            "registerTarget": "High literary reflective memoir and personal essay register",
            "pragmaticTarget": "Interpreting cultural nostalgia as an enduring anchor of nomadic identity.",
            "prerequisiteLessonIds": ["les_b1_153_01_festive_affect_exclamations_lexicon"],
            "reviewsLessonIds": ["les_b1_138_03_biographical_memoir_reading"],
            "reviewsUnitIds": ["unit_b1_138_subordinate_subject_genitive_case_m"],
            "reviewReason": "Expands biographical reading from mentorship chronicles to deep affective homesickness and festive nostalgia.",
            "audioSuitability": "standard_speech_synthesis_acceptable",
            "audioPurpose": "Narration of diaspora memoir excerpt.",
            "successCriteria": [
                "Identifies affective idioms describing nostalgic homesickness",
                "Extracts specific cultural anchors (boov, tea, melody) that trigger emotional reflection"
            ],
            "masteryEvidence": "Identifies that hearing the first notes of 'Ulemjiin Chanar' in a foreign city moved the author to tears of homesickness.",
            "recommendedExerciseModalities": ["affective_timeline_mapping", "memoir_theme_extraction", "multiple_choice"]
        },
        {
            "lessonId": "les_b1_153_03_stadium_triumph_interviews_listening",
            "unitId": uid_153, "cefrLevel": "B1", "sequenceWithinUnit": 3,
            "title": "Acoustic Comprehension: Post-Match Victory Tears & Joyous Family Embraces",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop auditory listening comprehension for emotionally overwhelming live stadium interviews: a newly crowned National Lion sobbing with his elderly father, or an eight-year-old jockey being hoisted onto the shoulders of village elders.",
            "communicativeOutcome": "Understand authentic unscripted emotional speech, broken syntax, tearful laughter, and exclamations of uncontainable triumph.",
            "objectivesIntroduced": ["obj_b1_153_03_comprehend_emotional_triumph_audio"],
            "objectivesPracticed": ["obj_b1_153_01_festive_affect_lexicon"],
            "objectivesReviewed": ["obj_b1_147_03_comprehend_giingoo_chants"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_converb_durative_saar"],
            "grammarReviewed": ["gram_b1_evidentiality_hearsay_gene_suragtai"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_b1_affective_exclamatory_lengthening"],
            "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_17_expressing_emotional_reactions"],
            "communicativeFunctionsReviewed": ["comm_b1_01_narrating_personal_anecdotes"],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_culture_traditions_heritage", "lex_b1_media_digital_society"],
            "previousVocabularyReused": ["ялалт", "баярын нулимс", "тэврэх", "баярлалаа", "аав"],
            "readingObjective": "",
            "listeningObjective": "Listen to a 2-minute live audio interview with a new champion wrestler choking back tears and transcribe his first words to his home aimag.",
            "writingObjective": "", "spokenProductionObjective": "",
            "registerTarget": "Raw emotional, spontaneous live sports victory register",
            "pragmaticTarget": "Navigating choked voices, joyous laughter, and passionate shouts in natural speech.",
            "prerequisiteLessonIds": ["les_b1_153_01_festive_affect_exclamations_lexicon", "les_b1_153_02_patriotic_memoir_reading"],
            "reviewsLessonIds": ["les_b1_147_04_finish_line_excitement_spoken"],
            "reviewsUnitIds": ["unit_b1_147_horse_racing_age_classes_giingoo"],
            "reviewReason": "Expands finish line excitement to the intimate human emotional interviews immediately following victory.",
            "audioSuitability": "mongolian_voice_required",
            "audioPurpose": "Authentic live audio of a champion wrestler crying with joy and dedicating his title to his deceased mother.",
            "successCriteria": [
                "Transcribes emotional, choked-up unscripted speech accurately",
                "Recognizes spontaneous affective phrases and grateful dedications"
            ],
            "masteryEvidence": "Transcribes 'Аавдаа, нутгийнхаа зон олонд маш их баярлалаа... энэ цолыг хүртсэндээ итгэж чадахгүй байна' from audio.",
            "recommendedExerciseModalities": ["audio_emotion_transcription", "affective_state_matching", "multiple_choice"]
        },
        {
            "lessonId": "les_b1_153_04_deep_festive_reflection_spoken",
            "unitId": uid_153, "cefrLevel": "B1", "sequenceWithinUnit": 4,
            "title": "Spoken Production: Delivering an Introspective Reflection on Belonging & Heritage",
            "lessonType": "spoken_production",
            "primaryPurpose": "Deliver an expressive, heartfelt 2-minute personal monologue sharing what Mongolian culture, festivities, and community belonging mean to you personally, weaving evocative affective expressions.",
            "communicativeOutcome": "Produce deeply moving, authentic personal discourse that bridges language skill into genuine human vulnerability and cultural connection.",
            "objectivesIntroduced": ["obj_b1_153_04_deliver_festive_reflection"],
            "objectivesPracticed": [
                "obj_b1_153_01_festive_affect_lexicon",
                "obj_b1_153_03_comprehend_emotional_triumph_audio"
            ],
            "objectivesReviewed": ["obj_b1_151_04_deliver_ceremonial_toast"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_converb_durative_saar"],
            "grammarReviewed": ["gram_a2_numerals_ordinal"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_b1_affective_exclamatory_lengthening"],
            "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_17_expressing_emotional_reactions"],
            "communicativeFunctionsReviewed": ["comm_b1_03_expressing_opinions_agreements"],
            "newProductiveLemmaTarget": 4, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_culture_traditions_heritage", "lex_b1_opinion_argumentation_rhetoric"],
            "previousVocabularyReused": ["сэтгэл", "бахархал", "соёл", "ойлгох", "мэдрэх"],
            "readingObjective": "", "listeningObjective": "", "writingObjective": "",
            "spokenProductionObjective": "Deliver a 2-minute heartfelt monologue reflecting on the profound sense of unity and spiritual uplift experienced during a Mongolian festival.",
            "registerTarget": "Introspective, deeply sincere personal essay spoken register",
            "pragmaticTarget": "Connecting personal growth to broader cultural and spiritual belonging.",
            "prerequisiteLessonIds": ["les_b1_153_02_patriotic_memoir_reading", "les_b1_153_03_stadium_triumph_interviews_listening"],
            "reviewsLessonIds": ["les_b1_151_04_toast_blessing_recitation_spoken"],
            "reviewsUnitIds": ["unit_b1_151_traditional_blessing_poetry_recitin"],
            "reviewReason": "Synthesizes formal banquet toasting into deep, personal introspective affective reflection.",
            "audioSuitability": "mongolian_voice_required",
            "audioPurpose": "Provide benchmark audio recording of a moving introspective reflection on cultural belonging.",
            "successCriteria": [
                "Delivers a 2-minute heartfelt monologue utilizing somatic emotional idioms (самсаа шархирах, цээж огших, сэтгэл уярах)",
                "Maintains sincere, moving vocal modulation and unhurried pacing"
            ],
            "masteryEvidence": "Delivers 'Монгол түмний дунд сууж, энэ аугаа түүх, өв соёлыг мэдрэх бүрд өөрийн эрхгүй цээж огшиж, хэл сурснаараа бахархдаг' movingly.",
            "recommendedExerciseModalities": ["introspective_monologue", "peer_aesthetic_feedback", "affective_expression_rubric"]
        }
    ])

    return lessons
