"""
Authoritative Pedagogical Specification for B1 Section 02: Part 1 (Units 124 - 126)
Units 124 (4 lessons), 125 (4 lessons), 126 (5 lessons) -> 13 lessons
"""

from typing import List, Dict, Any

def get_sec02_part1_lessons() -> List[Dict[str, Any]]:
    lessons = []

    # =========================================================================
    # UNIT 124: Formulating Nuanced Personal Stances & Viewpoints
    # Budget: (20, 14, 6, 4) across 4 lessons -> (5,4,2,1), (6,4,2,1), (5,3,1,1), (4,3,1,1)
    # =========================================================================
    uid_124 = "unit_b1_124_formulating_nuanced_personal_stance"
    lessons.extend([
        {
            "lessonId": "les_b1_124_01_opinion_epistemic_stance_lexicon",
            "unitId": uid_124, "cefrLevel": "B1", "sequenceWithinUnit": 1,
            "title": "Stance Formulas: Expressing Degrees of Conviction & Subjective Perspective",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Introduce nuanced lexical formulas for articulating personal stances, varying from tentative conjecture (миний бодлоор, миний ажигласнаар) to firm conviction (миний бат итгэлтэй байгаагаар, эргэлзээгүй).",
            "communicativeOutcome": "Express subjective stances on social and professional topics with calibrated epistemic certainty.",
            "objectivesIntroduced": ["obj_b1_124_01_express_nuanced_stance"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_b1_123_01_indirect_reported_speech"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_reported_speech_indirect_tense_shift"],
            "grammarReviewed": ["gram_a1_nominal_negation_bish", "gram_a2_converb_temporal_while_khad"],
            "phonologyIntroduced": ["phono_b1_parenthetical_stance_intonation"],
            "phonologyPracticed": [], "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": ["comm_b1_03_expressing_opinions_agreements"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 4, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_opinion_argumentation_rhetoric"],
            "previousVocabularyReused": ["бодох", "санах", "үзэх", "санал", "баттай", "үнэн"],
            "readingObjective": "", "listeningObjective": "",
            "writingObjective": "Draft 5 statements expressing varying degrees of certainty on public transit modernization.",
            "spokenProductionObjective": "Orally state your viewpoint on remote work flexibility using calibrated stance markers.",
            "registerTarget": "Intellectual discussion and formal conversational register",
            "pragmaticTarget": "Using parenthetical stance markers to signal openness to interlocutor dialogue.",
            "prerequisiteLessonIds": ["les_b1_123_06_section_01_milestone_synthesis_checkpoint"],
            "reviewsLessonIds": ["les_b1_123_01_reported_speech_tense_shift_intro"],
            "reviewsUnitIds": ["unit_b1_123_complex_banking_electronic_funds_tr"],
            "reviewReason": "Transforms reported speech citation into personalized subjective stance framing.",
            "audioSuitability": "standard_speech_synthesis_acceptable",
            "audioPurpose": "Model parenthetical comma pauses preceding stance phrases like 'Миний хувьд авч үзвэл...'.",
            "successCriteria": [
                "Differentiates between strong conviction and tentative hypothesis markers",
                "Positions stance expressions correctly in sentence initial or medial topical slots"
            ],
            "masteryEvidence": "Produces 'Миний ажигласнаар бол энэ шийдвэр урт хугацаандаа эерэг үр дүн авчирна' accurately.",
            "recommendedExerciseModalities": ["stance_calibration_ranking", "sentence_completion", "collocation_drill"]
        },
        {
            "lessonId": "les_b1_124_02_editorial_opinion_reading",
            "unitId": uid_124, "cefrLevel": "B1", "sequenceWithinUnit": 2,
            "title": "Reading Analysis: Contemporary Mongolian Newspaper Editorials & Columns",
            "lessonType": "reading_development",
            "primaryPurpose": "Deconstruct authentic editorial opinion columns from leading Mongolian publications analyzing social reforms, youth entrepreneurship, and urban lifestyle shifts.",
            "communicativeOutcome": "Distinguish between objective factual evidence, journalistic interpretation, and editorial value judgments.",
            "objectivesIntroduced": ["obj_b1_124_02_read_opinion_editorials"],
            "objectivesPracticed": ["obj_b1_124_01_express_nuanced_stance"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_voice_causative_argument_structure"],
            "grammarReviewed": ["gram_a1_telling_time_clock_calendar"],
            "phonologyIntroduced": [], "phonologyPracticed": [], "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_03_expressing_opinions_agreements"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 4, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_opinion_argumentation_rhetoric", "lex_b1_media_digital_society"],
            "previousVocabularyReused": ["нийтлэл", "сэтгүүлч", "нийгэм", "хөгжил", "бодит байдал"],
            "readingObjective": "Read a 300-word editorial on urban green spaces and identify the author's primary thesis and 2 supporting arguments.",
            "listeningObjective": "", "writingObjective": "", "spokenProductionObjective": "",
            "registerTarget": "High literary and journalistic analytical register",
            "pragmaticTarget": "Separating subjective ideological framing from verifiable empirical data.",
            "prerequisiteLessonIds": ["les_b1_124_01_opinion_epistemic_stance_lexicon"],
            "reviewsLessonIds": ["les_b1_120_01_conflict_case_studies_reading"],
            "reviewsUnitIds": ["unit_b1_120_workplace_conflict_resolution_clari"],
            "reviewReason": "Extends analytical reading from corporate dispute cases to public socio-political editorials.",
            "audioSuitability": "standard_speech_synthesis_acceptable",
            "audioPurpose": "Narration of editorial prose with persuasive rhetorical inflection.",
            "successCriteria": [
                "Identifies the author's core ideological stance across 2 divergent opinion columns",
                "Extracts rhetorical question devices and stance collocations from texts"
            ],
            "masteryEvidence": "Identifies that the author endorses pedestrian zones while rejecting vehicular congestion fees.",
            "recommendedExerciseModalities": ["claim_evidence_mapping", "thesis_identification", "vocabulary_extraction"]
        },
        {
            "lessonId": "les_b1_124_03_civic_issues_discussion",
            "unitId": uid_124, "cefrLevel": "B1", "sequenceWithinUnit": 3,
            "title": "Discussion: Debating Urban Development & Quality of Life in Ulaanbaatar",
            "lessonType": "discussion",
            "primaryPurpose": "Participate in a structured discussion evaluating municipal initiatives such as bicycle lanes, smog reduction subsidies, and public transit overhaul.",
            "communicativeOutcome": "Articulate and defend nuanced perspectives on civic issues, building upon peers' arguments collaboratively.",
            "objectivesIntroduced": ["obj_b1_124_03_debate_civic_development"],
            "objectivesPracticed": ["obj_b1_124_01_express_nuanced_stance", "obj_b1_124_02_read_opinion_editorials"],
            "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_reported_speech_indirect_tense_shift"],
            "grammarReviewed": ["gram_a2_converb_temporal_while_khad"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_b1_parenthetical_stance_intonation"],
            "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_03_expressing_opinions_agreements"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_opinion_argumentation_rhetoric", "lex_b1_environment_geography_climate"],
            "previousVocabularyReused": ["хот", "тээвэр", "агаар", "орчин", "хөрөнгө оруулалт"],
            "readingObjective": "", "listeningObjective": "",
            "writingObjective": "",
            "spokenProductionObjective": "Contribute 4 substantive speaking turns in a roundtable discussion on urban renewal, substantiating opinions with examples.",
            "registerTarget": "Public intellectual civic debate register",
            "pragmaticTarget": "Validating others' concerns while introducing alternative urban perspectives.",
            "prerequisiteLessonIds": ["les_b1_124_02_editorial_opinion_reading"],
            "reviewsLessonIds": ["les_b1_123_05_investing_microfinance_discussion"],
            "reviewsUnitIds": ["unit_b1_123_complex_banking_electronic_funds_tr"],
            "reviewReason": "Applies debate and roundtable conventions to public policy and civic infrastructure themes.",
            "audioSuitability": "mongolian_voice_required",
            "audioPurpose": "Provide discussion questions and counter-arguments by multiple native speakers.",
            "successCriteria": [
                "Contributes multiple coherent turns integrating targeted stance formulas",
                "Substantiates viewpoints with concrete urban examples from Mongolian life"
            ],
            "masteryEvidence": "Articulates 'Миний бодлоор дугуйн замыг нэмэгдүүлснээр түгжрэл буурах боловч өвлийн цагт аюулгүй байдлыг хангах шаардлагатай' effectively.",
            "recommendedExerciseModalities": ["roundtable_debate", "stance_defense", "peer_critique"]
        },
        {
            "lessonId": "les_b1_124_04_opinion_editorial_writing",
            "unitId": uid_124, "cefrLevel": "B1", "sequenceWithinUnit": 4,
            "title": "Writing Workshop: Authoring a 150-Word Opinion Column",
            "lessonType": "writing",
            "primaryPurpose": "Compose a structured 150-word opinion piece (Нийтлэл) defending a personal stance on education, technology, or urban living with clear argumentative progression.",
            "communicativeOutcome": "Produce a well-reasoned argumentative essay featuring a clear thesis statement, supporting evidence, and balanced conclusion.",
            "objectivesIntroduced": ["obj_b1_124_04_write_opinion_editorial"],
            "objectivesPracticed": ["obj_b1_124_01_express_nuanced_stance", "obj_b1_124_02_read_opinion_editorials"],
            "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_voice_causative_argument_structure"],
            "grammarReviewed": ["gram_a1_nominal_negation_bish"],
            "phonologyIntroduced": [], "phonologyPracticed": [], "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_03_expressing_opinions_agreements"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 4, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_opinion_argumentation_rhetoric"],
            "previousVocabularyReused": ["дүгнэлт", "нотолгоо", "шалтгаан", "нөлөө", "дэмжих"],
            "readingObjective": "", "listeningObjective": "",
            "writingObjective": "Author a 150-word essay defending an educational reform proposal with thesis, 2 body arguments, and conclusion.",
            "spokenProductionObjective": "",
            "registerTarget": "Formal written analytical essay register",
            "pragmaticTarget": "Maintaining persuasive momentum without relying on emotional hyperbole.",
            "prerequisiteLessonIds": ["les_b1_124_02_editorial_opinion_reading", "les_b1_124_03_civic_issues_discussion"],
            "reviewsLessonIds": ["les_b1_114_03_formal_business_email_composition"],
            "reviewsUnitIds": ["unit_b1_114_formal_workplace_email_business_cor"],
            "reviewReason": "Transitions structured formal writing from business correspondence to public opinion essay authorship.",
            "audioSuitability": "standard_speech_synthesis_acceptable",
            "audioPurpose": "Provide audio readback of the authored editorial text.",
            "successCriteria": [
                "Produces distinct Introduction (with hook and thesis), Body, and Conclusion sections",
                "Integrates at least 3 distinct stance phrases with flawless grammatical syntax"
            ],
            "masteryEvidence": "Submits an essay opening with 'Орчин үеийн нийгэмд дижитал ур чадвар зайлшгүй шаардлагатай болж байна' and sustaining clear logic throughout.",
            "recommendedExerciseModalities": ["guided_essay_writing", "outline_expansion", "peer_review"]
        }
    ])

    # =========================================================================
    # UNIT 125: Respectful Disagreement & Constructive Rebuttal
    # Budget: (20, 14, 6, 4) across 4 lessons -> (5,4,2,1), (5,4,1,1), (6,3,2,1), (4,3,1,1)
    # =========================================================================
    uid_125 = "unit_b1_125_respectful_disagreement_constructiv"
    lessons.extend([
        {
            "lessonId": "les_b1_125_01_polite_rebuttal_formulas_lexicon",
            "unitId": uid_125, "cefrLevel": "B1", "sequenceWithinUnit": 1,
            "title": "Diplomatic Rebuttal: Concessive Openings & Counter-Argument Formulas",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Introduce rhetorical concession-and-rebuttal formulas (тийм боловч, таны хэлдэг зөв ч гэсэн, нөгөө талаас нь авч үзвэл) to dispute opposing views without causing offense.",
            "communicativeOutcome": "Formulate polite, face-saving rebuttals in professional and academic settings.",
            "objectivesIntroduced": ["obj_b1_125_01_polite_disagreement_formulas"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_b1_124_01_express_nuanced_stance"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_voice_passive_gd"],
            "grammarReviewed": ["gram_a2_converb_concessive_vch_bolovch"],
            "phonologyIntroduced": ["phono_b1_diplomatic_fall_rise_intonation"],
            "phonologyPracticed": [], "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": ["comm_b1_04_respectful_disagreement"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 4, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_opinion_argumentation_rhetoric"],
            "previousVocabularyReused": ["санал нийлэх", "эсэргүүцэх", "зөвшөөрөх", "ялгаатай", "бодит"],
            "readingObjective": "", "listeningObjective": "",
            "writingObjective": "Draft 4 polite rebuttal sentences responding to controversial business assertions.",
            "spokenProductionObjective": "Diplomatically counter a colleague's proposal while validating their good intentions.",
            "registerTarget": "High formal parliamentary and intellectual debate register",
            "pragmaticTarget": "Preserving interlocutor face by acknowledging partial validity before introducing counter-evidence.",
            "prerequisiteLessonIds": ["les_b1_124_04_opinion_editorial_writing"],
            "reviewsLessonIds": ["les_b1_120_02_diplomatic_clarification_hedging_lexicon"],
            "reviewsUnitIds": ["unit_b1_120_workplace_conflict_resolution_clari"],
            "reviewReason": "Deepens diplomatic workplace de-escalation into formal academic and rhetorical counter-argumentation.",
            "audioSuitability": "standard_speech_synthesis_acceptable",
            "audioPurpose": "Model soothing fall-rise intonation contours during concessive clauses.",
            "successCriteria": [
                "Selects appropriate concessive connectors (-вч, боловч, хэдий ч) to frame counterpoints",
                "Maintains courteous, non-aggressive register throughout rebuttal assertions"
            ],
            "masteryEvidence": "Produces 'Таны хэлж байгаа санаа маш сонирхолтой хэдий ч бодит нөхцөл байдалд хэрэгжихэд учир дутагдалтай байна' fluently.",
            "recommendedExerciseModalities": ["concession_rebuttal_drill", "phrase_matching", "sentence_restructuring"]
        },
        {
            "lessonId": "les_b1_125_02_academic_symposium_rebuttal_listening",
            "unitId": uid_125, "cefrLevel": "B1", "sequenceWithinUnit": 2,
            "title": "Acoustic Decoding: Counter-Arguments in Academic Symposiums",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop auditory listening comprehension for rapid, formal academic exchanges and conference Q&A sessions where researchers debate findings.",
            "communicativeOutcome": "Identify the core critique, empirical objections, and proposed methodological refinements in spoken symposium debates.",
            "objectivesIntroduced": ["obj_b1_125_02_comprehend_symposium_debate"],
            "objectivesPracticed": ["obj_b1_125_01_polite_disagreement_formulas"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_voice_passive_gd"],
            "grammarReviewed": ["gram_a1_polar_questions_uu_uu", "gram_a1_content_questions_be_ve"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_b1_diplomatic_fall_rise_intonation"],
            "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_04_respectful_disagreement"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 4, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_opinion_argumentation_rhetoric", "lex_b1_education_career_workplace"],
            "previousVocabularyReused": ["судалгаа", "илтгэл", "шинжлэх ухаан", "асуулт", "хариулт"],
            "readingObjective": "",
            "listeningObjective": "Listen to a 2-minute academic debate audio and identify 2 methodological flaws raised by the respondent.",
            "writingObjective": "", "spokenProductionObjective": "",
            "registerTarget": "Formal academic symposium conference register",
            "pragmaticTarget": "Distinguishing professional scientific disagreement from personal hostility in speech.",
            "prerequisiteLessonIds": ["les_b1_125_01_polite_rebuttal_formulas_lexicon"],
            "reviewsLessonIds": ["les_b1_117_04_broadcast_news_reforms_listening"],
            "reviewsUnitIds": ["unit_b1_117_passive_voice_morphosyntax_suffixes"],
            "reviewReason": "Exposes learners to high-register spoken intellectual argumentation.",
            "audioSuitability": "mongolian_voice_required",
            "audioPurpose": "Authentic conference hall acoustics with microphone amplification and multi-speaker question-and-answer exchanges.",
            "successCriteria": [
                "Identifies the speaker's main counter-claim and specific evidentiary challenge",
                "Recognizes concessive discourse markers in natural academic delivery"
            ],
            "masteryEvidence": "Correctly transcribes that the questioner contested the sample size of the economic study.",
            "recommendedExerciseModalities": ["audio_comprehension", "argument_flowcharting", "multiple_choice"]
        },
        {
            "lessonId": "les_b1_125_03_structured_oxford_debate_simulation",
            "unitId": uid_125, "cefrLevel": "B1", "sequenceWithinUnit": 3,
            "title": "Interactive Simulation: The Formal Parliamentary Debate",
            "lessonType": "debate_simulation",
            "primaryPurpose": "Engage in an interactive parliamentary-style debate defending or opposing a motion on renewable energy mandates or university tuition subsidies.",
            "communicativeOutcome": "Present opening arguments, respond to points of information, and deliver an impromptu rebuttal adhering to formal debate protocol.",
            "objectivesIntroduced": ["obj_b1_125_03_participate_formal_debate"],
            "objectivesPracticed": ["obj_b1_125_01_polite_disagreement_formulas", "obj_b1_125_02_comprehend_symposium_debate"],
            "objectivesReviewed": ["obj_b1_124_03_debate_civic_development"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_voice_passive_gd"],
            "grammarReviewed": ["gram_a2_converb_concessive_vch_bolovch"],
            "phonologyIntroduced": ["phono_b1_rhetorical_emphasis_stress"],
            "phonologyPracticed": [], "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_04_respectful_disagreement"],
            "communicativeFunctionsReviewed": ["comm_b1_03_expressing_opinions_agreements"],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_opinion_argumentation_rhetoric"],
            "previousVocabularyReused": ["мэтгэлцээн", "байр суурь", "нотолгоо", "цаг", "даргалагч"],
            "readingObjective": "",
            "listeningObjective": "Comprehend opponent arguments delivered during debate turns and formulate rapid rebuttals.",
            "writingObjective": "",
            "spokenProductionObjective": "Deliver a 2-minute structured rebuttal speech dismantling the opposing side's core economic assumptions.",
            "registerTarget": "Parliamentary debate standard register",
            "pragmaticTarget": "Using formal address formulas (Эрхэм даргалагч, хүндэт сөрөг тал) to maintain decorum.",
            "prerequisiteLessonIds": ["les_b1_125_01_polite_rebuttal_formulas_lexicon", "les_b1_125_02_academic_symposium_rebuttal_listening"],
            "reviewsLessonIds": ["les_b1_124_03_civic_issues_discussion"],
            "reviewsUnitIds": ["unit_b1_124_formulating_nuanced_personal_stance"],
            "reviewReason": "Synthesizes opinion stances and polite rebuttals in a high-stakes competitive debate format.",
            "audioSuitability": "mongolian_voice_required",
            "audioPurpose": "Prompt learner turns with native debate opponents presenting sharp counter-arguments.",
            "successCriteria": [
                "Delivers a 2-minute rebuttal addressing at least 2 points made by the opposing team",
                "Employs concessive structures and formal debate protocols without code-switching"
            ],
            "masteryEvidence": "Delivers 'Сөрөг талын дурдсан зардал өндөр гэдэгтэй санал нийлэх боловч байгаль орчны хохирлыг тооцвол сэргээгдэх эрчим хүч илүү хэмнэлттэй' eloquently.",
            "recommendedExerciseModalities": ["parliamentary_roleplay", "point_of_information_drill", "timed_rebuttal"]
        },
        {
            "lessonId": "les_b1_125_04_formal_rebuttal_letter_writing",
            "unitId": uid_125, "cefrLevel": "B1", "sequenceWithinUnit": 4,
            "title": "Writing Workshop: Authoring a Formal Letter of Counter-Argument",
            "lessonType": "writing",
            "primaryPurpose": "Compose an official 150-word letter of rebuttal responding to an unfair audit report or contested committee finding.",
            "communicativeOutcome": "Produce a dignified, evidentiary written rebuttal that disputes specific charges while preserving institutional goodwill.",
            "objectivesIntroduced": ["obj_b1_125_04_write_rebuttal_letter"],
            "objectivesPracticed": ["obj_b1_125_01_polite_disagreement_formulas"],
            "objectivesReviewed": ["obj_b1_120_04_write_reconciliation_memo"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_voice_passive_gd"],
            "grammarReviewed": ["gram_a2_converb_concessive_vch_bolovch"],
            "phonologyIntroduced": [], "phonologyPracticed": [], "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_04_respectful_disagreement"],
            "communicativeFunctionsReviewed": ["comm_b1_20_clarifying_misunderstandings"],
            "newProductiveLemmaTarget": 4, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_opinion_argumentation_rhetoric", "lex_b1_education_career_workplace"],
            "previousVocabularyReused": ["албан бичиг", "тайлбар", "үндэслэл", "гомдол гаргах", "шалгах"],
            "readingObjective": "", "listeningObjective": "",
            "writingObjective": "Draft a 150-word formal letter disputing an institutional assessment with 3 specific counter-arguments and documentary references.",
            "spokenProductionObjective": "",
            "registerTarget": "Formal administrative legalistic epistolary register",
            "pragmaticTarget": "Maintaining professional courtesy and objective evidentiary tone when contesting official judgments.",
            "prerequisiteLessonIds": ["les_b1_125_03_structured_oxford_debate_simulation"],
            "reviewsLessonIds": ["les_b1_120_04_reconciliation_memo_composition_writing"],
            "reviewsUnitIds": ["unit_b1_120_workplace_conflict_resolution_clari"],
            "reviewReason": "Synthesizes administrative writing from internal reconciliation to external formal rebuttal advocacy.",
            "audioSuitability": "standard_speech_synthesis_acceptable",
            "audioPurpose": "Provide auditory verification of written rebuttal syntax.",
            "successCriteria": [
                "Produces formal correspondence structure with salutation, point-by-point rebuttal, and request for review",
                "Uses concessive and passive grammatical constructions accurately throughout"
            ],
            "masteryEvidence": "Writes 'Аудитын дүгнэлтэд дурдсан зөрчлийг хүндэтгэн үзэж байгаа хэдий ч дараах баримтууд дутуу тусгагдсан гэж үзэж байна' flawlessly.",
            "recommendedExerciseModalities": ["guided_rebuttal_drafting", "clause_refinement", "error_correction"]
        }
    ])

    # =========================================================================
    # UNIT 126: Causal Conjunctions & Connectors: Учраас, Тул, Учир нь
    # Budget: (22, 15, 6, 4) across 5 lessons -> (6,4,2,1), (5,3,1,1), (5,4,1,1), (6,4,2,1), (0,0,0,0)
    # =========================================================================
    uid_126 = "unit_b1_126_causal_conjunctions_connectors_"
    lessons.extend([
        {
            "lessonId": "les_b1_126_01_causal_connectors_morphosyntax_intro",
            "unitId": uid_126, "cefrLevel": "B1", "sequenceWithinUnit": 1,
            "title": "Morphosyntax of Causality: Postpositional Connectors -аас/ээс учраас and тул",
            "lessonType": "grammar_introduction",
            "primaryPurpose": "Introduce the syntactic mechanisms of complex causal subordination in Mongolian: 1) Ablative participle + учраас (-сан/-х учраас), 2) Direct causal postposition тул (-сан/-х тул), and 3) Explanatory sentence-initial connector Учир нь.",
            "communicativeOutcome": "Formulate multi-clause causal sentences expressing reasons, justifications, and systemic consequences.",
            "objectivesIntroduced": ["obj_b1_126_01_form_causal_clauses"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_b1_125_01_polite_disagreement_formulas"],
            "grammarIntroduced": ["gram_b1_clause_causal_uchir_uchraas_tul"],
            "grammarPracticed": [], "grammarReviewed": ["gram_a2_modal_obligation_heregtei_yostoi", "gram_b1_voice_reciprocal_collective"],
            "phonologyIntroduced": ["phono_b1_causal_clause_boundary_pausing"],
            "phonologyPracticed": [], "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": ["comm_b1_05_making_causal_arguments"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 4, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_opinion_argumentation_rhetoric"],
            "previousVocabularyReused": ["учир", "шалтгаан", "болох", "хийх", "үүсэх", "үр дүн"],
            "readingObjective": "", "listeningObjective": "",
            "writingObjective": "Combine 6 pairs of independent clauses into complex causal sentences using учраас, тул, and учир нь.",
            "spokenProductionObjective": "Explain the causes of a project delay using both subordinate (учраас) and coordinating (учир нь) causal frames.",
            "registerTarget": "Standard formal spoken and written analytical register",
            "pragmaticTarget": "Distinguishing pre-posed cause (тул/учраас) from post-posed explanatory justification (Учир нь...).",
            "prerequisiteLessonIds": ["les_b1_125_04_formal_rebuttal_letter_writing"],
            "reviewsLessonIds": ["les_b1_124_01_opinion_epistemic_stance_lexicon"],
            "reviewsUnitIds": ["unit_b1_124_formulating_nuanced_personal_stance"],
            "reviewReason": "Equips learners with syntactic causality mechanisms to substantiate personal stances.",
            "audioSuitability": "standard_speech_synthesis_acceptable",
            "audioPurpose": "Model comma pauses after subordinate causal clauses ending in учраас and тул.",
            "successCriteria": [
                "Selects ablative participle before учраас and unmarked participle before тул",
                "Places 'Учир нь' at the start of a secondary explanatory sentence followed by genitive subject"
            ],
            "masteryEvidence": "Produces 'Цас их орсон учраас нислэг хойшлогдлоо' and 'Нислэг хойшлогдлоо. Учир нь цас их оров' accurately.",
            "recommendedExerciseModalities": ["clause_combining", "connector_selection", "syntax_transformation"]
        },
        {
            "lessonId": "les_b1_126_02_causal_syntax_contrastive_guided_practice",
            "unitId": uid_126, "cefrLevel": "B1", "sequenceWithinUnit": 2,
            "title": "Guided Practice: Precision in Causal Subordination (Тул vs Учраас vs Учир нь)",
            "lessonType": "grammar_guided_practice",
            "primaryPurpose": "Provide structured syntactic drills mastering subtle register and stylistic differences between bureaucratic тул, neutral учраас, and emphatic explanatory Учир нь.",
            "communicativeOutcome": "Skillfully choose between causal connectors based on formal register, clause weight, and discourse focus.",
            "objectivesIntroduced": ["obj_b1_126_02_master_causal_nuances"],
            "objectivesPracticed": ["obj_b1_126_01_form_causal_clauses"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_clause_causal_uchir_uchraas_tul"],
            "grammarReviewed": ["gram_b1_reported_speech_indirect_tense_shift"],
            "phonologyIntroduced": [], "phonologyPracticed": [], "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_05_making_causal_arguments"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_opinion_argumentation_rhetoric"],
            "previousVocabularyReused": ["шийдвэр", "нөхцөл", "боломж", "хууль", "журам"],
            "readingObjective": "", "listeningObjective": "",
            "writingObjective": "Rewrite 6 casual causal sentences into formal administrative prose using -х тул.",
            "spokenProductionObjective": "Deliver 3 rapid spoken justifications for strategic decisions using varying causal connectors.",
            "registerTarget": "Formal administrative and academic register",
            "pragmaticTarget": "Using тул in administrative decrees to signal institutional necessity.",
            "prerequisiteLessonIds": ["les_b1_126_01_causal_connectors_morphosyntax_intro"],
            "reviewsLessonIds": ["les_b1_126_01_causal_connectors_morphosyntax_intro"],
            "reviewsUnitIds": ["unit_b1_126_causal_conjunctions_connectors_"],
            "reviewReason": "Consolidates causal morphosyntax through intensive contrastive sentence manipulation.",
            "audioSuitability": "standard_speech_synthesis_acceptable",
            "audioPurpose": "Synthesize formal causal utterances contrasting oral and written rhythm.",
            "successCriteria": [
                "Consistently applies -х тул in official notices and business memoranda",
                "Integrates 'Учир нь' correctly to open independent explanatory sentences"
            ],
            "masteryEvidence": "Converts 'Бид яарч байгаа учраас хурал эхэлье' into 'Цаг хугацаа хомс буй тул хурлыг эхлүүлье' accurately.",
            "recommendedExerciseModalities": ["sentence_transformation", "register_matching", "error_correction"]
        },
        {
            "lessonId": "les_b1_126_03_socio_economic_causality_reading",
            "unitId": uid_126, "cefrLevel": "B1", "sequenceWithinUnit": 3,
            "title": "Reading Analysis: Socio-Economic Whitepapers on Demographic Migration",
            "lessonType": "reading_development",
            "primaryPurpose": "Deconstruct authentic sociological reports examining the causes of rural-to-urban migration from Western aimags to Ulaanbaatar.",
            "communicativeOutcome": "Extract cause-and-effect chains, economic push/pull factors, and policy recommendations from analytical texts.",
            "objectivesIntroduced": ["obj_b1_126_03_read_causal_analyses"],
            "objectivesPracticed": ["obj_b1_126_01_form_causal_clauses"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_clause_causal_uchir_uchraas_tul"],
            "grammarReviewed": ["gram_a2_modal_obligation_heregtei_yostoi"],
            "phonologyIntroduced": [], "phonologyPracticed": [], "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_05_making_causal_arguments"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 4, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_opinion_argumentation_rhetoric", "lex_b1_environment_geography_climate"],
            "previousVocabularyReused": ["шилжилт хөдөлгөөн", "хөдөө орон нутаг", "ажлын байр", "боловсрол", "хүн ам"],
            "readingObjective": "Read an excerpt from a national statistical report and diagram 3 economic causes and 2 social effects of urbanization.",
            "listeningObjective": "", "writingObjective": "", "spokenProductionObjective": "",
            "registerTarget": "Formal sociological and statistical research register",
            "pragmaticTarget": "Distinguishing correlation from direct causation in formal Mongolian prose.",
            "prerequisiteLessonIds": ["les_b1_126_01_causal_connectors_morphosyntax_intro"],
            "reviewsLessonIds": ["les_b1_124_02_editorial_opinion_reading"],
            "reviewsUnitIds": ["unit_b1_124_formulating_nuanced_personal_stance"],
            "reviewReason": "Deepens analytical reading from journalistic editorials to evidence-based sociological whitepapers.",
            "audioSuitability": "standard_speech_synthesis_acceptable",
            "audioPurpose": "Audio narration of sociological report passages.",
            "successCriteria": [
                "Identifies cause clauses marked by тул and учраас across 3 statistical excerpts",
                "Maps multi-tier cause-and-effect relationships into a visual causal chain"
            ],
            "masteryEvidence": "Identifies that 'Ажлын байр дутмаг байгаагаас шалтгаалан залуучууд хот руу шилжиж байна' identifies the primary economic driver.",
            "recommendedExerciseModalities": ["causal_chain_diagramming", "information_extraction", "multiple_choice"]
        },
        {
            "lessonId": "les_b1_126_04_economic_roundtable_listening",
            "unitId": uid_126, "cefrLevel": "B1", "sequenceWithinUnit": 4,
            "title": "Acoustic Comprehension: Television Panel on Inflationary Pressures & Supply Chains",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop listening comprehension for complex macroeconomic roundtable broadcasts where economists explain currency fluctuations, fuel tariffs, and consumer price indices.",
            "communicativeOutcome": "Track spoken causal reasoning explaining why prices fluctuate and what monetary interventions are projected.",
            "objectivesIntroduced": ["obj_b1_126_04_comprehend_economic_causality"],
            "objectivesPracticed": ["obj_b1_126_01_form_causal_clauses"],
            "objectivesReviewed": ["obj_b1_126_03_read_causal_analyses"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_clause_causal_uchir_uchraas_tul"],
            "grammarReviewed": ["gram_b1_reported_speech_indirect_tense_shift"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_b1_causal_clause_boundary_pausing"],
            "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_05_making_causal_arguments"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 4, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_opinion_argumentation_rhetoric", "lex_b1_money_consumerism"],
            "previousVocabularyReused": ["инфляци", "үнэ өсөх", "ханш", "шатахуун", "хэрэглээний сагс"],
            "readingObjective": "",
            "listeningObjective": "Listen to a 2.5-minute televised economic debate and transcribe the 3 root causes of inflation identified by the lead analyst.",
            "writingObjective": "", "spokenProductionObjective": "",
            "registerTarget": "High-register broadcast analytical panel discussion",
            "pragmaticTarget": "Tracking rapid spoken causal shifts where economists use nested subordinate clauses.",
            "prerequisiteLessonIds": ["les_b1_126_02_causal_syntax_contrastive_guided_practice", "les_b1_126_03_socio_economic_causality_reading"],
            "reviewsLessonIds": ["les_b1_117_04_broadcast_news_reforms_listening"],
            "reviewsUnitIds": ["unit_b1_117_passive_voice_morphosyntax_suffixes"],
            "reviewReason": "Expands broadcast listening from news bulletins to unscripted expert panel debates.",
            "audioSuitability": "mongolian_voice_required",
            "audioPurpose": "Authentic studio broadcast recording featuring two economists with fast-paced natural analytical delivery.",
            "successCriteria": [
                "Identifies the primary and secondary causal factors cited for price inflation",
                "Distinguishes between domestic supply constraints and imported external cost pressures"
            ],
            "masteryEvidence": "Summarizes accurately that international transport bottlenecks and rising oil prices were identified as prime inflation catalysts.",
            "recommendedExerciseModalities": ["audio_note_taking", "cause_effect_matching", "summary_completion"]
        },
        {
            "lessonId": "les_b1_126_05_explaining_systemic_causes_spoken",
            "unitId": uid_126, "cefrLevel": "B1", "sequenceWithinUnit": 5,
            "title": "Spoken Production: Delivering an Analytical Briefing on Root Causes",
            "lessonType": "spoken_production",
            "primaryPurpose": "Deliver a 2-minute oral analytical briefing diagnosing why a major project exceeded budget or failed to meet deadlines, substantiating findings with causal connectors.",
            "communicativeOutcome": "Present a structured root-cause analysis orally to an audience of supervisors or stakeholders.",
            "objectivesIntroduced": ["obj_b1_126_05_deliver_causal_briefing"],
            "objectivesPracticed": ["obj_b1_126_01_form_causal_clauses", "obj_b1_126_02_master_causal_nuances"],
            "objectivesReviewed": ["obj_b1_126_04_comprehend_economic_causality"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_clause_causal_uchir_uchraas_tul"],
            "grammarReviewed": ["gram_a2_modal_obligation_heregtei_yostoi"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_b1_causal_clause_boundary_pausing"],
            "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_05_making_causal_arguments"],
            "communicativeFunctionsReviewed": ["comm_b1_19_describing_accidents_unintended_actions"],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_b1_opinion_argumentation_rhetoric", "lex_b1_education_career_workplace"],
            "previousVocabularyReused": ["шалтгаан", "үр дагавар", "дүгнэлт", "төсөв", "хэтрэх"],
            "readingObjective": "", "listeningObjective": "", "writingObjective": "",
            "spokenProductionObjective": "Deliver a 2-minute oral briefing presenting a 3-step causal breakdown of an operational delay.",
            "registerTarget": "Formal professional analytical presentation register",
            "pragmaticTarget": "Focusing objectively on systemic failure points rather than interpersonal finger-pointing.",
            "prerequisiteLessonIds": ["les_b1_126_03_socio_economic_causality_reading", "les_b1_126_04_economic_roundtable_listening"],
            "reviewsLessonIds": ["les_b1_119_05_reporting_operational_accidents_spoken"],
            "reviewsUnitIds": ["unit_b1_119_intensive_completive_aspect_suffix_"],
            "reviewReason": "Elevates operational accident reports to structured systemic causal analyses.",
            "audioSuitability": "mongolian_voice_required",
            "audioPurpose": "Provide benchmark model of an executive analytical causal briefing.",
            "successCriteria": [
                "Delivers a coherent 2-minute oral presentation using at least 3 distinct causal connectors",
                "Structures argument logically from underlying condition to direct trigger to final outcome"
            ],
            "masteryEvidence": "Speaks for 2 minutes stating 'Ханшийн өсөлтөөс шалтгаалан импортын түүхий эдийн үнэ нэмэгдсэн тул төслийн төсөв 15 хувиар хэтэрсэн юм' fluently.",
            "recommendedExerciseModalities": ["causal_presentation_rubric", "timed_speech", "peer_critique"]
        }
    ])

    return lessons
