"""
B1 Section 01: Workplace Communication, Employment & Professional Processes
Units 112 - 123 (12 Units, 55 Lessons)
Authoritative pedagogical specifications for CEFR B1 Threshold.
"""

from typing import List, Dict, Any

def get_b1_section_01_lessons() -> List[Dict[str, Any]]:
    lessons: List[Dict[str, Any]] = []

    # =========================================================================
    # UNIT 112: Job Searching, CV Preparation & Qualifications
    # Theme: Formulating educational history and professional competencies
    # Grammar Intro: gram_b1_noun_derivation_abstract_dal_laga
    # Grammar Reinf: gram_a1_case_nominative_unmarked, gram_a1_case_genitive_possession
    # Functions: comm_b1_24_discussing_education_career_path
    # Budget: PL=22, RL=15, PE=6, RE=4 (5 Lessons: (6,4,2,1), (5,3,1,1), (6,4,2,1), (5,4,1,1), (0,0,0,0))
    # =========================================================================
    uid_112 = "unit_b1_112_job_searching_cv_preparation_qualif"
    lessons.extend([
        {
            "lessonId": "les_b1_112_01_abstract_noun_derivation_intro",
            "unitId": uid_112, "cefrLevel": "B1", "sequenceWithinUnit": 1,
            "title": "Abstract Nouns in the Workplace: Nominalizers -дал/-дэл and -лга/-лгэ",
            "lessonType": "grammar_introduction",
            "primaryPurpose": "Master the morphological derivation of abstract corporate concepts and institutional nouns from verb roots using -дал⁴ and -лга⁴.",
            "communicativeOutcome": "Formulate and understand abstract professional nouns such as хариуцлага (responsibility), амжилт/боловсрол, ажиллах нөхцөл, and боломж.",
            "objectivesIntroduced": ["obj_b1_112_01_derive_abstract_nouns_workplace"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_a2_101_01_describe_career_milestones"],
            "grammarIntroduced": ["gram_b1_noun_derivation_abstract_dal_laga"],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_nominative_unmarked", "gram_a1_case_genitive_possession"],
            "phonologyIntroduced": ["phono_b1_abstract_suffix_vowel_harmony"],
            "phonologyPracticed": ["phono_a2_long_vowels_corporate"], "phonologyReviewed": ["phono_a1_vowel_harmony_basic"],
            "communicativeFunctionsIntroduced": ["comm_b1_24_discussing_education_career_path"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": ["comm_a2_15_describing_past_employment"],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 4, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_education_career_workplace"],
            "previousVocabularyReused": ["ажил", "мэргэжил", "сургууль", "их сургууль", "төгсөх", "хүсэх"],
            "readingObjective": "Identify abstract derived nouns in authentic job specifications outlining institutional duties.",
            "listeningObjective": "",
            "writingObjective": "Transform 6 verbal roots into abstract institutional nouns correctly applying vowel harmony.",
            "spokenProductionObjective": "Explain your key work responsibilities using abstract nouns ending in -лга and -дал.",
            "registerTarget": "Formal written and spoken corporate register",
            "pragmaticTarget": "Using formal nominalizations to convey professional authority rather than informal descriptive verbs.",
            "prerequisiteLessonIds": ["les_a2_111_06_waystage_a2_exit_milestone_benchmark_checkpoint"],
            "reviewsLessonIds": ["les_a2_101_02_biographical_chronology_milestones_lexicon"],
            "reviewsUnitIds": ["unit_a2_101_personal_history_capstone_autobiogr"],
            "reviewReason": "Bridges A2 milestone descriptions into formal B1 professional qualification discourse.",
            "audioSuitability": "standard_speech_synthesis_acceptable",
            "audioPurpose": "Model vowel harmony allomorphs for -дал/-дэл/-дол/-дөл and -лга/-лгэ/-лго/-лгө.",
            "successCriteria": [
                "Accurately attaches -дал⁴ or -лга⁴ to verbal stems to form abstract nouns",
                "Uses derived nouns appropriately as subjects and objects in workplace descriptions"
            ],
            "masteryEvidence": "Produces sentences like 'Миний гол хариуцлага бол төслийн төлөвлөлтийг хангах явдал юм' without morphological errors.",
            "recommendedExerciseModalities": ["suffix_selection", "word_transformation", "sentence_completion"]
        },
        {
            "lessonId": "les_b1_112_02_mongolian_cv_decoding_reading",
            "unitId": uid_112, "cefrLevel": "B1", "sequenceWithinUnit": 2,
            "title": "Deciphering Mongolian CVs & Professional Job Postings",
            "lessonType": "reading_development",
            "primaryPurpose": "Analyze the structural organization, standard headings, and qualification requirements of authentic Mongolian curriculum vitae and vacancy announcements.",
            "communicativeOutcome": "Extract key job requirements, required competencies, degree qualifications, and experience prerequisites from recruitment notices.",
            "objectivesIntroduced": ["obj_b1_112_02_read_mongolian_cv_postings"],
            "objectivesPracticed": ["obj_b1_112_01_derive_abstract_nouns_workplace"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_noun_derivation_abstract_dal_laga"],
            "grammarReviewed": ["gram_a1_case_genitive_possession"],
            "phonologyIntroduced": [], "phonologyPracticed": [], "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_24_discussing_education_career_path"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_education_career_workplace"],
            "previousVocabularyReused": ["диплом", "боловсрол", "мэргэжил", "туршлага", "байгууллага"],
            "readingObjective": "Skim and scan authentic job notices to extract required qualifications, language proficiency, and duties.",
            "listeningObjective": "",
            "writingObjective": "",
            "spokenProductionObjective": "",
            "registerTarget": "Formal administrative Mongolian vacancy style",
            "pragmaticTarget": "Distinguishing essential requirements (тавигдах шаардлага) from preferred assets (давуу тал).",
            "prerequisiteLessonIds": ["les_b1_112_01_abstract_noun_derivation_intro"],
            "reviewsLessonIds": ["les_b1_112_01_abstract_noun_derivation_intro"],
            "reviewsUnitIds": ["unit_b1_112_job_searching_cv_preparation_qualif"],
            "reviewReason": "Applies freshly acquired abstract nominal vocabulary to authentic written hiring texts.",
            "audioSuitability": "standard_speech_synthesis_acceptable",
            "audioPurpose": "Provide audio pronunciation of specialized occupational titles and professional jargon.",
            "successCriteria": [
                "Identifies required education level and years of experience across 3 vacancy profiles",
                "Matches applicant credentials to vacancy requirements accurately"
            ],
            "masteryEvidence": "Identifies that a vacancy requires 'хүний нөөцийн чиглэлээр 3-аас доошгүй жил ажилласан туршлага' from contract text.",
            "recommendedExerciseModalities": ["document_analysis", "information_extraction", "matching"]
        },
        {
            "lessonId": "les_b1_112_03_competency_lexicon_qualifications",
            "unitId": uid_112, "cefrLevel": "B1", "sequenceWithinUnit": 3,
            "title": "Professional Competency Lexicon: Skills, Credentials & Attributes",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Acquire core professional vocabulary to articulate educational credentials, technical capabilities, leadership skills, and career achievements.",
            "communicativeOutcome": "Formulate a personalized profile of professional skills, certifications, and workplace competencies in Mongolian.",
            "objectivesIntroduced": ["obj_b1_112_03_express_workplace_competencies"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_b1_112_01_derive_abstract_nouns_workplace"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_noun_derivation_abstract_dal_laga"],
            "grammarReviewed": ["gram_a1_case_nominative_unmarked"],
            "phonologyIntroduced": ["phono_b1_consonant_clusters_loanwords"],
            "phonologyPracticed": [], "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_24_discussing_education_career_path"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 4, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_education_career_workplace"],
            "previousVocabularyReused": ["мэдэх", "чадах", "хэлтэс", "захирал", "мэргэжилтэн"],
            "readingObjective": "",
            "listeningObjective": "",
            "writingObjective": "Draft 5 bullet points characterizing personal technical competencies using newly acquired professional lexicon.",
            "spokenProductionObjective": "State three core professional strengths and one technical credential during a profile introduction.",
            "registerTarget": "Standard professional self-presentation register",
            "pragmaticTarget": "Projecting competence without appearing boastful, balancing modesty with clear capability statements.",
            "prerequisiteLessonIds": ["les_b1_112_01_abstract_noun_derivation_intro"],
            "reviewsLessonIds": ["les_b1_112_01_abstract_noun_derivation_intro"],
            "reviewsUnitIds": ["unit_b1_112_job_searching_cv_preparation_qualif"],
            "reviewReason": "Deepens vocabulary building on the morphological nominalization foundation.",
            "audioSuitability": "standard_speech_synthesis_acceptable",
            "audioPurpose": "Pronounce professional compound terms and modern workplace loanwords.",
            "successCriteria": [
                "Selects appropriate competency adjectives and nouns to describe work capabilities",
                "Pairs qualifications with evidence of prior employment"
            ],
            "masteryEvidence": "Articulates 'Мэдээллийн технологийн чиглэлээр төсөл удирдах бүрэн чадвартай' with correct case agreement.",
            "recommendedExerciseModalities": ["vocabulary_association", "collocation_drill", "self_assessment_matching"]
        },
        {
            "lessonId": "les_b1_112_04_authoring_professional_cv_writing",
            "unitId": uid_112, "cefrLevel": "B1", "sequenceWithinUnit": 4,
            "title": "Writing Workshop: Authoring a Professional Mongolian Resume",
            "lessonType": "writing",
            "primaryPurpose": "Compose a structured 1-page Mongolian CV comprising personal info, education chronology, career experience, and core competencies.",
            "communicativeOutcome": "Produce a well-formatted, culturally standard Mongolian resume suitable for submission to local and international employers.",
            "objectivesIntroduced": ["obj_b1_112_04_write_structured_cv"],
            "objectivesPracticed": ["obj_b1_112_01_derive_abstract_nouns_workplace", "obj_b1_112_03_express_workplace_competencies"],
            "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_noun_derivation_abstract_dal_laga"],
            "grammarReviewed": ["gram_a1_case_genitive_possession", "gram_a1_case_dative_locative_temporal"],
            "phonologyIntroduced": [], "phonologyPracticed": [], "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_24_discussing_education_career_path"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 4, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_education_career_workplace"],
            "previousVocabularyReused": ["төрсөн он", "хаяг", "утас", "имэйл", "боловсрол", "ажлын туршлага"],
            "readingObjective": "",
            "listeningObjective": "",
            "writingObjective": "Draft a complete 4-section Mongolian resume adhering to standard typographic and structural layout conventions.",
            "spokenProductionObjective": "",
            "registerTarget": "Formal written administrative standard",
            "pragmaticTarget": "Adhering to standard Mongolian administrative formatting conventions for employment documentation.",
            "prerequisiteLessonIds": ["les_b1_112_02_mongolian_cv_decoding_reading", "les_b1_112_03_competency_lexicon_qualifications"],
            "reviewsLessonIds": ["les_b1_112_02_mongolian_cv_decoding_reading"],
            "reviewsUnitIds": ["unit_b1_112_job_searching_cv_preparation_qualif"],
            "reviewReason": "Synthesizes reading analysis and vocabulary targets into direct written production.",
            "audioSuitability": "standard_speech_synthesis_acceptable",
            "audioPurpose": "Provide auditory reinforcement of written cv section titles and key descriptors.",
            "successCriteria": [
                "Constructs all 4 required CV sections with correct terminology and dates",
                "Employs abstract nominalizations in experience descriptions without grammatical errors"
            ],
            "masteryEvidence": "Drafts a complete CV draft containing 'Боловсрол', 'Ажлын туршлага', and 'Ур чадвар' sections accurately.",
            "recommendedExerciseModalities": ["document_construction", "section_organization", "error_correction"]
        },
        {
            "lessonId": "les_b1_112_05_career_trajectory_pitch_spoken",
            "unitId": uid_112, "cefrLevel": "B1", "sequenceWithinUnit": 5,
            "title": "Spoken Production: Pitching Your Career Trajectory & Ambitions",
            "lessonType": "spoken_production",
            "primaryPurpose": "Deliver a coherent, sustained 2-minute oral monologue presenting educational background, key achievements, and future career direction.",
            "communicativeOutcome": "Present yourself professionally to a recruitment panel or networking contact with fluent delivery and structured discourse.",
            "objectivesIntroduced": ["obj_b1_112_05_deliver_career_pitch"],
            "objectivesPracticed": ["obj_b1_112_03_express_workplace_competencies", "obj_b1_112_04_write_structured_cv"],
            "objectivesReviewed": ["obj_b1_112_01_derive_abstract_nouns_workplace"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_noun_derivation_abstract_dal_laga"],
            "grammarReviewed": ["gram_a1_case_nominative_unmarked", "gram_a1_case_genitive_possession"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_b1_consonant_clusters_loanwords"],
            "phonologyReviewed": ["phono_a2_long_vowels_corporate"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_24_discussing_education_career_path"],
            "communicativeFunctionsReviewed": ["comm_a2_15_describing_past_employment"],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_b1_education_career_workplace"],
            "previousVocabularyReused": ["боловсрол", "хариуцлага", "туршлага", "зорилго", "төсөл"],
            "readingObjective": "",
            "listeningObjective": "",
            "writingObjective": "",
            "spokenProductionObjective": "Deliver a continuous 2-minute self-introduction outlining career milestones, key skills, and current professional aims.",
            "registerTarget": "Formal professional spoken presentation register",
            "pragmaticTarget": "Maintaining confident eye contact, clear cadence, and professional tone in oral pitch.",
            "prerequisiteLessonIds": ["les_b1_112_03_competency_lexicon_qualifications", "les_b1_112_04_authoring_professional_cv_writing"],
            "reviewsLessonIds": ["les_b1_112_04_authoring_professional_cv_writing"],
            "reviewsUnitIds": ["unit_b1_112_job_searching_cv_preparation_qualif"],
            "reviewReason": "Converts written CV content into active, persuasive spoken delivery.",
            "audioSuitability": "mongolian_voice_required",
            "audioPurpose": "Provide natural native speaker model of a professional career pitch.",
            "successCriteria": [
                "Speaks for 90-120 seconds continuously without disruptive hesitations",
                "Integrates education, work history, and aspirations using chronological discourse markers"
            ],
            "masteryEvidence": "Delivers an oral presentation opening with 'Би МУИС-ийг төгссөн бөгөөд сүүлийн гурван жилд...' maintaining steady pacing.",
            "recommendedExerciseModalities": ["oral_presentation_planning", "timed_monologue", "peer_critique"]
        }
    ])

    # =========================================================================
    # UNIT 113: Job Interview Strategies & Answering Tough Questions
    # Theme: Presenting professional strengths and answering behavioral questions
    # Grammar Intro: gram_b1_verb_derivation_denominal_lakh
    # Grammar Reinf: gram_a1_content_questions_be_ve, gram_a1_case_dative_locative_temporal,
    #                gram_a1_verb_tense_past_perfective_san, gram_a2_numerals_ordinal,
    #                gram_b1_noun_derivation_abstract_dal_laga
    # Functions: comm_b1_09_participating_job_interview
    # Budget: PL=22, RL=15, PE=6, RE=4 (5 Lessons: (6,4,2,1), (5,4,1,1), (5,3,1,1), (6,4,2,1), (0,0,0,0))
    # =========================================================================
    uid_113 = "unit_b1_113_job_interview_strategies_answering_t"
    lessons.extend([
        {
            "lessonId": "les_b1_113_01_interview_action_verbs_lexicon",
            "unitId": uid_113, "cefrLevel": "B1", "sequenceWithinUnit": 1,
            "title": "Interview Action Lexicon: Operational Verbs & Behavioral Descriptors",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Acquire dynamic operational verbs and behavioral terminology required to explain workplace challenges, problem resolution, and leadership initiatives.",
            "communicativeOutcome": "Describe specific past job actions and achievements using precise professional action verbs.",
            "objectivesIntroduced": ["obj_b1_113_01_interview_action_lexicon"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_b1_112_03_express_workplace_competencies"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_noun_derivation_abstract_dal_laga"],
            "grammarReviewed": ["gram_a1_verb_tense_past_perfective_san"],
            "phonologyIntroduced": ["phono_b1_stress_denominal_verbs"],
            "phonologyPracticed": [], "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": ["comm_b1_09_participating_job_interview"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 4, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_education_career_workplace"],
            "previousVocabularyReused": ["ажиллах", "хийх", "төлөвлөх", "шийдэх", "хянах"],
            "readingObjective": "",
            "listeningObjective": "",
            "writingObjective": "Compose 4 sentences describing past achievements using behavioral action verbs in past perfective tense.",
            "spokenProductionObjective": "Explain how you solved a challenging situation at work using operational action verbs.",
            "registerTarget": "Formal professional spoken register",
            "pragmaticTarget": "Using active, assertive verbs to claim personal agency in team achievements.",
            "prerequisiteLessonIds": ["les_b1_112_05_career_trajectory_pitch_spoken"],
            "reviewsLessonIds": ["les_b1_112_03_competency_lexicon_qualifications"],
            "reviewsUnitIds": ["unit_b1_112_job_searching_cv_preparation_qualif"],
            "reviewReason": "Builds on general competency lexicon by introducing dynamic behavioral action verbs.",
            "audioSuitability": "standard_speech_synthesis_acceptable",
            "audioPurpose": "Model proper verb stress and pronunciation of multi-syllable operational terms.",
            "successCriteria": [
                "Uses operational verbs (зохион байгуулах, сайжруулах, хэрэгжүүлэх) in appropriate contexts",
                "Pairs verbs correctly with direct and indirect workplace complements"
            ],
            "masteryEvidence": "Explains 'Би борлуулалтын системийг шинэчлэн зохион байгуулж, үр дүнг хорин хувиар өсгөсөн' accurately.",
            "recommendedExerciseModalities": ["verb_noun_collocation", "sentence_completion", "flashcard_matching"]
        },
        {
            "lessonId": "les_b1_113_02_denominal_verb_derivation_intro",
            "unitId": uid_113, "cefrLevel": "B1", "sequenceWithinUnit": 2,
            "title": "Verbalizing Nouns: Denominal Derivation Suffix -лах/-лэх/-лох/-лөх",
            "lessonType": "grammar_introduction",
            "primaryPurpose": "Introduce the productive denominal verbalizer suffix -лах⁴ to convert nouns into operational workplace action verbs.",
            "communicativeOutcome": "Form and apply denominal verbs such as ажиллах, төлөвлөх, баталгаажуулах, and удирдах in interview responses.",
            "objectivesIntroduced": ["obj_b1_113_02_derive_denominal_verbs"],
            "objectivesPracticed": ["obj_b1_113_01_interview_action_lexicon"],
            "objectivesReviewed": ["obj_b1_112_01_derive_abstract_nouns_workplace"],
            "grammarIntroduced": ["gram_b1_verb_derivation_denominal_lakh"],
            "grammarPracticed": ["gram_b1_noun_derivation_abstract_dal_laga"],
            "grammarReviewed": ["gram_a1_content_questions_be_ve", "gram_a1_case_dative_locative_temporal"],
            "phonologyIntroduced": ["phono_b1_denominal_vowel_harmony"],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_vowel_harmony_basic"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_09_participating_job_interview"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 4, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_education_career_workplace"],
            "previousVocabularyReused": ["ажил", "төлөвлөгөө", "баталгаа", "алба", "хурал"],
            "readingObjective": "",
            "listeningObjective": "",
            "writingObjective": "Transform 8 workplace nouns into denominal verbs and construct sample sentences showing action.",
            "spokenProductionObjective": "Explain your daily professional duties using derived denominal verbs.",
            "registerTarget": "Standard professional interview register",
            "pragmaticTarget": "Using derived denominal verbs to describe procedural steps systematically.",
            "prerequisiteLessonIds": ["les_b1_113_01_interview_action_verbs_lexicon"],
            "reviewsLessonIds": ["les_b1_112_01_abstract_noun_derivation_intro"],
            "reviewsUnitIds": ["unit_b1_112_job_searching_cv_preparation_qualif"],
            "reviewReason": "Contrasts abstract nominalization (-дал/-лга) with denominal verbalization (-лах).",
            "audioSuitability": "standard_speech_synthesis_acceptable",
            "audioPurpose": "Illustrate vowel harmony changes across masculine and feminine noun roots.",
            "successCriteria": [
                "Correctly derives verbs using -лах, -лэх, -лох, or -лөх based on stem vowel quality",
                "Integrates derived verbs into complex SOV interview clauses"
            ],
            "masteryEvidence": "Transforms төлөвлөгөө into төлөвлөх and uses it in 'Бид дараа сарын ажлыг урьдчилан төлөвлөдөг'.",
            "recommendedExerciseModalities": ["morphology_drill", "sentence_transformation", "cloze_test"]
        },
        {
            "lessonId": "les_b1_113_03_panel_interview_questions_listening",
            "unitId": uid_113, "cefrLevel": "B1", "sequenceWithinUnit": 3,
            "title": "Acoustic Decoding: Multi-Part Behavioral Interview Questions",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop auditory listening comprehension for multi-part, complex behavioral questions posed by Mongolian interview panels.",
            "communicativeOutcome": "Understand the core premise, implicit expectations, and specific examples requested in rapid interview questions.",
            "objectivesIntroduced": ["obj_b1_113_03_comprehend_interview_questions"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_b1_113_01_interview_action_lexicon"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_verb_derivation_denominal_lakh"],
            "grammarReviewed": ["gram_a1_content_questions_be_ve", "gram_a2_numerals_ordinal"],
            "phonologyIntroduced": ["phono_b1_intonation_complex_questions"],
            "phonologyPracticed": [], "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_09_participating_job_interview"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_education_career_workplace"],
            "previousVocabularyReused": ["асуулт", "хариулах", "туршлага", "бэрхшээл", "хамт олон"],
            "readingObjective": "",
            "listeningObjective": "Extract key question components from 4 recorded authentic panel interview prompts.",
            "writingObjective": "",
            "spokenProductionObjective": "",
            "registerTarget": "Formal corporate HR questioning register",
            "pragmaticTarget": "Identifying the underlying competency being evaluated behind indirect behavioral questions.",
            "prerequisiteLessonIds": ["les_b1_113_01_interview_action_verbs_lexicon", "les_b1_113_02_denominal_verb_derivation_intro"],
            "reviewsLessonIds": ["les_b1_113_01_interview_action_verbs_lexicon"],
            "reviewsUnitIds": ["unit_b1_113_job_interview_strategies_answering_t"],
            "reviewReason": "Exposes learners to natural spoken question cadences incorporating targeted action verbs.",
            "audioSuitability": "mongolian_voice_required",
            "audioPurpose": "Authentic HR panel dialogue with varied adult speakers and realistic corporate acoustic ambiance.",
            "successCriteria": [
                "Identifies the two distinct components in a multi-part behavioral question",
                "Recognizes question markers (-в уу, юу байсан бэ, яаж шийдсэн бэ) in natural speed speech"
            ],
            "masteryEvidence": "Accurately transcribes that the interviewer asked both about the project obstacle and how team consensus was reached.",
            "recommendedExerciseModalities": ["audio_comprehension", "question_decomposition", "multiple_choice"]
        },
        {
            "lessonId": "les_b1_113_04_simulated_high_stakes_interview",
            "unitId": uid_113, "cefrLevel": "B1", "sequenceWithinUnit": 4,
            "title": "Interactive Simulation: The Formal Job Interview",
            "lessonType": "interview_simulation",
            "primaryPurpose": "Engage in a full multi-turn simulated job interview handling challenging behavioral, technical, and salary expectations questions.",
            "communicativeOutcome": "Respond fluently and diplomatically to tough interviewer prompts, structuring responses using the STAR method (Нөхцөл байдал, Даалгавар, Үйлдэл, Үр дүн).",
            "objectivesIntroduced": ["obj_b1_113_04_conduct_job_interview"],
            "objectivesPracticed": ["obj_b1_113_01_interview_action_lexicon", "obj_b1_113_02_derive_denominal_verbs", "obj_b1_113_03_comprehend_interview_questions"],
            "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_verb_derivation_denominal_lakh"],
            "grammarReviewed": ["gram_a1_verb_tense_past_perfective_san", "gram_a1_case_dative_locative_temporal"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_b1_stress_denominal_verbs"],
            "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_09_participating_job_interview"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 4, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_b1_education_career_workplace"],
            "previousVocabularyReused": ["цалин", "нөхцөл", "боломж", "туршлага", "амжилт"],
            "readingObjective": "",
            "listeningObjective": "Comprehend interviewer follow-up questions during real-time interactive turn-taking.",
            "writingObjective": "",
            "spokenProductionObjective": "Deliver 4 structured spoken responses answering behavioral interview prompts with complete syntactic coherence.",
            "registerTarget": "High-formality corporate interview register",
            "pragmaticTarget": "Using polite indirect phrasing when discussing compensation and personal limitations.",
            "prerequisiteLessonIds": ["les_b1_113_02_denominal_verb_derivation_intro", "les_b1_113_03_panel_interview_questions_listening"],
            "reviewsLessonIds": ["les_b1_113_03_panel_interview_questions_listening"],
            "reviewsUnitIds": ["unit_b1_113_job_interview_strategies_answering_t"],
            "reviewReason": "Synthesizes listening comprehension and lexical generation in an interactive simulation.",
            "audioSuitability": "mongolian_voice_required",
            "audioPurpose": "Prompt learner turns with native interviewer voices asking follow-up challenges.",
            "successCriteria": [
                "Answers 4 consecutive interview questions adhering to structured discourse conventions",
                "Employs past perfective and denominal verbs accurately to narrate past problem solving"
            ],
            "masteryEvidence": "Successfully navigates 'Та өмнөх ажлаасаа яагаад гарсан бэ?' using constructive, professional framing.",
            "recommendedExerciseModalities": ["interactive_roleplay", "branching_dialogue", "oral_response_recording"]
        },
        {
            "lessonId": "les_b1_113_05_interview_performance_debrief_discussion",
            "unitId": uid_113, "cefrLevel": "B1", "sequenceWithinUnit": 5,
            "title": "Discussion & Strategy: Evaluating Interview Performance & Negotiating Terms",
            "lessonType": "discussion",
            "primaryPurpose": "Debrief interview outcomes, evaluate candidate responses, and discuss strategic nuances of job offer negotiations in Mongolian culture.",
            "communicativeOutcome": "Critique sample candidate answers, articulate strengths and weaknesses, and formulate strategic follow-up inquiries.",
            "objectivesIntroduced": ["obj_b1_113_05_evaluate_interview_tactics"],
            "objectivesPracticed": ["obj_b1_113_04_conduct_job_interview"],
            "objectivesReviewed": ["obj_b1_112_01_derive_abstract_nouns_workplace"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_b1_verb_derivation_denominal_lakh"],
            "grammarReviewed": ["gram_b1_noun_derivation_abstract_dal_laga"],
            "phonologyIntroduced": [], "phonologyPracticed": [], "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_b1_09_participating_job_interview"],
            "communicativeFunctionsReviewed": ["comm_b1_24_discussing_education_career_path"],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_b1_education_career_workplace"],
            "previousVocabularyReused": ["давуу тал", "сул тал", "шийдвэр", "хариу", "гэрээ"],
            "readingObjective": "",
            "listeningObjective": "",
            "writingObjective": "Draft a short 4-sentence email inquiring politely about post-interview selection status.",
            "spokenProductionObjective": "Participate in a group debrief analyzing why a candidate was selected or rejected.",
            "registerTarget": "Collaborative professional discussion register",
            "pragmaticTarget": "Providing constructive feedback diplomatically without blunt criticism.",
            "prerequisiteLessonIds": ["les_b1_113_04_simulated_high_stakes_interview"],
            "reviewsLessonIds": ["les_b1_113_04_simulated_high_stakes_interview"],
            "reviewsUnitIds": ["unit_b1_113_job_interview_strategies_answering_t"],
            "reviewReason": "Consolidates interview experience through meta-linguistic reflection and strategic discussion.",
            "audioSuitability": "standard_speech_synthesis_acceptable",
            "audioPurpose": "Provide discussion prompts and sample feedback comments.",
            "successCriteria": [
                "Identifies at least two constructive critiques in a peer interview transcript",
                "Drafts an appropriate formal post-interview follow-up inquiry"
            ],
            "masteryEvidence": "Articulates 'Нэр дэвшигчийн хариулт хэт ерөнхий байсан тул бодит баримтаар баяжуулах хэрэгтэй' during discussion.",
            "recommendedExerciseModalities": ["peer_evaluation", "critical_analysis", "follow_up_drafting"]
        }
    ])

    return lessons
