// Direct definition of Phase 1C Pilot Lessons: Pre-A1 (Units 1-15) and A1 Section 1 (Units 16-23)
import { LessonBlueprint } from "./lessonBlueprintTypes";

export const pilotLessonsPreA1: LessonBlueprint[] = [
  // =========================================================================
  // UNIT 1: Cyrillic Script Recognition & Shared Consonants (unit_pre_a1_01_alphabet_consonants_intro)
  // Target: Prod=8, Rec=3, ProdExp=2, RecExp=1
  // Lessons: 4
  // =========================================================================
  {
    lessonId: "les_pre_a1_01_01_shared_consonants_visual",
    unitId: "unit_pre_a1_01_alphabet_consonants_intro",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 1,
    title: "Recognizing Shared Cyrillic Consonants: М, Т, К, О, А",
    lessonType: "orthography",
    primaryPurpose: "Introduce printed capital and lowercase letterforms for shared Cyrillic consonants and cardinal anchor vowels.",
    communicativeOutcome: "Visually identify and match Cyrillic letters М, Т, К, О, and А against identical Latin and international glyphs.",
    objectivesIntroduced: ["obj_pre_a1_01_01_identify_shared_glyphs"],
    objectivesPracticed: [],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: ["phono_cyr_35_alphabet"],
    phonologyPracticed: [],
    phonologyReviewed: [],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_general_education_literacy"],
    previousVocabularyReused: [],
    readingObjective: "Recognize isolated uppercase and lowercase letterforms М, Т, К, О, А across standard serif and sans-serif fonts.",
    listeningObjective: null,
    writingObjective: "Transcribe uppercase and lowercase glyphs М, Т, К, О, А accurately into ruled line guides.",
    spokenProductionObjective: null,
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Recognizing formal written educational signage and instructional symbols.",
    prerequisiteLessonIds: [],
    reviewsLessonIds: [],
    reviewsUnitIds: [],
    reviewReason: null,
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Authentic articulation of isolated Cyrillic consonant phonemes without trailing neutral schwa.",
    successCriteria: [
      "Select correct Cyrillic letter from a distracter set of 4 letters with 100% accuracy.",
      "Pair uppercase and lowercase variants (М-м, Т-т, К-к, О-о, А-а) correctly."
    ],
    masteryEvidence: [
      "Discriminates correctly between visual false friends such as Latin T vs Cyrillic Т.",
      "Accurately transcribes 5 isolated characters on paper or digital canvas."
    ],
    recommendedExerciseModalities: ["matching", "phonetic_discrimination", "typing"]
  },
  {
    lessonId: "les_pre_a1_01_02_false_friend_letters",
    unitId: "unit_pre_a1_01_alphabet_consonants_intro",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 2,
    title: "Navigating Cyrillic False Friends: В, Н, Р, С, Х",
    lessonType: "orthography",
    primaryPurpose: "Differentiate letters that look identical to Latin graphemes but represent distinct Slavic/Mongolian phonemes.",
    communicativeOutcome: "Distinguish and decode misleading letterforms В (/w/~/v/), Н (/n/), Р (/r/), С (/s/), Х (/x/) without phonetic Latin interference.",
    objectivesIntroduced: ["obj_pre_a1_01_02_discriminate_false_friends"],
    objectivesPracticed: ["obj_pre_a1_01_01_identify_shared_glyphs"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_cyr_35_alphabet"],
    phonologyReviewed: [],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 1,
    lexicalDomains: ["lex_domain_general_education_literacy"],
    previousVocabularyReused: [],
    readingObjective: "Read short international loan words (спорт, такси, парк) distinguishing Cyrillic P (/r/) and H (/n/).",
    listeningObjective: "Discriminate sound values of false friends when paired with audio models of native phonemes.",
    writingObjective: "Transcribe 3-5 simple international loan words without substituting Latin phoneme mappings.",
    spokenProductionObjective: null,
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Interpreting urban signage featuring global loanwords.",
    prerequisiteLessonIds: ["les_pre_a1_01_01_shared_consonants_visual"],
    reviewsLessonIds: ["les_pre_a1_01_01_shared_consonants_visual"],
    reviewsUnitIds: [],
    reviewReason: "Anchor newly learned false-friend letters into previously mastered shared consonant templates.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Native pronunciation of initial fricatives and rolled alveolar trill Р (/r/).",
    successCriteria: [
      "Correctly classify В, Н, Р, С, Х by phonetic value rather than Latin value in 10 test items.",
      "Accurately read aloud short loan words containing false friend letters."
    ],
    masteryEvidence: [
      "Reads 'спорт' as /spɔrət/ rather than mistaking 'р' for /p/.",
      "Identifies Cyrillic 'H' as alveolar nasal /n/ in initial and medial positions."
    ],
    recommendedExerciseModalities: ["phonetic_discrimination", "matching", "dictation"]
  },
  {
    lessonId: "les_pre_a1_01_03_simple_syllables_reading",
    unitId: "unit_pre_a1_01_alphabet_consonants_intro",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 3,
    title: "Blending Consonants and Vowels into Simple Syllables (CV and CVC)",
    lessonType: "phonology_introduction",
    primaryPurpose: "Train the blending of shared consonants with cardinal vowels А and О into transparent open and closed syllables.",
    communicativeOutcome: "Pronounce and decode basic monosyllabic and disyllabic letter strings with accurate phonemic boundaries.",
    objectivesIntroduced: ["obj_pre_a1_01_03_blend_cv_syllables"],
    objectivesPracticed: ["obj_pre_a1_01_01_identify_shared_glyphs", "obj_pre_a1_01_02_discriminate_false_friends"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_cyr_35_alphabet"],
    phonologyReviewed: [],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_general_education_literacy"],
    previousVocabularyReused: [],
    readingObjective: "Decode written open (ма, та, са, ха) and closed (ном, сор, тал) monosyllables in printed type.",
    listeningObjective: "Match spoken monosyllables against corresponding written Cyrillic syllable cards.",
    writingObjective: "Write dictated monosyllables and disyllables without omitted vowel characters.",
    spokenProductionObjective: "Articulate open syllables with clear vowel release and non-aspirated voiceless stops.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Responding to teacher phonics prompts in language training contexts.",
    prerequisiteLessonIds: ["les_pre_a1_01_02_false_friend_letters"],
    reviewsLessonIds: ["les_pre_a1_01_01_shared_consonants_visual", "les_pre_a1_01_02_false_friend_letters"],
    reviewsUnitIds: [],
    reviewReason: "Integrate shared consonants and false friends into active syllable decoding.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Phonetically pure syllable audio without synthetic formant warping.",
    successCriteria: [
      "Correctly blend and read 8 out of 8 CV/CVC syllables.",
      "Spell dictated monosyllabic strings with 100% orthographic fidelity."
    ],
    masteryEvidence: [
      "Distinguishes spoken 'сон' vs 'сан' and selects correct written representation.",
      "Vocalizes non-aspirated stops without English-style aspiration burst."
    ],
    recommendedExerciseModalities: ["phonetic_discrimination", "dictation", "word_ordering"]
  },
  {
    lessonId: "les_pre_a1_01_04_cognates_and_signs_decoding",
    unitId: "unit_pre_a1_01_alphabet_consonants_intro",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 4,
    title: "Decoding Real-World Signs and Global Cognates",
    lessonType: "reading_development",
    primaryPurpose: "Apply learned consonants and anchor vowels to decipher authentic public signs, logos, and international cognates.",
    communicativeOutcome: "Read and comprehend high-frequency urban signs (КИНО, ТАКСИ, БАНК, КАССА, АПТЕК) in public environments.",
    objectivesIntroduced: ["obj_pre_a1_01_04_read_public_cognate_signs"],
    objectivesPracticed: ["obj_pre_a1_01_03_blend_cv_syllables"],
    objectivesReviewed: ["obj_pre_a1_01_01_identify_shared_glyphs", "obj_pre_a1_01_02_discriminate_false_friends"],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_cyr_35_alphabet"],
    phonologyReviewed: [],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 0,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_public_spaces_urban_navigation"],
    previousVocabularyReused: [],
    readingObjective: "Scan and decode 5 authentic storefront signs and identify the corresponding service or location.",
    listeningObjective: "Identify spoken place names when matching them with written street signs.",
    writingObjective: "Transcribe 3 city facility names from signage into personal notebook.",
    spokenProductionObjective: "Read storefront titles aloud with appropriate word-level stress.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Navigating municipal transit hubs and commercial facilities.",
    prerequisiteLessonIds: ["les_pre_a1_01_03_simple_syllables_reading"],
    reviewsLessonIds: ["les_pre_a1_01_01_shared_consonants_visual", "les_pre_a1_01_02_false_friend_letters", "les_pre_a1_01_03_simple_syllables_reading"],
    reviewsUnitIds: [],
    reviewReason: "Cumulative capstone application for Unit 1 script decoding.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Authentic urban audio models of store names and public announcements.",
    successCriteria: [
      "Correctly match 5 authentic sign images with their English functional descriptions.",
      "Accurately decode multi-syllable cognates with correct stress placement on the initial syllable."
    ],
    masteryEvidence: [
      "Identifies 'КИНО' as cinema and 'АПТЕК' as pharmacy without hesitation.",
      "Zero Latin-letter phoneme interference when reading words with 'P' and 'C'."
    ],
    recommendedExerciseModalities: ["matching", "reading_comprehension", "short_answer_writing"]
  }
];
