import { LessonBlueprint } from "./lessonBlueprintTypes";

export const a1_Units_20_to_23: LessonBlueprint[] = [
  // =========================================================================
  // UNIT 20: Demonstrative Deixis: Энэ, Тэр, Эдгээр, Тэдгээр (unit_a1_20_demonstrative_deixis_)
  // Target: Prod=17, Rec=6, ProdExp=4, RecExp=2 | Lessons: 6
  // =========================================================================
  {
    lessonId: "les_a1_20_01_proximal_distal_deixis_ene_ter",
    unitId: "unit_a1_20_demonstrative_deixis_",
    cefrLevel: "A1",
    sequenceWithinUnit: 1,
    title: "Spatial Deixis: Contrasting Proximal Энэ (This) and Distal Тэр (That)",
    lessonType: "grammar_introduction",
    primaryPurpose: "Introduce demonstrative pronouns 'энэ' (proximal, near speaker) and 'тэр' (distal, away from speaker) functioning as determiners and pronouns.",
    communicativeOutcome: "Point to objects, people, and documents in space using 'энэ' and 'тэр' (Энэ ном 'this book', Тэр багш 'that teacher').",
    objectivesIntroduced: ["obj_a1_20_01_use_ene_ter_demonstratives"],
    objectivesPracticed: [],
    objectivesReviewed: ["obj_a1_18_01_form_zero_copula_clauses"],
    grammarIntroduced: ["gram_a1_pronouns_demonstrative_ene_ter"],
    grammarPracticed: [],
    grammarReviewed: ["gram_a1_sov_word_order", "gram_a1_nominal_predicate_zero_copula"],
    phonologyIntroduced: [],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_stress_initial_and_full_vowels"],
    communicativeFunctionsIntroduced: ["comm_a1_08_professions_occupations"],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 3,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_personal_information_identity", "lex_domain_household_home_environment"],
    previousVocabularyReused: [],
    readingObjective: "Read 6 demonstrative phrases paired with pictures of near and far objects.",
    listeningObjective: "Distinguish between 'энэ' and 'тэр' in spoken requests and references.",
    writingObjective: "Write 4 sentences using 'энэ' and 'тэр' as prenominal demonstratives.",
    spokenProductionObjective: "Point to real physical classroom objects and identify them using 'Энэ бол...' and 'Тэр бол...'.",
    registerTarget: "Everyday standard courteous",
    pragmaticTarget: "Directing joint visual attention during conversations and business meetings.",
    prerequisiteLessonIds: ["les_a1_19_06_polar_inquiries_synthesis_checkpoint"],
    reviewsLessonIds: ["les_a1_18_01_zero_copula_structure_intro"],
    reviewsUnitIds: ["unit_a1_18_zero_copula_identity_origin_predica"],
    reviewReason: "Integrate demonstrative deixis into zero-copula subject slots.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Authentic deictic utterances with clear pitch peak on the demonstrative.",
    successCriteria: [
      "Correctly designate proximal items with 'энэ' and distal items with 'тэр'.",
      "Accurately position demonstrative before the noun it modifies."
    ],
    masteryEvidence: [
      "Never puts demonstrative after the noun.",
      "Distinguishes third-person pronoun 'тэр' (he/she) from demonstrative determiner 'тэр' (that)."
    ],
    recommendedExerciseModalities: ["matching", "word_ordering", "categorization"]
  },
  {
    lessonId: "les_a1_20_02_plural_demonstratives_edgeer_tedgeer",
    unitId: "unit_a1_20_demonstrative_deixis_",
    cefrLevel: "A1",
    sequenceWithinUnit: 2,
    title: "Plural Deixis: Эдгээр (These) and Тэдгээр (Those)",
    lessonType: "grammar_guided_practice",
    primaryPurpose: "Introduce the plural demonstrative forms 'эдгээр' (these) and 'тэдгээр' (those) for multiple referents.",
    communicativeOutcome: "Refer to collections of items or groups of individuals ('эдгээр номууд' 'these books', 'тэдгээр хүмүүс' 'those people').",
    objectivesIntroduced: ["obj_a1_20_02_use_edgeer_tedgeer_plural"],
    objectivesPracticed: ["obj_a1_20_01_use_ene_ter_demonstratives"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: ["gram_a1_pronouns_demonstrative_ene_ter"],
    grammarReviewed: ["gram_a1_pronouns_personal_nominative"],
    phonologyIntroduced: [],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_vowel_long_pairs"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: ["comm_a1_08_professions_occupations"],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 3,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_general_education_literacy", "lex_domain_professions_workplace_office"],
    previousVocabularyReused: [],
    readingObjective: "Read catalogue entries and library labels featuring plural demonstratives.",
    listeningObjective: "Identify whether a speaker refers to singular ('энэ') or plural ('эдгээр') items in audio.",
    writingObjective: "Convert 4 singular demonstrative sentences into plural sentences using 'эдгээр' and 'тэдгээр'.",
    spokenProductionObjective: "Describe groups of items on a desk using plural demonstratives.",
    registerTarget: "Everyday standard courteous",
    pragmaticTarget: "Organizing paperwork, sorting documents, and presenting multiple items.",
    prerequisiteLessonIds: ["les_a1_20_01_proximal_distal_deixis_ene_ter"],
    reviewsLessonIds: ["les_a1_17_03_plural_address_protocols", "les_a1_20_01_proximal_distal_deixis_ene_ter"],
    reviewsUnitIds: ["unit_a1_17_personal_pronouns_direct_address_pr"],
    reviewReason: "Extend singular deixis to plural grammatical categories.",
    audioSuitability: "standard_speech_synthesis_acceptable",
    audioPurpose: "Clear distinction between long vowel /e:/ in 'эдгээр' vs short vowel.",
    successCriteria: [
      "Select 'эдгээр' for proximal plurals and 'тэдгээр' for distal plurals with 100% accuracy.",
      "Maintain correct long vowel spelling in '-гээр'."
    ],
    masteryEvidence: [
      "Uses 'эдгээр оюутнууд' correctly in classroom discussion.",
      "Spells 'эдгээр' with double 'э' in the final syllable."
    ],
    recommendedExerciseModalities: ["matching", "cloze", "sentence_transformation"]
  },
  {
    lessonId: "les_a1_20_03_inquiry_with_demonstratives_ene_yuu_ve",
    unitId: "unit_a1_20_demonstrative_deixis_",
    cefrLevel: "A1",
    sequenceWithinUnit: 3,
    title: "Asking What Things Are: Энэ юу вэ? & Тэр хэн бэ?",
    lessonType: "dialogue_work",
    primaryPurpose: "Combine demonstratives with interrogative pronouns 'юу' (what) and 'хэн' (who) using content question particle вэ/бэ.",
    communicativeOutcome: "Ask 'Энэ юу вэ?' (What is this?) and 'Тэр хэн бэ?' (Who is that?) and provide complete nominal answers.",
    objectivesIntroduced: ["obj_a1_20_03_ask_what_and_who_with_deictics"],
    objectivesPracticed: ["obj_a1_20_01_use_ene_ter_demonstratives"],
    objectivesReviewed: ["obj_a1_19_01_form_polar_questions_uu_uu"],
    grammarIntroduced: [],
    grammarPracticed: ["gram_a1_pronouns_demonstrative_ene_ter", "gram_a1_sov_word_order"],
    grammarReviewed: ["gram_a1_polar_questions_uu_uu"],
    phonologyIntroduced: [],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_stress_initial_and_full_vowels"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: ["comm_a1_08_professions_occupations"],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 3,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 1,
    lexicalDomains: ["lex_domain_personal_information_identity", "lex_domain_household_home_environment"],
    previousVocabularyReused: [],
    readingObjective: "Read illustrated museum guidebooks with 'Энэ юу вэ?' captions.",
    listeningObjective: "Differentiate between polar questions (уу/үү) and content questions (вэ/бэ) in spoken dialogues.",
    writingObjective: "Write 3 question-and-answer pairs inquiring about mysterious objects in an office.",
    spokenProductionObjective: "Ask instructor 'Энэ юу вэ?' pointing to unknown objects in the room.",
    registerTarget: "Everyday standard courteous",
    pragmaticTarget: "Inquiring about unfamiliar objects, tools, and cultural artifacts in Mongolia.",
    prerequisiteLessonIds: ["les_a1_20_02_plural_demonstratives_edgeer_tedgeer"],
    reviewsLessonIds: ["les_a1_19_01_polar_particles_uu_uu_distribution", "les_a1_20_01_proximal_distal_deixis_ene_ter"],
    reviewsUnitIds: ["unit_a1_19_polar_inquiries_polar_question_part"],
    reviewReason: "Contrast content questions (вэ/бэ) with polar questions (уу/үү) using demonstratives.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Authentic inquiring intonation on 'Энэ юу вэ?' with terminal rise-fall.",
    successCriteria: [
      "Select particle 'вэ' after 'юу' and 'бэ' after 'хэн' with 100% accuracy.",
      "Respond using 'Энэ бол...' followed by predicate noun."
    ],
    masteryEvidence: [
      "Asks 'Энэ юу вэ?' without substituting English 'What is this?'.",
      "Correctly distinguishes between particle 'юу' (polar) and pronoun 'юу' (what)."
    ],
    recommendedExerciseModalities: ["role_play_response", "dialogue_completion", "matching"]
  },
  {
    lessonId: "les_a1_20_04_reading_office_equipment_inventories",
    unitId: "unit_a1_20_demonstrative_deixis_",
    cefrLevel: "A1",
    sequenceWithinUnit: 4,
    title: "Reading Workplace Equipment Inventories & Supply Lists",
    lessonType: "reading_development",
    primaryPurpose: "Decode office equipment catalogues, supply manifests, and room inventories using demonstrative labels.",
    communicativeOutcome: "Scan an office inventory list and verify which items are located on specific desks or shelves.",
    objectivesIntroduced: ["obj_a1_20_04_read_office_inventories"],
    objectivesPracticed: ["obj_a1_20_01_use_ene_ter_demonstratives", "obj_a1_20_02_use_edgeer_tedgeer_plural"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: ["gram_a1_pronouns_demonstrative_ene_ter", "gram_a1_nominal_predicate_zero_copula"],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: [],
    phonologyReviewed: [],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: ["comm_a1_08_professions_occupations"],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 3,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 1,
    lexicalDomains: ["lex_domain_professions_workplace_office", "lex_domain_technology_communications_media"],
    previousVocabularyReused: [],
    readingObjective: "Read an illustrated office diagram labeled with demonstrative captions: 'Энэ компьютер', 'Тэр принтер'.",
    listeningObjective: "Verify items on an inventory audio checklist (компьютер, ширээ, сандал, утас).",
    writingObjective: "Write a 4-item inventory list specifying office objects using 'энэ' and 'эдгээр'.",
    spokenProductionObjective: "Present an office workstation layout aloud to a coworker.",
    registerTarget: "Everyday standard courteous",
    pragmaticTarget: "Conducting inventory checks and orienting new employees in an office.",
    prerequisiteLessonIds: ["les_a1_20_03_inquiry_with_demonstratives_ene_yuu_ve"],
    reviewsLessonIds: ["les_pre_a1_14_02_office_and_facility_signs", "les_a1_20_01_proximal_distal_deixis_ene_ter"],
    reviewsUnitIds: ["unit_pre_a1_14_public_signs_and_notices"],
    reviewReason: "Integrate workplace signage literacy with demonstrative deixis.",
    audioSuitability: "standard_speech_synthesis_acceptable",
    audioPurpose: "Clear office equipment inventory audio dictation.",
    successCriteria: [
      "Correctly identify 5 office objects from inventory descriptions.",
      "Accurately spell tech and office terms (компьютер, утас, принтер)."
    ],
    masteryEvidence: [
      "Verifies inventory against real physical items accurately.",
      "Reads technical terms borrowed into Cyrillic without hesitation."
    ],
    recommendedExerciseModalities: ["reading_comprehension", "matching", "cloze"]
  },
  {
    lessonId: "les_a1_20_05_introducing_colleagues_by_deixis",
    unitId: "unit_a1_20_demonstrative_deixis_",
    cefrLevel: "A1",
    sequenceWithinUnit: 5,
    title: "Speaking Workshop: Introducing Team Members Using Deictic Reference",
    lessonType: "dialogue_work",
    primaryPurpose: "Introduce team members, coworkers, and visiting guests using 'Энэ бол...' and 'Тэр бол...'.",
    communicativeOutcome: "Formally introduce team members to clients ('Энэ бол манай менежер Болд. Тэр бол манай нягтлан бодогч.').",
    objectivesIntroduced: ["obj_a1_20_05_introduce_team_members"],
    objectivesPracticed: ["obj_a1_20_01_use_ene_ter_demonstratives", "obj_a1_20_03_ask_what_and_who_with_deictics"],
    objectivesReviewed: ["obj_a1_18_05_introduce_self_and_colleague"],
    grammarIntroduced: [],
    grammarPracticed: ["gram_a1_pronouns_demonstrative_ene_ter", "gram_a1_nominal_predicate_zero_copula"],
    grammarReviewed: ["gram_a1_pronouns_personal_nominative"],
    phonologyIntroduced: [],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_stress_initial_and_full_vowels"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: ["comm_a1_08_professions_occupations"],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 3,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_professions_workplace_office", "lex_domain_social_interaction_courtesy"],
    previousVocabularyReused: [],
    readingObjective: "Read staff directory entries and team organograms.",
    listeningObjective: "Follow introductions given by a director presenting staff members to guests.",
    writingObjective: "Write a 4-sentence introductory script presenting department staff.",
    spokenProductionObjective: "Introduce 2 colleagues using 'Энэ бол...' with polite hand gestures (open palm).",
    registerTarget: "Everyday standard courteous",
    pragmaticTarget: "Welcoming visitors and introducing team members in business environments.",
    prerequisiteLessonIds: ["les_a1_20_04_reading_office_equipment_inventories"],
    reviewsLessonIds: ["les_a1_18_05_introducing_oneself_and_others_origin", "les_a1_20_01_proximal_distal_deixis_ene_ter"],
    reviewsUnitIds: [],
    reviewReason: "Combine zero-copula predication, professional roles, and demonstrative deixis.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Authentic corporate team introduction dialogue.",
    successCriteria: [
      "Present 2 colleagues using correct demonstratives and profession nouns.",
      "Employ culturally respectful open-palm gesture instead of pointing with index finger."
    ],
    masteryEvidence: [
      "Uses open palm when gesturing toward colleagues.",
      "Uses 'Энэ бол...' smoothly to highlight the topic."
    ],
    recommendedExerciseModalities: ["role_play_response", "dialogue_completion", "word_ordering"]
  },
  {
    lessonId: "les_a1_20_06_demonstrative_deixis_checkpoint",
    unitId: "unit_a1_20_demonstrative_deixis_",
    cefrLevel: "A1",
    sequenceWithinUnit: 6,
    title: "Demonstrative Deixis & Object Identification Synthesis",
    lessonType: "checkpoint",
    primaryPurpose: "Assess integrated command of demonstrative pronouns, spatial deixis, and deictic introductions.",
    communicativeOutcome: "Accurately identify, introduce, and question objects and people across spatial fields.",
    objectivesIntroduced: [],
    objectivesPracticed: ["obj_a1_20_01_use_ene_ter_demonstratives", "obj_a1_20_02_use_edgeer_tedgeer_plural", "obj_a1_20_03_ask_what_and_who_with_deictics", "obj_a1_20_05_introduce_team_members"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: ["gram_a1_pronouns_demonstrative_ene_ter", "gram_a1_nominal_predicate_zero_copula"],
    grammarReviewed: ["gram_a1_sov_word_order", "gram_a1_polar_questions_uu_uu"],
    phonologyIntroduced: [],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_stress_initial_and_full_vowels"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: ["comm_a1_08_professions_occupations"],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_professions_workplace_office"],
    previousVocabularyReused: [],
    readingObjective: "Read and verify 6 demonstrative descriptions against spatial layout diagrams.",
    listeningObjective: "Transcribe 5 dictated deictic sentences and mark whether items are near or far.",
    writingObjective: "Write a 5-sentence descriptive paragraph about objects and coworkers in a workspace.",
    spokenProductionObjective: "Perform an unscripted object and colleague introduction presentation for rubric assessment.",
    registerTarget: "Everyday standard courteous",
    pragmaticTarget: "Confirming mastery of demonstrative deixis before introducing negative nominal assertion in Unit 21.",
    prerequisiteLessonIds: ["les_a1_20_05_introducing_colleagues_by_deixis"],
    reviewsLessonIds: ["les_a1_20_01_proximal_distal_deixis_ene_ter", "les_a1_20_02_plural_demonstratives_edgeer_tedgeer", "les_a1_20_03_inquiry_with_demonstratives_ene_yuu_ve", "les_a1_20_05_introducing_colleagues_by_deixis"],
    reviewsUnitIds: ["unit_a1_17_personal_pronouns_direct_address_pr", "unit_a1_18_zero_copula_identity_origin_predica"],
    reviewReason: "Unit 20 synthesis evaluating deictic reference and workplace vocabulary.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Diagnostic audio evaluation items for demonstrative deixis.",
    successCriteria: [
      "Achieve at least 90% on demonstrative identification and usage exam.",
      "Zero errors placing demonstratives before head nouns."
    ],
    masteryEvidence: [
      "Deploys энэ/тэр/эдгээр/тэдгээр with complete spatial accuracy.",
      "Flawlessly distinguishes between content and polar questions in deictic contexts."
    ],
    recommendedExerciseModalities: ["dictation", "role_play_response", "error_correction"]
  },

  // =========================================================================
  // UNIT 21: Negative Nominal Assertion: The Copular Particle Биш (unit_a1_21_negative_nominal_assertion_the_copu)
  // Target: Prod=17, Rec=6, ProdExp=4, RecExp=2 | Lessons: 6
  // =========================================================================
  {
    lessonId: "les_a1_21_01_nominal_negation_particle_bish",
    unitId: "unit_a1_21_negative_nominal_assertion_the_copu",
    cefrLevel: "A1",
    sequenceWithinUnit: 1,
    title: "Nominal Negation: Negating Identity and Class with Биш (Not)",
    lessonType: "grammar_introduction",
    primaryPurpose: "Introduce the postposed negative copular particle 'биш' used to negate nominal predicates.",
    communicativeOutcome: "Negate nominal identity statements (Би багш биш 'I am not a teacher', Энэ ном биш 'This is not a book').",
    objectivesIntroduced: ["obj_a1_21_01_negate_nominal_predicates_bish"],
    objectivesPracticed: [],
    objectivesReviewed: ["obj_a1_18_01_form_zero_copula_clauses"],
    grammarIntroduced: ["gram_a1_nominal_negation_bish"],
    grammarPracticed: [],
    grammarReviewed: ["gram_a1_nominal_predicate_zero_copula", "gram_a1_case_nominative_unmarked"],
    phonologyIntroduced: [],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_stress_initial_and_full_vowels"],
    communicativeFunctionsIntroduced: ["comm_a1_05_apologies_pardon"],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 3,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_personal_information_identity", "lex_domain_professions_workplace_office"],
    previousVocabularyReused: [],
    readingObjective: "Read 6 pairs of affirmative vs negative nominal statements and observe the position of 'биш'.",
    listeningObjective: "Detect the heavy stress and falling pitch on sentence-final 'биш'.",
    writingObjective: "Convert 5 affirmative zero-copula sentences into negative sentences by appending 'биш'.",
    spokenProductionObjective: "State what one is not ('Би оюутан биш, би багш') with natural rhythm.",
    registerTarget: "Everyday standard courteous",
    pragmaticTarget: "Clarifying false assumptions regarding identity and profession.",
    prerequisiteLessonIds: ["les_a1_20_06_demonstrative_deixis_checkpoint"],
    reviewsLessonIds: ["les_a1_18_01_zero_copula_structure_intro"],
    reviewsUnitIds: ["unit_a1_18_zero_copula_identity_origin_predica"],
    reviewReason: "Provide the negative counterpart to Unit 18 zero-copula identity statements.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Authentic negative assertions with emphatic falling intonation on 'биш'.",
    successCriteria: [
      "Place 'биш' immediately after the predicate noun with 100% syntactic precision.",
      "Accurately pronounce /piʃ/ with clean palato-alveolar fricative."
    ],
    masteryEvidence: [
      "Never places 'биш' before the noun it negates.",
      "Distinguishes nominal negation 'биш' from verbal negation 'гүй'."
    ],
    recommendedExerciseModalities: ["sentence_transformation", "matching", "cloze"]
  },
  {
    lessonId: "les_a1_21_02_correcting_false_assumptions_clarification",
    unitId: "unit_a1_21_negative_nominal_assertion_the_copu",
    cefrLevel: "A1",
    sequenceWithinUnit: 2,
    title: "Correcting Misconceptions: Үгүй, [Noun] биш, харин [Noun]",
    lessonType: "dialogue_work",
    primaryPurpose: "Teach the clarification formula: 'Үгүй, [A] биш, харин [B]' (No, not A, but rather B).",
    communicativeOutcome: "Politely correct mistaken assumptions about identity, nationality, or objects ('Үгүй ээ, би япон биш, би монгол').",
    objectivesIntroduced: ["obj_a1_21_02_correct_assumptions_harin"],
    objectivesPracticed: ["obj_a1_21_01_negate_nominal_predicates_bish"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: ["gram_a1_nominal_negation_bish", "gram_a1_nominal_predicate_zero_copula"],
    grammarReviewed: ["gram_a1_pronouns_demonstrative_ene_ter"],
    phonologyIntroduced: [],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_stress_initial_and_full_vowels"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: ["comm_a1_05_apologies_pardon"],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 3,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 1,
    lexicalDomains: ["lex_domain_social_interaction_courtesy", "lex_domain_countries_nationalities_languages"],
    previousVocabularyReused: [],
    readingObjective: "Read dialogues where characters correct mistaken identities politely.",
    listeningObjective: "Identify what is being negated and what is being asserted as true in audio clarifications.",
    writingObjective: "Write 3 correction sentences using the pattern: 'Үгүй, ... биш, ...'.",
    spokenProductionObjective: "Correct an interlocutor's misconception with courteous tone: 'Уучлаарай, би япон биш, харин солонгос.'",
    registerTarget: "Everyday standard courteous",
    pragmaticTarget: "Clarifying personal background without sounding confrontational.",
    prerequisiteLessonIds: ["les_a1_21_01_nominal_negation_particle_bish"],
    reviewsLessonIds: ["les_a1_18_02_nationality_and_origin_predication", "les_a1_21_01_nominal_negation_particle_bish"],
    reviewsUnitIds: ["unit_a1_18_zero_copula_identity_origin_predica"],
    reviewReason: "Combine negative assertion with nationality and identity vocabulary.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Authentic polite clarification dialogues with softening particle 'ээ'.",
    successCriteria: [
      "Use 'Үгүй ээ, ... биш' correctly when responding to false polar questions.",
      "Employ 'харин' (but rather / on the other hand) smoothly to introduce the correct fact."
    ],
    masteryEvidence: [
      "Responds to 'Та багш уу?' with 'Үгүй ээ, би багш биш, би оюутан' seamlessly.",
      "Precedes correction with polite apologies where socially required."
    ],
    recommendedExerciseModalities: ["role_play_response", "dialogue_completion", "word_ordering"]
  },
  {
    lessonId: "les_a1_21_03_negative_polar_questions_bish_uu",
    unitId: "unit_a1_21_negative_nominal_assertion_the_copu",
    cefrLevel: "A1",
    sequenceWithinUnit: 3,
    title: "Negative Polar Inquiries: Combining Биш + уу / үү (Биш үү?)",
    lessonType: "grammar_guided_practice",
    primaryPurpose: "Introduce negative polar confirmation questions combining 'биш' with question particle 'үү' (Биш үү? 'Isn't it?').",
    communicativeOutcome: "Seek confirmation of expected truths using '... биш үү?' (Та багш биш үү? 'Aren't you a teacher? / You are a teacher, right?').",
    objectivesIntroduced: ["obj_a1_21_03_form_negative_polar_inquiries"],
    objectivesPracticed: ["obj_a1_21_01_negate_nominal_predicates_bish"],
    objectivesReviewed: ["obj_a1_19_01_form_polar_questions_uu_uu"],
    grammarIntroduced: [],
    grammarPracticed: ["gram_a1_nominal_negation_bish"],
    grammarReviewed: ["gram_a1_polar_questions_uu_uu"],
    phonologyIntroduced: [],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_vowel_harmony_masc_fem"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: ["comm_a1_05_apologies_pardon"],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 3,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_social_interaction_courtesy", "lex_domain_personal_information_identity"],
    previousVocabularyReused: [],
    readingObjective: "Read 6 confirmation inquiries ending in 'биш үү?' and match them to appropriate contextual responses.",
    listeningObjective: "Recognize tag-question intonation on 'биш үү?' in conversational exchanges.",
    writingObjective: "Form 4 negative confirmation questions using 'биш үү?'.",
    spokenProductionObjective: "Ask a partner for confirmation using '... биш үү?' with friendly rising intonation.",
    registerTarget: "Everyday standard courteous",
    pragmaticTarget: "Checking mutual assumptions and seeking agreement softly.",
    prerequisiteLessonIds: ["les_a1_21_02_correcting_false_assumptions_clarification"],
    reviewsLessonIds: ["les_a1_19_01_polar_particles_uu_uu_distribution", "les_a1_21_01_nominal_negation_particle_bish"],
    reviewsUnitIds: ["unit_a1_19_polar_inquiries_polar_question_part"],
    reviewReason: "Harmonize question particle 'үү' with front-vowel particle 'биш'.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Authentic confirmation-seeking speech with rising-falling intonation.",
    successCriteria: [
      "Always pair 'биш' with feminine particle 'үү' (never masculine 'уу') due to vowel harmony.",
      "Accurately write 'биш үү' as two separate words."
    ],
    masteryEvidence: [
      "Understands why 'биш үү' always uses 'үү' (биш is front-vocalic).",
      "Deploys 'биш үү' naturally as a conversational tag question."
    ],
    recommendedExerciseModalities: ["matching", "cloze", "role_play_response"]
  },
  {
    lessonId: "les_a1_21_04_reading_lost_and_found_notices",
    unitId: "unit_a1_21_negative_nominal_assertion_the_copu",
    cefrLevel: "A1",
    sequenceWithinUnit: 4,
    title: "Reading Lost & Found Notices: Clarifying Ownership",
    lessonType: "reading_development",
    primaryPurpose: "Decode notices at university lost-and-found desks and office noticeboards clarifying item ownership using 'биш'.",
    communicativeOutcome: "Scan 45-word notices and determine which items belong to whom and which claims are denied.",
    objectivesIntroduced: ["obj_a1_21_04_read_lost_and_found_notices"],
    objectivesPracticed: ["obj_a1_21_01_negate_nominal_predicates_bish", "obj_a1_21_02_correct_assumptions_harin"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: ["gram_a1_nominal_negation_bish"],
    grammarReviewed: ["gram_a1_pronouns_demonstrative_ene_ter"],
    phonologyIntroduced: [],
    phonologyPracticed: [],
    phonologyReviewed: [],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: ["comm_a1_05_apologies_pardon"],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 3,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 1,
    lexicalDomains: ["lex_domain_household_home_environment", "lex_domain_public_administration_civic_life"],
    previousVocabularyReused: [],
    readingObjective: "Read a bulletin board announcement: 'Энэ түлхүүр минийх биш. Энэ Батын түлхүүр мөн үү?'",
    listeningObjective: "Listen to a desk clerk inquiring about unclaimed bags and jackets.",
    writingObjective: "Write a short 3-line note denying ownership of an item and redirecting to the owner.",
    spokenProductionObjective: "State clearly at a service counter: 'Энэ миний цүнх биш.'",
    registerTarget: "Everyday standard courteous",
    pragmaticTarget: "Resolving property confusion and sorting personal belongings politely.",
    prerequisiteLessonIds: ["les_a1_21_03_negative_polar_questions_bish_uu"],
    reviewsLessonIds: ["les_pre_a1_14_01_reading_regulatory_signs_banned_actions", "les_a1_21_01_nominal_negation_particle_bish"],
    reviewsUnitIds: ["unit_pre_a1_14_public_signs_and_notices"],
    reviewReason: "Integrate public notice reading with negative nominal assertion.",
    audioSuitability: "standard_speech_synthesis_acceptable",
    audioPurpose: "Clear service counter clerk dialogue inquiring about items.",
    successCriteria: [
      "Extract item identity and ownership denial from notices with 100% accuracy.",
      "Accurately understand the possessive pronoun 'минийх' (mine)."
    ],
    masteryEvidence: [
      "Distinguishes between 'миний' (my) and 'минийх биш' (not mine).",
      "Explains notice contents in English accurately."
    ],
    recommendedExerciseModalities: ["reading_comprehension", "matching", "cloze"]
  },
  {
    lessonId: "les_a1_21_05_apology_and_correction_scenarios",
    unitId: "unit_a1_21_negative_nominal_assertion_the_copu",
    cefrLevel: "A1",
    sequenceWithinUnit: 5,
    title: "Speaking Workshop: Social Apologies and Identity Clarification",
    lessonType: "dialogue_work",
    primaryPurpose: "Synthesize apologies ('Уучлаарай', 'Зүгээр ээ') with nominal corrections in realistic social mishaps.",
    communicativeOutcome: "Politely excuse oneself when mistaken and accept apologies gracefully ('Уучлаарай, би андуурчээ' - 'Зүгээр ээ, асуудалгүй').",
    objectivesIntroduced: ["obj_a1_21_05_execute_apology_and_clarification"],
    objectivesPracticed: ["obj_a1_21_01_negate_nominal_predicates_bish", "obj_a1_21_02_correct_assumptions_harin"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: ["gram_a1_nominal_negation_bish"],
    grammarReviewed: ["gram_a1_nominal_predicate_zero_copula"],
    phonologyIntroduced: [],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_stress_initial_and_full_vowels"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: ["comm_a1_05_apologies_pardon"],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 3,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_social_interaction_courtesy"],
    previousVocabularyReused: [],
    readingObjective: "Read comic strips depicting humorous social misunderstandings and apologies.",
    listeningObjective: "Follow multi-speaker interactions where an mistaken identity is cleared up politely.",
    writingObjective: "Write a 4-turn apology-and-correction script.",
    spokenProductionObjective: "Perform a role-play apologizing for mistaking a person's name or profession.",
    registerTarget: "Everyday standard courteous",
    pragmaticTarget: "Navigating awkward social misidentifications with cultural grace.",
    prerequisiteLessonIds: ["les_a1_21_04_reading_lost_and_found_notices"],
    reviewsLessonIds: ["les_pre_a1_13_02_courtesy_formulas_bayarlalaa_uuchlaarai", "les_a1_21_02_correcting_false_assumptions_clarification"],
    reviewsUnitIds: ["unit_pre_a1_13_gratitude_apologies_politeness"],
    reviewReason: "Elevate Pre-A1 apologies into sophisticated clarification dialogues.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Authentic apologetic vocal tone and reassuring replies.",
    successCriteria: [
      "Combine 'Уучлаарай' with negative nominal correction in 100% of mishap scenarios.",
      "Respond to apologies with 'Зүгээр ээ'."
    ],
    masteryEvidence: [
      "Delivers apologies with sincere, polite vocal inflection.",
      "Deploys 'биш' with absolute syntactic accuracy in live role-play."
    ],
    recommendedExerciseModalities: ["role_play_response", "dialogue_completion", "word_ordering"]
  },
  {
    lessonId: "les_a1_21_06_nominal_negation_checkpoint",
    unitId: "unit_a1_21_negative_nominal_assertion_the_copu",
    cefrLevel: "A1",
    sequenceWithinUnit: 6,
    title: "Negative Nominal Assertion & Clarification Synthesis",
    lessonType: "checkpoint",
    primaryPurpose: "Assess integrated competence in nominal negation with 'биш', polite clarification, and negative polar inquiry.",
    communicativeOutcome: "Accurately deny, correct, and confirm identity and category assertions across varied conversational contexts.",
    objectivesIntroduced: [],
    objectivesPracticed: ["obj_a1_21_01_negate_nominal_predicates_bish", "obj_a1_21_02_correct_assumptions_harin", "obj_a1_21_03_form_negative_polar_inquiries", "obj_a1_21_05_execute_apology_and_clarification"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: ["gram_a1_nominal_negation_bish"],
    grammarReviewed: ["gram_a1_nominal_predicate_zero_copula", "gram_a1_case_nominative_unmarked", "gram_a1_pronouns_demonstrative_ene_ter"],
    phonologyIntroduced: [],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_stress_initial_and_full_vowels"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: ["comm_a1_05_apologies_pardon"],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_social_interaction_courtesy"],
    previousVocabularyReused: [],
    readingObjective: "Proofread 6 sentences, identifying and correcting 3 misplaced or misused negation particles.",
    listeningObjective: "Transcribe 5 dictated negative assertions and state whether each is a statement, question, or correction.",
    writingObjective: "Write a 5-sentence paragraph clarifying misconceptions about one's hometown, job, and nationality.",
    spokenProductionObjective: "Participate in an unscripted clarification interview for rubric evaluation.",
    registerTarget: "Everyday standard courteous",
    pragmaticTarget: "Confirming mastery of nominal negation before transitioning to formal departures in Unit 22.",
    prerequisiteLessonIds: ["les_a1_21_05_apology_and_correction_scenarios"],
    reviewsLessonIds: ["les_a1_21_01_nominal_negation_particle_bish", "les_a1_21_02_correcting_false_assumptions_clarification", "les_a1_21_03_negative_polar_questions_bish_uu", "les_a1_21_05_apology_and_correction_scenarios"],
    reviewsUnitIds: ["unit_a1_18_zero_copula_identity_origin_predica", "unit_a1_19_polar_inquiries_polar_question_part"],
    reviewReason: "Unit 21 synthesis evaluating negative nominal mechanics.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Diagnostic audio evaluation items for negative nominal predication.",
    successCriteria: [
      "Achieve at least 90% on nominal negation and clarification exam.",
      "Zero placement of 'биш' in prenominal positions."
    ],
    masteryEvidence: [
      "Executes nominal negation flawlessly in both statements and questions.",
      "Navigates apologies and corrections with high pragmatic polish."
    ],
    recommendedExerciseModalities: ["dictation", "role_play_response", "error_correction"]
  },

  // =========================================================================
  // UNIT 22: Formal Departure & Social Gratitude Formulas (unit_a1_22_formal_departure_social_gratitude_f)
  // Target: Prod=15, Rec=5, ProdExp=4, RecExp=2 | Lessons: 5
  // =========================================================================
  {
    lessonId: "les_a1_22_01_formal_departure_formulas_bayartai",
    unitId: "unit_a1_22_formal_departure_social_gratitude_f",
    cefrLevel: "A1",
    sequenceWithinUnit: 1,
    title: "Formal Departures: Баяртай, Дараа уулзъя & Сайхан амраарай",
    lessonType: "vocabulary_introduction",
    primaryPurpose: "Introduce standard and formal departure formulas across evening, weekend, and future encounter contexts.",
    communicativeOutcome: "Close encounters politely using 'Баяртай' (Goodbye), 'Дараа уулзъя' (See you later), and 'Сайхан амраарай' (Have a good rest).",
    objectivesIntroduced: ["obj_a1_22_01_deploy_departure_formulas"],
    objectivesPracticed: [],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: ["gram_a1_polar_questions_uu_uu", "gram_a1_nominal_negation_bish"],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_vowel_diphthongs", "phono_stress_initial_and_full_vowels"],
    communicativeFunctionsIntroduced: ["comm_a1_03_departures_farewells"],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 3,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_social_interaction_courtesy", "lex_domain_daily_routines_lifestyle"],
    previousVocabularyReused: [],
    readingObjective: "Read email closing lines and social messaging farewells.",
    listeningObjective: "Identify various farewell formulas spoken at the end of meetings and broadcast programs.",
    writingObjective: "Write 3 appropriate farewell messages for a colleague leaving for the weekend.",
    spokenProductionObjective: "Say farewell to instructor and classmates with clear pronunciation and warm intonation.",
    registerTarget: "Everyday standard courteous",
    pragmaticTarget: "Concluding social and professional encounters gracefully.",
    prerequisiteLessonIds: ["les_a1_21_06_nominal_negation_checkpoint"],
    reviewsLessonIds: ["les_pre_a1_13_04_polite_farewells_bayartai"],
    reviewsUnitIds: ["unit_pre_a1_13_gratitude_apologies_politeness"],
    reviewReason: "Expand Pre-A1 basic farewells into nuanced situational departure formulas.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Warm, polite departure audio with terminal gentle pitch slope.",
    successCriteria: [
      "Select 'Сайхан амраарай' for evening/weekend departures.",
      "Accurately pronounce diphthong in 'баяртай' /pɑjr̥tʰæ/."
    ],
    masteryEvidence: [
      "Closes interactions smoothly without abrupt departures.",
      "Appropriately distinguishes between peer farewells and elder farewells."
    ],
    recommendedExerciseModalities: ["role_play_response", "matching", "dialogue_completion"]
  },
  {
    lessonId: "les_a1_22_02_gratitude_formulas_ih_bayarlalaa",
    unitId: "unit_a1_22_formal_departure_social_gratitude_f",
    cefrLevel: "A1",
    sequenceWithinUnit: 2,
    title: "Expressing Deep Gratitude: Танд маш их баярлалаа & Зүгээр ээ",
    lessonType: "vocabulary_introduction",
    primaryPurpose: "Introduce intensive and formal gratitude expressions ('Танд маш их баярлалаа', 'Гялайлаа') and polite receptions.",
    communicativeOutcome: "Express profound thanks to hosts, teachers, and service staff with appropriate honorific pronouns ('Танд').",
    objectivesIntroduced: ["obj_a1_22_02_express_formal_gratitude"],
    objectivesPracticed: ["obj_a1_22_01_deploy_departure_formulas"],
    objectivesReviewed: ["obj_a1_17_02_navigate_chi_ta_protocols"],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: ["gram_a1_pronouns_personal_nominative"],
    phonologyIntroduced: [],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_vowel_long_pairs"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: ["comm_a1_03_departures_farewells"],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 3,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 1,
    lexicalDomains: ["lex_domain_social_interaction_courtesy"],
    previousVocabularyReused: [],
    readingObjective: "Read formal thank-you letters and banquet toast transcripts.",
    listeningObjective: "Detect sincere gratitude inflections in customer service and hospitality audio.",
    writingObjective: "Write a short thank-you card to a host family: 'Танд маш их баярлалаа. Баяртай!'.",
    spokenProductionObjective: "Express formal thanks to an elder host with two-handed handshake posture.",
    registerTarget: "polite_formal",
    pragmaticTarget: "Acknowledging hospitality, gifts, and assistance in Mongolian culture.",
    prerequisiteLessonIds: ["les_a1_22_01_formal_departure_formulas_bayartai"],
    reviewsLessonIds: ["les_pre_a1_13_02_courtesy_formulas_bayarlalaa_uuchlaarai", "les_a1_17_02_politeness_protocols_chi_vs_ta"],
    reviewsUnitIds: ["unit_pre_a1_13_gratitude_apologies_politeness"],
    reviewReason: "Deepen Pre-A1 gratitude with honorific dative pronouns and intensive adverbs.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Authentic hospitality gratitude exchanges.",
    successCriteria: [
      "Use 'Танд' when thanking a superior or elder.",
      "Respond to gratitude with 'Зүгээр ээ' or 'Зүгээр зүгээр'."
    ],
    masteryEvidence: [
      "Demonstrates awareness that 'Гялайлаа' is an authentic traditional word of thanks.",
      "Accurately combines gratitude with departure formulas."
    ],
    recommendedExerciseModalities: ["role_play_response", "dialogue_completion", "matching"]
  },
  {
    lessonId: "les_a1_22_03_reading_farewell_cards_email_signoffs",
    unitId: "unit_a1_22_formal_departure_social_gratitude_f",
    cefrLevel: "A1",
    sequenceWithinUnit: 3,
    title: "Reading Farewell Cards, Postcards & Email Sign-Offs",
    lessonType: "reading_development",
    primaryPurpose: "Decode authentic handwritten postcards, greeting cards, and professional email sign-offs.",
    communicativeOutcome: "Extract sender, recipient, well-wishes, and closing formulas from 50-word written notes.",
    objectivesIntroduced: ["obj_a1_22_03_read_farewell_cards"],
    objectivesPracticed: ["obj_a1_22_01_deploy_departure_formulas", "obj_a1_22_02_express_formal_gratitude"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: ["gram_a1_nominal_negation_bish"],
    grammarReviewed: ["gram_a1_sov_word_order"],
    phonologyIntroduced: [],
    phonologyPracticed: [],
    phonologyReviewed: [],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: ["comm_a1_03_departures_farewells"],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 3,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 1,
    lexicalDomains: ["lex_domain_social_interaction_courtesy", "lex_domain_general_education_literacy"],
    previousVocabularyReused: [],
    readingObjective: "Read 3 authentic postcard texts wishing safe travels ('Аян замдаа сайн яваарай') and good health.",
    listeningObjective: "Match spoken airport farewells with written postcard messages.",
    writingObjective: "Draft a 4-line postcard to a friend concluding with 'Хүндэтгэсэн' (Respectfully) or 'Баяртай'.",
    spokenProductionObjective: "Read a farewell postcard text aloud with emotional resonance.",
    registerTarget: "Everyday standard courteous",
    pragmaticTarget: "Sending warm personal and professional written notes.",
    prerequisiteLessonIds: ["les_a1_22_02_gratitude_formulas_ih_bayarlalaa"],
    reviewsLessonIds: ["les_pre_a1_15_02_reading_short_postcards_and_notes"],
    reviewsUnitIds: ["unit_pre_a1_15_pre_a1_synthesis_and_literacy_capstone"],
    reviewReason: "Integrate A1 departure formulas into authentic reading genres.",
    audioSuitability: "standard_speech_synthesis_acceptable",
    audioPurpose: "Clear reading of heartfelt personal notes and postcards.",
    successCriteria: [
      "Identify the formal email closing formula 'Хүндэтгэсэн' (Respectfully).",
      "Extract departure destinations and dates from postcard texts."
    ],
    masteryEvidence: [
      "Understands 'Сайн яваарай' (Go well / Safe travels) used specifically for the person departing.",
      "Understands 'Сайн сууж байгаарай' (Stay well) used for the person remaining."
    ],
    recommendedExerciseModalities: ["reading_comprehension", "matching", "cloze"]
  },
  {
    lessonId: "les_a1_22_04_hotel_checkout_office_departure_roleplay",
    unitId: "unit_a1_22_formal_departure_social_gratitude_f",
    cefrLevel: "A1",
    sequenceWithinUnit: 4,
    title: "Speaking Workshop: Hotel Checkout & End-of-Day Office Departures",
    lessonType: "dialogue_work",
    primaryPurpose: "Simulate departing from an office at the end of the workday or checking out of a hotel reception.",
    communicativeOutcome: "Execute a multi-turn departure exchange: hand over keys, settle account, express thanks, and say goodbye.",
    objectivesIntroduced: ["obj_a1_22_04_execute_checkout_departure"],
    objectivesPracticed: ["obj_a1_22_01_deploy_departure_formulas", "obj_a1_22_02_express_formal_gratitude"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: ["gram_a1_polar_questions_uu_uu", "gram_a1_nominal_negation_bish"],
    grammarReviewed: ["gram_a1_nominal_predicate_zero_copula"],
    phonologyIntroduced: [],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_stress_initial_and_full_vowels"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: ["comm_a1_03_departures_farewells"],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 3,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_social_interaction_courtesy", "lex_domain_professions_workplace_office"],
    previousVocabularyReused: [],
    readingObjective: "Read a hotel checkout bill and receipt acknowledging payment.",
    listeningObjective: "Follow a 4-turn hotel checkout conversation between guest and receptionist.",
    writingObjective: "Write a 4-turn dialogue script of leaving an office on Friday evening.",
    spokenProductionObjective: "Perform hotel checkout role-play delivering departure formulas with polished confidence.",
    registerTarget: "polite_formal",
    pragmaticTarget: "Handling administrative service departures smoothly.",
    prerequisiteLessonIds: ["les_a1_22_03_reading_farewell_cards_email_signoffs"],
    reviewsLessonIds: ["les_a1_16_05_reception_desk_simulation", "les_a1_22_01_formal_departure_formulas_bayartai"],
    reviewsUnitIds: [],
    reviewReason: "Complete the full circle from reception arrival (Unit 16) to departure checkout.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Authentic hotel checkout dialogue with cash register and lobby ambiance.",
    successCriteria: [
      "Complete checkout role-play within 4 turns without English hesitation.",
      "Appropriately combine gratitude with farewell."
    ],
    masteryEvidence: [
      "Says 'Маш их баярлалаа, баяртай' naturally at conclusion.",
      "Responds to 'Сайхан амраарай' with 'Танд бас сайхан амраарай'."
    ],
    recommendedExerciseModalities: ["role_play_response", "dialogue_completion", "word_ordering"]
  },
  {
    lessonId: "les_a1_22_05_departures_and_gratitude_checkpoint",
    unitId: "unit_a1_22_formal_departure_social_gratitude_f",
    cefrLevel: "A1",
    sequenceWithinUnit: 5,
    title: "Formal Departure & Social Gratitude Synthesis",
    lessonType: "checkpoint",
    primaryPurpose: "Assess integrated command of formal departures, situational farewells, and deep gratitude formulas.",
    communicativeOutcome: "Gracefully conclude interactions across diverse social, professional, and domestic scenarios.",
    objectivesIntroduced: [],
    objectivesPracticed: ["obj_a1_22_01_deploy_departure_formulas", "obj_a1_22_02_express_formal_gratitude", "obj_a1_22_03_read_farewell_cards", "obj_a1_22_04_execute_checkout_departure"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: ["gram_a1_polar_questions_uu_uu", "gram_a1_nominal_negation_bish"],
    grammarReviewed: ["gram_a1_sov_word_order"],
    phonologyIntroduced: [],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_stress_initial_and_full_vowels"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: ["comm_a1_03_departures_farewells"],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 3,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_social_interaction_courtesy"],
    previousVocabularyReused: [],
    readingObjective: "Read 4 departure notes and match them to the correct social scenario.",
    listeningObjective: "Transcribe 4 dictated farewell sentences and assess register appropriateness.",
    writingObjective: "Write a short farewell email to a project supervisor thanking them and wishing them well.",
    spokenProductionObjective: "Execute an unscripted farewell role-play for oral proficiency assessment.",
    registerTarget: "Everyday standard courteous",
    pragmaticTarget: "Confirming mastery of departures and gratitude before Section 1 synthesis in Unit 23.",
    prerequisiteLessonIds: ["les_a1_22_04_hotel_checkout_office_departure_roleplay"],
    reviewsLessonIds: ["les_a1_22_01_formal_departure_formulas_bayartai", "les_a1_22_02_gratitude_formulas_ih_bayarlalaa", "les_a1_22_04_hotel_checkout_office_departure_roleplay"],
    reviewsUnitIds: ["unit_a1_20_demonstrative_deixis_", "unit_a1_21_negative_nominal_assertion_the_copu"],
    reviewReason: "Unit 22 synthesis evaluating social departure protocols.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Diagnostic audio evaluation items for departures and gratitude.",
    successCriteria: [
      "Achieve at least 90% on departure and gratitude competency test.",
      "Flawlessly select appropriate farewell formula for Friday afternoon vs elder visit."
    ],
    masteryEvidence: [
      "Executes the full departure ritual with authentic cultural polish.",
      "Combines verbal formulas with respectful physical conduct."
    ],
    recommendedExerciseModalities: ["dictation", "role_play_response", "error_correction"]
  },

  // =========================================================================
  // UNIT 23: Section Synthesis: Social Reception & Guest Welcome (unit_a1_23_section_synthesis_social_reception_)
  // Target: Prod=20, Rec=8, ProdExp=6, RecExp=3 | Lessons: 6
  // =========================================================================
  {
    lessonId: "les_a1_23_01_social_reception_greeting_and_entry",
    unitId: "unit_a1_23_section_synthesis_social_reception_",
    cefrLevel: "A1",
    sequenceWithinUnit: 1,
    title: "Guest Reception Stage 1: Welcoming Guests at the Threshold (Тавтай морилно уу)",
    lessonType: "dialogue_work",
    primaryPurpose: "Synthesize formal salutations, honorific address, and guest welcoming formulas at the door of a home or office.",
    communicativeOutcome: "Welcome guests warmly ('Тавтай морилно уу! Ороорой, дээшээ сууцгаа') and accept invitations to enter.",
    objectivesIntroduced: ["obj_a1_23_01_welcome_guests_at_threshold"],
    objectivesPracticed: [],
    objectivesReviewed: ["obj_a1_16_02_deliver_formal_time_greetings", "obj_a1_17_02_navigate_chi_ta_protocols"],
    grammarIntroduced: [],
    grammarPracticed: ["gram_a1_pronouns_personal_nominative", "gram_a1_sov_word_order"],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_stress_initial_and_full_vowels"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: ["comm_a1_02_formal_elder_greetings"],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 4,
    newReceptiveLemmaTarget: 2,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 1,
    lexicalDomains: ["lex_domain_social_interaction_courtesy", "lex_domain_household_home_environment"],
    previousVocabularyReused: [],
    readingObjective: "Read welcome signage (Тавтай морилно уу) and doorstep greeting transcripts.",
    listeningObjective: "Follow authentic threshold welcoming exchanges in Mongolian homes.",
    writingObjective: "Write a 3-turn greeting exchange of guests arriving for dinner.",
    spokenProductionObjective: "Welcome an instructor into a room using authentic guest hospitable formulas.",
    registerTarget: "polite_formal",
    pragmaticTarget: "Observing Mongolian threshold etiquette (never stepping on the threshold sill).",
    prerequisiteLessonIds: ["les_a1_22_05_departures_and_gratitude_checkpoint"],
    reviewsLessonIds: ["les_a1_16_02_formal_time_greetings_mori", "les_a1_16_03_inquiry_after_peace_amar_mend"],
    reviewsUnitIds: ["unit_a1_16_standard_salutations_time_of_day_gr"],
    reviewReason: "Begin Section 1 capstone by synthesizing greeting rituals into live social reception.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Warm domestic threshold welcome with tea preparation sounds.",
    successCriteria: [
      "Deploy 'Тавтай морилно уу' smoothly when greeting arriving guests.",
      "Exhibit cultural awareness of threshold etiquette."
    ],
    masteryEvidence: [
      "Invites guests inside using 'Ороорой' (Please enter).",
      "Welcomes elders with utmost honorific deference."
    ],
    recommendedExerciseModalities: ["role_play_response", "dialogue_completion", "matching"]
  },
  {
    lessonId: "les_a1_23_02_social_reception_introductions_and_origin",
    unitId: "unit_a1_23_section_synthesis_social_reception_",
    cefrLevel: "A1",
    sequenceWithinUnit: 2,
    title: "Guest Reception Stage 2: Mutual Introductions, Identity, and Provenance",
    lessonType: "dialogue_work",
    primaryPurpose: "Synthesize personal pronouns, zero-copula predication, origin expressions, and deixis around the reception table.",
    communicativeOutcome: "Introduce all present parties, state their professions, nationalities, and regional origins smoothly.",
    objectivesIntroduced: ["obj_a1_23_02_execute_table_introductions"],
    objectivesPracticed: ["obj_a1_23_01_welcome_guests_at_threshold"],
    objectivesReviewed: ["obj_a1_18_01_form_zero_copula_clauses", "obj_a1_18_02_state_nationality_origin", "obj_a1_20_01_use_ene_ter_demonstratives"],
    grammarIntroduced: [],
    grammarPracticed: ["gram_a1_nominal_predicate_zero_copula", "gram_a1_pronouns_demonstrative_ene_ter", "gram_a1_pronouns_personal_nominative"],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_stress_initial_and_full_vowels"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: ["comm_a1_06_self_introduction_name"],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 4,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 1,
    lexicalDomains: ["lex_domain_personal_information_identity", "lex_domain_social_interaction_courtesy"],
    previousVocabularyReused: [],
    readingObjective: "Read a seating chart and guest list specifying identities, professions, and affiliations.",
    listeningObjective: "Track multi-party introductions around a conference or dinner table.",
    writingObjective: "Write a 5-sentence paragraph introducing 3 international delegates at a reception.",
    spokenProductionObjective: "Introduce self and a partner to the host family, stating names, jobs, and home countries.",
    registerTarget: "Everyday standard courteous",
    pragmaticTarget: "Fostering mutual connection and establishing rapport among new acquaintances.",
    prerequisiteLessonIds: ["les_a1_23_01_social_reception_greeting_and_entry"],
    reviewsLessonIds: ["les_a1_17_05_interviewing_classmates_protocols", "les_a1_18_05_introducing_oneself_and_others_origin", "les_a1_20_05_introducing_colleagues_by_deixis"],
    reviewsUnitIds: ["unit_a1_17_personal_pronouns_direct_address_pr", "unit_a1_18_zero_copula_identity_origin_predica", "unit_a1_20_demonstrative_deixis_"],
    reviewReason: "Integrate Units 17, 18, and 20 into cohesive social introductions.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Authentic multi-party table introductions with background tea pouring.",
    successCriteria: [
      "Introduce self and companion with zero grammatical pause.",
      "Deploy zero-copula identity statements accurately across all participants."
    ],
    masteryEvidence: [
      "Uses 'Энэ бол...' and personal pronouns effortlessly.",
      "Accurately answers origin inquiries without hesitation."
    ],
    recommendedExerciseModalities: ["role_play_response", "dialogue_completion", "word_ordering"]
  },
  {
    lessonId: "les_a1_23_03_social_reception_clarification_and_inquiry",
    unitId: "unit_a1_23_section_synthesis_social_reception_",
    cefrLevel: "A1",
    sequenceWithinUnit: 3,
    title: "Guest Reception Stage 3: Inquiring, Clarifying, and Negating Misconceptions",
    lessonType: "dialogue_work",
    primaryPurpose: "Synthesize polar questions (уу/үү) and nominal negation with 'биш' during polite reception conversation.",
    communicativeOutcome: "Clarify misunderstandings, answer inquiries about backgrounds, and confirm details gracefully ('Та англи хүн үү?' - 'Үгүй ээ, би америк.').",
    objectivesIntroduced: ["obj_a1_23_03_clarify_reception_inquiries"],
    objectivesPracticed: ["obj_a1_23_02_execute_table_introductions"],
    objectivesReviewed: ["obj_a1_19_01_form_polar_questions_uu_uu", "obj_a1_21_01_negate_nominal_predicates_bish"],
    grammarIntroduced: [],
    grammarPracticed: ["gram_a1_nominal_negation_bish", "gram_a1_polar_questions_uu_uu"],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_vowel_harmony_masc_fem"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: ["comm_a1_06_self_introduction_name"],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 3,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_social_interaction_courtesy", "lex_domain_countries_nationalities_languages"],
    previousVocabularyReused: [],
    readingObjective: "Read multi-turn conversation transcripts featuring questions, denials, and corrections.",
    listeningObjective: "Detect true and false claims in reception audio dialogues.",
    writingObjective: "Write a 4-turn dialogue where a mistaken profession or nationality is clarified politely.",
    spokenProductionObjective: "Participate in an inquiry-and-clarification role-play with an interlocutor.",
    registerTarget: "Everyday standard courteous",
    pragmaticTarget: "Handling social inquiries smoothly and preventing awkward cultural misinterpretations.",
    prerequisiteLessonIds: ["les_a1_23_02_social_reception_introductions_and_origin"],
    reviewsLessonIds: ["les_a1_19_01_polar_particles_uu_uu_distribution", "les_a1_21_02_correcting_false_assumptions_clarification"],
    reviewsUnitIds: ["unit_a1_19_polar_inquiries_polar_question_part", "unit_a1_21_negative_nominal_assertion_the_copu"],
    reviewReason: "Integrate Units 19 and 21 polar inquiries and negative assertions.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Authentic social inquiry and clarification dialogue.",
    successCriteria: [
      "Correctly use polar question particles and 'биш' under conversational pressure.",
      "Maintain polite register throughout correction exchanges."
    ],
    masteryEvidence: [
      "Flawlessly uses 'Үгүй ээ, ... биш' without syntactic hesitation.",
      "Selects harmonic question particle with 100% accuracy."
    ],
    recommendedExerciseModalities: ["role_play_response", "dialogue_completion", "matching"]
  },
  {
    lessonId: "les_a1_23_04_reading_complete_social_vignette",
    unitId: "unit_a1_23_section_synthesis_social_reception_",
    cefrLevel: "A1",
    sequenceWithinUnit: 4,
    title: "Reading Synthesis: A Full Social Reception & Diplomatic Visit Narrative",
    lessonType: "reading_development",
    primaryPurpose: "Decode a comprehensive 55-word illustrated narrative describing a complete social reception from arrival to farewell.",
    communicativeOutcome: "Read and comprehend a cohesive story incorporating all Section 1 grammatical and communicative targets.",
    objectivesIntroduced: ["obj_a1_23_04_read_comprehensive_vignette"],
    objectivesPracticed: ["obj_a1_23_01_welcome_guests_at_threshold", "obj_a1_23_02_execute_table_introductions", "obj_a1_23_03_clarify_reception_inquiries"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: ["gram_a1_sov_word_order", "gram_a1_pronouns_personal_nominative", "gram_a1_nominal_predicate_zero_copula", "gram_a1_nominal_negation_bish"],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: [],
    phonologyReviewed: [],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: ["comm_a1_02_formal_elder_greetings", "comm_a1_06_self_introduction_name"],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 3,
    newReceptiveLemmaTarget: 2,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 1,
    lexicalDomains: ["lex_domain_social_interaction_courtesy", "lex_domain_general_education_literacy"],
    previousVocabularyReused: [],
    readingObjective: "Read the 55-word narrative: 'Өглөө 10 цагт зочид ирэв. Бат багш: Тавтай морилно уу! Тэд Америк болон Японоос ирсэн...' and answer 5 comprehension questions.",
    listeningObjective: "Follow the narrated story read aloud at natural tempo (90 wpm).",
    writingObjective: "Write a 4-sentence summary of the reception event in chronological order.",
    spokenProductionObjective: "Retell the main events of the story aloud using target vocabulary.",
    registerTarget: "Everyday standard courteous",
    pragmaticTarget: "Reading connected narrative texts at the conclusion of CEFR A1 Section 1.",
    prerequisiteLessonIds: ["les_a1_23_03_social_reception_clarification_and_inquiry"],
    reviewsLessonIds: ["les_a1_16_04_reading_daily_greeting_schedules", "les_a1_18_04_reading_international_participant_roster"],
    reviewsUnitIds: ["unit_a1_16_standard_salutations_time_of_day_gr", "unit_a1_18_zero_copula_identity_origin_predica"],
    reviewReason: "Capstone reading task validating Section 1 textual literacy.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Narrative storytelling voice with natural phrasing and pauses.",
    successCriteria: [
      "Answer all 5 reading comprehension questions correctly without English translation.",
      "Demonstrate full parsing of SOV clauses and nominal predicates in connected text."
    ],
    masteryEvidence: [
      "Extracts all character relationships and factual data accurately.",
      "Reads narrative aloud with correct phrasing and intonational cadences."
    ],
    recommendedExerciseModalities: ["reading_comprehension", "cloze", "sentence_transformation"]
  },
  {
    lessonId: "les_a1_23_05_interactive_social_reception_simulation",
    unitId: "unit_a1_23_section_synthesis_social_reception_",
    cefrLevel: "A1",
    sequenceWithinUnit: 5,
    title: "Speaking Workshop: End-to-End Social Reception Simulation",
    lessonType: "dialogue_work",
    primaryPurpose: "Execute a continuous, multi-turn role-play simulation spanning arrival greetings, introductions, inquiries, tea drinking, and farewells.",
    communicativeOutcome: "Demonstrate fluid, unscripted conversational competence across the complete lifecycle of a social visit.",
    objectivesIntroduced: ["obj_a1_23_05_execute_full_reception_simulation"],
    objectivesPracticed: ["obj_a1_23_01_welcome_guests_at_threshold", "obj_a1_23_02_execute_table_introductions", "obj_a1_23_03_clarify_reception_inquiries"],
    objectivesReviewed: ["obj_a1_22_01_deploy_departure_formulas", "obj_a1_22_02_express_formal_gratitude"],
    grammarIntroduced: [],
    grammarPracticed: ["gram_a1_sov_word_order", "gram_a1_pronouns_personal_nominative", "gram_a1_nominal_predicate_zero_copula", "gram_a1_pronouns_demonstrative_ene_ter", "gram_a1_nominal_negation_bish"],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_stress_initial_and_full_vowels"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: ["comm_a1_02_formal_elder_greetings", "comm_a1_06_self_introduction_name"],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 3,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_social_interaction_courtesy"],
    previousVocabularyReused: [],
    readingObjective: "Read role-play briefing cards assigning secret roles and character objectives.",
    listeningObjective: "Follow unscripted multi-speaker role-play turns dynamically.",
    writingObjective: "Write a post-event journal entry summarizing the social gathering.",
    spokenProductionObjective: "Maintain active, culturally authentic role-play for 5 continuous turns.",
    registerTarget: "Everyday standard courteous",
    pragmaticTarget: "Proving communicative agility in holistic cultural simulations.",
    prerequisiteLessonIds: ["les_a1_23_04_reading_complete_social_vignette"],
    reviewsLessonIds: ["les_a1_16_05_reception_desk_simulation", "les_a1_22_04_hotel_checkout_office_departure_roleplay"],
    reviewsUnitIds: ["unit_a1_16_standard_salutations_time_of_day_gr", "unit_a1_22_formal_departure_social_gratitude_f"],
    reviewReason: "Live communicative integration of entire Section 1 functional repertoire.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Authentic dynamic role-play interaction with varied native voices.",
    successCriteria: [
      "Sustain continuous role-play for 5 turns without breaking character or falling back to English.",
      "Employ culturally appropriate physical gestures (posture, hand positions)."
    ],
    masteryEvidence: [
      "Transitions effortlessly from greeting to introduction, inquiry, clarification, and farewell.",
      "Speaks with confidence and authentic Mongolian polite cadence."
    ],
    recommendedExerciseModalities: ["role_play_response", "dialogue_completion", "short_answer_writing"]
  },
  {
    lessonId: "les_a1_23_06_a1_section_1_capstone_exam",
    unitId: "unit_a1_23_section_synthesis_social_reception_",
    cefrLevel: "A1",
    sequenceWithinUnit: 6,
    title: "A1 Section 1 Comprehensive Benchmark Examination",
    lessonType: "checkpoint",
    primaryPurpose: "Administer the formal, comprehensive benchmark examination for CEFR A1 Section 1 (Identity, Courtesy & Nominal Clauses).",
    communicativeOutcome: "Formally certify readiness to advance to Section 2 (Locative, Existential & Possessive Constructions).",
    objectivesIntroduced: [],
    objectivesPracticed: ["obj_a1_23_01_welcome_guests_at_threshold", "obj_a1_23_02_execute_table_introductions", "obj_a1_23_03_clarify_reception_inquiries", "obj_a1_23_04_read_comprehensive_vignette", "obj_a1_23_05_execute_full_reception_simulation"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: ["gram_a1_sov_word_order", "gram_a1_pronouns_personal_nominative", "gram_a1_nominal_predicate_zero_copula", "gram_a1_pronouns_demonstrative_ene_ter", "gram_a1_nominal_negation_bish"],
    grammarReviewed: ["gram_a1_polar_questions_uu_uu", "gram_a1_case_nominative_unmarked"],
    phonologyIntroduced: [],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_stress_initial_and_full_vowels", "phono_vowel_harmony_masc_fem"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: ["comm_a1_02_formal_elder_greetings", "comm_a1_06_self_introduction_name"],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 3,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_social_interaction_courtesy", "lex_domain_personal_information_identity"],
    previousVocabularyReused: [],
    readingObjective: "Read an unadapted 60-word official reception transcript and answer 6 detailed diagnostic questions.",
    listeningObjective: "Transcribe 6 complex A1 sentences and identify social registers with 100% accuracy.",
    writingObjective: "Write a structured 6-sentence personal and team introduction essay demonstrating all Section 1 grammatical forms.",
    spokenProductionObjective: "Complete a standardized oral interview covering greeting, identity, provenance, polar inquiries, negation, and farewell.",
    registerTarget: "Everyday standard courteous",
    pragmaticTarget: "Certifying mastery across all CEFR A1 Section 1 competencies.",
    prerequisiteLessonIds: ["les_a1_23_05_interactive_social_reception_simulation"],
    reviewsLessonIds: ["les_a1_16_06_salutations_and_sov_synthesis", "les_a1_17_06_pronouns_and_address_checkpoint", "les_a1_18_06_identity_predication_checkpoint", "les_a1_19_06_polar_inquiries_synthesis_checkpoint", "les_a1_20_06_demonstrative_deixis_checkpoint", "les_a1_21_06_nominal_negation_checkpoint", "les_a1_22_05_departures_and_gratitude_checkpoint"],
    reviewsUnitIds: ["unit_a1_16_standard_salutations_time_of_day_gr", "unit_a1_21_negative_nominal_assertion_the_copu"],
    reviewReason: "A1 Section 1 definitive capstone and benchmark assessment.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Standardized diagnostic oral examination prompts and test items.",
    successCriteria: [
      "Achieve an overall composite score of >=85% across Reading, Listening, Writing, and Speaking modules.",
      "Demonstrate zero persistent fossilized errors in SOV syntax, zero-copula identity, or harmonic polar particles."
    ],
    masteryEvidence: [
      "Flawlessly commands all 7 personal pronouns, zero-copula predication, deixis, and nominal negation.",
      "Deploys socially nuanced Mongolian courtesy formulas naturally and accurately."
    ],
    recommendedExerciseModalities: ["dictation", "role_play_response", "error_correction", "reading_comprehension"]
  }
];
