export interface GrammarConceptSpec {
  conceptId: string;
  englishTitle: string;
  mongolianTitle: string;
  category: string;
  firstTargetLevel: string;
  masteryTargetLevel: string;
  prerequisites: string[];
  recommendedPriorConcepts: string[];
  unlocks: string[];
  modality: "receptive" | "productive" | "both";
  vowelHarmonyRequired: boolean;
  morphologyRequired: boolean;
  recursInAdvanced: boolean;
  knownComplications: string[];
  description: string;
  verificationStatus: "VERIFIED" | "NEEDS REVISION" | "UNCERTAIN / SOURCE REVIEW REQUIRED";
  pedagogicalLabel: string;
  linguisticAnalysis: string;
  learnerExplanation: string;
  technicalNotes: string;
}

export const grammarA1Data: GrammarConceptSpec[] = [
  {
    conceptId: "gram_a1_nominal_predicate_zero_copula",
    englishTitle: "Nominal Predicate and Zero Copula",
    mongolianTitle: "Нэрийн өгүүлэхүүн ба тэг холбоос",
    category: "Clause Architecture",
    firstTargetLevel: "A1",
    masteryTargetLevel: "A1",
    prerequisites: ["phono_cyr_35_alphabet"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_a1_nominal_negation_bish", "gram_a1_existential_baina_baihgui"],
    modality: "productive",
    vowelHarmonyRequired: false,
    morphologyRequired: false,
    recursInAdvanced: false,
    knownComplications: ["English speakers often try to insert an overt 'is/am/are' copula where none exists in Mongolian."],
    description: "In simple equative and attributive sentences (X is Y), Mongolian places the subject first and predicate noun/adjective second without any overt copula verb (e.g. Би оюутан 'I [am a] student', Энэ ном 'This [is a] book').",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Stating Who or What Something Is: 'I am a student' (Zero Copula)",
    linguisticAnalysis: "Zero copula equative construction with nominal predicate in nominative case.",
    learnerExplanation: "To say 'I am a student' in Mongolian, simply put the words together: Би оюутан. There is no word for 'am', 'is', or 'are' in basic present-tense identification.",
    technicalNotes: "Fundamental syntactic baseline; prevent learners from calquing English 'to be' into zero-copula sentences."
  },
  {
    conceptId: "gram_a1_nominal_negation_bish",
    englishTitle: "Nominal Negation with Particle 'Биш'",
    mongolianTitle: "Нэрийн өгүүлэхүүнийг 'Биш' сул үгээр үгүйсгэх",
    category: "Clause Architecture",
    firstTargetLevel: "A1",
    masteryTargetLevel: "A1",
    prerequisites: ["gram_a1_nominal_predicate_zero_copula"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_a1_existential_baina_baihgui"],
    modality: "productive",
    vowelHarmonyRequired: false,
    morphologyRequired: false,
    recursInAdvanced: false,
    knownComplications: ["Must not be confused with verbal negation (-гүй or үгүй). Биш only negates nouns and pronouns."],
    description: "Equative and nominal sentences are negated using the postpositional negative particle биш placed directly after the predicate noun (e.g. Би багш биш 'I am not a teacher', Энэ минийх биш 'This is not mine').",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Saying 'Not': 'I am not a teacher' (Биш)",
    linguisticAnalysis: "Post-nominal negative particle (*bisi) functioning as the negative counterpart of the zero copula.",
    learnerExplanation: "To say you are NOT something, add биш right after the noun: Би багш биш ('I am not a teacher'). Remember: биш is only for nouns, never verbs.",
    technicalNotes: "Strict complementary distribution with verbal negation suffix -гүй."
  },
  {
    conceptId: "gram_a1_existential_baina_baihgui",
    englishTitle: "Existential and Locative Predicates: Байна, Байхгүй, Бий",
    mongolianTitle: "Орших, байхын утга илэрхийлэх: Байна, Байхгүй, Бий",
    category: "Clause Architecture",
    firstTargetLevel: "A1",
    masteryTargetLevel: "A1",
    prerequisites: ["gram_a1_nominal_predicate_zero_copula"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_a1_sov_word_order", "gram_a1_case_dative_locative_location"],
    modality: "productive",
    vowelHarmonyRequired: false,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["Distinguishing existential байна (there is) from progressive aspect marker -ж байна."],
    description: "Expressing existence ('there is/are') and presence using affirmative байна or formal/timeless бий, and negation using байхгүй (e.g. Энд цай байна 'There is tea here', Надад зав байхгүй 'I have no free time').",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "There is / There isn't: Existence & Presence (Байна / Байхгүй)",
    linguisticAnalysis: "Existential/locative copular predicates based on auxiliary stem бай- (*bayi-).",
    learnerExplanation: "Use байна to say something exists or is present ('There is tea'). Use байхгүй to say something is absent or doesn't exist ('There is no tea').",
    technicalNotes: "Forms the bedrock of Mongolian spatial orientation and possession constructions."
  },
  {
    conceptId: "gram_a1_sov_word_order",
    englishTitle: "Basic Constituent Order: Subject-Object-Verb (SOV)",
    mongolianTitle: "Өгүүлбэрийн үндсэн бүтэц: Эзэн бие - Тусагдахуун - Өгүүлэхүүн",
    category: "Clause Architecture",
    firstTargetLevel: "A1",
    masteryTargetLevel: "A1",
    prerequisites: ["gram_a1_existential_baina_baihgui"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_a1_polar_questions_uu_uu", "gram_a1_case_accusative_definite"],
    modality: "productive",
    vowelHarmonyRequired: false,
    morphologyRequired: false,
    recursInAdvanced: true,
    knownComplications: ["Modifiers, adverbials, and objects must strictly precede their head verbs; English SVO habits must be unlearned."],
    description: "Modern Mongolian is strictly head-final and verb-final. Normal neutral word order is Subject - Temporal Adverbial - Locative Adverbial - Direct/Indirect Object - Verb/Predicate (e.g. Би өнөөдөр ном уншина 'I will read a book today').",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Sentence Structure: Verb Always Comes at the End (SOV Order)",
    linguisticAnalysis: "Strict head-final syntactic typology with canonical left-branching constituent structure.",
    learnerExplanation: "In Mongolian sentences, the main verb always stands at the very end. The pattern is: Who -> When -> Where -> What -> Does action.",
    technicalNotes: "Enforce verb-final discipline across all basic sentence drilling exercises."
  },
  {
    conceptId: "gram_a1_polar_questions_uu_uu",
    englishTitle: "Polar (Yes/No) Questions with Particle Уу / Үү",
    mongolianTitle: "Асуух сул үг Уу / Үү-гээр асуулт бүтээх",
    category: "Clause Architecture",
    firstTargetLevel: "A1",
    masteryTargetLevel: "A1",
    prerequisites: ["gram_a1_sov_word_order", "phono_suffix_vowel_selection_fourfold"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_a1_content_questions_be_ve"],
    modality: "productive",
    vowelHarmonyRequired: true,
    morphologyRequired: false,
    recursInAdvanced: false,
    knownComplications: ["Selecting masculine уу vs feminine үү, and recognizing post-vocalic alternations (юу/юү)."],
    description: "Polar yes/no questions are formed by placing the interrogative particle уу (masculine) or үү (feminine) sentence-finally (e.g. Та оюутан уу? 'Are you a student?', Чи завтай юу? 'Are you free?').",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Asking Yes/No Questions: The Ending Tag (Уу / Үү)",
    linguisticAnalysis: "Sentence-final interrogative enclitic (*uu/*üü) undergoing back/front vowel harmony.",
    learnerExplanation: "To turn any statement into a yes/no question, add уу (for words with masculine vowels а, о, у) or үү (for words with feminine vowels э, ө, ү) at the end.",
    technicalNotes: "Highlight glide insertion: words ending in long vowels or diphthongs take юу / юү."
  },
  {
    conceptId: "gram_a1_content_questions_be_ve",
    englishTitle: "Content Questions with Interrogatives and Particle Бэ / Вэ",
    mongolianTitle: "Асуух төлөөний үг ба Бэ / Вэ сул үгээр асуулт бүтээх",
    category: "Clause Architecture",
    firstTargetLevel: "A1",
    masteryTargetLevel: "A1",
    prerequisites: ["gram_a1_polar_questions_uu_uu"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_a1_pronouns_personal_nominative"],
    modality: "productive",
    vowelHarmonyRequired: true,
    morphologyRequired: false,
    recursInAdvanced: false,
    knownComplications: ["Choosing between бэ (after nasal and specific consonant codas) and вэ (after vowels and other consonants)."],
    description: "Questions containing wh-words (хэн, юу, хаана, хэзээ, ямар, яагаад) require the sentence-final question particle бэ or вэ (e.g. Энэ юу вэ? 'What is this?', Та хэн бэ? 'Who are you?').",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Asking Who, What, Where Questions: Question Tags (Бэ / Вэ)",
    linguisticAnalysis: "Wh-interrogative enclitic with morphophonemic allomorphy conditioned by preceding segment coda sonority.",
    learnerExplanation: "Whenever you use question words like Who (хэн), What (юу), Where (хаана), or When (хэзээ), finish your question with either бэ (after м, н, л) or вэ (after vowels and other sounds).",
    technicalNotes: "Distinct enclitic from polar уу/үү; cannot be mixed within the same clause."
  },
  {
    conceptId: "gram_a1_pronouns_personal_nominative",
    englishTitle: "Personal Pronouns in Nominative (Би, Чи, Та, Тэр, Бид, Та нар, Тэд)",
    mongolianTitle: "Биеийн төлөөний нэрс: Нэрлэхийн тийн ялгал",
    category: "Pronouns & Deixis",
    firstTargetLevel: "A1",
    masteryTargetLevel: "A1",
    prerequisites: ["gram_a1_nominal_predicate_zero_copula"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_a1_pronouns_demonstrative_ene_ter", "gram_a1_case_genitive_possession"],
    modality: "productive",
    vowelHarmonyRequired: false,
    morphologyRequired: false,
    recursInAdvanced: false,
    knownComplications: ["Understanding the politeness distinction between casual чи and respectful/plural Та."],
    description: "The personal pronoun inventory: би (I), чи (you, informal), Та (you, polite/formal), тэр (he/she/it), бид / бид нар (we), та нар (you, plural), тэд / тэд нар (they).",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Talking About People: I, You, He, She, We & They",
    linguisticAnalysis: "Pronominal closed-class paradigm in nominative case differentiating speaker honorific social distance.",
    learnerExplanation: "Use би for 'I', чи for close friends and peers, and Та for elders, teachers, or strangers. Тэр covers 'he', 'she', and 'it'.",
    technicalNotes: "Social register awareness is critical: using чи with an elder violates cultural respect norms."
  },
  {
    conceptId: "gram_a1_pronouns_demonstrative_ene_ter",
    englishTitle: "Demonstrative Pronouns and Deictic Pointers (Энэ, Тэр, Эдгээр, Тэдгээр)",
    mongolianTitle: "Заах төлөөний нэрс: Энэ, тэр, эдгээр, тэдгээр",
    category: "Pronouns & Deixis",
    firstTargetLevel: "A1",
    masteryTargetLevel: "A1",
    prerequisites: ["gram_a1_pronouns_personal_nominative"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_a1_noun_phrase_attributive_adjective"],
    modality: "productive",
    vowelHarmonyRequired: false,
    morphologyRequired: false,
    recursInAdvanced: false,
    knownComplications: ["Тэр acts both as third-person personal pronoun ('he/she/that person') and distal demonstrative ('that')."],
    description: "Proximal энэ (this/these) and distal тэр (that/those), and their explicit plural forms эдгээр (these) and тэдгээр (those) (e.g. Энэ ном 'This book', Тэр байшин 'That building').",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Pointing to Things: This & That (Энэ / Тэр)",
    linguisticAnalysis: "Binary spatial deictic system: proximal (*ene) vs distal (*tere).",
    learnerExplanation: "Use энэ for objects close to you ('this'), and тэр for objects further away ('that'). In plural contexts, you can also use эдгээр ('these') and тэдгээр ('those').",
    technicalNotes: "Demonstratives do not decline or take plural endings when modifying nouns directly."
  },
  {
    conceptId: "gram_a1_noun_phrase_attributive_adjective",
    englishTitle: "Noun Phrase Structure: Attributive Adjectives",
    mongolianTitle: "Нэр үгийн холбоо: Тэмдэг нэрийн байрлал",
    category: "Noun Phrase Structure",
    firstTargetLevel: "A1",
    masteryTargetLevel: "A1",
    prerequisites: ["gram_a1_pronouns_demonstrative_ene_ter"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_a1_noun_plural_markers"],
    modality: "productive",
    vowelHarmonyRequired: false,
    morphologyRequired: false,
    recursInAdvanced: false,
    knownComplications: ["Adjectives never agree in gender, number, or case with the head noun in Mongolian; they remain invariant."],
    description: "Adjectives in Mongolian always precede the noun they modify and never take plural or case inflection when functioning attributively (e.g. том гэр 'big yurt', сайхан хот 'beautiful city', том гэрүүдэд 'in the big yurts').",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Describing Things: Word Order for Adjectives (Big House)",
    linguisticAnalysis: "Pre-nominal invariant adjectival modification with zero grammatical agreement.",
    learnerExplanation: "Adjectives always go BEFORE the noun, and they NEVER change their form. Whether the noun is singular or plural, the adjective stays exactly the same: том гэр ('big yurt'), том гэрүүд ('big yurts').",
    technicalNotes: "Greatly simplifies syntax compared to Indo-European concord systems."
  },
  {
    conceptId: "gram_a1_noun_plural_markers",
    englishTitle: "Nominal Plural Markers (-ууд/-үүд, -чууд/-чүүд, -д, -с)",
    mongolianTitle: "Нэр үгийн олон тооны дагавар (-ууд/-үүд, -чууд/-чүүд, -д, -с)",
    category: "Noun Phrase Structure",
    firstTargetLevel: "A1",
    masteryTargetLevel: "A1",
    prerequisites: ["gram_a1_noun_phrase_attributive_adjective", "phono_suffix_vowel_selection_fourfold"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_a1_numerals_cardinal_counting"],
    modality: "productive",
    vowelHarmonyRequired: true,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["Nouns accompanied by numerals or quantifiers NEVER take plural markers (e.g. гурван хүн, NOT *гурван хүмүүс)."],
    description: "Plural suffixation in Mongolian: productive -ууд/-үүд for general nouns (ном -> номууд), -чууд/-чүүд for groups of people (монголчууд), and non-productive suffixes -д (багш -> багш нар / багш нар) and -с (нөхөр -> нөхөд).",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Making Nouns Plural: Adding More Than One (-ууд / -үүд)",
    linguisticAnalysis: "Agglutinative nominal number marking conditioned by animacy and semantic collective classes.",
    learnerExplanation: "To make words plural, add -ууд or -үүд (e.g. номууд = books). For groups of people, use -чууд / -чүүд (монголчууд = Mongolians). Remember: if a number is in front, do not add any plural ending!",
    technicalNotes: "Highlight the strict constraint: Cardinal Numeral + Noun[SINGULAR]."
  },
  {
    conceptId: "gram_a1_numerals_cardinal_counting",
    englishTitle: "Cardinal Numbers (1-100) and Counting Quantified Nouns",
    mongolianTitle: "Үндсэн тооны нэр ба тоологдох нэрсийг хэрэглэх ёс",
    category: "Number & Quantification",
    firstTargetLevel: "A1",
    masteryTargetLevel: "A1",
    prerequisites: ["gram_a1_noun_plural_markers"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_a1_case_genitive_possession"],
    modality: "productive",
    vowelHarmonyRequired: false,
    morphologyRequired: false,
    recursInAdvanced: false,
    knownComplications: ["The numeral 3 has stem variations: гурав (citation) vs гурван (attributive before nouns). Similarly дөрөв/дөрвөн, тав/таван."],
    description: "Cardinal numbers 1 to 100 and the unstable -н retained in attributive counting position (нэг, хоёр, гурван ном, дөрвөн оюутан, арван гэр).",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Counting Items: Numbers 1 to 100 with Objects",
    linguisticAnalysis: "Cardinal numeral syntax with unstable stem-final nasal retention in attributive position.",
    learnerExplanation: "When counting objects, numbers drop their final vowel and keep an -н sound: гурав becomes гурван ном ('three books'), дөрөв becomes дөрвөн ширээ ('four tables').",
    technicalNotes: "Core morphophonemic rule that learners must master early for shopping and daily transactions."
  },
  {
    conceptId: "gram_a1_case_nominative_unmarked",
    englishTitle: "Nominative / Unmarked Case: Subject and Citation Function",
    mongolianTitle: "Нэрлэхийн тийн ялгал (Нөхцөлгүй тийн ялгал)",
    category: "Case System",
    firstTargetLevel: "A1",
    masteryTargetLevel: "A1",
    prerequisites: ["gram_a1_sov_word_order"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_a1_case_genitive_possession"],
    modality: "productive",
    vowelHarmonyRequired: false,
    morphologyRequired: false,
    recursInAdvanced: false,
    knownComplications: ["Indefinite non-specific direct objects also appear in the unmarked nominative form."],
    description: "The zero-marked base form of nouns functioning as sentence subject, citation dictionary form, or indefinite non-specific direct object (e.g. Ном ширээн дээр байна 'A book is on the desk', Би ном авсан 'I bought a book').",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Base Form of Words: The Starting Point (Nominative)",
    linguisticAnalysis: "Unmarked zero-morpheme case serving as subject, citation lemma, and non-referential object.",
    learnerExplanation: "This is the dictionary form of a noun without any endings attached. It is used when the noun is doing the action (the subject) or when talking about something in general.",
    technicalNotes: "Zero-marking on indefinite non-specific objects contrasts with overt accusative -ыг."
  },
  {
    conceptId: "gram_a1_case_genitive_possession",
    englishTitle: "Genitive Case: Possession and Nominal Modification (-ын/-ийн/-ы/-ий/-н)",
    mongolianTitle: "Харьяалахын тийн ялгал: Өмчлөх ба тодотгох утга",
    category: "Case System",
    firstTargetLevel: "A1",
    masteryTargetLevel: "A1",
    prerequisites: ["gram_a1_case_nominative_unmarked", "phono_suffix_vowel_selection_fourfold"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_a1_case_accusative_definite", "gram_a1_possessive_pronouns_minii_chiniih"],
    modality: "productive",
    vowelHarmonyRequired: true,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["Allomorph distribution: -ын/-ийн after consonants, -ы/-ий after vowels, -н after long vowels/diphthongs, and -ны/-ний on unstable 'n' stems."],
    description: "The genitive case expresses possession, association, and attributive relation (e.g. багшийн ном 'the teacher's book', Монголын түүх 'the history of Mongolia', модны навч 'leaves of the tree').",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Showing Ownership: 's and 'of' (-ын / -ийн)",
    linguisticAnalysis: "Genitive case marker with phonologically conditioned allomorphy expressing adnominal possession and attribution.",
    learnerExplanation: "To show that something belongs to someone, add the genitive ending: багш ('teacher') -> багшийн ном ('the teacher's book'). Choose -ын for masculine words and -ийн for feminine words.",
    technicalNotes: "Mastery of stem-final consonant rules is crucial for accurate allomorph selection."
  },
  {
    conceptId: "gram_a1_possessive_pronouns_minii_chiniih",
    englishTitle: "Pronominal Possession (Миний, Чиний, Түүний, Бидний, Таны, Тэдний)",
    mongolianTitle: "Биеийн төлөөний нэрийн харьяалах хэлбэр ба өмчлөх төлөөний нэр",
    category: "Possession & Reflexives",
    firstTargetLevel: "A1",
    masteryTargetLevel: "A1",
    prerequisites: ["gram_a1_case_genitive_possession", "gram_a1_pronouns_personal_nominative"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_a1_case_accusative_definite"],
    modality: "productive",
    vowelHarmonyRequired: false,
    morphologyRequired: true,
    recursInAdvanced: false,
    knownComplications: ["Distinguishing preposed modifier (миний ном 'my book') from substantivized pronoun with -х (энэ минийх 'this is mine')."],
    description: "Possessive pronouns derived from genitive personal pronouns: миний (my), чиний (your), түүний (his/her), бидний (our), таны (your, polite), тэдний (their), and the possessive nominalizer -х (минийх, таных) (e.g. Энэ миний ном 'This is my book', Тэр таных 'That is yours').",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "My, Your & Mine: Possessive Words (Миний / Минийх)",
    linguisticAnalysis: "Genitive pronominal possessive determiners and secondary substantivized possessive pronouns with -х suffix.",
    learnerExplanation: "Put миний before a noun for 'my' (миний ном = 'my book'). Add -х to say 'mine' (энэ ном минийх = 'this book is mine').",
    technicalNotes: "High-frequency communicative tool essential for daily interaction."
  },
  {
    conceptId: "gram_a1_case_accusative_definite",
    englishTitle: "Accusative Case: Definite Direct Objects (-ыг/-ийг/-г)",
    mongolianTitle: "Заахын тийн ялгал: Тодорхой заагдсан тусагдахуун",
    category: "Case System",
    firstTargetLevel: "A1",
    masteryTargetLevel: "A1",
    prerequisites: ["gram_a1_case_nominative_unmarked", "gram_a1_sov_word_order", "phono_suffix_vowel_selection_fourfold"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_a1_case_dative_locative_location"],
    modality: "productive",
    vowelHarmonyRequired: true,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["Indefinite generic objects do NOT take the accusative suffix (e.g. Би ном уншдаг vs Би энэ номыг уншиж байна)."],
    description: "Marks definite, specific, or individualized direct objects with -ыг (masculine consonant), -ийг (feminine/palatal consonant), or -г (after long vowels and diphthongs) (e.g. Би тэр номыг уншсан 'I read that book', Аавыг дууд 'Call father').",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Direct Objects: Pointing to Specific Things (-ыг / -ийг)",
    linguisticAnalysis: "Differential object marking (DOM) system where specificity and definiteness trigger overt accusative inflection.",
    learnerExplanation: "When you are doing an action to a SPECIFIC object or person (like 'this book' or 'father'), add -ыг / -ийг. If it's just general ('I read books'), leave the ending off.",
    technicalNotes: "Differential object marking is one of the hallmarks of Mongolic syntax."
  },
  {
    conceptId: "gram_a1_case_dative_locative_location",
    englishTitle: "Dative-Locative Case: Static Location In, At, On (-д/-т)",
    mongolianTitle: "Өгөх оршихын тийн ялгал: Байрлал, орших утга",
    category: "Case System",
    firstTargetLevel: "A1",
    masteryTargetLevel: "A1",
    prerequisites: ["gram_a1_case_nominative_unmarked"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_a1_case_dative_locative_recipient", "gram_a1_case_dative_locative_temporal"],
    modality: "productive",
    vowelHarmonyRequired: false,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["Distribution of -д vs -т based on final consonant sonority, and -нд on unstable 'n' stems."],
    description: "The dative-locative suffix (-д/-т) marks the physical location where an entity exists or where a state occurs (e.g. Улаанбаатарт 'in Ulaanbaatar', гэрт 'at home', ширээн дээр 'on the desk').",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Saying Where Something Is: In, At, On (-д / -т)",
    linguisticAnalysis: "Locative-dative syncretic case affix marking spatial stative coordinates.",
    learnerExplanation: "To say you are IN or AT a place, attach -д or -т to the word: Улаанбаатарт ('in Ulaanbaatar'), гэрт ('at home'), сургуульд ('at school').",
    technicalNotes: "Attach -т after voiceless obstruents (в, г, д, р, с, т); attach -д elsewhere."
  },
  {
    conceptId: "gram_a1_case_dative_locative_recipient",
    englishTitle: "Dative-Locative Case: Recipient, Indirect Object, and Goal (-д/-т)",
    mongolianTitle: "Өгөх оршихын тийн ялгал: Хүлээн авагч ба чиглэл",
    category: "Case System",
    firstTargetLevel: "A1",
    masteryTargetLevel: "A1",
    prerequisites: ["gram_a1_case_dative_locative_location"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_a1_case_ablative_origin"],
    modality: "productive",
    vowelHarmonyRequired: false,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["Distinguishing dative-locative endpoint/goal (сургуульд очих) from directional trajectory (сургууль руу явах)."],
    description: "Marks the recipient of giving/telling verbs, indirect objects, and destination endpoints (e.g. багшид өгөх 'give to the teacher', найздаа хэлэх 'tell one's friend', хотод очих 'arrive in the city').",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Giving and Telling: To Whom and Whither (-д / -т)",
    linguisticAnalysis: "Dative case semantic roles: recipient, addressee, and telic spatial destination.",
    learnerExplanation: "When you give something TO someone or talk TO them, use the dative ending -д/-т: багшид өгөх ('give to the teacher'), ээжид хэлэх ('tell mom').",
    technicalNotes: "Shared morphology with locative; semantics disambiguated by verbal argument structure."
  },
  {
    conceptId: "gram_a1_case_dative_locative_temporal",
    englishTitle: "Dative-Locative Case: Temporal Location at Time Points (-д/-т)",
    mongolianTitle: "Өгөх оршихын тийн ялгал: Цаг хугацааны утга",
    category: "Case System",
    firstTargetLevel: "A1",
    masteryTargetLevel: "A1",
    prerequisites: ["gram_a1_case_dative_locative_location"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_a1_case_ablative_origin"],
    modality: "productive",
    vowelHarmonyRequired: false,
    morphologyRequired: true,
    recursInAdvanced: false,
    knownComplications: ["Certain general temporal adverbs (өчигдөр, өнөөдөр, маргааш) do not take the dative suffix."],
    description: "Marks points in time, hours, days, months, and years (e.g. таван цагт 'at five o'clock', даваа гарагт 'on Monday', зун 'in summer' / зуунд 'in the century').",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Stating When: At What Time and On Which Day (-д / -т)",
    linguisticAnalysis: "Temporal extension of dative-locative case marking specific points in chronological time.",
    learnerExplanation: "Use -д or -т to specify the exact time an event happens: таван цагт ('at 5 o'clock'), Даваа гарагт ('on Monday'). Note: words like 'today' (өнөөдөр) don't take this ending.",
    technicalNotes: "Essential for scheduling, appointments, and timetable discussions."
  },
  {
    conceptId: "gram_a1_case_ablative_origin",
    englishTitle: "Ablative Case: Spatial Origin and Separation (-аас/-ээс/-оос/-өөс)",
    mongolianTitle: "Гарахын тийн ялгал: Гарах, холдох орон зайн утга",
    category: "Case System",
    firstTargetLevel: "A1",
    masteryTargetLevel: "A1",
    prerequisites: ["gram_a1_case_dative_locative_location", "phono_suffix_vowel_selection_fourfold"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_a1_case_ablative_comparative", "gram_a1_case_comitative_accompaniment"],
    modality: "productive",
    vowelHarmonyRequired: true,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["Adding epenthetic -н- after stems ending in long vowels or diphthongs (e.g. хүү -> хүүнээс, далай -> далайнаас)."],
    description: "Expresses motion away from, starting point, or physical origin (e.g. гэрээс гарах 'to leave the house', Америк улсаас ирэх 'to come from the USA', сургуулиас авах 'to get from school').",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Saying Where From: Starting Points & Origins (-аас / -ээс)",
    linguisticAnalysis: "Ablative case (*-Acha/*-Eche) expressing spatial separation, source material, and origin.",
    learnerExplanation: "To say where you are coming FROM, add -аас, -ээс, -оос, or -өөс according to vowel harmony: гэрээс ('from home'), Америк улсаас ('from the USA').",
    technicalNotes: "Fourfold harmonic suffix; enforce glide/nasal epenthesis on vocalic stems."
  },
  {
    conceptId: "gram_a1_case_ablative_comparative",
    englishTitle: "Ablative Case: Standard of Comparison (X-ээс илүү/дутуу)",
    mongolianTitle: "Гарахын тийн ялгал: Харьцуулах утга",
    category: "Case System",
    firstTargetLevel: "A1",
    masteryTargetLevel: "A1",
    prerequisites: ["gram_a1_case_ablative_origin"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_a1_case_comitative_accompaniment"],
    modality: "productive",
    vowelHarmonyRequired: true,
    morphologyRequired: true,
    recursInAdvanced: false,
    knownComplications: ["The standard of comparison takes the ablative case while the adjective follows directly (e.g. Энэ тэрнээс том 'This is bigger than that')."],
    description: "Forming comparative structures using the ablative case on the comparison benchmark, optionally reinforced by илүү (more) or дутуу (less) (e.g. Энэ нь тэрнээс илүү үнэтэй 'This is more expensive than that').",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Comparing Things: 'Bigger than X' (Ablative + Adjective)",
    linguisticAnalysis: "Comparative construction with ablative-marked standard and adjective head.",
    learnerExplanation: "In Mongolian, to say 'A is bigger than B', put the 'from' ending (-аас) on B: Энэ тэрнээс том ('This is bigger than that'). You can add илүү ('more') for emphasis.",
    technicalNotes: "Does not require morphological change to the adjective itself, unlike English '-er'."
  },
  {
    conceptId: "gram_a1_case_comitative_accompaniment",
    englishTitle: "Comitative Case: Accompaniment and Association (-тай/-тэй/-той)",
    mongolianTitle: "Хамтрахын тийн ялгал: Хамт байх, нийлэх утга",
    category: "Case System",
    firstTargetLevel: "A1",
    masteryTargetLevel: "A1",
    prerequisites: ["gram_a1_case_nominative_unmarked"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_a1_case_comitative_possession_predicates"],
    modality: "productive",
    vowelHarmonyRequired: true,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["Threefold vowel harmony (-тай/-тэй/-той) with no fourth variant (-төй does not exist in standard Cyrillic)."],
    description: "Marks association, accompaniment, or partnership ('with X', e.g. найзтайгаа явах 'to go with one's friend', аавтайгаа ярих 'to speak with one's father', сүүтэй цай 'tea with milk').",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Saying 'With': Accompaniment & Ingredients (-тай / -тэй)",
    linguisticAnalysis: "Sociative-comitative case marker indicating accompaniment, association, and comitative possession.",
    learnerExplanation: "Add -тай, -тэй, or -той to mean 'with': найзтай ('with a friend'), сүүтэй цай ('tea with milk'). It has only 3 vowel forms (-тай, -тэй, -той).",
    technicalNotes: "Note orthographic asymmetry: stems with ө take -тэй (e.g. нөхөртэй)."
  },
  {
    conceptId: "gram_a1_case_comitative_possession_predicates",
    englishTitle: "Comitative Case: Predicative Possession (X-тэй байх = To Have X)",
    mongolianTitle: "Хамтрахын тийн ялгал: Өмчлөх, эзэмших утга (X-тэй байх)",
    category: "Possession & Reflexives",
    firstTargetLevel: "A1",
    masteryTargetLevel: "A1",
    prerequisites: ["gram_a1_case_comitative_accompaniment", "gram_a1_existential_baina_baihgui"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_a1_verb_dictionary_infinitive_kh"],
    modality: "productive",
    vowelHarmonyRequired: true,
    morphologyRequired: true,
    recursInAdvanced: false,
    knownComplications: ["Mongolian expresses 'having' primarily via [Subject comitative + noun] or [Possessor dative + possessed noun + бий/байна]."],
    description: "Expressing possession and physical attributes using the comitative suffix: Би ахтай 'I have an older brother', Энэ машин дөрвөн дугуйтай 'This car has four wheels', Чи завтай юу? 'Are you free (with leisure)?'",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Expressing 'To Have': Possessing Things and Qualities (-тай)",
    linguisticAnalysis: "Predicative attributive possession via comitative case inflection functioning as nominal predicate.",
    learnerExplanation: "Mongolian doesn't use a verb 'to have'. Instead, you say 'I am with an older brother' (Би ахтай) to mean 'I have an older brother'. To ask 'Do you have time?', say Чи завтай юу? ('Are you with leisure?').",
    technicalNotes: "Crucial conceptual pivot away from Western transitive 'have' verbs."
  },
  {
    conceptId: "gram_a1_verb_dictionary_infinitive_kh",
    englishTitle: "Verb Dictionary / Infinitive Form in -х",
    mongolianTitle: "Үйл үгийн үндсэн/толь бичгийн хэлбэр (-х нөхцөл)",
    category: "Verb Morphology",
    firstTargetLevel: "A1",
    masteryTargetLevel: "A1",
    prerequisites: ["gram_a1_sov_word_order", "phono_suffix_vowel_selection_fourfold"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_a1_verb_tense_present_habitual_dag", "gram_a1_verb_aspect_progressive_j_baina"],
    modality: "productive",
    vowelHarmonyRequired: true,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["Finding the true bare stem by dropping -х, and accounting for stem-final vowel drops (явах -> яв-, сурах -> сур-)."],
    description: "The citation form of all Mongolian verbs ending in the prospective participle / infinitive suffix -х (e.g. ирэх 'to come', явах 'to go', унших 'to read', үзэх 'to see').",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Dictionary Form of Verbs: Finding the Root (-х Ending)",
    linguisticAnalysis: "Prospective participle (*-ku/*-kü) functioning as the canonical citation infinitive lemma.",
    learnerExplanation: "Every Mongolian verb in the dictionary ends with the letter -х (явах = 'to go', ирэх = 'to come'). To add endings, remove the -х to find the verb root.",
    technicalNotes: "Acts as prospective participle in clausal nominalization and relative clause formation."
  },
  {
    conceptId: "gram_a1_verb_tense_present_habitual_dag",
    englishTitle: "Present-Habitual Tense / Aspect (-даг/-дэг/-дог/-дөг)",
    mongolianTitle: "Одоо-энгийн цаг: Хэвшил үйлдэл (-даг/-дэг/-дог/-дөг)",
    category: "Verb Morphology",
    firstTargetLevel: "A1",
    masteryTargetLevel: "A1",
    prerequisites: ["gram_a1_verb_dictionary_infinitive_kh", "phono_suffix_vowel_selection_fourfold"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_a1_verb_aspect_progressive_j_baina"],
    modality: "productive",
    vowelHarmonyRequired: true,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["Negated by appending -гүй directly to the suffix (e.g. явдаггүй 'does not go')."],
    description: "Expresses repeated, routine, habitual, or characteristic actions (e.g. Би өглөө бүр кофе уудаг 'I drink coffee every morning', Тэр Монголд амьдардаг 'He lives in Mongolia').",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Daily Habits & Routines: 'I usually do' (-даг / -дэг)",
    linguisticAnalysis: "Habitual aspectual participle suffix (*-dAg) functioning as main clause finite predicate.",
    learnerExplanation: "Attach -даг, -дэг, -дог, or -дөг to express habits and regular routines: Би кофе уудаг ('I drink coffee'). To say you DON'T do it, add -гүй: Би тамхи татдаггүй ('I don't smoke').",
    technicalNotes: "Follows strict fourfold vowel harmony; negative suffix -гүй invariant."
  },
  {
    conceptId: "gram_a1_verb_aspect_progressive_j_baina",
    englishTitle: "Present Continuous / Progressive Aspect (-ж байна / -ч байна)",
    mongolianTitle: "Үйлдэл үргэлжлэх хэлбэр (-ж / -ч байна)",
    category: "Verb Morphology",
    firstTargetLevel: "A1",
    masteryTargetLevel: "A1",
    prerequisites: ["gram_a1_verb_dictionary_infinitive_kh", "gram_a1_existential_baina_baihgui"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_a1_verb_tense_past_witnessed_laa", "gram_a1_verb_tense_past_perfective_san"],
    modality: "productive",
    vowelHarmonyRequired: false,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["Distribution of -ж (after vowels, l, m, n) vs -ч (after voiceless/affricate codas: b, d, g, r, s, t, ts, ch, sh)."],
    description: "Expresses an action currently in progress at the moment of speech, formed with coordinating converb -ж/-ч plus the auxiliary verb байна (e.g. Би монгол хэл сурч байна 'I am learning Mongolian', Чи юу хийж байна вэ? 'What are you doing?').",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Happening Right Now: -ing Actions (-ж байна)",
    linguisticAnalysis: "Imperfective/progressive periphrastic aspect formed by coordinating converb + existential auxiliary.",
    learnerExplanation: "To describe what you are doing right now, attach -ж or -ч to the verb root and add байна: Би сурч байна ('I am studying'), Би уншиж байна ('I am reading').",
    technicalNotes: "Allomorph rule: use -ч after voiceless/obstruent codas (р, с, т, г, б); use -ж elsewhere."
  },
  {
    conceptId: "gram_a1_verb_tense_past_witnessed_laa",
    englishTitle: "Immediate / Witnessed Past Tense (-лаа/-лээ/-лоо/-лөө)",
    mongolianTitle: "Гэрчилсэн өнгөрсөн цаг (-лаа/-лээ/-лоо/-лөө)",
    category: "Verb Morphology",
    firstTargetLevel: "A1",
    masteryTargetLevel: "A1",
    prerequisites: ["gram_a1_verb_dictionary_infinitive_kh", "phono_suffix_vowel_selection_fourfold"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_a1_verb_tense_future_prospective_na"],
    modality: "productive",
    vowelHarmonyRequired: true,
    morphologyRequired: true,
    recursInAdvanced: false,
    knownComplications: ["Used for events just witnessed or performed by the speaker; also used for announcements of immediate departure (би явлаа)."],
    description: "Marks recent actions directly witnessed, experienced, or announced by the speaker (e.g. Бороо орлоо 'It just rained / It is raining!', Би ирлээ 'I have arrived!', Би явлаа 'I'm taking off now!').",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Just Happened: Fresh Witnessed Past (-лаа / -лээ)",
    linguisticAnalysis: "Direct evidential past finite inflection marking newly observed or immediately realized events.",
    learnerExplanation: "Use -лаа / -лээ when an action just took place right before your eyes, or when announcing an immediate departure: Би явлаа! ('I'm off!'), Бороо орлоо! ('Look, it just started raining!').",
    technicalNotes: "Strict fourfold vowel harmony; carries strong immediate perceptual evidentiality."
  },
  {
    conceptId: "gram_a1_verb_tense_past_perfective_san",
    englishTitle: "Established Past Tense / Past Participle (-сан/-сэн/-сон/-сөн)",
    mongolianTitle: "Өнгөрсөн цагийн нөхцөл (-сан/-сэн/-сон/-сөн)",
    category: "Verb Morphology",
    firstTargetLevel: "A1",
    masteryTargetLevel: "A1",
    prerequisites: ["gram_a1_verb_dictionary_infinitive_kh", "phono_suffix_vowel_selection_fourfold"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_a1_verb_tense_future_prospective_na"],
    modality: "productive",
    vowelHarmonyRequired: true,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["Functions both as a finite sentence predicate and as a relative clause attributive participle."],
    description: "The primary general past tense marker in spoken and written Mongolian, indicating an established or completed event in the past (e.g. Би өчигдөр ном уншсан 'I read a book yesterday'). Negated with -гүй (уншаагүй).",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "General Past Tense: Completed Past Actions (-сан / -сэн)",
    linguisticAnalysis: "Perfective past participle suffix (*-gsAn) functioning as finite narrative past predicate.",
    learnerExplanation: "This is the everyday past tense in Mongolian for actions that happened in the past: Би өчигдөр ирсэн ('I came yesterday'). To say you didn't do it, use -аагүй / -ээгүй: Би яваагүй ('I didn't go').",
    technicalNotes: "Follows fourfold vowel harmony; fundamental past-tense workhorse across all registers."
  },
  {
    conceptId: "gram_a1_verb_tense_future_prospective_na",
    englishTitle: "Future-Prospective Tense (-на/-нэ/-но/-нө)",
    mongolianTitle: "Ирээдүй-заах цаг (-на/-нэ/-но/-нө)",
    category: "Verb Morphology",
    firstTargetLevel: "A1",
    masteryTargetLevel: "A1",
    prerequisites: ["gram_a1_verb_dictionary_infinitive_kh", "phono_suffix_vowel_selection_fourfold"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_a1_verb_volitional_intention_ya"],
    modality: "productive",
    vowelHarmonyRequired: true,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["Before vowels/consonant stems, orthographic epenthesis or contraction occurs (явах -> явна, өгөх -> өгнө, харах -> харна)."],
    description: "Expresses future events, expectations, willingness, or general truths (e.g. Би маргааш ирнэ 'I will come tomorrow', Нар мандана 'The sun will rise', Би тусална 'I will help').",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Future Actions: What Will Happen (-на / -нэ)",
    linguisticAnalysis: "Non-past prospective finite inflection marking future temporality and modal commitment.",
    learnerExplanation: "To talk about what will happen tomorrow or later, add -на, -нэ, -но, or -нө to the verb root: Би маргааш явна ('I will go tomorrow'), Би тусална ('I will help').",
    technicalNotes: "Follows fourfold vowel harmony; interacts with stem-final consonant phonology."
  },
  {
    conceptId: "gram_a1_verb_volitional_intention_ya",
    englishTitle: "Volitional Intention and First-Person Optative (-я/-е/-ё)",
    mongolianTitle: "Хүсэх, төлөвлөх үйлийн төлөв (-я/-е/-ё)",
    category: "Modality & Stance",
    firstTargetLevel: "A1",
    masteryTargetLevel: "A1",
    prerequisites: ["gram_a1_verb_tense_future_prospective_na", "phono_iotated_vowels_behavior"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_a1_verb_imperative_polite_aarai"],
    modality: "productive",
    vowelHarmonyRequired: true,
    morphologyRequired: true,
    recursInAdvanced: false,
    knownComplications: ["Stem-final consonants often require hard sign ъ or soft sign ь before the suffix (e.g. явъя, үзье, олъё)."],
    description: "Expresses the speaker's immediate intention ('Let me...', 'I will...') or collective proposal ('Let's...') (e.g. Цай ууя 'Let's drink tea / I will drink tea', Явъя 'Let's go', Баримт авъя 'I will take the receipt').",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Suggesting 'Let's Do It': Intentions & Orders (-я / -е)",
    linguisticAnalysis: "First-person volitional/cohortative modal inflection marking speaker resolution or collective proposal.",
    learnerExplanation: "Use -я or -е when suggesting an activity ('Let's go!' = Явъя!) or ordering food at a restaurant ('I'll have buuz' = Бууз авъя).",
    technicalNotes: "Watch out for hard/soft sign spelling rules: яв- + -я -> явъя; үз- + -е -> үзье."
  },
  {
    conceptId: "gram_a1_verb_imperative_polite_aarai",
    englishTitle: "Polite Request and Prescriptive Imperative (-аарай/-ээрэй/-оорой/-өөрэй)",
    mongolianTitle: "Захирах хүсэх аялга: Эелдгээр хүсэх (-аарай/-ээрэй/-оорой/-өөрэй)",
    category: "Modality & Stance",
    firstTargetLevel: "A1",
    masteryTargetLevel: "A1",
    prerequisites: ["gram_a1_verb_dictionary_infinitive_kh", "phono_suffix_vowel_selection_fourfold"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_a1_verb_prohibitive_bitgii"],
    modality: "productive",
    vowelHarmonyRequired: true,
    morphologyRequired: true,
    recursInAdvanced: false,
    knownComplications: ["Used for polite requests, well-wishing farewells, and instructional guidelines."],
    description: "Forms standard polite instructions and parting blessings (e.g. Дахин ирээрэй 'Please come again!', Болгоомжтой яваарай 'Have a safe journey!', Сайн сураарай 'Study well!').",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Polite Requests & Wishes: 'Please do this' (-аарай / -ээрэй)",
    linguisticAnalysis: "Prescriptive future-imperative suffix marking polite requests, instructions, and parting benedictions.",
    learnerExplanation: "This is the most common polite way to ask someone to do something or wish them well: Сайн яваарай ('Have a safe trip!'), Маргааш ирээрэй ('Please come tomorrow').",
    technicalNotes: "Essential for polite daily interaction; softens direct imperative commands."
  },
  {
    conceptId: "gram_a1_verb_prohibitive_bitgii",
    englishTitle: "Prohibitive Negative Imperative (Битгий + Verb)",
    mongolianTitle: "Хориглох хүсэх хэлбэр (Битгий + үйл үндэс)",
    category: "Modality & Stance",
    firstTargetLevel: "A1",
    masteryTargetLevel: "A1",
    prerequisites: ["gram_a1_verb_imperative_polite_aarai"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_a1_converb_coordinating_j_ch"],
    modality: "productive",
    vowelHarmonyRequired: false,
    morphologyRequired: false,
    recursInAdvanced: false,
    knownComplications: ["Distinguishing conversational битгий from formal/archaic бүү."],
    description: "Expresses negative commands ('Don't do X!') using the prohibitive particle битгий placed before the verb stem or polite imperative (e.g. Битгий яв! 'Don't go!', Битгий мартаарай 'Please don't forget!').",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Telling Someone 'Don't': Negative Commands (Битгий)",
    linguisticAnalysis: "Pre-verbal prohibitive negative modal particle governing bare verb stem or imperative.",
    learnerExplanation: "To tell someone NOT to do something, put битгий right before the verb: Битгий яв! ('Don't go!'), Битгий ай ('Don't be afraid!').",
    technicalNotes: "Conversational standard; distinct from formal administrative бүү."
  },
  {
    conceptId: "gram_a1_converb_coordinating_j_ch",
    englishTitle: "Coordinating Converb: Sequential and Manner Linkage (-ж / -ч)",
    mongolianTitle: "Зэрэгцүүлэн холбох нөхцөл (-ж / -ч)",
    category: "Converbs",
    firstTargetLevel: "A1",
    masteryTargetLevel: "A2",
    prerequisites: ["gram_a1_verb_aspect_progressive_j_baina"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_a1_converb_sequential_aad"],
    modality: "both",
    vowelHarmonyRequired: false,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["Both chained verbs must share the same subject in standard simple coordination."],
    description: "Joins two closely associated actions performed sequentially or simultaneously by the same subject (e.g. Би сууж ярилцсан 'I sat and talked', Ном авч уншив 'took the book and read [it]').",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Linking Two Actions: Doing This and Doing That (-ж / -ч)",
    linguisticAnalysis: "Coordinating (imperfect) converb linking clauses in co-temporal or immediate sequential nexus.",
    learnerExplanation: "Attach -ж or -ч to combine two actions together into one sentence: Би сууж ярилцсан ('I sat down and talked'). Both actions must be done by the same person.",
    technicalNotes: "Does not require vowel harmony; conditioned by final consonant voicing."
  },
  {
    conceptId: "gram_a1_converb_sequential_aad",
    englishTitle: "Prior Sequential Converb: After Doing X (-аад/-ээд/-оод/-өөд)",
    mongolianTitle: "Урьдчилан холбох нөхцөл (-аад/-ээд/-оод/-өөд)",
    category: "Converbs",
    firstTargetLevel: "A1",
    masteryTargetLevel: "A2",
    prerequisites: ["gram_a1_converb_coordinating_j_ch", "phono_suffix_vowel_selection_fourfold"],
    recommendedPriorConcepts: [],
    unlocks: [],
    modality: "both",
    vowelHarmonyRequired: true,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["Indicates explicit chronological priority: Action 1 is fully finished before Action 2 begins."],
    description: "Connects two actions where the first action is completed prior to the second (e.g. Би өглөөний цайгаа уугаад, сургуульдаа явсан 'After drinking my breakfast tea, I went to school').",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "First This, Then That: Action Chains (-аад / -ээд)",
    linguisticAnalysis: "Perfective sequential converb (*-gAAd) establishing anteriority in inter-clausal narrative chaining.",
    learnerExplanation: "Use -аад, -ээд, -оод, or -өөд to say that you finished one action BEFORE starting the next one: Цайгаа уугаад явлаа ('Having finished my tea, I went').",
    technicalNotes: "Follows fourfold vowel harmony; essential for building longer spoken stories."
  }
];
