import { CommunicativeFunctionSpec } from './dataCommunicative_A1';

export const communicativeC1C2Data: CommunicativeFunctionSpec[] = [
  // C1 Communicative Functions (15 Functions)
  {
    functionId: "comm_c1_01_honorific_elder_conversations",
    title: "Sustain High-Honorific Dialogue with Venerated Elders",
    mongolianTitle: "Ахмад настан, хүндэт хүмүүстэй өндөр хүндэтгэлийн найруулгаар харилцах",
    level: "C1",
    domain: "Interpersonal",
    prerequisites: ["comm_a1_02_formal_elder_greetings"],
    communicativeGoal: "Maintain faultless use of lexical honorifics (морилох, зооглох, айлдах, таалал) across extended inter-generational discourse.",
    typicalScenarios: ["Audience with a Buddhist lama or state academician", "Formal reception of village elders"],
    keyStructures: ["Та тухлан сууж болгооно уу", "Таны айлдсан үг үнэтэй сургаал боллоо", "Бие лагшин сайн тунгалаг байна уу?"],
    expectedOutcome: "Learner replaces all everyday verbs and nouns with their reverential equivalents without hesitation."
  },
  {
    functionId: "comm_c1_02_diplomatic_official_receptions",
    title: "Formulate Protocol Remarks for Foreign Diplomatic Receptions",
    mongolianTitle: "Дипломат ёслол, албан ёсны хүлээн авалтын үг хэллэг найруулах",
    level: "C1",
    domain: "Professional",
    prerequisites: ["comm_b2_07_delivering_prepared_presentations"],
    communicativeGoal: "Deliver diplomatic welcomes, toast bilateral friendship, and express state-level protocol courtesies.",
    typicalScenarios: ["State banquet reception", "Embassy national day celebration"],
    keyStructures: ["Хоёр орны найрсаг харилцаа, хамтын ажиллагааг өргөжүүлэн хөгжүүлэх", "Эрхэм хүндэт төлөөлөгчдийг халуун дотноор угтан авч байна"],
    expectedOutcome: "Learner employs elevated diplomatic register conforming strictly to state protocol conventions."
  },
  {
    functionId: "comm_c1_03_drafting_executive_decrees",
    title: "Draft Executive Orders and Government Decrees (Тогтоох нь)",
    mongolianTitle: "Засгийн газрын тогтоол, албан шийдвэр, тушаал найруулах",
    level: "C1",
    domain: "Professional",
    prerequisites: ["comm_b2_16_legal_contract_comprehension"],
    communicativeGoal: "Draft legislative enactments using chancellery imperatives (ТОГТООХ нь, захирамжилсугай, үүрэг болгосугай).",
    typicalScenarios: ["Ministry legal drafting department", "Municipal government resolution formulation"],
    keyStructures: ["Монгол Улсын хуулийг үндэслэн ТОГТООХ нь:", "Дараах арга хэмжээг авч хэрэгжүүлэхийг даалгасугай", "Хэрэгжилтэд хяналт тавьж ажиллахыг үүрэг болгосугай"],
    expectedOutcome: "Learner drafts statutory instruments adhering to Mongolian administrative drafting standards."
  },
  {
    functionId: "comm_c1_04_statutory_legislative_drafting",
    title: "Draft Statutory Provisions and Legislative Amendments",
    mongolianTitle: "Хуулийн төсөл, нэмэлт өөрчлөлтийн заалт боловсруулах",
    level: "C1",
    domain: "Professional",
    prerequisites: ["comm_c1_03_drafting_executive_decrees"],
    communicativeGoal: "Draft legal articles defining definitions, rights, liabilities, and exceptions with zero syntactic ambiguity.",
    typicalScenarios: ["State Great Khural parliamentary committee work", "Legislative drafting workgroup"],
    keyStructures: ["Энэ хуулийн зорилго нь ... зохицуулахад оршино", "Хуулийн этгээд дараах үүрэг хүлээнэ", "Хэрэв хуульд өөрөөр заагаагүй бол"],
    expectedOutcome: "Learner uses canonical legislative syntax and nominalized proviso constructions."
  },
  {
    functionId: "comm_c1_05_academic_peer_review",
    title: "Perform Peer Reviews of Scholarly Submissions",
    mongolianTitle: "Эрдэм шинжилгээний бүтээлд мэргэжлийн шүүмж, үнэлгээ бичих",
    level: "C1",
    domain: "Academic",
    prerequisites: ["comm_b2_21_academic_abstract_formulation"],
    communicativeGoal: "Evaluate theoretical rigor, methodology, citation integrity, and originality of a scholarly paper.",
    typicalScenarios: ["Peer review for Mongolian Academy of Sciences journal", "Doctoral dissertation evaluation"],
    keyStructures: ["Зохиогчийн дэвшүүлсэн үзэл санаа нь шинэлэг талтай боловч", "Арга зүйн хувьд дараах дутагдал ажиглагдаж байна", "Хэвлэн нийтлэхийг дэмжиж байна"],
    expectedOutcome: "Learner delivers balanced, rigorous academic critiques with professional collegiate tone."
  },
  {
    functionId: "comm_c1_06_hedging_scientific_claims",
    title: "Modulate Scientific Claims with Epistemic Modesty (Hedging)",
    mongolianTitle: "Шинжлэх ухааны дүгнэлтийг болгоомжтой, нотолгоотой илэрхийлэх",
    level: "C1",
    domain: "Academic",
    prerequisites: ["comm_c1_05_academic_peer_review"],
    communicativeGoal: "Moderate conclusions using epistemic markers (үүсгэж болзошгүй, гэж үзэх үндэслэлтэй) to avoid premature generalization.",
    typicalScenarios: ["Scientific research paper discussion section", "Public health risk evaluation"],
    keyStructures: ["Энэхүү үр дүн нь дараах таамаглалыг баталж байна гэж шууд дүгнэхэд эрт байна", "Үүнд өөр хүчин зүйлс нөлөөлсөн байх магадлалтай"],
    expectedOutcome: "Learner uses precise grammatical hedging devices without appearing unconfident."
  },
  {
    functionId: "comm_c1_07_investigative_journalism_reports",
    title: "Author In-Depth Investigative Journalism Reports",
    mongolianTitle: "Эрэн сурвалжлах сэтгүүл зүйн нийтлэл, тайлан найруулах",
    level: "C1",
    domain: "Professional",
    prerequisites: ["comm_b2_10_drafting_press_releases"],
    communicativeGoal: "Document systemic corruption, regulatory capture, or environmental violations while protecting confidential sources.",
    typicalScenarios: ["Investigative media feature article", "Television documentary investigative voiceover"],
    keyStructures: ["Албаны эх сурвалжийн мэдээлснээр", "Баримт бичгүүдийг судлан үзэхэд дараах зөрчил илэрлээ", "Энэ нь хууль бус үйлдэл байж болзошгүй"],
    expectedOutcome: "Learner synthesizes complex factual trails into compelling, evidence-backed investigative prose."
  },
  {
    functionId: "comm_c1_08_philosophical_discourse",
    title: "Conduct Ontological and Philosophical Inquiries (-хуй)",
    mongolianTitle: "Гүн ухаан, оршихуй, танин мэдэхүйн асуудлыг хэлэлцэх",
    level: "C1",
    domain: "Academic",
    prerequisites: ["comm_b2_17_cross_cultural_comparisons"],
    communicativeGoal: "Debate existence, metaphysics, consciousness, and nomad ontology utilizing classical nominalizations (оршихуй, сэтгэхүй).",
    typicalScenarios: ["Philosophy symposium", "Intellectual salon discussion"],
    keyStructures: ["Хүний сэтгэхүй ба оршихуйн мөн чанар", "Цаг хугацааны эцэс төгсгөлгүй урсгал", "Танин мэдэхүйн хязгаар ба учир шалтгаан"],
    expectedOutcome: "Learner handles abstract philosophical terminology and classical nominal derivations fluently."
  },
  {
    functionId: "comm_c1_09_high_level_policy_briefs",
    title: "Author Ministerial White Papers and Strategic Policy Briefs",
    mongolianTitle: "Сайдын түвшний бодлогын зөвлөмж, стратеги баримт бичиг боловсруулах",
    level: "C1",
    domain: "Professional",
    prerequisites: ["comm_b2_25_strategic_consultation"],
    communicativeGoal: "Analyze strategic trade-offs across geopolitical, fiscal, and social spheres for top decision-makers.",
    typicalScenarios: ["National Security Council policy paper", "Ministerial economic roadmap briefing"],
    keyStructures: ["Улс орны язгуур ашиг сонирхлыг хамгаалах үүднээс", "Эрсдэлийг бууруулах цогц арга хэмжээ", "Геополитикийн нөхцөл байдалд нийцүүлэн"],
    expectedOutcome: "Learner provides executive leadership with concise, decision-grade strategic analysis."
  },
  {
    functionId: "comm_c1_10_rhetorical_speechwriting",
    title: "Compose Persuasive Ceremonial and Political Keynotes",
    mongolianTitle: "Илтгэх урлаг, ёслолын болон улс төрийн цоглог үг найруулах",
    level: "C1",
    domain: "Professional",
    prerequisites: ["comm_b2_07_delivering_prepared_presentations"],
    communicativeGoal: "Write inspirational addresses using parallelism, historical allusion, rhetorical questions, and emotional crescendo.",
    typicalScenarios: ["National Day keynote address", "University commencement address"],
    keyStructures: ["Эх орныхоо өнцөг булан бүрт ажиллаж, хөдөлмөрлөж буй эрхэм иргэд ээ!", "Бидний өвөг дээдсийн үлдээсэн үнэт өв", "Ирээдүй хойч үеийнхээ өмнө бид хариуцлагатай"],
    expectedOutcome: "Learner crafts resonant oratory combining modern political rhetoric with deep cultural resonance."
  },
  {
    functionId: "comm_c1_11_courtroom_legal_argumentation",
    title: "Present Appellate Court Arguments and Legal Pleadings",
    mongolianTitle: "Шүүх хуралдаанд өмгөөлөл, яллах дүгнэлт, хууль зүйн тайлбар хийх",
    level: "C1",
    domain: "Professional",
    prerequisites: ["comm_c1_04_statutory_legislative_drafting"],
    communicativeGoal: "Present oral arguments before judges, cite precedent statutes, cross-examine evidence, and request acquittal or judgment.",
    typicalScenarios: ["Appellate court hearing", "Commercial arbitration tribunal"],
    keyStructures: ["Эрүүгийн / Иргэний хуулийн тухайн зүйл заалтыг буруу хэрэглэсэн тул", "Нотлох баримтыг хууль бусаар цуглуулсан", "Шүүх бүрэлдэхүүнээс хүсэх нь"],
    expectedOutcome: "Learner utilizes procedural legal terminology and razor-sharp deductive forensic logic."
  },
  {
    functionId: "comm_c1_12_consecutive_interpreting_support",
    title: "Facilitate Consecutive Interpreting in High-Stakes Bilateral Meetings",
    mongolianTitle: "Өндөр түвшний хоёр талт уулзалтад дараалсан орчуулга хийх",
    level: "C1",
    domain: "Professional",
    prerequisites: ["comm_c1_02_diplomatic_official_receptions"],
    communicativeGoal: "Accurately translate 3-minute ministerial spoken segments retaining exact political nuance and courtesy forms.",
    typicalScenarios: ["Bilateral trade talks", "Presidential state visit delegation meetings"],
    keyStructures: ["Эрхэм ерөнхийлөгчийн дурдсанчлан", "Манай тал энэхүү саналыг бүрэн дэмжиж байна", "Хоёр улсын хөгжилд үнэтэй хувь нэмэр оруулах"],
    expectedOutcome: "Learner maintains fidelity to register, omissions zero substantive content, and speaks fluently."
  },
  {
    functionId: "comm_c1_13_editorial_counter_argumentation",
    title: "Write Analytical Rebuttals to Prominent Public Editorials",
    mongolianTitle: "Нийтлэлд няцаалт, мэргэжлийн хариу тайлбар нийтлэх",
    level: "C1",
    domain: "Academic",
    prerequisites: ["comm_b2_02_academic_essay_concessions"],
    communicativeGoal: "Deconstruct flaws in a published newspaper op-ed and present a rigorously supported counter-narrative.",
    typicalScenarios: ["Op-ed page of major national daily (Өнөөдөр, Зууны Мэдээ)", "Intellectual online platform"],
    keyStructures: ["Тус нийтлэлд дурдсан баримтууд нь бодит байдалд нийцэхгүй байна", "Асуудлыг нэг талын өнцгөөс харсан нь", "Бодит дүн шинжилгээ дараах зүйлийг харуулж байна"],
    expectedOutcome: "Learner critiques public viewpoints with incisive logic and elevated literary style."
  },
  {
    functionId: "comm_c1_14_navigating_subtle_social_hierarchies",
    title: "Navigate Multi-Generational Social Hierarchies with Ease",
    mongolianTitle: "Олон үеийн цугларалтад нийгмийн зэрэг дэв, ёс жаягийг төгс мөрдөх",
    level: "C1",
    domain: "Interpersonal",
    prerequisites: ["comm_c1_01_honorific_elder_conversations"],
    communicativeGoal: "Seamlessly pivot tone and register when addressing elderly relatives, peers, younger juniors, and honored guests simultaneously.",
    typicalScenarios: ["Clan lineage gathering (ураг удмын баяр)", "Multi-generational wedding banquet"],
    keyStructures: ["Ахмадуудаа дээдлэн хүндэтгэх", "Үе тэнгийнхэнтэйгээ энгийн найрсаг харилцах", "Дүү нартаа сургаал хайрлах"],
    expectedOutcome: "Learner shifts effortlessly between elevated honorifics, polite neutral speech, and warm guidance."
  },
  {
    functionId: "comm_c1_15_literary_translation_evaluation",
    title: "Evaluate Nuances in Classic and Modern Literary Translations",
    mongolianTitle: "Уран зохиолын орчуулгын торгон торгон утга, найруулгыг шүүн тунгаах",
    level: "C1",
    domain: "Academic",
    prerequisites: ["comm_c1_08_philosophical_discourse"],
    communicativeGoal: "Analyze how world classics (Shakespeare, Tolstoy, Marquez) were rendered into Mongolian by master translators.",
    typicalScenarios: ["Literary translation symposium", "Comparative literature seminar"],
    keyStructures: ["Эх зохиолын уур амьсгалыг монгол хэлний баялаг сангаар амилуулсан нь", "Үгийн сонголт, өнгө аясыг гайхалтай хадгалсан", "Орчуулгын онолын үүднээс авч үзвэл"],
    expectedOutcome: "Learner analyzes subtle phonetic rhythms, idioms, and stylistic fidelity in translations."
  },

  // C2 Communicative Functions (15 Functions)
  {
    functionId: "comm_c2_01_rapid_colloquial_banter",
    title: "Command Rapid Colloquial Banter, Slang, and Idiomatic Puns",
    mongolianTitle: "Шуурхай ярианы хэл, этгээд үг, хошин яриаг чөлөөтэй эзэмших",
    level: "C2",
    domain: "Interpersonal",
    prerequisites: ["comm_b1_01_narrating_personal_anecdotes"],
    communicativeGoal: "Participate in fast-paced colloquial banter, decipher youth slang, understand truncated contractions, and return witty remarks.",
    typicalScenarios: ["Lively informal gathering of urban youths", "Fast-moving improvisational humor"],
    keyStructures: ["Тэгээд яасан гэнэ ээ?", "Юу яриад байгаа юм бэ дээ", "Шал утгагүй юм болоод", "Битгий маяглаад бай"],
    expectedOutcome: "Learner processes rapid contracted speech and uses colloquial phonological reductions naturally."
  },
  {
    functionId: "comm_c2_02_conversational_repair_turn_taking",
    title: "Execute Fluid Turn-Taking and Floor-Holding in High-Speed Exchanges",
    mongolianTitle: "Хурц ярианы явцад ярианы ээлжийг удирдах, өөртөө татах",
    level: "C2",
    domain: "Interpersonal",
    prerequisites: ["comm_c2_01_rapid_colloquial_banter"],
    communicativeGoal: "Interrupt politely, hold the floor under interruptions, and yield turns seamlessly in heated roundtables.",
    typicalScenarios: ["Live televised political talk show", "High-stakes executive boardroom debates"],
    keyStructures: ["Намайг үгээ дуусгахыг зөвшөөрнө үү", "Таны хэлсэнтэй холбогдуулан нэг зүйл нэмж хэлэхэд", "Яг энэ цэг дээр анхаарлаа хандуулъя"],
    expectedOutcome: "Learner commands conversation flow dynamics without causing communicative friction."
  },
  {
    functionId: "comm_c2_03_humor_sarcasm_irony",
    title: "Decode and Deploy Dry Steppe Humor, Sarcasm, and Understatement",
    mongolianTitle: "Егөөдөл, хошигнол, далд утгатай ёж үгийг тайлах ба хэрэглэх",
    level: "C2",
    domain: "Interpersonal",
    prerequisites: ["comm_c2_01_rapid_colloquial_banter"],
    communicativeGoal: "Understand dark humor, dry steppe irony, and litotes where praise disguises critique or vice versa.",
    typicalScenarios: ["Listening to satirical folk tales", "Decoding subtle political sarcasm in columns"],
    keyStructures: ["Маш 'сайхан' болж дээ", "Тэр ч ёстой 'гарамгай' хийж дээ", "Нүдээ олсон хэрэг болж"],
    expectedOutcome: "Learner detects ironic vocal intonation and produces witty, culturally resonant understatements."
  },
  {
    functionId: "comm_c2_04_somatic_steppe_idioms",
    title: "Weave Somatic and Pastoral Idioms into Modern Commentary",
    mongolianTitle: "Анатомийн болон нүүдлийн аж байдлын хэлц үгийг яриандаа уусгах",
    level: "C2",
    domain: "Cultural",
    prerequisites: ["comm_b2_17_cross_cultural_comparisons"],
    communicativeGoal: "Use traditional steppe idioms based on liver (элэг), heart (зүрх), spine (нуруу), and horses to enrich discourse.",
    typicalScenarios: ["Cultural essays", "Thought-provoking commentary on national character"],
    keyStructures: ["Элэг нь хөших (инээх)", "Зүрх алдах (айх)", "Нуруугаа үүрч явах", "Ам халах", "Хөл алдах"],
    expectedOutcome: "Learner deploys somatic idioms accurately according to situational and stylistic decorum."
  },
  {
    functionId: "comm_c2_05_satirical_cultural_critique",
    title: "Publish Witty Satirical Critiques of Modern Bureaucracy and Consumerism",
    mongolianTitle: "Нийгмийн гажиг, хүнд суртал, хэрэглээний шуналыг шоглон бичих",
    level: "C2",
    domain: "Cultural",
    prerequisites: ["comm_c2_03_humor_sarcasm_irony"],
    communicativeGoal: "Author a biting satirical feuilleton lampooning bureaucratic paperwork, social media vanities, or corruption.",
    typicalScenarios: ["Satirical journal column (Тоншуул tradition)", "Humorous social commentary"],
    keyStructures: ["Хүнд суртлын машины араа шүд", "Цаасан дээрх төгс төгөлдөр ертөнц", "Ажил хийсэн нэр зүүж"],
    expectedOutcome: "Learner composes sophisticated satire that entertains while delivering profound ethical critique."
  },
  {
    functionId: "comm_c2_06_literary_polyphony_writing",
    title: "Compose Psychological Fiction with Free Indirect Discourse",
    mongolianTitle: "Сэтгэл зүйн хүүрнэл зохиол, олон хоолойн найруулгаар бичих",
    level: "C2",
    domain: "Narrative",
    prerequisites: ["comm_c1_15_literary_translation_evaluation"],
    communicativeGoal: "Write a short story shifting perspectives between characters, blending inner stream-of-consciousness with narrator voice.",
    typicalScenarios: ["Literary short fiction submission", "Creative writing workshop"],
    keyStructures: ["Түүний дотоод сэтгэлийн зөрчил", "Бодолдоо төөрсөн нь", "Цаг хугацаа зогссон мэт санагдав"],
    expectedOutcome: "Learner produces evocative prose exhibiting depth, lyrical rhythm, and character interiority."
  },
  {
    functionId: "comm_c2_07_constitutional_court_parsing",
    title: "Parse Constitutional Jurisprudence and Complex Proviso Clauses",
    mongolianTitle: "Үндсэн хуулийн Цэцийн дүгнэлт, нарийн хууль зүйн тайлбарыг нягтлах",
    level: "C2",
    domain: "Academic",
    prerequisites: ["comm_c1_04_statutory_legislative_drafting"],
    communicativeGoal: "Dissect complex Constitutional Tsets decisions, resolving dense chains of embedded participial and gerundial clauses.",
    typicalScenarios: ["Constitutional law research", "Drafting an appeal to the Constitutional Court"],
    keyStructures: ["Үндсэн хуулийн холбогдох заалтыг зөрчсөн эсэх маргаан", "Цэцийн их суудлын хуралдааны дүгнэлт", "Хуулийн уг зорилгод үл нийцэх"],
    expectedOutcome: "Learner decodes high-level legal prose with 5+ layers of embedded hypotaxis with complete precision."
  },
  {
    functionId: "comm_c2_08_omni_register_agility",
    title: "Demonstrate Omni-Register Agility from Steppe Camp to State Gala",
    mongolianTitle: "Бүх найруулгын хүрээнд чөлөөтэй шилжих, дасан зохицох чадвар",
    level: "C2",
    domain: "Interpersonal",
    prerequisites: ["comm_c1_14_navigating_subtle_social_hierarchies"],
    communicativeGoal: "Instantly and naturally switch between raw dialectal steppe vernacular and elevated academic/diplomatic speech.",
    typicalScenarios: ["Field researcher moving from nomadic pastures to ministerial debriefings in a single day"],
    keyStructures: ["Хөдөөний малчны ахуй ярианд бүрэн уусах", "Эрдэм шинжилгээний танхимд эрдэмтний найруулгаар үг хэлэх"],
    expectedOutcome: "Learner displays zero linguistic awkwardness or register dissonance across disparate social milieus."
  },
  {
    functionId: "comm_c2_09_metric_alliterative_poetry",
    title: "Compose Metric Head-Alliterative Mongolian Poetry (Толгой холболт)",
    mongolianTitle: "Монгол яруу найргийн толгой холбох ёсоор шүлэг зохиох",
    level: "C2",
    domain: "Cultural",
    prerequisites: ["comm_c2_06_literary_polyphony_writing"],
    communicativeGoal: "Write traditional four-line stanzas adhering to initial consonant alliteration (толгой холболт) and syllabic balance.",
    typicalScenarios: ["Poetry competition (Болор Цом)", "Dedication ode for a milestone occasion"],
    keyStructures: ["Хөх тэнгэрийн нар гийж / Хөвчин дэлхий дулаацна / Хүний сайхан сэтгэлээр / Хорвоо ертөнц жаргана"],
    expectedOutcome: "Learner applies the classical Mongolian alliteration system and 7/8 syllable rhythmic meters."
  },
  {
    functionId: "comm_c2_10_secret_history_philological_reading",
    title: "Interpret 13th-Century Secret History Excerpts in Cyrillic",
    mongolianTitle: "Монголын Нууц Товчооны эх бичвэрийг утга зүйн хувьд тайлбарлах",
    level: "C2",
    domain: "Academic",
    prerequisites: ["comm_c1_08_philosophical_discourse"],
    communicativeGoal: "Read and interpret passages of the Secret History (Монголын Нууц Товчоо) in modern Cyrillic scholarly editions.",
    typicalScenarios: ["Philological reading group", "Historical documentary analysis"],
    keyStructures: ["Дээд тэнгэрээс заяат төрсөн Бөртэ чоно", "Төрийн алтан жолоог барих", "Нөхөрлөх ба эв нэгдлийн сургаал"],
    expectedOutcome: "Learner recognizes archaic lexical items, clan names, and ancient metaphorical structures."
  },
  {
    functionId: "comm_c2_11_ceremonial_blessings_performance",
    title: "Perform Traditional Ceremonial Benedictions (Ерөөл тавих)",
    mongolianTitle: "Найр хуримын ерөөл, зан үйлийн үгийг уран яруу айлдах",
    level: "C2",
    domain: "Ceremonial",
    prerequisites: ["comm_c2_09_metric_alliterative_poetry"],
    communicativeGoal: "Deliver improvised or classic rhythmic benedictions for housewarmings (гэрийн ерөөл) or first-haircut rites (даахь үргээх).",
    typicalScenarios: ["Countryside yurt raising celebration", "Child's first haircut celebration"],
    keyStructures: ["Алтан шаргал нар нь ээж байг / Мөнгөн саран дээрээс ивээж байг / Өнө мөнхөд жаргахын ерөөлийг өргөн дэвшүүлье!"],
    expectedOutcome: "Learner recites or chants rhythmic benedictions with booming acoustic projection and festive cadence."
  },
  {
    functionId: "comm_c2_12_praise_poetry_chanting",
    title: "Perform Praise Odes for Winning Wrestlers, Horses, and Mountains (Магтаал)",
    mongolianTitle: "Хүлэг морь, хүчит бөх, хайрхан уулын магтаал хайлах",
    level: "C2",
    domain: "Ceremonial",
    prerequisites: ["comm_c2_11_ceremonial_blessings_performance"],
    communicativeGoal: "Chant traditional praise poetry at festivals honoring champion horses, victorious wrestlers, or sacred peaks (Bogd Khan, Otgontenger).",
    typicalScenarios: ["Local Naadam festival closing ceremony", "Mountain oboo reverence ritual"],
    keyStructures: ["Түмэн эхийн магтаал", "Дархан аваргын цол дуудах", "Хан Богд уулын магтаал"],
    expectedOutcome: "Learner commands the solemn musical intonations and praise epithets characteristic of the magtaal genre."
  },
  {
    functionId: "comm_c2_13_proverbial_gnomic_deployment",
    title: "Deploy Pithy Proverbial Wisdom to Clinch Arguments Persuasively",
    mongolianTitle: "Зүйр цэцэн үг, ертөнцийн гурвыг яриандаа оновчтой шигтгэх",
    level: "C2",
    domain: "Cultural",
    prerequisites: ["comm_c2_04_somatic_steppe_idioms"],
    communicativeGoal: "Integrate folk proverbs (зүйр үг) and triads of the world (ертөнцийн гурав) to crystallize ethical points persuasively.",
    typicalScenarios: ["Keynote conclusions", "Mentoring young professionals", "Philosophical debate climax"],
    keyStructures: ["Дуслыг хураавал далай / Дуулсныг хураавал эрдэм", "Эвт шаазгай буга барина", "Ертөнцийн гурван хөөрхөн"],
    expectedOutcome: "Learner selects the exact folk aphorism that resolves a debate with moral and cultural authority."
  },
  {
    functionId: "comm_c2_14_pan_mongolian_dialect_comprehension",
    title: "Comprehend Oirat, Buryat, and Inner Mongolian Regional Dialects",
    mongolianTitle: "Ойрад, Буриад, Өвөр Монгол аялгууны онцлогийг сонсож ойлгох",
    level: "C2",
    domain: "Informational",
    prerequisites: ["comm_c2_08_omni_register_agility"],
    communicativeGoal: "Understand spoken and written variations across Western Oirat (Zakhchin, Dörvöd), Northern Buryat, and Southern Chahar speech.",
    typicalScenarios: ["Pan-Mongolian cultural festival", "Listening to radio broadcasts from Western aimags"],
    keyStructures: ["Аялгууны авианы онцлог шинжүүд", "Үгийн сангийн бүсийн ялгаа", "Хэлзүйн төстэй болон ялгаатай талууд"],
    expectedOutcome: "Learner demonstrates robust auditory and lexical comprehension across the major dialect groups."
  },
  {
    functionId: "comm_c2_15_creative_mastery_authorial_voice",
    title: "Demonstrate Authentic Authorial Voice in Creative Non-Fiction",
    mongolianTitle: "Өвөрмөц уран сэтгэмж, хувийн хэв маягаар эсээ бичлэг туурвих",
    level: "C2",
    domain: "Narrative",
    prerequisites: ["comm_c2_06_literary_polyphony_writing"],
    communicativeGoal: "Write original creative essays displaying a distinct personal literary voice, sensory imagery, and philosophical depth.",
    typicalScenarios: ["Publishing an essay collection", "Contributing to literary journals"],
    keyStructures: ["Хувь хүний дотоод ертөнц ба эх байгалийн сүлбээ", "Сэтгэлийн гүнд орших нарийн мэдрэмжүүд", "Үгийн урлагийн гайхамшиг"],
    expectedOutcome: "Learner exhibits supreme mastery of the Mongolian language as an instrument of original intellectual and literary creation."
  }
];
