import { LessonBlueprint } from "./lessonBlueprintTypes";

export const preA1_Units_08_to_11: LessonBlueprint[] = [
  // =========================================================================
  // UNIT 8: Vowel Length Contrast: Short vs Long Pairs (unit_pre_a1_08_vowel_length_pairs)
  // Target: Prod=8, Rec=3, ProdExp=2, RecExp=1 | Lessons: 5
  // =========================================================================
  {
    lessonId: "les_pre_a1_08_01_orthography_double_vowels",
    unitId: "unit_pre_a1_08_vowel_length_pairs",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 1,
    title: "Orthography of Long Vowels: Double Letters (аа, ээ, оо, уу, өө, үү, ий)",
    lessonType: "orthography",
    primaryPurpose: "Introduce the orthographic convention of representing phonemic vowel length through doubled Cyrillic vowel letters.",
    communicativeOutcome: "Recognize, read, and write double vowel graphemes across all seven vowel qualities.",
    objectivesIntroduced: ["obj_pre_a1_08_01_identify_double_vowels"],
    objectivesPracticed: [],
    objectivesReviewed: ["obj_pre_a1_03_01_classify_seven_vowels"],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: ["phono_vowel_long_pairs"],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_vowel_short_seven"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_general_education_literacy"],
    previousVocabularyReused: [],
    readingObjective: "Distinguish between single and double vowel spellings in isolated printed word cards.",
    listeningObjective: null,
    writingObjective: "Write doubled vowel sequences (аа, ээ, оо, уу, өө, үү, ий) with equal character sizing.",
    spokenProductionObjective: null,
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Following standard Mongolian orthographic conventions.",
    prerequisiteLessonIds: ["les_pre_a1_07_05_personal_identification_synthesis"],
    reviewsLessonIds: ["les_pre_a1_03_01_vowel_heptad_system"],
    reviewsUnitIds: ["unit_pre_a1_07_personal_names_and_identification"],
    reviewReason: "Expand cardinal short vowels into phonemically distinct long vowel series.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Contrasting audio durations for isolated short vs long vowels.",
    successCriteria: [
      "Correctly identify whether a written word contains a short or long vowel in 10 test items.",
      "Accurately write the special long counterpart for И (which is written 'ий' in non-initial syllables or 'ии')."
    ],
    masteryEvidence: [
      "Identifies that 'аа' represents twice the phonetic duration of 'а'.",
      "Does not confuse double letters with two distinct syllables."
    ],
    recommendedExerciseModalities: ["matching", "typing", "categorization"]
  },
  {
    lessonId: "les_pre_a1_08_02_acoustic_duration_contrast",
    unitId: "unit_pre_a1_08_vowel_length_pairs",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 2,
    title: "Acoustic Duration Discrimination: Short vs Long Vowels",
    lessonType: "phonology_introduction",
    primaryPurpose: "Train auditory perception to detect the roughly 2:1 duration ratio separating short vowels from long vowels.",
    communicativeOutcome: "Distinguish spoken short and long vowels in isolated syllables and continuous speech.",
    objectivesIntroduced: ["obj_pre_a1_08_02_discriminate_vowel_duration"],
    objectivesPracticed: ["obj_pre_a1_08_01_identify_double_vowels"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_vowel_long_pairs"],
    phonologyReviewed: [],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 1,
    lexicalDomains: ["lex_domain_general_education_literacy"],
    previousVocabularyReused: [],
    readingObjective: "Associate duration indicators (short vs long bars) with corresponding Cyrillic spellings.",
    listeningObjective: "Categorize played audio stimuli as 'богино' (short) or 'урт' (long) with immediate acoustic feedback.",
    writingObjective: "Transcribe the appropriate single or double vowel based purely on acoustic duration.",
    spokenProductionObjective: "Sustain long vowels for approximately double the time duration of short vowels without changing pitch or quality.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Developing precision in oral speech delivery.",
    prerequisiteLessonIds: ["les_pre_a1_08_01_orthography_double_vowels"],
    reviewsLessonIds: ["les_pre_a1_08_01_orthography_double_vowels"],
    reviewsUnitIds: [],
    reviewReason: "Acoustically ground double-vowel orthography into physical timing control.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Pristine duration contrast audio recorded by native speaker at standard tempo.",
    successCriteria: [
      "Achieve at least 90% accuracy on a short vs long vowel auditory discrimination test.",
      "Accurately sustain long vowels in spoken production tests."
    ],
    masteryEvidence: [
      "Distinguishes spoken [a] from [a:] with 100% consistency.",
      "Does not introduce pitch glide or diphthongization when holding long vowels."
    ],
    recommendedExerciseModalities: ["phonetic_discrimination", "dictation", "matching"]
  },
  {
    lessonId: "les_pre_a1_08_03_minimal_pairs_length_semantics",
    unitId: "unit_pre_a1_08_vowel_length_pairs",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 3,
    title: "Minimal Pair Semantic Shifts: хол vs хоол, шар vs шаар, сүр vs сүүр",
    lessonType: "vocabulary_introduction",
    primaryPurpose: "Demonstrate that vowel length is strictly phonemic in Mongolian and changes the entire lexical meaning of a word.",
    communicativeOutcome: "Avoid critical semantic errors by distinguishing everyday minimal pairs (хол 'far' vs хоол 'food', шар 'yellow' vs шаар 'balloon').",
    objectivesIntroduced: ["obj_pre_a1_08_03_master_length_minimal_pairs"],
    objectivesPracticed: ["obj_pre_a1_08_02_discriminate_vowel_duration"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_vowel_long_pairs"],
    phonologyReviewed: [],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 0,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_food_beverage_dining", "lex_domain_household_home_environment"],
    previousVocabularyReused: [],
    readingObjective: "Read contrastive sentence pairs featuring length minimal pairs (Энэ хол / Энэ хоол).",
    listeningObjective: "Select the intended meaning card upon hearing minimal pair audio.",
    writingObjective: "Spell the target word correctly to complete context sentences (Би ___ иднэ: хол / хоол).",
    spokenProductionObjective: "Pronounce 'хоол' and 'хол' distinctly when ordering or describing locations.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Ordering food accurately without lexical confusion.",
    prerequisiteLessonIds: ["les_pre_a1_08_02_acoustic_duration_contrast"],
    reviewsLessonIds: ["les_pre_a1_08_01_orthography_double_vowels", "les_pre_a1_08_02_acoustic_duration_contrast"],
    reviewsUnitIds: [],
    reviewReason: "Demonstrate the high communicative stakes of phonemic vowel length.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Clear lexical contrast audio recorded in identical pitch environments.",
    successCriteria: [
      "Match 6 minimal pair audio clips to their corresponding pictorial meanings with zero errors.",
      "Accurately spell 'хоол' (food) vs 'хол' (far) in context."
    ],
    masteryEvidence: [
      "Never orders 'хол' (distance) when meaning 'хоол' (meal).",
      "Correctly identifies that 'шар' is color yellow while 'шаар' is a balloon."
    ],
    recommendedExerciseModalities: ["matching", "phonetic_discrimination", "cloze"]
  },
  {
    lessonId: "les_pre_a1_08_04_reading_food_menus_signs_long_vowels",
    unitId: "unit_pre_a1_08_vowel_length_pairs",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 4,
    title: "Decoding Menus and Food Signs with Long Vowels: цай, хоол, бууз, хуушуур",
    lessonType: "reading_development",
    primaryPurpose: "Apply long vowel reading skills to real Mongolian dining menus, dish names, and storefront signs.",
    communicativeOutcome: "Read and comprehend foundational Mongolian culinary items (хоол 'food/meal', бууз 'steamed dumplings', хуушуур 'fried meat pies', цай 'tea').",
    objectivesIntroduced: ["obj_pre_a1_08_04_read_culinary_stems"],
    objectivesPracticed: ["obj_pre_a1_08_03_master_length_minimal_pairs"],
    objectivesReviewed: ["obj_pre_a1_01_04_read_public_cognate_signs"],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_vowel_long_pairs"],
    phonologyReviewed: ["phono_cyr_35_alphabet"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 1,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_food_beverage_dining"],
    previousVocabularyReused: [],
    readingObjective: "Scan an authentic Mongolian cafeteria menu board and identify 4 traditional food items.",
    listeningObjective: "Recognize spoken dish names in a busy canteen environment.",
    writingObjective: "Transcribe a 3-item food order correctly in Cyrillic.",
    spokenProductionObjective: "Read menu items aloud with correct vowel duration when ordering.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Navigating local cafeterias (цайны газар) and fast-casual eateries.",
    prerequisiteLessonIds: ["les_pre_a1_08_03_minimal_pairs_length_semantics"],
    reviewsLessonIds: ["les_pre_a1_08_01_orthography_double_vowels", "les_pre_a1_08_03_minimal_pairs_length_semantics"],
    reviewsUnitIds: ["unit_pre_a1_01_alphabet_consonants_intro"],
    reviewReason: "Anchor long vowel decoding in authentic hospitality and dining genres.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Authentic cafeteria order dialogues with background café atmosphere.",
    successCriteria: [
      "Identify 'хуушуур' and 'бууз' on a printed menu without error.",
      "Accurately read prices and dish names aloud."
    ],
    masteryEvidence: [
      "Reads 'хуушуур' with sustained back rounded vowel /ʊ:/ in both syllables.",
      "Selects correct dish when viewing food photography paired with Cyrillic labels."
    ],
    recommendedExerciseModalities: ["matching", "reading_comprehension", "short_answer_writing"]
  },
  {
    lessonId: "les_pre_a1_08_05_vowel_length_dictation_checkpoint",
    unitId: "unit_pre_a1_08_vowel_length_pairs",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 5,
    title: "Vowel Length Mastery & Spelling Evaluation",
    lessonType: "checkpoint",
    primaryPurpose: "Evaluate learner competence in distinguishing and writing single vs double vowels across spoken and written tasks.",
    communicativeOutcome: "Spell, read, and pronounce short and long vowel pairs with 100% orthographic and phonemic precision.",
    objectivesIntroduced: [],
    objectivesPracticed: ["obj_pre_a1_08_01_identify_double_vowels", "obj_pre_a1_08_02_discriminate_vowel_duration", "obj_pre_a1_08_03_master_length_minimal_pairs", "obj_pre_a1_08_04_read_culinary_stems"],
    objectivesReviewed: ["obj_pre_a1_03_01_classify_seven_vowels"],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_vowel_long_pairs"],
    phonologyReviewed: ["phono_vowel_short_seven"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 1,
    newReceptiveLemmaTarget: 0,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_general_education_literacy", "lex_domain_food_beverage_dining"],
    previousVocabularyReused: [],
    readingObjective: "Proofread and correct 5 words containing vowel length errors.",
    listeningObjective: "Transcribe 10 dictated words accurately representing single vs double vowels.",
    writingObjective: "Write 10 dictated items with zero vowel omission or unauthorized doubling.",
    spokenProductionObjective: "Read aloud 6 minimal pairs clearly demonstrating the 2:1 duration ratio.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Demonstrating solid orthographic reliability for culinary and domestic vocabulary.",
    prerequisiteLessonIds: ["les_pre_a1_08_04_reading_food_menus_signs_long_vowels"],
    reviewsLessonIds: ["les_pre_a1_08_01_orthography_double_vowels", "les_pre_a1_08_02_acoustic_duration_contrast", "les_pre_a1_08_03_minimal_pairs_length_semantics", "les_pre_a1_08_04_reading_food_menus_signs_long_vowels"],
    reviewsUnitIds: ["unit_pre_a1_03_cardinal_short_vowels"],
    reviewReason: "Unit 8 synthesis checkpoint closing the vowel length foundational sequence.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Standardized evaluation audio recording for vowel length spelling.",
    successCriteria: [
      "Achieve at least 90% on auditory vowel length transcription test.",
      "Zero semantic misidentifications between minimal pair items."
    ],
    masteryEvidence: [
      "Spells 'хоол', 'аав', 'ээж', 'үүд', 'бууз' with correct double vowels.",
      "Spells 'гал', 'гэр', 'ус', 'нар' with single short vowels accurately."
    ],
    recommendedExerciseModalities: ["dictation", "error_correction", "matching"]
  },

  // =========================================================================
  // UNIT 9: Diphthong Sequences: ай, ой, уй, үй, эй (unit_pre_a1_09_diphthongs_inventory)
  // Target: Prod=8, Rec=3, ProdExp=2, RecExp=1 | Lessons: 4
  // =========================================================================
  {
    lessonId: "les_pre_a1_09_01_diphthongs_formation_glides",
    unitId: "unit_pre_a1_09_diphthongs_inventory",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 1,
    title: "Diphthong Sequences with Short 'й': ай, ой, уй, үй, эй",
    lessonType: "orthography",
    primaryPurpose: "Introduce the orthography and articulatory glide mechanics of Mongolian diphthongs ending in short-i (й).",
    communicativeOutcome: "Recognize, read, and write the 5 primary diphthong sequences (ай, ой, уй, үй, эй) without confusing 'й' with 'и'.",
    objectivesIntroduced: ["obj_pre_a1_09_01_identify_diphthong_glyphs"],
    objectivesPracticed: [],
    objectivesReviewed: ["obj_pre_a1_08_01_identify_double_vowels"],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: ["phono_vowel_diphthongs"],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_vowel_long_pairs"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_general_education_literacy"],
    previousVocabularyReused: [],
    readingObjective: "Read isolated diphthong combinations and contrast them visually with long vowels (ай vs аа, ой vs оо).",
    listeningObjective: null,
    writingObjective: "Transcribe diphthong sequences maintaining clear distinction between full vowel 'и' and short 'й' (with breve).",
    spokenProductionObjective: null,
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Following standard spelling conventions in handwritten and typed Mongolian.",
    prerequisiteLessonIds: ["les_pre_a1_08_05_vowel_length_dictation_checkpoint"],
    reviewsLessonIds: ["les_pre_a1_08_01_orthography_double_vowels"],
    reviewsUnitIds: ["unit_pre_a1_08_vowel_length_pairs"],
    reviewReason: "Contrast diphthong glide sequences against long vowel monophthongs.",
    audioSuitability: "standard_speech_synthesis_acceptable",
    audioPurpose: "Clear acoustic gliding from nucleus vowel to palatal offglide.",
    successCriteria: [
      "Distinguish between 'и' and 'й' with 100% accuracy in 10 test words.",
      "Accurately write uppercase and lowercase 'Й-й' with the diacritic breve."
    ],
    masteryEvidence: [
      "Correctly identifies that 'ай' is a single syllable ending in a glide.",
      "Never omits the breve over 'й' when spelling diphthongs."
    ],
    recommendedExerciseModalities: ["matching", "typing", "categorization"]
  },
  {
    lessonId: "les_pre_a1_09_02_articulatory_acoustic_glides",
    unitId: "unit_pre_a1_09_diphthongs_inventory",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 2,
    title: "Auditory Discrimination: Long Monophthongs vs Diphthongs (аа vs ай, оо vs ой)",
    lessonType: "phonology_introduction",
    primaryPurpose: "Train acoustic perception to separate stable long vowels from dynamic offgliding diphthongs.",
    communicativeOutcome: "Distinguish between monophthongal long vowels and diphthongs in minimal pairs (маа vs май, соо vs сой).",
    objectivesIntroduced: ["obj_pre_a1_09_02_discriminate_diphthong_glides"],
    objectivesPracticed: ["obj_pre_a1_09_01_identify_diphthong_glyphs"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_vowel_diphthongs"],
    phonologyReviewed: ["phono_vowel_long_pairs"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 1,
    lexicalDomains: ["lex_domain_general_education_literacy"],
    previousVocabularyReused: [],
    readingObjective: "Read minimal pair cards (найр vs наар, ой vs оо) and link them to audio models.",
    listeningObjective: "Classify played audio tokens as monophthong or diphthong in an automated acoustic drill.",
    writingObjective: "Write the correct vowel nucleus (double vowel vs vowel+й) upon hearing isolated audio stimuli.",
    spokenProductionObjective: "Articulate the palatal offglide smoothly without breaking the diphthong into two distinct syllables.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Achieving phonemic accuracy in everyday vowel production.",
    prerequisiteLessonIds: ["les_pre_a1_09_01_diphthongs_formation_glides"],
    reviewsLessonIds: ["les_pre_a1_08_02_acoustic_duration_contrast", "les_pre_a1_09_01_diphthongs_formation_glides"],
    reviewsUnitIds: [],
    reviewReason: "Acoustically anchor diphthong glides against long vowel standards.",
    audioSuitability: "standard_speech_synthesis_acceptable",
    audioPurpose: "Precise glide recordings contrasting monophthongs with palatal offglides.",
    successCriteria: [
      "Score at least 9/10 on monophthong vs diphthong auditory sorting.",
      "Accurately articulate the front diphthong 'үй' vs back 'уй'."
    ],
    masteryEvidence: [
      "Pronounces 'цай' with smooth single-syllable diphthong.",
      "Differentiates 'ой' (forest/memory) from 'оо' (toothpaste/powder) cleanly."
    ],
    recommendedExerciseModalities: ["phonetic_discrimination", "matching", "dictation"]
  },
  {
    lessonId: "les_pre_a1_09_03_high_frequency_diphthong_vocabulary",
    unitId: "unit_pre_a1_09_diphthongs_inventory",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 3,
    title: "Essential Diphthong Vocabulary: цай, ой, нохой, гэр бүл, найз",
    lessonType: "vocabulary_introduction",
    primaryPurpose: "Introduce high-frequency domestic and kinship vocabulary containing diphthongs.",
    communicativeOutcome: "Read and comprehend everyday vocabulary (цай 'tea', ой 'forest/anniversary', нохой 'dog', гэр бүл 'family', найз 'friend').",
    objectivesIntroduced: ["obj_pre_a1_09_03_read_diphthong_nouns"],
    objectivesPracticed: ["obj_pre_a1_09_01_identify_diphthong_glyphs", "obj_pre_a1_09_02_discriminate_diphthong_glides"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_vowel_diphthongs"],
    phonologyReviewed: [],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_household_home_environment", "lex_domain_family_kinship_relations"],
    previousVocabularyReused: [],
    readingObjective: "Read disyllabic words containing diphthongs in short family and household captions.",
    listeningObjective: "Recognize spoken items (цай, найз, нохой) in simple home conversations.",
    writingObjective: "Write 5 common diphthong nouns accurately from memory.",
    spokenProductionObjective: "Introduce one's friend using 'Миний найз...' with accurate diphthong pronunciation.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Talking about friends, pets, and hospitality beverages.",
    prerequisiteLessonIds: ["les_pre_a1_09_02_articulatory_acoustic_glides"],
    reviewsLessonIds: ["les_pre_a1_09_01_diphthongs_formation_glides", "les_pre_a1_09_02_articulatory_acoustic_glides"],
    reviewsUnitIds: [],
    reviewReason: "Integrate diphthongs into high-utility social vocabulary.",
    audioSuitability: "standard_speech_synthesis_acceptable",
    audioPurpose: "Authentic family dialogues discussing tea and friends.",
    successCriteria: [
      "Correctly spell 'цай', 'нохой', 'найз' in context quizzes.",
      "Pair vocabulary items with family and domestic illustrations without error."
    ],
    masteryEvidence: [
      "Reads 'нохой' [nɔxœ:] with standard Khalkha rounded diphthong.",
      "Identifies 'гэр бүл' as family and 'найз' as friend immediately."
    ],
    recommendedExerciseModalities: ["matching", "cloze", "short_answer_writing"]
  },
  {
    lessonId: "les_pre_a1_09_04_diphthong_reading_and_dictation_checkpoint",
    unitId: "unit_pre_a1_09_diphthongs_inventory",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 4,
    title: "Diphthong Literacy & Dictation Synthesis",
    lessonType: "checkpoint",
    primaryPurpose: "Consolidate reading, spelling, and auditory discrimination of diphthongs through an integrated assessment.",
    communicativeOutcome: "Spell and read any standard Mongolian diphthong word accurately and reliably.",
    objectivesIntroduced: [],
    objectivesPracticed: ["obj_pre_a1_09_01_identify_diphthong_glyphs", "obj_pre_a1_09_02_discriminate_diphthong_glides", "obj_pre_a1_09_03_read_diphthong_nouns"],
    objectivesReviewed: ["obj_pre_a1_08_01_identify_double_vowels"],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_vowel_diphthongs"],
    phonologyReviewed: ["phono_vowel_long_pairs"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 0,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_general_education_literacy", "lex_domain_household_home_environment"],
    previousVocabularyReused: [],
    readingObjective: "Read a short 15-word passage about daily tea drinking containing multiple diphthongs.",
    listeningObjective: "Transcribe 8 dictated words containing contrastive diphthongs and long vowels.",
    writingObjective: "Spell dictated diphthong words with 100% orthographic accuracy.",
    spokenProductionObjective: "Read the evaluation passage aloud maintaining crisp glide boundaries.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Demonstrating mastery of Mongolian complex vowel systems.",
    prerequisiteLessonIds: ["les_pre_a1_09_03_high_frequency_diphthong_vocabulary"],
    reviewsLessonIds: ["les_pre_a1_09_01_diphthongs_formation_glides", "les_pre_a1_09_02_articulatory_acoustic_glides", "les_pre_a1_09_03_high_frequency_diphthong_vocabulary"],
    reviewsUnitIds: ["unit_pre_a1_08_vowel_length_pairs"],
    reviewReason: "Unit 9 synthesis completing the complex vowel foundation.",
    audioSuitability: "standard_speech_synthesis_acceptable",
    audioPurpose: "Standardized audio dictation evaluation of diphthongs.",
    successCriteria: [
      "Achieve at least 90% on diphthong dictation and reading evaluation.",
      "Zero confusion between 'ай' and 'аа', or 'ой' and 'оо'."
    ],
    masteryEvidence: [
      "Accurately transcribes 'цай ууна' (drinks tea) with proper diphthong and long vowel.",
      "Corrects misspellings in sample texts effortlessly."
    ],
    recommendedExerciseModalities: ["dictation", "error_correction", "reading_comprehension"]
  },

  // =========================================================================
  // UNIT 10: Vowel Harmony: Masculine vs Feminine Roots (unit_pre_a1_10_masculine_feminine_harmony)
  // Target: Prod=8, Rec=3, ProdExp=2, RecExp=1 | Lessons: 6
  // =========================================================================
  {
    lessonId: "les_pre_a1_10_01_masculine_back_vowels",
    unitId: "unit_pre_a1_10_masculine_feminine_harmony",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 1,
    title: "Masculine Vowel Class (Эр үг): А, О, У, Я, Ё, Ю (back)",
    lessonType: "grammar_introduction",
    primaryPurpose: "Define the masculine (back/retracted tongue root) vowel class and its orthographic members.",
    communicativeOutcome: "Identify masculine root words based on the presence of back vowels (а, о, у, я, ё, ю).",
    objectivesIntroduced: ["obj_pre_a1_10_01_identify_masculine_vowels"],
    objectivesPracticed: [],
    objectivesReviewed: ["obj_pre_a1_03_01_classify_seven_vowels"],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: ["phono_vowel_front_back_distinction", "phono_vowel_harmony_masc_fem"],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_vowel_short_seven"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_general_education_literacy"],
    previousVocabularyReused: [],
    readingObjective: "Scan a list of 10 words and flag those containing exclusively masculine vowels (ном, мод, багш, зам).",
    listeningObjective: "Detect the pharyngealized/back acoustic timbre of masculine roots in spoken audio.",
    writingObjective: "List the 6 masculine vowel letters and transcribe 3 masculine example words.",
    spokenProductionObjective: "Pronounce masculine root words with low larynx and retracted tongue root.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Applying grammatical terminology in linguistic instruction.",
    prerequisiteLessonIds: ["les_pre_a1_09_04_diphthong_reading_and_dictation_checkpoint"],
    reviewsLessonIds: ["les_pre_a1_03_03_vowel_harmony_intro_roots"],
    reviewsUnitIds: ["unit_pre_a1_03_cardinal_short_vowels"],
    reviewReason: "Formalize the foundational intuition of back root resonance introduced in Unit 3.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Pristine acoustic models of retracted tongue root (RTR) masculine vowels.",
    successCriteria: [
      "Categorize 10 isolated words into masculine vs non-masculine with 100% accuracy.",
      "State the rule that masculine vowels never co-occur with feminine vowels in native roots."
    ],
    masteryEvidence: [
      "Identifies that 'хот' (city) and 'улс' (state) are masculine words.",
      "Explains why a suffix attached to 'ном' must contain a back vowel."
    ],
    recommendedExerciseModalities: ["categorization", "matching", "phonetic_discrimination"]
  },
  {
    lessonId: "les_pre_a1_10_02_feminine_front_vowels",
    unitId: "unit_pre_a1_10_masculine_feminine_harmony",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 2,
    title: "Feminine Vowel Class (Эм үг): Э, Ө, Ү, Е, Ю (front)",
    lessonType: "grammar_introduction",
    primaryPurpose: "Define the feminine (front/advanced tongue root) vowel class and its orthographic members.",
    communicativeOutcome: "Identify feminine root words based on the presence of front vowels (э, ө, ү, е, ю).",
    objectivesIntroduced: ["obj_pre_a1_10_02_identify_feminine_vowels"],
    objectivesPracticed: ["obj_pre_a1_10_01_identify_masculine_vowels"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_vowel_front_back_distinction", "phono_vowel_harmony_masc_fem"],
    phonologyReviewed: [],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 0,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 1,
    lexicalDomains: ["lex_domain_general_education_literacy"],
    previousVocabularyReused: [],
    readingObjective: "Scan a list of 10 words and flag those containing exclusively feminine vowels (гэр, цэцэг, өвөл, үнэг).",
    listeningObjective: "Detect the bright/front acoustic timbre of feminine roots in spoken audio.",
    writingObjective: "List the feminine vowel letters and transcribe 3 feminine example words.",
    spokenProductionObjective: "Pronounce feminine root words with high tongue body and advanced tongue root.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Following grammatical explanations in Mongolian language instruction.",
    prerequisiteLessonIds: ["les_pre_a1_10_01_masculine_back_vowels"],
    reviewsLessonIds: ["les_pre_a1_10_01_masculine_back_vowels"],
    reviewsUnitIds: [],
    reviewReason: "Establish the symmetrical counterpart to the masculine vowel class.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Pristine acoustic models of advanced tongue root (ATR) feminine vowels.",
    successCriteria: [
      "Correctly classify words into masculine (эр үг) and feminine (эм үг) columns.",
      "Accurately identify feminine vowels in multisyllabic words."
    ],
    masteryEvidence: [
      "Identifies that 'цэцэг' (flower) and 'дэвтэр' (notebook) are feminine words.",
      "Explains that 'гэр' requires front-vowel suffixes."
    ],
    recommendedExerciseModalities: ["categorization", "matching", "phonetic_discrimination"]
  },
  {
    lessonId: "les_pre_a1_10_03_neutral_vowel_behavior_i",
    unitId: "unit_pre_a1_10_masculine_feminine_harmony",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 3,
    title: "The Neutral Vowel 'И' (Саармаг эгшиг) & Mixed Roots",
    lessonType: "grammar_guided_practice",
    primaryPurpose: "Explain the unique behavior of the vowel 'И', which can appear freely in both masculine and feminine words.",
    communicativeOutcome: "Determine the harmonic class of words containing 'И' based on the surrounding dominant vowels.",
    objectivesIntroduced: ["obj_pre_a1_10_03_apply_neutral_vowel_rules"],
    objectivesPracticed: ["obj_pre_a1_10_01_identify_masculine_vowels", "obj_pre_a1_10_02_identify_feminine_vowels"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: ["phono_neutral_vowel_behavior"],
    phonologyPracticed: ["phono_vowel_harmony_masc_fem"],
    phonologyReviewed: [],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 1,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_general_education_literacy"],
    previousVocabularyReused: [],
    readingObjective: "Determine the harmonic class of mixed words containing 'И' (багш -> masculine; эгч -> feminine; бичиг -> feminine by default).",
    listeningObjective: "Hear that 'И' adapts transparently to masculine backness or feminine frontness.",
    writingObjective: "Sort words containing 'И' into their proper masculine or feminine harmonic categories.",
    spokenProductionObjective: "Pronounce 'багш' with retracted [ɯ] resonance and 'бичиг' with front [i] resonance.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Handling the most common source of vowel harmony errors.",
    prerequisiteLessonIds: ["les_pre_a1_10_02_feminine_front_vowels"],
    reviewsLessonIds: ["les_pre_a1_10_01_masculine_back_vowels", "les_pre_a1_10_02_feminine_front_vowels"],
    reviewsUnitIds: [],
    reviewReason: "Master the exceptional behavior of neutral 'И' in harmonic classification.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Acoustic realization of allophonic variation of /i/ in back vs front words.",
    successCriteria: [
      "Correctly classify 'багш' as masculine and 'эмч' as feminine.",
      "Classify all-neutral words (бичиг, жижиг) as feminine for suffixing purposes."
    ],
    masteryEvidence: [
      "Selects masculine suffixes for 'аав' and 'багш' without hesitation.",
      "Explains that words containing only 'И' take feminine suffixes."
    ],
    recommendedExerciseModalities: ["categorization", "matching", "suffix_selection"]
  },
  {
    lessonId: "les_pre_a1_10_04_labial_rounding_harmony",
    unitId: "unit_pre_a1_10_masculine_feminine_harmony",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 4,
    title: "Labial Vowel Harmony: Rounding with О and Ө",
    lessonType: "grammar_guided_practice",
    primaryPurpose: "Introduce the secondary rounding harmony rule: first-syllable О and Ө demand rounded vowels (о, ө) in subsequent syllables.",
    communicativeOutcome: "Apply rounding harmony to recognize why words have 'о-о' or 'ө-ө' patterns (ногоо, өдөр, өвөл, толь).",
    objectivesIntroduced: ["obj_pre_a1_10_04_apply_labial_rounding"],
    objectivesPracticed: ["obj_pre_a1_10_01_identify_masculine_vowels", "obj_pre_a1_10_02_identify_feminine_vowels"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_vowel_harmony_masc_fem"],
    phonologyReviewed: ["phono_vowel_front_back_distinction"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 1,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_food_beverage_dining", "lex_domain_nature_geography_weather"],
    previousVocabularyReused: [],
    readingObjective: "Read disyllabic words demonstrating labial harmony (ногоо 'vegetable', одон 'star/medal', өдөр 'day', хөдөө 'countryside').",
    listeningObjective: "Detect sustained lip rounding throughout disyllabic stems starting with О or Ө.",
    writingObjective: "Complete words by filling in the rounded vowel required by initial О or Ө.",
    spokenProductionObjective: "Maintain lip rounding consistently across both syllables of 'хөдөө' and 'ногоо'.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Pronouncing culinary and rural terms with natural phonetic elegance.",
    prerequisiteLessonIds: ["les_pre_a1_10_03_neutral_vowel_behavior_i"],
    reviewsLessonIds: ["les_pre_a1_02_02_auditory_discrimination_minimal_pairs", "les_pre_a1_10_01_masculine_back_vowels"],
    reviewsUnitIds: ["unit_pre_a1_08_vowel_length_pairs"],
    reviewReason: "Integrate rounding dynamics with vowel harmony classification.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Authentic labial harmony audio showing sustained lip rounding.",
    successCriteria: [
      "Select 'о' rather than 'а' when completing stems with initial 'о' (ног___ -> ногоо).",
      "Select 'ө' rather than 'э' when completing stems with initial 'ө' (өд___ -> өдөр)."
    ],
    masteryEvidence: [
      "Pronounces 'хөдөө' without spreading lips on the second syllable.",
      "Explains that initial О never tolerates an unrounded А in the immediate next non-final syllable."
    ],
    recommendedExerciseModalities: ["cloze", "phonetic_discrimination", "matching"]
  },
  {
    lessonId: "les_pre_a1_10_05_predicting_fourfold_suffix_variants",
    unitId: "unit_pre_a1_10_masculine_feminine_harmony",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 5,
    title: "Predicting Suffix Vowels: The 4-Fold Pattern (-аа, -ээ, -оо, -өө)",
    lessonType: "grammar_guided_practice",
    primaryPurpose: "Teach learners how to predict which of the 4 harmonic suffix variants (-аа/-ээ/-оо/-өө) a noun selects.",
    communicativeOutcome: "Choose the correct fourfold suffix vowel for any native Mongolian noun base.",
    objectivesIntroduced: ["obj_pre_a1_10_05_predict_fourfold_suffixes"],
    objectivesPracticed: ["obj_pre_a1_10_01_identify_masculine_vowels", "obj_pre_a1_10_02_identify_feminine_vowels", "obj_pre_a1_10_04_apply_labial_rounding"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_vowel_harmony_masc_fem"],
    phonologyReviewed: [],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 1,
    newReceptiveLemmaTarget: 0,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_household_home_environment"],
    previousVocabularyReused: [],
    readingObjective: "Read noun + suffix combinations and identify whether the suffix vowel matches the root.",
    listeningObjective: "Detect harmony clashes in synthetic incorrect audio recordings.",
    writingObjective: "Attach the correct fourfold suffix allomorph to 6 sample root nouns (ном -> -оо; гэр -> -ээ; нар -> -аа; өдөр -> -өө).",
    spokenProductionObjective: "Produce suffixed forms smoothly without pausing at morpheme boundaries.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Setting the foundation for all subsequent nominal case and verbal suffixation in A1.",
    prerequisiteLessonIds: ["les_pre_a1_10_04_labial_rounding_harmony"],
    reviewsLessonIds: ["les_pre_a1_10_01_masculine_back_vowels", "les_pre_a1_10_02_feminine_front_vowels", "les_pre_a1_10_04_labial_rounding_harmony"],
    reviewsUnitIds: [],
    reviewReason: "Operationalize vowel harmony rules into active suffix selection skills.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Authentic pronunciation of suffixed noun stems.",
    successCriteria: [
      "Select correct fourfold suffix for 8 out of 8 nouns with 100% accuracy.",
      "Articulate suffixed forms with unified root-suffix vocalic resonance."
    ],
    masteryEvidence: [
      "Selects -оо for 'ном', -аа for 'аав', -ээ for 'гэр', and -өө for 'өдөр'.",
      "Explains why 'ном'-ээ is impossible in native Mongolian grammar."
    ],
    recommendedExerciseModalities: ["suffix_selection", "matching", "error_correction"]
  },
  {
    lessonId: "les_pre_a1_10_06_vowel_harmony_classification_checkpoint",
    unitId: "unit_pre_a1_10_masculine_feminine_harmony",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 6,
    title: "Vowel Harmony Comprehensive Mastery Checkpoint",
    lessonType: "checkpoint",
    primaryPurpose: "Evaluate learner mastery of root classification (masculine, feminine, neutral) and fourfold suffix selection.",
    communicativeOutcome: "Analyze any unfamiliar word and determine its harmonic category and appropriate suffix vowel with complete accuracy.",
    objectivesIntroduced: [],
    objectivesPracticed: ["obj_pre_a1_10_01_identify_masculine_vowels", "obj_pre_a1_10_02_identify_feminine_vowels", "obj_pre_a1_10_03_apply_neutral_vowel_rules", "obj_pre_a1_10_04_apply_labial_rounding", "obj_pre_a1_10_05_predict_fourfold_suffixes"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_vowel_front_back_distinction", "phono_vowel_harmony_masc_fem", "phono_neutral_vowel_behavior"],
    phonologyReviewed: ["phono_vowel_short_seven", "phono_vowel_long_pairs"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 1,
    newReceptiveLemmaTarget: 0,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_general_education_literacy"],
    previousVocabularyReused: [],
    readingObjective: "Classify 12 diverse vocabulary items into masculine, feminine, and rounded sub-classes.",
    listeningObjective: "Identify vowel harmony violations in spoken sentence clips.",
    writingObjective: "Attach correct fourfold suffixes to 10 assorted roots with 100% accuracy.",
    spokenProductionObjective: "Read aloud suffixed nouns demonstrating natural harmonic vocal resonance.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Solidifying core structural phonology required for all future A1 grammar.",
    prerequisiteLessonIds: ["les_pre_a1_10_05_predicting_fourfold_suffix_variants"],
    reviewsLessonIds: ["les_pre_a1_10_01_masculine_back_vowels", "les_pre_a1_10_02_feminine_front_vowels", "les_pre_a1_10_03_neutral_vowel_behavior_i", "les_pre_a1_10_04_labial_rounding_harmony", "les_pre_a1_10_05_predicting_fourfold_suffix_variants"],
    reviewsUnitIds: ["unit_pre_a1_03_cardinal_short_vowels", "unit_pre_a1_08_vowel_length_pairs"],
    reviewReason: "Unit 10 capstone evaluating the most foundational phonological mechanism of Mongolian.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Diagnostic audio items testing suffix harmony discrimination.",
    successCriteria: [
      "Achieve at least 95% on fourfold suffix prediction test.",
      "Zero classification errors across masculine, feminine, and neutral nouns."
    ],
    masteryEvidence: [
      "Flawlessly handles loan words, native roots, and neutral-vowel stems.",
      "Explains harmonic mechanics clearly without confusion."
    ],
    recommendedExerciseModalities: ["suffix_selection", "categorization", "error_correction"]
  },

  // =========================================================================
  // UNIT 11: Iotated Vowels (Я, Е, Ё, Ю) & Signs (Ъ, Ь) (unit_pre_a1_11_iotated_vowels_signs)
  // Target: Prod=8, Rec=3, ProdExp=2, RecExp=1 | Lessons: 5
  // =========================================================================
  {
    lessonId: "les_pre_a1_11_01_iotated_vowels_inventory",
    unitId: "unit_pre_a1_11_iotated_vowels_signs",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 1,
    title: "Iotated Vowels: Я (/ja/), Е (/je/), Ё (/jɔ/), Ю (/jʊ/ & /ju/)",
    lessonType: "orthography",
    primaryPurpose: "Introduce the four iotated Cyrillic vowel letters and their dual phonetic function as palatal glide + vowel.",
    communicativeOutcome: "Recognize, read, and transcribe the iotated letters Я, Е, Ё, Ю in isolation and word-initial position.",
    objectivesIntroduced: ["obj_pre_a1_11_01_identify_iotated_vowels"],
    objectivesPracticed: [],
    objectivesReviewed: ["obj_pre_a1_01_01_identify_shared_glyphs", "obj_pre_a1_03_01_classify_seven_vowels"],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: ["phono_iotated_vowels_behavior"],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_vowel_short_seven"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_general_education_literacy"],
    previousVocabularyReused: [],
    readingObjective: "Read isolated iotated characters and associate them with their base vowel counterparts (Я=й+а, Е=й+э, Ё=й+о, Ю=й+у/ү).",
    listeningObjective: null,
    writingObjective: "Write uppercase and lowercase Я-я, Е-е, Ё-ё, Ю-ю with correct stroke sequences.",
    spokenProductionObjective: null,
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Following standard alphabetical instructions.",
    prerequisiteLessonIds: ["les_pre_a1_10_06_vowel_harmony_classification_checkpoint"],
    reviewsLessonIds: ["les_pre_a1_01_01_shared_consonants_visual", "les_pre_a1_03_01_vowel_heptad_system"],
    reviewsUnitIds: ["unit_pre_a1_10_masculine_feminine_harmony"],
    reviewReason: "Integrate iotated glide vowels into the vowel harmony system.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Clear onset glide articulation in isolated iotated vowels.",
    successCriteria: [
      "Match all 4 iotated letters with their decomposed glide+vowel values.",
      "Accurately write the diaeresis dots over Ё-ё without omission."
    ],
    masteryEvidence: [
      "Identifies that Я contains the back vowel /a/.",
      "Recognizes that Ё contains the back rounded vowel /ɔ/."
    ],
    recommendedExerciseModalities: ["matching", "typing", "categorization"]
  },
  {
    lessonId: "les_pre_a1_11_02_iotated_vowels_harmony_dual_yu",
    unitId: "unit_pre_a1_11_iotated_vowels_signs",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 2,
    title: "Vowel Harmony of Iotated Letters & The Dual Nature of Ю (back vs front)",
    lessonType: "grammar_guided_practice",
    primaryPurpose: "Classify iotated vowels into harmonic classes and teach the split identity of Ю (masculine /jʊ/ vs feminine /ju/).",
    communicativeOutcome: "Correctly assign words with iotated vowels to masculine (я, ё, ю-back) or feminine (е, ю-front) classes.",
    objectivesIntroduced: ["obj_pre_a1_11_02_classify_iotated_harmony"],
    objectivesPracticed: ["obj_pre_a1_11_01_identify_iotated_vowels"],
    objectivesReviewed: ["obj_pre_a1_10_01_identify_masculine_vowels", "obj_pre_a1_10_02_identify_feminine_vowels"],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_iotated_vowels_behavior", "phono_vowel_harmony_masc_fem"],
    phonologyReviewed: [],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 1,
    lexicalDomains: ["lex_domain_general_education_literacy"],
    previousVocabularyReused: [],
    readingObjective: "Read words starting with iotated vowels and predict their harmonic suffix (явах -> -аад; ерөнхий -> -өөд).",
    listeningObjective: "Discriminate the back rounded glide in 'юм' (/jʊm/ 'thing') vs front rounded glide in 'юүл' (/jyl/ 'pour').",
    writingObjective: "Sort words with iotated vowels into masculine and feminine suffix categories.",
    spokenProductionObjective: "Pronounce masculine 'явах' and feminine 'ерөнхий' with appropriate vocalic resonance.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Eliminating harmonic errors when suffixing words with initial iotated vowels.",
    prerequisiteLessonIds: ["les_pre_a1_11_01_iotated_vowels_inventory"],
    reviewsLessonIds: ["les_pre_a1_10_01_masculine_back_vowels", "les_pre_a1_10_02_feminine_front_vowels", "les_pre_a1_11_01_iotated_vowels_inventory"],
    reviewsUnitIds: ["unit_pre_a1_10_masculine_feminine_harmony"],
    reviewReason: "Resolve the harmonic complexity introduced by iotated graphemes.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Acoustic demonstration of the back vs front realization of letter Ю.",
    successCriteria: [
      "Correctly classify 'явах', 'ёроол', and 'юм' as masculine roots.",
      "Correctly classify 'ерөөл' and 'юүл' as feminine roots."
    ],
    masteryEvidence: [
      "Selects masculine suffix for 'явах' (явах-аар).",
      "Selects feminine suffix for 'ерөнхий' (ерөнхий-дөө)."
    ],
    recommendedExerciseModalities: ["categorization", "suffix_selection", "phonetic_discrimination"]
  },
  {
    lessonId: "les_pre_a1_11_03_soft_sign_palatalization",
    unitId: "unit_pre_a1_11_iotated_vowels_signs",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 3,
    title: "The Soft Sign (Зөөлний тэмдэг Ь): Palatalization of Preceding Consonants",
    lessonType: "orthography",
    primaryPurpose: "Explain the phonetic role of the soft sign (ь) in palatalizing preceding consonants and creating non-syllabic palatal offglides.",
    communicativeOutcome: "Pronounce and read words with the soft sign (морь 'horse', тань 'acquaint', сонин 'newspaper', барь 'hold').",
    objectivesIntroduced: ["obj_pre_a1_11_03_apply_soft_sign_palatalization"],
    objectivesPracticed: [],
    objectivesReviewed: ["obj_pre_a1_04_01_identify_obstruent_glyphs"],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: ["phono_soft_and_hard_signs"],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_consonant_basic_inventory"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 1,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_household_home_environment", "lex_domain_animals_wildlife_nature"],
    previousVocabularyReused: [],
    readingObjective: "Read monosyllabic and disyllabic words ending in the soft sign (морь, барь, тарь, зорь).",
    listeningObjective: "Discriminate plain vs palatalized final consonants (мор vs морь) in minimal pair audio.",
    writingObjective: "Transcribe words ending in the soft sign without confusing 'ь' with 'ъ' or 'ы'.",
    spokenProductionObjective: "Articulate palatalized final consonants with secondary palatal tongue elevation without adding an extra syllable.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Accurately identifying nomadic cultural symbols like 'морь' (horse).",
    prerequisiteLessonIds: ["les_pre_a1_11_02_iotated_vowels_harmony_dual_yu"],
    reviewsLessonIds: ["les_pre_a1_04_03_nasals_liquids_sonorants", "les_pre_a1_11_01_iotated_vowels_inventory"],
    reviewsUnitIds: ["unit_pre_a1_04_consonants_inventory_stops"],
    reviewReason: "Anchor palatal consonant modification into syllable decoding.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Authentic palatalized consonant pronunciation by native speaker.",
    successCriteria: [
      "Distinguish 'мор' vs 'морь' in 8 out of 8 listening checks.",
      "Accurately write 'морь' (horse) with soft sign from memory."
    ],
    masteryEvidence: [
      "Pronounces 'морь' as a single syllable with palatalized /rʲ/.",
      "Does not pronounce 'ь' as an independent vowel sound."
    ],
    recommendedExerciseModalities: ["phonetic_discrimination", "matching", "dictation"]
  },
  {
    lessonId: "les_pre_a1_11_04_hard_sign_separator",
    unitId: "unit_pre_a1_11_iotated_vowels_signs",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 4,
    title: "The Hard Sign (Хатуугийн тэмдэг Ъ): Silent Syllable Separation",
    lessonType: "orthography",
    primaryPurpose: "Explain the silent separator role of the hard sign (ъ) in preventing palatalization before iotated vowels in masculine words.",
    communicativeOutcome: "Read and write words containing the hard sign separator (оръё, явъя, өгье vs авъя).",
    objectivesIntroduced: ["obj_pre_a1_11_04_apply_hard_sign_separator"],
    objectivesPracticed: ["obj_pre_a1_11_03_apply_soft_sign_palatalization"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_soft_and_hard_signs"],
    phonologyReviewed: [],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 0,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_general_education_literacy"],
    previousVocabularyReused: [],
    readingObjective: "Read polite volitional and suggestion verb forms featuring the hard sign (явъя 'let's go', оръё 'let's enter').",
    listeningObjective: "Notice the distinct syllable break without palatalization before the glide.",
    writingObjective: "Choose between 'ъ' (for masculine stems) and 'ь' (for feminine stems) in cohortative endings (явъя vs үзье).",
    spokenProductionObjective: "Articulate 'явъя' with clear non-palatalized [w] followed by clean iotated onset [ja].",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Making natural conversational suggestions ('Let's go!').",
    prerequisiteLessonIds: ["les_pre_a1_11_03_soft_sign_palatalization"],
    reviewsLessonIds: ["les_pre_a1_10_01_masculine_back_vowels", "les_pre_a1_10_02_feminine_front_vowels", "les_pre_a1_11_03_soft_sign_palatalization"],
    reviewsUnitIds: [],
    reviewReason: "Complete the contrast between soft and hard orthographic signs.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Native pronunciation of cohortative verb suggestions (явъя, оръё, үзье).",
    successCriteria: [
      "Select 'ъ' for masculine roots and 'ь' for feminine roots in cohortative verb prompts with 100% accuracy.",
      "Accurately read aloud 'явъя' with natural conversational enthusiasm."
    ],
    masteryEvidence: [
      "Correctly writes 'явъя' with hard sign and 'үзье' with soft sign.",
      "Explains that hard sign occurs only in masculine harmonic environments."
    ],
    recommendedExerciseModalities: ["suffix_selection", "cloze", "dialogue_completion"]
  },
  {
    lessonId: "les_pre_a1_11_05_iotated_letters_signs_synthesis",
    unitId: "unit_pre_a1_11_iotated_vowels_signs",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 5,
    title: "Iotated Vowels & Signs Comprehensive Dictation Checkpoint",
    lessonType: "checkpoint",
    primaryPurpose: "Assess integrated decoding and spelling of words with iotated vowels, soft signs, and hard signs.",
    communicativeOutcome: "Read and spell complex Cyrillic words containing glides and orthographic signs with zero phonetic ambiguity.",
    objectivesIntroduced: [],
    objectivesPracticed: ["obj_pre_a1_11_01_identify_iotated_vowels", "obj_pre_a1_11_02_classify_iotated_harmony", "obj_pre_a1_11_03_apply_soft_sign_palatalization", "obj_pre_a1_11_04_apply_hard_sign_separator"],
    objectivesReviewed: ["obj_pre_a1_10_01_identify_masculine_vowels"],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_iotated_vowels_behavior", "phono_soft_and_hard_signs"],
    phonologyReviewed: ["phono_vowel_harmony_masc_fem", "phono_consonant_basic_inventory"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 1,
    newReceptiveLemmaTarget: 0,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_general_education_literacy"],
    previousVocabularyReused: [],
    readingObjective: "Proofread a short 20-word text and correct 4 spelling errors involving ь, ъ, and iotated letters.",
    listeningObjective: "Transcribe 10 dictated words covering the full inventory of iotated vowels and signs.",
    writingObjective: "Write dictated vocabulary with 100% orthographic accuracy.",
    spokenProductionObjective: "Read the evaluated words aloud with authentic palatalization and glide timing.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Achieving full orthographic literacy across the entire 35-letter Cyrillic alphabet.",
    prerequisiteLessonIds: ["les_pre_a1_11_04_hard_sign_separator"],
    reviewsLessonIds: ["les_pre_a1_11_01_iotated_vowels_inventory", "les_pre_a1_11_02_iotated_vowels_harmony_dual_yu", "les_pre_a1_11_03_soft_sign_palatalization", "les_pre_a1_11_04_hard_sign_separator"],
    reviewsUnitIds: ["unit_pre_a1_04_consonants_inventory_stops", "unit_pre_a1_10_masculine_feminine_harmony"],
    reviewReason: "Unit 11 synthesis concluding the complete Cyrillic orthographic inventory.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Diagnostic audio dictation items evaluating iotated letters and signs.",
    successCriteria: [
      "Achieve at least 90% on iotated vowels and signs dictation test.",
      "Zero errors distinguishing between ь, ъ, and normal vowels."
    ],
    masteryEvidence: [
      "Correctly writes 'морь', 'явъя', 'баяр', 'ерөөл', 'сургууль'.",
      "Demonstrates total mastery of the 35-letter Cyrillic alphabet."
    ],
    recommendedExerciseModalities: ["dictation", "error_correction", "matching"]
  }
];
