import { LessonBlueprint } from "./lessonBlueprintTypes";

export const preA1_Units_12_to_15: LessonBlueprint[] = [
  // =========================================================================
  // UNIT 12: Syllable Structure & Word-Level Stress (unit_pre_a1_12_survival_greetings_farewells)
  // Target: Prod=8, Rec=3, ProdExp=2, RecExp=1 | Lessons: 5
  // =========================================================================
  {
    lessonId: "les_pre_a1_12_01_syllable_types_cvc_ccvc",
    unitId: "unit_pre_a1_12_survival_greetings_farewells",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 1,
    title: "Mongolian Syllable Canons: V, CV, CVC, and Complex Codas (CVCC)",
    lessonType: "phonology_introduction",
    primaryPurpose: "Analyze permissible syllable templates in Khalkha Mongolian, focusing on consonant cluster codas.",
    communicativeOutcome: "Break polysyllabic words into valid phonetic syllables without inserting unauthorized epenthetic vowels.",
    objectivesIntroduced: ["obj_pre_a1_12_01_parse_syllables"],
    objectivesPracticed: [],
    objectivesReviewed: ["obj_pre_a1_04_01_identify_obstruent_glyphs", "obj_pre_a1_08_01_identify_double_vowels"],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: ["phono_syllable_templates"],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_consonant_basic_inventory"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_general_education_literacy"],
    previousVocabularyReused: [],
    readingObjective: "Divide 8 printed words into their structural syllables using hyphenation marks (ном-нууд, сур-гууль).",
    listeningObjective: "Count the number of audible syllables in spoken Mongolian words.",
    writingObjective: "Write hyphenated syllable boundaries for 6 disyllabic and trisyllabic words.",
    spokenProductionObjective: "Pronounce words with final consonant clusters (галст, дөрст) cleanly without trailing release vowels.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Following standard reading instruction guidelines.",
    prerequisiteLessonIds: ["les_pre_a1_11_05_iotated_letters_signs_synthesis"],
    reviewsLessonIds: ["les_pre_a1_01_03_simple_syllables_reading"],
    reviewsUnitIds: ["unit_pre_a1_11_iotated_vowels_signs"],
    reviewReason: "Deepen basic syllable blending into advanced syllable phonotactics.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Carefully articulated syllable segmentation audio by native speaker.",
    successCriteria: [
      "Correctly parse syllables in 8 out of 8 target words.",
      "Accurately identify valid vs invalid consonant coda combinations."
    ],
    masteryEvidence: [
      "Breaks 'сургууль' into сур-гууль accurately.",
      "Does not insert an extra vowel between consonant clusters in codas."
    ],
    recommendedExerciseModalities: ["categorization", "matching", "phonetic_discrimination"]
  },
  {
    lessonId: "les_pre_a1_12_02_first_syllable_stress_rule",
    unitId: "unit_pre_a1_12_survival_greetings_farewells",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 2,
    title: "Initial Syllable Stress & Prominence Hierarchy",
    lessonType: "phonology_introduction",
    primaryPurpose: "Teach the primary stress rule: stress falls on the initial syllable, or shifts to the first full/long vowel.",
    communicativeOutcome: "Pronounce Mongolian words with natural word-level dynamic accent on the correct syllable.",
    objectivesIntroduced: ["obj_pre_a1_12_02_apply_stress_rules"],
    objectivesPracticed: ["obj_pre_a1_12_01_parse_syllables"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: ["phono_stress_initial_and_full_vowels"],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_vowel_long_pairs"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 1,
    lexicalDomains: ["lex_domain_general_education_literacy"],
    previousVocabularyReused: [],
    readingObjective: "Mark the stressed syllable on 10 vocabulary cards (У́лаанбаатар, Ба́т, Багшаа́).",
    listeningObjective: "Identify which syllable bears acoustic prominence (pitch peak, intensity) in spoken words.",
    writingObjective: "Place acute stress marks over the stressed vowel in transcribed words.",
    spokenProductionObjective: "Produce dynamic intensity on the initial syllable, shifting to long vowels when present.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Eliminating unnatural foreign sentence cadence and lexical rhythm.",
    prerequisiteLessonIds: ["les_pre_a1_12_01_syllable_types_cvc_ccvc"],
    reviewsLessonIds: ["les_pre_a1_08_02_acoustic_duration_contrast", "les_pre_a1_12_01_syllable_types_cvc_ccvc"],
    reviewsUnitIds: [],
    reviewReason: "Connect vowel length hierarchy to word-level stress assignment.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Authentic pitch and intensity contour recordings illustrating stress shift.",
    successCriteria: [
      "Correctly locate stress in words containing only short vowels (first syllable).",
      "Correctly locate stress in words containing a non-initial long vowel (shifts to long vowel)."
    ],
    masteryEvidence: [
      "Stresses 'ө́дөр' on the first syllable.",
      "Stresses 'багшаа́' on the final long vowel /a:/."
    ],
    recommendedExerciseModalities: ["phonetic_discrimination", "matching", "dictation"]
  },
  {
    lessonId: "les_pre_a1_12_03_non_initial_vowel_reduction",
    unitId: "unit_pre_a1_12_survival_greetings_farewells",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 3,
    title: "Non-Initial Short Vowel Reduction & Epenthetic Vowels",
    lessonType: "phonology_introduction",
    primaryPurpose: "Explain the phenomenon of non-initial short vowel reduction, where non-initial vowels reduce to brief schwa-like vowels.",
    communicativeOutcome: "Read and pronounce non-initial short vowels without over-articulating them, sounding natural to native speakers.",
    objectivesIntroduced: ["obj_pre_a1_12_03_apply_vowel_reduction"],
    objectivesPracticed: ["obj_pre_a1_12_02_apply_stress_rules"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: ["phono_non_initial_reduction"],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_vowel_short_seven"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 1,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_household_home_environment"],
    previousVocabularyReused: [],
    readingObjective: "Read disyllabic words (ажил, амьдрал, дэвтэр) understanding that the second vowel is phonetically reduced.",
    listeningObjective: "Hear the ultra-short duration of non-initial short vowels compared to initial stressed vowels.",
    writingObjective: "Transcribe words retaining the written historical vowel letter despite its reduced acoustic presence.",
    spokenProductionObjective: "Shadow audio models reducing non-initial short vowels to natural centralized qualities.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Overcoming artificial 'spelling-pronunciation' habits.",
    prerequisiteLessonIds: ["les_pre_a1_12_02_first_syllable_stress_rule"],
    reviewsLessonIds: ["les_pre_a1_12_02_first_syllable_stress_rule"],
    reviewsUnitIds: [],
    reviewReason: "Acoustically ground the major discrepancy between Cyrillic spelling and Khalkha spoken reality.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Contrasting hyper-articulated vs natural reduced speech in native audio.",
    successCriteria: [
      "Identify the reduced vowel in 6 disyllabic words.",
      "Produce 'ажил' as [adʒĭɬ] rather than over-enunciating [adʒil]."
    ],
    masteryEvidence: [
      "Pronounces 'дэвтэр' with reduced second syllable without losing the consonant coda.",
      "Spells 'амьдрал' correctly retaining the written short 'а'."
    ],
    recommendedExerciseModalities: ["phonetic_discrimination", "matching", "dictation"]
  },
  {
    lessonId: "les_pre_a1_12_04_reading_polysyllabic_city_signs",
    unitId: "unit_pre_a1_12_survival_greetings_farewells",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 4,
    title: "Decoding Polysyllabic Signs & Public Institutions",
    lessonType: "reading_development",
    primaryPurpose: "Apply syllable parsing and stress principles to read complex multi-syllable public institution signs and building placards.",
    communicativeOutcome: "Read and comprehend multi-syllable institution names (их сургууль 'university', эмнэлэг 'hospital', номын сан 'library').",
    objectivesIntroduced: ["obj_pre_a1_12_04_read_polysyllabic_signs"],
    objectivesPracticed: ["obj_pre_a1_12_01_parse_syllables", "obj_pre_a1_12_02_apply_stress_rules", "obj_pre_a1_12_03_apply_vowel_reduction"],
    objectivesReviewed: ["obj_pre_a1_04_04_read_street_signs"],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_syllable_templates", "phono_stress_initial_and_full_vowels"],
    phonologyReviewed: ["phono_cyr_35_alphabet"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 0,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_public_spaces_urban_navigation", "lex_domain_public_administration_civic_life"],
    previousVocabularyReused: [],
    readingObjective: "Scan and read 5 authentic institutional signs in Ulaanbaatar.",
    listeningObjective: "Identify institutional names announced over transit loudspeakers.",
    writingObjective: "Write the names of 3 key public facilities correctly in Cyrillic.",
    spokenProductionObjective: "Read multi-syllable signs aloud with fluent syllable pacing and accurate stress.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Navigating municipal administrative and educational centers.",
    prerequisiteLessonIds: ["les_pre_a1_12_03_non_initial_vowel_reduction"],
    reviewsLessonIds: ["les_pre_a1_04_04_decoding_street_signs_stems", "les_pre_a1_12_02_first_syllable_stress_rule"],
    reviewsUnitIds: ["unit_pre_a1_04_consonants_inventory_stops"],
    reviewReason: "Synthesize stress and syllable mastery on urban administrative signage.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Authentic urban announcements of institutional destinations.",
    successCriteria: [
      "Decode 'МУИС' (Монгол Улсын Их Сургууль) and 'Төв Номын Сан' on photographic placards.",
      "Accurately pronounce 4-syllable compounds without stumbling over codas."
    ],
    masteryEvidence: [
      "Identifies 'Эмнэлэг' as hospital immediately.",
      "Pronounces 'их сургууль' with correct stress and reduced final vowel."
    ],
    recommendedExerciseModalities: ["matching", "reading_comprehension", "short_answer_writing"]
  },
  {
    lessonId: "les_pre_a1_12_05_rhythm_and_stress_synthesis_checkpoint",
    unitId: "unit_pre_a1_12_survival_greetings_farewells",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 5,
    title: "Syllable Parsing & Stress Mastery Checkpoint",
    lessonType: "checkpoint",
    primaryPurpose: "Evaluate learner ability to parse syllables, predict stress placement, and apply natural vowel reduction.",
    communicativeOutcome: "Pronounce, spell, and parse polysyllabic Mongolian vocabulary with native-like rhythmic cadence.",
    objectivesIntroduced: [],
    objectivesPracticed: ["obj_pre_a1_12_01_parse_syllables", "obj_pre_a1_12_02_apply_stress_rules", "obj_pre_a1_12_03_apply_vowel_reduction", "obj_pre_a1_12_04_read_polysyllabic_signs"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_syllable_templates", "phono_stress_initial_and_full_vowels", "phono_non_initial_reduction"],
    phonologyReviewed: ["phono_vowel_long_pairs", "phono_consonant_basic_inventory"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 1,
    newReceptiveLemmaTarget: 0,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_general_education_literacy"],
    previousVocabularyReused: [],
    readingObjective: "Read aloud a 30-word descriptive text with natural rhythmic stress and vowel reduction.",
    listeningObjective: "Identify words with non-standard stress placement from spoken audio samples.",
    writingObjective: "Transcribe 8 polysyllabic words with correct syllable divisions.",
    spokenProductionObjective: "Demonstrate accurate stress shift when suffixes with long vowels are added to nominal roots.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Demonstrating polished oral reading fluency.",
    prerequisiteLessonIds: ["les_pre_a1_12_04_reading_polysyllabic_city_signs"],
    reviewsLessonIds: ["les_pre_a1_12_01_syllable_types_cvc_ccvc", "les_pre_a1_12_02_first_syllable_stress_rule", "les_pre_a1_12_03_non_initial_vowel_reduction", "les_pre_a1_12_04_reading_polysyllabic_city_signs"],
    reviewsUnitIds: ["unit_pre_a1_08_vowel_length_pairs", "unit_pre_a1_11_iotated_vowels_signs"],
    reviewReason: "Unit 12 synthesis consolidating phonotactic and prosodic mastery.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Diagnostic audio dictation items evaluating syllable cadence.",
    successCriteria: [
      "Achieve at least 90% on syllable parsing and stress placement evaluation.",
      "Demonstrate zero foreign stress placement on non-initial short syllables."
    ],
    masteryEvidence: [
      "Flawlessly reads multi-syllable words like 'байгууллага' and 'аялагчид'.",
      "Divides words into syllables adhering strictly to Mongolian phonotactic rules."
    ],
    recommendedExerciseModalities: ["dictation", "error_correction", "reading_comprehension"]
  },

  // =========================================================================
  // UNIT 13: Core Greetings & Social Pleasantries (unit_pre_a1_13_gratitude_apologies_politeness)
  // Target: Prod=8, Rec=3, ProdExp=2, RecExp=1 | Lessons: 5
  // =========================================================================
  {
    lessonId: "les_pre_a1_13_01_universal_greeting_sain_baina_uu",
    unitId: "unit_pre_a1_13_gratitude_apologies_politeness",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 1,
    title: "The Universal Greeting: Сайн байна уу? & Сайн, сайн байна уу?",
    lessonType: "dialogue_work",
    primaryPurpose: "Teach the structure, pronunciation, and polite response patterns for the ubiquitous greeting 'Сайн байна уу?'.",
    communicativeOutcome: "Initiate greetings with 'Сайн байна уу?' and respond appropriately with 'Сайн, сайн байна уу?' across all social settings.",
    objectivesIntroduced: ["obj_pre_a1_13_01_use_basic_greeting"],
    objectivesPracticed: [],
    objectivesReviewed: ["obj_pre_a1_12_02_apply_stress_rules"],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: ["phono_intonation_greetings"],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_stress_initial_and_full_vowels"],
    communicativeFunctionsIntroduced: ["comm_a1_01_greetings_farewells"],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_social_interaction_courtesy"],
    previousVocabularyReused: [],
    readingObjective: "Read written greeting dialogue exchanges in comic-strip format.",
    listeningObjective: "Recognize 'Сайн байна уу' in rapid conversational audio.",
    writingObjective: "Transcribe the greeting phrase and question mark correctly in Cyrillic.",
    spokenProductionObjective: "Utter 'Сайн байна уу?' with natural rising-falling conversational intonation.",
    registerTarget: "polite_formal",
    pragmaticTarget: "Opening face-to-face interactions respectfully with strangers and acquaintances.",
    prerequisiteLessonIds: ["les_pre_a1_12_05_rhythm_and_stress_synthesis_checkpoint"],
    reviewsLessonIds: ["les_pre_a1_08_01_orthography_double_vowels"],
    reviewsUnitIds: ["unit_pre_a1_12_survival_greetings_farewells"],
    reviewReason: "Transition from literacy drills into real human communicative exchanges.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Authentic greeting exchanges recorded with varied social registers.",
    successCriteria: [
      "Produce the greeting and its conventional response with 100% appropriate phrasing.",
      "Accurately pronounce 'сайн' with smooth diphthong /sæ:ɲ/."
    ],
    masteryEvidence: [
      "Greets the instructor spontaneously upon initiating session.",
      "Responds 'Сайн, та сайн байна уу?' with natural intonation."
    ],
    recommendedExerciseModalities: ["role_play_response", "dialogue_completion", "matching"]
  },
  {
    lessonId: "les_pre_a1_13_02_informal_greetings_yu_baina",
    unitId: "unit_pre_a1_13_gratitude_apologies_politeness",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 2,
    title: "Informal Greetings Among Peers: Сайн уу?, Юу байна?, Тайван",
    lessonType: "dialogue_work",
    primaryPurpose: "Introduce casual greetings used among friends and youth, contrasting them with polite formal equivalents.",
    communicativeOutcome: "Greet friends casually ('Сайн уу?', 'Юу байна?') and respond ('Тайван', 'Юмгүй, тайван').",
    objectivesIntroduced: ["obj_pre_a1_13_02_use_informal_greetings"],
    objectivesPracticed: ["obj_pre_a1_13_01_use_basic_greeting"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_intonation_greetings"],
    phonologyReviewed: [],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: ["comm_a1_01_greetings_farewells"],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 1,
    lexicalDomains: ["lex_domain_social_interaction_courtesy"],
    previousVocabularyReused: [],
    readingObjective: "Read text message dialogues between young friends.",
    listeningObjective: "Distinguish between formal 'Сайн байна уу' and informal 'Сайн уу' in audio vignettes.",
    writingObjective: "Write a short 2-line messaging exchange between friends.",
    spokenProductionObjective: "Exchange casual greetings with a peer partner with relaxed conversational delivery.",
    registerTarget: "informal_peer",
    pragmaticTarget: "Interacting naturally with classmates and peers without sounding overly stiff.",
    prerequisiteLessonIds: ["les_pre_a1_13_01_universal_greeting_sain_baina_uu"],
    reviewsLessonIds: ["les_pre_a1_13_01_universal_greeting_sain_baina_uu"],
    reviewsUnitIds: [],
    reviewReason: "Establish clear register awareness in social greetings.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Authentic youth slang and casual conversational delivery.",
    successCriteria: [
      "Select the informal greeting in casual peer scenarios and formal in elder scenarios.",
      "Respond to 'Юу байна?' with 'Тайван' (Calm/Peaceful)."
    ],
    masteryEvidence: [
      "Uses 'Сайн уу' with classmates but 'Сайн байна уу' with teachers.",
      "Understands 'Тайван' as the standard reassuring reply to 'Юу байна?'."
    ],
    recommendedExerciseModalities: ["role_play_response", "dialogue_completion", "matching"]
  },
  {
    lessonId: "les_pre_a1_13_03_time_based_greetings",
    unitId: "unit_pre_a1_13_gratitude_apologies_politeness",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 3,
    title: "Time-of-Day Greetings: Өглөөний мэнд, Өдрийн мэнд, Оройн мэнд",
    lessonType: "vocabulary_introduction",
    primaryPurpose: "Introduce time-specific greetings incorporating the noun 'мэнд' (wellness/blessing) across morning, afternoon, and evening.",
    communicativeOutcome: "Greet others appropriately according to the time of day (Өглөөний мэнд 'Good morning', Өдрийн мэнд 'Good afternoon', Оройн мэнд 'Good evening').",
    objectivesIntroduced: ["obj_pre_a1_13_03_greet_by_time_of_day"],
    objectivesPracticed: ["obj_pre_a1_13_01_use_basic_greeting"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_intonation_greetings"],
    phonologyReviewed: [],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: ["comm_a1_01_greetings_farewells"],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 0,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_social_interaction_courtesy", "lex_domain_time_calendar_dates"],
    previousVocabularyReused: [],
    readingObjective: "Read business emails opening with 'Өглөөний мэнд' and TV broadcast introductions.",
    listeningObjective: "Identify the time of day from greeting cues in audio news clips.",
    writingObjective: "Write the 3 time-based greetings with correct genitive ending (-ний/-ийн).",
    spokenProductionObjective: "Deliver time-specific greetings with clear, polite social warmth.",
    registerTarget: "polite_formal",
    pragmaticTarget: "Opening formal business meetings and morning workplace conversations.",
    prerequisiteLessonIds: ["les_pre_a1_13_02_informal_greetings_yu_baina"],
    reviewsLessonIds: ["les_pre_a1_02_03_high_frequency_core_roots", "les_pre_a1_13_01_universal_greeting_sain_baina_uu"],
    reviewsUnitIds: ["unit_pre_a1_02_mongolian_distinct_letters"],
    reviewReason: "Integrate core temporal roots (өдөр, өглөө) with social pleasantries.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Authentic professional greetings in workplace settings.",
    successCriteria: [
      "Select 'Өглөөний мэнд' before noon and 'Оройн мэнд' after sunset.",
      "Accurately pronounce 'мэнд' with final palatalized /nd/."
    ],
    masteryEvidence: [
      "Begins morning communication with 'Өглөөний мэнд'.",
      "Recognizes 'Өдрийн мэнд' in lunchtime radio broadcasts."
    ],
    recommendedExerciseModalities: ["matching", "role_play_response", "dialogue_completion"]
  },
  {
    lessonId: "les_pre_a1_13_04_gratitude_apology_farewells",
    unitId: "unit_pre_a1_13_gratitude_apologies_politeness",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 4,
    title: "Essential Courtesy Formulas: Баярлалаа, Уучлаарай, Баяртай",
    lessonType: "dialogue_work",
    primaryPurpose: "Introduce formulas for expressing gratitude, offering apologies, requesting pardons, and parting.",
    communicativeOutcome: "Express sincere thanks ('Баярлалаа'), apologize or excuse oneself ('Уучлаарай'), and say goodbye ('Баяртай').",
    objectivesIntroduced: ["obj_pre_a1_13_04_express_gratitude_apology_farewell"],
    objectivesPracticed: [],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_vowel_long_pairs"],
    communicativeFunctionsIntroduced: ["comm_a1_02_thanks_polite_replies", "comm_a1_03_apologies_excuses"],
    communicativeFunctionsPracticed: ["comm_a1_01_greetings_farewells"],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 1,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_social_interaction_courtesy"],
    previousVocabularyReused: [],
    readingObjective: "Read customer service dialogues featuring gratitude and apology exchanges.",
    listeningObjective: "Recognize 'Уучлаарай' spoken on crowded buses when someone passes through.",
    writingObjective: "Write 'Баярлалаа' and 'Уучлаарай' correctly with long vowels (-лаа/-раа).",
    spokenProductionObjective: "Deploy 'Баярлалаа' when receiving an item, and 'Уучлаарай' when accidentally bumping someone.",
    registerTarget: "polite_formal",
    pragmaticTarget: "Maintaining polite social etiquette in public stores, transit, and social encounters.",
    prerequisiteLessonIds: ["les_pre_a1_13_03_time_based_greetings"],
    reviewsLessonIds: ["les_pre_a1_08_01_orthography_double_vowels"],
    reviewsUnitIds: ["unit_pre_a1_08_vowel_length_pairs"],
    reviewReason: "Apply long vowel orthography to the most critical social courtesy formulas.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Authentic interpersonal courtesy audio with realistic emotional inflection.",
    successCriteria: [
      "Select 'Баярлалаа' in 100% of gift or service reception scenarios.",
      "Deploy 'Уучлаарай' to get attention ('Excuse me') and apologize ('I am sorry')."
    ],
    masteryEvidence: [
      "Says 'Баяртай' naturally at the end of every conversation.",
      "Spells 'баярлалаа' with double 'аа' at the end."
    ],
    recommendedExerciseModalities: ["role_play_response", "dialogue_completion", "matching"]
  },
  {
    lessonId: "les_pre_a1_13_05_courtesy_formulas_synthesis",
    unitId: "unit_pre_a1_13_gratitude_apologies_politeness",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 5,
    title: "Social Etiquette & Greetings Integration Checkpoint",
    lessonType: "checkpoint",
    primaryPurpose: "Consolidate all social courtesy routines through multi-turn role-play simulations and listening comprehension.",
    communicativeOutcome: "Smoothly navigate a complete social interaction: greeting, inquiring about wellness, thanking, and bidding farewell.",
    objectivesIntroduced: [],
    objectivesPracticed: ["obj_pre_a1_13_01_use_basic_greeting", "obj_pre_a1_13_02_use_informal_greetings", "obj_pre_a1_13_03_greet_by_time_of_day", "obj_pre_a1_13_04_express_gratitude_apology_farewell"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_intonation_greetings"],
    phonologyReviewed: ["phono_cyr_35_alphabet"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: ["comm_a1_01_greetings_farewells", "comm_a1_02_thanks_polite_replies", "comm_a1_03_apologies_excuses"],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 1,
    newReceptiveLemmaTarget: 0,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_social_interaction_courtesy"],
    previousVocabularyReused: [],
    readingObjective: "Read and put in order a 4-turn scrambled dialogue between two acquaintances meeting on the street.",
    listeningObjective: "Follow a complete social greeting encounter and answer comprehension questions.",
    writingObjective: "Write a complete 4-turn greeting exchange from memory in Cyrillic.",
    spokenProductionObjective: "Participate in a fluid, unprompted greeting-to-farewell role-play simulation.",
    registerTarget: "polite_formal",
    pragmaticTarget: "Demonstrating full social readiness for real-world interactions in Mongolia.",
    prerequisiteLessonIds: ["les_pre_a1_13_04_gratitude_apology_farewells"],
    reviewsLessonIds: ["les_pre_a1_13_01_universal_greeting_sain_baina_uu", "les_pre_a1_13_02_informal_greetings_yu_baina", "les_pre_a1_13_03_time_based_greetings", "les_pre_a1_13_04_gratitude_apology_farewells"],
    reviewsUnitIds: ["unit_pre_a1_06_digits_and_classroom_prompts", "unit_pre_a1_07_personal_names_and_identification"],
    reviewReason: "Unit 13 synthesis uniting greetings, politeness, and social identity.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Multi-character conversational role-play audio recording.",
    successCriteria: [
      "Achieve 100% on dialogue sequencing and appropriate register matching.",
      "Execute full conversational exchange without reverting to English."
    ],
    masteryEvidence: [
      "Fluently handles: Greeting -> Response -> Thanks -> Farewell.",
      "Zero register confusion between casual friend and formal elder contexts."
    ],
    recommendedExerciseModalities: ["role_play_response", "dialogue_completion", "word_ordering"]
  },

  // =========================================================================
  // UNIT 14: Emergency Signs & Public Safety (unit_pre_a1_14_public_signs_and_notices)
  // Target: Prod=8, Rec=3, ProdExp=2, RecExp=1 | Lessons: 5
  // =========================================================================
  {
    lessonId: "les_pre_a1_14_01_prohibitions_and_warnings",
    unitId: "unit_pre_a1_14_public_signs_and_notices",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 1,
    title: "Decoding Prohibition & Warning Signs: Хориотой, Анхаар, Зогс",
    lessonType: "reading_development",
    primaryPurpose: "Decode high-stakes emergency and prohibition signage found in public transit, industrial zones, and buildings.",
    communicativeOutcome: "Recognize and obey urgent visual warning and prohibition signs (ХОРИОТОЙ 'Prohibited', АНХААР 'Caution/Attention', ЗОГС 'Stop').",
    objectivesIntroduced: ["obj_pre_a1_14_01_decode_danger_signs"],
    objectivesPracticed: [],
    objectivesReviewed: ["obj_pre_a1_12_04_read_polysyllabic_signs"],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_cyr_35_alphabet"],
    phonologyReviewed: ["phono_consonant_basic_inventory"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_emergency_safety_medical", "lex_domain_public_spaces_urban_navigation"],
    previousVocabularyReused: [],
    readingObjective: "Read warning placards featuring standard yellow/red pictograms paired with Cyrillic text.",
    listeningObjective: "Recognize spoken warnings ('Болгоомжтой!', 'Зогс!') in simulated emergency audio.",
    writingObjective: "Transcribe the warning terms 'АНХААР' and 'ЗОГС' accurately in block capitals.",
    spokenProductionObjective: "Read warning signs aloud with urgent, decisive intonation.",
    registerTarget: "formal_administrative",
    pragmaticTarget: "Avoiding hazardous situations and obeying civic safety mandates.",
    prerequisiteLessonIds: ["les_pre_a1_13_05_courtesy_formulas_synthesis"],
    reviewsLessonIds: ["les_pre_a1_01_04_read_public_cognate_signs", "les_pre_a1_04_04_decoding_street_signs_stems"],
    reviewsUnitIds: ["unit_pre_a1_04_consonants_inventory_stops", "unit_pre_a1_12_survival_greetings_farewells"],
    reviewReason: "Apply reading literacy to urgent public survival contexts.",
    audioSuitability: "standard_speech_synthesis_acceptable",
    audioPurpose: "Urgent vocalized warning announcements and alarms.",
    successCriteria: [
      "Instantly pair 5 warning words with their corresponding hazard icons.",
      "Never confuse 'ХОРИОТОЙ' (Forbidden) with an authorization notice."
    ],
    masteryEvidence: [
      "Stops moving immediately upon reading 'ЗОГС' or hearing 'Болгоомжтой!'.",
      "Identifies high-voltage and construction warnings instantly."
    ],
    recommendedExerciseModalities: ["matching", "reading_comprehension", "categorization"]
  },
  {
    lessonId: "les_pre_a1_14_02_emergency_exits_and_medical",
    unitId: "unit_pre_a1_14_public_signs_and_notices",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 2,
    title: "Navigating Safety Facilities: Гарц, Эмнэлэг, Түргэн тусламж",
    lessonType: "reading_development",
    primaryPurpose: "Decode signs designating safe egress, emergency medical stations, and pharmacy facilities.",
    communicativeOutcome: "Locate emergency exits ('Гарц', 'Аваарын гарц'), medical stations ('Эмнэлэг'), and ambulance services ('Түргэн тусламж').",
    objectivesIntroduced: ["obj_pre_a1_14_02_locate_safety_facilities"],
    objectivesPracticed: ["obj_pre_a1_14_01_decode_danger_signs"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_cyr_35_alphabet"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 1,
    lexicalDomains: ["lex_domain_emergency_safety_medical", "lex_domain_public_spaces_urban_navigation"],
    previousVocabularyReused: [],
    readingObjective: "Read building evacuation maps, green emergency exit signs, and hospital entrance placards.",
    listeningObjective: "Recognize facility names in emergency broadcast alerts.",
    writingObjective: "Transcribe 'ГАРЦ' and 'ЭМНЭЛЭГ' into an emergency response plan.",
    spokenProductionObjective: "Ask where the emergency exit is located using 'Гарц хаана байна?' with intelligible articulation.",
    registerTarget: "formal_administrative",
    pragmaticTarget: "Locating medical assistance and building egress during emergencies.",
    prerequisiteLessonIds: ["les_pre_a1_14_01_prohibitions_and_warnings"],
    reviewsLessonIds: ["les_pre_a1_12_04_reading_polysyllabic_city_signs"],
    reviewsUnitIds: [],
    reviewReason: "Reinforce public facility reading under emergency conditions.",
    audioSuitability: "standard_speech_synthesis_acceptable",
    audioPurpose: "Public address evacuation announcements.",
    successCriteria: [
      "Identify 'Аваарын гарц' (Emergency Exit) on floor plans with 100% accuracy.",
      "Distinguish 'Орц' (Entrance) from 'Гарц' (Exit) without hesitation."
    ],
    masteryEvidence: [
      "Heads towards the exit marked 'Гарц' immediately in simulation.",
      "Recognizes ambulance vehicles bearing 'Түргэн тусламж'."
    ],
    recommendedExerciseModalities: ["matching", "reading_comprehension", "cloze"]
  },
  {
    lessonId: "les_pre_a1_14_03_emergency_telephone_hotlines",
    unitId: "unit_pre_a1_14_public_signs_and_notices",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 3,
    title: "Mongolian Emergency Hotlines: 101, 102, 103, 105",
    lessonType: "vocabulary_introduction",
    primaryPurpose: "Memorize and comprehend the four national emergency phone numbers: Fire (101), Police (102), Ambulance (103), Rescue (105).",
    communicativeOutcome: "Dial and state the correct emergency service number corresponding to specific crisis situations.",
    objectivesIntroduced: ["obj_pre_a1_14_03_dial_emergency_hotlines"],
    objectivesPracticed: [],
    objectivesReviewed: ["obj_pre_a1_06_01_count_zero_to_five", "obj_pre_a1_06_02_count_six_to_ten"],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_consonant_basic_inventory"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: ["comm_a1_13_numbers_counting_1_to_100"],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 1,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_emergency_safety_medical", "lex_domain_numbers_quantities_measurement"],
    previousVocabularyReused: [],
    readingObjective: "Read emergency contact listings on public informational posters and hotel room safety cards.",
    listeningObjective: "Identify which emergency department is being called in operator audio prompts.",
    writingObjective: "Write the 3-digit emergency hotlines alongside their corresponding Mongolian agency names.",
    spokenProductionObjective: "State emergency numbers clearly over the telephone (нэг-тэг-хоёр, нэг-тэг-гурав).",
    registerTarget: "formal_administrative",
    pragmaticTarget: "Summoning police, fire, or ambulance services during urgent crises.",
    prerequisiteLessonIds: ["les_pre_a1_14_02_emergency_exits_and_medical"],
    reviewsLessonIds: ["les_pre_a1_06_01_counting_zero_to_five", "les_pre_a1_06_02_counting_six_to_ten"],
    reviewsUnitIds: ["unit_pre_a1_06_digits_and_classroom_prompts"],
    reviewReason: "Integrate digit mastery directly into lifesaving civic hotlines.",
    audioSuitability: "standard_speech_synthesis_acceptable",
    audioPurpose: "Simulated emergency dispatch operator audio greetings.",
    successCriteria: [
      "Select 102 for police, 103 for ambulance, and 101 for fire with 100% accuracy.",
      "Recite emergency numbers accurately in Mongolian digits."
    ],
    masteryEvidence: [
      "Instantly matches medical emergency scenario to 103.",
      "Correctly reads and dials numbers from emergency decals."
    ],
    recommendedExerciseModalities: ["matching", "role_play_response", "dictation"]
  },
  {
    lessonId: "les_pre_a1_14_04_shouting_for_help_survival",
    unitId: "unit_pre_a1_14_public_signs_and_notices",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 4,
    title: "Urgent Crisis Vocalizations: Туслаарай!, Гал!, Цагдаа дуудаарай!",
    lessonType: "dialogue_work",
    primaryPurpose: "Equip the learner with urgent spoken cries for help and requests to summon authorities in critical distress.",
    communicativeOutcome: "Shout for help ('Туслаарай!'), report fire ('Гал!'), and instruct someone to call police ('Цагдаа дуудаарай!').",
    objectivesIntroduced: ["obj_pre_a1_14_04_call_for_help"],
    objectivesPracticed: ["obj_pre_a1_14_03_dial_emergency_hotlines"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_vowel_long_pairs"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 0,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_emergency_safety_medical"],
    previousVocabularyReused: [],
    readingObjective: "Read urgent safety placards and dialogue captions in crisis comic strips.",
    listeningObjective: "Recognize cries for help in noisy crowd audio simulations.",
    writingObjective: "Transcribe 'Туслаарай!' and 'Цагдаа!' with correct exclamation punctuation.",
    spokenProductionObjective: "Vocalize 'Туслаарай!' with urgent volume, sharp attack, and sustained vowel length.",
    registerTarget: "informal_peer",
    pragmaticTarget: "Summoning bystander assistance during physical peril, theft, or medical distress.",
    prerequisiteLessonIds: ["les_pre_a1_14_03_emergency_telephone_hotlines"],
    reviewsLessonIds: ["les_pre_a1_03_04_reading_monosyllables_disyllables", "les_pre_a1_08_01_orthography_double_vowels"],
    reviewsUnitIds: ["unit_pre_a1_03_cardinal_short_vowels"],
    reviewReason: "Transform passive vocabulary (гал, цагдаа) into active emergency imperatives.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Realistic emergency voice acting demonstrating urgent distress calls.",
    successCriteria: [
      "Accurately pronounce 'Туслаарай!' with double 'аа' without hesitation.",
      "Deploy 'Цагдаа дуудаарай!' when witnessing a crime in simulation."
    ],
    masteryEvidence: [
      "Utters 'Туслаарай' spontaneously when distressed in virtual simulation.",
      "Clear, non-hesitant vocal projection."
    ],
    recommendedExerciseModalities: ["role_play_response", "dialogue_completion", "matching"]
  },
  {
    lessonId: "les_pre_a1_14_05_safety_and_emergency_checkpoint",
    unitId: "unit_pre_a1_14_public_signs_and_notices",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 5,
    title: "Public Safety & Emergency Response Synthesis",
    lessonType: "checkpoint",
    primaryPurpose: "Assess integrated comprehension of danger signs, facility navigation, hotline knowledge, and emergency vocalization.",
    communicativeOutcome: "Respond appropriately to written hazard warnings and execute simulated emergency survival procedures.",
    objectivesIntroduced: [],
    objectivesPracticed: ["obj_pre_a1_14_01_decode_danger_signs", "obj_pre_a1_14_02_locate_safety_facilities", "obj_pre_a1_14_03_dial_emergency_hotlines", "obj_pre_a1_14_04_call_for_help"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_cyr_35_alphabet"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 1,
    newReceptiveLemmaTarget: 0,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_emergency_safety_medical", "lex_domain_public_spaces_urban_navigation"],
    previousVocabularyReused: [],
    readingObjective: "Read an integrated building safety layout and identify 4 hazard signs and 2 emergency exit paths.",
    listeningObjective: "Listen to an emergency broadcast and identify the nature of the hazard and designated shelter.",
    writingObjective: "Complete an emergency contact reference sheet accurately in Cyrillic.",
    spokenProductionObjective: "State emergency situation and needed service clearly in simulated phone call.",
    registerTarget: "formal_administrative",
    pragmaticTarget: "Ensuring personal safety and survival autonomy in Mongolia.",
    prerequisiteLessonIds: ["les_pre_a1_14_04_shouting_for_help_survival"],
    reviewsLessonIds: ["les_pre_a1_14_01_prohibitions_and_warnings", "les_pre_a1_14_02_emergency_exits_and_medical", "les_pre_a1_14_03_emergency_telephone_hotlines", "les_pre_a1_14_04_shouting_for_help_survival"],
    reviewsUnitIds: ["unit_pre_a1_04_consonants_inventory_stops", "unit_pre_a1_06_digits_and_classroom_prompts"],
    reviewReason: "Unit 14 comprehensive safety assessment prior to the final Pre-A1 capstone.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Diagnostic emergency scenario audio recording.",
    successCriteria: [
      "Achieve 100% on safety sign recognition and hotline matching.",
      "Execute correct verbal response in crisis simulation test."
    ],
    masteryEvidence: [
      "Never steps into areas marked 'Хориотой'.",
      "Dials 103 and shouts 'Туслаарай!' when presented with an injured person scenario."
    ],
    recommendedExerciseModalities: ["matching", "role_play_response", "reading_comprehension"]
  },

  // =========================================================================
  // UNIT 15: Environmental Literacy Capstone & Pre-A1 Benchmark (unit_pre_a1_15_pre_a1_synthesis_and_literacy_capstone)
  // Target: Prod=8, Rec=3, ProdExp=2, RecExp=1 | Lessons: 6
  // =========================================================================
  {
    lessonId: "les_pre_a1_15_01_comprehensive_alphabet_audit",
    unitId: "unit_pre_a1_15_pre_a1_synthesis_and_literacy_capstone",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 1,
    title: "The Complete 35-Letter Alphabet: Comprehensive Audit & Speed Run",
    lessonType: "orthography",
    primaryPurpose: "Verify automated, effortless recognition and naming of all 35 letters of the Mongolian Cyrillic alphabet.",
    communicativeOutcome: "Identify, name, and transcribe every uppercase and lowercase Cyrillic character without hesitation.",
    objectivesIntroduced: ["obj_pre_a1_15_01_audit_alphabet_mastery"],
    objectivesPracticed: [],
    objectivesReviewed: ["obj_pre_a1_01_01_identify_shared_glyphs", "obj_pre_a1_02_01_identify_distinctive_graphemes", "obj_pre_a1_04_01_identify_obstruent_glyphs", "obj_pre_a1_11_01_identify_iotated_vowels"],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_cyr_35_alphabet"],
    phonologyReviewed: ["phono_mongolian_specific_letters", "phono_consonant_basic_inventory"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_general_education_literacy"],
    previousVocabularyReused: [],
    readingObjective: "Read randomized alphabet sequences with an average recognition latency under 400 milliseconds per letter.",
    listeningObjective: "Transcribe any spoken letter name into its corresponding written glyph instantly.",
    writingObjective: "Write the complete 35-letter Cyrillic alphabet in alphabetical order from memory.",
    spokenProductionObjective: "Recite the Mongolian alphabet sequence aloud from А to Я.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Demonstrating complete orthographic baseline fluency.",
    prerequisiteLessonIds: ["les_pre_a1_14_05_safety_and_emergency_checkpoint"],
    reviewsLessonIds: ["les_pre_a1_01_01_shared_consonants_visual", "les_pre_a1_02_01_grapheme_recognition_o_u", "les_pre_a1_04_01_plosives_affricates_inventory", "les_pre_a1_11_01_iotated_vowels_inventory"],
    reviewsUnitIds: ["unit_pre_a1_01_alphabet_consonants_intro", "unit_pre_a1_02_mongolian_distinct_letters", "unit_pre_a1_04_consonants_inventory_stops", "unit_pre_a1_11_iotated_vowels_signs"],
    reviewReason: "Comprehensive diagnostic verification of the 35-letter Cyrillic alphabet inventory.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Authentic native recitation of the official Cyrillic alphabet song/sequence.",
    successCriteria: [
      "Achieve 100% accuracy on a 35-letter randomized identification test.",
      "Accurately match all uppercase glyphs with their lowercase pairs."
    ],
    masteryEvidence: [
      "Zero hesitation on Ө, Ү, Щ, Ъ, Ь, Ю, Я.",
      "Writes the complete alphabet in correct alphabetical order."
    ],
    recommendedExerciseModalities: ["matching", "typing", "dictation"]
  },
  {
    lessonId: "les_pre_a1_15_02_urban_signage_simulation_walkthrough",
    unitId: "unit_pre_a1_15_pre_a1_synthesis_and_literacy_capstone",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 2,
    title: "Virtual Walking Tour of Ulaanbaatar: Reading Commercial Signage",
    lessonType: "reading_development",
    primaryPurpose: "Simulate a walking tour along Peace Avenue (Энхтайваны өргөн чөлөө), decoding authentic street-level signage.",
    communicativeOutcome: "Read and identify commercial establishments (супермаркет, номын дэлгүүр, цайны газар, үсчин, эмийн сан).",
    objectivesIntroduced: ["obj_pre_a1_15_02_read_urban_landscape"],
    objectivesPracticed: ["obj_pre_a1_15_01_audit_alphabet_mastery"],
    objectivesReviewed: ["obj_pre_a1_01_04_read_public_cognate_signs", "obj_pre_a1_04_04_read_street_signs", "obj_pre_a1_12_04_read_polysyllabic_signs"],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_cyr_35_alphabet"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 1,
    lexicalDomains: ["lex_domain_public_spaces_urban_navigation", "lex_domain_shopping_commerce_retail"],
    previousVocabularyReused: [],
    readingObjective: "Read 10 photographic storefront signs captured in urban Mongolia and state the service provided.",
    listeningObjective: "Match spoken destination directions to photographs of commercial facades.",
    writingObjective: "Create a handwritten shopping route map containing 4 designated store names in Cyrillic.",
    spokenProductionObjective: "Read business names aloud with proper vowel harmony and initial stress.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Navigating Mongolian urban commercial centers independently.",
    prerequisiteLessonIds: ["les_pre_a1_15_01_comprehensive_alphabet_audit"],
    reviewsLessonIds: ["les_pre_a1_04_04_decoding_street_signs_stems", "les_pre_a1_12_04_reading_polysyllabic_city_signs"],
    reviewsUnitIds: ["unit_pre_a1_04_consonants_inventory_stops", "unit_pre_a1_12_survival_greetings_farewells"],
    reviewReason: "Synthesize urban reading skills across all Pre-A1 vocabulary domains.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Authentic ambient street audio paired with sign descriptions.",
    successCriteria: [
      "Correctly classify 8 storefront photos by service type.",
      "Accurately read multi-word business titles (жишээ: 'Монгол Ном')."
    ],
    masteryEvidence: [
      "Identifies 'Үсчин' as barber/hairdresser and 'Эмийн сан' as pharmacy.",
      "Locates dining options by reading 'Цайны газар' signs."
    ],
    recommendedExerciseModalities: ["matching", "reading_comprehension", "short_answer_writing"]
  },
  {
    lessonId: "les_pre_a1_15_03_transit_and_receipts_decoding",
    unitId: "unit_pre_a1_15_pre_a1_synthesis_and_literacy_capstone",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 3,
    title: "Decoding Authentic Ephemera: Bus Cards, Receipts & Price Tags",
    lessonType: "reading_development",
    primaryPurpose: "Decode authentic printed ephemera: U-Money transit receipts, supermarket cash register receipts (НӨАТ), and price stickers.",
    communicativeOutcome: "Extract total cost, date, item names, and transaction numbers from authentic Mongolian receipts and tickets.",
    objectivesIntroduced: ["obj_pre_a1_15_03_decode_ephemera"],
    objectivesPracticed: ["obj_pre_a1_15_02_read_urban_landscape"],
    objectivesReviewed: ["obj_pre_a1_06_01_count_zero_to_five", "obj_pre_a1_06_02_count_six_to_ten"],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_consonant_basic_inventory"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: ["comm_a1_13_numbers_counting_1_to_100"],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 1,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_shopping_commerce_retail", "lex_domain_numbers_quantities_measurement"],
    previousVocabularyReused: [],
    readingObjective: "Locate and extract the Total (Дүн), VAT (НӨАТ), Date (Огноо), and Change (Хариулт) on a cash register receipt.",
    listeningObjective: null,
    writingObjective: "Write the purchase amount in digits and verbal Mongolian currency terms (төгрөг).",
    spokenProductionObjective: null,
    registerTarget: "formal_administrative",
    pragmaticTarget: "Verifying retail purchases and checking transportation balances.",
    prerequisiteLessonIds: ["les_pre_a1_15_02_urban_signage_simulation_walkthrough"],
    reviewsLessonIds: ["les_pre_a1_06_02_counting_six_to_ten"],
    reviewsUnitIds: ["unit_pre_a1_06_digits_and_classroom_prompts"],
    reviewReason: "Integrate numerical decoding with authentic printed transactional documents.",
    audioSuitability: "standard_speech_synthesis_acceptable",
    audioPurpose: "Cashier voice prompts reading totals at the register.",
    successCriteria: [
      "Find total price on 3 different supermarket receipts with 100% accuracy.",
      "Identify whether a receipt includes lottery/tax refund QR codes."
    ],
    masteryEvidence: [
      "Identifies 'Нийт дүн' as total price immediately.",
      "Reads date and time of transaction accurately."
    ],
    recommendedExerciseModalities: ["reading_comprehension", "matching", "cloze"]
  },
  {
    lessonId: "les_pre_a1_15_04_digital_messaging_and_profile_setup",
    unitId: "unit_pre_a1_15_pre_a1_synthesis_and_literacy_capstone",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 4,
    title: "Digital Communication & Social Profile Setup in Cyrillic",
    lessonType: "writing",
    primaryPurpose: "Set up a complete digital user profile and compose a 3-turn introductory chat message in Mongolian Cyrillic.",
    communicativeOutcome: "Complete an online profile bio (name, nationality, occupation) and type greeting messages via smartphone interface.",
    objectivesIntroduced: ["obj_pre_a1_15_04_compose_digital_profile"],
    objectivesPracticed: ["obj_pre_a1_15_01_audit_alphabet_mastery"],
    objectivesReviewed: ["obj_pre_a1_05_03_type_digital_queries", "obj_pre_a1_07_04_fill_hotel_form"],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_cyr_35_alphabet"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: ["comm_a1_06_self_introduction_name", "comm_a1_01_greetings_farewells"],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 1,
    newReceptiveLemmaTarget: 0,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_technology_digital_communication", "lex_domain_personal_information_identity"],
    previousVocabularyReused: [],
    readingObjective: "Read user profiles of language exchange partners in Cyrillic.",
    listeningObjective: null,
    writingObjective: "Type a short 25-word introductory text message introducing oneself and greeting a partner.",
    spokenProductionObjective: null,
    registerTarget: "informal_peer",
    pragmaticTarget: "Initiating digital language exchanges and mobile chat correspondence.",
    prerequisiteLessonIds: ["les_pre_a1_15_03_transit_and_receipts_decoding"],
    reviewsLessonIds: ["les_pre_a1_05_03_digital_search_input", "les_pre_a1_07_04_filling_hotel_registration_form"],
    reviewsUnitIds: ["unit_pre_a1_05_cyrillic_keyboard_mastery", "unit_pre_a1_07_personal_names_and_identification"],
    reviewReason: "Unite digital keyboard typing with personal introduction formulas.",
    audioSuitability: "standard_speech_synthesis_acceptable",
    audioPurpose: "Incoming message audio chime paired with text-to-speech message playback.",
    successCriteria: [
      "Type a 20-word introductory profile without spelling errors in under 2 minutes.",
      "Input both Ө and Ү correctly using standard Mongolian keyboard layout."
    ],
    masteryEvidence: [
      "Types: 'Сайн байна уу? Намайг ... гэдэг. Би оюутан.' accurately.",
      "Uses Cyrillic keyboard smoothly without reverting to Latin transliteration."
    ],
    recommendedExerciseModalities: ["typing", "short_answer_writing", "cloze"]
  },
  {
    lessonId: "les_pre_a1_15_05_pre_a1_integrated_benchmark_exam",
    unitId: "unit_pre_a1_15_pre_a1_synthesis_and_literacy_capstone",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 5,
    title: "Pre-A1 Integrated Environmental Literacy Benchmark Exam",
    lessonType: "checkpoint",
    primaryPurpose: "Execute the formal Pre-A1 exit assessment covering reading decoding, phonemic listening, and typing accuracy.",
    communicativeOutcome: "Demonstrate verified Pre-A1 environmental literacy competence across all 15 foundational literacy domains.",
    objectivesIntroduced: [],
    objectivesPracticed: ["obj_pre_a1_15_01_audit_alphabet_mastery", "obj_pre_a1_15_02_read_urban_landscape", "obj_pre_a1_15_03_decode_ephemera", "obj_pre_a1_15_04_compose_digital_profile"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_cyr_35_alphabet", "phono_vowel_harmony_masc_fem", "phono_vowel_long_pairs"],
    phonologyReviewed: ["phono_consonant_basic_inventory", "phono_syllable_templates"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: ["comm_a1_01_greetings_farewells", "comm_a1_06_self_introduction_name"],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 1,
    newReceptiveLemmaTarget: 0,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_general_education_literacy"],
    previousVocabularyReused: [],
    readingObjective: "Achieve at least 85% on a 25-item authentic environmental print reading comprehension assessment.",
    listeningObjective: "Score at least 85% on a 15-item phonetic discrimination and dictation exam.",
    writingObjective: "Score at least 90% on a 20-word standardized Cyrillic spelling and typing battery.",
    spokenProductionObjective: "Read aloud a 35-word authentic text passage with verified phonemic clarity and correct stress.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Qualifying formally for advancement into A1 sentence construction.",
    prerequisiteLessonIds: ["les_pre_a1_15_04_digital_messaging_and_profile_setup"],
    reviewsLessonIds: ["les_pre_a1_15_01_comprehensive_alphabet_audit", "les_pre_a1_15_02_urban_signage_simulation_walkthrough", "les_pre_a1_15_03_transit_and_receipts_decoding", "les_pre_a1_15_04_digital_messaging_and_profile_setup"],
    reviewsUnitIds: ["unit_pre_a1_01_alphabet_consonants_intro", "unit_pre_a1_08_vowel_length_pairs", "unit_pre_a1_10_masculine_feminine_harmony", "unit_pre_a1_12_survival_greetings_farewells"],
    reviewReason: "Authoritative Phase 1C Pre-A1 benchmark qualification exam.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Standardized institutional exam audio recordings.",
    successCriteria: [
      "Overall composite score of 85% or higher across all 4 literacy quadrants.",
      "Zero critical failures on vowel harmony or emergency sign recognition."
    ],
    masteryEvidence: [
      "Passes all reading, listening, writing, and oral pronunciation rubric criteria.",
      "Demonstrates total readiness to begin A1 Section 1 grammar."
    ],
    recommendedExerciseModalities: ["dictation", "reading_comprehension", "typing"]
  },
  {
    lessonId: "les_pre_a1_15_06_pre_a1_celebration_and_bridge_to_a1",
    unitId: "unit_pre_a1_15_pre_a1_synthesis_and_literacy_capstone",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 6,
    title: "Pre-A1 Graduation & The Bridge to Sentence Construction",
    lessonType: "dialogue_work",
    primaryPurpose: "Consolidate literacy achievements, celebrate script mastery, and preview the transition into nominal sentences in A1 Unit 16.",
    communicativeOutcome: "Confidently recite one's achievements in Mongolian literacy and state personal learning goals for CEFR A1.",
    objectivesIntroduced: [],
    objectivesPracticed: ["obj_pre_a1_15_01_audit_alphabet_mastery"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_cyr_35_alphabet"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: ["comm_a1_01_greetings_farewells", "comm_a1_06_self_introduction_name"],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 1,
    newReceptiveLemmaTarget: 0,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_general_education_literacy"],
    previousVocabularyReused: [],
    readingObjective: "Read the Pre-A1 Certificate of Literacy Achievement in Mongolian Cyrillic.",
    listeningObjective: "Understand congratulations from Mongolian instructors in audio celebration clip.",
    writingObjective: "Sign Certificate of Achievement with full personal name in beautiful Cyrillic cursive or print.",
    spokenProductionObjective: "Say 'Баярлалаа! Би монгол хэл сурч байна' (Thank you! I am learning Mongolian).",
    registerTarget: "polite_formal",
    pragmaticTarget: "Reflecting on learning accomplishments and building motivation for A1.",
    prerequisiteLessonIds: ["les_pre_a1_15_05_pre_a1_integrated_benchmark_exam"],
    reviewsLessonIds: ["les_pre_a1_15_05_pre_a1_integrated_benchmark_exam"],
    reviewsUnitIds: ["unit_pre_a1_13_gratitude_apologies_politeness"],
    reviewReason: "Grand capstone transition bridging Pre-A1 literacy into A1 sentence construction.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Warm congratulatory audio messages from native speakers.",
    successCriteria: [
      "Recite graduation pledge fluently in Mongolian.",
      "Express excitement and readiness for A1 Section 1 grammar."
    ],
    masteryEvidence: [
      "Produces complete authentic spoken sentence 'Би монголоор уншиж чадна' (I can read in Mongolian).",
      "Seamlessly bridges into A1 Unit 16 nominal sentences."
    ],
    recommendedExerciseModalities: ["role_play_response", "reading_comprehension", "short_answer_writing"]
  }
];
