import { CommunicativeFunctionSpec } from './dataCommunicative_A1';

export const communicativeA2Data: CommunicativeFunctionSpec[] = [
  {
    functionId: "comm_a2_01_describing_extended_family",
    title: "Describe Extended Family and Kinship Networks",
    mongolianTitle: "Ураг төрөл, хамаатан саднаа танилцуулах",
    level: "A2",
    domain: "Informational",
    prerequisites: ["comm_a1_15_family_nuclear_members"],
    communicativeGoal: "Introduce uncles, aunts, cousins, and in-laws, and explain maternal vs paternal lineages.",
    typicalScenarios: ["Family gathering", "Sharing photo albums with Mongolian friends"],
    keyStructures: ["Энэ манай нагац ах", "Аавын талын авга эгч", "Хадам аав, ээж", "Би олон үеэлтэй"],
    expectedOutcome: "Learner distinguishes paternal (авга) from maternal (нагац) relations accurately."
  },
  {
    functionId: "comm_a2_02_describing_appearance_clothing",
    title: "Describe Physical Appearance, Height, and Attire",
    mongolianTitle: "Гадаад төрх, өндөр нам, өмссөн хувцсыг тодорхойлох",
    level: "A2",
    domain: "Informational",
    prerequisites: ["comm_a1_10_identifying_objects", "comm_a1_22_shopping_clothing_sizes"],
    communicativeGoal: "Describe a person's hair, height, build, and current clothes using descriptive adjectives.",
    typicalScenarios: ["Meeting someone at an airport", "Describing a lost friend in a mall"],
    keyStructures: ["Өндөр нуруутай, хар үстэй", "Цэнхэр цамцтай, шилтэй", "Тэр ямар харагддаг вэ?", "Дунд зэргийн нуруутай"],
    expectedOutcome: "Learner uses attributive adjective stacking and comitative case (-тай) to specify appearance."
  },
  {
    functionId: "comm_a2_03_describing_personality_character",
    title: "Describe Personal Character Traits and Temperament",
    mongolianTitle: "Хүний зан ааш, зан чанарыг тодорхойлох",
    level: "A2",
    domain: "Interpersonal",
    prerequisites: ["comm_a2_02_describing_appearance_clothing"],
    communicativeGoal: "Talk about whether someone is kind, hard-working, calm, funny, or strict.",
    typicalScenarios: ["Talking about a new boss or teacher", "Discussing prospective roommates"],
    keyStructures: ["Тэр их тусархаг хүн", "Зан сайтай, эелдэг", "Маш шаргуу ажилладаг", "Шооч, хөгжилтэй зантай"],
    expectedOutcome: "Learner attributes moral and behavioral traits using idiomatic compound descriptors."
  },
  {
    functionId: "comm_a2_04_renting_apartment_housing",
    title: "Inquire About Renting an Apartment and Housing Conditions",
    mongolianTitle: "Орон сууц хөлслөх, байрны нөхцөл лавлах",
    level: "A2",
    domain: "Transactional",
    prerequisites: ["comm_a1_20_asking_bill_payment"],
    communicativeGoal: "Inquire about rent per month, heating, utility fees, furnishing, and lease terms.",
    typicalScenarios: ["Calling a landlord from an online listing", "Inspecting an apartment in Ulaanbaatar"],
    keyStructures: ["Сарын түрээс хэд вэ?", "Халаалт сайн уу?", "Тавилгатай юу?", "Хэддүгээр давхарт вэ?", "Гэрээ хэдэн сараар хийх вэ?"],
    expectedOutcome: "Learner clarifies residential conditions, heating reliability, and deposit terms."
  },
  {
    functionId: "comm_a2_05_describing_home_rooms_furniture",
    title: "Describe Rooms, Interior Layout, and Ger Organization",
    mongolianTitle: "Гэр сууц, өрөөний зохион байгуулалт, тавилгыг дүрслэх",
    level: "A2",
    domain: "Informational",
    prerequisites: ["comm_a1_12_location_simple_objects"],
    communicativeGoal: "Describe furniture arrangement in an apartment or traditional spatial zones inside a ger.",
    typicalScenarios: ["Giving a room tour", "Explaining sacred/male/female sides of a yurt to a visitor"],
    keyStructures: ["Хойморт бурханы ширээ байна", "Баруун талд эрэгтэй хүний эд зүйлс", "Гал тогооны өрөө зүүн талд"],
    expectedOutcome: "Learner explains traditional steppe layout principles (хоймор, баруун, зүүн) accurately."
  },
  {
    functionId: "comm_a2_06_weekend_activities_past",
    title: "Recount Past Weekend and Evening Activities",
    mongolianTitle: "Өнгөрсөн амралтын өдрүүдийн сонин сайхныг ярих",
    level: "A2",
    domain: "Narrative",
    prerequisites: ["comm_a1_25_days_of_the_week"],
    communicativeGoal: "Narrate events that happened over the weekend using past tense and converbs.",
    typicalScenarios: ["Monday morning chat with coworkers", "Catching up with a friend over coffee"],
    keyStructures: ["Амралтын өдрүүдээр юу хийсэн бэ?", "Би хөдөө явж амарсан", "Найзуудтайгаа хоол идээд кино үзсэн"],
    expectedOutcome: "Learner chains chronological actions using past forms (-сан, -лаа) and coordinating converb (-аад)."
  },
  {
    functionId: "comm_a2_07_childhood_hometown_memories",
    title: "Share Memories of Childhood and Growing Up",
    mongolianTitle: "Хүүхэд насны дурсамж, төрсөн нутгийн тухай хуваалцах",
    level: "A2",
    domain: "Narrative",
    prerequisites: ["comm_a2_06_weekend_activities_past"],
    communicativeGoal: "Describe where one spent childhood, games played, and childhood routines.",
    typicalScenarios: ["Intimate evening conversation around a stove", "Language partner storytelling"],
    keyStructures: ["Би багадаа хөдөө өссөн", "Бид өдөржин гадаа тоглодог байсан", "Манай нутаг их сайхан байгальтай"],
    expectedOutcome: "Learner employs the habitual past construction (-даг байсан) to recount nostalgic routines."
  },
  {
    functionId: "comm_a2_08_vacation_travel_experiences",
    title: "Narrate Vacation Travel and Countryside Journeys",
    mongolianTitle: "Аялал жуулчлал, амралтын дурсамжаа ярих",
    level: "A2",
    domain: "Narrative",
    prerequisites: ["comm_a2_06_weekend_activities_past"],
    communicativeGoal: "Describe a trip to Lake Khövsgöl, Terelj, or the Gobi, highlighting sights and weather.",
    typicalScenarios: ["Returning from summer vacation", "Sharing travel tips with fellow students"],
    keyStructures: ["Би Хөвсгөл нуур луу явсан", "Байгаль нь үнэхээр үзэсгэлэнтэй байсан", "Бид майханд хоноглосон"],
    expectedOutcome: "Learner describes travel routes, lodging, and landscape impressions using past participles."
  },
  {
    functionId: "comm_a2_09_making_accepting_invitations",
    title: "Extend and Enthusiastically Accept Invitations",
    mongolianTitle: "Урилга тавих, урилгыг баяртайгаар хүлээн авах",
    level: "A2",
    domain: "Interpersonal",
    prerequisites: ["comm_a1_01_formulaic_greetings"],
    communicativeGoal: "Invite someone to dinner, a concert, or home visit, and respond with enthusiastic consent.",
    typicalScenarios: ["Inviting a friend to a cafe", "Inviting a teacher to an end-of-term meal"],
    keyStructures: ["Манайд зочлоорой", "Хамт хоол идэх үү?", "Тэгье, тэгье, дуртайяа очъё", "Тэгвэл сайхан байна"],
    expectedOutcome: "Learner uses polite imperative (-аарай) and volitional (-я) forms to manage invitations."
  },
  {
    functionId: "comm_a2_10_declining_invitations_excuses",
    title: "Politely Decline Invitations and Offer Plausible Reasons",
    mongolianTitle: "Урилгаас эелдгээр татгалзах, шалтгаан тайлбарлах",
    level: "A2",
    domain: "Interpersonal",
    prerequisites: ["comm_a2_09_making_accepting_invitations"],
    communicativeGoal: "Turn down an invitation without causing loss of face by offering respectful justification.",
    typicalScenarios: ["Declining an evening event due to an exam", "Unable to attend a family party"],
    keyStructures: ["Уучлаарай, би тэр өдөр завгүй", "Маргааш шалгалттай тул явж чадахгүй нь", "Дараа заавал хамт явъя"],
    expectedOutcome: "Learner uses mitigating expressions and causal particles (тул, учраас) to cushion refusal."
  },
  {
    functionId: "comm_a2_11_scheduling_rescheduling_meetings",
    title: "Schedule, Confirm, and Reschedule Appointments",
    mongolianTitle: "Уулзалт товлох, цаг өөрчлөх, тохиролцох",
    level: "A2",
    domain: "Transactional",
    prerequisites: ["comm_a1_24_asking_clock_time", "comm_a1_25_days_of_the_week"],
    communicativeGoal: "Agree upon meeting time and place, and telephone ahead to postpone when delayed.",
    typicalScenarios: ["Arranging study group time", "Rescheduling a dentist visit"],
    keyStructures: ["Хэдэн цагт уулзах вэ?", "Хоёр цагт тохирох уу?", "Би бага зэрэг хоцрох нь, уулзалтыг хойшлуулах уу?"],
    expectedOutcome: "Learner negotiates mutual availability and adjusts schedule proactively."
  },
  {
    functionId: "comm_a2_12_medical_symptoms_doctor",
    title: "Report Illness Symptoms and Body Pain to a Doctor",
    mongolianTitle: "Эмчид зовуурь, биеийн өвчнөө тайлбарлах",
    level: "A2",
    domain: "Transactional",
    prerequisites: ["comm_a1_05_apologies_pardon"],
    communicativeGoal: "Describe fever, stomachache, sore throat, or cough, and state how long symptoms lasted.",
    typicalScenarios: ["Visiting a polyclinic", "Calling an emergency consultation line"],
    keyStructures: ["Миний толгой өвдөж байна", "Ходоод өвдөөд байна", "Халуурч байна", "Хоёр хоногийн өмнөөс эхэлсэн"],
    expectedOutcome: "Learner identifies body parts and conveys symptom duration and intensity to medical staff."
  },
  {
    functionId: "comm_a2_13_buying_medicine_pharmacy",
    title: "Purchase Over-the-Counter Medicine at a Pharmacy",
    mongolianTitle: "Эмийн сангаас эм авах, хэрэглэх заавар лавлах",
    level: "A2",
    domain: "Transactional",
    prerequisites: ["comm_a2_12_medical_symptoms_doctor"],
    communicativeGoal: "Ask for headache or cold medication, and understand dosage instructions (before/after meals).",
    typicalScenarios: ["Neighborhood pharmacy", "Buying bandages and pain relief"],
    keyStructures: ["Ханиадны эм байна уу?", "Өдөрт хэдэн удаа уух вэ?", "Хоолны өмнө үү, хойно уу?", "Нэг шахмалаар ууна"],
    expectedOutcome: "Learner asks for remedies and accurately interprets temporal medication rules."
  },
  {
    functionId: "comm_a2_14_countryside_ger_visiting_etiquette",
    title: "Observe Steppe Ger Hospitality and Guest Customs",
    mongolianTitle: "Хөдөө айлд зочлох, гэрийн ёс заншил дагах",
    level: "A2",
    domain: "Interpersonal",
    prerequisites: ["comm_a1_02_formal_elder_greetings", "comm_a2_05_describing_home_rooms_furniture"],
    communicativeGoal: "Call to tie up dogs, step over the threshold, accept snuff bottle, and receive tea with two hands.",
    typicalScenarios: ["Arriving at a nomad family's camp", "Visiting a rural herder household"],
    keyStructures: ["Нохойгоо хориорой!", "Тарган сайхан зусаж байна уу?", "Та сайхан намаржиж байна уу?", "Аягатай цайг хоёр гардаж авах"],
    expectedOutcome: "Learner executes critical nomadic guest etiquette smoothly without violating taboos."
  },
  {
    functionId: "comm_a2_15_nomadic_livestock_five_animals",
    title: "Discuss Herding and the Five Types of Livestock (Таван хошуу мал)",
    mongolianTitle: "Таван хошуу мал, мал аж ахуйн тухай ярих",
    level: "A2",
    domain: "Informational",
    prerequisites: ["comm_a2_14_countryside_ger_visiting_etiquette"],
    communicativeGoal: "Identify horses, sheep, goats, cattle, and camels, and discuss milking and seasonal pasture.",
    typicalScenarios: ["Talking with herders on the steppe", "Visiting an animal corral"],
    keyStructures: ["Танайх хэдэн толгой малтай вэ?", "Адуу, үхэр, тэмээ, хонь, ямаа", "Гүү саах", "Бэлчээрт гарах"],
    expectedOutcome: "Learner uses appropriate animal terms and counting classifiers for livestock (толгой мал)."
  },
  {
    functionId: "comm_a2_16_seasonal_weather_forecast",
    title: "Interpret Weather Forecasts and Steppe Wind Warnings",
    mongolianTitle: "Цаг агаарын урьдчилсан мэдээ, салхи шуургыг ойлгох",
    level: "A2",
    domain: "Informational",
    prerequisites: ["comm_a1_31_weather_seasons_basic"],
    communicativeGoal: "Understand TV/radio forecasts regarding dust storms, blizzards, freezing temperatures, and rainfall.",
    typicalScenarios: ["Listening to national news before a road trip", "Checking phone forecast app"],
    keyStructures: ["Маргааш цасан шуурга шуурна", "Шөнөдөө хасах хорин градус", "Хүчтэй салхитай байна"],
    expectedOutcome: "Learner interprets temperature scales and weather hazard warnings accurately."
  },
  {
    functionId: "comm_a2_17_giving_multistep_directions",
    title: "Provide Multi-Step Route Directions with Landmarks",
    mongolianTitle: "Олон шатлалт замын чиг зааж тайлбарлах",
    level: "A2",
    domain: "Transactional",
    prerequisites: ["comm_a1_28_asking_directions_street"],
    communicativeGoal: "Guide an interlocutor past specific buildings, traffic lights, and crosswalks to a goal.",
    typicalScenarios: ["Directing a lost tourist in Ulaanbaatar", "Giving directions to one's home"],
    keyStructures: ["Шулуун яваад гэрлэн дохиогоор зүүн эргэ", "Их сургуулийн хажуугаар өнгөрөөд", "Замын эсрэг талд байна"],
    expectedOutcome: "Learner uses sequential converbs (-аад) and spatial postpositions to convey complex routes."
  },
  {
    functionId: "comm_a2_18_buying_bus_train_tickets",
    title: "Book Provincial Intercity Bus or Train Tickets",
    mongolianTitle: "Хот хоорондын автобус, галт тэрэгний тасалбар авах",
    level: "A2",
    domain: "Transactional",
    prerequisites: ["comm_a1_24_asking_clock_time", "comm_a1_20_asking_bill_payment"],
    communicativeGoal: "Purchase a ticket to a rural aimag center, specify travel date, berth type, and baggage.",
    typicalScenarios: ["Dragon (Драгон) bus terminal", "Ulaanbaatar Central Railway Station"],
    keyStructures: ["Дархан луу явах тасалбар авъя", "Хэдэн цагт хөдлөх вэ?", "Унтлагын суудал байна уу?", "Буцах тасалбар захиалах"],
    expectedOutcome: "Learner reserves regional travel tickets confirming departure time, seat tier, and return date."
  },
  {
    functionId: "comm_a2_19_postal_and_parcel_services",
    title: "Send Letters and Registered Parcels at Post Office",
    mongolianTitle: "Шуудангаар илгээмж явуулах, хаяг бичих",
    level: "A2",
    domain: "Transactional",
    prerequisites: ["comm_a1_20_asking_bill_payment"],
    communicativeGoal: "Weigh a box, write a delivery address in Mongolian order, and calculate shipping fees.",
    typicalScenarios: ["Central Post Office (Төв шуудан)", "Sending souvenirs to family abroad"],
    keyStructures: ["Энэ илгээмжийг явуулъя", "Хэд хоногт хүрэх вэ?", "Жин нь хэдэн килограмм байна?", "Хаягаа энд бичнэ үү"],
    expectedOutcome: "Learner formats postal addresses correctly (Country -> Aimag/City -> Sum/District -> Street)."
  },
  {
    functionId: "comm_a2_20_banking_atm_currency_exchange",
    title: "Execute Currency Exchange and ATM Withdrawals",
    mongolianTitle: "Валют арилжаа хийх, АТМ-аас мөнгө авах",
    level: "A2",
    domain: "Transactional",
    prerequisites: ["comm_a1_13_numbers_counting_1_to_100", "comm_a1_20_asking_bill_payment"],
    communicativeGoal: "Exchange foreign currency for Tugriks at an exchange office and manage ATM prompts.",
    typicalScenarios: ["Bank teller window", "Currency exchange kiosk along Peace Avenue"],
    keyStructures: ["Доллар солиулах гэсэн юм", "Өнөөдрийн ханш хэд вэ?", "Данснаасаа мөнгө авъя", "Пин кодоо хийнэ үү"],
    expectedOutcome: "Learner checks exchange rates and completes cash withdrawal or conversion without confusion."
  },
  {
    functionId: "comm_a2_21_expressing_obligation_rules",
    title: "Express Mandatory Rules and Personal Obligations",
    mongolianTitle: "Хийх ёстой үүрэг, дүрмийг илэрхийлэх",
    level: "A2",
    domain: "Informational",
    prerequisites: ["comm_a1_34_classroom_instructions"],
    communicativeGoal: "State what students, citizens, or employees must do (-х ёстой) or need to do (-х хэрэгтэй).",
    typicalScenarios: ["Explaining house rules to a roommate", "Discussing study requirements"],
    keyStructures: ["Чи хичээлдээ цагтаа ирэх ёстой", "Би өнөөдөр даалгавраа дуусгах хэрэгтэй", "Гутал тайлах ёстой юу?"],
    expectedOutcome: "Learner uses deontic modals to communicate moral duty and pragmatic necessity clearly."
  },
  {
    functionId: "comm_a2_22_requesting_granting_permission",
    title: "Request, Grant, and Politely Deny Permission",
    mongolianTitle: "Зөвшөөрөл хүсэх ба олгох, хориглох",
    level: "A2",
    domain: "Interpersonal",
    prerequisites: ["comm_a2_21_expressing_obligation_rules"],
    communicativeGoal: "Ask whether an action is permitted (-ж болох уу?) and respond with consent or prohibition.",
    typicalScenarios: ["Asking to take photos in a museum", "Asking to open the window in an office"],
    keyStructures: ["Энд зураг авч болох уу?", "Тэг, болно", "Үгүй, энд тамхи татаж болохгүй", "Цонх нээж болох уу?"],
    expectedOutcome: "Learner uses -ж болно / -ж болохгүй to navigate public regulations courteously."
  },
  {
    functionId: "comm_a2_23_comparing_items_places",
    title: "Compare Dimensions, Qualities, and Prices",
    mongolianTitle: "Эд зүйлс, газруудын чанар, үнийг харьцуулах",
    level: "A2",
    domain: "Informational",
    prerequisites: ["comm_a1_22_shopping_clothing_sizes"],
    communicativeGoal: "Compare two items using ablative constructions (-аас илүү / дутуу) for price, size, or speed.",
    typicalScenarios: ["Comparing two phone models in a store", "Choosing between travel routes"],
    keyStructures: ["Энэ нь тэрнээсээ илүү үнэтэй", "Өнөөдөр өчигдрөөс дулаахан байна", "Автобус таксинаас удаан"],
    expectedOutcome: "Learner forms comparative sentences using noun + ablative (-аас) without English-style copulas."
  },
  {
    functionId: "comm_a2_24_superlative_best_in_town",
    title: "Identify Superlatives and Recommend Top Choices",
    mongolianTitle: "Хамгийн шилдэг, дээд зэргийн зүйлсийг санал болгох",
    level: "A2",
    domain: "Informational",
    prerequisites: ["comm_a2_23_comparing_items_places"],
    communicativeGoal: "Identify the biggest, oldest, or best places and recommend them to peers.",
    typicalScenarios: ["Recommending a good restaurant", "Discussing the tallest building or coldest month"],
    keyStructures: ["Энэ бол хотын хамгийн амттай хоолтой газар", "Хамгийн хүйтэн сар бол нэгдүгээр сар", "Хамгийн өндөр уул"],
    expectedOutcome: "Learner uses хамгийн and superlative reduplication to rank items effectively."
  },
  {
    functionId: "comm_a2_25_reporting_third_party_speech",
    title: "Report What Someone Said or Inquired (Гэж хэлэх)",
    mongolianTitle: "Хөндлөнгийн хүний үгийг дамжуулж ярих",
    level: "A2",
    domain: "Narrative",
    prerequisites: ["comm_a1_06_self_introduction_name"],
    communicativeGoal: "Relay messages from third parties to an interlocutor using the quotative particle гэж.",
    typicalScenarios: ["Passing a phone message to a roommate", "Reporting a teacher's reminder to classmates"],
    keyStructures: ["Багш 'маргааш шалгалттай' гэж хэлсэн", "Тэр намайг ир гэж дуудсан", "Чи юу гэж бодож байна?"],
    expectedOutcome: "Learner quotes direct and indirect statements accurately using sentence-final гэж хэлэв."
  },
  {
    functionId: "comm_a2_26_simple_recipe_cooking_steps",
    title: "Explain Step-by-Step Food Recipes and Preparation",
    mongolianTitle: "Хоол хийх энгийн заавар, дарааллыг тайлбарлах",
    level: "A2",
    domain: "Informational",
    prerequisites: ["comm_a1_17_ordering_basic_food"],
    communicativeGoal: "Describe how to chop meat, knead dough, wrap buuz, and boil milk tea step by step.",
    typicalScenarios: ["Cooking dinner together with friends", "Sharing a traditional recipe"],
    keyStructures: ["Эхлээд гурилаа зуурна", "Дараа нь махаа жижиглэж татна", "Сонгино, давсаар амтлаад чимхэнэ"],
    expectedOutcome: "Learner explains kitchen procedures using ordinal sequence connectives (эхлээд, дараа нь)."
  },
  {
    functionId: "comm_a2_27_expressing_future_intentions",
    title: "Express Future Personal Plans and Intentions",
    mongolianTitle: "Ирээдүйн төлөвлөгөө, зорилгоо илэрхийлэх",
    level: "A2",
    domain: "Interpersonal",
    prerequisites: ["comm_a1_26_dates_months_calendar"],
    communicativeGoal: "Share what one intends to do next month or after graduation using volitional and intention forms.",
    typicalScenarios: ["Discussing career aspirations with a mentor", "New Year resolution discussions"],
    keyStructures: ["Би ирэх жил их сургуульд орно", "Монгол хэл сайн сурах бодолтой байна", "Хөдөө ажиллахаар төлөвлөж байгаа"],
    expectedOutcome: "Learner discusses plans using prospective participle (-х) with nouns like бодолтой or төлөвлөгөөтэй."
  },
  {
    functionId: "comm_a2_28_describing_lost_items",
    title: "Report Lost Property to Security or Information Desk",
    mongolianTitle: "Гээсэн эд зүйлсээ эрэн сурвалжлах, бүртгүүлэх",
    level: "A2",
    domain: "Transactional",
    prerequisites: ["comm_a2_02_describing_appearance_clothing", "comm_a1_11_ownership_possession"],
    communicativeGoal: "Describe a missing wallet, backpack, or phone, where it was lost, and leave contact info.",
    typicalScenarios: ["Airport lost-and-found", "University security office"],
    keyStructures: ["Би түрийвчээ гээчихлээ", "Хар өнгөтэй, арьсан түрийвч байсан", "Автобусанд мартсан бололтой", "Олбол залгаарай"],
    expectedOutcome: "Learner provides identifying physical attributes and circumstantial timeline for lost items."
  },
  {
    functionId: "comm_a2_29_phone_conversations_leaving_messages",
    title: "Conduct Telephone Calls and Leave Messages",
    mongolianTitle: "Утсаар ярих, зурвас үлдээх",
    level: "A2",
    domain: "Interpersonal",
    prerequisites: ["comm_a1_14_phone_numbers_contact"],
    communicativeGoal: "Answer the phone, identify oneself, ask to speak to someone, and leave a return message.",
    typicalScenarios: ["Calling an office receptionist", "Phoning a friend's home landline"],
    keyStructures: ["Байна уу? Бат байна уу?", "Би найз нь байна", "Тэр одоогоор алга", "Намайг залгасан гэж хэлээрэй"],
    expectedOutcome: "Learner uses Mongolian telephone conventions (Байна уу?) and leaves structured voice messages."
  },
  {
    functionId: "comm_a2_30_congratulations_milestones",
    title: "Offer Congratulations on Birthdays and Seasonal Milestones",
    mongolianTitle: "Баяр хүргэх, төрсөн өдөр ба тэмдэглэлт өдрийн ерөөл хэлэх",
    level: "A2",
    domain: "Interpersonal",
    prerequisites: ["comm_a1_04_expressing_gratitude", "comm_a1_26_dates_months_calendar"],
    communicativeGoal: "Congratulate friends on birthdays, graduations, weddings, or the New Year with standard blessings.",
    typicalScenarios: ["Signing a greeting card", "Proposing a brief toast at a dinner party"],
    keyStructures: ["Төрсөн өдрийн баярын мэнд хүргэе!", "Шинэ жилийн мэнд хүргэе!", "Сурлагын өндөр амжилт хүсье!", "Аз жаргал хүсье!"],
    expectedOutcome: "Learner selects appropriate formulaic wishes for personal and calendar celebrations."
  }
];
