import { GrammarConceptSpec } from './dataGrammar_A1';

export const grammarC1C2Data: GrammarConceptSpec[] = [
  // ==========================================
  // LEVEL C1 CONCEPTS (20 CONCEPTS)
  // ==========================================
  {
    conceptId: "gram_c1_honorific_lexical_verbs",
    englishTitle: "Honorific System: Lexical Respectful Verbs (Айлдах, Морилох, Зооглох, Таалагдах)",
    mongolianTitle: "Хүндэтгэлийн үйл үгс: Айлдах, морилох, зооглох, таалагдах",
    category: "Register & Sociolinguistics",
    firstTargetLevel: "C1",
    masteryTargetLevel: "C1",
    prerequisites: ["gram_b2_discourse_connectors_rhetorical"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_c1_honorific_suppletive_existentials", "gram_c1_honorific_nouns_and_somatic_terms"],
    modality: "productive",
    vowelHarmonyRequired: true,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["Honorific verbs can NEVER be applied to oneself; they are exclusively reserved for honoring elders, esteemed guests, dignitaries, or spiritual figures."],
    description: "The core lexical honorific system replacing common verbs with specialized high-respect terms: хэлэх -> айлдах (to say), явах/ирэх -> морилох (to come/go), идэх/уух -> зооглох (to eat/drink), унтах -> нойрсох (to sleep), харах -> болгоох (to look/consider), өгөх -> өргөх / барих (to give/present).",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Respectful Verbs for Elders and Honored Guests (айлдах, морилох, зооглох)",
    linguisticAnalysis: "Suppletive lexical honorification encoding sociolinguistic deference and asymmetrical age/status hierarchy.",
    learnerExplanation: "When speaking to or about elders, guests, or dignitaries, never use basic everyday verbs like 'eat' or 'say'. Use respectful honorific verbs instead.",
    technicalNotes: "A cardinal rule of Mongolian sociolinguistics: using honorific verbs for one's own actions is considered a major breach of modesty."
  },
  {
    conceptId: "gram_c1_honorific_suppletive_existentials",
    englishTitle: "Honorific Existentials and Verbs of Dwelling (Заларч байна, Саатан морилох)",
    mongolianTitle: "Хүндэтгэлийн орших, суух үйл үгс: Заларч байна, саатан морилох",
    category: "Register & Sociolinguistics",
    firstTargetLevel: "C1",
    masteryTargetLevel: "C1",
    prerequisites: ["gram_c1_honorific_lexical_verbs"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_c1_honorific_nouns_and_somatic_terms"],
    modality: "productive",
    vowelHarmonyRequired: true,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["Replacing everyday суух or байх with dignified honorific predicates."],
    description: "Expressing the presence, residence, or travel of honored persons: заларч байна (is present / gracing us with their presence), морилон саатах (to dwell / pay a gracious visit), нойрсох (to repose/sleep).",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Honored Presence: Describing Where Honored Guests Stay (заларч байна)",
    linguisticAnalysis: "Honorific copular and locative periphrases encoding extreme spatial and institutional deference.",
    learnerExplanation: "Use заларч байна instead of basic байна when announcing the arrival or presence of an esteemed teacher or guest.",
    technicalNotes: "Widely used in formal university ceremonies, conferences, and ceremonial hospitality."
  },
  {
    conceptId: "gram_c1_honorific_nouns_and_somatic_terms",
    englishTitle: "Honorific Nouns and Somatic Respect Terminology (Мутар, Мэлмий, Айлдвар, Таалал)",
    mongolianTitle: "Хүндэтгэлийн нэр үг ба эрхтний нэрс: Мутар, мэлмий, айлдвар, таалал",
    category: "Register & Sociolinguistics",
    firstTargetLevel: "C1",
    masteryTargetLevel: "C1",
    prerequisites: ["gram_c1_honorific_lexical_verbs"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_c1_honorific_humble_forms_object_elevation"],
    modality: "productive",
    vowelHarmonyRequired: false,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["Replaces body parts and personal possessions of elders with elevated cultural vocabulary."],
    description: "Replacing everyday nouns with elevated respectful counterparts: гар (hand) -> мутар, нүд (eye) -> мэлмий, үг (word) -> айлдвар, гэр/байр -> өргөө/өргөө цацах, сэтгэл (mind/heart) -> таалал, нас (age) -> сүүдэр.",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Elevated Nouns: Sacred Words for Hands, Eyes & Words (мутар, мэлмий, айлдвар)",
    linguisticAnalysis: "Lexical noun substitution within the honorific register replacing anatomical and personal possession terms.",
    learnerExplanation: "Refer to an elder's words as айлдвар, an elder's hand as мутар, and an elder's home as өргөө to convey traditional Mongolian courtesy.",
    technicalNotes: "Influenced historically by Classical Mongolian court language and Buddhist liturgical translations."
  },
  {
    conceptId: "gram_c1_honorific_humble_forms_object_elevation",
    englishTitle: "Humble Self-Referencing and Object-Honorific Elevation (Айлтгах, Бараалхах, Өргөн барих)",
    mongolianTitle: "Өөрийгөө даруулах ба бусдыг эрхэмлэх найруулга: Айлтгах, бараалхах, өргөн барих",
    category: "Register & Sociolinguistics",
    firstTargetLevel: "C1",
    masteryTargetLevel: "C1",
    prerequisites: ["gram_c1_honorific_nouns_and_somatic_terms"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_c1_honorific_imperative_gtun_no_uu"],
    modality: "productive",
    vowelHarmonyRequired: true,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["Used when the speaker performs an action directed TOWARD a person of higher status."],
    description: "Verbs where the speaker humbles their own action to honor the recipient: айлтгах (to humbly report / report up to a senior), бараалхах (to be granted an audience with / pay respects to), өргөн барих (to respectfully present a gift or document).",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Humble Actions: Speaking Up to Seniors (айлтгах, бараалхах, өргөн барих)",
    linguisticAnalysis: "Allocentric humble verbs (object honorification) lowering the grammatical subject while exalting the dative/accusative referent.",
    learnerExplanation: "Use айлтгах instead of хэлэх when presenting an official report or speaking humbly to an esteemed senior.",
    technicalNotes: "Mirror image of subject honorification; essential for formal diplomacy and state etiquette."
  },
  {
    conceptId: "gram_c1_honorific_imperative_gtun_no_uu",
    englishTitle: "Honorific and Prescriptive Imperatives (-гтун/-гтүн, -но уу/-нэ үү)",
    mongolianTitle: "Хүндэтгэлийн ба албан тушаалын захирах хэлбэр (-гтун/-гтүн, -но уу)",
    category: "Register & Sociolinguistics",
    firstTargetLevel: "C1",
    masteryTargetLevel: "C1",
    prerequisites: ["gram_c1_honorific_humble_forms_object_elevation"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_c1_administrative_chancellery_syntax"],
    modality: "productive",
    vowelHarmonyRequired: true,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["-гтун is high literary/formal; -но уу is standard diplomatic/chancellery polite request."],
    description: "Formal and ceremonial imperative forms: -гтун/-гтүн for solemn directives to a collective or venerated audience (Сонсогтун! 'Listen ye!'), and -но уу/-нэ үү for formal administrative and diplomatic requests (Анхааралдаа авна уу 'Please take note of this').",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Formal & Dignified Requests (-гтун, -но уу)",
    linguisticAnalysis: "Honorific prescriptive imperatives and formal interrogative cohortative modal inflections.",
    learnerExplanation: "Use -но уу when writing polite official business emails, and recognize -гтун in solemn public declarations.",
    technicalNotes: "-но уу derives from indicative -на/-нэ + question particle уу/үү used performatively as a high-politeness request."
  },
  {
    conceptId: "gram_c1_administrative_chancellery_syntax",
    englishTitle: "Official Administrative and Chancellery Syntax (Тогтоох нь, Дурдсанчлан, Захирамжлах нь)",
    mongolianTitle: "Төрийн албан бичгийн найруулга, тогтоол захирамжийн хэл",
    category: "Register & Sociolinguistics",
    firstTargetLevel: "C1",
    masteryTargetLevel: "C1",
    prerequisites: ["gram_c1_honorific_imperative_gtun_no_uu"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_c1_archaic_jussive_sugai_tugai", "gram_c1_classical_converbs_vaas_khuits"],
    modality: "productive",
    vowelHarmonyRequired: true,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["Adhering to strict state standards for decree preambles, enactment clauses, and operative directives."],
    description: "The formulaic grammar of Mongolian government acts, decrees, and corporate bylaws: opening with participial topicalizers (Тогтоох нь 'Be it resolved that...'), referencing previous articles (заасанчлан 'as stipulated', дурдсанчлан 'as mentioned'), and establishing legal mandates.",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Government Decrees & Legal Directives: Formal Chancellery Syntax",
    linguisticAnalysis: "Standardized bureaucratic syntactic templates utilizing deverbal nominal topicalizers in -х нь followed by legal stipulations.",
    learnerExplanation: "This is the precise formulaic language used in Mongolian government resolutions, ministerial orders, and corporate directives.",
    technicalNotes: "Governed by the State Standard for Official Document Formulation (MNS 5140)."
  },
  {
    conceptId: "gram_c1_archaic_jussive_sugai_tugai",
    englishTitle: "Formal Legislative Enactments Closing with Jussive (-сугай/-сүгэй, -тугай/-түгэй)",
    mongolianTitle: "Төрийн шийдвэр, захирамжийн төгсгөл дэх соёрхон тушаах хэлбэр (-сугай, -тугай)",
    category: "Register & Sociolinguistics",
    firstTargetLevel: "C1",
    masteryTargetLevel: "C1",
    prerequisites: ["gram_c1_administrative_chancellery_syntax"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_c1_classical_converbs_vaas_khuits"],
    modality: "productive",
    vowelHarmonyRequired: true,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["-сугай marks authoritative decree closing by executive authority ('Be it resolved!'); -тугай marks solemn wish ('May it be!')."],
    description: "The formulaic operative verb endings that legally seal ministerial decrees and state orders: Үүрэг болгосугай 'Be it ordered that...', Хүчингүйд тооцсугай 'Be it deemed null and void', Мандан бадартугай! 'May it flourish!'.",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "The Law Decrees: Sovereign Enactments (-сугай, -тугай)",
    linguisticAnalysis: "Classical Mongolian jussive and precative inflectional suffixes preserved in modern Cyrillic legislative acts and state mottoes.",
    learnerExplanation: "Every official decree issued by a Mongolian minister, governor, or president ends its action clauses with -сугай.",
    technicalNotes: "Preserves the historical Classical Mongolian voluntative/jussive morphology into modern administrative law."
  },
  {
    conceptId: "gram_c1_classical_converbs_vaas_khuits",
    englishTitle: "Classical Converbs in Formal Discourse: -ваас/-вээс and -хуйц/-хүйц",
    mongolianTitle: "Уламжлалт найруулгын холбох нөхцөл (-ваас/-вээс, -хуйц/-хүйц)",
    category: "Converbs",
    firstTargetLevel: "C1",
    masteryTargetLevel: "C1",
    prerequisites: ["gram_c1_administrative_chancellery_syntax"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_c1_classical_temporal_khlaar", "gram_c1_classical_quotative_khemeen"],
    modality: "both",
    vowelHarmonyRequired: true,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["-ваас represents an archaic high-register variant of standard conditional -вал; -хуйц denotes capacity or sufficiency."],
    description: "Preserved classical converbs utilized in elevated formal, literary, and ceremonial oratory: -ваас/-вээс ('if it be that...', e.g. Үзвээс 'If one considers...'), and -хуйц/-хүйц ('to an extent sufficient to...', e.g. Бахархуйц амжилт 'an achievement worthy of pride').",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Elevated Connectors: Worthy of & If It Be That (-хуйц, -ваас)",
    linguisticAnalysis: "Archaic conditional converb (-ваас) and adequative converb (-хуйц) functioning as stylistic registers in high discourse.",
    learnerExplanation: "Use -хуйц to mean 'worthy of' or 'sufficient to' (e.g. 'an accomplishment worthy of pride' = 'бахархуйц амжилт').",
    technicalNotes: "-хуйц historically combines classical participle -хуй with caritive/adequative suffix."
  },
  {
    conceptId: "gram_c1_classical_temporal_khlaar",
    englishTitle: "Formal Successive Converb: -хлаар/-хлээр/-хлоор/-хлөөр",
    mongolianTitle: "Уламжлалт цаг заах холбох нөхцөл (-хлаар/-хлээр)",
    category: "Converbs",
    firstTargetLevel: "C1",
    masteryTargetLevel: "C1",
    prerequisites: ["gram_c1_classical_converbs_vaas_khuits"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_c1_classical_quotative_khemeen"],
    modality: "both",
    vowelHarmonyRequired: true,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["Expresses both temporal succession ('whenever/as soon as') and causal inference ('given that')."],
    description: "Formal converb denoting inevitable temporal sequence or logical transition: Нар гарахаар дулаардаг (when sun rises, it warms), Түүнийг сонсохлоор бахархах сэтгэл төрдөг (Upon hearing that, feelings of pride arise).",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Whenever & Upon Doing: Formal Successive Converb (-хлаар)",
    linguisticAnalysis: "Analytical temporal converb composed of future verbal noun -х plus instrumental-ablative succession marker -лаар.",
    learnerExplanation: "Use -хлаар in reflective essays to describe what inevitably happens whenever a condition is met.",
    technicalNotes: "Shows fourfold vowel harmony: -хлаар/-хлээр/-хлоор/-хлөөр."
  },
  {
    conceptId: "gram_c1_classical_quotative_khemeen",
    englishTitle: "Classical Quotative and Connective Particles: Хэмээн, Хэмээх, Гэгч",
    mongolianTitle: "Уламжлалт хэлний эшлэх, нэрлэх холбоос: Хэмээн, хэмээх, гэгч",
    category: "Discourse Grammar",
    firstTargetLevel: "C1",
    masteryTargetLevel: "C1",
    prerequisites: ["gram_c1_classical_converbs_vaas_khuits"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_c1_classical_participle_khui"],
    modality: "both",
    vowelHarmonyRequired: true,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["Archaic converbial forms of verb хэмээх 'to say' used in formal literature, legal acts, and philosophical prose."],
    description: "Formal, literary equivalents of everyday гэж: хэмээн ('saying so / declaring that...'), хэмээх ('so-called / which is termed...'), and гэгч ('the one who is called / known as...').",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Classical Quotatives: Formally Quoting and Naming (хэмээн, хэмээх)",
    linguisticAnalysis: "Literary quotative converbial and participial forms of defective verb хэмээх 'to speak/designate'.",
    learnerExplanation: "In high formal literature and academic books, хэмээн is used where everyday speech uses гэж.",
    technicalNotes: "Direct descendant of Classical Mongolian kemen."
  },
  {
    conceptId: "gram_c1_classical_participle_khui",
    englishTitle: "Classical Participle in -хуй/-хүй and Philosophical Nominalization",
    mongolianTitle: "Эртний нэрийн үйл үг -хуй/-хүй ба гүн ухааны нэршил",
    category: "Participles",
    firstTargetLevel: "C1",
    masteryTargetLevel: "C1",
    prerequisites: ["gram_c1_classical_quotative_khemeen"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_c1_academic_nominalization_frames"],
    modality: "receptive",
    vowelHarmonyRequired: true,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["Appears frequently in high intellectual literature, Buddhist translations, and philosophical titles (e.g. Оршихуй ба Эс оршихуй)."],
    description: "The classical Mongolian participial nominalizer -хуй/-хүй used in philosophical terminology to denote abstract states of being, essence, and ontology (оршихуй 'existence/being', сэтгэхүй 'thinking/cognition', баригдахуй 'tangibility').",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Philosophical Essence: The -хуй Suffix (оршихуй 'being', сэтгэхүй 'thought')",
    linguisticAnalysis: "Archaic verbal noun nominalizer forming ontological and cognitive abstract terminology.",
    learnerExplanation: "This suffix turns verbs into deep philosophical concepts, like turning 'to exist' (орших) into 'Existence / Being' (оршихуй).",
    technicalNotes: "Standard modern philosophical and psychological register formative in Cyrillic Mongolian."
  },
  {
    conceptId: "gram_c1_academic_nominalization_frames",
    englishTitle: "Academic Register: Complex Propositional Frames and Multi-Layered Nominalization",
    mongolianTitle: "Шинжлэх ухааны найруулгын нийлмэл бүтэц, нэршсэн хэллэг",
    category: "Register & Sociolinguistics",
    firstTargetLevel: "C1",
    masteryTargetLevel: "C1",
    prerequisites: ["gram_c1_classical_participle_khui"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_c1_academic_hedging_and_epistemic_stance"],
    modality: "productive",
    vowelHarmonyRequired: false,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["Managing dense, left-branching nominalizations without losing syntactic coherence across long paragraphs."],
    description: "Constructing rigorous academic discourse in Mongolian using multi-layered nominalizations, abstract conceptual nouns (үзэл баримтлал, арга зүй, зүй тогтол), and impersonal passive citations (ажиглагдаж байна, авч үзвэл, судалгаагаар нотлогдсон).",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Writing Academic Papers: Dense Conceptual Framing",
    linguisticAnalysis: "Heavy left-branching prenominal clausal subordination and deverbal abstract nominal packing in scholarly monographs.",
    learnerExplanation: "Learn to construct multi-clause academic sentences that summarize research findings clearly without relying on conversational pronouns.",
    technicalNotes: "Hallmark of peer-reviewed articles published by the Mongolian Academy of Sciences."
  },
  {
    conceptId: "gram_c1_academic_hedging_and_epistemic_stance",
    englishTitle: "Academic Hedging and Epistemic Modesty (Ажиглагдаж байна, Үндэслэлтэй, Талтай)",
    mongolianTitle: "Эрдэм шинжилгээний найруулгын таамаглал, болгоомжлол",
    category: "Register & Sociolinguistics",
    firstTargetLevel: "C1",
    masteryTargetLevel: "C1",
    prerequisites: ["gram_c1_academic_nominalization_frames"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_c1_journalistic_evidential_distancing"],
    modality: "productive",
    vowelHarmonyRequired: false,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["Avoiding dogmatic over-assertion in scientific and doctoral literature."],
    description: "Techniques for scholarly hedging and nuanced claim modulation: ...гэж үзэх үндэслэлтэй 'there are reasonable grounds to consider that...', ...гэсэн хандлага ажиглагдаж байна 'a tendency toward ... is observed', ...тал ажиглагддаг 'aspects of ... are noted'.",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Scholarly Hedging: Expressing Measured Claims (үндэслэлтэй, ажиглагдаж байна)",
    linguisticAnalysis: "Epistemic hedging strategies depersonalizing scientific agency via passive verbs and modal nominal predicates.",
    learnerExplanation: "Instead of saying 'I proved this', educated academic Mongolian says 'the evidence suggests that...' using impersonal passive frames.",
    technicalNotes: "Standard convention in Mongolian doctoral theses and scientific peer critique."
  },
  {
    conceptId: "gram_c1_journalistic_evidential_distancing",
    englishTitle: "Journalistic Evidential Distancing in Investigative Reporting",
    mongolianTitle: "Сэтгүүл зүйн мэдээллийн эх сурвалж, зай барих найруулга",
    category: "Register & Sociolinguistics",
    firstTargetLevel: "C1",
    masteryTargetLevel: "C1",
    prerequisites: ["gram_c1_academic_hedging_and_epistemic_stance"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_c1_legal_statutory_framing"],
    modality: "productive",
    vowelHarmonyRequired: false,
    morphologyRequired: false,
    recursInAdvanced: true,
    knownComplications: ["Maintaining journalistic neutrality to protect legal compliance and avoid libel."],
    description: "Constructing objective investigative broadcast and print copy: Эх сурвалжийн мэдээлснээр 'According to sources', ...гэх мэдээлэл цацагдаж байна 'Reports are circulating that...', ...гэдгийг албаныхан батлаагүй байна 'Authorities have not confirmed that...'.",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Journalistic Neutrality: Citing Unconfirmed Reports and Sources",
    linguisticAnalysis: "Evidential citation framing attributing propositional content to third-party sources to maintain investigative detachment.",
    learnerExplanation: "Use these phrases when reporting breaking news or investigative findings while maintaining professional objectivity.",
    technicalNotes: "Essential for modern journalists working in Mongolian media organizations."
  },
  {
    conceptId: "gram_c1_legal_statutory_framing",
    englishTitle: "Legal and Statutory Framing: Conditionality in Law (-сан тохиолдолд, -х нөхцөлд)",
    mongolianTitle: "Хууль эрх зүйн нөхцөлт найруулга (-сан тохиолдолд, заасны дагуу)",
    category: "Register & Sociolinguistics",
    firstTargetLevel: "C1",
    masteryTargetLevel: "C1",
    prerequisites: ["gram_c1_journalistic_evidential_distancing"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_c1_rhetorical_inversion_and_clefting"],
    modality: "productive",
    vowelHarmonyRequired: false,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["Legal conditions require precise nominal case frames rather than informal converbs."],
    description: "Drafting and interpreting statutory conditions and contractual clauses: ...зөрчсөн тохиолдолд 'in the event of violating...', ...заасны дагуу 'pursuant to / in accordance with...', ...хүчин төгөлдөр болох 'entering into legal force'.",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Statutory Law & Contracts: In the Event of (-сан тохиолдолд, заасны дагуу)",
    linguisticAnalysis: "Legal conditional frame using locative-marked abstract nouns of circumstance (тохиолдолд, нөхцөлд) governing past participles.",
    learnerExplanation: "Use -сан тохиолдолд for 'in case of' or 'in the event that' when writing business contracts or reading legislation.",
    technicalNotes: "The universal conditional frame in modern statutory legislation of the State Great Khural."
  },
  {
    conceptId: "gram_c1_rhetorical_inversion_and_clefting",
    englishTitle: "Rhetorical Inversion and Syntactic Clefting for Dramatic Emphasis",
    mongolianTitle: "Найруулгын уран байрлал солилцоо ба онцлох бүтэц",
    category: "Discourse Grammar",
    firstTargetLevel: "C1",
    masteryTargetLevel: "C1",
    prerequisites: ["gram_c1_legal_statutory_framing"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_c1_complex_appositive_titles_and_epithets"],
    modality: "productive",
    vowelHarmonyRequired: false,
    morphologyRequired: false,
    recursInAdvanced: true,
    knownComplications: ["Inversion departs from strict SOV order and is used exclusively for heightened oratorical impact."],
    description: "Deliberate dislocation of sentence constituents to create suspense, solemn focus, or oratorical cadence in speeches and essays: moving the predicate forward or topicalizing post-verbal complements (e.g. Ирлээ, бидний хүсэн хүлээсэн цаг мөч! 'It has arrived—the moment we so longed for!').",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Dramatic Word Order: Moving Words for Oratorical Power",
    linguisticAnalysis: "Marked post-verbal right-dislocation and predicate fronting for high-register rhetorical focus.",
    learnerExplanation: "In high oratorical speeches, speakers deliberately move the verb to the front to create a powerful, poetic rhythm.",
    technicalNotes: "While Mongolian is strictly SOV in neutral syntax, high oratory licenses pragmatic inversion."
  },
  {
    conceptId: "gram_c1_complex_appositive_titles_and_epithets",
    englishTitle: "Complex Multi-Tier Appositive Titles and Diplomatic Protocol Formulas",
    mongolianTitle: "Төрийн дээд цол, өргөмжлөл, дипломат ёслолын нэр томьёо",
    category: "Register & Sociolinguistics",
    firstTargetLevel: "C1",
    masteryTargetLevel: "C1",
    prerequisites: ["gram_c1_rhetorical_inversion_and_clefting"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_c1_adversative_concessive_connectors_formal"],
    modality: "productive",
    vowelHarmonyRequired: false,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["Long appositive chains precede the personal name; only the final noun takes case inflection."],
    description: "Navigating elaborate chains of state honorifics, academic titles, and diplomatic protocol designations: Монгол Улсын Их Хурлын гишүүн, Төрийн шагналт, Шинжлэх ухааны доктор, профессор [Нэр] 'Member of Parliament, State Laureate, Doctor of Science, Professor [Name]'.",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Diplomatic Titles & State Honors: Structuring Long Official Titles",
    linguisticAnalysis: "Multi-layered nominal apposition with suspended case inflection marking only the rightmost head nominal.",
    learnerExplanation: "When introducing state officials or laureates, stack their formal titles in front of their name, adding case endings only to the final word.",
    technicalNotes: "Suspended affixation rule: preceding appositives remain in the bare citation stem."
  },
  {
    conceptId: "gram_c1_adversative_concessive_connectors_formal",
    englishTitle: "Formal Adversative and Concessive Transitions (Үүнийг үл харгалзан, Хэдийгээр тийм боловч)",
    mongolianTitle: "Албан найруулгын харшуулан өгүүлэх холбоос үгс",
    category: "Discourse Grammar",
    firstTargetLevel: "C1",
    masteryTargetLevel: "C1",
    prerequisites: ["gram_c1_complex_appositive_titles_and_epithets"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_c1_causative_nominalizations_in_governance"],
    modality: "productive",
    vowelHarmonyRequired: false,
    morphologyRequired: false,
    recursInAdvanced: true,
    knownComplications: ["Used to structure counter-arguments in policy briefs and analytical white papers."],
    description: "Elevated transitions for policy analysis: үүнийг үл харгалзан 'notwithstanding this / regardless of this', хэдийгээр тийм боловч 'be that as it may / even so', гэвч нөгөө талаар 'yet on the other hand'.",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "High-Level Transitions: Notwithstanding This & Even So",
    linguisticAnalysis: "Negative converbial postpositions (үл харгалзан) and complex modal adversatives structuring formal policy counter-argumentation.",
    learnerExplanation: "Use these phrases when writing high-level policy papers to present counter-arguments gracefully.",
    technicalNotes: "Үл харгалзан uses the pre-verbal classical negative particle үл."
  },
  {
    conceptId: "gram_c1_causative_nominalizations_in_governance",
    englishTitle: "Causative Nominalizations in Institutional Governance (Шийдвэрлүүлэхээр, Батлуулахаар)",
    mongolianTitle: "Төрийн удирдлагын шийдвэр гүйцэтгэлийн нэрлэсэн бүтэц",
    category: "Voice & Valency",
    firstTargetLevel: "C1",
    masteryTargetLevel: "C1",
    prerequisites: ["gram_c1_adversative_concessive_connectors_formal"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_c1_register_switching_matrix"],
    modality: "productive",
    vowelHarmonyRequired: true,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["Combines causative voice with future participle and instrumental/purposive case."],
    description: "Administrative formulation indicating submission for decision or enactment: Засгийн газарт шийдвэрлүүлэхээр өргөн мэдүүлэв 'Submitted to the Government for resolution', УИХ-аар батлуулахаар төсөл боловсруулав 'Drafted a bill to be enacted by Parliament'.",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Governance Language: Submitting Bills for Enactment (батлуулахаар өргөн барих)",
    linguisticAnalysis: "Causative-purposive participial construction (-уул- + -х- + -аар) indicating institutional submission for ratification.",
    learnerExplanation: "This construction is how Mongolian civil servants state that a proposal has been sent up for official approval.",
    technicalNotes: "Standard phrasing in civil service correspondence and parliamentary bill submissions."
  },
  {
    conceptId: "gram_c1_register_switching_matrix",
    englishTitle: "Sociolinguistic Register Calibration: Bureaucratic, Academic, and Cultured Vernacular",
    mongolianTitle: "Найруулгын төрөл зүйлийг оновчтой хослуулах ба шилжих чадвар",
    category: "Register & Sociolinguistics",
    firstTargetLevel: "C1",
    masteryTargetLevel: "C1",
    prerequisites: ["gram_c1_causative_nominalizations_in_governance"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_c2_rapid_khalkha_spoken_phonotactics"],
    modality: "productive",
    vowelHarmonyRequired: false,
    morphologyRequired: false,
    recursInAdvanced: true,
    knownComplications: ["Avoiding inappropriate colloquialisms in state filings and avoiding stiff bureaucratic phrasing in media interviews."],
    description: "The pragmatic ability to smoothly shift registers in real time: transitioning from intimate peer humor (юу байна, хөгшөөн?), to formal conference presentation (эрхэм хүндэт төлөөлөгчид өө), diplomatic greeting (та бүхний амар амгаланг айлтгая), or precise technical analysis without stylistic friction.",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Switching Registers: Sounding Right in Every Situation",
    linguisticAnalysis: "Meta-pragmatic stylistic competence across the five classical Mongolian prose functional styles (functional stylistics).",
    learnerExplanation: "Learn to recognize the right words for every occasion, knowing when to be casual and when to sound like a state diplomat.",
    technicalNotes: "Aligns with the Mongolian national standard for functional prose stylistics (Уран найруулга зүй)."
  },

  // ==========================================
  // LEVEL C2 CONCEPTS (18 CONCEPTS)
  // ==========================================
  {
    conceptId: "gram_c2_rapid_khalkha_spoken_phonotactics",
    englishTitle: "Rapid Khalkha Connected Speech: Vowel Coalescence, Particle Contraction & Ellipsis",
    mongolianTitle: "Ярианы хэлний хурдан хэллэг, авианы нийлц ба товчлол",
    category: "Spoken Discourse",
    firstTargetLevel: "C2",
    masteryTargetLevel: "C2",
    prerequisites: ["gram_c1_register_switching_matrix"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_c2_conversational_repair_and_discourse_particles"],
    modality: "both",
    vowelHarmonyRequired: false,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["Colloquial speech compresses written grammatical suffixes into radically shortened phonetic forms."],
    description: "Decoding and producing authentic fast Khalkha speech reductions: байгаа юм -> байна / байгаан, явж байна -> явжийн, юу хийж байгаа юм бэ -> юу хийжийн, мэдэхгүй -> мэдэхкү, тэгээд тэгсэн чинь -> тэгэнгүүт.",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Real Fast Spoken Mongolian: Contractions & Everyday Reductions (явжийн, байгаан)",
    linguisticAnalysis: "Post-lexical phonological rules in naturalistic connected Khalkha: vowel coalescence, unstressed schwa deletion, and clitic merging.",
    learnerExplanation: "Native speakers in Ulaanbaatar don't say 'явж байна' in quick talk—they say 'явжийн'. Master these natural contractions to sound truly native.",
    technicalNotes: "Crucial for C2 listening comprehension of unscripted podcasts, comedy sketches, and street banter."
  },
  {
    conceptId: "gram_c2_conversational_repair_and_discourse_particles",
    englishTitle: "Spoken Conversational Management: Fillers, Hesitation Markers, and Real-Time Repair",
    mongolianTitle: "Ам ярианы явц дахь аялга сул үгс, засаж залруулах арга барил",
    category: "Spoken Discourse",
    firstTargetLevel: "C2",
    masteryTargetLevel: "C2",
    prerequisites: ["gram_c2_rapid_khalkha_spoken_phonotactics"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_c2_conversational_tag_consensus_markers"],
    modality: "productive",
    vowelHarmonyRequired: false,
    morphologyRequired: false,
    recursInAdvanced: true,
    knownComplications: ["Deploying fillers naturally without sounding inarticulate."],
    description: "Using authentic Mongolian conversational management devices: нөгөө юу... 'you know, that...', ер нь бол 'basically / in general', тэгээд яахав 'well, whatever the case', юу л даа 'well, it's like this...', шулуухан хэлэхэд 'to speak candidly'.",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Natural Speech Fillers: Thinking Out Loud in Mongolian (нөгөө юу, ер нь бол)",
    linguisticAnalysis: "Spoken discourse management particles facilitating turn-taking, floor-holding, and conversational self-repair.",
    learnerExplanation: "Use phrases like ер нь бол ('basically') and нөгөө юу ('well, you know') to pause and think naturally just like native speakers do.",
    technicalNotes: "Significantly enhances perceived native fluency during spontaneous oral presentations and interviews."
  },
  {
    conceptId: "gram_c2_conversational_tag_consensus_markers",
    englishTitle: "Conversational Tag Questions and Interpersonal Consensus Seeking",
    mongolianTitle: "Ярианы явц дахь ойлголцол, санаа нийлэлтийг баталгаажуулах сул үгс",
    category: "Spoken Discourse",
    firstTargetLevel: "C2",
    masteryTargetLevel: "C2",
    prerequisites: ["gram_c2_conversational_repair_and_discourse_particles"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_c2_pragmatic_irony_and_understatement"],
    modality: "productive",
    vowelHarmonyRequired: false,
    morphologyRequired: false,
    recursInAdvanced: true,
    knownComplications: ["Requires perfect intonation contour to distinguish genuine inquiry from rhetorical solidarity."],
    description: "Seeking peer consensus and conversational solidarity: тийм биз дээ? 'right? / wouldn't you say?', тэгэлгүй яахав 'naturally / without a doubt!', тийм ээ? 'isn't that right?', үнэн биз? 'true, isn't it?'.",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Tag Questions & Seeking Agreement: Right? & Naturally! (тийм биз дээ, тэгэлгүй яахав)",
    linguisticAnalysis: "Interpersonal consensus markers operating at the pragmatic layer to sustain interlocutor engagement and solidarity.",
    learnerExplanation: "Keep your listener engaged with tags like тийм биз дээ? ('right?') and respond warmly with тэгэлгүй яахав ('of course!').",
    technicalNotes: "Essential for spontaneous debates, social dinners, and informal business rapport."
  },
  {
    conceptId: "gram_c2_pragmatic_irony_and_understatement",
    englishTitle: "Subtle Pragmatic Stance: Irony, Sarcasm, and Rhetorical Understatement",
    mongolianTitle: "Ёгт битүү утга, хошигнол, далд шүүмжлэлийг илэрхийлэх арга",
    category: "Discourse Grammar",
    firstTargetLevel: "C2",
    masteryTargetLevel: "C2",
    prerequisites: ["gram_c2_conversational_tag_consensus_markers"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_c2_somatic_idiomatic_metaphors"],
    modality: "both",
    vowelHarmonyRequired: false,
    morphologyRequired: false,
    recursInAdvanced: true,
    knownComplications: ["Detecting veiled irony where surface words appear polite or positive but intonation reveals critique."],
    description: "Navigating deep conversational nuance: praising with mild irony (Сүрхий л хүн дээ 'What a remarkable fellow indeed [sarcastic]'), rhetorical understatement (Яахав дээ, болж л байна 'Well, it's managing somehow [implying modest success]'), and self-deprecating humor.",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Mongolian Irony & Humor: Reading Between the Lines",
    linguisticAnalysis: "Pragmatic presupposition violation and conversational implicature modulation in high-fluency Khalkha dialogue.",
    learnerExplanation: "Understand when a Mongolian speaker is gently teasing or being sarcastic even when using polite words.",
    technicalNotes: "A hallmark of true C2 cultural and linguistic mastery."
  },
  {
    conceptId: "gram_c2_somatic_idiomatic_metaphors",
    englishTitle: "Steppe Somatic Metaphors in Modern Professional and Political Discourse",
    mongolianTitle: "Бие эрхтний шилжсэн утга ба орчин цагийн нийгмийн хэллэг",
    category: "Idiomatic Grammar",
    firstTargetLevel: "C2",
    masteryTargetLevel: "C2",
    prerequisites: ["gram_c2_pragmatic_irony_and_understatement"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_c2_satirical_polemical_framing"],
    modality: "productive",
    vowelHarmonyRequired: false,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["These traditional anatomical metaphors are pervasive in modern business and political talk."],
    description: "Mastering ubiquitous conceptual body metaphors: толгой өвдөх (to be a headache/major problem), гар хумхих (to sit idly / fold one's hands), нүд тайлах (to broaden one's horizons / be enlightened), хөл алдах (to stumble/be overwhelmed), ам алдах (to slip of the tongue / make a promise).",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Body Metaphors in Modern Life: Hands, Eyes & Head in Business & News",
    linguisticAnalysis: "Embodied cognitive metaphor schemes mapped onto abstract socio-political and economic relations.",
    learnerExplanation: "Use phrases like гар хумхих ('folding one's hands' = doing nothing) and нүд тайлах ('opening eyes' = learning the world) in modern commentary.",
    technicalNotes: "Grounds modern political discourse directly in traditional nomadic somatic imagery."
  },
  {
    conceptId: "gram_c2_satirical_polemical_framing",
    englishTitle: "Contemporary Editorial Polemics: Satirical Framing and Political Commentary",
    mongolianTitle: "Нийтлэлийн хурц найруулга, хоржоонтой шүүмжлэл",
    category: "Discourse Grammar",
    firstTargetLevel: "C2",
    masteryTargetLevel: "C2",
    prerequisites: ["gram_c2_somatic_idiomatic_metaphors"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_c2_literary_polyphony_and_indirect_interior_monologue"],
    modality: "productive",
    vowelHarmonyRequired: false,
    morphologyRequired: false,
    recursInAdvanced: true,
    knownComplications: ["Crafting biting social critique while preserving stylistic elegance and wit."],
    description: "Constructing satirical and polemical arguments for leading newspaper columns and media essays: utilizing rhetorical questions (хэзээ хүртэл тэвчих вэ? 'until when shall we endure?'), ironic parallelisms, and pungent cultural proverbs adapted to modern urban life.",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Sharp Opinion Columns: Satire, Critique & Biting Commentary",
    linguisticAnalysis: "Polemological macro-syntax, adversarial topicalization, and satirical rhetorical tropes in contemporary opinion journalism.",
    learnerExplanation: "Write persuasive, witty opinion pieces that challenge social issues using authentic Mongolian rhetorical style.",
    technicalNotes: "Required for publishing commentary in top Mongolian media such as Baabar.mn or News.mn."
  },
  {
    conceptId: "gram_c2_literary_polyphony_and_indirect_interior_monologue",
    englishTitle: "Contemporary Fiction Syntax: Polyphonic Voice and Free Indirect Monologue",
    mongolianTitle: "Уран зохиолын найруулгын олон хоолойн бүтэц, дотоод монолог",
    category: "Literary Syntax",
    firstTargetLevel: "C2",
    masteryTargetLevel: "C2",
    prerequisites: ["gram_c2_satirical_polemical_framing"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_c2_legal_constitutional_clause_architecture"],
    modality: "productive",
    vowelHarmonyRequired: false,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["Seamless blending of narrator voice and character thought without overt 'he thought' tags."],
    description: "Analyzing and producing modern Mongolian literary prose: shifting viewpoints between narrator and protagonist, free indirect discourse (дотоод сэтгэлийн монолог), lyrical nature personification, and stream-of-consciousness clauses in contemporary novels.",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Modern Mongolian Fiction: Internal Thoughts & Narrative Voices",
    linguisticAnalysis: "Syntactic polyphony and quasi-direct discourse in award-winning contemporary Mongolian literature.",
    learnerExplanation: "Read and write modern Mongolian short stories where characters' inner psychological thoughts blend smoothly into the narrator's voice.",
    technicalNotes: "Exemplified in the contemporary prose of authors such as G. Ayurzana and B. Shuudertsetseg."
  },
  {
    conceptId: "gram_c2_legal_constitutional_clause_architecture",
    englishTitle: "Advanced Legal Interpretation: Constitutional and Statutory Clause Parsing",
    mongolianTitle: "Үндсэн хууль ба хууль зүйн нарийн найруулгын тайлал",
    category: "Register & Sociolinguistics",
    firstTargetLevel: "C2",
    masteryTargetLevel: "C2",
    prerequisites: ["gram_c2_literary_polyphony_and_indirect_interior_monologue"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_c2_seamless_register_navigating"],
    modality: "both",
    vowelHarmonyRequired: false,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["Disentangling multi-sentence legislative provisions where multiple exceptions and proviso clauses modify a single subject."],
    description: "Analyzing the constitutional syntax of the 1992 Constitution of Mongolia: proviso clauses (...гэхдээ энэ нь ... үндэслэл болохгүй 'provided however that this shall not constitute grounds for...'), jurisdictional carve-outs, and statutory definitions in high corporate and constitutional jurisprudence.",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Constitutional Law & Legal Filings: Parsing Complex Legislation",
    linguisticAnalysis: "Juridical macro-syntax, deontic scoping, exception proviso clauses, and statutory definitions in Mongolian constitutional law.",
    learnerExplanation: "Parse the most complex legal documents in Mongolia, such as constitutional court decisions and commercial arbitration agreements.",
    technicalNotes: "Standard for senior legal practitioners and constitutional scholars."
  },
  {
    conceptId: "gram_c2_seamless_register_navigating",
    englishTitle: "Seamless Register Navigation: Steppe Vernacular to Supreme State Chancellery",
    mongolianTitle: "Аялгуу, найруулгын дээд зэргийн чөлөөт шилжилт",
    category: "Register & Sociolinguistics",
    firstTargetLevel: "C2",
    masteryTargetLevel: "C2",
    prerequisites: ["gram_c2_legal_constitutional_clause_architecture"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_c2_rhetorical_parallelism_alliteration"],
    modality: "productive",
    vowelHarmonyRequired: false,
    morphologyRequired: false,
    recursInAdvanced: true,
    knownComplications: ["Requires complete intuitive socio-pragmatic instinct across all generations and settings."],
    description: "Fluid, native-level movement across the full sociolinguistic continuum: chatting comfortably with a countryside herder in traditional pastoral vocabulary (малын тарга хүч, өвөлжөө бууц), negotiating business in modern technical terms (хөрөнгө оруулалтын өгөөж), and addressing dignitaries in supreme honorific protocol (төрийн тэргүүн танаа).",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Complete Linguistic Chameleon: From Steppe Ger to Diplomatic Banquet",
    linguisticAnalysis: "Omni-register sociolinguistic agility and dynamic stylistic code-switching across the totality of modern Mongolian speech domains.",
    learnerExplanation: "Express yourself with total confidence anywhere in Mongolia—from a fireside chat in a rural ger to a live televised debate in the capital.",
    technicalNotes: "The ultimate definition of modern CEFR C2 communicative competence in Mongolian."
  },
  // Cultural Enrichment Stream
  {
    conceptId: "gram_c2_rhetorical_parallelism_alliteration",
    englishTitle: "Cultural Enrichment: Metric Head-Alliteration Syntactic Balance (Толгой холбох ёс)",
    mongolianTitle: "Толгой холбох ёс ба найруулгын уран тэгш хэм",
    category: "Cultural Heritage Syntax",
    firstTargetLevel: "C2",
    masteryTargetLevel: "C2",
    prerequisites: ["gram_c2_seamless_register_navigating"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_c2_syntactic_parallelism_in_verse"],
    modality: "productive",
    vowelHarmonyRequired: true,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["Constructing poetic lines where initial consonants or vowels alliterate strictly across every line."],
    description: "The metric foundation of Mongolian poetry: initial sound alliteration (толгой холболт) where each poetic line begins with the same phoneme or syllable class, coupled with syntactic and semantic parallelism across paired couplets.",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Poetic Craft: Head-Alliteration in Mongolian Verse (толгой холбох)",
    linguisticAnalysis: "Strophic head-alliteration metrics and syntactic parallelism governing poetic lines in traditional and modern Mongolian poetry.",
    learnerExplanation: "In Mongolian poetry, lines rhyme at the beginning rather than at the end. Master this rule to compose authentic poetic verses.",
    technicalNotes: "Distinctive structural feature of Central Asian oral and written poetic heritage."
  },
  {
    conceptId: "gram_c2_syntactic_parallelism_in_verse",
    englishTitle: "Cultural Enrichment: Syntactic Parallelism and Paired Couplets in Traditional Verse",
    mongolianTitle: "Яруу найргийн тэгш хэмт бүтэц, хоршоо мөрийн найруулга",
    category: "Cultural Heritage Syntax",
    firstTargetLevel: "C2",
    masteryTargetLevel: "C2",
    prerequisites: ["gram_c2_rhetorical_parallelism_alliteration"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_c2_classical_epic_syntax_secret_history"],
    modality: "productive",
    vowelHarmonyRequired: true,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["Requires identical grammatical case, participle, or converb slots across matching paired lines."],
    description: "Balancing lines of verse so that each grammatical slot in Line 1 mirrors the grammatical category in Line 2 (e.g. Морины явдал саадгүй / Мөрний урсгал саадгүй 'Unobstructed the horse's gait / Unobstructed the river's flow').",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Poetic Symmetry: Paired Grammar Slots in Traditional Couplets",
    linguisticAnalysis: "Isosyntactic verse parallelism with morphological symmetry across strophes.",
    learnerExplanation: "Learn how Mongolian poets construct matching couplets where every word in line 2 matches the grammatical part of speech in line 1.",
    technicalNotes: "Preserved continuously from the Orkhon Inscriptions through modern lyrical verse."
  },
  {
    conceptId: "gram_c2_classical_epic_syntax_secret_history",
    englishTitle: "Cultural Enrichment: Syntactic Architecture of The Secret History of the Mongols (1240 CE)",
    mongolianTitle: "Монголын нууц товчооны найруулга зүй, эртний хэлний өгүүлбэрийн бүтэц",
    category: "Cultural Heritage Syntax",
    firstTargetLevel: "C2",
    masteryTargetLevel: "C2",
    prerequisites: ["gram_c2_syntactic_parallelism_in_verse"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_c2_archaic_case_morphology_secret_history"],
    modality: "both",
    vowelHarmonyRequired: true,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["Deciphering pre-modern syntax, unreduced vowels, and archaic converbs in modern Cyrillic scholarly editions."],
    description: "Reading and analyzing excerpts from The Secret History of the Mongols (Монголын нууц товчоо): understanding epic narrative cadences, heroic epithets, and the formulaic oaths of blood brotherhood (анда бололцох) and vassalage.",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Reading The Secret History of the Mongols: 13th-Century Epic Syntax",
    linguisticAnalysis: "Middle Mongol syntactic structures rendered in modern Cyrillic transcription, including paratactic coordination and archaic aspectual markers.",
    learnerExplanation: "Read passages from Mongolia's greatest historical and literary monument in modern Cyrillic, understanding the rhythmic oaths of Chinggis Khaan.",
    technicalNotes: "A cultural enrichment pinnacle establishing profound philological insight into modern vocabulary roots."
  },
  {
    conceptId: "gram_c2_archaic_case_morphology_secret_history",
    englishTitle: "Cultural Enrichment: Archaic Case and Suffix Variations in Historical Texts",
    mongolianTitle: "Түүхэн сурвалжийн хуучин тийн ялгал ба бүтцийн онцлог",
    category: "Cultural Heritage Syntax",
    firstTargetLevel: "C2",
    masteryTargetLevel: "C2",
    prerequisites: ["gram_c2_classical_epic_syntax_secret_history"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_c2_ceremonial_blessing_formulaic_syntax"],
    modality: "receptive",
    vowelHarmonyRequired: true,
    morphologyRequired: true,
    recursInAdvanced: false,
    knownComplications: ["Recognizing historical case markers (-ай/-эй, -а/-э, -нар) when reading philological adaptations."],
    description: "Recognizing historical morphological remnants: genitive in -ай/-эй, accusative in -ий, locative in -а/-э, and archaic plural markers (-уд/-үд, -нар) when reading philological editions of ancient chronicles.",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Archaic Endings in Historical Chronicles: Deciphering Ancient Suffixes",
    linguisticAnalysis: "Philological recognition of Middle Mongol case suffixes and historical plural morphemes.",
    learnerExplanation: "Recognize older grammatical endings when reading historical documents and classical legends.",
    technicalNotes: "Essential for reading historical monuments and 17th-century chronicles (Алтан товч, Эрдэнийн эрхи)."
  },
  {
    conceptId: "gram_c2_ceremonial_blessing_formulaic_syntax",
    englishTitle: "Cultural Enrichment: Formulaic Syntax of Ceremonial Blessings (Ерөөл тавих)",
    mongolianTitle: "Ерөөлийн найруулга, бэлгэ дэмбэрэлт үгийн өгүүлбэрийн тогтолцоо",
    category: "Cultural Heritage Syntax",
    firstTargetLevel: "C2",
    masteryTargetLevel: "C2",
    prerequisites: ["gram_c2_archaic_case_morphology_secret_history"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_c2_praise_poetry_cataloguing_syntax"],
    modality: "productive",
    vowelHarmonyRequired: true,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["Must follow strict auspicious formulaic opening, elaboration of virtues, and concluding optative blessings."],
    description: "The syntactic composition of traditional ceremonial blessings recited at Tsagaan Sar, weddings, and child hair-cutting rites: auspicious cataloguing, optative verb sequences (-болтугай, -болтугай), and rhythmic steppe imagery.",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "The Art of Blessing: Crafting Ceremonial Verses (ерөөл тавих)",
    linguisticAnalysis: "Auspicious performative speech-act syntax characterized by repetitive optative and precative verbal inflections.",
    learnerExplanation: "Deliver a traditional blessing at a wedding or celebration following the exact poetic formulas honored by Mongolian elders.",
    technicalNotes: "One of the most admired traditional social skills in Mongolian communal life."
  },
  {
    conceptId: "gram_c2_praise_poetry_cataloguing_syntax",
    englishTitle: "Cultural Enrichment: Praise Poetry Syntax and Rhythmic Cataloguing (Магтаал)",
    mongolianTitle: "Магтаалын найруулга, эд зүйл ба байгалийг магтан дуулах бүтэц",
    category: "Cultural Heritage Syntax",
    firstTargetLevel: "C2",
    masteryTargetLevel: "C2",
    prerequisites: ["gram_c2_ceremonial_blessing_formulaic_syntax"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_c2_proverbial_syntactic_compression"],
    modality: "both",
    vowelHarmonyRequired: true,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["Synthesizing vast descriptive adjectives and similes before a climactic nominal subject."],
    description: "Analyzing and performing traditional praise odes (магтаал) dedicated to fast racehorses, sacred mountains, wrestling champions, or the Morin Khuur: rhythmic lists, extensive similes, and climactic vocatives.",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Praise Odes: Chanting the Virtues of Steppe & Steed (магтаал)",
    linguisticAnalysis: "Laudatory hymnodic syntax employing extensive pre-nominal adjectival subordination and acoustic onomatopoeia.",
    learnerExplanation: "Understand how bards praise winning racehorses and great wrestlers using flowing rhythmic catalogues.",
    technicalNotes: "Performs a key ritual role at Naadam festivals nationwide."
  },
  {
    conceptId: "gram_c2_proverbial_syntactic_compression",
    englishTitle: "Cultural Enrichment: Gnomic Syntactic Compression in Nomadic Proverbs (Зүйр цэцэн үг)",
    mongolianTitle: "Зүйр цэцэн үгийн найруулгын хураангуйлал ба гүн утга",
    category: "Cultural Heritage Syntax",
    firstTargetLevel: "C2",
    masteryTargetLevel: "C2",
    prerequisites: ["gram_c2_praise_poetry_cataloguing_syntax"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_c2_dialectal_morphosyntax_awareness"],
    modality: "both",
    vowelHarmonyRequired: false,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["Proverbs omit copulas, pronouns, and explicit case markers in favor of compressed elliptic balance."],
    description: "The elliptic, highly compressed grammar of classical nomadic proverbs: subject ellipsis, stark contrastive parallelism, and implicit conditional logic (e.g. Тэжээсэн бяруу тэрэг эвдэнэ 'The reared calf breaks the cart' [ingratitude], Эзэн хичээвэл заяа хичээнэ 'If the master strives, fate strives').",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Proverbial Wisdom: Compressed Mongolian Proverbs (зүйр цэцэн үг)",
    linguisticAnalysis: "Gnomic present aspect, copular zero-ellipsis, and condensed binary parallelism in paremiological syntax.",
    learnerExplanation: "Deploy authentic Mongolian proverbs in conversation to summarize complex life situations with traditional eloquence.",
    technicalNotes: "Proverbs embody centuries of empirical nomadic pastoral philosophy."
  },
  {
    conceptId: "gram_c2_dialectal_morphosyntax_awareness",
    englishTitle: "Cultural Enrichment: Dialectal Morphosyntactic Awareness (Oirat, Buryat, Inner Mongolian)",
    mongolianTitle: "Монгол хэлний нутгийн аялгууны бүтэц, хувирлыг ялган таних",
    category: "Cultural Heritage Syntax",
    firstTargetLevel: "C2",
    masteryTargetLevel: "C2",
    prerequisites: ["gram_c2_proverbial_syntactic_compression"],
    recommendedPriorConcepts: [],
    unlocks: ["gram_c2_supreme_stylistic_authorship"],
    modality: "receptive",
    vowelHarmonyRequired: true,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["Distinguishing standard Khalkha suffixes from western Oirat (-на/нэ vs -на/-нэ) and northern Buryat (-ха/-хэ, -жа байна) dialectal markers."],
    description: "Receptive comprehension of major regional Mongolic dialects: western Oirat (Kalmyk/Bayad/Dörvöd phonological shifts and past marker -вээ), northern Buryat (intervocalic sibilant debuccalization s -> h and verbal forms), and southern Inner Mongolian grammatical idioms.",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Mongolian Dialects: Understanding Western, Northern & Southern Speech",
    linguisticAnalysis: "Comparative Mongolic dialectology analyzing isoglosses across Khalkha, Oirat-Kalmyk, Buryat, and Chakhar-Khorchin varieties.",
    learnerExplanation: "Recognize and understand regional accents and grammatical variants when traveling to Western Mongolia or meeting Buryat and Inner Mongolian speakers.",
    technicalNotes: "Enables students to engage with the broader Pan-Mongolian cultural sphere."
  },
  {
    conceptId: "gram_c2_supreme_stylistic_authorship",
    englishTitle: "Supreme Stylistic Authorship: Cultivating a Personal Modern Mongolian Voice",
    mongolianTitle: "Хувийн уран зохиол, илтгэхүйн бие даасан өвөрмөц найруулга",
    category: "Discourse Grammar",
    firstTargetLevel: "C2",
    masteryTargetLevel: "C2",
    prerequisites: ["gram_c2_dialectal_morphosyntax_awareness"],
    recommendedPriorConcepts: [],
    unlocks: [],
    modality: "productive",
    vowelHarmonyRequired: true,
    morphologyRequired: true,
    recursInAdvanced: true,
    knownComplications: ["Requires seamless command of the entire language to produce original, publishable prose or captivating oratory."],
    description: "The peak of language learning: expressing complex original thoughts, philosophical arguments, or literary memoirs with an unmistakable authorial voice, effortless rhetorical variety, and deep cultural resonance in Modern Standard Mongolian (жишээлбэл, 'он цагийн эрхээр замхрахгүй үнэт зүйлс', 'сэтгэлийн гүнд орших эх нутаг').",
    verificationStatus: "VERIFIED",
    pedagogicalLabel: "Mastery: Finding Your Own Voice in Mongolian",
    linguisticAnalysis: "Unconstrained stylistic creativity and rhetorical sovereignty across all communicative genres of Modern Standard Mongolian.",
    learnerExplanation: "Write and speak with your own unique style, creating elegant essays and persuasive speeches that move and inspire native listeners.",
    technicalNotes: "The ultimate culmination of the CEFR C2 proficiency framework."
  }
];
