import { CommunicativeFunctionSpec } from './dataCommunicative_A1';

export const communicativeB1B2Data: CommunicativeFunctionSpec[] = [
  // B1 Communicative Functions (25 Functions)
  {
    functionId: "comm_b1_01_narrating_personal_anecdotes",
    title: "Narrate Humorous and Dramatic Personal Anecdotes",
    mongolianTitle: "Хөгжилтэй, сонирхолтой явдал, онигоо ярих",
    level: "B1",
    domain: "Narrative",
    prerequisites: ["comm_a2_06_weekend_activities_past"],
    communicativeGoal: "Deliver an extended personal narrative detailing setting, complications, climax, and resolution.",
    typicalScenarios: ["Sharing stories around a campfire", "Social banter among university friends"],
    keyStructures: ["Тэгсэн чинь юу болсон гээч", "Гэтэл гэнэт", "Яг тэр үед би сандраад", "Эцэст нь бид инээлдсэн"],
    expectedOutcome: "Learner uses lively discourse markers to sustain listener suspense across 10-15 sentences."
  },
  {
    functionId: "comm_b1_02_sequencing_past_chronology",
    title: "Sequence Events Chronologically with Complex Converbs",
    mongolianTitle: "Үйл явдлын дарааллыг нарийн холбоосоор илэрхийлэх",
    level: "B1",
    domain: "Narrative",
    prerequisites: ["comm_b1_01_narrating_personal_anecdotes"],
    communicativeGoal: "Chronicle actions using immediate (-магц), continuous (-саар), and anterior (-сны дараа) converbs.",
    typicalScenarios: ["Debriefing after an event", "Reporting incident timelines"],
    keyStructures: ["Тэр ирмэгц хурал эхэлсэн", "Бороо орсоор байв", "Их сургуулиа төгссөний дараа ажилд орсон"],
    expectedOutcome: "Learner marshals temporal converbs to build precise chronological timelines."
  },
  {
    functionId: "comm_b1_03_expressing_opinions_agreements",
    title: "Express Personal Opinions and Partial Agreement",
    mongolianTitle: "Өөрийн байр суурийг илэрхийлэх ба санал нэгдэх",
    level: "B1",
    domain: "Interpersonal",
    prerequisites: ["comm_a2_25_reporting_third_party_speech"],
    communicativeGoal: "State views on contemporary topics and signal agreement with an interlocutor's points.",
    typicalScenarios: ["Roundtable seminar discussion", "Book club conversation"],
    keyStructures: ["Миний бодлоор энэ бол зөв шийдвэр", "Би тантай санал нэг байна", "Энэ тал дээр би санал нийлж байна"],
    expectedOutcome: "Learner articulates a point of view supported by reasoned elaboration."
  },
  {
    functionId: "comm_b1_04_respectful_disagreement",
    title: "Express Respectful Disagreement and Alternative Views",
    mongolianTitle: "Эелдгээр татгалзах, сөрөг байр сууриа илэрхийлэх",
    level: "B1",
    domain: "Interpersonal",
    prerequisites: ["comm_b1_03_expressing_opinions_agreements"],
    communicativeGoal: "Contradict or qualify an opinion without being confrontational.",
    typicalScenarios: ["Academic tutorial debate", "Workplace planning meeting"],
    keyStructures: ["Тийм байж болох ч, нөгөө талаас нь харвал", "Би өөр бодолтой байна", "Энэ арай л өрөөсгөл дүгнэлт байх"],
    expectedOutcome: "Learner employs concessive formulas (боловч, гэвч) to express respectful opposition."
  },
  {
    functionId: "comm_b1_05_making_causal_arguments",
    title: "Construct Logical Causal Arguments (Учраас, Тул, Учир нь)",
    mongolianTitle: "Шалтгаант холбоо, учир зүйг тайлбарлан ярих",
    level: "B1",
    domain: "Informational",
    prerequisites: ["comm_b1_03_expressing_opinions_agreements"],
    communicativeGoal: "Explain reasons, motivations, and contributing factors behind decisions or problems.",
    typicalScenarios: ["Explaining why a project was delayed", "Justifying a budget choice"],
    keyStructures: ["Цаг агаар муудсан учраас бид буцсан", "Шалгалт дөхсөн тул би завгүй байна", "Учир нь энэ арга илүү үр дүнтэй"],
    expectedOutcome: "Learner connects propositions logically using causal postpositions and conjunctions."
  },
  {
    functionId: "comm_b1_06_stating_purpose_long_term_goals",
    title: "Articulate Long-Term Objectives and Dedicated Purposes",
    mongolianTitle: "Хэтийн зорилго, эрмэлзлээ тодорхойлох (-хын тулд)",
    level: "B1",
    domain: "Interpersonal",
    prerequisites: ["comm_b1_05_making_causal_arguments"],
    communicativeGoal: "Explain what one is striving to achieve for career, family, or society using -хын тулд and -ын төлөө.",
    typicalScenarios: ["Scholarship statement of purpose interview", "Mentorship discussion"],
    keyStructures: ["Монголын хөгжилд хувь нэмэр оруулахын тулд", "Гэр бүлийнхээ ирээдүйн төлөө би суралцаж байна"],
    expectedOutcome: "Learner uses telic postpositional phrases to express principled personal purpose."
  },
  {
    functionId: "comm_b1_07_relaying_hearsay_news",
    title: "Report Hearsay, Rumors, and Indirect News (Гэнэ, Сурагтай)",
    mongolianTitle: "Сонссон дуулснаа дамжуулах, цуу яриа лавлах",
    level: "B1",
    domain: "Informational",
    prerequisites: ["comm_a2_25_reporting_third_party_speech"],
    communicativeGoal: "Relay news heard from third parties, rumors, or unverified reports using reportative evidentials.",
    typicalScenarios: ["Sharing community news", "Discussing public transit fare changes"],
    keyStructures: ["Тэнд шинэ зам тавьж байгаа гэнэ", "Цас их орсон сурагтай байна", "Түүнийг ажилдаа эргэж ирнэ гэж сонслоо"],
    expectedOutcome: "Learner disclaims personal responsibility for information veracity using гэнэ / сурагтай."
  },
  {
    functionId: "comm_b1_08_speculating_visual_evidence",
    title: "Deduce Outcomes Based on Visual Evidence (Бололтой, Магадгүй)",
    mongolianTitle: "Гадаад байдалд тулгуурлан таамаглал дэвшүүлэх",
    level: "B1",
    domain: "Informational",
    prerequisites: ["comm_b1_07_relaying_hearsay_news"],
    communicativeGoal: "Speculate about what has happened or is about to happen based on visual clues.",
    typicalScenarios: ["Looking at storm clouds gathering", "Observing an empty office desk"],
    keyStructures: ["Тэр өвдсөн бололтой", "Бороо орох шинжтэй байна", "Магадгүй тэр хоцрох байх"],
    expectedOutcome: "Learner uses epistemic modals of deduction (бололтой, шинжтэй, янзтай) appropriately."
  },
  {
    functionId: "comm_b1_09_participating_job_interview",
    title: "Answer Questions in a Structured Employment Interview",
    mongolianTitle: "Ажлын ярилцлагад оролцох, туршлагаа танилцуулах",
    level: "B1",
    domain: "Professional",
    prerequisites: ["comm_a1_08_professions_occupations", "comm_b1_06_stating_purpose_long_term_goals"],
    communicativeGoal: "Describe work experience, educational background, professional strengths, and salary expectations.",
    typicalScenarios: ["Job interview with a Mongolian NGO or company", "Internship screening"],
    keyStructures: ["Би энэ салбарт гурван жил ажилласан туршлагатай", "Миний давуу тал бол багаар ажиллах чадвар", "Энэ албан тушаалд өөрийгөө сорихыг хүсэж байна"],
    expectedOutcome: "Learner speaks about professional capabilities with formal grammatical register."
  },
  {
    functionId: "comm_b1_10_writing_formal_email_letter",
    title: "Compose Structured Formal Emails and Inquiries",
    mongolianTitle: "Албан захидал, цахим шуудан найруулах",
    level: "B1",
    domain: "Professional",
    prerequisites: ["comm_b1_09_participating_job_interview"],
    communicativeGoal: "Draft an email with proper greeting (Эрхэм хүндэт...), purpose statement, body paragraphs, and polite closing.",
    typicalScenarios: ["Writing to an academic advisor", "Contacting a government ministry department"],
    keyStructures: ["Эрхэм хүндэт захирал танаа", "Танд энэ өдрийн амар амгаланг айлтгая", "Хүсэлтийг хүлээн авч хариу ирүүлнэ үү", "Хүндэтгэсэн, ..."],
    expectedOutcome: "Learner formats business correspondence according to Mongolian epistolary norms."
  },
  {
    functionId: "comm_b1_11_hotel_reservation_complaints",
    title: "Resolve Hotel Lodging Issues and Lodge Polite Complaints",
    mongolianTitle: "Зочид буудалд гомдол гаргах, асуудал шийдвэрлэх",
    level: "B1",
    domain: "Transactional",
    prerequisites: ["comm_a2_04_renting_apartment_housing"],
    communicativeGoal: "Complain about lack of hot water, noisy neighbors, or broken heaters, and request a room change.",
    typicalScenarios: ["Hotel front desk in a regional center", "Tourist ger camp management"],
    keyStructures: ["Манай өрөөнд халуун ус гарахгүй байна", "Халаалт ажиллахгүй байгаа тул өрөөгөө сольмоор байна", "Үүнийг яаралтай засаж өгнө үү"],
    expectedOutcome: "Learner states dissatisfaction assertively yet politely and negotiates remedies."
  },
  {
    functionId: "comm_b1_12_reporting_car_breakdown_repair",
    title: "Describe Vehicle Mechanical Breakdown to a Mechanic",
    mongolianTitle: "Машины эвдрэл гэмтлийг засварчинд тайлбарлах",
    level: "B1",
    domain: "Transactional",
    prerequisites: ["comm_a2_18_buying_bus_train_tickets"],
    communicativeGoal: "Explain engine overheating, flat tire, brake failure, or strange noises to an auto mechanic.",
    typicalScenarios: ["Auto repair shop in Ulaanbaatar", "Roadside breakdown during a countryside expedition"],
    keyStructures: ["Хөдөлгүүр халаад байна", "Дугуй хагарчихсан", "Тоормос сайн барихгүй байна", "Засахад хэр хугацаа орох вэ?"],
    expectedOutcome: "Learner identifies mechanical components and conveys operational failure symptoms."
  },
  {
    functionId: "comm_b1_13_discussing_environmental_issues",
    title: "Discuss Air Pollution, Pasture Degradation, and Desertification",
    mongolianTitle: "Утаа, бэлчээрийн доройтол, цөлжилтийн тухай хэлэлцэх",
    level: "B1",
    domain: "Informational",
    prerequisites: ["comm_b1_05_making_causal_arguments"],
    communicativeGoal: "Discuss causes and remedies for Ulaanbaatar winter smog, mining impacts, and overgrazing.",
    typicalScenarios: ["Community discussion forum", "Classroom presentation on ecology"],
    keyStructures: ["Өвлийн улиралд утаа маш ихэсдэг", "Бэлчээрийн даац хэтэрсэн", "Цөлжилтийг зогсоохын тулд мод тарих хэрэгтэй"],
    expectedOutcome: "Learner uses ecological terms and articulates cause-and-effect relationships."
  },
  {
    functionId: "comm_b1_14_traditional_celebrations_tsagaan_sar",
    title: "Explain Tsagaan Sar Customs, Zolgolt, and Festive Foods",
    mongolianTitle: "Цагаан сарын уламжлал, золголт, идээ шүүсийг тайлбарлах",
    level: "B1",
    domain: "Cultural",
    prerequisites: ["comm_a2_14_countryside_ger_visiting_etiquette"],
    communicativeGoal: "Explain arm-crossing zolgolt rules for elders, preparation of uuts and buuz, and gifting.",
    typicalScenarios: ["Explaining White Month to foreign visitors", "Preparing for family Tsagaan Sar"],
    keyStructures: ["Сар шинэдээ сайхан шинэлж байна уу?", "Дүү нь ахмад хүнийхээ тохойг дэмжиж золгодог", "Ширээн дээр таваг засах, ууц тавих"],
    expectedOutcome: "Learner explains ritual kinship greetings and feast architecture with precision."
  },
  {
    functionId: "comm_b1_15_naadam_festival_three_games",
    title: "Describe the Three Manly Games of Naadam Festival",
    mongolianTitle: "Эрийн гурван наадмын дүрэм, онцлогийг ярих",
    level: "B1",
    domain: "Cultural",
    prerequisites: ["comm_b1_14_traditional_celebrations_tsagaan_sar"],
    communicativeGoal: "Explain rules of traditional wrestling (бөх), archery (сур), and long-distance horse racing (морин уралдаан).",
    typicalScenarios: ["Watching the Central Stadium opening ceremony", "Explaining festival highlights"],
    keyStructures: ["Монгол бөхөд жингийн ангилал байдаггүй", "Хурдан морьдыг нас насаар нь уралдуулдаг", "Мэргэн харваачдыг шалгаруулах"],
    expectedOutcome: "Learner discusses ranks (арслан, заан, аварга) and rules of traditional sport."
  },
  {
    functionId: "comm_b1_16_giving_advice_recommendations",
    title: "Offer Prudent Advice and Suggest Practical Alternatives",
    mongolianTitle: "Зөвлөгөө өгөх, оновчтой шийдэл санал болгох",
    level: "B1",
    domain: "Interpersonal",
    prerequisites: ["comm_b1_03_expressing_opinions_agreements"],
    communicativeGoal: "Recommend actionable courses of action using conditional converbs (-вал дээр) and modal softeners.",
    typicalScenarios: ["Advising a friend on housing", "Counseling a peer preparing for an exam"],
    keyStructures: ["Чи эмчид үзүүлбэл дээр байх", "Энэ номыг уншвал чамд хэрэгтэй", "Яараад хэрэггүй, дахин бодож үз"],
    expectedOutcome: "Learner calibrates advice politely to avoid sounding authoritarian."
  },
  {
    functionId: "comm_b1_17_expressing_emotional_reactions",
    title: "Express Disappointment, Relief, and Sympathy",
    mongolianTitle: "Сэтгэлийн хөдөлгөөн, харамсал, тайвшралаа илэрхийлэх",
    level: "B1",
    domain: "Interpersonal",
    prerequisites: ["comm_a1_05_apologies_pardon"],
    communicativeGoal: "Express shared sorrow upon hearing bad news or heartfelt relief after a narrow escape.",
    typicalScenarios: ["Supporting a friend who failed an interview", "Reacting to news of a recovered friend"],
    keyStructures: ["Ямар харамсалтай юм бэ!", "Ашгүй дээ, ямар их санаа амарчихав аа", "Битгий сэтгэлээр унаарай, бүх зүйл сайхан болно"],
    expectedOutcome: "Learner uses affective exclamations (ашгүй, хөөрхий) and consoling imperatives."
  },
  {
    functionId: "comm_b1_18_delegating_tasks_causative",
    title: "Delegate Tasks and Instruct Service Personnel (Causative)",
    mongolianTitle: "Ажил үүрэг даалгах, хүнээр ажил хийлгэх",
    level: "B1",
    domain: "Professional",
    prerequisites: ["comm_a1_34_classroom_instructions"],
    communicativeGoal: "Instruct tailors, printers, or assistants to modify, print, or deliver items using causative verbs.",
    typicalScenarios: ["Getting a document printed/copied", "Asking a tailor to shorten trousers"],
    keyStructures: ["Энэ хувцсыг богиносгуулмаар байна", "Үүнийг гурван хувь хэвлүүлээд өгнө үү", "Жолоочоор хүргүүлчихье"],
    expectedOutcome: "Learner commands causative verbal suffixes (-уулах, -лгах) to structure delegation."
  },
  {
    functionId: "comm_b1_19_describing_accidents_unintended_actions",
    title: "Describe Unintended Mishaps and Passive Occurrences",
    mongolianTitle: "Санамсаргүй болсон явдал, алдаа дутагдлыг тайлбарлах",
    level: "B1",
    domain: "Narrative",
    prerequisites: ["comm_b1_01_narrating_personal_anecdotes"],
    communicativeGoal: "Explain that an item was accidentally dropped, forgotten, or broken using passive/intensive forms.",
    typicalScenarios: ["Explaining why a vase broke", "Explaining late arrival due to traffic block"],
    keyStructures: ["Би түлхүүрээ хаячихсан", "Санамсаргүй гараас мултраад уначихлаа", "Зам хаагдсан тул саатсан"],
    expectedOutcome: "Learner uses aspectual -чих- and passive -гдэх to signal lack of deliberate intent."
  },
  {
    functionId: "comm_b1_20_clarifying_misunderstandings",
    title: "Clarify Semantic Misunderstandings and Rephrase Speech",
    mongolianTitle: "Буруу ойлголцлыг засах, үгээ өөрөөр тайлбарлах",
    level: "B1",
    domain: "Interpersonal",
    prerequisites: ["comm_a1_35_asking_language_clarification"],
    communicativeGoal: "Clarify what one originally meant when an interlocutor misunderstands.",
    typicalScenarios: ["Clearing up a confused meeting time", "Correcting an unintentional faux pas"],
    keyStructures: ["Би тэгж хэлэх гээгүй юм аа", "Миний хэлэх гэсэн санаа бол", "Өөрөөр хэлбэл, энэ нь ийм учиртай"],
    expectedOutcome: "Learner rephrases propositions seamlessly to preserve interpersonal harmony."
  },
  {
    functionId: "comm_b1_21_understanding_bank_transactions",
    title: "Manage Bank Account Operations and Mobile Transactions",
    mongolianTitle: "Банкны үйлчилгээ, данс нээх, гүйлгээ хийх",
    level: "B1",
    domain: "Transactional",
    prerequisites: ["comm_a2_20_banking_atm_currency_exchange"],
    communicativeGoal: "Open a commercial bank account, transfer funds via mobile app, and resolve transaction errors.",
    typicalScenarios: ["Visiting Khan Bank or Golomt Bank branch", "Configuring QPay payments"],
    keyStructures: ["Шинэ данс нээлгэх хүсэлтэй байна", "Шилжүүлэг хийх гэсэн юм", "Гүйлгээний шимтгэл хэд вэ?", "QPay-ээр төлөх боломжтой юу?"],
    expectedOutcome: "Learner conducts multi-tier banking transactions and electronic mobile payments."
  },
  {
    functionId: "comm_b1_22_discussing_books_films_reviews",
    title: "Review Books, Films, and Theatrical Performances",
    mongolianTitle: "Ном, кино, урлагийн бүтээлийг шүүмжлэн ярих",
    level: "B1",
    domain: "Informational",
    prerequisites: ["comm_a1_33_hobbies_free_time", "comm_b1_03_expressing_opinions_agreements"],
    communicativeGoal: "Summarize a film plot, analyze character motivation, and evaluate artistic execution.",
    typicalScenarios: ["Discussing a new Mongolian cinematic release", "Classroom literary critique"],
    keyStructures: ["Энэ киноны гол баатар бол", "Зохиолын гол санаа нь", "Жүжигчдийн тоглолт маш гайхалтай болсон"],
    expectedOutcome: "Learner presents a balanced aesthetic critique with thematic analysis."
  },
  {
    functionId: "comm_b1_23_comparing_city_country_lifestyles",
    title: "Contrast Urban Life in Ulaanbaatar with Pastoral Steppe Life",
    mongolianTitle: "Хот ба хөдөөгийн амьдралын хэв маягийг харьцуулах",
    level: "B1",
    domain: "Informational",
    prerequisites: ["comm_a2_23_comparing_items_places", "comm_a2_15_nomadic_livestock_five_animals"],
    communicativeGoal: "Analyze differences in pace of life, stress, food security, and family closeness between city and countryside.",
    typicalScenarios: ["Sociological essay discussion", "Intercultural dinner forum"],
    keyStructures: ["Хотод амьдрал хурдацтай боловч агаарын бохирдол ихтэй", "Хөдөөний амьдрал байгальтай ойр, тайван", "Нүүдэлчдийн сэтгэлгээ ба хотын соёл"],
    expectedOutcome: "Learner articulates multi-dimensional socio-cultural contrasts."
  },
  {
    functionId: "comm_b1_24_discussing_education_career_path",
    title: "Discuss Academic Specializations and Career Trajectories",
    mongolianTitle: "Мэргэжил сонголт, боловсролын замналын тухай ярих",
    level: "B1",
    domain: "Professional",
    prerequisites: ["comm_b1_09_participating_job_interview"],
    communicativeGoal: "Discuss university entrance exams, international scholarships, and market demand for skills.",
    typicalScenarios: ["Student guidance counseling", "Peer discussions about graduation paths"],
    keyStructures: ["ЭЕШ-д бэлтгэж байна", "Гадаадын тэтгэлэгт хөтөлбөрт өргөдөл гаргасан", "Энэ мэргэжил ирээдүйд их эрэлттэй"],
    expectedOutcome: "Learner uses Mongolian educational acronyms and career planning vocabulary."
  },
  {
    functionId: "comm_b1_25_hypothetical_present_wishes",
    title: "Express Hypothetical Wishes and Unreal Conditions",
    mongolianTitle: "Болзолт ба хүсэл мөрөөдлийн өгүүлбэр бүтээх (-сан бол)",
    level: "B1",
    domain: "Informational",
    prerequisites: ["comm_a2_27_expressing_future_intentions"],
    communicativeGoal: "Formulate hypothetical present and past wishes ('If I had more time, I would study Mongolian history').",
    typicalScenarios: ["Philosophical parlor games", "Discussing hypothetical policy choices"],
    keyStructures: ["Надад цаг байсан бол би хөдөө явах байсан", "Хэрэв би тэр үед мэдсэн бол тэгэхгүй байсан"],
    expectedOutcome: "Learner constructs counterfactual and hypothetical sentences using -сан бол ... -х байсан."
  },

  // B2 Communicative Functions (25 Functions)
  {
    functionId: "comm_b2_01_participating_formal_debates",
    title: "Participate in Structured Formal Debates and Forums",
    mongolianTitle: "Албан мэтгэлцээн, хэлэлцүүлэгт оролцож байр сууриа хамгаалах",
    level: "B2",
    domain: "Academic",
    prerequisites: ["comm_b1_04_respectful_disagreement"],
    communicativeGoal: "Present affirmative or negative arguments, cite empirical data, and rebut opposing speakers.",
    typicalScenarios: ["University debate club", "Public civic forum on municipal spending"],
    keyStructures: ["Нэгдүгээрт, баримт нотолгооноос харвал", "Сөрөг талын гаргасан дүгнэлт үндэслэл муутай", "Дүгнэж хэлэхэд"],
    expectedOutcome: "Learner adheres to debate parliamentary protocols and marshals structured rhetoric."
  },
  {
    functionId: "comm_b2_02_academic_essay_concessions",
    title: "Draft Academic Essays with Counter-Arguments and Concessions",
    mongolianTitle: "Эрдэм шинжилгээний эсээ найруулах, сөрөг талыг няцаах",
    level: "B2",
    domain: "Academic",
    prerequisites: ["comm_b2_01_participating_formal_debates"],
    communicativeGoal: "Write balanced scholarly essays addressing counter-theses using sophisticated transition particles.",
    typicalScenarios: ["Submitting a term paper", "Publishing an analytical blog post"],
    keyStructures: ["Хэдий тийм боловч", "Үүний зэрэгцээ анхаарах ёстой зүйл бол", "Үүнээс үзэхэд дараах дүгнэлтийг хийж болно"],
    expectedOutcome: "Learner writes academic texts maintaining scholarly distance and lexical variety."
  },
  {
    functionId: "comm_b2_03_counterfactual_regrets",
    title: "Analyze Historic Failures and Express Nuanced Regret",
    mongolianTitle: "Түүхэн болон хувийн алдаа дутагдлыг дүн шинжилгээтэй шүүн тунгаах",
    level: "B2",
    domain: "Narrative",
    prerequisites: ["comm_b1_25_hypothetical_present_wishes"],
    communicativeGoal: "Dissect why an initiative failed and evaluate how things would have unfolded under alternate strategies.",
    typicalScenarios: ["Business post-mortem", "Historical seminar evaluating 20th-century events"],
    keyStructures: ["Хэрэв тэгж шийдвэрлээгүй байсан бол ийм үр дагаварт хүрэхгүй байсан", "Бид цаг алдсан нь том алдаа болжээ"],
    expectedOutcome: "Learner combines complex modal auxiliary phrases to evaluate counterfactual histories."
  },
  {
    functionId: "comm_b2_04_analyzing_social_trends",
    title: "Analyze Demographic Shifts and Societal Megatrends",
    mongolianTitle: "Хүн ам зүйн өөрчлөлт, нийгмийн хандлагыг шинжлэх",
    level: "B2",
    domain: "Informational",
    prerequisites: ["comm_b1_13_discussing_environmental_issues"],
    communicativeGoal: "Discuss rural-to-urban migration, aging demographics, and digital consumption patterns in Mongolia.",
    typicalScenarios: ["Sociology conference paper", "Government think-tank round table"],
    keyStructures: ["Хөдөөнөөс хот руу чиглэсэн нүүдэл эрчимжиж байна", "Залуу үеийн үнэт зүйлс өөрчлөгдөж буй нь", "Цахим шилжилтийн үр дүнд"],
    expectedOutcome: "Learner utilizes sociological terminology and explains macro-level societal shifts."
  },
  {
    functionId: "comm_b2_05_business_negotiations_terms",
    title: "Negotiate Business Contracts and Transaction Terms",
    mongolianTitle: "Бизнесийн хэлэлцээ хийх, гэрээний нөхцөл тохиролцох",
    level: "B2",
    domain: "Professional",
    prerequisites: ["comm_b1_09_participating_job_interview"],
    communicativeGoal: "Negotiate payment schedules, intellectual property clauses, delivery milestones, and penalties.",
    typicalScenarios: ["Commercial procurement meeting", "Joint venture partnership talks"],
    keyStructures: ["Төлбөрийн нөхцөлийг уян хатан болгох", "Гэрээний хугацааг сунгах", "Үүргийн гүйцэтгэл хангаагүй тохиолдолд торгууль төлөх"],
    expectedOutcome: "Learner protects organizational interests using standard commercial legal formulations."
  },
  {
    functionId: "comm_b2_06_evaluating_public_policies",
    title: "Evaluate Municipal Public Policies and Infrastructure Plans",
    mongolianTitle: "Төрийн бодлого, нийтийн дэд бүтцийн төслийг үнэлж дүгнэх",
    level: "B2",
    domain: "Academic",
    prerequisites: ["comm_b2_04_analyzing_social_trends"],
    communicativeGoal: "Critique light-rail transit proposals, thermal power upgrades, and ger-district redevelopment plans.",
    typicalScenarios: ["Urban planning consultation", "Television debate show"],
    keyStructures: ["Төсвийн үр ашигтай зарцуулалт", "Урт хугацааны үр дагаврыг тооцоолох", "Дэд бүтцийн шинэчлэл зайлшгүй шаардлагатай"],
    expectedOutcome: "Learner evaluates policy feasibility using cost-benefit and societal impact criteria."
  },
  {
    functionId: "comm_b2_07_delivering_prepared_presentations",
    title: "Deliver Prepared Professional Slide Presentations",
    mongolianTitle: "Бэлтгэсэн илтгэл тавих, танилцуулга хийх",
    level: "B2",
    domain: "Professional",
    prerequisites: ["comm_b2_01_participating_formal_debates"],
    communicativeGoal: "Introduce slide deck, signpost sections, highlight graphical trends, and summarize conclusions.",
    typicalScenarios: ["Corporate annual general meeting", "Academic conference presentation"],
    keyStructures: ["Өнөөдрийн илтгэлээрээ би дараах сэдвийг хөндөх болно", "Дараагийн слайд руу анхаарлаа хандуулна уу", "Дүгнэж хэлэхэд"],
    expectedOutcome: "Learner delivers a coherent 15-minute presentation utilizing professional signposting language."
  },
  {
    functionId: "comm_b2_08_handling_qa_sessions",
    title: "Field and Answer Challenging Audience Questions",
    mongolianTitle: "Илтгэлийн дараах асуултад оновчтой хариулах",
    level: "B2",
    domain: "Academic",
    prerequisites: ["comm_b2_07_delivering_prepared_presentations"],
    communicativeGoal: "Acknowledge insightful questions, request clarification on vague queries, and provide structured responses.",
    typicalScenarios: ["Post-presentation Q&A session", "Press conference briefing"],
    keyStructures: ["Маш сонирхолтой асуулт тавьсанд баярлалаа", "Таны асуултын хувьд би дараах хариултыг өгье", "Хэрэв би зөв ойлгосон бол"],
    expectedOutcome: "Learner maintains poise under probing questions and responds with intellectual precision."
  },
  {
    functionId: "comm_b2_09_moderating_group_discussions",
    title: "Moderate Multi-Participant Panel Discussions",
    mongolianTitle: "Хэлэлцүүлэг удирдах, чиглүүлэх, дүгнэх",
    level: "B2",
    domain: "Professional",
    prerequisites: ["comm_b2_07_delivering_prepared_presentations"],
    communicativeGoal: "Keep time, introduce panelists, intervene to ensure balanced participation, and summarize key takeaways.",
    typicalScenarios: ["Industry panel discussion", "Youth leadership summit workshop"],
    keyStructures: ["Одоо дараагийн зочинд үг өгье", "Цагтаа багтааж хариулна уу", "Хэлэлцүүлгийн гол санааг нэгтгэн дүгнэвэл"],
    expectedOutcome: "Learner steers multi-speaker conversations smoothly without dominating the microphone."
  },
  {
    functionId: "comm_b2_10_drafting_press_releases",
    title: "Draft Organizational Press Releases and Media Advisories",
    mongolianTitle: "Хэвлэлийн мэдээ, албан мэдэгдэл боловсруулах",
    level: "B2",
    domain: "Professional",
    prerequisites: ["comm_b1_10_writing_formal_email_letter"],
    communicativeGoal: "Compose newsworthy statements with eye-catching headlines, dates, quotes from executives, and media contact info.",
    typicalScenarios: ["Announcing a new product launch", "Responding to public inquiries on behalf of an NGO"],
    keyStructures: ["Хэвлэлийн мэдээ: Улаанбаатар хот", "Энэхүү үйл явдал нь салбарын хөгжилд чухал ач холбогдолтой", "Дэлгэрэнгүй мэдээллийг дараах хаягаар авна уу"],
    expectedOutcome: "Learner writes clear journalistic prose tailored for national media distribution."
  },
  {
    functionId: "comm_b2_11_summarizing_complex_articles",
    title: "Synthesize 10-Page Research Reports into Executive Briefs",
    mongolianTitle: "Цогц судалгааны тайланг товчлон хураангуйлах",
    level: "B2",
    domain: "Academic",
    prerequisites: ["comm_b2_02_academic_essay_concessions"],
    communicativeGoal: "Distill methodology, findings, limitations, and recommendations of a long report into a 1-page brief.",
    typicalScenarios: ["Preparing a briefing paper for a minister", "Summarizing international NGO reports"],
    keyStructures: ["Энэхүү тайланд дараах гол асуудлыг тусгажээ", "Судалгааны үр дүнгээс үзвэл", "Бодлогын зөвлөмжүүд"],
    expectedOutcome: "Learner condenses voluminous content without omitting critical factual subtleties."
  },
  {
    functionId: "comm_b2_12_expository_causal_chains",
    title: "Detail Complex Multi-Step Causal Chains (Улмаар, Үүдэн)",
    mongolianTitle: "Олон шатлалт шалтгаан үр дагаврын гинжин хэлхээг тайлбарлах",
    level: "B2",
    domain: "Academic",
    prerequisites: ["comm_b1_05_making_causal_arguments"],
    communicativeGoal: "Trace how a primary event leads to secondary and tertiary consequences through connective markers.",
    typicalScenarios: ["Explaining macroeconomic inflation cascades", "Environmental degradation impact chains"],
    keyStructures: ["Энэ нь эдийн засгийн хямралд хүргэж, улмаар иргэдийн худалдан авах чадвар буурахад нөлөөлөв", "Үүнээс үүдэн"],
    expectedOutcome: "Learner builds coherent paragraph-length causal chains using formal connectives."
  },
  {
    functionId: "comm_b2_13_expressing_proportional_growth",
    title: "Formulate Proportional and Correlative Dynamics (-х тусам)",
    mongolianTitle: "Харилцан хамаарал ба өсөн нэмэгдэх явцыг илэрхийлэх",
    level: "B2",
    domain: "Informational",
    prerequisites: ["comm_b2_12_expository_causal_chains"],
    communicativeGoal: "Express that as one variable increases or changes, another changes in direct proportion ('The more X, the more Y').",
    typicalScenarios: ["Explaining language acquisition curves", "Describing market demand economics"],
    keyStructures: ["Хүн хичээх тусам амжилтад хүрнэ", "Хот томрох тусам замын түгжрэл ихэсдэг", "Унших тусам шинэ зүйл мэднэ"],
    expectedOutcome: "Learner uses the -х тусам construction with fluid intonation and syntactic parallelism."
  },
  {
    functionId: "comm_b2_14_discourse_topic_framing",
    title: "Structure Discourse Framing and Topical Shifts (Бол, Харин, Тухайд)",
    mongolianTitle: "Сэдвийг онцлон зааглах, ярианы чиглэлийг өөрчлөх",
    level: "B2",
    domain: "Interpersonal",
    prerequisites: ["comm_b1_03_expressing_opinions_agreements"],
    communicativeGoal: "Pivot between themes gracefully using topic particles (тухайд, авч үзвэл, харин).",
    typicalScenarios: ["Multi-topic meeting agenda management", "Analytical essay topic transitions"],
    keyStructures: ["Эхний асуудлын тухайд бол", "Харин хоёр дахь асуудлыг авч үзвэл", "Бидний ярьж буй сэдэвт эргэн орвол"],
    expectedOutcome: "Learner signals topic shifts clearly to maintain listener mental mapping."
  },
  {
    functionId: "comm_b2_15_employing_emphatic_nuance",
    title: "Deploy Modal Enclitics for Interpersonal Nuance (Шүү, Даа, Л)",
    mongolianTitle: "Сул үгсээр сэтгэл хөдлөл, итгэл үнэмшлийн өнгө аяс оруулах",
    level: "B2",
    domain: "Interpersonal",
    prerequisites: ["comm_b1_03_expressing_opinions_agreements"],
    communicativeGoal: "Subtly calibrate conviction, intimacy, warning, or gentleness using conversational enclitics.",
    typicalScenarios: ["Warning a peer gently about a deadline", "Reinforcing friendly solidarity"],
    keyStructures: ["Чи заавал ирээрэй шүү", "Тэр ч тийм л дээ", "Би чамд итгэж л байна даа", "Үүнийг л мэдэх хэрэгтэй"],
    expectedOutcome: "Learner attaches modal particles with native-like prosody and emotional attunement."
  },
  {
    functionId: "comm_b2_16_legal_contract_comprehension",
    title: "Interpret Rights, Obligations, and Penalties in Legal Contracts",
    mongolianTitle: "Гэрээний эрх үүрэг, хариуцлагын заалтыг уншиж ойлгох",
    level: "B2",
    domain: "Professional",
    prerequisites: ["comm_b2_05_business_negotiations_terms"],
    communicativeGoal: "Read employment or real estate contracts, identify arbitration terms, force majeure, and breach clauses.",
    typicalScenarios: ["Signing an apartment lease in Ulaanbaatar", "Reviewing a freelance consultancy contract"],
    keyStructures: ["Гэнэтийн болон давагдашгүй хүчин зүйл", "Талуудын хүлээх эрх, үүрэг", "Гэрээ цуцлах нөхцөл", "Маргааныг шийдвэрлэх журам"],
    expectedOutcome: "Learner identifies legal liability commitments and conditional breach penalties."
  },
  {
    functionId: "comm_b2_17_cross_cultural_comparisons",
    title: "Articulate Deep Cross-Cultural and Philosophical Comparisons",
    mongolianTitle: "Соёл хоорондын ялгаа, үнэт зүйлсийг гүнзгий харьцуулах",
    level: "B2",
    domain: "Cultural",
    prerequisites: ["comm_b1_23_comparing_city_country_lifestyles"],
    communicativeGoal: "Contrast nomadic Mongolian conceptions of space, time, and community with Western or East Asian norms.",
    typicalScenarios: ["Anthropological seminar", "Cultural orientation for foreign diplomats"],
    keyStructures: ["Нүүдэлчдийн орон зайг хүртэх мэдрэмж", "Цаг хугацааны талаарх уламжлалт ойлголт", "Байгальтайгаа зохицон амьдрах ухаан"],
    expectedOutcome: "Learner analyzes deep cultural values without falling into stereotypes."
  },
  {
    functionId: "comm_b2_18_critiquing_artistic_exhibitions",
    title: "Critique Contemporary Art, Theater, and Morin Khuur Performances",
    mongolianTitle: "Урлагийн үзэсгэлэн, драмын жүжиг, морин хуурын тоглолтыг шүүмжлэх",
    level: "B2",
    domain: "Cultural",
    prerequisites: ["comm_b1_22_discussing_books_films_reviews"],
    communicativeGoal: "Review a morin khuur concert, throat singing (хөөмий) performance, or modern gallery exhibition.",
    typicalScenarios: ["Arts magazine review", "Cultural blog commentary"],
    keyStructures: ["Уламжлалт болон орчин үеийн хэв маягийг хослуулсан нь", "Морин хуурын аялгуу нь эгшиглэнт тансаг", "Уран зураачийн өвөрмөц илэрхийлэл"],
    expectedOutcome: "Learner writes evocative aesthetic descriptions employing Mongolian arts terminology."
  },
  {
    functionId: "comm_b2_19_conflict_mediation_peers",
    title: "Mediate Interpersonal Disputes and De-escalate Tensions",
    mongolianTitle: "Маргаантай асуудлыг эвлэрүүлэн зохицуулах, уур амьсгалыг зөөллөх",
    level: "B2",
    domain: "Interpersonal",
    prerequisites: ["comm_b1_04_respectful_disagreement"],
    communicativeGoal: "Intervene neutrally between conflicting colleagues, validate both viewpoints, and forge compromise.",
    typicalScenarios: ["Resolving workplace division", "Mediating room disputes in shared housing"],
    keyStructures: ["Хоёр талын байр суурь хоёулаа үндэслэлтэй байна", "Бүгдээрээ тайван ярилцаж дундын шийдэл ольё", "Эв зүйгээ олж ажиллах нь чухал"],
    expectedOutcome: "Learner employs diplomatic de-escalating phrasing to guide constructive compromise."
  },
  {
    functionId: "comm_b2_20_interpreting_graphs_statistics",
    title: "Interpret Quantitative Economic Graphs and Statistical Trends",
    mongolianTitle: "Эдийн засгийн график, статистик тоон үзүүлэлтийг тайлбарлах",
    level: "B2",
    domain: "Professional",
    prerequisites: ["comm_b2_07_delivering_prepared_presentations"],
    communicativeGoal: "Describe bar charts, pie charts, inflation curves, and GDP growth metrics verbally.",
    typicalScenarios: ["Financial analyst briefing", "Economic journalism report"],
    keyStructures: ["Графикаас харахад инфляцын түвшин 8 хувиар өссөн байна", "Үзүүлэлт буурах хандлагатай байна", "Өнгөрсөн онтой харьцуулахад"],
    expectedOutcome: "Learner explains quantitative fluctuations accurately using statistical verbs."
  },
  {
    functionId: "comm_b2_21_academic_abstract_formulation",
    title: "Compose Concise Academic Research Abstracts",
    mongolianTitle: "Эрдэм шинжилгээний өгүүллийн хураангуй бичих",
    level: "B2",
    domain: "Academic",
    prerequisites: ["comm_b2_11_summarizing_complex_articles"],
    communicativeGoal: "Write a 250-word research abstract specifying research background, methodology, empirical findings, and keywords.",
    typicalScenarios: ["Submitting paper to Mongolian National University journal", "Master's thesis defense prep"],
    keyStructures: ["Энэхүү судалгааны зорилго нь ... оршино", "Судалгаанд дараах арга зүйг ашиглав", "Түлхүүр үгс: ..."],
    expectedOutcome: "Learner writes academic abstracts adhering to Mongolian scholarly publication conventions."
  },
  {
    functionId: "comm_b2_22_discussing_historical_events",
    title: "Analyze Major Epochs in Modern Mongolian History",
    mongolianTitle: "Монголын орчин үеийн түүхийн гол үйл явдлуудыг дүн шинжлэх",
    level: "B2",
    domain: "Informational",
    prerequisites: ["comm_b2_03_counterfactual_regrets"],
    communicativeGoal: "Discuss the 1911 National Liberation Revolution, the 1921 People's Revolution, and the 1990 Democratic Transition.",
    typicalScenarios: ["History seminar", "National holiday historical documentary analysis"],
    keyStructures: ["1911 оны үндэсний эрх чөлөөний хувьсгал", "Тусгаар тогтнолоо сэргээн мандуулсан нь", "1990 оны ардчилсан өөрчлөлт шинэчлэлт"],
    expectedOutcome: "Learner articulates historical context, leaders, and ideological shifts accurately."
  },
  {
    functionId: "comm_b2_23_scientific_popular_articles",
    title: "Explain Complex Science and Technology in Layman Terms",
    mongolianTitle: "Шинжлэх ухаан, технологийн ололтыг энгийнээр тайлбарлах",
    level: "B2",
    domain: "Informational",
    prerequisites: ["comm_b2_11_summarizing_complex_articles"],
    communicativeGoal: "Explain solar photovoltaics, renewable energy, artificial intelligence, or genetics to a general audience.",
    typicalScenarios: ["Science communication podcast", "Writing an informative science column"],
    keyStructures: ["Энэхүү технологийн ажиллах зарчим нь", "Энгийнээр тайлбарлавал", "Энэ ололт нь хүн төрөлхтөнд ямар ач тустай вэ гэвэл"],
    expectedOutcome: "Learner bridges technical precision and public intelligibility through apt metaphors."
  },
  {
    functionId: "comm_b2_24_crisis_management_advisories",
    title: "Issue Public Safety Advisories During Natural Disasters (Зуд, Шүүр)",
    mongolianTitle: "Байгалийн гамшиг, зудын үед сэрэмжлүүлэг, зөвлөмж өгөх",
    level: "B2",
    domain: "Professional",
    prerequisites: ["comm_a2_16_seasonal_weather_forecast"],
    communicativeGoal: "Formulate emergency warnings regarding heavy winter dzud, dust storms, or spring forest fires.",
    typicalScenarios: ["National Emergency Management Agency (ОБЕГ) announcement", "Red Cross field coordination"],
    keyStructures: ["Иргэдийг онцын шаардлагагүй бол хөдөө замд гарахгүй байхыг анхааруулж байна", "Бэлэн байдлаа хангах", "Цаг агаарын аюултай үзэгдэл"],
    expectedOutcome: "Learner drafts urgent public bulletins prioritizing life safety and imperative clarity."
  },
  {
    functionId: "comm_b2_25_strategic_consultation",
    title: "Deliver Strategic Consultation and Organizational Recommendations",
    mongolianTitle: "Стратеги төлөвлөлт, байгууллагын зөвлөх үйлчилгээ үзүүлэх",
    level: "B2",
    domain: "Professional",
    prerequisites: ["comm_b2_06_evaluating_public_policies"],
    communicativeGoal: "Advise enterprise executives on restructuring, technological modernization, and long-term risk mitigation.",
    typicalScenarios: ["Board of Directors consultation session", "Executive retreat debrief"],
    keyStructures: ["Байгууллагын дунд болон урт хугацааны стратеги", "Эрсдэлийн удирдлагыг сайжруулах", "Өрсөлдөх чадварыг дээшлүүлэх чиглэлээр"],
    expectedOutcome: "Learner formulates strategic roadmaps with clear risk assessment and milestones."
  }
];
