import { LessonBlueprint } from "./lessonBlueprintTypes";

export const preA1_Units_01_to_03: LessonBlueprint[] = [
  // =========================================================================
  // UNIT 1: Cyrillic Script Recognition & Shared Consonants (unit_pre_a1_01_alphabet_consonants_intro)
  // Target: Prod=8, Rec=3, ProdExp=2, RecExp=1 | Lessons: 4
  // =========================================================================
  {
    lessonId: "les_pre_a1_01_01_shared_consonants_visual",
    unitId: "unit_pre_a1_01_alphabet_consonants_intro",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 1,
    title: "Recognizing Shared Cyrillic Consonants: М, Т, К, О, А",
    lessonType: "orthography",
    primaryPurpose: "Introduce printed capital and lowercase letterforms for shared Cyrillic consonants and cardinal anchor vowels.",
    communicativeOutcome: "Visually identify and match Cyrillic letters М, Т, К, О, and А against identical Latin and international glyphs.",
    objectivesIntroduced: ["obj_pre_a1_01_01_identify_shared_glyphs"],
    objectivesPracticed: [],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: ["phono_cyr_35_alphabet"],
    phonologyPracticed: [],
    phonologyReviewed: [],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_general_education_literacy"],
    previousVocabularyReused: [],
    readingObjective: "Recognize isolated uppercase and lowercase letterforms М, Т, К, О, А across standard serif and sans-serif fonts.",
    listeningObjective: null,
    writingObjective: "Transcribe uppercase and lowercase glyphs М, Т, К, О, А accurately into ruled line guides.",
    spokenProductionObjective: null,
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Recognizing formal written educational signage and instructional symbols.",
    prerequisiteLessonIds: [],
    reviewsLessonIds: [],
    reviewsUnitIds: [],
    reviewReason: null,
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Authentic articulation of isolated Cyrillic consonant phonemes without trailing neutral schwa.",
    successCriteria: [
      "Select correct Cyrillic letter from a distracter set of 4 letters with 100% accuracy.",
      "Pair uppercase and lowercase variants (М-м, Т-т, К-к, О-о, А-а) correctly."
    ],
    masteryEvidence: [
      "Discriminates correctly between visual false friends such as Latin T vs Cyrillic Т.",
      "Accurately transcribes 5 isolated characters on paper or digital canvas."
    ],
    recommendedExerciseModalities: ["matching", "phonetic_discrimination", "typing"]
  },
  {
    lessonId: "les_pre_a1_01_02_false_friend_letters",
    unitId: "unit_pre_a1_01_alphabet_consonants_intro",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 2,
    title: "Navigating Cyrillic False Friends: В, Н, Р, С, Х",
    lessonType: "orthography",
    primaryPurpose: "Differentiate letters that look identical to Latin graphemes but represent distinct Slavic/Mongolian phonemes.",
    communicativeOutcome: "Distinguish and decode misleading letterforms В (/w/~/v/), Н (/n/), Р (/r/), С (/s/), Х (/x/) without phonetic Latin interference.",
    objectivesIntroduced: ["obj_pre_a1_01_02_discriminate_false_friends"],
    objectivesPracticed: ["obj_pre_a1_01_01_identify_shared_glyphs"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_cyr_35_alphabet"],
    phonologyReviewed: [],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 1,
    lexicalDomains: ["lex_domain_general_education_literacy"],
    previousVocabularyReused: [],
    readingObjective: "Read short international loan words (спорт, такси, парк) distinguishing Cyrillic P (/r/) and H (/n/).",
    listeningObjective: "Discriminate sound values of false friends when paired with audio models of native phonemes.",
    writingObjective: "Transcribe 3-5 simple international loan words without substituting Latin phoneme mappings.",
    spokenProductionObjective: null,
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Interpreting urban signage featuring global loanwords.",
    prerequisiteLessonIds: ["les_pre_a1_01_01_shared_consonants_visual"],
    reviewsLessonIds: ["les_pre_a1_01_01_shared_consonants_visual"],
    reviewsUnitIds: [],
    reviewReason: "Anchor newly learned false-friend letters into previously mastered shared consonant templates.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Native pronunciation of initial fricatives and rolled alveolar trill Р (/r/).",
    successCriteria: [
      "Correctly classify В, Н, Р, С, Х by phonetic value rather than Latin value in 10 test items.",
      "Accurately read aloud short loan words containing false friend letters."
    ],
    masteryEvidence: [
      "Reads 'спорт' as /spɔrət/ rather than mistaking 'р' for /p/.",
      "Identifies Cyrillic 'H' as alveolar nasal /n/ in initial and medial positions."
    ],
    recommendedExerciseModalities: ["phonetic_discrimination", "matching", "dictation"]
  },
  {
    lessonId: "les_pre_a1_01_03_simple_syllables_reading",
    unitId: "unit_pre_a1_01_alphabet_consonants_intro",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 3,
    title: "Blending Consonants and Vowels into Simple Syllables (CV and CVC)",
    lessonType: "phonology_introduction",
    primaryPurpose: "Train the blending of shared consonants with cardinal vowels А and О into transparent open and closed syllables.",
    communicativeOutcome: "Pronounce and decode basic monosyllabic and disyllabic letter strings with accurate phonemic boundaries.",
    objectivesIntroduced: ["obj_pre_a1_01_03_blend_cv_syllables"],
    objectivesPracticed: ["obj_pre_a1_01_01_identify_shared_glyphs", "obj_pre_a1_01_02_discriminate_false_friends"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_cyr_35_alphabet"],
    phonologyReviewed: [],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_general_education_literacy"],
    previousVocabularyReused: [],
    readingObjective: "Decode written open (ма, та, са, ха) and closed (ном, сор, тал) monosyllables in printed type.",
    listeningObjective: "Match spoken monosyllables against corresponding written Cyrillic syllable cards.",
    writingObjective: "Write dictated monosyllables and disyllables without omitted vowel characters.",
    spokenProductionObjective: "Articulate open syllables with clear vowel release and non-aspirated voiceless stops.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Responding to teacher phonics prompts in language training contexts.",
    prerequisiteLessonIds: ["les_pre_a1_01_02_false_friend_letters"],
    reviewsLessonIds: ["les_pre_a1_01_01_shared_consonants_visual", "les_pre_a1_01_02_false_friend_letters"],
    reviewsUnitIds: [],
    reviewReason: "Integrate shared consonants and false friends into active syllable decoding.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Phonetically pure syllable audio without synthetic formant warping.",
    successCriteria: [
      "Correctly blend and read 8 out of 8 CV/CVC syllables.",
      "Spell dictated monosyllabic strings with 100% orthographic fidelity."
    ],
    masteryEvidence: [
      "Distinguishes spoken 'сон' vs 'сан' and selects correct written representation.",
      "Vocalizes non-aspirated stops without English-style aspiration burst."
    ],
    recommendedExerciseModalities: ["phonetic_discrimination", "dictation", "word_ordering"]
  },
  {
    lessonId: "les_pre_a1_01_04_cognates_and_signs_decoding",
    unitId: "unit_pre_a1_01_alphabet_consonants_intro",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 4,
    title: "Decoding Real-World Signs and Global Cognates",
    lessonType: "reading_development",
    primaryPurpose: "Apply learned consonants and anchor vowels to decipher authentic public signs, logos, and international cognates.",
    communicativeOutcome: "Read and comprehend high-frequency urban signs (КИНО, ТАКСИ, БАНК, КАССА, АПТЕК) in public environments.",
    objectivesIntroduced: ["obj_pre_a1_01_04_read_public_cognate_signs"],
    objectivesPracticed: ["obj_pre_a1_01_03_blend_cv_syllables"],
    objectivesReviewed: ["obj_pre_a1_01_01_identify_shared_glyphs", "obj_pre_a1_01_02_discriminate_false_friends"],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_cyr_35_alphabet"],
    phonologyReviewed: [],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 0,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_public_spaces_urban_navigation"],
    previousVocabularyReused: [],
    readingObjective: "Scan and decode 5 authentic storefront signs and identify the corresponding service or location.",
    listeningObjective: "Identify spoken place names when matching them with written street signs.",
    writingObjective: "Transcribe 3 city facility names from signage into personal notebook.",
    spokenProductionObjective: "Read storefront titles aloud with appropriate word-level stress.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Navigating municipal transit hubs and commercial facilities.",
    prerequisiteLessonIds: ["les_pre_a1_01_03_simple_syllables_reading"],
    reviewsLessonIds: ["les_pre_a1_01_01_shared_consonants_visual", "les_pre_a1_01_02_false_friend_letters", "les_pre_a1_01_03_simple_syllables_reading"],
    reviewsUnitIds: [],
    reviewReason: "Cumulative capstone application for Unit 1 script decoding.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Authentic urban audio models of store names and public announcements.",
    successCriteria: [
      "Correctly match 5 authentic sign images with their English functional descriptions.",
      "Accurately decode multi-syllable cognates with correct stress placement on the initial syllable."
    ],
    masteryEvidence: [
      "Identifies 'КИНО' as cinema and 'АПТЕК' as pharmacy without hesitation.",
      "Zero Latin-letter phoneme interference when reading words with 'P' and 'C'."
    ],
    recommendedExerciseModalities: ["matching", "reading_comprehension", "short_answer_writing"]
  },

  // =========================================================================
  // UNIT 2: Mongolian-Specific Letters: Ө and Ү (unit_pre_a1_02_mongolian_distinct_letters)
  // Target: Prod=8, Rec=3, ProdExp=2, RecExp=1 | Lessons: 4
  // =========================================================================
  {
    lessonId: "les_pre_a1_02_01_grapheme_recognition_o_u",
    unitId: "unit_pre_a1_02_mongolian_distinct_letters",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 1,
    title: "Identifying Distinctive Mongolian Letters Ө and Ү",
    lessonType: "orthography",
    primaryPurpose: "Introduce the visual letterforms and historical background of the two unique Mongolian Cyrillic characters Ө and Ү.",
    communicativeOutcome: "Recognize Ө and Ү in isolation and within authentic words without confusing them with standard О or У.",
    objectivesIntroduced: ["obj_pre_a1_02_01_identify_distinctive_graphemes"],
    objectivesPracticed: [],
    objectivesReviewed: ["obj_pre_a1_01_01_identify_shared_glyphs"],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: ["phono_mongolian_specific_letters"],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_cyr_35_alphabet"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_general_education_literacy"],
    previousVocabularyReused: [],
    readingObjective: "Distinguish between О vs Ө and У vs Ү in identical typographic environments.",
    listeningObjective: null,
    writingObjective: "Draw the crossbar for capital and lowercase Ө-ө and the straight stem of Ү-ү accurately.",
    spokenProductionObjective: null,
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Correctly reading print and digital Mongolian texts without grapheme confusion.",
    prerequisiteLessonIds: ["les_pre_a1_01_04_cognates_and_signs_decoding"],
    reviewsLessonIds: ["les_pre_a1_01_01_shared_consonants_visual"],
    reviewsUnitIds: ["unit_pre_a1_01_alphabet_consonants_intro"],
    reviewReason: "Contrast new Mongolian letters Ө/Ү against previously mastered basic vowels О/У.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Phonetic articulation of rounded front vowels [ɵ] and [u].",
    successCriteria: [
      "Sort 12 mixed words into groups containing О, Ө, У, and Ү with 100% accuracy.",
      "Accurately write uppercase and lowercase forms on ruled guidelines."
    ],
    masteryEvidence: [
      "Instantly identifies Ө as distinct from О and Russian Э.",
      "Correctly distinguishes Ү from Latin Y and Cyrillic У."
    ],
    recommendedExerciseModalities: ["matching", "categorization", "typing"]
  },
  {
    lessonId: "les_pre_a1_02_02_auditory_discrimination_minimal_pairs",
    unitId: "unit_pre_a1_02_mongolian_distinct_letters",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 2,
    title: "Auditory Discrimination: О vs Ө and У vs Ү",
    lessonType: "phonology_introduction",
    primaryPurpose: "Train the ear to differentiate the open mid-rounded back vowel /ɔ/ from the front-rounded /ɵ/, and /ʊ/ from /u/.",
    communicativeOutcome: "Accurately discern minimal pairs such as ор (bed/place) vs өр (debt), and ус (water) vs үс (hair).",
    objectivesIntroduced: ["obj_pre_a1_02_02_discriminate_vowel_pairs"],
    objectivesPracticed: ["obj_pre_a1_02_01_identify_distinctive_graphemes"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_mongolian_specific_letters"],
    phonologyReviewed: [],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 1,
    lexicalDomains: ["lex_domain_household_home_environment"],
    previousVocabularyReused: [],
    readingObjective: "Match spoken minimal pair audio recordings with the corresponding written word card.",
    listeningObjective: "Identify whether the played vowel sound belongs to the back series (О/У) or front series (Ө/Ү).",
    writingObjective: "Write the correct vowel letter upon hearing isolated minimal pair words.",
    spokenProductionObjective: "Produce the lip rounding and tongue retraction necessary for distinct Ө and Ү sounds.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Avoiding meaning confusion in basic domestic vocabulary.",
    prerequisiteLessonIds: ["les_pre_a1_02_01_grapheme_recognition_o_u"],
    reviewsLessonIds: ["les_pre_a1_02_01_grapheme_recognition_o_u"],
    reviewsUnitIds: [],
    reviewReason: "Connect visual graphemes Ө/Ү to acoustic phonetic boundaries.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Pristine acoustic contrast between Khalkha phonemes /ɔ/, /ɵ/, /ʊ/, /u/.",
    successCriteria: [
      "Score at least 9/10 on an auditory two-alternative forced-choice minimal pair quiz.",
      "Articulate distinct vowel qualities without merging front and back vowels."
    ],
    masteryEvidence: [
      "Selects 'өр' when hearing [ɵr] and 'ор' when hearing [ɔr].",
      "Correctly detects [u] in 'үнэ' vs [ʊ] in 'унш'."
    ],
    recommendedExerciseModalities: ["phonetic_discrimination", "matching", "dictation"]
  },
  {
    lessonId: "les_pre_a1_02_03_high_frequency_core_roots",
    unitId: "unit_pre_a1_02_mongolian_distinct_letters",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 3,
    title: "Reading High-Frequency Words with Ө and Ү: өдөр, өвөл, үнэн, сүү",
    lessonType: "vocabulary_introduction",
    primaryPurpose: "Introduce essential daily vocabulary containing Ө and Ү across common domestic and temporal contexts.",
    communicativeOutcome: "Read and recognize essential everyday words (өдөр 'day', өвөл 'winter', үнэн 'true', сүү 'milk') in print.",
    objectivesIntroduced: ["obj_pre_a1_02_03_read_core_o_u_words"],
    objectivesPracticed: ["obj_pre_a1_02_01_identify_distinctive_graphemes", "obj_pre_a1_02_02_discriminate_vowel_pairs"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_mongolian_specific_letters"],
    phonologyReviewed: [],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_household_home_environment", "lex_domain_food_beverage_dining"],
    previousVocabularyReused: [],
    readingObjective: "Read disyllabic words containing Ө and Ү in environmental food labels and calendar entries.",
    listeningObjective: "Recognize spoken core items (сүү, өдөр) in grocery and daily life contexts.",
    writingObjective: "Type or write 4 core words containing Ө and Ү from memory.",
    spokenProductionObjective: "Pronounce 'өдөр' and 'сүү' with clear initial stress and proper vowel quality.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Identifying staple dairy products and basic temporal units.",
    prerequisiteLessonIds: ["les_pre_a1_02_02_auditory_discrimination_minimal_pairs"],
    reviewsLessonIds: ["les_pre_a1_02_01_grapheme_recognition_o_u", "les_pre_a1_02_02_auditory_discrimination_minimal_pairs"],
    reviewsUnitIds: [],
    reviewReason: "Consolidate phonology through practical lexical items.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Authentic lexical pronunciation with natural Khalkha word stress.",
    successCriteria: [
      "Read 6 printed grocery and daily items accurately with correct vowel values.",
      "Match words to pictorial representations (milk, sun/day, winter) without error."
    ],
    masteryEvidence: [
      "Reads 'сүү' as [su:] with front rounded high vowel rather than back [sʊ:].",
      "Accurately transcribes 'өдөр' without omitting vowel characters."
    ],
    recommendedExerciseModalities: ["matching", "cloze", "typing"]
  },
  {
    lessonId: "les_pre_a1_02_04_reading_place_names_o_u",
    unitId: "unit_pre_a1_02_mongolian_distinct_letters",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 4,
    title: "Decoding Mongolian Geographic and Cultural Names: Өвөрхангай, Сүхбаатар",
    lessonType: "reading_development",
    primaryPurpose: "Decode prominent Mongolian administrative regions, provinces (аймаг), and landmarks featuring Ө and Ү.",
    communicativeOutcome: "Read and pronounce major Mongolian place names, square names, and street signs containing Ө and Ү.",
    objectivesIntroduced: ["obj_pre_a1_02_04_read_proper_toponyms"],
    objectivesPracticed: ["obj_pre_a1_02_03_read_core_o_u_words"],
    objectivesReviewed: ["obj_pre_a1_01_04_read_public_cognate_signs"],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_mongolian_specific_letters"],
    phonologyReviewed: ["phono_cyr_35_alphabet"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 0,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_public_spaces_urban_navigation", "lex_domain_mongolian_geography_landscapes"],
    previousVocabularyReused: [],
    readingObjective: "Read authentic map labels, transit destination displays, and public squares (Сүхбаатар, Өвөрхангай, Төв).",
    listeningObjective: "Identify destination names broadcast on bus transit voice announcements.",
    writingObjective: "Write the names of two major provinces containing Ө or Ү correctly on an outline map.",
    spokenProductionObjective: "State transit destinations clearly when requesting assistance.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Navigating regional bus stations and city transit maps.",
    prerequisiteLessonIds: ["les_pre_a1_02_03_high_frequency_core_roots"],
    reviewsLessonIds: ["les_pre_a1_02_01_grapheme_recognition_o_u", "les_pre_a1_02_02_auditory_discrimination_minimal_pairs", "les_pre_a1_02_03_high_frequency_core_roots"],
    reviewsUnitIds: ["unit_pre_a1_01_alphabet_consonants_intro"],
    reviewReason: "Synthesize Unit 1 consonant recognition with Unit 2 vowel mastery on geographic names.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Native pronunciation of compound place names and province designations.",
    successCriteria: [
      "Correctly read 4 Mongolian province names and match with map locations.",
      "Accurately pronounce 'Сүхбаатар' with front vowels throughout the first syllable."
    ],
    masteryEvidence: [
      "Recognizes 'Төв аймаг' on a highway sign instantly.",
      "Distinguishes 'Өвөрхангай' from 'Архангай' in transit route boards."
    ],
    recommendedExerciseModalities: ["matching", "reading_comprehension", "short_answer_writing"]
  },

  // =========================================================================
  // UNIT 3: The Seven Cardinal Short Vowels (unit_pre_a1_03_cardinal_short_vowels)
  // Target: Prod=8, Rec=3, ProdExp=2, RecExp=1 | Lessons: 5
  // =========================================================================
  {
    lessonId: "les_pre_a1_03_01_vowel_heptad_system",
    unitId: "unit_pre_a1_03_cardinal_short_vowels",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 1,
    title: "The Seven Short Vowels of Mongolian: А, Э, И, О, У, Ө, Ү",
    lessonType: "orthography",
    primaryPurpose: "Present the complete 7-vowel inventory of Modern Khalkha Cyrillic, establishing their systematic acoustic order.",
    communicativeOutcome: "Recite, write, and visually classify the 7 cardinal short vowels in standard linguistic order.",
    objectivesIntroduced: ["obj_pre_a1_03_01_classify_seven_vowels"],
    objectivesPracticed: [],
    objectivesReviewed: ["obj_pre_a1_02_01_identify_distinctive_graphemes"],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: ["phono_vowel_short_seven"],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_mongolian_specific_letters"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_general_education_literacy"],
    previousVocabularyReused: [],
    readingObjective: "Read the seven vowel characters in random order across diverse typographic styles.",
    listeningObjective: null,
    writingObjective: "Transcribe all 7 vowel characters in uppercase and lowercase from memory.",
    spokenProductionObjective: null,
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Following literacy curriculum instructions and orthographic classifications.",
    prerequisiteLessonIds: ["les_pre_a1_02_04_reading_place_names_o_u"],
    reviewsLessonIds: ["les_pre_a1_02_01_grapheme_recognition_o_u"],
    reviewsUnitIds: ["unit_pre_a1_02_mongolian_distinct_letters"],
    reviewReason: "Integrate Ө and Ү into the comprehensive seven-vowel structural matrix.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Sequential pure vowel sounds articulated by native speaker.",
    successCriteria: [
      "Correctly write and label the 7 short vowels without omission.",
      "Identify any missing vowel from a scrambled set of 6 characters."
    ],
    masteryEvidence: [
      "Lists the full series А, Э, И, О, У, Ө, Ү without hesitation.",
      "Categorizes each vowel as standard Cyrillic or Mongolian-distinct."
    ],
    recommendedExerciseModalities: ["matching", "typing", "categorization"]
  },
  {
    lessonId: "les_pre_a1_03_02_articulatory_acoustic_matrix",
    unitId: "unit_pre_a1_03_cardinal_short_vowels",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 2,
    title: "Vowel Articulation: Tongue Height, Backness, and Lip Rounding",
    lessonType: "phonology_introduction",
    primaryPurpose: "Analyze the articulatory mechanics of open vs mid vs closed and rounded vs unrounded vowels.",
    communicativeOutcome: "Articulate each of the 7 short vowels with accurate tongue position and acoustic clarity.",
    objectivesIntroduced: ["obj_pre_a1_03_02_articulate_vowel_matrix"],
    objectivesPracticed: ["obj_pre_a1_03_01_classify_seven_vowels"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_vowel_short_seven"],
    phonologyReviewed: [],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 1,
    lexicalDomains: ["lex_domain_general_education_literacy"],
    previousVocabularyReused: [],
    readingObjective: "Associate schematic tongue-position diagrams with the corresponding Cyrillic vowel symbol.",
    listeningObjective: "Discriminate open [a] vs mid [e] vs closed [i] in minimal auditory clips.",
    writingObjective: "Label vowel charts with appropriate phonetic descriptors.",
    spokenProductionObjective: "Produce short vowel sounds with crisp onset and termination without diphthongal glide.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Engaging in accurate pronunciation drills with language teachers.",
    prerequisiteLessonIds: ["les_pre_a1_03_01_vowel_heptad_system"],
    reviewsLessonIds: ["les_pre_a1_03_01_vowel_heptad_system"],
    reviewsUnitIds: [],
    reviewReason: "Ground vowel symbols into physical articulatory habits.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Contrasting acoustic formants of high, mid, and low vowels.",
    successCriteria: [
      "Discriminate high vs low vowel sounds in 8 out of 8 audio tests.",
      "Maintain lip rounding for О, Ө, У, Ү and unrounded spread lips for А, Э, И."
    ],
    masteryEvidence: [
      "No audible glide when pronouncing short [e] or [a].",
      "Clear differentiation between rounded high [u] and unrounded [i]."
    ],
    recommendedExerciseModalities: ["phonetic_discrimination", "matching", "dictation"]
  },
  {
    lessonId: "les_pre_a1_03_03_vowel_harmony_intro_roots",
    unitId: "unit_pre_a1_03_cardinal_short_vowels",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 3,
    title: "Vowel Resonance in Root Words: Back Roots vs Front Roots",
    lessonType: "grammar_introduction",
    primaryPurpose: "Introduce the intuitive concept that words in Mongolian choose either back/masculine or front/feminine vowel sets.",
    communicativeOutcome: "Identify whether simple disyllabic words have back resonance (а/о/у) or front resonance (э/ө/ү).",
    objectivesIntroduced: ["obj_pre_a1_03_03_identify_vowel_resonance"],
    objectivesPracticed: ["obj_pre_a1_03_01_classify_seven_vowels"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_vowel_short_seven"],
    phonologyReviewed: [],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 0,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_nature_geography_weather", "lex_domain_household_home_environment"],
    previousVocabularyReused: [],
    readingObjective: "Classify 10 basic vocabulary items into Back-Vowel words (гал, ус, нар) vs Front-Vowel words (гэр, өдөр, үнэг).",
    listeningObjective: "Detect the holistic acoustic 'timbre' (dark/back vs bright/front) of spoken root words.",
    writingObjective: "Sort written words into two columns on a worksheet based on vowel harmony class.",
    spokenProductionObjective: "Shadow recorded native words preserving unified resonance throughout both syllables.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Developing phonetic intuition for Mongolian word formation.",
    prerequisiteLessonIds: ["les_pre_a1_03_02_articulatory_acoustic_matrix"],
    reviewsLessonIds: ["les_pre_a1_03_01_vowel_heptad_system"],
    reviewsUnitIds: [],
    reviewReason: "Prepare foundational intuition for formal vowel harmony rules in Unit 10.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Authentic resonance contrasts in disyllabic root words.",
    successCriteria: [
      "Sort 10 words into back vs front categories with 90% accuracy.",
      "Identify the neutral vowel 'И' appearing comfortably in both classes."
    ],
    masteryEvidence: [
      "Recognizes that 'нар' (sun) and 'гэр' (yurt) belong to opposing vowel harmony classes.",
      "Identifies that words do not mix А and Э in native stems."
    ],
    recommendedExerciseModalities: ["categorization", "matching", "phonetic_discrimination"]
  },
  {
    lessonId: "les_pre_a1_03_04_reading_monosyllables_disyllables",
    unitId: "unit_pre_a1_03_cardinal_short_vowels",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 4,
    title: "Decoding Short Vowel Roots: гал, гэр, ус, өвс, нар",
    lessonType: "vocabulary_introduction",
    primaryPurpose: "Build rapid sight-word recognition of elemental natural and domestic monosyllabic nouns.",
    communicativeOutcome: "Read and comprehend foundational monosyllabic words (гал 'fire', гэр 'ger/house', нар 'sun', ус 'water').",
    objectivesIntroduced: ["obj_pre_a1_03_04_read_short_vowel_nouns"],
    objectivesPracticed: ["obj_pre_a1_03_03_identify_vowel_resonance"],
    objectivesReviewed: ["obj_pre_a1_01_03_blend_cv_syllables"],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_vowel_short_seven"],
    phonologyReviewed: ["phono_cyr_35_alphabet"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 1,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_nature_geography_weather", "lex_domain_household_home_environment"],
    previousVocabularyReused: [],
    readingObjective: "Read illustrated environmental flashcards representing core natural elements.",
    listeningObjective: "Match spoken natural nouns with corresponding picture cards.",
    writingObjective: "Write 4 core monosyllabic nouns correctly in Cyrillic.",
    spokenProductionObjective: "Name basic natural elements (sun, water, fire, yurt) when prompted with pictures.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Identifying primary environmental features in rural and urban settings.",
    prerequisiteLessonIds: ["les_pre_a1_03_03_vowel_harmony_intro_roots"],
    reviewsLessonIds: ["les_pre_a1_03_01_vowel_heptad_system", "les_pre_a1_03_03_vowel_harmony_intro_roots"],
    reviewsUnitIds: ["unit_pre_a1_01_alphabet_consonants_intro"],
    reviewReason: "Reinforce consonant-vowel blending with cardinal short vowels.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Clear lexical pronunciation of basic nominal stems.",
    successCriteria: [
      "Read aloud 5 basic nouns with accurate vowel quality.",
      "Spell 'ус', 'гал', 'гэр', 'нар' correctly from audio dictation."
    ],
    masteryEvidence: [
      "Reads 'гэр' with pure short [e] rather than English diphthong.",
      "Matches 'ус' with water and 'гал' with fire immediately."
    ],
    recommendedExerciseModalities: ["matching", "dictation", "typing"]
  },
  {
    lessonId: "les_pre_a1_03_05_acoustic_dictation_assessment",
    unitId: "unit_pre_a1_03_cardinal_short_vowels",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 5,
    title: "Acoustic Discrimination & Dictation Assessment: The 7 Vowels",
    lessonType: "checkpoint",
    primaryPurpose: "Assess auditory identification and written transcription of all 7 cardinal short vowels across diverse consonant frames.",
    communicativeOutcome: "Transcribe any spoken short vowel accurately within monosyllabic and disyllabic words.",
    objectivesIntroduced: [],
    objectivesPracticed: ["obj_pre_a1_03_01_classify_seven_vowels", "obj_pre_a1_03_02_articulate_vowel_matrix", "obj_pre_a1_03_04_read_short_vowel_nouns"],
    objectivesReviewed: ["obj_pre_a1_01_01_identify_shared_glyphs", "obj_pre_a1_02_01_identify_distinctive_graphemes"],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_vowel_short_seven"],
    phonologyReviewed: ["phono_mongolian_specific_letters", "phono_cyr_35_alphabet"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 1,
    newReceptiveLemmaTarget: 0,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_general_education_literacy"],
    previousVocabularyReused: [],
    readingObjective: "Identify intentional vowel spelling errors in a list of 6 simple words.",
    listeningObjective: "Transcribe 10 dictated words focusing on accurate vowel selection.",
    writingObjective: "Write dictated words with 100% accurate vowel representation.",
    spokenProductionObjective: "Read back transcribed words clearly for instructor evaluation.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Completing structured classroom spelling evaluations.",
    prerequisiteLessonIds: ["les_pre_a1_03_04_reading_monosyllables_disyllables"],
    reviewsLessonIds: ["les_pre_a1_03_01_vowel_heptad_system", "les_pre_a1_03_02_articulatory_acoustic_matrix", "les_pre_a1_03_03_vowel_harmony_intro_roots", "les_pre_a1_03_04_reading_monosyllables_disyllables"],
    reviewsUnitIds: ["unit_pre_a1_02_mongolian_distinct_letters", "unit_pre_a1_01_alphabet_consonants_intro"],
    reviewReason: "Unit 3 synthesis checkpoint consolidating cardinal vowel literacy.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Standardized diagnostic audio dictation items.",
    successCriteria: [
      "Achieve at least 90% accuracy on vowel dictation assessment.",
      "Zero confusion between back and front vowel counterparts."
    ],
    masteryEvidence: [
      "Spells 'толгой', 'дэвтэр', 'улс', 'хүүхэд' with correct short vowels in root positions.",
      "Identifies that 'хэн' contains vowel Э and 'хүн' contains Ү."
    ],
    recommendedExerciseModalities: ["dictation", "error_correction", "matching"]
  }
];

export const preA1_Units_04_to_07: LessonBlueprint[] = [
  // =========================================================================
  // UNIT 4: Consonant Inventory: Obstruents & Sonorants (unit_pre_a1_04_consonants_inventory_stops)
  // Target: Prod=8, Rec=3, ProdExp=2, RecExp=1 | Lessons: 5
  // =========================================================================
  {
    lessonId: "les_pre_a1_04_01_plosives_affricates_inventory",
    unitId: "unit_pre_a1_04_consonants_inventory_stops",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 1,
    title: "Obstruents of Mongolian: Б, П, Д, Т, Г, Ц, Ч, З, Ж",
    lessonType: "orthography",
    primaryPurpose: "Introduce the full inventory of Mongolian plosives, affricates, and their written Cyrillic letterforms.",
    communicativeOutcome: "Recognize, name, and transcribe the 9 obstruent consonant characters in printed and written forms.",
    objectivesIntroduced: ["obj_pre_a1_04_01_identify_obstruent_glyphs"],
    objectivesPracticed: [],
    objectivesReviewed: ["obj_pre_a1_01_01_identify_shared_glyphs"],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: ["phono_consonant_basic_inventory"],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_cyr_35_alphabet"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_general_education_literacy"],
    previousVocabularyReused: [],
    readingObjective: "Read isolated consonants Б, П, Д, Т, Г, Ц, Ч, З, Ж across varied typefaces.",
    listeningObjective: null,
    writingObjective: "Write the glyphs Ц, Ч, З, Ж, Д with correct stroke order and distinguishing descenders.",
    spokenProductionObjective: null,
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Following alphabetical classroom chart prompts.",
    prerequisiteLessonIds: ["les_pre_a1_03_05_acoustic_dictation_assessment"],
    reviewsLessonIds: ["les_pre_a1_01_01_shared_consonants_visual"],
    reviewsUnitIds: ["unit_pre_a1_03_cardinal_short_vowels"],
    reviewReason: "Expand initial consonant set into the full obstruent series.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Clear phonetic demonstration of non-aspirated vs aspirated stops.",
    successCriteria: [
      "Distinguish visually between similar glyphs (Ц vs Щ, Ч vs У, З vs Э).",
      "Write all 9 obstruent consonants without visual errors."
    ],
    masteryEvidence: [
      "Does not confuse Ц with Russian Щ.",
      "Identifies that Ч has an open upper-left bowl compared to У."
    ],
    recommendedExerciseModalities: ["matching", "typing", "categorization"]
  },
  {
    lessonId: "les_pre_a1_04_02_aspiration_contrast_stops",
    unitId: "unit_pre_a1_04_consonants_inventory_stops",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 2,
    title: "Aspiration Contrast: Fortis (п, т, к, ц, ч) vs Lenis (б, д, г, з, ж)",
    lessonType: "phonology_introduction",
    primaryPurpose: "Train auditory discrimination and articulatory production of the aspiration contrast characterizing Mongolian obstruents.",
    communicativeOutcome: "Pronounce and differentiate aspirated voiceless stops from unaspirated lax stops without voicing confusion.",
    objectivesIntroduced: ["obj_pre_a1_04_02_discriminate_aspiration_pairs"],
    objectivesPracticed: ["obj_pre_a1_04_01_identify_obstruent_glyphs"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_consonant_basic_inventory"],
    phonologyReviewed: [],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 1,
    lexicalDomains: ["lex_domain_general_education_literacy"],
    previousVocabularyReused: [],
    readingObjective: "Read minimal stop pairs: бар (tiger) vs пар (steam), дас (accustom) vs тас (vulture).",
    listeningObjective: "Identify whether an initial stop is aspirated (fortis) or unaspirated (lenis) in native audio.",
    writingObjective: "Write the correct initial consonant letter based on auditory aspiration cues.",
    spokenProductionObjective: "Produce strong aspiration on Т and П while keeping Д and Б completely unaspirated.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Achieving phonemic accuracy in everyday speech.",
    prerequisiteLessonIds: ["les_pre_a1_04_01_plosives_affricates_inventory"],
    reviewsLessonIds: ["les_pre_a1_04_01_plosives_affricates_inventory"],
    reviewsUnitIds: [],
    reviewReason: "Acoustically ground the written obstruent letterforms.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Precise recording of aspiration burst dynamics in initial stops.",
    successCriteria: [
      "Score 8/10 on an auditory stop-voicing/aspiration discrimination task.",
      "Demonstrate physical aspiration difference using paper-deflection test."
    ],
    masteryEvidence: [
      "Articulates 'та' without voicing and with crisp post-release aspiration.",
      "Articulates 'да' as a voiceless lax lenis stop without English-style voiced lead."
    ],
    recommendedExerciseModalities: ["phonetic_discrimination", "matching", "dictation"]
  },
  {
    lessonId: "les_pre_a1_04_03_nasals_liquids_sonorants",
    unitId: "unit_pre_a1_04_consonants_inventory_stops",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 3,
    title: "Sonorant Consonants: М, Н, Л, Р, В, Й",
    lessonType: "orthography",
    primaryPurpose: "Introduce the sonorant series (nasals, lateral, trill, and approximants) and their positional phonotactics.",
    communicativeOutcome: "Read and pronounce sonorant consonants in initial, medial, and coda positions with natural resonance.",
    objectivesIntroduced: ["obj_pre_a1_04_03_read_sonorants_in_context"],
    objectivesPracticed: ["obj_pre_a1_04_01_identify_obstruent_glyphs"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_consonant_basic_inventory"],
    phonologyReviewed: [],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 1,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_household_home_environment"],
    previousVocabularyReused: [],
    readingObjective: "Read words with complex sonorant codas (мал, зам, үнэн, нар, сар).",
    listeningObjective: "Recognize word-final velar nasal /ŋ/ (written as н) vs alveolar /n/ in spoken Mongolian.",
    writingObjective: "Write 5 sonorant-rich nouns from oral dictation.",
    spokenProductionObjective: "Produce the alveolar trill Р (/r/) in word-final position without American-style retroflex coloring.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Reading domestic livestock and geographic terminology.",
    prerequisiteLessonIds: ["les_pre_a1_04_02_aspiration_contrast_stops"],
    reviewsLessonIds: ["les_pre_a1_04_01_plosives_affricates_inventory"],
    reviewsUnitIds: [],
    reviewReason: "Complete the inventory of consonants in combination with short vowels.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Authentic Khalkha lateral and velar nasal articulation.",
    successCriteria: [
      "Correctly articulate final -л and -р in words like 'сар' (moon) and 'мал' (livestock).",
      "Spell dictated sonorant coda words without errors."
    ],
    masteryEvidence: [
      "Distinguishes between alveolar 'н' and velar 'н' [ŋ] at the end of words.",
      "Reads 'зам' (road) with clear bilabial closure."
    ],
    recommendedExerciseModalities: ["phonetic_discrimination", "matching", "dictation"]
  },
  {
    lessonId: "les_pre_a1_04_04_decoding_street_signs_stems",
    unitId: "unit_pre_a1_04_consonants_inventory_stops",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 4,
    title: "Decoding Street Signs & Basic Nominal Stems: гудамж, зам, буудал",
    lessonType: "reading_development",
    primaryPurpose: "Decode authentic public transit and municipal signs combining newly learned obstruents and sonorants.",
    communicativeOutcome: "Read and understand street signs (гудамж 'street', зам 'road', буудал 'station/stop', цагдаа 'police').",
    objectivesIntroduced: ["obj_pre_a1_04_04_read_street_signs"],
    objectivesPracticed: ["obj_pre_a1_04_01_identify_obstruent_glyphs", "obj_pre_a1_04_03_read_sonorants_in_context"],
    objectivesReviewed: ["obj_pre_a1_01_04_read_public_cognate_signs"],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_consonant_basic_inventory"],
    phonologyReviewed: ["phono_cyr_35_alphabet"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 0,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_public_spaces_urban_navigation"],
    previousVocabularyReused: [],
    readingObjective: "Scan and read 5 authentic Ulaanbaatar street and bus stop nameplates.",
    listeningObjective: "Identify announced bus stop names in recorded onboard transit audio.",
    writingObjective: "Transcribe street addresses and stop names accurately into a travel itinerary.",
    spokenProductionObjective: "State bus stop names with clear consonant articulation when asking for directions.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Navigating urban public transportation and pedestrian intersections.",
    prerequisiteLessonIds: ["les_pre_a1_04_03_nasals_liquids_sonorants"],
    reviewsLessonIds: ["les_pre_a1_04_01_plosives_affricates_inventory", "les_pre_a1_04_02_aspiration_contrast_stops"],
    reviewsUnitIds: ["unit_pre_a1_01_alphabet_consonants_intro"],
    reviewReason: "Apply full consonant inventory to urban civic signage.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Authentic urban transit voice announcements.",
    successCriteria: [
      "Match 5 authentic street/transit signs with their English meanings.",
      "Accurately pronounce 'гудамж' with proper affricate Ж ending."
    ],
    masteryEvidence: [
      "Instantly decodes 'Автобусны буудал' on a bus shelter.",
      "Identifies 'Цагдаа' on an emergency police station sign."
    ],
    recommendedExerciseModalities: ["matching", "reading_comprehension", "short_answer_writing"]
  },
  {
    lessonId: "les_pre_a1_04_05_consonant_inventory_dictation",
    unitId: "unit_pre_a1_04_consonants_inventory_stops",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 5,
    title: "Consonant Inventory Synthesis & Dictation Checkpoint",
    lessonType: "checkpoint",
    primaryPurpose: "Consolidate consonant grapheme-phoneme correspondences through systematic auditory dictation and spelling evaluation.",
    communicativeOutcome: "Spell, read, and discriminate any standard Mongolian consonant sound in root-initial and root-final positions.",
    objectivesIntroduced: [],
    objectivesPracticed: ["obj_pre_a1_04_01_identify_obstruent_glyphs", "obj_pre_a1_04_02_discriminate_aspiration_pairs", "obj_pre_a1_04_03_read_sonorants_in_context"],
    objectivesReviewed: ["obj_pre_a1_03_01_classify_seven_vowels"],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_consonant_basic_inventory"],
    phonologyReviewed: ["phono_cyr_35_alphabet", "phono_vowel_short_seven"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 1,
    newReceptiveLemmaTarget: 0,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_general_education_literacy"],
    previousVocabularyReused: [],
    readingObjective: "Proofread and detect consonant substitution errors in 6 sample words.",
    listeningObjective: "Transcribe 10 spoken words demonstrating the full consonant spectrum.",
    writingObjective: "Write 10 dictated words with zero consonant orthographic errors.",
    spokenProductionObjective: "Read aloud a diagnostic word list containing all obstruents and sonorants.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Demonstrating foundational spelling competence in educational settings.",
    prerequisiteLessonIds: ["les_pre_a1_04_04_decoding_street_signs_stems"],
    reviewsLessonIds: ["les_pre_a1_04_01_plosives_affricates_inventory", "les_pre_a1_04_02_aspiration_contrast_stops", "les_pre_a1_04_03_nasals_liquids_sonorants", "les_pre_a1_04_04_decoding_street_signs_stems"],
    reviewsUnitIds: ["unit_pre_a1_03_cardinal_short_vowels"],
    reviewReason: "Unit 4 synthesis verifying consonant decoding prior to digital keyboard training.",
    audioSuitability: "mongolian_voice_required",
    audioPurpose: "Standardized phonetic assessment recording of consonant stems.",
    successCriteria: [
      "Score at least 90% on consonant spelling dictation.",
      "Demonstrate zero confusion between Д and Т, or Б and П in dictation."
    ],
    masteryEvidence: [
      "Correctly spells 'буудал', 'цаг', 'зам', 'өдөр', 'нөхөр' upon hearing native audio.",
      "Accurately articulates all stops during oral reading verification."
    ],
    recommendedExerciseModalities: ["dictation", "error_correction", "matching"]
  },

  // =========================================================================
  // UNIT 5: Cyrillic Keyboard Mastery & Digital Input (unit_pre_a1_05_cyrillic_keyboard_mastery)
  // Target: Prod=8, Rec=3, ProdExp=2, RecExp=1 | Lessons: 4
  // =========================================================================
  {
    lessonId: "les_pre_a1_05_01_keyboard_layout_home_row",
    unitId: "unit_pre_a1_05_cyrillic_keyboard_mastery",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 1,
    title: "Mongolian Cyrillic Keyboard Layout & The Home Row",
    lessonType: "orthography",
    primaryPurpose: "Introduce the standard Mongolian Cyrillic keyboard layout (MN QWERTY) and key positions on the home row.",
    communicativeOutcome: "Locate and type home-row characters (ф, ц, у, в, а, п, р, о, л, д, ж, э) on a standard keyboard without visual hunting.",
    objectivesIntroduced: ["obj_pre_a1_05_01_locate_home_row_keys"],
    objectivesPracticed: [],
    objectivesReviewed: ["obj_pre_a1_04_01_identify_obstruent_glyphs", "obj_pre_a1_01_01_identify_shared_glyphs"],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_cyr_35_alphabet"],
    phonologyReviewed: [],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_technology_digital_communication"],
    previousVocabularyReused: [],
    readingObjective: "Map visual Cyrillic prompts to corresponding keyboard key coordinates.",
    listeningObjective: null,
    writingObjective: "Type home-row consonant-vowel combinations with accurate finger placement.",
    spokenProductionObjective: null,
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Setting up digital input devices for Mongolian language correspondence.",
    prerequisiteLessonIds: ["les_pre_a1_04_05_consonant_inventory_dictation"],
    reviewsLessonIds: ["les_pre_a1_01_01_shared_consonants_visual", "les_pre_a1_04_01_plosives_affricates_inventory"],
    reviewsUnitIds: ["unit_pre_a1_01_alphabet_consonants_intro"],
    reviewReason: "Transfer letter recognition into active digital touch-typing capabilities.",
    audioSuitability: "standard_speech_synthesis_acceptable",
    audioPurpose: "Pacing audio prompts dictating letters for rhythmic typing drills.",
    successCriteria: [
      "Type a 20-character randomized home-row sequence with 95% accuracy.",
      "Identify the key locations for А, О, Л, and Д without looking at key labels."
    ],
    masteryEvidence: [
      "Operates Mongolian keyboard layout without reverting to system Latin defaults.",
      "Types disyllabic home-row syllables fluently."
    ],
    recommendedExerciseModalities: ["typing", "matching", "dictation"]
  },
  {
    lessonId: "les_pre_a1_05_02_typing_special_keys_o_u",
    unitId: "unit_pre_a1_05_cyrillic_keyboard_mastery",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 2,
    title: "Locating Mongolian Specific Keys: Ө and Ү",
    lessonType: "orthography",
    primaryPurpose: "Train muscle memory for typing the Mongolian-specific keys Ө and Ү, typically mapped to =/+ and -/_ or bracket keys.",
    communicativeOutcome: "Quickly and accurately input Ө and Ү in digital text fields without key-mapping delays.",
    objectivesIntroduced: ["obj_pre_a1_05_02_type_special_vowels"],
    objectivesPracticed: ["obj_pre_a1_05_01_locate_home_row_keys"],
    objectivesReviewed: ["obj_pre_a1_02_01_identify_distinctive_graphemes"],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_cyr_35_alphabet"],
    phonologyReviewed: ["phono_mongolian_specific_letters"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 1,
    lexicalDomains: ["lex_domain_technology_digital_communication"],
    previousVocabularyReused: [],
    readingObjective: "Recognize on-screen feedback when typing Ө and Ү.",
    listeningObjective: null,
    writingObjective: "Type 10 words containing Ө and Ү (өдөр, үнэн, сүү, өвөл) with zero keystroke errors.",
    spokenProductionObjective: null,
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Composing accurate digital messages on mobile and desktop interfaces.",
    prerequisiteLessonIds: ["les_pre_a1_05_01_keyboard_layout_home_row"],
    reviewsLessonIds: ["les_pre_a1_02_01_grapheme_recognition_o_u", "les_pre_a1_05_01_keyboard_layout_home_row"],
    reviewsUnitIds: ["unit_pre_a1_02_mongolian_distinct_letters"],
    reviewReason: "Solve the specific mechanical hurdle of typing the two non-standard Cyrillic keys.",
    audioSuitability: "standard_speech_synthesis_acceptable",
    audioPurpose: "Pacing dictation prompts for typing exercises.",
    successCriteria: [
      "Type words containing Ө and Ү at a speed of at least 15 words per minute.",
      "Input both lowercase (ө, ү) and uppercase (Ө, Ү) forms using Shift correctly."
    ],
    masteryEvidence: [
      "Inputs 'Өвөрхангай' correctly with capital Ө.",
      "Does not mistakenly type О instead of Ө when typing under time constraints."
    ],
    recommendedExerciseModalities: ["typing", "dictation", "error_correction"]
  },
  {
    lessonId: "les_pre_a1_05_03_digital_search_input",
    unitId: "unit_pre_a1_05_cyrillic_keyboard_mastery",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 3,
    title: "Typing Search Queries, Names, and Map Destinations",
    lessonType: "writing",
    primaryPurpose: "Apply digital typing skills to real-world search box queries: searching for hotels, map points, and city facilities.",
    communicativeOutcome: "Type accurate search terms into web search bars, navigation apps, and contacts lists in Mongolian.",
    objectivesIntroduced: ["obj_pre_a1_05_03_type_digital_queries"],
    objectivesPracticed: ["obj_pre_a1_05_01_locate_home_row_keys", "obj_pre_a1_05_02_type_special_vowels"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_cyr_35_alphabet"],
    phonologyReviewed: [],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_technology_digital_communication", "lex_domain_public_spaces_urban_navigation"],
    previousVocabularyReused: [],
    readingObjective: "Read typed queries in simulated mobile app search interfaces.",
    listeningObjective: null,
    writingObjective: "Type 5 landmark search strings (зочид буудал, төв талбай, банк, эмнэлэг) accurately.",
    spokenProductionObjective: null,
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Using smartphone navigation and booking services in Mongolia.",
    prerequisiteLessonIds: ["les_pre_a1_05_02_typing_special_keys_o_u"],
    reviewsLessonIds: ["les_pre_a1_05_01_keyboard_layout_home_row", "les_pre_a1_05_02_typing_special_keys_o_u"],
    reviewsUnitIds: [],
    reviewReason: "Bridge keyboard drills into functional smartphone utility.",
    audioSuitability: "standard_speech_synthesis_acceptable",
    audioPurpose: "Dictation of search queries for audio-to-text typing practice.",
    successCriteria: [
      "Type search queries into search bar simulations with 100% spelling precision.",
      "Input destination names without autocorrect interference."
    ],
    masteryEvidence: [
      "Types 'зочид буудал' (hotel) in under 6 seconds.",
      "Searches for 'төв шуудан' (Central Post Office) with correct vowel spelling."
    ],
    recommendedExerciseModalities: ["typing", "cloze", "short_answer_writing"]
  },
  {
    lessonId: "les_pre_a1_05_04_keyboard_speed_accuracy_evaluation",
    unitId: "unit_pre_a1_05_cyrillic_keyboard_mastery",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 4,
    title: "Cyrillic Keyboard Speed & Accuracy Evaluation",
    lessonType: "checkpoint",
    primaryPurpose: "Evaluate digital typing speed and character accuracy on a 25-word representative text passage.",
    communicativeOutcome: "Type everyday vocabulary and short phrases in Mongolian Cyrillic at a functional baseline speed.",
    objectivesIntroduced: [],
    objectivesPracticed: ["obj_pre_a1_05_01_locate_home_row_keys", "obj_pre_a1_05_02_type_special_vowels", "obj_pre_a1_05_03_type_digital_queries"],
    objectivesReviewed: ["obj_pre_a1_04_01_identify_obstruent_glyphs"],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_cyr_35_alphabet"],
    phonologyReviewed: ["phono_consonant_basic_inventory"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 0,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_technology_digital_communication"],
    previousVocabularyReused: [],
    readingObjective: "Read on-screen text rapidly while transcribing via keyboard.",
    listeningObjective: null,
    writingObjective: "Type a 20-word text passage with at least 95% accuracy and minimum 18 WPM.",
    spokenProductionObjective: null,
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Achieving digital operational autonomy for future course activities.",
    prerequisiteLessonIds: ["les_pre_a1_05_03_digital_search_input"],
    reviewsLessonIds: ["les_pre_a1_05_01_keyboard_layout_home_row", "les_pre_a1_05_02_typing_special_keys_o_u", "les_pre_a1_05_03_digital_search_input"],
    reviewsUnitIds: ["unit_pre_a1_04_consonants_inventory_stops", "unit_pre_a1_01_alphabet_consonants_intro"],
    reviewReason: "Unit 5 capstone ensuring digital input does not bottleneck subsequent learning units.",
    audioSuitability: "standard_speech_synthesis_acceptable",
    audioPurpose: "Audio dictation for blind typing assessment.",
    successCriteria: [
      "Attain typing speed of at least 15 WPM with fewer than 3 errors.",
      "Successfully input digits and punctuation symbols commonly used in Mongolian."
    ],
    masteryEvidence: [
      "Transcribes dictated sentences directly into digital editor without hesitation.",
      "Corrects mistyped characters using backspace instinctively."
    ],
    recommendedExerciseModalities: ["typing", "dictation", "error_correction"]
  },

  // =========================================================================
  // UNIT 6: Digits 0–10 & Basic Classroom Commands (unit_pre_a1_06_digits_and_classroom_prompts)
  // Target: Prod=8, Rec=3, ProdExp=2, RecExp=1 | Lessons: 5
  // =========================================================================
  {
    lessonId: "les_pre_a1_06_01_counting_zero_to_five",
    unitId: "unit_pre_a1_06_digits_and_classroom_prompts",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 1,
    title: "Counting from Zero to Five: тэг, нэг, хоёр, гурав, дөрөв, таван",
    lessonType: "vocabulary_introduction",
    primaryPurpose: "Introduce the spoken pronunciation and written Cyrillic orthography for digits 0 through 5.",
    communicativeOutcome: "Count items, state small quantities, and read digits 0–5 in everyday survival contexts.",
    objectivesIntroduced: ["obj_pre_a1_06_01_count_zero_to_five"],
    objectivesPracticed: [],
    objectivesReviewed: ["obj_pre_a1_05_01_locate_home_row_keys"],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: ["phono_consonant_basic_inventory"],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_cyr_35_alphabet"],
    communicativeFunctionsIntroduced: ["comm_a1_13_numbers_counting_1_to_100"],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_numbers_quantities_measurement"],
    previousVocabularyReused: [],
    readingObjective: "Read the written numeral words (тэг, нэг, хоёр, гурав, дөрөв, тав) and associate them with Arabic numerals (0–5).",
    listeningObjective: "Identify spoken quantities 0–5 in audio clips.",
    writingObjective: "Write the numeral words in Cyrillic alongside their Arabic numerals.",
    spokenProductionObjective: "Count aloud from 0 to 5 with accurate vowel length and consonant clarity.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Specifying item counts in retail purchases and ticket kiosks.",
    prerequisiteLessonIds: ["les_pre_a1_05_04_keyboard_speed_accuracy_evaluation"],
    reviewsLessonIds: ["les_pre_a1_03_01_vowel_heptad_system"],
    reviewsUnitIds: ["unit_pre_a1_05_cyrillic_keyboard_mastery"],
    reviewReason: "Apply newly acquired keyboard and consonant skills to numerical language.",
    audioSuitability: "standard_speech_synthesis_acceptable",
    audioPurpose: "Clear counting audio models with steady tempo.",
    successCriteria: [
      "Correctly pair spoken and written words for 0–5 with numerals.",
      "Accurately pronounce 'хоёр' [xœjr] without phonetic distortion."
    ],
    masteryEvidence: [
      "Counts 0-5 in sequence without hesitation.",
      "Identifies that 'дөрөв' contains the vowel Ө and 'гурав' contains У."
    ],
    recommendedExerciseModalities: ["matching", "phonetic_discrimination", "typing"]
  },
  {
    lessonId: "les_pre_a1_06_02_counting_six_to_ten",
    unitId: "unit_pre_a1_06_digits_and_classroom_prompts",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 2,
    title: "Counting from Six to Ten: зургаа, долоо, найм, ес, арав",
    lessonType: "vocabulary_introduction",
    primaryPurpose: "Introduce the pronunciation and spelling of digits 6 through 10, completing the base ten set.",
    communicativeOutcome: "Count from 1 to 10, quote phone numbers, and express single-digit prices.",
    objectivesIntroduced: ["obj_pre_a1_06_02_count_six_to_ten"],
    objectivesPracticed: ["obj_pre_a1_06_01_count_zero_to_five"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_consonant_basic_inventory"],
    phonologyReviewed: [],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: ["comm_a1_13_numbers_counting_1_to_100"],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 1,
    lexicalDomains: ["lex_domain_numbers_quantities_measurement"],
    previousVocabularyReused: [],
    readingObjective: "Read written numbers 6–10 in price tags and telephone listings.",
    listeningObjective: "Note down spoken digits in simulated phone number sequences.",
    writingObjective: "Transcribe spoken telephone numbers (8 digits) accurately in Arabic numerals.",
    spokenProductionObjective: "Recite an 8-digit mobile number rhythmically (e.g., 9911-2233).",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Exchanging personal mobile telephone numbers.",
    prerequisiteLessonIds: ["les_pre_a1_06_01_counting_zero_to_five"],
    reviewsLessonIds: ["les_pre_a1_06_01_counting_zero_to_five"],
    reviewsUnitIds: [],
    reviewReason: "Integrate upper digits with lower digits to form complete decimal counting.",
    audioSuitability: "standard_speech_synthesis_acceptable",
    audioPurpose: "Authentic recitation of mobile phone number patterns.",
    successCriteria: [
      "Transcribe an 8-digit phone number read at natural speed with 100% accuracy.",
      "Count forward from 1 to 10 and backward from 10 to 1 fluently."
    ],
    masteryEvidence: [
      "Spells 'зургаа' and 'долоо' recognizing double vowels.",
      "Recognizes 'найм' and 'ес' without confusing initial iotated Е."
    ],
    recommendedExerciseModalities: ["dictation", "matching", "role_play_response"]
  },
  {
    lessonId: "les_pre_a1_06_03_classroom_instructions_listen",
    unitId: "unit_pre_a1_06_digits_and_classroom_prompts",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 3,
    title: "Understanding Classroom Prompts: Сонсоорой, Хараарай, Уншаарай",
    lessonType: "listening_development",
    primaryPurpose: "Introduce high-frequency polite imperative classroom and instructional prompts ending in -аарай/-ээрэй.",
    communicativeOutcome: "Respond physically and behaviorally to teacher commands (Сонсоорой 'Listen', Хараарай 'Look', Уншаарай 'Read').",
    objectivesIntroduced: ["obj_pre_a1_06_03_follow_classroom_prompts"],
    objectivesPracticed: [],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_consonant_basic_inventory"],
    phonologyReviewed: [],
    communicativeFunctionsIntroduced: ["comm_a1_34_classroom_instructions"],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 1,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_general_education_literacy"],
    previousVocabularyReused: [],
    readingObjective: "Recognize classroom prompt icons paired with written verbs (Сонс, Хар, Унш, Бич).",
    listeningObjective: "Execute the corresponding physical action upon hearing the spoken command (e.g., pointing to ear for 'Сонсоорой').",
    writingObjective: "Match instructional commands with appropriate textbook exercise sections.",
    spokenProductionObjective: null,
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Functioning smoothly in a formal classroom or online learning session.",
    prerequisiteLessonIds: ["les_pre_a1_06_02_counting_six_to_ten"],
    reviewsLessonIds: ["les_pre_a1_06_01_counting_zero_to_five"],
    reviewsUnitIds: [],
    reviewReason: "Equip learner with auditory comprehension tools for interactive instruction.",
    audioSuitability: "standard_speech_synthesis_acceptable",
    audioPurpose: "Teacher classroom directives with clear polite imperative intonation.",
    successCriteria: [
      "Respond accurately to 5 different spoken classroom commands within 2 seconds.",
      "Differentiate between 'уншаарай' (please read) and 'бичээрэй' (please write)."
    ],
    masteryEvidence: [
      "Opens text immediately upon hearing 'Номоо нээгээрэй'.",
      "Listens quietly upon hearing 'Сонсоорой'."
    ],
    recommendedExerciseModalities: ["matching", "phonetic_discrimination", "categorization"]
  },
  {
    lessonId: "les_pre_a1_06_04_classroom_interaction_say_again",
    unitId: "unit_pre_a1_06_digits_and_classroom_prompts",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 4,
    title: "Essential Classroom Clarification: Дахиад хэлээрэй, Ойлголоо",
    lessonType: "dialogue_work",
    primaryPurpose: "Provide the learner with vital survival phrases to request repetition or signal comprehension in class.",
    communicativeOutcome: "Ask a teacher or interlocutor to repeat ('Дахиад хэлээрэй') and confirm understanding ('Ойлголоо' / 'Ойлгосонгүй').",
    objectivesIntroduced: ["obj_pre_a1_06_04_request_clarification_in_class"],
    objectivesPracticed: ["obj_pre_a1_06_03_follow_classroom_prompts"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_consonant_basic_inventory"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: ["comm_a1_34_classroom_instructions"],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 0,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_general_education_literacy"],
    previousVocabularyReused: [],
    readingObjective: "Read short speech bubbles containing classroom clarification requests.",
    listeningObjective: "Recognize teacher checks such as 'Ойлгосон уу?' in natural classroom dialogue.",
    writingObjective: "Transcribe the phrase 'Дахиад хэлээрэй' into a language survival quick-sheet.",
    spokenProductionObjective: "Politely request repetition using 'Дахиад хэлээрэй' with appropriate rising intonation.",
    registerTarget: "polite_formal",
    pragmaticTarget: "Managing communicative breakdowns gracefully in learning environments.",
    prerequisiteLessonIds: ["les_pre_a1_06_03_classroom_instructions_listen"],
    reviewsLessonIds: ["les_pre_a1_06_03_classroom_instructions_listen"],
    reviewsUnitIds: [],
    reviewReason: "Turn passive listening comprehension into active learner-initiated clarification.",
    audioSuitability: "standard_speech_synthesis_acceptable",
    audioPurpose: "Authentic two-way student-teacher clarification exchanges.",
    successCriteria: [
      "Select and utter appropriate survival phrase when presented with incomprehensible audio.",
      "Appropriately answer 'Ойлголоо' (I understood) or 'Ойлгосонгүй' (I didn't understand)."
    ],
    masteryEvidence: [
      "Spontaneously deploys 'Дахиад хэлээрэй' during live drills when audio is played too fast.",
      "Clear pronunciation of diphthong in 'ойлголоо'."
    ],
    recommendedExerciseModalities: ["dialogue_completion", "role_play_response", "matching"]
  },
  {
    lessonId: "les_pre_a1_06_05_digits_and_prompts_synthesis",
    unitId: "unit_pre_a1_06_digits_and_classroom_prompts",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 5,
    title: "Numbers & Instructional Commands Integration Checkpoint",
    lessonType: "checkpoint",
    primaryPurpose: "Consolidate decimal digits (0–10) and instructional commands through integrated listening, counting, and response tasks.",
    communicativeOutcome: "Follow multi-step classroom numbered instructions and write down numerical values accurately.",
    objectivesIntroduced: [],
    objectivesPracticed: ["obj_pre_a1_06_01_count_zero_to_five", "obj_pre_a1_06_02_count_six_to_ten", "obj_pre_a1_06_03_follow_classroom_prompts", "obj_pre_a1_06_04_request_clarification_in_class"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_consonant_basic_inventory"],
    phonologyReviewed: ["phono_cyr_35_alphabet"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: ["comm_a1_13_numbers_counting_1_to_100", "comm_a1_34_classroom_instructions"],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 1,
    newReceptiveLemmaTarget: 0,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_numbers_quantities_measurement", "lex_domain_general_education_literacy"],
    previousVocabularyReused: [],
    readingObjective: "Read numbered exercise prompts (Жишээ 1: Уншаарай, Жишээ 2: Бичээрэй).",
    listeningObjective: "Follow a sequence of 3 spoken classroom commands incorporating page and exercise numbers.",
    writingObjective: "Write dictated digit lists and complete short instructional cloze prompts.",
    spokenProductionObjective: "State page numbers and counts aloud when prompted.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Demonstrating readiness for structured classroom participation.",
    prerequisiteLessonIds: ["les_pre_a1_06_04_classroom_interaction_say_again"],
    reviewsLessonIds: ["les_pre_a1_06_01_counting_zero_to_five", "les_pre_a1_06_02_counting_six_to_ten", "les_pre_a1_06_03_classroom_instructions_listen", "les_pre_a1_06_04_classroom_interaction_say_again"],
    reviewsUnitIds: ["unit_pre_a1_03_cardinal_short_vowels"],
    reviewReason: "Unit 6 comprehensive synthesis evaluating numerical and classroom fluency.",
    audioSuitability: "standard_speech_synthesis_acceptable",
    audioPurpose: "Classroom simulation audio with numbered instructions.",
    successCriteria: [
      "Achieve 100% accuracy on a 10-item numbers and commands listening test.",
      "Accurately write down numbers 1 through 10 in both digits and words."
    ],
    masteryEvidence: [
      "Navigates to exercise 4 without confusion when hearing 'Дөрөвдүгээр дасгал'.",
      "Accurately writes down a recited telephone number without pausing."
    ],
    recommendedExerciseModalities: ["dictation", "matching", "dialogue_completion"]
  },

  // =========================================================================
  // UNIT 7: Spelling Personal Names & ID Cards (unit_pre_a1_07_personal_names_and_identification)
  // Target: Prod=8, Rec=3, ProdExp=2, RecExp=1 | Lessons: 5
  // =========================================================================
  {
    lessonId: "les_pre_a1_07_01_spelling_common_mongolian_names",
    unitId: "unit_pre_a1_07_personal_names_and_identification",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 1,
    title: "Reading & Spelling Mongolian Given Names: Болд, Бат, Сараа, Энхээ",
    lessonType: "orthography",
    primaryPurpose: "Analyze the orthographic structure of ubiquitous Mongolian personal names and their traditional cultural meanings.",
    communicativeOutcome: "Read, pronounce, and accurately spell common Mongolian personal names in Cyrillic.",
    objectivesIntroduced: ["obj_pre_a1_07_01_spell_mongolian_names"],
    objectivesPracticed: [],
    objectivesReviewed: ["obj_pre_a1_04_01_identify_obstruent_glyphs", "obj_pre_a1_03_01_classify_seven_vowels"],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: ["phono_cyr_35_alphabet"],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_consonant_basic_inventory"],
    communicativeFunctionsIntroduced: ["comm_a1_06_self_introduction_name"],
    communicativeFunctionsPracticed: [],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_personal_information_identity"],
    previousVocabularyReused: [],
    readingObjective: "Read 8 common Mongolian given names on business cards and name tags.",
    listeningObjective: "Discriminate similar names when pronounced in introductions (Бат vs Болд).",
    writingObjective: "Write 4 traditional Mongolian names from memory with correct capitalization.",
    spokenProductionObjective: "Pronounce names with proper initial stress and non-aspirated stop consonants.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Recognizing colleagues and acquaintances by name in Mongolia.",
    prerequisiteLessonIds: ["les_pre_a1_06_05_digits_and_prompts_synthesis"],
    reviewsLessonIds: ["les_pre_a1_01_01_shared_consonants_visual", "les_pre_a1_02_01_grapheme_recognition_o_u"],
    reviewsUnitIds: ["unit_pre_a1_01_alphabet_consonants_intro", "unit_pre_a1_02_mongolian_distinct_letters"],
    reviewReason: "Apply script mastery to culturally authentic personal naming conventions.",
    audioSuitability: "standard_speech_synthesis_acceptable",
    audioPurpose: "Authentic pronunciation of common Mongolian given names.",
    successCriteria: [
      "Correctly read and spell 6 common names without orthographic errors.",
      "Identify the auspicious root meanings (бат = firm, болд = steel, энх = peace)."
    ],
    masteryEvidence: [
      "Spells 'Бат-Эрдэнэ' with correct hyphenation and capitalization.",
      "Reads 'Сарангэрэл' without stumbling over compound stem transition."
    ],
    recommendedExerciseModalities: ["matching", "typing", "dictation"]
  },
  {
    lessonId: "les_pre_a1_07_02_transliterating_foreign_names",
    unitId: "unit_pre_a1_07_personal_names_and_identification",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 2,
    title: "Transliterating Your Own Name into Mongolian Cyrillic",
    lessonType: "writing",
    primaryPurpose: "Teach the systematic conventions for transliterating international non-Mongolian personal names into Cyrillic script.",
    communicativeOutcome: "Write one's own full name, nationality, and home city in accurate Mongolian Cyrillic characters.",
    objectivesIntroduced: ["obj_pre_a1_07_02_transliterate_foreign_name"],
    objectivesPracticed: ["obj_pre_a1_07_01_spell_mongolian_names"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_cyr_35_alphabet"],
    phonologyReviewed: [],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: ["comm_a1_06_self_introduction_name"],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 1,
    lexicalDomains: ["lex_domain_personal_information_identity"],
    previousVocabularyReused: [],
    readingObjective: "Read international personal names transliterated into Cyrillic in official hotel manifests.",
    listeningObjective: "Recognize how international names sound when pronounced through Mongolian phonotactics.",
    writingObjective: "Transliterate own given name and surname into Mongolian Cyrillic with appropriate vowel adaptations.",
    spokenProductionObjective: "Spell out one's name letter by letter using Cyrillic letter names.",
    registerTarget: "neutral_instructional",
    pragmaticTarget: "Registering at hotels, border checkpoints, and conferences in Mongolia.",
    prerequisiteLessonIds: ["les_pre_a1_07_01_spelling_common_mongolian_names"],
    reviewsLessonIds: ["les_pre_a1_07_01_spelling_common_mongolian_names"],
    reviewsUnitIds: [],
    reviewReason: "Transfer name-spelling mechanics to the learner's own identity.",
    audioSuitability: "standard_speech_synthesis_acceptable",
    audioPurpose: "Phonetic demonstration of Cyrillic letter names during oral spelling.",
    successCriteria: [
      "Produce a phonetically sound Cyrillic transliteration of personal name.",
      "Orally spell personal name in Cyrillic letter names without hesitation."
    ],
    masteryEvidence: [
      "Transliterates 'David' as 'Дэвид' or 'Michael' as 'Майкл' accurately.",
      "Spells name aloud over phone simulation without relying on Latin alphabet names."
    ],
    recommendedExerciseModalities: ["short_answer_writing", "typing", "phonetic_discrimination"]
  },
  {
    lessonId: "les_pre_a1_07_03_reading_id_cards_registration",
    unitId: "unit_pre_a1_07_personal_names_and_identification",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 3,
    title: "Decoding Mongolian National ID Cards (Иргэний үнэмлэх) & Badges",
    lessonType: "reading_development",
    primaryPurpose: "Decode layout, standard field headers, and abbreviations found on Mongolian ID cards and conference name badges.",
    communicativeOutcome: "Read and extract surname, given name, birth date, and registration number from a sample identity document.",
    objectivesIntroduced: ["obj_pre_a1_07_03_decode_id_card_fields"],
    objectivesPracticed: ["obj_pre_a1_07_01_spell_mongolian_names"],
    objectivesReviewed: ["obj_pre_a1_06_01_count_zero_to_five", "obj_pre_a1_06_02_count_six_to_ten"],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_cyr_35_alphabet"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: ["comm_a1_06_self_introduction_name"],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 1,
    newReceptiveLemmaTarget: 1,
    newProductiveExpressionTarget: 1,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_personal_information_identity", "lex_domain_public_administration_civic_life"],
    previousVocabularyReused: [],
    readingObjective: "Scan simulated identity card documents for essential fields: Овог (Clan name), Эцгийн нэр (Patronymic), Нэр (Given name), Регистрийн дугаар (Registration number).",
    listeningObjective: null,
    writingObjective: "Copy identity fields from a sample ID card onto a verification slip.",
    spokenProductionObjective: null,
    registerTarget: "formal_administrative",
    pragmaticTarget: "Navigating immigration registration and bank account opening procedures.",
    prerequisiteLessonIds: ["les_pre_a1_07_02_transliterating_foreign_names"],
    reviewsLessonIds: ["les_pre_a1_06_01_counting_zero_to_five", "les_pre_a1_06_02_counting_six_to_ten"],
    reviewsUnitIds: ["unit_pre_a1_06_digits_and_classroom_prompts"],
    reviewReason: "Integrate digit decoding with nominal identity card fields.",
    audioSuitability: "standard_speech_synthesis_acceptable",
    audioPurpose: "Recitation of official identity verification dialogs.",
    successCriteria: [
      "Extract the person's given name vs patronymic from an ID card layout with 100% accuracy.",
      "Identify the 2-letter Cyrillic prefix of a registration number."
    ],
    masteryEvidence: [
      "Differentiates between 'Овог' and 'Нэр' on standard government forms.",
      "Reads birth date encoded in Mongolian registration numbers."
    ],
    recommendedExerciseModalities: ["reading_comprehension", "matching", "cloze"]
  },
  {
    lessonId: "les_pre_a1_07_04_filling_hotel_registration_form",
    unitId: "unit_pre_a1_07_personal_names_and_identification",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 4,
    title: "Filling Out a Simple Hotel Registration Card",
    lessonType: "writing",
    primaryPurpose: "Guide the learner in filling out essential personal information fields on a hotel guest registration form.",
    communicativeOutcome: "Complete a paper or digital hotel registration card with name, nationality, phone number, and passport data.",
    objectivesIntroduced: ["obj_pre_a1_07_04_fill_hotel_form"],
    objectivesPracticed: ["obj_pre_a1_07_02_transliterate_foreign_name", "obj_pre_a1_07_03_decode_id_card_fields"],
    objectivesReviewed: [],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: [],
    phonologyReviewed: ["phono_cyr_35_alphabet"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: ["comm_a1_06_self_introduction_name"],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 2,
    newReceptiveLemmaTarget: 0,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_personal_information_identity", "lex_domain_travel_tourism_hospitality"],
    previousVocabularyReused: [],
    readingObjective: "Read form field labels: Нэр (Name), Утас (Phone), Иргэншил (Citizenship), Өрөө (Room).",
    listeningObjective: null,
    writingObjective: "Fill out all 6 required fields of a hotel check-in voucher accurately in Cyrillic.",
    spokenProductionObjective: null,
    registerTarget: "formal_administrative",
    pragmaticTarget: "Checking in at hotels and guesthouses independently.",
    prerequisiteLessonIds: ["les_pre_a1_07_03_reading_id_cards_registration"],
    reviewsLessonIds: ["les_pre_a1_07_02_transliterating_foreign_names", "les_pre_a1_07_03_reading_id_cards_registration"],
    reviewsUnitIds: [],
    reviewReason: "Synthesize personal name spelling and registration vocabulary in practical document completion.",
    audioSuitability: "standard_speech_synthesis_acceptable",
    audioPurpose: "Desk clerk instructions during registration check-in.",
    successCriteria: [
      "Complete all form fields without using Latin characters for name or citizenship.",
      "Input valid Mongolian contact phone number format."
    ],
    masteryEvidence: [
      "Correctly fills 'Иргэншил' with appropriate country name in Cyrillic.",
      "Labels room number correctly."
    ],
    recommendedExerciseModalities: ["cloze", "short_answer_writing", "matching"]
  },
  {
    lessonId: "les_pre_a1_07_05_personal_identification_synthesis",
    unitId: "unit_pre_a1_07_personal_names_and_identification",
    cefrLevel: "Pre-A1",
    sequenceWithinUnit: 5,
    title: "Personal Identification & Name Spelling Capstone",
    lessonType: "checkpoint",
    primaryPurpose: "Consolidate personal identification literacy through integrated reading, spelling, and form-completion tasks.",
    communicativeOutcome: "Orally state and spell one's name, read another's business card, and verify personal registration data.",
    objectivesIntroduced: [],
    objectivesPracticed: ["obj_pre_a1_07_01_spell_mongolian_names", "obj_pre_a1_07_02_transliterate_foreign_name", "obj_pre_a1_07_03_decode_id_card_fields", "obj_pre_a1_07_04_fill_hotel_form"],
    objectivesReviewed: ["obj_pre_a1_06_01_count_zero_to_five"],
    grammarIntroduced: [],
    grammarPracticed: [],
    grammarReviewed: [],
    phonologyIntroduced: [],
    phonologyPracticed: ["phono_cyr_35_alphabet"],
    phonologyReviewed: ["phono_consonant_basic_inventory"],
    communicativeFunctionsIntroduced: [],
    communicativeFunctionsPracticed: ["comm_a1_06_self_introduction_name"],
    communicativeFunctionsReviewed: [],
    newProductiveLemmaTarget: 1,
    newReceptiveLemmaTarget: 0,
    newProductiveExpressionTarget: 0,
    newReceptiveExpressionTarget: 0,
    lexicalDomains: ["lex_domain_personal_information_identity"],
    previousVocabularyReused: [],
    readingObjective: "Read a business card and state the person's full name, organization, and phone number.",
    listeningObjective: "Transcribe a stranger's name accurately as spelled out letter-by-letter over audio.",
    writingObjective: "Produce an accurate personal identity index card in Cyrillic.",
    spokenProductionObjective: "State full name clearly and spell it aloud using Cyrillic letter names.",
    registerTarget: "formal_administrative",
    pragmaticTarget: "Handling official introductions and identification checks with confidence.",
    prerequisiteLessonIds: ["les_pre_a1_07_04_filling_hotel_registration_form"],
    reviewsLessonIds: ["les_pre_a1_07_01_spelling_common_mongolian_names", "les_pre_a1_07_02_transliterating_foreign_names", "les_pre_a1_07_03_reading_id_cards_registration", "les_pre_a1_07_04_filling_hotel_registration_form"],
    reviewsUnitIds: ["unit_pre_a1_01_alphabet_consonants_intro", "unit_pre_a1_02_mongolian_distinct_letters"],
    reviewReason: "Unit 7 synthesis checkpoint completing Section 1 literacy foundation.",
    audioSuitability: "standard_speech_synthesis_acceptable",
    audioPurpose: "Authentic receptionist-client name verification dialogue.",
    successCriteria: [
      "Achieve 100% accuracy on personal name spelling and registration decoding.",
      "Accurately read and transcribe telephone number from audio."
    ],
    masteryEvidence: [
      "Successfully writes out personal bio card containing name, nationality, and contact number.",
      "Spells name aloud in Cyrillic without prompting."
    ],
    recommendedExerciseModalities: ["short_answer_writing", "dictation", "role_play_response"]
  }
];
