"""
Section 2 Generator Part 2 (Units 77 - 79): 15 Lessons
77: Third-Person Possessive Enclitic 'нь' (5 lessons)
78: Comparative & Superlative: Хамгийн, Илүү (4 lessons)
79: Conditional Converb -вал/-вэл in Bargaining (6 lessons)
"""

import json
from typing import List, Dict, Any

def get_sec02_part2_lessons(u_map: Dict[int, Any]) -> List[Dict[str, Any]]:
    lessons: List[Dict[str, Any]] = []

    # =========================================================================
    # UNIT 77: Third-Person Possessive Enclitic 'нь': Topic & Possession (pos 77)
    # 5 Lessons | Targets: ProdLem=21, RecLem=10, ProdExp=5, RecExp=3
    # Budget: (5,2,1,1), (6,3,1,1), (5,3,2,1), (0,0,0,0), (5,2,1,0) = (21, 10, 5, 3)
    # =========================================================================
    u = u_map[77]
    uid = u["unitId"]
    lessons.extend([
        {
            "lessonId": "les_a2_77_01_possessive_enclitic_ni_intro",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 1,
            "title": "Its Price & Its Quality: The Third-Person Enclitic 'нь'",
            "lessonType": "grammar_introduction",
            "primaryPurpose": "Introduce the unstressed third-person possessive enclitic particle 'нь' marking third-person possession ('its/his/her/their') and functioning as an informational topic marker.",
            "communicativeOutcome": "Describe attributes of products and places using 'нь' (e.g. 'Үнэ нь боломжийн, чанар нь сайн', 'Өнгө нь гоё юм').",
            "objectivesIntroduced": ["obj_a2_77_01_enclitic_ni_marking"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_a2_76_01_reflexive_case_combination"],
            "grammarIntroduced": ["gram_a2_possessive_third_person_enclitic_ni"],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_genitive_possession", "gram_a1_predicate_adjective_nominal"],
            "phonologyIntroduced": ["phono_a2_enclitic_cliticization_prosody"],
            "phonologyPracticed": ["phono_a1_nasal_vowels"], "phonologyReviewed": ["phono_a1_vowel_reduction_non_initial"],
            "communicativeFunctionsIntroduced": ["comm_a2_24_superlative_best_in_town"],
            "communicativeFunctionsPracticed": ["comm_a2_23_comparing_items_places"], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_commerce_transactions", "lex_domain_evaluative_descriptions"],
            "previousVocabularyReused": ["үнэ", "чанар", "өнгө", "хэмжээ", "сайн", "муу"],
            "readingObjective": "Read consumer reviews highlighting product attributes marked with the enclitic 'нь'.",
            "listeningObjective": "Identify 'нь' functioning as a topic marker in product reviews and retail advice.",
            "writingObjective": "Write 3 sentences evaluating products using 'X нь Y' topic-comment structure.",
            "spokenProductionObjective": "Evaluate an item: 'Энэ цамцны өнгө нь гоё боловч, үнэ нь арай өндөр байна'.",
            "registerTarget": "Everyday evaluative retail register",
            "pragmaticTarget": "Using 'нь' to soften statements and present topic-comment evaluations naturally.",
            "prerequisiteLessonIds": ["les_a2_76_01_reflexive_case_morphology_overview"],
            "reviewsLessonIds": ["les_a1_29_01_genitive_possession_intro"],
            "reviewsUnitIds": ["unit_a1_29_genitive_possession_relational_suff"],
            "reviewReason": "Expands nominal possession from genitive case into third-person enclitic topic marking.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Model prosodic integration of clitic 'нь' without vowel elongation.",
            "successCriteria": [
                "Places 'нь' correctly following nominal head without attaching it as a bound suffix",
                "Constructs well-formed topic-comment evaluations of products"
            ],
            "masteryEvidence": "Produces 'Энэ дэлгүүрийн бараа нь чанартай боловч үнэ нь үнэтэй' correctly.",
            "recommendedExerciseModalities": ["sentence_construction", "contextual_cloze", "error_correction"]
        },
        {
            "lessonId": "les_a2_77_02_evaluating_specs_features_lexicon",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 2,
            "title": "Specs & Features: Weight, Durability & Origin",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Introduce technical and practical product evaluation vocabulary (хөнгөн, бат бөх, эдэлгээ, загвар, гарал үүсэл) commonly paired with the topic marker 'нь'.",
            "communicativeOutcome": "Evaluate consumer goods across multiple dimensions (weight, durability, design, brand reputation).",
            "objectivesIntroduced": ["obj_a2_77_02_product_spec_lexicon"],
            "objectivesPracticed": ["obj_a2_77_01_enclitic_ni_marking"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_possessive_third_person_enclitic_ni"],
            "grammarReviewed": ["gram_a1_predicate_adjective_nominal", "gram_a1_existential_baina_baihgui"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_consonant_clusters"], "phonologyReviewed": ["phono_a1_vowel_reduction_non_initial"],
            "communicativeFunctionsIntroduced": ["comm_a2_24_superlative_best_in_town"],
            "communicativeFunctionsPracticed": ["comm_a2_23_comparing_items_places"], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_commerce_transactions", "lex_domain_technology_devices"],
            "previousVocabularyReused": ["жин", "хүнд", "хөнгөн", "шинэ", "хуучин", "бараа"],
            "readingObjective": "Read technical spec sheets for electronics and home appliances comparing dimensions and power.",
            "listeningObjective": "Understand salesperson explaining product durability and warranty coverage.",
            "writingObjective": "List 5 key evaluation criteria for purchasing a smartphone or winter boots.",
            "spokenProductionObjective": "Compare two items: 'Энэ гуталны эдэлгээ нь сайн, жин нь их хөнгөн юм байна'.",
            "registerTarget": "Informed consumer and sales consultation register",
            "pragmaticTarget": "Balancing positive and negative features constructively before buying.",
            "prerequisiteLessonIds": ["les_a2_77_01_possessive_enclitic_ni_intro"],
            "reviewsLessonIds": ["les_a1_21_01_attributive_adjectives_intro"],
            "reviewsUnitIds": ["unit_a1_21_attributive_predicative_adjective"],
            "reviewReason": "Expands basic physical adjectives to technical performance criteria.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Pronounce technical product specifications clearly.",
            "successCriteria": [
                "Accurately defines эдэлгээ (durability), загвар (design/model), бат бөх (sturdy), гарал үүсэл (origin)",
                "Forms comparative evaluations using 'нь' naturally"
            ],
            "masteryEvidence": "Accurately analyzes 4 consumer items across 3 separate quality dimensions.",
            "recommendedExerciseModalities": ["categorization", "contextual_cloze", "matching"]
        },
        {
            "lessonId": "les_a2_77_03_shopper_critique_audio_lab",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 3,
            "title": "Acoustic Lab: Shopper Critiques & Honest Reviews",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop acoustic listening comprehension of authentic colloquial shopper discussions comparing alternative brands and weighing pros and cons.",
            "communicativeOutcome": "Extract which features are praised and which are criticized by shoppers discussing purchases in an electronics or clothing store.",
            "objectivesIntroduced": ["obj_a2_77_03_decode_shopper_critiques"],
            "objectivesPracticed": ["obj_a2_77_01_enclitic_ni_marking", "obj_a2_77_02_product_spec_lexicon"],
            "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_ablative_comparative", "gram_a1_converb_coordinating_j_ch"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_vowel_reduction_non_initial"], "phonologyReviewed": ["phono_a1_nasal_vowels"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_24_superlative_best_in_town", "comm_a2_23_comparing_items_places"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_commerce_transactions"],
            "previousVocabularyReused": ["үнэ", "дэлгүүр", "сонгох", "авах", "дуртай", "бодол"],
            "readingObjective": "",
            "listeningObjective": "Identify specific features praised ('дуу нь сайн') vs faulted ('батарей нь муу') across 4 shopper dialogue audio clips.",
            "writingObjective": "",
            "spokenProductionObjective": "Summarize shoppers' consensus on the best purchase option.",
            "registerTarget": "Spontaneous colloquial consumer conversation register",
            "pragmaticTarget": "Distinguishing genuine consumer feedback from paid promotional talk.",
            "prerequisiteLessonIds": ["les_a2_77_02_evaluating_specs_features_lexicon"],
            "reviewsLessonIds": ["les_a1_52_03_listening_market_vendors"],
            "reviewsUnitIds": ["unit_a1_52_open_market_grocery_shopping_bulk_q"],
            "reviewReason": "Sharpening consumer listening acuity in multi-speaker retail environments.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Multi-speaker dialogue between two friends deliberating between two laptop models in a store.",
            "successCriteria": [
                "Identifies which of 2 products is selected by the speakers and why",
                "Extracts specific complaints regarding price, battery, or build quality"
            ],
            "masteryEvidence": "Completes product comparison balance sheet accurately based on 90 seconds of dialogue.",
            "recommendedExerciseModalities": ["listening_comprehension", "phonetic_discrimination", "categorization"]
        },
        {
            "lessonId": "les_a2_77_04_product_consultation_dialogue",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 4,
            "title": "Store Consultation: Asking About Origin, Warranty & Performance",
            "lessonType": "dialogue_work",
            "primaryPurpose": "Develop spoken communicative fluency for consulting with store specialists, asking about warranty terms (баталгаат хугацаа), origin, and accessories.",
            "communicativeOutcome": "Conduct a product consultation with a retail specialist: ask about warranty duration, where the product was made, and whether spare parts are available.",
            "objectivesIntroduced": ["obj_a2_77_04_product_consultation_dialogue"],
            "objectivesPracticed": ["obj_a2_77_01_enclitic_ni_marking", "obj_a2_77_02_product_spec_lexicon"],
            "objectivesReviewed": ["obj_a1_19_01_polar_questions"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_possessive_third_person_enclitic_ni"],
            "grammarReviewed": ["gram_a1_polar_questions_uu_uu", "gram_a1_case_ablative_origin"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_intonation_polite"], "phonologyReviewed": ["phono_a1_vowel_length_distinction"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_24_superlative_best_in_town", "comm_a1_22_making_purchases"],
            "communicativeFunctionsReviewed": ["comm_a1_16_greetings_time_of_day"],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_commerce_transactions", "lex_domain_technology_devices"],
            "previousVocabularyReused": ["баталгаа", "хугацаа", "хаана", "үйлдвэрлэх", "сэлбэг", "асуух"],
            "readingObjective": "",
            "listeningObjective": "Understand specialist explaining warranty terms: 'Баталгаат хугацаа нь нэг жил, гэхдээ засвар нь үнэгүй'.",
            "writingObjective": "",
            "spokenProductionObjective": "Ask specialist: 'Энэ төхөөрөмжийн баталгаа нь хэдэн сар байдаг вэ? Сэлбэг нь олдоцтой юу?'.",
            "registerTarget": "Courteous informative customer-specialist register",
            "pragmaticTarget": "Inquiring about after-sales support before paying for expensive consumer durables.",
            "prerequisiteLessonIds": ["les_a2_77_02_evaluating_specs_features_lexicon", "les_a2_77_03_shopper_critique_audio_lab"],
            "reviewsLessonIds": ["les_a1_19_01_polar_questions_intro"],
            "reviewsUnitIds": ["unit_a1_19_polar_inquiries_polar_question_part"],
            "reviewReason": "Spirals polar question syntax (уу/үү, юу/юү) into technical retail queries.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Provide authentic customer-specialist dialogue in an electronics retailer.",
            "successCriteria": [
                "Asks about warranty, origin, and maintenance using 'нь' topic structures",
                "Understands technical explanation of product limitations and strengths"
            ],
            "masteryEvidence": "Completes full simulated consultation asking 3 distinct technical feature questions.",
            "recommendedExerciseModalities": ["role-play response", "dialogue_completion", "listening_comprehension"]
        },
        {
            "lessonId": "les_a2_77_05_comparative_product_review_writing",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 5,
            "title": "Tech Review: Writing a Feature-by-Feature Product Comparison",
            "lessonType": "grammar_guided_practice",
            "primaryPurpose": "Synthesize the third-person possessive enclitic 'нь', comparative vocabulary, and evaluative adjectives into a written product review.",
            "communicativeOutcome": "Write a 5-sentence comparative review contrasting two electronic devices or appliances on performance, price, and battery life.",
            "objectivesIntroduced": ["obj_a2_77_05_write_product_comparison"],
            "objectivesPracticed": ["obj_a2_77_01_enclitic_ni_marking", "obj_a2_77_04_product_consultation_dialogue"],
            "objectivesReviewed": ["obj_a1_40_01_ablative_comparative"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_possessive_third_person_enclitic_ni"],
            "grammarReviewed": ["gram_a1_case_ablative_comparative", "gram_a1_predicate_adjective_nominal"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_24_superlative_best_in_town", "comm_a2_23_comparing_items_places"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_commerce_transactions", "lex_domain_technology_devices"],
            "previousVocabularyReused": ["үнэ", "хүчин чадал", "жижиг", "том", "сайн", "дүгнэлт"],
            "readingObjective": "Read professional gadget reviews comparing battery benchmarks and screen resolutions.",
            "listeningObjective": "",
            "writingObjective": "Draft a 5-sentence written comparative review utilizing 'нь' in every sentence.",
            "spokenProductionObjective": "",
            "registerTarget": "Public analytical consumer review register",
            "pragmaticTarget": "Clear structured prose contrasting multiple specs systematically.",
            "prerequisiteLessonIds": ["les_a2_77_04_product_consultation_dialogue"],
            "reviewsLessonIds": ["les_a1_40_01_ablative_origin_intro"],
            "reviewsUnitIds": ["unit_a1_40_ablative_of_spatial_temporal_origin"],
            "reviewReason": "Combines comparative ablative (-аас) with 'нь' topic marker: 'Түүнээс үнэ нь хямд'.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Audio read-back of written comparative review.",
            "successCriteria": [
                "Produces written review comparing at least 2 distinct attributes using 'нь'",
                "Correctly spells specialized technical terms: баталгаа, хүчин чадал, батарей"
            ],
            "masteryEvidence": "Drafts 'Энэ утасны дэлгэц нь тод, батарей нь удаан барьдаг боловч үнэ нь арай өндөр байна' correctly.",
            "recommendedExerciseModalities": ["short-answer writing", "sentence construction", "error correction"]
        }
    ])

    # =========================================================================
    # UNIT 78: Comparative & Superlative: Хамгийн, Илүү, Дутуу (pos 78)
    # 4 Lessons | Targets: ProdLem=19, RecLem=9, ProdExp=5, RecExp=3
    # Budget: (7,3,2,1), (5,3,1,1), (0,0,0,0), (7,3,2,1) = (19, 9, 5, 3)
    # =========================================================================
    u = u_map[78]
    uid = u["unitId"]
    lessons.extend([
        {
            "lessonId": "les_a2_78_01_superlative_khamgiin_comparative_iluu",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 1,
            "title": "The Very Best: Superlative 'Хамгийн' & Comparative 'Илүү'",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Introduce the superlative modifier хамгийн (the most / -est) and comparative adverbs илүү (more / superior) and дутуу (less / deficient) in evaluative sentences.",
            "communicativeOutcome": "Identify the best, cheapest, fastest, or most famous items in town (e.g. 'Хамгийн амттай хоол', 'Үүнээс илүү сайн чанартай').",
            "objectivesIntroduced": ["obj_a2_78_01_superlative_comparative_adverbs"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_a2_77_01_enclitic_ni_marking"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_ablative_comparative", "gram_a1_noun_phrase_attributive_adjective"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_long_vowels"], "phonologyReviewed": ["phono_a1_masculine_feminine_harmony"],
            "communicativeFunctionsIntroduced": ["comm_a2_24_superlative_best_in_town"],
            "communicativeFunctionsPracticed": ["comm_a2_23_comparing_items_places"], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 7, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_commerce_transactions", "lex_domain_evaluative_descriptions"],
            "previousVocabularyReused": ["хамгийн", "илүү", "сайн", "хямд", "үнэтэй", "том"],
            "readingObjective": "Read 'Best of Ulaanbaatar' lifestyle rankings and restaurant awards.",
            "listeningObjective": "Recognize superlative claims ('хамгийн том дэлгүүр') in commercial promotional audio.",
            "writingObjective": "Write 3 superlative sentences declaring personal favorites in food, sports, and music.",
            "spokenProductionObjective": "Declare local recommendations: 'Манай хотын хамгийн амттай бууз энэ гуанзанд байдаг'.",
            "registerTarget": "Enthusiastic evaluative recommendation register",
            "pragmaticTarget": "Offering genuine local recommendations to visitors without hyperbolic exaggeration.",
            "prerequisiteLessonIds": ["les_a2_77_01_possessive_enclitic_ni_intro"],
            "reviewsLessonIds": ["les_a1_40_01_ablative_origin_intro"],
            "reviewsUnitIds": ["unit_a1_40_ablative_of_spatial_temporal_origin"],
            "reviewReason": "Connects ablative comparative base (-аас илүү) with absolute superlative (хамгийн).",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Model emphatic pitch accent on superlative 'хамгийн'.",
            "successCriteria": [
                "Uses хамгийн immediately preceding adjectives to form absolute superlatives",
                "Contrasts илүү (more) with дутуу (less/incomplete) in functional contexts"
            ],
            "masteryEvidence": "Produces 'Энэ бол Улаанбаатарын хамгийн хуучин барилга мөн' accurately.",
            "recommendedExerciseModalities": ["sentence_construction", "contextual_cloze", "matching"]
        },
        {
            "lessonId": "les_a2_78_02_city_rankings_awards_reading",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 2,
            "title": "Deciphering City Rankings, Top 10 Guides & Consumer Awards",
            "lessonType": "reading_development",
            "primaryPurpose": "Develop targeted reading skills for top-ten city rankings, consumer choice awards (Шилдэг бүтээгдэхүүн), and restaurant guidebooks.",
            "communicativeOutcome": "Inspect a 'Top 5 Coffee Shops in UB' article to identify which venue has the best coffee, quietest atmosphere, and fastest Wi-Fi.",
            "objectivesIntroduced": ["obj_a2_78_02_read_city_rankings"],
            "objectivesPracticed": ["obj_a2_78_01_superlative_comparative_adverbs"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_genitive_possession", "gram_a1_predicate_adjective_nominal"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_24_superlative_best_in_town"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_city_urban_life", "lex_domain_evaluative_descriptions"],
            "previousVocabularyReused": ["шилдэг", "нэгдүгээр", "байр", "үйлчилгээ", "орчин", "сонголт"],
            "readingObjective": "Locate ranking criteria (үнэ, чанар, орчин) and top-rated venue names from a 150-word magazine article.",
            "listeningObjective": "",
            "writingObjective": "Note down top-rated recommendations in a travel notebook.",
            "spokenProductionObjective": "Explain why a restaurant won first place to a peer based on text evidence.",
            "registerTarget": "Journalistic lifestyle and rankings register",
            "pragmaticTarget": "Understanding criteria behind municipal awards and public certifications.",
            "prerequisiteLessonIds": ["les_a2_78_01_superlative_khamgiin_comparative_iluu"],
            "reviewsLessonIds": ["les_a1_36_02_reading_calendar_dates"],
            "reviewsUnitIds": ["unit_a1_36_calendar_dates_months_seasons"],
            "reviewReason": "Interprets award years and annual competition timelines in published articles.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Read magazine excerpts aloud with lively journalistic cadence.",
            "successCriteria": [
                "Identifies which business won 'Шилдэг үйлдвэрлэгч' (Best Producer) from article",
                "Extracts specific superlative reasons cited for top ranking"
            ],
            "masteryEvidence": "Correctly answers 4 comprehension questions based on an authentic Top-5 ranking list.",
            "recommendedExerciseModalities": ["reading_comprehension", "contextual_cloze", "categorization"]
        },
        {
            "lessonId": "les_a2_78_03_critic_deliberation_listening",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 3,
            "title": "Acoustic Lab: Food Critics & Local Guide Deliberations",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop acoustic listening comprehension of food critics and culture bloggers debating which establishment deserves the title of 'Best in Town'.",
            "communicativeOutcome": "Follow dynamic spoken debates comparing hospitality, portion sizes, authentic flavor, and atmosphere across different establishments.",
            "objectivesIntroduced": ["obj_a2_78_03_decode_critic_debates"],
            "objectivesPracticed": ["obj_a2_78_01_superlative_comparative_adverbs"], "objectivesReviewed": ["obj_a2_77_01_enclitic_ni_marking"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_ablative_comparative", "gram_a2_possessive_third_person_enclitic_ni"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_vowel_reduction_non_initial"], "phonologyReviewed": ["phono_a1_nasal_vowels"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_24_superlative_best_in_town"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_food_dining", "lex_domain_city_urban_life"],
            "previousVocabularyReused": ["хоол", "амттай", "үйлчилгээ", "илүү", "хамгийн", "бодол"],
            "readingObjective": "",
            "listeningObjective": "Track shifting speaker opinions across a 2-minute podcast debate evaluating 3 traditional Mongolian restaurants.",
            "writingObjective": "",
            "spokenProductionObjective": "Summarize which restaurant the hosts finally selected as their top pick.",
            "registerTarget": "Informative broadcast debate and podcast register",
            "pragmaticTarget": "Understanding nuanced opinion markers ('Миний хувьд бол...', 'Гэхдээ нөгөө талаар...').",
            "prerequisiteLessonIds": ["les_a2_78_01_superlative_khamgiin_comparative_iluu"],
            "reviewsLessonIds": ["les_a1_54_03_listening_cafe_orders"],
            "reviewsUnitIds": ["unit_a1_54_coffee_shops_teahouses_beverage_cu"],
            "reviewReason": "Advances from basic cafe ordering to evaluating food quality and dining atmosphere.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Two podcast hosts exchanging candid banter over Ulaanbaatar's culinary scene.",
            "successCriteria": [
                "Identifies final restaurant winner chosen by both podcast hosts",
                "Extracts specific comparative claims made about buuz crust thickness and broth flavor"
            ],
            "masteryEvidence": "Accurately maps out the pros and cons table for all 3 discussed dining venues from audio.",
            "recommendedExerciseModalities": ["listening_comprehension", "phonetic_discrimination", "categorization"]
        },
        {
            "lessonId": "les_a2_78_04_recommending_best_spots_dialogue",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 4,
            "title": "Local Guide: Recommending the City's Hidden Gems & Top Spots",
            "lessonType": "dialogue_work",
            "primaryPurpose": "Develop spoken conversational fluency for acting as a local host, recommending the best spots for cashmere, book shopping, or dining.",
            "communicativeOutcome": "Recommend the top 3 spots in Ulaanbaatar to a foreign visitor, defending your choices with comparative and superlative justifications.",
            "objectivesIntroduced": ["obj_a2_78_04_recommend_local_spots_dialogue"],
            "objectivesPracticed": ["obj_a2_78_01_superlative_comparative_adverbs", "obj_a2_78_02_read_city_rankings"],
            "objectivesReviewed": ["obj_a1_16_01_greet_time_of_day"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_ablative_comparative", "gram_a1_converb_coordinating_j_ch"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_intonation_polite"], "phonologyReviewed": ["phono_a1_vowel_length_distinction"],
            "communicativeFunctionsIntroduced": ["comm_a2_24_superlative_best_in_town"],
            "communicativeFunctionsPracticed": ["comm_a2_23_comparing_items_places"],
            "communicativeFunctionsReviewed": ["comm_a1_19_inquiring_location"],
            "newProductiveLemmaTarget": 7, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_city_urban_life", "lex_domain_commerce_transactions"],
            "previousVocabularyReused": ["газар", "очих", "үзэх", "зөвлөх", "дуртай", "сайхан"],
            "readingObjective": "",
            "listeningObjective": "Understand visitor's preferences (e.g. wants affordable cashmere vs luxury showroom).",
            "writingObjective": "",
            "spokenProductionObjective": "Provide detailed recommendation: 'Хэрэв та чанартай ноолуур авахыг хүсвэл Говь хамгийн сайн нь. Харин хямд сонголт хэрэгтэй бол Нарантуул илүү дээр'.",
            "registerTarget": "Warm hospitable cultural guide register",
            "pragmaticTarget": "Tailoring recommendations to visitor's budget and specific personal interests.",
            "prerequisiteLessonIds": ["les_a2_78_02_city_rankings_awards_reading", "les_a2_78_03_critic_deliberation_listening"],
            "reviewsLessonIds": ["les_a1_63_05_interactive_checkpoint_simulation"],
            "reviewsUnitIds": ["unit_a1_63_a1_comprehensive_review_checkpoint_c"],
            "reviewReason": "Applies conversational host skills to authentic urban recommendations.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Deliver natural spoken recommendations with hospitable and enthusiastic tone.",
            "successCriteria": [
                "Provides at least 2 distinct recommendations utilizing хамгийн and илүү",
                "Justifies each recommendation with reference to quality, price, or convenience"
            ],
            "masteryEvidence": "Completes a 5-turn unscripted dialogue advising a foreign student on where to buy winter gear.",
            "recommendedExerciseModalities": ["role-play response", "dialogue_completion", "listening_comprehension"]
        }
    ])

    # =========================================================================
    # UNIT 79: Open-Air Market Bargaining at Narantuul: -bal4 (pos 79)
    # 6 Lessons | Targets: ProdLem=21, RecLem=10, ProdExp=5, RecExp=3
    # Budget: (4,2,1,1), (6,3,1,1), (0,0,0,0), (5,3,1,0), (4,2,2,1), (2,0,0,0) = (21, 10, 5, 3)
    # =========================================================================
    u = u_map[79]
    uid = u["unitId"]
    lessons.extend([
        {
            "lessonId": "les_a2_79_01_conditional_converb_val_intro",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 1,
            "title": "If You Buy Two: The Conditional Converb (-бал/-бэл/-бол/-бөл, -вал/-вэл)",
            "lessonType": "grammar_introduction",
            "primaryPurpose": "Introduce the conditional converb suffix (-бал4 after consonants / -вал4 after vowels) to construct conditional clauses and bargaining propositions.",
            "communicativeOutcome": "Negotiate volume discounts and conditional agreements (e.g. 'Хоёрыг авбал хэдээр өгөх вэ?', 'Бэлэн мөнгөөр төлбөл хямдруулах уу?').",
            "objectivesIntroduced": ["obj_a2_79_01_conditional_converb_val"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_a2_78_01_superlative_comparative_adverbs"],
            "grammarIntroduced": ["gram_a2_converb_conditional_val"],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_converb_coordinating_j_ch", "gram_a1_polar_questions_uu_uu"],
            "phonologyIntroduced": ["phono_a2_conditional_allomorph_harmony"],
            "phonologyPracticed": ["phono_a1_masculine_feminine_harmony"], "phonologyReviewed": ["phono_a1_long_vowels"],
            "communicativeFunctionsIntroduced": ["comm_a2_23_comparing_items_places", "comm_a1_23_bargaining_clarifying_price"],
            "communicativeFunctionsPracticed": ["comm_a1_22_making_purchases"], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 4, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_commerce_transactions", "lex_domain_actions_movement"],
            "previousVocabularyReused": ["авах", "өгөх", "төлөх", "хямдрах", "хэд", "болно"],
            "readingObjective": "Read market promotional placards offering conditional bulk discounts ('3-ыг авбал 1 үнэгүй').",
            "listeningObjective": "Identify conditional converb endings (-бал/-вал) in vendor discount offers.",
            "writingObjective": "Combine 3 premise clauses with consequence clauses using conditional converbs.",
            "spokenProductionObjective": "Propose conditional bargaining offers: 'Би хоёрыг авбал арай хямд өгөх үү?'.",
            "registerTarget": "Open-air market commercial negotiation register",
            "pragmaticTarget": "Using conditional propositions politely to test seller flexibility without offending.",
            "prerequisiteLessonIds": ["les_a2_78_01_superlative_khamgiin_comparative_iluu"],
            "reviewsLessonIds": ["les_a1_52_01_open_market_grocery_shopping"],
            "reviewsUnitIds": ["unit_a1_52_open_market_grocery_shopping_bulk_q"],
            "reviewReason": "Expands basic A1 market shopping into sophisticated hypothetical bargaining syntax.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Model allomorph selection (-бал after consonants, -вал after vowels) and vowel harmony.",
            "successCriteria": [
                "Selects correct allomorph (-бал vs -вал) based on stem coda",
                "Constructs valid conditional sentence connecting premise and outcome"
            ],
            "masteryEvidence": "Produces 'Бэлнээр төлбөл таван мянган төгрөг хасаж болох уу?' accurately.",
            "recommendedExerciseModalities": ["suffix_selection", "sentence_construction", "clause_combination"]
        },
        {
            "lessonId": "les_a2_79_02_narantuul_market_geography_lexicon",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 2,
            "title": "Narantuul Market: Rows, Stalls & Open-Air Commerce",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Introduce specific vocabulary for navigating the massive Narantuul open-air market (хар зах, лангуу, эгнээ, бөөний үнэ, жижиглэн, гар тэрэг).",
            "communicativeOutcome": "Navigate market rows, locate wholesale vs retail sections, and ask stallholders about bulk pricing.",
            "objectivesIntroduced": ["obj_a2_79_02_open_market_lexicon"],
            "objectivesPracticed": ["obj_a2_79_01_conditional_converb_val"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_converb_conditional_val"],
            "grammarReviewed": ["gram_a1_case_dative_locative_location", "gram_a1_case_genitive_possession"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_consonant_clusters"], "phonologyReviewed": ["phono_a1_vowel_reduction_non_initial"],
            "communicativeFunctionsIntroduced": ["comm_a1_23_bargaining_clarifying_price"],
            "communicativeFunctionsPracticed": ["comm_a1_22_making_purchases"], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_commerce_transactions", "lex_domain_city_urban_life"],
            "previousVocabularyReused": ["зах", "лангуу", "бараа", "хямд", "үнэ", "хүн"],
            "readingObjective": "Read Narantuul perimeter signage directing visitors to boot rows, felt sections, and fabric rows.",
            "listeningObjective": "Understand porter shouts ('Зам тавиарай!') and stall vendors advertising fresh arrivals.",
            "writingObjective": "List 5 distinct shopping zones of Narantuul market in Cyrillic.",
            "spokenProductionObjective": "Ask a vendor: 'Энэ барааг бөөний үнээр авбал хэд вэ?'.",
            "registerTarget": "Lively open-air marketplace register",
            "pragmaticTarget": "Maintaining awareness of personal belongings while navigating crowded market alleyways.",
            "prerequisiteLessonIds": ["les_a2_79_01_conditional_converb_val_intro"],
            "reviewsLessonIds": ["les_a1_52_02_vegetable_meat_pricing"],
            "reviewsUnitIds": ["unit_a1_52_open_market_grocery_shopping_bulk_q"],
            "reviewReason": "Expands open-air grocery shopping to consumer durables and traditional goods.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Pronounce open-air market trading terminology clearly.",
            "successCriteria": [
                "Defines лангуу (stall), эгнээ (row), бөөний үнэ (wholesale price), жижиглэн (retail)",
                "Distinguishes market sectors for boots, saddles, fabric, and home goods"
            ],
            "masteryEvidence": "Correctly matches 6 traditional market commodities with their designated Narantuul rows.",
            "recommendedExerciseModalities": ["categorization", "contextual_cloze", "matching"]
        },
        {
            "lessonId": "les_a2_79_03_narantuul_acoustic_bargaining_lab",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 3,
            "title": "Acoustic Lab: Market Hustle & Rapid Price Wrangling",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop acoustic listening comprehension of intense, rapid market bargaining dialogues amidst background yelling, wind, and cart wheels.",
            "communicativeOutcome": "Extract initial asking price, buyer counter-offer, vendor conditional compromises, and agreed settlement from noisy market audio.",
            "objectivesIntroduced": ["obj_a2_79_03_decode_market_bargaining_audio"],
            "objectivesPracticed": ["obj_a2_79_01_conditional_converb_val", "obj_a2_79_02_open_market_lexicon"],
            "objectivesReviewed": ["obj_a1_27_01_counting_tens_hundreds"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_numerals_cardinal_counting", "gram_a2_converb_conditional_val"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_vowel_reduction_non_initial"], "phonologyReviewed": ["phono_a1_nasal_vowels"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a1_23_bargaining_clarifying_price"],
            "communicativeFunctionsReviewed": ["comm_a1_22_making_purchases"],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_commerce_transactions"],
            "previousVocabularyReused": ["төгрөг", "мянга", "өгөхгүй", "авах", "ярих", "буух"],
            "readingObjective": "",
            "listeningObjective": "Extract starting price, counter-offer, and final agreed price across 3 recorded vendor-buyer bargaining exchanges.",
            "writingObjective": "",
            "spokenProductionObjective": "Explain how much the buyer managed to save in each audio clip.",
            "registerTarget": "High-tempo colloquial market transaction register",
            "pragmaticTarget": "Parsing rapid price elisions (e.g. 'хорин тав' for 25,000) under intense auditory noise.",
            "prerequisiteLessonIds": ["les_a2_79_02_narantuul_market_geography_lexicon"],
            "reviewsLessonIds": ["les_a1_52_03_listening_market_vendors"],
            "reviewsUnitIds": ["unit_a1_52_open_market_grocery_shopping_bulk_q"],
            "reviewReason": "Tests listening acuity under authentic high-density open-air acoustic conditions.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Field audio recorded at Narantuul with outdoor wind, vendor banter, and customer haggling.",
            "successCriteria": [
                "Identifies final settlement price accurately without being confused by intermediary counter-offers",
                "Recognizes the conditional converb structure used by the vendor to offer a deal"
            ],
            "masteryEvidence": "Logs all financial figures correctly across 3 distinct bargaining audio clips.",
            "recommendedExerciseModalities": ["listening_comprehension", "dictation", "phonetic_discrimination"]
        },
        {
            "lessonId": "les_a2_79_04_reading_stallholder_receipts_signs",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 4,
            "title": "Deciphering Market Signs, Handwritten Tags & Bill Slips",
            "lessonType": "reading_development",
            "primaryPurpose": "Develop reading skills for handwritten stall placards (Эцсийн үнэ, Бөөний үнэ), promotional cardboard markers, and handwritten market receipts.",
            "communicativeOutcome": "Inspect market signs to determine whether prices are fixed or negotiable, and verify handwritten receipt tallies.",
            "objectivesIntroduced": ["obj_a2_79_04_read_market_signs_receipts"],
            "objectivesPracticed": ["obj_a2_79_02_open_market_lexicon"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_numerals_cardinal_counting", "gram_a1_noun_plural_markers"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a1_23_bargaining_clarifying_price"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_commerce_transactions"],
            "previousVocabularyReused": ["үнэ", "бэлэн", "тооцоо", "баримт", "бараа", "ширхэг"],
            "readingObjective": "Read handwritten cardboard signs ('Яриа байхгүй', '5-аас дээш бөөний үнээр') and verify receipt items.",
            "listeningObjective": "",
            "writingObjective": "Transcribe purchased market items and total expenditures into a budgeting log.",
            "spokenProductionObjective": "Explain to a shopping peer which stalls have fixed prices vs negotiable items.",
            "registerTarget": "Informal handwritten commercial signage register",
            "pragmaticTarget": "Respecting 'Яриа байхгүй' (no bargaining / firm price) signs to avoid pointless haggling.",
            "prerequisiteLessonIds": ["les_a2_79_02_narantuul_market_geography_lexicon"],
            "reviewsLessonIds": ["les_a1_52_04_reading_price_placards"],
            "reviewsUnitIds": ["unit_a1_52_open_market_grocery_shopping_bulk_q"],
            "reviewReason": "Applies handwriting recognition to market receipts and Cyrillic placards.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Pronounce colloquial stall sign slogans.",
            "successCriteria": [
                "Understands meaning of 'Яриа байхгүй' (firm price) and 'Бөөний үнэ' (wholesale price)",
                "Calculates total on a handwritten market invoice accurately"
            ],
            "masteryEvidence": "Answers 4 comprehension questions based on authentic photographed handwritten market tags.",
            "recommendedExerciseModalities": ["reading_comprehension", "contextual_cloze", "categorization"]
        },
        {
            "lessonId": "les_a2_79_05_stallholder_haggling_dialogue",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 5,
            "title": "Haggling at the Stall: Polite Negotiation with Stallholders",
            "lessonType": "dialogue_work",
            "primaryPurpose": "Master spoken bargaining exchanges with Narantuul stallholders: inspecting goods, pointing out flaws, proposing conditional package deals, and reaching consensus.",
            "communicativeOutcome": "Negotiate a fair price for a traditional felt rug or pair of boots using conditional converbs and polite bargaining expressions.",
            "objectivesIntroduced": ["obj_a2_79_05_bargaining_negotiation_dialogue"],
            "objectivesPracticed": ["obj_a2_79_01_conditional_converb_val", "obj_a2_79_02_open_market_lexicon"],
            "objectivesReviewed": ["obj_a1_23_01_bargaining_basics"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_converb_conditional_val"],
            "grammarReviewed": ["gram_a1_verb_volitional_intention_ya", "gram_a1_polar_questions_uu_uu"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_intonation_polite"], "phonologyReviewed": ["phono_a1_vowel_length_distinction"],
            "communicativeFunctionsIntroduced": ["comm_a1_23_bargaining_clarifying_price"],
            "communicativeFunctionsPracticed": ["comm_a1_22_making_purchases"],
            "communicativeFunctionsReviewed": ["comm_a1_16_greetings_time_of_day"],
            "newProductiveLemmaTarget": 4, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_commerce_transactions"],
            "previousVocabularyReused": ["үнэ", "буулгах", "авах", "өгөх", "хэд", "болох"],
            "readingObjective": "",
            "listeningObjective": "Understand vendor's counter-offer: 'За яахав, та хоёрыг авбал дөчин мянгаар өгье'.",
            "writingObjective": "",
            "spokenProductionObjective": "Haggle politely: 'Эгч ээ, би бэлэн мөнгөөр шууд авбал жаахан буулгаж өгөх үү?'.",
            "registerTarget": "Good-humored respectful market bargaining register",
            "pragmaticTarget": "Maintaining a warm, friendly rapport with respectful address terms ('эгч ээ', 'ах аа') during price negotiation.",
            "prerequisiteLessonIds": ["les_a2_79_03_narantuul_acoustic_bargaining_lab", "les_a2_79_04_reading_stallholder_receipts_signs"],
            "reviewsLessonIds": ["les_a1_52_05_market_transaction_simulation"],
            "reviewsUnitIds": ["unit_a1_52_open_market_grocery_shopping_bulk_q"],
            "reviewReason": "Builds on A1 market bargaining with advanced conditional syntax (-бал/-вал).",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Deliver lively, warm banter between friendly customer and stallholder.",
            "successCriteria": [
                "Initiates negotiation politely using conditional converb clause",
                "Accepts or counter-proposes within realistic market pricing bounds without friction"
            ],
            "masteryEvidence": "Completes a 5-turn bargaining roleplay reaching a 10% discount on boots.",
            "recommendedExerciseModalities": ["role-play response", "dialogue_completion", "listening_comprehension"]
        },
        {
            "lessonId": "les_a2_79_06_market_bargaining_summary_writing",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 6,
            "title": "Market Chronicle: Writing a Personal Bargaining Narrative",
            "lessonType": "grammar_guided_practice",
            "primaryPurpose": "Synthesize conditional converbs, numerical prices, and marketplace vocabulary into a written narrative of a shopping expedition.",
            "communicativeOutcome": "Write a 5-6 sentence journal entry recounting a trip to Narantuul, the goods purchased, the bargaining process, and final savings.",
            "objectivesIntroduced": ["obj_a2_79_06_write_market_narrative"],
            "objectivesPracticed": ["obj_a2_79_01_conditional_converb_val", "obj_a2_79_05_bargaining_negotiation_dialogue"],
            "objectivesReviewed": ["obj_a1_41_01_witnessed_past_laa"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_converb_conditional_val"],
            "grammarReviewed": ["gram_a1_verb_tense_past_witnessed_laa", "gram_a1_converb_sequential_aad"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a1_23_bargaining_clarifying_price", "comm_a2_23_comparing_items_places"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 2, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_commerce_transactions", "lex_domain_city_urban_life"],
            "previousVocabularyReused": ["зах", "бараа", "худалдаж авах", "үнэ", "хямдрах", "дурсамж"],
            "readingObjective": "Review a peer's draft market chronicle for conditional converb usage.",
            "listeningObjective": "",
            "writingObjective": "Draft a 6-sentence narrative describing purchases and conditional bargaining agreements at the market.",
            "spokenProductionObjective": "",
            "registerTarget": "Engaging personal journal chronicle register",
            "pragmaticTarget": "Reflecting on consumer experiences and financial stewardship in written form.",
            "prerequisiteLessonIds": ["les_a2_79_05_stallholder_haggling_dialogue"],
            "reviewsLessonIds": ["les_a1_52_06_market_shopping_diary_writing"],
            "reviewsUnitIds": ["unit_a1_52_open_market_grocery_shopping_bulk_q"],
            "reviewReason": "Deepens market shopping diary entries with advanced conditional syntax.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Audio read-back of written market chronicle.",
            "successCriteria": [
                "Produces a coherent paragraph containing at least 2 correctly formed conditional converbs (-бал/-вал)",
                "Accurately quotes pricing dialogue and final savings"
            ],
            "masteryEvidence": "Writes 'Би Нарантуул захаас гутал авахдаа: 'Хоёрыг авбал хямдруулах уу?' гэж асуугаад, 10 мянган төгрөг хасуулж авлаа' correctly.",
            "recommendedExerciseModalities": ["short-answer writing", "clause_combination", "error correction"]
        }
    ])

    return lessons
