"""
Section 2 Generator Part 1 (Units 73 - 76): 21 Lessons
73: Department Stores & Malls (5 lessons)
74: Clothing Sizes & Fitting Rooms (5 lessons)
75: Reflexive-Possessive Base Suffixes (5 lessons)
76: Reflexive Case Combinations (6 lessons)
"""

import json
from typing import List, Dict, Any

def get_sec02_part1_lessons(u_map: Dict[int, Any]) -> List[Dict[str, Any]]:
    lessons: List[Dict[str, Any]] = []

    # =========================================================================
    # UNIT 73: Department Stores & Shopping Mall Navigation (pos 73)
    # 5 Lessons | Targets: ProdLem=21, RecLem=10, ProdExp=5, RecExp=3
    # Budget: (5,2,1,1), (6,3,1,1), (5,3,2,1), (0,0,0,0), (5,2,1,0) = (21, 10, 5, 3)
    # =========================================================================
    u = u_map[73]
    uid = u["unitId"]
    lessons.extend([
        {
            "lessonId": "les_a2_73_01_ordinal_numerals_floors",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 1,
            "title": "Floors & Sequences: Ordinal Numerals (-дугаар/-дүгээр, -дахь/-дэх)",
            "lessonType": "grammar_introduction",
            "primaryPurpose": "Introduce ordinal numeral derivation using suffixes -дугаар/-дүгээр and -дахь/-дэх for floor levels, sequential rankings, and retail departments.",
            "communicativeOutcome": "Ask and explain which floor a retail department or store is located on (e.g. 'Гуравдугаар давхарт', 'Тав дахь давхар луу гараарай').",
            "objectivesIntroduced": ["obj_a2_73_01_ordinal_numeral_derivation"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_a2_65_01_directional_suffix_marking"],
            "grammarIntroduced": ["gram_a2_numerals_ordinal"],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_numerals_cardinal_counting", "gram_a1_case_dative_locative_location"],
            "phonologyIntroduced": ["phono_a2_ordinal_vocalic_harmony"],
            "phonologyPracticed": ["phono_a1_masculine_feminine_harmony"], "phonologyReviewed": ["phono_a1_consonant_clusters"],
            "communicativeFunctionsIntroduced": ["comm_a2_23_comparing_items_places"],
            "communicativeFunctionsPracticed": ["comm_a1_19_inquiring_location"], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_commerce_transactions", "lex_domain_city_urban_life"],
            "previousVocabularyReused": ["давхар", "дэлгүүр", "нэг", "хоёр", "гурав", "дөрөв", "тав"],
            "readingObjective": "Read floor directories of major department stores (State Department Store, Shangri-La Mall).",
            "listeningObjective": "Identify floor numbers and store names from mall directory help desk speech.",
            "writingObjective": "Write 3 sentences detailing which products are found on specific floors.",
            "spokenProductionObjective": "Direct a shopper: 'Эмэгтэй хувцасны тасаг хоёрдугаар давхарт байгаа'.",
            "registerTarget": "Standard polite retail informative register",
            "pragmaticTarget": "Using formal ordinals (-дугаар) for formal directories and colloquial ordinals (-дахь) for speech.",
            "prerequisiteLessonIds": ["les_a2_72_05_urban_transit_benchmark_checkpoint"],
            "reviewsLessonIds": ["les_a1_27_01_counting_tens_hundreds"],
            "reviewsUnitIds": ["unit_a1_27_cardinal_numbers_counting_up_to_one"],
            "reviewReason": "Transforms cardinal roots into ordinal markers for hierarchical physical navigation.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Model vowel harmony alternation between back (-дугаар, -дахь) and front (-дүгээр, -дэх) suffixes.",
            "successCriteria": [
                "Selects appropriate ordinal suffix according to root vowel harmony and stylistic register",
                "Accurately constructs locative phrases specifying floor locations"
            ],
            "masteryEvidence": "Produces 'Номын дэлгүүр зургаадугаар давхарт байна' accurately matching phonology.",
            "recommendedExerciseModalities": ["suffix_selection", "sentence_construction", "matching"]
        },
        {
            "lessonId": "les_a2_73_02_mall_directories_department_lexicon",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 2,
            "title": "Ikh Delguur & Modern Malls: Department Store Vocabulary",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Introduce specific vocabulary for shopping mall sections (гоо сайхан, цахилгаан бараа, бэлэг дурсгал, цахилгаан шат, урсдаг шат).",
            "communicativeOutcome": "Identify mall departments, locate escalators/elevators, and ask for specific product categories.",
            "objectivesIntroduced": ["obj_a2_73_02_mall_departments_lexicon"],
            "objectivesPracticed": ["obj_a2_73_01_ordinal_numeral_derivation"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_numerals_ordinal"],
            "grammarReviewed": ["gram_a1_case_genitive_possession", "gram_a1_case_dative_locative_location"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_consonant_clusters"], "phonologyReviewed": ["phono_a1_vowel_reduction_non_initial"],
            "communicativeFunctionsIntroduced": ["comm_a2_23_comparing_items_places"],
            "communicativeFunctionsPracticed": ["comm_a1_22_making_purchases"], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_commerce_transactions", "lex_domain_city_urban_life"],
            "previousVocabularyReused": ["бараа", "хувцас", "гутал", "нохой", "цахилгаан шат", "шат"],
            "readingObjective": "Read hanging overhead mall signs directing foot traffic to escalators and restrooms.",
            "listeningObjective": "Understand mall directory audio kiosk prompts and category selections.",
            "writingObjective": "Create a shopping checklist organized by department store floor.",
            "spokenProductionObjective": "Ask a store clerk: 'Цахилгаан барааны тасаг хэддүгээр давхарт байдаг вэ?'.",
            "registerTarget": "Everyday retail customer register",
            "pragmaticTarget": "Navigating multi-story shopping centers independently and efficiently.",
            "prerequisiteLessonIds": ["les_a2_73_01_ordinal_numerals_floors"],
            "reviewsLessonIds": ["les_a1_22_01_making_purchases_intro"],
            "reviewsUnitIds": ["unit_a1_22_shopping_transactions_making_purch"],
            "reviewReason": "Expands basic convenience store shopping to multi-department commercial complexes.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Pronounce compound departmental terms clearly.",
            "successCriteria": [
                "Identifies key retail sections: гэр ахуйн бараа (home goods), бэлэг дурсгал (souvenirs), хүнс (groceries)",
                "Distinguishes урсдаг шат (escalator) from цахилгаан шат (elevator)"
            ],
            "masteryEvidence": "Accurately categorizes 8 everyday items into their corresponding department store floors.",
            "recommendedExerciseModalities": ["categorization", "contextual_cloze", "matching"]
        },
        {
            "lessonId": "les_a2_73_03_information_desk_inquiries_dialogue",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 3,
            "title": "At the Information Desk: Inquiring About Brands & Services",
            "lessonType": "dialogue_work",
            "primaryPurpose": "Develop spoken interaction skills with shopping mall information desk staff, inquiring about specific boutiques, lost property, and wheelchair access.",
            "communicativeOutcome": "Ask information desk staff where a specific brand is sold, locate customer service, and ask about gift wrapping.",
            "objectivesIntroduced": ["obj_a2_73_03_mall_inquiry_dialogue"],
            "objectivesPracticed": ["obj_a2_73_01_ordinal_numeral_derivation", "obj_a2_73_02_mall_departments_lexicon"],
            "objectivesReviewed": ["obj_a1_19_01_polar_questions"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_numerals_ordinal"],
            "grammarReviewed": ["gram_a1_polar_questions_uu_uu", "gram_a1_case_directional_towards"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_intonation_polite"], "phonologyReviewed": ["phono_a1_diphthongs"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_23_comparing_items_places", "comm_a1_19_inquiring_location"],
            "communicativeFunctionsReviewed": ["comm_a1_13_apologies_politeness"],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_commerce_transactions", "lex_domain_city_urban_life"],
            "previousVocabularyReused": ["уучлаарай", "хаана", "байх", "орох", "бэлэг", "боох"],
            "readingObjective": "",
            "listeningObjective": "Follow information officer's instructions: 'Та урсдаг шатаар гуравдугаар давхарт гараад зүүн тийш эргээрэй'.",
            "writingObjective": "",
            "spokenProductionObjective": "Ask information clerk: 'Уучлаарай, монгол бэлэг дурсгалын тасаг аль давхарт байдаг вэ?'.",
            "registerTarget": "Courteous customer service exchange register",
            "pragmaticTarget": "Using respectful conversational openers ('Танаас нэг зүйл лавлаж болох уу?').",
            "prerequisiteLessonIds": ["les_a2_73_02_mall_directories_department_lexicon"],
            "reviewsLessonIds": ["les_a1_16_05_reception_desk_simulation"],
            "reviewsUnitIds": ["unit_a1_16_canonical_sov_word_order_declarat"],
            "reviewReason": "Builds on service counter inquiry routines established in A1.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Model polite, professional concierge responses in a busy mall lobby.",
            "successCriteria": [
                "Inquires about store location using ordinal numbers and polite phrasing",
                "Comprehends spoken directions combining floor number, escalator, and cardinal turns"
            ],
            "masteryEvidence": "Successfully completes simulated concierge dialogue finding the cashmere boutique.",
            "recommendedExerciseModalities": ["role-play response", "dialogue_completion", "listening_comprehension"]
        },
        {
            "lessonId": "les_a2_73_04_mall_promotions_pa_listening",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 4,
            "title": "Acoustic Lab: Mall Promotional Announcements & Store Hours",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop acoustic listening comprehension of mall-wide promotional announcements (хямдрал, урамшуулал), flash sales, and closing announcements.",
            "communicativeOutcome": "Extract discount percentages, participating store departments, and evening closing times from public address audio.",
            "objectivesIntroduced": ["obj_a2_73_04_decode_mall_promotions"],
            "objectivesPracticed": ["obj_a2_73_02_mall_departments_lexicon"], "objectivesReviewed": ["obj_a1_27_01_counting_tens_hundreds"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_numerals_cardinal_counting", "gram_a1_case_ablative_origin"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_vowel_reduction_non_initial"], "phonologyReviewed": ["phono_a1_nasal_vowels"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_23_comparing_items_places"],
            "communicativeFunctionsReviewed": ["comm_a1_22_making_purchases"],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_commerce_transactions"],
            "previousVocabularyReused": ["хямдрал", "хувь", "хаагдах", "цаг", "бараа", "үйлчлүүлэгч"],
            "readingObjective": "",
            "listeningObjective": "Identify discount percentages (20%-50%), affected departments, and closing announcement ('Манай их дэлгүүр 21 цагт хаагдана') from mall audio.",
            "writingObjective": "",
            "spokenProductionObjective": "Inform shopping companion of closing time: 'Дэлгүүр 30 минутын дараа хаагдах гэж байна'.",
            "registerTarget": "Public commercial announcement broadcast register",
            "pragmaticTarget": "Parsing recorded announcements with musical jingles and customer background noise.",
            "prerequisiteLessonIds": ["les_a2_73_02_mall_directories_department_lexicon"],
            "reviewsLessonIds": ["les_a1_52_03_listening_market_vendors"],
            "reviewsUnitIds": ["unit_a1_52_open_market_grocery_shopping_bulk_q"],
            "reviewReason": "Advances from market stall vendor calls to polished commercial store announcements.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Authentic audio with mall background music, cashier beeps, and echoing loudspeaker voice.",
            "successCriteria": [
                "Extracts discount percentages (хорин хувь, тавин хувь) accurately from audio",
                "Identifies floor number and department hosting the promotional event"
            ],
            "masteryEvidence": "Fills in promotional summary table correctly for 3 distinct mall broadcast announcements.",
            "recommendedExerciseModalities": ["listening_comprehension", "phonetic_discrimination", "categorization"]
        },
        {
            "lessonId": "les_a2_73_05_mall_directory_memo_writing",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 5,
            "title": "Shopping Guide: Writing Floor Directory Guides & Store Notes",
            "lessonType": "grammar_guided_practice",
            "primaryPurpose": "Synthesize ordinal numerals, departmental vocabulary, and spatial postpositions in a written shopping guide and personal errand plan.",
            "communicativeOutcome": "Draft a written floor-by-floor shopping guide advising a visitor where to buy gifts, electronics, and clothing.",
            "objectivesIntroduced": ["obj_a2_73_05_write_shopping_guide"],
            "objectivesPracticed": ["obj_a2_73_01_ordinal_numeral_derivation", "obj_a2_73_02_mall_departments_lexicon"],
            "objectivesReviewed": ["obj_a1_61_01_spatial_postpositions"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_numerals_ordinal"],
            "grammarReviewed": ["gram_a1_spatial_postpositions_deeree_door", "gram_a1_case_dative_locative_location"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_23_comparing_items_places"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_commerce_transactions", "lex_domain_city_urban_life"],
            "previousVocabularyReused": ["давхар", "тасаг", "худалдаж авах", "бараа", "бэлэг", "сонгох"],
            "readingObjective": "Review a sample floor plan guide to model written layout.",
            "listeningObjective": "",
            "writingObjective": "Write a 5-point floor guide listing ordinal numbers, departments, and recommended items to purchase.",
            "spokenProductionObjective": "",
            "registerTarget": "Informational guidebook and memo register",
            "pragmaticTarget": "Clear structural layout with bulleted or numbered floor listings.",
            "prerequisiteLessonIds": ["les_a2_73_03_information_desk_inquiries_dialogue", "les_a2_73_04_mall_promotions_pa_listening"],
            "reviewsLessonIds": ["les_a1_61_03_reading_spatial_signs"],
            "reviewsUnitIds": ["unit_a1_61_spatial_postpositions_"],
            "reviewReason": "Combines spatial relations with ordinal hierarchy in organized written prose.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Read back generated directory text for spelling verification.",
            "successCriteria": [
                "Produces written guide accurately using ordinal suffixes (-дугаар/-дүгээр) across at least 4 floors",
                "Correctly spells specialized retail categories: бэлэг дурсгал, гоо сайхан, цахилгаан бараа"
            ],
            "masteryEvidence": "Drafts '1-р давхарт: супермаркет ба эмийн сан; 2-р давхарт: эмэгтэй бэлэн хувцас...' correctly.",
            "recommendedExerciseModalities": ["short-answer writing", "sentence construction", "error correction"]
        }
    ])

    # =========================================================================
    # UNIT 74: Clothing Sizes, Fabrics & Fitting Rooms (pos 74)
    # 5 Lessons | Targets: ProdLem=19, RecLem=9, ProdExp=5, RecExp=3
    # Budget: (4,2,1,1), (6,3,1,1), (0,0,0,0), (5,2,2,1), (4,2,1,0) = (19, 9, 5, 3)
    # =========================================================================
    u = u_map[74]
    uid = u["unitId"]
    lessons.extend([
        {
            "lessonId": "les_a2_74_01_clothing_fit_adjectives",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 1,
            "title": "Too Tight or Just Right: Clothing Fit & Proportion Adjectives",
            "lessonType": "grammar_introduction",
            "primaryPurpose": "Introduce qualitative adjectives for garment fit, length, and tightness (бариу, сул, урт, богино, таарах) and the degree adverb хэт (too / excessively).",
            "communicativeOutcome": "Describe how clothing fits the body and state whether an item is too tight, loose, long, or short.",
            "objectivesIntroduced": ["obj_a2_74_01_garment_fit_adjectives"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_a2_73_01_ordinal_numeral_derivation"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_noun_phrase_attributive_adjective", "gram_a1_predicate_adjective_nominal"],
            "phonologyIntroduced": ["phono_a2_adjective_emphasis_stress"],
            "phonologyPracticed": ["phono_a1_long_vowels"], "phonologyReviewed": ["phono_a1_masculine_feminine_harmony"],
            "communicativeFunctionsIntroduced": ["comm_a2_23_comparing_items_places"],
            "communicativeFunctionsPracticed": ["comm_a1_22_making_purchases"], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 4, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_clothing_fashion", "lex_domain_commerce_transactions"],
            "previousVocabularyReused": ["том", "жижиг", "урт", "хувцас", "өмсөх", "болох"],
            "readingObjective": "Read garment fit advice columns discussing contemporary trends (сул загвар / oversized).",
            "listeningObjective": "Recognize fit descriptors when shoppers discuss trying on garments.",
            "writingObjective": "Write 3 sentences evaluating garment dimensions using fit adjectives and 'хэт' (too).",
            "spokenProductionObjective": "State fit assessment: 'Энэ өмд надад хэтэрхий бариу байна, арай сул нь байна уу?'.",
            "registerTarget": "Everyday retail boutique register",
            "pragmaticTarget": "Expressing dissatisfaction with fit politely without criticizing garment quality.",
            "prerequisiteLessonIds": ["les_a2_73_01_ordinal_numerals_floors"],
            "reviewsLessonIds": ["les_a1_21_01_attributive_adjectives_intro"],
            "reviewsUnitIds": ["unit_a1_21_attributive_predicative_adjective"],
            "reviewReason": "Expands basic size adjectives (том, жижиг) to nuanced garment fitting terminology.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Model emphatic pitch accent on degree modifiers (хэт, арай, яг).",
            "successCriteria": [
                "Differentiates бариу (tight) from сул (loose/baggy) and богино (short) from урт (long)",
                "Uses verb таарах (to fit/suit) correctly with dative subject: 'Надад яг таарч байна'"
            ],
            "masteryEvidence": "Produces 'Энэ цамц мөрөөрөө бариу боловч ханцуй нь урт байна' accurately.",
            "recommendedExerciseModalities": ["contextual_cloze", "sentence_construction", "matching"]
        },
        {
            "lessonId": "les_a2_74_02_fabrics_sizes_fitting_room_lexicon",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 2,
            "title": "Cotton, Wool & Silk: Garment Fabrics & Fitting Rooms",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Introduce vocabulary for clothing materials (хөвөн даавуу, ноос, ноолуур, торго), international size conversions, and fitting room amenities (өлгүүр, толь).",
            "communicativeOutcome": "Ask for clothing sizes (S, M, L or European sizes), identify textile composition, and locate fitting rooms.",
            "objectivesIntroduced": ["obj_a2_74_02_textile_fitting_lexicon"],
            "objectivesPracticed": ["obj_a2_74_01_garment_fit_adjectives"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_genitive_possession", "gram_a1_case_dative_locative_location"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_consonant_clusters"], "phonologyReviewed": ["phono_a1_vowel_reduction_non_initial"],
            "communicativeFunctionsIntroduced": ["comm_a2_23_comparing_items_places"],
            "communicativeFunctionsPracticed": ["comm_a1_22_making_purchases"], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_clothing_fashion", "lex_domain_commerce_transactions"],
            "previousVocabularyReused": ["материал", "өнгө", "хэмжээ", "өрөө", "толь", "үзэх"],
            "readingObjective": "Read clothing care labels specifying fabric percentages (100% даавуу) and washing icons.",
            "listeningObjective": "Understand sales assistant explaining size numbering differences (Asian vs European).",
            "writingObjective": "List personal clothing measurements and fabric preferences in Cyrillic.",
            "spokenProductionObjective": "Ask sales clerk: 'Энэ цамцнаас M хэмжээтэй нь байна уу? Би өмсөж үзэж болох уу?'.",
            "registerTarget": "Customer-to-clerk retail register",
            "pragmaticTarget": "Checking fabric care requirements before committing to a purchase.",
            "prerequisiteLessonIds": ["les_a2_74_01_clothing_fit_adjectives"],
            "reviewsLessonIds": ["les_a1_22_02_clothing_colors_shopping"],
            "reviewsUnitIds": ["unit_a1_22_shopping_transactions_making_purch"],
            "reviewReason": "Deepens basic garment naming from A1 into textile science and sizing systems.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Pronounce textile materials and size terms clearly.",
            "successCriteria": [
                "Identifies key fabrics: даавуу (cotton), ноос (wool), ноолуур (cashmere), торго (silk)",
                "Asks politely to use the fitting room (хувцас солих өрөө)"
            ],
            "masteryEvidence": "Correctly matches 6 fabric descriptions with their thermal and aesthetic properties.",
            "recommendedExerciseModalities": ["categorization", "contextual_cloze", "matching"]
        },
        {
            "lessonId": "les_a2_74_03_fitting_room_audio_lab",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 3,
            "title": "Acoustic Lab: Fitting Room Conversations & Size Inquiries",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop acoustic listening comprehension of spontaneous shopper-clerk dialogues through fitting room curtains and mirrors.",
            "communicativeOutcome": "Understand sales assistants offering alternative sizes, colorways, or fits while trying on clothes.",
            "objectivesIntroduced": ["obj_a2_74_03_decode_fitting_room_dialogue"],
            "objectivesPracticed": ["obj_a2_74_01_garment_fit_adjectives", "obj_a2_74_02_textile_fitting_lexicon"],
            "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_converb_coordinating_j_ch", "gram_a1_polar_questions_uu_uu"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_vowel_reduction_non_initial"], "phonologyReviewed": ["phono_a1_nasal_vowels"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_23_comparing_items_places", "comm_a1_22_making_purchases"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_clothing_fashion", "lex_domain_commerce_transactions"],
            "previousVocabularyReused": ["хэмжээ", "өнгө", "авчрах", "солих", "таарах", "ямар"],
            "readingObjective": "",
            "listeningObjective": "Identify whether shopper accepts the tried garment or requests a different size/color from audio clips.",
            "writingObjective": "",
            "spokenProductionObjective": "Explain to a friend what the sales clerk suggested from behind the curtain.",
            "registerTarget": "Muffled spontaneous indoor conversational register",
            "pragmaticTarget": "Parsing speech muffled by fitting room drapery and store acoustics.",
            "prerequisiteLessonIds": ["les_a2_74_02_fabrics_sizes_fitting_room_lexicon"],
            "reviewsLessonIds": ["les_a1_22_03_shopping_listening_comprehension"],
            "reviewsUnitIds": ["unit_a1_22_shopping_transactions_making_purch"],
            "reviewReason": "Tests listening acuity in conversational retail settings.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Deliver authentic fitting room dialogue with acoustic curtain dampening and clothing hanger clatter.",
            "successCriteria": [
                "Identifies whether garment is described as too tight, too loose, or ideal fit",
                "Extracts requested replacement size (e.g. 'Нэг размер том') correctly"
            ],
            "masteryEvidence": "Scores 100% on 4 fitting room interaction comprehension audio items.",
            "recommendedExerciseModalities": ["listening_comprehension", "phonetic_discrimination", "role-play response"]
        },
        {
            "lessonId": "les_a2_74_04_boutique_fitting_room_dialogue",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 4,
            "title": "In the Boutique: Requesting Different Sizes & Colors",
            "lessonType": "dialogue_work",
            "primaryPurpose": "Master spoken interaction in a clothing boutique: asking to try on garments, requesting a different size or shade, and asking for a mirror assessment.",
            "communicativeOutcome": "Engage with a boutique clerk to exchange sizes, ask for a matching color, and make a purchasing decision.",
            "objectivesIntroduced": ["obj_a2_74_04_boutique_shopping_dialogue"],
            "objectivesPracticed": ["obj_a2_74_01_garment_fit_adjectives", "obj_a2_74_02_textile_fitting_lexicon"],
            "objectivesReviewed": ["obj_a1_22_01_making_purchases"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_verb_imperative_polite_aarai", "gram_a1_verb_volitional_intention_ya"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_intonation_polite"], "phonologyReviewed": ["phono_a1_vowel_length_distinction"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_23_comparing_items_places", "comm_a1_22_making_purchases"],
            "communicativeFunctionsReviewed": ["comm_a1_16_greetings_time_of_day"],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_clothing_fashion", "lex_domain_commerce_transactions"],
            "previousVocabularyReused": ["өмсөх", "үзэх", "том", "жижиг", "солих", "авах"],
            "readingObjective": "",
            "listeningObjective": "Understand sales clerk offering opinions: 'Энэ өнгө танд их сайхан зохиж байна'.",
            "writingObjective": "",
            "spokenProductionObjective": "Request another size: 'Уучлаарай, энэ жаахан бариу байна. Үүнээс нэг размер томыг авчирч өгөөч?'.",
            "registerTarget": "Courteous boutique commercial register",
            "pragmaticTarget": "Using constructive polite requests while evaluating clothing in front of a mirror.",
            "prerequisiteLessonIds": ["les_a2_74_02_fabrics_sizes_fitting_room_lexicon", "les_a2_74_03_fitting_room_audio_lab"],
            "reviewsLessonIds": ["les_a1_49_01_polite_imperative_aarai"],
            "reviewsUnitIds": ["unit_a1_49_polite_request_imperative_suffixes_"],
            "reviewReason": "Utilizes polite request imperatives (-аач/-ээч) during retail service requests.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Provide natural native speaker boutique dialogue with realistic compliments and advice.",
            "successCriteria": [
                "Conducts a complete 5-turn exchange trying on an item, requesting an adjustment, and deciding to purchase",
                "Uses verb зохих (to suit/flatter) accurately: 'Танд сайхан зохиж байна'"
            ],
            "masteryEvidence": "Executes full unscripted fitting room roleplay without communication breakdown.",
            "recommendedExerciseModalities": ["role-play response", "dialogue_completion", "listening_comprehension"]
        },
        {
            "lessonId": "les_a2_74_05_garment_review_tag_reading_writing",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 5,
            "title": "Online Boutique Review: Garment Fit & Fabric Evaluation",
            "lessonType": "grammar_guided_practice",
            "primaryPurpose": "Synthesize fabric vocabulary, size ratings, and fit adjectives in a written customer review on a local clothing website.",
            "communicativeOutcome": "Write a 4-sentence clothing review assessing material softness, true-to-size fit, and color fidelity.",
            "objectivesIntroduced": ["obj_a2_74_05_write_clothing_review"],
            "objectivesPracticed": ["obj_a2_74_01_garment_fit_adjectives", "obj_a2_74_02_textile_fitting_lexicon"],
            "objectivesReviewed": ["obj_a1_21_01_adjectives_review"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_predicate_adjective_nominal", "gram_a1_converb_sequential_aad"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_23_comparing_items_places"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 4, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_clothing_fashion", "lex_domain_commerce_transactions"],
            "previousVocabularyReused": ["материал", "хэмжээ", "зузаан", "нимгэн", "чанар", "сэтгэгдэл"],
            "readingObjective": "Read customer reviews on a Mongolian e-commerce boutique assessing fabric shrinkage and color fading.",
            "listeningObjective": "",
            "writingObjective": "Draft a written customer review stating garment size, material quality, and fit verdict.",
            "spokenProductionObjective": "",
            "registerTarget": "Public e-commerce customer review register",
            "pragmaticTarget": "Providing helpful, balanced consumer feedback on fit and fabric quality.",
            "prerequisiteLessonIds": ["les_a2_74_04_boutique_fitting_room_dialogue"],
            "reviewsLessonIds": ["les_a1_21_02_describing_objects_adjectives"],
            "reviewsUnitIds": ["unit_a1_21_attributive_predicative_adjective"],
            "reviewReason": "Applies descriptive adjective syntax to contemporary online consumer culture.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Audio read-back of written reviews.",
            "successCriteria": [
                "Composes a coherent review detailing fabric composition, size accuracy, and comfort",
                "Uses qualitative fit vocabulary (таарсан, хэт бариу, зөөлөн) without error"
            ],
            "masteryEvidence": "Writes 'Энэ ноолууран цамц маш зөөлөн, биед эвтэйхэн байна. Размер нь яг таарлаа' accurately.",
            "recommendedExerciseModalities": ["short-answer writing", "sentence construction", "error correction"]
        }
    ])

    # =========================================================================
    # UNIT 75: Reflexive-Possessive Base Suffixes: -aa4 (pos 75)
    # 5 Lessons | Targets: ProdLem=21, RecLem=10, ProdExp=5, RecExp=3
    # Budget: (5,2,1,1), (6,3,1,1), (5,3,2,1), (0,0,0,0), (5,2,1,0) = (21, 10, 5, 3)
    # =========================================================================
    u = u_map[75]
    uid = u["unitId"]
    lessons.extend([
        {
            "lessonId": "les_a2_75_01_reflexive_possessive_base_intro",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 1,
            "title": "One's Own Belongings: The Reflexive Suffix (-аа/-ээ/-оо/-өө)",
            "lessonType": "grammar_introduction",
            "primaryPurpose": "Introduce the core reflexive-possessive suffix (-аа4) indicating that the possessed noun belongs to the grammatical subject of the clause.",
            "communicativeOutcome": "Distinguish between one's own possessions and another person's possessions (e.g. 'Би дээлээ өмслөө' vs 'Би түүний дээлийг өмслөө').",
            "objectivesIntroduced": ["obj_a2_75_01_reflexive_possessive_marking"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_a2_74_01_garment_fit_adjectives"],
            "grammarIntroduced": ["gram_a2_reflexive_possessive_base"],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_genitive_possession", "gram_a1_case_accusative_definite"],
            "phonologyIntroduced": ["phono_a2_reflexive_vocalic_harmony"],
            "phonologyPracticed": ["phono_a1_masculine_feminine_harmony"], "phonologyReviewed": ["phono_a1_long_vowels"],
            "communicativeFunctionsIntroduced": ["comm_a2_02_describing_appearance_clothing"],
            "communicativeFunctionsPracticed": ["comm_a1_17_describing_daily_routines"], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_clothing_fashion", "lex_domain_family_kinship"],
            "previousVocabularyReused": ["дээл", "гутал", "цүнх", "ном", "авах", "өмсөх"],
            "readingObjective": "Read narrative sentences distinguishing subject-owned items from third-party items.",
            "listeningObjective": "Identify the reflexive suffix (-аа4) in spoken accounts of dressing and preparing personal belongings.",
            "writingObjective": "Transform 4 sentences replacing genitive pronouns ('миний ном') with the reflexive-possessive suffix ('номоо').",
            "spokenProductionObjective": "Explain personal actions: 'Би малгайгаа өмсөөд, цүнхээ авлаа'.",
            "registerTarget": "Standard grammatical discourse register",
            "pragmaticTarget": "Using reflexive possession naturally to avoid unnatural repetitive genitive pronouns ('миний', 'чиний').",
            "prerequisiteLessonIds": ["les_a2_74_01_clothing_fit_adjectives"],
            "reviewsLessonIds": ["les_a1_29_01_genitive_possession_intro"],
            "reviewsUnitIds": ["unit_a1_29_genitive_possession_relational_suff"],
            "reviewReason": "Transforms analytical genitive possession (миний X) into synthetic reflexive possession (X-аа).",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Model quadruple vowel harmony (-аа, -ээ, -оо, -өө) and long vowel acoustic quality.",
            "successCriteria": [
                "Selects correct reflexive allomorph according to root vowel harmony",
                "Uses reflexive suffix when object belongs to clause subject"
            ],
            "masteryEvidence": "Correctly converts 'Би миний дээлийг авлаа' to 'Би дээлээ авлаа' consistently.",
            "recommendedExerciseModalities": ["suffix_selection", "sentence_transformation", "case_marking"]
        },
        {
            "lessonId": "les_a2_75_02_wardrobe_dressing_reflexive_lexicon",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 2,
            "title": "Dressing Up: Wardrobe Items & Daily Dressing Routines",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Introduce expanded wardrobe vocabulary (бүс, ороолт, бээлий, оймс, хүрэм, гутал) paired with specialized dressing verbs (өмсөх, бүслэх, зүүх, углах).",
            "communicativeOutcome": "Describe getting dressed for different weather conditions using reflexive possession on each article of clothing.",
            "objectivesIntroduced": ["obj_a2_75_02_wardrobe_verbs_lexicon"],
            "objectivesPracticed": ["obj_a2_75_01_reflexive_possessive_marking"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_reflexive_possessive_base"],
            "grammarReviewed": ["gram_a1_verb_tense_present_habitual_dag", "gram_a1_converb_coordinating_j_ch"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_consonant_clusters"], "phonologyReviewed": ["phono_a1_vowel_reduction_non_initial"],
            "communicativeFunctionsIntroduced": ["comm_a2_02_describing_appearance_clothing"],
            "communicativeFunctionsPracticed": ["comm_a1_17_describing_daily_routines"], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_clothing_fashion", "lex_domain_daily_routines"],
            "previousVocabularyReused": ["хүйтэн", "гадаа", "гарах", "өмсөх", "зүүх", "хүрэм"],
            "readingObjective": "Read a weather advisory instructing citizens how to bundle up for -30°C winter temperatures.",
            "listeningObjective": "Understand parent instructing child to put on hat, scarf, and mittens before leaving.",
            "writingObjective": "Write a 4-sentence daily morning dressing checklist using reflexive nouns.",
            "spokenProductionObjective": "Describe your winter outfit: 'Би дулаан хүрэм өмсөж, ороолтоо зүүж, бээлийгээ өмсөнө'.",
            "registerTarget": "Everyday personal and family routine register",
            "pragmaticTarget": "Selecting culturally accurate dressing verbs (өмсөх for garments, зүүх for scarves/jewelry/watches, бүслэх for sashes).",
            "prerequisiteLessonIds": ["les_a2_75_01_reflexive_possessive_base_intro"],
            "reviewsLessonIds": ["les_a1_38_01_habitual_routines_intro"],
            "reviewsUnitIds": ["unit_a1_38_habitual_present_verbal_aspect_suff"],
            "reviewReason": "Links habitual daily routines (-даг) with reflexive wardrobe dressing.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Pronounce paired clothing items and corresponding dressing verbs.",
            "successCriteria": [
                "Applies appropriate verb for each accessory: малгайгаа өмсөх, ороолтоо зүүх, бүсээ бүслэх",
                "Marks all possessed clothing items with reflexive-possessive suffix"
            ],
            "masteryEvidence": "Accurately matches 6 clothing articles with their specific dressing verbs and adds reflexive endings.",
            "recommendedExerciseModalities": ["matching", "contextual_cloze", "sentence_construction"]
        },
        {
            "lessonId": "les_a2_75_03_dressing_for_celebration_dialogue",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 3,
            "title": "Preparing for Tsagaan Sar: Traditional Deel & Festive Attire",
            "lessonType": "dialogue_work",
            "primaryPurpose": "Develop spoken conversational fluency discussing festival attire, traditional deel colors, matching sashes, and family preparations.",
            "communicativeOutcome": "Discuss what you and your family are wearing for a major holiday (Tsagaan Sar or Naadam) using reflexive forms.",
            "objectivesIntroduced": ["obj_a2_75_03_festive_attire_dialogue"],
            "objectivesPracticed": ["obj_a2_75_01_reflexive_possessive_marking", "obj_a2_75_02_wardrobe_verbs_lexicon"],
            "objectivesReviewed": ["obj_a1_22_01_making_purchases"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_reflexive_possessive_base"],
            "grammarReviewed": ["gram_a1_verb_tense_future_prospective_na", "gram_a1_converb_sequential_aad"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_intonation_polite"], "phonologyReviewed": ["phono_a1_diphthongs"],
            "communicativeFunctionsIntroduced": ["comm_a2_02_describing_appearance_clothing"],
            "communicativeFunctionsPracticed": ["comm_a1_20_expressing_intentions"],
            "communicativeFunctionsReviewed": ["comm_a1_16_greetings_time_of_day"],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_clothing_fashion", "lex_domain_culture_traditions"],
            "previousVocabularyReused": ["баяр", "дээл", "өнгө", "бүс", "гутал", "сайхан"],
            "readingObjective": "",
            "listeningObjective": "Follow a family member's description of tailoring new silk deels for the coming celebration.",
            "writingObjective": "",
            "spokenProductionObjective": "Describe festival preparation: 'Би энэ Цагаан сараар цэнхэр торгон дээлээ өмсөж, шар бүсээ бүслэнэ'.",
            "registerTarget": "Warm cultural conversational register",
            "pragmaticTarget": "Appreciating the cultural pride associated with wearing finely coordinated national costume.",
            "prerequisiteLessonIds": ["les_a2_75_02_wardrobe_dressing_reflexive_lexicon"],
            "reviewsLessonIds": ["les_a1_48_01_volitional_ya_intro"],
            "reviewsUnitIds": ["unit_a1_48_volitional_intention_suffixes_"],
            "reviewReason": "Combines prospective and volitional intentions with traditional holiday wear.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Authentic conversational tone of family holiday preparations.",
            "successCriteria": [
                "Accurately describes traditional festival attire using reflexive suffixes",
                "Distinguishes between subject's own deel (дээлээ) and another person's deel (дээлийг нь)"
            ],
            "masteryEvidence": "Engages in a 4-turn dialogue describing personal festival outfit and family accessories.",
            "recommendedExerciseModalities": ["role-play response", "dialogue_completion", "listening_comprehension"]
        },
        {
            "lessonId": "les_a2_75_04_wardrobe_narrative_listening",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 4,
            "title": "Acoustic Lab: Parsing Reflexive Pronouns in Narrative Monologues",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop focused auditory discrimination between reflexive-possessive nouns (-аа4) and non-reflexive accusative/genitive nouns in narrative speech.",
            "communicativeOutcome": "Distinguish whether an actor in a narrative is taking their own belongings or someone else's belongings based solely on auditory case morphology.",
            "objectivesIntroduced": ["obj_a2_75_04_discriminate_reflexive_audio"],
            "objectivesPracticed": ["obj_a2_75_01_reflexive_possessive_marking"], "objectivesReviewed": ["obj_a1_30_01_accusative_definite"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_accusative_definite_object", "gram_a1_case_genitive_possession"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_vowel_length_distinction"], "phonologyReviewed": ["phono_a1_nasal_vowels"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_02_describing_appearance_clothing"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_clothing_fashion", "lex_domain_family_kinship"],
            "previousVocabularyReused": ["машин", "түлхүүр", "цүнх", "авах", "өгөх", "гэр"],
            "readingObjective": "",
            "listeningObjective": "Determine possession ownership (own vs another's) across 6 audio sentence pairs (e.g. 'Машинаа уналаа' vs 'Машиныг нь уналаа').",
            "writingObjective": "",
            "spokenProductionObjective": "Explain to a peer who owned the item in each audio clip.",
            "registerTarget": "Standard narrative audio register",
            "pragmaticTarget": "Auditory precision in identifying crucial possessive grammatical distinctions.",
            "prerequisiteLessonIds": ["les_a2_75_02_wardrobe_dressing_reflexive_lexicon"],
            "reviewsLessonIds": ["les_a1_30_03_accusative_listening_comprehension"],
            "reviewsUnitIds": ["unit_a1_30_accusative_definite_direct_object_s"],
            "reviewReason": "Sharpens phonological discrimination between accusative (-ыг/-ийг) and reflexive (-аа4).",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Provide high-clarity native speech contrasting minimal pairs in possessive endings.",
            "successCriteria": [
                "Achieves 100% accuracy distinguishing reflexive -аа from third-person -ийг нь in audio pairs",
                "Correctly identifies the owner of lost or exchanged items in short audio stories"
            ],
            "masteryEvidence": "Accurately categorizes 6 audio sentences into 'subject's own property' vs 'other person's property'.",
            "recommendedExerciseModalities": ["listening_comprehension", "phonetic_discrimination", "categorization"]
        },
        {
            "lessonId": "les_a2_75_05_festival_wardrobe_essay_writing",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 5,
            "title": "Festive Wardrobe: Writing an Account of Personal Holiday Attire",
            "lessonType": "grammar_guided_practice",
            "primaryPurpose": "Synthesize reflexive-possessive morphology, clothing terminology, and colors in a coherent personal written description.",
            "communicativeOutcome": "Compose a 5-6 sentence descriptive paragraph explaining your holiday attire, boots, accessories, and preparation routine.",
            "objectivesIntroduced": ["obj_a2_75_05_write_wardrobe_account"],
            "objectivesPracticed": ["obj_a2_75_01_reflexive_possessive_marking", "obj_a2_75_02_wardrobe_verbs_lexicon"],
            "objectivesReviewed": ["obj_a1_50_01_sequential_converb"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_reflexive_possessive_base"],
            "grammarReviewed": ["gram_a1_converb_sequential_aad", "gram_a1_noun_phrase_attributive_adjective"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_02_describing_appearance_clothing"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_clothing_fashion", "lex_domain_culture_traditions"],
            "previousVocabularyReused": ["дээл", "хүрэм", "гутал", "малгай", "бэлтгэх", "гоёх"],
            "readingObjective": "Read a peer's festival attire essay to check for correct reflexive suffixation.",
            "listeningObjective": "",
            "writingObjective": "Draft a 6-sentence paragraph describing your festival clothing using at least 4 reflexive-possessive nouns.",
            "spokenProductionObjective": "",
            "registerTarget": "Descriptive personal narrative register",
            "pragmaticTarget": "Expressing cultural elegance and personal identity through polished written Mongolian.",
            "prerequisiteLessonIds": ["les_a2_75_03_dressing_for_celebration_dialogue", "les_a2_75_04_wardrobe_narrative_listening"],
            "reviewsLessonIds": ["les_a1_50_02_sequential_daily_routine_texts"],
            "reviewsUnitIds": ["unit_a1_50_sequential_converb_clause_connector"],
            "reviewReason": "Utilizes sequential converb clauses (-аад) to structure the sequence of dressing up.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Read back written personal essay for grammatical auditing.",
            "successCriteria": [
                "Writes a coherent paragraph with at least 4 correctly formed reflexive-possessive nouns",
                "Accurately pairs garments with appropriate dressing verbs (өмсөх, зүүх, бүслэх)"
            ],
            "masteryEvidence": "Produces 'Би баяраар шинэ дээлээ өмсөж, тоногтой мөнгөн бүсээ бүслээд, монгол гутлаа өмсөнө' flawlessly.",
            "recommendedExerciseModalities": ["short-answer writing", "sentence construction", "error correction"]
        }
    ])

    # =========================================================================
    # UNIT 76: Reflexive Case Combinations (-аасаа, -даа, -аараа, -тайгаа) (pos 76)
    # 6 Lessons | Targets: ProdLem=21, RecLem=10, ProdExp=5, RecExp=3
    # Budget: (4,2,1,1), (6,3,1,1), (0,0,0,0), (5,3,1,0), (4,2,2,1), (2,0,0,0) = (21, 10, 5, 3)
    # =========================================================================
    u = u_map[76]
    uid = u["unitId"]
    lessons.extend([
        {
            "lessonId": "les_a2_76_01_reflexive_case_morphology_overview",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 1,
            "title": "Fused Suffixes: Combining Cases with Reflexive Possession",
            "lessonType": "grammar_introduction",
            "primaryPurpose": "Introduce the synthetic fusion of case suffixes with the reflexive-possessive morpheme: Ablative (-аасаа4), Dative-Locative (-даа4), Instrumental (-аараа4), and Comitative (-тайгаа4).",
            "communicativeOutcome": "Express actions originating from, located at, or done with one's own people and possessions (e.g. 'Гэрээсээ гарлаа', 'Ахтайгаа уулзлаа', 'Машинаараа явлаа').",
            "objectivesIntroduced": ["obj_a2_76_01_reflexive_case_combination"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_a2_75_01_reflexive_possessive_marking"],
            "grammarIntroduced": ["gram_a2_reflexive_case_combinations"],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_ablative_origin", "gram_a1_case_comitative_association"],
            "phonologyIntroduced": ["phono_a2_reflexive_case_allomorphy"],
            "phonologyPracticed": ["phono_a1_masculine_feminine_harmony"], "phonologyReviewed": ["phono_a1_long_vowels"],
            "communicativeFunctionsIntroduced": ["comm_a2_02_describing_appearance_clothing"],
            "communicativeFunctionsPracticed": ["comm_a1_17_describing_daily_routines"], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 4, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_family_kinship", "lex_domain_daily_routines"],
            "previousVocabularyReused": ["гэр", "сургууль", "найз", "ах", "эгч", "явах"],
            "readingObjective": "Read personal journal entries highlighting reflexive case combinations.",
            "listeningObjective": "Identify fused reflexive case endings in conversational speech.",
            "writingObjective": "Combine 4 root nouns with ablative-reflexive, comitative-reflexive, and instrumental-reflexive suffixes.",
            "spokenProductionObjective": "Explain personal movements: 'Би гэрээсээ гараад, найзтайгаа хамт сургууль руугаа явлаа'.",
            "registerTarget": "Standard everyday conversational and narrative register",
            "pragmaticTarget": "Using synthetic fused case-reflexive endings effortlessly in continuous speech.",
            "prerequisiteLessonIds": ["les_a2_75_01_reflexive_possessive_base_intro"],
            "reviewsLessonIds": ["les_a1_40_01_ablative_origin_intro", "les_a1_32_01_comitative_case_intro"],
            "reviewsUnitIds": ["unit_a1_40_ablative_of_spatial_temporal_origin", "unit_a1_32_comitative_case_accompaniment_instr"],
            "reviewReason": "Fuses previously mastered A1 independent case suffixes with the A2 reflexive system.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Demonstrate phonological fusion and long vowel duration in fused case-reflexive endings.",
            "successCriteria": [
                "Correctly selects fused form: -аасаа (from own), -даа (at/to own), -аараа (by own), -тайгаа (with own)",
                "Respects root vowel harmony across all four cases"
            ],
            "masteryEvidence": "Produces 'Би өөрийнхөө машинаараа найзынхаа гэр рүү явлаа' without morphological error.",
            "recommendedExerciseModalities": ["suffix_selection", "sentence_construction", "case_marking"]
        },
        {
            "lessonId": "les_a2_76_02_comitative_reflexive_social_lexicon",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 2,
            "title": "With My Family & Friends: The Comitative Reflexive (-тайгаа4)",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Master the comitative reflexive suffix (-тайгаа4 / -тойгоо / -тэйгээ / -төөгөө) in social contexts: spending time with one's spouse, children, colleagues, and siblings.",
            "communicativeOutcome": "Describe social gatherings and family leisure activities with one's own companions (e.g. 'Гэр бүлийнхэнтэйгээ амарлаа', 'Хүүхдүүдтэйгээ тоглолоо').",
            "objectivesIntroduced": ["obj_a2_76_02_comitative_reflexive_social"],
            "objectivesPracticed": ["obj_a2_76_01_reflexive_case_combination"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_reflexive_case_combinations"],
            "grammarReviewed": ["gram_a1_case_comitative_association", "gram_a1_verb_tense_past_witnessed_laa"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_consonant_clusters"], "phonologyReviewed": ["phono_a1_vowel_reduction_non_initial"],
            "communicativeFunctionsIntroduced": ["comm_a2_02_describing_appearance_clothing"],
            "communicativeFunctionsPracticed": ["comm_a1_17_describing_daily_routines"], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_family_kinship", "lex_domain_social_interaction"],
            "previousVocabularyReused": ["гэр бүл", "хүүхэд", "найз", "хамт", "уулзах", "ярилцах"],
            "readingObjective": "Read social media posts describing weekend outings with one's relatives and peers.",
            "listeningObjective": "Understand friends recounting weekend trips taken with their respective families.",
            "writingObjective": "List 4 weekend activities performed together with your own family members.",
            "spokenProductionObjective": "Explain weekend plans: 'Би амралтын өдрөөр аав ээжтэйгээ хөдөө явна'.",
            "registerTarget": "Warm interpersonal conversational register",
            "pragmaticTarget": "Expressing affectionate familial closeness naturally through comitative-reflexive marking.",
            "prerequisiteLessonIds": ["les_a2_76_01_reflexive_case_morphology_overview"],
            "reviewsLessonIds": ["les_a1_32_02_comitative_family_companions"],
            "reviewsUnitIds": ["unit_a1_32_comitative_case_accompaniment_instr"],
            "reviewReason": "Expands simple comitative companion phrases into reflexive family togetherness.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Model comitative reflexive vowel harmony combinations.",
            "successCriteria": [
                "Selects correct vowel harmony allomorph (-тайгаа, -тэйгээ, -тойгоо, -төөгөө)",
                "Expresses shared activities with family without redundant possessive pronouns"
            ],
            "masteryEvidence": "Utters 'Би дүүтэйгээ хамт кино үзсэн' with fluent pronunciation and correct suffixation.",
            "recommendedExerciseModalities": ["contextual_cloze", "sentence_construction", "matching"]
        },
        {
            "lessonId": "les_a2_76_03_reflexive_acoustic_discrimination_lab",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 3,
            "title": "Acoustic Lab: Discriminating Case-Reflexive Fusions in Fast Speech",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop acoustic listening comprehension of fast conversational contractions of case-reflexive fusions (-аасаа, -даа, -аараа, -тайгаа) in rapid speech.",
            "communicativeOutcome": "Correctly identify originating place (-аасаа), destination/location (-даа), instrument (-аараа), or companion (-тайгаа) from rapid spoken clips.",
            "objectivesIntroduced": ["obj_a2_76_03_decode_reflexive_case_speech"],
            "objectivesPracticed": ["obj_a2_76_01_reflexive_case_combination"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a2_reflexive_case_combinations"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_vowel_reduction_non_initial"], "phonologyReviewed": ["phono_a1_nasal_vowels"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_02_describing_appearance_clothing"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_family_kinship", "lex_domain_actions_movement"],
            "previousVocabularyReused": ["гэр", "өрөө", "машин", "найз", "гарах", "орох"],
            "readingObjective": "",
            "listeningObjective": "Identify specific case-reflexive suffix across 8 rapid speech audio items and match with semantic role.",
            "writingObjective": "",
            "spokenProductionObjective": "Repeat overheard case-reflexive phrases with accurate vowel harmony.",
            "registerTarget": "Rapid natural conversational register",
            "pragmaticTarget": "Parsing reduced case-reflexive vowels in unscripted colloquial exchanges.",
            "prerequisiteLessonIds": ["les_a2_76_02_comitative_reflexive_social_lexicon"],
            "reviewsLessonIds": ["les_a1_40_03_ablative_listening_comprehension"],
            "reviewsUnitIds": ["unit_a1_40_ablative_of_spatial_temporal_origin"],
            "reviewReason": "Tests auditory comprehension of complex fused ablative endings.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Provide natural native conversational clips with fast elision of case endings.",
            "successCriteria": [
                "Correctly classifies auditory stimuli into ablative (-аасаа), dative (-даа), instrumental (-аараа), or comitative (-тайгаа)",
                "Differentiates 'гэртээ' (at/to own home) from 'гэрээсээ' (from own home) without hesitation"
            ],
            "masteryEvidence": "Achieves 100% accuracy on an 8-item rapid speech case-reflexive discrimination quiz.",
            "recommendedExerciseModalities": ["listening_comprehension", "phonetic_discrimination", "categorization"]
        },
        {
            "lessonId": "les_a2_76_04_reading_family_memoirs_letters",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 4,
            "title": "Deciphering Personal Letters: Family Chronicles & Homecoming",
            "lessonType": "reading_development",
            "primaryPurpose": "Develop reading comprehension for personal correspondence, family emails, and travel memoirs rich in case-reflexive structures.",
            "communicativeOutcome": "Read an authentic personal email describing leaving one's hometown, traveling with siblings, and returning to one's parents.",
            "objectivesIntroduced": ["obj_a2_76_04_read_family_memoirs"],
            "objectivesPracticed": ["obj_a2_76_01_reflexive_case_combination"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_reflexive_case_combinations"],
            "grammarReviewed": ["gram_a1_case_ablative_origin", "gram_a1_case_dative_locative_location"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_02_describing_appearance_clothing"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_family_kinship", "lex_domain_transportation_travel"],
            "previousVocabularyReused": ["нутгаасаа", "гэртээ", "аавтайгаа", "буцах", "хүрэх", "санах"],
            "readingObjective": "Extract chronological travel milestones and family encounters from a 120-word personal email.",
            "listeningObjective": "",
            "writingObjective": "Transcribe key case-reflexive sentences from the letter into a study journal.",
            "spokenProductionObjective": "Summarize the writer's journey to a partner in 3 Mongolian sentences.",
            "registerTarget": "Intimate personal correspondence register",
            "pragmaticTarget": "Appreciating emotional resonance of homecoming themes in Mongolian cultural writing.",
            "prerequisiteLessonIds": ["les_a2_76_02_comitative_reflexive_social_lexicon"],
            "reviewsLessonIds": ["les_a1_33_02_reading_short_family_narratives"],
            "reviewsUnitIds": ["unit_a1_33_immediate_family_kinship_terms_ex"],
            "reviewReason": "Expands basic kinship narratives into syntactically complex autobiographical letters.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Expressive narration of personal family letter.",
            "successCriteria": [
                "Answers 5 comprehension questions regarding who traveled with whom, from where, and to whose home",
                "Identifies all 4 case-reflexive suffix instances in the text"
            ],
            "masteryEvidence": "Accurately maps the writer's itinerary and companion interactions based on reading passage.",
            "recommendedExerciseModalities": ["reading_comprehension", "contextual_cloze", "matching"]
        },
        {
            "lessonId": "les_a2_76_05_family_reunion_dialogue",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 5,
            "title": "Family Reunion: Sharing News of Relatives & Travel Plans",
            "lessonType": "dialogue_work",
            "primaryPurpose": "Develop spoken conversational fluency during family gatherings, discussing travel from one's hometown, visiting siblings, and shared projects.",
            "communicativeOutcome": "Conduct a conversation at a family reunion explaining who you traveled with, how you arrived, and whose home you are staying at.",
            "objectivesIntroduced": ["obj_a2_76_05_family_reunion_dialogue"],
            "objectivesPracticed": ["obj_a2_76_01_reflexive_case_combination", "obj_a2_76_02_comitative_reflexive_social"],
            "objectivesReviewed": ["obj_a1_16_01_greet_time_of_day"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_reflexive_case_combinations"],
            "grammarReviewed": ["gram_a1_converb_coordinating_j_ch", "gram_a1_verb_tense_past_witnessed_laa"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_intonation_polite"], "phonologyReviewed": ["phono_a1_vowel_length_distinction"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_02_describing_appearance_clothing", "comm_a1_17_describing_daily_routines"],
            "communicativeFunctionsReviewed": ["comm_a1_16_greetings_time_of_day"],
            "newProductiveLemmaTarget": 4, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_family_kinship", "lex_domain_social_interaction"],
            "previousVocabularyReused": ["уулзах", "ярих", "сонин", "сайхан", "хөдөө", "хот"],
            "readingObjective": "",
            "listeningObjective": "Understand relative asking about your trip: 'Та хэзээ нутгаасаа гарсан бэ? Машинаараа ирсэн үү?'.",
            "writingObjective": "",
            "spokenProductionObjective": "Explain trip details: 'Би өчигдөр өглөө хотоосоо гараад, ахтайгаа хамт машинтайгаа ирлээ'.",
            "registerTarget": "Warm respectful kinship conversational register",
            "pragmaticTarget": "Greeting elder relatives with appropriate respectful questions and sharing news modestly.",
            "prerequisiteLessonIds": ["les_a2_76_03_reflexive_acoustic_discrimination_lab", "les_a2_76_04_reading_family_memoirs_letters"],
            "reviewsLessonIds": ["les_a1_33_03_kinship_dialogues"],
            "reviewsUnitIds": ["unit_a1_33_immediate_family_kinship_terms_ex"],
            "reviewReason": "Recycles kinship vocabulary in spontaneous adult social gatherings.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Deliver warm, authentic family reunion dialogue with authentic elder and peer voices.",
            "successCriteria": [
                "Conducts a smooth 5-turn exchange using at least 3 distinct case-reflexive endings",
                "Answers kinship questions accurately without hesitation"
            ],
            "masteryEvidence": "Completes simulated family reunion dialogue with accurate case endings and natural politeness.",
            "recommendedExerciseModalities": ["role-play response", "dialogue_completion", "listening_comprehension"]
        },
        {
            "lessonId": "les_a2_76_06_personal_journey_written_memoir",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 6,
            "title": "Homecoming Memoir: Writing Personal Travel Chronology",
            "lessonType": "grammar_guided_practice",
            "primaryPurpose": "Consolidate all four reflexive case combinations (-аасаа, -даа, -аараа, -тайгаа) into an extended written autobiographical reflection.",
            "communicativeOutcome": "Write a 6-8 sentence personal narrative detailing leaving home, traveling with loved ones, and returning to one's own hearth.",
            "objectivesIntroduced": ["obj_a2_76_06_write_homecoming_memoir"],
            "objectivesPracticed": ["obj_a2_76_01_reflexive_case_combination", "obj_a2_76_05_family_reunion_dialogue"],
            "objectivesReviewed": ["obj_a1_50_01_sequential_clauses"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_reflexive_case_combinations"],
            "grammarReviewed": ["gram_a1_converb_sequential_aad", "gram_a1_verb_tense_past_perfective_san"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_02_describing_appearance_clothing"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 2, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_family_kinship", "lex_domain_actions_movement"],
            "previousVocabularyReused": ["гэр", "нутаг", "аялал", "дурсамж", "буцах", "хүрэх"],
            "readingObjective": "Proofread a peer's draft memoir for case harmony and spelling accuracy.",
            "listeningObjective": "",
            "writingObjective": "Draft a 6-8 sentence memoir including ablative-reflexive, dative-reflexive, instrumental-reflexive, and comitative-reflexive structures.",
            "spokenProductionObjective": "",
            "registerTarget": "Expressive written autobiographical register",
            "pragmaticTarget": "Synthesizing morphological complexity into fluent, emotionally coherent Mongolian prose.",
            "prerequisiteLessonIds": ["les_a2_76_05_family_reunion_dialogue"],
            "reviewsLessonIds": ["les_a1_50_01_sequential_converb_aad"],
            "reviewsUnitIds": ["unit_a1_50_sequential_converb_clause_connector"],
            "reviewReason": "Links sequential converb chains with advanced synthetic case-reflexive nominals.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Read back generated memoir for prosodic and syntactic validation.",
            "successCriteria": [
                "Produces a coherent narrative correctly integrating all 4 case-reflexive fusions",
                "Demonstrates accurate vowel harmony across all suffixed stems"
            ],
            "masteryEvidence": "Drafts 'Би зун нутгаасаа гараад, дүүтэйгээ машинаараа явж, ээжийнхээ гэртээ очсон...' flawlessly.",
            "recommendedExerciseModalities": ["short-answer writing", "clause_combination", "error correction"]
        }
    ])

    return lessons
