"""
Section 4 Generator Part 2 (Units 96 - 98): 15 Lessons
96: Recurring Weekend Pastimes: Habitual Aspect -даг4 (5 lessons)
97: Social Invitations & Personal Desires: Participle -маар4 (5 lessons)
98: Purposive Intentions & Plans: Converb -хаар4 (5 lessons)
"""

import json
from typing import List, Dict, Any

def get_sec04_part2_lessons(u_map: Dict[int, Any]) -> List[Dict[str, Any]]:
    lessons: List[Dict[str, Any]] = []

    # =========================================================================
    # UNIT 96: Recurring Weekend Pastimes: Habitual Aspect -даг4 (pos 96)
    # 5 Lessons | Targets: ProdLem=21, RecLem=10, ProdExp=5, RecExp=3
    # Budget: (5,2,1,1), (6,3,1,1), (5,3,2,1), (0,0,0,0), (5,2,1,0) = (21, 10, 5, 3)
    # =========================================================================
    u = u_map[96]
    uid = u["unitId"]
    lessons.extend([
        {
            "lessonId": "les_a2_96_01_habitual_aspect_pastimes_intro",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 1,
            "title": "Weekend Rhythms: The Habitual Aspect (-даг/-дэг/-дог/-дөг)",
            "lessonType": "grammar_introduction",
            "primaryPurpose": "Deepen the habitual aspect suffix (-даг4 / -дэг / -дог / -дөг) to describe regular hobbies, recurring weekend traditions, cultural visits, and lifestyle habits.",
            "communicativeOutcome": "Explain regular leisure routines: 'Би хагас сайн өдөр бүр ууланд алхдаг' (I hike in the mountains every Saturday), 'Манай гэр бүл амралтын өдрөөр музей үздэг' (Our family visits museums on weekends).",
            "objectivesIntroduced": ["obj_a2_96_01_habitual_aspect_expansion"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_a2_95_01_witnessed_past_travel_expansion"],
            "grammarIntroduced": ["gram_a2_verb_habitual_present_dag"],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_dative_locative_time", "gram_a1_predicate_adjective_nominal"],
            "phonologyIntroduced": ["phono_a2_habitual_aspect_cadence"],
            "phonologyPracticed": ["phono_a1_masculine_feminine_harmony"], "phonologyReviewed": ["phono_a1_consonant_clusters"],
            "communicativeFunctionsIntroduced": ["comm_a2_06_weekend_activities_past"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_recreation_leisure", "lex_domain_daily_routines"],
            "previousVocabularyReused": ["өдөр", "амралт", "хийх", "явах", "үзэх", "тоглох"],
            "readingObjective": "Read a lifestyle survey article detailing how Ulaanbaatar residents spend their leisure hours.",
            "listeningObjective": "Identify habitual verbal endings in -даг4 in conversational audio interviews.",
            "writingObjective": "Write 4 sentences detailing your recurring weekly hobbies using -даг4.",
            "spokenProductionObjective": "Explain weekend habits: 'Би бүтэн сайн өдөр номын санд сууж ном уншдаг'.",
            "registerTarget": "Standard everyday leisure and lifestyle register",
            "pragmaticTarget": "Using habitual aspect (-даг4) to describe established regular customs rather than single isolated events.",
            "prerequisiteLessonIds": ["les_a2_95_01_witnessed_past_travel_accounts_intro"],
            "reviewsLessonIds": ["les_a1_38_01_habitual_routines_intro"],
            "reviewsUnitIds": ["unit_a1_38_habitual_present_verbal_aspect_suff"],
            "reviewReason": "Expands daily morning routines into rich cultural pastimes and recreational traditions.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Model rhythmic articulation of habitual suffix (-даг/-дэг/-дог/-дөг).",
            "successCriteria": [
                "Selects correct harmonic variant of -даг4 based on verb stem vowel",
                "Contrasts recurring habits (-даг) with immediate witnessed events (-лаа)"
            ],
            "masteryEvidence": "Produces 'Би өглөө бүр гүйдэг, харин өчигдөр ууланд алхлаа' with clear aspectual contrast.",
            "recommendedExerciseModalities": ["suffix_selection", "sentence_construction", "matching"]
        },
        {
            "lessonId": "les_a2_96_02_cultural_outings_arts_lexicon",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 2,
            "title": "Opera, Galleries & Concerts: Cultural Outings Vocabulary",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Introduce cultural entertainment, performance arts, and museum vocabulary (дуурь бүжгийн эрдмийн театр, уран зургийн галерей, цирк, тоглолт үзэх, үзэсгэлэн, тасалбар захиалах).",
            "communicativeOutcome": "Talk about attending classical opera, art exhibitions, traditional concerts, and booking performance tickets.",
            "objectivesIntroduced": ["obj_a2_96_02_cultural_outings_lexicon"],
            "objectivesPracticed": ["obj_a2_96_01_habitual_aspect_expansion"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_verb_habitual_present_dag"],
            "grammarReviewed": ["gram_a1_case_accusative_definite", "gram_a1_case_dative_locative_location"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_consonant_clusters"], "phonologyReviewed": ["phono_a1_vowel_reduction_non_initial"],
            "communicativeFunctionsIntroduced": ["comm_a2_06_weekend_activities_past"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_arts_entertainment", "lex_domain_culture_traditions"],
            "previousVocabularyReused": ["театр", "урлаг", "зураг", "дуу", "үзэх", "хөгжим"],
            "readingObjective": "Read a monthly cultural event poster for the National Academic Theatre of Opera and Ballet.",
            "listeningObjective": "Understand friends debating whether to attend a folk orchestra concert or an art gallery opening.",
            "writingObjective": "List 5 cultural venues in Ulaanbaatar in Cyrillic.",
            "spokenProductionObjective": "Describe cultural outings: 'Манай гэр бүл сард нэг удаа дуурийн театрт очиж сонгодог балет үздэг'.",
            "registerTarget": "Refined cultural arts and recreation register",
            "pragmaticTarget": "Expressing artistic appreciation and engaging in metropolitan cultural life.",
            "prerequisiteLessonIds": ["les_a2_96_01_habitual_aspect_pastimes_intro"],
            "reviewsLessonIds": ["les_a1_54_01_recreation_entertainment_intro"],
            "reviewsUnitIds": ["unit_a1_54_entertainment_cinema_recreation_le"],
            "reviewReason": "Elevates cinema/sports vocabulary to fine arts, opera, and cultural exhibitions.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Pronounce cultural arts venues and genre terms clearly.",
            "successCriteria": [
                "Defines дуурь (opera), балет (ballet), үзэсгэлэн (exhibition), галерей (gallery)",
                "Forms sentences using habitual aspect describing cultural outing frequencies"
            ],
            "masteryEvidence": "Accurately plans and describes 3 distinct cultural outing itineraries in Ulaanbaatar.",
            "recommendedExerciseModalities": ["categorization", "contextual_cloze", "matching"]
        },
        {
            "lessonId": "les_a2_96_03_weekend_routines_exchange_dialogue",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 3,
            "title": "How Do You Unwind: Exchanging Weekend Habits with Coworkers",
            "lessonType": "dialogue_work",
            "primaryPurpose": "Develop spoken communicative fluency for Monday morning chats: discussing how you recharge on weekends, recurring sports activities, and favorite quiet spots.",
            "communicativeOutcome": "Exchange weekend leisure routines with a colleague, discuss favorite cafes or hiking trails, and compare habitual schedules.",
            "objectivesIntroduced": ["obj_a2_96_03_weekend_routines_dialogue"],
            "objectivesPracticed": ["obj_a2_96_01_habitual_aspect_expansion", "obj_a2_96_02_cultural_outings_lexicon"],
            "objectivesReviewed": ["obj_a1_16_01_greet_time_of_day"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_verb_habitual_present_dag"],
            "grammarReviewed": ["gram_a1_case_comitative_association", "gram_a1_polar_questions_uu_uu"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_intonation_polite"], "phonologyReviewed": ["phono_a1_diphthongs"],
            "communicativeFunctionsIntroduced": ["comm_a2_06_weekend_activities_past"],
            "communicativeFunctionsPracticed": ["comm_a1_16_greetings_time_of_day"],
            "communicativeFunctionsReviewed": ["comm_a1_13_apologies_politeness"],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_recreation_leisure", "lex_domain_social_interaction"],
            "previousVocabularyReused": ["амрах", "цаг", "өнгөрөөх", "хамт", "хэзээ", "дуртай"],
            "readingObjective": "",
            "listeningObjective": "Understand coworker sharing their Sunday routine of cycling in Bogd Khan mountain foothills.",
            "writingObjective": "",
            "spokenProductionObjective": "Explain regular weekend: 'Би амралтын өдрөөр эрт босоод, найзуудтайгаа сагс тоглодог. Орой нь гэр бүлээрээ амардаг'.",
            "registerTarget": "Friendly collegial workplace watercooler register",
            "pragmaticTarget": "Building social rapport on Monday mornings through pleasant personal exchanges.",
            "prerequisiteLessonIds": ["les_a2_96_02_cultural_outings_arts_lexicon"],
            "reviewsLessonIds": ["les_a1_43_05_past_weekend_activities_dialogue"],
            "reviewsUnitIds": ["unit_a1_43_past_witnessed_conversational_narr"],
            "reviewReason": "Shifts weekend discussions from specific past events to general habitual lifestyles.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Warm, cheerful Monday morning workplace dialogue between friendly colleagues.",
            "successCriteria": [
                "Expresses recurring activities using habitual verb forms in -даг4 accurately",
                "Asks partner engaged questions about their recreational preferences"
            ],
            "masteryEvidence": "Conducts a 5-turn weekend routine sharing dialogue highlighting 3 habitual pastimes.",
            "recommendedExerciseModalities": ["role-play response", "dialogue_completion", "listening_comprehension"]
        },
        {
            "lessonId": "les_a2_96_04_leisure_habits_survey_listening",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 4,
            "title": "Acoustic Lab: Street Interviews on City Leisure & Fitness Habits",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop acoustic listening comprehension of spontaneous street interviews with diverse citizens describing their weekly exercise, reading, and cinema habits.",
            "communicativeOutcome": "Extract frequency details (өдөр бүр, хааяа, сард нэг, долоо хоногт хоёр удаа) and habitual pastimes from unscripted interview audio.",
            "objectivesIntroduced": ["obj_a2_96_04_decode_leisure_surveys"],
            "objectivesPracticed": ["obj_a2_96_01_habitual_aspect_expansion"], "objectivesReviewed": ["obj_a1_27_01_counting_tens_hundreds"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a2_verb_habitual_present_dag", "gram_a1_adverbs_frequency_hed_hed"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_vowel_reduction_non_initial"], "phonologyReviewed": ["phono_a1_nasal_vowels"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_06_weekend_activities_past"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_recreation_leisure"],
            "previousVocabularyReused": ["хүмүүс", "чөлөөт цаг", "спорт", "байнга", "хааяа", "сонирхол"],
            "readingObjective": "",
            "listeningObjective": "Identify specific recreational activities and frequencies across 3 diverse street interviewees.",
            "writingObjective": "",
            "spokenProductionObjective": "Summarize the survey findings to a partner in 3 Mongolian sentences.",
            "registerTarget": "Spontaneous public street interview register",
            "pragmaticTarget": "Parsing varied colloquial accents and ambient street acoustics.",
            "prerequisiteLessonIds": ["les_a2_96_02_cultural_outings_arts_lexicon"],
            "reviewsLessonIds": ["les_a1_62_03_workplace_interviews_listening"],
            "reviewsUnitIds": ["unit_a1_62_workplace_interactions_routines_po"],
            "reviewReason": "Applies interview listening skills to leisure and lifestyle surveys.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Dynamic street interview clips with authentic city background ambience.",
            "successCriteria": [
                "Identifies each interviewee's primary hobby correctly from audio",
                "Associates each hobby with its stated frequency adverb (байнга, хааяа, огт үгүй)"
            ],
            "masteryEvidence": "Accurately completes a lifestyle survey grid based on 3 spoken interviews.",
            "recommendedExerciseModalities": ["listening_comprehension", "phonetic_discrimination", "categorization"]
        },
        {
            "lessonId": "les_a2_96_05_leisure_profile_essay_writing",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 5,
            "title": "Lifestyle Portrait: Composing a Personal Leisure & Hobbies Essay",
            "lessonType": "grammar_guided_practice",
            "primaryPurpose": "Synthesize habitual aspect verbs (-даг4), leisure vocabulary, and frequency adverbs into a written personal essay (Миний чөлөөт цаг ба сонирхол).",
            "communicativeOutcome": "Write a 6-sentence personal essay detailing your leisure habits, how you balance work and relaxation, and hobbies you pursue regularly.",
            "objectivesIntroduced": ["obj_a2_96_05_write_leisure_profile"],
            "objectivesPracticed": ["obj_a2_96_01_habitual_aspect_expansion", "obj_a2_96_02_cultural_outings_lexicon"],
            "objectivesReviewed": ["obj_a1_50_01_sequential_converb"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_verb_habitual_present_dag"],
            "grammarReviewed": ["gram_a1_converb_coordinating_j_ch", "gram_a1_case_comitative_association"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_06_weekend_activities_past"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_recreation_leisure", "lex_domain_daily_routines"],
            "previousVocabularyReused": ["чөлөөт цаг", "сонирхол", "бичих", "ном", "спорт", "өнгөрөөх"],
            "readingObjective": "Review a model personal lifestyle profile from a student magazine.",
            "listeningObjective": "",
            "writingObjective": "Draft a 6-sentence leisure profile utilizing at least 3 verbs in -даг4 and 2 frequency adverbs.",
            "spokenProductionObjective": "",
            "registerTarget": "Reflective written personal profile register",
            "pragmaticTarget": "Expressing well-rounded personal interests with structured, coherent paragraphs.",
            "prerequisiteLessonIds": ["les_a2_96_03_weekend_routines_exchange_dialogue", "les_a2_96_04_leisure_habits_survey_listening"],
            "reviewsLessonIds": ["les_a1_50_01_sequential_converb_aad"],
            "reviewsUnitIds": ["unit_a1_50_sequential_converb_clause_connector"],
            "reviewReason": "Combines coordinating clauses with habitual aspect predicates.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Audio read-back of written personal leisure profile.",
            "successCriteria": [
                "Produces written profile using at least 3 correctly formed verbs in -даг4",
                "Demonstrates lexical variety covering physical fitness, reading, or arts"
            ],
            "masteryEvidence": "Drafts 'Би чөлөөт цагаараа уран зохиолын ном унших дуртай. Мөн долоо хоногт хоёр удаа усан санд сэлдэг...' flawlessly.",
            "recommendedExerciseModalities": ["short-answer writing", "sentence construction", "error correction"]
        }
    ])

    # =========================================================================
    # UNIT 97: Social Invitations & Personal Desires: Participle -маар4 (pos 97)
    # 5 Lessons | Targets: ProdLem=21, RecLem=10, ProdExp=5, RecExp=3
    # Budget: (5,2,1,1), (6,3,1,1), (5,3,2,1), (0,0,0,0), (5,2,1,0) = (21, 10, 5, 3)
    # =========================================================================
    u = u_map[97]
    uid = u["unitId"]
    lessons.extend([
        {
            "lessonId": "les_a2_97_01_desiderative_participle_maar_intro",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 1,
            "title": "I'd Love to: The Desiderative Participle (-маар/-мээр/-моор/-мөөр)",
            "lessonType": "grammar_introduction",
            "primaryPurpose": "Introduce the desiderative/inclination participle (-маар4 / -мээр / -моор / -мөөр + байна/санагдах) expressing personal desire, wish, or inclination ('would like to do').",
            "communicativeOutcome": "Express polite personal wishes and desires: 'Би халуун кофе уумаар байна' (I would like to drink hot coffee), 'Бид кино үзмээр байна' (We'd like to see a movie).",
            "objectivesIntroduced": ["obj_a2_97_01_desiderative_maar"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_a2_96_01_habitual_aspect_expansion"],
            "grammarIntroduced": ["gram_a2_participle_desire_inclination_maar"],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_existential_baina_baihgui", "gram_a1_predicate_adjective_nominal"],
            "phonologyIntroduced": ["phono_a2_desiderative_suffix_harmony"],
            "phonologyPracticed": ["phono_a1_masculine_feminine_harmony"], "phonologyReviewed": ["phono_a1_long_vowels"],
            "communicativeFunctionsIntroduced": ["comm_a2_09_making_accepting_invitations"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_social_interaction", "lex_domain_recreation_leisure"],
            "previousVocabularyReused": ["хийх", "явах", "уух", "идэх", "үзэх", "байна"],
            "readingObjective": "Read social media posts where friends express desires for weekend trips and outings.",
            "listeningObjective": "Identify desiderative verbal endings in -маар4 in audio dialogues.",
            "writingObjective": "Write 4 sentences expressing personal wishes for the upcoming weekend using -маар байна.",
            "spokenProductionObjective": "Express personal desire: 'Би энэ амралтын өдрөөр хөдөө агаарт гармаар байна'.",
            "registerTarget": "Warm polite interpersonal register",
            "pragmaticTarget": "Using -маар байна as a gentle, polite expression of desire rather than blunt imperatives.",
            "prerequisiteLessonIds": ["les_a2_96_01_habitual_aspect_pastimes_intro"],
            "reviewsLessonIds": ["les_a1_20_01_expressing_intentions_intro"],
            "reviewsUnitIds": ["unit_a1_20_expressing_intentions_wishes_fut"],
            "reviewReason": "Expands simple volitional future forms into nuanced desiderative expressions.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Model harmonious vowel elongation in suffix (-маар, -мээр, -моор, -мөөр).",
            "successCriteria": [
                "Attaches correct harmonic variant of -маар4 to verb stems",
                "Combines -маар4 with existential auxiliary байна to form complete predicate"
            ],
            "masteryEvidence": "Produces 'Би өнөө орой найзуудтайгаа уулзмаар байна' with natural phonological flow.",
            "recommendedExerciseModalities": ["suffix_selection", "sentence_construction", "matching"]
        },
        {
            "lessonId": "les_a2_97_02_social_gatherings_events_lexicon",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 2,
            "title": "Birthdays, Dinners & Gatherings: Social Invitations Vocabulary",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Introduce social gathering and party vocabulary (урилга, зочлох, төрсөн өдөр тэмдэглэх, цугларах, хамт хооллох, баяр хүргэх, бэлэг өгөх).",
            "communicativeOutcome": "Invite friends to birthday parties, dinner gatherings, and home visits; discuss event details and gift ideas.",
            "objectivesIntroduced": ["obj_a2_97_02_social_gatherings_lexicon"],
            "objectivesPracticed": ["obj_a2_97_01_desiderative_maar"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_participle_desire_inclination_maar"],
            "grammarReviewed": ["gram_a1_case_comitative_association", "gram_a1_verb_volitional_intention_ya"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_consonant_clusters"], "phonologyReviewed": ["phono_a1_vowel_reduction_non_initial"],
            "communicativeFunctionsIntroduced": ["comm_a2_09_making_accepting_invitations"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_social_interaction", "lex_domain_culture_traditions"],
            "previousVocabularyReused": ["урих", "зочин", "баяр", "өдөр", "хоол", "найз"],
            "readingObjective": "Read printed and digital party invitation cards specifying date, venue, and dress code.",
            "listeningObjective": "Understand an audio voicemail inviting a friend to a celebratory dinner.",
            "writingObjective": "List 5 essential elements of a social invitation in Cyrillic.",
            "spokenProductionObjective": "Extend an invitation: 'Би маргааш орой төрсөн өдрөө тэмдэглэнэ, чамайг уримаар байна'.",
            "registerTarget": "Warm hospitable social gathering register",
            "pragmaticTarget": "Offering social invitations with sincere, generous hospitality.",
            "prerequisiteLessonIds": ["les_a2_97_01_desiderative_participle_maar_intro"],
            "reviewsLessonIds": ["les_a1_47_01_invitations_suggestions_intro"],
            "reviewsUnitIds": ["unit_a1_47_making_accepting_declining_invita"],
            "reviewReason": "Deepens basic invitation phrases into nuanced social event organization.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Pronounce festive event vocabulary clearly.",
            "successCriteria": [
                "Defines урилга (invitation), цугларах (gather), зочлох (visit/be a guest)",
                "Forms invitations combining -маар байна with volitional proposals (-я/-е)"
            ],
            "masteryEvidence": "Accurately plans and articulates an invitation to a housewarming or birthday gathering.",
            "recommendedExerciseModalities": ["categorization", "contextual_cloze", "matching"]
        },
        {
            "lessonId": "les_a2_97_03_extending_invitations_dialogue",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 3,
            "title": "Join Us Tonight: Extending & Accepting Warm Social Invitations",
            "lessonType": "dialogue_work",
            "primaryPurpose": "Master spoken communication for extending, accepting, and coordinating social invitations: agreeing on meeting spots, asking what to bring, and confirming times.",
            "communicativeOutcome": "Invite a friend or colleague to a social event, accept an invitation enthusiastically ('Дуртайяа очьё!'), and coordinate logistics.",
            "objectivesIntroduced": ["obj_a2_97_03_invitation_coordination_dialogue"],
            "objectivesPracticed": ["obj_a2_97_01_desiderative_maar", "obj_a2_97_02_social_gatherings_lexicon"],
            "objectivesReviewed": ["obj_a1_16_01_greet_time_of_day"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_participle_desire_inclination_maar"],
            "grammarReviewed": ["gram_a1_verb_volitional_intention_ya", "gram_a1_case_dative_locative_time"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_intonation_polite"], "phonologyReviewed": ["phono_a1_diphthongs"],
            "communicativeFunctionsIntroduced": ["comm_a2_09_making_accepting_invitations"],
            "communicativeFunctionsPracticed": ["comm_a1_16_greetings_time_of_day"],
            "communicativeFunctionsReviewed": ["comm_a1_13_apologies_politeness"],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_social_interaction"],
            "previousVocabularyReused": ["очих", "уулзах", "цаг", "газар", "авах", "дуртайяа"],
            "readingObjective": "",
            "listeningObjective": "Understand friend proposing a group dinner: 'Бид өнөө орой шинэ монгол хоолны газар ормоор байна, чи хамт явах уу?'.",
            "writingObjective": "",
            "spokenProductionObjective": "Accept and ask details: 'Маш сайхан санаа байна, би дуртайяа очьё! Хэдэн цагт, хаана уулзах вэ?'.",
            "registerTarget": "Warm, eager interpersonal social register",
            "pragmaticTarget": "Expressing enthusiasm and asking politely whether to bring a dish or drink.",
            "prerequisiteLessonIds": ["les_a2_97_02_social_gatherings_events_lexicon"],
            "reviewsLessonIds": ["les_a1_47_05_invitations_dialogue_simulation"],
            "reviewsUnitIds": ["unit_a1_47_making_accepting_declining_invita"],
            "reviewReason": "Expands invitation dialogues with flexible desiderative constructions.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Warm, engaging phone dialogue between friends coordinating a weekend dinner outing.",
            "successCriteria": [
                "Extends invitation using -маар байна and accepts using volitional -я",
                "Confirms time and meeting location clearly"
            ],
            "masteryEvidence": "Conducts a 5-turn invitation dialogue agreeing on dinner arrangements smoothly.",
            "recommendedExerciseModalities": ["role-play response", "dialogue_completion", "listening_comprehension"]
        },
        {
            "lessonId": "les_a2_97_04_party_invitations_acoustic_listening",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 4,
            "title": "Acoustic Lab: Voicemail Invitations & Casual Social Proposals",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop acoustic listening comprehension of spoken voicemail messages, voice notes on messaging apps, and casual group invitations.",
            "communicativeOutcome": "Extract event type (housewarming, graduation celebration), time, location, and RSVP instructions from spoken voice messages.",
            "objectivesIntroduced": ["obj_a2_97_04_decode_voicemail_invitations"],
            "objectivesPracticed": ["obj_a2_97_01_desiderative_maar"], "objectivesReviewed": ["obj_a1_36_01_calendar_dates"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a2_participle_desire_inclination_maar", "gram_a1_case_dative_locative_time"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_vowel_reduction_non_initial"], "phonologyReviewed": ["phono_a1_nasal_vowels"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_09_making_accepting_invitations"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_social_interaction", "lex_domain_technology_devices"],
            "previousVocabularyReused": ["мессеж", "сонсох", "ирнэ", "хүлээх", "баяр", "гэр"],
            "readingObjective": "",
            "listeningObjective": "Identify specific party details across 3 distinct audio voicemails.",
            "writingObjective": "",
            "spokenProductionObjective": "Leave a return voicemail confirming attendance.",
            "registerTarget": "Casual recorded voice messaging register",
            "pragmaticTarget": "Extracting key event data from fast, casual voice notes with background chatter.",
            "prerequisiteLessonIds": ["les_a2_97_02_social_gatherings_events_lexicon"],
            "reviewsLessonIds": ["les_a1_69_03_courier_phone_listening"],
            "reviewsUnitIds": ["unit_a2_69_postal_courier_package_delivery_ser"],
            "reviewReason": "Applies recorded messaging listening skills to social invitations.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Realistic voice note acoustics with varying microphone closeness and casual friendly inflection.",
            "successCriteria": [
                "Identifies occasion, date, and address correctly from audio clips",
                "Detects whether the host requests bringing specific items"
            ],
            "masteryEvidence": "Accurately completes an event planner card based on 3 spoken voice notes.",
            "recommendedExerciseModalities": ["listening_comprehension", "phonetic_discrimination", "categorization"]
        },
        {
            "lessonId": "les_a2_97_05_invitation_card_rsvp_writing",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 5,
            "title": "You Are Cordially Invited: Composing Party Invitations & RSVPs",
            "lessonType": "grammar_guided_practice",
            "primaryPurpose": "Synthesize desiderative forms (-маар4 байна), celebration vocabulary, and polite written formulas into formal and informal party invitations and RSVP responses.",
            "communicativeOutcome": "Draft a written invitation card for a family milestone or friendly celebration, and write a polite written RSVP acceptance.",
            "objectivesIntroduced": ["obj_a2_97_05_write_party_invitations"],
            "objectivesPracticed": ["obj_a2_97_01_desiderative_maar", "obj_a2_97_02_social_gatherings_lexicon"],
            "objectivesReviewed": ["obj_a1_50_01_sequential_converb"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_participle_desire_inclination_maar"],
            "grammarReviewed": ["gram_a1_case_dative_locative_time", "gram_a1_verb_volitional_intention_ya"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_09_making_accepting_invitations"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_social_interaction", "lex_domain_culture_traditions"],
            "previousVocabularyReused": ["урилга", "хүлээн авах", "баяр", "хүндэтгэсэн", "хүрэлцэн ирэх", "огноо"],
            "readingObjective": "Review authentic printed invitation cards to observe traditional opening formulas.",
            "listeningObjective": "",
            "writingObjective": "Draft a 5-line celebration invitation card using -маар байна and formal invitation etiquette.",
            "spokenProductionObjective": "",
            "registerTarget": "Polite festive invitation and correspondence register",
            "pragmaticTarget": "Using respectful invitation formulas ('хүрэлцэн ирэхийг урьж байна') appropriately.",
            "prerequisiteLessonIds": ["les_a2_97_03_extending_invitations_dialogue", "les_a2_97_04_party_invitations_acoustic_listening"],
            "reviewsLessonIds": ["les_a1_50_01_sequential_converb_aad"],
            "reviewsUnitIds": ["unit_a1_50_sequential_converb_clause_connector"],
            "reviewReason": "Links sequential scheduling clauses with polite invitation formulas.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Audio read-back of written invitation text.",
            "successCriteria": [
                "Produces written invitation with occasion, date, time, location, and polite closing",
                "Drafts a courteous written acceptance memo using desiderative forms"
            ],
            "masteryEvidence": "Drafts 'Эрхэм найзуудаа! Шинэ байрны найраа тэмдэглэхээр та нарыг уримаар байна...' flawlessly.",
            "recommendedExerciseModalities": ["short-answer writing", "sentence construction", "error correction"]
        }
    ])

    # =========================================================================
    # UNIT 98: Purposive Intentions & Plans: Converb -хаар4 (pos 98)
    # 5 Lessons | Targets: ProdLem=21, RecLem=10, ProdExp=5, RecExp=3
    # Budget: (5,2,1,1), (6,3,1,1), (5,3,2,1), (0,0,0,0), (5,2,1,0) = (21, 10, 5, 3)
    # =========================================================================
    u = u_map[98]
    uid = u["unitId"]
    lessons.extend([
        {
            "lessonId": "les_a2_98_01_purposive_converb_khaar_intro",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 1,
            "title": "In Order to & Planning to: The Purposive Converb (-хаар/-хээр)",
            "lessonType": "grammar_introduction",
            "primaryPurpose": "Introduce the purposive converb suffix (-хаар4 / -хээр / -хоор / -хөөр) indicating goal/purpose ('in order to') and immediate planned intention ('planning to / about to do' when paired with байна/болох).",
            "communicativeOutcome": "State purpose of actions: 'Би монгол хэл сурахаар ирсэн' (I came to learn Mongolian), 'Бид маргааш хөдөө явахаар төлөвлөж байна' (We are planning to go to the countryside tomorrow).",
            "objectivesIntroduced": ["obj_a2_98_01_purposive_converb_khaar"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_a2_97_01_desiderative_maar"],
            "grammarIntroduced": ["gram_a2_converb_purposive_khaar"],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_instrumental_transport_language", "gram_a1_verbal_noun_future_participle_h"],
            "phonologyIntroduced": ["phono_a2_purposive_suffix_harmony"],
            "phonologyPracticed": ["phono_a1_masculine_feminine_harmony"], "phonologyReviewed": ["phono_a1_long_vowels"],
            "communicativeFunctionsIntroduced": ["comm_a2_10_declining_invitations_excuses"],
            "communicativeFunctionsPracticed": ["comm_a2_09_making_accepting_invitations"], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_intentions_plans", "lex_domain_social_interaction"],
            "previousVocabularyReused": ["сурах", "ажиллах", "явах", "ирэх", "уулзах", "төлөвлөх"],
            "readingObjective": "Read university study abroad program descriptions explaining student study objectives.",
            "listeningObjective": "Identify purposive converb endings (-хаар4) in interviewees explaining career goals.",
            "writingObjective": "Combine 4 pairs of independent clauses into purpose statements using -хаар4.",
            "spokenProductionObjective": "Explain purpose: 'Би маргааш шалгалт өгөхөөр бэлдэж байна, тиймээс өнөөдөр гарч чадахгүй'.",
            "registerTarget": "Standard goal-oriented explanatory register",
            "pragmaticTarget": "Connecting motives to actions smoothly and providing valid rationale for scheduling conflicts.",
            "prerequisiteLessonIds": ["les_a2_97_01_desiderative_participle_maar_intro"],
            "reviewsLessonIds": ["les_a1_39_01_instrumental_case_intro"],
            "reviewsUnitIds": ["unit_a1_39_instrumental_case_means_manner_in"],
            "reviewReason": "Fuses verbal noun -х with instrumental case suffix (-аар4 = -хаар4).",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Model quadruple vowel harmony in purposive suffix (-хаар, -хээр, -хоор, -хөөр).",
            "successCriteria": [
                "Attaches correct harmonic variant of -хаар4 according to root vocalism",
                "Forms purposive clauses expressing reasons: 'номын санд ном уншихаар очлоо'"
            ],
            "masteryEvidence": "Produces 'Би найзтайгаа уулзахаар хот руу явлаа' without morphological hesitation.",
            "recommendedExerciseModalities": ["suffix_selection", "clause_combination", "matching"]
        },
        {
            "lessonId": "les_a2_98_02_prior_commitments_excuses_lexicon",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 2,
            "title": "I'd Love to, But: Polite Excuses & Prior Commitments",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Introduce polite declination formulas, prior commitments, and social excuses vocabulary (амжихгүй байх, завгүй, ажилтай, урьдчилж товлосон, чухал ажил, дараа заавал).",
            "communicativeOutcome": "Decline social invitations gracefully without causing offense, citing prior commitments and suggesting alternative dates.",
            "objectivesIntroduced": ["obj_a2_98_02_prior_commitments_lexicon"],
            "objectivesPracticed": ["obj_a2_98_01_purposive_converb_khaar"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_converb_purposive_khaar"],
            "grammarReviewed": ["gram_a1_converb_coordinating_j_ch", "gram_a1_existential_baina_baihgui"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_consonant_clusters"], "phonologyReviewed": ["phono_a1_vowel_reduction_non_initial"],
            "communicativeFunctionsIntroduced": ["comm_a2_10_declining_invitations_excuses"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_social_interaction", "lex_domain_daily_routines"],
            "previousVocabularyReused": ["завгүй", "ажил", "амжихгүй", "уучлаарай", "дараа", "болох"],
            "readingObjective": "Read polite email declinations for meeting and social event invitations.",
            "listeningObjective": "Understand colleague politely turning down a lunch invitation due to urgent project deadlines.",
            "writingObjective": "List 4 courteous formulas for declining invitations in Cyrillic.",
            "spokenProductionObjective": "Decline politely: 'Урьсанд маш их баярлалаа. Гэвч би тэр өдөр урьдчилж төлөвлөсөн чухал ажилтай тул амжихгүй нь'.",
            "registerTarget": "Diplomatic courteous social etiquette register",
            "pragmaticTarget": "Softening declinations with gratitude ('Баярлалаа, гэвч...') and promising future catch-ups.",
            "prerequisiteLessonIds": ["les_a2_98_01_purposive_converb_khaar_intro"],
            "reviewsLessonIds": ["les_a1_47_03_declining_invitations_politely"],
            "reviewsUnitIds": ["unit_a1_47_making_accepting_declining_invita"],
            "reviewReason": "Expands basic declinations with complex purposive rationales.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Pronounce diplomatic polite declination formulas clearly.",
            "successCriteria": [
                "Defines завгүй (busy), амжихгүй (unable to make it in time), товлосон ажил (scheduled commitment)",
                "Uses -хаар to state conflicting plans: 'хөдөө явахаар болсон тул'"
            ],
            "masteryEvidence": "Declines an invitation with complete courtesy and proposes a realistic alternate date.",
            "recommendedExerciseModalities": ["categorization", "contextual_cloze", "matching"]
        },
        {
            "lessonId": "les_a2_98_03_graceful_declination_dialogue",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 3,
            "title": "Rain Check: Declining Gracefully & Rescheduling Social Plans",
            "lessonType": "dialogue_work",
            "primaryPurpose": "Master spoken communication for declining invitations gracefully: expressing genuine regret, explaining conflicting obligations with purposive converbs, and offering a 'rain check'.",
            "communicativeOutcome": "Navigate an invitation declination gracefully, ensuring friendly relationships remain warm, and proposing a concrete alternate meeting date.",
            "objectivesIntroduced": ["obj_a2_98_03_declination_rescheduling_dialogue"],
            "objectivesPracticed": ["obj_a2_98_01_purposive_converb_khaar", "obj_a2_98_02_prior_commitments_lexicon"],
            "objectivesReviewed": ["obj_a1_13_01_apologies_intro"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_converb_purposive_khaar"],
            "grammarReviewed": ["gram_a1_converb_conditional_val", "gram_a1_verb_volitional_intention_ya"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_intonation_polite"], "phonologyReviewed": ["phono_a1_vowel_length_distinction"],
            "communicativeFunctionsIntroduced": ["comm_a2_10_declining_invitations_excuses"],
            "communicativeFunctionsPracticed": ["comm_a1_13_apologies_politeness"],
            "communicativeFunctionsReviewed": ["comm_a1_16_greetings_time_of_day"],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_social_interaction"],
            "previousVocabularyReused": ["харамсалтай", "дараа", "уулзах", "болох", "баярлалаа", "утсаар"],
            "readingObjective": "",
            "listeningObjective": "Understand friend's warm acceptance of declination: 'Ойлголоо, ажилдаа амжилт! Тэгвэл ирэх долоо хоногт кофе ууцгаая'.",
            "writingObjective": "",
            "spokenProductionObjective": "Decline and reschedule: 'Өнөөдөр үнэхээр очмоор байвч, шалгалтандаа бэлдэхээр номын санд сууж байна. Ирэх бүтэн сайнд уулзвал ямар вэ?'.",
            "registerTarget": "Warm diplomatic social diplomacy register",
            "pragmaticTarget": "Maintaining social warmth and preventing feelings of rejection when declining.",
            "prerequisiteLessonIds": ["les_a2_98_02_prior_commitments_excuses_lexicon"],
            "reviewsLessonIds": ["les_a1_47_05_invitations_dialogue_simulation"],
            "reviewsUnitIds": ["unit_a1_47_making_accepting_declining_invita"],
            "reviewReason": "Synthesizes polite apologies with purposive converbs in live social dialogue.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Genuine apologetic warmth and constructive rescheduling tone between close friends.",
            "successCriteria": [
                "Expresses regret politely and provides valid purpose using -хаар",
                "Successfully proposes an alternate meeting time accepted by partner"
            ],
            "masteryEvidence": "Executes a 5-turn declination and rescheduling dialogue without friction.",
            "recommendedExerciseModalities": ["role-play response", "dialogue_completion", "listening_comprehension"]
        },
        {
            "lessonId": "les_a2_98_04_scheduling_conflicts_acoustic_listening",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 4,
            "title": "Acoustic Lab: Resolving Calendar Clashes & Social Excuses Audio",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop acoustic listening comprehension of rapid spoken exchanges where multiple parties juggle conflicting commitments, family duties, and evening schedules.",
            "communicativeOutcome": "Listen to a group discussion planning an outing, extract each person's scheduling conflicts, and identify the single day everyone is free.",
            "objectivesIntroduced": ["obj_a2_98_04_decode_scheduling_conflicts"],
            "objectivesPracticed": ["obj_a2_98_01_purposive_converb_khaar"], "objectivesReviewed": ["obj_a1_36_01_calendar_dates"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a2_converb_purposive_khaar", "gram_a1_case_dative_locative_time"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_vowel_reduction_non_initial"], "phonologyReviewed": ["phono_a1_nasal_vowels"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_10_declining_invitations_excuses"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_social_interaction", "lex_domain_intentions_plans"],
            "previousVocabularyReused": ["боломжтой", "завтай", "өдөр", "хүн", "цугларах", "хэзээ"],
            "readingObjective": "",
            "listeningObjective": "Identify specific conflicting commitments mentioned across 3 speakers in a group audio call.",
            "writingObjective": "",
            "spokenProductionObjective": "State which day works for the entire group based on the recording.",
            "registerTarget": "Fast colloquial multi-party group chat register",
            "pragmaticTarget": "Parsing overlapping schedules and synthesizing consensus from conflicting statements.",
            "prerequisiteLessonIds": ["les_a2_98_02_prior_commitments_excuses_lexicon"],
            "reviewsLessonIds": ["les_a1_70_03_teller_guidance_listening"],
            "reviewsUnitIds": ["unit_a2_70_banking_basics_atms_cash_withdrawal"],
            "reviewReason": "Tests auditory synthesis across multiple competing speakers.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Realistic multi-speaker audio with friends proposing and ruling out different days.",
            "successCriteria": [
                "Identifies why Speaker A and Speaker B cannot attend on Friday",
                "Pinpoints the consensus day and time agreed by all participants"
            ],
            "masteryEvidence": "Accurately maps out a 3-person schedule grid and determines the consensus meeting window.",
            "recommendedExerciseModalities": ["listening_comprehension", "phonetic_discrimination", "categorization"]
        },
        {
            "lessonId": "les_a2_98_05_formal_declination_note_writing",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 5,
            "title": "Diplomatic Correspondence: Writing Polite Declination Notes & Emails",
            "lessonType": "grammar_guided_practice",
            "primaryPurpose": "Synthesize purposive converbs (-хаар4), polite apology formulas, and conditional future proposals into formal written declination messages and emails.",
            "communicativeOutcome": "Write a formal email declining an official invitation or social gathering, articulating conflicting commitments clearly and expressing cordial wishes.",
            "objectivesIntroduced": ["obj_a2_98_05_write_declination_notes"],
            "objectivesPracticed": ["obj_a2_98_01_purposive_converb_khaar", "obj_a2_98_02_prior_commitments_lexicon"],
            "objectivesReviewed": ["obj_a1_50_01_sequential_converb"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_converb_purposive_khaar"],
            "grammarReviewed": ["gram_a1_case_ablative_origin", "gram_a1_converb_coordinating_j_ch"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_10_declining_invitations_excuses"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_social_interaction", "lex_domain_civic_administrative"],
            "previousVocabularyReused": ["захидал", "хариу", "уучлалт", "баярлалаа", "ажил", "хүндэтгэсэн"],
            "readingObjective": "Review model diplomatic declination correspondence for structural etiquette.",
            "listeningObjective": "",
            "writingObjective": "Draft a 5-sentence polite written declination containing at least one purposive clause in -хаар4.",
            "spokenProductionObjective": "",
            "registerTarget": "Formal polite written correspondence register",
            "pragmaticTarget": "Adhering to high social courtesy standards in written communication.",
            "prerequisiteLessonIds": ["les_a2_98_03_graceful_declination_dialogue", "les_a2_98_04_scheduling_conflicts_acoustic_listening"],
            "reviewsLessonIds": ["les_a1_68_05_polite_delay_notice_sms_writing"],
            "reviewsUnitIds": ["unit_a2_68_handling_transit_delays_traffic_jam"],
            "reviewReason": "Elevates short SMS excuses to formal written correspondence.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Audio read-back of written formal declination note.",
            "successCriteria": [
                "Includes formal greeting, genuine expression of gratitude for invitation, and courteous closing",
                "Explains conflict using purposive converb: 'гадаад томилолтоор явахаар болсон тул...'"
            ],
            "masteryEvidence": "Drafts 'Урилга илгээсэнд гүнээ талархаж байна. Харамсалтай нь би тэр өдөр... амжихгүй боллоо' flawlessly.",
            "recommendedExerciseModalities": ["short-answer writing", "sentence construction", "error correction"]
        }
    ])

    return lessons
