"""
Section 5 Generator Part 1 (Units 103 - 105): 13 Lessons
103: Domestic Living Spaces & Furnishing Layout (4 lessons)
104: The Mongolian Ger: Architectural Anatomy & Orientation (4 lessons)
105: Ger Etiquette & Concessive Converb: -вч / боловч (5 lessons)
"""

import json
from typing import List, Dict, Any

def get_sec05_part1_lessons(u_map: Dict[int, Any]) -> List[Dict[str, Any]]:
    lessons: List[Dict[str, Any]] = []

    # =========================================================================
    # UNIT 103: Domestic Living Spaces & Furnishing Layout (pos 103)
    # 4 Lessons | Targets: ProdLem=19, RecLem=9, ProdExp=5, RecExp=3
    # Budget: (7,3,2,1), (5,3,1,1), (0,0,0,0), (7,3,2,1) = (19, 9, 5, 3)
    # =========================================================================
    u = u_map[103]
    uid = u["unitId"]
    lessons.extend([
        {
            "lessonId": "les_a2_103_01_interior_layout_furniture_lexicon",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 1,
            "title": "Living Rooms, Balconies & Decor: Interior Layout & Furnishings",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Introduce room types, interior furnishings, and spatial arrangement vocabulary (зочны өрөө, унтлагын өрөө, тагт, үүдний өрөө, буйдан, шүүгээ, хивс, тавих, байрлуулах).",
            "communicativeOutcome": "Describe the interior floor plan of an apartment or house, detailing furniture placement in each room.",
            "objectivesIntroduced": ["obj_a2_103_01_interior_layout_lexicon"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_a2_102_01_lease_furnishings_lexicon"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_spatial_postpositions_deeree_door", "gram_a1_case_dative_locative_location"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_consonant_clusters"], "phonologyReviewed": ["phono_a1_vowel_reduction_non_initial"],
            "communicativeFunctionsIntroduced": ["comm_a2_05_describing_home_rooms_furniture"],
            "communicativeFunctionsPracticed": ["comm_a2_04_renting_apartment_housing"], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 7, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_housing_home"],
            "previousVocabularyReused": ["өрөө", "тавилга", "ширээ", "сандал", "гэр", "байр"],
            "readingObjective": "Read an interior design article describing optimal furniture layout for small urban apartments.",
            "listeningObjective": "Understand an interior decorator advising where to place a bookshelf and sofa.",
            "writingObjective": "List 6 furniture items with their typical room locations in Cyrillic.",
            "spokenProductionObjective": "Describe room arrangement: 'Зочны өрөөний цонхны доор буйдангаа байрлуулж, өөдөөс нь зурагт тавьсан'.",
            "registerTarget": "Domestic home arrangement and interior design register",
            "pragmaticTarget": "Using precise spatial postpositions to describe home layout clearly.",
            "prerequisiteLessonIds": ["les_a2_102_01_lease_agreements_furnishings_lexicon"],
            "reviewsLessonIds": ["les_a1_55_01_residential_housing_intro"],
            "reviewsUnitIds": ["unit_a1_55_residential_housing_apartments_ger_"],
            "reviewReason": "Expands basic room naming to comprehensive interior spatial layout.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Pronounce furniture and interior decor terminology clearly.",
            "successCriteria": [
                "Defines зочны өрөө (living room), тагт (balcony), буйдан (sofa), шүүгээ (cabinet/closet)",
                "Forms spatial descriptions using compound postpositions (дэргэд, өөдөөс нь, буланд)"
            ],
            "masteryEvidence": "Accurately describes the layout of a 3-room apartment using precise spatial postpositions.",
            "recommendedExerciseModalities": ["categorization", "contextual_cloze", "matching"]
        },
        {
            "lessonId": "les_a2_103_02_furniture_catalog_floorplan_reading",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 2,
            "title": "Deciphering Furniture Catalogs & Floorplan Blueprints",
            "lessonType": "reading_development",
            "primaryPurpose": "Develop reading comprehension of furniture store promotional catalogs, dimension listings, assembly guides, and architectural floorplans.",
            "communicativeOutcome": "Inspect a furniture catalog, verify product dimensions (урт, өргөн, өндөр), materials (мод, төмөр, даавуу), and match items to a floorplan layout.",
            "objectivesIntroduced": ["obj_a2_103_02_read_furniture_catalogs"],
            "objectivesPracticed": ["obj_a2_103_01_interior_layout_lexicon"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_noun_phrase_attributive_adjective", "gram_a1_predicate_adjective_nominal"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_05_describing_home_rooms_furniture"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_housing_home", "lex_domain_commerce_transactions"],
            "previousVocabularyReused": ["хэмжээ", "үнэ", "материал", "модон", "өнгө", "хямдрал"],
            "readingObjective": "Locate dimensions, materials, and warranty information in a 120-word modular furniture catalog snippet.",
            "listeningObjective": "",
            "writingObjective": "Transcribe furniture dimensions into a room planning worksheet.",
            "spokenProductionObjective": "Explain to a partner whether the dining table will fit in the kitchen.",
            "registerTarget": "Commercial retail catalog and specifications register",
            "pragmaticTarget": "Checking spatial dimensions carefully against real room measurements.",
            "prerequisiteLessonIds": ["les_a2_103_01_interior_layout_furniture_lexicon"],
            "reviewsLessonIds": ["les_a1_77_02_reading_product_specifications"],
            "reviewsUnitIds": ["unit_a2_77_third_person_possessive_enclitic_th"],
            "reviewReason": "Extends retail specification reading to home furnishings and architectural measurements.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Read furniture product specifications aloud.",
            "successCriteria": [
                "Extracts length, width, and height correctly from product description",
                "Determines whether the item matches the designated room space"
            ],
            "masteryEvidence": "Correctly matches 4 furniture pieces to corresponding rooms on a floorplan diagram.",
            "recommendedExerciseModalities": ["reading_comprehension", "contextual_cloze", "matching"]
        },
        {
            "lessonId": "les_a2_103_03_room_rearrangement_acoustic_listening",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 3,
            "title": "Acoustic Lab: Rearranging the Living Room & Moving Furniture",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop acoustic listening comprehension of an authentic dialogue between two family members rearranging furniture, discussing aesthetic preferences, and shifting heavy items.",
            "communicativeOutcome": "Follow spoken spatial instructions during a furniture move: 'Буйданг нааш нь тат', 'Шүүгээг хана руу шахаж тавья'.",
            "objectivesIntroduced": ["obj_a2_103_03_decode_furniture_moving"],
            "objectivesPracticed": ["obj_a2_103_01_interior_layout_lexicon"], "objectivesReviewed": ["obj_a1_39_01_instrumental_case"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_spatial_postpositions_deeree_door", "gram_a1_verb_imperative_polite_aarai"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_vowel_reduction_non_initial"], "phonologyReviewed": ["phono_a1_nasal_vowels"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_05_describing_home_rooms_furniture"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_housing_home"],
            "previousVocabularyReused": ["татаж", "түлхэх", "тавих", "хана", "булан", "зай"],
            "readingObjective": "",
            "listeningObjective": "Identify specific movement directives (нааш нь, цааш нь, эргүүлэх) from audio dialogue.",
            "writingObjective": "",
            "spokenProductionObjective": "Direct a mover: 'Ширээг баруун буланд тавиад, сандлуудыг тойруулаад тавьчих'.",
            "registerTarget": "Everyday practical household coordination register",
            "pragmaticTarget": "Parsing rapid directional adverbs (нааш нь, цааш нь, дээш нь) in physical coordination contexts.",
            "prerequisiteLessonIds": ["les_a2_103_01_interior_layout_furniture_lexicon"],
            "reviewsLessonIds": ["les_a1_81_03_courier_delivery_acoustic_lab"],
            "reviewsUnitIds": ["unit_a2_81_errands_dry_cleaning_tailoring_re"],
            "reviewReason": "Applies physical delivery listening to domestic spatial reorganization.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Realistic household audio with furniture sliding sounds and coordinated verbal cues.",
            "successCriteria": [
                "Identifies where each piece of furniture was ultimately placed",
                "Follows directional adverbs indicating distance and orientation accurately"
            ],
            "masteryEvidence": "Accurately draws final furniture arrangement on a floor grid based on dialogue audio.",
            "recommendedExerciseModalities": ["listening_comprehension", "phonetic_discrimination", "sequencing"]
        },
        {
            "lessonId": "les_a2_103_04_home_renovation_decor_dialogue",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 4,
            "title": "Redecorating the Home: Choosing Paint, Curtains & Lighting",
            "lessonType": "dialogue_work",
            "primaryPurpose": "Master spoken communication for discussing home renovation, interior styling, color coordination, and lighting choices with family or a decorator.",
            "communicativeOutcome": "Discuss home redecorating plans with a partner: select wallpaper colors, curtain styles, and lighting fixtures to create a cozy home atmosphere.",
            "objectivesIntroduced": ["obj_a2_103_04_home_renovation_dialogue"],
            "objectivesPracticed": ["obj_a2_103_01_interior_layout_lexicon", "obj_a2_103_02_read_furniture_catalogs"],
            "objectivesReviewed": ["obj_a1_16_01_greet_time_of_day"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_comitative_association", "gram_a1_predicate_adjective_nominal"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_intonation_polite"], "phonologyReviewed": ["phono_a1_diphthongs"],
            "communicativeFunctionsIntroduced": ["comm_a2_05_describing_home_rooms_furniture"],
            "communicativeFunctionsPracticed": ["comm_a1_16_greetings_time_of_day"],
            "communicativeFunctionsReviewed": ["comm_a1_13_apologies_politeness"],
            "newProductiveLemmaTarget": 7, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_housing_home", "lex_domain_social_interaction"],
            "previousVocabularyReused": ["гэр", "өнгө", "гэрэл", "хөшиг", "тохилог", "солих"],
            "readingObjective": "",
            "listeningObjective": "Understand decorator suggesting warm ambient lighting and cream curtains for the living room.",
            "writingObjective": "",
            "spokenProductionObjective": "Propose decorating ideas: 'Унтлагын өрөөний ханыг цайвар цэнхэр өнгөөр будаж, дулаахан шар гэрэл тавибал их тохилог харагдана'.",
            "registerTarget": "Collaborative domestic styling and home improvement register",
            "pragmaticTarget": "Giving constructive design opinions and reaching mutual aesthetic consensus.",
            "prerequisiteLessonIds": ["les_a2_103_02_furniture_catalog_floorplan_reading", "les_a2_103_03_room_rearrangement_acoustic_listening"],
            "reviewsLessonIds": ["les_a1_78_05_clothing_alterations_dialogue"],
            "reviewsUnitIds": ["unit_a2_78_department_store_apparel_sizing_fi"],
            "reviewReason": "Transfers aesthetic design and color coordination to interior spaces.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Engaging, collaborative domestic conversation between partners planning apartment updates.",
            "successCriteria": [
                "Proposes color, curtain, and lighting choices using descriptive adjectives",
                "Reaches agreement on home renovation budget and timeline"
            ],
            "masteryEvidence": "Conducts a 5-turn home redecorating dialogue finalizing living room styling seamlessly.",
            "recommendedExerciseModalities": ["role-play response", "dialogue_completion", "listening_comprehension"]
        }
    ])

    # =========================================================================
    # UNIT 104: The Mongolian Ger: Architectural Anatomy & Orientation (pos 104)
    # 4 Lessons | Targets: ProdLem=19, RecLem=9, ProdExp=5, RecExp=3
    # Budget: (7,3,2,1), (5,3,1,1), (0,0,0,0), (7,3,2,1) = (19, 9, 5, 3)
    # =========================================================================
    u = u_map[104]
    uid = u["unitId"]
    lessons.extend([
        {
            "lessonId": "les_a2_104_01_ger_architectural_anatomy_lexicon",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 1,
            "title": "Crown, Pillars & Lattice: Architectural Anatomy of the Ger",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Introduce the traditional nomadic dwelling's architectural components and engineering terms (тооно, багана, уни, хана, хаалга, өрх, бүслүүр, эсгий бүрээс).",
            "communicativeOutcome": "Name and describe every structural element of a Mongolian ger, explaining how the trellis wall, roof poles, and compression crown assemble into a stable nomadic home.",
            "objectivesIntroduced": ["obj_a2_104_01_ger_anatomy_lexicon"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_a2_103_01_interior_layout_lexicon"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_genitive_possession", "gram_a1_predicate_adjective_nominal"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_consonant_clusters"], "phonologyReviewed": ["phono_a1_vowel_reduction_non_initial"],
            "communicativeFunctionsIntroduced": ["comm_a2_14_countryside_ger_visiting_etiquette"],
            "communicativeFunctionsPracticed": ["comm_a2_05_describing_home_rooms_furniture"], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 7, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_housing_home", "lex_domain_culture_traditions"],
            "previousVocabularyReused": ["гэр", "мод", "эсгий", "хана", "хаалга", "барих"],
            "readingObjective": "Read a cultural heritage guide detailing the engineering genius of the portable nomadic ger.",
            "listeningObjective": "Understand an elder carpenter naming the structural components of a five-wall ger (таван ханатай гэр).",
            "writingObjective": "Label an anatomical diagram of a ger with 6 structural terms in Cyrillic.",
            "spokenProductionObjective": "Explain ger construction: 'Монгол гэрийн тооныг хоёр багана тулдаг бөгөөд олон униар ханатайгаа холбогддог'.",
            "registerTarget": "Traditional cultural architecture and craftsmanship register",
            "pragmaticTarget": "Respecting traditional terminology for the sacred nomadic dwelling.",
            "prerequisiteLessonIds": ["les_a2_103_01_interior_layout_furniture_lexicon"],
            "reviewsLessonIds": ["les_a1_55_01_residential_housing_intro"],
            "reviewsUnitIds": ["unit_a1_55_residential_housing_apartments_ger_"],
            "reviewReason": "Transitions general housing terminology into authoritative nomadic architectural anatomy.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Pronounce traditional nomadic architectural terms clearly.",
            "successCriteria": [
                "Defines тооно (crown ring), багана (central pillars), уни (roof poles), хана (lattice wall)",
                "Explains the function of each element in assembling the dwelling"
            ],
            "masteryEvidence": "Accurately identifies and explains all 8 components of a ger on an architectural schematic.",
            "recommendedExerciseModalities": ["diagram_labeling", "matching", "categorization"]
        },
        {
            "lessonId": "les_a2_104_02_sacred_orientation_interior_zones_reading",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 2,
            "title": "Sacred Space: The Four Cardinal Quarters of the Ger Interior",
            "lessonType": "reading_development",
            "primaryPurpose": "Develop reading comprehension of cultural texts explaining the sacred interior zoning of the ger: hoimor (north/honor seat), female quarter (east), male quarter (west), and entrance (south).",
            "communicativeOutcome": "Understand the cultural zoning of a ger: why elders sit at the hoimor, why saddles and tools are kept on the west side, and kitchen utensils on the east side.",
            "objectivesIntroduced": ["obj_a2_104_02_read_ger_spatial_zoning"],
            "objectivesPracticed": ["obj_a2_104_01_ger_anatomy_lexicon"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_spatial_postpositions_deeree_door", "gram_a1_case_dative_locative_location"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_14_countryside_ger_visiting_etiquette"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_culture_traditions", "lex_domain_housing_home"],
            "previousVocabularyReused": ["хоймор", "баруун", "зүүн", "үүд", "хүндэтгэх", "суух"],
            "readingObjective": "Locate cultural explanations for the male/female quarters and the sacred status of the hoimor in a 140-word text.",
            "listeningObjective": "",
            "writingObjective": "Transcribe the 4 spatial quadrants onto a circular ger floorplan schematic.",
            "spokenProductionObjective": "Explain to a foreign traveler where guests are invited to sit in a countryside ger.",
            "registerTarget": "Cultural ethnography and traditional etiquette register",
            "pragmaticTarget": "Internalizing sacred spatial boundaries to navigate nomadic homes with perfect respect.",
            "prerequisiteLessonIds": ["les_a2_104_01_ger_architectural_anatomy_lexicon"],
            "reviewsLessonIds": ["les_a1_55_04_reading_home_advertisements"],
            "reviewsUnitIds": ["unit_a1_55_residential_housing_apartments_ger_"],
            "reviewReason": "Deepens home reading from urban apartments to sacred nomadic spatial philosophy.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Read cultural ethnography excerpt aloud.",
            "successCriteria": [
                "Identifies хоймор as the north seat of honor for elders, guests, and altars",
                "Associates west (баруун тал) with male activities and east (зүүн тал) with female domestic tasks"
            ],
            "masteryEvidence": "Correctly assigns 6 household activities and objects to their designated ger quadrant.",
            "recommendedExerciseModalities": ["reading_comprehension", "diagram_labeling", "categorization"]
        },
        {
            "lessonId": "les_a2_104_03_raising_a_ger_acoustic_listening",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 3,
            "title": "Acoustic Lab: Community Teamwork — Raising a Nomad's Ger",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop acoustic listening comprehension of an authentic countryside audio recording where herders and neighbors collaborate to erect a ger (гэр барих), calling out instructions and lifting the crown.",
            "communicativeOutcome": "Follow spoken commands during ger assembly: 'Баганыг тэгш бариарай', 'Униа ээлжилж өлгөе', 'Бүслүүрээ чанга тат'.",
            "objectivesIntroduced": ["obj_a2_104_03_decode_ger_raising"],
            "objectivesPracticed": ["obj_a2_104_01_ger_anatomy_lexicon"], "objectivesReviewed": ["obj_a1_39_01_instrumental_case"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_verb_imperative_polite_aarai", "gram_a1_converb_coordinating_j_ch"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_vowel_reduction_non_initial"], "phonologyReviewed": ["phono_a1_nasal_vowels"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_14_countryside_ger_visiting_etiquette"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_culture_traditions", "lex_domain_housing_home"],
            "previousVocabularyReused": ["барих", "өргөх", "тэгш", "холбох", "эсгий", "бүс"],
            "readingObjective": "",
            "listeningObjective": "Identify specific assembly stages (unfolding walls, hoisting the crown, inserting roof poles) from live audio commands.",
            "writingObjective": "",
            "spokenProductionObjective": "Explain the sequence of raising a ger to a peer in 3 sentences.",
            "registerTarget": "Spontaneous cooperative countryside work register",
            "pragmaticTarget": "Parsing shouted instructions over windy steppe acoustics during communal labor.",
            "prerequisiteLessonIds": ["les_a2_104_01_ger_architectural_anatomy_lexicon"],
            "reviewsLessonIds": ["les_a1_95_04_travel_podcast_acoustic_listening"],
            "reviewsUnitIds": ["unit_a2_95_narrating_past_vacations_countrysid"],
            "reviewReason": "Applies countryside listening skills to communal nomadic construction.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Authentic steppe audio with wind ambiance, wooden clatter, and communal calls.",
            "successCriteria": [
                "Orders the 4 stages of ger assembly correctly based on heard directives",
                "Identifies which structural part requires immediate adjustment in the audio"
            ],
            "masteryEvidence": "Accurately sequences the full ger erection process based on raw audio commands.",
            "recommendedExerciseModalities": ["listening_comprehension", "sequencing", "matching"]
        },
        {
            "lessonId": "les_a2_104_04_guiding_nomadic_homestay_guests_dialogue",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 4,
            "title": "Welcome to Our Ger: Introducing Nomadic Architecture to Visitors",
            "lessonType": "dialogue_work",
            "primaryPurpose": "Master spoken communication for guiding a newcomer or foreign guest into a traditional ger, explaining architectural features, sacred orientation, and heating stove operation.",
            "communicativeOutcome": "Give a complete verbal tour of a traditional ger to a visiting guest: point out the crown and pillars, explain natural solar timekeeping through the toono, and invite them to the hoimor.",
            "objectivesIntroduced": ["obj_a2_104_04_ger_tour_dialogue"],
            "objectivesPracticed": ["obj_a2_104_01_ger_anatomy_lexicon", "obj_a2_104_02_read_ger_spatial_zoning"],
            "objectivesReviewed": ["obj_a1_16_01_greet_time_of_day"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_predicate_adjective_nominal", "gram_a1_verb_imperative_polite_aarai"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_intonation_polite"], "phonologyReviewed": ["phono_a1_vowel_length_distinction"],
            "communicativeFunctionsIntroduced": ["comm_a2_14_countryside_ger_visiting_etiquette"],
            "communicativeFunctionsPracticed": ["comm_a1_16_greetings_time_of_day"],
            "communicativeFunctionsReviewed": ["comm_a1_13_apologies_politeness"],
            "newProductiveLemmaTarget": 7, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_culture_traditions", "lex_domain_social_interaction"],
            "previousVocabularyReused": ["тавтай морил", "хоймор", "зуух", "нар", "цаг", "суух"],
            "readingObjective": "",
            "listeningObjective": "Understand guest asking how the felt insulation protects against winter cold (-40°C).",
            "writingObjective": "",
            "spokenProductionObjective": "Guide visitor: 'Манай гэрт тавтай морилно уу! Та хойморт тухалж сууна уу. Дээшээ харвал энэ нь тооно бөгөөд нарны тусгалаар цаг мэддэг'.",
            "registerTarget": "Warm hospitable cultural interpretation register",
            "pragmaticTarget": "Explaining nomadic wisdom and living culture with pride and gracious hospitality.",
            "prerequisiteLessonIds": ["les_a2_104_02_sacred_orientation_interior_zones_reading", "les_a2_104_03_raising_a_ger_acoustic_listening"],
            "reviewsLessonIds": ["les_a1_97_03_extending_invitations_dialogue"],
            "reviewsUnitIds": ["unit_a2_97_extending_social_invitations_to_gat"],
            "reviewReason": "Fuses social welcoming etiquette with traditional nomadic architecture interpretation.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Warm, proud host guiding an appreciative guest into a cozy countryside ger.",
            "successCriteria": [
                "Names at least 4 structural elements and explains their practical or cultural role",
                "Invites guest to sit in the culturally appropriate quadrant with polite honorific phrasing"
            ],
            "masteryEvidence": "Conducts a 5-turn cultural tour dialogue welcoming a visitor into a ger flawlessly.",
            "recommendedExerciseModalities": ["role-play response", "dialogue_completion", "listening_comprehension"]
        }
    ])

    # =========================================================================
    # UNIT 105: Ger Etiquette & Concessive Converb: -вч / боловч (pos 105)
    # 5 Lessons | Targets: ProdLem=21, RecLem=10, ProdExp=5, RecExp=3
    # Budget: (5,2,1,1), (6,3,1,1), (5,3,2,1), (0,0,0,0), (5,2,1,0) = (21, 10, 5, 3)
    # =========================================================================
    u = u_map[105]
    uid = u["unitId"]
    lessons.extend([
        {
            "lessonId": "les_a2_105_01_concessive_converb_vch_intro",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 1,
            "title": "Although & Even Though: The Concessive Converb (-вч / боловч)",
            "lessonType": "grammar_introduction",
            "primaryPurpose": "Introduce the concessive converb suffix (-вч / -эвч / -овч / -өвч) and periphrastic marker боловч ('although / even though / despite'), enabling complex subordinate clauses expressing contrast or unexpected outcomes.",
            "communicativeOutcome": "Form concessive complex sentences: 'Гадаа хүйтэн байвч, гэрийн дотор маш дулаахан байна' (Although it is cold outside, inside the ger it is very warm), 'Ядарсан боловч ажлаа дуусгав' (Although tired, finished the work).",
            "objectivesIntroduced": ["obj_a2_105_01_concessive_converb_vch"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_a2_104_01_ger_anatomy_lexicon"],
            "grammarIntroduced": ["gram_a2_converb_concessive_vch_bolovch"],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_converb_conditional_val", "gram_a1_predicate_adjective_nominal"],
            "phonologyIntroduced": ["phono_a2_concessive_vch_juncture"],
            "phonologyPracticed": ["phono_a1_masculine_feminine_harmony"], "phonologyReviewed": ["phono_a1_consonant_clusters"],
            "communicativeFunctionsIntroduced": ["comm_a2_14_countryside_ger_visiting_etiquette"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_culture_traditions", "lex_domain_social_interaction"],
            "previousVocabularyReused": ["хүйтэн", "дулаан", "хэцүү", "гэхдээ", "боловч", "байх"],
            "readingObjective": "Read a cultural article discussing how nomadic pastoralism thrives despite extreme Siberian winters.",
            "listeningObjective": "Identify concessive clauses (-вч / боловч) in conversational audio debates.",
            "writingObjective": "Combine 4 pairs of contrasting independent clauses into complex concessive sentences using -вч.",
            "spokenProductionObjective": "Express concessive contrast: 'Хол зам туулсан боловч, бид огт ядраагүй'.",
            "registerTarget": "Standard subordinate clause complex register",
            "pragmaticTarget": "Balancing contrasting realities and acknowledging hardships without complaining.",
            "prerequisiteLessonIds": ["les_a2_104_01_ger_architectural_anatomy_lexicon"],
            "reviewsLessonIds": ["les_a1_50_01_sequential_converb_aad"],
            "reviewsUnitIds": ["unit_a1_50_sequential_converb_clause_connector"],
            "reviewReason": "Expands subordinate converbial repertoire from sequence (-аад) to concession (-вч).",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Model phonological attachment of -вч across vowel and consonant stems.",
            "successCriteria": [
                "Attaches -вч correctly according to vowel harmony and epenthesis rules",
                "Constructs concessive sentences with боловч after nouns, adjectives, or past participles"
            ],
            "masteryEvidence": "Produces 'Хэдийгээр бороо орсон боловч бид аяллаа үргэлжлүүллээ' flawlessly.",
            "recommendedExerciseModalities": ["suffix_selection", "clause_combination", "matching"]
        },
        {
            "lessonId": "les_a2_105_02_sacred_threshold_hearth_taboos_lexicon",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 2,
            "title": "Thresholds & Sacred Flames: Ger Taboos & Visiting Customs",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Introduce sacred nomadic taboos and visiting etiquette vocabulary (босго гишгэхгүй байх, голомт хүндэтгэх, гал руу хог хаяхгүй, багана түшихгүй, малгай тайлахгүй, цай амсах).",
            "communicativeOutcome": "Explain traditional nomadic etiquette: never step on the door threshold (босго), never pass between the two central pillars, respect the hearth fire (голомт), and accept tea with right hand.",
            "objectivesIntroduced": ["obj_a2_105_02_ger_taboos_etiquette_lexicon"],
            "objectivesPracticed": ["obj_a2_105_01_concessive_converb_vch"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_converb_concessive_vch_bolovch"],
            "grammarReviewed": ["gram_a1_verb_prohibitive_bitgii", "gram_a1_case_instrumental_transport_language"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_consonant_clusters"], "phonologyReviewed": ["phono_a1_vowel_reduction_non_initial"],
            "communicativeFunctionsIntroduced": ["comm_a2_14_countryside_ger_visiting_etiquette"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_culture_traditions", "lex_domain_social_interaction"],
            "previousVocabularyReused": ["босго", "гал", "багана", "хүндэтгэх", "ёс", "хориотой"],
            "readingObjective": "Read a cultural code of conduct poster for foreign travelers visiting nomadic ger camps.",
            "listeningObjective": "Understand an elder herder gently instructing a young visitor on proper hearth customs.",
            "writingObjective": "List 5 essential cultural taboos (цээрлэх ёс) when visiting a nomadic ger in Cyrillic.",
            "spokenProductionObjective": "Explain etiquette: 'Монгол гэрт орохдоо босгон дээр гишгэж болохгүй, мөн гал руу хог хаяж цээрлэнэ'.",
            "registerTarget": "Sacred cultural tradition and behavioral etiquette register",
            "pragmaticTarget": "Understanding the spiritual and practical significance behind ancient pastoral taboos.",
            "prerequisiteLessonIds": ["les_a2_105_01_concessive_converb_vch_intro"],
            "reviewsLessonIds": ["les_a1_87_01_modal_permission_bolno_intro"],
            "reviewsUnitIds": ["unit_a2_87_modal_permission_possibility_suffix"],
            "reviewReason": "Applies modal prohibitions (болохгүй, цээрлэнэ) to traditional sacred taboos.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Pronounce sacred cultural taboo terminology clearly.",
            "successCriteria": [
                "Defines босго (threshold), голомт (hearth/sacred fire), цээрлэх (to taboo/abstain)",
                "Explains why stepping on the threshold is considered disrespectful to the host"
            ],
            "masteryEvidence": "Accurately details 5 inviolable ger etiquette rules using appropriate prohibitive forms.",
            "recommendedExerciseModalities": ["categorization", "contextual_cloze", "matching"]
        },
        {
            "lessonId": "les_a2_105_03_nomadic_hospitality_tea_offering_dialogue",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 3,
            "title": "Milk Tea & Snuff Bottles: The Pastoral Greeting Ritual",
            "lessonType": "dialogue_work",
            "primaryPurpose": "Master spoken communication for traditional pastoral guest greetings: exchanging snuff bottles (хөөрөг зөрүүлэх), inquiring about herd well-being (тарган тавтай өвөлжиж байна уу?), and receiving milk tea with both hands.",
            "communicativeOutcome": "Perform the traditional nomadic greeting ritual seamlessly upon entering a herder's ger: exchange seasonal greetings, accept milk tea respectfully, and engage in gracious small talk.",
            "objectivesIntroduced": ["obj_a2_105_03_pastoral_greeting_ritual_dialogue"],
            "objectivesPracticed": ["obj_a2_105_01_concessive_converb_vch", "obj_a2_105_02_ger_taboos_etiquette_lexicon"],
            "objectivesReviewed": ["obj_a1_16_01_greet_time_of_day"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_converb_concessive_vch_bolovch"],
            "grammarReviewed": ["gram_a1_case_comitative_association", "gram_a1_verb_imperative_polite_aarai"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_intonation_polite"], "phonologyReviewed": ["phono_a1_diphthongs"],
            "communicativeFunctionsIntroduced": ["comm_a2_14_countryside_ger_visiting_etiquette"],
            "communicativeFunctionsPracticed": ["comm_a1_16_greetings_time_of_day"],
            "communicativeFunctionsReviewed": ["comm_a1_13_apologies_politeness"],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_culture_traditions", "lex_domain_social_interaction"],
            "previousVocabularyReused": ["цай", "уух", "мал", "өвөлжих", "зусах", "баярлалаа"],
            "readingObjective": "",
            "listeningObjective": "Understand an elder host welcoming weary travelers with fresh hot milk tea and clotted cream (өрөм).",
            "writingObjective": "",
            "spokenProductionObjective": "Perform pastoral greeting: 'Сайн байна уу? Мал сүрэг тарган тавтай зусаж байна уу? Сайхан цай байна, баярлалаа'.",
            "registerTarget": "High traditional pastoral courtesy register",
            "pragmaticTarget": "Holding tea bowl with right hand supported by left elbow, sipping before putting down.",
            "prerequisiteLessonIds": ["les_a2_105_02_sacred_threshold_hearth_taboos_lexicon"],
            "reviewsLessonIds": ["les_a1_16_05_greeting_dialogue_practice"],
            "reviewsUnitIds": ["unit_a1_16_daily_greetings_time_of_day_cultura"],
            "reviewReason": "Evolves basic greetings into the full ceremonial nomadic pastoral greeting ritual.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Warm, resonant countryside dialogue between herder host and respectful visiting guest.",
            "successCriteria": [
                "Uses traditional seasonal livestock inquiry formula appropriately",
                "Receives tea and dairy offerings with proper verbal gratitude and cultural gestures"
            ],
            "masteryEvidence": "Executes a 5-turn pastoral greeting dialogue with impeccable cultural propriety.",
            "recommendedExerciseModalities": ["role-play response", "dialogue_completion", "listening_comprehension"]
        },
        {
            "lessonId": "les_a2_105_04_steppe_etiquette_tales_acoustic_listening",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 4,
            "title": "Acoustic Lab: Steppe Etiquette Tales & Cultural Misunderstandings",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop acoustic listening comprehension of an audio story narrating a foreign traveler's initial blunders in a herder camp and how the gracious nomadic hosts accommodated them.",
            "communicativeOutcome": "Extract cultural lessons and concessive grammar structures from an audio narrative describing steppe hospitality and mutual cultural adaptation.",
            "objectivesIntroduced": ["obj_a2_105_04_decode_etiquette_narratives"],
            "objectivesPracticed": ["obj_a2_105_01_concessive_converb_vch"], "objectivesReviewed": ["obj_a1_41_01_witnessed_past_laa"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a2_converb_concessive_vch_bolovch", "gram_a1_converb_sequential_aad"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_vowel_reduction_non_initial"], "phonologyReviewed": ["phono_a1_nasal_vowels"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_14_countryside_ger_visiting_etiquette"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_culture_traditions", "lex_domain_travel_transport"],
            "previousVocabularyReused": ["зочин", "айх", "мэдэхгүй", "заах", "инээх", "сурах"],
            "readingObjective": "",
            "listeningObjective": "Identify specific cultural blunders (e.g. whistling inside a ger) mentioned in the 2-minute audio narrative.",
            "writingObjective": "",
            "spokenProductionObjective": "Explain why whistling inside a ger is tabood (it summons storm winds) to a peer.",
            "registerTarget": "Humorous and educational narrative storytelling register",
            "pragmaticTarget": "Understanding the protective logic underlying traditional folkloric taboos.",
            "prerequisiteLessonIds": ["les_a2_105_02_sacred_threshold_hearth_taboos_lexicon"],
            "reviewsLessonIds": ["les_a1_94_04_radio_memoir_acoustic_listening"],
            "reviewsUnitIds": ["unit_a2_94_childhood_hometown_recollections_ea"],
            "reviewReason": "Applies narrative acoustic listening to traditional pastoral folklore and customs.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Warm storytelling audio with gentle humor and steppe ambiance.",
            "successCriteria": [
                "Identifies the 2 etiquette mistakes made by the traveler in the story",
                "Extracts how the hosts explained the custom using concessive converb structures"
            ],
            "masteryEvidence": "Accurately answers 5 comprehension questions analyzing the etiquette story.",
            "recommendedExerciseModalities": ["listening_comprehension", "phonetic_discrimination", "categorization"]
        },
        {
            "lessonId": "les_a2_105_05_homestay_cultural_code_writing",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 5,
            "title": "Nomadic Etiquette Guide: Writing a Countryside Visiting Handbook",
            "lessonType": "grammar_guided_practice",
            "primaryPurpose": "Synthesize concessive converbs (-вч / боловч), ger anatomy, and sacred taboos into a concise written cultural etiquette guide for visitors to nomadic camps.",
            "communicativeOutcome": "Draft a 6-point cultural guidebook entry instructing travelers on proper behavior inside a Mongolian ger, utilizing concessive contrast and respectful modal forms.",
            "objectivesIntroduced": ["obj_a2_105_05_write_etiquette_guide"],
            "objectivesPracticed": ["obj_a2_105_01_concessive_converb_vch", "obj_a2_105_02_ger_taboos_etiquette_lexicon"],
            "objectivesReviewed": ["obj_a1_50_01_sequential_converb"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_converb_concessive_vch_bolovch"],
            "grammarReviewed": ["gram_a1_verb_prohibitive_bitgii", "gram_a1_verb_imperative_polite_aarai"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_14_countryside_ger_visiting_etiquette"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_culture_traditions", "lex_domain_travel_transport"],
            "previousVocabularyReused": ["дүрэм", "ёс", "бичих", "зөвлөмж", "аялагч", "хүндэтгэх"],
            "readingObjective": "Review authentic cultural tourism guidelines for structural layout and tone.",
            "listeningObjective": "",
            "writingObjective": "Draft a 6-sentence visitor etiquette handbook incorporating at least two concessive clauses (-вч / боловч).",
            "spokenProductionObjective": "",
            "registerTarget": "Instructive cultural guidebook register",
            "pragmaticTarget": "Presenting traditional customs clearly, respectfully, and persuasively.",
            "prerequisiteLessonIds": ["les_a2_105_03_nomadic_hospitality_tea_offering_dialogue", "les_a2_105_04_steppe_etiquette_tales_acoustic_listening"],
            "reviewsLessonIds": ["les_a1_50_01_sequential_converb_aad"],
            "reviewsUnitIds": ["unit_a1_50_sequential_converb_clause_connector"],
            "reviewReason": "Combines sequential instructions with concessive clauses in cultural guide writing.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Audio read-back of written cultural etiquette handbook.",
            "successCriteria": [
                "Produces written guidebook containing at least 2 correctly formed concessive clauses in -вч / боловч",
                "Covers entry, seating, tea acceptance, and fire reverence comprehensively"
            ],
            "masteryEvidence": "Drafts 'Гэрт орохдоо босгон дээр бүү гишгээрэй. Цаг агаар халуун байвч, гэрт малгайгаа өмсөж ордог ёстой...' flawlessly.",
            "recommendedExerciseModalities": ["short-answer writing", "sentence construction", "error correction"]
        }
    ])

    return lessons
