"""
Section 5 Generator Part 3 (Units 109 - 111): 15 Lessons
109: Reporting Lost Possessions in City & Countryside (4 lessons)
110: Telephone Courtesy & Deductive Future: -х болно (5 lessons)
111: Waystage Pastoral Capstone & Comprehensive A2 Exit Milestone (6 lessons)
"""

import json
from typing import List, Dict, Any

def get_sec05_part3_lessons(u_map: Dict[int, Any]) -> List[Dict[str, Any]]:
    lessons: List[Dict[str, Any]] = []

    # =========================================================================
    # UNIT 109: Reporting Lost Possessions in City & Countryside (pos 109)
    # 4 Lessons | Targets: ProdLem=19, RecLem=9, ProdExp=5, RecExp=3
    # Budget: (7,3,2,1), (5,3,1,1), (0,0,0,0), (7,3,2,1) = (19, 9, 5, 3)
    # =========================================================================
    u = u_map[109]
    uid = u["unitId"]
    lessons.extend([
        {
            "lessonId": "les_a2_109_01_lost_property_inquiry_lexicon",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 1,
            "title": "Lost & Found: Reporting Missing Possessions & Identifying Belongings",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Introduce lost property, item descriptions, and search inquiry vocabulary (гээх, хаях, гээгдүүлсэн эд зүйл, олох, түрийвч, бичиг баримт, түлхүүр, эрэх, хайх, байцаагч).",
            "communicativeOutcome": "Report lost or misplaced personal items (wallet, ID card, backpack, phone, keys) at a hotel desk, airport lost-and-found, or police substation.",
            "objectivesIntroduced": ["obj_a2_109_01_lost_property_lexicon"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_a2_108_01_negative_indefinites"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_genitive_possession", "gram_a1_predicate_adjective_nominal"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_consonant_clusters"], "phonologyReviewed": ["phono_a1_vowel_reduction_non_initial"],
            "communicativeFunctionsIntroduced": ["comm_a2_28_describing_lost_items"],
            "communicativeFunctionsPracticed": ["comm_a2_02_describing_appearance_clothing"], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 7, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_civic_administrative", "lex_domain_commerce_transactions"],
            "previousVocabularyReused": ["гээх", "олох", "түрийвч", "утас", "цүнх", "хайх"],
            "readingObjective": "Read public lost-and-found notice board listings describing discovered items.",
            "listeningObjective": "Understand an inquiry clerk asking when and where a bag was last seen.",
            "writingObjective": "List 6 common personal belongings with color and brand descriptors in Cyrillic.",
            "spokenProductionObjective": "Report a lost item: 'Би таксинд хар өнгийн арьсан түрийвчээ гээчихлээ. Дотор нь миний иргэний үнэмлэх байсан'.",
            "registerTarget": "Administrative inquiry and public service desk register",
            "pragmaticTarget": "Providing precise identifying features (color, brand, distinguishing marks, contents) calmly.",
            "prerequisiteLessonIds": ["les_a2_108_01_indefinite_pronouns_negation_intro"],
            "reviewsLessonIds": ["les_a1_70_01_banking_atm_cash_intro"],
            "reviewsUnitIds": ["unit_a2_70_banking_basics_atms_cash_withdrawal"],
            "reviewReason": "Connects financial card replacement needs with lost property reporting.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Pronounce lost property and personal item terminology clearly.",
            "successCriteria": [
                "Defines гээгдүүлсэн эд зүйл (lost property), түрийвч (wallet), бичиг баримт (documents)",
                "Forms detailed item descriptions including material, color, and contents"
            ],
            "masteryEvidence": "Accurately files an oral lost-item claim describing a missing backpack and contents.",
            "recommendedExerciseModalities": ["categorization", "matching", "contextual_cloze"]
        },
        {
            "lessonId": "les_a2_109_02_lost_and_found_bulletin_reading",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 2,
            "title": "Deciphering Lost Property Notices & Community Finder Boards",
            "lessonType": "reading_development",
            "primaryPurpose": "Develop targeted reading comprehension of online community lost-and-found announcements, social media group posts, and municipal transit claim forms.",
            "communicativeOutcome": "Inspect online lost-and-found bulletins, verify claimed item details, locations found, and contact telephone numbers.",
            "objectivesIntroduced": ["obj_a2_109_02_read_lost_notices"],
            "objectivesPracticed": ["obj_a2_109_01_lost_property_lexicon"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_dative_locative_location", "gram_a1_case_instrumental_transport_language"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_28_describing_lost_items"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_civic_administrative", "lex_domain_social_interaction"],
            "previousVocabularyReused": ["зар", "олсон", "утсаар", "холбогдох", "шагналтай", "хүлээлгэн өгөх"],
            "readingObjective": "Locate date found, route number, and handover desk location in a 120-word transit lost-property notice.",
            "listeningObjective": "",
            "writingObjective": "Transcribe contact info and identifying marks from a finder's notice into an inquiry claim.",
            "spokenProductionObjective": "Explain to a peer that an item matching their description was posted on the notice board.",
            "registerTarget": "Public announcement and community board register",
            "pragmaticTarget": "Verifying ownership claims through unique non-public identifying details.",
            "prerequisiteLessonIds": ["les_a2_109_01_lost_property_inquiry_lexicon"],
            "reviewsLessonIds": ["les_a1_69_02_postal_forms_tracking_reading"],
            "reviewsUnitIds": ["unit_a2_69_postal_courier_package_delivery_ser"],
            "reviewReason": "Extends postal tracking form reading to public lost-and-found notices.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Read public lost-and-found announcement aloud.",
            "successCriteria": [
                "Identifies found item type, discovery location, and custodian contact information",
                "Recognizes terms like шагналтай (reward offered) and эзэн нь холбогдоно уу (owner please contact)"
            ],
            "masteryEvidence": "Correctly matches 3 lost claims to 3 published finder announcements.",
            "recommendedExerciseModalities": ["reading_comprehension", "matching", "categorization"]
        },
        {
            "lessonId": "les_a2_109_03_transit_lost_property_acoustic_listening",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 3,
            "title": "Acoustic Lab: Lost Property Desks at Bus Terminals & Train Stations",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop acoustic listening comprehension of fast-paced exchanges at busy transit information desks where passengers describe items accidentally left behind on vehicles.",
            "communicativeOutcome": "Understand dialogue between desk clerk and claimant: verify vehicle license number, departure time, seat location, and physical appearance of forgotten luggage.",
            "objectivesIntroduced": ["obj_a2_109_03_decode_lost_property_inquiry"],
            "objectivesPracticed": ["obj_a2_109_01_lost_property_lexicon"], "objectivesReviewed": ["obj_a1_36_01_calendar_dates"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_dative_locative_location", "gram_a1_polar_questions_uu_uu"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_vowel_reduction_non_initial"], "phonologyReviewed": ["phono_a1_nasal_vowels"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_28_describing_lost_items"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_civic_administrative", "lex_domain_travel_transport"],
            "previousVocabularyReused": ["автобус", "мартсан", "суудал", "шалгах", "авах", "хүлээх"],
            "readingObjective": "",
            "listeningObjective": "Identify specific lost item features and seat location from an audio exchange at Dragon Bus Terminal (Драгон төв).",
            "writingObjective": "",
            "spokenProductionObjective": "Explain what the clerk discovered inside the bag to a partner in 3 sentences.",
            "registerTarget": "Busy public transit service desk acoustic register",
            "pragmaticTarget": "Parsing rapid administrative questions amidst background station reverberation.",
            "prerequisiteLessonIds": ["les_a2_109_01_lost_property_inquiry_lexicon"],
            "reviewsLessonIds": ["les_a1_72_02_commuter_acoustic_decoding_lab"],
            "reviewsUnitIds": ["unit_a2_72_urban_transit_capstone_navigating_the"],
            "reviewReason": "Applies transit auditory comprehension to lost property inquiries.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Realistic bus terminal acoustics with public announcements and station clerk dialogue.",
            "successCriteria": [
                "Extracts departure time and bus route number accurately from audio",
                "Identifies whether the item was successfully recovered by the clerk"
            ],
            "masteryEvidence": "Accurately fills out a lost property recovery slip based on station audio.",
            "recommendedExerciseModalities": ["listening_comprehension", "phonetic_discrimination", "categorization"]
        },
        {
            "lessonId": "les_a2_109_04_lost_item_report_dialogue",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 4,
            "title": "Filing a Claim: Explaining What Happened to the Duty Officer",
            "lessonType": "dialogue_work",
            "primaryPurpose": "Master spoken communication for interacting with a hotel concierge, transit dispatcher, or police duty officer to report a missing possession.",
            "communicativeOutcome": "Explain the full circumstances of a lost possession: where you last had it, what you were doing, what it looks like, and leaving your contact number.",
            "objectivesIntroduced": ["obj_a2_109_04_lost_report_dialogue"],
            "objectivesPracticed": ["obj_a2_109_01_lost_property_lexicon", "obj_a2_109_02_read_lost_notices"],
            "objectivesReviewed": ["obj_a1_16_01_greet_time_of_day"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_ablative_origin", "gram_a1_verb_tense_past_witnessed_laa"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_intonation_polite"], "phonologyReviewed": ["phono_a1_vowel_length_distinction"],
            "communicativeFunctionsIntroduced": ["comm_a2_28_describing_lost_items"],
            "communicativeFunctionsPracticed": ["comm_a1_16_greetings_time_of_day"],
            "communicativeFunctionsReviewed": ["comm_a1_13_apologies_politeness"],
            "newProductiveLemmaTarget": 7, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_civic_administrative", "lex_domain_social_interaction"],
            "previousVocabularyReused": ["гээсэн", "орхисон", "хайж байна", "дугаар", "мэдэгдэх", "туслах"],
            "readingObjective": "",
            "listeningObjective": "Understand duty officer asking for signature and passport number to process official claim.",
            "writingObjective": "",
            "spokenProductionObjective": "Report missing backpack: 'Би өчигдөр орой ресторанд хар цүнхээ мартаад гарчихжээ. Олдвол энэ дугаарт залгаж мэдэгдэнэ үү?'.",
            "registerTarget": "Formal administrative complaint and inquiry register",
            "pragmaticTarget": "Maintaining polite composure and providing clear descriptive facts under stress.",
            "prerequisiteLessonIds": ["les_a2_109_02_lost_and_found_bulletin_reading", "les_a2_109_03_transit_lost_property_acoustic_listening"],
            "reviewsLessonIds": ["les_a1_81_05_tailoring_repair_dialogue"],
            "reviewsUnitIds": ["unit_a2_81_errands_dry_cleaning_tailoring_re"],
            "reviewReason": "Spirals service desk customer dialogues into administrative recovery interactions.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Courteous, helpful dialogue between duty officer and relieved customer.",
            "successCriteria": [
                "Explains timeline and location of loss with past verbal constructions",
                "Provides distinguishing features and valid callback number clearly"
            ],
            "masteryEvidence": "Conducts a 5-turn lost item report dialogue leaving complete verifiable details.",
            "recommendedExerciseModalities": ["role-play response", "dialogue_completion", "listening_comprehension"]
        }
    ])

    # =========================================================================
    # UNIT 110: Telephone Courtesy & Deductive Future: -х болно (pos 110)
    # 5 Lessons | Targets: ProdLem=21, RecLem=10, ProdExp=5, RecExp=3
    # Budget: (5,2,1,1), (6,3,1,1), (5,3,2,1), (0,0,0,0), (5,2,1,0) = (21, 10, 5, 3)
    # =========================================================================
    u = u_map[110]
    uid = u["unitId"]
    lessons.extend([
        {
            "lessonId": "les_a2_110_01_deductive_future_kh_bolno_intro",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 1,
            "title": "It Will Come to Pass: The Deductive Future (-х болно / боломжтой)",
            "lessonType": "grammar_introduction",
            "primaryPurpose": "Introduce the deductive future and polite eventuality construction (-х болно / -х боломжтой) used in administrative forecasts, polite announcements, and formal telephone confirmations.",
            "communicativeOutcome": "State polite commitments and schedule eventualities: 'Бид маргааш эргэн залгах болно' (We will call back tomorrow), 'Та өглөө ирэх боломжтой юу?' (Will you be able to come in the morning?).",
            "objectivesIntroduced": ["obj_a2_110_01_deductive_future_kh_bolno"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_a2_109_01_lost_property_lexicon"],
            "grammarIntroduced": ["gram_a2_verb_future_deductive_kh_bolno"],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_verbal_noun_future_participle_h", "gram_a1_existential_baina_baihgui"],
            "phonologyIntroduced": ["phono_a2_deductive_future_phrasing"],
            "phonologyPracticed": ["phono_a1_vowel_length_distinction"], "phonologyReviewed": ["phono_a1_masculine_feminine_harmony"],
            "communicativeFunctionsIntroduced": ["comm_a2_29_phone_conversations_leaving_messages"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_communication_speech", "lex_domain_workplace_occupations"],
            "previousVocabularyReused": ["болох", "залгах", "ирнэ", "хэлэх", "боломжтой", "хийх"],
            "readingObjective": "Read customer service email confirmations promising callback timeframes.",
            "listeningObjective": "Identify deductive future predicates (-х болно) in automated customer service announcements.",
            "writingObjective": "Formulate 4 polite formal commitments using -х болно.",
            "spokenProductionObjective": "State formal commitment: 'Манай менежер тантай маргааш үдээс хойш холбогдох болно'.",
            "registerTarget": "High polite administrative and customer service register",
            "pragmaticTarget": "Using -х болно as a respectful, dignified alternative to plain future verb forms.",
            "prerequisiteLessonIds": ["les_a2_109_01_lost_property_inquiry_lexicon"],
            "reviewsLessonIds": ["les_a1_20_01_expressing_intentions_intro"],
            "reviewsUnitIds": ["unit_a1_20_expressing_intentions_wishes_fut"],
            "reviewReason": "Elevates simple future intentions into formal deductive promises.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Model dignified cadence in polite administrative promises ending in -х болно.",
            "successCriteria": [
                "Pairs future participle (-х) with auxiliary болно / боломжтой",
                "Applies deductive future in professional phone and email promises"
            ],
            "masteryEvidence": "Produces 'Бид таны хүсэлтийг шуурхай шийдвэрлэх болно' with polished diction.",
            "recommendedExerciseModalities": ["suffix_selection", "sentence_construction", "matching"]
        },
        {
            "lessonId": "les_a2_110_02_telephone_etiquette_office_lexicon",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 2,
            "title": "May I Ask Who Is Calling: Professional Telephone Etiquette Vocabulary",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Introduce professional office telephone protocol and phrasing (хэнтэй ярьж байна вэ, түр хүлээнэ үү, шугам холбох, мессеж үлдээх, таслах, дугаар андуурах).",
            "communicativeOutcome": "Conduct professional office phone calls: introduce your department, ask for callers' names politely, place calls on hold, and transfer extensions.",
            "objectivesIntroduced": ["obj_a2_110_02_telephone_etiquette_lexicon"],
            "objectivesPracticed": ["obj_a2_110_01_deductive_future_kh_bolno"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_verb_future_deductive_kh_bolno"],
            "grammarReviewed": ["gram_a1_verb_imperative_polite_aarai", "gram_a1_interrogative_wh_pronouns"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_consonant_clusters"], "phonologyReviewed": ["phono_a1_vowel_reduction_non_initial"],
            "communicativeFunctionsIntroduced": ["comm_a2_29_phone_conversations_leaving_messages"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_communication_speech", "lex_domain_workplace_occupations"],
            "previousVocabularyReused": ["утас", "ярих", "хүлээх", "холбох", "компани", "алба"],
            "readingObjective": "Read an office employee telephone etiquette standard operating manual.",
            "listeningObjective": "Understand an administrative receptionist placing a client on brief hold to check availability.",
            "writingObjective": "List 5 essential phone courtesy phrases in Cyrillic.",
            "spokenProductionObjective": "Answer telephone: 'Сайн байна уу? 'Монгол Экспедишн' компани байна. Танд юугаар туслах вэ?'.",
            "registerTarget": "Corporate front-desk telephone courtesy register",
            "pragmaticTarget": "Projecting warmth, professionalism, and prompt attentiveness over audio-only phone channels.",
            "prerequisiteLessonIds": ["les_a2_110_01_deductive_future_kh_bolno_intro"],
            "reviewsLessonIds": ["les_a1_69_03_courier_phone_listening"],
            "reviewsUnitIds": ["unit_a2_69_postal_courier_package_delivery_ser"],
            "reviewReason": "Evolves delivery phone calls into comprehensive corporate telephone protocols.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Pronounce professional telephone formulas clearly.",
            "successCriteria": [
                "Defines холбох (transfer/connect), түр хүлээх (hold on a moment), андуурах (dial wrong number)",
                "Forms polite phone inquiries: 'Хэнтэй холбогдохыг хүсэж байна вэ?'"
            ],
            "masteryEvidence": "Accurately articulates all standard phone exchange formulas across 4 call scenarios.",
            "recommendedExerciseModalities": ["categorization", "contextual_cloze", "matching"]
        },
        {
            "lessonId": "les_a2_110_03_corporate_switchboard_dialogue",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 3,
            "title": "Please Hold the Line: Switchboard Transfers & Leaving Voicemails",
            "lessonType": "dialogue_work",
            "primaryPurpose": "Develop spoken communicative fluency for handling multi-branch phone inquiries: transferring calls to specific extensions, explaining lines are busy, and recording detailed callback requests.",
            "communicativeOutcome": "Manage an office switchboard exchange: direct caller to accounting or sales, inform them that the line is engaged, and take down a comprehensive callback memo.",
            "objectivesIntroduced": ["obj_a2_110_03_switchboard_dialogue"],
            "objectivesPracticed": ["obj_a2_110_01_deductive_future_kh_bolno", "obj_a2_110_02_telephone_etiquette_lexicon"],
            "objectivesReviewed": ["obj_a1_16_01_greet_time_of_day"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_verb_future_deductive_kh_bolno"],
            "grammarReviewed": ["gram_a1_converb_sequential_aad", "gram_a1_verb_imperative_polite_aarai"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_intonation_polite"], "phonologyReviewed": ["phono_a1_diphthongs"],
            "communicativeFunctionsIntroduced": ["comm_a2_29_phone_conversations_leaving_messages"],
            "communicativeFunctionsPracticed": ["comm_a1_16_greetings_time_of_day"],
            "communicativeFunctionsReviewed": ["comm_a1_13_apologies_politeness"],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_communication_speech", "lex_domain_workplace_occupations"],
            "previousVocabularyReused": ["шугам", "завгүй", "дарга", "тэмдэглэх", "дугаар", "эргэн залгах"],
            "readingObjective": "",
            "listeningObjective": "Understand caller requesting transfer to the international marketing director.",
            "writingObjective": "",
            "spokenProductionObjective": "Handle transfer: 'Түр хүлээнэ үү, би таныг захирлын туслахтай холбож өгөх болно... Уучлаарай, одоогоор шугам завгүй байна. Та зурвас үлдээх үү?'.",
            "registerTarget": "Corporate switchboard and administrative receptionist register",
            "pragmaticTarget": "Maintaining polite poise when managing busy lines and impatient callers.",
            "prerequisiteLessonIds": ["les_a2_110_02_telephone_etiquette_office_lexicon"],
            "reviewsLessonIds": ["les_a1_99_03_passing_messages_phone_dialogue"],
            "reviewsUnitIds": ["unit_a2_99_reporting_third_party_statements_ve"],
            "reviewReason": "Combines telephone message relay with deductive future commitments.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Polished telephone audio with realistic phone filter and transfer tones.",
            "successCriteria": [
                "Places caller on hold politely and updates them on line status",
                "Records callback number and promises follow-up using -х болно"
            ],
            "masteryEvidence": "Conducts a 5-turn corporate receptionist phone call flawlessly.",
            "recommendedExerciseModalities": ["role-play response", "dialogue_completion", "listening_comprehension"]
        },
        {
            "lessonId": "les_a2_110_04_automated_voicemail_acoustic_listening",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 4,
            "title": "Acoustic Lab: Automated IVR Menus & Recorded Voicemail Outlines",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop acoustic listening comprehension of automated Interactive Voice Response (IVR) phone menus ('Нэгийг дарна уу, хоёрыг дарна уу') and recorded answering machine announcements.",
            "communicativeOutcome": "Navigate automated telephone systems: listen to numeric menu options, select correct department, and listen to recorded operating hours.",
            "objectivesIntroduced": ["obj_a2_110_04_decode_ivr_menus"],
            "objectivesPracticed": ["obj_a2_110_01_deductive_future_kh_bolno"], "objectivesReviewed": ["obj_a1_27_01_counting_tens_hundreds"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a2_verb_future_deductive_kh_bolno", "gram_a1_verb_imperative_polite_aarai"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_vowel_reduction_non_initial"], "phonologyReviewed": ["phono_a1_nasal_vowels"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_29_phone_conversations_leaving_messages"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_communication_speech", "lex_domain_technology_devices"],
            "previousVocabularyReused": ["товч", "дарах", "лавлах", "ажиллах", "цаг", "сонгох"],
            "readingObjective": "",
            "listeningObjective": "Identify which key to press for flight cancellations in an automated airline phone system.",
            "writingObjective": "",
            "spokenProductionObjective": "Explain the phone menu options to a partner based on the automated recording.",
            "registerTarget": "Automated IVR synthetic telephone register",
            "pragmaticTarget": "Extracting key navigational numbers from rapid automated voice prompts without repeating.",
            "prerequisiteLessonIds": ["les_a2_110_02_telephone_etiquette_office_lexicon"],
            "reviewsLessonIds": ["les_a1_70_03_teller_guidance_listening"],
            "reviewsUnitIds": ["unit_a2_70_banking_basics_atms_cash_withdrawal"],
            "reviewReason": "Transfers automated ATM audio comprehension to telephony IVR systems.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Crisp automated IVR telephone audio with simulated dial tones and numeric prompts.",
            "successCriteria": [
                "Selects the correct numeric key for 3 distinct customer service needs",
                "Extracts office working hours stated in the voicemail greeting"
            ],
            "masteryEvidence": "Accurately navigates a 3-tier automated banking IVR menu based on audio prompts.",
            "recommendedExerciseModalities": ["listening_comprehension", "phonetic_discrimination", "sequencing"]
        },
        {
            "lessonId": "les_a2_110_05_phone_log_callback_memo_writing",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 5,
            "title": "Call Log Protocol: Writing Workplace Phone Records & Action Summaries",
            "lessonType": "grammar_guided_practice",
            "primaryPurpose": "Synthesize deductive future forms (-х болно), telephone vocabulary, and reported action directives into a formal corporate call log register.",
            "communicativeOutcome": "Maintain an official office call log sheet: record incoming inquiries, summarize caller requests, assign action items, and note committed callback dates.",
            "objectivesIntroduced": ["obj_a2_110_05_write_call_logs"],
            "objectivesPracticed": ["obj_a2_110_01_deductive_future_kh_bolno", "obj_a2_110_02_telephone_etiquette_lexicon"],
            "objectivesReviewed": ["obj_a1_50_01_sequential_converb"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_verb_future_deductive_kh_bolno"],
            "grammarReviewed": ["gram_a1_case_dative_locative_time", "gram_a1_converb_coordinating_j_ch"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_29_phone_conversations_leaving_messages"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_communication_speech", "lex_domain_workplace_occupations"],
            "previousVocabularyReused": ["бүртгэл", "утас", "огноо", "шийдвэрлэх", "хариулах", "бичих"],
            "readingObjective": "Review professional administrative call log templates from international Mongolian corporations.",
            "listeningObjective": "",
            "writingObjective": "Draft a 5-entry workplace telephone log utilizing -х болно for pending action items.",
            "spokenProductionObjective": "",
            "registerTarget": "Administrative record-keeping and workflow documentation register",
            "pragmaticTarget": "Maintaining precise chronological accountability for all institutional communications.",
            "prerequisiteLessonIds": ["les_a2_110_03_corporate_switchboard_dialogue", "les_a2_110_04_automated_voicemail_acoustic_listening"],
            "reviewsLessonIds": ["les_a1_99_05_phone_memo_message_slip_writing"],
            "reviewsUnitIds": ["unit_a2_99_reporting_third_party_statements_ve"],
            "reviewReason": "Expands single phone message slips into a comprehensive institutional call registry.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Audio read-back of written call log records.",
            "successCriteria": [
                "Produces structured call log with caller name, affiliation, phone number, issue, and follow-up deadline",
                "Uses deductive future for assigned responsibilities: 'Менежер 14:00 цагт эргэн залгах болно'"
            ],
            "masteryEvidence": "Drafts complete, audit-ready call log entries from 2 simulated phone recordings.",
            "recommendedExerciseModalities": ["short-answer writing", "sentence construction", "error correction"]
        }
    ])

    # =========================================================================
    # UNIT 111: Waystage Pastoral Capstone & A2 Exit Milestone (pos 111)
    # 6 Lessons | Targets: ProdLem=24, RecLem=12, ProdExp=8, RecExp=4
    # Budget: (6,3,2,1), (5,3,2,1), (0,0,0,0), (7,3,2,1), (6,3,2,1), (0,0,0,0) = (24, 12, 8, 4)
    # =========================================================================
    u = u_map[111]
    uid = u["unitId"]
    lessons.extend([
        {
            "lessonId": "les_a2_111_01_pastoral_homestay_immersion_lexicon",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 1,
            "title": "Living with Herders: Nomadic Homestay Immersion & Steppe Routines",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Synthesize the entire nomadic pastoral domain: morning animal turnout (мал бэлчээх), penning stock (хотлуулах), fetching well water, gathering argal dung fuel (аргал түүх), preparing evening stew, and sharing tea with nomadic hosts.",
            "communicativeOutcome": "Participate fully in the daily rhythms of a nomadic homestay family, offering help with camp chores, describing pastoral routines, and expressing profound gratitude for hospitality.",
            "objectivesIntroduced": ["obj_a2_111_01_homestay_immersion_lexicon"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_a2_110_01_deductive_future_kh_bolno"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_converb_coordinating_j_ch", "gram_a1_converb_sequential_aad"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_consonant_clusters"], "phonologyReviewed": ["phono_a1_masculine_feminine_harmony"],
            "communicativeFunctionsIntroduced": ["comm_a2_14_countryside_ger_visiting_etiquette", "comm_a2_15_nomadic_livestock_five_animals"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_countryside_nature", "lex_domain_culture_traditions"],
            "previousVocabularyReused": ["гэр", "мал", "аргал", "ус", "хот", "туслах"],
            "readingObjective": "Read a cultural homestay guide outlining daily camp responsibilities and herder expectations.",
            "listeningObjective": "Understand an elder host allocating morning camp tasks among family members.",
            "writingObjective": "List the sequential daily chores of a pastoral nomadic camp from sunrise to sunset in Cyrillic.",
            "spokenProductionObjective": "Offer assistance: 'Би өглөө худаг руу ус авахаар явах уу, эсвэл аргал түүхэд туслах уу?'.",
            "registerTarget": "Warm cooperative pastoral homestay register",
            "pragmaticTarget": "Showing initiative to contribute to camp labor humbly and respectfully.",
            "prerequisiteLessonIds": ["les_a2_110_01_deductive_future_kh_bolno_intro"],
            "reviewsLessonIds": ["les_a1_104_01_ger_architectural_anatomy_lexicon"],
            "reviewsUnitIds": ["unit_a2_104_the_mongolian_ger_architectural_ana"],
            "reviewReason": "Synthesizes ger architecture and etiquette into full immersive camp living.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Pronounce pastoral daily labor and camp vocabulary clearly.",
            "successCriteria": [
                "Defines аргал түүх (gather dried dung fuel), хотлуулах (pen livestock for night), бэлчээх (graze herds)",
                "Forms cooperative offers of assistance in herder camps"
            ],
            "masteryEvidence": "Accurately sequences and describes a full 24-hour day in a nomadic camp.",
            "recommendedExerciseModalities": ["categorization", "contextual_cloze", "matching"]
        },
        {
            "lessonId": "les_a2_111_02_steppeland_memoir_reading",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 2,
            "title": "Deciphering Pastoral Memoirs & Rural Homestay Reflections",
            "lessonType": "reading_development",
            "primaryPurpose": "Develop advanced A2 reading comprehension of authentic published travel essays, student homestay diaries, and cultural reflections recounting transformative stays with nomadic families in the Mongolian steppe.",
            "communicativeOutcome": "Read an extended 180-word narrative essay describing a three-week homestay in the Orkhon Valley, identifying descriptive adjectives, participial relative clauses, and reflective observations.",
            "objectivesIntroduced": ["obj_a2_111_02_read_pastoral_memoirs"],
            "objectivesPracticed": ["obj_a2_111_01_homestay_immersion_lexicon"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_participle_relative_clause_past_san", "gram_a2_converb_concessive_vch_bolovch"],
            "grammarReviewed": ["gram_a1_case_instrumental_transport_language"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_14_countryside_ger_visiting_etiquette"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_countryside_nature", "lex_domain_personal_history"],
            "previousVocabularyReused": ["өдөр", "амьдрал", "сэтгэгдэл", "байгаль", "сурах", "мартагдашгүй"],
            "readingObjective": "Analyze narrative trajectory, key lessons learned, and philosophical reflections across a 180-word homestay memoir.",
            "listeningObjective": "",
            "writingObjective": "Extract 3 core themes from the reading text into a reflection matrix.",
            "spokenProductionObjective": "Explain to a classmate what made the author's stay in the Orkhon Valley so memorable.",
            "registerTarget": "Literary reflective personal travel prose register",
            "pragmaticTarget": "Appreciating emotional and philosophical nuance in personal narrative prose.",
            "prerequisiteLessonIds": ["les_a2_111_01_pastoral_homestay_immersion_lexicon"],
            "reviewsLessonIds": ["les_a1_101_04_biography_profile_reading"],
            "reviewsUnitIds": ["unit_a2_101_personal_history_capstone_autobiogr"],
            "reviewReason": "Synthesizes biographical reading skills with authentic pastoral memoir analysis.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Read extended literary homestay narrative aloud.",
            "successCriteria": [
                "Parses complex sentences containing both concessive (-вч) and relative (-сан) clauses",
                "Answers 5 comprehensive analytical questions on authorial intent and perspective"
            ],
            "masteryEvidence": "Demonstrates unassisted reading comprehension of an authentic 180-word steppe memoir.",
            "recommendedExerciseModalities": ["reading_comprehension", "contextual_cloze", "categorization"]
        },
        {
            "lessonId": "les_a2_111_03_homestay_evening_hearth_acoustic_listening",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 3,
            "title": "Acoustic Lab: Evening by the Hearth — Stories, Legends & Flute Melodies",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop acoustic listening comprehension of an extended 2.5-minute audio recording inside a ger at night: crackling wood fire in the stove, sheep settling outside, an elder reciting a steppe legend, and family members exchanging reflections.",
            "communicativeOutcome": "Extract legendary folklore motifs, character actions, and family dialogue from an authentic evening hearthside audio capture.",
            "objectivesIntroduced": ["obj_a2_111_03_decode_hearthside_folklore"],
            "objectivesPracticed": ["obj_a2_111_01_homestay_immersion_lexicon"], "objectivesReviewed": ["obj_a1_94_04_decode_radio_memoirs"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a2_verb_past_narrative_v", "gram_a2_verb_past_resultative_zhee"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_vowel_reduction_non_initial"], "phonologyReviewed": ["phono_a1_nasal_vowels"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_14_countryside_ger_visiting_etiquette"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_culture_traditions", "lex_domain_personal_history"],
            "previousVocabularyReused": ["домог", "үдэш", "ярих", "сонсох", "өвөө", "сэтгэл"],
            "readingObjective": "",
            "listeningObjective": "Comprehend a 2.5-minute hearthside storytelling recording, identifying the moral of the elder's legend.",
            "writingObjective": "",
            "spokenProductionObjective": "Retell the core event of the herder's legend to a classmate in 3 Mongolian sentences.",
            "registerTarget": "Traditional oral folklore and intimate evening family storytelling register",
            "pragmaticTarget": "Sustaining deep acoustic concentration through multi-layered natural ambient soundscapes.",
            "prerequisiteLessonIds": ["les_a2_111_01_pastoral_homestay_immersion_lexicon"],
            "reviewsLessonIds": ["les_a1_94_04_radio_memoir_acoustic_listening"],
            "reviewsUnitIds": ["unit_a2_94_childhood_hometown_recollections_ea"],
            "reviewReason": "Capstone expansion of narrative acoustic listening to authentic multi-speaker folklore.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Atmospheric evening ger acoustics with crackling stove fire, wind gusts, and elder's resonant storytelling voice.",
            "successCriteria": [
                "Identifies the legendary figures and their animal companions from audio",
                "Extracts narrative past verbs in -в and resultative forms in -жээ from the oral tale"
            ],
            "masteryEvidence": "Accurately diagrams the narrative arc of a 2.5-minute traditional hearthside tale.",
            "recommendedExerciseModalities": ["listening_comprehension", "sequencing", "categorization"]
        },
        {
            "lessonId": "les_a2_111_04_pastoral_life_capstone_narrative_writing",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 4,
            "title": "Nomad's Horizon: Writing a Comprehensive Countryside Homestay Journal",
            "lessonType": "grammar_guided_practice",
            "primaryPurpose": "Synthesize all major A2 syntactic structures (relative clauses, concessive converbs, terminative converbs, narrative past, and reported speech) into an extended written travel memoir.",
            "communicativeOutcome": "Compose an 8-sentence reflective essay detailing your journey to a herder camp, the family's kindness, daily pastoral labor, and how the steppe changed your outlook on life.",
            "objectivesIntroduced": ["obj_a2_111_04_write_homestay_journal"],
            "objectivesPracticed": ["obj_a2_111_01_homestay_immersion_lexicon"], "objectivesReviewed": ["obj_a1_50_01_sequential_converb"],
            "grammarIntroduced": [],
            "grammarPracticed": [
                "gram_a2_participle_relative_clause_past_san",
                "gram_a2_converb_concessive_vch_bolovch",
                "gram_a2_converb_terminative_tal",
                "gram_a2_verb_past_narrative_v"
            ],
            "grammarReviewed": ["gram_a1_converb_sequential_aad"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_14_countryside_ger_visiting_etiquette", "comm_a2_15_nomadic_livestock_five_animals"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 7, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_countryside_nature", "lex_domain_personal_history"],
            "previousVocabularyReused": ["аялал", "дурсамж", "малчин", "гэр", "хөдөө", "сайхан"],
            "readingObjective": "Review exemplary student memoirs for paragraph transitions and rhetorical cohesion.",
            "listeningObjective": "",
            "writingObjective": "Draft an 8-sentence written capstone memoir demonstrating mature clause combining across multiple converb and participial systems.",
            "spokenProductionObjective": "",
            "registerTarget": "Polished personal narrative and travel journal register",
            "pragmaticTarget": "Creating evocative, cohesive paragraphs expressing profound intercultural appreciation.",
            "prerequisiteLessonIds": ["les_a2_111_02_steppeland_memoir_reading", "les_a2_111_03_homestay_evening_hearth_acoustic_listening"],
            "reviewsLessonIds": ["les_a1_94_05_childhood_memoir_essay_writing"],
            "reviewsUnitIds": ["unit_a2_94_childhood_hometown_recollections_ea"],
            "reviewReason": "Expands early childhood essays into a multi-syntactic capstone narrative.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Audio read-back of written capstone journal entry.",
            "successCriteria": [
                "Integrates at least one relative clause, one concessive converb, and one terminative converb",
                "Maintains rich pastoral vocabulary and coherent chronological progression"
            ],
            "masteryEvidence": "Produces an exemplary 8-sentence written memoir achieving 100% syntactic and lexical accuracy.",
            "recommendedExerciseModalities": ["short-answer writing", "sentence construction", "error correction"]
        },
        {
            "lessonId": "les_a2_111_05_full_pastoral_encounter_simulation",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 5,
            "title": "Interactive Simulation: The Steppe Encounter & Parting Blessings",
            "lessonType": "dialogue_work",
            "primaryPurpose": "Execute a full multi-turn unscripted spoken simulation encompassing arrival at a remote nomadic camp, greeting the herders, helping with livestock, sharing an evening meal, and parting with traditional blessings.",
            "communicativeOutcome": "Navigate a 4-stage interactive simulation representing a complete 24-hour pastoral visit, adapting fluidly to dynamic host inquiries and demonstrating flawless cultural etiquette.",
            "objectivesIntroduced": ["obj_a2_111_05_simulate_pastoral_encounter"],
            "objectivesPracticed": ["obj_a2_111_01_homestay_immersion_lexicon"],
            "objectivesReviewed": ["obj_a2_105_03_pastoral_greeting_ritual_dialogue", "obj_a2_106_04_pastoral_life_dialogue", "obj_a2_107_03_dairy_making_dialogue"],
            "grammarIntroduced": [],
            "grammarPracticed": [
                "gram_a2_converb_concessive_vch_bolovch",
                "gram_a2_participle_desire_inclination_maar",
                "gram_a2_verb_past_resultative_zhee"
            ],
            "grammarReviewed": ["gram_a1_case_comitative_association"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_intonation_polite"], "phonologyReviewed": ["phono_a1_vowel_length_distinction"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_14_countryside_ger_visiting_etiquette", "comm_a2_15_nomadic_livestock_five_animals", "comm_a2_30_congratulations_milestones"],
            "communicativeFunctionsReviewed": ["comm_a1_16_greetings_time_of_day"],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_culture_traditions", "lex_domain_social_interaction"],
            "previousVocabularyReused": ["сайн байна уу", "баярлалаа", "зам", "хүрэх", "ерөөе", "баяртай"],
            "readingObjective": "",
            "listeningObjective": "Respond seamlessly to host's farewell toast and traditional travel blessing (Алтан шар зам тань өлзийтэй байг).",
            "writingObjective": "",
            "spokenProductionObjective": "Execute 6 consecutive spoken turns across 4 simulation stages demonstrating total situational independence.",
            "registerTarget": "High traditional steppe guest and host farewell register",
            "pragmaticTarget": "Offering heartfelt reciprocal blessings (Ажил үйлс тань бүтэж, мал сүрэг тань өсөх болтугай) upon departure.",
            "prerequisiteLessonIds": ["les_a2_111_04_pastoral_life_capstone_narrative_writing"],
            "reviewsLessonIds": ["les_a1_101_05_autobiographical_interview_simulation"],
            "reviewsUnitIds": ["unit_a2_101_personal_history_capstone_autobiogr"],
            "reviewReason": "Ultimate spoken interaction simulation integrating all A2 linguistic and cultural competencies.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Provide responsive herder host dialogue turns with steppe wind ambiance.",
            "successCriteria": [
                "Performs greeting, small talk, meal etiquette, and farewell ritual without communicative hesitation",
                "Uses appropriate honorific and traditional blessing formulas with total cultural fluency"
            ],
            "masteryEvidence": "Completes full 4-stage pastoral immersion simulation with zero communicative breakdowns.",
            "recommendedExerciseModalities": ["role-play response", "dialogue_completion", "sequencing"]
        },
        {
            "lessonId": "les_a2_111_06_waystage_a2_exit_milestone_benchmark_checkpoint",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 6,
            "title": "Comprehensive Waystage (A2) Exit Milestone Benchmark Checkpoint",
            "lessonType": "checkpoint",
            "primaryPurpose": "Authoritative CEFR A2 Waystage Exit Benchmark certifying comprehensive mastery across all 48 A2 Units (Units 64–111): urban navigation, commercial transactions, health clinics, personal character, narrative past tense, relative clauses, social invitations, reported speech, nomadic ger architecture, livestock taxonomy, dairy crafts, and countryside travel logistics.",
            "communicativeOutcome": "Demonstrate complete situational independence, unassisted reading, complex listening comprehension, and fluid interactive spoken production across all Waystage (A2) communicative domains.",
            "objectivesIntroduced": [],
            "objectivesPracticed": ["obj_a2_111_01_homestay_immersion_lexicon", "obj_a2_111_05_simulate_pastoral_encounter"],
            "objectivesReviewed": [
                "obj_a2_64_01_urban_districts_lexicon", "obj_a2_73_01_reflexive_possessive_suffix",
                "obj_a2_80_01_pharmacy_consultation_lexicon", "obj_a2_83_01_postposition_governance",
                "obj_a2_87_01_modal_bolno_permission", "obj_a2_94_01_narrative_past_v",
                "obj_a2_97_01_desiderative_maar", "obj_a2_98_01_purposive_converb_khaar",
                "obj_a2_99_01_reported_speech_gej", "obj_a2_100_01_resultative_past_zhee",
                "obj_a2_101_01_relative_clause_participles", "obj_a2_105_01_concessive_converb_vch",
                "obj_a2_107_01_terminative_converb_tal", "obj_a2_108_01_negative_indefinites",
                "obj_a2_110_01_deductive_future_kh_bolno"
            ],
            "grammarIntroduced": [],
            "grammarPracticed": [
                "gram_a2_possessive_reflexive_mor",
                "gram_a2_participle_relative_clause_past_san",
                "gram_a2_converb_concessive_vch_bolovch",
                "gram_a2_converb_terminative_tal",
                "gram_a2_verb_past_narrative_v",
                "gram_a2_reported_speech_gej_kheleh",
                "gram_a2_verb_past_resultative_zhee",
                "gram_a2_participle_desire_inclination_maar",
                "gram_a2_converb_purposive_khaar",
                "gram_a2_indefinite_pronouns_negation",
                "gram_a2_verb_future_deductive_kh_bolno"
            ],
            "grammarReviewed": ["gram_a2_participle_negative_aagui"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_intonation_polite"], "phonologyReviewed": ["phono_a1_vowel_length_distinction"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": [
                "comm_a2_01_asking_giving_street_directions", "comm_a2_03_describing_personality_character",
                "comm_a2_04_renting_apartment_housing", "comm_a2_07_childhood_hometown_memories",
                "comm_a2_08_vacation_travel_experiences", "comm_a2_09_making_accepting_invitations",
                "comm_a2_10_declining_invitations_excuses", "comm_a2_14_countryside_ger_visiting_etiquette",
                "comm_a2_15_nomadic_livestock_five_animals", "comm_a2_25_reporting_third_party_speech",
                "comm_a2_26_simple_recipe_cooking_steps", "comm_a2_27_expressing_future_intentions",
                "comm_a2_28_describing_lost_items", "comm_a2_29_phone_conversations_leaving_messages",
                "comm_a2_30_congratulations_milestones"
            ],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_countryside_nature", "lex_domain_culture_traditions", "lex_domain_social_interaction"],
            "previousVocabularyReused": ["шалгалт", "түвшин", "монгол хэл", "мэдлэг", "амжилт", "бүрэн"],
            "readingObjective": "Demonstrate unassisted reading comprehension of an authentic multi-paragraph Mongolian text incorporating relative clauses, concessives, and formal vocabulary.",
            "listeningObjective": "Demonstrate unassisted comprehension of authentic long-form conversational and broadcast audio clips with natural ambient noise.",
            "writingObjective": "Draft a coherent, multi-paragraph written essay synthesizing past narrative, future plans, and personal reflections with rich clause combining.",
            "spokenProductionObjective": "Sustain a dynamic, multi-turn spoken dialogue across varied unfamiliar situations demonstrating situational independence.",
            "registerTarget": "Comprehensive authoritative CEFR benchmark evaluation register",
            "pragmaticTarget": "Certifying complete learner readiness to transition from elementary language into independent B1 threshold proficiency.",
            "prerequisiteLessonIds": ["les_a2_111_05_full_pastoral_encounter_simulation"],
            "reviewsLessonIds": [
                "les_a2_72_05_full_urban_transit_journey_simulation", "les_a2_82_05_full_retail_service_encounter_simulation",
                "les_a2_90_04_full_clinical_encounter_simulation", "les_a2_101_06_personal_history_benchmark_checkpoint",
                "les_a2_110_05_phone_log_callback_memo_writing"
            ],
            "reviewsUnitIds": [
                "unit_a2_72_urban_transit_capstone_navigating_the", "unit_a2_82_retail_service_transaction_capstone",
                "unit_a2_90_medical_encounters_capstone_full_cl", "unit_a2_101_personal_history_capstone_autobiogr",
                "unit_a2_110_telephone_courtesy_leaving_messages"
            ],
            "reviewReason": "Ultimate authoritative milestone certifying complete learner graduation from CEFR A2 Waystage into B1 Threshold.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Deliver high-fidelity audio stimuli for formal A2 graduation benchmark examination items.",
            "successCriteria": [
                "Achieves passing score across all 4 skill modalities (Reading, Listening, Writing, Speaking)",
                "Demonstrates mastery of all 32 A2 grammar targets and core lexical inventories",
                "Navigates both metropolitan urban and nomadic pastoral domains with linguistic and cultural confidence"
            ],
            "masteryEvidence": "Successfully passes the comprehensive 4-modality A2 Waystage Exit Examination, certifying full progression to CEFR B1.",
            "recommendedExerciseModalities": ["reading_comprehension", "listening_comprehension", "role-play response", "short-answer writing"]
        }
    ])

    return lessons
