"""
Section 1 Generator (Units 64 - 72): 46 Lessons
Urban Transit, Wayfinding & Public Space Encounters
"""

import json
from typing import List, Dict, Any

def get_sec01_lessons() -> List[Dict[str, Any]]:
    with open("curriculum/blueprint/units/a2.json") as f:
        units = json.load(f)
    u_map = {u["sequencePosition"]: u for u in units}

    lessons: List[Dict[str, Any]] = []

    # =========================================================================
    # UNIT 64: Navigating Ulaanbaatar Bus Routes & Digital Smart Cards (pos 64)
    # 6 Lessons | Targets: ProdLem=21, RecLem=10, ProdExp=5, RecExp=3
    # Budget: (4,2,1,1), (6,3,1,1), (0,0,0,0), (5,3,1,0), (4,2,2,1), (2,0,0,0)
    # =========================================================================
    u = u_map[64]
    uid = u["unitId"]
    lessons.extend([
        {
            "lessonId": "les_a2_64_01_instrumental_transport_allomorphs",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 1,
            "title": "Taking the Bus: The Instrumental Suffix (-аар/-ээр/-оор/-өөр)",
            "lessonType": "grammar_introduction",
            "primaryPurpose": "Introduce the instrumental case suffix to express vehicles, transport modes, and physical instruments of transit.",
            "communicativeOutcome": "Explain which mode of transport you use to commute across the city (e.g. 'Би автобусаар явна', 'Би машинаар ирлээ').",
            "objectivesIntroduced": ["obj_a2_64_01_express_transport_instrumental"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_a1_38_01_habitual_routines"],
            "grammarIntroduced": ["gram_a2_case_instrumental_transport_language"],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_sov_word_order", "gram_a1_verb_tense_present_habitual_dag"],
            "phonologyIntroduced": ["phono_a2_instrumental_suffix_vowel_harmony"],
            "phonologyPracticed": ["phono_a1_long_vowels"], "phonologyReviewed": ["phono_a1_masculine_feminine_harmony"],
            "communicativeFunctionsIntroduced": ["comm_a2_18_buying_bus_train_tickets"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": ["comm_a1_17_describing_daily_routines"],
            "newProductiveLemmaTarget": 4, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_transportation_travel", "lex_domain_city_urban_life"],
            "previousVocabularyReused": ["автобус", "машин", "гэр", "сургууль", "ажил", "явах", "ирэх"],
            "readingObjective": "Read short commuters' forum sentences contrasting travel modes (bus vs walking vs car).",
            "listeningObjective": "Recognize the instrumental suffix when speakers state how they arrived at school or work.",
            "writingObjective": "Write 3 simple sentences declaring daily commute methods using instrumental case marking.",
            "spokenProductionObjective": "Answer prompts regarding how you travel to work or university using instrumental nouns.",
            "registerTarget": "Standard polite everyday transit register",
            "pragmaticTarget": "Stating transit choices plainly and neutrally without unnecessary hesitation.",
            "prerequisiteLessonIds": ["les_a1_63_06_elementary_stage_synthesis_capstone"],
            "reviewsLessonIds": ["les_a1_43_01_bus_routes_stops_intro"],
            "reviewsUnitIds": ["unit_a1_43_public_transit_commuting_bus_routes"],
            "reviewReason": "Builds directly upon A1 public transit vocabulary by introducing the formal instrumental case.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Model vowel harmony allomorphs of the instrumental case on stems ending in consonants and vowels.",
            "successCriteria": [
                "Selects correct instrumental allomorph (-аар, -ээр, -оор, -өөр) based on root vowel harmony",
                "Constructs well-formed SOV sentences specifying transit mode as instrumental adjunct"
            ],
            "masteryEvidence": "Produces 'Би өдөр бүр арван хоёр дугаар автобусаар явдаг' accurately matching vowel harmony.",
            "recommendedExerciseModalities": ["suffix_selection", "sentence_construction", "case_marking"]
        },
        {
            "lessonId": "les_a2_64_02_bus_routes_u_money_cards",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 2,
            "title": "Smart Card Tap & Bus Stops: U-Money in Practice",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Introduce practical vocabulary for digital transit smart cards (U-Money), balance checks, and boarding etiquette.",
            "communicativeOutcome": "Purchase, tap, and reload a municipal bus card, and ask where to check card balance.",
            "objectivesIntroduced": ["obj_a2_64_02_u_money_card_lexicon"],
            "objectivesPracticed": ["obj_a2_64_01_express_transport_instrumental"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_case_instrumental_transport_language"],
            "grammarReviewed": ["gram_a1_case_dative_locative_location", "gram_a1_existential_baina_baihgui"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_consonant_clusters"], "phonologyReviewed": ["phono_a1_vowel_reduction_non_initial"],
            "communicativeFunctionsIntroduced": ["comm_a2_18_buying_bus_train_tickets"],
            "communicativeFunctionsPracticed": ["comm_a1_22_making_purchases"], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_transportation_travel", "lex_domain_commerce_transactions"],
            "previousVocabularyReused": ["мөнгө", "карт", "хэд", "өгөх", "авах"],
            "readingObjective": "Read kiosk stickers instructing passengers where and how to reload U-Money cards.",
            "listeningObjective": "Understand convenience store cashier explaining minimum card reload amounts.",
            "writingObjective": "Note down card balance and bus line numbers in a pocket memo.",
            "spokenProductionObjective": "Ask a kiosk vendor to top up a transit card with a specified amount of tugriks.",
            "registerTarget": "Everyday transactional customer-to-vendor register",
            "pragmaticTarget": "Handing over card and cash with respectful two-handed or right-hand elbow support gesture.",
            "prerequisiteLessonIds": ["les_a2_64_01_instrumental_transport_allomorphs"],
            "reviewsLessonIds": ["les_a1_51_01_canteen_bill_settlement"],
            "reviewsUnitIds": ["unit_a1_51_settling_the_bill_canteen_transacti"],
            "reviewReason": "Connects money transactions from A1 canteen encounters to digital smart transit reloading.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Demonstrate authentic fast speech customer requests at small street convenience kiosks.",
            "successCriteria": [
                "Accurately names smart card components: цэнэглэх (top up), үлдэгдэл (balance), уншуулах (tap card)",
                "Conducts a smooth kiosk transaction requesting a 5,000 or 10,000 MNT card recharge"
            ],
            "masteryEvidence": "Requests 'U-Money карт таван мянган төгрөгөөр цэнэглэж өгөөч' fluently at a sales counter.",
            "recommendedExerciseModalities": ["contextual_cloze", "dialogue_completion", "categorization"]
        },
        {
            "lessonId": "les_a2_64_03_transit_announcements_decoding",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 3,
            "title": "Onboard Chimes & Next Stop PA Announcements",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop acoustic decoding skills for automated public bus announcements, next-stop chimes, and door warnings.",
            "communicativeOutcome": "Identify target stop names, upcoming transfer points, and door alerts from authentic bus audio.",
            "objectivesIntroduced": ["obj_a2_64_03_decode_automated_bus_announcements"],
            "objectivesPracticed": ["obj_a2_64_02_u_money_card_lexicon"], "objectivesReviewed": ["obj_a1_43_01_identify_bus_stops"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_dative_locative_location"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_diphthongs", "phono_a1_nasal_vowels"], "phonologyReviewed": ["phono_a1_vowel_length_distinction"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_18_buying_bus_train_tickets"],
            "communicativeFunctionsReviewed": ["comm_a1_19_inquiring_location"],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_transportation_travel"],
            "previousVocabularyReused": ["зогсоол", "дараагийн", "хаалга", "хаагдах", "буух", "суух"],
            "readingObjective": "",
            "listeningObjective": "Identify next stop name ('Дараагийн зогсоол...'), transfer alerts, and door closing warnings from onboard automated PA clips.",
            "writingObjective": "",
            "spokenProductionObjective": "Confirm with fellow passenger if the bus stops at your target destination.",
            "registerTarget": "Public automated civic announcement register",
            "pragmaticTarget": "Attuning ear to automated voice inflection and noisy bus engine acoustics.",
            "prerequisiteLessonIds": ["les_a2_64_02_bus_routes_u_money_cards"],
            "reviewsLessonIds": ["les_a1_43_03_bus_stop_listening"],
            "reviewsUnitIds": ["unit_a1_43_public_transit_commuting_bus_routes"],
            "reviewReason": "Progresses from simple A1 stop name recognition to parsing compound automated PA sentences.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Provide high-fidelity onboard recordings with authentic bus background ambient rumble and chime.",
            "successCriteria": [
                "Identifies stop name following 'Дараагийн зогсоол' under simulated cabin engine noise",
                "Extracts door safety warning 'Хаалга хаагдлаа, болгоомжтой байгаарай' without visual text"
            ],
            "masteryEvidence": "Correctly matches 4 recorded bus announcements to their corresponding route map stop sequences.",
            "recommendedExerciseModalities": ["listening_comprehension", "sequencing", "phonetic_discrimination"]
        },
        {
            "lessonId": "les_a2_64_04_route_maps_schedules_reading",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 4,
            "title": "Deciphering Bus Shelter Route Diagrams & Operating Hours",
            "lessonType": "reading_development",
            "primaryPurpose": "Build reading skills for authentic municipal bus stop route placards, direction arrows, and first/last bus schedules.",
            "communicativeOutcome": "Read a bus shelter schedule to determine operating hours, route paths, and whether a bus runs on weekends.",
            "objectivesIntroduced": ["obj_a2_64_04_read_bus_route_placards"],
            "objectivesPracticed": ["obj_a2_64_01_express_transport_instrumental"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_case_instrumental_transport_language"],
            "grammarReviewed": ["gram_a1_case_ablative_origin", "gram_a1_case_dative_locative_temporal"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_vowel_reduction_non_initial"], "phonologyReviewed": [],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_17_giving_multistep_directions"],
            "communicativeFunctionsReviewed": ["comm_a1_18_scheduling_appointments"],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_transportation_travel", "lex_domain_time_calendar"],
            "previousVocabularyReused": ["өглөө", "орой", "цаг", "эхлэх", "дуусах", "чиглэл"],
            "readingObjective": "Locate departure interval (зай/хүлээх хугацаа), terminal stop, and evening cutoff time on a bus route diagram.",
            "listeningObjective": "",
            "writingObjective": "Transcribe bus schedule operating window into a personal calendar entry.",
            "spokenProductionObjective": "Explain to a peer how often the bus runs and when the final bus departs.",
            "registerTarget": "Public administrative transit signage",
            "pragmaticTarget": "Extracting vital transit facts quickly from complex graphic layouts.",
            "prerequisiteLessonIds": ["les_a2_64_02_bus_routes_u_money_cards"],
            "reviewsLessonIds": ["les_a1_35_01_days_of_the_week_intro"],
            "reviewsUnitIds": ["unit_a1_35_days_of_the_week_weekly_calendars"],
            "reviewReason": "Integrates time/calendar terms from A1 with public transit schedule reading.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Provide spoken pronunciation of route numbers and schedule captions.",
            "successCriteria": [
                "Locates operating hours (e.g. 06:40 - 22:30) on a Cyrillic route graphic",
                "Determines whether bus route runs straight along Peace Avenue or turns north towards Sansar"
            ],
            "masteryEvidence": "Identifies departure frequency and final evening run from an authentic Ulaanbaatar route diagram.",
            "recommendedExerciseModalities": ["reading_comprehension", "contextual_cloze", "categorization"]
        },
        {
            "lessonId": "les_a2_64_05_bus_stop_inquiries_dialogue",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 5,
            "title": "Which Bus Goes to the Central Post Office? Stop Inquiries",
            "lessonType": "dialogue_work",
            "primaryPurpose": "Develop interactive spoken ability to ask bystanders at a crowded stop which bus reaches a specific destination.",
            "communicativeOutcome": "Ask pedestrians for bus route advice, confirm if a bus goes through Sukhbaatar Square, and signal intent to alight.",
            "objectivesIntroduced": ["obj_a2_64_05_inquire_bus_destinations"],
            "objectivesPracticed": ["obj_a2_64_01_express_transport_instrumental", "obj_a2_64_03_decode_automated_bus_announcements"],
            "objectivesReviewed": ["obj_a1_16_01_greet_time_of_day"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_case_instrumental_transport_language"],
            "grammarReviewed": ["gram_a1_polar_questions_uu_uu", "gram_a1_case_dative_locative_location"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_intonation_questions"], "phonologyReviewed": ["phono_a1_polite_phrasing"],
            "communicativeFunctionsIntroduced": ["comm_a2_17_giving_multistep_directions"],
            "communicativeFunctionsPracticed": ["comm_a2_18_buying_bus_train_tickets"],
            "communicativeFunctionsReviewed": ["comm_a1_19_inquiring_location"],
            "newProductiveLemmaTarget": 4, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_transportation_travel", "lex_domain_city_urban_life"],
            "previousVocabularyReused": ["уучлаарай", "энэ", "тийшээ", "хүрэх", "зогсох", "буух"],
            "readingObjective": "",
            "listeningObjective": "Follow a fellow passenger's spoken reply explaining which bus number to take and where to transfer.",
            "writingObjective": "",
            "spokenProductionObjective": "Ask a fellow commuter: 'Уучлаарай, энэ автобус Төв шуудангаар дайрах уу?' and respond appropriately.",
            "registerTarget": "Spontaneous polite public bystander register",
            "pragmaticTarget": "Using polite attention getters ('Уучлаарай, танаас нэг зүйл асууж болох уу?') without being intrusive.",
            "prerequisiteLessonIds": ["les_a2_64_03_transit_announcements_decoding", "les_a2_64_04_route_maps_schedules_reading"],
            "reviewsLessonIds": ["les_a1_19_01_polar_questions_intro"],
            "reviewsUnitIds": ["unit_a1_19_polar_inquiries_polar_question_part"],
            "reviewReason": "Spirals polar question syntax (уу/үү) into real-time transit route inquiries.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Simulate natural conversational pace between two commuters at an outdoor winter bus stop.",
            "successCriteria": [
                "Asks whether a specific bus line passes a landmark using polite particle and instrumental case",
                "Understands bystander's recommendation to wait for another line or transfer at the next stop"
            ],
            "masteryEvidence": "Participates in an unscripted roleplay asking how to reach the Central Post Office from 120 Myangat.",
            "recommendedExerciseModalities": ["dialogue_completion", "role-play response", "listening_comprehension"]
        },
        {
            "lessonId": "les_a2_64_06_transit_card_sms_writing",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 6,
            "title": "Transit SMS: Coordinating Bus Commute Times with a Friend",
            "lessonType": "grammar_guided_practice",
            "primaryPurpose": "Synthesize instrumental case, bus route numbers, and arrival predictions in short personal messaging.",
            "communicativeOutcome": "Compose a brief message informing a friend which bus you boarded and at which stop to meet.",
            "objectivesIntroduced": ["obj_a2_64_06_draft_transit_sms"],
            "objectivesPracticed": ["obj_a2_64_01_express_transport_instrumental", "obj_a2_64_05_inquire_bus_destinations"],
            "objectivesReviewed": ["obj_a1_34_01_tell_clock_time"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_case_instrumental_transport_language"],
            "grammarReviewed": ["gram_a1_case_dative_locative_temporal", "gram_a1_verb_aspect_progressive_j_baina"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_18_buying_bus_train_tickets", "comm_a1_18_scheduling_appointments"],
            "communicativeFunctionsReviewed": ["comm_a1_17_describing_daily_routines"],
            "newProductiveLemmaTarget": 2, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_transportation_travel", "lex_domain_communication_media"],
            "previousVocabularyReused": ["найз", "уулзах", "зогсоол", "хүлээх", "ирж байна", "минут"],
            "readingObjective": "Read a friend's incoming SMS inquiring about your current bus stop location.",
            "listeningObjective": "",
            "writingObjective": "Write a 3-sentence SMS stating which bus you are on, your current stop, and estimated arrival.",
            "spokenProductionObjective": "",
            "registerTarget": "Casual digital peer messaging",
            "pragmaticTarget": "Using concise digital text conventions while maintaining accurate grammatical case endings.",
            "prerequisiteLessonIds": ["les_a2_64_05_bus_stop_inquiries_dialogue"],
            "reviewsLessonIds": ["les_a1_57_01_progressive_aspect_intro"],
            "reviewsUnitIds": ["unit_a1_57_ongoing_progressive_aspect_verbal_s"],
            "reviewReason": "Combines ongoing progressive aspect (-ж байна) with instrumental transit markings.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Read back written messages for ear training.",
            "successCriteria": [
                "Drafts a coherent text message indicating bus number in instrumental case",
                "Coordinates arrival time with meeting place using locative case correctly"
            ],
            "masteryEvidence": "Writes 'Би 2-р автобусаар явж байна. Их дэлгүүрийн зогсоол дээр 10 минутын дараа уулзъя' without grammatical error.",
            "recommendedExerciseModalities": ["short-answer writing", "sentence construction", "error correction"]
        }
    ])

    # =========================================================================
    # UNIT 65: Hailing Street Taxis & Giving Micro-Directions (pos 65)
    # 5 Lessons | Targets: ProdLem=21, RecLem=10, ProdExp=5, RecExp=3
    # Budget: (5,2,1,1), (6,3,1,1), (5,3,2,1), (0,0,0,0), (5,2,1,0) = (21, 10, 5, 3)
    # =========================================================================
    u = u_map[65]
    uid = u["unitId"]
    lessons.extend([
        {
            "lessonId": "les_a2_65_01_directional_case_micro_turns",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 1,
            "title": "Directing the Driver: The Directional Suffix (-руу/-рүү)",
            "lessonType": "grammar_introduction",
            "primaryPurpose": "Introduce the directional case suffix (-руу/-рүү) after consonants and vowels to indicate orientation and movement towards landmarks.",
            "communicativeOutcome": "Instruct a taxi driver to turn or head towards specific landmarks (e.g. 'Баруун гар тийшээ, их дэлгүүр лүү эргээрэй').",
            "objectivesIntroduced": ["obj_a2_65_01_directional_suffix_marking"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_a2_64_01_express_transport_instrumental"],
            "grammarIntroduced": ["gram_a2_case_directional_towards"],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_dative_locative_location", "gram_a2_case_instrumental_transport_language"],
            "phonologyIntroduced": ["phono_a2_directional_suffix_vowel_harmony"],
            "phonologyPracticed": ["phono_a1_masculine_feminine_harmony"], "phonologyReviewed": ["phono_a1_vowel_length_distinction"],
            "communicativeFunctionsIntroduced": ["comm_a2_19_taxi_hailing_fare_negotiation"],
            "communicativeFunctionsPracticed": ["comm_a2_17_giving_multistep_directions"], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_transportation_travel", "lex_domain_spatial_relations"],
            "previousVocabularyReused": ["баруун", "зүүн", "урагшаа", "хойшоо", "эргэх", "явах"],
            "readingObjective": "Read navigation app prompts specifying turns toward key monuments and thoroughfares.",
            "listeningObjective": "Distinguish between directional (-руу) and locative (-д) markers in taxi dispatch instructions.",
            "writingObjective": "Write 3 directional commands directing a driver toward a specific street or landmark.",
            "spokenProductionObjective": "Direct a driver in real time: 'Гэрлэн дохиогоор зүүн тийш, эмнэлэг рүү эргээрэй'.",
            "registerTarget": "Everyday spoken directive register with polite imperatives",
            "pragmaticTarget": "Giving clear, calm spatial instructions to drivers without abrupt hesitation.",
            "prerequisiteLessonIds": ["les_a2_64_01_instrumental_transport_allomorphs"],
            "reviewsLessonIds": ["les_a1_61_01_spatial_postpositions_intro"],
            "reviewsUnitIds": ["unit_a1_61_spatial_postpositions_"],
            "reviewReason": "Builds on spatial postpositions by introducing synthetic directional case morphology.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Model vowel harmony choices (-руу vs -рүү) after various noun codas.",
            "successCriteria": [
                "Correctly selects -руу or -рүү depending on back/front vocalic harmony of noun root",
                "Accurately guides vehicle movement toward landmarks using directional case"
            ],
            "masteryEvidence": "Produces 'Төв талбай руу чигээрээ яваад, баруун тийшээ эргээрэй' with flawless case marking.",
            "recommendedExerciseModalities": ["suffix_selection", "sentence_construction", "case_marking"]
        },
        {
            "lessonId": "les_a2_65_02_hailing_taxis_landmark_navigation",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 2,
            "title": "Hailing Street Cabs: Raising Hands & Landmark Waypoints",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Introduce essential colloquial vocabulary for hailing informal street cabs, negotiating drop-off points, and using landmarks.",
            "communicativeOutcome": "Hail an informal street taxi, state destination by prominent landmark, and negotiate a per-kilometer fare.",
            "objectivesIntroduced": ["obj_a2_65_02_street_taxi_lexicon"],
            "objectivesPracticed": ["obj_a2_65_01_directional_suffix_marking"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_case_directional_towards"],
            "grammarReviewed": ["gram_a1_converb_coordinating_j_ch"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_consonant_clusters"], "phonologyReviewed": ["phono_a1_vowel_reduction_non_initial"],
            "communicativeFunctionsIntroduced": ["comm_a2_19_taxi_hailing_fare_negotiation"],
            "communicativeFunctionsPracticed": ["comm_a1_23_bargaining_clarifying_price"], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_transportation_travel", "lex_domain_city_urban_life"],
            "previousVocabularyReused": ["хэд", "төгрөг", "километр", "зогсох", "буух", "мөнгө"],
            "readingObjective": "Read taxi app rate cards detailing base fare and nighttime surcharges.",
            "listeningObjective": "Comprehend taxi driver asking 'Хаашаа явах вэ? Хэдэн төгрөгөөр явах юм?' through car window.",
            "writingObjective": "Note down street intersections and agreed taxi fares.",
            "spokenProductionObjective": "Hail a car and state: 'Багшийн дээд орно, хоёр мянгаар явах уу?' clearly.",
            "registerTarget": "Everyday informal street transaction register",
            "pragmaticTarget": "Quick roadside verbal negotiation with driver with window rolled down.",
            "prerequisiteLessonIds": ["les_a2_65_01_directional_case_micro_turns"],
            "reviewsLessonIds": ["les_a1_52_01_open_market_grocery_shopping"],
            "reviewsUnitIds": ["unit_a1_52_open_market_grocery_shopping_bulk_q"],
            "reviewReason": "Applies transactional negotiation techniques to urban transport services.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Simulate authentic street side roadside noise and driver banter.",
            "successCriteria": [
                "Correctly names common urban waypoints: уулзвар (intersection), гүүр (bridge), гэрлэн дохио (traffic light)",
                "Negotiates ride terms within 10 seconds of car stopping"
            ],
            "masteryEvidence": "Successfully negotiates destination and fare with simulated street cab driver.",
            "recommendedExerciseModalities": ["dialogue_completion", "contextual_cloze", "role-play response"]
        },
        {
            "lessonId": "les_a2_65_03_in_cab_navigation_dialogue",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 3,
            "title": "Inside the Cab: Giving Turn-by-Turn Drop-Off Instructions",
            "lessonType": "dialogue_work",
            "primaryPurpose": "Develop interactive fluency for guiding the driver in real time, navigating side streets, and requesting drop-off.",
            "communicativeOutcome": "Guide driver through side streets, ask to pull over right after an intersection, and request change.",
            "objectivesIntroduced": ["obj_a2_65_03_in_cab_turn_guidance"],
            "objectivesPracticed": ["obj_a2_65_01_directional_suffix_marking", "obj_a2_65_02_street_taxi_lexicon"],
            "objectivesReviewed": ["obj_a1_49_01_polite_imperative"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_case_directional_towards"],
            "grammarReviewed": ["gram_a1_verb_imperative_polite_aarai", "gram_a1_converb_coordinating_j_ch"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_intonation_polite"], "phonologyReviewed": ["phono_a1_diphthongs"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_19_taxi_hailing_fare_negotiation", "comm_a2_17_giving_multistep_directions"],
            "communicativeFunctionsReviewed": ["comm_a1_22_making_purchases"],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_transportation_travel", "lex_domain_spatial_relations"],
            "previousVocabularyReused": ["энд", "тэнд", "зогсох", "барих", "эргэх", "орц"],
            "readingObjective": "",
            "listeningObjective": "Follow driver's clarifying questions: 'Хоёрдугаар орцны өмнө зогсох уу, хашааны гадаа юу?'.",
            "writingObjective": "",
            "spokenProductionObjective": "Instruct driver: 'Энэ булангаар баруун тийшээ эргээд, эмийн сангийн хажууд буулгачих'.",
            "registerTarget": "Polite conversational driver-passenger exchange",
            "pragmaticTarget": "Using softening converbs (-чих) and polite imperatives (-аарай) to ensure pleasant cooperation.",
            "prerequisiteLessonIds": ["les_a2_65_02_hailing_taxis_landmark_navigation"],
            "reviewsLessonIds": ["les_a1_49_01_polite_imperative_aarai"],
            "reviewsUnitIds": ["unit_a1_49_polite_request_imperative_suffixes_"],
            "reviewReason": "Combines polite imperative suffixation (-аарай) with rapid navigational directives.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Deliver realistic passenger-driver dialogue with typical turns of speech and hesitation.",
            "successCriteria": [
                "Directs driver through 2 consecutive turns without pauses causing missed turns",
                "Politely asks driver to stop near a specific building entrance"
            ],
            "masteryEvidence": "Guides cab to drop-off point and completes payment exchange without English intervention.",
            "recommendedExerciseModalities": ["role-play response", "dialogue_completion", "listening_comprehension"]
        },
        {
            "lessonId": "les_a2_65_04_taxi_radio_fare_listening",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 4,
            "title": "Acoustic Lab: Radio Dispatch Audio & Fare Calculations",
            "lessonType": "listening_development",
            "primaryPurpose": "Sharpen listening comprehension of authentic taxi radio chatter, automated dispatch updates, and fare calculation disputes.",
            "communicativeOutcome": "Extract pickup address, destination landmark, and calculated fare from authentic taxi dispatch communications.",
            "objectivesIntroduced": ["obj_a2_65_04_decode_taxi_dispatch_audio"],
            "objectivesPracticed": ["obj_a2_65_02_street_taxi_lexicon"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_numerals_cardinal_counting"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_vowel_reduction_non_initial"], "phonologyReviewed": ["phono_a1_nasal_vowels"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_19_taxi_hailing_fare_negotiation"],
            "communicativeFunctionsReviewed": ["comm_a1_23_bargaining_clarifying_price"],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_transportation_travel"],
            "previousVocabularyReused": ["хаяг", "байр", "дуудах", "тооцоо", "мөнгө"],
            "readingObjective": "",
            "listeningObjective": "Extract pickup address, kilometer meter reading, and total fare from taxi dispatch radio audio.",
            "writingObjective": "",
            "spokenProductionObjective": "Summarize the overheard taxi dispute to a partner in 2 Mongolian sentences.",
            "registerTarget": "Rapid dispatcher-to-fleet radio communication register",
            "pragmaticTarget": "Extracting key spatial and numeric information despite low-bandwidth audio distortion.",
            "prerequisiteLessonIds": ["les_a2_65_02_hailing_taxis_landmark_navigation"],
            "reviewsLessonIds": ["les_a1_27_01_counting_tens_hundreds"],
            "reviewsUnitIds": ["unit_a1_27_cardinal_numbers_counting_up_to_one"],
            "reviewReason": "Reinforces rapid mental decoding of multi-digit currency numbers from A1.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Acoustic dispatch audio with radio squelch, background traffic horns, and rapid Mongolian numbers.",
            "successCriteria": [
                "Accurately extracts building number, street landmark, and price from dispatch audio clips",
                "Determines whether driver accepts or rejects passenger pickup request"
            ],
            "masteryEvidence": "Logs 3 distinct radio dispatch tasks with 100% correct landmark and fare transcription.",
            "recommendedExerciseModalities": ["listening_comprehension", "dictation", "categorization"]
        },
        {
            "lessonId": "les_a2_65_05_micro_directions_written_pin",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 5,
            "title": "Written Micro-Directions: Dropping a Text Pin for Ride Pickup",
            "lessonType": "grammar_guided_practice",
            "primaryPurpose": "Synthesize directional case (-руу/-рүү), spatial adverbs, and landmark descriptions in written ride-hailing notes.",
            "communicativeOutcome": "Write clear pickup instructions in a ride app chat explaining exactly where you are waiting.",
            "objectivesIntroduced": ["obj_a2_65_05_write_pickup_instructions"],
            "objectivesPracticed": ["obj_a2_65_01_directional_suffix_marking", "obj_a2_65_02_street_taxi_lexicon"],
            "objectivesReviewed": ["obj_a1_61_01_spatial_postpositions_intro"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_case_directional_towards"],
            "grammarReviewed": ["gram_a1_spatial_postpositions_deeree_door", "gram_a1_case_dative_locative_location"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_17_giving_multistep_directions", "comm_a2_19_taxi_hailing_fare_negotiation"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_transportation_travel", "lex_domain_spatial_relations"],
            "previousVocabularyReused": ["үүд", "өмнө", "хажууд", "хүлээх", "байр", "машин"],
            "readingObjective": "Read driver's written text query: 'Та байрны аль талд нь зогсож байна вэ?'.",
            "listeningObjective": "",
            "writingObjective": "Compose concise written instructions detailing your precise curb location, clothing, and surrounding signs.",
            "spokenProductionObjective": "",
            "registerTarget": "Direct and polite digital written chat",
            "pragmaticTarget": "Providing unambiguous location cues in minimum words to prevent driver circling.",
            "prerequisiteLessonIds": ["les_a2_65_03_in_cab_navigation_dialogue", "les_a2_65_04_taxi_radio_fare_listening"],
            "reviewsLessonIds": ["les_a1_61_03_reading_spatial_signs"],
            "reviewsUnitIds": ["unit_a1_61_spatial_postpositions_"],
            "reviewReason": "Applies postpositional spatial phrases (өмнө, хажууд, хойно) to real-time written driver communication.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Audio playback of user drafted pickup messages.",
            "successCriteria": [
                "Writes a 2-3 sentence location note containing directional suffix and spatial postposition",
                "Accurately guides vehicle toward building entrance without ambiguity"
            ],
            "masteryEvidence": "Drafts 'Би төв хаалганы баруун талд, кофе шопын үүдэнд хар куртиктэй зогсож байна' correctly.",
            "recommendedExerciseModalities": ["short-answer writing", "sentence construction", "error correction"]
        }
    ])

    # =========================================================================
    # UNIT 66: Intercity Bus & Passenger Train Travel (pos 66)
    # 6 Lessons | Targets: ProdLem=21, RecLem=10, ProdExp=5, RecExp=3
    # Budget: (4,2,1,1), (6,3,1,1), (0,0,0,0), (5,3,1,0), (4,2,2,1), (2,0,0,0) = (21, 10, 5, 3)
    # =========================================================================
    u = u_map[66]
    uid = u["unitId"]
    lessons.extend([
        {
            "lessonId": "les_a2_66_01_instrumental_means_transit_goals",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 1,
            "title": "By Train, By Bus, By Card: Instrumental Case of Means (-аар4)",
            "lessonType": "grammar_introduction",
            "primaryPurpose": "Introduce the instrumental case suffix (-аар / -ээр / -оор / -өөр) for expressing means of transit, tools, and methods of payment in intercity travel.",
            "communicativeOutcome": "Specify transit vehicles and transaction methods across provinces (e.g. 'Бид Дархан руу хурдан галт тэргээр явна', 'Би тасалбарын үнийг картаар төлнө').",
            "objectivesIntroduced": ["obj_a2_66_01_instrumental_means_marking"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_a2_65_01_directional_suffix_marking"],
            "grammarIntroduced": ["gram_a2_case_instrumental_means"],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_instrumental_transport_language", "gram_a2_case_directional_towards"],
            "phonologyIntroduced": ["phono_a2_instrumental_means_harmony"],
            "phonologyPracticed": ["phono_a1_masculine_feminine_harmony"], "phonologyReviewed": ["phono_a1_long_vowels"],
            "communicativeFunctionsIntroduced": ["comm_a2_18_buying_bus_train_tickets"],
            "communicativeFunctionsPracticed": ["comm_a1_20_expressing_intentions"], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 4, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_transportation_travel", "lex_domain_actions_movement"],
            "previousVocabularyReused": ["явах", "ирэх", "уулзах", "үзэх", "хот", "хөдөө"],
            "readingObjective": "Read passenger statement bubbles explaining reasons and transit methods for boarding intercity transport.",
            "listeningObjective": "Identify vehicle noun and instrumental suffix in passengers' recorded travel methods.",
            "writingObjective": "Formulate 3 sentences combining destination in directional case and transit vehicle in instrumental case.",
            "spokenProductionObjective": "Explain to a ticket agent how and by what vehicle you wish to travel to Darkhan or Erdenet.",
            "registerTarget": "Standard transactional traveler register",
            "pragmaticTarget": "Specifying transit modes and payment methods concisely during ticket purchasing.",
            "prerequisiteLessonIds": ["les_a2_65_01_directional_case_micro_turns"],
            "reviewsLessonIds": ["les_a1_39_01_instrumental_case_intro"],
            "reviewsUnitIds": ["unit_a1_39_instrumental_case_transport_instru"],
            "reviewReason": "Expands instrumental case from basic transport nouns to broader means, methods, and transaction modes.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Model quadruple vowel harmony of the instrumental suffix (-аар, -ээр, -оор, -өөр).",
            "successCriteria": [
                "Applies correct allomorph of -аар4 according to root stem harmony",
                "Expresses valid instrument or transit means modifying movement verb"
            ],
            "masteryEvidence": "Produces 'Бид Дархан руу хурдан галт тэргээр явахаар шийдсэн' accurately.",
            "recommendedExerciseModalities": ["suffix_selection", "sentence_construction", "matching"]
        },
        {
            "lessonId": "les_a2_66_02_intercity_terminals_rail_vocabulary",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 2,
            "title": "Dragon Terminal & Railway Station: Intercity Travel Hubs",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Introduce core vocabulary for regional transport hubs, rail berths, sleeper compartments, and long-distance buses.",
            "communicativeOutcome": "Distinguish between train carriage types, understand baggage weight allowances, and navigate bus platforms.",
            "objectivesIntroduced": ["obj_a2_66_02_intercity_terminal_lexicon"],
            "objectivesPracticed": ["obj_a2_66_01_purposive_converb_expression"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_converb_purposive_khaar"],
            "grammarReviewed": ["gram_a1_case_genitive_possession", "gram_a1_noun_plural_markers"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_consonant_clusters"], "phonologyReviewed": ["phono_a1_diphthongs"],
            "communicativeFunctionsIntroduced": ["comm_a2_18_buying_bus_train_tickets"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_transportation_travel", "lex_domain_geography_places"],
            "previousVocabularyReused": ["галт тэрэг", "буудал", "суудал", "тасалбар", "тээш", "үнэ"],
            "readingObjective": "Read terminal floor directories locating ticket windows, waiting halls, and luggage storage.",
            "listeningObjective": "Understand baggage clerk stating overweight luggage fees per kilogram.",
            "writingObjective": "List essential long-distance travel items and luggage labels in Cyrillic.",
            "spokenProductionObjective": "Inquire about sleeper berth options (купе vs плацкарт) at the station inquiry window.",
            "registerTarget": "Public service counter register",
            "pragmaticTarget": "Clear articulation in noisy transport terminal halls.",
            "prerequisiteLessonIds": ["les_a2_66_01_instrumental_means_transit_goals"],
            "reviewsLessonIds": ["les_a1_43_02_bus_terminal_schedule_reading"],
            "reviewsUnitIds": ["unit_a1_43_public_transit_commuting_bus_routes"],
            "reviewReason": "Expands city transit vocabulary to provincial long-distance transit.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Acoustic modeling of terminal announcements and ticketing clerk voice.",
            "successCriteria": [
                "Identifies key carriage categories: купе (soft sleeper), плацкарт (hard sleeper), нийтийн (general)",
                "Distinguishes Dragon terminal intercity coach gates from railway platforms"
            ],
            "masteryEvidence": "Correctly names and classifies 8 intercity travel items and locations.",
            "recommendedExerciseModalities": ["categorization", "contextual_cloze", "dialogue_completion"]
        },
        {
            "lessonId": "les_a2_66_03_station_pa_announcement_listening",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 3,
            "title": "Platform Audio Lab: Departure Calls & Track Announcements",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop acoustic comprehension of reverberant public railway station and long-distance bus terminal announcements.",
            "communicativeOutcome": "Extract train/bus route numbers, track numbers, departure delays, and boarding calls from live public address audio.",
            "objectivesIntroduced": ["obj_a2_66_03_decode_platform_announcements"],
            "objectivesPracticed": ["obj_a2_66_02_intercity_terminal_lexicon"], "objectivesReviewed": ["obj_a1_34_01_tell_clock_time"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_telling_time_clock_calendar"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_vowel_reduction_non_initial"], "phonologyReviewed": ["phono_a1_nasal_vowels"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_18_buying_bus_train_tickets"],
            "communicativeFunctionsReviewed": ["comm_a1_18_scheduling_appointments"],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_transportation_travel", "lex_domain_time_calendar"],
            "previousVocabularyReused": ["зам", "хөдлөх", "хоцрох", "цаг", "минут", "зорчигч"],
            "readingObjective": "",
            "listeningObjective": "Extract train number, track/platform number, departure time, and delay duration from platform PA recordings.",
            "writingObjective": "",
            "spokenProductionObjective": "Inform traveling companion of platform assignment and departure time change.",
            "registerTarget": "Public automated civic transit announcement",
            "pragmaticTarget": "Parsing high-reverberation station audio with echo and acoustic distortion.",
            "prerequisiteLessonIds": ["les_a2_66_02_intercity_terminals_rail_vocabulary"],
            "reviewsLessonIds": ["les_a1_34_03_time_listening_comprehension"],
            "reviewsUnitIds": ["unit_a1_34_telling_clock_time_"],
            "reviewReason": "Applies clock time listening comprehension to high-stakes transit schedule announcements.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Provide reverberant station audio with realistic echo, platform bells, and diesel train engine sounds.",
            "successCriteria": [
                "Identifies train number and departure track from simulated station broadcast",
                "Catches 15-minute delay notice without repeating the audio clip more than twice"
            ],
            "masteryEvidence": "Fills in complete boarding table (train #, track, departure, destination) from 3 audio clips.",
            "recommendedExerciseModalities": ["listening_comprehension", "dictation", "sequencing"]
        },
        {
            "lessonId": "les_a2_66_04_train_bus_timetables_reading",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 4,
            "title": "Deciphering Mongolian Railway Tickets & Departure Boards",
            "lessonType": "reading_development",
            "primaryPurpose": "Develop targeted reading skills for official Mongolian railway e-tickets, carriage numbers, berth codes, and baggage vouchers.",
            "communicativeOutcome": "Inspect a printed railway ticket or digital PDF voucher to find carriage number, berth, passenger name, and departure date.",
            "objectivesIntroduced": ["obj_a2_66_04_read_railway_tickets"],
            "objectivesPracticed": ["obj_a2_66_02_intercity_terminal_lexicon"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_converb_purposive_khaar"],
            "grammarReviewed": ["gram_a1_case_ablative_origin", "gram_a1_case_dative_locative_location"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_18_buying_bus_train_tickets"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_transportation_travel", "lex_domain_commerce_transactions"],
            "previousVocabularyReused": ["огноо", "вагон", "суудал", "овог", "нэр", "үнэ"],
            "readingObjective": "Locate departure date, train number, carriage (вагон), upper/lower berth (дээд/доод ор), and passport details on ticket PDF.",
            "listeningObjective": "",
            "writingObjective": "Transcribe critical ticket numbers into personal travel log.",
            "spokenProductionObjective": "Explain ticket seat allocation to a fellow traveler in Mongolian.",
            "registerTarget": "Official state transportation documentation",
            "pragmaticTarget": "Verifying ticket authenticity and ensuring passport name matches ticket Cyrillic spelling.",
            "prerequisiteLessonIds": ["les_a2_66_02_intercity_terminals_rail_vocabulary"],
            "reviewsLessonIds": ["les_a1_36_02_reading_calendar_dates"],
            "reviewsUnitIds": ["unit_a1_36_calendar_dates_months_seasons"],
            "reviewReason": "Recycles date and month reading skills on authentic government ticket vouchers.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Pronounce formal administrative ticket labels.",
            "successCriteria": [
                "Locates carriage and seat number on an authentic Mongolian Railway (УБТЗ) ticket",
                "Distinguishes upper berth (дээд ор) from lower berth (доод ор)"
            ],
            "masteryEvidence": "Answers 5 comprehension questions based on a sample Ulaanbaatar-Sainshand e-ticket.",
            "recommendedExerciseModalities": ["reading_comprehension", "contextual_cloze", "categorization"]
        },
        {
            "lessonId": "les_a2_66_05_ticket_counter_booking_dialogue",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 5,
            "title": "At the Ticket Window: Booking Sleeper Berths & Round-Trips",
            "lessonType": "dialogue_work",
            "primaryPurpose": "Simulate spoken interaction at an intercity bus or train ticket window, negotiating departure times and berth positions.",
            "communicativeOutcome": "Purchase round-trip tickets to an aimag center, specify lower berth preference, and ask about cancellation policies.",
            "objectivesIntroduced": ["obj_a2_66_05_book_intercity_tickets"],
            "objectivesPracticed": ["obj_a2_66_01_purposive_converb_expression", "obj_a2_66_02_intercity_terminal_lexicon"],
            "objectivesReviewed": ["obj_a1_51_01_canteen_bill_settlement"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_converb_purposive_khaar"],
            "grammarReviewed": ["gram_a1_verb_volitional_intention_ya", "gram_a1_polar_questions_uu_uu"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_intonation_polite"], "phonologyReviewed": ["phono_a1_vowel_length_distinction"],
            "communicativeFunctionsIntroduced": ["comm_a2_18_buying_bus_train_tickets"],
            "communicativeFunctionsPracticed": ["comm_a1_22_making_purchases"],
            "communicativeFunctionsReviewed": ["comm_a1_16_greetings_time_of_day"],
            "newProductiveLemmaTarget": 4, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_transportation_travel", "lex_domain_commerce_transactions"],
            "previousVocabularyReused": ["тасалбар", "өгөх", "авах", "хэд", "буцах", "нэг талдаа"],
            "readingObjective": "",
            "listeningObjective": "Understand ticketing agent presenting remaining seat choices and departure times.",
            "writingObjective": "",
            "spokenProductionObjective": "Request round-trip tickets: 'Эрдэнэт рүү хоёр талын купе тасалбар хоёрыг авъя. Доод ор байна уу?'.",
            "registerTarget": "Courteous transactional customer-agent register",
            "pragmaticTarget": "Checking ticket details before stepping away from the glass partition counter.",
            "prerequisiteLessonIds": ["les_a2_66_03_station_pa_announcement_listening", "les_a2_66_04_train_bus_timetables_reading"],
            "reviewsLessonIds": ["les_a1_48_01_volitional_ya_intro"],
            "reviewsUnitIds": ["unit_a1_48_volitional_intention_suffixes_"],
            "reviewReason": "Uses volitional verb forms (-я/-е) for transactional requests at ticket counters.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Model fast, professional cashier responses through ticket glass microphone.",
            "successCriteria": [
                "Negotiates ticket purchase including date, destination, class, and seat position",
                "Confirms return travel date using calendar vocabulary and volitional forms"
            ],
            "masteryEvidence": "Completes full simulated ticket booking dialogue including ID check and payment.",
            "recommendedExerciseModalities": ["role-play response", "dialogue_completion", "listening_comprehension"]
        },
        {
            "lessonId": "les_a2_66_06_travel_itinerary_drafting",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 6,
            "title": "Intercity Travel Plan: Writing Itinerary & Packing Essentials",
            "lessonType": "grammar_guided_practice",
            "primaryPurpose": "Consolidate purposive converb, transportation nouns, and schedule timings in a comprehensive written travel plan.",
            "communicativeOutcome": "Write a 5-6 sentence travel itinerary detailing departure station, transit purpose, stops, and arrival checklist.",
            "objectivesIntroduced": ["obj_a2_66_06_write_travel_itinerary"],
            "objectivesPracticed": ["obj_a2_66_01_purposive_converb_expression", "obj_a2_66_05_book_intercity_tickets"],
            "objectivesReviewed": ["obj_a1_44_01_workday_schedule_synthesis"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_converb_purposive_khaar"],
            "grammarReviewed": ["gram_a1_converb_sequential_aad", "gram_a1_case_dative_locative_temporal"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_18_buying_bus_train_tickets", "comm_a1_17_describing_daily_routines"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 2, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_transportation_travel", "lex_domain_time_calendar"],
            "previousVocabularyReused": ["өглөө", "хөдлөх", "хүрэх", "аялал", "төлөвлөгөө", "чемодан"],
            "readingObjective": "Read a sample rural expedition schedule to emulate chronological layout.",
            "listeningObjective": "",
            "writingObjective": "Draft a complete personal itinerary using purposive converbs (-хаар) and sequential converbs (-аад).",
            "spokenProductionObjective": "",
            "registerTarget": "Organized personal narrative/log register",
            "pragmaticTarget": "Clear chronological structuring of travel events and packing requirements.",
            "prerequisiteLessonIds": ["les_a2_66_05_ticket_counter_booking_dialogue"],
            "reviewsLessonIds": ["les_a1_50_01_sequential_converb_aad"],
            "reviewsUnitIds": ["unit_a1_50_sequential_converb_clause_connector"],
            "reviewReason": "Links sequential converb (-аад) from A1 with A2 purposive converb (-хаар) in written prose.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Read back generated travel plan for self-correction.",
            "successCriteria": [
                "Produces written itinerary with correct time stamps, departure locations, and purposive verbs",
                "Integrates at least one sequential converb and one purposive converb"
            ],
            "masteryEvidence": "Writes: 'Бид маргааш өглөө 8 цагт галт тэргээр Дархан руу найзтайгаа уулзахаар явна' and subsequent steps correctly.",
            "recommendedExerciseModalities": ["short-answer writing", "clause_combination", "sentence_construction"]
        }
    ])

    from scripts.framework_builder.gen_sec01_part2 import get_sec01_part2_lessons
    from scripts.framework_builder.gen_sec01_part3 import get_sec01_part3_lessons

    lessons.extend(get_sec01_part2_lessons(u_map))
    lessons.extend(get_sec01_part3_lessons(u_map))

    return lessons

if __name__ == "__main__":
    sec01 = get_sec01_lessons()
    print(f"Total Section 1 lessons: {len(sec01)}")
    with open("curriculum/lesson_blueprints/a2_section_01.json", "w", encoding="utf-8") as f:
        json.dump(sec01, f, ensure_ascii=False, indent=2)
    print("Successfully saved curriculum/lesson_blueprints/a2_section_01.json")

