"""
Section 5 Generator Part 2 (Units 106 - 108): 14 Lessons
106: The Five Animals of Pastoral Nomadism: Таван хошуу мал (4 lessons)
107: Pastoral Dairy Processing & Terminative Converb: -тал4 (5 lessons)
108: Countryside Logistics, Weather & Negative Indefinites (5 lessons)
"""

import json
from typing import List, Dict, Any

def get_sec05_part2_lessons(u_map: Dict[int, Any]) -> List[Dict[str, Any]]:
    lessons: List[Dict[str, Any]] = []

    # =========================================================================
    # UNIT 106: The Five Animals of Pastoral Nomadism: Таван хошуу мал (pos 106)
    # 4 Lessons | Targets: ProdLem=19, RecLem=9, ProdExp=5, RecExp=3
    # Budget: (7,3,2,1), (5,3,1,1), (0,0,0,0), (7,3,2,1) = (19, 9, 5, 3)
    # =========================================================================
    u = u_map[106]
    uid = u["unitId"]
    lessons.extend([
        {
            "lessonId": "les_a2_106_01_five_pastoral_animals_lexicon",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 1,
            "title": "The Five Snouts: Pastoral Herds of the Steppe (Таван хошуу мал)",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Introduce the foundational Mongolian pastoral livestock taxonomy: horse, cattle/yak, camel, sheep, goat (адуу/морь, үхэр/сарлаг, тэмээ, хонь, ямаа), their herds (сүрэг), and collective terms.",
            "communicativeOutcome": "Identify, categorize, and describe the five traditional livestock types of Mongolia, distinguishing large cattle (бод мал) from small stock (бог мал).",
            "objectivesIntroduced": ["obj_a2_106_01_five_animals_lexicon"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_a2_105_01_concessive_converb_vch"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_noun_plural_nuud", "gram_a1_predicate_adjective_nominal"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_consonant_clusters"], "phonologyReviewed": ["phono_a1_vowel_reduction_non_initial"],
            "communicativeFunctionsIntroduced": ["comm_a2_15_nomadic_livestock_five_animals"],
            "communicativeFunctionsPracticed": ["comm_a2_14_countryside_ger_visiting_etiquette"], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 7, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_countryside_nature", "lex_domain_culture_traditions"],
            "previousVocabularyReused": ["мал", "сүрэг", "морь", "үхэр", "хонь", "хөдөө"],
            "readingObjective": "Read a pastoral veterinary brochure detailing the geographic distribution of camels in the Gobi and yaks in the Khangai.",
            "listeningObjective": "Understand an elder herder explaining the distinction between бод (horses, cattle, camels) and бог (sheep, goats).",
            "writingObjective": "List the five pastoral animals with their corresponding herd collective nouns in Cyrillic.",
            "spokenProductionObjective": "Describe a herder's stock: 'Манай нутгийн айлууд голдуу үхэр, хонь өсгөдөг бол говьд тэмээн сүрэг олон байдаг'.",
            "registerTarget": "Traditional pastoral animal husbandry register",
            "pragmaticTarget": "Using accurate pastoral collective nouns (адуун сүрэг, хонин сүрэг, тэмээн жин) respectfully.",
            "prerequisiteLessonIds": ["les_a2_105_01_concessive_converb_vch_intro"],
            "reviewsLessonIds": ["les_a1_56_01_countryside_landscape_intro"],
            "reviewsUnitIds": ["unit_a1_56_countryside_landscapes_pastoral_ge"],
            "reviewReason": "Connects pastoral landscapes with active livestock husbandry.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Pronounce pastoral livestock terms clearly.",
            "successCriteria": [
                "Names all five snouts: морь, үхэр, тэмээ, хонь, ямаа",
                "Distinguishes бод мал (large stock) from бог мал (small stock)"
            ],
            "masteryEvidence": "Accurately categorizes and describes livestock distribution across 4 ecological zones of Mongolia.",
            "recommendedExerciseModalities": ["categorization", "matching", "contextual_cloze"]
        },
        {
            "lessonId": "les_a2_106_02_livestock_age_terminology_reading",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 2,
            "title": "Foals, Lambs & Calves: Livestock Age & Gender Classification",
            "lessonType": "reading_development",
            "primaryPurpose": "Develop targeted reading comprehension of agricultural livestock census reports, pasture journals, and herder diaries tracking young animals by age and gender (унага, даага, хурга, ишиг, тугал, ботго).",
            "communicativeOutcome": "Inspect a seasonal livestock birth report, recognize terms for young animals (унага, хурга, ишиг, тугал, ботго), and determine herd growth rates.",
            "objectivesIntroduced": ["obj_a2_106_02_read_livestock_census"],
            "objectivesPracticed": ["obj_a2_106_01_five_animals_lexicon"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_numerals_cardinal_counting", "gram_a1_case_genitive_possession"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_15_nomadic_livestock_five_animals"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_countryside_nature", "lex_domain_culture_traditions"],
            "previousVocabularyReused": ["төл", "хүүхэд", "тоо", "өсөх", "хавар", "намар"],
            "readingObjective": "Extract livestock counts and spring newborn survival figures from a 120-word soum herding report.",
            "listeningObjective": "",
            "writingObjective": "Pair adult livestock with their young offspring in a taxonomy study table.",
            "spokenProductionObjective": "Explain spring births: 'Энэ хавар манай хотонд зуун хурга, тавин ишиг бойжиж байна'.",
            "registerTarget": "Agricultural statistical and pastoral husbandry register",
            "pragmaticTarget": "Understanding the deep cultural joy associated with successful spring births (төл хүлээн авах).",
            "prerequisiteLessonIds": ["les_a2_106_01_five_pastoral_animals_lexicon"],
            "reviewsLessonIds": ["les_a1_27_01_counting_tens_hundreds"],
            "reviewsUnitIds": ["unit_a1_27_cardinal_numerals_higher_quantitie"],
            "reviewReason": "Applies numerical quantification to authentic pastoral livestock headcounts.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Read pastoral agricultural report aloud.",
            "successCriteria": [
                "Pairs every adult animal with its corresponding young: морь-унага, хонь-хурга, ямаа-ишиг, үхэр-тугал, тэмээ-ботго",
                "Extracts newborn counts from a soum census text"
            ],
            "masteryEvidence": "Achieves 100% accuracy matching young animal terms to their species and age brackets.",
            "recommendedExerciseModalities": ["reading_comprehension", "matching", "categorization"]
        },
        {
            "lessonId": "les_a2_106_03_pasture_herding_acoustic_listening",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 3,
            "title": "Acoustic Lab: Pasture Calls, Whistles & Herding Directives",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop acoustic listening comprehension of authentic open-air pasture audio where herders ride horses, whistle, call out traditional animal driving sounds (чөөг, хөөг, өвөө), and guide livestock toward water wells.",
            "communicativeOutcome": "Understand herder calls on the steppe, distinguish specific pastoral commands, and follow herding movements across pastures.",
            "objectivesIntroduced": ["obj_a2_106_03_decode_pastoral_calls"],
            "objectivesPracticed": ["obj_a2_106_01_five_animals_lexicon"], "objectivesReviewed": ["obj_a1_39_01_instrumental_case"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_allative_direction", "gram_a1_verb_imperative_polite_aarai"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_vowel_reduction_non_initial"], "phonologyReviewed": ["phono_a1_nasal_vowels"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_15_nomadic_livestock_five_animals"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_countryside_nature"],
            "previousVocabularyReused": ["худаг", "ус", "бэлчээр", "туух", "морь", "дуудах"],
            "readingObjective": "",
            "listeningObjective": "Identify specific herding directives (bringing sheep to the well, rounding up horses) from steppe pasture audio.",
            "writingObjective": "",
            "spokenProductionObjective": "Explain to a partner which pasture the herd is moving toward based on audio cues.",
            "registerTarget": "Open-air pastoral acoustic and vocal directive register",
            "pragmaticTarget": "Deciphering traditional animal calling interjections used across the Eurasian steppe.",
            "prerequisiteLessonIds": ["les_a2_106_01_five_pastoral_animals_lexicon"],
            "reviewsLessonIds": ["les_a1_104_03_raising_a_ger_acoustic_listening"],
            "reviewsUnitIds": ["unit_a2_104_the_mongolian_ger_architectural_ana"],
            "reviewReason": "Expands countryside auditory decoding from domestic camp to open pasture fields.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Steppe pasture audio with horse hoofbeats, sheep bleating, and rhythmic herder whistling.",
            "successCriteria": [
                "Identifies which livestock type is being directed from audio cues",
                "Extracts destination (уст худаг, хойд бэлчээр) from heard herder speech"
            ],
            "masteryEvidence": "Accurately maps out pasture livestock movements based on 3 distinct herding audio tracks.",
            "recommendedExerciseModalities": ["listening_comprehension", "phonetic_discrimination", "sequencing"]
        },
        {
            "lessonId": "les_a2_106_04_herder_camp_pastoral_life_dialogue",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 4,
            "title": "A Day in the Khot Ail: Inquiring About Herds, Grazing & Pasture",
            "lessonType": "dialogue_work",
            "primaryPurpose": "Master spoken communication for conversational exchanges with herders: discussing pasture condition (бэлчээрийн гарц), seasonal migration plans (оторт явах), and herd health.",
            "communicativeOutcome": "Engage in an authentic, respectful conversation with a nomadic herder about pasture conditions, livestock numbers, and nomadic seasonal rhythms.",
            "objectivesIntroduced": ["obj_a2_106_04_pastoral_life_dialogue"],
            "objectivesPracticed": ["obj_a2_106_01_five_animals_lexicon", "obj_a2_106_02_read_livestock_census"],
            "objectivesReviewed": ["obj_a1_16_01_greet_time_of_day"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_comitative_association", "gram_a1_polar_questions_uu_uu"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_intonation_polite"], "phonologyReviewed": ["phono_a1_diphthongs"],
            "communicativeFunctionsIntroduced": ["comm_a2_15_nomadic_livestock_five_animals"],
            "communicativeFunctionsPracticed": ["comm_a1_16_greetings_time_of_day"],
            "communicativeFunctionsReviewed": ["comm_a1_13_apologies_politeness"],
            "newProductiveLemmaTarget": 7, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_countryside_nature", "lex_domain_social_interaction"],
            "previousVocabularyReused": ["бэлчээр", "өвс", "бороо", "отор", "нүүх", "сайхан"],
            "readingObjective": "",
            "listeningObjective": "Understand herder explaining that good summer rains have produced rich grass for the horses.",
            "writingObjective": "",
            "spokenProductionObjective": "Inquire about pasture: 'Танай нутгаар зуншлага хэр байна? Бэлчээрийн өвс ногоо сайн ургаж байна уу?'.",
            "registerTarget": "Respectful pastoral small talk register",
            "pragmaticTarget": "Never asking direct, blunt livestock counts (considered bad omen); using respectful general inquiries instead.",
            "prerequisiteLessonIds": ["les_a2_106_02_livestock_age_terminology_reading", "les_a2_106_03_pasture_herding_acoustic_listening"],
            "reviewsLessonIds": ["les_a1_105_03_nomadic_hospitality_tea_offering_dialogue"],
            "reviewsUnitIds": ["unit_a2_105_ger_etiquette_sacred_threshold_hear"],
            "reviewReason": "Deepens tea-offering dialogue into rich conversational discussion of livestock and pasture.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Warm, authentic dialogue between traveling guest and knowledgeable herder host.",
            "successCriteria": [
                "Uses traditional pastoral idioms for pasture well-being (зуншлага сайхан, ногоо сайн)",
                "Respects cultural convention of indirect herd inquiry"
            ],
            "masteryEvidence": "Conducts a 5-turn pastoral dialogue discussing grazing lands and livestock well-being with natural poise.",
            "recommendedExerciseModalities": ["role-play response", "dialogue_completion", "listening_comprehension"]
        }
    ])

    # =========================================================================
    # UNIT 107: Pastoral Dairy Processing & Terminative Converb: -тал4 (pos 107)
    # 5 Lessons | Targets: ProdLem=21, RecLem=10, ProdExp=5, RecExp=3
    # Budget: (5,2,1,1), (6,3,1,1), (5,3,2,1), (0,0,0,0), (5,2,1,0) = (21, 10, 5, 3)
    # =========================================================================
    u = u_map[107]
    uid = u["unitId"]
    lessons.extend([
        {
            "lessonId": "les_a2_107_01_terminative_converb_tal_intro",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 1,
            "title": "Until & By the Time: The Terminative Converb (-тал/-тэл/-тол/-төл)",
            "lessonType": "grammar_introduction",
            "primaryPurpose": "Introduce the terminative converb suffix (-тал4 / -тэл / -тол / -төл) indicating temporal boundaries: an action continuing 'until' an event occurs, or an event happening 'by the time' another action unfolds.",
            "communicativeOutcome": "Form terminative temporal clauses: 'Сүүг буцалтал самар' (Stir the milk until it boils), 'Намайг очитол хоол бэлэн болсон байв' (By the time I arrived, dinner was ready).",
            "objectivesIntroduced": ["obj_a2_107_01_terminative_converb_tal"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_a2_106_01_five_animals_lexicon"],
            "grammarIntroduced": ["gram_a2_converb_terminative_tal"],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_converb_sequential_aad", "gram_a1_verb_imperative_polite_aarai"],
            "phonologyIntroduced": ["phono_a2_terminative_suffix_harmony"],
            "phonologyPracticed": ["phono_a1_masculine_feminine_harmony"], "phonologyReviewed": ["phono_a1_consonant_clusters"],
            "communicativeFunctionsIntroduced": ["comm_a2_26_simple_recipe_cooking_steps"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_food_cuisine", "lex_domain_daily_routines"],
            "previousVocabularyReused": ["хүлээх", "болох", "хийх", "очих", "ирнэ", "хүртэл"],
            "readingObjective": "Read traditional dairy preparation instructions explaining how long to simmer milk.",
            "listeningObjective": "Identify verbs ending in -тал4 in cooking instructions.",
            "writingObjective": "Combine 4 pairs of clauses into temporal bounds using -тал4.",
            "spokenProductionObjective": "Give step-by-step instruction: 'Сүү хөртөл тагийг нь битгий таглаарай'.",
            "registerTarget": "Procedural instructional and culinary process register",
            "pragmaticTarget": "Expressing precise temporal endpoints in culinary and craft processes.",
            "prerequisiteLessonIds": ["les_a2_106_01_five_pastoral_animals_lexicon"],
            "reviewsLessonIds": ["les_a1_50_01_sequential_converb_aad"],
            "reviewsUnitIds": ["unit_a1_50_sequential_converb_clause_connector"],
            "reviewReason": "Expands clause connectors from sequence (-аад) to terminative endpoints (-тал).",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Model harmonious articulation of -тал, -тэл, -тол, -төл.",
            "successCriteria": [
                "Attaches correct harmonic allomorph of -тал4 based on root vowels",
                "Constructs clauses specifying actions continuing until a state change occurs"
            ],
            "masteryEvidence": "Produces 'Өрөм тогттол сүүг хөдөлгөөнгүй байлгах хэрэгтэй' with grammatical precision.",
            "recommendedExerciseModalities": ["suffix_selection", "clause_combination", "matching"]
        },
        {
            "lessonId": "les_a2_107_02_white_food_dairy_processing_lexicon",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 2,
            "title": "White Food: Pastoral Dairy Processing & Delicacies (Цагаан идээ)",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Introduce traditional Mongolian dairy products and processing terminology (цагаан идээ, сүү саах, хөөрүүлэх, өрөм хураах, ааруул хатаах, тараг бүрэх, айраг исгэх).",
            "communicativeOutcome": "Describe traditional nomadic dairy crafts: milking cows/mares, boiling milk, skimming clotted cream (өрөм), setting yogurt (тараг), drying curd cheese (ааруул), and fermenting airag.",
            "objectivesIntroduced": ["obj_a2_107_02_dairy_processing_lexicon"],
            "objectivesPracticed": ["obj_a2_107_01_terminative_converb_tal"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_converb_terminative_tal"],
            "grammarReviewed": ["gram_a1_case_accusative_definite", "gram_a1_case_instrumental_transport_language"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_consonant_clusters"], "phonologyReviewed": ["phono_a1_vowel_reduction_non_initial"],
            "communicativeFunctionsIntroduced": ["comm_a2_26_simple_recipe_cooking_steps"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_food_cuisine", "lex_domain_culture_traditions"],
            "previousVocabularyReused": ["сүү", "идээ", "өрөм", "ааруул", "айраг", "хийх"],
            "readingObjective": "Read an authentic recipe guide explaining how to make dried curd cheese (ааруул) in the summer sun.",
            "listeningObjective": "Understand an elder explaining the intricate steps of fermenting mare's milk into airag.",
            "writingObjective": "List 5 iconic Mongolian dairy products with their preparation methods in Cyrillic.",
            "spokenProductionObjective": "Explain dairy process: 'Бид өглөө эрт сүүгээ саагаад, тогоонд хөөрүүлж өрөм хураадаг'.",
            "registerTarget": "Traditional culinary heritage and dairy craft register",
            "pragmaticTarget": "Expressing appreciation for the artisanal complexity of nomadic dairy culture.",
            "prerequisiteLessonIds": ["les_a2_107_01_terminative_converb_tal_intro"],
            "reviewsLessonIds": ["les_a1_60_01_food_preparation_cooking_intro"],
            "reviewsUnitIds": ["unit_a1_60_cooking_recipes_food_preparation_"],
            "reviewReason": "Elevates domestic cooking to nomadic dairy processing traditions.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Pronounce pastoral dairy terminology clearly.",
            "successCriteria": [
                "Defines өрөм (clotted cream), ааруул (dried curd), тараг (yogurt), айраг (fermented mare's milk)",
                "Uses processing verbs: саах (milk), хөөрүүлэх (boil milk), бүрэх (set yogurt), исгэх (ferment)"
            ],
            "masteryEvidence": "Accurately details the 4-step sequence for preparing curd cheese using terminative converbs.",
            "recommendedExerciseModalities": ["categorization", "contextual_cloze", "matching"]
        },
        {
            "lessonId": "les_a2_107_03_dairy_making_masterclass_dialogue",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 3,
            "title": "Making Airag & Aaruul: Learning Dairy Crafts from a Nomadic Host",
            "lessonType": "dialogue_work",
            "primaryPurpose": "Develop spoken communicative fluency for participating in dairy preparation: asking how many times to churn airag (айраг бүлэх), when to cut curds, and how to preserve milk products for winter.",
            "communicativeOutcome": "Engage in an interactive cooking dialogue with a herder host, asking practical questions about dairy processing steps, timing, and traditional fermentation secrets.",
            "objectivesIntroduced": ["obj_a2_107_03_dairy_making_dialogue"],
            "objectivesPracticed": ["obj_a2_107_01_terminative_converb_tal", "obj_a2_107_02_dairy_processing_lexicon"],
            "objectivesReviewed": ["obj_a1_16_01_greet_time_of_day"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_converb_terminative_tal"],
            "grammarReviewed": ["gram_a1_verb_imperative_polite_aarai", "gram_a1_polar_questions_uu_uu"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_intonation_polite"], "phonologyReviewed": ["phono_a1_diphthongs"],
            "communicativeFunctionsIntroduced": ["comm_a2_26_simple_recipe_cooking_steps"],
            "communicativeFunctionsPracticed": ["comm_a1_16_greetings_time_of_day"],
            "communicativeFunctionsReviewed": ["comm_a1_13_apologies_politeness"],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_food_cuisine", "lex_domain_culture_traditions"],
            "previousVocabularyReused": ["бүлэх", "хэрхэн", "хэзээ", "цаг", "заах", "амттай"],
            "readingObjective": "",
            "listeningObjective": "Understand host instructing visitor to churn the leather airag sack (хөхүүр) 1,000 times until frothy.",
            "writingObjective": "",
            "spokenProductionObjective": "Ask and confirm: 'Энэ ааруулыг наранд хэдэн өдөр хаттал нь тавих вэ?'.",
            "registerTarget": "Hands-on apprenticeship and domestic instruction register",
            "pragmaticTarget": "Showing enthusiasm to learn nomadic traditions hands-on.",
            "prerequisiteLessonIds": ["les_a2_107_02_white_food_dairy_processing_lexicon"],
            "reviewsLessonIds": ["les_a1_60_05_cooking_recipe_instruction_dialog"],
            "reviewsUnitIds": ["unit_a1_60_cooking_recipes_food_preparation_"],
            "reviewReason": "Deepens recipe dialogue with pastoral artisanal techniques.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Warm, patient dialogue between knowledgeable dairy craftswoman and enthusiastic learner.",
            "successCriteria": [
                "Asks procedural questions about dairy fermentation timing using -тал",
                "Follows host's live culinary instructions accurately"
            ],
            "masteryEvidence": "Conducts a 5-turn dairy crafting dialogue mastering churning and drying protocols.",
            "recommendedExerciseModalities": ["role-play response", "dialogue_completion", "listening_comprehension"]
        },
        {
            "lessonId": "les_a2_107_04_culinary_heritage_acoustic_listening",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 4,
            "title": "Acoustic Lab: Radio Documentary on Nomadic Gastronomy & Milk Fermentation",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop acoustic listening comprehension of a radio documentary exploring the microbial science and heritage of nomadic milk fermentation, churn acoustics, and seasonal diets.",
            "communicativeOutcome": "Extract processing steps, scientific health benefits of dairy curds, and seasonal consumption patterns from an authentic documentary audio clip.",
            "objectivesIntroduced": ["obj_a2_107_04_decode_gastronomy_documentary"],
            "objectivesPracticed": ["obj_a2_107_01_terminative_converb_tal"], "objectivesReviewed": ["obj_a1_41_01_witnessed_past_laa"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a2_converb_terminative_tal", "gram_a1_converb_coordinating_j_ch"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_vowel_reduction_non_initial"], "phonologyReviewed": ["phono_a1_nasal_vowels"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_26_simple_recipe_cooking_steps"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_food_cuisine", "lex_domain_culture_traditions"],
            "previousVocabularyReused": ["эрүүл мэнд", "ашигтай", "хоол", "зун", "өвөл", "эрдэмтэн"],
            "readingObjective": "",
            "listeningObjective": "Identify specific health benefits of aaruul (calcium, teeth strengthening) from documentary narration.",
            "writingObjective": "",
            "spokenProductionObjective": "Summarize the documentary's explanation of summer dairy detox to a peer.",
            "registerTarget": "Educational radio documentary broadcast register",
            "pragmaticTarget": "Synthesizing culinary heritage with modern nutritional science concepts.",
            "prerequisiteLessonIds": ["les_a2_107_02_white_food_dairy_processing_lexicon"],
            "reviewsLessonIds": ["les_a1_94_04_radio_memoir_acoustic_listening"],
            "reviewsUnitIds": ["unit_a2_94_childhood_hometown_recollections_ea"],
            "reviewReason": "Applies documentary listening skills to gastronomic and ethnobotanical science.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Polished documentary narration interspersed with rhythmic sounds of butter churning.",
            "successCriteria": [
                "Identifies the primary scientific benefit of fermented dairy explained in the audio",
                "Extracts terminative clauses ending in -тал4 from the spoken narrative"
            ],
            "masteryEvidence": "Answers 5 detailed factual questions after listening to a 90-second documentary segment.",
            "recommendedExerciseModalities": ["listening_comprehension", "phonetic_discrimination", "categorization"]
        },
        {
            "lessonId": "les_a2_107_05_traditional_recipe_card_writing",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 5,
            "title": "Nomad's Kitchen: Writing a Traditional Step-by-Step Dairy Recipe",
            "lessonType": "grammar_guided_practice",
            "primaryPurpose": "Synthesize terminative converbs (-тал4), dairy processing vocabulary, and imperative directives into a clear written recipe card for making Mongolian yogurt or clotted cream.",
            "communicativeOutcome": "Write an instructional recipe card outlining equipment, ingredients, and sequential preparation steps for an authentic nomadic dairy delicacy.",
            "objectivesIntroduced": ["obj_a2_107_05_write_dairy_recipe"],
            "objectivesPracticed": ["obj_a2_107_01_terminative_converb_tal", "obj_a2_107_02_dairy_processing_lexicon"],
            "objectivesReviewed": ["obj_a1_50_01_sequential_converb"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_converb_terminative_tal"],
            "grammarReviewed": ["gram_a1_verb_imperative_polite_aarai", "gram_a1_converb_sequential_aad"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_26_simple_recipe_cooking_steps"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_food_cuisine", "lex_domain_culture_traditions"],
            "previousVocabularyReused": ["жор", "орц", "хийх", "дараалал", "тогоо", "амтлах"],
            "readingObjective": "Review a classic cookbook layout for traditional pastoral confectionery.",
            "listeningObjective": "",
            "writingObjective": "Draft a 6-step recipe for making yogurt (тараг бүрэх) utilizing at least 2 terminative converbs in -тал4.",
            "spokenProductionObjective": "",
            "registerTarget": "Instructive culinary recipe register",
            "pragmaticTarget": "Structuring clear, repeatable instructional steps with unambiguous temporal markers.",
            "prerequisiteLessonIds": ["les_a2_107_03_dairy_making_masterclass_dialogue", "les_a2_107_04_culinary_heritage_acoustic_listening"],
            "reviewsLessonIds": ["les_a1_60_05_cooking_recipe_instruction_dialog"],
            "reviewsUnitIds": ["unit_a1_60_cooking_recipes_food_preparation_"],
            "reviewReason": "Transitions verbal recipe instructions into structured written recipe card publications.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Audio read-back of written recipe instructions.",
            "successCriteria": [
                "Produces written recipe card with ingredients, tools, and ordered steps",
                "Integrates terminative converbs accurately: 'бүлээхэн болтол нь хөргөнө'"
            ],
            "masteryEvidence": "Drafts 'Сүүгээ сайтар хөөрүүлээд, бүлээн болтол нь хөргөнө. Дараа нь хөрөнгө хийж хучаад, 4 цаг болтол хөдөлгөхгүй тавина' flawlessly.",
            "recommendedExerciseModalities": ["short-answer writing", "sentence construction", "error correction"]
        }
    ])

    # =========================================================================
    # UNIT 108: Countryside Logistics, Weather & Negative Indefinites (pos 108)
    # 5 Lessons | Targets: ProdLem=21, RecLem=10, ProdExp=5, RecExp=3
    # Budget: (5,2,1,1), (6,3,1,1), (5,3,2,1), (0,0,0,0), (5,2,1,0) = (21, 10, 5, 3)
    # =========================================================================
    u = u_map[108]
    uid = u["unitId"]
    lessons.extend([
        {
            "lessonId": "les_a2_108_01_indefinite_pronouns_negation_intro",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 1,
            "title": "Nowhere & Nobody: Indefinite Pronouns with Negation (юу ч үгүй, хэн ч биш)",
            "lessonType": "grammar_introduction",
            "primaryPurpose": "Introduce indefinite pronouns combined with emphatic particle ч and negative predicates expressing absolute negative polarity: хэн ч биш / байхгүй (nobody), юу ч үгүй / хийхгүй (nothing), хаашаа ч үгүй (nowhere), хэзээ ч үгүй (never).",
            "communicativeOutcome": "Express absolute negative states in remote wilderness: 'Тэнд хэн ч байхгүй' (There is nobody there), 'Замд юу ч харагдахгүй байна' (Nothing is visible on the road), 'Би хаашаа ч яваагүй' (I went nowhere).",
            "objectivesIntroduced": ["obj_a2_108_01_negative_indefinites"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_a2_107_01_terminative_converb_tal"],
            "grammarIntroduced": ["gram_a2_indefinite_pronouns_negation"],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_negative_particles_gui_bish", "gram_a1_existential_baina_baihgui"],
            "phonologyIntroduced": ["phono_a2_negative_indefinite_stress"],
            "phonologyPracticed": ["phono_a1_vowel_length_distinction"], "phonologyReviewed": ["phono_a1_consonant_clusters"],
            "communicativeFunctionsIntroduced": ["comm_a2_16_seasonal_weather_forecast"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_travel_transport", "lex_domain_geography_places"],
            "previousVocabularyReused": ["хэн", "юу", "хаана", "хэзээ", "байхгүй", "үгүй"],
            "readingObjective": "Read safety advisories describing isolated Gobi wilderness stretches where there are no settlements for 200 km.",
            "listeningObjective": "Identify negative indefinite constructions (юу ч алга, хэн ч ирээгүй) in travel broadcasts.",
            "writingObjective": "Write 4 sentences describing isolated steppe conditions using negative indefinites.",
            "spokenProductionObjective": "Describe remote wilderness: 'Энэ талд хэн ч амьдардаггүй, юу ч үгүй нам гүм байдаг'.",
            "registerTarget": "Standard negative polarity and wilderness description register",
            "pragmaticTarget": "Using emphatic particle 'ч' with negation to convey complete emptiness or absence emphatically.",
            "prerequisiteLessonIds": ["les_a2_107_01_terminative_converb_tal_intro"],
            "reviewsLessonIds": ["les_a1_22_01_negation_particles_intro"],
            "reviewsUnitIds": ["unit_a1_22_negative_predicates_particles_bi"],
            "reviewReason": "Expands simple negation (үгүй, биш) to complete negative indefinite pronouns.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Model emphatic stress on clitic particle 'ч' before negative verbs.",
            "successCriteria": [
                "Pairs interrogative stems with particle ч and negative predicates (хэн ч үгүй, юу ч үгүй)",
                "Contrasts negative polarity with affirmative existential statements"
            ],
            "masteryEvidence": "Produces 'Өвлийн замд ямар ч машин тааралдсангүй' without hesitation.",
            "recommendedExerciseModalities": ["suffix_selection", "sentence_transformation", "matching"]
        },
        {
            "lessonId": "les_a2_108_02_countryside_travel_hazards_weather_lexicon",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 2,
            "title": "Blizzards, Mud & Mountain Passes: Countryside Travel Hazards & Weather",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Introduce steppe weather hazards, off-road driving risks, and route logistics vocabulary (цасан шуурга, шавар, даваа гүвээ, зам хаагдах, төөрөх, шатахуун, сэлбэг хэрэгсэл).",
            "communicativeOutcome": "Understand seasonal weather warnings, plan off-road road trips, prepare reserve fuel and spare tires, and describe treacherous mountain pass conditions.",
            "objectivesIntroduced": ["obj_a2_108_02_travel_hazards_weather_lexicon"],
            "objectivesPracticed": ["obj_a2_108_01_negative_indefinites"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_indefinite_pronouns_negation"],
            "grammarReviewed": ["gram_a1_case_ablative_origin", "gram_a1_predicate_adjective_nominal"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_consonant_clusters"], "phonologyReviewed": ["phono_a1_vowel_reduction_non_initial"],
            "communicativeFunctionsIntroduced": ["comm_a2_16_seasonal_weather_forecast"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_travel_transport", "lex_domain_weather_climate"],
            "previousVocabularyReused": ["цас", "бороо", "шуурга", "зам", "унаа", "аюултай"],
            "readingObjective": "Read National Emergency Management Agency (ОБЕГ) weather alerts warning of sudden blizzards across western aimags.",
            "listeningObjective": "Understand an off-road expedition leader briefing drivers on rocky passes and reserve fuel canisters.",
            "writingObjective": "List 5 essential winter road trip survival items in Cyrillic.",
            "spokenProductionObjective": "Warn companions: 'Даваа цасаар хаагдсан тул өнөөдөр яагаад ч явж болохгүй'.",
            "registerTarget": "Emergency preparedness and travel safety advisory register",
            "pragmaticTarget": "Taking steppe weather risks seriously and adhering strictly to safety advisories.",
            "prerequisiteLessonIds": ["les_a2_108_01_indefinite_pronouns_negation_intro"],
            "reviewsLessonIds": ["les_a1_57_01_weather_seasons_intro"],
            "reviewsUnitIds": ["unit_a1_57_weather_conditions_seasons_climate"],
            "reviewReason": "Elevates basic weather descriptions to severe steppe logistics and travel safety hazards.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Pronounce meteorological warning terms clearly.",
            "successCriteria": [
                "Defines цасан шуурга (blizzard), даваа (mountain pass), шатахуун (fuel), төөрөх (get lost)",
                "Interprets severity levels of national meteorological warnings"
            ],
            "masteryEvidence": "Accurately assesses route viability based on an official road condition bulletin.",
            "recommendedExerciseModalities": ["categorization", "contextual_cloze", "matching"]
        },
        {
            "lessonId": "les_a2_108_03_road_condition_advisory_dialogue",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 3,
            "title": "Is the Pass Clear: Inquiring About Road Conditions at Countryside Gas Stations",
            "lessonType": "dialogue_work",
            "primaryPurpose": "Master spoken communication for en-route countryside travel: asking gas station attendants and local drivers about road conditions ahead, muddy river crossings, and pass clearance.",
            "communicativeOutcome": "Stop at a remote countryside petrol station, inquire about pass viability ('Даваагаар машин гарч байна уу?'), check fuel quality, and decide whether to proceed or wait out a storm.",
            "objectivesIntroduced": ["obj_a2_108_03_road_condition_dialogue"],
            "objectivesPracticed": ["obj_a2_108_01_negative_indefinites", "obj_a2_108_02_travel_hazards_weather_lexicon"],
            "objectivesReviewed": ["obj_a1_16_01_greet_time_of_day"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_indefinite_pronouns_negation"],
            "grammarReviewed": ["gram_a1_converb_conditional_val", "gram_a1_polar_questions_uu_uu"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_intonation_polite"], "phonologyReviewed": ["phono_a1_diphthongs"],
            "communicativeFunctionsIntroduced": ["comm_a2_16_seasonal_weather_forecast"],
            "communicativeFunctionsPracticed": ["comm_a1_16_greetings_time_of_day"],
            "communicativeFunctionsReviewed": ["comm_a1_13_apologies_politeness"],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_travel_transport"],
            "previousVocabularyReused": ["бензин", "зам", "гарах", "хэцүү", "хонох", "болгоомжтой"],
            "readingObjective": "",
            "listeningObjective": "Understand local trucker warning that the river bridge washed out and detour is necessary.",
            "writingObjective": "",
            "spokenProductionObjective": "Inquire and decide: 'Урд талын даваа цастай юу? Хэрэв зам хэцүү бол бид сумын төвд хонохоор шийдлээ'.",
            "registerTarget": "Practical traveler roadside consultation register",
            "pragmaticTarget": "Seeking reliable local intelligence before entering hazardous terrain.",
            "prerequisiteLessonIds": ["les_a2_108_02_countryside_travel_hazards_weather_lexicon"],
            "reviewsLessonIds": ["les_a1_71_05_route_planning_dialogue"],
            "reviewsUnitIds": ["unit_a2_71_urban_bus_navigation_routes_stops_"],
            "reviewReason": "Expands route navigation dialogues from city buses to remote steppe highways.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Realistic roadside exchange with idling diesel engine background sound.",
            "successCriteria": [
                "Asks detailed questions regarding road surface, mud, and pass conditions",
                "Incorporates negative indefinites: 'замд ямар ч утасны сүлжээ байхгүй'"
            ],
            "masteryEvidence": "Conducts a 5-turn roadside inquiry dialogue reaching a safe travel decision.",
            "recommendedExerciseModalities": ["role-play response", "dialogue_completion", "listening_comprehension"]
        },
        {
            "lessonId": "les_a2_108_04_weather_warning_broadcast_listening",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 4,
            "title": "Acoustic Lab: National Meteorological Emergency Bulletins",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop acoustic listening comprehension of official radio weather warnings (цаг агаарын аюултай үзэгдлийн сэрэмжлүүлэг), wind velocity alerts (м/с), and temperature drops.",
            "communicativeOutcome": "Decode emergency radio alerts: extract specific aimags affected, wind gusts in meters per second, blizzard onset times, and travel bans.",
            "objectivesIntroduced": ["obj_a2_108_04_decode_weather_alerts"],
            "objectivesPracticed": ["obj_a2_108_01_negative_indefinites"], "objectivesReviewed": ["obj_a1_27_01_counting_tens_hundreds"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a2_indefinite_pronouns_negation", "gram_a1_case_dative_locative_time"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_vowel_reduction_non_initial"], "phonologyReviewed": ["phono_a1_nasal_vowels"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_16_seasonal_weather_forecast"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_weather_climate", "lex_domain_civic_administrative"],
            "previousVocabularyReused": ["сэрэмжлүүлэг", "салхи", "хүйтрэх", "аймаг", "анхаарах", "сонсох"],
            "readingObjective": "",
            "listeningObjective": "Extract wind speeds (18-20 м/с) and blizzard start times from an urgent radio bulletin.",
            "writingObjective": "",
            "spokenProductionObjective": "Summarize the emergency bulletin to fellow travelers in 3 sentences.",
            "registerTarget": "Urgent official broadcast warning register",
            "pragmaticTarget": "Extracting critical numbers and geographic scopes rapidly during emergency broadcasts.",
            "prerequisiteLessonIds": ["les_a2_108_02_countryside_travel_hazards_weather_lexicon"],
            "reviewsLessonIds": ["les_a1_68_03_traffic_radio_listening"],
            "reviewsUnitIds": ["unit_a2_68_handling_transit_delays_traffic_jam"],
            "reviewReason": "Elevates traffic delay listening to nationwide meteorological alerts.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Urgent news chime followed by authoritative announcer reading weather bulletin.",
            "successCriteria": [
                "Identifies which 3 aimags are placed under blizzard warning from audio",
                "Extracts specific advisory directives (e.g. hold livestock near camps, cancel long-distance travel)"
            ],
            "masteryEvidence": "Accurately completes an emergency action sheet based on a 60-second weather bulletin.",
            "recommendedExerciseModalities": ["listening_comprehension", "phonetic_discrimination", "categorization"]
        },
        {
            "lessonId": "les_a2_108_05_expedition_safety_checklist_writing",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 5,
            "title": "Winter Expedition: Writing an Off-Road Safety Plan & Equipment Checklist",
            "lessonType": "grammar_guided_practice",
            "primaryPurpose": "Synthesize negative indefinite pronouns (юу ч үгүй, хаашаа ч үгүй), travel hazard terms, and conditional precautions into a written expedition safety protocol.",
            "communicativeOutcome": "Draft a written travel safety checklist and emergency protocol for an off-road journey across remote aimags, outlining contingency plans for breakdowns and storms.",
            "objectivesIntroduced": ["obj_a2_108_05_write_travel_safety_plan"],
            "objectivesPracticed": ["obj_a2_108_01_negative_indefinites", "obj_a2_108_02_travel_hazards_weather_lexicon"],
            "objectivesReviewed": ["obj_a1_50_01_sequential_converb"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_indefinite_pronouns_negation"],
            "grammarReviewed": ["gram_a1_converb_conditional_val", "gram_a1_verb_prohibitive_bitgii"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_16_seasonal_weather_forecast"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_travel_transport", "lex_domain_weather_climate"],
            "previousVocabularyReused": ["төлөвлөгөө", "аюулгүй", "бэлтгэл", "дулаан", "хэрэгсэл", "бичих"],
            "readingObjective": "Review professional mountaineering and 4WD club expedition checklists.",
            "listeningObjective": "",
            "writingObjective": "Draft a 6-point travel safety guide containing at least 2 negative indefinite pronoun constructions.",
            "spokenProductionObjective": "",
            "registerTarget": "Instructive safety protocol and planning register",
            "pragmaticTarget": "Presenting life-saving travel precautions systematically and authoritatively.",
            "prerequisiteLessonIds": ["les_a2_108_03_road_condition_advisory_dialogue", "les_a2_108_04_weather_warning_broadcast_listening"],
            "reviewsLessonIds": ["les_a1_95_05_travel_blog_post_writing"],
            "reviewsUnitIds": ["unit_a2_95_narrating_past_vacations_countrysid"],
            "reviewReason": "Connects travel blogging with professional safety and logistics planning.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Audio read-back of written expedition safety checklist.",
            "successCriteria": [
                "Produces written safety protocol with vehicle checks, emergency supplies, and weather protocol",
                "Applies negative indefinites correctly: 'сүлжээгүй газар хаашаа ч ганцаараа бүү яв'"
            ],
            "masteryEvidence": "Drafts 'Хээр хөдөө замд гарахад юу ч тохиолдож болно. Тиймээс бэлтгэлгүйгээр хаашаа ч явахгүй байх нь чухал...' flawlessly.",
            "recommendedExerciseModalities": ["short-answer writing", "sentence construction", "error correction"]
        }
    ])

    return lessons
