"""
Section 2 Generator Part 3 (Units 80 - 82): 14 Lessons
80: Tailoring & Traditional Deel Alterations (5 lessons)
81: Cashmere Shopping & Wool Certification (4 lessons)
82: Retail & Service Capstone (5 lessons)
"""

import json
from typing import List, Dict, Any

def get_sec02_part3_lessons(u_map: Dict[int, Any]) -> List[Dict[str, Any]]:
    lessons: List[Dict[str, Any]] = []

    # =========================================================================
    # UNIT 80: Tailoring, Traditional Deel & Alterations: -uul4, -aad4 (pos 80)
    # 5 Lessons | Targets: ProdLem=21, RecLem=10, ProdExp=5, RecExp=3
    # Budget: (5,2,1,1), (6,3,1,1), (5,3,2,1), (0,0,0,0), (5,2,1,0) = (21, 10, 5, 3)
    # =========================================================================
    u = u_map[80]
    uid = u["unitId"]
    lessons.extend([
        {
            "lessonId": "les_a2_80_01_collective_approximate_numerals_intro",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 1,
            "title": "All of Us & About Twenty: Collective & Approximate Numerals",
            "lessonType": "grammar_introduction",
            "primaryPurpose": "Introduce collective numerals (-уул4: хоёул, гурвуул, дөрвүүл) and approximate numerals (-аад4: аравtrans, хориод, гучаад, зуугаад) for groups and approximations.",
            "communicativeOutcome": "Express group participation ('Бид гурвуул хамт оёдолчинд очлоо') and approximate measurements/costs ('Энэ дээл хориод метр торго орно').",
            "objectivesIntroduced": ["obj_a2_80_01_collective_approximate_numerals"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_a2_79_01_conditional_converb_val"],
            "grammarIntroduced": ["gram_a2_numerals_collective_approximate"],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_numerals_cardinal_counting", "gram_a1_case_comitative_association"],
            "phonologyIntroduced": ["phono_a2_collective_numeral_elision"],
            "phonologyPracticed": ["phono_a1_masculine_feminine_harmony"], "phonologyReviewed": ["phono_a1_consonant_clusters"],
            "communicativeFunctionsIntroduced": ["comm_a2_02_describing_appearance_clothing"],
            "communicativeFunctionsPracticed": ["comm_a2_23_comparing_items_places"], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_clothing_fashion", "lex_domain_measurements_quantities"],
            "previousVocabularyReused": ["нэг", "хоёр", "гурав", "дөрөв", "тав", "арав"],
            "readingObjective": "Read tailor's workshop pricing estimates utilizing approximate numbers (-аад).",
            "listeningObjective": "Identify collective numerals in group errand descriptions ('Бид хоёул явъя').",
            "writingObjective": "Write 3 sentences contrasting exact vs approximate quantities in tailoring.",
            "spokenProductionObjective": "Explain group outing: 'Бид дөрвүүл баярын дээлээ захиалахаар оёдлын газар очсон'.",
            "registerTarget": "Standard collaborative everyday register",
            "pragmaticTarget": "Using collective numerals to emphasize unified group action rather than separate individuals.",
            "prerequisiteLessonIds": ["les_a2_79_01_conditional_converb_val_intro"],
            "reviewsLessonIds": ["les_a1_27_01_counting_tens_hundreds"],
            "reviewsUnitIds": ["unit_a1_27_cardinal_numbers_counting_up_to_one"],
            "reviewReason": "Expands cardinal number roots into collective (-уул) and approximate (-аад) numerical derivatives.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Model phonological reduction in collective forms (хоёр + уул = хоёул).",
            "successCriteria": [
                "Forms collective numerals accurately for roots 2 through 7 (хоёул, гурвуул, дөрвүүл, тавуул, зургаул, долуулаа)",
                "Applies approximate suffix -аад to decades (арав -> аравtrans, хорь -> хориод)"
            ],
            "masteryEvidence": "Produces 'Бид тавуул хориод метр торго авлаа' without morphological hesitation.",
            "recommendedExerciseModalities": ["suffix_selection", "sentence_construction", "matching"]
        },
        {
            "lessonId": "les_a2_80_02_tailoring_measurements_alterations_lexicon",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 2,
            "title": "At the Atelier: Deel Tailoring, Seams & Measurements",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Introduce traditional tailoring and alterations vocabulary (оёдолчин, хэмжээ авах, энгэр, нударга, зах, хажлага, ханцуй богиносгох, хасах).",
            "communicativeOutcome": "Explain tailoring instructions to a seamstress: taking measurements, altering sleeve lengths, selecting collar styles, and adjusting waist seams.",
            "objectivesIntroduced": ["obj_a2_80_02_tailoring_alterations_lexicon"],
            "objectivesPracticed": ["obj_a2_80_01_collective_approximate_numerals"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_numerals_collective_approximate"],
            "grammarReviewed": ["gram_a1_case_genitive_possession", "gram_a1_spatial_postpositions_deeree_door"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_consonant_clusters"], "phonologyReviewed": ["phono_a1_vowel_reduction_non_initial"],
            "communicativeFunctionsIntroduced": ["comm_a2_02_describing_appearance_clothing"],
            "communicativeFunctionsPracticed": ["comm_a1_22_making_purchases"], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_clothing_fashion", "lex_domain_crafts_artisans"],
            "previousVocabularyReused": ["дээл", "хэмжээ", "оёх", "богино", "урт", "газар"],
            "readingObjective": "Read tailor atelier alteration pricelists (өмдний шуумаг хасах, цахилгаан солих, зах янзлах).",
            "listeningObjective": "Understand tailor taking bodily measurements aloud (мөр, цээжний тойрог, ханцуйны урт).",
            "writingObjective": "List 5 essential components of a Mongolian deel with Cyrillic anatomical terms.",
            "spokenProductionObjective": "Explain an alteration request: 'Энэ өмдний шуумгийг гурван сантиметр хасаад өгөөч'.",
            "registerTarget": "Artisanal craftsmanship consultation register",
            "pragmaticTarget": "Understanding traditional deel anatomy (энгэр, нударга, хажлага) with cultural appreciation.",
            "prerequisiteLessonIds": ["les_a2_80_01_collective_approximate_numerals_intro"],
            "reviewsLessonIds": ["les_a1_22_02_clothing_colors_shopping"],
            "reviewsUnitIds": ["unit_a1_22_shopping_transactions_making_purch"],
            "reviewReason": "Expands commercial clothing terms to bespoke craftsmanship and tailoring.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Pronounce traditional garment component terminology accurately.",
            "successCriteria": [
                "Identifies key parts of a deel: энгэр (flap/lapel), зах (collar), нударга (cuffs), бүс (sash)",
                "Uses alteration verbs accurately: хасах (shorten), танах (take in), өргөсгөх (let out)"
            ],
            "masteryEvidence": "Accurately labels 6 parts of a traditional deel and explains 2 alteration requests.",
            "recommendedExerciseModalities": ["categorization", "matching", "contextual_cloze"]
        },
        {
            "lessonId": "les_a2_80_03_tailor_consultation_dialogue",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 3,
            "title": "Fitting Session: Ordering a Custom Deel for Naadam",
            "lessonType": "dialogue_work",
            "primaryPurpose": "Develop spoken conversational fluency for custom garment ordering: selecting silk and lining fabrics, agreeing on completion deadlines, and scheduling fittings.",
            "communicativeOutcome": "Order a custom-made deel at an atelier: choose fabric, discuss design details, establish pickup date, and pay deposit.",
            "objectivesIntroduced": ["obj_a2_80_03_custom_tailoring_dialogue"],
            "objectivesPracticed": ["obj_a2_80_01_collective_approximate_numerals", "obj_a2_80_02_tailoring_alterations_lexicon"],
            "objectivesReviewed": ["obj_a1_20_01_expressing_intentions"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_numerals_collective_approximate"],
            "grammarReviewed": ["gram_a1_verb_tense_future_prospective_na", "gram_a1_verb_imperative_polite_aarai"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_intonation_polite"], "phonologyReviewed": ["phono_a1_diphthongs"],
            "communicativeFunctionsIntroduced": ["comm_a2_02_describing_appearance_clothing"],
            "communicativeFunctionsPracticed": ["comm_a1_22_making_purchases"],
            "communicativeFunctionsReviewed": ["comm_a1_16_greetings_time_of_day"],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_clothing_fashion", "lex_domain_crafts_artisans"],
            "previousVocabularyReused": ["захиалах", "торго", "өнгө", "бэлэн", "болох", "тооцоо"],
            "readingObjective": "",
            "listeningObjective": "Understand tailor explaining preparation timeline: 'Наадмаас өмнө бэлэн болно, гэхдээ ирэх долоо хоногт нэг удаа өмсөж үзээрэй'.",
            "writingObjective": "",
            "spokenProductionObjective": "Place custom order: 'Би энэ ногоон торгоор дан дээл оёулмаар байна. Нударгыг нь торгон хажлагаар эмжээрэй'.",
            "registerTarget": "Artisanal respectful service register",
            "pragmaticTarget": "Establishing realistic craftsmanship timelines ahead of major national holiday surges.",
            "prerequisiteLessonIds": ["les_a2_80_02_tailoring_measurements_alterations_lexicon"],
            "reviewsLessonIds": ["les_a1_49_01_polite_imperative_aarai"],
            "reviewsUnitIds": ["unit_a1_49_polite_request_imperative_suffixes_"],
            "reviewReason": "Utilizes polite request imperatives (-аарай/-ээрэй) in tailoring instructions.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Authentic dialogue between seasoned Mongolian tailor and client measuring up for Naadam.",
            "successCriteria": [
                "Communicates design specifications clearly using traditional garment terms",
                "Confirms fitting appointment date and deposit amount"
            ],
            "masteryEvidence": "Conducts a 5-turn custom tailoring consultation with complete clarity.",
            "recommendedExerciseModalities": ["role-play response", "dialogue_completion", "listening_comprehension"]
        },
        {
            "lessonId": "les_a2_80_04_atelier_acoustic_measurements_listening",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 4,
            "title": "Acoustic Lab: Tailor's Studio Murmurs & Measurement Dictation",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop acoustic listening comprehension of tailor studio interactions: measuring tape callouts, fabric cutting scissors, sewing machine ambiance, and alteration notes.",
            "communicativeOutcome": "Transcribe numeric measurements called out by a tailor to an apprentice (waist, sleeve, chest in centimeters).",
            "objectivesIntroduced": ["obj_a2_80_04_decode_tailor_measurements"],
            "objectivesPracticed": ["obj_a2_80_02_tailoring_alterations_lexicon"], "objectivesReviewed": ["obj_a1_27_01_counting_tens_hundreds"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_numerals_cardinal_counting", "gram_a1_case_genitive_possession"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_vowel_reduction_non_initial"], "phonologyReviewed": ["phono_a1_nasal_vowels"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_02_describing_appearance_clothing"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_clothing_fashion", "lex_domain_measurements_quantities"],
            "previousVocabularyReused": ["хэмжээ", "сантиметр", "урт", "өргөн", "бичих", "тойрог"],
            "readingObjective": "",
            "listeningObjective": "Accurately write down 5 numerical measurements called out rapidly in a working tailoring atelier.",
            "writingObjective": "",
            "spokenProductionObjective": "Read back the dictated measurements to verify accuracy.",
            "registerTarget": "High-speed workshop professional dictation register",
            "pragmaticTarget": "Auditory precision parsing measurements in a busy artisan workshop environment.",
            "prerequisiteLessonIds": ["les_a2_80_02_tailoring_measurements_alterations_lexicon"],
            "reviewsLessonIds": ["les_a1_27_02_listening_measurements"],
            "reviewsUnitIds": ["unit_a1_27_cardinal_numbers_counting_up_to_one"],
            "reviewReason": "Applies number dictation listening skills to professional tailoring metrics.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Sewing machine whir, fabric shears snip, and clear rhythmic measurement dictation.",
            "successCriteria": [
                "Transcribes all 5 anatomical measurement figures without numerical error",
                "Associates each measurement with correct body location (ханцуй, бэлхүүс, мөр)"
            ],
            "masteryEvidence": "Fills in complete tailor measurement order card with 100% numerical accuracy.",
            "recommendedExerciseModalities": ["listening_comprehension", "dictation", "phonetic_discrimination"]
        },
        {
            "lessonId": "les_a2_80_05_tailoring_order_receipt_writing",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 5,
            "title": "Custom Order Specification: Drafting a Tailoring Work Order",
            "lessonType": "grammar_guided_practice",
            "primaryPurpose": "Synthesize collective/approximate numerals, deel anatomy vocabulary, and alteration verbs in a written bespoke tailoring work order.",
            "communicativeOutcome": "Draft a written custom order specification for a family set of festival deels, specifying silk meterage, lining type, and deadline.",
            "objectivesIntroduced": ["obj_a2_80_05_write_tailoring_order"],
            "objectivesPracticed": ["obj_a2_80_01_collective_approximate_numerals", "obj_a2_80_02_tailoring_alterations_lexicon"],
            "objectivesReviewed": ["obj_a1_50_01_sequential_converb"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_numerals_collective_approximate"],
            "grammarReviewed": ["gram_a1_case_instrumental_transport_language", "gram_a1_case_genitive_possession"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_02_describing_appearance_clothing"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_clothing_fashion", "lex_domain_crafts_artisans"],
            "previousVocabularyReused": ["захиалга", "хугацаа", "дээл", "торго", "үнэ", "хүлээж авах"],
            "readingObjective": "Review authentic atelier order forms to understand standardized layout.",
            "listeningObjective": "",
            "writingObjective": "Draft a written order specification including fabric meters, collective participants, design notes, and delivery date.",
            "spokenProductionObjective": "",
            "registerTarget": "Artisanal commercial work order register",
            "pragmaticTarget": "Ensuring all bespoke specifications and approximate meterages are documented unambiguously.",
            "prerequisiteLessonIds": ["les_a2_80_03_tailor_consultation_dialogue", "les_a2_80_04_atelier_acoustic_measurements_listening"],
            "reviewsLessonIds": ["les_a1_50_01_sequential_converb_aad"],
            "reviewsUnitIds": ["unit_a1_50_sequential_converb_clause_connector"],
            "reviewReason": "Uses sequential converbs to structure fabrication and fitting milestones.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Audio read-back of written tailoring specification.",
            "successCriteria": [
                "Produces written order including approximate quantity suffix (-аад) and collective numeral (-уул)",
                "Accurately documents deel components: зах, энгэр, нударга, дотор"
            ],
            "masteryEvidence": "Drafts 'Бид гурвуул Наадмаар өмсөх дээл захиаллаа. Нийт гучаад метр торго орно...' accurately.",
            "recommendedExerciseModalities": ["short-answer writing", "sentence construction", "error correction"]
        }
    ])

    # =========================================================================
    # UNIT 81: Cashmere Shopping & Wool Grade Certification (pos 81)
    # 4 Lessons | Targets: ProdLem=19, RecLem=9, ProdExp=5, RecExp=3
    # Budget: (7,3,2,1), (5,3,1,1), (0,0,0,0), (7,3,2,1) = (19, 9, 5, 3)
    # =========================================================================
    u = u_map[81]
    uid = u["unitId"]
    lessons.extend([
        {
            "lessonId": "les_a2_81_01_cashmere_ply_fiber_certification_lexicon",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 1,
            "title": "Gobi Cashmere: Fiber Micron, Ply & Quality Grades",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Introduce premium wool and cashmere terminology (ноолуур, сарлагийн хөөвөр, тэмээний ноос, утсан утас/ply, микрон, баталгааны гэрчилгээ).",
            "communicativeOutcome": "Distinguish between goat cashmere, yak down, and camel wool; inquire about yarn thickness (1-ply vs 2-ply) and organic certification.",
            "objectivesIntroduced": ["obj_a2_81_01_cashmere_fiber_lexicon"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_a2_80_01_collective_approximate_numerals"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_noun_phrase_attributive_adjective", "gram_a1_case_genitive_possession"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_consonant_clusters"], "phonologyReviewed": ["phono_a1_long_vowels"],
            "communicativeFunctionsIntroduced": ["comm_a2_24_superlative_best_in_town"],
            "communicativeFunctionsPracticed": ["comm_a2_23_comparing_items_places"], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 7, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_clothing_fashion", "lex_domain_commerce_transactions"],
            "previousVocabularyReused": ["ноос", "цамц", "дулаан", "зөөлөн", "үнэ", "үйлдвэр"],
            "readingObjective": "Read hangtags on cashmere garments specifying micron count, fiber purity (100% цэвэр ноолуур), and wash care.",
            "listeningObjective": "Understand cashmere brand showroom presentation on nomadic sustainable shearing.",
            "writingObjective": "List 3 distinctive natural wool fibers of Mongolia and their thermal qualities.",
            "spokenProductionObjective": "Ask sales specialist: 'Энэ цамц 100 хувь ямааны ноолуур уу, эсвэл сарлагийн хөөвөртэй хольсон уу?'.",
            "registerTarget": "Specialized luxury textile retail register",
            "pragmaticTarget": "Appreciating the distinction between raw nomadic fibers and industrial blends.",
            "prerequisiteLessonIds": ["les_a2_80_01_collective_approximate_numerals_intro"],
            "reviewsLessonIds": ["les_a1_22_01_making_purchases_intro"],
            "reviewsUnitIds": ["unit_a1_22_shopping_transactions_making_purch"],
            "reviewReason": "Expands general retail vocabulary into iconic Mongolian luxury export industries.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Pronounce technical textile terms clearly.",
            "successCriteria": [
                "Distinguishes ноолуур (cashmere), сарлагийн хөөвөр (yak down), and тэмээний ноос (camel wool)",
                "Identifies fiber purity markings (100% цэвэр, холимог)"
            ],
            "masteryEvidence": "Accurately defines 7 luxury textile terms and explains differences in thermal softness.",
            "recommendedExerciseModalities": ["categorization", "contextual_cloze", "matching"]
        },
        {
            "lessonId": "les_a2_81_02_cashmere_certificate_label_reading",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 2,
            "title": "Deciphering Cashmere Certificates, Export Seals & Care Tags",
            "lessonType": "reading_development",
            "primaryPurpose": "Develop reading comprehension for authentic export certificates (Чанартай ноолуурын гэрчилгээ), origin stamps, eco-certifications, and specialized care instructions.",
            "communicativeOutcome": "Inspect cashmere tags to confirm genuine Mongolian origin, hand-wash temperature limits, and anti-pilling guarantees.",
            "objectivesIntroduced": ["obj_a2_81_02_read_cashmere_certifications"],
            "objectivesPracticed": ["obj_a2_81_01_cashmere_fiber_lexicon"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_ablative_origin", "gram_a1_predicate_adjective_nominal"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_24_superlative_best_in_town"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_clothing_fashion", "lex_domain_commerce_transactions"],
            "previousVocabularyReused": ["гэрчилгээ", "чанар", "угаах", "цэвэрлэх", "халуун", "хориглох"],
            "readingObjective": "Extract fiber micron thickness, washing temperature (30°C гараар угаах), and origin verification from a garment booklet.",
            "listeningObjective": "",
            "writingObjective": "Transcribe proper care steps for luxury knitwear into a home memo.",
            "spokenProductionObjective": "Explain to a peer how to wash a pure cashmere cardigan without shrinking it.",
            "registerTarget": "Technical product labeling and certification register",
            "pragmaticTarget": "Heeding non-ironing and hand-wash icons to protect delicate protein fibers.",
            "prerequisiteLessonIds": ["les_a2_81_01_cashmere_ply_fiber_certification_lexicon"],
            "reviewsLessonIds": ["les_a1_40_01_ablative_origin_intro"],
            "reviewsUnitIds": ["unit_a1_40_ablative_of_spatial_temporal_origin"],
            "reviewReason": "Utilizes ablative case of origin ('Монголоос гаралтай', 'ямаанаас самнасан').",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Read garment care tags aloud with precise pronunciation.",
            "successCriteria": [
                "Locates washing and drying restrictions accurately on Mongolian textile tag",
                "Verifies whether item is certified 100% Mongolian organic cashmere"
            ],
            "masteryEvidence": "Answers 4 comprehension questions based on an authentic Gobi Cashmere certification booklet.",
            "recommendedExerciseModalities": ["reading_comprehension", "contextual_cloze", "categorization"]
        },
        {
            "lessonId": "les_a2_81_03_cashmere_showroom_tour_listening",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 3,
            "title": "Acoustic Lab: Cashmere Showroom Tour & Gift Consultation",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop acoustic comprehension of showroom sales consultants guiding high-end shoppers through fiber collections, seasonal colors, and export packaging.",
            "communicativeOutcome": "Understand consultant recommendations regarding weight (нимгэн зуны ноолуур vs зузаан өвлийн сүлжмэл), natural dye-free shades, and tax-free export forms.",
            "objectivesIntroduced": ["obj_a2_81_03_decode_cashmere_consultation"],
            "objectivesPracticed": ["obj_a2_81_01_cashmere_fiber_lexicon"], "objectivesReviewed": ["obj_a2_77_01_enclitic_ni_marking"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a2_possessive_third_person_enclitic_ni", "gram_a1_converb_coordinating_j_ch"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_vowel_reduction_non_initial"], "phonologyReviewed": ["phono_a1_nasal_vowels"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_24_superlative_best_in_town"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_clothing_fashion", "lex_domain_commerce_transactions"],
            "previousVocabularyReused": ["өнгө", "будаггүй", "байгалийн", "хөнгөн", "дулаан", "бэлэг"],
            "readingObjective": "",
            "listeningObjective": "Identify natural dye-free colors (цагаан, шаргал, саарал, хөх саарал) and knit weights from consultant audio.",
            "writingObjective": "",
            "spokenProductionObjective": "Explain to a travel companion why natural un-dyed cashmere is softer.",
            "registerTarget": "Polished luxury boutique consultation register",
            "pragmaticTarget": "Understanding sustainability and chemical-free dyeing advantages.",
            "prerequisiteLessonIds": ["les_a2_81_01_cashmere_ply_fiber_certification_lexicon"],
            "reviewsLessonIds": ["les_a1_73_03_mall_promotions_listening"],
            "reviewsUnitIds": ["unit_a2_73_department_stores_shopping_mall_nav"],
            "reviewReason": "Elevates retail store listening to high-end specialist boutique guidance.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Elegant, gentle boutique consultant voice with soft ambient showroom background.",
            "successCriteria": [
                "Identifies the 4 natural un-dyed cashmere colors mentioned in audio",
                "Extracts tax-free refund (НӨАТ буцаан олголт) procedure explained by consultant"
            ],
            "masteryEvidence": "Accurately maps out consultant's product recommendations across 3 customer profiles.",
            "recommendedExerciseModalities": ["listening_comprehension", "phonetic_discrimination", "categorization"]
        },
        {
            "lessonId": "les_a2_81_04_cashmere_boutique_purchasing_dialogue",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 4,
            "title": "Boutique Encounter: Selecting Cashmere Gifts & Requesting Tax-Free",
            "lessonType": "dialogue_work",
            "primaryPurpose": "Master spoken communication in a premier cashmere boutique: comparing sweater weaves, selecting scarves as gifts, requesting gift boxes, and completing tax-free forms.",
            "communicativeOutcome": "Purchase cashmere knitwear, compare yarn weights, request gift packaging, and obtain a tax refund receipt.",
            "objectivesIntroduced": ["obj_a2_81_04_cashmere_shopping_dialogue"],
            "objectivesPracticed": ["obj_a2_81_01_cashmere_fiber_lexicon", "obj_a2_81_02_read_cashmere_certifications"],
            "objectivesReviewed": ["obj_a1_22_01_making_purchases"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_verb_imperative_polite_aarai", "gram_a1_case_instrumental_transport_language"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_intonation_polite"], "phonologyReviewed": ["phono_a1_vowel_length_distinction"],
            "communicativeFunctionsIntroduced": ["comm_a2_24_superlative_best_in_town"],
            "communicativeFunctionsPracticed": ["comm_a1_22_making_purchases"],
            "communicativeFunctionsReviewed": ["comm_a1_16_greetings_time_of_day"],
            "newProductiveLemmaTarget": 7, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_clothing_fashion", "lex_domain_commerce_transactions"],
            "previousVocabularyReused": ["ороолт", "бэлэг", "хайрцаг", "баримт", "боох", "карт"],
            "readingObjective": "",
            "listeningObjective": "Understand cashier explaining tax refund kiosk at Chinggis Khaan International Airport.",
            "writingObjective": "",
            "spokenProductionObjective": "Purchase items: 'Энэ байгалийн шаргал өнгийн ноолууран ороолтыг бэлгийн хайрцагт хийгээд, татварын буцаан олголтын баримт бичиж өгөөч'.",
            "registerTarget": "Refined commercial transaction register",
            "pragmaticTarget": "Requesting export documentation and proper gift packaging politely.",
            "prerequisiteLessonIds": ["les_a2_81_02_cashmere_certificate_label_reading", "les_a2_81_03_cashmere_showroom_tour_listening"],
            "reviewsLessonIds": ["les_a1_22_05_making_purchases_simulation"],
            "reviewsUnitIds": ["unit_a1_22_shopping_transactions_making_purch"],
            "reviewReason": "Synthesizes advanced retail purchasing with export formalities.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Polite native speaker showroom dialogue with authentic transaction pacing.",
            "successCriteria": [
                "Conducts a complete purchase specifying natural fiber type and requesting gift wrapping",
                "Requests and verifies tax refund document (НӨАТ буцаан олголт)"
            ],
            "masteryEvidence": "Completes a 5-turn showroom transaction roleplay with complete linguistic accuracy.",
            "recommendedExerciseModalities": ["role-play response", "dialogue_completion", "listening_comprehension"]
        }
    ])

    # =========================================================================
    # UNIT 82: Retail & Service Transaction Capstone (pos 82)
    # 5 Lessons | Targets: ProdLem=24, RecLem=12, ProdExp=8, RecExp=4
    # Budget: (10,5,3,2), (0,0,0,0), (8,4,3,1), (6,3,2,1), (0,0,0,0) = (24, 12, 8, 4)
    # =========================================================================
    u = u_map[82]
    uid = u["unitId"]
    lessons.extend([
        {
            "lessonId": "les_a2_82_01_consumer_rights_service_disputes_lexicon",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 1,
            "title": "Consumer Rights: Exchanges, Returns & Defective Merchandise",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Introduce high-level consumer protection vocabulary (хэрэглэгчийн эрх, буцаалт, бараа солих, гэмтэлтэй бараа, төлбөр буцаах, гомдол гаргах) to resolve retail disputes.",
            "communicativeOutcome": "Explain consumer rights, request a replacement for a defective product, or demand a refund in compliance with consumer law.",
            "objectivesIntroduced": ["obj_a2_82_01_consumer_rights_lexicon"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_a2_79_01_conditional_converb_val", "obj_a2_77_01_enclitic_ni_marking"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_converb_conditional_val", "gram_a2_possessive_third_person_enclitic_ni"],
            "grammarReviewed": ["gram_a1_converb_sequential_aad"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_consonant_clusters"], "phonologyReviewed": ["phono_a1_vowel_reduction_non_initial"],
            "communicativeFunctionsIntroduced": ["comm_a2_23_comparing_items_places", "comm_a2_24_superlative_best_in_town"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 10, "newReceptiveLemmaTarget": 5, "newProductiveExpressionTarget": 3, "newReceptiveExpressionTarget": 2,
            "lexicalDomains": ["lex_domain_commerce_transactions", "lex_domain_civic_administrative"],
            "previousVocabularyReused": ["бараа", "мөнгө", "буцаах", "солих", "гомдол", "баримт"],
            "readingObjective": "Read consumer protection regulations regarding 14-day return policies for non-perishable goods.",
            "listeningObjective": "Understand customer service representative explaining exchange criteria.",
            "writingObjective": "List 4 valid grounds for returning merchandise under Mongolian consumer law.",
            "spokenProductionObjective": "Explain a consumer complaint: 'Энэ бараа гэмтэлтэй гарсан тул солих эсвэл мөнгийг нь буцааж авмаар байна'.",
            "registerTarget": "Assertive polite administrative consumer register",
            "pragmaticTarget": "Advocating for consumer rights calmly and firmly with legal and policy terminology.",
            "prerequisiteLessonIds": ["les_a2_79_01_conditional_converb_val_intro", "les_a2_80_01_collective_approximate_numerals_intro", "les_a2_81_01_cashmere_ply_fiber_certification_lexicon"],
            "reviewsLessonIds": ["les_a1_63_06_elementary_stage_synthesis_capstone"],
            "reviewsUnitIds": ["unit_a1_63_a1_comprehensive_review_checkpoint_c"],
            "reviewReason": "Synthesizes retail vocabulary into assertive intermediate consumer autonomy.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Pronounce formal consumer protection and legal terms.",
            "successCriteria": [
                "Defines гомдол (complaint), буцаалт (refund/return), гэмтэл (defect), хууль (law)",
                "Forms conditional sentences expressing return requirements: 'Баримт нь байвал буцаана'"
            ],
            "masteryEvidence": "Articulates a clear 3-point explanation of consumer return conditions in Mongolian.",
            "recommendedExerciseModalities": ["categorization", "contextual_cloze", "sentence_construction"]
        },
        {
            "lessonId": "les_a2_82_02_consumer_service_acoustic_decoding_lab",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 2,
            "title": "Acoustic Lab: Customer Service Disputes & Resolution Audio",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop acoustic listening comprehension of intense multi-speaker customer service disputes, manager interventions, and policy compromise solutions.",
            "communicativeOutcome": "Follow a multi-speaker debate between an upset customer, a sales clerk, and a department manager to identify the root cause and eventual settlement.",
            "objectivesIntroduced": ["obj_a2_82_02_decode_customer_disputes"],
            "objectivesPracticed": ["obj_a2_82_01_consumer_rights_lexicon"], "objectivesReviewed": ["obj_a2_79_03_decode_market_bargaining_audio"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a2_verb_past_recent_witnessed_laa", "gram_a2_converb_conditional_val"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_vowel_reduction_non_initial"], "phonologyReviewed": ["phono_a1_nasal_vowels"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_23_comparing_items_places"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_commerce_transactions"],
            "previousVocabularyReused": ["менежер", "солих", "гомдол", "мөнгө", "өгөх", "зөв"],
            "readingObjective": "",
            "listeningObjective": "Comprehend a 2-minute customer service dispute regarding a faded coat, extracting whether a refund or replacement was agreed.",
            "writingObjective": "",
            "spokenProductionObjective": "Summarize the manager's resolution to a partner.",
            "registerTarget": "Tense conversational conflict resolution register",
            "pragmaticTarget": "Parsing emotional, fast-paced dialogue and separating emotional complaints from contractual facts.",
            "prerequisiteLessonIds": ["les_a2_82_01_consumer_rights_service_disputes_lexicon"],
            "reviewsLessonIds": ["les_a1_63_03_auditory_comprehension_lab"],
            "reviewsUnitIds": ["unit_a1_63_a1_comprehensive_review_checkpoint_c"],
            "reviewReason": "Elevates listening stamina to multi-speaker conflict scenarios.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Realistic 2-minute customer service desk audio featuring frustrated buyer and calm manager.",
            "successCriteria": [
                "Identifies root issue (torn seam / incorrect sizing / lack of original box)",
                "Extracts final outcome (immediate replacement with valid receipt)"
            ],
            "masteryEvidence": "Answers 6 comprehensive questions following a single hearing of the customer service audio.",
            "recommendedExerciseModalities": ["listening_comprehension", "sequencing", "categorization"]
        },
        {
            "lessonId": "les_a2_82_03_retail_policy_warranty_terms_reading",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 3,
            "title": "Deciphering Retail Return Policies & Warranty Agreements",
            "lessonType": "reading_development",
            "primaryPurpose": "Develop targeted reading comprehension of an authentic store return policy document, warranty booklet exclusions, and consumer complaint forms.",
            "communicativeOutcome": "Inspect store policy documentation to locate deadlines (7 хоног, 14 хоног), required condition (шошготой, өмсөөгүй), and non-refundable categories.",
            "objectivesIntroduced": ["obj_a2_82_03_read_return_policies"],
            "objectivesPracticed": ["obj_a2_82_01_consumer_rights_lexicon"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_ablative_origin", "gram_a1_spatial_postpositions_deeree_door"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_23_comparing_items_places"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 8, "newReceptiveLemmaTarget": 4, "newProductiveExpressionTarget": 3, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_commerce_transactions", "lex_domain_civic_administrative"],
            "previousVocabularyReused": ["журам", "шошго", "хугацаа", "баталгаа", "буцаах", "нөхцөл"],
            "readingObjective": "Extract return conditions from a 150-word official store policy brochure.",
            "listeningObjective": "",
            "writingObjective": "Summarize key consumer rights into a checklist for personal shopping trips.",
            "spokenProductionObjective": "Explain to a peer why intimate apparel or customized goods cannot be returned.",
            "registerTarget": "Commercial legal and administrative register",
            "pragmaticTarget": "Distinguishing mandatory statutory rights from voluntary merchant store policies.",
            "prerequisiteLessonIds": ["les_a2_82_01_consumer_rights_service_disputes_lexicon"],
            "reviewsLessonIds": ["les_a1_63_02_textual_synthesis_reading"],
            "reviewsUnitIds": ["unit_a1_63_a1_comprehensive_review_checkpoint_c"],
            "reviewReason": "Applies rigorous reading analysis to authentic retail contracts and policies.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Read administrative return conditions aloud.",
            "successCriteria": [
                "Identifies the 14-day statutory return deadline and proof-of-purchase requirement",
                "Determines which product categories are exempt from exchange"
            ],
            "masteryEvidence": "Scores 100% on a 5-question comprehension quiz based on an official store return charter.",
            "recommendedExerciseModalities": ["reading_comprehension", "contextual_cloze", "categorization"]
        },
        {
            "lessonId": "les_a2_82_04_customer_service_desk_simulation",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 4,
            "title": "Interactive Simulation: Resolving a Product Dispute at the Service Desk",
            "lessonType": "dialogue_work",
            "primaryPurpose": "Synthesize all spoken interaction capabilities developed across Section 2 in an unscripted multi-stage retail service desk simulation.",
            "communicativeOutcome": "Successfully resolve a complex retail dispute: present receipt, explain defect using 'нь' topic structures, negotiate exchange using conditional converb, and obtain replacement.",
            "objectivesIntroduced": ["obj_a2_82_04_simulate_retail_dispute_resolution"],
            "objectivesPracticed": ["obj_a2_82_01_consumer_rights_lexicon"],
            "objectivesReviewed": ["obj_a2_73_03_mall_inquiry_dialogue", "obj_a2_74_04_boutique_shopping_dialogue", "obj_a2_79_05_bargaining_negotiation_dialogue"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_possessive_third_person_enclitic_ni", "gram_a2_converb_conditional_val", "gram_a2_numerals_ordinal"],
            "grammarReviewed": ["gram_a2_reflexive_case_combinations"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_intonation_polite"], "phonologyReviewed": ["phono_a1_vowel_length_distinction"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_23_comparing_items_places", "comm_a2_24_superlative_best_in_town"],
            "communicativeFunctionsReviewed": ["comm_a1_13_apologies_politeness"],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_commerce_transactions"],
            "previousVocabularyReused": ["бараа", "баримт", "солих", "буцаах", "гэмтэл", "шийдэх"],
            "readingObjective": "",
            "listeningObjective": "Respond adaptively to dynamic situational hurdles introduced by the clerk (e.g. lost tags, manager approval needed).",
            "writingObjective": "",
            "spokenProductionObjective": "Conduct consecutive dialogue turns across 4 simulated service desk stages without reverting to English.",
            "registerTarget": "Spontaneous assertive diplomatic register",
            "pragmaticTarget": "Maintaining composure and polite firmness while navigating bureaucracy.",
            "prerequisiteLessonIds": ["les_a2_82_02_consumer_service_acoustic_decoding_lab", "les_a2_82_03_retail_policy_warranty_terms_reading"],
            "reviewsLessonIds": ["les_a1_63_05_interactive_checkpoint_simulation"],
            "reviewsUnitIds": ["unit_a1_63_a1_comprehensive_review_checkpoint_c"],
            "reviewReason": "Builds upon A1 capstone interactive simulations with higher situational complexity.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Provide responsive native speaker voice prompts for the interactive simulation.",
            "successCriteria": [
                "Presents return case clearly using receipt and appropriate legal terminology",
                "Negotiates acceptable replacement using conditional phrasing without escalating conflict"
            ],
            "masteryEvidence": "Completes full 4-stage simulation with zero communicative breakdowns.",
            "recommendedExerciseModalities": ["role-play response", "dialogue_completion", "sequencing"]
        },
        {
            "lessonId": "les_a2_82_05_retail_service_transaction_checkpoint",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 5,
            "title": "Benchmark Checkpoint: Retail Variety, Consumer Rights & Public Dining",
            "lessonType": "checkpoint",
            "primaryPurpose": "Formal milestone evaluation assessing productive and receptive mastery of Section 2: ordinal numerals, clothing fit, reflexive-possessive base (-аа4), fused case-reflexive endings, third-person enclitic 'нь', superlative 'хамгийн', conditional converb (-бал4/-вал4), collective/approximate numerals, and luxury textile trade.",
            "communicativeOutcome": "Demonstrate comprehensive communicative competence across all Section 2 commercial, retail, and artisanal domains without reference materials.",
            "objectivesIntroduced": [],
            "objectivesPracticed": ["obj_a2_82_01_consumer_rights_lexicon", "obj_a2_82_04_simulate_retail_dispute_resolution"],
            "objectivesReviewed": ["obj_a2_73_01_ordinal_numeral_derivation", "obj_a2_75_01_reflexive_possessive_marking", "obj_a2_76_01_reflexive_case_combination", "obj_a2_77_01_enclitic_ni_marking", "obj_a2_78_01_superlative_comparative_adverbs", "obj_a2_79_01_conditional_converb_val", "obj_a2_80_01_collective_approximate_numerals"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_numerals_ordinal", "gram_a2_reflexive_possessive_base", "gram_a2_reflexive_case_combinations", "gram_a2_possessive_third_person_enclitic_ni", "gram_a2_converb_conditional_val", "gram_a2_numerals_collective_approximate"],
            "grammarReviewed": ["gram_a1_case_ablative_comparative"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_intonation_polite"], "phonologyReviewed": ["phono_a1_vowel_length_distinction"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_23_comparing_items_places", "comm_a2_24_superlative_best_in_town", "comm_a1_23_bargaining_clarifying_price", "comm_a2_02_describing_appearance_clothing"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_commerce_transactions", "lex_domain_clothing_fashion"],
            "previousVocabularyReused": ["дэлгүүр", "хувцас", "зах", "ноолуур", "хямдрал", "баталгаа"],
            "readingObjective": "Demonstrate unassisted comprehension of an authentic consumer warranty dispute case study.",
            "listeningObjective": "Demonstrate unassisted comprehension of an authentic high-speed retail transaction debate.",
            "writingObjective": "Draft a formal written consumer complaint and request for exchange or refund.",
            "spokenProductionObjective": "Conduct a live spoken negotiation resolving a complex commercial purchase complication.",
            "registerTarget": "Standard formal evaluation register",
            "pragmaticTarget": "Demonstrating holistic linguistic control and situational independence in commercial life.",
            "prerequisiteLessonIds": ["les_a2_82_04_customer_service_desk_simulation"],
            "reviewsLessonIds": ["les_a2_73_05_mall_directory_memo_writing", "les_a2_74_05_garment_review_tag_reading_writing", "les_a2_75_05_festival_wardrobe_essay_writing", "les_a2_76_06_personal_journey_written_memoir", "les_a2_77_05_comparative_product_review_writing", "les_a2_78_04_recommending_best_spots_dialogue", "les_a2_79_06_market_bargaining_summary_writing", "les_a2_80_05_tailoring_order_receipt_writing", "les_a2_81_04_cashmere_boutique_purchasing_dialogue"],
            "reviewsUnitIds": ["unit_a2_73_department_stores_shopping_mall_nav", "unit_a2_74_clothing_sizes_fabrics_fitting_room", "unit_a2_75_reflexive_possessive_base_suffixes_", "unit_a2_76_reflexive_case_combinations_", "unit_a2_77_third_person_possessive_enclitic_th", "unit_a2_78_comparative_superlative_vs_", "unit_a2_79_open_air_market_bargaining_at_naran", "unit_a2_80_tailoring_traditional_deel_alterati", "unit_a2_81_cashmere_shopping_wool_grade_certif"],
            "reviewReason": "Milestone synthesis certifying learner readiness to proceed to Section 3 health, domestic life, and civic services.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Deliver high-fidelity audio stimuli for formal benchmark assessment items.",
            "successCriteria": [
                "Demonstrates mastery of ordinal numerals, reflexive combinations, 'нь' enclitic, and conditional converbs in context",
                "Completes receptive and productive tasks across all 4 skill modalities without communicative breakdown"
            ],
            "masteryEvidence": "Successfully navigates all 4 benchmark assessment modalities achieving independent task completion.",
            "recommendedExerciseModalities": ["reading_comprehension", "listening_comprehension", "role-play response", "short-answer writing"]
        }
    ])

    return lessons
