"""
Section 1 Generator Part 2 (Units 67 - 69): 16 Lessons
67: Pedestrian Wayfinding (6 lessons)
68: Transit Delays & Traffic (5 lessons)
69: Postal & Courier Services (5 lessons)
"""

import json
from typing import List, Dict, Any

def get_sec01_part2_lessons(u_map: Dict[int, Any]) -> List[Dict[str, Any]]:
    lessons: List[Dict[str, Any]] = []

    # =========================================================================
    # UNIT 67: Pedestrian Wayfinding & Landmark Relations (pos 67)
    # 6 Lessons | Targets: ProdLem=21, RecLem=10, ProdExp=5, RecExp=3
    # Budget: (4,2,1,1), (6,3,1,1), (5,2,2,1), (4,3,1,0), (0,0,0,0), (2,0,0,0) = (21, 10, 5, 3)
    # =========================================================================
    u = u_map[67]
    uid = u["unitId"]
    lessons.extend([
        {
            "lessonId": "les_a2_67_01_comparative_adverbials_postpositions",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 1,
            "title": "Like and Similar To: Comparative Adverbials (Шиг, Адил, Мэт)",
            "lessonType": "grammar_introduction",
            "primaryPurpose": "Introduce comparative adverbials and postpositions (шиг, адил, мэт) to describe landmarks, visual likeness, and relative scale.",
            "communicativeOutcome": "Describe building landmarks by analogy (e.g. 'Тэр барилга цамхаг шиг харагдана', 'Номын сангийн адил том байшин').",
            "objectivesIntroduced": ["obj_a2_67_01_comparative_particles"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_a2_65_01_directional_suffix_marking"],
            "grammarIntroduced": ["gram_a2_adverbial_comparative_shig_adil_met"],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_ablative_comparative", "gram_a1_spatial_postpositions_deeree_door"],
            "phonologyIntroduced": ["phono_a2_postposition_clitic_stress"],
            "phonologyPracticed": ["phono_a1_vowel_length_distinction"], "phonologyReviewed": ["phono_a1_masculine_feminine_harmony"],
            "communicativeFunctionsIntroduced": ["comm_a2_17_giving_multistep_directions"],
            "communicativeFunctionsPracticed": ["comm_a2_23_comparing_items_places"], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 4, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_spatial_relations", "lex_domain_city_urban_life"],
            "previousVocabularyReused": ["том", "жижиг", "өндөр", "барилга", "харагдах", "адилхан"],
            "readingObjective": "Read tourist blurbs describing Ulaanbaatar architecture using visual analogies (Blue Sky Tower like a sail).",
            "listeningObjective": "Recognize comparative particles (шиг/адил) when pedestrians describe building facades.",
            "writingObjective": "Write 3 comparative sentences identifying buildings by resemblance.",
            "spokenProductionObjective": "Explain to a visitor: 'Тэр хөх шилтэй байшин Blue Sky шиг харагдаж байна'.",
            "registerTarget": "Descriptive conversational register",
            "pragmaticTarget": "Using vivid visual metaphors to make wayfinding cues memorable.",
            "prerequisiteLessonIds": ["les_a2_65_01_directional_case_micro_turns"],
            "reviewsLessonIds": ["les_a1_40_01_ablative_origin_intro"],
            "reviewsUnitIds": ["unit_a1_40_ablative_of_spatial_temporal_origin"],
            "reviewReason": "Complements the ablative of comparison from A1 with postpositional comparative constructions.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Model clitic-like prosodic integration of 'шиг' after nominal phrases.",
            "successCriteria": [
                "Distinguishes syntactic use of 'шиг' (postpositional) vs 'адил' (independent adverbial)",
                "Forms well-formed comparative descriptive phrases identifying visual landmarks"
            ],
            "masteryEvidence": "Produces 'Энэ өндөр барилга нь цирк шиг дугуй оройтой' correctly.",
            "recommendedExerciseModalities": ["sentence_construction", "categorization", "contextual_cloze"]
        },
        {
            "lessonId": "les_a2_67_02_urban_spatial_landmarks_lexicon",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 2,
            "title": "Alleyways, Squares & Underpasses: Urban Topography",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Introduce spatial vocabulary for navigating pedestrian zones, subterranean underpasses (нүхэн гарц), alleys, and monumental statues.",
            "communicativeOutcome": "Name and recognize complex pedestrian infrastructure, crosswalks, traffic circles, and public statues.",
            "objectivesIntroduced": ["obj_a2_67_02_pedestrian_infrastructure_lexicon"],
            "objectivesPracticed": ["obj_a2_67_01_comparative_particles"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_adverbial_comparative_shig_adil_met"],
            "grammarReviewed": ["gram_a1_case_dative_locative_location", "gram_a1_case_instrumental_transport_language"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_consonant_clusters"], "phonologyReviewed": ["phono_a1_vowel_reduction_non_initial"],
            "communicativeFunctionsIntroduced": ["comm_a2_17_giving_multistep_directions"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": ["comm_a1_19_inquiring_location"],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_city_urban_life", "lex_domain_spatial_relations"],
            "previousVocabularyReused": ["зам", "гудамж", "талбай", "хөшөө", "гарц", "хүн"],
            "readingObjective": "Read pedestrian directional signs on Peace Avenue directing foot traffic to underpasses.",
            "listeningObjective": "Understand street crossing safety announcements at pedestrian crossings.",
            "writingObjective": "List 6 pedestrian landmarks encountered on a daily walking route.",
            "spokenProductionObjective": "Describe a walking shortcut using alleyways and underground passageways.",
            "registerTarget": "Urban navigational informative register",
            "pragmaticTarget": "Accurate spatial precision in dense urban neighborhoods.",
            "prerequisiteLessonIds": ["les_a2_67_01_comparative_adverbials_postpositions"],
            "reviewsLessonIds": ["les_a1_61_02_postposition_dialogues"],
            "reviewsUnitIds": ["unit_a1_61_spatial_postpositions_"],
            "reviewReason": "Expands A1 spatial relational nouns to modern built environment vocabulary.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Pronounce compound spatial terms with stress on initial syllable.",
            "successCriteria": [
                "Accurately defines нүхэн гарц (underpass), явган хүний зам (sidewalk), уулзвар (crossroad)",
                "Uses newly introduced landmarks in locative sentences"
            ],
            "masteryEvidence": "Identifies and explains 5 pedestrian map symbols correctly in Mongolian.",
            "recommendedExerciseModalities": ["categorization", "contextual_cloze", "sentence_construction"]
        },
        {
            "lessonId": "les_a2_67_03_multistep_pedestrian_dialogue",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 3,
            "title": "Turn Past the Statues: Interactive Multi-Step Directions",
            "lessonType": "dialogue_work",
            "primaryPurpose": "Master asking for and executing multi-step pedestrian directions involving at least three spatial transitions.",
            "communicativeOutcome": "Ask a passerby how to walk to the State Department Store from Chinggis Square, confirming each intermediate landmark.",
            "objectivesIntroduced": ["obj_a2_67_03_multistep_wayfinding_dialogue"],
            "objectivesPracticed": ["obj_a2_67_01_comparative_particles", "obj_a2_67_02_pedestrian_infrastructure_lexicon"],
            "objectivesReviewed": ["obj_a1_49_01_polite_imperative"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_adverbial_comparative_shig_adil_met"],
            "grammarReviewed": ["gram_a1_converb_coordinating_j_ch", "gram_a1_verb_imperative_polite_aarai"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_intonation_polite"], "phonologyReviewed": ["phono_a1_diphthongs"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_17_giving_multistep_directions"],
            "communicativeFunctionsReviewed": ["comm_a1_19_inquiring_location"],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_city_urban_life", "lex_domain_spatial_relations"],
            "previousVocabularyReused": ["баруун", "зүүн", "чигээрээ", "алхах", "хүрэх", "булан"],
            "readingObjective": "",
            "listeningObjective": "Track a 3-step pedestrian route delivered in fast spontaneous speech by an Ulaanbaatar resident.",
            "writingObjective": "",
            "spokenProductionObjective": "Give 3 sequential walking instructions: 'Эхлээд чигээрээ алхаад, уулзвараар баруун тийш эргээд, банкны өмнүүр гараарай'.",
            "registerTarget": "Courteous pedestrian street exchange register",
            "pragmaticTarget": "Using active backchanneling ('Тэгээд цаашаа юу?', 'Аан, ойлголоо') to confirm direction comprehension.",
            "prerequisiteLessonIds": ["les_a2_67_02_urban_spatial_landmarks_lexicon"],
            "reviewsLessonIds": ["les_a1_42_01_coordinating_converb_intro"],
            "reviewsUnitIds": ["unit_a1_42_coordinating_converb_clause_linking"],
            "reviewReason": "Links sequential motion verbs using coordinating converbs (-ж/-ч).",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Deliver authentic multi-speaker dialogue recorded outdoors on a windy city street.",
            "successCriteria": [
                "Produces a coherent 3-clause instruction connecting sequential turns and landmarks",
                "Repeats back directions to confirm comprehension before departing"
            ],
            "masteryEvidence": "Guides interlocutor accurately from Sukhbaatar statue to the National Museum of Mongolia.",
            "recommendedExerciseModalities": ["role-play response", "dialogue_completion", "sequencing"]
        },
        {
            "lessonId": "les_a2_67_04_pedestrian_route_map_reading",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 4,
            "title": "Deciphering City Center Walking Maps & Heritage Trails",
            "lessonType": "reading_development",
            "primaryPurpose": "Develop reading skills for municipal walking tour brochures, monument plaques, and walking route legends.",
            "communicativeOutcome": "Read a historical downtown walking circuit map, identifying key architectural highlights and distance markers.",
            "objectivesIntroduced": ["obj_a2_67_04_read_walking_tour_maps"],
            "objectivesPracticed": ["obj_a2_67_02_pedestrian_infrastructure_lexicon"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_genitive_possession", "gram_a1_noun_phrase_attributive_adjective"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_17_giving_multistep_directions"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 4, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_city_urban_life", "lex_domain_geography_places"],
            "previousVocabularyReused": ["түүх", "соёл", "хөшөө", "байшин", "газар", "минут"],
            "readingObjective": "Read a 100-word historical walking trail brochure detailing distances, notable facades, and rest areas.",
            "listeningObjective": "",
            "writingObjective": "Annotate map landmarks with brief Cyrillic descriptive notes.",
            "spokenProductionObjective": "Explain to a companion which historical building is next on the walking trail.",
            "registerTarget": "Public educational tourist guide register",
            "pragmaticTarget": "Correlating printed text descriptions with geographic map symbols.",
            "prerequisiteLessonIds": ["les_a2_67_02_urban_spatial_landmarks_lexicon"],
            "reviewsLessonIds": ["les_a1_20_01_demonstratives_intro"],
            "reviewsUnitIds": ["unit_a1_20_demonstrative_deixis_"],
            "reviewReason": "Utilizes demonstratives (энэ, тэр) to point out features on printed city maps.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Narrate text excerpts from historical walking trail guide.",
            "successCriteria": [
                "Answers 4 detailed questions about walking distances and historical highlights from brochure",
                "Traces the walking path accurately based on textual instructions"
            ],
            "masteryEvidence": "Matches 5 historical descriptions to their corresponding map pins on an Ulaanbaatar city center map.",
            "recommendedExerciseModalities": ["reading_comprehension", "sequencing", "contextual_cloze"]
        },
        {
            "lessonId": "les_a2_67_05_ambient_street_directions_listening",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 5,
            "title": "Acoustic Wayfinding Lab: Parsing Directions in City Noise",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop focused acoustic decoding of rapid spoken directions against realistic ambient background noise of horns, wind, and footsteps.",
            "communicativeOutcome": "Extract exact turns, distance in meters, and destination landmarks from rapid street responses.",
            "objectivesIntroduced": ["obj_a2_67_05_decode_noisy_street_directions"],
            "objectivesPracticed": ["obj_a2_67_03_multistep_wayfinding_dialogue"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_spatial_postpositions_deeree_door"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_vowel_reduction_non_initial"], "phonologyReviewed": ["phono_a1_nasal_vowels"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_17_giving_multistep_directions"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_city_urban_life", "lex_domain_spatial_relations"],
            "previousVocabularyReused": ["метр", "эргэх", "явах", "гарц", "гэрлэн дохио", "булан"],
            "readingObjective": "",
            "listeningObjective": "Identify 3 distinct navigational checkpoints and final target from noisy street audio clips.",
            "writingObjective": "",
            "spokenProductionObjective": "Verify directions with interlocutor: 'Таны хэлснээр бол, гэрлэн дохиогоор зүүн эргэх үү?'.",
            "registerTarget": "Spontaneous colloquial public street speech",
            "pragmaticTarget": "Parsing reduced vowels and colloquial contractions in hurried urban speech.",
            "prerequisiteLessonIds": ["les_a2_67_03_multistep_pedestrian_dialogue"],
            "reviewsLessonIds": ["les_a1_25_03_locative_listening_comprehension"],
            "reviewsUnitIds": ["unit_a1_25_dative_locative_spatial_anchoring_s"],
            "reviewReason": "Tests locative discrimination under adverse acoustic conditions.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Realistic audio captured on Peace Avenue with traffic hum, footsteps, and wind noise.",
            "successCriteria": [
                "Identifies correct sequence of turns (left, straight, right) from 4 audio clips",
                "Extracts approximate walking distance (зуун метр, хоёр зуун метр) without text"
            ],
            "masteryEvidence": "Accurately maps out pedestrian route from audio recording without errors.",
            "recommendedExerciseModalities": ["listening_comprehension", "phonetic_discrimination", "sequencing"]
        },
        {
            "lessonId": "les_a2_67_06_written_wayfinding_guide_portfolio",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 6,
            "title": "Wayfinding Portfolio: Drafting Written Walking Directions",
            "lessonType": "grammar_guided_practice",
            "primaryPurpose": "Synthesize comparative particles, directional suffixes, spatial postpositions, and landmarks into a written guide for foreign guests.",
            "communicativeOutcome": "Draft written step-by-step walking instructions explaining how to walk from a major hotel to a traditional restaurant.",
            "objectivesIntroduced": ["obj_a2_67_06_draft_written_walking_guide"],
            "objectivesPracticed": ["obj_a2_67_01_comparative_particles", "obj_a2_67_02_pedestrian_infrastructure_lexicon"],
            "objectivesReviewed": ["obj_a1_50_01_sequential_clauses"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_adverbial_comparative_shig_adil_met"],
            "grammarReviewed": ["gram_a1_converb_sequential_aad", "gram_a2_case_directional_towards"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_17_giving_multistep_directions"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 2, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_city_urban_life", "lex_domain_communication_media"],
            "previousVocabularyReused": ["зочид буудал", "зоогийн газар", "алхах", "зам", "хүрэх", "харах"],
            "readingObjective": "Review a peer's draft walking instructions for clarity and landmark accuracy.",
            "listeningObjective": "",
            "writingObjective": "Compose an 8-sentence written pedestrian guide with sequential converbs (-аад) and comparative descriptions (шиг).",
            "spokenProductionObjective": "",
            "registerTarget": "Clear instructional written handbook register",
            "pragmaticTarget": "Ensuring foolproof navigational guidance for someone visiting the city for the first time.",
            "prerequisiteLessonIds": ["les_a2_67_03_multistep_pedestrian_dialogue", "les_a2_67_04_pedestrian_route_map_reading"],
            "reviewsLessonIds": ["les_a1_50_01_sequential_converb_aad"],
            "reviewsUnitIds": ["unit_a1_50_sequential_converb_clause_connector"],
            "reviewReason": "Utilizes sequential converb chains (-аад) to build multi-stage procedural directions.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Synthesize written text for self-audit.",
            "successCriteria": [
                "Writes a coherent sequential guide detailing at least 3 distinct turns and landmarks",
                "Correctly incorporates at least one comparative particle and one directional suffix"
            ],
            "masteryEvidence": "Produces complete written guide: 'Буудлаас гараад зүүн тийш алхаарай. Цамхаг шиг өндөр барилга өнгөрөөд...' flawlessly.",
            "recommendedExerciseModalities": ["short-answer writing", "sentence construction", "clause_combination"]
        }
    ])

    # =========================================================================
    # UNIT 68: Handling Transit Delays, Traffic Jams & Breakdowns (pos 68)
    # 5 Lessons | Targets: ProdLem=19, RecLem=9, ProdExp=5, RecExp=3
    # Budget: (4,2,1,1), (6,3,1,1), (0,0,0,0), (5,2,2,1), (4,2,1,0) = (19, 9, 5, 3)
    # =========================================================================
    u = u_map[68]
    uid = u["unitId"]
    lessons.extend([
        {
            "lessonId": "les_a2_68_01_witnessed_recent_past_transit",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 1,
            "title": "Immediate Incidents: The Witnessed Recent Past (-лаа/-лээ/-лоо/-лөө)",
            "lessonType": "grammar_introduction",
            "primaryPurpose": "Introduce the witnessed recent past tense suffix (-лаа4) to report immediate events, sudden delays, and newly observed breakdowns.",
            "communicativeOutcome": "Announce immediate occurrences in transit (e.g. 'Машин эвдэрлээ', 'Зам бөглөрлөө', 'Бид ирлээ').",
            "objectivesIntroduced": ["obj_a2_68_01_witnessed_past_immediate_events"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_a2_67_01_comparative_particles"],
            "grammarIntroduced": ["gram_a2_verb_past_recent_witnessed_laa"],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_verb_tense_past_witnessed_laa", "gram_a1_verb_tense_past_perfective_san"],
            "phonologyIntroduced": ["phono_a2_recent_past_vocalic_harmony"],
            "phonologyPracticed": ["phono_a1_masculine_feminine_harmony"], "phonologyReviewed": ["phono_a1_long_vowels"],
            "communicativeFunctionsIntroduced": ["comm_a2_19_taxi_hailing_fare_negotiation"],
            "communicativeFunctionsPracticed": ["comm_a1_17_describing_daily_routines"], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 4, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_transportation_travel", "lex_domain_actions_movement"],
            "previousVocabularyReused": ["ирлээ", "явлаа", "боллоо", "дууслаа", "машин", "зам"],
            "readingObjective": "Read real-time status notifications on transit apps announcing mechanical incidents and route diversions.",
            "listeningObjective": "Identify sudden event announcements marked with -лаа4 during commuter conversations.",
            "writingObjective": "Write 3 prompt updates using -лаа4 to describe sudden transit disruptions.",
            "spokenProductionObjective": "Exclaim sudden observations: 'Автобус ирлээ!', 'Зам дээр осол гарлаа!'.",
            "registerTarget": "Urgent immediate observational register",
            "pragmaticTarget": "Delivering timely situational alerts to traveling companions.",
            "prerequisiteLessonIds": ["les_a2_67_01_comparative_adverbials_postpositions"],
            "reviewsLessonIds": ["les_a1_41_01_witnessed_past_laa_intro"],
            "reviewsUnitIds": ["unit_a1_41_witnessed_past_verbal_tense_suffix_"],
            "reviewReason": "Deepens A1 witnessed past tense by contrasting immediate event reporting with historical narration.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Model emphatic exclamatory intonation on witnessed past verb forms.",
            "successCriteria": [
                "Selects correct vowel harmony allomorph (-лаа, -лээ, -лоо, -лөө) based on verbal root",
                "Contrasts immediate witnessed past (-лаа) with resultative past (-сан)"
            ],
            "masteryEvidence": "Utters 'Зам дээр түгжрэл үүслээ, унаа зогслоо' immediately in response to a visual cue.",
            "recommendedExerciseModalities": ["suffix_selection", "sentence_transformation", "contextual_cloze"]
        },
        {
            "lessonId": "les_a2_68_02_traffic_congestion_lexicon",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 2,
            "title": "Gridlock & Detours: Traffic Delays & Mechanical Breakdowns",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Introduce practical vocabulary for severe traffic congestion (түгжрэл), road construction detours (тойруу зам), flat tires (дугуй хагарах), and delays.",
            "communicativeOutcome": "Explain why you are delayed in traffic, identify detour signs, and discuss vehicle repairs.",
            "objectivesIntroduced": ["obj_a2_68_02_traffic_delay_lexicon"],
            "objectivesPracticed": ["obj_a2_68_01_witnessed_past_immediate_events"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_verb_past_recent_witnessed_laa"],
            "grammarReviewed": ["gram_a1_existential_baina_baihgui", "gram_a1_case_dative_locative_location"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_consonant_clusters"], "phonologyReviewed": ["phono_a1_vowel_reduction_non_initial"],
            "communicativeFunctionsIntroduced": ["comm_a2_19_taxi_hailing_fare_negotiation"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": ["comm_a1_18_scheduling_appointments"],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_transportation_travel", "lex_domain_city_urban_life"],
            "previousVocabularyReused": ["түгжрэл", "хоцрох", "машин", "засвар", "зам", "хүлээх"],
            "readingObjective": "Read roadside digital matrix signs warning of roadwork closures and expected travel delays.",
            "listeningObjective": "Understand taxi driver explaining that the main bridge is closed for resurfacing.",
            "writingObjective": "List 5 vehicular problems and roadway obstacles in Mongolian.",
            "spokenProductionObjective": "Explain to a peer why traffic is stopped: 'Зам засвартай байгаа тул машин явахгүй байна'.",
            "registerTarget": "Everyday colloquial commuter register",
            "pragmaticTarget": "Expressing reasonable empathy and shared patience over citywide gridlock.",
            "prerequisiteLessonIds": ["les_a2_68_01_witnessed_recent_past_transit"],
            "reviewsLessonIds": ["les_a1_43_01_bus_routes_stops_intro"],
            "reviewsUnitIds": ["unit_a1_43_public_transit_commuting_bus_routes"],
            "reviewReason": "Expands public transit vocabulary to cover real-world disruptions and delays.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Pronounce terms for vehicular parts and roadway conditions.",
            "successCriteria": [
                "Correctly defines түгжрэл (traffic jam), саатал (delay), эвдрэл (breakdown), тойрох (detour)",
                "Uses newly introduced delay nouns in complete sentences"
            ],
            "masteryEvidence": "Accurately categorizes 6 transit disruption scenarios into mechanical vs infrastructure causes.",
            "recommendedExerciseModalities": ["categorization", "contextual_cloze", "sentence_construction"]
        },
        {
            "lessonId": "les_a2_68_03_radio_traffic_bulletin_listening",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 3,
            "title": "Acoustic Lab: Radio Traffic Bulletins & Rush-Hour Updates",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop acoustic listening comprehension of authentic Ulaanbaatar radio traffic broadcasts (FM 106.3 / Авто радио).",
            "communicativeOutcome": "Extract gridlocked bridge names, average vehicle speeds, and suggested alternative bypass routes from radio audio.",
            "objectivesIntroduced": ["obj_a2_68_03_decode_radio_traffic_bulletins"],
            "objectivesPracticed": ["obj_a2_68_02_traffic_delay_lexicon"], "objectivesReviewed": ["obj_a1_34_01_tell_clock_time"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_dative_locative_location"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_vowel_reduction_non_initial"], "phonologyReviewed": ["phono_a1_nasal_vowels"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_19_taxi_hailing_fare_negotiation"],
            "communicativeFunctionsReviewed": ["comm_a1_17_describing_daily_routines"],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_transportation_travel", "lex_domain_communication_media"],
            "previousVocabularyReused": ["радио", "мэдээ", "сонсох", "гүүр", "зам", "хурд"],
            "readingObjective": "",
            "listeningObjective": "Identify affected avenues (Энхтайваны өргөн чөлөө), direction of congestion, and estimated delay from radio broadcast.",
            "writingObjective": "",
            "spokenProductionObjective": "Summarize radio traffic bulletin to a driver: 'Нарны гүүр их түгжрэлтэй байна гэнэ'.",
            "registerTarget": "Professional journalistic broadcast register",
            "pragmaticTarget": "Extracting operational transit advisories delivered at high professional speech rates (130+ wpm).",
            "prerequisiteLessonIds": ["les_a2_68_02_traffic_congestion_lexicon"],
            "reviewsLessonIds": ["les_a1_43_03_bus_stop_listening"],
            "reviewsUnitIds": ["unit_a1_43_public_transit_commuting_bus_routes"],
            "reviewReason": "Advances listening skills from isolated transit stops to rapid radio broadcast discourse.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Deliver fast-paced radio announcer voice with signature radio jingle and background traffic noise.",
            "successCriteria": [
                "Identifies which of 3 major arterial roads is completely blocked based on broadcast",
                "Extracts suggested alternative detour street correctly"
            ],
            "masteryEvidence": "Completes traffic status sheet for 3 city sectors from a 90-second authentic radio bulletin.",
            "recommendedExerciseModalities": ["listening_comprehension", "phonetic_discrimination", "categorization"]
        },
        {
            "lessonId": "les_a2_68_04_calling_to_explain_delay_dialogue",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 4,
            "title": "Calling Ahead: Apologizing for Traffic & Rescheduling Arrival",
            "lessonType": "dialogue_work",
            "primaryPurpose": "Develop spoken conversational skills for calling an appointment or host while stuck in traffic, apologizing politely, and adjusting arrival time.",
            "communicativeOutcome": "Call a meeting host, state current stuck location, apologize for the unexpected delay, and commit to a new arrival window.",
            "objectivesIntroduced": ["obj_a2_68_04_delay_apology_phone_exchange"],
            "objectivesPracticed": ["obj_a2_68_01_witnessed_past_immediate_events", "obj_a2_68_02_traffic_delay_lexicon"],
            "objectivesReviewed": ["obj_a1_13_01_apologies_gratitude"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_verb_past_recent_witnessed_laa"],
            "grammarReviewed": ["gram_a1_case_dative_locative_temporal", "gram_a1_polar_questions_uu_uu"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_intonation_polite"], "phonologyReviewed": ["phono_a1_vowel_length_distinction"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_19_taxi_hailing_fare_negotiation", "comm_a1_18_scheduling_appointments"],
            "communicativeFunctionsReviewed": ["comm_a1_13_apologies_politeness"],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_transportation_travel", "lex_domain_communication_media"],
            "previousVocabularyReused": ["уучлаарай", "хоцрох", "минут", "хүлээх", "уулзах", "байна"],
            "readingObjective": "",
            "listeningObjective": "Understand caller's reassurance and willingness to delay the meeting by 20 minutes.",
            "writingObjective": "",
            "spokenProductionObjective": "Conduct phone call: 'Байна уу? Би замын түгжрэлд орчихлоо. 20 минут орчим хоцрохоор байна, уучлаарай'.",
            "registerTarget": "Polite interpersonal and business phone register",
            "pragmaticTarget": "Proactively calling before the scheduled meeting time rather than after becoming late.",
            "prerequisiteLessonIds": ["les_a2_68_01_witnessed_recent_past_transit", "les_a2_68_02_traffic_congestion_lexicon"],
            "reviewsLessonIds": ["les_a1_13_01_gratitude_apologies"],
            "reviewsUnitIds": ["unit_a1_13_gratitude_apologies_politeness"],
            "reviewReason": "Recycles polite apologies ('уучлаарай', 'хүлцэл өчье') in modern workplace and social interactions.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Simulate telephone acoustic equalization with authentic car horn background ambiance.",
            "successCriteria": [
                "Executes phone greeting, states delay reason with witnessed past, and offers revised arrival time",
                "Responds appropriately to host's questions regarding current location"
            ],
            "masteryEvidence": "Conducts a spontaneous 4-turn telephone call explaining gridlock delay without breaking character.",
            "recommendedExerciseModalities": ["role-play response", "dialogue_completion", "listening_comprehension"]
        },
        {
            "lessonId": "les_a2_68_05_polite_delay_notice_sms_writing",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 5,
            "title": "Written Delay Notice: Drafting Apology Texts to Colleagues",
            "lessonType": "grammar_guided_practice",
            "primaryPurpose": "Synthesize witnessed past tense, traffic vocabulary, and temporal markers into clear, courteous written messages.",
            "communicativeOutcome": "Compose a polite SMS or instant message to colleagues explaining a transit breakdown and giving ETA.",
            "objectivesIntroduced": ["obj_a2_68_05_draft_delay_sms"],
            "objectivesPracticed": ["obj_a2_68_01_witnessed_past_immediate_events", "obj_a2_68_04_delay_apology_phone_exchange"],
            "objectivesReviewed": ["obj_a1_39_01_temporal_dative_locative"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_verb_past_recent_witnessed_laa"],
            "grammarReviewed": ["gram_a1_case_dative_locative_temporal", "gram_a1_verb_tense_future_prospective_na"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a1_18_scheduling_appointments", "comm_a1_13_apologies_politeness"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 4, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_transportation_travel", "lex_domain_communication_media"],
            "previousVocabularyReused": ["ажил", "осол", "хүрэх", "цаг", "эхлэх", "байх"],
            "readingObjective": "Read a colleague's reply confirming they will hold the start of the presentation.",
            "listeningObjective": "",
            "writingObjective": "Draft a 3-sentence SMS clearly stating reason for delay, current location, and revised arrival time.",
            "spokenProductionObjective": "",
            "registerTarget": "Professional digital messaging register",
            "pragmaticTarget": "Concise, professional tone conveying accountability without over-explaining.",
            "prerequisiteLessonIds": ["les_a2_68_04_calling_to_explain_delay_dialogue"],
            "reviewsLessonIds": ["les_a1_39_01_temporal_dative_locative_intro"],
            "reviewsUnitIds": ["unit_a1_39_temporal_dative_locative_times_dead"],
            "reviewReason": "Applies temporal dative-locative case (-д/-т) to specify revised meeting times.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Audio playback of sample SMS texts for orthographic review.",
            "successCriteria": [
                "Composes well-formed text with appropriate witnessed past and polite closure",
                "Accurately spells transit delay vocabulary: түгжрэл, хоцролт, очих"
            ],
            "masteryEvidence": "Drafts 'Сайн байна уу? Замд түгжрэл үүссэн тул би 15 минут хоцрохоор боллоо. Уучлаарай, 14:30 гэхэд очно' flawlessly.",
            "recommendedExerciseModalities": ["short-answer writing", "sentence construction", "error correction"]
        }
    ])

    # =========================================================================
    # UNIT 69: Postal, Courier & Package Delivery Services (pos 69)
    # 5 Lessons | Targets: ProdLem=19, RecLem=9, ProdExp=5, RecExp=3
    # Budget: (6,3,2,1), (4,2,1,1), (0,0,0,0), (5,2,1,1), (4,2,1,0) = (19, 9, 5, 3)
    # =========================================================================
    u = u_map[69]
    uid = u["unitId"]
    lessons.extend([
        {
            "lessonId": "les_a2_69_01_postal_services_parcel_lexicon",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 1,
            "title": "Mongol Post & Parcel Lockers: Courier Service Vocabulary",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Introduce practical vocabulary for postal counters (шуудангийн салбар), parcel shipping (илгээмж), automated parcel lockers, tracking numbers, and packaging materials.",
            "communicativeOutcome": "Identify parcel services, weigh packages, and ask about domestic vs international courier rates.",
            "objectivesIntroduced": ["obj_a2_69_01_postal_courier_lexicon"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_a2_64_02_u_money_card_lexicon"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_case_instrumental_transport_language"],
            "grammarReviewed": ["gram_a1_case_genitive_possession", "gram_a1_case_dative_locative_recipient"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_consonant_clusters"], "phonologyReviewed": ["phono_a1_vowel_reduction_non_initial"],
            "communicativeFunctionsIntroduced": ["comm_a2_19_postal_and_parcel_services"],
            "communicativeFunctionsPracticed": ["comm_a1_22_making_purchases"], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_communication_media", "lex_domain_commerce_transactions"],
            "previousVocabularyReused": ["шуудан", "явуулах", "авах", "хайрцаг", "жин", "үнэ"],
            "readingObjective": "Read postal counter tariff brochures comparing regular mail, airmail, and express EMS.",
            "listeningObjective": "Understand postal clerk stating package weight in kilograms and grams.",
            "writingObjective": "List package contents and customs descriptions in Cyrillic.",
            "spokenProductionObjective": "Inquire at Mongol Post: 'Энэ илгээмжийг Солонгос руу агаараар явуулахад хэдэн төгрөг болох вэ?'.",
            "registerTarget": "Everyday postal service transactional register",
            "pragmaticTarget": "Understanding parcel regulations regarding prohibited liquids, batteries, and perishables.",
            "prerequisiteLessonIds": ["les_a2_68_01_witnessed_recent_past_transit"],
            "reviewsLessonIds": ["les_a1_31_01_classifiers_measure_words_intro"],
            "reviewsUnitIds": ["unit_a1_31_measure_words_nominal_counting_clas"],
            "reviewReason": "Applies weight and volumetric measure words (килограмм, грамм, хайрцаг) to shipping logistics.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Pronounce postal terminology and measure unit combinations.",
            "successCriteria": [
                "Correctly defines илгээмж (parcel), дугтуй (envelope), хүргэлт (delivery), хаяг (address)",
                "Differentiates air parcel (агаарын шуудан) from surface freight (газрын шуудан)"
            ],
            "masteryEvidence": "Correctly matches 6 postal terms with their operational descriptions.",
            "recommendedExerciseModalities": ["categorization", "contextual_cloze", "dialogue_completion"]
        },
        {
            "lessonId": "les_a2_69_02_postal_customs_rates_reading",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 2,
            "title": "Deciphering Shipping Labels, Tracking Slips & Customs Forms",
            "lessonType": "reading_development",
            "primaryPurpose": "Develop reading comprehension for postal tracking printouts, shipping labels, customs declaration slips, and delivery notifications.",
            "communicativeOutcome": "Inspect a postal receipt to find tracking barcode number, sender/recipient addresses, weight, and delivery status.",
            "objectivesIntroduced": ["obj_a2_69_02_read_postal_tracking_slips"],
            "objectivesPracticed": ["obj_a2_69_01_postal_courier_lexicon"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_ablative_origin", "gram_a1_case_dative_locative_recipient"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_19_postal_and_parcel_services"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 4, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_communication_media", "lex_domain_commerce_transactions"],
            "previousVocabularyReused": ["хүлээн авагч", "илгээгч", "хаяг", "утас", "огноо", "код"],
            "readingObjective": "Locate tracking code (хяналтын дугаар), customs value declaration, and destination zip code on an authentic Mongol Post receipt.",
            "listeningObjective": "",
            "writingObjective": "Transcribe tracking numbers and sender details into parcel query form.",
            "spokenProductionObjective": "Explain tracking status to a friend based on postal website tracking results.",
            "registerTarget": "Administrative postal paperwork register",
            "pragmaticTarget": "Ensuring recipient phone number and postal code (шуудангийн код) are 100% accurate to prevent lost packages.",
            "prerequisiteLessonIds": ["les_a2_69_01_postal_services_parcel_lexicon"],
            "reviewsLessonIds": ["les_a1_28_01_phone_numbers_digital_exchange"],
            "reviewsUnitIds": ["unit_a1_28_telephone_numbers_digital_contact_e"],
            "reviewReason": "Recycles 8-digit mobile phone and 5-digit postal code reading from A1.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Pronounce formal administrative label categories.",
            "successCriteria": [
                "Locates sender, recipient, weight, and tariff fields on an authentic Mongol Post form",
                "Determines tracking status (e.g. 'Гаалийн хяналтад байна' vs 'Салбарт ирсэн')"
            ],
            "masteryEvidence": "Answers 5 questions correctly based on an authentic Mongolian parcel dispatch slip.",
            "recommendedExerciseModalities": ["reading_comprehension", "contextual_cloze", "categorization"]
        },
        {
            "lessonId": "les_a2_69_03_courier_dispatch_audio_listening",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 3,
            "title": "Acoustic Lab: Courier Phone Calls & Delivery Gate Codes",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop acoustic listening comprehension of fast, informal delivery driver phone calls regarding gate codes, intercom numbers, and drop-off instructions.",
            "communicativeOutcome": "Understand courier delivery calls, identify requested building entry information, and agree on parcel handover.",
            "objectivesIntroduced": ["obj_a2_69_03_decode_courier_delivery_calls"],
            "objectivesPracticed": ["obj_a2_69_01_postal_courier_lexicon"], "objectivesReviewed": ["obj_a1_28_01_telephone_numbers"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_dative_locative_location", "gram_a1_polar_questions_uu_uu"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_vowel_reduction_non_initial"], "phonologyReviewed": ["phono_a1_nasal_vowels"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_19_postal_and_parcel_services"],
            "communicativeFunctionsReviewed": ["comm_a1_19_inquiring_location"],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_communication_media", "lex_domain_transportation_travel"],
            "previousVocabularyReused": ["байна уу", "хүргэлт", "орц", "код", "ирлээ", "байр"],
            "readingObjective": "",
            "listeningObjective": "Extract caller identity (хүргэгч), building entrance number, and intercom code request from live phone audio.",
            "writingObjective": "",
            "spokenProductionObjective": "Provide intercom code and floor number to courier driver over the phone.",
            "registerTarget": "Rapid informal service telephone register",
            "pragmaticTarget": "Answering courier calls promptly and providing concise gate/door access instructions.",
            "prerequisiteLessonIds": ["les_a2_69_01_postal_services_parcel_lexicon"],
            "reviewsLessonIds": ["les_a1_28_03_listening_contact_info"],
            "reviewsUnitIds": ["unit_a1_28_telephone_numbers_digital_contact_e"],
            "reviewReason": "Tests comprehension of spoken digits in real-time phone exchanges.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Simulate courier voice calling from a moving moped/van with street background noise.",
            "successCriteria": [
                "Identifies that caller is a delivery courier with a package waiting at the entrance",
                "Extracts delivery driver's question regarding whether anyone is home to sign for parcel"
            ],
            "masteryEvidence": "Logs delivery details accurately from 3 distinct audio phone calls.",
            "recommendedExerciseModalities": ["listening_comprehension", "dictation", "role-play response"]
        },
        {
            "lessonId": "les_a2_69_04_mailing_parcels_counter_dialogue",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 4,
            "title": "At the Postal Counter: Mailing Parcels & Choosing Shipping Classes",
            "lessonType": "dialogue_work",
            "primaryPurpose": "Master spoken interaction at a postal counter, weighing parcels, declaring fragile contents, and purchasing packing boxes.",
            "communicativeOutcome": "Conduct a full postal counter transaction: hand over parcel, choose airmail vs surface, purchase packing tape, and receive tracking receipt.",
            "objectivesIntroduced": ["obj_a2_69_04_postal_counter_dialogue"],
            "objectivesPracticed": ["obj_a2_69_01_postal_courier_lexicon", "obj_a2_69_02_read_postal_tracking_slips"],
            "objectivesReviewed": ["obj_a1_22_01_making_purchases"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_case_instrumental_transport_language"],
            "grammarReviewed": ["gram_a1_verb_volitional_intention_ya", "gram_a1_case_accusative_definite"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_intonation_polite"], "phonologyReviewed": ["phono_a1_vowel_length_distinction"],
            "communicativeFunctionsIntroduced": ["comm_a2_19_postal_and_parcel_services"],
            "communicativeFunctionsPracticed": ["comm_a1_22_making_purchases"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_commerce_transactions", "lex_domain_communication_media"],
            "previousVocabularyReused": ["хайрцаг", "наах", "жинлэх", "үнэ", "төлөх", "карт"],
            "readingObjective": "",
            "listeningObjective": "Understand postal clerk's questions regarding parcel contents ('Дотор нь шингэн зүйл байгаа юу?').",
            "writingObjective": "",
            "spokenProductionObjective": "State shipping preference: 'Энэ хайрцгийг хурдан шуудангаар явуулъя. Хагарч болзошгүй тул болгоомжтой наагаарай'.",
            "registerTarget": "Courteous transactional service register",
            "pragmaticTarget": "Declaring fragile or valuable items explicitly to ensure careful handling.",
            "prerequisiteLessonIds": ["les_a2_69_02_postal_customs_rates_reading", "les_a2_69_03_courier_dispatch_audio_listening"],
            "reviewsLessonIds": ["les_a1_48_01_volitional_ya_intro"],
            "reviewsUnitIds": ["unit_a1_48_volitional_intention_suffixes_"],
            "reviewReason": "Applies volitional intentions (-я/-е) for transactional service requests.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Deliver authentic, clear counter dialogue with typical postal scale and tape dispensing sounds.",
            "successCriteria": [
                "Conducts smooth counter transaction specifying shipping tier, recipient destination, and packing needs",
                "Answers postal agent's security questions regarding prohibited contents"
            ],
            "masteryEvidence": "Completes 5-turn simulated postal transaction receiving tracking slip and price quote.",
            "recommendedExerciseModalities": ["role-play response", "dialogue_completion", "listening_comprehension"]
        },
        {
            "lessonId": "les_a2_69_05_postal_waybill_addressing_writing",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 5,
            "title": "Addressing the Waybill: Formatting Mongolian Postal Addresses",
            "lessonType": "grammar_guided_practice",
            "primaryPurpose": "Teach the correct hierarchical formatting of Mongolian postal addresses (Aimag/City -> District/Sum -> Khoroo/Bag -> Street -> Building -> Door).",
            "communicativeOutcome": "Fill out an official postal dispatch waybill and address label with complete hierarchical precision in Cyrillic.",
            "objectivesIntroduced": ["obj_a2_69_05_write_mongolian_postal_addresses"],
            "objectivesPracticed": ["obj_a2_69_01_postal_courier_lexicon", "obj_a2_69_04_postal_counter_dialogue"],
            "objectivesReviewed": ["obj_a1_07_01_personal_identification"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_genitive_possession", "gram_a1_case_dative_locative_location"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_19_postal_and_parcel_services"],
            "communicativeFunctionsReviewed": ["comm_a1_07_personal_names_identification"],
            "newProductiveLemmaTarget": 4, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_communication_media", "lex_domain_geography_places"],
            "previousVocabularyReused": ["аймаг", "хот", "дүүрэг", "хороо", "байр", "тоот"],
            "readingObjective": "Read domestic and international address samples on standard envelope layouts.",
            "listeningObjective": "",
            "writingObjective": "Fill in complete postal dispatch form with sender, recipient, zip code, and telephone contact.",
            "spokenProductionObjective": "",
            "registerTarget": "Formal administrative postal documentation",
            "pragmaticTarget": "Writing addresses from largest administrative unit to smallest, following authentic Mongolian postal conventions.",
            "prerequisiteLessonIds": ["les_a2_69_04_mailing_parcels_counter_dialogue"],
            "reviewsLessonIds": ["les_a1_07_02_writing_mongolian_names"],
            "reviewsUnitIds": ["unit_a1_07_personal_names_and_identification"],
            "reviewReason": "Connects personal identification and patronymics with formal postal recipient naming.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Read back correctly structured address fields.",
            "successCriteria": [
                "Formats postal address in correct descending hierarchical order (Хот -> Дүүрэг -> Хороо -> Байр -> Тоот)",
                "Includes 5-digit postal code and 8-digit mobile contact without omissions"
            ],
            "masteryEvidence": "Accurately completes 2 official postal dispatch waybills without formatting errors.",
            "recommendedExerciseModalities": ["short-answer writing", "error correction", "categorization"]
        }
    ])

    return lessons
