"""
Section 3 Generator Part 1 (Units 83 - 85): 13 Lessons
83: Human Anatomy & Somatic Pain Locations (4 lessons)
84: Describing Symptoms & Temporal Converb -хад4 (5 lessons)
85: Pharmacy Consultation & Medicine Purchasing (4 lessons)
"""

import json
from typing import List, Dict, Any

def get_sec03_part1_lessons(u_map: Dict[int, Any]) -> List[Dict[str, Any]]:
    lessons: List[Dict[str, Any]] = []

    # =========================================================================
    # UNIT 83: Human Anatomy & Somatic Pain Location (pos 83)
    # 4 Lessons | Targets: ProdLem=19, RecLem=9, ProdExp=5, RecExp=3
    # Budget: (7,3,2,1), (5,3,1,1), (0,0,0,0), (7,3,2,1) = (19, 9, 5, 3)
    # =========================================================================
    u = u_map[83]
    uid = u["unitId"]
    lessons.extend([
        {
            "lessonId": "les_a2_83_01_body_parts_somatic_pain_lexicon",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 1,
            "title": "Where Does It Hurt: Human Anatomy & Pain Verbs (өвдөх, хатгах, чинэрэх)",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Introduce human anatomical vocabulary (толгой, хоолой, гэдэс, нуруу, шүд, үе мөч) paired with sensory pain descriptors (өвдөх, хатгах, шархирах, янгинах, чинэрэх).",
            "communicativeOutcome": "Pinpoint physical pain and differentiate between sharp, throbbing, aching, and stabbing sensations.",
            "objectivesIntroduced": ["obj_a2_83_01_anatomy_pain_lexicon"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_a2_82_01_consumer_rights_lexicon"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_predicate_adjective_nominal", "gram_a1_case_genitive_possession"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_consonant_clusters"], "phonologyReviewed": ["phono_a1_vowel_reduction_non_initial"],
            "communicativeFunctionsIntroduced": ["comm_a2_12_medical_symptoms_doctor"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 7, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_health_medicine", "lex_domain_body_anatomy"],
            "previousVocabularyReused": ["толгой", "хөл", "гар", "өвдөх", "муу", "байх"],
            "readingObjective": "Read an anatomical clinic poster diagramming internal organs and pain zones.",
            "listeningObjective": "Understand a patient describing a localized headache vs sinus pressure.",
            "writingObjective": "List 6 human body parts and pair each with a specific discomfort verb.",
            "spokenProductionObjective": "Explain symptoms to a doctor: 'Миний хоолой сөөж, толгой янгинаж өвдөж байна'.",
            "registerTarget": "Clinical somatic diagnostic register",
            "pragmaticTarget": "Using precise Mongolian sensory verbs to convey the specific nature of internal pain.",
            "prerequisiteLessonIds": ["les_a2_82_05_retail_service_transaction_checkpoint"],
            "reviewsLessonIds": ["les_a1_21_01_attributive_adjectives_intro"],
            "reviewsUnitIds": ["unit_a1_21_attributive_predicative_adjective"],
            "reviewReason": "Expands basic physical condition adjectives into nuanced somatic sensory descriptions.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Pronounce anatomical body parts and sensory pain verbs clearly.",
            "successCriteria": [
                "Identifies anatomical areas: нуруу (back), үе мөч (joints), хоолой (throat), гэдэс (stomach)",
                "Differentiates хатгах (sharp/stabbing) from янгинах (aching/throbbing)"
            ],
            "masteryEvidence": "Accurately describes 4 distinct pain scenarios matching body part to specific sensation.",
            "recommendedExerciseModalities": ["categorization", "contextual_cloze", "matching"]
        },
        {
            "lessonId": "les_a2_83_02_medical_triage_intake_reading",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 2,
            "title": "Deciphering Clinic Intake Forms & Triage Questionnaires",
            "lessonType": "reading_development",
            "primaryPurpose": "Develop reading comprehension for clinic intake forms (үзлэгийн хуудас), pain scale questionnaires (1-10 оноо), and symptom checklists.",
            "communicativeOutcome": "Inspect medical intake paperwork, identify chronic vs acute complaints, and rate pain severity.",
            "objectivesIntroduced": ["obj_a2_83_02_read_clinic_intake_forms"],
            "objectivesPracticed": ["obj_a2_83_01_anatomy_pain_lexicon"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_dative_locative_location", "gram_a1_case_ablative_origin"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_12_medical_symptoms_doctor"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_health_medicine", "lex_domain_civic_administrative"],
            "previousVocabularyReused": ["өвчин", "огноо", "нас", "хүчтэй", "эхлэх", "эмч"],
            "readingObjective": "Extract pain onset date, severity rating, and anatomical checkboxes from a clinic intake sheet.",
            "listeningObjective": "",
            "writingObjective": "Transcribe personal allergy history and symptoms onto a medical template.",
            "spokenProductionObjective": "Explain to a triage nurse where the pain is centered based on questionnaire answers.",
            "registerTarget": "Institutional medical intake register",
            "pragmaticTarget": "Providing clear, concise medical self-assessments on formal paperwork.",
            "prerequisiteLessonIds": ["les_a2_83_01_body_parts_somatic_pain_lexicon"],
            "reviewsLessonIds": ["les_a1_36_02_reading_calendar_dates"],
            "reviewsUnitIds": ["unit_a1_36_calendar_dates_months_seasons"],
            "reviewReason": "Recycles calendar date reading for establishing medical symptom onset.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Read clinical intake form categories aloud.",
            "successCriteria": [
                "Locates sections for current symptoms (одоогийн зовиур) and past illnesses (өнгөрсөн өвчин)",
                "Understands medical pain scale rankings from 1 (хөнгөн) to 10 (тэсвэрлэшгүй)"
            ],
            "masteryEvidence": "Fills in complete clinic registration card based on a simulated somatic profile.",
            "recommendedExerciseModalities": ["reading_comprehension", "contextual_cloze", "categorization"]
        },
        {
            "lessonId": "les_a2_83_03_patient_nurse_triage_listening",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 3,
            "title": "Acoustic Lab: Triage Nurse Assessments & Blood Pressure Checks",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop acoustic listening comprehension of nurse triage checks: measuring blood pressure (даралт үзэх), checking temperature (халуун хэмжих), and asking diagnostic questions.",
            "communicativeOutcome": "Understand nurse instructions during preliminary triage and extract vital sign values (blood pressure and body temperature).",
            "objectivesIntroduced": ["obj_a2_83_03_decode_triage_assessments"],
            "objectivesPracticed": ["obj_a2_83_01_anatomy_pain_lexicon"], "objectivesReviewed": ["obj_a1_27_01_counting_tens_hundreds"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_numerals_cardinal_counting", "gram_a1_verb_imperative_polite_aarai"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_vowel_reduction_non_initial"], "phonologyReviewed": ["phono_a1_nasal_vowels"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_12_medical_symptoms_doctor"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_health_medicine"],
            "previousVocabularyReused": ["даралт", "халуун", "хэмжих", "суух", "ханцуй", "хэвийн"],
            "readingObjective": "",
            "listeningObjective": "Extract blood pressure reading ('120-той 80') and temperature ('38.2 градус') from spoken nurse dialogue.",
            "writingObjective": "",
            "spokenProductionObjective": "Ask nurse if the readings are normal: 'Миний даралт хэвийн байна уу?'.",
            "registerTarget": "Clinical bedside triage register",
            "pragmaticTarget": "Following physical clinical instructions promptly (rolling up sleeves, breathing deeply).",
            "prerequisiteLessonIds": ["les_a2_83_01_body_parts_somatic_pain_lexicon"],
            "reviewsLessonIds": ["les_a1_49_01_polite_imperative_aarai"],
            "reviewsUnitIds": ["unit_a1_49_polite_request_imperative_suffixes_"],
            "reviewReason": "Applies polite imperative listening (-аарай) to clinical examination instructions.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Deliver realistic nurse-patient triage dialogue with blood pressure cuff velcro sounds.",
            "successCriteria": [
                "Transcribes vital sign numbers accurately from auditory speech stream",
                "Understands whether the nurse reports elevated blood pressure (өндөр даралт) or fever (халуунтай)"
            ],
            "masteryEvidence": "Accurately notes down vital metrics for 3 distinct triage audio vignettes.",
            "recommendedExerciseModalities": ["listening_comprehension", "dictation", "phonetic_discrimination"]
        },
        {
            "lessonId": "les_a2_83_04_doctor_somatic_exam_dialogue",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 4,
            "title": "In the Examination Room: Explaining Pain to the General Practitioner",
            "lessonType": "dialogue_work",
            "primaryPurpose": "Master spoken interaction with a physician: answering palpation questions ('Энд дарахад өвдөж байна уу?'), detailing duration, and explaining when pain worsens.",
            "communicativeOutcome": "Conduct a clinical consultation with a doctor, specifying pain location, intensity, and aggravating factors (eating, moving, cold).",
            "objectivesIntroduced": ["obj_a2_83_04_doctor_exam_dialogue"],
            "objectivesPracticed": ["obj_a2_83_01_anatomy_pain_lexicon", "obj_a2_83_02_read_clinic_intake_forms"],
            "objectivesReviewed": ["obj_a1_16_01_greet_time_of_day"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_converb_coordinating_j_ch", "gram_a1_case_dative_locative_location"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_intonation_polite"], "phonologyReviewed": ["phono_a1_vowel_length_distinction"],
            "communicativeFunctionsIntroduced": ["comm_a2_12_medical_symptoms_doctor"],
            "communicativeFunctionsPracticed": ["comm_a1_13_apologies_politeness"],
            "communicativeFunctionsReviewed": ["comm_a1_16_greetings_time_of_day"],
            "newProductiveLemmaTarget": 7, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_health_medicine"],
            "previousVocabularyReused": ["өвдөх", "дарах", "хэвтэх", "амьсгалах", "эмч", "туслах"],
            "readingObjective": "",
            "listeningObjective": "Understand doctor's diagnostic questions during physical examination.",
            "writingObjective": "",
            "spokenProductionObjective": "Describe pain: 'Баруун хавирган дор хатгаж өвдөөд, гүнзгий амьсгалахад улам хүчтэй болж байна'.",
            "registerTarget": "Confidential patient-doctor clinical register",
            "pragmaticTarget": "Responding accurately to diagnostic palpation without minimizing symptoms.",
            "prerequisiteLessonIds": ["les_a2_83_02_medical_triage_intake_reading", "les_a2_83_03_patient_nurse_triage_listening"],
            "reviewsLessonIds": ["les_a1_41_01_witnessed_past_laa_intro"],
            "reviewsUnitIds": ["unit_a1_41_witnessed_past_verbal_tense_suffix_"],
            "reviewReason": "Recycles witnessed past tense (-лаа4) to report when symptoms started.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Model gentle, inquisitive doctor voice and clear patient symptom articulation.",
            "successCriteria": [
                "Explains pain location and triggers clearly during physical examination",
                "Follows doctor's commands: 'Гүнзгий амьсгал аваад гаргаарай', 'Хэлээ гаргаарай'"
            ],
            "masteryEvidence": "Conducts a 5-turn simulated doctor-patient examination dialogue without communicative breakdown.",
            "recommendedExerciseModalities": ["role-play response", "dialogue_completion", "listening_comprehension"]
        }
    ])

    # =========================================================================
    # UNIT 84: Describing Illness Symptoms & Temporal Converb: -khad4 (pos 84)
    # 5 Lessons | Targets: ProdLem=21, RecLem=10, ProdExp=5, RecExp=3
    # Budget: (5,2,1,1), (6,3,1,1), (5,3,2,1), (0,0,0,0), (5,2,1,0) = (21, 10, 5, 3)
    # =========================================================================
    u = u_map[84]
    uid = u["unitId"]
    lessons.extend([
        {
            "lessonId": "les_a2_84_01_temporal_converb_khad_intro",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 1,
            "title": "When I Walk, It Hurts: The Temporal Converb (-хад/-хэд/-ход/-хөд)",
            "lessonType": "grammar_introduction",
            "primaryPurpose": "Introduce the temporal-locative converb (-хад4 / -хэд / -ход / -хөд) indicating 'when/while/upon doing', essential for describing conditions under which symptoms manifest.",
            "communicativeOutcome": "Explain conditional symptoms: 'Явахад хөл өвдөж байна' (When walking, my leg hurts), 'Ханиалгахад цээж хатгаж байна' (When coughing, my chest stabs).",
            "objectivesIntroduced": ["obj_a2_84_01_temporal_converb_khad"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_a2_83_01_anatomy_pain_lexicon"],
            "grammarIntroduced": ["gram_a2_converb_temporal_while_khad"],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_dative_locative_location", "gram_a1_predicate_adjective_nominal"],
            "phonologyIntroduced": ["phono_a2_temporal_converb_harmony"],
            "phonologyPracticed": ["phono_a1_masculine_feminine_harmony"], "phonologyReviewed": ["phono_a1_consonant_clusters"],
            "communicativeFunctionsIntroduced": ["comm_a2_12_medical_symptoms_doctor"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_health_medicine", "lex_domain_actions_movement"],
            "previousVocabularyReused": ["явах", "идэх", "уух", "унтах", "өвдөх", "халуурах"],
            "readingObjective": "Read medical advisory articles explaining when patients should seek urgent care.",
            "listeningObjective": "Identify the temporal suffix (-хад4) in patients' symptom descriptions.",
            "writingObjective": "Combine 3 verbal actions with symptom predicates using the temporal converb.",
            "spokenProductionObjective": "Explain symptom triggers: 'Юм залгихад хоолой маш хүчтэй өвдөж байна'.",
            "registerTarget": "Clinical explanatory register",
            "pragmaticTarget": "Connecting physical actions directly to symptom triggers in clear temporal-locative clauses.",
            "prerequisiteLessonIds": ["les_a2_83_01_body_parts_somatic_pain_lexicon"],
            "reviewsLessonIds": ["les_a1_31_01_dative_locative_intro"],
            "reviewsUnitIds": ["unit_a1_31_dative_locative_spatial_location_t"],
            "reviewReason": "Expands dative-locative case marking (-д/-т) from nouns to nominalized verbs (-х + -д = -хад).",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Model quadruple vowel harmony in temporal suffix (-хад, -хэд, -ход, -хөд).",
            "successCriteria": [
                "Applies correct temporal allomorph according to root vowel harmony",
                "Constructs well-formed complex sentence connecting action trigger to somatic reaction"
            ],
            "masteryEvidence": "Produces 'Босоход толгой эргэж байна' with accurate pronunciation and morphology.",
            "recommendedExerciseModalities": ["suffix_selection", "sentence_construction", "clause_combination"]
        },
        {
            "lessonId": "les_a2_84_02_clinical_illness_symptoms_lexicon",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 2,
            "title": "Cold, Flu & Fatigue: Systemic Illness Vocabulary",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Introduce systemic illness and constitutional symptom vocabulary (ханиад томуу, халуурах, даарах, жихүүцэх, дотор муухайрах, толгой эргэх, сульдах).",
            "communicativeOutcome": "Describe common winter ailments, viral symptoms, nausea, dizziness, and bodily chills.",
            "objectivesIntroduced": ["obj_a2_84_02_illness_symptoms_lexicon"],
            "objectivesPracticed": ["obj_a2_84_01_temporal_converb_khad"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_converb_temporal_while_khad"],
            "grammarReviewed": ["gram_a1_existential_baina_baihgui", "gram_a1_converb_coordinating_j_ch"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_consonant_clusters"], "phonologyReviewed": ["phono_a1_vowel_reduction_non_initial"],
            "communicativeFunctionsIntroduced": ["comm_a2_12_medical_symptoms_doctor"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_health_medicine"],
            "previousVocabularyReused": ["ханиад", "халуун", "даарах", "хүйтэн", "бие", "муу"],
            "readingObjective": "Read a public health bulletin outlining influenza precautions and warning signs.",
            "listeningObjective": "Understand colleague calling in sick explaining flu symptoms.",
            "writingObjective": "List 5 winter illness symptoms in Cyrillic.",
            "spokenProductionObjective": "Explain feeling unwell: 'Би өчигдрөөс хойш жихүүцэж, халуураад, бие маш их сульдаж байна'.",
            "registerTarget": "Everyday health condition and workplace absence register",
            "pragmaticTarget": "Accurately conveying systemic malaise without understating severity.",
            "prerequisiteLessonIds": ["les_a2_84_01_temporal_converb_khad_intro"],
            "reviewsLessonIds": ["les_a1_42_01_weather_descriptions_intro"],
            "reviewsUnitIds": ["unit_a1_42_weather_atmospheric_conditions_cl"],
            "reviewReason": "Connects cold climatic conditions with seasonal respiratory illnesses.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Pronounce systemic symptom terms clearly.",
            "successCriteria": [
                "Identifies systemic symptoms: жихүүцэх (chills), халуурах (fever), дотор муухайрах (nausea), толгой эргэх (dizziness)",
                "Forms compound symptom statements: 'Халуурахад жихүүцдэг'"
            ],
            "masteryEvidence": "Accurately categorizes 6 common cold/flu symptoms and explains their physical sensations.",
            "recommendedExerciseModalities": ["categorization", "contextual_cloze", "matching"]
        },
        {
            "lessonId": "les_a2_84_03_workplace_sick_leave_call_dialogue",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 3,
            "title": "Calling In Sick: Requesting Leave & Explaining Flu Symptoms",
            "lessonType": "dialogue_work",
            "primaryPurpose": "Develop spoken communicative fluency for calling a supervisor or teacher, explaining acute illness, requesting sick leave (чөлөө авах), and promising a medical certificate.",
            "communicativeOutcome": "Call your office or school to report illness, state expected absence duration, and confirm coverage for urgent tasks.",
            "objectivesIntroduced": ["obj_a2_84_03_sick_leave_phone_dialogue"],
            "objectivesPracticed": ["obj_a2_84_01_temporal_converb_khad", "obj_a2_84_02_illness_symptoms_lexicon"],
            "objectivesReviewed": ["obj_a1_13_01_apologies_intro"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_converb_temporal_while_khad"],
            "grammarReviewed": ["gram_a1_verb_volitional_intention_ya", "gram_a1_case_ablative_origin"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_intonation_polite"], "phonologyReviewed": ["phono_a1_diphthongs"],
            "communicativeFunctionsIntroduced": ["comm_a2_12_medical_symptoms_doctor"],
            "communicativeFunctionsPracticed": ["comm_a1_13_apologies_politeness"],
            "communicativeFunctionsReviewed": ["comm_a1_16_greetings_time_of_day"],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_health_medicine", "lex_domain_workplace_occupations"],
            "previousVocabularyReused": ["чөлөө", "өвдөх", "хэвтэх", "маргааш", "ажил", "хэлэх"],
            "readingObjective": "",
            "listeningObjective": "Understand manager expressing sympathy and asking about doctor consultation.",
            "writingObjective": "",
            "spokenProductionObjective": "Call supervisor: 'Багш аа / захирал аа, миний бие өвдөөд, өнөөдөр хичээлдээ/ажилдаа ирж чадахгүй нь. Эмчид үзүүлээд бичиг авчиръя'.",
            "registerTarget": "Respectful professional telephone register",
            "pragmaticTarget": "Apologizing politely for unexpected absence and confirming medical note protocol.",
            "prerequisiteLessonIds": ["les_a2_84_02_clinical_illness_symptoms_lexicon"],
            "reviewsLessonIds": ["les_a1_68_03_transit_delay_phone_dialogue"],
            "reviewsUnitIds": ["unit_a2_68_handling_transit_delays_traffic_jam"],
            "reviewReason": "Applies professional phone courtesy to medical emergency notifications.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Deliver authentic congested/sick phone voice contrasting with understanding manager.",
            "successCriteria": [
                "Articulates illness reason clearly and requests specific days of leave",
                "Promises to bring formal doctor note (эмчийн магадлагаа)"
            ],
            "masteryEvidence": "Completes 4-turn sick leave telephone call without communicative hesitation.",
            "recommendedExerciseModalities": ["role-play response", "dialogue_completion", "listening_comprehension"]
        },
        {
            "lessonId": "les_a2_84_04_flu_advisory_acoustic_listening",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 4,
            "title": "Acoustic Lab: Public Health Radio Broadcasts on Seasonal Epidemics",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop acoustic listening comprehension of official public health radio advisories announcing seasonal flu peaks, school closures, and fever clinic operating hours.",
            "communicativeOutcome": "Extract key public health advisories regarding high-risk groups, clinic operating hours, and fever management recommendations from radio broadcasts.",
            "objectivesIntroduced": ["obj_a2_84_04_decode_health_broadcasts"],
            "objectivesPracticed": ["obj_a2_84_02_illness_symptoms_lexicon"], "objectivesReviewed": ["obj_a1_36_01_calendar_dates"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a2_converb_temporal_while_khad", "gram_a1_verb_imperative_polite_aarai"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_vowel_reduction_non_initial"], "phonologyReviewed": ["phono_a1_nasal_vowels"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_12_medical_symptoms_doctor"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_health_medicine", "lex_domain_civic_administrative"],
            "previousVocabularyReused": ["эмнэлэг", "томуу", "халуурах", "хүүхэд", "цаг", "өглөө"],
            "readingObjective": "",
            "listeningObjective": "Identify recommended home care steps (warm fluids, rest) and when to visit hospital from public service audio.",
            "writingObjective": "",
            "spokenProductionObjective": "Explain the radio warning to family members in 3 Mongolian sentences.",
            "registerTarget": "Public administrative broadcast health register",
            "pragmaticTarget": "Parsing professional broadcast Mongolian with medical terminology.",
            "prerequisiteLessonIds": ["les_a2_84_02_clinical_illness_symptoms_lexicon"],
            "reviewsLessonIds": ["les_a1_68_04_radio_traffic_listening"],
            "reviewsUnitIds": ["unit_a2_68_handling_transit_delays_traffic_jam"],
            "reviewReason": "Expands broadcast listening competence from traffic alerts to health announcements.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Authoritative radio broadcaster tone with official public health advisory background chime.",
            "successCriteria": [
                "Identifies fever threshold (38.5°C) requiring doctor consultation from broadcast",
                "Extracts district clinic extended weekend hours from announcement"
            ],
            "masteryEvidence": "Fills in public health guideline summary table with 100% accuracy based on broadcast.",
            "recommendedExerciseModalities": ["listening_comprehension", "phonetic_discrimination", "categorization"]
        },
        {
            "lessonId": "les_a2_84_05_sick_leave_written_request",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 5,
            "title": "Formal Absence: Writing a Sick Leave Note & Symptom Report",
            "lessonType": "grammar_guided_practice",
            "primaryPurpose": "Synthesize temporal converbs (-хад4), symptom vocabulary, and polite written formulas into a formal written sick leave request (чөлөө гуйх өргөдөл / мэдэгдэл).",
            "communicativeOutcome": "Draft a formal written absence notification to an employer or university stating symptom onset, medical appointment, and expected return date.",
            "objectivesIntroduced": ["obj_a2_84_05_write_sick_leave_note"],
            "objectivesPracticed": ["obj_a2_84_01_temporal_converb_khad", "obj_a2_84_02_illness_symptoms_lexicon"],
            "objectivesReviewed": ["obj_a1_50_01_sequential_converb"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_converb_temporal_while_khad"],
            "grammarReviewed": ["gram_a1_converb_sequential_aad", "gram_a1_case_ablative_origin"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_12_medical_symptoms_doctor"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_health_medicine", "lex_domain_workplace_occupations"],
            "previousVocabularyReused": ["өргөдөл", "чөлөө", "хүндэтгэсэн", "өвдөх", "эмчийн бичиг", "огноо"],
            "readingObjective": "Review a model Mongolian workplace absence email to observe formal salutation and sign-off.",
            "listeningObjective": "",
            "writingObjective": "Draft a 5-sentence formal absence memo using the temporal converb (-хад4) and formal medical terms.",
            "spokenProductionObjective": "",
            "registerTarget": "Formal administrative absence correspondence register",
            "pragmaticTarget": "Adhering to standard Mongolian corporate and academic absence request conventions.",
            "prerequisiteLessonIds": ["les_a2_84_03_workplace_sick_leave_call_dialogue", "les_a2_84_04_flu_advisory_acoustic_listening"],
            "reviewsLessonIds": ["les_a1_68_05_polite_delay_notice_sms_writing"],
            "reviewsUnitIds": ["unit_a2_68_handling_transit_delays_traffic_jam"],
            "reviewReason": "Elevates written delay notices to formal sick leave documentation.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Audio read-back of formal sick leave document.",
            "successCriteria": [
                "Produces formal written memo with correct heading, date, and respectful closing",
                "Includes at least one temporal converb clause: 'Эмнэлэгт үзүүлэхэд эмч 3 өдрийн амралт өгсөн тул...'"
            ],
            "masteryEvidence": "Drafts complete, error-free workplace sick leave email with accompanying doctor note reference.",
            "recommendedExerciseModalities": ["short-answer writing", "clause_combination", "error correction"]
        }
    ])

    # =========================================================================
    # UNIT 85: Purchasing Medicine & Pharmacy Consultation (pos 85)
    # 4 Lessons | Targets: ProdLem=19, RecLem=9, ProdExp=5, RecExp=3
    # Budget: (7,3,2,1), (5,3,1,1), (0,0,0,0), (7,3,2,1) = (19, 9, 5, 3)
    # =========================================================================
    u = u_map[85]
    uid = u["unitId"]
    lessons.extend([
        {
            "lessonId": "les_a2_85_01_pharmacy_dosage_medication_lexicon",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 1,
            "title": "At the Pharmacy: Dosages, Pills, Syrups & Prescriptions",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Introduce pharmacy and pharmaceutical vocabulary (эмийн сан, эмчийн жор, шахмал эм, сироп, түрхлэг, тун хэмжээ, хоолны дараа/өмнө).",
            "communicativeOutcome": "Ask for over-the-counter medicine, understand pharmacist dosage instructions, and check prescription requirements.",
            "objectivesIntroduced": ["obj_a2_85_01_pharmacy_dosage_lexicon"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_a2_84_01_temporal_converb_khad"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_spatial_postpositions_deeree_door", "gram_a1_numerals_cardinal_counting"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_consonant_clusters"], "phonologyReviewed": ["phono_a1_long_vowels"],
            "communicativeFunctionsIntroduced": ["comm_a2_13_buying_medicine_pharmacy"],
            "communicativeFunctionsPracticed": ["comm_a1_22_making_purchases"], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 7, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_health_medicine", "lex_domain_commerce_transactions"],
            "previousVocabularyReused": ["эм", "сан", "жор", "уух", "өдөр", "цаг"],
            "readingObjective": "Read pharmacy counter signs identifying prescription-only (жороор олгох) vs OTC medications.",
            "listeningObjective": "Understand pharmacist explaining whether to take medicine before or after meals.",
            "writingObjective": "List 4 types of medical preparations (шахмал, сироп, дусаалга, тос) in Cyrillic.",
            "spokenProductionObjective": "Ask a pharmacist: 'Хоолойн өвчинд уух сайн эм юу байна вэ?'.",
            "registerTarget": "Healthcare commercial consultation register",
            "pragmaticTarget": "Clarifying timing relative to food intake (хоолноос өмнө / дараа) for optimal pharmaceutical efficacy.",
            "prerequisiteLessonIds": ["les_a2_84_01_temporal_converb_khad_intro"],
            "reviewsLessonIds": ["les_a1_22_01_making_purchases_intro"],
            "reviewsUnitIds": ["unit_a1_22_shopping_transactions_making_purch"],
            "reviewReason": "Expands retail shopping into pharmaceutical terminology and health regimens.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Pronounce pharmaceutical dosage forms clearly.",
            "successCriteria": [
                "Distinguishes шахмал (tablets), сироп (syrup), түрхлэг (ointment), дусаалга (drops)",
                "Understands timing: хоолны өмнө (before meals) vs хоолны дараа (after meals)"
            ],
            "masteryEvidence": "Accurately interprets 4 distinct pharmaceutical dosage regimens.",
            "recommendedExerciseModalities": ["categorization", "contextual_cloze", "matching"]
        },
        {
            "lessonId": "les_a2_85_02_medication_package_insert_reading",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 2,
            "title": "Deciphering Medicine Boxes & Patient Information Leaflets",
            "lessonType": "reading_development",
            "primaryPurpose": "Develop targeted reading comprehension of Mongolian pharmaceutical packaging (хайрцаг), expiry dates (дуусах хугацаа), storage conditions, and contraindications.",
            "communicativeOutcome": "Inspect a medicine box to locate daily dosage limits, storage temperature (хөргөгчинд хадгалах), and expiry date.",
            "objectivesIntroduced": ["obj_a2_85_02_read_medication_packaging"],
            "objectivesPracticed": ["obj_a2_85_01_pharmacy_dosage_lexicon"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_dative_locative_location", "gram_a1_numerals_cardinal_counting"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_13_buying_medicine_pharmacy"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_health_medicine"],
            "previousVocabularyReused": ["хугацаа", "хадгалах", "хүүхэд", "хориглох", "градус", "хэмжээ"],
            "readingObjective": "Extract maximum daily dose (өдөрт хамгийн ихдээ 3 ширхэг), expiry month/year, and cautionary warnings from a medicine box.",
            "listeningObjective": "",
            "writingObjective": "Transcribe medication dosage instructions onto an adhesive bottle label in Cyrillic.",
            "spokenProductionObjective": "Explain package warning to a family member: 'Энэ эмийг хүүхдээс хол хадгалах ёстой'.",
            "registerTarget": "Technical medical packaging and advisory register",
            "pragmaticTarget": "Checking expiry dates and child-safety storage warnings vigilantly.",
            "prerequisiteLessonIds": ["les_a2_85_01_pharmacy_dosage_medication_lexicon"],
            "reviewsLessonIds": ["les_a1_36_02_reading_calendar_dates"],
            "reviewsUnitIds": ["unit_a1_36_calendar_dates_months_seasons"],
            "reviewReason": "Applies calendar date decoding to medicine manufacturing and expiry stamps.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Read package warning statements aloud.",
            "successCriteria": [
                "Locates expiry date and batch number accurately on box",
                "Extracts daily pill intake ceiling without error"
            ],
            "masteryEvidence": "Answers 4 comprehension questions based on an authentic Mongolian medicine box label.",
            "recommendedExerciseModalities": ["reading_comprehension", "contextual_cloze", "categorization"]
        },
        {
            "lessonId": "les_a2_85_03_pharmacist_advice_acoustic_listening",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 3,
            "title": "Acoustic Lab: Pharmacist Consultation & Side Effect Cautions",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop acoustic listening comprehension of fast pharmacist explanations behind security glass: side effects (нойр хүргэх, толгой өвдөх), drug interactions, and water intake.",
            "communicativeOutcome": "Extract crucial warnings from pharmacist audio: whether the drug causes drowsiness, if it should be taken with milk or water, and duration of course.",
            "objectivesIntroduced": ["obj_a2_85_03_decode_pharmacist_cautions"],
            "objectivesPracticed": ["obj_a2_85_01_pharmacy_dosage_lexicon"], "objectivesReviewed": ["obj_a1_49_01_polite_imperative_aarai"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_verb_imperative_polite_aarai", "gram_a1_case_instrumental_transport_language"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_vowel_reduction_non_initial"], "phonologyReviewed": ["phono_a1_nasal_vowels"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_13_buying_medicine_pharmacy"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_health_medicine"],
            "previousVocabularyReused": ["нойр", "ус", "уух", "өдөр", "машин", "жолоодох"],
            "readingObjective": "",
            "listeningObjective": "Identify specific cautionary advice ('Энэ эмийг уугаад машин барьж болохгүй, нойр их хүргэнэ') from pharmacist audio.",
            "writingObjective": "",
            "spokenProductionObjective": "Warn a companion not to drive after taking the prescribed cold remedy.",
            "registerTarget": "High-speed professional pharmacy consultation register",
            "pragmaticTarget": "Heeding contraindication warnings (avoiding alcohol, not operating machinery).",
            "prerequisiteLessonIds": ["les_a2_85_01_pharmacy_dosage_medication_lexicon"],
            "reviewsLessonIds": ["les_a1_49_02_imperative_daily_requests"],
            "reviewsUnitIds": ["unit_a1_49_polite_request_imperative_suffixes_"],
            "reviewReason": "Applies polite imperative listening to health safety warnings.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Authentic pharmacy counter dialogue with pill bottle rattle and clear protective guidance.",
            "successCriteria": [
                "Identifies whether medicine induces drowsiness from audio stream",
                "Extracts daily dosage frequency (өдөрт гурван удаа, нэг нэгээр)"
            ],
            "masteryEvidence": "Correctly notes down dosage and side-effect profile for 3 audio pharmacist consultations.",
            "recommendedExerciseModalities": ["listening_comprehension", "dictation", "phonetic_discrimination"]
        },
        {
            "lessonId": "les_a2_85_04_pharmacy_counter_purchasing_dialogue",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 4,
            "title": "At the Drugstore Counter: Buying Remedies & Asking for Generics",
            "lessonType": "dialogue_work",
            "primaryPurpose": "Master spoken interaction at a pharmacy counter: presenting a prescription, asking for affordable generic alternatives, asking for fever reducers, and clarifying instructions.",
            "communicativeOutcome": "Purchase needed medications at a Mongolian drugstore, ask for an equivalent domestic generic, and verify dosage schedule.",
            "objectivesIntroduced": ["obj_a2_85_04_pharmacy_counter_dialogue"],
            "objectivesPracticed": ["obj_a2_85_01_pharmacy_dosage_lexicon", "obj_a2_85_02_read_medication_packaging"],
            "objectivesReviewed": ["obj_a1_22_01_making_purchases"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_verb_volitional_intention_ya", "gram_a1_polar_questions_uu_uu"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_intonation_polite"], "phonologyReviewed": ["phono_a1_vowel_length_distinction"],
            "communicativeFunctionsIntroduced": ["comm_a2_13_buying_medicine_pharmacy"],
            "communicativeFunctionsPracticed": ["comm_a1_22_making_purchases"],
            "communicativeFunctionsReviewed": ["comm_a1_16_greetings_time_of_day"],
            "newProductiveLemmaTarget": 7, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_health_medicine", "lex_domain_commerce_transactions"],
            "previousVocabularyReused": ["жор", "эм", "авах", "хямд", "ижил", "баярлалаа"],
            "readingObjective": "",
            "listeningObjective": "Understand pharmacist verifying identity and explaining domestic equivalent brand.",
            "writingObjective": "",
            "spokenProductionObjective": "Conduct transaction: 'Энэ жорын дагуу эмүүдийг авъя. Үнэтэй импортын эмний оронд ижил найрлагатай монгол эм байна уу?'.",
            "registerTarget": "Courteous healthcare commercial register",
            "pragmaticTarget": "Inquiring about generic equivalents (ижил найрлагатай эм) professionally and cost-effectively.",
            "prerequisiteLessonIds": ["les_a2_85_02_medication_package_insert_reading", "les_a2_85_03_pharmacist_advice_acoustic_listening"],
            "reviewsLessonIds": ["les_a1_22_05_making_purchases_simulation"],
            "reviewsUnitIds": ["unit_a1_22_shopping_transactions_making_purch"],
            "reviewReason": "Transforms general store buying routines into specialized pharmacy transactions.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Provide realistic dialogue between customer seeking cold relief and helpful pharmacist.",
            "successCriteria": [
                "Conducts a complete purchase of 2 medications specifying symptoms or prescription",
                "Verifies and repeats back dosage regimen accurately"
            ],
            "masteryEvidence": "Completes a 5-turn pharmacy roleplay with zero misunderstandings.",
            "recommendedExerciseModalities": ["role-play response", "dialogue_completion", "listening_comprehension"]
        }
    ])

    return lessons
