"""
Section 4 Generator Part 1 (Units 93 - 95): 14 Lessons
93: Personality Traits & Moral Character (4 lessons)
94: Childhood & Hometown Recollections: Narrative Past -v (5 lessons)
95: Past Vacations & Countryside Travel: Witnessed Past -laa4 (5 lessons)
"""

import json
from typing import List, Dict, Any

def get_sec04_part1_lessons(u_map: Dict[int, Any]) -> List[Dict[str, Any]]:
    lessons: List[Dict[str, Any]] = []

    # =========================================================================
    # UNIT 93: Personality Traits & Moral Character (pos 93)
    # 4 Lessons | Targets: ProdLem=19, RecLem=9, ProdExp=5, RecExp=3
    # Budget: (7,3,2,1), (5,3,1,1), (0,0,0,0), (7,3,2,1) = (19, 9, 5, 3)
    # =========================================================================
    u = u_map[93]
    uid = u["unitId"]
    lessons.extend([
        {
            "lessonId": "les_a2_93_01_personality_character_traits_lexicon",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 1,
            "title": "Kind, Honest & Modest: Personality Traits & Moral Character",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Introduce personality, temperament, and moral character vocabulary (тусархаг, шударга, даруу, нийтэч, хөдөлмөрч, тайван, зан ааш, төлөв даруу).",
            "communicativeOutcome": "Describe a person's inner virtues, work ethic, social disposition, and temperament in personal or professional appraisals.",
            "objectivesIntroduced": ["obj_a2_93_01_personality_traits_lexicon"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_a2_92_01_physical_appearance_lexicon"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_noun_phrase_attributive_adjective", "gram_a1_predicate_adjective_nominal"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_consonant_clusters"], "phonologyReviewed": ["phono_a1_vowel_reduction_non_initial"],
            "communicativeFunctionsIntroduced": ["comm_a2_03_describing_personality_character"],
            "communicativeFunctionsPracticed": ["comm_a2_02_describing_appearance_clothing"], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 7, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_people_descriptions", "lex_domain_social_interaction"],
            "previousVocabularyReused": ["хүн", "сайн", "найз", "зан", "ажил", "байх"],
            "readingObjective": "Read letters of recommendation describing an applicant's integrity, diligence, and collegiality.",
            "listeningObjective": "Understand an employer praising an employee's honesty and teamwork.",
            "writingObjective": "List 6 moral character adjectives with short English definitions.",
            "spokenProductionObjective": "Describe a friend's character: 'Манай найз маш тусархаг, шударга, бас их даруухан зантай'.",
            "registerTarget": "Standard interpersonal character appraisal register",
            "pragmaticTarget": "Using cultural virtue concepts (даруухан, тусархаг) to praise peers respectfully.",
            "prerequisiteLessonIds": ["les_a2_92_01_physical_appearance_features_lexicon"],
            "reviewsLessonIds": ["les_a1_21_01_attributive_adjectives_intro"],
            "reviewsUnitIds": ["unit_a1_21_attributive_predicative_adjective"],
            "reviewReason": "Expands simple adjectives (сайн, муу) to rich characterization traits.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Pronounce moral and personality adjectives clearly.",
            "successCriteria": [
                "Defines тусархаг (helpful), шударга (honest/fair), нийтэч (sociable), хөдөлмөрч (hardworking)",
                "Forms predicative character descriptions: 'Тэр хүн их төлөв даруу'"
            ],
            "masteryEvidence": "Accurately characterizes 4 coworkers across diligence, honesty, and social disposition.",
            "recommendedExerciseModalities": ["categorization", "contextual_cloze", "matching"]
        },
        {
            "lessonId": "les_a2_93_02_character_reference_letters_reading",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 2,
            "title": "Deciphering Recommendation Letters & Character References",
            "lessonType": "reading_development",
            "primaryPurpose": "Develop reading comprehension of formal character appraisals (тодорхойлолт), academic reference letters, and workplace peer evaluations.",
            "communicativeOutcome": "Inspect a professional recommendation letter, identify praised virtues (хариуцлагатай, нямбай, хамт олонч), and evaluate candidate suitability.",
            "objectivesIntroduced": ["obj_a2_93_02_read_recommendation_letters"],
            "objectivesPracticed": ["obj_a2_93_01_personality_traits_lexicon"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_genitive_possession", "gram_a1_predicate_adjective_nominal"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_03_describing_personality_character"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_workplace_occupations", "lex_domain_people_descriptions"],
            "previousVocabularyReused": ["тодорхойлолт", "ажиллах", "хамт олон", "хариуцлага", "хүндэтгэх", "нөхөрсөг"],
            "readingObjective": "Extract candidate strengths (нягт нямбай, итгэл найдвартай) and supervisor endorsements from a 120-word reference letter.",
            "listeningObjective": "",
            "writingObjective": "Transcribe 3 core virtues from a reference text into a summary evaluation card.",
            "spokenProductionObjective": "Explain to a hiring manager why the recommended candidate is dependable.",
            "registerTarget": "Formal workplace appraisal and recommendation register",
            "pragmaticTarget": "Understanding formal praise idioms in Mongolian corporate culture.",
            "prerequisiteLessonIds": ["les_a2_93_01_personality_character_traits_lexicon"],
            "reviewsLessonIds": ["les_a1_61_02_reading_workplace_profiles"],
            "reviewsUnitIds": ["unit_a1_61_workplace_occupations_professions_"],
            "reviewReason": "Deepens occupational reading from duties to personal ethics and character.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Read formal recommendation text aloud.",
            "successCriteria": [
                "Identifies key professional attributes: хариуцлагатай (responsible), нямбай (meticulous)",
                "Determines supervisor's overall endorsement sentiment"
            ],
            "masteryEvidence": "Answers 4 comprehension questions on an authentic Mongolian character reference letter.",
            "recommendedExerciseModalities": ["reading_comprehension", "contextual_cloze", "categorization"]
        },
        {
            "lessonId": "les_a2_93_03_character_impressions_acoustic_listening",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 3,
            "title": "Acoustic Lab: Conversational Impressions & Friendship Confidences",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop acoustic listening comprehension of two close friends sharing personal impressions of a new roommate, colleague, or prospective in-law.",
            "communicativeOutcome": "Extract nuanced character assessments (whether someone is cheerful, short-tempered, trustworthy, or reserved) from candid audio conversations.",
            "objectivesIntroduced": ["obj_a2_93_03_decode_character_impressions"],
            "objectivesPracticed": ["obj_a2_93_01_personality_traits_lexicon"], "objectivesReviewed": ["obj_a2_77_01_enclitic_ni_marking"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a2_possessive_third_person_enclitic_ni", "gram_a1_converb_coordinating_j_ch"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_vowel_reduction_non_initial"], "phonologyReviewed": ["phono_a1_nasal_vowels"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_03_describing_personality_character"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_people_descriptions", "lex_domain_social_interaction"],
            "previousVocabularyReused": ["найз", "хүн", "зан", "хөгжилтэй", "ярих", "итгэх"],
            "readingObjective": "",
            "listeningObjective": "Identify specific temperament traits ('Тэр залуу их хөгжилтэй, гэхдээ хааяа түргэн зантай') from candid dialogue audio.",
            "writingObjective": "",
            "spokenProductionObjective": "Explain to a peer why the speaker trusts their new colleague.",
            "registerTarget": "Informal intimate interpersonal register",
            "pragmaticTarget": "Deciphering colloquial character descriptors with balanced objectivity.",
            "prerequisiteLessonIds": ["les_a2_93_01_personality_character_traits_lexicon"],
            "reviewsLessonIds": ["les_a1_77_03_product_comparison_listening"],
            "reviewsUnitIds": ["unit_a2_77_third_person_possessive_enclitic_th"],
            "reviewReason": "Applies third-person enclitic 'нь' listening to character appraisals ('зан нь сайхан').",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Natural conversational cadence between two friends discussing mutual acquaintances.",
            "successCriteria": [
                "Identifies both positive strengths and mild character flaws from audio stream",
                "Extracts speaker's overall verdict on candidate's trustworthiness"
            ],
            "masteryEvidence": "Accurately profiles 3 individuals based on overheard conversational evaluations.",
            "recommendedExerciseModalities": ["listening_comprehension", "phonetic_discrimination", "categorization"]
        },
        {
            "lessonId": "les_a2_93_04_peer_appraisal_colleague_dialogue",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 4,
            "title": "Peer Review: Discussing Coworker Strengths & Team Dynamics",
            "lessonType": "dialogue_work",
            "primaryPurpose": "Master spoken communication for evaluating coworkers, discussing team collaboration, and describing interpersonal dynamics in a workplace setting.",
            "communicativeOutcome": "Participate in a workplace peer review or team debrief, articulating colleagues' strengths and interpersonal qualities constructively.",
            "objectivesIntroduced": ["obj_a2_93_04_peer_appraisal_dialogue"],
            "objectivesPracticed": ["obj_a2_93_01_personality_traits_lexicon", "obj_a2_93_02_read_recommendation_letters"],
            "objectivesReviewed": ["obj_a1_16_01_greet_time_of_day"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_converb_coordinating_j_ch", "gram_a1_predicate_adjective_nominal"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_intonation_polite"], "phonologyReviewed": ["phono_a1_vowel_length_distinction"],
            "communicativeFunctionsIntroduced": ["comm_a2_03_describing_personality_character"],
            "communicativeFunctionsPracticed": ["comm_a1_16_greetings_time_of_day"],
            "communicativeFunctionsReviewed": ["comm_a1_13_apologies_politeness"],
            "newProductiveLemmaTarget": 7, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_workplace_occupations", "lex_domain_people_descriptions"],
            "previousVocabularyReused": ["баг", "ажиллах", "санаа", "нээлттэй", "найдвартай", "туслах"],
            "readingObjective": "",
            "listeningObjective": "Understand team leader asking for honest feedback on project collaboration.",
            "writingObjective": "",
            "spokenProductionObjective": "Provide balanced feedback: 'Болд бол маш хариуцлагатай, нямбай ажилтан. Хамт олонтойгоо нийтэч, тусархаг харьцдаг'.",
            "registerTarget": "Professional collaborative workplace register",
            "pragmaticTarget": "Offering constructive, balanced praise that reinforces team harmony.",
            "prerequisiteLessonIds": ["les_a2_93_02_character_reference_letters_reading", "les_a2_93_03_character_impressions_acoustic_listening"],
            "reviewsLessonIds": ["les_a1_61_05_workplace_duties_dialogue"],
            "reviewsUnitIds": ["unit_a1_61_workplace_occupations_professions_"],
            "reviewReason": "Transitions workplace talk from task descriptions to professional team appraisal.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Polished, diplomatic workplace dialogue between two respectful colleagues.",
            "successCriteria": [
                "Articulates coworker strengths using at least 3 distinct character adjectives",
                "Maintains respectful, encouraging tone throughout professional exchange"
            ],
            "masteryEvidence": "Conducts a 5-turn peer evaluation dialogue highlighting colleague contributions seamlessly.",
            "recommendedExerciseModalities": ["role-play response", "dialogue_completion", "listening_comprehension"]
        }
    ])

    # =========================================================================
    # UNIT 94: Childhood & Hometown Recollections: Narrative Past -v (pos 94)
    # 5 Lessons | Targets: ProdLem=21, RecLem=10, ProdExp=5, RecExp=3
    # Budget: (5,2,1,1), (6,3,1,1), (5,3,2,1), (0,0,0,0), (5,2,1,0) = (21, 10, 5, 3)
    # =========================================================================
    u = u_map[94]
    uid = u["unitId"]
    lessons.extend([
        {
            "lessonId": "les_a2_94_01_past_narrative_v_intro",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 1,
            "title": "Stories of the Past: The Narrative Past Tense (-в)",
            "lessonType": "grammar_introduction",
            "primaryPurpose": "Introduce the literary and formal narrative past tense suffix (-в / -эв / -ов / -өв) used in storytelling, biographical chronicles, historical narratives, and written recollections.",
            "communicativeOutcome": "Narrate chronological life events in formal or literary style: 'Би хөдөө өсөв' (I grew up in the countryside), 'Тэр сургуулиа төгсөв' (He graduated).",
            "objectivesIntroduced": ["obj_a2_94_01_narrative_past_v"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_a2_93_01_personality_traits_lexicon"],
            "grammarIntroduced": ["gram_a2_verb_past_narrative_v"],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_verb_tense_past_witnessed_laa", "gram_a1_verb_tense_past_perfective_san"],
            "phonologyIntroduced": ["phono_a2_narrative_past_v_suffixation"],
            "phonologyPracticed": ["phono_a1_masculine_feminine_harmony"], "phonologyReviewed": ["phono_a1_consonant_clusters"],
            "communicativeFunctionsIntroduced": ["comm_a2_07_childhood_hometown_memories"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_personal_history", "lex_domain_biography_chronology"],
            "previousVocabularyReused": ["төрөх", "өсөх", "амьдрах", "сургууль", "явах", "ирэх"],
            "readingObjective": "Read an excerpt from a famous Mongolian author's childhood biography written with narrative past -в.",
            "listeningObjective": "Identify narrative past verbs ending in -в in audio storytelling.",
            "writingObjective": "Transform 4 conversational past sentences into formal narrative style using -в.",
            "spokenProductionObjective": "Recite a short biographical sequence: 'Миний өвөө 1945 онд цэрэгт татагдав. Дараа нь сумандаа багшлав'.",
            "registerTarget": "Formal narrative and written biographical register",
            "pragmaticTarget": "Using the narrative past (-в) for structured, authoritative biographical recounting.",
            "prerequisiteLessonIds": ["les_a2_93_01_personality_character_traits_lexicon"],
            "reviewsLessonIds": ["les_a1_41_01_witnessed_past_laa_intro"],
            "reviewsUnitIds": ["unit_a1_41_witnessed_past_verbal_tense_suffix_"],
            "reviewReason": "Contrasts spoken witnessed past (-лаа4) with formal written narrative past (-в).",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Model crisp syllable-final /w/ or /v/ articulation in narrative verbs.",
            "successCriteria": [
                "Attaches -в or epenthetic vowel + -в according to consonant/vowel phonotactics",
                "Contrasts narrative past -в with colloquial past -лаа appropriately"
            ],
            "masteryEvidence": "Produces 'Би багадаа голын хөвөөнд тоглож өсөв' accurately in a written narrative.",
            "recommendedExerciseModalities": ["suffix_selection", "sentence_transformation", "matching"]
        },
        {
            "lessonId": "les_a2_94_02_childhood_pastimes_hometown_lexicon",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 2,
            "title": "Riverbanks & Summer Pastures: Childhood Memories & Nostalgia",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Introduce childhood pastimes, rural nostalgia, and hometown vocabulary (төрсөн нутаг, бага нас, дурсамж, зуслан, голын хөвөө, шагайн наадам, хурга хариулах).",
            "communicativeOutcome": "Recount nostalgic childhood memories, summer vacations at grandparents' pastures, herding lambs, and playing traditional games.",
            "objectivesIntroduced": ["obj_a2_94_02_childhood_nostalgia_lexicon"],
            "objectivesPracticed": ["obj_a2_94_01_narrative_past_v"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_verb_past_narrative_v"],
            "grammarReviewed": ["gram_a1_case_dative_locative_location", "gram_a1_case_comitative_association"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_consonant_clusters"], "phonologyReviewed": ["phono_a1_vowel_reduction_non_initial"],
            "communicativeFunctionsIntroduced": ["comm_a2_07_childhood_hometown_memories"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_personal_history", "lex_domain_countryside_nature"],
            "previousVocabularyReused": ["хүүхэд", "нас", "хөдөө", "зун", "тоглох", "өвөө"],
            "readingObjective": "Read a poetic essay on memories of nomadic childhood summers in Arkhangai.",
            "listeningObjective": "Understand an interviewee reminiscing about learning to ride horses at age six.",
            "writingObjective": "List 5 traditional childhood activities in Cyrillic.",
            "spokenProductionObjective": "Share a childhood memory: 'Би багадаа зун бүр өвөөгийнхөө хөдөө очиж хурга хариулдаг байсан'.",
            "registerTarget": "Warm reflective nostalgic narrative register",
            "pragmaticTarget": "Evoking authentic Mongolian pastoral memories with heartfelt cultural resonance.",
            "prerequisiteLessonIds": ["les_a2_94_01_past_narrative_v_intro"],
            "reviewsLessonIds": ["les_a1_56_01_countryside_landscape_intro"],
            "reviewsUnitIds": ["unit_a1_56_countryside_landscapes_pastoral_ge"],
            "reviewReason": "Spirals countryside landscape terms into personal autobiographical memories.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Pronounce nostalgic childhood vocabulary clearly.",
            "successCriteria": [
                "Defines бага нас (childhood), дурсамж (memory), төрсөн нутаг (birthplace/hometown)",
                "Narrates childhood episodes using narrative past verbs"
            ],
            "masteryEvidence": "Accurately describes 4 childhood memories using rich rural and play terminology.",
            "recommendedExerciseModalities": ["categorization", "contextual_cloze", "matching"]
        },
        {
            "lessonId": "les_a2_94_03_reminiscing_with_friends_dialogue",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 3,
            "title": "School Reunion: Reminiscing About Childhood & Old Classmates",
            "lessonType": "dialogue_work",
            "primaryPurpose": "Develop spoken communicative fluency for reminiscing with old classmates: discussing childhood mischief, favorite teachers, schoolyard games, and hometown changes.",
            "communicativeOutcome": "Engage in an extended nostalgic conversation with an old friend or classmate, exchanging memories of childhood events and school experiences.",
            "objectivesIntroduced": ["obj_a2_94_03_reminiscing_dialogue"],
            "objectivesPracticed": ["obj_a2_94_01_narrative_past_v", "obj_a2_94_02_childhood_nostalgia_lexicon"],
            "objectivesReviewed": ["obj_a1_16_01_greet_time_of_day"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_verb_past_narrative_v"],
            "grammarReviewed": ["gram_a1_verb_tense_past_perfective_san", "gram_a1_converb_coordinating_j_ch"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_intonation_polite"], "phonologyReviewed": ["phono_a1_diphthongs"],
            "communicativeFunctionsIntroduced": ["comm_a2_07_childhood_hometown_memories"],
            "communicativeFunctionsPracticed": ["comm_a1_16_greetings_time_of_day"],
            "communicativeFunctionsReviewed": ["comm_a1_13_apologies_politeness"],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_personal_history", "lex_domain_social_interaction"],
            "previousVocabularyReused": ["сургууль", "багш", "анги", "санах", "хөгжилтэй", "өөрчлөгдөх"],
            "readingObjective": "",
            "listeningObjective": "Understand classmate recalling a humorous childhood soccer mishap.",
            "writingObjective": "",
            "spokenProductionObjective": "Reminisce: 'Чи 10 жилийн өмнөх тэр зуныг санаж байна уу? Бид хоёр өдөржин гол дээр сэлдэг байсан сан'.",
            "registerTarget": "Warm intimate conversational nostalgic register",
            "pragmaticTarget": "Using empathetic conversational tags ('санаж байна уу?', 'тийм шүү') in shared reminiscence.",
            "prerequisiteLessonIds": ["les_a2_94_02_childhood_pastimes_hometown_lexicon"],
            "reviewsLessonIds": ["les_a1_43_05_past_weekend_activities_dialogue"],
            "reviewsUnitIds": ["unit_a1_43_past_witnessed_conversational_narr"],
            "reviewReason": "Deepens past narrative dialogue from recent weekends to lifelong childhood memories.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Lively laughter, fond nostalgic pauses, and warm colloquial backchanneling between friends.",
            "successCriteria": [
                "Prompts and responds to shared memories using past forms accurately",
                "Expresses nostalgic sentiment using appropriate conversational markers"
            ],
            "masteryEvidence": "Conducts a 5-turn reunion dialogue reminiscing about elementary school days with ease.",
            "recommendedExerciseModalities": ["role-play response", "dialogue_completion", "listening_comprehension"]
        },
        {
            "lessonId": "les_a2_94_04_radio_memoir_acoustic_listening",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 4,
            "title": "Acoustic Lab: Radio Memoirs & Hometown Audio Essays",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop acoustic listening comprehension of professional radio essayists narrating lyrical childhood memoirs set in historic aimags and countryside valleys.",
            "communicativeOutcome": "Extract chronological life milestones, regional details, and emotional reflections from a literary radio broadcast.",
            "objectivesIntroduced": ["obj_a2_94_04_decode_radio_memoirs"],
            "objectivesPracticed": ["obj_a2_94_01_narrative_past_v"], "objectivesReviewed": ["obj_a1_41_01_witnessed_past_laa"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a2_verb_past_narrative_v", "gram_a1_converb_sequential_aad"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_vowel_reduction_non_initial"], "phonologyReviewed": ["phono_a1_nasal_vowels"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_07_childhood_hometown_memories"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_personal_history", "lex_domain_countryside_nature"],
            "previousVocabularyReused": ["нутаг", "уул", "гол", "хүүхэд", "сонсох", "сэтгэл"],
            "readingObjective": "",
            "listeningObjective": "Identify specific narrative past forms (-в) and geographic landmarks in a 90-second radio memoir.",
            "writingObjective": "",
            "spokenProductionObjective": "Summarize the radio narrator's childhood memory of winter horses in 3 Mongolian sentences.",
            "registerTarget": "High literary and broadcast cultural memoir register",
            "pragmaticTarget": "Parsing expressive intonation, poetic pauses, and rich descriptive adjectives in spoken literary Mongolian.",
            "prerequisiteLessonIds": ["les_a2_94_02_childhood_pastimes_hometown_lexicon"],
            "reviewsLessonIds": ["les_a1_76_04_reading_family_memoirs_letters"],
            "reviewsUnitIds": ["unit_a2_76_reflexive_case_combinations_"],
            "reviewReason": "Elevates listening stamina to poetic and broadcast narrative prose.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Deep, lyrical narrator voice with evocative traditional morin khuur background chords.",
            "successCriteria": [
                "Identifies narrator's childhood valley and historical timeframe from audio",
                "Extracts at least 3 narrative past verbs ending in -в from the recording"
            ],
            "masteryEvidence": "Accurately maps out narrator's childhood memories onto a chronological milestone timeline.",
            "recommendedExerciseModalities": ["listening_comprehension", "dictation", "sequencing"]
        },
        {
            "lessonId": "les_a2_94_05_childhood_memoir_essay_writing",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 5,
            "title": "My Native Land: Writing a Lyrical Hometown Recollection Essay",
            "lessonType": "grammar_guided_practice",
            "primaryPurpose": "Synthesize narrative past tense (-в), nostalgic childhood vocabulary, and sequential converbs into a written autobiographical essay (Миний төрсөн нутаг ба бага нас).",
            "communicativeOutcome": "Draft a 6-sentence personal memoir describing your birthplace, early childhood memories, and how your hometown has evolved.",
            "objectivesIntroduced": ["obj_a2_94_05_write_childhood_memoir"],
            "objectivesPracticed": ["obj_a2_94_01_narrative_past_v", "obj_a2_94_02_childhood_nostalgia_lexicon"],
            "objectivesReviewed": ["obj_a1_50_01_sequential_converb"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_verb_past_narrative_v"],
            "grammarReviewed": ["gram_a1_converb_sequential_aad", "gram_a1_case_ablative_origin"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_07_childhood_hometown_memories"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_personal_history", "lex_domain_countryside_nature"],
            "previousVocabularyReused": ["эссэ", "бичих", "нутаг", "бага нас", "өсөх", "дурсамж"],
            "readingObjective": "Review a classic student model memoir to observe opening rhetorical hooks.",
            "listeningObjective": "",
            "writingObjective": "Draft a 6-sentence nostalgic essay utilizing at least 3 narrative past verbs (-в) and 2 sequential converbs.",
            "spokenProductionObjective": "",
            "registerTarget": "Written personal literary narrative register",
            "pragmaticTarget": "Expressing deep affection for one's roots using traditional Mongolian literary stylistic conventions.",
            "prerequisiteLessonIds": ["les_a2_94_03_reminiscing_with_friends_dialogue", "les_a2_94_04_radio_memoir_acoustic_listening"],
            "reviewsLessonIds": ["les_a1_50_01_sequential_converb_aad"],
            "reviewsUnitIds": ["unit_a1_50_sequential_converb_clause_connector"],
            "reviewReason": "Combines sequential converbs (-аад) with narrative past verbs (-в) for structured storytelling.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Audio read-back of written autobiographical essay.",
            "successCriteria": [
                "Produces written essay with at least 3 correctly formed narrative past verbs in -в",
                "Includes sensory descriptions of nature, family, or childhood games"
            ],
            "masteryEvidence": "Drafts 'Би Хөвсгөлийн үзэсгэлэнт байгальд төрж өсөв. Багадаа морь унаж, нуурын хөвөөгөөр гүйж өнгөрүүлэв...' flawlessly.",
            "recommendedExerciseModalities": ["short-answer writing", "sentence construction", "error correction"]
        }
    ])

    # =========================================================================
    # UNIT 95: Past Vacations & Countryside Travel: Witnessed Past -laa4 (pos 95)
    # 5 Lessons | Targets: ProdLem=21, RecLem=10, ProdExp=5, RecExp=3
    # Budget: (5,2,1,1), (6,3,1,1), (5,3,2,1), (0,0,0,0), (5,2,1,0) = (21, 10, 5, 3)
    # =========================================================================
    u = u_map[95]
    uid = u["unitId"]
    lessons.extend([
        {
            "lessonId": "les_a2_95_01_witnessed_past_travel_accounts_intro",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 1,
            "title": "We Arrived at Khuvsgul: Recent Travel Narratives with -лаа4",
            "lessonType": "grammar_introduction",
            "primaryPurpose": "Deepen and consolidate the witnessed past tense (-лаа4 / -лээ / -лоо / -лөө) for vivid, immediate personal travel narratives, personal sightings, and recent discoveries.",
            "communicativeOutcome": "Recount a recent vacation or countryside journey with conversational immediacy: 'Бид өчигдөр орой Хөвсгөл нуурын эрэгт майхнаа барилаа' (We pitched our tent on Khuvsgul shore last night).",
            "objectivesIntroduced": ["obj_a2_95_01_witnessed_past_travel_expansion"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_a2_94_01_narrative_past_v"],
            "grammarIntroduced": ["gram_a2_verb_past_recent_witnessed_laa"],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_dative_locative_location", "gram_a1_case_instrumental_transport_language"],
            "phonologyIntroduced": ["phono_a2_witnessed_past_vivid_intonation"],
            "phonologyPracticed": ["phono_a1_masculine_feminine_harmony"], "phonologyReviewed": ["phono_a1_long_vowels"],
            "communicativeFunctionsIntroduced": ["comm_a2_08_vacation_travel_experiences"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_travel_transport", "lex_domain_recreation_leisure"],
            "previousVocabularyReused": ["явах", "хүрэх", "үзэх", "буух", "хонох", "сайхан"],
            "readingObjective": "Read a contemporary travel blog post recounting a 3-day road trip to Terelj National Park.",
            "listeningObjective": "Identify verbs in -лаа4 used to describe recent discoveries and arrivals in travel podcasts.",
            "writingObjective": "Write 4 sentences describing yesterday's road trip milestones using -лаа4.",
            "spokenProductionObjective": "Explain recent trip: 'Бид өглөө эрт гараад, өдөр нь Хархоринд хүрлээ'.",
            "registerTarget": "Vivid conversational recount register",
            "pragmaticTarget": "Conveying excitement and fresh, first-hand witness experiences in travel stories.",
            "prerequisiteLessonIds": ["les_a2_94_01_past_narrative_v_intro"],
            "reviewsLessonIds": ["les_a1_41_01_witnessed_past_laa_intro"],
            "reviewsUnitIds": ["unit_a1_41_witnessed_past_verbal_tense_suffix_"],
            "reviewReason": "Expands immediate daily past tense into extended multi-day travel itineraries.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Model energetic conversational intonation on witnessed past predicates.",
            "successCriteria": [
                "Selects correct harmonic variant of -лаа4 based on preceding vowel",
                "Uses -лаа4 to convey personally experienced, fresh travel events"
            ],
            "masteryEvidence": "Produces 'Бид нуурын хөвөөнд хоноод, өглөө нь нар мандахыг харлаа' effortlessly.",
            "recommendedExerciseModalities": ["suffix_selection", "sentence_construction", "matching"]
        },
        {
            "lessonId": "les_a2_95_02_countryside_expedition_camping_lexicon",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 2,
            "title": "Tents, Campfires & Trails: Wilderness Expedition Vocabulary",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Introduce countryside camping, expedition, and nature travel vocabulary (аялал, майхан барих, түүдэг гал, үүргэвч, дурандах, жимээр алхах, нар мандах, жаргах).",
            "communicativeOutcome": "Describe wilderness camping, pitching a tent, gathering firewood, making a campfire, watching the sunrise, and trekking forest trails.",
            "objectivesIntroduced": ["obj_a2_95_02_camping_wilderness_lexicon"],
            "objectivesPracticed": ["obj_a2_95_01_witnessed_past_travel_expansion"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_verb_past_recent_witnessed_laa"],
            "grammarReviewed": ["gram_a1_case_instrumental_transport_language", "gram_a1_spatial_postpositions_deeree_door"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_consonant_clusters"], "phonologyReviewed": ["phono_a1_vowel_reduction_non_initial"],
            "communicativeFunctionsIntroduced": ["comm_a2_08_vacation_travel_experiences"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_travel_transport", "lex_domain_countryside_nature"],
            "previousVocabularyReused": ["гал", "майхан", "уул", "ой", "алхах", "нар"],
            "readingObjective": "Read a wilderness camping guide outlining Leave-No-Trace principles in Mongolian national parks.",
            "listeningObjective": "Understand outdoor guide briefing hikers on campsite selection and firewood gathering.",
            "writingObjective": "List 5 essential camping equipment items in Cyrillic.",
            "spokenProductionObjective": "Describe camping activities: 'Бид голын дэргэд майхнаа бариад, орой нь түүдэг гал асаалаа'.",
            "registerTarget": "Outdoor adventure and recreation register",
            "pragmaticTarget": "Understanding campfire safety and ecological respect when camping in the Mongolian steppe.",
            "prerequisiteLessonIds": ["les_a2_95_01_witnessed_past_travel_accounts_intro"],
            "reviewsLessonIds": ["les_a1_56_01_countryside_landscape_intro"],
            "reviewsUnitIds": ["unit_a1_56_countryside_landscapes_pastoral_ge"],
            "reviewReason": "Connects pastoral landscapes with active outdoor adventure tourism.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Pronounce wilderness and camping expedition terms clearly.",
            "successCriteria": [
                "Defines майхан барих (pitch a tent), түүдэг гал (campfire), үүргэвч (backpack)",
                "Forms complete sentences describing wilderness travel actions"
            ],
            "masteryEvidence": "Accurately describes 4 stages of setting up an outdoor camp in Mongolian.",
            "recommendedExerciseModalities": ["categorization", "contextual_cloze", "matching"]
        },
        {
            "lessonId": "les_a2_95_03_vacation_highlights_exchange_dialogue",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 3,
            "title": "Back from the Gobi: Exchanging Vacation Highlights with Friends",
            "lessonType": "dialogue_work",
            "primaryPurpose": "Master spoken communication for sharing vacation adventures: discussing route highlights, bumpy off-road tracks, homestays with nomadic herders, and scenic canyons.",
            "communicativeOutcome": "Share vacation highlights with a friend, inquire about their travels, describe natural sights visited, and recommend off-the-beaten-path destinations.",
            "objectivesIntroduced": ["obj_a2_95_03_vacation_highlights_dialogue"],
            "objectivesPracticed": ["obj_a2_95_01_witnessed_past_travel_expansion", "obj_a2_95_02_camping_wilderness_lexicon"],
            "objectivesReviewed": ["obj_a1_16_01_greet_time_of_day"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_verb_past_recent_witnessed_laa"],
            "grammarReviewed": ["gram_a1_case_ablative_origin", "gram_a1_converb_coordinating_j_ch"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_intonation_polite"], "phonologyReviewed": ["phono_a1_vowel_length_distinction"],
            "communicativeFunctionsIntroduced": ["comm_a2_08_vacation_travel_experiences"],
            "communicativeFunctionsPracticed": ["comm_a1_16_greetings_time_of_day"],
            "communicativeFunctionsReviewed": ["comm_a1_13_apologies_politeness"],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_travel_transport", "lex_domain_social_interaction"],
            "previousVocabularyReused": ["аялал", "говь", "элс", "үзэх", "сонин", "гоё"],
            "readingObjective": "",
            "listeningObjective": "Understand travel enthusiast enthusiastically describing camel riding across Khongor Sand Dunes.",
            "writingObjective": "",
            "spokenProductionObjective": "Recount vacation highlights: 'Бид Говь гурван сайханд очоод, мөст хавцлаар алхлаа. Замдаа олон зэрлэг ан амьтан харлаа'.",
            "registerTarget": "Enthusiastic friendly conversational travel register",
            "pragmaticTarget": "Sharing travel stories with expressive adjectives and authentic enthusiasm.",
            "prerequisiteLessonIds": ["les_a2_95_02_countryside_expedition_camping_lexicon"],
            "reviewsLessonIds": ["les_a1_43_05_past_weekend_activities_dialogue"],
            "reviewsUnitIds": ["unit_a1_43_past_witnessed_conversational_narr"],
            "reviewReason": "Expands weekend recreation dialogue into comprehensive multi-provincial expedition debriefs.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Warm, animated conversational dialogue between two friends back from summer holidays.",
            "successCriteria": [
                "Describes itinerary, transport, and notable scenery using past forms accurately",
                "Asks partner engaged follow-up questions about their trip"
            ],
            "masteryEvidence": "Conducts a 5-turn vacation sharing dialogue highlighting 3 destinations and activities.",
            "recommendedExerciseModalities": ["role-play response", "dialogue_completion", "listening_comprehension"]
        },
        {
            "lessonId": "les_a2_95_04_travel_podcast_acoustic_listening",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 4,
            "title": "Acoustic Lab: Travel Podcast on Off-Road Steppe Expeditions",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop acoustic listening comprehension of an authentic travel podcast detailing off-road 4WD challenges, river crossings, flat tires, and hospitable nomadic rescues.",
            "communicativeOutcome": "Extract travel route details, mechanical mishaps, and cultural interactions from an unscripted travel podcast episode.",
            "objectivesIntroduced": ["obj_a2_95_04_decode_travel_podcasts"],
            "objectivesPracticed": ["obj_a2_95_01_witnessed_past_travel_expansion"], "objectivesReviewed": ["obj_a1_41_01_witnessed_past_laa"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a2_verb_past_recent_witnessed_laa", "gram_a1_converb_coordinating_j_ch"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_vowel_reduction_non_initial"], "phonologyReviewed": ["phono_a1_nasal_vowels"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_08_vacation_travel_experiences"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_travel_transport"],
            "previousVocabularyReused": ["машин", "зам", "гол", "гарах", "туслах", "айл"],
            "readingObjective": "",
            "listeningObjective": "Identify specific travel mishaps ('Машины дугуй хагараад, нутгийн малчин ах ирж тусаллаа') from podcast audio.",
            "writingObjective": "",
            "spokenProductionObjective": "Summarize the podcast's river crossing story to a classmate in 3 sentences.",
            "registerTarget": "Dynamic audio broadcast travel storytelling register",
            "pragmaticTarget": "Parsing lively narrative speech punctuated with humor and natural sound effects.",
            "prerequisiteLessonIds": ["les_a2_95_02_countryside_expedition_camping_lexicon"],
            "reviewsLessonIds": ["les_a1_72_02_commuter_acoustic_decoding_lab"],
            "reviewsUnitIds": ["unit_a2_72_urban_transit_capstone_navigating_the"],
            "reviewReason": "Expands transport listening from urban buses to off-road steppe journeys.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Realistic podcast audio featuring two travel hosts sharing road trip anecdotes with engine ambiance.",
            "successCriteria": [
                "Identifies the travel destination and primary challenge encountered from audio",
                "Extracts how the traveling companions resolved their mechanical hurdle"
            ],
            "masteryEvidence": "Accurately answers 5 comprehension questions following a 2-minute travel podcast excerpt.",
            "recommendedExerciseModalities": ["listening_comprehension", "phonetic_discrimination", "sequencing"]
        },
        {
            "lessonId": "les_a2_95_05_travel_blog_post_writing",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 5,
            "title": "On the Road: Composing a Countryside Travel Blog & Photo Log",
            "lessonType": "grammar_guided_practice",
            "primaryPurpose": "Synthesize witnessed past tense (-лаа4), wilderness travel vocabulary, and descriptive adjectives into a vibrant written travel blog post.",
            "communicativeOutcome": "Write a 6-sentence travel blog post recounting a journey across the countryside, detailing route, campsite, wildlife, and memories.",
            "objectivesIntroduced": ["obj_a2_95_05_write_travel_blog"],
            "objectivesPracticed": ["obj_a2_95_01_witnessed_past_travel_expansion", "obj_a2_95_02_camping_wilderness_lexicon"],
            "objectivesReviewed": ["obj_a1_50_01_sequential_converb"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_verb_past_recent_witnessed_laa"],
            "grammarReviewed": ["gram_a1_converb_sequential_aad", "gram_a1_noun_phrase_attributive_adjective"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_08_vacation_travel_experiences"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 2, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_travel_transport", "lex_domain_countryside_nature"],
            "previousVocabularyReused": ["блог", "зураг", "аялал", "нуур", "уул", "дурсамж"],
            "readingObjective": "Read a popular Mongolian travel blog entry for structure and photo captioning style.",
            "listeningObjective": "",
            "writingObjective": "Draft a 6-sentence travel blog entry with vivid descriptions utilizing at least 3 verbs in -лаа4.",
            "spokenProductionObjective": "",
            "registerTarget": "Informal engaging digital travel writing register",
            "pragmaticTarget": "Engaging readers with captivating travel anecdotes and sensory scenery details.",
            "prerequisiteLessonIds": ["les_a2_95_03_vacation_highlights_exchange_dialogue", "les_a2_95_04_travel_podcast_acoustic_listening"],
            "reviewsLessonIds": ["les_a1_50_01_sequential_converb_aad"],
            "reviewsUnitIds": ["unit_a1_50_sequential_converb_clause_connector"],
            "reviewReason": "Links sequential converbs (-аад) with witnessed past verbs (-лаа) for narrative momentum.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Audio read-back of written travel blog post.",
            "successCriteria": [
                "Produces written travel post containing at least 3 correctly formed verbs in -лаа4",
                "Includes vivid environmental adjectives: үзэсгэлэнтэй, сүрлэг, тунгалаг"
            ],
            "masteryEvidence": "Drafts 'Бид өнгөрсөн амралтын өдрөөр Тэрэлж рүү явлаа. Уулын орой дээр гарч, байгалийн сайхныг биширлээ...' flawlessly.",
            "recommendedExerciseModalities": ["short-answer writing", "sentence construction", "error correction"]
        }
    ])

    return lessons
