"""
Section 3 Generator Part 3 (Units 89 - 92): 17 Lessons
89: Scheduling Clinic & Dental Appointments (4 lessons)
90: Medical Encounters Capstone (5 lessons)
91: Extended Kinship: Clans vs Relatives (4 lessons)
92: Describing Physical Appearance & Grooming (4 lessons)
"""

import json
from typing import List, Dict, Any

def get_sec03_part3_lessons(u_map: Dict[int, Any]) -> List[Dict[str, Any]]:
    lessons: List[Dict[str, Any]] = []

    # =========================================================================
    # UNIT 89: Scheduling Clinic & Dental Appointments (pos 89)
    # 4 Lessons | Targets: ProdLem=19, RecLem=9, ProdExp=5, RecExp=3
    # Budget: (7,3,2,1), (5,3,1,1), (0,0,0,0), (7,3,2,1) = (19, 9, 5, 3)
    # =========================================================================
    u = u_map[89]
    uid = u["unitId"]
    lessons.extend([
        {
            "lessonId": "les_a2_89_01_clinic_dental_scheduling_lexicon",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 1,
            "title": "Booking the Dentist: Appointments, Postponements & Cleanings",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Introduce clinical and dental appointment scheduling vocabulary (цаг авах, цаг солих, цуцлах, шүдний эмч, үзлэг, цэвэрлэгээ, ломбодох, рентген).",
            "communicativeOutcome": "Book, reschedule, or cancel a medical or dental appointment via telephone or online portal.",
            "objectivesIntroduced": ["obj_a2_89_01_appointment_scheduling_lexicon"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_a2_88_01_modal_ability_chadah_yadah"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_dative_locative_time", "gram_a1_verb_tense_future_prospective_na"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_consonant_clusters"], "phonologyReviewed": ["phono_a1_long_vowels"],
            "communicativeFunctionsIntroduced": ["comm_a2_11_scheduling_rescheduling_meetings"],
            "communicativeFunctionsPracticed": ["comm_a2_12_medical_symptoms_doctor"], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 7, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_health_medicine", "lex_domain_civic_administrative"],
            "previousVocabularyReused": ["цаг", "өдөр", "шүд", "эмч", "солих", "болох"],
            "readingObjective": "Read an online dental clinic booking calendar displaying open time slots and practitioner specialties.",
            "listeningObjective": "Understand clinic receptionist offering alternative appointment times.",
            "writingObjective": "List 4 dental procedures (цэвэрлэгээ, ломбо, авахуулах, зураг) in Cyrillic.",
            "spokenProductionObjective": "Request appointment: 'Би маргааш үдээс хойш шүдний эмчид үзүүлэхээр цаг авч болох уу?'.",
            "registerTarget": "Standard administrative appointment booking register",
            "pragmaticTarget": "Checking available time slots politely and confirming practitioner names.",
            "prerequisiteLessonIds": ["les_a2_88_01_modal_ability_chadakh_yadakh_intro"],
            "reviewsLessonIds": ["les_a1_36_01_calendar_dates_intro"],
            "reviewsUnitIds": ["unit_a1_36_calendar_dates_months_seasons"],
            "reviewReason": "Integrates calendar days and clock times into formal scheduling workflows.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Pronounce clinical appointment terminology and dental procedures clearly.",
            "successCriteria": [
                "Defines цаг авах (book appointment), цуцлах (cancel), хойшлуулах (postpone), ломбодох (fill a cavity)",
                "Proposes and confirms specific dates and times"
            ],
            "masteryEvidence": "Accurately books a dental cleaning slot for Wednesday at 14:00 without assistance.",
            "recommendedExerciseModalities": ["categorization", "contextual_cloze", "matching"]
        },
        {
            "lessonId": "les_a2_89_02_appointment_confirmations_sms_reading",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 2,
            "title": "Deciphering Appointment Confirmation Texts & Reminder Alerts",
            "lessonType": "reading_development",
            "primaryPurpose": "Develop reading skills for authentic automated SMS reminders, clinic confirmation notifications, and cancellation deadlines.",
            "communicativeOutcome": "Inspect clinic SMS reminders to extract appointment date, doctor's office room number, required preparation, and reply confirmation codes.",
            "objectivesIntroduced": ["obj_a2_89_02_read_appointment_sms"],
            "objectivesPracticed": ["obj_a2_89_01_appointment_scheduling_lexicon"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_dative_locative_location", "gram_a1_case_genitive_possession"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_11_scheduling_rescheduling_meetings"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_health_medicine", "lex_domain_technology_devices"],
            "previousVocabularyReused": ["сануулга", "ирнэ", "цуцлах", "хариу", "өрөө", "утас"],
            "readingObjective": "Locate date, time, clinic address, and cancellation protocol in a 60-character automated SMS notification.",
            "listeningObjective": "",
            "writingObjective": "Transcribe confirmed medical appointment details into a personal calendar entry.",
            "spokenProductionObjective": "Explain SMS confirmation details to a peer.",
            "registerTarget": "Concise automated digital notification register",
            "pragmaticTarget": "Responding promptly with confirmation codes ('1 гэж хариулж баталгаажуулна уу') to prevent slot forfeiture.",
            "prerequisiteLessonIds": ["les_a2_89_01_clinic_dental_scheduling_lexicon"],
            "reviewsLessonIds": ["les_a1_64_06_transit_card_sms_writing"],
            "reviewsUnitIds": ["unit_a2_64_navigating_ulaanbaatar_bus_routes_d"],
            "reviewReason": "Applies short digital text reading to medical appointment reminders.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Read automated appointment SMS text aloud.",
            "successCriteria": [
                "Extracts appointment time and room number from SMS with 100% accuracy",
                "Understands cancellation notice policy (24 цагийн өмнө мэдэгдэх)"
            ],
            "masteryEvidence": "Answers 4 comprehension questions based on authentic clinic appointment reminder messages.",
            "recommendedExerciseModalities": ["reading_comprehension", "contextual_cloze", "categorization"]
        },
        {
            "lessonId": "les_a2_89_03_receptionist_scheduling_acoustic_listening",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 3,
            "title": "Acoustic Lab: Rapid Clinic Receptionist Phone Booking",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop acoustic listening comprehension of fast clinic receptionists navigating booking calendars, checking doctor availability, and confirming personal ID numbers.",
            "communicativeOutcome": "Understand rapid receptionist queries regarding national registration number (регистр), insurance coverage, and open time slots.",
            "objectivesIntroduced": ["obj_a2_89_03_decode_receptionist_booking"],
            "objectivesPracticed": ["obj_a2_89_01_appointment_scheduling_lexicon"], "objectivesReviewed": ["obj_a1_27_01_counting_tens_hundreds"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_numerals_cardinal_counting", "gram_a1_polar_questions_uu_uu"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_vowel_reduction_non_initial"], "phonologyReviewed": ["phono_a1_nasal_vowels"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_11_scheduling_rescheduling_meetings"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_health_medicine", "lex_domain_civic_administrative"],
            "previousVocabularyReused": ["регистр", "даатгал", "боломжтой", "цаг", "бүртгэл", "сонсох"],
            "readingObjective": "",
            "listeningObjective": "Extract confirmed booking day, hour, and doctor name across 3 rapid receptionist phone audio clips.",
            "writingObjective": "",
            "spokenProductionObjective": "Confirm appointment verbally by repeating back time and doctor name.",
            "registerTarget": "Fast transactional receptionist telephone register",
            "pragmaticTarget": "Providing national registration alphanumeric characters smoothly over the telephone.",
            "prerequisiteLessonIds": ["les_a2_89_01_clinic_dental_scheduling_lexicon"],
            "reviewsLessonIds": ["les_a1_69_03_courier_phone_listening"],
            "reviewsUnitIds": ["unit_a2_69_postal_courier_package_delivery_ser"],
            "reviewReason": "Tests phone comprehension under fast native speaker delivery conditions.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Realistic clinic phone acoustics with keyboard typing in the background.",
            "successCriteria": [
                "Transcribes appointment time accurately from telephone dialogue",
                "Identifies whether insurance (даатгал) covers the selected procedure"
            ],
            "masteryEvidence": "Logs all booking parameters correctly across 3 distinct receptionist phone calls.",
            "recommendedExerciseModalities": ["listening_comprehension", "dictation", "phonetic_discrimination"]
        },
        {
            "lessonId": "les_a2_89_04_dental_clinic_booking_dialogue",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 4,
            "title": "On the Line: Booking, Rescheduling & Confirming Dental Visits",
            "lessonType": "dialogue_work",
            "primaryPurpose": "Master spoken communication for scheduling, rescheduling, and negotiating appointment slots with dental or medical clinic receptionists.",
            "communicativeOutcome": "Call a dental clinic to schedule an emergency toothache visit or move an existing appointment to a different day.",
            "objectivesIntroduced": ["obj_a2_89_04_clinic_booking_dialogue"],
            "objectivesPracticed": ["obj_a2_89_01_appointment_scheduling_lexicon", "obj_a2_89_02_read_appointment_sms"],
            "objectivesReviewed": ["obj_a1_16_01_greet_time_of_day"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_verb_volitional_intention_ya", "gram_a1_case_dative_locative_time"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_intonation_polite"], "phonologyReviewed": ["phono_a1_vowel_length_distinction"],
            "communicativeFunctionsIntroduced": ["comm_a2_11_scheduling_rescheduling_meetings"],
            "communicativeFunctionsPracticed": ["comm_a2_12_medical_symptoms_doctor"],
            "communicativeFunctionsReviewed": ["comm_a1_16_greetings_time_of_day"],
            "newProductiveLemmaTarget": 7, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_health_medicine", "lex_domain_civic_administrative"],
            "previousVocabularyReused": ["өдөр", "солих", "шүд", "өвдөх", "яаралтай", "баярлалаа"],
            "readingObjective": "",
            "listeningObjective": "Understand receptionist proposing alternative times: 'Маргааш 11 цагт нэг хүн цагаа цуцалсан байна, та тэр цаг дээр ирж амжих уу?'.",
            "writingObjective": "",
            "spokenProductionObjective": "Reschedule appointment: 'Уучлаарай, би өнөөдөр очиж чадахааргүй боллоо. Цагаа баасан гарагийн үдээс хойш руу шилжүүлж болох уу?'.",
            "registerTarget": "Courteous institutional scheduling register",
            "pragmaticTarget": "Politely negotiating alternative slots without inconveniencing the clinic staff.",
            "prerequisiteLessonIds": ["les_a2_89_02_appointment_confirmations_sms_reading", "les_a2_89_03_receptionist_scheduling_acoustic_listening"],
            "reviewsLessonIds": ["les_a1_68_03_transit_delay_phone_dialogue"],
            "reviewsUnitIds": ["unit_a2_68_handling_transit_delays_traffic_jam"],
            "reviewReason": "Applies professional phone etiquette to healthcare appointment coordination.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Deliver natural telephone dialogue between patient and clinic scheduling officer.",
            "successCriteria": [
                "Successfully books or reschedules an appointment stating preferred day and time",
                "Repeats back confirmed appointment details accurately"
            ],
            "masteryEvidence": "Completes a 5-turn unscripted dental booking phone simulation without error.",
            "recommendedExerciseModalities": ["role-play response", "dialogue_completion", "listening_comprehension"]
        }
    ])

    # =========================================================================
    # UNIT 90: Medical Encounters Capstone: Full Clinical Encounter (pos 90)
    # 5 Lessons | Targets: ProdLem=24, RecLem=12, ProdExp=8, RecExp=4
    # Budget: (10,5,3,2), (0,0,0,0), (8,4,3,1), (6,3,2,1), (0,0,0,0) = (24, 12, 8, 4)
    # =========================================================================
    u = u_map[90]
    uid = u["unitId"]
    lessons.extend([
        {
            "lessonId": "les_a2_90_01_comprehensive_clinical_lexicon",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 1,
            "title": "Hospital Navigation: Wards, Diagnostics & Medical Records",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Introduce high-level hospital navigation and diagnostic terminology (оношлогоо, шинжилгээний хариу, дүрс оношлогоо, эмчийн дүгнэлт, эмчилгээний карт, хэвтэн эмчлүүлэх).",
            "communicativeOutcome": "Navigate a major district hospital or university clinic, understand diagnostic test referrals, and locate inpatient vs outpatient departments.",
            "objectivesIntroduced": ["obj_a2_90_01_comprehensive_clinical_lexicon"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_a2_84_01_temporal_converb_khad", "obj_a2_86_01_modal_obligation_constructions"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_converb_temporal_while_khad", "gram_a2_modal_obligation_heregtei_yostoi"],
            "grammarReviewed": ["gram_a1_case_dative_locative_location"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_consonant_clusters"], "phonologyReviewed": ["phono_a1_vowel_reduction_non_initial"],
            "communicativeFunctionsIntroduced": ["comm_a2_12_medical_symptoms_doctor", "comm_a2_13_buying_medicine_pharmacy"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 10, "newReceptiveLemmaTarget": 5, "newProductiveExpressionTarget": 3, "newReceptiveExpressionTarget": 2,
            "lexicalDomains": ["lex_domain_health_medicine", "lex_domain_civic_administrative"],
            "previousVocabularyReused": ["эмнэлэг", "онош", "шинжилгээ", "хариу", "эмчилгээ", "эмч"],
            "readingObjective": "Read hospital directory signage directing patients to laboratories, radiology, and ultrasound.",
            "listeningObjective": "Understand hospital receptionist directing outpatient traffic to diagnostic labs.",
            "writingObjective": "Outline a 3-step diagnostic route through a hospital facility in Cyrillic.",
            "spokenProductionObjective": "Ask for diagnostic guidance: 'Цусны шинжилгээ өгөх лаборатори хэддүгээр давхарт байдаг вэ?'.",
            "registerTarget": "Institutional healthcare facility register",
            "pragmaticTarget": "Navigating complex hospital infrastructure autonomously.",
            "prerequisiteLessonIds": ["les_a2_86_01_modal_obligation_heregtei_yostoi_intro", "les_a2_87_01_modal_permission_bolno_bolokhgui_intro", "les_a2_88_01_modal_ability_chadakh_yadakh_intro", "les_a2_89_01_clinic_dental_scheduling_lexicon"],
            "reviewsLessonIds": ["les_a1_63_06_elementary_stage_synthesis_capstone"],
            "reviewsUnitIds": ["unit_a1_63_a1_comprehensive_review_checkpoint_c"],
            "reviewReason": "Synthesizes foundation communicative skills into intermediate clinical autonomy.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Pronounce hospital facility and diagnostic laboratory terms clearly.",
            "successCriteria": [
                "Defines оношлогоо (diagnostics), дүрс оношлогоо (imaging/radiology), шинжилгээний хариу (lab results)",
                "Forms complete locative and directional queries in hospital settings"
            ],
            "masteryEvidence": "Accurately maps out an entire clinical journey from triage to lab and pharmacy.",
            "recommendedExerciseModalities": ["categorization", "contextual_cloze", "sentence_construction"]
        },
        {
            "lessonId": "les_a2_90_02_clinical_consultation_acoustic_decoding_lab",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 2,
            "title": "Acoustic Lab: Multi-Speaker Clinical Consultation Decoding",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop acoustic listening comprehension of realistic multi-speaker healthcare scenarios involving doctor, patient, family member, and nurse.",
            "communicativeOutcome": "Follow a multi-speaker clinical encounter, extract doctor's diagnosis, understand nurse's care instructions, and note prescription details.",
            "objectivesIntroduced": ["obj_a2_90_02_decode_clinical_encounters"],
            "objectivesPracticed": ["obj_a2_90_01_comprehensive_clinical_lexicon"], "objectivesReviewed": ["obj_a2_83_03_decode_triage_assessments"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a2_converb_temporal_while_khad", "gram_a2_modal_obligation_heregtei_yostoi"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_vowel_reduction_non_initial"], "phonologyReviewed": ["phono_a1_nasal_vowels"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_12_medical_symptoms_doctor"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_health_medicine"],
            "previousVocabularyReused": ["эмч", "өвчтөн", "онош", "эм", "уух", "зөвлөх"],
            "readingObjective": "",
            "listeningObjective": "Comprehend a 2-minute multi-speaker clinical encounter and extract the formal diagnosis and primary recovery rule.",
            "writingObjective": "",
            "spokenProductionObjective": "Summarize the clinical consultation outcome to a partner in 3 Mongolian sentences.",
            "registerTarget": "Authentic clinical multi-party consultation register",
            "pragmaticTarget": "Extracting critical medical advice without being overwhelmed by professional jargon.",
            "prerequisiteLessonIds": ["les_a2_90_01_comprehensive_clinical_lexicon"],
            "reviewsLessonIds": ["les_a1_63_03_auditory_comprehension_lab"],
            "reviewsUnitIds": ["unit_a1_63_a1_comprehensive_review_checkpoint_c"],
            "reviewReason": "Elevates listening stamina to multi-speaker clinical encounters.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Realistic 2-minute audio environment featuring doctor, patient, and nurse discussing treatment.",
            "successCriteria": [
                "Identifies the doctor's primary diagnosis correctly from audio",
                "Extracts prescribed medications and mandatory dietary restrictions"
            ],
            "masteryEvidence": "Answers 6 comprehensive questions following a single hearing of the clinical encounter audio.",
            "recommendedExerciseModalities": ["listening_comprehension", "sequencing", "categorization"]
        },
        {
            "lessonId": "les_a2_90_03_diagnostic_results_treatment_reading",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 3,
            "title": "Deciphering Diagnostic Lab Sheets, Ultrasound Reports & Doctor Notes",
            "lessonType": "reading_development",
            "primaryPurpose": "Develop targeted reading comprehension of authentic diagnostic reports, blood test ranges (хэвийн хэмжээ), ultrasound summaries, and physician conclusions.",
            "communicativeOutcome": "Inspect diagnostic test result sheets, determine whether parameters fall within normal ranges, and read doctor's handwritten treatment recommendations.",
            "objectivesIntroduced": ["obj_a2_90_03_read_diagnostic_reports"],
            "objectivesPracticed": ["obj_a2_90_01_comprehensive_clinical_lexicon"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_ablative_origin", "gram_a1_predicate_adjective_nominal"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_12_medical_symptoms_doctor"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 8, "newReceptiveLemmaTarget": 4, "newProductiveExpressionTarget": 3, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_health_medicine"],
            "previousVocabularyReused": ["шинжилгээ", "хэвийн", "өндөр", "бага", "дүгнэлт", "зөвлөгөө"],
            "readingObjective": "Extract diagnostic findings and physician orders from a 150-word medical assessment sheet.",
            "listeningObjective": "",
            "writingObjective": "Summarize medical report findings into a personal health record.",
            "spokenProductionObjective": "Explain to a family member whether laboratory results were normal.",
            "registerTarget": "Technical diagnostic report and clinical documentation register",
            "pragmaticTarget": "Understanding standard reference intervals (лавлах хэмжээ) and medical abbreviations.",
            "prerequisiteLessonIds": ["les_a2_90_01_comprehensive_clinical_lexicon"],
            "reviewsLessonIds": ["les_a1_63_02_textual_synthesis_reading"],
            "reviewsUnitIds": ["unit_a1_63_a1_comprehensive_review_checkpoint_c"],
            "reviewReason": "Applies advanced text skimming and scanning skills to authentic clinical documentation.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Read clinical report findings aloud.",
            "successCriteria": [
                "Identifies whether lab results indicate inflammation or normal parameters",
                "Extracts prescribed follow-up date and treatment timeline"
            ],
            "masteryEvidence": "Scores 100% on a 5-question comprehension quiz based on an official clinical report form.",
            "recommendedExerciseModalities": ["reading_comprehension", "contextual_cloze", "categorization"]
        },
        {
            "lessonId": "les_a2_90_04_full_clinical_encounter_simulation",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 4,
            "title": "Interactive Simulation: The Complete Clinical Encounter",
            "lessonType": "dialogue_work",
            "primaryPurpose": "Synthesize all spoken interaction capabilities developed across medical units in an unscripted multi-stage hospital journey simulation.",
            "communicativeOutcome": "Navigate an entire simulated hospital visit: register at reception, describe symptoms to physician, undergo preliminary checks, receive diagnosis, and collect medication.",
            "objectivesIntroduced": ["obj_a2_90_04_simulate_clinical_journey"],
            "objectivesPracticed": ["obj_a2_90_01_comprehensive_clinical_lexicon"],
            "objectivesReviewed": ["obj_a2_83_04_doctor_exam_dialogue", "obj_a2_85_04_pharmacy_counter_dialogue", "obj_a2_89_04_clinic_booking_dialogue"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_converb_temporal_while_khad", "gram_a2_modal_obligation_heregtei_yostoi", "gram_a2_modal_permission_possibility_bolno"],
            "grammarReviewed": ["gram_a2_modal_ability_yadah_chadah"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_intonation_polite"], "phonologyReviewed": ["phono_a1_vowel_length_distinction"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_12_medical_symptoms_doctor", "comm_a2_13_buying_medicine_pharmacy", "comm_a2_11_scheduling_rescheduling_meetings"],
            "communicativeFunctionsReviewed": ["comm_a1_13_apologies_politeness"],
            "newProductiveLemmaTarget": 6, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_health_medicine"],
            "previousVocabularyReused": ["эмч", "өвчин", "шинжилгээ", "эм", "уух", "эдгэрэх"],
            "readingObjective": "",
            "listeningObjective": "Respond adaptively to dynamic situational hurdles introduced by the medical staff (e.g. need for additional test, pharmacy stock shortage).",
            "writingObjective": "",
            "spokenProductionObjective": "Conduct consecutive dialogue turns across 4 simulated clinical stages without reverting to English.",
            "registerTarget": "Spontaneous adaptable healthcare register",
            "pragmaticTarget": "Maintaining clarity, composure, and communicative efficacy during medical consultations.",
            "prerequisiteLessonIds": ["les_a2_90_02_clinical_consultation_acoustic_decoding_lab", "les_a2_90_03_diagnostic_results_treatment_reading"],
            "reviewsLessonIds": ["les_a1_63_05_interactive_checkpoint_simulation"],
            "reviewsUnitIds": ["unit_a1_63_a1_comprehensive_review_checkpoint_c"],
            "reviewReason": "Builds upon A1 capstone interactive simulations with higher situational complexity.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Provide responsive native speaker voice prompts for the interactive simulation.",
            "successCriteria": [
                "Explains somatic symptoms accurately using temporal converb (-хад)",
                "Negotiates appointment and clarifies prescription dosage with pharmacist"
            ],
            "masteryEvidence": "Completes full 4-stage simulation with zero communicative breakdowns.",
            "recommendedExerciseModalities": ["role-play response", "dialogue_completion", "sequencing"]
        },
        {
            "lessonId": "les_a2_90_05_medical_clinic_benchmark_checkpoint",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 5,
            "title": "Benchmark Checkpoint: Health, Medical Encounters & Civic Life",
            "lessonType": "checkpoint",
            "primaryPurpose": "Formal milestone evaluation assessing productive and receptive mastery of medical and civic competencies: human anatomy, pain verbs, temporal converb (-хад4), systemic symptoms, pharmacy purchasing, modal obligation (хэрэгтэй/ёстой), permission/prohibition (болно/болохгүй), and modal ability (чадах/ядах).",
            "communicativeOutcome": "Demonstrate comprehensive communicative competence across all Section 3 medical, domestic, and civic domains without reference materials.",
            "objectivesIntroduced": [],
            "objectivesPracticed": ["obj_a2_90_01_comprehensive_clinical_lexicon", "obj_a2_90_04_simulate_clinical_journey"],
            "objectivesReviewed": ["obj_a2_83_01_anatomy_pain_lexicon", "obj_a2_84_01_temporal_converb_khad", "obj_a2_85_01_pharmacy_dosage_lexicon", "obj_a2_86_01_modal_obligation_constructions", "obj_a2_87_01_modal_permission_bolno", "obj_a2_88_01_modal_ability_chadah_yadah"],
            "grammarIntroduced": [],
            "grammarPracticed": ["gram_a2_converb_temporal_while_khad", "gram_a2_modal_obligation_heregtei_yostoi", "gram_a2_modal_permission_possibility_bolno", "gram_a2_modal_ability_yadah_chadah"],
            "grammarReviewed": ["gram_a2_converb_conditional_val"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_intonation_polite"], "phonologyReviewed": ["phono_a1_vowel_length_distinction"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_12_medical_symptoms_doctor", "comm_a2_13_buying_medicine_pharmacy", "comm_a2_21_expressing_obligation_rules", "comm_a2_22_requesting_granting_permission"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_health_medicine", "lex_domain_civic_administrative"],
            "previousVocabularyReused": ["өвчин", "эмнэлэг", "эм", "дүрэм", "болох", "чадах"],
            "readingObjective": "Demonstrate unassisted comprehension of an authentic hospital discharge summary and prescription.",
            "listeningObjective": "Demonstrate unassisted comprehension of an authentic multi-speaker doctor-patient encounter.",
            "writingObjective": "Draft a coherent written clinical symptom summary and absence notification.",
            "spokenProductionObjective": "Conduct a live spoken negotiation resolving a healthcare appointment or medical dispute.",
            "registerTarget": "Standard formal evaluation register",
            "pragmaticTarget": "Demonstrating holistic linguistic control and situational independence in health contexts.",
            "prerequisiteLessonIds": ["les_a2_90_04_full_clinical_encounter_simulation"],
            "reviewsLessonIds": ["les_a2_83_04_doctor_somatic_exam_dialogue", "les_a2_84_05_sick_leave_written_request", "les_a2_85_04_pharmacy_counter_purchasing_dialogue", "les_a2_86_05_patient_care_plan_writing", "les_a2_87_05_building_bylaws_notice_writing", "les_a2_88_05_rehabilitation_progress_report_writing", "les_a2_89_04_dental_clinic_booking_dialogue"],
            "reviewsUnitIds": ["unit_a2_83_human_anatomy_somatic_pain_location", "unit_a2_84_describing_illness_symptoms_to_a_ph", "unit_a2_85_purchasing_medicine_pharmacy_consul", "unit_a2_86_modal_obligation_modals_vs_", "unit_a2_87_modal_permission_possibility_suffix", "unit_a2_88_modal_potentiality_verbs_vs_", "unit_a2_89_scheduling_clinic_dental_appointmen"],
            "reviewReason": "Milestone synthesis certifying learner readiness to manage healthcare and domestic obligations independently.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Deliver high-fidelity audio stimuli for formal benchmark assessment items.",
            "successCriteria": [
                "Demonstrates mastery of temporal converb (-хад), modal obligation, permission, and ability in context",
                "Completes receptive and productive tasks across all 4 skill modalities without communicative breakdown"
            ],
            "masteryEvidence": "Successfully navigates all 4 benchmark assessment modalities achieving independent task completion.",
            "recommendedExerciseModalities": ["reading_comprehension", "listening_comprehension", "role-play response", "short-answer writing"]
        }
    ])

    # =========================================================================
    # UNIT 91: Extended Kinship: Clans vs Relatives (pos 91)
    # 4 Lessons | Targets: ProdLem=19, RecLem=9, ProdExp=5, RecExp=3
    # Budget: (7,3,2,1), (5,3,1,1), (0,0,0,0), (7,3,2,1) = (19, 9, 5, 3)
    # =========================================================================
    u = u_map[91]
    uid = u["unitId"]
    lessons.extend([
        {
            "lessonId": "les_a2_91_01_clan_patrilineal_matrilineal_lexicon",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 1,
            "title": "Avga & Nagats: Patrilineal vs Matrilineal Relatives & Clan Heritage",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Introduce extended Mongolian kinship terminology distinguishing paternal relatives (авга ах, авга эгч) from maternal relatives (нагац ах, нагац эгч, нагац эмээ) and clan names (ургийн овог).",
            "communicativeOutcome": "Chart family genealogy, differentiate paternal and maternal relatives accurately, and explain one's clan heritage (ургийн овог).",
            "objectivesIntroduced": ["obj_a2_91_01_extended_kinship_lexicon"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_a2_76_01_reflexive_case_combination"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_genitive_possession", "gram_a1_predicate_adjective_nominal"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_consonant_clusters"], "phonologyReviewed": ["phono_a1_vowel_reduction_non_initial"],
            "communicativeFunctionsIntroduced": ["comm_a2_01_describing_extended_family"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 7, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_family_kinship", "lex_domain_culture_traditions"],
            "previousVocabularyReused": ["ах", "эгч", "аав", "ээж", "гэр бүл", "нэр"],
            "readingObjective": "Read a genealogical family tree chart (ургийн бичиг) tracing 4 generations.",
            "listeningObjective": "Understand an elder explaining kinship ties between cousins.",
            "writingObjective": "List 6 extended kinship designations contrasting paternal and maternal branches.",
            "spokenProductionObjective": "Explain family ties: 'Энэ хүн бол миний ээжийн ах, өөрөөр хэлбэл миний нагац ах юм'.",
            "registerTarget": "Traditional cultural kinship register",
            "pragmaticTarget": "Respecting traditional generational hierarchy and precise bilateral kinship terms.",
            "prerequisiteLessonIds": ["les_a2_90_05_medical_clinic_benchmark_checkpoint"],
            "reviewsLessonIds": ["les_a1_33_01_kinship_terms_intro"],
            "reviewsUnitIds": ["unit_a1_33_immediate_family_kinship_terms_ex"],
            "reviewReason": "Expands nuclear family terms (аав, ээж, ах, дүү) into bilateral clan systems.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Pronounce bilateral kinship terminology clearly.",
            "successCriteria": [
                "Differentiates авга (paternal) from нагац (maternal) relatives without confusion",
                "Defines ургийн овог (clan name) and ургийн бичиг (genealogy book)"
            ],
            "masteryEvidence": "Accurately maps 6 relatives on a bilateral family tree diagram.",
            "recommendedExerciseModalities": ["categorization", "contextual_cloze", "matching"]
        },
        {
            "lessonId": "les_a2_91_02_genealogy_tree_reading",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 2,
            "title": "Deciphering the Urgiin Bichig: Clan Books & Ancestral Heritage",
            "lessonType": "reading_development",
            "primaryPurpose": "Develop targeted reading comprehension of traditional genealogy books (ургийн бичиг), ancestral geographic origins (уг гарвал), and clan history narratives.",
            "communicativeOutcome": "Inspect a family genealogical record to identify ancestral provinces, clan designations, and relationships among distant cousins (үеэл, хаяал).",
            "objectivesIntroduced": ["obj_a2_91_02_read_genealogy_records"],
            "objectivesPracticed": ["obj_a2_91_01_extended_kinship_lexicon"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_ablative_origin", "gram_a1_case_genitive_possession"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_01_describing_extended_family"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_family_kinship", "lex_domain_culture_traditions"],
            "previousVocabularyReused": ["овог", "удам", "өвөг эцэг", "нутаг", "түүх", "аймаг"],
            "readingObjective": "Extract ancestral clan name (Боржигон, Тайж, Сартуул) and birthplace from a family chronicle excerpt.",
            "listeningObjective": "",
            "writingObjective": "Transcribe personal ancestral branch data into a family tree worksheet.",
            "spokenProductionObjective": "Explain ancestral origins to a peer based on genealogical text.",
            "registerTarget": "Formal cultural chronicle and archival register",
            "pragmaticTarget": "Appreciating Mongolian cultural pride in maintaining ancestral lineages for nine generations.",
            "prerequisiteLessonIds": ["les_a2_91_01_clan_patrilineal_matrilineal_lexicon"],
            "reviewsLessonIds": ["les_a1_33_02_reading_short_family_narratives"],
            "reviewsUnitIds": ["unit_a1_33_immediate_family_kinship_terms_ex"],
            "reviewReason": "Elevates family reading comprehension to historical clan heritage.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Read historical genealogical chronicle excerpts aloud.",
            "successCriteria": [
                "Identifies relationships: үеэл (first cousin), хаяал (second cousin)",
                "Traces patrilineal lineage back to grandfather's origin province"
            ],
            "masteryEvidence": "Answers 4 comprehension questions based on authentic excerpts of an Urgiin Bichig.",
            "recommendedExerciseModalities": ["reading_comprehension", "contextual_cloze", "categorization"]
        },
        {
            "lessonId": "les_a2_91_03_elder_clan_history_acoustic_listening",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 3,
            "title": "Acoustic Lab: Elder Oral Histories & Clan Lineage Recitations",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop acoustic listening comprehension of elder family members narrating ancestral migrations, nomadic heritage, and clan lineage orally.",
            "communicativeOutcome": "Follow an elder recounting how their grandparents moved from western aimags to the central region and preserving clan customs.",
            "objectivesIntroduced": ["obj_a2_91_03_decode_elder_oral_histories"],
            "objectivesPracticed": ["obj_a2_91_01_extended_kinship_lexicon"], "objectivesReviewed": ["obj_a1_41_01_witnessed_past_laa"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_verb_tense_past_witnessed_laa", "gram_a1_converb_sequential_aad"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_vowel_reduction_non_initial"], "phonologyReviewed": ["phono_a1_nasal_vowels"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_01_describing_extended_family"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_family_kinship", "lex_domain_culture_traditions"],
            "previousVocabularyReused": ["өвөө", "эмээ", "нүүх", "хөдөө", "мал", "амьдрах"],
            "readingObjective": "",
            "listeningObjective": "Identify geographic origins and clan names from elder's reflective spoken narrative.",
            "writingObjective": "",
            "spokenProductionObjective": "Summarize the elder's story to a family member in 3 sentences.",
            "registerTarget": "Traditional respectful oral storytelling register",
            "pragmaticTarget": "Attentive, respectful listening to senior family elders during oral history transmission.",
            "prerequisiteLessonIds": ["les_a2_91_01_clan_patrilineal_matrilineal_lexicon"],
            "reviewsLessonIds": ["les_a1_76_03_reflexive_acoustic_discrimination_lab"],
            "reviewsUnitIds": ["unit_a2_76_reflexive_case_combinations_"],
            "reviewReason": "Advances listening acuity to older generational speech cadences and kinship vocabulary.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Warm, resonant elder voice recounting ancestral history with traditional narrative cadence.",
            "successCriteria": [
                "Identifies the speaker's home province and ancestral clan name from audio",
                "Extracts key life events of grandparents recounted in the oral history"
            ],
            "masteryEvidence": "Accurately maps out 3 key historical milestones from a 90-second elder oral history audio clip.",
            "recommendedExerciseModalities": ["listening_comprehension", "phonetic_discrimination", "sequencing"]
        },
        {
            "lessonId": "les_a2_91_04_family_gathering_introductions_dialogue",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 4,
            "title": "Kinship Introductions: Presenting Extended Relatives at a Celebration",
            "lessonType": "dialogue_work",
            "primaryPurpose": "Master spoken communication during large family gatherings (Tsagaan Sar, weddings): introducing maternal and paternal cousins, addressing in-laws, and explaining connections.",
            "communicativeOutcome": "Introduce extended relatives to guests at a family banquet, articulating precise kinship connections and expressing respectful greetings.",
            "objectivesIntroduced": ["obj_a2_91_04_kinship_introductions_dialogue"],
            "objectivesPracticed": ["obj_a2_91_01_extended_kinship_lexicon", "obj_a2_91_02_read_genealogy_records"],
            "objectivesReviewed": ["obj_a1_16_01_greet_time_of_day"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a2_reflexive_case_combinations", "gram_a1_converb_coordinating_j_ch"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_intonation_polite"], "phonologyReviewed": ["phono_a1_vowel_length_distinction"],
            "communicativeFunctionsIntroduced": ["comm_a2_01_describing_extended_family"],
            "communicativeFunctionsPracticed": ["comm_a1_16_greetings_time_of_day"],
            "communicativeFunctionsReviewed": ["comm_a1_13_apologies_politeness"],
            "newProductiveLemmaTarget": 7, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_family_kinship", "lex_domain_social_interaction"],
            "previousVocabularyReused": ["танилцах", "энэ бол", "нагац", "авга", "үеэл", "хүргэн"],
            "readingObjective": "",
            "listeningObjective": "Understand relative explaining complex in-law relationship during dinner conversation.",
            "writingObjective": "",
            "spokenProductionObjective": "Introduce family members: 'Энэ бол миний нагац эгчийн охин, миний үеэл дүү Батцэцэг юм'.",
            "registerTarget": "Warm hospitable cultural banquet register",
            "pragmaticTarget": "Using formal respectful honorific terms when introducing elder relatives to peers.",
            "prerequisiteLessonIds": ["les_a2_91_02_genealogy_tree_reading", "les_a2_91_03_elder_clan_history_acoustic_listening"],
            "reviewsLessonIds": ["les_a1_76_05_family_reunion_dialogue"],
            "reviewsUnitIds": ["unit_a2_76_reflexive_case_combinations_"],
            "reviewReason": "Deepens family reunion dialogues with precise bilateral kinship terminology.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Lively festive banquet atmosphere with warm multi-generational introductions.",
            "successCriteria": [
                "Introduces at least 2 relatives using correct bilateral terms (авга/нагац)",
                "Explains relationship to host accurately during banquet conversation"
            ],
            "masteryEvidence": "Conducts a 5-turn family introduction dialogue at a festive banquet without hesitation.",
            "recommendedExerciseModalities": ["role-play response", "dialogue_completion", "listening_comprehension"]
        }
    ])

    # =========================================================================
    # UNIT 92: Describing Physical Appearance & Grooming (pos 92)
    # 4 Lessons | Targets: ProdLem=19, RecLem=9, ProdExp=5, RecExp=3
    # Budget: (7,3,2,1), (5,3,1,1), (0,0,0,0), (7,3,2,1) = (19, 9, 5, 3)
    # =========================================================================
    u = u_map[92]
    uid = u["unitId"]
    lessons.extend([
        {
            "lessonId": "les_a2_92_01_physical_appearance_features_lexicon",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 1,
            "title": "Tall, Short & Slender: Describing Stature, Hair & Features",
            "lessonType": "vocabulary_introduction",
            "primaryPurpose": "Introduce physical appearance descriptors (өндөр нуруутай, намхан, туранхай, махлаг/мяраалаг, долгионтой үс, халзан, сахалтай, цайвар/бор царайтай).",
            "communicativeOutcome": "Describe a person's physical build, facial features, complexion, hairstyle, and facial hair accurately.",
            "objectivesIntroduced": ["obj_a2_92_01_physical_appearance_lexicon"],
            "objectivesPracticed": [], "objectivesReviewed": ["obj_a2_91_01_extended_kinship_lexicon"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_noun_phrase_attributive_adjective", "gram_a1_predicate_adjective_nominal"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_consonant_clusters"], "phonologyReviewed": ["phono_a1_long_vowels"],
            "communicativeFunctionsIntroduced": ["comm_a2_02_describing_appearance_clothing"],
            "communicativeFunctionsPracticed": [], "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 7, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_people_descriptions", "lex_domain_body_anatomy"],
            "previousVocabularyReused": ["өндөр", "намхан", "үс", "хар", "царай", "нүд"],
            "readingObjective": "Read character descriptions in a contemporary Mongolian novel excerpt.",
            "listeningObjective": "Understand an eyewitness describing a person's height, hair, and clothing.",
            "writingObjective": "List 6 physical appearance traits contrasting height, build, and complexion.",
            "spokenProductionObjective": "Describe a friend: 'Тэр өндөр нуруутай, богино хар үстэй, шил зүүдэг'.",
            "registerTarget": "Standard descriptive interpersonal register",
            "pragmaticTarget": "Using respectful, polite terms for body types (e.g. махлаг or мяраалаг rather than crude terms).",
            "prerequisiteLessonIds": ["les_a2_91_01_clan_patrilineal_matrilineal_lexicon"],
            "reviewsLessonIds": ["les_a1_21_01_attributive_adjectives_intro"],
            "reviewsUnitIds": ["unit_a1_21_attributive_predicative_adjective"],
            "reviewReason": "Expands basic physical adjectives into nuanced human portraiture.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Pronounce physical appearance compound adjectives clearly.",
            "successCriteria": [
                "Differentiates туранхай (slender/thin) from махлаг/мяраалаг (stout/plump)",
                "Combines physical features with possessive suffix -тай: сахалтай (bearded), шилтэй (bespectacled)"
            ],
            "masteryEvidence": "Accurately describes 4 photographed people across height, hair, build, and accessories.",
            "recommendedExerciseModalities": ["categorization", "contextual_cloze", "matching"]
        },
        {
            "lessonId": "les_a2_92_02_id_badges_portraits_reading",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 2,
            "title": "Deciphering Identification Badges, Profiles & Lost Person Notices",
            "lessonType": "reading_development",
            "primaryPurpose": "Develop reading comprehension for corporate security ID profiles, missing person notices, and literary character sketches.",
            "communicativeOutcome": "Inspect security descriptions and public notices to identify individuals based on height, distinctive scars/marks, and clothing.",
            "objectivesIntroduced": ["obj_a2_92_02_read_appearance_profiles"],
            "objectivesPracticed": ["obj_a2_92_01_physical_appearance_lexicon"], "objectivesReviewed": [],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a1_case_genitive_possession", "gram_a1_noun_phrase_attributive_adjective"],
            "phonologyIntroduced": [],
            "phonologyPracticed": [], "phonologyReviewed": ["phono_a1_cyrillic_spelling_rules"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_02_describing_appearance_clothing"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 5, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 1, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_people_descriptions", "lex_domain_civic_administrative"],
            "previousVocabularyReused": ["өндөр", "нас", "хүрэм", "содон", "тэмдэг", "хайх"],
            "readingObjective": "Locate height, age estimate, distinctive birthmarks/scars (содон шинж тэмдэг), and last seen attire in a 100-word public notice.",
            "listeningObjective": "",
            "writingObjective": "Transcribe physical traits from a security profile into a descriptive witness log.",
            "spokenProductionObjective": "Explain profile details to a security officer in Mongolian.",
            "registerTarget": "Administrative identification and descriptive register",
            "pragmaticTarget": "Scanning for distinctive identifying features systematically.",
            "prerequisiteLessonIds": ["les_a2_92_01_physical_appearance_features_lexicon"],
            "reviewsLessonIds": ["les_a1_22_02_clothing_colors_shopping"],
            "reviewsUnitIds": ["unit_a1_22_shopping_transactions_making_purch"],
            "reviewReason": "Combines clothing color descriptors with bodily physical traits.",
            "audioSuitability": "standard_speech_synthesis_acceptable", "audioPurpose": "Read administrative identification profiles aloud.",
            "successCriteria": [
                "Extracts height and distinctive marks (содон шинж) from text accurately",
                "Identifies matching portrait among 3 alternatives based on text description"
            ],
            "masteryEvidence": "Scores 100% on a 4-question profile matching comprehension exercise.",
            "recommendedExerciseModalities": ["reading_comprehension", "contextual_cloze", "matching"]
        },
        {
            "lessonId": "les_a2_92_03_eyewitness_description_acoustic_listening",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 3,
            "title": "Acoustic Lab: Eyewitness Accounts & Identifying People in a Crowd",
            "lessonType": "listening_development",
            "primaryPurpose": "Develop acoustic listening comprehension of spontaneous eyewitness accounts describing someone seen at a train station or bus stop.",
            "communicativeOutcome": "Pick out a target individual from a crowd based on spoken auditory descriptions of build, hairstyle, gait, and coat color.",
            "objectivesIntroduced": ["obj_a2_92_03_decode_eyewitness_descriptions"],
            "objectivesPracticed": ["obj_a2_92_01_physical_appearance_lexicon"], "objectivesReviewed": ["obj_a2_77_01_enclitic_ni_marking"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a2_possessive_third_person_enclitic_ni", "gram_a1_converb_coordinating_j_ch"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_vowel_reduction_non_initial"], "phonologyReviewed": ["phono_a1_nasal_vowels"],
            "communicativeFunctionsIntroduced": [],
            "communicativeFunctionsPracticed": ["comm_a2_02_describing_appearance_clothing"],
            "communicativeFunctionsReviewed": [],
            "newProductiveLemmaTarget": 0, "newReceptiveLemmaTarget": 0, "newProductiveExpressionTarget": 0, "newReceptiveExpressionTarget": 0,
            "lexicalDomains": ["lex_domain_people_descriptions"],
            "previousVocabularyReused": ["хүн", "харсан", "явах", "цүнх", "малгай", "хөх"],
            "readingObjective": "",
            "listeningObjective": "Identify target person's key features ('Тэр залуу өндөр нуруутай, урт шар хүрэмтэй, сахалтай байсан') across 3 eyewitness audio clips.",
            "writingObjective": "",
            "spokenProductionObjective": "Explain to a police officer which person the witness described.",
            "registerTarget": "Spontaneous eyewitness testimony register",
            "pragmaticTarget": "Separating subjective impressions from verifiable physical facts.",
            "prerequisiteLessonIds": ["les_a2_92_01_physical_appearance_features_lexicon"],
            "reviewsLessonIds": ["les_a1_72_02_commuter_acoustic_decoding_lab"],
            "reviewsUnitIds": ["unit_a2_72_urban_transit_capstone_navigating_the"],
            "reviewReason": "Applies urban transit listening skills to eyewitness person descriptions.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Field audio of witness recalling a person's appearance to a friend at a busy transit hub.",
            "successCriteria": [
                "Identifies correct person from an image array based on audio description",
                "Extracts specific accessories mentioned (e.g. цүнх, шил, ороолт)"
            ],
            "masteryEvidence": "Accurately identifies all 3 targets from auditory descriptions without error.",
            "recommendedExerciseModalities": ["listening_comprehension", "phonetic_discrimination", "matching"]
        },
        {
            "lessonId": "les_a2_92_04_meeting_at_station_dialogue",
            "unitId": uid, "cefrLevel": "A2", "sequenceWithinUnit": 4,
            "title": "Meeting a Stranger: Describing Yourself to Be Recognized",
            "lessonType": "dialogue_work",
            "primaryPurpose": "Master spoken communication for meeting someone for the first time at an airport or railway station: describing your own appearance, clothing, and holding a sign.",
            "communicativeOutcome": "Coordinate a meeting with a person you have never met before via telephone, describing your appearance and location in a crowded terminal.",
            "objectivesIntroduced": ["obj_a2_92_04_coordinate_meeting_dialogue"],
            "objectivesPracticed": ["obj_a2_92_01_physical_appearance_lexicon", "obj_a2_92_02_read_appearance_profiles"],
            "objectivesReviewed": ["obj_a1_16_01_greet_time_of_day"],
            "grammarIntroduced": [],
            "grammarPracticed": [], "grammarReviewed": ["gram_a2_reflexive_possessive_base", "gram_a1_case_dative_locative_location"],
            "phonologyIntroduced": [],
            "phonologyPracticed": ["phono_a1_intonation_polite"], "phonologyReviewed": ["phono_a1_vowel_length_distinction"],
            "communicativeFunctionsIntroduced": ["comm_a2_02_describing_appearance_clothing"],
            "communicativeFunctionsPracticed": ["comm_a1_19_inquiring_location"],
            "communicativeFunctionsReviewed": ["comm_a1_16_greetings_time_of_day"],
            "newProductiveLemmaTarget": 7, "newReceptiveLemmaTarget": 3, "newProductiveExpressionTarget": 2, "newReceptiveExpressionTarget": 1,
            "lexicalDomains": ["lex_domain_people_descriptions", "lex_domain_social_interaction"],
            "previousVocabularyReused": ["зогсох", "харах", "хүрэм", "цүнх", "олох", "энд"],
            "readingObjective": "",
            "listeningObjective": "Follow caller's self-description: 'Би гарцны хажууд хар савхин хүрэмтэй, чемодантай зогсож байна'.",
            "writingObjective": "",
            "spokenProductionObjective": "Describe yourself over phone: 'Би цагаан малгай, улаан ороолттой, гар утсаараа яриад зогсож байна. Та намайг харж байна уу?'.",
            "registerTarget": "Spontaneous coordination telephone register",
            "pragmaticTarget": "Using prominent, distinctive visual cues to expedite meeting in crowded public areas.",
            "prerequisiteLessonIds": ["les_a2_92_02_id_badges_portraits_reading", "les_a2_92_03_eyewitness_description_acoustic_listening"],
            "reviewsLessonIds": ["les_a1_75_03_dressing_for_celebration_dialogue"],
            "reviewsUnitIds": ["unit_a2_75_reflexive_possessive_base_suffixes_"],
            "reviewReason": "Utilizes reflexive clothing descriptions in real-time wayfinding coordination.",
            "audioSuitability": "mongolian_voice_required", "audioPurpose": "Realistic cell phone audio with airport arrival hall reverberation and clear mutual guidance.",
            "successCriteria": [
                "Describes own physical traits and outerwear with complete clarity",
                "Spots interlocutor based on auditory cues and completes rendezvous"
            ],
            "masteryEvidence": "Conducts a 5-turn rendezvous phone call locating a partner in an arrival terminal.",
            "recommendedExerciseModalities": ["role-play response", "dialogue_completion", "listening_comprehension"]
        }
    ])

    return lessons
