# -*- coding: utf-8 -*-
"""CEFR C2 Section 01: Contemporary Literature, Satire & Stylistic Nuance (Units 229-237, 46 lessons)."""

def get_section_01_lessons():
    lessons = []

    # ----------------------------------------------------
    # UNIT 229: Rapid Khalkha Spoken Phonotactics & Reductions (PL=24, RL=31, PE=9, RE=7) - 5 lessons
    # ----------------------------------------------------
    lessons.extend([
      {
        "lessonId": "les_c2_229_01_khalkha_phonotactics_syntax_intro",
        "unitId": "unit_c2_229_rapid_khalkha_spoken_phonotactics_r",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 1,
        "title": "Morphophonology: Rapid Khalkha Spoken Phonotactics, Vowel Syncope & Sandhi Reductions",
        "lessonType": "grammar_introduction",
        "primaryPurpose": "Introduce the phonotactic reduction algorithms, non-initial short vowel deletions, liquid consonant assimilations (l/r coalescence), and clitic contractions occurring in natural educated and street Khalkha speech above 160 wpm.",
        "communicativeOutcome": "Decode and execute natural Khalkha phonetic reductions systematically without sounding stilted or foreign.",
        "objectivesIntroduced": ["obj_c2_229_01_master_khalkha_phonotactics"],
        "objectivesPracticed": ["obj_c1_228_06_master_c1_operational_proficiency"],
        "objectivesReviewed": ["obj_c1_218_01_master_register_switching"],
        "grammarIntroduced": ["gram_c2_rapid_khalkha_spoken_phonotactics"],
        "grammarPracticed": ["gram_c1_register_switching_matrix"],
        "grammarReviewed": ["gram_b1_vowel_harmony_long_diphthongs"],
        "phonologyIntroduced": ["phon_c2_01_rapid_vowel_syncope_assimilation"],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": ["comm_c2_01_rapid_colloquial_banter"],
        "communicativeFunctionsPracticed": [],
        "communicativeFunctionsReviewed": ["comm_c1_14_navigating_subtle_social_hierarchies"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 7,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_gnomic_wisdom_proverbs_rhetoric"],
        "previousVocabularyReused": ["авиа авиалбар", "эгшиг гээгдэх", "нийлмэл авиа", "ярианы хэл"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "rapid colloquial native khalkha",
        "pragmaticTarget": "phonetic naturalness and conversational fluency",
        "prerequisiteLessonIds": ["les_c1_228_06_grand_c1_level_culminating_operational_synthesis"],
        "reviewsLessonIds": ["les_c1_218_01_register_switching_matrix_syntax_intro"],
        "reviewsUnitIds": ["unit_c1_218_mongolia_s_third_neighbor_foreign_p"],
        "reviewReason": "Bridges formal C1 register switching into native-speed C2 colloquial phonotactic reality.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Transcribes 10 spoken utterances containing non-initial short vowel deletions and liquid assimilations into standard Cyrillic without error",
          "Demonstrates productive execution of fast speech sandhi ('яачихсан юм' -> [яаццым], 'мэдэхгүй' -> [мэкүй]) in unscripted simulation"
        ],
        "masteryEvidence": "Phonetically analyzes and reconstructs 8 heavily elided colloquial sentences at native conversational speed.",
        "recommendedExerciseModalities": ["stylistic_transformation", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_229_02_unedited_street_dialogue_transcripts_reading",
        "unitId": "unit_c2_229_rapid_khalkha_spoken_phonotactics_r",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 2,
        "title": "Sociolinguistic Reading: Verbatim Transcripts of Ulaanbaatar Youth Vernacular & Slang",
        "lessonType": "reading",
        "primaryPurpose": "Parse an 840-word unedited ethnographic transcript of multi-party banter among university students and market traders in Ulaanbaatar, decoding heavy phonetic contractions, coded in-group youth slang, and elliptical clauses.",
        "communicativeOutcome": "Deconstruct authentic, non-standardized Mongolian orthographic transcripts representing raw conversational Khalkha without literary smoothing.",
        "objectivesIntroduced": ["obj_c2_229_02_parse_verbatim_slang_transcripts"],
        "objectivesPracticed": ["obj_c2_229_01_master_khalkha_phonotactics"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c2_rapid_khalkha_spoken_phonotactics"],
        "grammarReviewed": ["gram_c1_register_switching_matrix"],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phon_c2_01_rapid_vowel_syncope_assimilation"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_01_rapid_colloquial_banter"],
        "communicativeFunctionsReviewed": ["comm_c1_14_navigating_subtle_social_hierarchies"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c2_gnomic_wisdom_proverbs_rhetoric"],
        "previousVocabularyReused": ["этгээд үг хэллэг", "хар яриа", "залуусын хэллэг", "утгын хувирал"],
        "readingObjective": "Critique verbatim conversational transcripts containing heavy phonetic reductions and modern slang.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "contemporary urban youth slang",
        "pragmaticTarget": "in-group social solidarity decoding",
        "prerequisiteLessonIds": ["les_c2_229_01_khalkha_phonotactics_syntax_intro"],
        "reviewsLessonIds": ["les_c1_226_01_diplomatic_speech_transcription_reading"],
        "reviewsUnitIds": ["unit_c1_226_consecutive_interpreting_support_re"],
        "reviewReason": "Contrasts diplomatic formal transcription with raw colloquial street vernacular parsing.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Translates 15 youth slang idioms and elisions into standard literary Mongolian without losing emotional nuance",
          "Explains the social dynamics and peer solidarity signals encoded in non-standard vowel truncations"
        ],
        "masteryEvidence": "Produces an analytical sociolinguistic gloss of the 840-word verbatim transcript.",
        "recommendedExerciseModalities": ["source_comparison", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_229_03_rush_hour_traffic_quarrel_listening",
        "unitId": "unit_c2_229_rapid_khalkha_spoken_phonotactics_r",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 3,
        "title": "Acoustic Dissection: Multi-Party Dispute at Ulaanbaatar Intersection at 180 wpm",
        "lessonType": "listening",
        "primaryPurpose": "Listen to a 4.5-minute unedited recording of a spontaneous verbal confrontation between drivers and a traffic police officer during peak Ulaanbaatar gridlock, spoken at 170-195 wpm with ambient traffic noise, severe vowel truncations, and heated emotional inflections.",
        "communicativeOutcome": "Process native Khalkha speech under acoustic stress and emotional agitation, tracking rapid claims, defensive retorts, and informal bargaining.",
        "objectivesIntroduced": ["obj_c2_229_03_comprehend_fast_spontaneous_quarrels"],
        "objectivesPracticed": ["obj_c2_229_01_master_khalkha_phonotactics"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c2_rapid_khalkha_spoken_phonotactics"],
        "grammarReviewed": ["gram_c1_register_switching_matrix"],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phon_c2_01_rapid_vowel_syncope_assimilation"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_01_rapid_colloquial_banter"],
        "communicativeFunctionsReviewed": ["comm_b2_10_high_stakes_negotiation"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_gnomic_wisdom_proverbs_rhetoric"],
        "previousVocabularyReused": ["замын хөдөлгөөн", "маргаан", "жолооч", "бухимдал", "цагдаа"],
        "readingObjective": "",
        "listeningObjective": "Decipher high-speed emotional Khalkha speech overlaid with city background noise, extracting factual disputes and interpersonal posturing.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "spontaneous confrontational street colloquial",
        "pragmaticTarget": "conflict escalation and de-escalation tracking",
        "prerequisiteLessonIds": ["les_c2_229_02_unedited_street_dialogue_transcripts_reading"],
        "reviewsLessonIds": ["les_c1_228_02_grand_capstone_national_security_council_listening"],
        "reviewsUnitIds": ["unit_c1_228_c1_operational_proficiency_capstone"],
        "reviewReason": "Transitions from high-statecraft executive multi-speaker listening to raw street-level acoustic complexity.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide authentic field audio of rapid heated urban exchange with real background honking and native acoustic elisions.",
        "successCriteria": [
          "Transcribes the central legal grievance of both parties despite speech rate exceeding 175 wpm",
          "Identifies the exact verbal turn where tone shifts from aggressive confrontation to negotiated settlement"
        ],
        "masteryEvidence": "Produces a forensic auditory transcript and situational analysis of the multi-party street dispute.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "stance_identification"]
      },
      {
        "lessonId": "les_c2_229_04_dialogue_adaptation_screenplay_writing",
        "unitId": "unit_c2_229_rapid_khalkha_spoken_phonotactics_r",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 4,
        "title": "Creative Writing: Authoring Realistic Contemporary Cinematic Screenplay Dialogue",
        "lessonType": "writing",
        "primaryPurpose": "Author an 750-word cinematic screenplay scene featuring natural Khalkha dialogue between contrasting social archetypes (a cynical tech entrepreneur, an elderly traditionalist, and a savvy taxi driver), capturing genuine spoken cadence, incomplete thoughts, and natural contractions.",
        "communicativeOutcome": "Produce hyper-realistic dramatic dialogue in Mongolian that sounds organic and rhythmically authentic when read aloud by native actors.",
        "objectivesIntroduced": ["obj_c2_229_04_author_authentic_dramatic_dialogue"],
        "objectivesPracticed": ["obj_c2_229_01_master_khalkha_phonotactics"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c2_rapid_khalkha_spoken_phonotactics"],
        "grammarReviewed": ["gram_c1_register_switching_matrix"],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phon_c2_01_rapid_vowel_syncope_assimilation"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_01_rapid_colloquial_banter"],
        "communicativeFunctionsReviewed": ["comm_c1_10_rhetorical_speechwriting"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c2_gnomic_wisdom_proverbs_rhetoric"],
        "previousVocabularyReused": ["кино зохиол", "харилцан яриа", "дүр бүтээх", "бодит амьдрал"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Draft screenplay dialogue integrating natural phonotactic contractions ('юу гэнэ ээ' -> 'юунэ', 'хүрээд ир' -> 'хүрээдрээ') without becoming unintelligible.",
        "spokenProductionObjective": "",
        "registerTarget": "contemporary dramatic screenwriting",
        "pragmaticTarget": "character voice differentiation and verisimilitude",
        "prerequisiteLessonIds": ["les_c2_229_03_rush_hour_traffic_quarrel_listening"],
        "reviewsLessonIds": ["les_c1_224_05_philosophical_essay_nomadic_civilization_writing"],
        "reviewsUnitIds": ["unit_c1_224_classical_converb_relics_suffixes_"],
        "reviewReason": "Contrasts elevated classical essay writing with hyper-realistic contemporary screen dialogue.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Differentiates the generational and social backgrounds of all three characters through lexical choice and contraction frequency",
          "Maintains organic dramatic pacing with realistic interruptions, subtext, and non-verbal beats"
        ],
        "masteryEvidence": "Submits a compliant 750-word screenplay dialogue scene ready for table-read by native theatrical actors.",
        "recommendedExerciseModalities": ["statutory_clause_drafting", "summary_writing"]
      },
      {
        "lessonId": "les_c2_229_05_spontaneous_rapid_podcast_banter_spoken",
        "unitId": "unit_c2_229_rapid_khalkha_spoken_phonotactics_r",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 5,
        "title": "Colloquial Speaking: Spontaneous Rapid Banter on an Unscripted Cultural Podcast",
        "lessonType": "spoken_production",
        "primaryPurpose": "Participate in an unscripted 4.5-minute fast-paced simulated podcast dialogue with two native co-hosts, reacting spontaneously to sudden topic pivots, bantering with native phonotactics, and interrupting naturally without awkward pauses.",
        "communicativeOutcome": "Demonstrate effortless, native-like conversational velocity (160+ wpm), deploying reductions, laughter tokens, and witty quips in real time.",
        "objectivesIntroduced": ["obj_c2_229_05_perform_rapid_podcast_banter"],
        "objectivesPracticed": ["obj_c2_229_01_master_khalkha_phonotactics"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c2_rapid_khalkha_spoken_phonotactics"],
        "grammarReviewed": ["gram_c1_register_switching_matrix"],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phon_c2_01_rapid_vowel_syncope_assimilation"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_01_rapid_colloquial_banter"],
        "communicativeFunctionsReviewed": ["comm_c1_14_navigating_subtle_social_hierarchies"],
        "newProductiveLemmaTarget": 4,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 1,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c2_gnomic_wisdom_proverbs_rhetoric"],
        "previousVocabularyReused": ["подкаст", "чөлөөт яриа", "давхар ярих", "хурдан хэмнэл"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Execute spontaneous spoken banter at 160+ wpm with native-tier phonological flow, seamless interjections, and natural laughter modulation.",
        "registerTarget": "educated contemporary podcast colloquial",
        "pragmaticTarget": "social chemistry and spontaneous conversational wit",
        "prerequisiteLessonIds": ["les_c2_229_04_dialogue_adaptation_screenplay_writing"],
        "reviewsLessonIds": ["les_c1_228_05_grand_capstone_un_general_assembly_oratory_spoken"],
        "reviewsUnitIds": ["unit_c1_228_c1_operational_proficiency_capstone"],
        "reviewReason": "Contrasts monumental UN plenary oratory with spontaneous, rapid conversational agility.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide benchmark audio of two urban professionals conducting rapid, humorous cultural podcast banter.",
        "successCriteria": [
          "Maintains speech tempo above 160 wpm without hesitation, false starts, or foreign phonetic hyper-articulation",
          "Successfully executes 3 spontaneous conversational overlaps and humorously reframes an unexpected question"
        ],
        "masteryEvidence": "Delivers an unscripted 4.5-minute podcast colloquy exhibiting impeccable native-tier conversational cadence.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
      }
    ])

    # ----------------------------------------------------
    # UNIT 230: Conversational Repair, Turn-Taking & Discourse Particles (PL=24, RL=31, PE=9, RE=7) - 5 lessons
    # ----------------------------------------------------
    lessons.extend([
      {
        "lessonId": "les_c2_230_01_conversational_repair_syntax_intro",
        "unitId": "unit_c2_230_conversational_repair_turn_taking_p",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 1,
        "title": "Morphosyntax: Conversational Repair, Hesitation Particles & Pragmatic Turn-Holding Devices",
        "lessonType": "grammar_introduction",
        "primaryPurpose": "Introduce the syntactic structures and pragmatic mechanics of conversational self-repair (юу билээ, аль вэ, үгүй ээ тэр чинь), turn-holding filler particles (нөгөө юу л даа, ер нь болбол), and subtle concession tokens in natural Khalkha interactions.",
        "communicativeOutcome": "Manage floor control, repair speech errors instantaneously, and hold conversational turns naturally without creating awkward communicative silences.",
        "objectivesIntroduced": ["obj_c2_230_01_master_conversational_repair"],
        "objectivesPracticed": ["obj_c2_229_01_master_khalkha_phonotactics"],
        "objectivesReviewed": [],
        "grammarIntroduced": ["gram_c2_conversational_repair_and_discourse_particles"],
        "grammarPracticed": ["gram_c2_rapid_khalkha_spoken_phonotactics"],
        "grammarReviewed": ["gram_b2_pragmatic_emphatic_stance_particles"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": ["comm_c2_02_conversational_repair_turn_taking"],
        "communicativeFunctionsPracticed": [],
        "communicativeFunctionsReviewed": ["comm_c2_01_rapid_colloquial_banter"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 7,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_gnomic_wisdom_proverbs_rhetoric"],
        "previousVocabularyReused": ["ярианы ээлж", "алдаа засах", "сул үг", "яриа таслахгүй байх"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "conversational pragmatic management",
        "pragmaticTarget": "floor control and seamless self-repair",
        "prerequisiteLessonIds": ["les_c2_229_05_spontaneous_rapid_podcast_banter_spoken"],
        "reviewsLessonIds": ["les_c2_229_01_khalkha_phonotactics_syntax_intro"],
        "reviewsUnitIds": ["unit_c2_229_rapid_khalkha_spoken_phonotactics_r"],
        "reviewReason": "Integrates phonotactic reductions into interactive conversational turn-taking and repair.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Deploys 5 varied Mongolian repair devices ('юу билээ', 'тийм биш ээ юу гэдэг билээ') during complex spontaneous speech retrieval",
          "Holds the conversational floor effectively against interruption attempts using native discourse elongation particles"
        ],
        "masteryEvidence": "Successfully executes 6 seamless conversational repairs in an impromptu argumentative simulation.",
        "recommendedExerciseModalities": ["stylistic_transformation", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_230_02_conversational_analysis_transcripts_reading",
        "unitId": "unit_c2_230_conversational_repair_turn_taking_p",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 2,
        "title": "Discourse Reading: Conversation Analysis of Disagreement in Live Radio Call-In Shows",
        "lessonType": "reading",
        "primaryPurpose": "Parse an 830-word annotated Conversation Analysis (CA) transcript of a contentious live radio phone-in show, analyzing micro-pauses (0.2s–0.8s), latching, overlap management, and polite pre-disagreement tokens ('Тийм л дээ, гэхдээ...').",
        "communicativeOutcome": "Deconstruct micro-level interactional architecture in spoken Mongolian, recognizing how power, entitlement, and deference are negotiated turn-by-turn.",
        "objectivesIntroduced": ["obj_c2_230_02_parse_ca_transcripts"],
        "objectivesPracticed": ["obj_c2_230_01_master_conversational_repair"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c2_conversational_repair_and_discourse_particles"],
        "grammarReviewed": ["gram_c2_rapid_khalkha_spoken_phonotactics"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_02_conversational_repair_turn_taking"],
        "communicativeFunctionsReviewed": ["comm_c1_14_navigating_subtle_social_hierarchies"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c2_gnomic_wisdom_proverbs_rhetoric"],
        "previousVocabularyReused": ["харилцан ярианы шинжилгээ", "давхардалт", "түр завсарлага", "санал зөрөлдөөн"],
        "readingObjective": "Analyze Jefferson-transcribed live radio debates evaluating turn-taking timing, floor-stealing strategies, and repair sequences.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "live broadcast conversation analysis",
        "pragmaticTarget": "interactional micro-structure deconstruction",
        "prerequisiteLessonIds": ["les_c2_230_01_conversational_repair_syntax_intro"],
        "reviewsLessonIds": ["les_c2_229_02_unedited_street_dialogue_transcripts_reading"],
        "reviewsUnitIds": ["unit_c2_229_rapid_khalkha_spoken_phonotactics_r"],
        "reviewReason": "Extends informal street transcript reading into rigorous conversation analysis of live media broadcasts.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Identifies 4 distinct pre-disagreement markers and explains their role in mitigating face threat",
          "Maps the turn-transition relevance places (TRPs) where the host reclaims control from an agitated caller"
        ],
        "masteryEvidence": "Constructs a technical interactional commentary on an 830-word multi-speaker transcript.",
        "recommendedExerciseModalities": ["argument_mapping", "source_comparison"]
      },
      {
        "lessonId": "les_c2_230_03_talk_show_cross_talk_listening",
        "unitId": "unit_c2_230_conversational_repair_turn_taking_p",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 3,
        "title": "Acoustic Dissection: Television Talk Show Panel Cross-Talk & Interruption Duels",
        "lessonType": "listening",
        "primaryPurpose": "Listen to a 4.5-minute unedited excerpt of a high-energy television talk show panel where three guests talk over each other at 170 wpm, deploying competitive overlaps, volume elevation, and pragmatic repair formulas to win the floor.",
        "communicativeOutcome": "Process overlapping acoustic streams simultaneously, identifying who yields the floor, who dominates, and how conversational face is preserved.",
        "objectivesIntroduced": ["obj_c2_230_03_comprehend_overlapping_cross_talk"],
        "objectivesPracticed": ["obj_c2_230_01_master_conversational_repair"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c2_conversational_repair_and_discourse_particles"],
        "grammarReviewed": ["gram_c2_rapid_khalkha_spoken_phonotactics"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_02_conversational_repair_turn_taking"],
        "communicativeFunctionsReviewed": ["comm_c1_14_navigating_subtle_social_hierarchies"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_gnomic_wisdom_proverbs_rhetoric"],
        "previousVocabularyReused": ["нэвтрүүлэг", "хөтлөгч", "үг булаалдах", "уулга алдах", "хүндэтгэл"],
        "readingObjective": "",
        "listeningObjective": "Decipher dense overlapping cross-talk where speakers battle for speaking turns using subtle intonation shifts and repair tokens.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "televised debate cross-talk",
        "pragmaticTarget": "competitive turn-taking and floor reclamation",
        "prerequisiteLessonIds": ["les_c2_230_02_conversational_analysis_transcripts_reading"],
        "reviewsLessonIds": ["les_c2_229_03_rush_hour_traffic_quarrel_listening"],
        "reviewsUnitIds": ["unit_c2_229_rapid_khalkha_spoken_phonotactics_r"],
        "reviewReason": "Bridges street quarrel listening into televised high-stakes panel cross-talk processing.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide authentic broadcast recording with simultaneous multi-speaker overlaps and complex turn-taking dynamics.",
        "successCriteria": [
          "Transcribes the overlapping speech segments of both competing speakers with accurate temporal alignment",
          "Identifies the specific pragmatic device used by the host to restore order without appearing heavy-handed"
        ],
        "masteryEvidence": "Produces an acoustic overlap transcript and turn-taking audit of the panel discussion.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_230_04_moderators_crisis_script_writing",
        "unitId": "unit_c2_230_conversational_repair_turn_taking_p",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 4,
        "title": "Discourse Writing: Designing a Moderator's Intervention Protocol for Hostile Panels",
        "lessonType": "writing",
        "primaryPurpose": "Author an 780-word Master Moderator's Live Intervention Guide codifying linguistic scripts for defusing vitriolic interruptions, managing aggressive filibustering, and redirecting dialogue using polished Mongolian discourse particles.",
        "communicativeOutcome": "Produce sophisticated meta-pragmatic intervention frameworks in Mongolian, setting authoritative standards for live broadcast media moderation.",
        "objectivesIntroduced": ["obj_c2_230_04_author_moderation_protocols"],
        "objectivesPracticed": ["obj_c2_230_01_master_conversational_repair"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c2_conversational_repair_and_discourse_particles"],
        "grammarReviewed": ["gram_c1_academic_hedging_and_epistemic_stance"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_02_conversational_repair_turn_taking"],
        "communicativeFunctionsReviewed": ["comm_c1_09_high_level_policy_briefs"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c2_gnomic_wisdom_proverbs_rhetoric"],
        "previousVocabularyReused": ["зохицуулагч", "хэлэлцүүлэг удирдах", "яриаг чиглүүлэх", "эв зүй"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Draft a complete moderator's tactical manual specifying exact phrasings for 6 escalating levels of panel disruption.",
        "spokenProductionObjective": "",
        "registerTarget": "professional media moderation protocol",
        "pragmaticTarget": "authoritative communicative de-escalation",
        "prerequisiteLessonIds": ["les_c2_230_03_talk_show_cross_talk_listening"],
        "reviewsLessonIds": ["les_c2_229_04_dialogue_adaptation_screenplay_writing"],
        "reviewsUnitIds": ["unit_c2_229_rapid_khalkha_spoken_phonotactics_r"],
        "reviewReason": "Synthesizes screenplay dialogue mechanics into high-level media moderation protocols.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Formulates nuanced intervention phrases balancing polite Mongolian deference with unyielding editorial authority",
          "Integrates conversational repair markers into smooth topical transitions under time constraints"
        ],
        "masteryEvidence": "Submits a compliant 780-word live moderation protocol adopted by a major television network.",
        "recommendedExerciseModalities": ["statutory_clause_drafting", "summary_writing"]
      },
      {
        "lessonId": "les_c2_230_05_live_panel_moderation_simulation_spoken",
        "unitId": "unit_c2_230_conversational_repair_turn_taking_p",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 5,
        "title": "Interactive Speaking: Live Moderation of a Volatile Political & Cultural Panel",
        "lessonType": "spoken_production",
        "primaryPurpose": "Moderate an unscripted 4.5-minute heated panel discussion between two feuding guests, managing turn allocations, interrupting politely yet firmly, repairing overlapping chaos, and summarizing consensus in real time.",
        "communicativeOutcome": "Demonstrate supreme conversational agility as an authoritative moderator, exercising effortless floor control and conversational repair under intense live pressure.",
        "objectivesIntroduced": ["obj_c2_230_05_moderate_volatile_panels_orally"],
        "objectivesPracticed": ["obj_c2_230_01_master_conversational_repair"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c2_conversational_repair_and_discourse_particles"],
        "grammarReviewed": ["gram_c1_register_switching_matrix"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_02_conversational_repair_turn_taking"],
        "communicativeFunctionsReviewed": ["comm_c1_14_navigating_subtle_social_hierarchies"],
        "newProductiveLemmaTarget": 4,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 1,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c2_gnomic_wisdom_proverbs_rhetoric"],
        "previousVocabularyReused": ["үг өгөх", "дүгнэх", "шууд нэвтрүүлэг", "хүндэт зочин", "санал хураалт"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Execute live verbal moderation controlling speaker transitions, defusing aggressive outbursts, and repairing communicative breakdowns flawlessly.",
        "registerTarget": "live media debate moderator oral",
        "pragmaticTarget": "firm diplomatic floor arbitration",
        "prerequisiteLessonIds": ["les_c2_230_04_moderators_crisis_script_writing"],
        "reviewsLessonIds": ["les_c2_229_05_spontaneous_rapid_podcast_banter_spoken"],
        "reviewsUnitIds": ["unit_c2_229_rapid_khalkha_spoken_phonotactics_r"],
        "reviewReason": "Culminates podcast banter agility into high-stakes live television panel moderation.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide benchmark audio of expert moderator orchestrating heated broadcast panel.",
        "successCriteria": [
          "Successfully interrupts a filibustering guest within 5 seconds using appropriate pragmatic particles without causing offense",
          "Executes 2 spontaneous communicative repairs to clarify ambiguous participant claims"
        ],
        "masteryEvidence": "Moderates an unscripted 4.5-minute high-conflict panel simulation demonstrating absolute conversational mastery.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
      }
    ])

    return lessons
