# -*- coding: utf-8 -*-
"""CEFR C2 Section 02 Part 1: The Secret History & Classical Philology (Units 238-242, 25 lessons)."""

def get_units_238_242():
    lessons = []

    # ----------------------------------------------------
    # UNIT 238: The Secret History of the Mongols: Philological Introduction (PL=22, RL=35, PE=9, RE=10) - 5 lessons
    # ----------------------------------------------------
    lessons.extend([
      {
        "lessonId": "les_c2_238_01_secret_history_philological_foundations_intro",
        "unitId": "unit_c2_238_the_secret_history_of_the_mongols_p",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 1,
        "title": "Philological Foundations: The Secret History of the Mongols (1240), Ming Transcriptions & Sinitic Glosses",
        "lessonType": "grammar_introduction",
        "primaryPurpose": "Introduce the textual genealogy, Ming Dynasty phonetic transcription system (Chinese characters with diacritics for Middle Mongolian sounds), interlinear glossing, and 20th-century Mongolian decipherment (Ts. Damdinsuren, Shiratori, Pelliot, Haenisch).",
        "communicativeOutcome": "Comprehend the historical-philological architecture of the Secret History, parsing Middle Mongolian linguistic reconstructions alongside modern Khalkha renditions.",
        "objectivesIntroduced": ["obj_c2_238_01_master_secret_history_philology"],
        "objectivesPracticed": ["obj_c2_237_01_synthesize_c2_sec01_stylistics"],
        "objectivesReviewed": ["obj_c1_224_01_master_classical_converbs"],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c2_dialectal_morphosyntax_awareness"],
        "grammarReviewed": ["gram_c1_classical_quotative_khemeen"],
        "phonologyIntroduced": ["phon_c2_05_middle_mongolian_phonology_reconstruction"],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": ["comm_c2_10_secret_history_philological_reading"],
        "communicativeFunctionsPracticed": ["comm_c2_15_creative_mastery_authorial_voice"],
        "communicativeFunctionsReviewed": ["comm_c1_07_literary_and_philosophical_hermeneutics"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 7,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["Монголын нууц товчоо", "эх бичиг судлал", "дундад зууны монгол хэл", "хятад галиг"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "archaic Middle Mongolian philological scholarship",
        "pragmaticTarget": "monumental textual authority and medieval historiography",
        "prerequisiteLessonIds": ["les_c2_237_06_c2_sec01_culminating_operational_synthesis"],
        "reviewsLessonIds": ["les_c1_224_01_classical_converb_relics_syntax_intro"],
        "reviewsUnitIds": ["unit_c1_224_classical_converb_relics_suffixes_"],
        "reviewReason": "Bridges C1 classical grammatical converbs into foundational Middle Mongolian philology.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Explains the 3 major transmission stages of the Secret History (1240 original Uighur-Mongolian, 1382 Ming phonetic transcript, 1947 Damdinsuren modern Cyrillic adaptation)",
          "Parses 4 reconstructed Middle Mongolian phrases comparing original phonetic forms with modern Khalkha cognates"
        ],
        "masteryEvidence": "Produces an authoritative philological analysis of 5 Middle Mongolian manuscript fragments.",
        "recommendedExerciseModalities": ["stylistic_transformation", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_238_02_secret_history_prologue_bodonchar_reading",
        "unitId": "unit_c2_238_the_secret_history_of_the_mongols_p",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 2,
        "title": "Textual Reading: The Mythic Genealogy & Bodonchar Munkhag (§1-§44)",
        "lessonType": "reading",
        "primaryPurpose": "Parse an 880-word critical edition excerpt of the opening chapters of the Secret History (§1 Börte Chino and Qo'ai Maral, to §44 Bodonchar capture of the pregnant woman), analyzing medieval narrative pacing, mythic geography, and ancestral lineage formulas.",
        "communicativeOutcome": "Deconstruct foundational 13th-century Mongolian epic prose, analyzing the intertwining of totemic mythology and historical clan formation.",
        "objectivesIntroduced": ["obj_c2_238_02_parse_bodonchar_mythic_genealogy"],
        "objectivesPracticed": ["obj_c2_238_01_master_secret_history_philology"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c2_dialectal_morphosyntax_awareness"],
        "grammarReviewed": ["gram_c1_classical_participle_khui"],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phon_c2_05_middle_mongolian_phonology_reconstruction"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_10_secret_history_philological_reading"],
        "communicativeFunctionsReviewed": ["comm_c1_07_literary_and_philosophical_hermeneutics"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 7,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["Бөртэ чоно", "Гоо марал", "Бодончар мунхаг", "овог аймаг", "ясан төрөл"],
        "readingObjective": "Analyze critical edition of Secret History prologue deconstructing totemic symbolism, kinship nomenclature, and mythic syntax.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "13th-century Middle Mongolian epic historical chronicle",
        "pragmaticTarget": "mythological genesis and clan foundation legitimacy",
        "prerequisiteLessonIds": ["les_c2_238_01_secret_history_philological_foundations_intro"],
        "reviewsLessonIds": ["les_c2_237_02_c2_sec01_capstone_literary_monument_reading"],
        "reviewsUnitIds": ["unit_c2_237_contemporary_literature_capstone_sa"],
        "reviewReason": "Contrasts 21st-century modernist fiction reading with 13th-century foundational epic chronicle parsing.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Identifies 6 archaic clan and kinship designators that lack exact modern equivalents",
          "Interprets the philosophical aphorism of Bodonchar ('Агтанд эзэн үгүй, дээлэнд зах үгүй') in its medieval political context"
        ],
        "masteryEvidence": "Produces an 880-word philological and historical commentary on §1-§44.",
        "recommendedExerciseModalities": ["source_comparison", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_238_03_damdinsuren_scholarly_lecture_listening",
        "unitId": "unit_c2_238_the_secret_history_of_the_mongols_p",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 3,
        "title": "Acoustic Dissection: Academician Ts. Damdinsuren's Master Lectures on Deciphering the Monument",
        "lessonType": "listening",
        "primaryPurpose": "Listen to a 4.5-minute archival recording of Academician Ts. Damdinsuren lecturing at the Mongolian Academy of Sciences (160 wpm), deconstructing his philological principles when translating 13th-century Middle Mongolian verse into modern literary Cyrillic.",
        "communicativeOutcome": "Process high-level historical philological lectures by Mongolia's greatest 20th-century philologist, tracking linguistic methodology and textual reconstructions.",
        "objectivesIntroduced": ["obj_c2_238_03_comprehend_damdinsuren_lectures"],
        "objectivesPracticed": ["obj_c2_238_01_master_secret_history_philology"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c2_dialectal_morphosyntax_awareness"],
        "grammarReviewed": ["gram_c1_academic_hedging_and_epistemic_stance"],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phon_c2_05_middle_mongolian_phonology_reconstruction"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_10_secret_history_philological_reading"],
        "communicativeFunctionsReviewed": ["comm_c1_03_academic_thesis_defense"],
        "newProductiveLemmaTarget": 4,
        "newReceptiveLemmaTarget": 7,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["Ц.Дамдинсүрэн", "Шинжлэх ухааны академи", "орчуулгын зарчим", "шүлэг найраг"],
        "readingObjective": "",
        "listeningObjective": "Decipher archival academic lectures on textual transmission, paleographic anomalies, and alliterative verse restoration.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "scholarly philological keynote lecture oral",
        "pragmaticTarget": "academic methodology and cultural heritage restitution",
        "prerequisiteLessonIds": ["les_c2_238_02_secret_history_prologue_bodonchar_reading"],
        "reviewsLessonIds": ["les_c2_237_03_c2_sec01_capstone_rapid_cultural_debate_listening"],
        "reviewsUnitIds": ["unit_c2_237_contemporary_literature_capstone_sa"],
        "reviewReason": "Transitions from high-velocity modern debate listening into authoritative archival academic philological lectures.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide authentic historical audio recording of Academician Damdinsuren discussing Secret History translation problems.",
        "successCriteria": [
          "Transcribes Damdinsuren's philological explanation for rendering archaic verbal converbs into modern Khalkha",
          "Identifies the specific scholarly debate with Soviet and Hungarian Mongolists addressed in the lecture"
        ],
        "masteryEvidence": "Produces an exhaustive acoustic and conceptual summary of the archival academic lecture.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_238_04_critical_apparatus_edition_writing",
        "unitId": "unit_c2_238_the_secret_history_of_the_mongols_p",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 4,
        "title": "Philological Writing: Authoring a Critical Textual Apparatus & Paleographic Note",
        "lessonType": "writing",
        "primaryPurpose": "Author an 800-word critical textual apparatus note for an academic edition of the Secret History (§21-§22), comparing variant readings between the Ye Dehui print, the Lu Xun manuscript, and modern reconstructions, defending a proposed emendation.",
        "communicativeOutcome": "Produce rigorous philological scholarship in Mongolian, demonstrating the highest standards of textual criticism and historical linguistics.",
        "objectivesIntroduced": ["obj_c2_238_04_author_philological_critical_apparatus"],
        "objectivesPracticed": ["obj_c2_238_01_master_secret_history_philology"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c2_dialectal_morphosyntax_awareness"],
        "grammarReviewed": ["gram_c1_academic_nominalization_frames"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_10_secret_history_philological_reading"],
        "communicativeFunctionsReviewed": ["comm_c1_04_peer_review_and_scholarly_refutation"],
        "newProductiveLemmaTarget": 4,
        "newReceptiveLemmaTarget": 7,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["текст судлал", "гар бичмэл", "хувилбар", "үгийн язгуур", "тайлбар зүүлт"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Draft an 800-word scholarly apparatus justifying a textual emendation using comparative Altaic and Mongolic philological evidence.",
        "spokenProductionObjective": "",
        "registerTarget": "academic philological apparatus criticus",
        "pragmaticTarget": "scholarly precision and rigorous textual defense",
        "prerequisiteLessonIds": ["les_c2_238_03_damdinsuren_scholarly_lecture_listening"],
        "reviewsLessonIds": ["les_c2_237_04_c2_sec01_capstone_satirical_novella_writing"],
        "reviewsUnitIds": ["unit_c2_237_contemporary_literature_capstone_sa"],
        "reviewReason": "Contrasts creative novella authorship with exacting academic textual criticism and philological drafting.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Follows international standard epigraphic and philological notation conventions in academic Mongolian",
          "Provides decisive phonological proof resolving an ambiguous Chinese phonetic character transcription"
        ],
        "masteryEvidence": "Submits an 800-word philological critical apparatus note deemed publishable in *Acta Mongolica*.",
        "recommendedExerciseModalities": ["statutory_clause_drafting", "summary_writing"]
      },
      {
        "lessonId": "les_c2_238_05_orientalists_congress_philological_paper_spoken",
        "unitId": "unit_c2_238_the_secret_history_of_the_mongols_p",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 5,
        "title": "Academic Speaking: Presenting a Philological Treatise at the International Congress of Mongolists",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver an unscripted 5.0-minute academic paper at the International Congress of Mongolists (Олон Улсын Монголч Эрдэмтдийн Их Хурал), presenting an original thesis on Middle Mongolian syntactic structures in the Secret History.",
        "communicativeOutcome": "Demonstrate effortless academic mastery among global experts, presenting dense historical linguistic data with impeccable poise, eloquence, and scholarly clarity.",
        "objectivesIntroduced": ["obj_c2_238_05_deliver_mongolist_congress_papers"],
        "objectivesPracticed": ["obj_c2_238_01_master_secret_history_philology"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c2_dialectal_morphosyntax_awareness"],
        "grammarReviewed": ["gram_c1_academic_hedging_and_epistemic_stance"],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phon_c2_05_middle_mongolian_phonology_reconstruction"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_10_secret_history_philological_reading"],
        "communicativeFunctionsReviewed": ["comm_c1_03_academic_thesis_defense"],
        "newProductiveLemmaTarget": 4,
        "newReceptiveLemmaTarget": 7,
        "newProductiveExpressionTarget": 1,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["Монголч эрдэмтдийн их хурал", "эрдэм шинжилгээний илтгэл", "өгүүлбэр зүй", "хэлний хувьсал"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Execute an authoritative 5-minute academic presentation defending a novel philological hypothesis on Middle Mongolian grammar.",
        "registerTarget": "international scholarly congress plenary oral",
        "pragmaticTarget": "peerless scholarly authority and scientific defense",
        "prerequisiteLessonIds": ["les_c2_238_04_critical_apparatus_edition_writing"],
        "reviewsLessonIds": ["les_c2_237_05_c2_sec01_capstone_literary_critics_defense_spoken"],
        "reviewsUnitIds": ["unit_c2_237_contemporary_literature_capstone_sa"],
        "reviewReason": "Elevates writers' union defense into global international Mongolist academic symposium presentation.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide benchmark audio of distinguished Mongolist presenting keynote address at State Palace congress.",
        "successCriteria": [
          "Articulates complex Middle Mongolian phonetic reconstructions accurately while lecturing in modern academic Khalkha",
          "Fields 2 technical questions from international linguists with definitive philological citations"
        ],
        "masteryEvidence": "Delivers an unscripted 5-minute scholarly conference paper receiving highest accolades from the academic committee.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
      }
    ])

    # ----------------------------------------------------
    # UNIT 239: Classical Epic Syntax in The Secret History (PL=24, RL=36, PE=9, RE=10) - 5 lessons
    # ----------------------------------------------------
    lessons.extend([
      {
        "lessonId": "les_c2_239_01_classical_epic_syntax_intro",
        "unitId": "unit_c2_239_classical_epic_syntax_in_the_secret",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 1,
        "title": "Morphosyntax: Classical Epic Syntax, Medieval Word Order & Verb Serializations in 1240 Prose",
        "lessonType": "grammar_introduction",
        "primaryPurpose": "Introduce the epic syntactic architectures of 13th-century Mongolian: SOV inversions in poetic stanzas, archaic serial converb chains (-n, -ju/-chu, -ad), formulaic fronted epithets, and medieval quotative frame inversions.",
        "communicativeOutcome": "Parse and replicate medieval epic syntactic structures, analyzing how rhythmic cadences and verb stacking drive epic narrative tempo.",
        "objectivesIntroduced": ["obj_c2_239_01_master_classical_epic_syntax"],
        "objectivesPracticed": ["obj_c2_238_01_master_secret_history_philology"],
        "objectivesReviewed": [],
        "grammarIntroduced": ["gram_c2_classical_epic_syntax_secret_history"],
        "grammarPracticed": ["gram_c2_dialectal_morphosyntax_awareness"],
        "grammarReviewed": ["gram_c1_classical_converbs_vaas_khuits"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": ["comm_c2_10_secret_history_philological_reading"],
        "communicativeFunctionsPracticed": ["comm_c2_15_creative_mastery_authorial_voice"],
        "communicativeFunctionsReviewed": ["comm_c1_12_reverential_and_honorific_oratory"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 8,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["туулийн өгүүлбэр зүй", "үйл үгийн цуваа", "эртний өгүүлбэр", "нөхцөл үйл үг"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "Middle Mongolian epic syntactic archaism",
        "pragmaticTarget": "monumental narrative momentum and heroic grandeur",
        "prerequisiteLessonIds": ["les_c2_238_05_orientalists_congress_philological_paper_spoken"],
        "reviewsLessonIds": ["les_c1_224_01_classical_converb_relics_syntax_intro"],
        "reviewsUnitIds": ["unit_c1_224_classical_converb_relics_suffixes_"],
        "reviewReason": "Expands individual classical converb suffixes into comprehensive medieval epic sentence architecture.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Diagrams the syntactic tree of a 45-word multi-clause Middle Mongolian epic sentence from §195",
          "Converts 3 standard modern Khalkha narrative sentences into authentic 13th-century serial converb syntax"
        ],
        "masteryEvidence": "Parses and reconstructs 6 complex Middle Mongolian epic clauses with flawless syntactic accuracy.",
        "recommendedExerciseModalities": ["stylistic_transformation", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_239_02_battle_of_the_thirteen_wings_reading",
        "unitId": "unit_c2_239_classical_epic_syntax_in_the_secret",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 2,
        "title": "Epic Reading: The Clash of Temüjin & Jamukha at the Battle of the Thirteen Wings (§129)",
        "lessonType": "reading",
        "primaryPurpose": "Parse an 880-word critical text of the iconic Battle of Dalan Balzhut (§129), analyzing the deployment of alliterative warrior catalogs, horse color nomenclatures, and relentless serial converbs describing tactical cavalry maneuvers.",
        "communicativeOutcome": "Deconstruct authentic medieval nomadic martial literature, reading battlefield descriptions with total linguistic and tactical comprehension.",
        "objectivesIntroduced": ["obj_c2_239_02_parse_thirteen_wings_battle"],
        "objectivesPracticed": ["obj_c2_239_01_master_classical_epic_syntax"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c2_classical_epic_syntax_secret_history"],
        "grammarReviewed": ["gram_c1_classical_converbs_vaas_khuits"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_10_secret_history_philological_reading"],
        "communicativeFunctionsReviewed": ["comm_c1_07_literary_and_philosophical_hermeneutics"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 7,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["арван гурван хүрээ", "Далан балжуд", "тулалдаан", "морины зүс", "дайны тактик"],
        "readingObjective": "Analyze medieval battle narrative evaluating heroic poetic formulas, weapon descriptions, and military command syntax.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "13th-century heroic military epic chronicle",
        "pragmaticTarget": "martial valor, tactical ferocity, and tragic steppe rivalry",
        "prerequisiteLessonIds": ["les_c2_239_01_classical_epic_syntax_intro"],
        "reviewsLessonIds": ["les_c2_238_02_secret_history_prologue_bodonchar_reading"],
        "reviewsUnitIds": ["unit_c2_238_the_secret_history_of_the_mongols_p"],
        "reviewReason": "Progresses from genealogical prologue to dramatic military clash between Temüjin and Jamukha.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Decodes 8 medieval military terms (хүрээ, цахир хуяг, зэв, өрлөг) in their exact 13th-century operational senses",
          "Explains how serial converbs in §129 mimic the acoustic acceleration of galloping cavalry charges"
        ],
        "masteryEvidence": "Produces an 880-word military and philological exegesis of the Battle of Dalan Balzhut.",
        "recommendedExerciseModalities": ["source_comparison", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_239_03_secret_history_epic_recitation_listening",
        "unitId": "unit_c2_239_classical_epic_syntax_in_the_secret",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 3,
        "title": "Acoustic Dissection: Authentic Traditional Recitation of Secret History Poetic Stanzas",
        "lessonType": "listening",
        "primaryPurpose": "Listen to a 4.5-minute master recording of a national artist reciting poetic stanzas from the Secret History in traditional liturgical declamatory style (165 wpm), analyzing head-alliteration (*толгой холбох ёс*), metric feet, and solemn pause distribution.",
        "communicativeOutcome": "Process the traditional acoustic cadence of Middle Mongolian poetic verse, internalizing the intrinsic rhythm of ancient steppe oral composition.",
        "objectivesIntroduced": ["obj_c2_239_03_comprehend_epic_strophic_recitations"],
        "objectivesPracticed": ["obj_c2_239_01_master_classical_epic_syntax"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c2_classical_epic_syntax_secret_history"],
        "grammarReviewed": ["gram_c2_somatic_idiomatic_metaphors"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_10_secret_history_philological_reading"],
        "communicativeFunctionsReviewed": ["comm_c1_12_reverential_and_honorific_oratory"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 7,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["шүлэглэсэн уншлага", "толгой холбох", "айзам хэмнэл", "ардын жүжигчин", "эртний аялгуу"],
        "readingObjective": "",
        "listeningObjective": "Decipher traditional alliterative poetic recitations of medieval stanzas, extracting metric parallelism and formulaic epithets.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "epic liturgical alliterative declamation oral",
        "pragmaticTarget": "ancestral awe, heroic elevation, and rhythmic hypnosis",
        "prerequisiteLessonIds": ["les_c2_239_02_battle_of_the_thirteen_wings_reading"],
        "reviewsLessonIds": ["les_c2_238_03_damdinsuren_scholarly_lecture_listening"],
        "reviewsUnitIds": ["unit_c2_238_the_secret_history_of_the_mongols_p"],
        "reviewReason": "Contrasts analytical lecture listening with evocative artistic declamation of epic poetry.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide authentic recording of People's Artist reciting Secret History battle and prophecy stanzas.",
        "successCriteria": [
          "Transcribes 8 alliterative lines accurately identifying the alliterating initial consonants and syllable counts",
          "Explains how declamatory pitch elevation corresponds to heroic epithets in the strophic structure"
        ],
        "masteryEvidence": "Produces an acoustic and metrical transcription of the 4.5-minute poetic recitation.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_239_04_epic_praise_strophic_reconstruction_writing",
        "unitId": "unit_c2_239_classical_epic_syntax_in_the_secret",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 4,
        "title": "Creative Philological Writing: Composing an Epic Praise Strophe in Middle Mongolian Syntax",
        "lessonType": "writing",
        "primaryPurpose": "Author an 800-word epic poetic passage in the authentic style and syntax of the Secret History, commemorating a legendary steppe steed or fallen warrior using medieval serial converbs, head-alliteration, and archaic formulaic epithets.",
        "communicativeOutcome": "Demonstrate supreme creative and philological authorship, producing authentic-sounding 13th-century epic poetry that adheres strictly to Middle Mongolian syntactic and alliterative rules.",
        "objectivesIntroduced": ["obj_c2_239_04_compose_middle_mongolian_epic_verse"],
        "objectivesPracticed": ["obj_c2_239_01_master_classical_epic_syntax"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c2_classical_epic_syntax_secret_history"],
        "grammarReviewed": ["gram_c1_classical_participle_khui"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_10_secret_history_philological_reading"],
        "communicativeFunctionsReviewed": ["comm_c1_10_rhetorical_speechwriting"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 7,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["магтаал шүлэг", "хүлэг морь", "баатар эр", "эртний найруулга", "бадаг"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Draft an 800-word epic poetic narrative in Middle Mongolian verse form with rigorous four-line alliteration and serial converbs.",
        "spokenProductionObjective": "",
        "registerTarget": "high Middle Mongolian classical epic poetry",
        "pragmaticTarget": "monumental poetic verisimilitude and heroic myth-making",
        "prerequisiteLessonIds": ["les_c2_239_03_secret_history_epic_recitation_listening"],
        "reviewsLessonIds": ["les_c2_238_04_critical_apparatus_edition_writing"],
        "reviewsUnitIds": ["unit_c2_238_the_secret_history_of_the_mongols_p"],
        "reviewReason": "Transforms academic apparatus writing into active creative composition of Middle Mongolian poetry.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Maintains unbroken head-alliteration across all stanzas without metrical breakdown",
          "Deploys at least 8 authentic Middle Mongolian syntactic converb chains that echo the exact style of the 1240 monument"
        ],
        "masteryEvidence": "Submits an 800-word epic poetic text evaluated as indistinguishable from 13th-century manuscripts by experts.",
        "recommendedExerciseModalities": ["statutory_clause_drafting", "summary_writing"]
      },
      {
        "lessonId": "les_c2_239_05_secret_history_dramatic_declamation_spoken",
        "unitId": "unit_c2_239_classical_epic_syntax_in_the_secret",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 5,
        "title": "Mastery Speaking: Dramatic Oral Declamation of an Epic Stanza Before State Cultural Elders",
        "lessonType": "spoken_production",
        "primaryPurpose": "Perform an unscripted 5.0-minute dramatic oral declamation and contextual exegesis of a Secret History battlefield passage before an assembly of national cultural luminaries, delivering verse with authentic epic cadence and delivering spontaneous philological commentary.",
        "communicativeOutcome": "Command the ancient oral performance tradition of Mongolian epic declamation, captivating an audience with resonant vocal authority and deep literary erudition.",
        "objectivesIntroduced": ["obj_c2_239_05_perform_epic_strophic_declamations"],
        "objectivesPracticed": ["obj_c2_239_01_master_classical_epic_syntax"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c2_classical_epic_syntax_secret_history"],
        "grammarReviewed": ["gram_c1_reverential_and_honorific_oratory"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_10_secret_history_philological_reading"],
        "communicativeFunctionsReviewed": ["comm_c1_12_reverential_and_honorific_oratory"],
        "newProductiveLemmaTarget": 4,
        "newReceptiveLemmaTarget": 7,
        "newProductiveExpressionTarget": 1,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["жүжиглэсэн уншлага", "уран уншигч", "төрийн их найр", "өвөг дээдсийн дуун"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Execute a 5-minute dramatic epic declamation with booming acoustic resonance, flawless alliterative emphasis, and scholarly exegesis.",
        "registerTarget": "traditional epic rhapsodic performance & philological oratory oral",
        "pragmaticTarget": "monumental national reverence and artistic virtuosity",
        "prerequisiteLessonIds": ["les_c2_239_04_epic_praise_strophic_reconstruction_writing"],
        "reviewsLessonIds": ["les_c2_238_05_orientalists_congress_philological_paper_spoken"],
        "reviewsUnitIds": ["unit_c2_238_the_secret_history_of_the_mongols_p"],
        "reviewReason": "Unites scholarly congress presentation with traditional heroic bardic recitation.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide benchmark audio of dramatic oral performance of Secret History stanzas at national cultural festival.",
        "successCriteria": [
          "Delivers 16 lines of Middle Mongolian verse from memory with rhythmic power and traditional head-alliteration stress",
          "Transitions immediately into modern academic Khalkha to explain the political significance of the recited passage"
        ],
        "masteryEvidence": "Performs an unscripted 5-minute epic declamation and commentary earning unanimous praise from cultural elders.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
      }
    ])

    # ----------------------------------------------------
    # UNIT 240: Archaic Case Morphology: Suffixes -аачаан & -дур/-дүр (PL=24, RL=31, PE=9, RE=7) - 5 lessons
    # ----------------------------------------------------
    lessons.extend([
      {
        "lessonId": "les_c2_240_01_archaic_case_morphology_syntax_intro",
        "unitId": "unit_c2_240_archaic_case_morphology_suffixes_",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 1,
        "title": "Morphology: Middle Mongolian Archaic Case Suffixes (-аачаан/-ээчээн, -дур/-дүр, -и) & Syntactic Relics",
        "lessonType": "grammar_introduction",
        "primaryPurpose": "Introduce the historical morphology and functions of 13th-century case markers: the instrumental-sociative/prosecutive *-аачаан*, the archaic locative-dative *-дур/-дүр*, and the unpalatalized accusative *-и*, examining their syntactic environments in the Secret History.",
        "communicativeOutcome": "Decode and accurately interpret archaic Middle Mongolian case markers in monumental manuscripts and classical texts without confusion with modern suffixes.",
        "objectivesIntroduced": ["obj_c2_240_01_master_archaic_case_morphology"],
        "objectivesPracticed": ["obj_c2_239_01_master_classical_epic_syntax"],
        "objectivesReviewed": [],
        "grammarIntroduced": ["gram_c2_archaic_case_morphology_secret_history"],
        "grammarPracticed": ["gram_c2_classical_epic_syntax_secret_history"],
        "grammarReviewed": ["gram_c1_classical_participle_khui"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": ["comm_c2_10_secret_history_philological_reading"],
        "communicativeFunctionsPracticed": ["comm_c2_15_creative_mastery_authorial_voice"],
        "communicativeFunctionsReviewed": ["comm_c1_07_literary_and_philosophical_hermeneutics"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 7,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["тийн ялгал", "эртний нөхцөл", "орших оршихуйн тийн ялгал", "хэлбэр зүй"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "Middle Mongolian epigraphic morphosyntax",
        "pragmaticTarget": "grammatical precision in deciphering medieval inscriptions",
        "prerequisiteLessonIds": ["les_c2_239_05_secret_history_dramatic_declamation_spoken"],
        "reviewsLessonIds": ["les_c1_224_01_classical_converb_relics_syntax_intro"],
        "reviewsUnitIds": ["unit_c1_224_classical_converb_relics_suffixes_"],
        "reviewReason": "Deepens classical grammatical relics into archaic 13th-century nominal case paradigms.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Differentiates the semantic scope of archaic locative *-дур* from modern Khalkha *-д/-т*",
          "Correctly parses 6 sentences containing *-аачаан* indicating passage through space or instrument of action"
        ],
        "masteryEvidence": "Morphologically analyzes 10 complex Middle Mongolian nominal phrases with archaic inflections.",
        "recommendedExerciseModalities": ["stylistic_transformation", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_240_02_kho_elun_wrath_strophic_reading",
        "unitId": "unit_c2_240_archaic_case_morphology_suffixes_",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 2,
        "title": "Textual Reading: Mother Hö'elün's Epic Wrath & the Defense of Belgütei (§244)",
        "lessonType": "reading",
        "primaryPurpose": "Parse an 870-word critical text of §244 where Mother Hö'elün confronts Chinggis Khaan for suspecting Belgütei, analyzing her blistering alliterative rebuke packed with archaic locative and instrumental suffixes and maternal somatic metaphors.",
        "communicativeOutcome": "Interpret one of the highest dramatic summits of the Secret History, analyzing Mother Hö'elün's legendary speech with linguistic and cultural mastery.",
        "objectivesIntroduced": ["obj_c2_240_02_parse_hoelun_wrath_passage"],
        "objectivesPracticed": ["obj_c2_240_01_master_archaic_case_morphology"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c2_archaic_case_morphology_secret_history"],
        "grammarReviewed": ["gram_c2_somatic_idiomatic_metaphors"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_10_secret_history_philological_reading"],
        "communicativeFunctionsReviewed": ["comm_c1_07_literary_and_philosophical_hermeneutics"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["Өэлүн эх", "Бэлгүтэй", "эх хүний зэмлэл", "хөхний сүү", "цусан төрөл"],
        "readingObjective": "Analyze Mother Hö'elün's dramatic monologue deconstructing maternal somatic metaphors, archaic case endings, and moral authority.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "13th-century dramatic maternal moral rebuke epic prose",
        "pragmaticTarget": "sacred maternal authority overriding imperial majesty",
        "prerequisiteLessonIds": ["les_c2_240_01_archaic_case_morphology_syntax_intro"],
        "reviewsLessonIds": ["les_c2_239_02_battle_of_the_thirteen_wings_reading"],
        "reviewsUnitIds": ["unit_c2_239_classical_epic_syntax_in_the_secret"],
        "reviewReason": "Shifts from external military battlefield prose to intense internal dynastic and maternal drama.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Identifies 5 occurrences of archaic case endings in Mother Hö'elün's monologue and explains their rhythmic function",
          "Analyzes how maternal somatic imagery ('хөхөө гарган хэлсэн үг') asserts supreme customary law over imperial decree"
        ],
        "masteryEvidence": "Produces an 870-word philological and hermeneutic critique of §244.",
        "recommendedExerciseModalities": ["source_comparison", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_240_03_archaic_phonology_reconstruction_listening",
        "unitId": "unit_c2_240_archaic_case_morphology_suffixes_",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 3,
        "title": "Acoustic Dissection: Reconstructed Middle Mongolian Phonetics by Comparative Linguists",
        "lessonType": "listening",
        "primaryPurpose": "Listen to a 4.5-minute comparative audio study by historical phonologists reconstructing the exact phonetic realization of Middle Mongolian case suffixes, consonant clusters (*-gda-*, *-btar-*), and vowel qualities (160 wpm).",
        "communicativeOutcome": "Process reconstructed 13th-century spoken Mongolic phonology, discerning how ancient sounds evolved into modern Khalkha vowel syncope and vowel harmony.",
        "objectivesIntroduced": ["obj_c2_240_03_comprehend_middle_mongolian_phonetics"],
        "objectivesPracticed": ["obj_c2_240_01_master_archaic_case_morphology"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c2_archaic_case_morphology_secret_history"],
        "grammarReviewed": ["gram_c2_rapid_khalkha_spoken_phonotactics"],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phon_c2_05_middle_mongolian_phonology_reconstruction"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_10_secret_history_philological_reading"],
        "communicativeFunctionsReviewed": ["comm_c1_03_academic_thesis_defense"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["авиалбар зүй", "авианы өөрчлөлт", "хэлний түүх", "эгшиг зохицох ёс"],
        "readingObjective": "",
        "listeningObjective": "Decipher reconstructed Middle Mongolian phonetic recordings, identifying non-initial short vowels and voiced velar fricatives.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "comparative historical linguistic laboratory audio",
        "pragmaticTarget": "scientific phonetic reconstruction and diachronic rigor",
        "prerequisiteLessonIds": ["les_c2_240_02_kho_elun_wrath_strophic_reading"],
        "reviewsLessonIds": ["les_c2_239_03_secret_history_epic_recitation_listening"],
        "reviewsUnitIds": ["unit_c2_239_classical_epic_syntax_in_the_secret"],
        "reviewReason": "Compares artistic epic declamation with scientific historical phonetic reconstruction.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide studio recording of historical linguists demonstrating reconstructed Middle Mongolian pronunciation.",
        "successCriteria": [
          "Transcribes reconstructed phonetic passages using the International Phonetic Alphabet (IPA) and Cyrillic equivalents",
          "Explains the diachronic phonetic pathway from Middle Mongolian *-дур* to Modern Khalkha *-д*"
        ],
        "masteryEvidence": "Produces a forensic phonological analysis of the 4.5-minute acoustic reconstruction.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_240_04_comparative_grammar_treatise_writing",
        "unitId": "unit_c2_240_archaic_case_morphology_suffixes_",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 4,
        "title": "Philological Writing: Authoring a Comparative Treatise on Nomadic Declension Evolution",
        "lessonType": "writing",
        "primaryPurpose": "Author an 850-word historical linguistic treatise tracing the evolution of nominal case inflections from 13th-century Middle Mongolian through 17th-century Classical Mongolian to contemporary Khalkha.",
        "communicativeOutcome": "Produce advanced comparative linguistic scholarship in Mongolian, documenting historical grammatical shifts with authoritative mastery.",
        "objectivesIntroduced": ["obj_c2_240_04_author_historical_declension_treatises"],
        "objectivesPracticed": ["obj_c2_240_01_master_archaic_case_morphology"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c2_archaic_case_morphology_secret_history"],
        "grammarReviewed": ["gram_c1_academic_nominalization_frames"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_10_secret_history_philological_reading"],
        "communicativeFunctionsReviewed": ["comm_c1_04_peer_review_and_scholarly_refutation"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["хэлний хувьсал", "харьцуулсан хэл шинжлэл", "хувиргал зүй", "түүхэн хэл зүй"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Draft an 850-word diachronic linguistic treatise with detailed declension tables and attested textual citations.",
        "spokenProductionObjective": "",
        "registerTarget": "academic historical grammar scholarship",
        "pragmaticTarget": "authoritative diachronic grammatical systematization",
        "prerequisiteLessonIds": ["les_c2_240_03_archaic_phonology_reconstruction_listening"],
        "reviewsLessonIds": ["les_c2_239_04_epic_praise_strophic_reconstruction_writing"],
        "reviewsUnitIds": ["unit_c2_239_classical_epic_syntax_in_the_secret"],
        "reviewReason": "Bridges creative epic strophe composition into rigorous historical grammar documentation.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Constructs rigorous comparative paradigms illustrating sound loss, assimilation, and semantic narrowing across 800 years",
          "Demonstrates complete command of modern Mongolian academic linguistic terminology"
        ],
        "masteryEvidence": "Submits an 850-word comparative grammar treatise evaluated at doctoral dissertation tier.",
        "recommendedExerciseModalities": ["statutory_clause_drafting", "summary_writing"]
      },
      {
        "lessonId": "les_c2_240_05_paleographic_seminar_debate_spoken",
        "unitId": "unit_c2_240_archaic_case_morphology_suffixes_",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 5,
        "title": "Scholarly Speaking: Leading a Graduate Seminar on Deciphering Epigraphic Inscriptions",
        "lessonType": "spoken_production",
        "primaryPurpose": "Lead an unscripted 4.5-minute advanced doctoral seminar at the National University of Mongolia, guiding graduate researchers through the syntactic and morphological decipherment of newly discovered 13th-century birch bark manuscripts (Цахирын хадны бичиг).",
        "communicativeOutcome": "Demonstrate supreme academic pedagogical authority, guiding senior scholars through the rigorous decipherment of fragmented medieval Mongolic texts.",
        "objectivesIntroduced": ["obj_c2_240_05_lead_paleographic_doctoral_seminars"],
        "objectivesPracticed": ["obj_c2_240_01_master_archaic_case_morphology"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c2_archaic_case_morphology_secret_history"],
        "grammarReviewed": ["gram_c1_academic_hedging_and_epistemic_stance"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_10_secret_history_philological_reading"],
        "communicativeFunctionsReviewed": ["comm_c1_03_academic_thesis_defense"],
        "newProductiveLemmaTarget": 4,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 1,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["үйсэн дээрх бичиг", "хадны бичээс", "эртний бичвэр", "семинар удирдах"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Conduct interactive graduate paleographic seminar directing student hypotheses, correcting grammatical misreadings, and establishing definitive readings.",
        "registerTarget": "advanced academic graduate seminar oral",
        "pragmaticTarget": "scholarly mentorship and epigraphic authority",
        "prerequisiteLessonIds": ["les_c2_240_04_comparative_grammar_treatise_writing"],
        "reviewsLessonIds": ["les_c2_239_05_secret_history_dramatic_declamation_spoken"],
        "reviewsUnitIds": ["unit_c2_239_classical_epic_syntax_in_the_secret"],
        "reviewReason": "Transforms dramatic oral recitation into interactive doctoral seminar leadership.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide benchmark audio of senior professor leading doctoral seminar on 13th-century epigraphic manuscripts.",
        "successCriteria": [
          "Guides students through ambiguous suffix decipherment using Socratic questioning in flawless academic Khalkha",
          "Provides immediate philological parallels from the Secret History and Muqaddimat al-Adab"
        ],
        "masteryEvidence": "Conducts an unscripted 4.5-minute doctoral seminar exhibiting absolute mastery of Mongolic paleography.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
      }
    ])

    # ----------------------------------------------------
    # UNIT 241: The Alan Qo'a Parable of the Five Arrows (PL=22, RL=30, PE=9, RE=7) - 5 lessons
    # ----------------------------------------------------
    lessons.extend([
      {
        "lessonId": "les_c2_241_01_alan_qoa_parable_philological_intro",
        "unitId": "unit_c2_241_the_alan_qo_a_parable_of_the_five_a",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 1,
        "title": "Philological Foundations: The Alan Qo'a Parable of the Five Arrows (§18-§22) in Middle Mongolian",
        "lessonType": "grammar_introduction",
        "primaryPurpose": "Introduce the textual, syntactic, and cultural foundations of Alan Qo'a's iconic lesson of the five arrow shafts, analyzing the medieval philosophical concepts of clan unity (*эв эе*), supernatural lineage, and gnomic dialogue.",
        "communicativeOutcome": "Deconstruct the foundational unity myth of the Mongol nation, analyzing its linguistic formulation in 13th-century Middle Mongolian and its cultural resonance across 800 years.",
        "objectivesIntroduced": ["obj_c2_241_01_master_alan_qoa_parable"],
        "objectivesPracticed": ["obj_c2_240_01_master_archaic_case_morphology"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_classical_epic_syntax_secret_history",
          "gram_c2_archaic_case_morphology_secret_history"
        ],
        "grammarReviewed": ["gram_c1_classical_quotative_khemeen"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": ["comm_c2_10_secret_history_philological_reading"],
        "communicativeFunctionsPracticed": ["comm_c2_15_creative_mastery_authorial_voice"],
        "communicativeFunctionsReviewed": ["comm_c1_07_literary_and_philosophical_hermeneutics"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["Алан гуа", "таван сумны сургаал", "эв эе", "нэгдэл", "сургаал үг"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "foundational ethical parable & Middle Mongolian prose",
        "pragmaticTarget": "clan solidarity, ancestral legitimacy, and moral instruction",
        "prerequisiteLessonIds": ["les_c2_240_05_paleographic_seminar_debate_spoken"],
        "reviewsLessonIds": ["les_c2_238_01_secret_history_philological_foundations_intro"],
        "reviewsUnitIds": ["unit_c2_238_the_secret_history_of_the_mongols_p"],
        "reviewReason": "Bridges initial Secret History philology into deep analysis of its most celebrated ethical parable.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Recites and grammatically parses the core aphorism of Alan Qo'a ('Ганц мод гал болохгүй, ганц сум хугарах...') in Middle Mongolian",
          "Explains the theological concept of the radiant visitor entering through the roof hole (*өрхөөр гийсэн шар хүн*)"
        ],
        "masteryEvidence": "Produces a complete philological and philosophical commentary on §18-§22.",
        "recommendedExerciseModalities": ["stylistic_transformation", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_241_02_alan_qoa_parable_interlinear_reading",
        "unitId": "unit_c2_241_the_alan_qo_a_parable_of_the_five_a",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 2,
        "title": "Textual Reading: Interlinear Decipherment of the Five Sons' Dialogue & Alan Qo'a's Oath",
        "lessonType": "reading",
        "primaryPurpose": "Parse an 860-word critical edition text featuring parallel columns: Middle Mongolian reconstructed text, Ming Chinese interlinear glosses, and modern scholarly Khalkha commentary, examining the subtle moral accusations and philosophical refutation.",
        "communicativeOutcome": "Read the Alan Qo'a narrative with complete philological autonomy, navigating between original Middle Mongolian and modern scholarly translations without reliance on secondary summaries.",
        "objectivesIntroduced": ["obj_c2_241_02_parse_alan_qoa_interlinear"],
        "objectivesPracticed": ["obj_c2_241_01_master_alan_qoa_parable"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_classical_epic_syntax_secret_history",
          "gram_c2_archaic_case_morphology_secret_history"
        ],
        "grammarReviewed": ["gram_c1_classical_participle_khui"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_10_secret_history_philological_reading"],
        "communicativeFunctionsReviewed": ["comm_c1_07_literary_and_philosophical_hermeneutics"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["мөр хоорондын орчуулга", "таван хөвгүүн", "сэжиг таамаг", "ариун гарал"],
        "readingObjective": "Analyze interlinear edition of Alan Qo'a parable evaluating variant glosses and syntactic subtleties.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "multilingual philological comparative edition",
        "pragmaticTarget": "hermeneutic precision and ethical deconstruction",
        "prerequisiteLessonIds": ["les_c2_241_01_alan_qoa_parable_philological_intro"],
        "reviewsLessonIds": ["les_c2_240_02_kho_elun_wrath_strophic_reading"],
        "reviewsUnitIds": ["unit_c2_240_archaic_case_morphology_suffixes_"],
        "reviewReason": "Compares Mother Hö'elün's fierce maternal rebuke with Alan Qo'a's calm, instructive parable pedagogy.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Identifies 4 discrepancies between the Ming Chinese literal gloss and Damdinsuren's Cyrillic translation",
          "Interprets the precise sociopolitical intent behind uniting the five brothers under a sacred covenant"
        ],
        "masteryEvidence": "Produces an 860-word critical textual commentary on the interlinear edition of §18-§22.",
        "recommendedExerciseModalities": ["source_comparison", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_241_03_shamanic_and_ancestral_mythology_listening",
        "unitId": "unit_c2_241_the_alan_qo_a_parable_of_the_five_a",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 3,
        "title": "Acoustic Dissection: Ethnographic Audio on Steppe Shamanic Cosmogony & Tengrism in the Secret History",
        "lessonType": "listening",
        "primaryPurpose": "Listen to a 4.5-minute field recording of a senior ethnographer and hereditary Darkhad shaman explaining the cosmological symbolism of the radiant yellow man (*шар хүн*) and heavenly conception in Tengrist metaphysics (165 wpm).",
        "communicativeOutcome": "Process deep ethnographic oral explanations of ancient Mongolian cosmological beliefs, linking linguistic metaphors directly to living shamanic traditions.",
        "objectivesIntroduced": ["obj_c2_241_03_comprehend_shamanic_cosmology_audio"],
        "objectivesPracticed": ["obj_c2_241_01_master_alan_qoa_parable"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c2_dialectal_morphosyntax_awareness"],
        "grammarReviewed": ["gram_c2_somatic_idiomatic_metaphors"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_10_secret_history_philological_reading"],
        "communicativeFunctionsReviewed": ["comm_c1_12_reverential_and_honorific_oratory"],
        "newProductiveLemmaTarget": 4,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["Бөө мөргөл", "Тэнгэр шүтлэг", "Дархад бөө", "соёлын антропологи", "онгод тэнгэр"],
        "readingObjective": "",
        "listeningObjective": "Decipher field recordings of shamanic cosmology linking oral ritual knowledge to medieval historical chronicles.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "indigenous ethnographic field interview oral",
        "pragmaticTarget": "sacred metaphysical interpretation and heritage continuity",
        "prerequisiteLessonIds": ["les_c2_241_02_alan_qoa_parable_interlinear_reading"],
        "reviewsLessonIds": ["les_c2_240_03_archaic_phonology_reconstruction_listening"],
        "reviewsUnitIds": ["unit_c2_240_archaic_case_morphology_suffixes_"],
        "reviewReason": "Contrasts academic phonological laboratory audio with living shamanic field ethnography.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide authentic field audio of Darkhad cultural elder discussing heavenly light conception in steppe traditions.",
        "successCriteria": [
          "Explains the Tengrist metaphysical interpretation of light conception through the yurt's toono",
          "Distinguishes between folklore myth and the ideological legitimization of the Golden Clan (Алтан ураг)"
        ],
        "masteryEvidence": "Produces an ethnographic summary and conceptual synthesis of the 4.5-minute field recording.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_241_04_philosophical_essay_on_steppe_solidarity_writing",
        "unitId": "unit_c2_241_the_alan_qo_a_parable_of_the_five_a",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 4,
        "title": "Philosophical Writing: Authoring an Essay on Nomadic Social Cohesion & the Alan Qo'a Covenant",
        "lessonType": "writing",
        "primaryPurpose": "Author an 850-word philosophical essay examining how the Alan Qo'a five-arrow parable provided the ethical and constitutional bedrock for Chinggis Khaan's unification of the warring steppe confederations.",
        "communicativeOutcome": "Produce high-level philosophical and historical prose in Mongolian, connecting medieval mythic narratives to modern political philosophy and statecraft.",
        "objectivesIntroduced": ["obj_c2_241_04_author_steppe_solidarity_essays"],
        "objectivesPracticed": ["obj_c2_241_01_master_alan_qoa_parable"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_classical_epic_syntax_secret_history",
          "gram_c2_satirical_polemical_framing"
        ],
        "grammarReviewed": ["gram_c1_academic_nominalization_frames"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_10_secret_history_philological_reading"],
        "communicativeFunctionsReviewed": ["comm_c1_07_literary_and_philosophical_hermeneutics"],
        "newProductiveLemmaTarget": 4,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["нийгмийн эв нэгдэл", "төрийн үзэл санаа", "гүн ухааны эсээ", "нүүдэлчдийн ёс зүй"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Draft an 850-word philosophical essay integrating Middle Mongolian quotations into a sophisticated modern theoretical discourse.",
        "spokenProductionObjective": "",
        "registerTarget": "high political philosophy and historical jurisprudence essayistic",
        "pragmaticTarget": "timeless moral legitimacy and statecraft philosophy",
        "prerequisiteLessonIds": ["les_c2_241_03_shamanic_and_ancestral_mythology_listening"],
        "reviewsLessonIds": ["les_c2_240_04_comparative_grammar_treatise_writing"],
        "reviewsUnitIds": ["unit_c2_240_archaic_case_morphology_suffixes_"],
        "reviewReason": "Elevates linguistic declension analysis into grand political philosophy of nomadic unity.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Synthesizes nomadic kinship theory with modern political theories of social contract (e.g., Ibn Khaldun's *asabiyyah*)",
          "Deploys 4 master-level Classical Mongolian rhetorical transitions with impeccable elegance"
        ],
        "masteryEvidence": "Submits an 850-word philosophical essay judged worthy of publication in *Philosophy & Sociology Journal*.",
        "recommendedExerciseModalities": ["statutory_clause_drafting", "summary_writing"]
      },
      {
        "lessonId": "les_c2_241_05_national_unity_presidential_oration_spoken",
        "unitId": "unit_c2_241_the_alan_qo_a_parable_of_the_five_a",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 5,
        "title": "Oratorical Speaking: Delivering a State of the Nation Address Grounded in Alan Qo'a's Covenant",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver an unscripted 5.0-minute monumental State of the Nation address as the President of Mongolia to the State Great Khural, invoking the five-arrow covenant of Alan Qo'a to heal deep political factionalism and inspire national unity.",
        "communicativeOutcome": "Command the supreme presidential oratorical register of Mongolia, uniting ancient ancestral authority with modern constitutional statesmanship to move a divided parliament.",
        "objectivesIntroduced": ["obj_c2_241_05_deliver_presidential_unity_addresses"],
        "objectivesPracticed": ["obj_c2_241_01_master_alan_qoa_parable"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_classical_epic_syntax_secret_history",
          "gram_c2_seamless_register_navigating"
        ],
        "grammarReviewed": ["gram_c1_reverential_and_honorific_oratory"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_10_secret_history_philological_reading"],
        "communicativeFunctionsReviewed": ["comm_c1_10_rhetorical_speechwriting"],
        "newProductiveLemmaTarget": 4,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 1,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["Улсын Их Хурал", "төрийн тэргүүн", "үндэсний эв нэгдэл", "илгээлт", "өвөг дээдсийн гэрээс"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Execute a 5-minute presidential address balancing solemn ancestral recitation, constitutional urgency, and impassioned national unity.",
        "registerTarget": "presidential state of the nation parliamentary oratory oral",
        "pragmaticTarget": "healing political schism and galvanizing national purpose",
        "prerequisiteLessonIds": ["les_c2_241_04_philosophical_essay_on_steppe_solidarity_writing"],
        "reviewsLessonIds": ["les_c2_240_05_paleographic_seminar_debate_spoken"],
        "reviewsUnitIds": ["unit_c2_240_archaic_case_morphology_suffixes_"],
        "reviewReason": "Expands graduate academic seminar leadership into national parliamentary presidential oratory.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide benchmark audio of President of Mongolia delivering formal address to parliament on Constitution Day.",
        "successCriteria": [
          "Integrates verbatim Middle Mongolian citations from §22 smoothly into elevated modern political Khalkha",
          "Maintains solemn acoustic resonance, presidential pacing, and powerful emotional cadence throughout"
        ],
        "masteryEvidence": "Delivers a 5.0-minute presidential address receiving bipartisan standing ovation in parliamentary simulation.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
      }
    ])

    # ----------------------------------------------------
    # UNIT 242: Chinggis Khaan & Jamukha: The Oath of Anda (Brothers) (PL=22, RL=30, PE=9, RE=7) - 5 lessons
    # ----------------------------------------------------
    lessons.extend([
      {
        "lessonId": "les_c2_242_01_oath_of_anda_philological_intro",
        "unitId": "unit_c2_242_chinggis_khaan_jamukha_the_oath_of_",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 1,
        "title": "Philological Foundations: The Nomadic Institution of Anda (Sworn Brotherhood) in Medieval Law",
        "lessonType": "grammar_introduction",
        "primaryPurpose": "Introduce the sociopolitical institution, ceremonial vows, and gift exchanges of *анда бололцох* (sworn brotherhood) in 12th-13th century Mongolia, examining the linguistic formulas exchanged between Temüjin and Jamukha across their three oaths (§116, §117).",
        "communicativeOutcome": "Deconstruct the sacred institution of sworn brotherhood in steppe culture, analyzing its legal obligations, ritual terminology, and tragic vulnerabilities.",
        "objectivesIntroduced": ["obj_c2_242_01_master_anda_sworn_brotherhood"],
        "objectivesPracticed": ["obj_c2_241_01_master_alan_qoa_parable"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_classical_epic_syntax_secret_history",
          "gram_c2_archaic_case_morphology_secret_history"
        ],
        "grammarReviewed": ["gram_c1_honorific_lexical_verbs"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": ["comm_c2_10_secret_history_philological_reading"],
        "communicativeFunctionsPracticed": ["comm_c2_15_creative_mastery_authorial_voice"],
        "communicativeFunctionsReviewed": ["comm_c1_14_navigating_subtle_social_hierarchies"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["анда", "тангараг", "анд бололцох", "бэлэг солилцох", "нөхөрлөл"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "medieval nomadic customary law & ceremonial oath",
        "pragmaticTarget": "sacred interpersonal allegiance and customary contract",
        "prerequisiteLessonIds": ["les_c2_241_05_national_unity_presidential_oration_spoken"],
        "reviewsLessonIds": ["les_c2_239_01_classical_epic_syntax_intro"],
        "reviewsUnitIds": ["unit_c2_239_classical_epic_syntax_in_the_secret"],
        "reviewReason": "Connects Middle Mongolian epic syntax directly to the solemn legal vows of sworn brotherhood.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Explains the legal and spiritual distinction between blood kinship (*ясан төрөл*) and sworn brotherhood (*анда*)",
          "Parses 4 archaic oath formulas detailing shared quilts, shared sashes, and mutual defense obligations"
        ],
        "masteryEvidence": "Produces an exhaustive philological and legal analysis of the three Anda ceremonies in the Secret History.",
        "recommendedExerciseModalities": ["stylistic_transformation", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_242_02_jamukha_final_dialogue_reading",
        "unitId": "unit_c2_242_chinggis_khaan_jamukha_the_oath_of_",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 2,
        "title": "Textual Reading: The Final Dialogue of Chinggis Khaan & Jamukha Before Execution (§200-§201)",
        "lessonType": "reading",
        "primaryPurpose": "Parse an 890-word critical edition text of the final philosophical dialogue between Chinggis Khaan and the captured Jamukha (§200-§201), analyzing Jamukha's poetic self-condemnation, his refusal of pardon ('Хоёр нар нэг тэнгэрт үл багтах'), and his request for death without shedding blood.",
        "communicativeOutcome": "Interpret the most psychologically profound and tragic dialogue in Mongolian literature, analyzing the clash between personal brotherhood and sovereign imperial destiny.",
        "objectivesIntroduced": ["obj_c2_242_02_parse_jamukha_final_dialogue"],
        "objectivesPracticed": ["obj_c2_242_01_master_anda_sworn_brotherhood"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_classical_epic_syntax_secret_history",
          "gram_c2_somatic_idiomatic_metaphors"
        ],
        "grammarReviewed": ["gram_c1_classical_participle_khui"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_10_secret_history_philological_reading"],
        "communicativeFunctionsReviewed": ["comm_c1_07_literary_and_philosophical_hermeneutics"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["Жамуха", "цус гаргахгүй алах", "эцсийн үг", "эмгэнэлт хувь заяа", "хаан суудал"],
        "readingObjective": "Analyze Jamukha's final farewell dialogue deconstructing tragic dignity, steppe metaphors of sovereignty, and honorable death.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "13th-century high tragic philosophical dialogue",
        "pragmaticTarget": "tragic aristocratic honor and unyielding destiny",
        "prerequisiteLessonIds": ["les_c2_242_01_oath_of_anda_philological_intro"],
        "reviewsLessonIds": ["les_c2_241_02_alan_qoa_parable_interlinear_reading"],
        "reviewsUnitIds": ["unit_c2_241_the_alan_qo_a_parable_of_the_five_a"],
        "reviewReason": "Contrasts the harmony of the five arrows with the heartbreaking, tragic fracture of sworn brotherhood.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Interprets Jamukha's famous metaphor of being an ill-fitting collar (*дээлэнд зах болоогүй*) in its feudal context",
          "Explains why dying without blood shedding (*цус гаргахгүй үхэх*) preserved the soul in Tengrist metaphysics"
        ],
        "masteryEvidence": "Produces an 890-word literary and psychological commentary on §200-§201.",
        "recommendedExerciseModalities": ["source_comparison", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_242_03_theatrical_jamukha_duel_listening",
        "unitId": "unit_c2_242_chinggis_khaan_jamukha_the_oath_of_",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 3,
        "title": "Acoustic Dissection: Dramatic Theatrical Staging of Jamukha's Death Speech at State Academic Theater",
        "lessonType": "listening",
        "primaryPurpose": "Listen to a 4.5-minute acclaimed stage recording of Mongolia's foremost actors performing Jamukha's final dialogue at the State Academic Drama Theatre (165 wpm), analyzing voice modulation between imperial sorrow and tragic defiance.",
        "communicativeOutcome": "Process theatrical Middle Mongolian dramatic delivery at the highest artistic tier, discerning subtle psychological undertones between sworn brothers.",
        "objectivesIntroduced": ["obj_c2_242_03_comprehend_jamukha_theatrical_staging"],
        "objectivesPracticed": ["obj_c2_242_01_master_anda_sworn_brotherhood"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_classical_epic_syntax_secret_history",
          "gram_c2_literary_polyphony_and_indirect_interior_monologue"
        ],
        "grammarReviewed": ["gram_c1_reverential_and_honorific_oratory"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_10_secret_history_philological_reading"],
        "communicativeFunctionsReviewed": ["comm_c1_12_reverential_and_honorific_oratory"],
        "newProductiveLemmaTarget": 4,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["жүжгийн тайз", "сонгодог жүжигчин", "дуу хоолойн хувирал", "харуусал", "үнэнч анда"],
        "readingObjective": "",
        "listeningObjective": "Decipher high-art dramatic staging of historical dialogue, parsing whispered concessions, prideful rejections, and profound pathos.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "master theatrical classical tragedy oral",
        "pragmaticTarget": "cathartic tragic release and immortal steppe brotherhood",
        "prerequisiteLessonIds": ["les_c2_242_02_jamukha_final_dialogue_reading"],
        "reviewsLessonIds": ["les_c2_241_03_shamanic_and_ancestral_mythology_listening"],
        "reviewsUnitIds": ["unit_c2_241_the_alan_qo_a_parable_of_the_five_a"],
        "reviewReason": "Contrasts shamanic ethnographic listening with high dramatic theatrical performance acoustics.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide authentic theater archival recording of celebrated actors playing Chinggis Khaan and Jamukha.",
        "successCriteria": [
          "Transcribes the dialogue capturing the actors' pauses, vocal tremors, and emotional inflection points",
          "Explains how Jamukha's acoustic delivery conveys aristocratic superiority even while in iron chains"
        ],
        "masteryEvidence": "Produces an acoustic and dramatic analysis of the 4.5-minute theatrical scene.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_242_04_tragic_drama_script_authoring_writing",
        "unitId": "unit_c2_242_chinggis_khaan_jamukha_the_oath_of_",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 4,
        "title": "Dramatic Writing: Authoring a Modern Verse Play Scene on Steppe Betrayal & Brotherhood",
        "lessonType": "writing",
        "primaryPurpose": "Author an 850-word verse drama scene depicting the tragic rupture between Chinggis Khaan and Jamukha on the mountain ridge, utilizing alliterative Middle Mongolian syntax, visceral somatic metaphors, and deep existential dialogue.",
        "communicativeOutcome": "Produce high-literary theatrical drama in Mongolian that honors the historical authenticity of the Secret History while generating electrifying contemporary stage tension.",
        "objectivesIntroduced": ["obj_c2_242_04_author_verse_drama_scenes"],
        "objectivesPracticed": ["obj_c2_242_01_master_anda_sworn_brotherhood"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_classical_epic_syntax_secret_history",
          "gram_c2_somatic_idiomatic_metaphors"
        ],
        "grammarReviewed": ["gram_c1_classical_participle_khui"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_10_secret_history_philological_reading"],
        "communicativeFunctionsReviewed": ["comm_c1_07_literary_and_philosophical_hermeneutics"],
        "newProductiveLemmaTarget": 4,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["шүлэглэсэн жүжиг", "жүжгийн зохиол", "дүрийн зөрчил", "андгай", "уулын хяр"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Draft an 850-word theatrical verse scene in authentic Middle Mongolian cadence balancing heroic pride and internal agony.",
        "spokenProductionObjective": "",
        "registerTarget": "high classical poetic verse drama",
        "pragmaticTarget": "electrifying theatrical tragedy and character foil perfection",
        "prerequisiteLessonIds": ["les_c2_242_03_theatrical_jamukha_duel_listening"],
        "reviewsLessonIds": ["les_c2_241_04_philosophical_essay_on_steppe_solidarity_writing"],
        "reviewsUnitIds": ["unit_c2_241_the_alan_qo_a_parable_of_the_five_a"],
        "reviewReason": "Shifts authorial focus from political philosophy essays into gripping verse drama dialogue.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Differentiates the conflicting imperial vision of Temüjin from the aristocratic pastoral traditionalism of Jamukha",
          "Integrates authentic alliteration and medieval Mongolian swearing formulas without modern anachronism"
        ],
        "masteryEvidence": "Submits an 850-word theatrical scene worthy of staging at the National Academic Drama Theatre.",
        "recommendedExerciseModalities": ["statutory_clause_drafting", "summary_writing"]
      },
      {
        "lessonId": "les_c2_242_05_jamukha_monologue_dramatic_performance_spoken",
        "unitId": "unit_c2_242_chinggis_khaan_jamukha_the_oath_of_",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 5,
        "title": "Mastery Speaking: Performing Jamukha's Farewell Soliloquy Before a Master Acting Jury",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver an unscripted 5.0-minute dramatic performance of Jamukha's farewell monologue before an expert jury of national theatrical directors and Shakespearean actors, embodying tragic pride, aristocratic defiance, and eternal love for his Anda.",
        "communicativeOutcome": "Demonstrate the absolute pinnacle of dramatic spoken Mongolian, commanding tragic emotional depth, impeccable phonetics, and magnetic stage presence.",
        "objectivesIntroduced": ["obj_c2_242_05_perform_jamukha_farewell_monologue"],
        "objectivesPracticed": ["obj_c2_242_01_master_anda_sworn_brotherhood"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_classical_epic_syntax_secret_history",
          "gram_c2_somatic_idiomatic_metaphors"
        ],
        "grammarReviewed": ["gram_c1_reverential_and_honorific_oratory"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_10_secret_history_philological_reading"],
        "communicativeFunctionsReviewed": ["comm_c1_12_reverential_and_honorific_oratory"],
        "newProductiveLemmaTarget": 4,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 1,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["жүжигчний урлаг", "монолог", "шүүлтийн зөвлөл", "тайзны ур чадвар", "сэтгэл хөдлөл"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Execute an impassioned 5-minute dramatic soliloquy modulating between proud defiance and heartbreaking brotherly farewell.",
        "registerTarget": "high dramatic theatrical tragedy soliloquy oral",
        "pragmaticTarget": "transcendent tragic catharsis and aristocratic defiance",
        "prerequisiteLessonIds": ["les_c2_242_04_tragic_drama_script_authoring_writing"],
        "reviewsLessonIds": ["les_c2_241_05_national_unity_presidential_oration_spoken"],
        "reviewsUnitIds": ["unit_c2_241_the_alan_qo_a_parable_of_the_five_a"],
        "reviewReason": "Contrasts statesmanlike presidential address with deeply personal, agonizing tragic theatrical soliloquy.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide benchmark audio of dramatic acting audition delivering Jamukha's farewell monologue.",
        "successCriteria": [
          "Embodies Jamukha's unyielding aristocratic dignity with flawless classical diction and dramatic pauses",
          "Moves the simulated theater jury to silence through authentic emotional resonance and somatic vocalization"
        ],
        "masteryEvidence": "Delivers an unscripted 5.0-minute tragic soliloquy awarded highest distinction by the theatrical jury.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
      }
    ])

    return lessons
