# -*- coding: utf-8 -*-
"""CEFR C2 Section 03 Part 1: Gnomic Wisdom, Metric Parallelism & Heroic Epics (Units 247-251, 25 lessons)."""

def get_units_247_251():
    lessons = []

    # ----------------------------------------------------
    # UNIT 247: Gnomic Wisdom: Traditional Proverbs (Зүйр Цэцэн Үг) (PL=24, RL=36, PE=9, RE=10) - 5 lessons
    # ----------------------------------------------------
    lessons.extend([
      {
        "lessonId": "les_c2_247_01_gnomic_wisdom_proverbial_compression_intro",
        "unitId": "unit_c2_247_gnomic_wisdom_traditional_proverbs_",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 1,
        "title": "Gnomic Linguistics: Traditional Proverbs (Зүйр Цэцэн Үг) & Syntactic Compression in Steppe Rhetoric",
        "lessonType": "grammar_introduction",
        "primaryPurpose": "Introduce the syntactic compression, metrical symmetry, and pragmatic deployment of traditional Mongolian proverbs (*зүйр цэцэн үг*) in elite discourse: elliptical zero-copulas, paired antithetical clauses, and rhetorical clinching mechanisms.",
        "communicativeOutcome": "Master the art of gnomic compression in Mongolian, deploying allegorical pastoral proverbs to decisively settle debates and summarize complex moral dilemmas.",
        "objectivesIntroduced": ["obj_c2_247_01_master_gnomic_proverbial_compression"],
        "objectivesPracticed": ["obj_c2_246_01_synthesize_c2_sec02_philology"],
        "objectivesReviewed": ["obj_c2_233_01_master_somatic_steppe_metaphors"],
        "grammarIntroduced": ["gram_c2_proverbial_syntactic_compression"],
        "grammarPracticed": ["gram_c2_seamless_register_navigating"],
        "grammarReviewed": ["gram_c1_classical_quotative_khemeen"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": ["comm_c2_13_proverbial_gnomic_deployment"],
        "communicativeFunctionsPracticed": ["comm_c2_08_omni_register_agility"],
        "communicativeFunctionsReviewed": ["comm_c1_07_literary_and_philosophical_hermeneutics"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 8,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_epic_ceremonial_tengrism"],
        "previousVocabularyReused": ["зүйр цэцэн үг", "сургаал", "мэргэн үг", "хэлц", "өгүүлбэрийн хураалт"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "gnomic pastoral philosophy & traditional oratorical clincher",
        "pragmaticTarget": "unquestionable traditional wisdom and rhetorical closure",
        "prerequisiteLessonIds": ["les_c2_246_06_c2_sec02_culminating_operational_synthesis"],
        "reviewsLessonIds": ["les_c2_233_01_somatic_steppe_metaphors_intro"],
        "reviewsUnitIds": ["unit_c2_233_somatic_steppe_metaphors_liver_gall"],
        "reviewReason": "Bridges somatic organ metaphors into complete syntactically compressed proverbial aphorisms.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Explains the syntactic rule of elliptical compression in 6 traditional antithetical proverbs",
          "Clinches 3 diverse argumentative standoffs by selecting the philosophically exact traditional proverb"
        ],
        "masteryEvidence": "Produces an authoritative structural and rhetorical analysis of 10 classic Mongolian gnomic sayings.",
        "recommendedExerciseModalities": ["stylistic_transformation", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_247_02_gnomic_corpus_oyun_tulkhiur_reading",
        "unitId": "unit_c2_247_gnomic_wisdom_traditional_proverbs_",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 2,
        "title": "Textual Reading: The Key of Mind (Оюун Түлхүүр) & Chinggis Khaan's Bilig (Maxims)",
        "lessonType": "reading",
        "primaryPurpose": "Parse an 880-word critical edition text of *Оюун түлхүүр* (The Key of Mind) and recorded imperial *билиг* (maxims) of Chinggis Khaan, analyzing the strict four-line poetic balance, ethical counsel, and statecraft aphorisms.",
        "communicativeOutcome": "Deconstruct classical Mongolian gnomic literature, evaluating moral philosophy, state leadership ethics, and nomadic pedagogy.",
        "objectivesIntroduced": ["obj_c2_247_02_parse_oyun_tulkhiur_and_bilig"],
        "objectivesPracticed": ["obj_c2_247_01_master_gnomic_proverbial_compression"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_proverbial_syntactic_compression",
          "gram_c2_classical_epic_syntax_secret_history"
        ],
        "grammarReviewed": ["gram_c1_classical_participle_khui"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_13_proverbial_gnomic_deployment"],
        "communicativeFunctionsReviewed": ["comm_c1_07_literary_and_philosophical_hermeneutics"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 7,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_epic_ceremonial_tengrism"],
        "previousVocabularyReused": ["Оюун түлхүүр", "Чингисийн билиг", "сургаалын зохиол", "эрдэм ном", "төрийн ухаан"],
        "readingObjective": "Analyze classical gnomic literature deconstructing strophic parallelism, ethical injunctions, and statecraft wisdom.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "classical moral-didactic verse & imperial maxims",
        "pragmaticTarget": "sovereign moral guidance and timeless philosophical grounding",
        "prerequisiteLessonIds": ["les_c2_247_01_gnomic_wisdom_proverbial_compression_intro"],
        "reviewsLessonIds": ["les_c2_241_02_alan_qoa_parable_interlinear_reading"],
        "reviewsUnitIds": ["unit_c2_241_the_alan_qo_a_parable_of_the_five_a"],
        "reviewReason": "Deepens Alan Qo'a's family parable into the broader literary corpus of imperial maxims (*билиг*).",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Analyzes 5 distinct maxims from *Оюун түлхүүр* examining metrical balance and lexical precision",
          "Differentiates between folk proverbs (*ардын зүйр үг*) and aristocratic imperial maxims (*хаадын билиг*)"
        ],
        "masteryEvidence": "Produces an 880-word hermeneutic critique of *Оюун түлхүүр*.",
        "recommendedExerciseModalities": ["source_comparison", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_247_03_village_elders_dispute_arbitration_listening",
        "unitId": "unit_c2_247_gnomic_wisdom_traditional_proverbs_",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 3,
        "title": "Acoustic Dissection: Authentic Pasture Dispute Mediation Among Countryside Elders Using Proverb Duels",
        "lessonType": "listening",
        "primaryPurpose": "Listen to a 4.5-minute field recording of two elder herders and a local bagh governor mediating an intense winter pasture boundary conflict in Zavkhan (165 wpm), analyzing how both sides deploy rapid-fire proverbs to parry claims, save face, and establish consensus.",
        "communicativeOutcome": "Process spontaneous authentic rural mediation, decoding complex interpersonal negotiation conducted entirely through allegorical proverbs and customary references.",
        "objectivesIntroduced": ["obj_c2_247_03_comprehend_rural_proverb_duels"],
        "objectivesPracticed": ["obj_c2_247_01_master_gnomic_proverbial_compression"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_proverbial_syntactic_compression",
          "gram_c2_dialectal_morphosyntax_awareness"
        ],
        "grammarReviewed": ["gram_c1_navigating_subtle_social_hierarchies"],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phon_c2_02_western_khalkha_phonology"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_13_proverbial_gnomic_deployment"],
        "communicativeFunctionsReviewed": ["comm_c1_14_navigating_subtle_social_hierarchies"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 7,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_epic_ceremonial_tengrism"],
        "previousVocabularyReused": ["өвөлжөөний маргаан", "нутгийн настан", "үгээр цохих", "эв зүй", "хээрийн бичлэг"],
        "readingObjective": "",
        "listeningObjective": "Decipher rapid countryside field recordings tracking high-context proverb duels during tense pasture mediation.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "authentic rural elder mediation & customary dialect oral",
        "pragmaticTarget": "conflict de-escalation, mutual face preservation, and community harmony",
        "prerequisiteLessonIds": ["les_c2_247_02_gnomic_corpus_oyun_tulkhiur_reading"],
        "reviewsLessonIds": ["les_c2_236_03_western_mongolian_listening"],
        "reviewsUnitIds": ["unit_c2_236_pan_mongolian_dialectal_morphosynta"],
        "reviewReason": "Applies western dialectal listening comprehension to high-stakes customary pasture arbitration.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide authentic field recording of elder herders resolving pasture dispute through proverbial sparring.",
        "successCriteria": [
          "Identifies 6 distinct proverbs spoken under heavy western rural dialectal phonetic reduction",
          "Explains how the bagh governor uses an overarching proverb to forge final binding consensus"
        ],
        "masteryEvidence": "Produces an exhaustive communicative and socio-pragmatic breakdown of the 4.5-minute rural dispute audio.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_247_04_gnomic_philosophical_treatise_writing",
        "unitId": "unit_c2_247_gnomic_wisdom_traditional_proverbs_",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 4,
        "title": "Philosophical Writing: Authoring a Modern Wisdom Treatise (Орчин Үеийн Сургаал) in Gnomic Verse",
        "lessonType": "writing",
        "primaryPurpose": "Author an 850-word philosophical wisdom treatise (*орчин үеийн сургаал*) addressing ethical crises of the digital age (alienation, algorithmic manipulation, ecological breakdown) composed in classical gnomic couplets and alliterative aphorisms.",
        "communicativeOutcome": "Produce profound contemporary moral philosophy in Mongolian, revitalizing the classical *сургаал* genre to illuminate urgent modern civilizational dilemmas.",
        "objectivesIntroduced": ["obj_c2_247_04_author_modern_gnomic_treatises"],
        "objectivesPracticed": ["obj_c2_247_01_master_gnomic_proverbial_compression"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_proverbial_syntactic_compression",
          "gram_c2_satirical_polemical_framing"
        ],
        "grammarReviewed": ["gram_c1_academic_nominalization_frames"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_13_proverbial_gnomic_deployment"],
        "communicativeFunctionsReviewed": ["comm_c1_07_literary_and_philosophical_hermeneutics"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 7,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_epic_ceremonial_tengrism"],
        "previousVocabularyReused": ["сургаал зохиол", "дижитал эрин", "ёс зүйн доройтол", "онч мэргэн үг", "бадаг шүлэг"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Draft an 850-word modern didactic treatise in alliterative gnomic stanzas confronting technological alienation.",
        "spokenProductionObjective": "",
        "registerTarget": "high classical didactic philosophy & modern essayistic synthesis",
        "pragmaticTarget": "timeless moral warning and civilizational renewal",
        "prerequisiteLessonIds": ["les_c2_247_03_village_elders_dispute_arbitration_listening"],
        "reviewsLessonIds": ["les_c2_244_04_cross_register_polemical_essay_writing"],
        "reviewsUnitIds": ["unit_c2_244_seamless_register_navigating_steppe"],
        "reviewReason": "Transforms multi-register polemical essay writing into pure classical didactic gnomic verse.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Crafts at least 12 original aphorisms exhibiting flawless metric symmetry and zero grammatical redundancy",
          "Maintains the elevated solemn tone of historical masters (Nagarjuna, Chinggis Khaan, Danzanravjaa)"
        ],
        "masteryEvidence": "Submits an 850-word philosophical treatise lauded for poetic brilliance and ethical depth.",
        "recommendedExerciseModalities": ["statutory_clause_drafting", "summary_writing"]
      },
      {
        "lessonId": "les_c2_247_05_parliamentary_proverbial_clinching_spoken",
        "unitId": "unit_c2_247_gnomic_wisdom_traditional_proverbs_",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 5,
        "title": "Oratorical Speaking: Clinching a High-Stakes Parliamentary Budget Deadlock with Gnomic Wit",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver an unscripted 5.0-minute parliamentary floor speech during a deadlocked midnight national budget session, utilizing three devastatingly apt traditional pastoral proverbs to dismantle populist extravagance and broker immediate bipartisan passage.",
        "communicativeOutcome": "Demonstrate the supreme rhetorical impact of gnomic wisdom in modern governance, commanding the parliamentary chamber through traditional wit and moral authority.",
        "objectivesIntroduced": ["obj_c2_247_05_clinch_parliamentary_debates_gnomically"],
        "objectivesPracticed": ["obj_c2_247_01_master_gnomic_proverbial_compression"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_proverbial_syntactic_compression",
          "gram_c2_seamless_register_navigating"
        ],
        "grammarReviewed": ["gram_c1_reverential_and_honorific_oratory"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_13_proverbial_gnomic_deployment"],
        "communicativeFunctionsReviewed": ["comm_c1_10_rhetorical_speechwriting"],
        "newProductiveLemmaTarget": 4,
        "newReceptiveLemmaTarget": 7,
        "newProductiveExpressionTarget": 1,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_epic_ceremonial_tengrism"],
        "previousVocabularyReused": ["төсвийн хууль", "чуулганы танхим", "хэлэлцүүлэг", "онч мэргэн үгээр буулгах", "эвлэрэл"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Execute a 5-minute parliamentary speech deploying proverbs with pinpoint timing to break parliamentary deadlock.",
        "registerTarget": "high parliamentary floor debate & master rhetorical clincher oral",
        "pragmaticTarget": "shattering political posturing and decisive consensus building",
        "prerequisiteLessonIds": ["les_c2_247_04_gnomic_philosophical_treatise_writing"],
        "reviewsLessonIds": ["les_c2_244_05_omni_register_live_chameleon_spoken"],
        "reviewsUnitIds": ["unit_c2_244_seamless_register_navigating_steppe"],
        "reviewReason": "Channels omni-register chameleon agility into targeted parliamentary oratorical mastery.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide benchmark audio of senior statesman resolving parliamentary crisis with devastating proverbial wit.",
        "successCriteria": [
          "Deploys 3 traditional proverbs that elicit instant bipartisan laughter and agreement across opposing party aisles",
          "Balances razor-sharp financial critique with unassailable cultural dignity and pastoral common sense"
        ],
        "masteryEvidence": "Delivers a 5.0-minute parliamentary address resulting in unanimous budget passage in simulation.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
      }
    ])

    # ----------------------------------------------------
    # UNIT 248: Poetic Parallelism & Head Alliteration (Толгой Холбох Ёс) (PL=24, RL=31, PE=9, RE=7) - 5 lessons
    # ----------------------------------------------------
    lessons.extend([
      {
        "lessonId": "les_c2_248_01_poetic_parallelism_head_alliteration_intro",
        "unitId": "unit_c2_248_poetic_parallelism_head_alliteratio",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 1,
        "title": "Versification: Poetic Parallelism, Metric Feet & The Law of Head Alliteration (Толгой Холбох Ёс)",
        "lessonType": "grammar_introduction",
        "primaryPurpose": "Introduce the formal rules of Mongolian classical versification: four-line strophic architecture, strict initial head alliteration (*толгой холбох ёс*), internal vowel harmony echoes, syllabic metric symmetry (7-8 or 10-11 syllables), and caesura placement.",
        "communicativeOutcome": "Master the metric and alliterative principles of Mongolian poetry, composing and analyzing traditional four-line strophes with total acoustic and syntactic precision.",
        "objectivesIntroduced": ["obj_c2_248_01_master_head_alliteration_versification"],
        "objectivesPracticed": ["obj_c2_247_01_master_gnomic_proverbial_compression"],
        "objectivesReviewed": [],
        "grammarIntroduced": ["gram_c2_rhetorical_parallelism_alliteration"],
        "grammarPracticed": ["gram_c2_proverbial_syntactic_compression"],
        "grammarReviewed": ["gram_c1_rhetorical_parallelism_and_strophic_balance"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": ["comm_c2_09_metric_alliterative_poetry"],
        "communicativeFunctionsPracticed": ["comm_c2_15_creative_mastery_authorial_voice"],
        "communicativeFunctionsReviewed": ["comm_c1_10_rhetorical_speechwriting"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 7,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_epic_ceremonial_tengrism"],
        "previousVocabularyReused": ["толгой холбох ёс", "шүлгийн хэмжээ", "үеийн тоо", "хэмнэл", "бадаг холбоц"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "classical Mongolian poetic versification theory",
        "pragmaticTarget": "acoustic symmetry, mnemonic immortality, and aesthetic perfection",
        "prerequisiteLessonIds": ["les_c2_247_05_parliamentary_proverbial_clinching_spoken"],
        "reviewsLessonIds": ["les_c1_225_01_rhetorical_parallelism_and_strophic_balance_intro"],
        "reviewsUnitIds": ["unit_c1_225_rhetorical_parallelism_and_stroph"],
        "reviewReason": "Expands C1 rhetorical parallelism into exhaustive C2 metric versification and head alliteration rules.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Diagrams the metric and alliterative scheme of 4 classic stanzas from D. Natsagdorj and B. Yavuukhulan",
          "Identifies and corrects metric flaws (syllabic excess, alliterative mismatch) in 5 corrupted poetic lines"
        ],
        "masteryEvidence": "Composes and analyzes 6 four-line strophes strictly conforming to classical alliteration laws.",
        "recommendedExerciseModalities": ["stylistic_transformation", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_248_02_natsagdorj_my_native_land_reading",
        "unitId": "unit_c2_248_poetic_parallelism_head_alliteratio",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 2,
        "title": "Textual Reading: D. Natsagdorj's 'My Native Land' (Миний Нутаг, 1933) — The Apex of Steppe Parallelism",
        "lessonType": "reading",
        "primaryPurpose": "Parse an 870-word critical edition text of Dashdorjiin Natsagdorj's monumental poem *Миний нутаг* (My Native Land, 1933), analyzing its panoramic geographic progression, strict four-line head alliteration across all 32 stanzas, and rhythmic strophic momentum.",
        "communicativeOutcome": "Deconstruct the foundational masterpiece of modern Mongolian poetry, evaluating its seamless marriage of 13th-century alliterative tradition with 20th-century national consciousness.",
        "objectivesIntroduced": ["obj_c2_248_02_parse_natsagdorj_mini_nutag"],
        "objectivesPracticed": ["obj_c2_248_01_master_head_alliteration_versification"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_rhetorical_parallelism_alliteration",
          "gram_c2_proverbial_syntactic_compression"
        ],
        "grammarReviewed": ["gram_c1_classical_participle_khui"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_09_metric_alliterative_poetry"],
        "communicativeFunctionsReviewed": ["comm_c1_07_literary_and_philosophical_hermeneutics"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c2_epic_ceremonial_tengrism"],
        "previousVocabularyReused": ["Миний нутаг", "Д.Нацагдорж", "Хэнтий хангай", "уудам тал", "шүлгийн цомог"],
        "readingObjective": "Analyze *Миний нутаг* deconstructing geographic catalogs, metric foot regularities, and alliterative consonantal patterns.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "monumental national lyric poetry & patriotic hymn",
        "pragmaticTarget": "sacred territorial attachment, geographical grandeur, and poetic immortality",
        "prerequisiteLessonIds": ["les_c2_248_01_poetic_parallelism_head_alliteration_intro"],
        "reviewsLessonIds": ["les_c2_247_02_gnomic_corpus_oyun_tulkhiur_reading"],
        "reviewsUnitIds": ["unit_c2_247_gnomic_wisdom_traditional_proverbs_"],
        "reviewReason": "Transitions from didactic moral maxims into ecstatic national lyric poetry.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Scans 8 stanzas demonstrating exact syllabic count (10-11 syllables) and initial consonant pairings",
          "Explains how the poem progresses symmetrically from northern taiga to southern Gobi dunes"
        ],
        "masteryEvidence": "Produces an 870-word metrical and hermeneutic analysis of *Миний нутаг*.",
        "recommendedExerciseModalities": ["source_comparison", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_248_03_masters_of_recitation_choinom_listening",
        "unitId": "unit_c2_248_poetic_parallelism_head_alliteratio",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 3,
        "title": "Acoustic Dissection: Archival Audio of R. Choinom Reciting Underground Dissident Verse in Solitude",
        "lessonType": "listening",
        "primaryPurpose": "Listen to a 4.5-minute clandestine archival audio recording of celebrated dissident poet Renchinii Choinom reciting his unreleased poems in an underground yurt (160 wpm), analyzing his rhythmic breath pauses, biting irony, and metrical head alliteration.",
        "communicativeOutcome": "Process raw, unedited historical literary audio in Mongolian, analyzing how metric poetry conveyed political resistance, tragic isolation, and transcendent poetic power.",
        "objectivesIntroduced": ["obj_c2_248_03_comprehend_choinom_dissident_audio"],
        "objectivesPracticed": ["obj_c2_248_01_master_head_alliteration_versification"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_rhetorical_parallelism_alliteration",
          "gram_c2_pragmatic_irony_and_subtle_sarcasm"
        ],
        "grammarReviewed": ["gram_c1_reverential_and_honorific_oratory"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_09_metric_alliterative_poetry"],
        "communicativeFunctionsReviewed": ["comm_c1_12_reverential_and_honorific_oratory"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_epic_ceremonial_tengrism"],
        "previousVocabularyReused": ["Р.Чойном", "нууц дуу хураагуур", "тэрслүү яруу найрагч", "зүрхний үг", "шүлэг унших"],
        "readingObjective": "",
        "listeningObjective": "Decipher raw archival tape recordings of dissident poetry, analyzing acoustic breath rhythm, vocal tremors, and biting satirical alliteration.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "underground dissident lyric declamation oral",
        "pragmaticTarget": "spiritual resistance, tragic defiance, and immortal artistic truth",
        "prerequisiteLessonIds": ["les_c2_248_02_natsagdorj_my_native_land_reading"],
        "reviewsLessonIds": ["les_c2_247_03_village_elders_dispute_arbitration_listening"],
        "reviewsUnitIds": ["unit_c2_247_gnomic_wisdom_traditional_proverbs_"],
        "reviewReason": "Contrasts communal elder dispute mediation with private, tragic dissident artistic recitation.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide authentic underground audio recording of poet R. Choinom reciting his banned poems.",
        "successCriteria": [
          "Transcribes the recited verse capturing Choinom's rhythmic stresses and vocal emphasis points",
          "Analyzes how Choinom wields head alliteration to sharpen satirical barbs against totalitarian hypocrisy"
        ],
        "masteryEvidence": "Produces an acoustic and poetic transcription of the 4.5-minute Choinom archival recording.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_248_04_original_alliterative_cycle_composition_writing",
        "unitId": "unit_c2_248_poetic_parallelism_head_alliteratio",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 4,
        "title": "Creative Poetic Writing: Composing an Original Alliterative Cycle of 10 Stanzas on Steppe Twilight",
        "lessonType": "writing",
        "primaryPurpose": "Author an original poetic cycle of 10 four-line stanzas (850 words) depicting dusk descending over the steppe, strictly adhering to initial head alliteration, consistent 8-syllable meter, rich somatic metaphors, and poignant evocative imagery.",
        "communicativeOutcome": "Demonstrate authentic master-level poetic authorship in Mongolian, creating a lyric work evaluated as worthy of publication in *Uran Zokhiol Biyelech*.",
        "objectivesIntroduced": ["obj_c2_248_04_compose_original_alliterative_cycle"],
        "objectivesPracticed": ["obj_c2_248_01_master_head_alliteration_versification"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_rhetorical_parallelism_alliteration",
          "gram_c2_somatic_idiomatic_metaphors"
        ],
        "grammarReviewed": ["gram_c1_classical_participle_khui"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_09_metric_alliterative_poetry"],
        "communicativeFunctionsReviewed": ["comm_c1_15_creative_writing_fiction_and_literary_nonfiction"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c2_epic_ceremonial_tengrism"],
        "previousVocabularyReused": ["яруу найраг туурвих", "үдшийн бүрий", "бадаг холбох", "уран дүрслэл", "найргийн мөр"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Draft a 10-stanza lyrical poem strictly maintaining four-line head alliteration and symmetrical syllable count.",
        "spokenProductionObjective": "",
        "registerTarget": "high lyric poetry & classical alliterative verse",
        "pragmaticTarget": "aesthetic beauty, emotional resonance, and metric virtuosity",
        "prerequisiteLessonIds": ["les_c2_248_03_masters_of_recitation_choinom_listening"],
        "reviewsLessonIds": ["les_c2_247_04_gnomic_philosophical_treatise_writing"],
        "reviewsUnitIds": ["unit_c2_247_gnomic_wisdom_traditional_proverbs_"],
        "reviewReason": "Expands gnomic wisdom verse into pure, evocative pastoral lyric poetry.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Zero alliterative breaches across all 40 lines of the 10-stanza cycle",
          "Weaves visceral sensory imagery (smell of wormwood, cooling stirrups, distant horse neighs) into every strophe"
        ],
        "masteryEvidence": "Submits a pristine 10-stanza poetic cycle evaluated at national literary prize winner standard.",
        "recommendedExerciseModalities": ["statutory_clause_drafting", "summary_writing"]
      },
      {
        "lessonId": "les_c2_248_05_bolor_tsom_poetry_festival_performance_spoken",
        "unitId": "unit_c2_248_poetic_parallelism_head_alliteratio",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 5,
        "title": "Mastery Speaking: Performing at the Bolor Tsom (Crystal Cup) National Poetry Festival",
        "lessonType": "spoken_production",
        "primaryPurpose": "Perform an unscripted 5.0-minute recitation of original alliterative verse before an audience of 3,000 poetry lovers and television cameras at the *Болор цом* (Crystal Cup) National Poetry Festival, executing dramatic pauses, melodic pitch inflections, and electric emotional connection.",
        "communicativeOutcome": "Command the grand stage of Mongolian public poetry performance, captivating the national audience with acoustic eloquence, metric cadence, and magnetic stage presence.",
        "objectivesIntroduced": ["obj_c2_248_05_perform_bolor_tsom_poetry"],
        "objectivesPracticed": ["obj_c2_248_01_master_head_alliteration_versification"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_rhetorical_parallelism_alliteration",
          "gram_c2_seamless_register_navigating"
        ],
        "grammarReviewed": ["gram_c1_reverential_and_honorific_oratory"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_09_metric_alliterative_poetry"],
        "communicativeFunctionsReviewed": ["comm_c1_12_reverential_and_honorific_oratory"],
        "newProductiveLemmaTarget": 4,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 1,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c2_epic_ceremonial_tengrism"],
        "previousVocabularyReused": ["Болор цом", "яруу найргийн наадам", "тайзны соёл", "дууны өнгө", "үзэгчдийн алга ташилт"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Recite 24 lines of original verse from memory with electrifying acoustic resonance, metric precision, and stage authority.",
        "registerTarget": "national festival poetic recitation & public performance oral",
        "pragmaticTarget": "mass aesthetic raptures, poetic triumph, and winning the Crystal Cup",
        "prerequisiteLessonIds": ["les_c2_248_04_original_alliterative_cycle_composition_writing"],
        "reviewsLessonIds": ["les_c2_247_05_parliamentary_proverbial_clinching_spoken"],
        "reviewsUnitIds": ["unit_c2_247_gnomic_wisdom_traditional_proverbs_"],
        "reviewReason": "Transitions from parliamentary political debate to grand cultural poetry stage recitation.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide benchmark audio of Crystal Cup winning poet reciting final round masterpiece.",
        "successCriteria": [
          "Maintains pristine metric cadence without faltering or missing alliterative stresses under simulated spotlight pressure",
          "Evokes intense emotional response and applause from the audience through vocal dynamics and sincere delivery"
        ],
        "masteryEvidence": "Delivers an unforgettable 5.0-minute performance crowned as the Bolor Tsom laureate in festival simulation.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
      }
    ])

    # ----------------------------------------------------
    # UNIT 249: Syntactic Parallelism in Epic Strophic Verse (PL=24, RL=31, PE=9, RE=7) - 5 lessons
    # ----------------------------------------------------
    lessons.extend([
      {
        "lessonId": "les_c2_249_01_syntactic_parallelism_strophic_syntax_intro",
        "unitId": "unit_c2_249_syntactic_parallelism_in_epic_strop",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 1,
        "title": "Morphosyntax: Deep Syntactic Parallelism, Morphological Rhymes & Strophic Symmetry in Epic Verse",
        "lessonType": "grammar_introduction",
        "primaryPurpose": "Introduce deep structural parallelism in Mongolian epic poetry: morphological grammatical rhyming (matching verbal aspectual suffixes *-на/-нэ*, *-в/-б*, converbs *-ж/-ч* across strophic lines), symmetrical noun phrase balancing, and syntactic mirror structures.",
        "communicativeOutcome": "Parse and compose multi-tiered symmetrical strophic verse in Mongolian, harmonizing head alliteration with end-of-line morphological rhyming and balanced clause structures.",
        "objectivesIntroduced": ["obj_c2_249_01_master_epic_syntactic_parallelism"],
        "objectivesPracticed": ["obj_c2_248_01_master_head_alliteration_versification"],
        "objectivesReviewed": [],
        "grammarIntroduced": ["gram_c2_syntactic_parallelism_in_verse"],
        "grammarPracticed": ["gram_c2_rhetorical_parallelism_alliteration"],
        "grammarReviewed": ["gram_c1_classical_converbs_vaas_khuits"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": ["comm_c2_09_metric_alliterative_poetry"],
        "communicativeFunctionsPracticed": ["comm_c2_15_creative_mastery_authorial_voice"],
        "communicativeFunctionsReviewed": ["comm_c1_10_rhetorical_speechwriting"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 7,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_epic_ceremonial_tengrism"],
        "previousVocabularyReused": ["өгүүлбэр зүйн зэрэгцэл", "төгсгөлийн холбоц", "хэлбэр зүйн ижилсэл", "тэгш хэм", "туулийн бадаг"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "epic morphosyntactic parallelism & strophic versification",
        "pragmaticTarget": "monumental acoustic symmetry and structural grandeur",
        "prerequisiteLessonIds": ["les_c2_248_05_bolor_tsom_poetry_festival_performance_spoken"],
        "reviewsLessonIds": ["les_c2_248_01_poetic_parallelism_head_alliteration_intro"],
        "reviewsUnitIds": ["unit_c2_248_poetic_parallelism_head_alliteratio"],
        "reviewReason": "Builds upon initial head alliteration by adding complex end-of-line morphological rhyming and clause symmetry.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Diagrams the dual head-alliteration and tail-morphological rhyme structure in 4 epic stanzas",
          "Transforms 3 asymmetric prose paragraphs into perfectly balanced parallel strophes"
        ],
        "masteryEvidence": "Produces an exhaustive morphosyntactic analysis of 8 complex epic strophes.",
        "recommendedExerciseModalities": ["stylistic_transformation", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_249_02_steppe_ballad_khukh_toli_reading",
        "unitId": "unit_c2_249_syntactic_parallelism_in_epic_strop",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 2,
        "title": "Textual Reading: Injannashi's 'The Blue Chronicle' (Хөх Судар, 1871) — High Classical Verse Chapters",
        "lessonType": "reading",
        "primaryPurpose": "Parse an 870-word critical text of the poetic prefaces and strophic verse interludes in Injannashi's masterpiece *Хөх судар* (The Blue Chronicle, 1871), analyzing how 19th-century classical verse integrated Chinese metric parallelism with indigenous Mongolian alliterative traditions.",
        "communicativeOutcome": "Deconstruct the pinnacle of 19th-century aristocratic Mongolian historical fiction, analyzing its refined poetic interludes and philosophical dualism.",
        "objectivesIntroduced": ["obj_c2_249_02_parse_injannashi_khokh_sudar"],
        "objectivesPracticed": ["obj_c2_249_01_master_epic_syntactic_parallelism"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_syntactic_parallelism_in_verse",
          "gram_c2_rhetorical_parallelism_alliteration"
        ],
        "grammarReviewed": ["gram_c1_classical_participle_khui"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_09_metric_alliterative_poetry"],
        "communicativeFunctionsReviewed": ["comm_c1_07_literary_and_philosophical_hermeneutics"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c2_epic_ceremonial_tengrism"],
        "previousVocabularyReused": ["Хөх судар", "Инжаннаши", "сонгодог роман", "шүлэглэсэн оршил", "түүхэн зохиол"],
        "readingObjective": "Analyze Injannashi's poetic interludes evaluating synthesized Sinitic-Mongolic parallel couplets and aristocratic historiography.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "19th-century classical aristocratic historical prose & verse",
        "pragmaticTarget": "cultural renaissance, dynastic nostalgia, and refined philosophical dualism",
        "prerequisiteLessonIds": ["les_c2_249_01_syntactic_parallelism_strophic_syntax_intro"],
        "reviewsLessonIds": ["les_c2_248_02_natsagdorj_my_native_land_reading"],
        "reviewsUnitIds": ["unit_c2_248_poetic_parallelism_head_alliteratio"],
        "reviewReason": "Contrasts 20th-century national lyric verse with 19th-century classical aristocratic historical verse.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Identifies the balanced antithetical parallelism between nature and human sorrow in Injannashi's stanzas",
          "Explains the fusion of Classical Mongolian chancellery syntax with Buddhist philosophical metaphors"
        ],
        "masteryEvidence": "Produces an 870-word philological and hermeneutic analysis of Injannashi's verse interludes.",
        "recommendedExerciseModalities": ["source_comparison", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_249_03_morin_khuur_and_urtiin_duu_interplay_listening",
        "unitId": "unit_c2_249_syntactic_parallelism_in_epic_strop",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 3,
        "title": "Acoustic Dissection: The Metric Synergy Between Morin Khuur Rubato & Long Song (Уртын Дуу) Melisma",
        "lessonType": "listening",
        "primaryPurpose": "Listen to a 4.5-minute master recording of a State Honored Long Song Singer and horsehead fiddle (*морин хуур*) virtuoso performing 'Ertnii Saikhan' (Ancient Splendor, 155 wpm), analyzing how elongated vowel melismas (*шуранхай*, *нугалаа*) map onto syntactic poetic parallelisms.",
        "communicativeOutcome": "Process the highest traditional vocal and instrumental art form of Mongolia, understanding how musical cadence and poetic syntax interpenetrate in authentic performance.",
        "objectivesIntroduced": ["obj_c2_249_03_comprehend_long_song_poetic_synergy"],
        "objectivesPracticed": ["obj_c2_249_01_master_epic_syntactic_parallelism"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c2_syntactic_parallelism_in_verse"],
        "grammarReviewed": ["gram_c1_reverential_and_honorific_oratory"],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phon_c2_06_traditional_vocal_melisma_phonetics"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_09_metric_alliterative_poetry"],
        "communicativeFunctionsReviewed": ["comm_c1_12_reverential_and_honorific_oratory"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_epic_ceremonial_tengrism"],
        "previousVocabularyReused": ["Уртын дуу", "морин хуур", "шуранхай", "нугалаа", "Эртний сайхан"],
        "readingObjective": "",
        "listeningObjective": "Decipher traditional long song recordings identifying poetic verse lines sustained across complex extended vocal melismas.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "traditional long song & liturgical steppe musicology oral",
        "pragmaticTarget": "timeless steppe serenity, cosmic grandeur, and ancestral memory",
        "prerequisiteLessonIds": ["les_c2_249_02_steppe_ballad_khukh_toli_reading"],
        "reviewsLessonIds": ["les_c2_248_03_masters_of_recitation_choinom_listening"],
        "reviewsUnitIds": ["unit_c2_248_poetic_parallelism_head_alliteratio"],
        "reviewReason": "Contrasts spoken dissident recitation with sublime traditional musical and vocal melisma.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide authentic recording of People's Artist performing 'Ertnii Saikhan' with Morin Khuur.",
        "successCriteria": [
          "Transcribes the poetic verse hidden within 16-second continuous vocal melismas with complete lexical accuracy",
          "Explains how the horsehead fiddle's accompanying drone underscores syntactic caesuras in the strophe"
        ],
        "masteryEvidence": "Produces an ethnomusicological and syntactic transcription of the 4.5-minute long song performance.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_249_04_epic_parallel_ballad_authoring_writing",
        "unitId": "unit_c2_249_syntactic_parallelism_in_epic_strop",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 4,
        "title": "Creative Poetic Writing: Composing an Epic Ballad on the Flight of the Wild Argali",
        "lessonType": "writing",
        "primaryPurpose": "Author an 850-word epic narrative ballad depicting a herd of wild argali sheep outrunning wolves through the Altai peaks, utilizing strict four-line syntactic parallelism, dual head and tail rhymes, and vivid dynamic pastoral verbs.",
        "communicativeOutcome": "Produce master-tier narrative epic poetry in Mongolian, demonstrating effortless command of multi-tiered syntactic symmetry and kinetic steppe imagery.",
        "objectivesIntroduced": ["obj_c2_249_04_compose_epic_parallel_ballads"],
        "objectivesPracticed": ["obj_c2_249_01_master_epic_syntactic_parallelism"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_syntactic_parallelism_in_verse",
          "gram_c2_rhetorical_parallelism_alliteration"
        ],
        "grammarReviewed": ["gram_c1_classical_participle_khui"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_09_metric_alliterative_poetry"],
        "communicativeFunctionsReviewed": ["comm_c1_15_creative_writing_fiction_and_literary_nonfiction"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c2_epic_ceremonial_tengrism"],
        "previousVocabularyReused": ["аргаль янгир", "Алтайн уулс", "туульсын найруулга", "хөөцөлдөөн", "сүрлэг хайрхан"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Draft an 850-word epic narrative poem maintaining strict syntactic and morphological parallelism throughout.",
        "spokenProductionObjective": "",
        "registerTarget": "high classical narrative epic poetry",
        "pragmaticTarget": "kinetic narrative thrill, wildlife majesty, and formal poetic balance",
        "prerequisiteLessonIds": ["les_c2_249_03_morin_khuur_and_urtiin_duu_interplay_listening"],
        "reviewsLessonIds": ["les_c2_248_04_original_alliterative_cycle_composition_writing"],
        "reviewsUnitIds": ["unit_c2_248_poetic_parallelism_head_alliteratio"],
        "reviewReason": "Expands static twilight lyric poetry into an action-packed, kinetic wildlife epic ballad.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Maintains unbroken syntactic parallel pairing between predator and prey across all narrative stanzas",
          "Integrates at least 16 authentic pastoral verbs describing movement across cliff faces and rocky scree"
        ],
        "masteryEvidence": "Submits an 850-word epic ballad celebrated for breathtaking rhythm and formal perfection.",
        "recommendedExerciseModalities": ["statutory_clause_drafting", "summary_writing"]
      },
      {
        "lessonId": "les_c2_249_05_rhapsodic_ballad_bardic_recitation_spoken",
        "unitId": "unit_c2_249_syntactic_parallelism_in_epic_strop",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 5,
        "title": "Mastery Speaking: Performing a Bardic Rhapsody with Traditional Throat-Singing Accompaniment",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver an unscripted 5.0-minute bardic oral recitation of the composed argali epic ballad accompanied by traditional overtone throat-singing (*хөөмий*) drones, synchronizing poetic meter with throat harmonics before an assembly of master folklorists.",
        "communicativeOutcome": "Command the ancient oral bardic tradition of Mongolian epic storytelling, fusing verbal metric precision with acoustic steppe harmonics to mesmerize an audience.",
        "objectivesIntroduced": ["obj_c2_249_05_perform_bardic_rhapsodies"],
        "objectivesPracticed": ["obj_c2_249_01_master_epic_syntactic_parallelism"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_syntactic_parallelism_in_verse",
          "gram_c2_seamless_register_navigating"
        ],
        "grammarReviewed": ["gram_c1_reverential_and_honorific_oratory"],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phon_c2_06_traditional_vocal_melisma_phonetics"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_09_metric_alliterative_poetry"],
        "communicativeFunctionsReviewed": ["comm_c1_12_reverential_and_honorific_oratory"],
        "newProductiveLemmaTarget": 4,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 1,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c2_epic_ceremonial_tengrism"],
        "previousVocabularyReused": ["хөөмий", "туульч", "аман зохиол", "өв уламжлал", "баатарлаг тууль"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Recite an original epic ballad from memory synchronizing verbal strophic meter with authentic throat harmonics.",
        "registerTarget": "epic bardic rhapsodic performance oral",
        "pragmaticTarget": "mythic transport, ancestral communion, and vocal mastery",
        "prerequisiteLessonIds": ["les_c2_249_04_epic_parallel_ballad_authoring_writing"],
        "reviewsLessonIds": ["les_c2_248_05_bolor_tsom_poetry_festival_performance_spoken"],
        "reviewsUnitIds": ["unit_c2_248_poetic_parallelism_head_alliteratio"],
        "reviewReason": "Elevates modern poetry festival declamation into sacred, archaic bardic storytelling with overtone accompaniment.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide benchmark audio of traditional epic bard (*туульч*) reciting ballad with throat drone.",
        "successCriteria": [
          "Executes seamless metric transitions across 3 distinct tempo changes (andante, allegro, presto)",
          "Demonstrates authentic throat-drone control or vocal resonance appropriate to epic rhapsodists"
        ],
        "masteryEvidence": "Delivers a 5.0-minute bardic rhapsody evaluated by folklorists as worthy of the title of Master Tuulchi.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
      }
    ])

    # ----------------------------------------------------
    # UNIT 250: Heroic Epics: The Epic of Jangar (Жангар Тууль) (PL=22, RL=30, PE=9, RE=7) - 5 lessons
    # ----------------------------------------------------
    lessons.extend([
      {
        "lessonId": "les_c2_250_01_epic_of_jangar_philological_intro",
        "unitId": "unit_c2_250_heroic_epics_the_epic_of_jangar_",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 1,
        "title": "Philological Foundations: The Epic of Jangar (Жангар Тууль) & Steppe Utopian Monumentalism",
        "lessonType": "grammar_introduction",
        "primaryPurpose": "Introduce the linguistic, mythological, and formulaic architecture of the *Jangar* epic cycle: the mythic land of Bumba (where winter never comes, where men remain thirty-three years of age forever), the hero catalogue of the twelve mighty paladins (*арван хоёр арслан шинжит баатар*), and hyperbolic description syntax.",
        "communicativeOutcome": "Deconstruct the monument of Oirat-Mongolian heroic oral literature, parsing formulaic epithets, cosmic hyperbole, and monumental narrative pacing.",
        "objectivesIntroduced": ["obj_c2_250_01_master_epic_of_jangar"],
        "objectivesPracticed": ["obj_c2_249_01_master_epic_syntactic_parallelism"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_syntactic_parallelism_in_verse",
          "gram_c2_rhetorical_parallelism_alliteration"
        ],
        "grammarReviewed": ["gram_c1_classical_participle_khui"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": ["comm_c2_12_praise_poetry_chanting"],
        "communicativeFunctionsPracticed": ["comm_c2_09_metric_alliterative_poetry"],
        "communicativeFunctionsReviewed": ["comm_c1_07_literary_and_philosophical_hermeneutics"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_epic_ceremonial_tengrism"],
        "previousVocabularyReused": ["Жангар тууль", "Бумбын орон", "баатрууд", "хэтрүүлэл", "туулийн оршил"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "Oirat-Mongolian monumental heroic epic philology",
        "pragmaticTarget": "steppe utopian transcendence and superhuman heroism",
        "prerequisiteLessonIds": ["les_c2_249_05_rhapsodic_ballad_bardic_recitation_spoken"],
        "reviewsLessonIds": ["les_c2_239_01_classical_epic_syntax_intro"],
        "reviewsUnitIds": ["unit_c2_239_classical_epic_syntax_in_the_secret"],
        "reviewReason": "Bridges Secret History 13th-century prose syntax into the monumental poetic epic of Jangar.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Decodes the formulaic description of the realm of Bumba identifying 6 invariant mythic epithets",
          "Explains the symbolic significance of the 33-year eternal prime (*гучин гурван насны зулай дээрээ зогсох*)"
        ],
        "masteryEvidence": "Produces an exhaustive philological and mythological analysis of the opening prologue of Jangar.",
        "recommendedExerciseModalities": ["stylistic_transformation", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_250_02_jangar_paladins_battle_reading",
        "unitId": "unit_c2_250_heroic_epics_the_epic_of_jangar_",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 2,
        "title": "Textual Reading: The Catalog of the 6,012 Paladins & Hongor's Duel Against Mangus Armies",
        "lessonType": "reading",
        "primaryPurpose": "Parse an 870-word critical text of the Hongor chapter in *Jangar*, analyzing the epic catalogue of warrior armaments, the hyperbolic descriptions of warhorses (*Аранзал зээрд*), and the colossal clashing of bronze-breasted stallions across cosmic battlefields.",
        "communicativeOutcome": "Interpret high-tier heroic epic texts with complete philological ease, appreciating the rhythmic acceleration of combat formulas and cosmological stakes.",
        "objectivesIntroduced": ["obj_c2_250_02_parse_hongor_epic_duel"],
        "objectivesPracticed": ["obj_c2_250_01_master_epic_of_jangar"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_syntactic_parallelism_in_verse",
          "gram_c2_classical_epic_syntax_secret_history"
        ],
        "grammarReviewed": ["gram_c1_classical_participle_khui"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_12_praise_poetry_chanting"],
        "communicativeFunctionsReviewed": ["comm_c1_07_literary_and_philosophical_hermeneutics"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c2_epic_ceremonial_tengrism"],
        "previousVocabularyReused": ["Хонгор баатар", "Аранзал зээрд", "мангас", "тулааны дүрслэл", "хуяг дуулга"],
        "readingObjective": "Analyze *Jangar* battle stanzas evaluating hyperbolic weapon descriptions, steed catalogs, and supernatural combat.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "monumental heroic epic battle verse",
        "pragmaticTarget": "mythic courage, cosmic combat, and heroic loyalty",
        "prerequisiteLessonIds": ["les_c2_250_01_epic_of_jangar_philological_intro"],
        "reviewsLessonIds": ["les_c2_249_02_steppe_ballad_khukh_toli_reading"],
        "reviewsUnitIds": ["unit_c2_249_syntactic_parallelism_in_epic_strop"],
        "reviewReason": "Shifts from 19th-century historical romance verse into primordial cosmic heroic myth.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Identifies 8 epic hyperbolic idioms (e.g., 'уул шиг өндөр хар мангас', 'үүлтэй тэнгэрт дүүлэн нисэх хүлэг')",
          "Explains how combat pacing is regulated through strophic parallelism and rhythmic alliteration"
        ],
        "masteryEvidence": "Produces an 870-word philological and stylistic exegesis of Hongor's battle.",
        "recommendedExerciseModalities": ["source_comparison", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_250_03_kalmyk_jangarchi_archival_listening",
        "unitId": "unit_c2_250_heroic_epics_the_epic_of_jangar_",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 3,
        "title": "Acoustic Dissection: Authentic 1930s Archival Recording of Kalmyk Master Jangarchi Eelian Ovla",
        "lessonType": "listening",
        "primaryPurpose": "Listen to a 4.5-minute restored wax cylinder audio recording of legendary Kalmyk bard Eelian Ovla (1857-1920, recorded 1908/1930s) chanting the *Jangar* in traditional guttural rhapsodic style (160 wpm), analyzing Oirat dialectal phonetics and metric pacing.",
        "communicativeOutcome": "Process the most legendary historic sound document of Mongolic oral epic literature, deciphering archaic Oirat phonological features and trance-like chanting rhythm.",
        "objectivesIntroduced": ["obj_c2_250_03_comprehend_eelian_ovla_jangar"],
        "objectivesPracticed": ["obj_c2_250_01_master_epic_of_jangar"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_dialectal_morphosyntax_awareness",
          "gram_c2_syntactic_parallelism_in_verse"
        ],
        "grammarReviewed": ["gram_c1_reverential_and_honorific_oratory"],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phon_c2_03_oirat_kalmyk_vowel_clearing"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_12_praise_poetry_chanting"],
        "communicativeFunctionsReviewed": ["comm_c1_12_reverential_and_honorific_oratory"],
        "newProductiveLemmaTarget": 4,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_epic_ceremonial_tengrism"],
        "previousVocabularyReused": ["Ээлян Овла", "халимаг жангарч", "тууль хайлах", "эртний хууран бичлэг", "ойрад аялгуу"],
        "readingObjective": "",
        "listeningObjective": "Decipher historical wax-cylinder recordings of master Kalmyk bard chanting Jangar, transcribing Oirat phonetic forms into modern Khalkha.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "archaic Oirat-Kalmyk epic rhapsodic chant oral",
        "pragmaticTarget": "primordial trance, ancestral spirit invocation, and oral immortality",
        "prerequisiteLessonIds": ["les_c2_250_02_jangar_paladins_battle_reading"],
        "reviewsLessonIds": ["les_c2_249_03_morin_khuur_and_urtiin_duu_interplay_listening"],
        "reviewsUnitIds": ["unit_c2_249_syntactic_parallelism_in_epic_strop"],
        "reviewReason": "Bridges long song melodic listening into authentic guttural epic chanting of the Oirat bards.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide restored historic audio recording of legendary Kalmyk master Eelian Ovla reciting Jangar.",
        "successCriteria": [
          "Transcribes 16 lines of Oirat epic chant accurately identifying cleared vowels (*тодорхой үсгийн авиа*)",
          "Explains how the bard's hypnotic chanting cadence sustained multi-day oral storytelling sessions"
        ],
        "masteryEvidence": "Produces an acoustic and dialectal transcription of the Eelian Ovla wax cylinder recording.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_250_04_epic_chapter_recreation_writing",
        "unitId": "unit_c2_250_heroic_epics_the_epic_of_jangar_",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 4,
        "title": "Creative Epic Writing: Authoring an Original Lost Chapter of the Realm of Bumba",
        "lessonType": "writing",
        "primaryPurpose": "Author an 850-word original chapter in the authentic epic idiom of *Jangar*, recounting how Jangar and his twelve paladins defended the golden palace of Bumba against a frost giant army from the northern frozen sea, utilizing formulaic epithets and hyperbolic parallel verse.",
        "communicativeOutcome": "Demonstrate sovereign creative authorship within the classical Mongolic heroic epic canon, producing a new chapter indistinguishable in tone and syntax from traditional Oirat bardic cycles.",
        "objectivesIntroduced": ["obj_c2_250_04_author_lost_jangar_chapters"],
        "objectivesPracticed": ["obj_c2_250_01_master_epic_of_jangar"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_syntactic_parallelism_in_verse",
          "gram_c2_rhetorical_parallelism_alliteration"
        ],
        "grammarReviewed": ["gram_c1_classical_participle_khui"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_12_praise_poetry_chanting"],
        "communicativeFunctionsReviewed": ["comm_c1_15_creative_writing_fiction_and_literary_nonfiction"],
        "newProductiveLemmaTarget": 4,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c2_epic_ceremonial_tengrism"],
        "previousVocabularyReused": ["Бумбын дайсан", "мөсөн далай", "алтан өргөө", "туульсийн бүлэг", "баатрын тангараг"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Draft an 850-word heroic epic chapter complete with formal prologue, warrior arming sequence, battle stanzas, and banquet celebration.",
        "spokenProductionObjective": "",
        "registerTarget": "high monumental heroic epic prose & verse",
        "pragmaticTarget": "mythic recreation, heroic grandeur, and folkloric authenticity",
        "prerequisiteLessonIds": ["les_c2_250_03_kalmyk_jangarchi_archival_listening"],
        "reviewsLessonIds": ["les_c2_249_04_epic_parallel_ballad_authoring_writing"],
        "reviewsUnitIds": ["unit_c2_249_syntactic_parallelism_in_epic_strop"],
        "reviewReason": "Expands wildlife narrative ballad writing into grand mythological epic chapter composition.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Maintains strict heroic formulae for arming, horse mounting, and clash of weapons across the text",
          "Integrates authentic Oirat-Mongolian cosmological concepts without anachronistic modernisms"
        ],
        "masteryEvidence": "Submits an 850-word epic chapter praised by Academy folklorists for flawless mythic resonance.",
        "recommendedExerciseModalities": ["statutory_clause_drafting", "summary_writing"]
      },
      {
        "lessonId": "les_c2_250_05_jangar_epic_chanting_performance_spoken",
        "unitId": "unit_c2_250_heroic_epics_the_epic_of_jangar_",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 5,
        "title": "Mastery Speaking: Performing the Opening of the Jangar Epic Before the National Folkloric Assembly",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver an unscripted 5.0-minute ceremonial performance of the opening of the *Jangar* epic before the National Assembly of Folklorists and Intangible Cultural Heritage Guardians, chanting with traditional guttural resonance, rhythmic table clapping (*дэвсэх ёс*), and monumental oral delivery.",
        "communicativeOutcome": "Demonstrate the absolute pinnacle of traditional epic chanting in Mongolian, commanding the ancient oral formulaic performance register with hypnotic mastery.",
        "objectivesIntroduced": ["obj_c2_250_05_perform_jangar_epic_chanting"],
        "objectivesPracticed": ["obj_c2_250_01_master_epic_of_jangar"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_syntactic_parallelism_in_verse",
          "gram_c2_seamless_register_navigating"
        ],
        "grammarReviewed": ["gram_c1_reverential_and_honorific_oratory"],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phon_c2_06_traditional_vocal_melisma_phonetics"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_12_praise_poetry_chanting"],
        "communicativeFunctionsReviewed": ["comm_c1_12_reverential_and_honorific_oratory"],
        "newProductiveLemmaTarget": 4,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 1,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c2_epic_ceremonial_tengrism"],
        "previousVocabularyReused": ["тууль хайлах", "хүндэтгэлийн танхим", "өв тээгч", "хөөмийн түрлэг", "аман өв"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Execute an uninterrupted 5-minute guttural epic chant of the prologue of Jangar with monumental vocal authority.",
        "registerTarget": "sacred heroic epic rhapsodic chant oral",
        "pragmaticTarget": "ancestral invocation, mythic awe, and intangible cultural heritage mastery",
        "prerequisiteLessonIds": ["les_c2_250_04_epic_chapter_recreation_writing"],
        "reviewsLessonIds": ["les_c2_249_05_rhapsodic_ballad_bardic_recitation_spoken"],
        "reviewsUnitIds": ["unit_c2_249_syntactic_parallelism_in_epic_strop"],
        "reviewReason": "Unites bardic rhapsody declamation with sacred heroic epic chanting before national heritage guardians.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide benchmark audio of certified Heritage Bearer chanting Jangar prologue.",
        "successCriteria": [
          "Sustains guttural acoustic resonance without vocal strain across the entire 5.0-minute performance",
          "Executes alliterative pauses and metric cadences precisely matching authentic West Mongolian traditions"
        ],
        "masteryEvidence": "Awarded official recognition as an Intangible Heritage Master Singer in national evaluation.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
      }
    ])

    # ----------------------------------------------------
    # UNIT 251: The Epic of Geser: Steppe Chivalry & Cosmological Battles (PL=22, RL=30, PE=9, RE=7) - 5 lessons
    # ----------------------------------------------------
    lessons.extend([
      {
        "lessonId": "les_c2_251_01_epic_of_geser_mythological_intro",
        "unitId": "unit_c2_251_the_epic_of_geser_steppe_chivalry_c",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 1,
        "title": "Philological Foundations: The Epic of Geser (Гэсэр Тууль) & Steppe Cosmological Chivalry",
        "lessonType": "grammar_introduction",
        "primaryPurpose": "Introduce the textual history (1716 Beijing xylograph woodblock print), mythic structure, and chivalric ethos of the Mongolian *Geser Khan* epic: divine descent from the 33 heavens (*гучин гурван тэнгэр*), vanquishing of cosmic monsters (*мангас*), and moral order restoration.",
        "communicativeOutcome": "Deconstruct the foundational monument of Mongolian heroic romance and spiritual warfare, analyzing the interpenetration of Buddhist cosmology and indigenous Tengrist mythology.",
        "objectivesIntroduced": ["obj_c2_251_01_master_epic_of_geser"],
        "objectivesPracticed": ["obj_c2_250_01_master_epic_of_jangar"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_syntactic_parallelism_in_verse",
          "gram_c2_proverbial_syntactic_compression"
        ],
        "grammarReviewed": ["gram_c1_classical_participle_khui"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": ["comm_c2_12_praise_poetry_chanting"],
        "communicativeFunctionsPracticed": ["comm_c2_09_metric_alliterative_poetry"],
        "communicativeFunctionsReviewed": ["comm_c1_07_literary_and_philosophical_hermeneutics"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_epic_ceremonial_tengrism"],
        "previousVocabularyReused": ["Гэсэр тууль", "1716 оны модон барын хэвлэл", "тэнгэрийн хүү", "мангасыг дарах", "буддын үзэл"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "classical Mongolian Buddhist-Tengrist heroic epic romance",
        "pragmaticTarget": "cosmic moral order, divine mandate, and chivalric triumph",
        "prerequisiteLessonIds": ["les_c2_250_05_jangar_epic_chanting_performance_spoken"],
        "reviewsLessonIds": ["les_c2_250_01_epic_of_jangar_philological_intro"],
        "reviewsUnitIds": ["unit_c2_250_heroic_epics_the_epic_of_jangar_"],
        "reviewReason": "Contrasts the Oirat steppe utopianism of Jangar with the divine cosmological chivalry of Geser.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Explains the significance of the 1716 Beijing blockprint in standardizing Classical Mongolian literary language",
          "Analyzes the synthesis between Tengrist heavenly descent (*Тэнгэрээс буусан*) and Buddhist Bodhisattva vows"
        ],
        "masteryEvidence": "Produces an exhaustive philological and theological exegesis of the 1716 Geser woodblock prologue.",
        "recommendedExerciseModalities": ["stylistic_transformation", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_251_02_geser_slaying_of_the_twelve_headed_mangus_reading",
        "unitId": "unit_c2_251_the_epic_of_geser_steppe_chivalry_c",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 2,
        "title": "Textual Reading: Geser's Vanquishing of the Twelve-Headed Mangus (Арван Хоёр Толгойтой Мангас)",
        "lessonType": "reading",
        "primaryPurpose": "Parse an 870-word critical text of the fifth chapter of *Geser*, analyzing the shapeshifting duel (*хувилгаан урлаг*), the psychological tricks of Rogmo Goa, and the cosmological archery duel atop the iron mountain.",
        "communicativeOutcome": "Deconstruct classical Mongolian mythological adventure prose, interpreting magical metamorphosis formulas, tactical deception, and spiritual allegories.",
        "objectivesIntroduced": ["obj_c2_251_02_parse_geser_mangus_slaying"],
        "objectivesPracticed": ["obj_c2_251_01_master_epic_of_geser"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_syntactic_parallelism_in_verse",
          "gram_c2_classical_epic_syntax_secret_history"
        ],
        "grammarReviewed": ["gram_c1_classical_converbs_vaas_khuits"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_12_praise_poetry_chanting"],
        "communicativeFunctionsReviewed": ["comm_c1_07_literary_and_philosophical_hermeneutics"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c2_epic_ceremonial_tengrism"],
        "previousVocabularyReused": ["арван хоёр толгойтой мангас", "Рогмо гоо", "хувилах эрдэм", "төмөр уул", "шидэт сум"],
        "readingObjective": "Analyze the fifth chapter of *Geser* evaluating shapeshifting dialogue, tactical trickery, and cosmological victory.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "18th-century classical heroic romance & mythological narrative",
        "pragmaticTarget": "moral triumph over spiritual corruption and demonic chaos",
        "prerequisiteLessonIds": ["les_c2_251_01_epic_of_geser_mythological_intro"],
        "reviewsLessonIds": ["les_c2_250_02_jangar_paladins_battle_reading"],
        "reviewsUnitIds": ["unit_c2_250_heroic_epics_the_epic_of_jangar_"],
        "reviewReason": "Compares Jangar's external physical battlefield clash with Geser's magical metamorphosis duel.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Decodes 6 classical Buddhist-Tengrist magical idioms (хувилгаан чанар, онгод тэнгэр, шидэт хувирал)",
          "Explains how Rogmo Goa's character represents both profound feminine wisdom and dangerous vulnerability"
        ],
        "masteryEvidence": "Produces an 870-word literary critique of the fifth chapter of *Geser*.",
        "recommendedExerciseModalities": ["source_comparison", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_251_03_geser_temple_liturgy_listening",
        "unitId": "unit_c2_251_the_epic_of_geser_steppe_chivalry_c",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 3,
        "title": "Acoustic Dissection: Liturgical Chanting at the Geser Temple in Ulaanbaatar by Buddhist Lamas",
        "lessonType": "listening",
        "primaryPurpose": "Listen to a 4.5-minute authentic ritual recording of the Geser propitiation ceremony (*Гэсэрийн сан тахилга*) at the historic Geser Sum in Ulaanbaatar (160 wpm), analyzing the fusion of Classical Mongolian liturgical recitation, Tibetan mantric phrasing, and traditional cymbals/horns.",
        "communicativeOutcome": "Process sacred religious Buddhist-Mongolian liturgical audio, tracking high-register ritual invocations dedicated to Geser as the protector of the state and dharma.",
        "objectivesIntroduced": ["obj_c2_251_03_comprehend_geser_liturgy"],
        "objectivesPracticed": ["obj_c2_251_01_master_epic_of_geser"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_ceremonial_blessing_formulaic_syntax",
          "gram_c2_seamless_register_navigating"
        ],
        "grammarReviewed": ["gram_c1_reverential_and_honorific_oratory"],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phon_c2_06_traditional_vocal_melisma_phonetics"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_12_praise_poetry_chanting"],
        "communicativeFunctionsReviewed": ["comm_c1_12_reverential_and_honorific_oratory"],
        "newProductiveLemmaTarget": 4,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_epic_ceremonial_tengrism"],
        "previousVocabularyReused": ["Гэсэрийн сүм", "сан тахилга", "сүсэг бишрэл", "шашны зан үйл", "номын уншлага"],
        "readingObjective": "",
        "listeningObjective": "Decipher high Buddhist-Mongolian ritual chanting identifying formulaic prayers of protection, incense offerings, and deity invocations.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "sacred Buddhist-Tengrist liturgical chant oral",
        "pragmaticTarget": "spiritual purification, cosmic protection, and state consecration",
        "prerequisiteLessonIds": ["les_c2_251_02_geser_slaying_of_the_twelve_headed_mangus_reading"],
        "reviewsLessonIds": ["les_c2_250_03_kalmyk_jangarchi_archival_listening"],
        "reviewsUnitIds": ["unit_c2_250_heroic_epics_the_epic_of_jangar_"],
        "reviewReason": "Contrasts secular-oral bardic chanting with institutional monastic temple liturgical recitation.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide authentic recording of lamas performing Geser incense offering ritual at Geser Sum.",
        "successCriteria": [
          "Transcribes the Classical Mongolian incantations chanted over deep dungchen horn drones with 100% accuracy",
          "Identifies the specific protective blessings invoking Geser against epidemics, war, and spiritual degeneration"
        ],
        "masteryEvidence": "Produces an acoustic and liturgical transcription of the 4.5-minute temple ceremony.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_251_04_comparative_epic_mythology_treatise_writing",
        "unitId": "unit_c2_251_the_epic_of_geser_steppe_chivalry_c",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 4,
        "title": "Scholarly Writing: Authoring a Comparative Treatise on the Eurasian Epic Triad (Secret History, Jangar, Geser)",
        "lessonType": "writing",
        "primaryPurpose": "Author an 850-word master comparative treatise in academic Mongolian analyzing the philosophical and linguistic differences between Mongolia's three epic summits: The Secret History (historical chronicle realism), Jangar (nomadic utopian communalism), and Geser (cosmic spiritual chivalry).",
        "communicativeOutcome": "Produce doctoral-grade comparative literary scholarship in Mongolian, establishing profound typological and ideological distinctions across the Eurasian epic heritage.",
        "objectivesIntroduced": ["obj_c2_251_04_author_comparative_epic_treatise"],
        "objectivesPracticed": ["obj_c2_251_01_master_epic_of_geser"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_syntactic_parallelism_in_verse",
          "gram_c2_seamless_register_navigating"
        ],
        "grammarReviewed": ["gram_c1_academic_nominalization_frames"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_12_praise_poetry_chanting"],
        "communicativeFunctionsReviewed": ["comm_c1_04_peer_review_and_scholarly_refutation"],
        "newProductiveLemmaTarget": 4,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c2_epic_ceremonial_tengrism"],
        "previousVocabularyReused": ["гурван их туурвил", "харьцуулсан уран зохиол", "тууль судлал", "үзэл санаа", "дүр бүтээх арга"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Draft an 850-word comparative literary monograph evaluating structural, theological, and linguistic parameters across the triad.",
        "spokenProductionObjective": "",
        "registerTarget": "academic comparative literary theory publication tier",
        "pragmaticTarget": "monumental literary typologizing and cultural theorization",
        "prerequisiteLessonIds": ["les_c2_251_03_geser_temple_liturgy_listening"],
        "reviewsLessonIds": ["les_c2_250_04_epic_chapter_recreation_writing"],
        "reviewsUnitIds": ["unit_c2_250_heroic_epics_the_epic_of_jangar_"],
        "reviewReason": "Synthesizes creative epic chapter recreation into rigorous comparative theoretical scholarship.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Establishes a rigorous three-column comparative framework (chronological origin, syntactic texture, ideological purpose)",
          "Demonstrates complete fluency in contemporary Mongolian literary criticism terminology"
        ],
        "masteryEvidence": "Submits an 850-word comparative monograph judged worthy of lead article status in *Acta Mongolica*.",
        "recommendedExerciseModalities": ["statutory_clause_drafting", "summary_writing"]
      },
      {
        "lessonId": "les_c2_251_05_epic_symposium_keynote_defense_spoken",
        "unitId": "unit_c2_251_the_epic_of_geser_steppe_chivalry_c",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 5,
        "title": "Academic Speaking: Delivering the Plenary Address at the World Epic Symposium in Ulaanbaatar",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver an unscripted 5.0-minute plenary address at the World Epic Symposium (Дэлхийн Туульчдын Их Чуулган) at the State Philharmonic Hall, presenting a synthesis on the resilience of nomadic oral literature and answering questions from international folklorists.",
        "communicativeOutcome": "Demonstrate the absolute pinnacle of cultural and academic keynote speaking in Mongolian, inspiring an international audience with eloquence, intellectual vision, and patriotic grace.",
        "objectivesIntroduced": ["obj_c2_251_05_deliver_world_epic_keynote"],
        "objectivesPracticed": ["obj_c2_251_01_master_epic_of_geser"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_seamless_register_navigating",
          "gram_c2_syntactic_parallelism_in_verse"
        ],
        "grammarReviewed": ["gram_c1_reverential_and_honorific_oratory"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_12_praise_poetry_chanting"],
        "communicativeFunctionsReviewed": ["comm_c1_10_rhetorical_speechwriting"],
        "newProductiveLemmaTarget": 4,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 1,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c2_epic_ceremonial_tengrism"],
        "previousVocabularyReused": ["Дэлхийн туульчдын чуулган", "нэгдсэн хуралдаан", "соёлын дархлаа", "аман уламжлал", "үндсэн илтгэл"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Execute an unscripted 5-minute keynote address blending academic rigor, heroic recitation, and cultural leadership.",
        "registerTarget": "international world symposium plenary oratory oral",
        "pragmaticTarget": "cosmopolitan cultural diplomacy, national pride, and scholarly supremacy",
        "prerequisiteLessonIds": ["les_c2_251_04_comparative_epic_mythology_treatise_writing"],
        "reviewsLessonIds": ["les_c2_250_05_jangar_epic_chanting_performance_spoken"],
        "reviewsUnitIds": ["unit_c2_250_heroic_epics_the_epic_of_jangar_"],
        "reviewReason": "Transforms traditional bardic chanting into high international symposium keynote statesmanship.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide benchmark audio of keynote address opening the World Epic Symposium.",
        "successCriteria": [
          "Seamlessly transitions between academic analysis and 30-second live bardic verse declamation",
          "Answers technical folkloric questions from foreign delegates with instant philological citations"
        ],
        "masteryEvidence": "Delivers an unscripted 5.0-minute keynote receiving standing ovation from global delegates.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
      }
    ])

    return lessons
