# -*- coding: utf-8 -*-
"""CEFR C2 Section 02 Part 2: Nomadic Jurisprudence, Inscriptions & Section Capstone (Units 243-246, 21 lessons)."""

def get_units_243_246():
    lessons = []

    # ----------------------------------------------------
    # UNIT 243: The Great Yasa (Их Засаг) & Nomadic Jurisprudence (PL=24, RL=31, PE=9, RE=7) - 5 lessons
    # ----------------------------------------------------
    lessons.extend([
      {
        "lessonId": "les_c2_243_01_great_yasa_jurisprudence_syntax_intro",
        "unitId": "unit_c2_243_the_great_yasa_nomadic_jurisprudenc",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 1,
        "title": "Nomadic Law: Syntactic Architectures of Medieval Steppe Jurisprudence & The Great Yasa (Их Засаг)",
        "lessonType": "grammar_introduction",
        "primaryPurpose": "Introduce the legal-syntactic structures of medieval steppe statutes: unconditional imperative injunctions (*-тугай/-түгэй*, *-сугай/-сүгэй*), strict conditional consequence structures (*-ваас... үхэх ял өгсүгэй*), and Shigi Qutuqu's Blue Book (*Хөх дэвтэр*) archival jurisprudence formulas.",
        "communicativeOutcome": "Parse and formulate authentic 13th-century imperial legal statutes and judicial verdicts, decoding medieval Mongol constitutional law.",
        "objectivesIntroduced": ["obj_c2_243_01_master_great_yasa_jurisprudence"],
        "objectivesPracticed": ["obj_c2_242_01_master_anda_sworn_brotherhood"],
        "objectivesReviewed": [],
        "grammarIntroduced": ["gram_c2_legal_constitutional_clause_architecture"],
        "grammarPracticed": [
          "gram_c2_classical_epic_syntax_secret_history",
          "gram_c2_archaic_case_morphology_secret_history"
        ],
        "grammarReviewed": ["gram_c1_legal_subjunctive_conditional_chains"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": ["comm_c2_07_constitutional_court_parsing"],
        "communicativeFunctionsPracticed": ["comm_c2_10_secret_history_philological_reading"],
        "communicativeFunctionsReviewed": ["comm_c1_02_statutory_interpretation"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 7,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["Их Засаг", "хууль цааз", "Хөх дэвтэр", "Шихихутуг", "ял шийтгэл"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "imperial steppe chancellery statute & medieval constitutional jurisprudence",
        "pragmaticTarget": "absolute legal authority and unalterable imperial decree",
        "prerequisiteLessonIds": ["les_c2_242_05_jamukha_monologue_dramatic_performance_spoken"],
        "reviewsLessonIds": ["les_c1_221_01_advanced_diplomatic_and_treaty_syntax_intro"],
        "reviewsUnitIds": ["unit_c1_221_advanced_diplomatic_and_treaty_s"],
        "reviewReason": "Bridges C1 modern diplomatic treaty syntax into foundational 13th-century imperial steppe jurisprudence.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Identifies the grammatical markers that distinguish unalterable customary steppe law from temporary military commands",
          "Parses 4 reconstructible fragments of the Great Yasa recorded in Persian (Juvayni, Rashid al-Din) and Mongolian sources"
        ],
        "masteryEvidence": "Syntactically analyzes and codifies 6 core fragments of the Great Yasa.",
        "recommendedExerciseModalities": ["stylistic_transformation", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_243_02_shigi_qutuqu_appointment_reading",
        "unitId": "unit_c2_243_the_great_yasa_nomadic_jurisprudenc",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 2,
        "title": "Textual Reading: The Appointment of Shigi Qutuqu as Supreme Judge & Keeper of the Blue Book (§203)",
        "lessonType": "reading",
        "primaryPurpose": "Parse an 870-word critical text of §203 in the Secret History, where Chinggis Khaan ordains Shigi Qutuqu as supreme judge (*заргач*), instructing him to record trials in the Blue Book (*Хөх дэвтэр*) and decreeing that no successor shall alter what has been recorded in blue ink on white paper.",
        "communicativeOutcome": "Analyze the constitutional inception of the Mongolian written legal tradition, decoding its procedural safeguards and judicial ethics.",
        "objectivesIntroduced": ["obj_c2_243_02_parse_shigi_qutuqu_appointment"],
        "objectivesPracticed": ["obj_c2_243_01_master_great_yasa_jurisprudence"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_legal_constitutional_clause_architecture",
          "gram_c2_classical_epic_syntax_secret_history"
        ],
        "grammarReviewed": ["gram_c1_statutory_framing_and_normative_clauses"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": [
          "comm_c2_07_constitutional_court_parsing",
          "comm_c2_10_secret_history_philological_reading"
        ],
        "communicativeFunctionsReviewed": ["comm_c1_02_statutory_interpretation"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["улсын их заргач", "цагаан цаас", "хөх бичиг", "өөрчилж үл болно", "шударга шүүх"],
        "readingObjective": "Analyze the supreme judicial investiture text evaluating principles of precedent, judicial neutrality, and unalterable records.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "13th-century constitutional investiture & legal decree",
        "pragmaticTarget": "immutable legal sanctity and institutional justice",
        "prerequisiteLessonIds": ["les_c2_243_01_great_yasa_jurisprudence_syntax_intro"],
        "reviewsLessonIds": ["les_c2_242_02_jamukha_final_dialogue_reading"],
        "reviewsUnitIds": ["unit_c2_242_chinggis_khaan_jamukha_the_oath_of_"],
        "reviewReason": "Transitions from individual tragic execution to the establishment of institutional imperial justice.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Explains the legal concept 'Цагаан цаасан дээр хөх бичиг бичиж, дэвтэрлэснийг ургийн урагт бүү өөрчилтүгэй'",
          "Identifies 4 judicial safeguards against corruption and arbitrary sentencing in Shigi Qutuqu's mandate"
        ],
        "masteryEvidence": "Produces an 870-word constitutional analysis of §203 in the Secret History.",
        "recommendedExerciseModalities": ["source_comparison", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_243_03_constitutional_historians_roundtable_listening",
        "unitId": "unit_c2_243_the_great_yasa_nomadic_jurisprudenc",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 3,
        "title": "Acoustic Dissection: Constitutional Historians' Debate on Steppe Common Law vs. Sedentary Statism",
        "lessonType": "listening",
        "primaryPurpose": "Listen to a 4.5-minute high-level academic panel at the Constitutional Court of Mongolia (165 wpm) where legal scholars debate whether the Great Yasa functioned as a codified written constitution or a body of unwritten customary steppe norms (*заншлын эрх зүй*).",
        "communicativeOutcome": "Process advanced jurisprudence debates in Mongolian, evaluating divergent legal theories on medieval constitutionalism and customary law.",
        "objectivesIntroduced": ["obj_c2_243_03_comprehend_constitutional_debates"],
        "objectivesPracticed": ["obj_c2_243_01_master_great_yasa_jurisprudence"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c2_legal_constitutional_clause_architecture"],
        "grammarReviewed": ["gram_c1_academic_hedging_and_epistemic_stance"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_07_constitutional_court_parsing"],
        "communicativeFunctionsReviewed": ["comm_c1_03_academic_thesis_defense"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["Үндсэн хуулийн цэц", "эрх зүйн түүх", "заншлын эрх зүй", "хууль зүйн шинжлэх ухаан"],
        "readingObjective": "",
        "listeningObjective": "Decipher rapid jurisprudence debates dissecting primary historical sources, Islamic legal chronicles, and modern jurisprudence concepts.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "high constitutional jurisprudence academic panel oral",
        "pragmaticTarget": "scholarly arbitration between competing legal-historical theories",
        "prerequisiteLessonIds": ["les_c2_243_02_shigi_qutuqu_appointment_reading"],
        "reviewsLessonIds": ["les_c2_242_03_theatrical_jamukha_duel_listening"],
        "reviewsUnitIds": ["unit_c2_242_chinggis_khaan_jamukha_the_oath_of_"],
        "reviewReason": "Contrasts dramatic emotional theater with rigorous constitutional court scholarly debate.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide authentic audio of Constitutional Court scholars debating legal legacy of the Great Yasa.",
        "successCriteria": [
          "Distinguishes between Professor S. Narangerel's thesis and opposing perspectives regarding Yasa codification",
          "Transcribes 3 key legal Latinate/Mongolian terms used in contemporary comparative nomadic jurisprudence"
        ],
        "masteryEvidence": "Produces an analytical legal brief summarizing the 4.5-minute jurisprudence roundtable.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_243_04_codification_of_modern_customary_statute_writing",
        "unitId": "unit_c2_243_the_great_yasa_nomadic_jurisprudenc",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 4,
        "title": "Legislative Writing: Drafting a Contemporary Environmental Protection Statute Anchored in Steppe Law",
        "lessonType": "writing",
        "primaryPurpose": "Draft an 850-word modern draft parliamentary bill (*хуулийн төсөл*) incorporating the environmental injunctions of the Great Yasa (prohibiting washing clothes in running water, slaughtering pregnant animals, polluting river sources) into binding contemporary legislation.",
        "communicativeOutcome": "Master legislative drafting in Mongolian, seamlessly fusing ancient customary ecological taboos (*цээр ёс*) with precise modern statutory architecture.",
        "objectivesIntroduced": ["obj_c2_243_04_draft_customary_anchored_statutes"],
        "objectivesPracticed": ["obj_c2_243_01_master_great_yasa_jurisprudence"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c2_legal_constitutional_clause_architecture"],
        "grammarReviewed": ["gram_c1_statutory_framing_and_normative_clauses"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_07_constitutional_court_parsing"],
        "communicativeFunctionsReviewed": ["comm_c1_01_legislative_drafting"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["хуулийн төсөл", "байгаль орчныг хамгаалах", "ус булингартуулах", "цээрлэх ёс", "зүйл заалт"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Draft an 850-word parliamentary bill complete with statutory preamble, definitions, normative obligations, and enforcement mechanisms.",
        "spokenProductionObjective": "",
        "registerTarget": "formal parliamentary legislative statute drafting",
        "pragmaticTarget": "statutory enforceability and ecological cultural continuity",
        "prerequisiteLessonIds": ["les_c2_243_03_constitutional_historians_roundtable_listening"],
        "reviewsLessonIds": ["les_c2_242_04_tragic_drama_script_authoring_writing"],
        "reviewsUnitIds": ["unit_c2_242_chinggis_khaan_jamukha_the_oath_of_"],
        "reviewReason": "Elevates creative theater scriptwriting into enforceable modern parliamentary statutory drafting.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Follows the formal legislative conventions of the State Great Khural (preamble, articles, clauses, sanction schedules)",
          "Articulates ancient pastoral ecological taboos with precision avoiding statutory vagueness or constitutional conflict"
        ],
        "masteryEvidence": "Submits an 850-word legislative bill evaluated as ready for introduction to the parliamentary committee.",
        "recommendedExerciseModalities": ["statutory_clause_drafting", "summary_writing"]
      },
      {
        "lessonId": "les_c2_243_05_constitutional_court_oral_argumentation_spoken",
        "unitId": "unit_c2_243_the_great_yasa_nomadic_jurisprudenc",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 5,
        "title": "Mastery Speaking: Delivering Oral Argument Before the Constitutional Court of Mongolia (Цэц)",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver an unscripted 5.0-minute oral argument before the nine Justices of the Constitutional Court of Mongolia (*Үндсэн хуулийн цэцийн их суудлын хуралдаан*), defending the constitutionality of a pastoral land tenure statute by invoking nomadic legal precedent.",
        "communicativeOutcome": "Demonstrate the absolute zenith of legal advocacy in Mongolian, arguing constitutional doctrine before the supreme judicial body with commanding authority.",
        "objectivesIntroduced": ["obj_c2_243_05_deliver_constitutional_court_advocacy"],
        "objectivesPracticed": ["obj_c2_243_01_master_great_yasa_jurisprudence"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_legal_constitutional_clause_architecture",
          "gram_c2_seamless_register_navigating"
        ],
        "grammarReviewed": ["gram_c1_appellate_brief_and_bench_memo_rhetoric"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_07_constitutional_court_parsing"],
        "communicativeFunctionsReviewed": ["comm_c1_03_academic_thesis_defense"],
        "newProductiveLemmaTarget": 4,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 1,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["Цэцийн гишүүд", "их суудлын хуралдаан", "өмгөөлөгч", "Үндсэн хуулийн зөрчил", "бэлчээр ашиглалт"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Argue a complex constitutional dispute addressing judicial interruptions with instant legal citations and constitutional doctrines.",
        "registerTarget": "supreme constitutional court judicial advocacy oral",
        "pragmaticTarget": "definitive judicial persuasion and constitutional interpretation",
        "prerequisiteLessonIds": ["les_c2_243_04_codification_of_modern_customary_statute_writing"],
        "reviewsLessonIds": ["les_c2_242_05_jamukha_monologue_dramatic_performance_spoken"],
        "reviewsUnitIds": ["unit_c2_242_chinggis_khaan_jamukha_the_oath_of_"],
        "reviewReason": "Transitions from theatrical tragic monologue to supreme judicial advocacy before the Constitutional Court.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide benchmark audio of constitutional advocate delivering closing argument before the Constitutional Court.",
        "successCriteria": [
          "Employs precise constitutional formulas ('Цэцийн эрхэм гишүүд ээ...', 'Үндсэн хуулийн суурь үзэл баримтлал...') flawlessly",
          "Refutes an adversarial objection regarding nomadic collective ownership within 45 seconds using statutory precedent"
        ],
        "masteryEvidence": "Delivers an unscripted 5.0-minute constitutional advocacy receiving unanimous affirmation from simulated bench.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
      }
    ])

    # ----------------------------------------------------
    # UNIT 244: Seamless Register Navigating: Steppe Colloquial to Epic (PL=24, RL=31, PE=9, RE=7) - 5 lessons
    # ----------------------------------------------------
    lessons.extend([
      {
        "lessonId": "les_c2_244_01_seamless_register_navigating_intro",
        "unitId": "unit_c2_244_seamless_register_navigating_steppe",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 1,
        "title": "Sociolinguistics: Seamless Register Navigating Across 8 Centuries of Mongolian Language Strata",
        "lessonType": "grammar_introduction",
        "primaryPurpose": "Introduce the mechanisms of multidirectional register switching in educated Mongolian: dynamically toggling between rapid informal Khalkha colloquialism, professional-bureaucratic modern prose, Classical Mongolian written formulas, and Middle Mongolian monumental archaism.",
        "communicativeOutcome": "Command the entire 800-year linguistic spectrum of Mongolian, calibrating lexical choices, honorific inflections, and syntactic density instantly to social context.",
        "objectivesIntroduced": ["obj_c2_244_01_master_omni_register_agility"],
        "objectivesPracticed": ["obj_c2_243_01_master_great_yasa_jurisprudence"],
        "objectivesReviewed": [],
        "grammarIntroduced": ["gram_c2_seamless_register_navigating"],
        "grammarPracticed": [
          "gram_c2_rapid_khalkha_spoken_phonotactics",
          "gram_c2_classical_epic_syntax_secret_history"
        ],
        "grammarReviewed": ["gram_c1_academic_hedging_and_epistemic_stance"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": ["comm_c2_08_omni_register_agility"],
        "communicativeFunctionsPracticed": ["comm_c2_15_creative_mastery_authorial_voice"],
        "communicativeFunctionsReviewed": ["comm_c1_14_navigating_subtle_social_hierarchies"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 7,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["найруулгын түвшин", "үгийн сангийн давхарга", "хэлний шилжилт", "ярианы найруулга", "сонгодог бичиг"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "pan-diachronic stylistic meta-register",
        "pragmaticTarget": "supreme socio-pragmatic fluidity and stylistic command",
        "prerequisiteLessonIds": ["les_c2_243_05_constitutional_court_oral_argumentation_spoken"],
        "reviewsLessonIds": ["les_c2_229_01_rapid_khalkha_phonotactics_intro"],
        "reviewsUnitIds": ["unit_c2_229_rapid_khalkha_spoken_phonotactics_r"],
        "reviewReason": "Unites rapid modern spoken phonotactics with Middle Mongolian epigraphic grammar into unified register agility.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Translates a single semantic proposition into 4 distinct registers (herder vernacular, tabloid press, legal statute, 13th-century chronicle)",
          "Explains the sociolinguistic cues that mandate an immediate upward or downward register shift in Mongolian society"
        ],
        "masteryEvidence": "Executes 5 flawless register transformations across four historical linguistic registers.",
        "recommendedExerciseModalities": ["stylistic_transformation", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_244_02_multi_register_chancellery_reading",
        "unitId": "unit_c2_244_seamless_register_navigating_steppe",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 2,
        "title": "Textual Reading: Multi-Register Analysis of a State Decrees Corpus (1911, 1924, 1992, 2024)",
        "lessonType": "reading",
        "primaryPurpose": "Parse an 880-word comparative dossier comprising four historical state documents: Bogd Khanate royal edict (1911), early socialist constitutional decree (1924), democratic constitution preamble (1992), and a 2024 presidential address, deconstructing the shifting registers.",
        "communicativeOutcome": "Deconstruct modern Mongolian political and institutional prose across four consecutive regimes, tracing lexical transformations and syntactic evolutions.",
        "objectivesIntroduced": ["obj_c2_244_02_parse_multi_register_state_decrees"],
        "objectivesPracticed": ["obj_c2_244_01_master_omni_register_agility"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c2_seamless_register_navigating"],
        "grammarReviewed": ["gram_c1_classical_converbs_vaas_khuits"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_08_omni_register_agility"],
        "communicativeFunctionsReviewed": ["comm_c1_02_statutory_interpretation"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["Богд хаант засаг", "хувьсгалын тунхаг", "ардчилсан үндсэн хууль", "төрийн зарлиг"],
        "readingObjective": "Analyze four historical political texts contrasting Sino-Mongolian royal formulas, Sovietized Marxist terminology, and democratic nomadic revivals.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "diachronic state chancellery & constitutional prose",
        "pragmaticTarget": "institutional legitimacy and political rhetoric across ideological regimes",
        "prerequisiteLessonIds": ["les_c2_244_01_seamless_register_navigating_intro"],
        "reviewsLessonIds": ["les_c2_243_02_shigi_qutuqu_appointment_reading"],
        "reviewsUnitIds": ["unit_c2_243_the_great_yasa_nomadic_jurisprudenc"],
        "reviewReason": "Follows the evolution of state chancellery prose from 13th-century Yasa to 20th/21st-century state decrees.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Identifies Tibetan and Manchu loan elements in the 1911 edict vs. Russian calques in the 1924 decree",
          "Explains how the 1992 democratic constitution revived traditional Classical Mongolian concepts like *хүмүүнлэг иргэний ардчилсан нийгэм*"
        ],
        "masteryEvidence": "Produces an 880-word historical sociolinguistic analysis of the four state decrees.",
        "recommendedExerciseModalities": ["source_comparison", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_244_03_diplomatic_crisis_interview_listening",
        "unitId": "unit_c2_244_seamless_register_navigating_steppe",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 3,
        "title": "Acoustic Dissection: Live Diplomatic Press Conference Shifting Under Aggressive Interrogation",
        "lessonType": "listening",
        "primaryPurpose": "Listen to a 4.5-minute unedited live audio recording of a veteran Mongolian foreign minister facing aggressive interrogation from international and domestic journalists (175 wpm), analyzing rapid shifts between diplomatic ambiguity, cordial steppe hospitality, and sharp formal pushback.",
        "communicativeOutcome": "Process instantaneous real-time register shifts in high-stakes public diplomacy, decoding subtle diplomatic deflection, subtextual firmness, and tactical warmth.",
        "objectivesIntroduced": ["obj_c2_244_03_comprehend_diplomatic_register_shifts"],
        "objectivesPracticed": ["obj_c2_244_01_master_omni_register_agility"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_seamless_register_navigating",
          "gram_c2_pragmatic_irony_and_subtle_sarcasm"
        ],
        "grammarReviewed": ["gram_c1_diplomatic_communique_framing"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_08_omni_register_agility"],
        "communicativeFunctionsReviewed": ["comm_c1_06_diplomatic_and_consular_negotiation"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["хэвлэлийн бага хурал", "гадаад харилцааны сайд", "дипломат хариулт", "асуулт шалгаалт"],
        "readingObjective": "",
        "listeningObjective": "Decipher high-stress live diplomatic press conference tracking instant register modulations under hostile questioning.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "high-stakes live international diplomatic oral",
        "pragmaticTarget": "strategic deflection, tactical face-saving, and sovereign firmness",
        "prerequisiteLessonIds": ["les_c2_244_02_multi_register_chancellery_reading"],
        "reviewsLessonIds": ["les_c2_243_03_constitutional_historians_roundtable_listening"],
        "reviewsUnitIds": ["unit_c2_243_the_great_yasa_nomadic_jurisprudenc"],
        "reviewReason": "Contrasts academic roundtable discussion with high-stress live diplomatic press confrontation.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide authentic recording of foreign minister navigating provocative questions in live press briefing.",
        "successCriteria": [
          "Identifies the exact second the minister shifts from cordial diplomatic boilerplate to icy sovereign reprimand",
          "Deconstructs 2 implicit diplomatic signals conveying state policy without explicit public statement"
        ],
        "masteryEvidence": "Produces an exhaustive communicative and rhetorical breakdown of the 4.5-minute press conference.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_244_04_cross_register_polemical_essay_writing",
        "unitId": "unit_c2_244_seamless_register_navigating_steppe",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 4,
        "title": "Stylistic Writing: Authoring a Multi-Register Polemical Essay on Modern Mongolian Identity",
        "lessonType": "writing",
        "primaryPurpose": "Author an 850-word master-tier polemical essay intentionally interweaving three linguistic layers: streetwise contemporary Ulaanbaatar slang, rigorous Western academic sociology, and grand Classical Mongolian poetic aphorisms, defending cultural resilience in globalization.",
        "communicativeOutcome": "Demonstrate supreme stylistic dexterity in written Mongolian, harmonizing disparate sociolinguistic registers into a dazzling, unified literary voice.",
        "objectivesIntroduced": ["obj_c2_244_04_author_multi_register_essays"],
        "objectivesPracticed": ["obj_c2_244_01_master_omni_register_agility"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_seamless_register_navigating",
          "gram_c2_satirical_polemical_framing"
        ],
        "grammarReviewed": ["gram_c1_academic_nominalization_frames"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_08_omni_register_agility"],
        "communicativeFunctionsReviewed": ["comm_c1_07_literary_and_philosophical_hermeneutics"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["даяаршил", "үндэсний онцлог", "холимог найруулга", "нийгмийн давхарга", "хэлний дархлаа"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Draft an 850-word poly-stylistic essay that shifts effortlessly between slang, academic critique, and classical literature.",
        "spokenProductionObjective": "",
        "registerTarget": "multi-register high literary-journalistic polemic",
        "pragmaticTarget": "stylistic virtuosity and cultural self-examination",
        "prerequisiteLessonIds": ["les_c2_244_03_diplomatic_crisis_interview_listening"],
        "reviewsLessonIds": ["les_c2_243_04_codification_of_modern_customary_statute_writing"],
        "reviewsUnitIds": ["unit_c2_243_the_great_yasa_nomadic_jurisprudenc"],
        "reviewReason": "Bridges formal statutory drafting into dazzling multi-register literary-philosophical essay writing.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Transitions between urban slang and Classical Mongolian without breaking narrative coherence or tone",
          "Achieves devastating cultural satire while upholding a profoundly serious intellectual thesis"
        ],
        "masteryEvidence": "Submits an 850-word poly-stylistic essay celebrated by leading Mongolian essayists.",
        "recommendedExerciseModalities": ["statutory_clause_drafting", "summary_writing"]
      },
      {
        "lessonId": "les_c2_244_05_omni_register_live_chameleon_spoken",
        "unitId": "unit_c2_244_seamless_register_navigating_steppe",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 5,
        "title": "Mastery Speaking: The Linguistic Chameleon Challenge — 4 Rapid Interlocutors in 5 Minutes",
        "lessonType": "spoken_production",
        "primaryPurpose": "Engage in an unscripted 5.0-minute interactive live oral simulation confronting 4 successive interlocutors with zero pause: an elderly herder inquiring about pasture rights, a young IT founder pitching a fintech venture, an archbishop monk debating Buddhist epistemology, and a foreign ambassador negotiating trade.",
        "communicativeOutcome": "Demonstrate instant, seamless sociolinguistic adaptability, matching the exact phonetics, vocabulary, honorifics, and cultural worldview of 4 completely distinct Mongolian social worlds.",
        "objectivesIntroduced": ["obj_c2_244_05_execute_linguistic_chameleon_simulation"],
        "objectivesPracticed": ["obj_c2_244_01_master_omni_register_agility"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c2_seamless_register_navigating"],
        "grammarReviewed": ["gram_c1_navigating_subtle_social_hierarchies"],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phon_c2_01_extreme_vowel_reduction_and_syncope"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_08_omni_register_agility"],
        "communicativeFunctionsReviewed": ["comm_c1_14_navigating_subtle_social_hierarchies"],
        "newProductiveLemmaTarget": 4,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 1,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["харилцан яриа", "эгшин зуурын шилжилт", "дүр бүтээх", "нийгмийн орчин"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Execute immediate, unhesitating register transitions across 4 radically disparate social encounters within 5 minutes.",
        "registerTarget": "omni-register rapid adaptive oral chameleon",
        "pragmaticTarget": "instant socio-cultural camouflage and communicative supremacy",
        "prerequisiteLessonIds": ["les_c2_244_04_cross_register_polemical_essay_writing"],
        "reviewsLessonIds": ["les_c2_243_05_constitutional_court_oral_argumentation_spoken"],
        "reviewsUnitIds": ["unit_c2_243_the_great_yasa_nomadic_jurisprudenc"],
        "reviewReason": "Tests total register switching mastery from supreme court oral advocacy to everyday pastoral dialect.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide benchmark audio of C2 master executing instant register shifts in simulated multi-party encounter.",
        "successCriteria": [
          "Modulates vocal timbre, speech tempo, and lexical choice within 3 seconds of greeting each interlocutor",
          "Commits zero sociolinguistic breaches across herder, tech startup, Buddhist monk, and ambassador encounters"
        ],
        "masteryEvidence": "Successfully passes the 5.0-minute 4-interlocutor chameleon challenge with zero hesitation.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
      }
    ])

    # ----------------------------------------------------
    # UNIT 245: Classical Inscriptions: The Stele of Yisüngge (1224) (PL=22, RL=30, PE=9, RE=7) - 5 lessons
    # ----------------------------------------------------
    lessons.extend([
      {
        "lessonId": "les_c2_245_01_stele_of_yisungge_epigraphic_intro",
        "unitId": "unit_c2_245_classical_inscriptions_the_stele_of",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 1,
        "title": "Philological Foundations: The Stele of Yisüngge (1224) & Earliest Uighur-Mongolian Inscriptions",
        "lessonType": "grammar_introduction",
        "primaryPurpose": "Introduce the world's oldest monument in traditional Mongolian script—the Stele of Yisüngge (Чингисийн чулууны бичиг, 1224)—analyzing its five-line epigraphic inscription, honorific line-spacing, measurement metrics (*алд*), and archery terminology.",
        "communicativeOutcome": "Decipher and analyze the foundational epigraphic artifact of Mongolian literacy, understanding its historical, archaeological, and paleographic significance.",
        "objectivesIntroduced": ["obj_c2_245_01_master_stele_of_yisungge"],
        "objectivesPracticed": ["obj_c2_244_01_master_omni_register_agility"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_classical_epic_syntax_secret_history",
          "gram_c2_archaic_case_morphology_secret_history"
        ],
        "grammarReviewed": ["gram_c1_classical_participle_khui"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": ["comm_c2_10_secret_history_philological_reading"],
        "communicativeFunctionsPracticed": ["comm_c2_08_omni_register_agility"],
        "communicativeFunctionsReviewed": ["comm_c1_07_literary_and_philosophical_hermeneutics"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["Чингисийн чулууны бичиг", "Есөнхэй", "хөшөөний бичээс", "хуучин монгол бичиг", "алд хэмжүүр"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "13th-century monumental stone epigraphy",
        "pragmaticTarget": "monumental commemoration, archery prowess, and imperial glory",
        "prerequisiteLessonIds": ["les_c2_244_05_omni_register_live_chameleon_spoken"],
        "reviewsLessonIds": ["les_c2_238_01_secret_history_philological_foundations_intro"],
        "reviewsUnitIds": ["unit_c2_238_the_secret_history_of_the_mongols_p"],
        "reviewReason": "Connects manuscript transmission of the Secret History with direct primary stone monument epigraphy.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Transcribes all 5 lines of the Yisüngge stone inscription from original script into Cyrillic and phonetic IPA",
          "Explains why Chinggis Khaan's name is placed higher than the main line of text (*мөр тэтгэх ёс*)"
        ],
        "masteryEvidence": "Produces an authoritative epigraphic parsing of the 1224 Stele of Yisüngge.",
        "recommendedExerciseModalities": ["stylistic_transformation", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_245_02_stele_and_paiza_comparative_reading",
        "unitId": "unit_c2_245_classical_inscriptions_the_stele_of",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 2,
        "title": "Textual Reading: Monumental Stelae & Imperial Paiza Passports (§1220-§1300 Inscriptions)",
        "lessonType": "reading",
        "primaryPurpose": "Parse an 860-word critical corpus of primary epigraphic inscriptions from the Mongol Empire: the Yisüngge stele, the Möngke Khaan inscription (1257), and three silver/gilt bronze imperial passport tablets (*гэрэгэ / пайз*), comparing formulaic invocations of Eternal Tengri.",
        "communicativeOutcome": "Deconstruct imperial epigraphy and diplomatic passports across the Mongol Empire, interpreting standard legal formulas with supreme philological accuracy.",
        "objectivesIntroduced": ["obj_c2_245_02_parse_imperial_paiza_inscriptions"],
        "objectivesPracticed": ["obj_c2_245_01_master_stele_of_yisungge"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_classical_epic_syntax_secret_history",
          "gram_c2_legal_constitutional_clause_architecture"
        ],
        "grammarReviewed": ["gram_c1_classical_quotative_khemeen"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_10_secret_history_philological_reading"],
        "communicativeFunctionsReviewed": ["comm_c1_07_literary_and_philosophical_hermeneutics"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["Мөнх хааны хөшөө", "гэрэгэ", "пайз", "Мөнх тэнгэрийн хүчин дор", "хааны зарлиг"],
        "readingObjective": "Analyze primary 13th-century imperial bronze tablets and stone inscriptions evaluating sovereign authority formulas.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "imperial epigraphic decree & diplomatic passport formula",
        "pragmaticTarget": "transcontinental diplomatic immunity and cosmic imperial legitimacy",
        "prerequisiteLessonIds": ["les_c2_245_01_stele_of_yisungge_epigraphic_intro"],
        "reviewsLessonIds": ["les_c2_244_02_multi_register_chancellery_reading"],
        "reviewsUnitIds": ["unit_c2_244_seamless_register_navigating_steppe"],
        "reviewReason": "Deepens multi-register chancellery reading into physical archaeological bronze and stone artifacts.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Decodes the universal imperial opening formula ('Мөнх тэнгэрийн хүчинд, их суу залийн ивээлд...') on 3 distinct paizas",
          "Identifies the precise legal penalties inscribed on paiza passports for impeding imperial messengers (*өрөө унаа өгөхгүй бол үхэх ялтай*)"
        ],
        "masteryEvidence": "Produces an 860-word epigraphic and diplomatic analysis of the imperial passport tablets.",
        "recommendedExerciseModalities": ["source_comparison", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_245_03_hermitage_curators_provenance_listening",
        "unitId": "unit_c2_245_classical_inscriptions_the_stele_of",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 3,
        "title": "Acoustic Dissection: Hermitage Museum Curator & Institute of Archaeology on Returning Steppe Heritage",
        "lessonType": "listening",
        "primaryPurpose": "Listen to a 4.5-minute archival audio discussion between a State Hermitage Museum curator in Saint Petersburg and the Director of the Institute of Archaeology of the Mongolian Academy of Sciences (165 wpm), analyzing diplomatic and legal claims for repatriating the Stele of Yisüngge.",
        "communicativeOutcome": "Process sophisticated international museum repatriation and cultural heritage diplomacy audio in Mongolian, analyzing archival legal claims and archaeological provenance.",
        "objectivesIntroduced": ["obj_c2_245_03_comprehend_repatriation_diplomacy"],
        "objectivesPracticed": ["obj_c2_245_01_master_stele_of_yisungge"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c2_seamless_register_navigating"],
        "grammarReviewed": ["gram_c1_advanced_diplomatic_and_treaty_syntax"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_10_secret_history_philological_reading"],
        "communicativeFunctionsReviewed": ["comm_c1_06_diplomatic_and_consular_negotiation"],
        "newProductiveLemmaTarget": 4,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["Эрмитаж музей", "Археологийн хүрээлэн", "соёлын өвийг буцаан авах", "палеографи", "дурсгал"],
        "readingObjective": "",
        "listeningObjective": "Decipher high-level international cultural heritage diplomacy discussing 19th-century colonial acquisition and modern repatriation treaties.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "international museum curatorial & repatriation diplomacy oral",
        "pragmaticTarget": "national heritage recovery and ethical provenance adjudication",
        "prerequisiteLessonIds": ["les_c2_245_02_stele_and_paiza_comparative_reading"],
        "reviewsLessonIds": ["les_c2_244_03_diplomatic_crisis_interview_listening"],
        "reviewsUnitIds": ["unit_c2_244_seamless_register_navigating_steppe"],
        "reviewReason": "Connects live diplomatic press confrontation to delicate museum cultural repatriation negotiations.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide authentic recording of archaeological negotiation on returning Mongol Empire stone monuments.",
        "successCriteria": [
          "Summarizes the legal arguments based on the 1970 UNESCO Convention on Cultural Property presented by the Mongolian side",
          "Extracts the curator's paleographic defense regarding climate-controlled preservation conditions"
        ],
        "masteryEvidence": "Produces an exhaustive diplomatic and legal dossier on the repatriation of the Stele of Yisüngge.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_245_04_unesco_heritage_nomination_writing",
        "unitId": "unit_c2_245_classical_inscriptions_the_stele_of",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 4,
        "title": "Diplomatic Writing: Authoring a UNESCO Memory of the World Nomination Dossier for 13th-Century Inscriptions",
        "lessonType": "writing",
        "primaryPurpose": "Author an 850-word formal UNESCO Memory of the World nomination dossier in academic Mongolian, establishing the universal outstanding value of the Stele of Yisüngge and the Secret History as foundational landmarks of world nomadic civilization.",
        "communicativeOutcome": "Produce international-tier cultural heritage documentation in Mongolian, articulating the global historical significance of steppe literacy with scholarly and diplomatic eloquence.",
        "objectivesIntroduced": ["obj_c2_245_04_author_unesco_nomination_dossiers"],
        "objectivesPracticed": ["obj_c2_245_01_master_stele_of_yisungge"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_seamless_register_navigating",
          "gram_c2_legal_constitutional_clause_architecture"
        ],
        "grammarReviewed": ["gram_c1_academic_nominalization_frames"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_10_secret_history_philological_reading"],
        "communicativeFunctionsReviewed": ["comm_c1_01_legislative_drafting"],
        "newProductiveLemmaTarget": 4,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["ЮНЕСКО", "Дэлхийн дурсамж хөтөлбөр", "дэлхийн дахины хосгүй үнэ цэнэ", "нүүдэлчдийн бичиг соёл"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Draft an 850-word UNESCO nomination dossier justifying authenticity, integrity, and global documentary heritage criteria.",
        "spokenProductionObjective": "",
        "registerTarget": "formal international cultural heritage nomination dossier",
        "pragmaticTarget": "global recognition and immortal cultural codification",
        "prerequisiteLessonIds": ["les_c2_245_03_hermitage_curators_provenance_listening"],
        "reviewsLessonIds": ["les_c2_244_04_cross_register_polemical_essay_writing"],
        "reviewsUnitIds": ["unit_c2_244_seamless_register_navigating_steppe"],
        "reviewReason": "Transforms polemical cultural essay writing into formal international treaty and UNESCO nomination documentation.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Satisfies all criteria of UNESCO Memory of the World documentation guidelines in formal diplomatic Mongolian",
          "Demonstrates that 13th-century Mongolian script unified multilingual administrations across Eurasia"
        ],
        "masteryEvidence": "Submits an 850-word UNESCO nomination dossier evaluated as meeting international treaty standards.",
        "recommendedExerciseModalities": ["statutory_clause_drafting", "summary_writing"]
      },
      {
        "lessonId": "les_c2_245_05_unesco_plenary_keynote_defense_spoken",
        "unitId": "unit_c2_245_classical_inscriptions_the_stele_of",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 5,
        "title": "Diplomatic Speaking: Defending the Steppe Epigraphic Legacy at the UNESCO World Heritage Assembly",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver an unscripted 5.0-minute keynote defense at the UNESCO World Heritage General Assembly in Paris (in elevated diplomatic Mongolian with simultaneous interpretation), defending Mongolia's sovereign right to lead global research on Eurasian nomadic epigraphy.",
        "communicativeOutcome": "Command international multilateral diplomatic oratory in Mongolian, projecting supreme cultural authority and intellectual sovereignty on the world stage.",
        "objectivesIntroduced": ["obj_c2_245_05_deliver_unesco_plenary_defense"],
        "objectivesPracticed": ["obj_c2_245_01_master_stele_of_yisungge"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c2_seamless_register_navigating"],
        "grammarReviewed": ["gram_c1_reverential_and_honorific_oratory"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c2_08_omni_register_agility"],
        "communicativeFunctionsReviewed": ["comm_c1_10_rhetorical_speechwriting"],
        "newProductiveLemmaTarget": 4,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 1,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["ЮНЕСКО-гийн ерөнхий ассамблей", "дэлхийн индэр", "соёлын тусгаар тогтнол", "элчин сайд"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Deliver a 5-minute multilateral keynote address defending Mongolian epigraphic patrimony with sovereign dignity and oratorical brilliance.",
        "registerTarget": "multilateral international diplomatic plenary oratory oral",
        "pragmaticTarget": "sovereign cultural primacy and international consensus leadership",
        "prerequisiteLessonIds": ["les_c2_245_04_unesco_heritage_nomination_writing"],
        "reviewsLessonIds": ["les_c2_244_05_omni_register_live_chameleon_spoken"],
        "reviewsUnitIds": ["unit_c2_244_seamless_register_navigating_steppe"],
        "reviewReason": "Expands individual social chameleon flexibility into global diplomatic leadership at the UNESCO General Assembly.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide benchmark audio of Ambassador of Mongolia addressing UNESCO plenary session.",
        "successCriteria": [
          "Balances profound national pride with universal cosmopolitan appeal in elevated diplomatic Khalkha",
          "Secures unanimous adoption of the draft resolution by delegates in simulated plenary vote"
        ],
        "masteryEvidence": "Delivers an unscripted 5.0-minute plenary defense receiving unanimous diplomatic support.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
      }
    ])

    # ----------------------------------------------------
    # UNIT 246: Secret History Capstone: Philological Textual Commentary (PL=26, RL=40, PE=12, RE=12) - 6 lessons
    # ----------------------------------------------------
    lessons.extend([
      {
        "lessonId": "les_c2_246_01_c2_sec02_capstone_philological_monograph_intro",
        "unitId": "unit_c2_246_secret_history_capstone_philologica",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 1,
        "title": "Section 02 Capstone Introduction: Synthesizing Classical Philology, Epigraphy & Medieval Steppe Law",
        "lessonType": "grammar_introduction",
        "primaryPurpose": "Synthesize the entire philological, syntactic, and legal architecture of Section 02 (The Secret History of the Mongols, Classical Epic Syntax, Archaic Case Morphology, The Alan Qo'a Parable, The Oath of Anda, The Great Yasa, Multi-Register Agility, and Epigraphic Stelae), outlining the capstone requirements.",
        "communicativeOutcome": "Establish an integrated theoretical framework unifying 13th-century linguistics, epigraphy, and legal history into a cohesive mastery-tier synthesis.",
        "objectivesIntroduced": ["obj_c2_246_01_synthesize_c2_sec02_philology"],
        "objectivesPracticed": [
          "obj_c2_238_01_master_secret_history_philology",
          "obj_c2_239_01_master_classical_epic_syntax",
          "obj_c2_240_01_master_archaic_case_morphology",
          "obj_c2_241_01_master_alan_qoa_parable",
          "obj_c2_242_01_master_anda_sworn_brotherhood",
          "obj_c2_243_01_master_great_yasa_jurisprudence",
          "obj_c2_244_01_master_omni_register_agility",
          "obj_c2_245_01_master_stele_of_yisungge"
        ],
        "objectivesReviewed": ["obj_c2_237_01_synthesize_c2_sec01_stylistics"],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_classical_epic_syntax_secret_history",
          "gram_c2_archaic_case_morphology_secret_history",
          "gram_c2_legal_constitutional_clause_architecture",
          "gram_c2_seamless_register_navigating"
        ],
        "grammarReviewed": ["gram_c2_literary_polyphony_and_indirect_interior_monologue"],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phon_c2_05_middle_mongolian_phonology_reconstruction"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": [
          "comm_c2_08_omni_register_agility",
          "comm_c2_10_secret_history_philological_reading",
          "comm_c2_07_constitutional_court_parsing"
        ],
        "communicativeFunctionsReviewed": ["comm_c2_15_creative_mastery_authorial_voice"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 8,
        "newProductiveExpressionTarget": 3,
        "newReceptiveExpressionTarget": 3,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["эгзэгтэй үе", "эртний судлал", "эх бичгийн цогц шинжилгээ", "судалгааны нэгтгэл"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "supreme philological, epigraphic & diachronic meta-register",
        "pragmaticTarget": "monumental scholarly synthesis and hermeneutic mastery",
        "prerequisiteLessonIds": ["les_c2_245_05_unesco_plenary_keynote_defense_spoken"],
        "reviewsLessonIds": ["les_c2_237_01_c2_sec01_capstone_stylistic_nuance_synthesis_intro"],
        "reviewsUnitIds": ["unit_c2_237_contemporary_literature_capstone_sa"],
        "reviewReason": "Unites Section 01 contemporary literary stylistics with Section 02 classical Middle Mongolian philology.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Outlines a comprehensive methodology for editing, annotating, and publishing a critical edition of a 13th-century Mongolian manuscript",
          "Articulates the interaction between phonological reconstruction, syntactic hierarchy, and legal pragmatics across all Section 02 units"
        ],
        "masteryEvidence": "Produces an exhaustive 10-point research prospectus for the Section 02 capstone monograph.",
        "recommendedExerciseModalities": ["stylistic_transformation", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_246_02_c2_sec02_capstone_untranslated_manuscript_reading",
        "unitId": "unit_c2_246_secret_history_capstone_philologica",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 2,
        "title": "Capstone Reading: Deciphering an Unedited Middle Mongolian Manuscript Fragment (§153-§155)",
        "lessonType": "reading",
        "primaryPurpose": "Parse an unedited 920-word Middle Mongolian manuscript fragment (§153-§155, describing the downfall of the Jurkin clan and the trial of Sacha Beki) containing corrupted Ming phonetic characters, archaic case morphology, and lacunae.",
        "communicativeOutcome": "Demonstrate the apex of philological reading autonomy, transcribing, emending, and interpreting corrupt primary Middle Mongolian texts without modern scholarly translations.",
        "objectivesIntroduced": ["obj_c2_246_02_parse_unedited_middle_mongolian_manuscript"],
        "objectivesPracticed": ["obj_c2_246_01_synthesize_c2_sec02_philology"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_classical_epic_syntax_secret_history",
          "gram_c2_archaic_case_morphology_secret_history",
          "gram_c2_legal_constitutional_clause_architecture"
        ],
        "grammarReviewed": ["gram_c1_classical_participle_khui"],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phon_c2_05_middle_mongolian_phonology_reconstruction"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": [
          "comm_c2_10_secret_history_philological_reading",
          "comm_c2_07_constitutional_court_parsing"
        ],
        "communicativeFunctionsReviewed": ["comm_c1_07_literary_and_philosophical_hermeneutics"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 8,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["Жүрхин", "Сача бэхи", "ял хэлэлцэх", "эртний хуулбар", "бичвэрийн зөрөө"],
        "readingObjective": "Decipher and emend corrupt primary Middle Mongolian manuscript passage analyzing genealogical treachery and customary trial syntax.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "unedited 13th-century Middle Mongolian manuscript primary text",
        "pragmaticTarget": "paleographic decipherment and judicial-historical truth recovery",
        "prerequisiteLessonIds": ["les_c2_246_01_c2_sec02_capstone_philological_monograph_intro"],
        "reviewsLessonIds": ["les_c2_245_02_stele_and_paiza_comparative_reading"],
        "reviewsUnitIds": ["unit_c2_245_classical_inscriptions_the_stele_of"],
        "reviewReason": "Progresses from epigraphic stone inscriptions to parsing unedited corrupted paper manuscript fragments.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Resolves 4 paleographic lacunae through comparative syntactic and lexical reconstruction",
          "Provides a pristine interlinear transcription into modern academic Cyrillic with zero morphological errors"
        ],
        "masteryEvidence": "Produces a 920-word critical transcription and textual commentary on §153-§155.",
        "recommendedExerciseModalities": ["source_comparison", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_246_03_c2_sec02_capstone_academician_colloquium_listening",
        "unitId": "unit_c2_246_secret_history_capstone_philologica",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 3,
        "title": "Capstone Listening: The Academy of Sciences High Colloquium on 13th-Century Textual Transmission",
        "lessonType": "listening",
        "primaryPurpose": "Listen to a 4.5-minute unedited recording of a high colloquium at the Institute of Language and Literature of the Mongolian Academy of Sciences (175 wpm) where 3 world-renowned academicians dispute the date of composition and possible Persian parallel sources (Jami al-Tawarikh).",
        "communicativeOutcome": "Process the fastest, most intellectually demanding academic speech in Mongolian linguistics, navigating competing scholarly citations, philological jargon, and rapid-fire intellectual refutations.",
        "objectivesIntroduced": ["obj_c2_246_03_comprehend_academy_high_colloquium"],
        "objectivesPracticed": ["obj_c2_246_01_synthesize_c2_sec02_philology"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_seamless_register_navigating",
          "gram_c2_satirical_polemical_framing"
        ],
        "grammarReviewed": ["gram_c1_academic_hedging_and_epistemic_stance"],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phon_c2_01_extreme_vowel_reduction_and_syncope"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": [
          "comm_c2_10_secret_history_philological_reading",
          "comm_c2_08_omni_register_agility"
        ],
        "communicativeFunctionsReviewed": ["comm_c1_03_academic_thesis_defense"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 8,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 3,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["Хэл зохиолын хүрээлэн", "эрдэмтдийн зөвлөл", "Рашид ад-Дин", "он цагийн тоолол"],
        "readingObjective": "",
        "listeningObjective": "Decipher intense high-velocity colloquium among Academy academicians debating Middle Mongolian philological controversies.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "elite academic colloquium & philological dispute oral",
        "pragmaticTarget": "scholarly polemic, evidentiary superiority, and academic prestige",
        "prerequisiteLessonIds": ["les_c2_246_02_c2_sec02_capstone_untranslated_manuscript_reading"],
        "reviewsLessonIds": ["les_c2_245_03_hermitage_curators_provenance_listening"],
        "reviewsUnitIds": ["unit_c2_245_classical_inscriptions_the_stele_of"],
        "reviewReason": "Elevates museum curatorial diplomacy into the highest level of academic philological dispute.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide authentic recording of Academy of Sciences high colloquium on Mongol Empire historiography.",
        "successCriteria": [
          "Deconstructs the 3 distinct chronological arguments regarding the Year of the Rat (1240 vs. 1252 vs. 1264)",
          "Transcribes the rapid colloquial phonetic elisions used by senior academicians during spontaneous heated debate"
        ],
        "masteryEvidence": "Produces an exhaustive analytical critique of the 4.5-minute Academy colloquium.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "discourse_analysis"]
      },
      {
        "lessonId": "les_c2_246_04_c2_sec02_capstone_critical_commentary_monograph_writing",
        "unitId": "unit_c2_246_secret_history_capstone_philologica",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 4,
        "title": "Capstone Writing: Authoring a 900-Word Published Philological Textual Commentary & Emendation",
        "lessonType": "writing",
        "primaryPurpose": "Author a 900-word publishable philological textual commentary on a controversial passage of the Secret History (§254, the succession debate between Jochi and Chagatai), providing original transcription, critical apparatus, syntactic tree, and historical-jurisprudential exegesis.",
        "communicativeOutcome": "Produce doctoral-tier philological scholarship in academic Mongolian, establishing a definitive textual commentary that withstands scrutiny from international Mongolists.",
        "objectivesIntroduced": ["obj_c2_246_04_author_capstone_philological_monograph"],
        "objectivesPracticed": ["obj_c2_246_01_synthesize_c2_sec02_philology"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_classical_epic_syntax_secret_history",
          "gram_c2_archaic_case_morphology_secret_history",
          "gram_c2_legal_constitutional_clause_architecture",
          "gram_c2_seamless_register_navigating"
        ],
        "grammarReviewed": ["gram_c1_academic_nominalization_frames"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": [
          "comm_c2_10_secret_history_philological_reading",
          "comm_c2_07_constitutional_court_parsing",
          "comm_c2_08_omni_register_agility"
        ],
        "communicativeFunctionsReviewed": ["comm_c1_04_peer_review_and_scholarly_refutation"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 8,
        "newProductiveExpressionTarget": 3,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["залгамжлах эрх", "Зүчи", "Цагаадай", "хэрүүл маргаан", "эх бичгийн судалгаа"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Draft a 900-word peer-reviewed scholarly commentary analyzing succession law, insulting idioms, and textual variants in §254.",
        "spokenProductionObjective": "",
        "registerTarget": "academic philological monograph publication tier",
        "pragmaticTarget": "definitive scholarly resolution of historic succession dispute",
        "prerequisiteLessonIds": ["les_c2_246_03_c2_sec02_capstone_academician_colloquium_listening"],
        "reviewsLessonIds": ["les_c2_245_04_unesco_heritage_nomination_writing"],
        "reviewsUnitIds": ["unit_c2_245_classical_inscriptions_the_stele_of"],
        "reviewReason": "Consolidates UNESCO nomination drafting into an exhaustive academic philological monograph chapter.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Incorporates full textual apparatus referencing Chinese phonetics, Cyrillic editions, and Persian chronicles",
          "Synthesizes syntactic, morphological, and jurisprudential analysis without leaving any interpretive lacunae"
        ],
        "masteryEvidence": "Submits a 900-word critical textual commentary accepted for publication in *Studia Mongolica*.",
        "recommendedExerciseModalities": ["statutory_clause_drafting", "summary_writing"]
      },
      {
        "lessonId": "les_c2_246_05_c2_sec02_capstone_doctoral_dissertation_defense_spoken",
        "unitId": "unit_c2_246_secret_history_capstone_philologica",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 5,
        "title": "Capstone Speaking: Defending a Doctoral Dissertation on Middle Mongolian Before the State Degree Council",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver an unscripted 5.0-minute defense of an original doctoral dissertation on Middle Mongolian morphosyntax before the State Degree Council (Эрдмийн зэрэг хамгаалуулах зөвлөл), delivering a rigorous presentation and fielding hostile inquisitorial questions from 3 designated academic opponents.",
        "communicativeOutcome": "Demonstrate supreme academic spoken mastery, defending complex linguistic discoveries with intellectual brilliance, total poise, and authoritative Mongolian terminology.",
        "objectivesIntroduced": ["obj_c2_246_05_defend_doctoral_dissertation_middle_mongolian"],
        "objectivesPracticed": ["obj_c2_246_01_synthesize_c2_sec02_philology"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_seamless_register_navigating",
          "gram_c2_satirical_polemical_framing"
        ],
        "grammarReviewed": ["gram_c1_academic_hedging_and_epistemic_stance"],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phon_c2_05_middle_mongolian_phonology_reconstruction"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": [
          "comm_c2_10_secret_history_philological_reading",
          "comm_c2_08_omni_register_agility"
        ],
        "communicativeFunctionsReviewed": ["comm_c1_03_academic_thesis_defense"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 8,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["Эрдмийн зэрэг хамгаалах зөвлөл", "доктор хамгаалах", "албан ёсны шүүмжлэгч", "эрдэм шинжилгээ"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Execute an unscripted 5-minute doctoral defense presenting novel linguistic proofs and refuting 3 hostile academic challenges.",
        "registerTarget": "highest academic degree defense & doctoral disputation oral",
        "pragmaticTarget": "scholarly coronation, total refutation of critics, and doctor of philology award",
        "prerequisiteLessonIds": ["les_c2_246_04_c2_sec02_capstone_critical_commentary_monograph_writing"],
        "reviewsLessonIds": ["les_c2_245_05_unesco_plenary_keynote_defense_spoken"],
        "reviewsUnitIds": ["unit_c2_245_classical_inscriptions_the_stele_of"],
        "reviewReason": "Elevates UNESCO keynote presentation into high-stakes defense before the State Degree Council.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide benchmark audio of candidate successfully defending Doctor of Science (Sc.D.) dissertation in Mongolian linguistics.",
        "successCriteria": [
          "Defends the dissertation's novel reconstruction of archaic verbal converbs with uncompromising philological rigor",
          "Maintains absolute composure and elevated academic register when challenged by senior academicians"
        ],
        "masteryEvidence": "Unanimously awarded the degree of Doctor of Philology (Sc.D.) with highest honors (100% affirmative ballots).",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
      },
      {
        "lessonId": "les_c2_246_06_c2_sec02_culminating_operational_synthesis",
        "unitId": "unit_c2_246_secret_history_capstone_philologica",
        "cefrLevel": "C2",
        "sequenceWithinUnit": 6,
        "title": "Section 02 Culminating Operational Synthesis: Full Mastery Verification of Classical Philology & Secret History",
        "lessonType": "review",
        "primaryPurpose": "Execute a comprehensive operational review of Section 02, verifying absolute native-like mastery across manuscript paleography, medieval epic syntax, archaic case morphology, nomadic jurisprudence, multi-register switching, and primary monument epigraphy.",
        "communicativeOutcome": "Lock in total operational mastery of Section 02, confirming readiness to advance to Section 03 (Gnomic Wisdom, Folk Epics, Ceremonial Blessings & Tengrism).",
        "objectivesIntroduced": [],
        "objectivesPracticed": [
          "obj_c2_246_01_synthesize_c2_sec02_philology",
          "obj_c2_246_04_author_capstone_philological_monograph",
          "obj_c2_246_05_defend_doctoral_dissertation_middle_mongolian"
        ],
        "objectivesReviewed": [
          "obj_c2_238_01_master_secret_history_philology",
          "obj_c2_239_01_master_classical_epic_syntax",
          "obj_c2_240_01_master_archaic_case_morphology",
          "obj_c2_241_01_master_alan_qoa_parable",
          "obj_c2_242_01_master_anda_sworn_brotherhood",
          "obj_c2_243_01_master_great_yasa_jurisprudence",
          "obj_c2_244_01_master_omni_register_agility",
          "obj_c2_245_01_master_stele_of_yisungge"
        ],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c2_classical_epic_syntax_secret_history",
          "gram_c2_archaic_case_morphology_secret_history",
          "gram_c2_legal_constitutional_clause_architecture",
          "gram_c2_seamless_register_navigating"
        ],
        "grammarReviewed": [
          "gram_c2_dialectal_morphosyntax_awareness",
          "gram_c2_literary_polyphony_and_indirect_interior_monologue"
        ],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phon_c2_05_middle_mongolian_phonology_reconstruction"],
        "phonologyReviewed": ["phon_c2_01_extreme_vowel_reduction_and_syncope"],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": [
          "comm_c2_08_omni_register_agility",
          "comm_c2_10_secret_history_philological_reading",
          "comm_c2_07_constitutional_court_parsing"
        ],
        "communicativeFunctionsReviewed": [
          "comm_c2_15_creative_mastery_authorial_voice",
          "comm_c2_02_rapid_dialogue_and_turn_taking"
        ],
        "newProductiveLemmaTarget": 0,
        "newReceptiveLemmaTarget": 0,
        "newProductiveExpressionTarget": 0,
        "newReceptiveExpressionTarget": 0,
        "lexicalDomains": ["lex_c2_the_secret_history_middle_mongolian"],
        "previousVocabularyReused": ["эх бичиг судлал", "дундад зууны монгол хэл", "Их Засаг", "Есөнхэй", "найруулгын чадвар"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "comprehensive Section 02 mastery review",
        "pragmaticTarget": "operational permanence across 13th-century epigraphy and philology",
        "prerequisiteLessonIds": [
          "les_c2_246_01_c2_sec02_capstone_philological_monograph_intro",
          "les_c2_246_02_c2_sec02_capstone_untranslated_manuscript_reading",
          "les_c2_246_03_c2_sec02_capstone_academician_colloquium_listening",
          "les_c2_246_04_c2_sec02_capstone_critical_commentary_monograph_writing",
          "les_c2_246_05_c2_sec02_capstone_doctoral_dissertation_defense_spoken"
        ],
        "reviewsLessonIds": ["les_c2_237_06_c2_sec01_culminating_operational_synthesis"],
        "reviewsUnitIds": ["unit_c2_237_contemporary_literature_capstone_sa"],
        "reviewReason": "Confirms holistic mastery across both Section 01 and Section 02 before initiating Section 03.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Verifies active control over all Section 02 competencies with zero hesitation or regression",
          "Demonstrates immediate synthesis of 13th-century philology, legal codes, and register control"
        ],
        "masteryEvidence": "Achieves 100% mastery score across comprehensive Section 02 operational assessment battery.",
        "recommendedExerciseModalities": ["stylistic_transformation", "discourse_analysis"]
      }
    ])

    return lessons
