#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Curated Pre-A1 and A1 Lexical Database for Lexicon Generator
"""

PRE_A1_VOCAB = [
    # Alphabet and literacy roots
    ("үсэг", "letter, alphabet character", "noun", "neutral", "nominal"),
    ("эгшиг", "vowel", "noun", "neutral", "nominal"),
    ("гийгүүлэгч", "consonant", "noun", "neutral", "nominal"),
    ("авиа", "sound, phoneme", "noun", "neutral", "nominal"),
    ("үе", "syllable, joint", "noun", "neutral", "nominal"),
    ("үг", "word, speech", "noun", "neutral", "nominal"),
    ("унших", "to read", "verb", "neutral", "verbal_infinitive"),
    ("бичих", "to write", "verb", "neutral", "verbal_infinitive"),
    ("сонсох", "to listen", "verb", "neutral", "verbal_infinitive"),
    ("хэлэх", "to say, speak", "verb", "neutral", "verbal_infinitive"),
    ("хараарай", "look (polite request)", "verb", "neutral", "imperative_polite"),
    ("суурай", "sit (polite request)", "verb", "neutral", "imperative_polite"),
    ("ном", "book", "noun", "neutral", "nominal"),
    ("дэвтэр", "notebook", "noun", "neutral", "nominal"),
    ("үзэг", "pen", "noun", "neutral", "nominal"),
    ("харандаа", "pencil", "noun", "neutral", "nominal"),
    ("ширээ", "table, desk", "noun", "neutral", "nominal"),
    ("сандал", "chair", "noun", "neutral", "nominal"),
    ("самбар", "blackboard, noticeboard", "noun", "neutral", "nominal"),
    ("анги", "classroom, class, grade", "noun", "neutral", "nominal"),
    ("сургууль", "school", "noun", "neutral", "nominal"),
    ("багш", "teacher", "noun", "neutral", "nominal"),
    ("сурагч", "student, pupil", "noun", "neutral", "nominal"),
    ("оюутан", "university student", "noun", "neutral", "nominal"),
    ("нэр", "name", "noun", "neutral", "nominal"),
    ("овог", "clan, surname", "noun", "neutral", "nominal"),
    ("хэн", "who", "pronoun", "neutral", "interrogative"),
    ("юу", "what", "pronoun", "neutral", "interrogative"),
    ("хаана", "where", "adverb", "neutral", "interrogative"),
    ("хэзээ", "when", "adverb", "neutral", "interrogative"),
    ("ямар", "what kind of, which", "adjective", "neutral", "interrogative"),
    ("хэд", "how many, several", "numeral", "neutral", "interrogative"),
    ("тийм", "yes, so", "adverb", "neutral", "affirmative"),
    ("үгүй", "no, not", "adverb", "neutral", "negative"),
    ("биш", "not (copular negation)", "particle", "neutral", "negative"),
    ("байна", "is, exists", "verb", "neutral", "copula"),
    ("байхгүй", "is not, does not exist", "adjective", "neutral", "negative_existential"),
    ("сайн", "good, well", "adjective", "neutral", "qualitative"),
    ("муу", "bad, poor", "adjective", "neutral", "qualitative"),
    ("том", "big, large", "adjective", "neutral", "qualitative"),
    ("жижиг", "small, little", "adjective", "neutral", "qualitative"),
    ("шинэ", "new", "adjective", "neutral", "qualitative"),
    ("хуучин", "old (objects)", "adjective", "neutral", "qualitative"),
    ("нэг", "one (1)", "numeral", "neutral", "cardinal"),
    ("хоёр", "two (2)", "numeral", "neutral", "cardinal"),
    ("гурав", "three (3)", "numeral", "neutral", "cardinal"),
    ("дөрөв", "four (4)", "numeral", "neutral", "cardinal"),
    ("тав", "five (5)", "numeral", "neutral", "cardinal"),
    ("зургаа", "six (6)", "numeral", "neutral", "cardinal"),
    ("долоо", "seven (7)", "numeral", "neutral", "cardinal"),
    ("найм", "eight (8)", "numeral", "neutral", "cardinal"),
    ("ес", "nine (9)", "numeral", "neutral", "cardinal"),
    ("арав", "ten (10)", "numeral", "neutral", "cardinal"),
    ("тэг", "zero (0)", "numeral", "neutral", "cardinal"),
    ("би", "I (1st person singular)", "pronoun", "neutral", "personal"),
    ("чи", "you (informal singular)", "pronoun", "informal", "personal"),
    ("та", "you (polite/formal singular or plural)", "pronoun", "formal", "personal"),
    ("тэр", "he, she, it, that", "pronoun", "neutral", "demonstrative"),
    ("бид", "we (exclusive)", "pronoun", "neutral", "personal"),
    ("бид нар", "we (plural)", "pronoun", "neutral", "personal"),
    ("та нар", "you (plural polite)", "pronoun", "formal", "personal"),
    ("тэд", "they, those", "pronoun", "neutral", "demonstrative"),
    ("энэ", "this", "pronoun", "neutral", "demonstrative"),
    ("эдгээр", "these", "pronoun", "neutral", "demonstrative"),
    ("тэдгээр", "those", "pronoun", "neutral", "demonstrative"),
    ("өглөө", "morning", "noun", "neutral", "temporal"),
    ("өдөр", "day, afternoon", "noun", "neutral", "temporal"),
    ("орой", "evening", "noun", "neutral", "temporal"),
    ("шөнө", "night", "noun", "neutral", "temporal"),
    ("өнөөдөр", "today", "noun", "neutral", "temporal"),
    ("маргааш", "tomorrow", "noun", "neutral", "temporal"),
    ("өчигдөр", "yesterday", "noun", "neutral", "temporal"),
    ("цаг", "hour, clock, time, o'clock", "noun", "neutral", "temporal"),
    ("минут", "minute", "noun", "neutral", "temporal"),
    ("хагас", "half", "noun", "neutral", "quantitative"),
    ("аав", "father, dad", "noun", "neutral", "kinship"),
    ("ээж", "mother, mom", "noun", "neutral", "kinship"),
    ("хүү", "son, boy", "noun", "neutral", "kinship"),
    ("охин", "daughter, girl", "noun", "neutral", "kinship"),
    ("ах", "older brother", "noun", "neutral", "kinship"),
    ("эгч", "older sister", "noun", "neutral", "kinship"),
    ("дүү", "younger sibling", "noun", "neutral", "kinship"),
    ("гэр", "ger, home, house, yurt", "noun", "neutral", "domestic"),
    ("хаалга", "door, entrance", "noun", "neutral", "domestic"),
    ("цонх", "window", "noun", "neutral", "domestic"),
    ("өрөө", "room", "noun", "neutral", "domestic"),
    ("ор", "bed", "noun", "neutral", "domestic"),
    ("зураг", "picture, photograph, map", "noun", "neutral", "domestic"),
    ("ус", "water", "noun", "neutral", "domestic"),
    ("цай", "tea", "noun", "neutral", "domestic"),
    ("сүү", "milk", "noun", "neutral", "domestic"),
    ("талх", "bread", "noun", "neutral", "domestic"),
    ("мах", "meat", "noun", "neutral", "domestic"),
    ("бууз", "buuz (steamed meat dumplings)", "noun", "neutral", "culinary"),
    ("хуушуур", "khuushuur (fried meat pastry)", "noun", "neutral", "culinary"),
    ("цуйван", "tsuivan (fried noodle dish)", "noun", "neutral", "culinary"),
    ("шөл", "soup, broth", "noun", "neutral", "culinary"),
    ("хоол", "food, meal", "noun", "neutral", "culinary"),
    ("давс", "salt", "noun", "neutral", "culinary"),
    ("чихэр", "sugar, candy, sweets", "noun", "neutral", "culinary"),
    ("аяга", "cup, bowl", "noun", "neutral", "domestic"),
    ("халбага", "spoon", "noun", "neutral", "domestic"),
    ("сэрээ", "fork", "noun", "neutral", "domestic"),
    ("хутга", "knife", "noun", "neutral", "domestic"),
    ("таваг", "plate, dish", "noun", "neutral", "domestic"),
    ("дэлгүүр", "store, shop", "noun", "neutral", "commerce"),
    ("зах", "market, bazaar, edge", "noun", "neutral", "commerce"),
    ("мөнгө", "money, silver", "noun", "neutral", "commerce"),
    ("төгрөг", "tugrik (Mongolian currency)", "noun", "neutral", "commerce"),
    ("үнэ", "price", "noun", "neutral", "commerce"),
    ("үнэтэй", "expensive", "adjective", "neutral", "commerce"),
    ("хямд", "cheap, inexpensive", "adjective", "neutral", "commerce"),
    ("гудамж", "street", "noun", "neutral", "urban"),
    ("хот", "city, town", "noun", "neutral", "urban"),
    ("хөдөө", "countryside, rural steppe", "noun", "neutral", "geography"),
    ("уул", "mountain", "noun", "neutral", "geography"),
    ("гол", "river", "noun", "neutral", "geography"),
    ("нуур", "lake", "noun", "neutral", "geography"),
    ("мод", "tree, wood", "noun", "neutral", "nature"),
    ("цэцэг", "flower", "noun", "neutral", "nature"),
    ("өвс", "grass, hay", "noun", "neutral", "nature"),
    ("мал", "livestock, animal", "noun", "neutral", "pastoral"),
    ("морь", "horse", "noun", "neutral", "pastoral"),
    ("хонь", "sheep", "noun", "neutral", "pastoral"),
    ("ямаа", "goat", "noun", "neutral", "pastoral"),
    ("үхэр", "cattle, cow, ox", "noun", "neutral", "pastoral"),
    ("тэмээ", "camel", "noun", "neutral", "pastoral"),
    ("нохой", "dog", "noun", "neutral", "domestic"),
    ("муур", "cat", "noun", "neutral", "domestic"),
    ("нар", "sun", "noun", "neutral", "astronomy"),
    ("сар", "moon, month", "noun", "neutral", "astronomy"),
    ("од", "star", "noun", "neutral", "astronomy"),
    ("тэнгэр", "sky, heaven", "noun", "neutral", "astronomy"),
    ("үүлэ", "cloud", "noun", "neutral", "weather"),
    ("бороо", "rain", "noun", "neutral", "weather"),
    ("цас", "snow", "noun", "neutral", "weather"),
    ("салхи", "wind", "noun", "neutral", "weather"),
    ("хүйтэн", "cold", "adjective", "neutral", "weather"),
    ("халуун", "hot, warm", "adjective", "neutral", "weather"),
    ("дулаан", "mild, warm", "adjective", "neutral", "weather"),
    ("сэрүүн", "cool, fresh", "adjective", "neutral", "weather"),
]

def get_pre_a1_vocab():
    return PRE_A1_VOCAB
