#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Curated Vocabulary Bank for Lexicon Construction
Provides authentic vocabulary across CEFR levels Pre-A1 through C2.
"""

# Categorized seed dictionaries with Cyrillic lemma, English gloss, part of speech, register, usage notes, and morphology
SEED_DATA = {
    'Pre-A1': [
        ('үсэг', 'letter, alphabet character', 'noun', 'neutral', 'Foundational literacy letterform', 'nominal'),
        ('эгшиг', 'vowel', 'noun', 'neutral', 'Cardinal vowel category', 'nominal'),
        ('гийгүүлэгч', 'consonant', 'noun', 'neutral', 'Consonantal sound category', 'nominal'),
        ('авиа', 'speech sound, phone', 'noun', 'neutral', 'Spoken sound unit', 'nominal'),
        ('үе', 'syllable', 'noun', 'neutral', 'Syllabic division', 'nominal'),
        ('үг', 'word', 'noun', 'neutral', 'Lexical word token', 'nominal'),
        ('ном', 'book', 'noun', 'neutral', 'Reading material', 'nominal'),
        ('дэвтэр', 'notebook', 'noun', 'neutral', 'Classroom stationery', 'nominal'),
        ('үзэг', 'pen', 'noun', 'neutral', 'Writing instrument', 'nominal'),
        ('харандаа', 'pencil', 'noun', 'neutral', 'Drawing instrument', 'nominal'),
        ('ширээ', 'desk, table', 'noun', 'neutral', 'Classroom furniture', 'nominal'),
        ('сандал', 'chair', 'noun', 'neutral', 'Classroom furniture', 'nominal'),
        ('самбар', 'blackboard', 'noun', 'neutral', 'Classroom board', 'nominal'),
        ('багш', 'teacher', 'noun', 'neutral', 'Instructor', 'nominal'),
        ('сурагч', 'pupil, student', 'noun', 'neutral', 'Learner', 'nominal'),
        ('сургууль', 'school', 'noun', 'neutral', 'Educational institution', 'nominal'),
        ('анги', 'classroom, grade', 'noun', 'neutral', 'Study room', 'nominal'),
        ('нэр', 'name', 'noun', 'neutral', 'Personal identification', 'nominal'),
        ('овог', 'surname, clan name', 'noun', 'neutral', 'Family name', 'nominal'),
        ('унших', 'to read', 'verb', 'neutral', 'Literacy action', 'verbal_infinitive'),
        ('бичих', 'to write', 'verb', 'neutral', 'Orthographic action', 'verbal_infinitive'),
        ('сонсох', 'to listen', 'verb', 'neutral', 'Auditory comprehension', 'verbal_infinitive'),
        ('хэлэх', 'to say, speak', 'verb', 'neutral', 'Spoken production', 'verbal_infinitive'),
        ('хараарай', 'look (polite)', 'verb', 'neutral', 'Polite visual instruction', 'imperative_polite'),
        ('суугаарай', 'sit down (polite)', 'verb', 'neutral', 'Polite posture instruction', 'imperative_polite'),
        ('би', 'I (1st person singular)', 'pronoun', 'neutral', 'Subject pronoun', 'personal_pronoun'),
        ('чи', 'you (singular informal)', 'pronoun', 'informal', 'Direct address', 'personal_pronoun'),
        ('та', 'you (singular formal/polite)', 'pronoun', 'formal', 'Respectful address', 'personal_pronoun'),
        ('тэр', 'he, she, it, that', 'pronoun', 'neutral', 'Third-person demonstrative', 'demonstrative_pronoun'),
        ('энэ', 'this', 'pronoun', 'neutral', 'Proximal demonstrative', 'demonstrative_pronoun'),
        ('тийм', 'yes, that is so', 'adverb', 'neutral', 'Affirmative response', 'adverbial'),
        ('үгүй', 'no', 'adverb', 'neutral', 'Negative response', 'adverbial'),
        ('биш', 'not (equative copula negation)', 'particle', 'neutral', 'Copular negative', 'particle'),
        ('байна', 'is, exists', 'verb', 'neutral', 'Present copula / existential', 'copula'),
        ('байхгүй', 'is not, absent', 'adjective', 'neutral', 'Negative existential', 'adjectival'),
        ('сайн', 'good, well', 'adjective', 'neutral', 'Positive quality', 'adjectival'),
        ('муу', 'bad, poor', 'adjective', 'neutral', 'Negative quality', 'adjectival'),
        ('том', 'big, large', 'adjective', 'neutral', 'Physical dimension', 'adjectival'),
        ('жижиг', 'small, little', 'adjective', 'neutral', 'Physical dimension', 'adjectival'),
        ('нэг', 'one (1)', 'numeral', 'neutral', 'Cardinal digit', 'cardinal_numeral'),
        ('хоёр', 'two (2)', 'numeral', 'neutral', 'Cardinal digit', 'cardinal_numeral'),
        ('гурав', 'three (3)', 'numeral', 'neutral', 'Cardinal digit', 'cardinal_numeral'),
        ('дөрөв', 'four (4)', 'numeral', 'neutral', 'Cardinal digit', 'cardinal_numeral'),
        ('тав', 'five (5)', 'numeral', 'neutral', 'Cardinal digit', 'cardinal_numeral'),
        ('зургаа', 'six (6)', 'numeral', 'neutral', 'Cardinal digit', 'cardinal_numeral'),
        ('долоо', 'seven (7)', 'numeral', 'neutral', 'Cardinal digit', 'cardinal_numeral'),
        ('найм', 'eight (8)', 'numeral', 'neutral', 'Cardinal digit', 'cardinal_numeral'),
        ('ес', 'nine (9)', 'numeral', 'neutral', 'Cardinal digit', 'cardinal_numeral'),
        ('арав', 'ten (10)', 'numeral', 'neutral', 'Cardinal digit', 'cardinal_numeral'),
        ('тэг', 'zero (0)', 'numeral', 'neutral', 'Cardinal digit', 'cardinal_numeral'),
        ('гэр', 'home, ger, yurt', 'noun', 'neutral', 'Nomadic dwelling', 'nominal'),
        ('өрөө', 'room', 'noun', 'neutral', 'Enclosed space', 'nominal'),
        ('хаалга', 'door', 'noun', 'neutral', 'Entrance barrier', 'nominal'),
        ('цонх', 'window', 'noun', 'neutral', 'Light opening', 'nominal'),
        ('ус', 'water', 'noun', 'neutral', 'Vital liquid', 'nominal'),
        ('цай', 'tea', 'noun', 'neutral', 'Steppe beverage', 'nominal'),
        ('сүү', 'milk', 'noun', 'neutral', 'Dairy drink', 'nominal'),
        ('талх', 'bread', 'noun', 'neutral', 'Staple bakery food', 'nominal'),
        ('мах', 'meat', 'noun', 'neutral', 'Staple protein', 'nominal'),
        ('хоол', 'meal, food', 'noun', 'neutral', 'Prepared nourishment', 'nominal'),
        ('аав', 'father', 'noun', 'neutral', 'Paternal parent', 'nominal'),
        ('ээж', 'mother', 'noun', 'neutral', 'Maternal parent', 'nominal'),
        ('хүү', 'son, boy', 'noun', 'neutral', 'Male offspring', 'nominal'),
        ('охин', 'daughter, girl', 'noun', 'neutral', 'Female offspring', 'nominal'),
        ('ах', 'older brother', 'noun', 'neutral', 'Senior male sibling', 'nominal'),
        ('эгч', 'older sister', 'noun', 'neutral', 'Senior female sibling', 'nominal'),
        ('дүү', 'younger sibling', 'noun', 'neutral', 'Junior sibling', 'nominal'),
        ('морь', 'horse', 'noun', 'neutral', 'Steppe equine', 'nominal'),
        ('хонь', 'sheep', 'noun', 'neutral', 'Pastoral ovine', 'nominal'),
        ('ямаа', 'goat', 'noun', 'neutral', 'Pastoral caprine', 'nominal'),
        ('үхэр', 'cow, cattle', 'noun', 'neutral', 'Pastoral bovine', 'nominal'),
        ('тэмээ', 'camel', 'noun', 'neutral', 'Desert camelid', 'nominal'),
        ('нохой', 'dog', 'noun', 'neutral', 'Domestic canine', 'nominal'),
        ('муур', 'cat', 'noun', 'neutral', 'Domestic feline', 'nominal'),
        ('нар', 'sun', 'noun', 'neutral', 'Solar body', 'nominal'),
        ('сар', 'moon, month', 'noun', 'neutral', 'Lunar body / time unit', 'nominal'),
        ('од', 'star', 'noun', 'neutral', 'Celestial star', 'nominal'),
        ('тэнгэр', 'sky, heaven', 'noun', 'neutral', 'Firmament', 'nominal'),
        ('бороо', 'rain', 'noun', 'neutral', 'Precipitation', 'nominal'),
        ('цас', 'snow', 'noun', 'neutral', 'Frozen precipitation', 'nominal'),
        ('салхи', 'wind', 'noun', 'neutral', 'Air current', 'nominal'),
        ('хүйтэн', 'cold', 'adjective', 'neutral', 'Low temperature', 'adjectival'),
        ('халуун', 'hot', 'adjective', 'neutral', 'High temperature', 'adjectival'),
        ('хот', 'city, town', 'noun', 'neutral', 'Urban center', 'nominal'),
        ('хөдөө', 'countryside, steppe', 'noun', 'neutral', 'Rural pastoral area', 'nominal'),
        ('уул', 'mountain', 'noun', 'neutral', 'Geological elevation', 'nominal'),
        ('гол', 'river', 'noun', 'neutral', 'Watercourse', 'nominal'),
        ('нуур', 'lake', 'noun', 'neutral', 'Water reservoir', 'nominal'),
        ('мод', 'tree, wood', 'noun', 'neutral', 'Forest timber', 'nominal'),
        ('өвс', 'grass', 'noun', 'neutral', 'Steppe vegetation', 'nominal'),
        ('цэцэг', 'flower', 'noun', 'neutral', 'Blossom', 'nominal'),
        ('дэлгүүр', 'shop, store', 'noun', 'neutral', 'Retail location', 'nominal'),
        ('зах', 'open market, border', 'noun', 'neutral', 'Trade market', 'nominal'),
        ('үнэ', 'price', 'noun', 'neutral', 'Monetary cost', 'nominal'),
        ('мөнгө', 'money, silver', 'noun', 'neutral', 'Currency', 'nominal'),
        ('төгрөг', 'tugrik', 'noun', 'neutral', 'Mongolian currency unit', 'nominal'),
        ('цаг', 'hour, clock, time', 'noun', 'neutral', 'Time unit / device', 'nominal'),
        ('минут', 'minute', 'noun', 'neutral', 'Time division', 'nominal'),
        ('өнөөдөр', 'today', 'noun', 'neutral', 'Current day', 'temporal_noun'),
        ('маргааш', 'tomorrow', 'noun', 'neutral', 'Following day', 'temporal_noun'),
        ('өчигдөр', 'yesterday', 'noun', 'neutral', 'Preceding day', 'temporal_noun'),
        ('өглөө', 'morning', 'noun', 'neutral', 'Early day period', 'temporal_noun'),
        ('өдөр', 'day, midday', 'noun', 'neutral', 'Daytime period', 'temporal_noun'),
        ('орой', 'evening', 'noun', 'neutral', 'Late day period', 'temporal_noun'),
        ('шөнө', 'night', 'noun', 'neutral', 'Dark hours', 'temporal_noun'),
        ('баярлалаа', 'thank you', 'interjection', 'neutral', 'Gratitude expression', 'formula'),
        ('уучлаарай', 'sorry, excuse me', 'interjection', 'neutral', 'Apology expression', 'formula'),
        ('баяртай', 'goodbye', 'interjection', 'neutral', 'Departure formula', 'formula'),
        ('амар', 'rest, peace, calm', 'noun', 'neutral', 'State of tranquility', 'nominal'),
        ('мэнд', 'well-being, health', 'noun', 'neutral', 'Greeting health state', 'nominal'),
        ('хэн', 'who', 'pronoun', 'neutral', 'Personal interrogative', 'interrogative_pronoun'),
        ('юу', 'what', 'pronoun', 'neutral', 'Inanimate interrogative', 'interrogative_pronoun'),
        ('хаана', 'where', 'adverb', 'neutral', 'Locative interrogative', 'interrogative_adverb'),
        ('хэзээ', 'when', 'adverb', 'neutral', 'Temporal interrogative', 'interrogative_adverb'),
        ('яагаад', 'why', 'adverb', 'neutral', 'Causal interrogative', 'interrogative_adverb'),
        ('ямар', 'what kind, which', 'adjective', 'neutral', 'Qualitative interrogative', 'interrogative_adjective'),
        ('хэд', 'how many, how much', 'numeral', 'neutral', 'Quantitative interrogative', 'interrogative_numeral'),
        ('шинэ', 'new', 'adjective', 'neutral', 'Recent origin', 'adjectival'),
        ('хуучин', 'old (of things)', 'adjective', 'neutral', 'Prior usage', 'adjectival'),
        ('хямд', 'cheap, inexpensive', 'adjective', 'neutral', 'Low cost', 'adjectival'),
        ('үнэтэй', 'expensive', 'adjective', 'neutral', 'High cost', 'adjectival'),
        ('дулаан', 'warm', 'adjective', 'neutral', 'Mild temperature', 'adjectival'),
        ('сэрүүн', 'cool, chilly', 'adjective', 'neutral', 'Brisk temperature', 'adjectival'),
        ('цэвэрхэн', 'clean, neat', 'adjective', 'neutral', 'Tidy state', 'adjectival'),
        ('бохир', 'dirty, soiled', 'adjective', 'neutral', 'Untidy state', 'adjectival'),
        ('ойрхон', 'near, close', 'adverb', 'neutral', 'Short distance', 'adverbial'),
        ('хол', 'far, distant', 'adverb', 'neutral', 'Long distance', 'adverbial'),
        ('хурдан', 'fast, quick', 'adverb', 'neutral', 'High speed', 'adverbial'),
        ('удаан', 'slow, lengthy', 'adverb', 'neutral', 'Low speed', 'adverbial'),
        ('гудамж', 'street', 'noun', 'neutral', 'Urban roadway', 'nominal'),
        ('зам', 'road, way, journey', 'noun', 'neutral', 'Travel path', 'nominal'),
        ('буудал', 'stop, station, hotel', 'noun', 'neutral', 'Transit stop', 'nominal'),
        ('автобус', 'bus', 'noun', 'neutral', 'Transit vehicle', 'nominal'),
        ('машин', 'car, vehicle', 'noun', 'neutral', 'Automobile', 'nominal'),
        ('онгоц', 'airplane, boat', 'noun', 'neutral', 'Aviation vehicle', 'nominal'),
        ('галт тэрэг', 'train', 'noun', 'neutral', 'Railway transit', 'compound_noun'),
        ('эмнэлэг', 'hospital, clinic', 'noun', 'neutral', 'Medical facility', 'nominal'),
        ('эмийн сан', 'pharmacy', 'noun', 'neutral', 'Medicine shop', 'compound_noun'),
        ('цагдаа', 'police', 'noun', 'neutral', 'Law enforcement', 'nominal'),
        ('шуудан', 'post, mail', 'noun', 'neutral', 'Postal service', 'nominal'),
        ('банк', 'bank', 'noun', 'neutral', 'Financial institution', 'nominal'),
        ('зочид буудал', 'hotel', 'noun', 'neutral', 'Lodging facility', 'compound_noun'),
        ('ресторан', 'restaurant', 'noun', 'neutral', 'Dining venue', 'nominal'),
        ('цайны газар', 'canteen, café', 'noun', 'neutral', 'Eatery', 'compound_noun'),
        ('хоолны газар', 'eatery, diner', 'noun', 'neutral', 'Dining location', 'compound_noun'),
        ('баяр', 'holiday, celebration, joy', 'noun', 'neutral', 'Festivity', 'nominal'),
        ('ажил', 'work, job, duty', 'noun', 'neutral', 'Employment task', 'nominal'),
        ('амралт', 'vacation, rest', 'noun', 'neutral', 'Leisure period', 'nominal'),
        ('хичээл', 'lesson, class', 'noun', 'neutral', 'Academic session', 'nominal'),
        ('найз', 'friend', 'noun', 'informal', 'Companion', 'nominal'),
        ('нөхөр', 'husband, friend, comrade', 'noun', 'neutral', 'Spouse or peer', 'nominal'),
        ('эхнэр', 'wife', 'noun', 'neutral', 'Female spouse', 'nominal'),
        ('хүүхэд', 'child, children', 'noun', 'neutral', 'Young person', 'nominal'),
        ('хүн', 'person, human', 'noun', 'neutral', 'Human individual', 'nominal'),
        ('хүмүүс', 'people', 'noun', 'neutral', 'Plural humans', 'nominal'),
        ('аймаг', 'aimag (province)', 'noun', 'neutral', 'Administrative division', 'nominal'),
        ('сум', 'soum (district)', 'noun', 'neutral', 'Sub-provincial district', 'nominal'),
        ('баг', 'bagh (sub-district), team', 'noun', 'neutral', 'Local community unit', 'nominal'),
        ('улс', 'state, country, nation', 'noun', 'neutral', 'Sovereign nation', 'nominal'),
        ('эх орон', 'homeland, motherland', 'noun', 'neutral', 'Native land', 'compound_noun'),
        ('нийслэл', 'capital city', 'noun', 'neutral', 'Administrative capital', 'nominal'),
        ('хэл', 'language, tongue', 'noun', 'neutral', 'Linguistic system', 'nominal'),
        ('соёл', 'culture', 'noun', 'neutral', 'Tradition and arts', 'nominal'),
        ('түүх', 'history, story', 'noun', 'neutral', 'Past chronology', 'nominal'),
        ('ёс заншил', 'custom, tradition', 'noun', 'neutral', 'Social conventions', 'compound_noun'),
    ]
}

def get_seed_data():
    return SEED_DATA
