# -*- coding: utf-8 -*-
"""Authoring Units 182-186 of Section 03 and validating full section."""
import json
from append_sec03_part2 import sec03_lessons

# UNIT 182: Sensory Appearance Modals: Suffixes -х шинжтэй / -х шиг байна (4 lessons)
# Budget: PL=26, RL=22, PE=8, RE=5
sec03_lessons.extend([
    {
        "lessonId": "les_b2_182_01_sensory_appearance_modals_syntax_intro",
        "unitId": "unit_b2_182_sensory_appearance_modals_suffixes_",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 1,
        "title": "Morphosyntax: Sensory Appearance Modals '-х шинжтэй', '-х янзтай' & '-х шиг байна'",
        "lessonType": "grammar_introduction",
        "primaryPurpose": "Introduce the syntactic formation, evidential semantics, and perceptual criteria of sensory appearance modals (-х шинжтэй, -х янзтай, -х шиг байна) expressing direct auditory or visual perceptual inference ('it appears to... / sounds as if...').",
        "communicativeOutcome": "Formulate precise perceptual assessments of musical instrument condition and performance timbre based on immediate acoustic and visual evidence.",
        "objectivesIntroduced": ["obj_b2_182_01_master_sensory_appearance_modals"],
        "objectivesPracticed": [],
        "objectivesReviewed": ["obj_b2_181_01_master_epistemic_stance_biz"],
        "grammarIntroduced": ["gram_b2_epistemic_appearance_shig_baiana_yanzytai"],
        "grammarPracticed": ["gram_a1_verb_aspect_progressive_j_baina", "gram_b1_epistemic_probability_bololtoi_magadgui"],
        "grammarReviewed": ["gram_b2_epistemic_stance_biz_baih"],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_discourse_chunking_cadence"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_18_critiquing_artistic_exhibitions"],
        "communicativeFunctionsReviewed": ["comm_b2_02_academic_essay_concessions"],
        "newProductiveLemmaTarget": 7,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_performing_arts_music_folklore"],
        "previousVocabularyReused": ["шинжтэй", "янзтай", "шиг байна", "харагдах", "сонсогдох", "мэдрэгдэх"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Draft 6 analytical observations evaluating aged wood tension and string fatigue using '-х шинжтэй' and '-х шиг байна'.",
        "spokenProductionObjective": "",
        "registerTarget": "aesthetic evaluative",
        "pragmaticTarget": "sensory evidential judgment",
        "prerequisiteLessonIds": ["les_b2_181_04_defending_historical_performance_speech"],
        "reviewsLessonIds": ["les_b2_181_01_epistemic_stance_biz_baih_syntax_intro"],
        "reviewsUnitIds": ["unit_b2_181_epistemic_stance_presumption_the_ma"],
        "reviewReason": "Integrates epistemic presumption markers with sensory-perceptual appearance modals.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Selects correctly between external visual evidence ('-х шинжтэй') and general sensory perception ('-х шиг байна')",
            "Attaches appearance suffixes to verbal nouns (-х) without morphophonological error"
        ],
        "masteryEvidence": "Accurately completes 8 sentence transformation tasks evaluating musical timbre and instrument wear using sensory modals.",
        "recommendedExerciseModalities": ["word_transformation", "sentence_reordering"]
    },
    {
        "lessonId": "les_b2_182_02_museum_conservator_instrument_inspection_reading",
        "unitId": "unit_b2_182_sensory_appearance_modals_suffixes_",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 2,
        "title": "Conservation Reading: Material Decay & Tonal Deterioration in Antique Morin Khuurs",
        "lessonType": "reading",
        "primaryPurpose": "Parse an expert museum conservation report evaluating wood desiccation, animal glue degradation, and soundpost shifting in 19th-century instruments.",
        "communicativeOutcome": "Extract conservation diagnoses, structural risk indices, and restoration recommendations from a 360-word technical report.",
        "objectivesIntroduced": ["obj_b2_182_02_read_conservation_reports"],
        "objectivesPracticed": ["obj_b2_182_01_master_sensory_appearance_modals"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_epistemic_appearance_shig_baiana_yanzytai", "gram_b2_information_structure_exclusive_focus_l"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_18_critiquing_artistic_exhibitions"],
        "communicativeFunctionsReviewed": ["comm_b2_11_summarizing_complex_articles"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_performing_arts_music_folklore"],
        "previousVocabularyReused": ["музей", "хадгалалт", "хамгаалалт", "хагарах", "цуурах", "цавуу"],
        "readingObjective": "Read a 360-word conservation dossier and extract 3 diagnostic evaluations formulated with '-х шинжтэй'.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "scientific conservation",
        "pragmaticTarget": "diagnostic precision",
        "prerequisiteLessonIds": ["les_b2_182_01_sensory_appearance_modals_syntax_intro"],
        "reviewsLessonIds": ["les_b2_177_01_morin_khuur_acoustic_engineering_reading"],
        "reviewsUnitIds": ["unit_b2_177_the_morin_khuur_acoustic_engineerin"],
        "reviewReason": "Re-engages organological physical knowledge to evaluate centuries of material conservation and wear.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Identifies specific material signs of lacquer micro-fracturing and soundboard warping",
            "Distinguishes surface aesthetic patina from structural acoustic failure"
        ],
        "masteryEvidence": "Completes a condition assessment rubric evaluating 3 museum artifacts based on textual evidence.",
        "recommendedExerciseModalities": ["source_comparison", "claim_evidence_matching"]
    },
    {
        "lessonId": "les_b2_182_03_evaluating_tonal_authenticity_spoken",
        "unitId": "unit_b2_182_sensory_appearance_modals_suffixes_",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 3,
        "title": "Spoken Critique: Evaluating Tonal Authenticity & Resonant Decay in Historic Fiddles",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver an oral appraisal of an antique instrument's acoustic response, critiquing overtone richness, string buzz, and soundbox damping for museum acquisitions.",
        "communicativeOutcome": "Deliver a 3-minute professional acoustic appraisal utilizing sensory appearance modals to express nuanced aesthetic impressions.",
        "objectivesIntroduced": ["obj_b2_182_03_deliver_acoustic_appraisal"],
        "objectivesPracticed": ["obj_b2_182_01_master_sensory_appearance_modals", "obj_b2_182_02_read_conservation_reports"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_epistemic_appearance_shig_baiana_yanzytai", "gram_a1_verb_aspect_progressive_j_baina"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_formal_presentation_cadence", "phono_b2_topic_prominence_intonation"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_18_critiquing_artistic_exhibitions"],
        "communicativeFunctionsReviewed": ["comm_b2_07_delivering_prepared_presentations"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_b2_performing_arts_music_folklore"],
        "previousVocabularyReused": ["үнэлгээ", "өнгө аяс", "хүчдэл", "сонсголонтой", "шалгах", "шинжээч"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Deliver a 3-minute oral appraisal advising a museum acquisitions board on the acoustic condition of an antique horsehead fiddle.",
        "registerTarget": "professional consultative",
        "pragmaticTarget": "expert appraisal",
        "prerequisiteLessonIds": ["les_b2_182_02_museum_conservator_instrument_inspection_reading"],
        "reviewsLessonIds": ["les_b2_177_03_jonon_khar_legend_acoustic_mythology_spoken"],
        "reviewsUnitIds": ["unit_b2_177_the_morin_khuur_acoustic_engineerin"],
        "reviewReason": "Synthesizes cultural narrative delivery with technical sensory acoustic appraisal.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide model audio of master appraiser delivering expert acoustic evaluation of bowed instrument.",
        "successCriteria": [
            "Integrates '-х шинжтэй', '-х янзтай', and '-х шиг байна' naturally into fluid spoken evaluation",
            "Maintains professional evaluative detachment while describing subjective acoustic qualities"
        ],
        "masteryEvidence": "Speech recording reflects consummate expert appraisal delivery and seamless sensory modal command.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
    },
    {
        "lessonId": "les_b2_182_04_artifact_condition_report_writing",
        "unitId": "unit_b2_182_sensory_appearance_modals_suffixes_",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 4,
        "title": "Technical Writing: Formal Museum Artifact Condition & Acoustic Integrity Report",
        "lessonType": "writing",
        "primaryPurpose": "Author a formal 260-word condition report assessing an archival musical instrument, detailing sensory indications of deterioration and intervention urgency.",
        "communicativeOutcome": "Author an authoritative museum condition report combining physical conservation data with acoustic integrity evaluations.",
        "objectivesIntroduced": ["obj_b2_182_04_write_condition_report"],
        "objectivesPracticed": ["obj_b2_182_01_master_sensory_appearance_modals", "obj_b2_182_02_read_conservation_reports"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_epistemic_appearance_shig_baiana_yanzytai", "gram_b1_epistemic_probability_bololtoi_magadgui"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_18_critiquing_artistic_exhibitions"],
        "communicativeFunctionsReviewed": ["comm_b2_11_summarizing_complex_articles"],
        "newProductiveLemmaTarget": 7,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_performing_arts_music_folklore"],
        "previousVocabularyReused": ["акталсан", "гэмтэл", "илрэл", "үзүүлэлт", "тэмдэглэл", "зөвлөмж"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Author a 260-word condition report evaluating an 1880s morin khuur and prescribing controlled-humidity conservation.",
        "spokenProductionObjective": "",
        "registerTarget": "institutional museum",
        "pragmaticTarget": "formal diagnostic assessment",
        "prerequisiteLessonIds": ["les_b2_182_03_evaluating_tonal_authenticity_spoken"],
        "reviewsLessonIds": ["les_b2_178_04_philharmonic_recital_musicological_critique_writing"],
        "reviewsUnitIds": ["unit_b2_178_urtyn_duu_long_song_vocal_melisma_g"],
        "reviewReason": "Connects musicological concert reviewing with physical artifact conservation writing.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Deploys sensory appearance modals to document empirical visual and sonic deterioration indicators",
            "Structures report according to ICOM museum documentation standards"
        ],
        "masteryEvidence": "Produces an artifact condition report judged as legally and museologically rigorous.",
        "recommendedExerciseModalities": ["summary_writing", "paragraph_reconstruction"]
    }
])

# UNIT 183: Indirect Discourse Framing Verbs: Өгүүлэх, Дурдах, Сануулах (4 lessons)
# Budget: PL=26, RL=22, PE=8, RE=5
sec03_lessons.extend([
    {
        "lessonId": "les_b2_183_01_indirect_framing_verbs_syntax_intro",
        "unitId": "unit_b2_183_indirect_discourse_framing_verbs_",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 1,
        "title": "Morphosyntax: Academic Citational Framing Verbs 'Өгүүлэх', 'Дурдах' & 'Сануулах'",
        "lessonType": "grammar_introduction",
        "primaryPurpose": "Introduce the syntactic complementation, evidential positioning, and register elevation of formal reporting verbs (өгүүлэх, дурдах, сануулах, онцлох, нотлох) in scholarly literature citations.",
        "communicativeOutcome": "Construct complex academic attribution sentences citing previous musicological research with precise stances of endorsement, distance, or reminder.",
        "objectivesIntroduced": ["obj_b2_183_01_master_indirect_framing_verbs"],
        "objectivesPracticed": [],
        "objectivesReviewed": ["obj_b2_182_01_master_sensory_appearance_modals"],
        "grammarIntroduced": ["gram_b2_indirect_discourse_framing_verbs"],
        "grammarPracticed": ["gram_b2_converb_chaining_discourse", "gram_b2_concessive_contrast_vch_gesen"],
        "grammarReviewed": ["gram_b2_epistemic_appearance_shig_baiana_yanzytai"],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_discourse_chunking_cadence"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_11_summarizing_complex_articles"],
        "communicativeFunctionsReviewed": ["comm_b2_18_critiquing_artistic_exhibitions"],
        "newProductiveLemmaTarget": 7,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_performing_arts_music_folklore"],
        "previousVocabularyReused": ["өгүүлэх", "дурдах", "сануулах", "онцлох", "нотлох", "иш татах"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Draft 6 academic citation sentences attributing historical musicological claims using 'өгүүлэх', 'дурдах', and 'сануулах'.",
        "spokenProductionObjective": "",
        "registerTarget": "academic citational",
        "pragmaticTarget": "scholarly attribution",
        "prerequisiteLessonIds": ["les_b2_182_04_artifact_condition_report_writing"],
        "reviewsLessonIds": ["les_b2_180_01_concessive_contrast_syntax_intro"],
        "reviewsUnitIds": ["unit_b2_180_concessive_contrast_discourse_conju"],
        "reviewReason": "Integrates concessive discourse linking with formal academic indirect reporting structures.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Distinguishes semantic nuances between neutral reporting ('дурдсан'), narrative exposition ('өгүүлсэн'), and cautionary assertion ('сануулсан')",
            "Embeds indirect speech complements using '-хыг / гэдгийг' without clausal breakdown"
        ],
        "masteryEvidence": "Correctly executes 8 sentence conversion items transforming direct quotes into nuanced academic indirect citations.",
        "recommendedExerciseModalities": ["word_transformation", "sentence_reordering"]
    },
    {
        "lessonId": "les_b2_183_02_secret_history_oral_performance_reading",
        "unitId": "unit_b2_183_indirect_discourse_framing_verbs_",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 2,
        "title": "Philological Reading: Secret History Citations & Oral Epic Recitation Traditions",
        "lessonType": "reading",
        "primaryPurpose": "Parse a 370-word philological critique reviewing scholarly citations regarding how the 'Secret History of the Mongols' was originally performed in rhythmic prosimetrum.",
        "communicativeOutcome": "Trace citational lineages, scholarly disagreements, and evidential attribution in a complex philological paper.",
        "objectivesIntroduced": ["obj_b2_183_02_read_citational_historiography"],
        "objectivesPracticed": ["obj_b2_183_01_master_indirect_framing_verbs"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_indirect_discourse_framing_verbs", "gram_b2_converb_chaining_discourse"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_11_summarizing_complex_articles"],
        "communicativeFunctionsReviewed": ["comm_b2_02_academic_essay_concessions"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_b2_performing_arts_music_folklore"],
        "previousVocabularyReused": ["нууц товчоо", "айзам", "шүлэглэл", "эрдэмтэн", "хэлэхүй", "дэвшүүлэх"],
        "readingObjective": "Read a 370-word philological paper and map 4 distinct scholarly hypotheses attributed via 'дурдах' and 'өгүүлэх'.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "academic philology",
        "pragmaticTarget": "historiographical attribution",
        "prerequisiteLessonIds": ["les_b2_183_01_indirect_framing_verbs_syntax_intro"],
        "reviewsLessonIds": ["les_b2_181_02_oral_epic_dating_hypotheses_reading"],
        "reviewsUnitIds": ["unit_b2_181_epistemic_stance_presumption_the_ma"],
        "reviewReason": "Extends philological hypothesis analysis to complex historiographical citation networks.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Distinguishes the primary author's stance from the viewpoints of cited scholars",
            "Identifies cautionary methodological reminders introduced by 'сануулжээ'"
        ],
        "masteryEvidence": "Completes a historiographical attribution matrix mapping 4 academic sources to their specific theoretical claims.",
        "recommendedExerciseModalities": ["source_comparison", "claim_evidence_matching"]
    },
    {
        "lessonId": "les_b2_183_03_musicological_literature_review_writing",
        "unitId": "unit_b2_183_indirect_discourse_framing_verbs_",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 3,
        "title": "Academic Writing: Musicological Literature Review Section with Multi-Source Citations",
        "lessonType": "writing",
        "primaryPurpose": "Author a 260-word literature review section synthesizing competing theories on the origin of pentatonic scale systems across Inner Asia.",
        "communicativeOutcome": "Author an academic literature review section integrating multiple scholarly voices through varied indirect discourse framing verbs.",
        "objectivesIntroduced": ["obj_b2_183_03_write_literature_review"],
        "objectivesPracticed": ["obj_b2_183_01_master_indirect_framing_verbs", "obj_b2_183_02_read_citational_historiography"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_indirect_discourse_framing_verbs", "gram_b2_concessive_contrast_vch_gesen"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_11_summarizing_complex_articles"],
        "communicativeFunctionsReviewed": ["comm_b2_02_academic_essay_concessions"],
        "newProductiveLemmaTarget": 7,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_performing_arts_music_folklore"],
        "previousVocabularyReused": ["тойм", "эх сурвалж", "дүгнэлт", "хандлага", "баримтлах", "баталгаа"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Author a 260-word academic literature review synthesizing 3 major musicologists' claims regarding pentatonic tonal foundations.",
        "spokenProductionObjective": "",
        "registerTarget": "academic literature review",
        "pragmaticTarget": "objective critical synthesis",
        "prerequisiteLessonIds": ["les_b2_183_02_secret_history_oral_performance_reading"],
        "reviewsLessonIds": ["les_b2_180_05_academic_essay_section_heritage_writing"],
        "reviewsUnitIds": ["unit_b2_180_concessive_contrast_discourse_conju"],
        "reviewReason": "Synthesizes concessive essay writing into multi-source academic literature review composition.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Deploys varied framing verbs ('дурдах', 'өгүүлэх', 'сануулах', 'онцлох') avoiding repetitive citational formulas",
            "Synthesizes sources thematically rather than producing a disjointed list of summaries"
        ],
        "masteryEvidence": "Produces a literature review draft judged as meeting doctoral-level academic Mongolian standards.",
        "recommendedExerciseModalities": ["summary_writing", "paragraph_reconstruction"]
    },
    {
        "lessonId": "les_b2_183_04_scholarly_attribution_conference_speech",
        "unitId": "unit_b2_183_indirect_discourse_framing_verbs_",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 4,
        "title": "Spoken Oratory: Literature Review Presentation at Ethnomusicology Congress",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver an oral literature synthesis at an academic congress, acknowledging previous research breakthroughs while introducing the speaker's innovative methodology.",
        "communicativeOutcome": "Deliver a 3-minute academic conference address synthesizing previous literature with polished citational phrasing and collegial respect.",
        "objectivesIntroduced": ["obj_b2_183_04_deliver_literature_synthesis_speech"],
        "objectivesPracticed": ["obj_b2_183_01_master_indirect_framing_verbs", "obj_b2_183_03_write_literature_review"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_indirect_discourse_framing_verbs", "gram_b2_converb_chaining_discourse"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_formal_presentation_cadence", "phono_b2_topic_prominence_intonation"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_11_summarizing_complex_articles"],
        "communicativeFunctionsReviewed": ["comm_b2_07_delivering_prepared_presentations"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_performing_arts_music_folklore"],
        "previousVocabularyReused": ["илтгэгч", "эрдэмтдийн зөвлөл", "судалгааны хэрэглэгдэхүүн", "хамт олон"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Deliver a 3-minute oral literature review situating current research within historical Mongolistics.",
        "registerTarget": "academic congress",
        "pragmaticTarget": "collegial scholarly attribution",
        "prerequisiteLessonIds": ["les_b2_183_03_musicological_literature_review_writing"],
        "reviewsLessonIds": ["les_b2_181_04_defending_historical_performance_speech"],
        "reviewsUnitIds": ["unit_b2_181_epistemic_stance_presumption_the_ma"],
        "reviewReason": "Combines epistemic hypothesis defense with smooth spoken citational framing.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide benchmark speech of senior scholar introducing literature review at international academic symposium.",
        "successCriteria": [
            "Deploys indirect framing verbs with natural intonation breaks before embedded clausal content",
            "Maintains collegial elegance and authoritative academic composure throughout"
        ],
        "masteryEvidence": "Speech recording demonstrates superior control of academic spoken discourse and citation conventions.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
    }
])

# UNIT 184: Limiting Scalar Particles: The Phrasing Бүү Хэл (4 lessons)
# Budget: PL=26, RL=22, PE=8, RE=5
sec03_lessons.extend([
    {
        "lessonId": "les_b2_184_01_limiting_scalar_particles_syntax_intro",
        "unitId": "unit_b2_184_limiting_scalar_particles_the_phras",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 1,
        "title": "Morphosyntax: Limiting Scalar Particles 'Бүү Хэл', 'Байтугай' & 'Гэлтгүй'",
        "lessonType": "grammar_introduction",
        "primaryPurpose": "Introduce the syntactic distribution and pragmatic intensification of limiting scalar particles (бүү хэл, байтугай, гэлтгүй) expressing extreme focal contrast ('let alone... / not to speak of...').",
        "communicativeOutcome": "Formulate scalar emphatic sentences highlighting endangered cultural traditions that risk total extinction before basic preservation begins.",
        "objectivesIntroduced": ["obj_b2_184_01_master_limiting_scalar_particles"],
        "objectivesPracticed": [],
        "objectivesReviewed": ["obj_b2_183_01_master_indirect_framing_verbs"],
        "grammarIntroduced": ["gram_b2_limiting_scalar_particles_buu_khel"],
        "grammarPracticed": ["gram_a2_case_instrumental_transport_language", "gram_b2_converb_chaining_switch_reference"],
        "grammarReviewed": ["gram_b2_indirect_discourse_framing_verbs"],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_topic_prominence_intonation"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": ["comm_b2_15_employing_emphatic_nuance"],
        "communicativeFunctionsPracticed": [],
        "communicativeFunctionsReviewed": ["comm_b2_18_critiquing_artistic_exhibitions"],
        "newProductiveLemmaTarget": 7,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_performing_arts_music_folklore"],
        "previousVocabularyReused": ["бүү хэл", "байтугай", "гэлтгүй", "үгүй", "хэцүү", "алдагдах"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Draft 6 scalar emphatic sentences contrasting widespread cultural literacy with vanishing regional epic singing traditions using 'бүү хэл'.",
        "spokenProductionObjective": "",
        "registerTarget": "advocacy formal",
        "pragmaticTarget": "scalar intensification",
        "prerequisiteLessonIds": ["les_b2_183_04_scholarly_attribution_conference_speech"],
        "reviewsLessonIds": ["les_b2_180_01_concessive_contrast_syntax_intro"],
        "reviewsUnitIds": ["unit_b2_180_concessive_contrast_discourse_conju"],
        "reviewReason": "Bridges concessive contrast into scalar emphatic negative coordination.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Positions 'бүү хэл' and 'байтугай' after the baseline scalar element with zero case dissonance",
            "Controls pragmatic scalar polarity (negative expectation escalated to extreme case)"
        ],
        "masteryEvidence": "Accurately completes 8 sentence transformation items intensifying cultural advocacy arguments using scalar particles.",
        "recommendedExerciseModalities": ["word_transformation", "sentence_reordering"]
    },
    {
        "lessonId": "les_b2_184_02_endangered_epic_traditions_editorial_reading",
        "unitId": "unit_b2_184_limiting_scalar_particles_the_phras",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 2,
        "title": "Critical Reading: Cultural Alarm on the Extinction of Uriankhai Epic Chanting",
        "lessonType": "reading",
        "primaryPurpose": "Parse an impassioned 360-word cultural editorial warning that modern youths cannot comprehend archaic epic vocabulary, let alone recite multi-day heroic verses.",
        "communicativeOutcome": "Extract scalar arguments, societal warnings, and preservation imperatives from an authoritative cultural editorial.",
        "objectivesIntroduced": ["obj_b2_184_02_read_cultural_alarm_editorials"],
        "objectivesPracticed": ["obj_b2_184_01_master_limiting_scalar_particles"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_limiting_scalar_particles_buu_khel", "gram_a2_case_instrumental_transport_language"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_15_employing_emphatic_nuance"],
        "communicativeFunctionsReviewed": ["comm_b2_11_summarizing_complex_articles"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_performing_arts_music_folklore"],
        "previousVocabularyReused": ["урианхай", "туульч", "мартагдах", "мөхөх", "ховор", "аврах"],
        "readingObjective": "Read a 360-word cultural editorial and identify 4 scalar emphatic contrasts marked by 'бүү хэл' and 'байтугай'.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "cultural editorial",
        "pragmaticTarget": "impassioned cultural alarm",
        "prerequisiteLessonIds": ["les_b2_184_01_limiting_scalar_particles_syntax_intro"],
        "reviewsLessonIds": ["les_b2_180_02_folklore_modernization_scholarly_reading"],
        "reviewsUnitIds": ["unit_b2_180_concessive_contrast_discourse_conju"],
        "reviewReason": "Extends folkloric modernization debates into urgent scalar advocacy analysis.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Identifies specific linguistic and social mechanisms leading to the extinction of oral epic singing",
            "Extracts policy solutions proposed by the author to incentivize young apprentice epic singers"
        ],
        "masteryEvidence": "Completes a scalar argument analysis tracking 4 escalating levels of cultural erosion.",
        "recommendedExerciseModalities": ["source_comparison", "claim_evidence_matching"]
    },
    {
        "lessonId": "les_b2_184_03_impassioned_heritage_appeal_speech",
        "unitId": "unit_b2_184_limiting_scalar_particles_the_phras",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 3,
        "title": "Spoken Oratory: Keynote Address at National Assembly on Endangered Intangible Heritage",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver an impassioned keynote address to cultural legislators emphasizing that even basic folklore transmission is collapsing in rural soums.",
        "communicativeOutcome": "Deliver a 3-minute stirring oratorical appeal using scalar particles ('бүү хэл') to galvanize legislative funding for master-apprentice programs.",
        "objectivesIntroduced": ["obj_b2_184_03_deliver_scalar_advocacy_speech"],
        "objectivesPracticed": ["obj_b2_184_01_master_limiting_scalar_particles", "obj_b2_184_02_read_cultural_alarm_editorials"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_limiting_scalar_particles_buu_khel", "gram_b2_converb_chaining_switch_reference"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_formal_presentation_cadence", "phono_b2_topic_prominence_intonation"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_15_employing_emphatic_nuance"],
        "communicativeFunctionsReviewed": ["comm_b2_07_delivering_prepared_presentations"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_b2_performing_arts_music_folklore"],
        "previousVocabularyReused": ["уриалга", "чуулган", "харанга", "өвлүүлэх", "хойч үе", "нэн даруй"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Deliver a 3-minute keynote address warning that without immediate funding, master epic singers will pass away without a single successor.",
        "registerTarget": "formal keynote oratorical",
        "pragmaticTarget": "urgent emotional galvanization",
        "prerequisiteLessonIds": ["les_b2_184_02_endangered_epic_traditions_editorial_reading"],
        "reviewsLessonIds": ["les_b2_180_04_debating_cultural_commercialization_spoken"],
        "reviewsUnitIds": ["unit_b2_180_concessive_contrast_discourse_conju"],
        "reviewReason": "Synthesizes concessive legislative debate rhetoric with powerful scalar emphatic intensification.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide benchmark speech of prominent writer delivering passionate cultural keynote address.",
        "successCriteria": [
            "Deploys 'бүү хэл' and 'байтугай' with dramatic pitch peaks on scalar intensifiers",
            "Maintains commanding oratorical rhythm without rhetorical collapse into pure emotion"
        ],
        "masteryEvidence": "Speech recording reflects extraordinary rhetorical urgency and consummate grammatical command.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
    },
    {
        "lessonId": "les_b2_184_04_unesco_urgent_safeguarding_appeal_writing",
        "unitId": "unit_b2_184_limiting_scalar_particles_the_phras",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 4,
        "title": "Advisory Composition: Urgent Safeguarding Justification for Endangered Folk Genres",
        "lessonType": "writing",
        "primaryPurpose": "Draft a formal justification section for a UNESCO Urgent Safeguarding List application, articulating that the surviving elder performers cannot find disciples in rural areas.",
        "communicativeOutcome": "Author a 260-word formal preservation justification integrating scalar particles to substantiate critical risk criteria.",
        "objectivesIntroduced": ["obj_b2_184_04_write_urgent_safeguarding_appeal"],
        "objectivesPracticed": ["obj_b2_184_01_master_limiting_scalar_particles", "obj_b2_184_03_deliver_scalar_advocacy_speech"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_limiting_scalar_particles_buu_khel", "gram_b2_indirect_discourse_framing_verbs"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_15_employing_emphatic_nuance"],
        "communicativeFunctionsReviewed": ["comm_b2_10_drafting_press_releases"],
        "newProductiveLemmaTarget": 7,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_performing_arts_music_folklore"],
        "previousVocabularyReused": ["шаардлага", "жагсаалт", "нотлох баримт", "тэтгэлэг", "сургалт", "хөтөлбөр"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Author a 260-word UNESCO nomination justification arguing for urgent safeguarding status for Western Mongolian epic recitation.",
        "spokenProductionObjective": "",
        "registerTarget": "international diplomatic",
        "pragmaticTarget": "formal institutional justification",
        "prerequisiteLessonIds": ["les_b2_184_03_impassioned_heritage_appeal_speech"],
        "reviewsLessonIds": ["les_b2_183_03_musicological_literature_review_writing"],
        "reviewsUnitIds": ["unit_b2_183_indirect_discourse_framing_verbs_"],
        "reviewReason": "Synthesizes scholarly literature reviewing with international heritage nomination drafting.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Deploys scalar particles ('бүү хэл') in formal administrative prose to document severe viability threats",
            "Structures text according to UNESCO Intangible Cultural Heritage nomination criteria"
        ],
        "masteryEvidence": "Produces a nomination text judged as immediately submissible to the National Commission for UNESCO.",
        "recommendedExerciseModalities": ["summary_writing", "paragraph_reconstruction"]
    }
])

# UNIT 185: Cross-Cultural Comparative Heritage Analysis (4 lessons)
# Budget: PL=24, RL=21, PE=8, RE=5
sec03_lessons.extend([
    {
        "lessonId": "les_b2_185_01_central_asian_comparative_organology_reading",
        "unitId": "unit_b2_185_cross_cultural_comparative_heritage",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 1,
        "title": "Comparative Reading: Inner Asian Bowed Lutes (Morin Khuur, Kobyz & Kyl Kyiak)",
        "lessonType": "reading",
        "primaryPurpose": "Parse a 380-word comparative organological monograph comparing horsehair friction acoustics across Mongolian, Kazakh, and Kyrgyz pastoral cultures.",
        "communicativeOutcome": "Extract cross-cultural morphological parallels, nomadic cosmological divergences, and shared steppe organological roots.",
        "objectivesIntroduced": ["obj_b2_185_01_read_comparative_organology"],
        "objectivesPracticed": [],
        "objectivesReviewed": ["obj_b2_184_02_read_cultural_alarm_editorials"],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_a1_nominal_predicate_zero_copula", "gram_a1_noun_phrase_attributive_adjective"],
        "grammarReviewed": ["gram_b2_discourse_connectors_rhetorical"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": ["comm_b2_17_cross_cultural_comparisons"],
        "communicativeFunctionsPracticed": [],
        "communicativeFunctionsReviewed": ["comm_b2_18_critiquing_artistic_exhibitions"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 8,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_b2_material_culture_horsemanship"],
        "previousVocabularyReused": ["харьцуулах", "төв ази", "нүүдэлчид", "хөвч", "утаст хөгжим", "нийтлэг"],
        "readingObjective": "Read a 380-word comparative organological analysis contrasting horsehair bridge design between the Mongolian morin khuur and Kazakh kobyz.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "comparative academic",
        "pragmaticTarget": "cross-cultural analytical precision",
        "prerequisiteLessonIds": ["les_b2_184_04_unesco_urgent_safeguarding_appeal_writing"],
        "reviewsLessonIds": ["les_b2_177_01_morin_khuur_acoustic_engineering_reading"],
        "reviewsUnitIds": ["unit_b2_177_the_morin_khuur_acoustic_engineerin"],
        "reviewReason": "Expands Mongolian morin khuur organology into a broader pan-Central Asian comparative perspective.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Accurately maps anatomical correspondences between open-resonator and covered soundbox traditions",
            "Identifies divergent shamanic and spiritual functions assigned to bowed instruments across steppe regions"
        ],
        "masteryEvidence": "Completes a comparative organological matrix contrasting 3 Central Asian bowed instruments across 6 structural metrics.",
        "recommendedExerciseModalities": ["source_comparison", "claim_evidence_matching"]
    },
    {
        "lessonId": "les_b2_185_02_silk_road_epic_poetry_roundtable_listening",
        "unitId": "unit_b2_185_cross_cultural_comparative_heritage",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 2,
        "title": "Acoustic Dissection: International Roundtable on Silk Road Nomadic Epic Recitation",
        "lessonType": "listening",
        "primaryPurpose": "Listen to an international cultural symposium where scholars from Ulaanbaatar, Almaty, and Bishkek compare metrics, alliteration, and musical accompaniment in heroic epics.",
        "communicativeOutcome": "Comprehend complex spoken comparative analyses delivered with regional accents and international academic terminology (145 wpm).",
        "objectivesIntroduced": ["obj_b2_185_02_comprehend_comparative_symposia"],
        "objectivesPracticed": ["obj_b2_185_01_read_comparative_organology"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_a2_converb_concessive_vch_bolovch", "gram_b2_epistemic_appearance_shig_baiana_yanzytai"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_topic_prominence_intonation"],
        "phonologyReviewed": ["phono_b1_stress_focus_contrast"],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_17_cross_cultural_comparisons"],
        "communicativeFunctionsReviewed": ["comm_b2_09_moderating_group_discussions"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_material_culture_horsemanship"],
        "previousVocabularyReused": ["хэлэлцүүлэг", "бүс нутаг", "торгоны зам", "баатарлаг", "шүлэг", "давтагдашгүй"],
        "readingObjective": "",
        "listeningObjective": "Listen to a 3-minute roundtable excerpt and log 3 shared alliterative head-rhyme patterns analyzed across Geser and Manas.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "international academic",
        "pragmaticTarget": "comparative cultural synthesis",
        "prerequisiteLessonIds": ["les_b2_185_01_central_asian_comparative_organology_reading"],
        "reviewsLessonIds": ["les_b2_180_03_cultural_heritage_preservation_panel_listening"],
        "reviewsUnitIds": ["unit_b2_180_concessive_contrast_discourse_conju"],
        "reviewReason": "Extends national heritage debate listening to international multilateral Silk Road scholarly exchanges.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide authentic multilateral academic recording with diverse native and near-native Mongolian accents.",
        "successCriteria": [
            "Identifies specific poetic metrics (head-alliteration, heptasyllabic lines) referenced by speakers",
            "Differentiates between shared archaic Turkic-Mongolic strata and later regional innovations"
        ],
        "masteryEvidence": "Produces a comparative synthesis table summarizing key comparative points from the 3 scholars.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "stance_identification"]
    },
    {
        "lessonId": "les_b2_185_03_comparative_pastoral_song_oral_presentation_speech",
        "unitId": "unit_b2_185_cross_cultural_comparative_heritage",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 3,
        "title": "Spoken Oratory: Comparative Lecture on Pastoral Vocal Traditions Across Inner Asia",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver an oral comparative lecture contrasting Mongolian Urtyn Duu with Tuvan and Buryat pastoral song aesthetics for visiting international scholars.",
        "communicativeOutcome": "Deliver a 3-minute structured comparative lecture highlighting shared pastoral roots and distinct ornamentational trajectories.",
        "objectivesIntroduced": ["obj_b2_185_03_deliver_comparative_lecture"],
        "objectivesPracticed": ["obj_b2_185_01_read_comparative_organology", "obj_b2_185_02_comprehend_comparative_symposia"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_a1_verb_tense_present_habitual_dag", "gram_b2_discourse_connectors_rhetorical"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_formal_presentation_cadence", "phono_b2_topic_prominence_intonation"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_17_cross_cultural_comparisons"],
        "communicativeFunctionsReviewed": ["comm_b2_07_delivering_prepared_presentations"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 4,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_material_culture_horsemanship"],
        "previousVocabularyReused": ["тува", "буриад", "язгуур", "ялгаа", "онцлог", "хувьсал"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Deliver a 3-minute oral presentation comparing modal scales and vibrato frequencies across Inner Asian nomadic vocal styles.",
        "registerTarget": "academic comparative",
        "pragmaticTarget": "comparative cultural illumination",
        "prerequisiteLessonIds": ["les_b2_185_02_silk_road_epic_poetry_roundtable_listening"],
        "reviewsLessonIds": ["les_b2_183_04_scholarly_attribution_conference_speech"],
        "reviewsUnitIds": ["unit_b2_183_indirect_discourse_framing_verbs_"],
        "reviewReason": "Synthesizes literature review presentation standards with complex comparative ethnomusicological analysis.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide benchmark speech of ethnomusicologist delivering comparative cultural lecture to international audience.",
        "successCriteria": [
            "Deploys comparative discourse markers ('үүнтэй харьцуулбал', 'нөгөө талаар', 'адил төстэй боловч') with fluid transitions",
            "Maintains objective cross-cultural respect without chauvinistic regional favoritism"
        ],
        "masteryEvidence": "Speech recording reveals superb comparative structure, balanced analysis, and flawless academic cadence.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
    },
    {
        "lessonId": "les_b2_185_04_unesco_comparative_nomination_paper_writing",
        "unitId": "unit_b2_185_cross_cultural_comparative_heritage",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 4,
        "title": "Academic Writing: Multinational UNESCO Inscription Comparative Assessment Paper",
        "lessonType": "writing",
        "primaryPurpose": "Author a formal 260-word comparative assessment section for a joint multinational intangible cultural heritage nomination dossier.",
        "communicativeOutcome": "Author an authoritative comparative assessment demonstrating unique national expressions within a shared multinational cultural phenomenon.",
        "objectivesIntroduced": ["obj_b2_185_04_write_comparative_assessment"],
        "objectivesPracticed": ["obj_b2_185_01_read_comparative_organology", "obj_b2_185_03_deliver_comparative_lecture"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_a2_case_directional_towards", "gram_b2_limiting_scalar_particles_buu_khel"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_17_cross_cultural_comparisons"],
        "communicativeFunctionsReviewed": ["comm_b2_16_legal_contract_comprehension"],
        "newProductiveLemmaTarget": 7,
        "newReceptiveLemmaTarget": 4,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_material_culture_horsemanship"],
        "previousVocabularyReused": ["хамтарсан", "нэр дэвшүүлэх", "үнэлгээ", "шалгуур", "биет бус өв", "батламж"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Author a 260-word comparative assessment justifying a multinational nomination of nomadic felt-crafting and yurt architecture.",
        "spokenProductionObjective": "",
        "registerTarget": "diplomatic international",
        "pragmaticTarget": "comparative policy justification",
        "prerequisiteLessonIds": ["les_b2_185_03_comparative_pastoral_song_oral_presentation_speech"],
        "reviewsLessonIds": ["les_b2_184_04_unesco_urgent_safeguarding_appeal_writing"],
        "reviewsUnitIds": ["unit_b2_184_limiting_scalar_particles_the_phras"],
        "reviewReason": "Translates single-nation urgent safeguarding appeals into multinational comparative nomination dossiers.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Clearly articulates both the shared common heritage and the distinctive national manifestations of the cultural element",
            "Follows the exact technical requirements of UNESCO Intergovernmental Committee operational directives"
        ],
        "masteryEvidence": "Produces a comparative assessment section judged as immediately submissible to an international nomination bureau.",
        "recommendedExerciseModalities": ["summary_writing", "paragraph_reconstruction"]
    }
])

# UNIT 186: Performing Arts Capstone: Musicological Exhibition Critique (6 lessons)
# Budget: PL=28, RL=25, PE=11, RE=7
sec03_lessons.extend([
    {
        "lessonId": "les_b2_186_01_comprehensive_exhibition_catalogue_reading",
        "unitId": "unit_b2_186_performing_arts_capstone_musicologi",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 1,
        "title": "Capstone Reading: Comprehensive National Performing Arts Heritage Exhibition Catalogue",
        "lessonType": "reading",
        "primaryPurpose": "Parse a 420-word comprehensive exhibition catalogue monograph integrating organological engineering, vocal acoustics, philological epic lineages, and conservation.",
        "communicativeOutcome": "Synthesize multi-domain musicological analyses, curatorial theses, and archival provenance records across 420 words of high-register prose.",
        "objectivesIntroduced": ["obj_b2_186_01_parse_exhibition_catalogue"],
        "objectivesPracticed": [],
        "objectivesReviewed": ["obj_b2_185_01_read_comparative_organology", "obj_b2_182_02_read_conservation_reports"],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_a1_verb_tense_past_witnessed_laa", "gram_a2_case_instrumental_means"],
        "grammarReviewed": ["gram_b2_discourse_causal_consequence_uuden_ulmaar"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_18_critiquing_artistic_exhibitions", "comm_b2_17_cross_cultural_comparisons"],
        "communicativeFunctionsReviewed": ["comm_b2_11_summarizing_complex_articles"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 8,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 3,
        "lexicalDomains": ["lex_b2_performing_arts_music_folklore"],
        "previousVocabularyReused": ["каталог", "дэглэлт", "үзэсгэлэн", "сан хөмрөг", "үнэт зүйлс", "урлаг судлал"],
        "readingObjective": "Read a 420-word national museum exhibition catalogue and synthesize 4 curatorial narratives spanning ancient court music and modern revival.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "curatorial academic",
        "pragmaticTarget": "comprehensive cultural synthesis",
        "prerequisiteLessonIds": ["les_b2_185_04_unesco_comparative_nomination_paper_writing"],
        "reviewsLessonIds": ["les_b2_177_01_morin_khuur_acoustic_engineering_reading"],
        "reviewsUnitIds": ["unit_b2_177_the_morin_khuur_acoustic_engineerin"],
        "reviewReason": "Synthesizes organological details from Unit 177 into a comprehensive national exhibition monograph.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Synthesizes physical organological data with intangible vocal and spiritual traditions without conceptual gaps",
            "Identifies the curatorial narrative structure connecting pastoral acoustic origins to international concert stages"
        ],
        "masteryEvidence": "Produces an executive curatorial summary evaluating the thematic coherence of the exhibition.",
        "recommendedExerciseModalities": ["source_comparison", "claim_evidence_matching"]
    },
    {
        "lessonId": "les_b2_186_02_curator_performer_walkthrough_listening",
        "unitId": "unit_b2_186_performing_arts_capstone_musicologi",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 2,
        "title": "Capstone Listening: Chief Curator & Master Performer Exhibition Gallery Walk-Through",
        "lessonType": "listening",
        "primaryPurpose": "Listen to an in-depth audio walk-through where the chief museum curator and a celebrated epic singer discuss rare 18th-century instruments, tuning changes, and vocal preservation.",
        "communicativeOutcome": "Comprehend rapid spoken curatorial discourse, acoustic demonstrations, and aesthetic critiques delivered in a live gallery setting (150 wpm).",
        "objectivesIntroduced": ["obj_b2_186_02_comprehend_curatorial_dialogue"],
        "objectivesPracticed": ["obj_b2_186_01_parse_exhibition_catalogue"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_concessive_contrast_vch_gesen", "gram_b2_indirect_discourse_framing_verbs"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_topic_prominence_intonation"],
        "phonologyReviewed": ["phono_b1_stress_focus_contrast"],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_18_critiquing_artistic_exhibitions"],
        "communicativeFunctionsReviewed": ["comm_b2_09_moderating_group_discussions"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_performing_arts_music_folklore"],
        "previousVocabularyReused": ["тайлбарлагч", "танхим", "үзмэр", "харилцан яриа", "сонирхолтой", "дэлгэрэнгүй"],
        "readingObjective": "",
        "listeningObjective": "Listen to a 3.5-minute exhibition walk-through recording and log 3 curatorial critiques regarding display lighting and acoustic dampening.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "curatorial dialogue",
        "pragmaticTarget": "discursive artistic appraisal",
        "prerequisiteLessonIds": ["les_b2_186_01_comprehensive_exhibition_catalogue_reading"],
        "reviewsLessonIds": ["les_b2_177_02_master_luthier_workshop_interview_listening"],
        "reviewsUnitIds": ["unit_b2_177_the_morin_khuur_acoustic_engineerin"],
        "reviewReason": "Elevates workshop luthier interviews to museum gallery curatorial dialogues with master performers.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide authentic museum gallery audio with acoustic spatial reverberation and multi-speaker expert dialogue.",
        "successCriteria": [
            "Transcribes exact curatorial terminology and artist aesthetic reflections without distortion",
            "Identifies subtle disagreements between academic curatorial classifications and the performer's living tradition"
        ],
        "masteryEvidence": "Produces an exhibition commentary analysis capturing key theoretical insights from both speakers.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "stance_identification"]
    },
    {
        "lessonId": "les_b2_186_03_critical_exhibition_review_writing",
        "unitId": "unit_b2_186_performing_arts_capstone_musicologi",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 3,
        "title": "Advisory Composition: Critical Musicological Review of National Heritage Exhibition",
        "lessonType": "writing",
        "primaryPurpose": "Draft a rigorous 280-word critical exhibition review evaluating whether the museum successfully conveys the living acoustic spirit of nomadic performance arts.",
        "communicativeOutcome": "Author a high-level musicological critique combining architectural display analysis, acoustic fidelity assessments, and cultural preservation policy.",
        "objectivesIntroduced": ["obj_b2_186_03_author_exhibition_critique"],
        "objectivesPracticed": ["obj_b2_186_01_parse_exhibition_catalogue", "obj_b2_186_02_comprehend_curatorial_dialogue"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_concessive_contrast_vch_gesen", "gram_b2_indirect_discourse_framing_verbs"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_18_critiquing_artistic_exhibitions"],
        "communicativeFunctionsReviewed": ["comm_b2_02_academic_essay_concessions"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 4,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_performing_arts_music_folklore"],
        "previousVocabularyReused": ["шүүмж", "нийтлэл", "дэглэлт", "агуулга", "амжилт", "дутагдал"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Author a 280-word critical exhibition review evaluating the integration of interactive sound installations with static glass-case instrument displays.",
        "spokenProductionObjective": "",
        "registerTarget": "academic cultural journalism",
        "pragmaticTarget": "discerning aesthetic evaluation",
        "prerequisiteLessonIds": ["les_b2_186_02_curator_performer_walkthrough_listening"],
        "reviewsLessonIds": ["les_b2_178_04_philharmonic_recital_musicological_critique_writing"],
        "reviewsUnitIds": ["unit_b2_178_urtyn_duu_long_song_vocal_melisma_g"],
        "reviewReason": "Elevates concert hall performance reviewing to comprehensive museum exhibition critique drafting.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Weaves concessive structures ('боловч', 'хэдий... боловч') and framing verbs ('онцлох', 'сануулах') seamlessly",
            "Provides constructive critique balanced with scholarly recognition of curatorial achievements"
        ],
        "masteryEvidence": "Produces an exhibition review judged as worthy of publication in an international cultural studies journal.",
        "recommendedExerciseModalities": ["summary_writing", "paragraph_reconstruction"]
    },
    {
        "lessonId": "les_b2_186_04_unesco_safeguarding_strategy_dossier_writing",
        "unitId": "unit_b2_186_performing_arts_capstone_musicologi",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 4,
        "title": "Policy Drafting: Strategic Action Plan for Urgent Safeguarding of Performing Arts",
        "lessonType": "writing",
        "primaryPurpose": "Draft the operational action plan section of a national policy dossier detailing institutional apprenticeship grants, digital acoustic archiving, and community workshops.",
        "communicativeOutcome": "Author a 260-word legally structured national action plan establishing concrete cultural preservation mechanisms.",
        "objectivesIntroduced": ["obj_b2_186_04_draft_safeguarding_strategy"],
        "objectivesPracticed": ["obj_b2_186_03_author_exhibition_critique"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_a2_case_instrumental_means", "gram_b2_discourse_causal_consequence_uuden_ulmaar"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_18_critiquing_artistic_exhibitions"],
        "communicativeFunctionsReviewed": ["comm_b2_06_evaluating_public_policies"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 4,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_performing_arts_music_folklore"],
        "previousVocabularyReused": ["стратеги", "үйл ажиллагааны төлөвлөгөө", "хэрэгжилт", "үр дүн", "санхүүжилт"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Author a 260-word strategic action plan detailing five-year state initiatives for safeguarding nomadic vocal arts.",
        "spokenProductionObjective": "",
        "registerTarget": "policy administrative",
        "pragmaticTarget": "actionable cultural strategy",
        "prerequisiteLessonIds": ["les_b2_186_03_critical_exhibition_review_writing"],
        "reviewsLessonIds": ["les_b2_184_04_unesco_urgent_safeguarding_appeal_writing"],
        "reviewsUnitIds": ["unit_b2_184_limiting_scalar_particles_the_phras"],
        "reviewReason": "Synthesizes urgent safeguarding justifications into comprehensive national policy strategic action plans.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Establishes precise timelines, responsible agencies, and quantifiable preservation metrics",
            "Maintains formal statutory administrative Mongolian syntax without ambiguity"
        ],
        "masteryEvidence": "Produces a policy document evaluated as compliant with Ministry of Culture strategic planning guidelines.",
        "recommendedExerciseModalities": ["summary_writing", "paragraph_reconstruction"]
    },
    {
        "lessonId": "les_b2_186_05_symposium_keynote_oration_speech",
        "unitId": "unit_b2_186_performing_arts_capstone_musicologi",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 5,
        "title": "Spoken Oratory: Keynote Gala Address Opening the International Musicology Congress",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver the inaugural keynote address at an international performing arts symposium celebrating the vitality and resilience of nomadic acoustic culture.",
        "communicativeOutcome": "Deliver a 4-minute commanding oratorical keynote address uniting acoustic science, pastoral heritage, and global humanistic value.",
        "objectivesIntroduced": ["obj_b2_186_05_deliver_gala_keynote"],
        "objectivesPracticed": ["obj_b2_186_03_author_exhibition_critique", "obj_b2_186_04_draft_safeguarding_strategy"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_a1_verb_tense_past_witnessed_laa", "gram_b2_concessive_contrast_vch_gesen"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_formal_presentation_cadence", "phono_b2_topic_prominence_intonation"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_18_critiquing_artistic_exhibitions", "comm_b2_17_cross_cultural_comparisons"],
        "communicativeFunctionsReviewed": ["comm_b2_07_delivering_prepared_presentations"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 3,
        "newProductiveExpressionTarget": 3,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_performing_arts_music_folklore"],
        "previousVocabularyReused": ["баярын хурал", "нээлт", "хүндэт зочид", "бахархал", "мөнхийн өв", "цогцлоох"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Deliver a 4-minute gala keynote oration inspiring international delegates on the enduring ecological wisdom of Mongolian music.",
        "registerTarget": "formal ceremonial oratorical",
        "pragmaticTarget": "inspirational cultural leadership",
        "prerequisiteLessonIds": ["les_b2_186_04_unesco_safeguarding_strategy_dossier_writing"],
        "reviewsLessonIds": ["les_b2_184_03_impassioned_heritage_appeal_speech"],
        "reviewsUnitIds": ["unit_b2_184_limiting_scalar_particles_the_phras"],
        "reviewReason": "Transforms passionate heritage appeals into majestic international symposium keynote addresses.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide benchmark recording of leading cultural statesman delivering opening keynote at international congress.",
        "successCriteria": [
            "Deploys rich cultural idioms and elevated grammatical subordination with resonant oratorical cadence",
            "Synthesizes technical musicological insights with universal humanistic themes of cultural preservation"
        ],
        "masteryEvidence": "Speech recording reflects consummate ceremonial poise, rhythmic brilliance, and inspiring emotional resonance.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
    },
    {
        "lessonId": "les_b2_186_06_b2_sec03_culminating_musicological_capstone",
        "unitId": "unit_b2_186_performing_arts_capstone_musicologi",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 6,
        "title": "Culminating Capstone: Comprehensive Performing Arts & Material Culture Synthesis",
        "lessonType": "synthesis_capstone",
        "primaryPurpose": "Synthesize all Section 03 material culture, acoustic organology, ethnomusicology, and advanced grammatical competencies into a multi-phase exhibition critique and safeguarding simulation without introducing new vocabulary.",
        "communicativeOutcome": "Demonstrate comprehensive B2 Vantage mastery across performing arts analysis, critical curatorial writing, and formal conference oratory.",
        "objectivesIntroduced": ["obj_b2_186_06_master_performing_arts_capstone"],
        "objectivesPracticed": [
            "obj_b2_186_01_parse_exhibition_catalogue",
            "obj_b2_186_02_comprehend_curatorial_dialogue",
            "obj_b2_186_03_author_exhibition_critique",
            "obj_b2_186_04_draft_safeguarding_strategy",
            "obj_b2_186_05_deliver_gala_keynote"
        ],
        "objectivesReviewed": [
            "obj_b2_177_01_read_organology_monographs",
            "obj_b2_178_01_read_vocal_ornamentation_studies",
            "obj_b2_179_01_read_overtone_physics",
            "obj_b2_180_01_master_concessive_contrast",
            "obj_b2_181_01_master_epistemic_stance_biz",
            "obj_b2_182_01_master_sensory_appearance_modals",
            "obj_b2_183_01_master_indirect_framing_verbs",
            "obj_b2_184_01_master_limiting_scalar_particles",
            "obj_b2_185_01_read_comparative_organology"
        ],
        "grammarIntroduced": [],
        "grammarPracticed": [
            "gram_b2_concessive_contrast_vch_gesen",
            "gram_b2_epistemic_stance_biz_baih",
            "gram_b2_epistemic_appearance_shig_baiana_yanzytai",
            "gram_b2_indirect_discourse_framing_verbs",
            "gram_b2_limiting_scalar_particles_buu_khel"
        ],
        "grammarReviewed": [
            "gram_b2_converb_gradual_proportional_tusam",
            "gram_b2_converb_durative_adversative_saar_baital",
            "gram_b2_voice_stacking_causative_passive"
        ],
        "phonologyIntroduced": [],
        "phonologyPracticed": [
            "phono_b2_formal_presentation_cadence",
            "phono_b2_concessive_contrast_pitch",
            "phono_b2_epistemic_doubt_pitch"
        ],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": [
            "comm_b2_18_critiquing_artistic_exhibitions",
            "comm_b2_17_cross_cultural_comparisons",
            "comm_b2_02_academic_essay_concessions",
            "comm_b2_15_employing_emphatic_nuance"
        ],
        "communicativeFunctionsReviewed": [
            "comm_b2_11_summarizing_complex_articles",
            "comm_b2_07_delivering_prepared_presentations"
        ],
        "newProductiveLemmaTarget": 0,
        "newReceptiveLemmaTarget": 0,
        "newProductiveExpressionTarget": 0,
        "newReceptiveExpressionTarget": 0,
        "lexicalDomains": ["lex_b2_performing_arts_music_folklore"],
        "previousVocabularyReused": [
            "морин хуур", "уртын дуу", "хөөмий", "тууль", "өв соёл", "хөгжим судлал", "хадгалалт", "үнэ цэнэ", "дэглэлт", "хөгжил"
        ],
        "readingObjective": "Read a multi-part exhibition and symposium dossier synthesizing organology, oral literature, and conservation science.",
        "listeningObjective": "Listen to a composite symposium walk-through recording and evaluate conflicting curatorial arguments.",
        "writingObjective": "Author a culminating 300-word Comprehensive Performing Arts Heritage & Safeguarding Dossier combining critique, comparative analysis, and strategy.",
        "spokenProductionObjective": "Deliver a 4-minute capstone keynote address presenting the safeguarding strategy to an international assembly of musicologists and cultural ministers.",
        "registerTarget": "academic curatorial executive",
        "pragmaticTarget": "comprehensive cultural leadership",
        "prerequisiteLessonIds": ["les_b2_186_05_symposium_keynote_oration_speech"],
        "reviewsLessonIds": ["les_b2_176_06_b2_sec02_culminating_resilience_capstone"],
        "reviewsUnitIds": ["unit_b2_176_ecological_resilience_capstone_cris"],
        "reviewReason": "Connects Section 02 Ecological Resilience capstone mastery with Section 03 Material Culture and Performing Arts culminating synthesis.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide multi-voice capstone recording featuring live exhibition gallery acoustics and symposium addresses.",
        "successCriteria": [
            "Seamlessly integrates all 5 Section 03 grammar structures (боловч, биз, -х шинжтэй, indirect framing verbs, бүү хэл) in speech and writing",
            "Synthesizes acoustic physics, folklore philology, and heritage preservation diplomacy without contradiction"
        ],
        "masteryEvidence": "Produces an exemplary exhibition critique and delivers an authoritative 4-minute keynote address meeting all B2 Vantage certification standards.",
        "recommendedExerciseModalities": [
            "oral_presentation_planning",
            "summary_writing",
            "rebuttal_transformation",
            "extended_listening_comprehension"
        ]
    }
])

print(f"Total Section 03 lessons authored: {len(sec03_lessons)}")

# Verify all 10 units in Section 03
with open("curriculum/blueprint/units/b2.json") as f:
    b2_units = {u["unitId"]: u for u in json.load(f)}

unit_sums = {}
for l in sec03_lessons:
    uid = l["unitId"]
    if uid not in unit_sums:
        unit_sums[uid] = {"PL": 0, "RL": 0, "PE": 0, "RE": 0, "count": 0}
    unit_sums[uid]["PL"] += l["newProductiveLemmaTarget"]
    unit_sums[uid]["RL"] += l["newReceptiveLemmaTarget"]
    unit_sums[uid]["PE"] += l["newProductiveExpressionTarget"]
    unit_sums[uid]["RE"] += l["newReceptiveExpressionTarget"]
    unit_sums[uid]["count"] += 1

mismatches = 0
for uid, sums in sorted(unit_sums.items()):
    u = b2_units[uid]
    exp = (u["newProductiveCoreLemmas"], u["newReceptiveCoreLemmas"], u["newProductiveExpressions"], u["newReceptiveExpressions"])
    act = (sums["PL"], sums["RL"], sums["PE"], sums["RE"])
    if exp != act:
        print(f"MISMATCH in {uid}: Expected {exp}, got {act}")
        mismatches += 1
    else:
        print(f"OK Unit {u['sequencePosition']}: {uid} ({sums['count']} lessons) -> {act}")

if mismatches == 0:
    print("ALL 10 UNITS IN SECTION 03 RECONCILED PERFECTLY!")
    with open("curriculum/lesson_blueprints/b2_section_03.json", "w", encoding="utf-8") as f:
        json.dump(sec03_lessons, f, indent=2, ensure_ascii=False)
    print("SAVED curriculum/lesson_blueprints/b2_section_03.json")
else:
    print(f"FAIL: Found {mismatches} mismatches.")
