# -*- coding: utf-8 -*-
"""Complete authoring for Units 170-176 of Section 02."""
import json
from add_units_169_176 import sec02_lessons

# UNIT 170: Negative Framing Converb (-гүйгээр) (4 lessons)
# Budget: PL=26, RL=22, PE=8, RE=5
sec02_lessons.extend([
    {
        "lessonId": "les_b2_170_01_negative_framing_converb_syntax_intro",
        "unitId": "unit_b2_170_negative_framing_converb_suffixes_",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 1,
        "title": "Morphosyntax: Negative Framing Converb Suffixes '-гүйгээр'",
        "lessonType": "grammar_introduction",
        "primaryPurpose": "Introduce the syntactic scope and administrative application of the negative framing converb '-гүйгээр' expressing essential prerequisites and conditional exclusion ('without having done...').",
        "communicativeOutcome": "Formulate precise regulatory conditional mandates specifying mandatory environmental actions without which operations cannot proceed.",
        "objectivesIntroduced": ["obj_b2_170_01_master_negative_framing_converb"],
        "objectivesPracticed": [],
        "objectivesReviewed": ["obj_b2_169_01_master_durative_adversative_converb"],
        "grammarIntroduced": ["gram_b2_converb_negative_framing_guigeer"],
        "grammarPracticed": ["gram_a1_verb_dictionary_infinitive_kh"],
        "grammarReviewed": ["gram_b2_converb_durative_adversative_saar_baital"],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_discourse_chunking_cadence"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_12_expository_causal_chains"],
        "communicativeFunctionsReviewed": [],
        "newProductiveLemmaTarget": 7,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_ecology_climate_environment"],
        "previousVocabularyReused": ["зөвшөөрөл", "дүгнэлт", "гүйцэтгэх", "эхлэх", "үйл ажиллагаа"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Draft 6 regulatory compliance statements stipulating mandatory environmental impact assessments using '-гүйгээр'.",
        "spokenProductionObjective": "",
        "registerTarget": "legal regulatory",
        "pragmaticTarget": "strict conditional obligation",
        "prerequisiteLessonIds": ["les_b2_169_04_cross_examining_crisis_logistics_spoken"],
        "reviewsLessonIds": ["les_b2_169_01_durative_adversative_converb_syntax_intro"],
        "reviewsUnitIds": ["unit_b2_169_durative_adversative_converb_suffix"],
        "reviewReason": "Integrates adversative temporal contrast with negative conditional clausal framing.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Forms '-гүйгээр' attached to verbal nouns (-х/-ах/-эх) with zero suffix assimilation errors",
            "Expresses strict sine qua non legal conditions without syntactic ambiguity"
        ],
        "masteryEvidence": "Successfully completes 8 sentence transformation tasks converting positive requirements into -гүйгээр negative exclusion clauses.",
        "recommendedExerciseModalities": ["word_transformation", "sentence_reordering"]
    },
    {
        "lessonId": "les_b2_170_02_environmental_compliance_audit_reading",
        "unitId": "unit_b2_170_negative_framing_converb_suffixes_",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 2,
        "title": "Regulatory Review: Environmental Compliance in Mining Tailings Management",
        "lessonType": "reading",
        "primaryPurpose": "Parse a dense 350-word ministerial environmental compliance order halting mining operations due to unpermitted tailing dam discharges.",
        "communicativeOutcome": "Evaluate regulatory infractions and legal consequences in an official environmental enforcement directive.",
        "objectivesIntroduced": ["obj_b2_170_02_read_compliance_directives"],
        "objectivesPracticed": ["obj_b2_170_01_master_negative_framing_converb"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_converb_negative_framing_guigeer", "gram_a1_verb_dictionary_infinitive_kh"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_12_expository_causal_chains"],
        "communicativeFunctionsReviewed": ["comm_b2_06_evaluating_public_policies"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_ecology_climate_environment"],
        "previousVocabularyReused": ["уурхай", "хаягдал", "далан", "ус", "бохирдол", "торгууль"],
        "readingObjective": "Read a 350-word ministry stop-work order and extract 3 non-negotiable remediation prerequisites marked by '-гүйгээр'.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "legal regulatory",
        "pragmaticTarget": "unconditional enforcement",
        "prerequisiteLessonIds": ["les_b2_170_01_negative_framing_converb_syntax_intro"],
        "reviewsLessonIds": ["les_b2_161_03_causal_consequence_policy_reading"],
        "reviewsUnitIds": ["unit_b2_161_institutional_causality_and_conse"],
        "reviewReason": "Extends institutional consequence analysis into statutory negative framing and injunctions.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Identifies specific environmental remediation thresholds required prior to license reinstatement",
            "Distinguishes administrative penalties from mandatory operational injunctions"
        ],
        "masteryEvidence": "Completes a compliance checklist identifying 4 distinct conditions that must be fulfilled before mining may resume.",
        "recommendedExerciseModalities": ["source_comparison", "claim_evidence_matching"]
    },
    {
        "lessonId": "les_b2_170_03_zero_wastewater_regulatory_mandate_writing",
        "unitId": "unit_b2_170_negative_framing_converb_suffixes_",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 3,
        "title": "Administrative Drafting: Mandatory Wastewater Treatment Compliance Order",
        "lessonType": "writing",
        "primaryPurpose": "Draft a formal administrative mandate prohibiting mineral processing operations without certified closed-cycle wastewater recycling facilities.",
        "communicativeOutcome": "Author a 250-word legally enforceable administrative compliance order specifying zero-discharge obligations.",
        "objectivesIntroduced": ["obj_b2_170_03_draft_compliance_orders"],
        "objectivesPracticed": ["obj_b2_170_01_master_negative_framing_converb"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_converb_negative_framing_guigeer", "gram_b2_converb_durative_adversative_saar_baital"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_12_expository_causal_chains"],
        "communicativeFunctionsReviewed": ["comm_b2_10_drafting_press_releases"],
        "newProductiveLemmaTarget": 7,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_b2_ecology_climate_environment"],
        "previousVocabularyReused": ["цэвэршүүлэх", "байгууламж", "хүрээлэн буй орчин", "тооцоо", "шаардах"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Author a 250-word administrative decree ordering mineral concentration plants to halt discharge without triple-phase filtration.",
        "spokenProductionObjective": "",
        "registerTarget": "legal administrative",
        "pragmaticTarget": "formal ultimatum",
        "prerequisiteLessonIds": ["les_b2_170_02_environmental_compliance_audit_reading"],
        "reviewsLessonIds": ["les_b2_167_03_livestock_emergency_evacuation_advisory_writing"],
        "reviewsUnitIds": ["unit_b2_167_the_meteorology_of_dzud_frost_ice_s"],
        "reviewReason": "Synthesizes emergency advisory drafting into legally binding environmental compliance decrees.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Deploys '-гүйгээр' to frame absolute legal preconditions without grammatical error",
            "Incorporates precise technical metrics (filtration microns, recycling percentages) into statutory clauses"
        ],
        "masteryEvidence": "Produces an administrative compliance mandate judged by legal rubrics as fully binding and syntactically flawless.",
        "recommendedExerciseModalities": ["summary_writing", "paragraph_reconstruction"]
    },
    {
        "lessonId": "les_b2_170_04_pasture_water_protection_advocacy_speech",
        "unitId": "unit_b2_170_negative_framing_converb_suffixes_",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 4,
        "title": "Spoken Advocacy: Demanding River Basin Conservation at Tripartite Council",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver an impassioned yet legally grounded oral appeal at a river basin council asserting that no gold exploration may occur without local pastoral consent.",
        "communicativeOutcome": "Deliver a 3-minute persuasive advocacy address demanding strict environmental compliance using '-гүйгээр' and evidential rhetoric.",
        "objectivesIntroduced": ["obj_b2_170_04_deliver_basin_advocacy_speech"],
        "objectivesPracticed": ["obj_b2_170_01_master_negative_framing_converb", "obj_b2_170_03_draft_compliance_orders"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_converb_negative_framing_guigeer", "gram_b2_converb_gradual_proportional_tusam"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_formal_presentation_cadence", "phono_b2_topic_prominence_intonation"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_12_expository_causal_chains"],
        "communicativeFunctionsReviewed": ["comm_b2_04_analyzing_social_trends"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_ecology_climate_environment"],
        "previousVocabularyReused": ["гол", "мөрөн", "сав газар", "нутгийн иргэд", "зөвшилцөл", "хамгаалах"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Deliver a 3-minute oral advocacy address demanding that river headwaters be protected from exploration without community consent.",
        "registerTarget": "civic advocacy",
        "pragmaticTarget": "principled insistence",
        "prerequisiteLessonIds": ["les_b2_170_03_zero_wastewater_regulatory_mandate_writing"],
        "reviewsLessonIds": ["les_b2_157_04_advocacy_oral_statement_spoken"],
        "reviewsUnitIds": ["unit_b2_157_civil_society_advocacy_protest_d"],
        "reviewReason": "Revitalizes Section 01 grassroots advocacy rhetorical strategies within environmental water protection forums.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide benchmark speech of civic environmental leader defending river headwaters with persuasive eloquence.",
        "successCriteria": [
            "Deploys at least 3 distinct -гүйгээр constructions to emphasize the non-negotiability of community consent",
            "Maintains forceful yet strictly professional civic register without rhetorical derailment"
        ],
        "masteryEvidence": "Speech recording reflects compelling civic advocacy and seamless command of negative framing morphology.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
    }
])

print(f"Added Unit 170. Total lessons: {len(sec02_lessons)}")
