# -*- coding: utf-8 -*-
"""Authoring Units 178-186 of Section 03."""
import json
from build_sec03 import sec03_lessons

# UNIT 178: Urtyn Duu (Long Song): Vocal Melisma & Glottal Tremolo (4 lessons)
# Budget: PL=24, RL=21, PE=8, RE=5
sec03_lessons.extend([
    {
        "lessonId": "les_b2_178_01_urtyn_duu_vocal_ornamentation_reading",
        "unitId": "unit_b2_178_urtyn_duu_long_song_vocal_melisma_g",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 1,
        "title": "Ethnomusicology: Vocal Melisma, Shurankhai & Glottal Tremolo in Urtyn Duu",
        "lessonType": "reading",
        "primaryPurpose": "Analyze a scholarly musicological breakdown of the microtonal ornamentation, falsetto leaps (шуранхай), and larynx vibration techniques in traditional long songs.",
        "communicativeOutcome": "Comprehend technical anatomical descriptions of breath control and melismatic phrasing in a 360-word ethnomusicology monograph.",
        "objectivesIntroduced": ["obj_b2_178_01_read_vocal_ornamentation_studies"],
        "objectivesPracticed": [],
        "objectivesReviewed": ["obj_b2_177_01_read_organology_monographs"],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_a2_converb_purposive_khaar", "gram_b1_converb_durative_saar"],
        "grammarReviewed": ["gram_b2_voice_double_causative_delegated"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_18_critiquing_artistic_exhibitions"],
        "communicativeFunctionsReviewed": ["comm_b2_11_summarizing_complex_articles"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 7,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_b2_performing_arts_music_folklore"],
        "previousVocabularyReused": ["уртын дуу", "аялгуу", "амьсгаа", "цохилго", "дуулах", "уламжлал"],
        "readingObjective": "Read a 360-word text explaining vocal tract positioning and falsetto transitions ('шуранхай') in the Central Khalkha style.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "academic ethnomusicology",
        "pragmaticTarget": "analytical aesthetic evaluation",
        "prerequisiteLessonIds": ["les_b2_177_04_traditional_vs_synthetic_strings_critique_writing"],
        "reviewsLessonIds": ["les_b2_177_01_morin_khuur_acoustic_engineering_reading"],
        "reviewsUnitIds": ["unit_b2_177_the_morin_khuur_acoustic_engineerin"],
        "reviewReason": "Extends organological reading skills to vocal tract acoustics and ethnomusicological analysis.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Identifies specific ornamentation categories ('нугалаа', 'цохилго', 'шуранхай') and their acoustic characteristics",
            "Understands the biomechanical distinctions between chest register and falsetto modulation"
        ],
        "masteryEvidence": "Completes an ornamentation taxonomy matching 4 vocal melisma types to their physical acoustic definitions.",
        "recommendedExerciseModalities": ["source_comparison", "claim_evidence_matching"]
    },
    {
        "lessonId": "les_b2_178_02_master_singer_archival_acoustic_listening",
        "unitId": "unit_b2_178_urtyn_duu_long_song_vocal_melisma_g",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 2,
        "title": "Acoustic Dissection: Archival Master Performance & Melisma Transcription",
        "lessonType": "listening",
        "primaryPurpose": "Listen to an authentic archival recording of a master singer performing 'Ulemjiin Chanar' accompanied by morin khuur, with spoken musicological commentary.",
        "communicativeOutcome": "Distinguish subtle vocal inflections, glottal breaks, and microtonal inflections in authentic non-synthetic performance audio.",
        "objectivesIntroduced": ["obj_b2_178_02_discern_vocal_melisma"],
        "objectivesPracticed": ["obj_b2_178_01_read_vocal_ornamentation_studies"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b1_converb_durative_saar", "gram_b2_voice_double_causative_delegated"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_topic_prominence_intonation"],
        "phonologyReviewed": ["phono_b1_stress_focus_contrast"],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_18_critiquing_artistic_exhibitions"],
        "communicativeFunctionsReviewed": [],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_performing_arts_music_folklore"],
        "previousVocabularyReused": ["магистр", "бичлэг", "сонсох", "өнгө", "нууц", "уншилт"],
        "readingObjective": "",
        "listeningObjective": "Listen to a 3-minute archival performance and track 4 distinct glottal tremolos analyzed by the ethnomusicologist.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "musicological critique",
        "pragmaticTarget": "aesthetic discrimination",
        "prerequisiteLessonIds": ["les_b2_178_01_urtyn_duu_vocal_ornamentation_reading"],
        "reviewsLessonIds": ["les_b2_177_02_master_luthier_workshop_interview_listening"],
        "reviewsUnitIds": ["unit_b2_177_the_morin_khuur_acoustic_engineerin"],
        "reviewReason": "Deepens acoustic timbre recognition from instrument crafting to authentic vocal artistry.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide authentic field recording of master urtyn duuch to capture genuine microtonal melisma without synthetic distortion.",
        "successCriteria": [
            "Accurately pinpoints the falsetto transition points ('шуранхай') indicated by the analyst",
            "Differentiates between breath resets and deliberate expressive pauses in the vocal line"
        ],
        "masteryEvidence": "Produces an acoustic performance map identifying ornamentation structures across two stanzas.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "stance_identification"]
    },
    {
        "lessonId": "les_b2_178_03_steppe_ecology_philosophical_vocal_speech",
        "unitId": "unit_b2_178_urtyn_duu_long_song_vocal_melisma_g",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 3,
        "title": "Spoken Oratory: The Steppe Landscape as Acoustic Generator of the Long Song",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver an intellectual oral presentation exploring the philosophical correlation between the boundless steppe horizon and the unmetered, sustained breath of Urtyn Duu.",
        "communicativeOutcome": "Deliver a 3-minute philosophical discourse articulating the ecological cosmology embedded in Mongolian long song traditions.",
        "objectivesIntroduced": ["obj_b2_178_03_deliver_ecological_musicology_speech"],
        "objectivesPracticed": ["obj_b2_178_01_read_vocal_ornamentation_studies", "obj_b2_178_02_discern_vocal_melisma"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_a2_converb_purposive_khaar", "gram_b2_voice_double_causative_delegated"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_formal_presentation_cadence"],
        "phonologyReviewed": ["phono_b2_topic_prominence_intonation"],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_18_critiquing_artistic_exhibitions"],
        "communicativeFunctionsReviewed": ["comm_b2_07_delivering_prepared_presentations"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 4,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_performing_arts_music_folklore"],
        "previousVocabularyReused": ["уудам", "тал", "орчлон", "гүн ухаан", "дуу хоолой", "байгаль"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Deliver a 3-minute philosophical presentation linking nomadic spatial awareness to extended musical melisma.",
        "registerTarget": "intellectual philosophical",
        "pragmaticTarget": "philosophical synthesis",
        "prerequisiteLessonIds": ["les_b2_178_02_master_singer_archival_acoustic_listening"],
        "reviewsLessonIds": ["les_b2_177_03_jonon_khar_legend_acoustic_mythology_spoken"],
        "reviewsUnitIds": ["unit_b2_177_the_morin_khuur_acoustic_engineerin"],
        "reviewReason": "Builds upon mythological storytelling to construct sophisticated aesthetic philosophy presentations.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide benchmark speech illustrating evocative oratorical tempo and rich philosophical vocabulary.",
        "successCriteria": [
            "Deploys purposeful converb constructions ('-хаар/-хээр') expressing artistic intent with poetic elevation",
            "Maintains unbroken conceptual flow between geography, breath capacity, and nomadic metaphysics"
        ],
        "masteryEvidence": "Speech recording reveals profound cultural insight and exceptional prosodic control.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
    },
    {
        "lessonId": "les_b2_178_04_philharmonic_recital_musicological_critique_writing",
        "unitId": "unit_b2_178_urtyn_duu_long_song_vocal_melisma_g",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 4,
        "title": "Critical Review: National Philharmonic Urtyn Duu & Symphony Convergence",
        "lessonType": "writing",
        "primaryPurpose": "Author a critical musicological review of a concert hall performance fusing traditional long song singing with Western symphonic orchestration.",
        "communicativeOutcome": "Author a 260-word critical review evaluating pitch temperaments, acoustic clashes, and expressive authenticity in orchestral fusion.",
        "objectivesIntroduced": ["obj_b2_178_04_write_concert_review"],
        "objectivesPracticed": ["obj_b2_178_01_read_vocal_ornamentation_studies", "obj_b2_178_03_deliver_ecological_musicology_speech"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b1_converb_durative_saar", "gram_a2_converb_purposive_khaar"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_18_critiquing_artistic_exhibitions"],
        "communicativeFunctionsReviewed": ["comm_b2_11_summarizing_complex_articles"],
        "newProductiveLemmaTarget": 7,
        "newReceptiveLemmaTarget": 4,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_performing_arts_music_folklore"],
        "previousVocabularyReused": ["шүүмж", "найрал", "хөгжмийн зэмсэг", "хэмнэл", "зохицол", "үнэлгээ"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Author a 260-word formal review examining how equal temperament equalizers affect authentic non-tempered vocal microtones.",
        "spokenProductionObjective": "",
        "registerTarget": "academic cultural journalism",
        "pragmaticTarget": "discerning aesthetic critique",
        "prerequisiteLessonIds": ["les_b2_178_03_steppe_ecology_philosophical_vocal_speech"],
        "reviewsLessonIds": ["les_b2_177_04_traditional_vs_synthetic_strings_critique_writing"],
        "reviewsUnitIds": ["unit_b2_177_the_morin_khuur_acoustic_engineerin"],
        "reviewReason": "Synthesizes string organology critiques with vocal performance evaluation standards.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Deploys specialized musical terminology ('тэгш хэмт хөг', 'бичил эгшиг') with flawless accuracy",
            "Critiques orchestration balance fairly, noting both artistic achievements and acoustic compromises"
        ],
        "masteryEvidence": "Produces a cultural review judged as publication-ready by cultural arts editorial rubrics.",
        "recommendedExerciseModalities": ["summary_writing", "paragraph_reconstruction"]
    }
])

# UNIT 179: Khöömii Throat Singing: Overtone Physics & Styles (4 lessons)
# Budget: PL=24, RL=21, PE=8, RE=5
sec03_lessons.extend([
    {
        "lessonId": "les_b2_179_01_throat_singing_overtone_physics_reading",
        "unitId": "unit_b2_179_kh_mii_throat_singing_overtone_phys",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 1,
        "title": "Acoustic Physics: Biphonic Phonation & Lingual Cavity Resonances in Khöömii",
        "lessonType": "reading",
        "primaryPurpose": "Parse an acoustic phonetics monograph analyzing how ventricular fold engagement creates a deep fundamental drone while tongue position isolates the 6th through 12th harmonics.",
        "communicativeOutcome": "Interpret spectrogram charts, formant filter formulas, and vocal tract anatomy in a 360-word scientific study of throat singing.",
        "objectivesIntroduced": ["obj_b2_179_01_read_overtone_physics"],
        "objectivesPracticed": [],
        "objectivesReviewed": ["obj_b2_178_01_read_vocal_ornamentation_studies"],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_a2_reported_speech_gej_kheleh", "gram_b1_converb_modal_manner_n"],
        "grammarReviewed": ["gram_b2_conditionals_counterfactual_past"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_18_critiquing_artistic_exhibitions"],
        "communicativeFunctionsReviewed": ["comm_b2_20_interpreting_graphs_statistics"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 7,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_b2_performing_arts_music_folklore"],
        "previousVocabularyReused": ["хөөмий", "давхар эгшиг", "хэлний угийн", "хэлбэлзэл", "судалгаа"],
        "readingObjective": "Read a 360-word phonetics paper comparing the acoustic filter profiles of sygyt (исгэрээ) and kargyraa (хархираа).",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "scientific phonetics",
        "pragmaticTarget": "biomechanical precision",
        "prerequisiteLessonIds": ["les_b2_178_04_philharmonic_recital_musicological_critique_writing"],
        "reviewsLessonIds": ["les_b2_178_01_urtyn_duu_vocal_ornamentation_reading"],
        "reviewsUnitIds": ["unit_b2_178_urtyn_duu_long_song_vocal_melisma_g"],
        "reviewReason": "Extends vocal melisma reading into biomechanical and overtone physics analysis.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Explains the physiological difference between false vocal cord vibration and lingual overtone filtering",
            "Identifies specific formant frequency ranges associated with Altai mountain stream imitation styles"
        ],
        "masteryEvidence": "Completes a phonetic analysis matching 4 khöömii sub-genres to their specific resonance cavity configurations.",
        "recommendedExerciseModalities": ["source_comparison", "claim_evidence_matching"]
    },
    {
        "lessonId": "les_b2_179_02_master_khoomiich_live_demonstration_listening",
        "unitId": "unit_b2_179_kh_mii_throat_singing_overtone_phys",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 2,
        "title": "Acoustic Dissection: Live Master Khöömiich Masterclass & Harmonic Isolation",
        "lessonType": "listening",
        "primaryPurpose": "Listen to an authentic live workshop where an Altai master throat singer demonstrates tongue positioning, breath pressure control, and harmonic whistle separation.",
        "communicativeOutcome": "Comprehend rapid spoken instructional feedback and distinguish live overtone shifts in authentic non-synthetic performance audio.",
        "objectivesIntroduced": ["obj_b2_179_02_comprehend_overtone_masterclasses"],
        "objectivesPracticed": ["obj_b2_179_01_read_overtone_physics"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b1_converb_modal_manner_n", "gram_a2_reported_speech_gej_kheleh"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_topic_prominence_intonation"],
        "phonologyReviewed": ["phono_b1_stress_focus_contrast"],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_18_critiquing_artistic_exhibitions"],
        "communicativeFunctionsReviewed": [],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_performing_arts_music_folklore"],
        "previousVocabularyReused": ["багш", "шавь", "дасгал", "хоолой", "шахах", "дуугаргах"],
        "readingObjective": "",
        "listeningObjective": "Listen to a 3-minute masterclass recording and log 3 corrective instructions regarding tongue arching given by the master.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "instructional masterclass",
        "pragmaticTarget": "didactic demonstration",
        "prerequisiteLessonIds": ["les_b2_179_01_throat_singing_overtone_physics_reading"],
        "reviewsLessonIds": ["les_b2_178_02_master_singer_archival_acoustic_listening"],
        "reviewsUnitIds": ["unit_b2_178_urtyn_duu_long_song_vocal_melisma_g"],
        "reviewReason": "Extends vocal timbre discrimination from long song melisma to dual-tone overtone singing.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide authentic live masterclass recording capturing simultaneous low drone and high whistle overtones without artificial processing.",
        "successCriteria": [
            "Identifies specific anatomical terms used by the master ('хэлний завь', 'хоолойн шахалт') during rapid spoken guidance",
            "Differentiates between correct harmonic isolation and strained guttural constriction"
        ],
        "masteryEvidence": "Produces an instructional summary mapping the master's pedagogical exercises for achieving high overtone clarity.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "stance_identification"]
    },
    {
        "lessonId": "les_b2_179_03_throat_singing_symposium_presentation_speech",
        "unitId": "unit_b2_179_kh_mii_throat_singing_overtone_phys",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 3,
        "title": "Spoken Oratory: Presenting Altai Khöömii Traditions at International Ethnomusicology Forum",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver an oral conference presentation explaining the origins of Khöömii in Chandmani Soum and its acoustic relationship to wind and cascading water sounds.",
        "communicativeOutcome": "Deliver a 3-minute authoritative musicological conference presentation integrating acoustic physics with nomadic animist soundscapes.",
        "objectivesIntroduced": ["obj_b2_179_03_deliver_musicology_symposium_speech"],
        "objectivesPracticed": ["obj_b2_179_01_read_overtone_physics", "obj_b2_179_02_comprehend_overtone_masterclasses"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_conditionals_counterfactual_past", "gram_b1_converb_modal_manner_n"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_formal_presentation_cadence", "phono_b2_complex_causal_contour"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_18_critiquing_artistic_exhibitions"],
        "communicativeFunctionsReviewed": ["comm_b2_07_delivering_prepared_presentations"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 4,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_performing_arts_music_folklore"],
        "previousVocabularyReused": ["хурал", "илтгэл", "уул", "ус", "дуурайх", "эгшиглэх"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Deliver a 3-minute oral presentation demonstrating how nomadic herders recreate environmental acoustics through throat resonance.",
        "registerTarget": "academic conference",
        "pragmaticTarget": "scholarly exposition",
        "prerequisiteLessonIds": ["les_b2_179_02_master_khoomiich_live_demonstration_listening"],
        "reviewsLessonIds": ["les_b2_178_03_steppe_ecology_philosophical_vocal_speech"],
        "reviewsUnitIds": ["unit_b2_178_urtyn_duu_long_song_vocal_melisma_g"],
        "reviewReason": "Synthesizes landscape aesthetic theory with acoustic overtone physics in conference presentation delivery.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide benchmark recording of ethnomusicologist presenting acoustic research slides at international forum.",
        "successCriteria": [
            "Deploys modal manner converb '-н/-н' and counterfactuals to show how environment shapes vocal technique",
            "Maintains stately conference cadence and precise anatomical/musicological vocabulary"
        ],
        "masteryEvidence": "Speech recording reveals exemplary conference oratorical poise and flawless pronunciation of complex phonological terms.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
    },
    {
        "lessonId": "les_b2_179_04_comparative_acoustic_styles_critique_writing",
        "unitId": "unit_b2_179_kh_mii_throat_singing_overtone_phys",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 4,
        "title": "Written Critique: Traditional Pastoral Animism vs Modern Commercial Stage Khöömii",
        "lessonType": "writing",
        "primaryPurpose": "Author an academic essay examining the stylistic divergence between intimate pastoral throat singing and amplified commercial folk-rock stage adaptations.",
        "communicativeOutcome": "Author a 260-word critical evaluation analyzing the acoustic and cultural transformations of throat singing in global entertainment venues.",
        "objectivesIntroduced": ["obj_b2_179_04_write_overtone_critique"],
        "objectivesPracticed": ["obj_b2_179_01_read_overtone_physics", "obj_b2_179_03_deliver_musicology_symposium_speech"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_a2_reported_speech_gej_kheleh", "gram_b2_conditionals_counterfactual_past"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_18_critiquing_artistic_exhibitions"],
        "communicativeFunctionsReviewed": ["comm_b2_11_summarizing_complex_articles"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 4,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_performing_arts_music_folklore"],
        "previousVocabularyReused": ["тайз", "рок", "арилжаа", "өөрчлөлт", "хөгжил", "үнэ цэнэ"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Author a 260-word critical essay comparing the acoustic intimacy of nomadic khöömii with modern amplified rock performance.",
        "spokenProductionObjective": "",
        "registerTarget": "academic cultural journalism",
        "pragmaticTarget": "critical cultural analysis",
        "prerequisiteLessonIds": ["les_b2_179_03_throat_singing_symposium_presentation_speech"],
        "reviewsLessonIds": ["les_b2_178_04_philharmonic_recital_musicological_critique_writing"],
        "reviewsUnitIds": ["unit_b2_178_urtyn_duu_long_song_vocal_melisma_g"],
        "reviewReason": "Builds upon symphonic fusion reviews to examine global commercialization of traditional overtone performance.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Evaluates microphone frequency response and stage amplification effects on delicate natural overtones",
            "Balances commercial success with concerns regarding acoustic distortion and spiritual detachment"
        ],
        "masteryEvidence": "Produces an analytical essay evaluated as intellectually rigorous and culturally nuanced.",
        "recommendedExerciseModalities": ["summary_writing", "paragraph_reconstruction"]
    }
])

print(f"Added Units 178-179. Total lessons: {len(sec03_lessons)}")
