# -*- coding: utf-8 -*-
"""Complete authoring for Units 172-176 of Section 02."""
import json
from append_sec02_all2 import sec02_lessons

# UNIT 172: Double Causative Morphology: Delegated Actions (4 lessons)
# Budget: PL=26, RL=22, PE=8, RE=5
sec02_lessons.extend([
    {
        "lessonId": "les_b2_172_01_double_causative_morphology_intro",
        "unitId": "unit_b2_172_double_causative_morphology_delegat",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 1,
        "title": "Morphosyntax: Double Causative Morphology (-уул-уул- / -лга-уул-) in Delegated Action",
        "lessonType": "grammar_introduction",
        "primaryPurpose": "Introduce double causative derivation expressing secondary delegation where an executive causes an intermediary to compel a contractor to perform environmental remediation.",
        "communicativeOutcome": "Construct complex institutional delegation chains distinguishing primary instigator, intermediate manager, and ultimate executor.",
        "objectivesIntroduced": ["obj_b2_172_01_master_double_causative"],
        "objectivesPracticed": [],
        "objectivesReviewed": ["obj_b2_171_01_master_stacked_causative_passive"],
        "grammarIntroduced": ["gram_b2_voice_double_causative_delegated"],
        "grammarPracticed": ["gram_a1_sov_word_order", "gram_a1_case_accusative_definite"],
        "grammarReviewed": ["gram_b2_voice_stacking_causative_passive"],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_discourse_chunking_cadence"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_05_business_negotiations_terms"],
        "communicativeFunctionsReviewed": ["comm_b2_12_expository_causal_chains"],
        "newProductiveLemmaTarget": 7,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_ecology_climate_environment"],
        "previousVocabularyReused": ["даалгах", "хийлгэх", "гүйцэтгүүлэх", "шаардуулах", "хянуулах"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Construct 6 institutional sentences illustrating secondary delegation chains using double causative morphology.",
        "spokenProductionObjective": "",
        "registerTarget": "administrative corporate",
        "pragmaticTarget": "delegated command",
        "prerequisiteLessonIds": ["les_b2_171_05_legal_petition_against_expropriation_writing"],
        "reviewsLessonIds": ["les_b2_171_01_stacked_voice_causative_passive_intro"],
        "reviewsUnitIds": ["unit_b2_171_stacked_voice_causative_passive_mor"],
        "reviewReason": "Expands single causative and causative-passive structures into multi-tier double causative delegation hierarchies.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Correctly stacks causative morphemes (-уул-уул- / -лга-уул-) with correct phonological glide insertions",
            "Assigns correct case marking across three participants (Subject in nominative, intermediary in dative-locative, direct patient in accusative)"
        ],
        "masteryEvidence": "Accurately completes 8 sentence construction exercises mapping three-tier corporate delegation chains.",
        "recommendedExerciseModalities": ["word_transformation", "sentence_reordering"]
    },
    {
        "lessonId": "les_b2_172_02_mine_tailings_remediation_tender_reading",
        "unitId": "unit_b2_172_double_causative_morphology_delegat",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 2,
        "title": "Technical Reading: Mine Tailings Ecological Remediation Subcontracting Tender",
        "lessonType": "reading",
        "primaryPurpose": "Parse a 360-word commercial tender document outlining obligations where a mining concessionaire delegates environmental engineering to specialized firms.",
        "communicativeOutcome": "Evaluate hierarchical performance liabilities and milestone verification protocols in a commercial ecological contract.",
        "objectivesIntroduced": ["obj_b2_172_02_parse_remediation_tenders"],
        "objectivesPracticed": ["obj_b2_172_01_master_double_causative"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_voice_double_causative_delegated", "gram_b2_converb_durative_adversative_saar_baital"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_05_business_negotiations_terms"],
        "communicativeFunctionsReviewed": ["comm_b2_16_legal_contract_comprehension"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_b2_ecology_climate_environment"],
        "previousVocabularyReused": ["тендер", "нөхөн сэргээлт", "гүйцэтгэгч", "хөрс", "хяналт", "баталгаа"],
        "readingObjective": "Read a 360-word technical remediation tender and extract 4 mandatory subcontractor performance milestones marked by double causatives.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "commercial legal",
        "pragmaticTarget": "contractual precision",
        "prerequisiteLessonIds": ["les_b2_172_01_double_causative_morphology_intro"],
        "reviewsLessonIds": ["les_b2_170_02_environmental_compliance_audit_reading"],
        "reviewsUnitIds": ["unit_b2_170_negative_framing_converb_suffixes_"],
        "reviewReason": "Builds upon environmental compliance auditing to interpret commercial subcontracting tender clauses.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Identifies which obligations the primary concessionaire must cause the subcontractor to fulfill",
            "Extracts penalty stipulations tied to unfulfilled toxic tailings encapsulation"
        ],
        "masteryEvidence": "Completes a contract responsibility matrix mapping 5 environmental duties to their responsible contractual tiers.",
        "recommendedExerciseModalities": ["source_comparison", "claim_evidence_matching"]
    },
    {
        "lessonId": "les_b2_172_03_executive_delegation_remediation_speech",
        "unitId": "unit_b2_172_double_causative_morphology_delegat",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 3,
        "title": "Spoken Direction: Corporate Executive Delegating Environmental Remediation",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver an executive managerial directive instructing division heads to commission external engineering audits and oversee revegetation contractors.",
        "communicativeOutcome": "Deliver a 3-minute executive managerial briefing delegating multi-stage environmental remediation tasks with authoritative clarity.",
        "objectivesIntroduced": ["obj_b2_172_03_deliver_delegation_briefing"],
        "objectivesPracticed": ["obj_b2_172_01_master_double_causative", "obj_b2_172_02_parse_remediation_tenders"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_voice_double_causative_delegated", "gram_a1_sov_word_order"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_formal_presentation_cadence"],
        "phonologyReviewed": ["phono_b2_topic_prominence_intonation"],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_05_business_negotiations_terms"],
        "communicativeFunctionsReviewed": ["comm_b2_07_delivering_prepared_presentations"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_ecology_climate_environment"],
        "previousVocabularyReused": ["захирал", "хэлтэс", "даалгавар", "гүйцэтгэл", "хугацаа", "шалгах"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Deliver a 3-minute executive briefing commanding division chiefs to execute and supervise outsourced biological pasture revegetation.",
        "registerTarget": "corporate executive",
        "pragmaticTarget": "authoritative delegation",
        "prerequisiteLessonIds": ["les_b2_172_02_mine_tailings_remediation_tender_reading"],
        "reviewsLessonIds": ["les_b2_167_04_provincial_emergency_press_briefing_speech"],
        "reviewsUnitIds": ["unit_b2_167_the_meteorology_of_dzud_frost_ice_s"],
        "reviewReason": "Translates public disaster briefing speech formats into private corporate executive operational commands.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide benchmark recording of corporate mining director delivering executive operational orders to management team.",
        "successCriteria": [
            "Deploys double causative morphology ('хянуулах', 'хийлгүүлэх') fluently without stumbling",
            "Maintains decisive executive tone and precise delegation deadlines"
        ],
        "masteryEvidence": "Speech recording confirms executive command presence and error-free multi-agent verb inflection.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
    },
    {
        "lessonId": "les_b2_172_04_environmental_responsibility_agreement_writing",
        "unitId": "unit_b2_172_double_causative_morphology_delegat",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 4,
        "title": "Contract Drafting: Corporate Social & Ecological Responsibility Agreement",
        "lessonType": "writing",
        "primaryPurpose": "Draft formal contract clauses specifying that the operating company must cause its subcontractors to carry out biological topsoil restoration.",
        "communicativeOutcome": "Author a 250-word legally binding corporate social responsibility contract section governing delegated pasture restoration.",
        "objectivesIntroduced": ["obj_b2_172_04_draft_delegated_contract_clauses"],
        "objectivesPracticed": ["obj_b2_172_01_master_double_causative", "obj_b2_172_02_parse_remediation_tenders"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_voice_double_causative_delegated", "gram_b2_converb_durative_adversative_saar_baital"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_05_business_negotiations_terms"],
        "communicativeFunctionsReviewed": ["comm_b2_16_legal_contract_comprehension"],
        "newProductiveLemmaTarget": 7,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_ecology_climate_environment"],
        "previousVocabularyReused": ["хариуцлага", "нөхөн сэргээлт", "заалт", "хүлээх", "батлах", "хэрэгжүүлэх"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Author a 250-word contractual clause stipulating delegated ecological remediation duties with double causative syntax.",
        "spokenProductionObjective": "",
        "registerTarget": "commercial legal",
        "pragmaticTarget": "binding contractual commitment",
        "prerequisiteLessonIds": ["les_b2_172_03_executive_delegation_remediation_speech"],
        "reviewsLessonIds": ["les_b2_171_05_legal_petition_against_expropriation_writing"],
        "reviewsUnitIds": ["unit_b2_171_stacked_voice_causative_passive_mor"],
        "reviewReason": "Synthesizes judicial petition precision with commercial contract drafting for environmental liability.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Integrates double causative verbs to specify chain of corporate and contractor liability",
            "Ensures contractual clauses are fully enforceable under Mongolian environmental law"
        ],
        "masteryEvidence": "Produces an authoritative contract section establishing unambiguous multi-tiered remediation obligations.",
        "recommendedExerciseModalities": ["summary_writing", "paragraph_reconstruction"]
    }
])

print(f"Added Unit 172. Total lessons: {len(sec02_lessons)}")
