# -*- coding: utf-8 -*-
"""Complete authoring for Units 171-176 of Section 02."""
import json
from append_sec02_all import sec02_lessons

# UNIT 171: Stacked Voice: Causative-Passive Morphology (-уулагдах) (5 lessons)
# Budget: PL=26, RL=22, PE=8, RE=5
sec02_lessons.extend([
    {
        "lessonId": "les_b2_171_01_stacked_voice_causative_passive_intro",
        "unitId": "unit_b2_171_stacked_voice_causative_passive_mor",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 1,
        "title": "Morphosyntax: Stacked Causative-Passive Morphology '-уулагдах / -лгэгдэх'",
        "lessonType": "grammar_introduction",
        "primaryPurpose": "Introduce the double-suffix morphological hierarchy combining causative derivation (-уул-/-лга-) with passive inflection (-агд-/-гд-) to express compelled or externally mandated institutional actions ('be made to undergo...').",
        "communicativeOutcome": "Construct complex institutional statements describing parties being subjected to mandatory state or corporate directives.",
        "objectivesIntroduced": ["obj_b2_171_01_master_stacked_causative_passive"],
        "objectivesPracticed": [],
        "objectivesReviewed": ["obj_b2_170_01_master_negative_framing_converb"],
        "grammarIntroduced": ["gram_b2_voice_stacking_causative_passive"],
        "grammarPracticed": ["gram_a1_case_accusative_definite"],
        "grammarReviewed": ["gram_b2_converb_negative_framing_guigeer"],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_complex_causal_contour"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": ["comm_b2_05_business_negotiations_terms"],
        "communicativeFunctionsPracticed": [],
        "communicativeFunctionsReviewed": ["comm_b2_12_expository_causal_chains"],
        "newProductiveLemmaTarget": 7,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_ecology_climate_environment"],
        "previousVocabularyReused": ["албадах", "шийтгэх", "нүүлгэх", "төлүүлэх", "хариуцуулах"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Draft 6 legal statements illustrating stacked causative-passive morphology in corporate liability contexts.",
        "spokenProductionObjective": "",
        "registerTarget": "legal institutional",
        "pragmaticTarget": "institutional compulsion",
        "prerequisiteLessonIds": ["les_b2_170_04_pasture_water_protection_advocacy_speech"],
        "reviewsLessonIds": ["les_b2_170_01_negative_framing_converb_syntax_intro"],
        "reviewsUnitIds": ["unit_b2_170_negative_framing_converb_suffixes_"],
        "reviewReason": "Integrates negative conditional framing with stacked causative-passive morphological hierarchies.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Correctly sequences causative suffix prior to passive morpheme (-уул-агд- / -лга-гд-)",
            "Accurately reassigns theta roles and grammatical cases (agent in dative-locative, patient in nominative)"
        ],
        "masteryEvidence": "Correctly converts 8 active delegated sentences into stacked causative-passive constructions without case errors.",
        "recommendedExerciseModalities": ["word_transformation", "sentence_reordering"]
    },
    {
        "lessonId": "les_b2_171_02_supreme_court_pasture_expropriation_reading",
        "unitId": "unit_b2_171_stacked_voice_causative_passive_mor",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 2,
        "title": "Judicial Parsing: Supreme Court Ruling on Pasture Expropriation & Compensation",
        "lessonType": "reading",
        "primaryPurpose": "Parse a highly technical 370-word judicial judgment from the Administrative Court reviewing herders who were compelled to relocate from mining lease territories.",
        "communicativeOutcome": "Extract legal precedents, statutory liability definitions, and restitution orders from a formal court ruling.",
        "objectivesIntroduced": ["obj_b2_171_02_read_judicial_rulings"],
        "objectivesPracticed": ["obj_b2_171_01_master_stacked_causative_passive"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_voice_stacking_causative_passive", "gram_a1_classifiers_measure_words"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_05_business_negotiations_terms"],
        "communicativeFunctionsReviewed": ["comm_b2_12_expository_causal_chains"],
        "newProductiveLemmaTarget": 4,
        "newReceptiveLemmaTarget": 8,
        "newProductiveExpressionTarget": 1,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_b2_ecology_climate_environment"],
        "previousVocabularyReused": ["шүүх", "шийдвэр", "нөхөн олговор", "нүүлгэн шилжүүлэлт", "газар чөлөөлөх"],
        "readingObjective": "Read a 370-word Administrative Court ruling and determine 3 procedural violations in forced resettlement orders marked by -уулагдах.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "judicial formal",
        "pragmaticTarget": "statutory interpretation",
        "prerequisiteLessonIds": ["les_b2_171_01_stacked_voice_causative_passive_intro"],
        "reviewsLessonIds": ["les_b2_161_02_regulatory_causality_reading"],
        "reviewsUnitIds": ["unit_b2_161_institutional_causality_and_conse"],
        "reviewReason": "Extends institutional causality analysis to high-level judicial jurisprudence.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Identifies which parties were legally compelled to pay indemnities and which were forced to evacuate",
            "Disentangles complex embedding of causative-passive verbs within participial relative clauses"
        ],
        "masteryEvidence": "Completes a judicial case brief detailing legal grounds, affected parties, and mandated compensation amounts.",
        "recommendedExerciseModalities": ["source_comparison", "claim_evidence_matching"]
    },
    {
        "lessonId": "les_b2_171_03_pasture_eviction_investigative_audio_listening",
        "unitId": "unit_b2_171_stacked_voice_causative_passive_mor",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 3,
        "title": "Investigative Audio: Investigative Report on Coerced Winter Camp Resettlement",
        "lessonType": "listening",
        "primaryPurpose": "Listen to an investigative audio documentary tracking herder families forced to dismantle ancestral winter encampments under corporate security pressure.",
        "communicativeOutcome": "Discern factual intimidation claims from legal corporate defenses in a multi-party spoken investigative program (145 wpm).",
        "objectivesIntroduced": ["obj_b2_171_03_analyze_investigative_audio"],
        "objectivesPracticed": ["obj_b2_171_01_master_stacked_causative_passive"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_voice_stacking_causative_passive", "gram_b2_converb_gradual_proportional_tusam"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_topic_prominence_intonation"],
        "phonologyReviewed": ["phono_b1_stress_focus_contrast"],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_05_business_negotiations_terms"],
        "communicativeFunctionsReviewed": ["comm_b2_04_analyzing_social_trends"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 4,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_ecology_climate_environment"],
        "previousVocabularyReused": ["өмгөөлөгч", "сурвалжлага", "гэрч", "шахалт", "эрх ашиг"],
        "readingObjective": "",
        "listeningObjective": "Listen to a 3-minute investigative audio report and map the conflicting accounts of herder evictions between mining representatives and elders.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "investigative broadcast",
        "pragmaticTarget": "discursive contestation",
        "prerequisiteLessonIds": ["les_b2_171_02_supreme_court_pasture_expropriation_reading"],
        "reviewsLessonIds": ["les_b2_169_02_herder_testimony_delayed_fodder_listening"],
        "reviewsUnitIds": ["unit_b2_169_durative_adversative_converb_suffix"],
        "reviewReason": "Contrasts climate crisis herder interviews with corporate land confrontation investigative reporting.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide authentic broadcast journalism audio with field interviews, background machinery noise, and sharp interviewer tone.",
        "successCriteria": [
            "Accurately transcribes instances of causative-passive verbs used to denote coerced actions",
            "Differentiates between voluntary compensation agreements and involuntary displacement"
        ],
        "masteryEvidence": "Produces an evidence log comparing company statements against eyewitness testimonies.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "stance_identification"]
    },
    {
        "lessonId": "les_b2_171_04_oral_defense_pasture_sovereignty_speech",
        "unitId": "unit_b2_171_stacked_voice_causative_passive_mor",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 4,
        "title": "Spoken Testimony: Defending Ancestral Grazing Rights Before Land Inquiry",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver an oral defense of herder rights before a national land commission, arguing against coerced relocation and unlawful licensing.",
        "communicativeOutcome": "Deliver a 3-minute impassioned legal-pastoral defense articulating why herders cannot be forced into resettlement.",
        "objectivesIntroduced": ["obj_b2_171_04_deliver_pasture_defense_speech"],
        "objectivesPracticed": ["obj_b2_171_01_master_stacked_causative_passive", "obj_b2_171_02_read_judicial_rulings"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_voice_stacking_causative_passive", "gram_b2_converb_negative_framing_guigeer"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_formal_presentation_cadence", "phono_b2_topic_prominence_intonation"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_05_business_negotiations_terms"],
        "communicativeFunctionsReviewed": ["comm_b2_01_participating_formal_debates"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 3,
        "newProductiveExpressionTarget": 1,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_ecology_climate_environment"],
        "previousVocabularyReused": ["уламжлал", "өвөг дээдэс", "тусгай хамгаалалт", "хууль ёсны", "эсэргүүцэл"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Deliver a 3-minute oral defense challenging municipal land orders that compel pastoral families to abandon winter pastures.",
        "registerTarget": "formal oratorical",
        "pragmaticTarget": "moral and legal vindication",
        "prerequisiteLessonIds": ["les_b2_171_03_pasture_eviction_investigative_audio_listening"],
        "reviewsLessonIds": ["les_b2_170_04_pasture_water_protection_advocacy_speech"],
        "reviewsUnitIds": ["unit_b2_170_negative_framing_converb_suffixes_"],
        "reviewReason": "Synthesizes water rights advocacy with formal anti-expropriation legal testimony.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide benchmark audio of senior legal advocate delivering oral arguments at national land tribunal.",
        "successCriteria": [
            "Deploys -уулагдах correctly in at least 3 rhetorical climaxes",
            "Maintains commanding oratorical rhythm and precise legal terminology"
        ],
        "masteryEvidence": "Speech recording demonstrates superior control of stacked voice morphology in high-stakes spoken argumentation.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
    },
    {
        "lessonId": "les_b2_171_05_legal_petition_against_expropriation_writing",
        "unitId": "unit_b2_171_stacked_voice_causative_passive_mor",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 5,
        "title": "Legal Petition: Formal Appeal to Constitutional Court on Pasture Inviolability",
        "lessonType": "writing",
        "primaryPurpose": "Draft a formal legal petition appealing an administrative eviction order, arguing that pastoralists were unconstitutionally subjected to forced contract signing.",
        "communicativeOutcome": "Author a 260-word formal legal appeal detailing violations of pasture user rights and requesting an immediate injunction.",
        "objectivesIntroduced": ["obj_b2_171_05_draft_legal_appeal"],
        "objectivesPracticed": ["obj_b2_171_01_master_stacked_causative_passive", "obj_b2_171_02_read_judicial_rulings"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_voice_stacking_causative_passive", "gram_a1_case_accusative_definite"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_05_business_negotiations_terms"],
        "communicativeFunctionsReviewed": ["comm_b2_10_drafting_press_releases"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 2,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 0,
        "lexicalDomains": ["lex_b2_ecology_climate_environment"],
        "previousVocabularyReused": ["өргөдөл", "гомдол", "үндсэн хууль", "зөрчих", "түдгэлзүүлэх"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Author a 260-word legal petition petitioning the Administrative Appellate Court to invalidate a forced pasture relocation decree.",
        "spokenProductionObjective": "",
        "registerTarget": "legal formal",
        "pragmaticTarget": "formal petitioning",
        "prerequisiteLessonIds": ["les_b2_171_04_oral_defense_pasture_sovereignty_speech"],
        "reviewsLessonIds": ["les_b2_170_03_zero_wastewater_regulatory_mandate_writing"],
        "reviewsUnitIds": ["unit_b2_170_negative_framing_converb_suffixes_"],
        "reviewReason": "Applies administrative drafting rigor to judicial appeal petitions contesting coercive land orders.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Deploys stacked voice verbs ('нүүлгэн шилжүүлэгдсэн', 'гарын үсэг зуруулагдсан') with absolute legal precision",
            "Structures petition in accordance with standard Mongolian legal pleading format"
        ],
        "masteryEvidence": "Produces a legal appeal judged as fully compliant with court submission standards.",
        "recommendedExerciseModalities": ["summary_writing", "paragraph_reconstruction"]
    }
])

print(f"Added Unit 171. Total lessons: {len(sec02_lessons)}")
