# -*- coding: utf-8 -*-
"""Authoring Units 180-186 of Section 03."""
import json
from append_sec03_all import sec03_lessons

# UNIT 180: Concessive Contrast Discourse: Conjunctions Боловч & Хэдий ч (5 lessons)
# Budget: PL=26, RL=22, PE=8, RE=5
sec03_lessons.extend([
    {
        "lessonId": "les_b2_180_01_concessive_contrast_syntax_intro",
        "unitId": "unit_b2_180_concessive_contrast_discourse_conju",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 1,
        "title": "Morphosyntax: Concessive Contrast Conjunctions 'Боловч' & 'Хэдий... боловч / ч гэсэн'",
        "lessonType": "grammar_introduction",
        "primaryPurpose": "Introduce the syntactic scope, clausal coordination, and pragmatic function of concessive conjunctions (боловч, хэдий... боловч, ч гэсэн) expressing non-preventive contrast in formal discourse ('although / even though').",
        "communicativeOutcome": "Construct balanced complex sentences acknowledging an established counter-fact while asserting an overriding cultural thesis.",
        "objectivesIntroduced": ["obj_b2_180_01_master_concessive_contrast"],
        "objectivesPracticed": [],
        "objectivesReviewed": ["obj_b2_179_01_read_overtone_physics"],
        "grammarIntroduced": ["gram_b2_concessive_contrast_vch_gesen"],
        "grammarPracticed": ["gram_a1_case_ablative_origin", "gram_a2_verb_past_resultative_zhee"],
        "grammarReviewed": ["gram_b1_converb_limiting_ngaa"],
        "phonologyIntroduced": ["phono_b2_concessive_contrast_pitch"],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": ["comm_b2_02_academic_essay_concessions"],
        "communicativeFunctionsPracticed": [],
        "communicativeFunctionsReviewed": ["comm_b2_18_critiquing_artistic_exhibitions"],
        "newProductiveLemmaTarget": 7,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_performing_arts_music_folklore"],
        "previousVocabularyReused": ["боловч", "хэдий", "гэсэн хэдий ч", "хэдийгээр", "үнэн", "гэвч"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Draft 6 formal concessive sentences balancing the loss of ancient rituals with the revitalization of folk music festivals.",
        "spokenProductionObjective": "",
        "registerTarget": "academic formal",
        "pragmaticTarget": "balanced concession",
        "prerequisiteLessonIds": ["les_b2_179_04_comparative_acoustic_styles_critique_writing"],
        "reviewsLessonIds": ["les_b2_173_01_past_counterfactual_syntax_intro"],
        "reviewsUnitIds": ["unit_b2_173_past_counterfactual_conditionals_su"],
        "reviewReason": "Bridges hypothetical counterfactual conditionals into realis concessive contrastive discourse.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Positions 'боловч' and paired correlatives ('хэдий... боловч') with correct clause boundaries",
            "Controls subtle pragmatic distinctions between factual concessives ('боловч') and scalar concessives ('ч гэсэн')"
        ],
        "masteryEvidence": "Accurately completes 8 sentence transformation items restructuring adversarial points into cohesive concessive arguments.",
        "recommendedExerciseModalities": ["word_transformation", "sentence_reordering"]
    },
    {
        "lessonId": "les_b2_180_02_folklore_modernization_scholarly_reading",
        "unitId": "unit_b2_180_concessive_contrast_discourse_conju",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 2,
        "title": "Academic Reading: Folkloric Modernization & Heritage Authenticity Debates",
        "lessonType": "reading",
        "primaryPurpose": "Parse a 370-word scholarly essay debating whether electronic arrangement of pastoral ballads diminishes their spiritual essence.",
        "communicativeOutcome": "Extract nuanced dialectical positions and concessive pivots in a complex cultural studies text.",
        "objectivesIntroduced": ["obj_b2_180_02_read_cultural_debates"],
        "objectivesPracticed": ["obj_b2_180_01_master_concessive_contrast"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_concessive_contrast_vch_gesen", "gram_a1_case_ablative_origin"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_02_academic_essay_concessions"],
        "communicativeFunctionsReviewed": ["comm_b2_11_summarizing_complex_articles"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 7,
        "newProductiveExpressionTarget": 1,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_b2_performing_arts_music_folklore"],
        "previousVocabularyReused": ["өв соёл", "шинэчлэл", "уламжлал", "эргэлзээ", "маргаан", "хамгаалах"],
        "readingObjective": "Read a 370-word academic paper and identify 4 concessive arguments defending digital archiving while lamenting ritual context loss.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "academic humanities",
        "pragmaticTarget": "dialectical reasoning",
        "prerequisiteLessonIds": ["les_b2_180_01_concessive_contrast_syntax_intro"],
        "reviewsLessonIds": ["les_b2_179_01_throat_singing_overtone_physics_reading"],
        "reviewsUnitIds": ["unit_b2_179_kh_mii_throat_singing_overtone_phys"],
        "reviewReason": "Connects acoustic physics reading to broader cultural and philosophical debates in ethnomusicology.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Maps the author's primary thesis without confusing concessive concessions for main claims",
            "Identifies rhetorical markers signaling shifts from concession to counter-assertion"
        ],
        "masteryEvidence": "Completes an argument diagram mapping concession clauses to their corresponding emphatic assertions.",
        "recommendedExerciseModalities": ["argument_mapping", "source_comparison"]
    },
    {
        "lessonId": "les_b2_180_03_cultural_heritage_preservation_panel_listening",
        "unitId": "unit_b2_180_concessive_contrast_discourse_conju",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 3,
        "title": "Acoustic Dissection: Round-Table Debate on Intangible Cultural Heritage Commercialization",
        "lessonType": "listening",
        "primaryPurpose": "Listen to a round-table debate featuring folklore professors, tourism executives, and traditional artists debating state festival sponsorship.",
        "communicativeOutcome": "Identify speaker alliances, diplomatic concessions, and irreconcilable ideological divides in spoken debate (145 wpm).",
        "objectivesIntroduced": ["obj_b2_180_03_track_cultural_debate_alliances"],
        "objectivesPracticed": ["obj_b2_180_01_master_concessive_contrast"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_concessive_contrast_vch_gesen", "gram_b1_converb_limiting_ngaa"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_concessive_contrast_pitch", "phono_b2_topic_prominence_intonation"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_02_academic_essay_concessions"],
        "communicativeFunctionsReviewed": ["comm_b2_01_participating_formal_debates"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 4,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_performing_arts_music_folklore"],
        "previousVocabularyReused": ["аялал жуулчлал", "ашиг", "дэмжлэг", "санхүүжилт", "үзэгчид", "хязгаарлах"],
        "readingObjective": "",
        "listeningObjective": "Listen to a 3-minute panel exchange and log 3 concessive rebuttals using 'хэдий... боловч' uttered by the folklore scholar.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "academic panel",
        "pragmaticTarget": "diplomatic counter-argumentation",
        "prerequisiteLessonIds": ["les_b2_180_02_folklore_modernization_scholarly_reading"],
        "reviewsLessonIds": ["les_b2_175_02_tense_bilateral_negotiation_listening"],
        "reviewsUnitIds": ["unit_b2_175_commercial_resource_negotiations_pa"],
        "reviewReason": "Adapts resource negotiation listening comprehension to cultural policy panel debates.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide multi-speaker academic debate audio illustrating vocal pitch reset following concessive introductory phrases.",
        "successCriteria": [
            "Differentiates between genuine agreement and polite rhetorical concessions",
            "Identifies the exact verbal counter-strikes following concessive clauses"
        ],
        "masteryEvidence": "Produces an analytical transcript breakdown showing concession-to-assertion ratios for all 3 panelists.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "stance_identification"]
    },
    {
        "lessonId": "les_b2_180_04_debating_cultural_commercialization_spoken",
        "unitId": "unit_b2_180_concessive_contrast_discourse_conju",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 4,
        "title": "Spoken Oratory: Parliamentary Debate on Regulating Commercial Folk Festivals",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver an oral debate speech arguing for state subsidies of authentic nomadic music while acknowledging the financial benefits of commercialized tourism.",
        "communicativeOutcome": "Deliver a 3-minute persuasive speech utilizing structured concessive pivots to neutralize opposing fiscal arguments.",
        "objectivesIntroduced": ["obj_b2_180_04_deliver_concessive_debate_speech"],
        "objectivesPracticed": ["obj_b2_180_01_master_concessive_contrast", "obj_b2_180_03_track_cultural_debate_alliances"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_concessive_contrast_vch_gesen", "gram_a2_verb_past_resultative_zhee"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_concessive_contrast_pitch", "phono_b2_formal_presentation_cadence"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_02_academic_essay_concessions"],
        "communicativeFunctionsReviewed": ["comm_b2_01_participating_formal_debates"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 3,
        "newProductiveExpressionTarget": 1,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_performing_arts_music_folklore"],
        "previousVocabularyReused": ["хууль", "татвар", "хөрөнгө оруулалт", "соёл", "үнэ цэнэ", "дэмжих"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Deliver a 3-minute parliamentary address urging state sponsorship of rural epic singers while granting tax credits to private festivals.",
        "registerTarget": "parliamentary formal",
        "pragmaticTarget": "persuasive concession",
        "prerequisiteLessonIds": ["les_b2_180_03_cultural_heritage_preservation_panel_listening"],
        "reviewsLessonIds": ["les_b2_176_05_cabinet_emergency_defense_speech"],
        "reviewsUnitIds": ["unit_b2_176_ecological_resilience_capstone_cris"],
        "reviewReason": "Applies cabinet defense oratorical standards to cultural heritage legislation debates.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide benchmark speech of cultural advocate delivering structured parliamentary address with concessive modulation.",
        "successCriteria": [
            "Deploys at least 3 distinct concessive formulas ('боловч', 'хэдий тийм боловч', 'ч гэсэн') during live delivery",
            "Elevates pitch slightly on the concession and strikes a resolute falling tone on the core legislative thesis"
        ],
        "masteryEvidence": "Speech recording confirms exceptional mastery of concessive rhetorical intonation and debate framing.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
    },
    {
        "lessonId": "les_b2_180_05_academic_essay_section_heritage_writing",
        "unitId": "unit_b2_180_concessive_contrast_discourse_conju",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 5,
        "title": "Academic Writing: Concessive Argumentation Section in Cultural Policy Monograph",
        "lessonType": "writing",
        "primaryPurpose": "Author an academic essay section examining the paradox of heritage commodification using multi-tiered concessive clauses.",
        "communicativeOutcome": "Author a 270-word scholarly essay section demonstrating dialectical balance on intangible heritage preservation.",
        "objectivesIntroduced": ["obj_b2_180_05_write_concessive_essay"],
        "objectivesPracticed": ["obj_b2_180_01_master_concessive_contrast", "obj_b2_180_02_read_cultural_debates"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_concessive_contrast_vch_gesen", "gram_a1_case_ablative_origin"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_02_academic_essay_concessions"],
        "communicativeFunctionsReviewed": ["comm_b2_06_evaluating_public_policies"],
        "newProductiveLemmaTarget": 4,
        "newReceptiveLemmaTarget": 3,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 0,
        "lexicalDomains": ["lex_b2_performing_arts_music_folklore"],
        "previousVocabularyReused": ["судалгааны бүтээл", "хэрэгцээ", "зайлшгүй", "нөхцөл", "хамгаалалт"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Author a 270-word academic monograph section analyzing how global recognition safeguards yet standardizes local oral genres.",
        "spokenProductionObjective": "",
        "registerTarget": "academic monograph",
        "pragmaticTarget": "scholarly dialectic",
        "prerequisiteLessonIds": ["les_b2_180_04_debating_cultural_commercialization_spoken"],
        "reviewsLessonIds": ["les_b2_173_05_retrospective_policy_critique_essay_writing"],
        "reviewsUnitIds": ["unit_b2_173_past_counterfactual_conditionals_su"],
        "reviewReason": "Synthesizes counterfactual policy critique writing with concessive academic essay construction.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Integrates concessive conjunctions without sentence fragments or run-on structures",
            "Preserves objective scholarly tone and rigorous academic citation phrasing"
        ],
        "masteryEvidence": "Produces an essay section meeting peer-reviewed cultural anthropology journal formatting.",
        "recommendedExerciseModalities": ["summary_writing", "paragraph_reconstruction"]
    }
])

# UNIT 181: Epistemic Stance & Presumption: The Marker Биз / Байх (4 lessons)
# Budget: PL=26, RL=22, PE=8, RE=5
sec03_lessons.extend([
    {
        "lessonId": "les_b2_181_01_epistemic_stance_biz_baih_syntax_intro",
        "unitId": "unit_b2_181_epistemic_stance_presumption_the_ma",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 1,
        "title": "Morphosyntax: Epistemic Presumption Particles 'Биз' & Inferential 'Байх'",
        "lessonType": "grammar_introduction",
        "primaryPurpose": "Introduce the syntactic placement, pragmatic nuances, and modal commitment levels of epistemic particles (биз, байлгүй, биз ээ, -х байх) expressing calibrated presumption and high-probability inference.",
        "communicativeOutcome": "Formulate nuanced epistemic statements expressing well-founded hypotheses regarding historical cultural origins without absolute evidential certainty.",
        "objectivesIntroduced": ["obj_b2_181_01_master_epistemic_stance_biz"],
        "objectivesPracticed": [],
        "objectivesReviewed": ["obj_b2_180_01_master_concessive_contrast"],
        "grammarIntroduced": ["gram_b2_epistemic_stance_biz_baih"],
        "grammarPracticed": ["gram_a1_nominal_negation_bish", "gram_a1_existential_baina_baihgui", "gram_a2_participle_relative_clause_past_san"],
        "grammarReviewed": ["gram_b2_concessive_contrast_vch_gesen"],
        "phonologyIntroduced": ["phono_b2_epistemic_doubt_pitch"],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_18_critiquing_artistic_exhibitions"],
        "communicativeFunctionsReviewed": ["comm_b2_02_academic_essay_concessions"],
        "newProductiveLemmaTarget": 7,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_performing_arts_music_folklore"],
        "previousVocabularyReused": ["биз", "байх", "магадгүй", "таамаглах", "лавтай", "эрхбиш"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Draft 6 scholarly statements hypothesizing 12th-century court banquet song structures using 'биз' and '-х байх'.",
        "spokenProductionObjective": "",
        "registerTarget": "academic historical",
        "pragmaticTarget": "calibrated epistemic stance",
        "prerequisiteLessonIds": ["les_b2_180_05_academic_essay_section_heritage_writing"],
        "reviewsLessonIds": ["les_b2_162_02_particles_pragmatic_syntax_intro"],
        "reviewsUnitIds": ["unit_b2_162_pragmatic_emphatic_nuance_particles"],
        "reviewReason": "Deepens pragmatic particle mastery by introducing epistemic presumptive stance markers.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Distinguishes between confident deduction ('-х биз ээ') and colloquial conversational tag ('биз дээ')",
            "Attaches epistemic particles to verbal participles (-сан/-х/-даг) without morphological error"
        ],
        "masteryEvidence": "Accurately completes 8 sentence transformation exercises converting direct assertions into cautious epistemic hypotheses.",
        "recommendedExerciseModalities": ["word_transformation", "sentence_reordering"]
    },
    {
        "lessonId": "les_b2_181_02_oral_epic_dating_hypotheses_reading",
        "unitId": "unit_b2_181_epistemic_stance_presumption_the_ma",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 2,
        "title": "Philological Reading: Hypotheses on the Chronological Stratification of Jangar & Geser",
        "lessonType": "reading",
        "primaryPurpose": "Parse a dense 360-word philological paper evaluating linguistic strata and archaic lexical forms in heroic epics.",
        "communicativeOutcome": "Extract authorial degree of certainty, evidential qualifications, and historical inferences in a philological study.",
        "objectivesIntroduced": ["obj_b2_181_02_read_philological_hypotheses"],
        "objectivesPracticed": ["obj_b2_181_01_master_epistemic_stance_biz"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_epistemic_stance_biz_baih", "gram_a2_participle_relative_clause_habitual_dag"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_18_critiquing_artistic_exhibitions"],
        "communicativeFunctionsReviewed": ["comm_b2_11_summarizing_complex_articles"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_performing_arts_music_folklore"],
        "previousVocabularyReused": ["тууль", "баатар", "үе давхарга", "он цаг", "эх сурвалж", "хэл шинжлэл"],
        "readingObjective": "Read a 360-word philological paper and isolate 4 distinct chronological hypotheses qualified by 'биз' and 'байх'.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "academic philological",
        "pragmaticTarget": "philological skepticism",
        "prerequisiteLessonIds": ["les_b2_181_01_epistemic_stance_biz_baih_syntax_intro"],
        "reviewsLessonIds": ["les_b2_180_02_folklore_modernization_scholarly_reading"],
        "reviewsUnitIds": ["unit_b2_180_concessive_contrast_discourse_conju"],
        "reviewReason": "Extends cultural debate reading to philological textual criticism and stance analysis.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Identifies which dating arguments the author considers definitively proven versus merely plausible",
            "Extracts phonological and morphosyntactic evidence cited to support ancient origins"
        ],
        "masteryEvidence": "Completes an evidential certainty matrix classifying 5 epic origins claims along a confidence scale.",
        "recommendedExerciseModalities": ["source_comparison", "claim_evidence_matching"]
    },
    {
        "lessonId": "les_b2_181_03_ancient_court_musicology_interview_listening",
        "unitId": "unit_b2_181_epistemic_stance_presumption_the_ma",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 3,
        "title": "Acoustic Dissection: Musicologist Discussion on Great Khan Court Instrumental Ensembles",
        "lessonType": "listening",
        "primaryPurpose": "Listen to an interview with an ethnomusicologist reconstructing 13th-century Yuan dynasty Mongolian palace orchestras from Persian and Chinese historical chronicles.",
        "communicativeOutcome": "Comprehend rapid spoken inferences, speculative modal particles, and historical citations in a radio interview (145 wpm).",
        "objectivesIntroduced": ["obj_b2_181_03_comprehend_historical_inferences"],
        "objectivesPracticed": ["obj_b2_181_01_master_epistemic_stance_biz"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_epistemic_stance_biz_baih", "gram_a2_participle_relative_clause_future_kh"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_epistemic_doubt_pitch", "phono_b2_topic_prominence_intonation"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_18_critiquing_artistic_exhibitions"],
        "communicativeFunctionsReviewed": [],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_b2_performing_arts_music_folklore"],
        "previousVocabularyReused": ["хааны ордон", "чуулга", "түүхч", "тэмдэглэл", "сэргээх", "хөгжим судлаач"],
        "readingObjective": "",
        "listeningObjective": "Listen to a 3-minute radio broadcast and log 3 presumptive deductions made by the musicologist regarding ancient pentatonic tunings.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "academic interview",
        "pragmaticTarget": "inferred hypothesis",
        "prerequisiteLessonIds": ["les_b2_181_02_oral_epic_dating_hypotheses_reading"],
        "reviewsLessonIds": ["les_b2_177_02_master_luthier_workshop_interview_listening"],
        "reviewsUnitIds": ["unit_b2_177_the_morin_khuur_acoustic_engineerin"],
        "reviewReason": "Expands workshop interview listening to high-level academic historical reconstructions.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide authentic broadcast interview featuring academic conversational tempo and subtle pitch variations on epistemic particles.",
        "successCriteria": [
            "Transcribes instances of 'байх', 'биз', and 'бололтой' indicating varying levels of historical certainty",
            "Identifies which instrument reconstructions are based on direct archaeological evidence versus historical inference"
        ],
        "masteryEvidence": "Produces an accurate summary of the musicologist's reconstruction hypotheses.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "stance_identification"]
    },
    {
        "lessonId": "les_b2_181_04_defending_historical_performance_speech",
        "unitId": "unit_b2_181_epistemic_stance_presumption_the_ma",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 4,
        "title": "Spoken Oratory: Defending Historical Reconstruction Hypotheses Before Peer Review",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver an oral defense of a proposed reconstruction of ancient nomadic harp ('ятга') tuning systems at a scholarly colloquium.",
        "communicativeOutcome": "Deliver a 3-minute persuasive academic defense articulating presumptive hypotheses using 'биз' and 'байх' with calibrated intellectual poise.",
        "objectivesIntroduced": ["obj_b2_181_04_defend_historical_hypotheses"],
        "objectivesPracticed": ["obj_b2_181_01_master_epistemic_stance_biz", "obj_b2_181_02_read_philological_hypotheses"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_epistemic_stance_biz_baih", "gram_b1_converb_abnutative_lgui"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_epistemic_doubt_pitch", "phono_b2_formal_presentation_cadence"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_18_critiquing_artistic_exhibitions"],
        "communicativeFunctionsReviewed": ["comm_b2_07_delivering_prepared_presentations"],
        "newProductiveLemmaTarget": 7,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_performing_arts_music_folklore"],
        "previousVocabularyReused": ["ятга", "утас", "хөг эгшиг", "баримт", "тайлбар", "хамгаалах"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Deliver a 3-minute oral defense arguing that curved harp pegboxes indicate Silk Road trans-cultural exchange using 'биз'.",
        "registerTarget": "academic colloquium",
        "pragmaticTarget": "scholarly persuasion",
        "prerequisiteLessonIds": ["les_b2_181_03_ancient_court_musicology_interview_listening"],
        "reviewsLessonIds": ["les_b2_180_04_debating_cultural_commercialization_spoken"],
        "reviewsUnitIds": ["unit_b2_180_concessive_contrast_discourse_conju"],
        "reviewReason": "Synthesizes concessive debate oratory with delicate epistemic stance modulation in peer review.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide benchmark speech of researcher presenting historical musicology paper with calibrated scholarly stance.",
        "successCriteria": [
            "Deploys 'биз' and 'байх' to convey scholarly humility while maintaining intellectual rigor",
            "Controls subtle pitch inflections to signal that a hypothesis is well-evidenced yet open to peer critique"
        ],
        "masteryEvidence": "Speech recording reflects consummate academic presentation cadence and flawless stance control.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
    }
])

print(f"Added Units 180-181. Total lessons: {len(sec03_lessons)}")
