# -*- coding: utf-8 -*-
"""Full lesson generator for B2 Section 02 (Units 167-176)."""
import json

lessons = [
    # -------------------------------------------------------------------------
    # UNIT 167: Meteorology of Dzud (Discourse Unit)
    # Budget: PL=24, RL=21, PE=8, RE=5. 5 lessons.
    # -------------------------------------------------------------------------
    {
        "lessonId": "les_b2_167_01_siberian_anticyclone_meteorological_bulletin_reading",
        "unitId": "unit_b2_167_the_meteorology_of_dzud_frost_ice_s",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 1,
        "title": "Meteorological Dossier: Siberian Anticyclone Dynamics & Ground Frost Severity",
        "lessonType": "reading",
        "primaryPurpose": "Parse dense synoptic weather bulletins and agro-meteorological bulletins analyzing cold-air inversions, barometric pressure anomalies, and snowpack crusting.",
        "communicativeOutcome": "Extract critical temperature anomalies, snow-cover depths, and pasture blockage metrics from institutional weather bulletins.",
        "objectivesIntroduced": ["obj_b2_167_01_parse_synoptic_bulletins"],
        "objectivesPracticed": [],
        "objectivesReviewed": ["obj_b2_166_01_extract_masterplan_projections"],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_a1_existential_baina_baihgui", "gram_b1_clause_temporal_omno_daraa_yed"],
        "grammarReviewed": ["gram_b2_discourse_causal_consequence_uuden_ulmaar"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": ["comm_b2_24_crisis_management_advisories"],
        "communicativeFunctionsPracticed": [],
        "communicativeFunctionsReviewed": ["comm_b2_06_evaluating_public_policies"],
        "newProductiveLemmaTarget": 4,
        "newReceptiveLemmaTarget": 7,
        "newProductiveExpressionTarget": 1,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_b2_ecology_climate_environment"],
        "previousVocabularyReused": ["цаг агаар", "хүйтрэл", "зуд", "цас", "салхи", "хэмжилт"],
        "readingObjective": "Read a 320-word synoptic bulletin detailing a -48C Siberian high-pressure ridge and calculate pasture ice crusting rates across northern aimags.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "meteorological institutional",
        "pragmaticTarget": "evidential caution",
        "prerequisiteLessonIds": ["les_b2_166_06_b2_sec01_culminating_mastery_capstone"],
        "reviewsLessonIds": ["les_b2_166_01_municipal_urban_masterplan_reading"],
        "reviewsUnitIds": ["unit_b2_166_public_policy_capstone_municipal_ur"],
        "reviewReason": "Bridges Section 01 policy reading into Section 02 technical environmental data interpretation.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Accurately extracts barometric pressure anomalies and ground frost depths from technical tables",
            "Identifies specific pasture areas categorized under critical ice crusting ('төмөр зуд')"
        ],
        "masteryEvidence": "Identifies the meteorological triggers of surface ice crusting and maps the 3 most severely threatened pasture corridors from the bulletin.",
        "recommendedExerciseModalities": ["source_comparison", "claim_evidence_matching"]
    },
    {
        "lessonId": "les_b2_167_02_emergency_agency_acoustic_bulletin_listening",
        "unitId": "unit_b2_167_the_meteorology_of_dzud_frost_ice_s",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 2,
        "title": "Acoustic Warning: National Emergency Agency Severe Dzud Radio Alert",
        "lessonType": "listening",
        "primaryPurpose": "Interpret rapid, urgent emergency management announcements containing blizzard route closures, stranded herder coordinates, and livestock shelter advisories.",
        "communicativeOutcome": "Comprehend rapid spoken crisis alerts (145 wpm) and transcribe actionable safety directives and road closures.",
        "objectivesIntroduced": ["obj_b2_167_02_comprehend_crisis_broadcasts"],
        "objectivesPracticed": ["obj_b2_167_01_parse_synoptic_bulletins"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_a2_modal_permission_possibility_bolno", "gram_b1_voice_passive_gd"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_topic_prominence_intonation"],
        "phonologyReviewed": ["phono_b1_stress_focus_contrast"],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_24_crisis_management_advisories"],
        "communicativeFunctionsReviewed": [],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_ecology_climate_environment"],
        "previousVocabularyReused": ["онцгой байдал", "зам", "хаах", "малчин", "шуурга", "аврах"],
        "readingObjective": "",
        "listeningObjective": "Listen to a 3-minute NEMA radio emergency dispatch and log closed mountain passes, fuel depot rationing, and livestock shelter protocol.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "emergency broadcast",
        "pragmaticTarget": "urgent directive framing",
        "prerequisiteLessonIds": ["les_b2_167_01_siberian_anticyclone_meteorological_bulletin_reading"],
        "reviewsLessonIds": ["les_b2_164_02_spokesperson_briefing_listening"],
        "reviewsUnitIds": ["unit_b2_164_press_conference_simulation_spokes"],
        "reviewReason": "Extends spokesperson acoustic parsing to live disaster response radio alerts.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Expose learners to rapid multi-region emergency dispatches with authentic radio static and acoustic urgency.",
        "successCriteria": [
            "Transcribes 4 closed mountain passes and the mandated livestock sheltering restrictions without error",
            "Identifies the priority evacuation zones based on blizzard velocity indicators"
        ],
        "masteryEvidence": "Produces an accurate emergency routing log detailing blocked roads and relief convoy staging locations from the broadcast.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "stance_identification"]
    },
    {
        "lessonId": "les_b2_167_03_livestock_emergency_evacuation_advisory_writing",
        "unitId": "unit_b2_167_the_meteorology_of_dzud_frost_ice_s",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 3,
        "title": "Advisory Composition: Herder Wintering & Fodder Allocation Warning",
        "lessonType": "writing",
        "primaryPurpose": "Draft structured crisis advisories detailing otar migration permits, emergency hay reserves distribution, and livestock hypothermia prevention.",
        "communicativeOutcome": "Author an authoritative 240-word district crisis advisory specifying pasture closures and emergency fodder distribution quotas.",
        "objectivesIntroduced": ["obj_b2_167_03_draft_crisis_advisories"],
        "objectivesPracticed": ["obj_b2_167_01_parse_synoptic_bulletins"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_a1_case_dative_locative_temporal", "gram_b2_discourse_causal_consequence_uuden_ulmaar"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_24_crisis_management_advisories"],
        "communicativeFunctionsReviewed": ["comm_b2_10_drafting_press_releases"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 3,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_ecology_climate_environment"],
        "previousVocabularyReused": ["өвөлжөө", "өвс", "тэжээл", "отор", "хуваарилалт", "хомсдол"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Draft a formal 240-word administrative emergency advisory instructing soum herders on otar pasture boundaries and rationed grain pickup.",
        "spokenProductionObjective": "",
        "registerTarget": "institutional administrative",
        "pragmaticTarget": "authoritative guidance",
        "prerequisiteLessonIds": ["les_b2_167_02_emergency_agency_acoustic_bulletin_listening"],
        "reviewsLessonIds": ["les_b2_164_03_crisis_press_release_drafting"],
        "reviewsUnitIds": ["unit_b2_164_press_conference_simulation_spokes"],
        "reviewReason": "Applies official press release drafting standards to environmental emergency advisory formulation.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Applies causal consequence morphology ('улмаас') to link snow depth to pasture closure",
            "Establishes precise dates, ration amounts, and regulatory penalties for unauthorized pasture trespass"
        ],
        "masteryEvidence": "Produces an advisory text evaluated as fully actionable and structurally compliant with Mongolian disaster response formats.",
        "recommendedExerciseModalities": ["summary_writing", "paragraph_reconstruction"]
    },
    {
        "lessonId": "les_b2_167_04_provincial_emergency_press_briefing_speech",
        "unitId": "unit_b2_167_the_meteorology_of_dzud_frost_ice_s",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 4,
        "title": "Spoken Delivery: Aimag Disaster Commission Crisis Press Briefing",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver an oral situation report summarizing provincial livestock losses, road unblocking operations, and aid convoy logistics.",
        "communicativeOutcome": "Deliver a 3-minute formal crisis briefing outlining provincial relief efforts with measured oratorical cadence and clear evidential framing.",
        "objectivesIntroduced": ["obj_b2_167_04_deliver_crisis_briefing"],
        "objectivesPracticed": ["obj_b2_167_02_comprehend_crisis_broadcasts", "obj_b2_167_03_draft_crisis_advisories"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_a1_verb_tense_past_witnessed_laa", "gram_b1_voice_passive_gd"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_formal_presentation_cadence"],
        "phonologyReviewed": ["phono_b2_discourse_chunking_cadence"],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_24_crisis_management_advisories"],
        "communicativeFunctionsReviewed": ["comm_b2_07_delivering_prepared_presentations"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 3,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_ecology_climate_environment"],
        "previousVocabularyReused": ["аймаг", "хохирол", "тусламж", "цуваа", "хүргэх", "нөхцөл"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Deliver a 3-minute oral briefing presenting current dzud casualty statistics and deployed snow-clearing machinery.",
        "registerTarget": "institutional formal",
        "pragmaticTarget": "calibrated reassurance",
        "prerequisiteLessonIds": ["les_b2_167_03_livestock_emergency_evacuation_advisory_writing"],
        "reviewsLessonIds": ["les_b2_164_04_press_briefing_delivery_spoken"],
        "reviewsUnitIds": ["unit_b2_164_press_conference_simulation_spokes"],
        "reviewReason": "Translates spokesperson delivery protocols into regional environmental disaster briefings.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide an exemplar regional governor disaster briefing modeling measured pace and grave vocal resonance.",
        "successCriteria": [
            "Presents casualty and relief statistics using formal numerical classifier constructions",
            "Sustains unbroken institutional cadence and authoritative tone throughout the 3-minute address"
        ],
        "masteryEvidence": "Speech recording demonstrates accurate statistical reporting and flawless deployment of emergency logistics terminology.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
    },
    {
        "lessonId": "les_b2_167_05_comparative_district_vulnerability_memo_writing",
        "unitId": "unit_b2_167_the_meteorology_of_dzud_frost_ice_s",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 5,
        "title": "Analytical Memorandum: Cross-Soum Dzud Vulnerability & Risk Tiering",
        "lessonType": "writing",
        "primaryPurpose": "Synthesize meteorological data, livestock herd numbers, and fodder stock levels into an executive risk tiering memorandum.",
        "communicativeOutcome": "Author a 250-word policy memorandum categorizing 4 districts into Red, Orange, and Yellow disaster risk tiers.",
        "objectivesIntroduced": ["obj_b2_167_05_tier_disaster_vulnerability"],
        "objectivesPracticed": ["obj_b2_167_01_parse_synoptic_bulletins", "obj_b2_167_03_draft_crisis_advisories"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_a1_numerals_cardinal_counting", "gram_b2_discourse_causal_consequence_uuden_ulmaar"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_24_crisis_management_advisories"],
        "communicativeFunctionsReviewed": ["comm_b2_06_evaluating_public_policies"],
        "newProductiveLemmaTarget": 4,
        "newReceptiveLemmaTarget": 3,
        "newProductiveExpressionTarget": 1,
        "newReceptiveExpressionTarget": 0,
        "lexicalDomains": ["lex_b2_ecology_climate_environment"],
        "previousVocabularyReused": ["эрсдэл", "зэрэглэл", "суурь", "нөөц", "дүн шинжилгээ", "хэрэгжилт"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Author a 250-word memorandum ranking 4 soums by vulnerability score based on snowpack density and herd composition.",
        "spokenProductionObjective": "",
        "registerTarget": "institutional administrative",
        "pragmaticTarget": "institutional neutrality",
        "prerequisiteLessonIds": ["les_b2_167_04_provincial_emergency_press_briefing_speech"],
        "reviewsLessonIds": ["les_b2_166_04_municipal_policy_brief_drafting"],
        "reviewsUnitIds": ["unit_b2_166_public_policy_capstone_municipal_ur"],
        "reviewReason": "Adapts urban municipal policy brief frameworks to rural disaster risk ranking.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Justifies district risk classification using empirical fodder-to-animal ratios",
            "Formulates 3 actionable mitigation priorities tailored to the highest-risk district"
        ],
        "masteryEvidence": "Produces a vulnerability memorandum with clear hierarchical heading structure and defensible analytical ratings.",
        "recommendedExerciseModalities": ["summary_writing", "argument_mapping"]
    },

    # -------------------------------------------------------------------------
    # UNIT 168: Gradual Proportional Converb (-тусам/-түсэм) (Grammar Unit)
    # Budget: PL=26, RL=22, PE=8, RE=5. 4 lessons.
    # -------------------------------------------------------------------------
    {
        "lessonId": "les_b2_168_01_gradual_proportional_converb_syntax_intro",
        "unitId": "unit_b2_168_gradual_proportional_converb_suffix",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 1,
        "title": "Morphosyntax: Gradual Proportional Converb Suffixes '-тусам/-түсэм'",
        "lessonType": "grammar_introduction",
        "primaryPurpose": "Introduce the morphophonology, syntactic distribution, and semantic function of the gradual proportional converb (-тусам/-түсэм) expressing correlated change ('the more... the more...').",
        "communicativeOutcome": "Construct complex paired sentences expressing proportional environmental acceleration using -тусам/-түсэм.",
        "objectivesIntroduced": ["obj_b2_168_01_master_proportional_converb"],
        "objectivesPracticed": [],
        "objectivesReviewed": ["obj_b2_167_01_parse_synoptic_bulletins"],
        "grammarIntroduced": ["gram_b2_converb_gradual_proportional_tusam"],
        "grammarPracticed": ["gram_a1_verb_tense_present_habitual_dag"],
        "grammarReviewed": ["gram_b2_particles_emphatic_nuance"],
        "phonologyIntroduced": ["phono_b2_complex_causal_contour"],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": ["comm_b2_13_expressing_proportional_growth"],
        "communicativeFunctionsPracticed": [],
        "communicativeFunctionsReviewed": ["comm_b2_12_expository_causal_chains"],
        "newProductiveLemmaTarget": 7,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_ecology_climate_environment"],
        "previousVocabularyReused": ["өсөх", "нэмэгдэх", "буурах", "хүйтрэх", "зузаарах"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Formulate 6 proportional environmental change statements linking temperature drops to livestock caloric depletion using -тусам/-түсэм.",
        "spokenProductionObjective": "",
        "registerTarget": "scientific academic",
        "pragmaticTarget": "analytical precision",
        "prerequisiteLessonIds": ["les_b2_167_05_comparative_district_vulnerability_memo_writing"],
        "reviewsLessonIds": ["les_b2_162_02_particles_pragmatic_syntax_intro"],
        "reviewsUnitIds": ["unit_b2_162_pragmatic_emphatic_nuance_particles"],
        "reviewReason": "Integrates pragmatic particle nuance with proportional subordinating clausal architecture.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Correctly applies back-vowel (-тусам) versus front-vowel (-түсэм) harmony to consonant and vocalic verb stems",
            "Aligns the dependent converbial clause with a corresponding matrix clause predicate indicating proportional escalation"
        ],
        "masteryEvidence": "Accurately completes 8 sentence transformation items converting parallel trends into -тусам proportional complex sentences.",
        "recommendedExerciseModalities": ["word_transformation", "sentence_reordering", "error_analysis"]
    },
    {
        "lessonId": "les_b2_168_02_pasture_degradation_correlations_reading",
        "unitId": "unit_b2_168_gradual_proportional_converb_suffix",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 2,
        "title": "Ecological Research: Exponential Overgrazing & Pasture Biomass Depletion",
        "lessonType": "reading",
        "primaryPurpose": "Analyze a specialized botanical report tracing how increases in herd density proportionally degrade palatable steppe vegetation cover.",
        "communicativeOutcome": "Interpret proportional scientific correlations in a 340-word academic study on pasture carrying capacities.",
        "objectivesIntroduced": ["obj_b2_168_02_read_pasture_degradation_studies"],
        "objectivesPracticed": ["obj_b2_168_01_master_proportional_converb"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_converb_gradual_proportional_tusam", "gram_b1_voice_reciprocal_collective"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_13_expressing_proportional_growth", "comm_b2_20_interpreting_graphs_statistics"],
        "communicativeFunctionsReviewed": [],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 7,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_b2_ecology_climate_environment"],
        "previousVocabularyReused": ["бэлчээр", "даац", "доройтол", "ургамал", "сүрэг", "тоо"],
        "readingObjective": "Read a 340-word academic pasture study and trace 4 proportional degradation thresholds using -тусам syntactic structures.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "scientific academic",
        "pragmaticTarget": "evidential caution",
        "prerequisiteLessonIds": ["les_b2_168_01_gradual_proportional_converb_syntax_intro"],
        "reviewsLessonIds": ["les_b2_158_01_discourse_converb_chaining_analysis"],
        "reviewsUnitIds": ["unit_b2_158_converb_chaining_in_complex_discour"],
        "reviewReason": "Expands multi-tier converb parsing to specialized proportional ecological discourse.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Identifies the mathematical tipping points where increased goat populations trigger irreversible topsoil erosion",
            "Extracts proportional arguments without conflating cause and correlative consequence"
        ],
        "masteryEvidence": "Completes a rigorous argument map matching 4 pasture degradation factors to their specific proportional impacts.",
        "recommendedExerciseModalities": ["argument_mapping", "source_comparison"]
    },
    {
        "lessonId": "les_b2_168_03_pasture_carrying_capacity_oral_briefing",
        "unitId": "unit_b2_168_gradual_proportional_converb_suffix",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 3,
        "title": "Oral Analysis: Presenting Proportional Herd Pressure to Pasture Committees",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver an oral briefing to local herder cooperative leaders demonstrating how continued herd expansion proportionally diminishes winter survival odds.",
        "communicativeOutcome": "Explain complex ecological trade-offs in a 3-minute persuasive address using -тусам/-түсэм and measured evidential rhetoric.",
        "objectivesIntroduced": ["obj_b2_168_03_deliver_carrying_capacity_briefing"],
        "objectivesPracticed": ["obj_b2_168_01_master_proportional_converb", "obj_b2_168_02_read_pasture_degradation_studies"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_converb_gradual_proportional_tusam", "gram_a2_modal_ability_yadah_chadah"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_complex_causal_contour", "phono_b2_formal_presentation_cadence"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_13_expressing_proportional_growth"],
        "communicativeFunctionsReviewed": ["comm_b2_01_participating_formal_debates"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 4,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_ecology_climate_environment"],
        "previousVocabularyReused": ["хоршоо", "тэжээх", "үр дагавар", "хасах", "хязгаар", "шийдвэр"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Deliver a 3-minute oral presentation urging herder cooperatives to cull non-breeding stock as winter approaches using -тусам.",
        "registerTarget": "professional consultative",
        "pragmaticTarget": "persuasive framing",
        "prerequisiteLessonIds": ["les_b2_168_02_pasture_degradation_correlations_reading"],
        "reviewsLessonIds": ["les_b2_160_04_keynote_persuasive_presentation"],
        "reviewsUnitIds": ["unit_b2_160_rhetorical_connectors_macro_discour"],
        "reviewReason": "Synthesizes macro-rhetorical signposting with proportional clausal cadence in persuasive environmental advocacy.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide benchmark recording of agricultural extension agent delivering persuasive pasture management briefing.",
        "successCriteria": [
            "Deploys at least 3 distinct -тусам/-түсэм constructions with correct vowel harmony during spoken delivery",
            "Maintains natural rising intonation on proportional clauses and decisive falling tone on main conclusions"
        ],
        "masteryEvidence": "Learner speech achieves high persuasive clarity and demonstrates correct prosodic handling of proportional clauses.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
    },
    {
        "lessonId": "les_b2_168_04_climate_desertification_analytical_summary_writing",
        "unitId": "unit_b2_168_gradual_proportional_converb_suffix",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 4,
        "title": "Written Synthesis: Long-Term Steppe Aridification & Degradation Trends",
        "lessonType": "writing",
        "primaryPurpose": "Author an analytical summary condensing multi-year environmental observations into an executive report on desertification progression.",
        "communicativeOutcome": "Draft a 260-word technical summary demonstrating proportional links between declining soil moisture and vegetative shift.",
        "objectivesIntroduced": ["obj_b2_168_04_write_aridification_summary"],
        "objectivesPracticed": ["obj_b2_168_01_master_proportional_converb", "obj_b2_168_02_read_pasture_degradation_studies"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_converb_gradual_proportional_tusam", "gram_b2_particles_emphatic_nuance"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_13_expressing_proportional_growth"],
        "communicativeFunctionsReviewed": ["comm_b2_11_summarizing_complex_articles"],
        "newProductiveLemmaTarget": 7,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_ecology_climate_environment"],
        "previousVocabularyReused": ["цөлжилт", "чийг", "хөрс", "умард", "өөрчлөлт", "хурдац"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Author a 260-word technical synthesis comparing 20-year precipitation declines with progressive grassland degradation.",
        "spokenProductionObjective": "",
        "registerTarget": "scientific academic",
        "pragmaticTarget": "institutional neutrality",
        "prerequisiteLessonIds": ["les_b2_168_03_pasture_carrying_capacity_oral_briefing"],
        "reviewsLessonIds": ["les_b2_166_03_stakeholder_position_synthesis_writing"],
        "reviewsUnitIds": ["unit_b2_166_public_policy_capstone_municipal_ur"],
        "reviewReason": "Transfers multi-stakeholder synthesis writing to empirical climate degradation trend reporting.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Seamlessly integrates -тусам/-түсэм to show multi-tiered ecological causality",
            "Preserves objective scholarly stance without emotional exaggeration of desertification rates"
        ],
        "masteryEvidence": "Produces an executive summary that clearly explains proportional correlations and meets academic publishing conventions.",
        "recommendedExerciseModalities": ["summary_writing", "paragraph_reconstruction"]
    }
]

print(f"Loaded {len(lessons)} lessons for Units 167-168.")
