# -*- coding: utf-8 -*-
"""Authoring and serialization for B2 Section 02 (Units 167-176)."""
import json

with open("curriculum/blueprint/units/b2.json") as f:
    b2_units = {u["unitId"]: u for u in json.load(f)}

# Load unit 167 from earlier
from generate_sec02_data import lessons as sec02_lessons

# Add Unit 168 (4 lessons)
sec02_lessons.extend([
    {
        "lessonId": "les_b2_168_01_gradual_proportional_converb_syntax_intro",
        "unitId": "unit_b2_168_gradual_proportional_converb_suffix",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 1,
        "title": "Morphosyntax: Gradual Proportional Converb Suffixes '-тусам/-түсэм'",
        "lessonType": "grammar_introduction",
        "primaryPurpose": "Introduce the morphophonology, syntactic distribution, and semantic function of the gradual proportional converb (-тусам/-түсэм) expressing correlated change ('the more... the more...').",
        "communicativeOutcome": "Construct complex paired sentences expressing proportional environmental acceleration using -тусам/-түсэм.",
        "objectivesIntroduced": ["obj_b2_168_01_master_proportional_converb"],
        "objectivesPracticed": [],
        "objectivesReviewed": ["obj_b2_167_01_parse_synoptic_bulletins"],
        "grammarIntroduced": ["gram_b2_converb_gradual_proportional_tusam"],
        "grammarPracticed": ["gram_a1_verb_tense_present_habitual_dag"],
        "grammarReviewed": ["gram_b2_particles_emphatic_nuance"],
        "phonologyIntroduced": ["phono_b2_complex_causal_contour"],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": ["comm_b2_13_expressing_proportional_growth"],
        "communicativeFunctionsPracticed": [],
        "communicativeFunctionsReviewed": ["comm_b2_12_expository_causal_chains"],
        "newProductiveLemmaTarget": 7,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_ecology_climate_environment"],
        "previousVocabularyReused": ["өсөх", "нэмэгдэх", "буурах", "хүйтрэх", "зузаарах"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Formulate 6 proportional environmental change statements linking temperature drops to livestock caloric depletion using -тусам/-түсэм.",
        "spokenProductionObjective": "",
        "registerTarget": "scientific academic",
        "pragmaticTarget": "analytical precision",
        "prerequisiteLessonIds": ["les_b2_167_05_comparative_district_vulnerability_memo_writing"],
        "reviewsLessonIds": ["les_b2_162_02_particles_pragmatic_syntax_intro"],
        "reviewsUnitIds": ["unit_b2_162_pragmatic_emphatic_nuance_particles"],
        "reviewReason": "Integrates pragmatic particle nuance with proportional subordinating clausal architecture.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Correctly applies back-vowel (-тусам) versus front-vowel (-түсэм) harmony to consonant and vocalic verb stems",
            "Aligns the dependent converbial clause with a corresponding matrix clause predicate indicating proportional escalation"
        ],
        "masteryEvidence": "Accurately completes 8 sentence transformation items converting parallel trends into -тусам proportional complex sentences.",
        "recommendedExerciseModalities": ["word_transformation", "sentence_reordering", "error_analysis"]
    },
    {
        "lessonId": "les_b2_168_02_pasture_degradation_correlations_reading",
        "unitId": "unit_b2_168_gradual_proportional_converb_suffix",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 2,
        "title": "Ecological Research: Exponential Overgrazing & Pasture Biomass Depletion",
        "lessonType": "reading",
        "primaryPurpose": "Analyze a specialized botanical report tracing how increases in herd density proportionally degrade palatable steppe vegetation cover.",
        "communicativeOutcome": "Interpret proportional scientific correlations in a 340-word academic study on pasture carrying capacities.",
        "objectivesIntroduced": ["obj_b2_168_02_read_pasture_degradation_studies"],
        "objectivesPracticed": ["obj_b2_168_01_master_proportional_converb"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_converb_gradual_proportional_tusam", "gram_b1_voice_reciprocal_collective"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_13_expressing_proportional_growth", "comm_b2_20_interpreting_graphs_statistics"],
        "communicativeFunctionsReviewed": [],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 7,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_b2_ecology_climate_environment"],
        "previousVocabularyReused": ["бэлчээр", "даац", "доройтол", "ургамал", "сүрэг", "тоо"],
        "readingObjective": "Read a 340-word academic pasture study and trace 4 proportional degradation thresholds using -тусам syntactic structures.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "scientific academic",
        "pragmaticTarget": "evidential caution",
        "prerequisiteLessonIds": ["les_b2_168_01_gradual_proportional_converb_syntax_intro"],
        "reviewsLessonIds": ["les_b2_158_01_discourse_converb_chaining_analysis"],
        "reviewsUnitIds": ["unit_b2_158_converb_chaining_in_complex_discour"],
        "reviewReason": "Expands multi-tier converb parsing to specialized proportional ecological discourse.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Identifies the mathematical tipping points where increased goat populations trigger irreversible topsoil erosion",
            "Extracts proportional arguments without conflating cause and correlative consequence"
        ],
        "masteryEvidence": "Completes a rigorous argument map matching 4 pasture degradation factors to their specific proportional impacts.",
        "recommendedExerciseModalities": ["argument_mapping", "source_comparison"]
    },
    {
        "lessonId": "les_b2_168_03_pasture_carrying_capacity_oral_briefing",
        "unitId": "unit_b2_168_gradual_proportional_converb_suffix",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 3,
        "title": "Oral Analysis: Presenting Proportional Herd Pressure to Pasture Committees",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver an oral briefing to local herder cooperative leaders demonstrating how continued herd expansion proportionally diminishes winter survival odds.",
        "communicativeOutcome": "Explain complex ecological trade-offs in a 3-minute persuasive address using -тусам/-түсэм and measured evidential rhetoric.",
        "objectivesIntroduced": ["obj_b2_168_03_deliver_carrying_capacity_briefing"],
        "objectivesPracticed": ["obj_b2_168_01_master_proportional_converb", "obj_b2_168_02_read_pasture_degradation_studies"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_converb_gradual_proportional_tusam", "gram_a2_modal_ability_yadah_chadah"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_complex_causal_contour", "phono_b2_formal_presentation_cadence"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_13_expressing_proportional_growth"],
        "communicativeFunctionsReviewed": ["comm_b2_01_participating_formal_debates"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 4,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_ecology_climate_environment"],
        "previousVocabularyReused": ["хоршоо", "тэжээх", "үр дагавар", "хасах", "хязгаар", "шийдвэр"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Deliver a 3-minute oral presentation urging herder cooperatives to cull non-breeding stock as winter approaches using -тусам.",
        "registerTarget": "professional consultative",
        "pragmaticTarget": "persuasive framing",
        "prerequisiteLessonIds": ["les_b2_168_02_pasture_degradation_correlations_reading"],
        "reviewsLessonIds": ["les_b2_160_04_keynote_persuasive_presentation"],
        "reviewsUnitIds": ["unit_b2_160_rhetorical_connectors_macro_discour"],
        "reviewReason": "Synthesizes macro-rhetorical signposting with proportional clausal cadence in persuasive environmental advocacy.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide benchmark recording of agricultural extension agent delivering persuasive pasture management briefing.",
        "successCriteria": [
            "Deploys at least 3 distinct -тусам/-түсэм constructions with correct vowel harmony during spoken delivery",
            "Maintains natural rising intonation on proportional clauses and decisive falling tone on main conclusions"
        ],
        "masteryEvidence": "Learner speech achieves high persuasive clarity and demonstrates correct prosodic handling of proportional clauses.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
    },
    {
        "lessonId": "les_b2_168_04_climate_desertification_analytical_summary_writing",
        "unitId": "unit_b2_168_gradual_proportional_converb_suffix",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 4,
        "title": "Written Synthesis: Long-Term Steppe Aridification & Degradation Trends",
        "lessonType": "writing",
        "primaryPurpose": "Author an analytical summary condensing multi-year environmental observations into an executive report on desertification progression.",
        "communicativeOutcome": "Draft a 260-word technical summary demonstrating proportional links between declining soil moisture and vegetative shift.",
        "objectivesIntroduced": ["obj_b2_168_04_write_aridification_summary"],
        "objectivesPracticed": ["obj_b2_168_01_master_proportional_converb", "obj_b2_168_02_read_pasture_degradation_studies"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_converb_gradual_proportional_tusam", "gram_b2_particles_emphatic_nuance"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_13_expressing_proportional_growth"],
        "communicativeFunctionsReviewed": ["comm_b2_11_summarizing_complex_articles"],
        "newProductiveLemmaTarget": 7,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b2_ecology_climate_environment"],
        "previousVocabularyReused": ["цөлжилт", "чийг", "хөрс", "умард", "өөрчлөлт", "хурдац"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Author a 260-word technical synthesis comparing 20-year precipitation declines with progressive grassland degradation.",
        "spokenProductionObjective": "",
        "registerTarget": "scientific academic",
        "pragmaticTarget": "institutional neutrality",
        "prerequisiteLessonIds": ["les_b2_168_03_pasture_carrying_capacity_oral_briefing"],
        "reviewsLessonIds": ["les_b2_166_03_stakeholder_position_synthesis_writing"],
        "reviewsUnitIds": ["unit_b2_166_public_policy_capstone_municipal_ur"],
        "reviewReason": "Transfers multi-stakeholder synthesis writing to empirical climate degradation trend reporting.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Seamlessly integrates -тусам/-түсэм to show multi-tiered ecological causality",
            "Preserves objective scholarly stance without emotional exaggeration of desertification rates"
        ],
        "masteryEvidence": "Produces an executive summary that clearly explains proportional correlations and meets academic publishing conventions.",
        "recommendedExerciseModalities": ["summary_writing", "paragraph_reconstruction"]
    }
])

print(f"Added Unit 168. Total lessons: {len(sec02_lessons)}")
