# -*- coding: utf-8 -*-
"""Authoring Units 192-197 of Section 04 and validating full section."""
import json
from build_sec04_part2 import sec04_lessons

# UNIT 192: Delivering Prepared Academic Conference Presentations (4 lessons)
# Budget: PL=24, RL=21, PE=8, RE=5
sec04_lessons.extend([
    {
        "lessonId": "les_b2_192_01_conference_presentation_structure_reading",
        "unitId": "unit_b2_192_delivering_prepared_academic_confer",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 1,
        "title": "Academic Reading: Rhetorical Architecture & Slide Pacing in International Symposia",
        "lessonType": "reading",
        "primaryPurpose": "Parse a 380-word scholarly guide on structuring 15-minute conference presentations in Mongolistics, optimizing slide economy and transition rhetoric.",
        "communicativeOutcome": "Extract oratorical framing strategies, slide transition formulas, and visual data commentary conventions from a presentation manual.",
        "objectivesIntroduced": ["obj_b2_192_01_read_presentation_guidelines"],
        "objectivesPracticed": [],
        "objectivesReviewed": ["obj_b2_191_03_write_dissertation_abstract"],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b1_voice_passive_gd", "gram_b1_clause_temporal_omno_daraa_yed"],
        "grammarReviewed": ["gram_b2_participle_relative_subject_genitive_alternation"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": ["comm_b2_07_delivering_prepared_presentations"],
        "communicativeFunctionsPracticed": [],
        "communicativeFunctionsReviewed": ["comm_b2_21_academic_abstract_formulation"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 8,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c1_academic_philology_mongolistics"],
        "previousVocabularyReused": ["хурлын илтгэл", "слайд", "бүтэц", "шилжилт", "дүрслэл", "илтгэгч"],
        "readingObjective": "Read a 380-word guide on academic presentation rhetoric and extract 4 slide transition formulas.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "academic instructional",
        "pragmaticTarget": "presentation rhetorical analysis",
        "prerequisiteLessonIds": ["les_b2_191_05_dissertation_council_examination_listening"],
        "reviewsLessonIds": ["les_b2_191_03_scholarly_dissertation_abstract_writing"],
        "reviewsUnitIds": ["unit_b2_191_relative_clause_subject_genitive_no"],
        "reviewReason": "Translates written dissertation abstracts into spoken conference presentation planning.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Identifies passive verb forms (-гд/-гд) used in objective scientific slide descriptions",
            "Maps timing benchmarks across introduction, methodology, findings, and implications"
        ],
        "masteryEvidence": "Completes a 15-minute conference slide timing script aligned with standard international symposia rubrics.",
        "recommendedExerciseModalities": ["source_comparison", "claim_evidence_matching"]
    },
    {
        "lessonId": "les_b2_192_02_keynote_conference_presentation_listening",
        "unitId": "unit_b2_192_delivering_prepared_academic_confer",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 2,
        "title": "Acoustic Dissection: Keynote Paper at the International Congress of Mongolists",
        "lessonType": "listening",
        "primaryPurpose": "Listen to an authentic 4-minute conference address on 13th-century postal relay (Өртөө) administrative registers delivered to an international assembly.",
        "communicativeOutcome": "Comprehend complex academic conference oratory, slide transition cues, and rhetorical signposting in live conference audio (150 wpm).",
        "objectivesIntroduced": ["obj_b2_192_02_comprehend_conference_keynotes"],
        "objectivesPracticed": ["obj_b2_192_01_read_presentation_guidelines"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_conditionals_hypothetical_present", "gram_b2_participle_relative_subject_genitive_alternation"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_formal_presentation_cadence", "phono_b2_topic_prominence_intonation"],
        "phonologyReviewed": ["phono_b1_stress_focus_contrast"],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_07_delivering_prepared_presentations"],
        "communicativeFunctionsReviewed": ["comm_b2_21_academic_abstract_formulation"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_academic_philology_mongolistics"],
        "previousVocabularyReused": ["өртөө", "захиргаа", "албан бичиг", "судлаач", "дэлхий дахин", "чуулган"],
        "readingObjective": "",
        "listeningObjective": "Listen to a 4-minute conference recording and log 3 distinct rhetorical signposts used to pivot between methodology and archival findings.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "academic keynote",
        "pragmaticTarget": "formal conference signposting",
        "prerequisiteLessonIds": ["les_b2_192_01_conference_presentation_structure_reading"],
        "reviewsLessonIds": ["les_b2_185_02_silk_road_epic_poetry_roundtable_listening"],
        "reviewsUnitIds": ["unit_b2_185_cross_cultural_comparative_heritage"],
        "reviewReason": "Extends roundtable discussion listening to formal academic solo keynote conference presentations.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide authentic lecture hall acoustic recording of senior historian presenting slides at International Congress of Mongolists.",
        "successCriteria": [
            "Transcribes exact transition markers ('дараагийн слайдад анхаарлаа хандуулна уу', 'үүнтэй холбогдуулан') without error",
            "Differentiates between primary empirical evidence and speculative concluding remarks"
        ],
        "masteryEvidence": "Produces a conference presentation outline mapping the speaker's rhetorical progression.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "stance_identification"]
    },
    {
        "lessonId": "les_b2_192_03_slide_script_and_handout_drafting_writing",
        "unitId": "unit_b2_192_delivering_prepared_academic_confer",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 3,
        "title": "Academic Writing: Conference Slide Commentary Script & Executive Handout",
        "lessonType": "writing",
        "primaryPurpose": "Author a 260-word conference presentation spoken script accompanying 4 presentation slides, detailing empirical findings on nomadic pastoral ecology.",
        "communicativeOutcome": "Author a high-density academic spoken script integrating slide signposting, quantitative data citations, and theoretical implications.",
        "objectivesIntroduced": ["obj_b2_192_03_write_conference_script"],
        "objectivesPracticed": ["obj_b2_192_01_read_presentation_guidelines", "obj_b2_192_02_comprehend_conference_keynotes"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b1_voice_passive_gd", "gram_b2_participle_relative_subject_genitive_alternation"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_07_delivering_prepared_presentations"],
        "communicativeFunctionsReviewed": ["comm_b2_20_interpreting_graphs_statistics"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 4,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_academic_philology_mongolistics"],
        "previousVocabularyReused": ["илтгэлийн эх", "товч хураангуй", "хүснэгт", "график", "диаграмм", "нотолгоо"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Author a 260-word presentation script coordinating spoken narration with 4 academic presentation slides.",
        "spokenProductionObjective": "",
        "registerTarget": "academic presentation script",
        "pragmaticTarget": "tight verbal-visual coordination",
        "prerequisiteLessonIds": ["les_b2_192_02_keynote_conference_presentation_listening"],
        "reviewsLessonIds": ["les_b2_191_03_scholarly_dissertation_abstract_writing"],
        "reviewsUnitIds": ["unit_b2_191_relative_clause_subject_genitive_no"],
        "reviewReason": "Translates dissertation abstract synthesis into live conference slide commentary drafting.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Includes explicit slide change prompts and verbal indicators directing audience gaze",
            "Synthesizes complex quantitative data concisely without reading raw numbers monotonously"
        ],
        "masteryEvidence": "Produces a presentation script judged as compliant with international conference delivery standards.",
        "recommendedExerciseModalities": ["summary_writing", "paragraph_reconstruction"]
    },
    {
        "lessonId": "les_b2_192_04_delivering_academic_conference_talk_speech",
        "unitId": "unit_b2_192_delivering_prepared_academic_confer",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 4,
        "title": "Spoken Oratory: Delivering 4-Minute Academic Paper at International Symposium",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver a formal 4-minute academic conference presentation from authored slides, demonstrating flawless rhetorical transitions and scholarly presence.",
        "communicativeOutcome": "Deliver a 4-minute academic conference paper with polished oratorical cadence, clear slide signposts, and authoritative vocal delivery.",
        "objectivesIntroduced": ["obj_b2_192_04_deliver_conference_paper"],
        "objectivesPracticed": ["obj_b2_192_01_read_presentation_guidelines", "obj_b2_192_03_write_conference_script"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_conditionals_hypothetical_present", "gram_b2_participle_relative_subject_genitive_alternation"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_formal_presentation_cadence", "phono_b2_topic_prominence_intonation"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_07_delivering_prepared_presentations"],
        "communicativeFunctionsReviewed": ["comm_b2_21_academic_abstract_formulation"],
        "newProductiveLemmaTarget": 7,
        "newReceptiveLemmaTarget": 4,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_academic_philology_mongolistics"],
        "previousVocabularyReused": ["эрдэмтэн", "сонсогчид", "сэдэв", "нээлт", "үр дүн", "тайлагнах"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Deliver a 4-minute academic paper presenting archival discoveries at an international Mongolistics symposium.",
        "registerTarget": "academic symposium oratorical",
        "pragmaticTarget": "charismatic scholarly delivery",
        "prerequisiteLessonIds": ["les_b2_192_03_slide_script_and_handout_drafting_writing"],
        "reviewsLessonIds": ["les_b2_191_04_dissertation_defense_opening_speech"],
        "reviewsUnitIds": ["unit_b2_191_relative_clause_subject_genitive_no"],
        "reviewReason": "Synthesizes dissertation defense opening with dynamic multi-slide conference presentation delivery.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide benchmark recording of conference presenter delivering slides with consummate oratorical poise.",
        "successCriteria": [
            "Executes seamless verbal-visual transitions while maintaining continuous audience engagement",
            "Finishes precisely within the 4-minute window without rushed concluding cadences"
        ],
        "masteryEvidence": "Speech recording confirms exceptional academic oratory, immaculate syntax, and professional conference delivery.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
    }
])

# UNIT 193: Handling Rigorous Academic Q&A Sessions (4 lessons)
# Budget: PL=24, RL=21, PE=8, RE=5
sec04_lessons.extend([
    {
        "lessonId": "les_b2_193_01_adversarial_qa_audio_analysis_listening",
        "unitId": "unit_b2_193_handling_rigorous_academic_q_a_sess",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 1,
        "title": "Acoustic Dissection: Rapid-Fire Academic Q&A Exchange at International Congress",
        "lessonType": "listening",
        "primaryPurpose": "Listen to a rigorous 3.5-minute Q&A session where audience scholars challenge a presenter's statistical sampling, archival dating, and ideological presuppositions.",
        "communicativeOutcome": "Comprehend rapid spoken questions containing embedded academic critique, rhetorical traps, and skepticism (155 wpm).",
        "objectivesIntroduced": ["obj_b2_193_01_comprehend_adversarial_qa"],
        "objectivesPracticed": [],
        "objectivesReviewed": ["obj_b2_192_04_deliver_conference_paper"],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_a1_polar_questions_uu_uu", "gram_a1_content_questions_be_ve"],
        "grammarReviewed": ["gram_b2_converb_gradual_proportional_tusam"],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_topic_prominence_intonation"],
        "phonologyReviewed": ["phono_b1_stress_focus_contrast"],
        "communicativeFunctionsIntroduced": ["comm_b2_08_handling_qa_sessions"],
        "communicativeFunctionsPracticed": [],
        "communicativeFunctionsReviewed": ["comm_b2_07_delivering_prepared_presentations"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 8,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c1_academic_philology_mongolistics"],
        "previousVocabularyReused": ["асуулт хариулт", "лавлах", "тодруулах", "шүүмжлэх", "маргаан", "хурлын танхим"],
        "readingObjective": "",
        "listeningObjective": "Listen to a 3.5-minute Q&A audio recording and log 3 pointed methodological challenges posed by the audience.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "academic adversarial",
        "pragmaticTarget": "discerning interrogative intent",
        "prerequisiteLessonIds": ["les_b2_192_04_delivering_academic_conference_talk_speech"],
        "reviewsLessonIds": ["les_b2_191_05_dissertation_council_examination_listening"],
        "reviewsUnitIds": ["unit_b2_191_relative_clause_subject_genitive_no"],
        "reviewReason": "Extends dissertation council examination listening to live open-floor conference Q&A exchanges.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide authentic lecture hall recording of audience members asking rapid, challenging questions via roving microphones.",
        "successCriteria": [
            "Separates polite introductory preambles from the stinging substantive core of the question",
            "Identifies interrogative intonational peaks and pragmatic presuppositions in audience queries"
        ],
        "masteryEvidence": "Produces an accurate summary breakdown of the 3 questions and presenter's responsive strategies.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "stance_identification"]
    },
    {
        "lessonId": "les_b2_193_02_qa_defensive_tactics_reading",
        "unitId": "unit_b2_193_handling_rigorous_academic_q_a_sess",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 2,
        "title": "Academic Reading: Diplomatic Evasion & Deflective Reframing in Academic Discourse",
        "lessonType": "reading",
        "primaryPurpose": "Parse a 370-word academic guide analyzing rhetorical tactics for reframing hostile questions, buying time, acknowledging empirical limits, and neutralizing false premises.",
        "communicativeOutcome": "Extract communicative formulas for diplomatic concession, question reframing, and boundary setting in academic defense.",
        "objectivesIntroduced": ["obj_b2_193_02_read_qa_tactics"],
        "objectivesPracticed": ["obj_b2_193_01_comprehend_adversarial_qa"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b1_voice_reciprocal_collective", "gram_b2_modal_complex_obligation_uchirtai"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_08_handling_qa_sessions"],
        "communicativeFunctionsReviewed": ["comm_b2_02_academic_essay_concessions"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_academic_philology_mongolistics"],
        "previousVocabularyReused": ["хариу няцаалт", "чиглүүлэх", "эелдгээр татгалзах", "хүрээ хязгаар", "хүлээж авах"],
        "readingObjective": "Read a 370-word treatise on academic rhetoric and categorize 4 formulas for reframing hostile premises.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "academic rhetorical analysis",
        "pragmaticTarget": "deflective diplomacy",
        "prerequisiteLessonIds": ["les_b2_193_01_adversarial_qa_audio_analysis_listening"],
        "reviewsLessonIds": ["les_b2_192_01_conference_presentation_structure_reading"],
        "reviewsUnitIds": ["unit_b2_192_delivering_prepared_academic_confer"],
        "reviewReason": "Extends presentation guideline reading into advanced Q&A defense and reframing strategies.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Identifies polite deflection phrases ('маш сонирхолтой асуулт байна, гэхдээ бидний судалгааны хүрээнд...')",
            "Analyzes reciprocal voice verbs (-лц/-лц) used in collaborative academic reframing"
        ],
        "masteryEvidence": "Completes a tactical response taxonomy matching 4 hostile query archetypes to optimal responses.",
        "recommendedExerciseModalities": ["source_comparison", "claim_evidence_matching"]
    },
    {
        "lessonId": "les_b2_193_03_spontaneous_qa_rebuttal_speech",
        "unitId": "unit_b2_193_handling_rigorous_academic_q_a_sess",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 3,
        "title": "Spoken Oratory: Defending Conference Paper Against Audience Cross-Examination",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver spontaneous 3-minute spoken responses to 2 sharp audience challenges regarding archival authenticity and sample representativeness.",
        "communicativeOutcome": "Deliver poised, articulate spoken responses neutralizing audience skepticism with collegial grace and evidential firmness.",
        "objectivesIntroduced": ["obj_b2_193_03_rebut_academic_challenges"],
        "objectivesPracticed": ["obj_b2_193_01_comprehend_adversarial_qa", "obj_b2_193_02_read_qa_tactics"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_modal_complex_obligation_uchirtai", "gram_b2_converb_gradual_proportional_tusam"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_formal_presentation_cadence", "phono_b2_topic_prominence_intonation"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_08_handling_qa_sessions"],
        "communicativeFunctionsReviewed": ["comm_b2_01_participating_formal_debates"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 4,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_academic_philology_mongolistics"],
        "previousVocabularyReused": ["хариулах", "тодотгох", "санал нийлэх", "байр суурь", "нотолгоо дурдах"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Deliver two 90-second spoken rebuttals addressing audience critiques regarding manuscript transcription errors.",
        "registerTarget": "academic extemporaneous",
        "pragmaticTarget": "collegial composure and firm rebuttal",
        "prerequisiteLessonIds": ["les_b2_193_02_qa_defensive_tactics_reading"],
        "reviewsLessonIds": ["les_b2_192_04_delivering_academic_conference_talk_speech"],
        "reviewsUnitIds": ["unit_b2_192_delivering_prepared_academic_confer"],
        "reviewReason": "Synthesizes prepared conference delivery with spontaneous, high-pressure Q&A defense.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide benchmark recording of scholar handling challenging conference question with poise and precision.",
        "successCriteria": [
            "Maintains unshakable collegial courtesy while firmly dismantling the factual basis of the critique",
            "Deploys '-х учиртай' to clarify theoretical boundaries without aggressive confrontation"
        ],
        "masteryEvidence": "Speech recording reflects extraordinary extemporaneous poise, flawless grammar, and persuasive authority.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
    },
    {
        "lessonId": "les_b2_193_04_moderating_contentious_academic_panel_speech",
        "unitId": "unit_b2_193_handling_rigorous_academic_q_a_sess",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 4,
        "title": "Spoken Oratory: Chairing a Contentious Conference Session & Regulating Floor Debate",
        "lessonType": "spoken_production",
        "primaryPurpose": "Simulate the role of session chair, diplomatically intervening to cut off overlong audience questions, defusing personal attacks, and summarizing panel outcomes.",
        "communicativeOutcome": "Deliver 3-minute executive moderator interventions maintaining parliamentary order, scholarly decorum, and strict time limits.",
        "objectivesIntroduced": ["obj_b2_193_04_chair_contentious_sessions"],
        "objectivesPracticed": ["obj_b2_193_02_read_qa_tactics", "obj_b2_193_03_rebut_academic_challenges"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_a2_numerals_ordinal", "gram_b1_voice_reciprocal_collective"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_formal_presentation_cadence", "phono_b2_topic_prominence_intonation"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_08_handling_qa_sessions"],
        "communicativeFunctionsReviewed": ["comm_b2_09_moderating_group_discussions"],
        "newProductiveLemmaTarget": 7,
        "newReceptiveLemmaTarget": 4,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_academic_philology_mongolistics"],
        "previousVocabularyReused": ["хуралдаан даргалагч", "цаг дуусах", "үг өгөх", "дүрэм сахих", "эелдэг шаардлага"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Deliver three 1-minute chair interventions regulating floor discussions and concluding an academic session.",
        "registerTarget": "academic session chair",
        "pragmaticTarget": "authoritative diplomatic regulation",
        "prerequisiteLessonIds": ["les_b2_193_03_spontaneous_qa_rebuttal_speech"],
        "reviewsLessonIds": ["les_b2_180_04_debating_cultural_commercialization_spoken"],
        "reviewsUnitIds": ["unit_b2_180_concessive_contrast_discourse_conju"],
        "reviewReason": "Applies parliamentary debate moderation skills to high-level academic conference session chairing.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide model audio of international conference chair managing heated floor debate with diplomatic authority.",
        "successCriteria": [
            "Intervenes with polite but unyielding authority to enforce question length limits",
            "Synthesizes opposing scholarly interventions into an elegant closing synthesis"
        ],
        "masteryEvidence": "Speech recording reflects consummate diplomatic authority, calm leadership, and superb timing.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
    }
])

# UNIT 194: Commercial Legal Contract Parsing & Lease Clauses (4 lessons)
# Budget: PL=24, RL=21, PE=8, RE=5
sec04_lessons.extend([
    {
        "lessonId": "les_b2_194_01_commercial_lease_statutory_parsing_reading",
        "unitId": "unit_b2_194_commercial_legal_contract_parsing_l",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 1,
        "title": "Legal Reading: Commercial Real Estate Lease Agreements & Liability Clauses",
        "lessonType": "reading",
        "primaryPurpose": "Parse a 390-word commercial lease contract governed by the Mongolian Civil Code, analyzing default remedies, security deposit escrow, and force majeure stipulations.",
        "communicativeOutcome": "Comprehend statutory legal terminology, conditional default triggers, and contractual indemnification provisions in formal contract Mongolian.",
        "objectivesIntroduced": ["obj_b2_194_01_parse_commercial_contracts"],
        "objectivesPracticed": [],
        "objectivesReviewed": ["obj_b2_190_02_read_ethics_charters"],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_a1_case_dative_locative_temporal", "gram_b1_aspect_intensive_chih_complete"],
        "grammarReviewed": ["gram_b2_converb_durative_adversative_saar_baital"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": ["comm_b2_16_legal_contract_comprehension"],
        "communicativeFunctionsPracticed": [],
        "communicativeFunctionsReviewed": ["comm_b2_02_academic_essay_concessions"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 8,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": ["түрээсийн гэрээ", "хариуцлага", "үл хөдлөх хөрөнгө", "торгууль", "цуцлах", "хохирол"],
        "readingObjective": "Read a 390-word commercial contract and isolate 4 clauses defining lessee default liabilities and cure periods.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "statutory jurisprudence",
        "pragmaticTarget": "contractual legal parsing",
        "prerequisiteLessonIds": ["les_b2_193_04_moderating_contentious_academic_panel_speech"],
        "reviewsLessonIds": ["les_b2_171_02_supreme_court_pasture_expropriation_reading"],
        "reviewsUnitIds": ["unit_b2_171_stacked_voice_causative_passive_mor"],
        "reviewReason": "Bridges supreme court jurisprudence reading into private commercial contract parsing.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Identifies exact monetary penalties and legal notification timelines for contractual breach",
            "Distinguishes between discretionary termination rights and automatic statutory voiding"
        ],
        "masteryEvidence": "Completes a contract compliance matrix correctly mapping 4 potential breach scenarios to legal remedies.",
        "recommendedExerciseModalities": ["source_comparison", "claim_evidence_matching"]
    },
    {
        "lessonId": "les_b2_194_02_contractual_amendment_drafting_writing",
        "unitId": "unit_b2_194_commercial_legal_contract_parsing_l",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 2,
        "title": "Legal Writing: Drafting Contractual Amendments & Indemnification Protocols",
        "lessonType": "writing",
        "primaryPurpose": "Draft a formal 260-word contractual addendum amending liability limits, rent indexation benchmarks, and dispute arbitration venues.",
        "communicativeOutcome": "Author legally binding contractual clauses conforming to statutory Mongolian drafting standards and precision syntax.",
        "objectivesIntroduced": ["obj_b2_194_02_draft_contract_addenda"],
        "objectivesPracticed": ["obj_b2_194_01_parse_commercial_contracts"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_purposive_distinctions_gej_khaar_tuld", "gram_b2_participle_relative_subject_genitive_alternation"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_16_legal_contract_comprehension"],
        "communicativeFunctionsReviewed": ["comm_b2_21_academic_abstract_formulation"],
        "newProductiveLemmaTarget": 7,
        "newReceptiveLemmaTarget": 4,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": ["нэмэлт өөрчлөлт", "хавсралт", "нөхөн төлбөр", "арбитрын шүүх", "хүчин төгөлдөр"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Author a 260-word contractual amendment modifying force majeure relief and early termination penalties.",
        "spokenProductionObjective": "",
        "registerTarget": "formal contractual legal",
        "pragmaticTarget": "statutory precision drafting",
        "prerequisiteLessonIds": ["les_b2_194_01_commercial_lease_statutory_parsing_reading"],
        "reviewsLessonIds": ["les_b2_190_03_academic_integrity_declaration_writing"],
        "reviewsUnitIds": ["unit_b2_190_complex_modal_obligation_the_modal_"],
        "reviewReason": "Synthesizes integrity declaration drafting with binding commercial contract addendum authoring.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Deploys purposive clausal markers and genitive-subject relatives to draft unambiguous legal stipulations",
            "Leaves zero loopholes regarding indemnification liability and jurisdiction"
        ],
        "masteryEvidence": "Produces a contract amendment evaluated as legally sound and enforceable by legal counsel.",
        "recommendedExerciseModalities": ["summary_writing", "paragraph_reconstruction"]
    },
    {
        "lessonId": "les_b2_194_03_commercial_contract_negotiation_listening",
        "unitId": "unit_b2_194_commercial_legal_contract_parsing_l",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 3,
        "title": "Acoustic Dissection: Commercial Lease Negotiation Between Corporate Attorneys",
        "lessonType": "listening",
        "primaryPurpose": "Listen to a 3.5-minute audio recording of corporate lawyers vigorously negotiating liability caps, maintenance obligations, and rent abatements.",
        "communicativeOutcome": "Comprehend rapid legal bargaining, conditional concessions, and tactical compromises in spoken commercial negotiations (150 wpm).",
        "objectivesIntroduced": ["obj_b2_194_03_comprehend_contract_bargaining"],
        "objectivesPracticed": ["obj_b2_194_01_parse_commercial_contracts"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_converb_durative_adversative_saar_baital", "gram_b2_purposive_distinctions_gej_khaar_tuld"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_topic_prominence_intonation"],
        "phonologyReviewed": ["phono_b1_stress_focus_contrast"],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_16_legal_contract_comprehension"],
        "communicativeFunctionsReviewed": ["comm_b2_02_academic_essay_concessions"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": ["хуульч", "хэлэлцээр", "буулт хийх", "заалт", "тохиролцоо", "эрх ашиг"],
        "readingObjective": "",
        "listeningObjective": "Listen to a 3.5-minute negotiation recording and log 3 contractual compromises achieved on repair liabilities.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "commercial legal negotiation",
        "pragmaticTarget": "discerning tactical legal positions",
        "prerequisiteLessonIds": ["les_b2_194_02_contractual_amendment_drafting_writing"],
        "reviewsLessonIds": ["les_b2_175_02_tense_bilateral_negotiation_listening"],
        "reviewsUnitIds": ["unit_b2_175_commercial_resource_negotiations_pa"],
        "reviewReason": "Translates resource dispute negotiation listening to corporate commercial lease bargaining dialogues.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide authentic spoken dialogue between corporate attorneys sparring over contract clauses.",
        "successCriteria": [
            "Differentiates between non-negotiable statutory terms and flexible commercial clauses",
            "Identifies adversative converb constructions ('-саар байтал') used to highlight unfulfilled contractual commitments"
        ],
        "masteryEvidence": "Produces an executive summary table tracking offer and counter-offer sequences for 3 disputed clauses.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "stance_identification"]
    },
    {
        "lessonId": "les_b2_194_04_closing_contractual_arbitration_speech",
        "unitId": "unit_b2_194_commercial_legal_contract_parsing_l",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 4,
        "title": "Spoken Oratory: Oral Argumentation Before the International Commercial Arbitration Court",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver a formal 3.5-minute oral argument before an arbitration panel, demonstrating that the opposing party breached explicit lease obligations without legal justification.",
        "communicativeOutcome": "Deliver a 3.5-minute formal legal argument deploying rigorous statutory terminology and contractual citations with judicial poise.",
        "objectivesIntroduced": ["obj_b2_194_04_deliver_arbitration_argument"],
        "objectivesPracticed": ["obj_b2_194_01_parse_commercial_contracts", "obj_b2_194_02_draft_contract_addenda"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_converb_durative_adversative_saar_baital", "gram_b2_participle_relative_subject_genitive_alternation"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_formal_presentation_cadence", "phono_b2_complex_causal_contour"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_16_legal_contract_comprehension"],
        "communicativeFunctionsReviewed": ["comm_b2_01_participating_formal_debates"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 4,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": ["арбитр", "нэхэмжлэл", "зөрчил", "гэрээний заалт", "гомдол", "шийдвэрлэх"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Deliver a 3.5-minute arbitration argument demonstrating breach of commercial lease terms.",
        "registerTarget": "formal judicial arbitration",
        "pragmaticTarget": "persuasive legal advocacy",
        "prerequisiteLessonIds": ["les_b2_194_03_commercial_contract_negotiation_listening"],
        "reviewsLessonIds": ["les_b2_175_05_closing_argumentation_water_rights_speech"],
        "reviewsUnitIds": ["unit_b2_175_commercial_resource_negotiations_pa"],
        "reviewReason": "Synthesizes bilateral negotiation closing speeches into formal commercial arbitration tribunal argumentation.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide benchmark speech of legal counsel delivering closing oral arguments before arbitration tribunal.",
        "successCriteria": [
            "Deploys formal judicial formulas ('Хүндэт арбитрын бүрэлдэхүүн ээ') with impeccable propriety",
            "Directs evidence clearly to specific contractual clauses and statutory civil code articles"
        ],
        "masteryEvidence": "Speech recording reflects consummate judicial oratorical dignity and flawless statutory precision.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
    }
])

# UNIT 195: Mediation of Professional Conflicts Between Peers (4 lessons)
# Budget: PL=24, RL=21, PE=8, RE=5
sec04_lessons.extend([
    {
        "lessonId": "les_b2_195_01_workplace_conflict_dialogue_listening",
        "unitId": "unit_b2_195_mediation_of_professional_conflicts",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 1,
        "title": "Acoustic Dissection: Tense Professional Conflict Between Research Lab Directors",
        "lessonType": "listening",
        "primaryPurpose": "Listen to a 3.5-minute recording of a heated dispute between two project leads over intellectual credit, budget reallocation, and doctoral student supervision.",
        "communicativeOutcome": "Comprehend emotional undertones, suppressed grievances, and conflicting professional interests in spoken workplace conflict (150 wpm).",
        "objectivesIntroduced": ["obj_b2_195_01_comprehend_workplace_conflict"],
        "objectivesPracticed": [],
        "objectivesReviewed": ["obj_b2_194_03_comprehend_contract_bargaining"],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_a1_possessive_pronouns_minii_chiniih", "gram_a1_case_dative_locative_recipient"],
        "grammarReviewed": ["gram_b2_converb_negative_framing_guigeer"],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_topic_prominence_intonation"],
        "phonologyReviewed": ["phono_b1_stress_focus_contrast"],
        "communicativeFunctionsIntroduced": ["comm_b2_19_conflict_mediation_peers"],
        "communicativeFunctionsPracticed": [],
        "communicativeFunctionsReviewed": ["comm_b2_09_moderating_group_discussions"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 8,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_b1_education_career_workplace"],
        "previousVocabularyReused": ["зөрчил", "маргаан", "хамт олон", "бухимдал", "хариуцлага", "гомдоллох"],
        "readingObjective": "",
        "listeningObjective": "Listen to a 3.5-minute dispute dialogue and identify 3 underlying root causes fueling the professional conflict.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "workplace conversational",
        "pragmaticTarget": "discerning affective undertones",
        "prerequisiteLessonIds": ["les_b2_194_04_closing_contractual_arbitration_speech"],
        "reviewsLessonIds": ["les_b2_194_03_commercial_contract_negotiation_listening"],
        "reviewsUnitIds": ["unit_b2_194_commercial_legal_contract_parsing_l"],
        "reviewReason": "Translates formal legal negotiation listening to interpersonal professional workplace mediation.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide multi-speaker audio of professional peers engaging in realistic workplace dispute with natural emotional tension.",
        "successCriteria": [
            "Distinguishes between personal grievances and legitimate institutional operational complaints",
            "Identifies instances of negative framing converbs ('-лгүйгээр') signaling perceived injustice"
        ],
        "masteryEvidence": "Produces an analytical conflict assessment report diagnosing root causes and emotional stakes.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "stance_identification"]
    },
    {
        "lessonId": "les_b2_195_02_principled_mediation_guide_reading",
        "unitId": "unit_b2_195_mediation_of_professional_conflicts",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 2,
        "title": "Professional Reading: Principled Negotiation & Peer Conflict Mediation Frameworks",
        "lessonType": "reading",
        "primaryPurpose": "Parse a 380-word organizational psychology manual on non-violent communication, neutral reframing, and interest-based peer mediation protocols in research institutes.",
        "communicativeOutcome": "Extract mediation methodologies, de-escalation formulas, and shared interest identification strategies from a professional manual.",
        "objectivesIntroduced": ["obj_b2_195_02_read_mediation_manuals"],
        "objectivesPracticed": ["obj_b2_195_01_comprehend_workplace_conflict"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_a2_reflexive_possessive_base", "gram_b2_converb_negative_framing_guigeer"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_19_conflict_mediation_peers"],
        "communicativeFunctionsReviewed": ["comm_b2_02_academic_essay_concessions"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b1_education_career_workplace"],
        "previousVocabularyReused": ["эвлэрүүлэн зуучлах", "шийдэл", "харилцан ойлголцол", "ашиг сонирхол", "зохицуулах"],
        "readingObjective": "Read a 380-word mediation manual and extract 4 verbal formulas for de-escalating personal accusations.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "organizational professional",
        "pragmaticTarget": "conflict de-escalation analysis",
        "prerequisiteLessonIds": ["les_b2_195_01_workplace_conflict_dialogue_listening"],
        "reviewsLessonIds": ["les_b2_193_02_qa_defensive_tactics_reading"],
        "reviewsUnitIds": ["unit_b2_193_handling_rigorous_academic_q_a_sess"],
        "reviewReason": "Extends academic Q&A reframing reading to institutional conflict mediation protocols.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Identifies specific reframing syntax transforming positional demands into shared institutional needs",
            "Analyzes reflexive possessive pronouns (-аа/-ээ) framing shared collective ownership of outcomes"
        ],
        "masteryEvidence": "Completes a mediation workflow flowchart mapping 5 stages from grievance airing to binding compromise.",
        "recommendedExerciseModalities": ["source_comparison", "claim_evidence_matching"]
    },
    {
        "lessonId": "les_b2_195_03_spoken_mediation_intervention_speech",
        "unitId": "unit_b2_195_mediation_of_professional_conflicts",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 3,
        "title": "Spoken Oratory: Neutral Mediation Facilitation Between Disputing Department Heads",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver spoken mediation interventions guiding two disputing senior colleagues toward collaborative problem-solving, reframing accusations without judgment.",
        "communicativeOutcome": "Deliver 3.5-minute spoken mediation facilitations using neutral phrasing, empathic listening reflections, and balanced hypothetical solutions.",
        "objectivesIntroduced": ["obj_b2_195_03_facilitate_peer_mediation"],
        "objectivesPracticed": ["obj_b2_195_01_comprehend_workplace_conflict", "obj_b2_195_02_read_mediation_manuals"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_conditionals_hypothetical_present", "gram_b2_converb_negative_framing_guigeer"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_formal_presentation_cadence", "phono_b2_topic_prominence_intonation"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_19_conflict_mediation_peers"],
        "communicativeFunctionsReviewed": ["comm_b2_09_moderating_group_discussions"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 4,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b1_education_career_workplace"],
        "previousVocabularyReused": ["зуучлагч", "төвийг сахих", "сонсох", "хамтын ажиллагаа", "буулт", "итгэлцэл"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Deliver a 3.5-minute mediation intervention reframing departmental grievances into actionable co-authorship agreements.",
        "registerTarget": "professional mediation",
        "pragmaticTarget": "empathic neutral facilitation",
        "prerequisiteLessonIds": ["les_b2_195_02_principled_mediation_guide_reading"],
        "reviewsLessonIds": ["les_b2_193_04_moderating_contentious_academic_panel_speech"],
        "reviewsUnitIds": ["unit_b2_193_handling_rigorous_academic_q_a_sess"],
        "reviewReason": "Synthesizes conference moderation skills with sensitive interpersonal workplace mediation.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide model audio of experienced mediator de-escalating workplace dispute with soothing, neutral intonation.",
        "successCriteria": [
            "Maintains absolute neutrality, avoiding taking sides or assigning moral blame",
            "Deploys hypothetical conditionals ('хэрэв бид ингэж үзвэл...') to open creative settlement avenues"
        ],
        "masteryEvidence": "Speech recording reveals exemplary empathic resonance, calm leadership, and superior linguistic control.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
    },
    {
        "lessonId": "les_b2_195_04_written_mediation_agreement_protocol_writing",
        "unitId": "unit_b2_195_mediation_of_professional_conflicts",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 4,
        "title": "Professional Writing: Formal Workplace Mediation Resolution & Co-Working Agreement",
        "lessonType": "writing",
        "primaryPurpose": "Draft a 260-word formal Mediation Settlement Protocol signed by both parties, establishing mutual commitments, resource allocation schedules, and respectful communication norms.",
        "communicativeOutcome": "Author a professional workplace settlement protocol uniting mutual obligations, grievance releases, and monitoring schedules.",
        "objectivesIntroduced": ["obj_b2_195_04_write_mediation_protocol"],
        "objectivesPracticed": ["obj_b2_195_02_read_mediation_manuals", "obj_b2_195_03_facilitate_peer_mediation"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_a2_reflexive_possessive_base", "gram_b2_converb_negative_framing_guigeer"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_19_conflict_mediation_peers"],
        "communicativeFunctionsReviewed": ["comm_b2_16_legal_contract_comprehension"],
        "newProductiveLemmaTarget": 7,
        "newReceptiveLemmaTarget": 4,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b1_education_career_workplace"],
        "previousVocabularyReused": ["эвлэрлийн гэрээ", "протокол", "харилцан хүлээх үүрэг", "гарын үсэг зурах", "мөрдөх"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Author a 260-word mediation protocol resolving a lab resource dispute and outlining shared publication authorship.",
        "spokenProductionObjective": "",
        "registerTarget": "professional institutional protocol",
        "pragmaticTarget": "constructive conflict resolution",
        "prerequisiteLessonIds": ["les_b2_195_03_spoken_mediation_intervention_speech"],
        "reviewsLessonIds": ["les_b2_194_02_contractual_amendment_drafting_writing"],
        "reviewsUnitIds": ["unit_b2_194_commercial_legal_contract_parsing_l"],
        "reviewReason": "Translates formal contractual amendment drafting to human-centered workplace mediation protocols.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Balances legal enforceability with collaborative, relationship-healing institutional prose",
            "Clearly details specific milestones, check-in dates, and neutral grievance reporting channels"
        ],
        "masteryEvidence": "Produces a mediation agreement judged as balanced, binding, and professionally restorative.",
        "recommendedExerciseModalities": ["summary_writing", "paragraph_reconstruction"]
    }
])

# UNIT 196: Popularizing Scientific Discoveries for Mass Media (4 lessons)
# Budget: PL=24, RL=21, PE=8, RE=5
sec04_lessons.extend([
    {
        "lessonId": "les_b2_196_01_popular_science_journalism_reading",
        "unitId": "unit_b2_196_popularizing_scientific_discoveries",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 1,
        "title": "Media Reading: Transforming Complex Paleoclimatological Studies into Compelling Public Features",
        "lessonType": "reading",
        "primaryPurpose": "Parse a 390-word feature article published in a leading national periodical explaining tree-ring analysis of medieval Mongolian droughts to a general audience.",
        "communicativeOutcome": "Extract journalistic narrative hooks, metaphorical explanations of complex data, and accessibility strategies from popular science writing.",
        "objectivesIntroduced": ["obj_b2_196_01_read_popular_science"],
        "objectivesPracticed": [],
        "objectivesReviewed": ["obj_b2_195_02_read_mediation_manuals"],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_a2_reflexive_case_combinations", "gram_b2_voice_stacking_causative_passive"],
        "grammarReviewed": ["gram_b2_modal_complex_obligation_uchirtai"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": ["comm_b2_23_scientific_popular_articles"],
        "communicativeFunctionsPracticed": [],
        "communicativeFunctionsReviewed": ["comm_b2_11_summarizing_complex_articles"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 8,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_b1_media_digital_society"],
        "previousVocabularyReused": ["хялбаршуулах", "нийтлэл", "шинжлэх ухааны ололт", "модны цагираг", "олон нийт"],
        "readingObjective": "Read a 390-word science journalism feature and extract 3 metaphorical analogies used to explain dendrochronology data.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "popular science journalism",
        "pragmaticTarget": "scientific accessibility and engagement",
        "prerequisiteLessonIds": ["les_b2_195_04_written_mediation_agreement_protocol_writing"],
        "reviewsLessonIds": ["les_b2_174_01_ipcc_pastoral_adaptation_reading"],
        "reviewsUnitIds": ["unit_b2_174_interpreting_environmental_statisti"],
        "reviewReason": "Transforms technical IPCC climate reading into engaging popular mass media science features.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Identifies how stacked causative-passive verbs translate laboratory actions for general readers",
            "Differentiates between scientific rigor and sensationalized media distortion"
        ],
        "masteryEvidence": "Completes a media framing analysis evaluating clarity and scientific fidelity.",
        "recommendedExerciseModalities": ["source_comparison", "claim_evidence_matching"]
    },
    {
        "lessonId": "les_b2_196_02_science_feature_article_writing",
        "unitId": "unit_b2_196_popularizing_scientific_discoveries",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 2,
        "title": "Journalistic Writing: Authoring a 260-Word Popular Science Column on Genetic Archaeology",
        "lessonType": "writing",
        "primaryPurpose": "Author a 260-word popular science feature explaining ancient DNA discoveries from Bronze Age kurgans, translating technical genomic data into gripping civic history.",
        "communicativeOutcome": "Author an engaging popular science article combining accessible vocabulary, vivid imagery, and strict factual fidelity.",
        "objectivesIntroduced": ["obj_b2_196_02_write_popular_science_column"],
        "objectivesPracticed": ["obj_b2_196_01_read_popular_science"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_voice_stacking_causative_passive", "gram_b2_modal_complex_obligation_uchirtai"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_23_scientific_popular_articles"],
        "communicativeFunctionsReviewed": ["comm_b2_10_drafting_press_releases"],
        "newProductiveLemmaTarget": 7,
        "newReceptiveLemmaTarget": 4,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b1_media_digital_society"],
        "previousVocabularyReused": ["генетик", "булш бунхан", "шинэ нээлт", "археологи", "тайлбарлах", "уншигчид"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Author a 260-word popular science feature explaining how ancient genomics rewrite our understanding of Bronze Age migrations.",
        "spokenProductionObjective": "",
        "registerTarget": "popular science journalism",
        "pragmaticTarget": "captivating public education",
        "prerequisiteLessonIds": ["les_b2_196_01_popular_science_journalism_reading"],
        "reviewsLessonIds": ["les_b2_192_03_slide_script_and_handout_drafting_writing"],
        "reviewsUnitIds": ["unit_b2_192_delivering_prepared_academic_confer"],
        "reviewReason": "Translates academic conference slide scripting into engaging journalistic science writing.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Avoids dense jargon while accurately explaining genomic sequencing concepts",
            "Crafts an irresistible opening hook and concludes with thought-provoking cultural reflections"
        ],
        "masteryEvidence": "Produces an article evaluated as immediately publishable in national science periodicals.",
        "recommendedExerciseModalities": ["summary_writing", "paragraph_reconstruction"]
    },
    {
        "lessonId": "les_b2_196_03_radio_science_broadcasting_listening",
        "unitId": "unit_b2_196_popularizing_scientific_discoveries",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 3,
        "title": "Acoustic Dissection: National Public Radio Science Feature on Nomadic Biotechnology",
        "lessonType": "listening",
        "primaryPurpose": "Listen to a 3.5-minute radio documentary explaining traditional dairy fermentation microflora (айраг/ааруул) and modern probiotic research.",
        "communicativeOutcome": "Comprehend dynamic radio broadcasting techniques, soundscape overlays, and accessible scientific interviews (150 wpm).",
        "objectivesIntroduced": ["obj_b2_196_03_comprehend_science_broadcasts"],
        "objectivesPracticed": ["obj_b2_196_01_read_popular_science"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_a2_reflexive_case_combinations", "gram_b2_voice_stacking_causative_passive"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_topic_prominence_intonation"],
        "phonologyReviewed": ["phono_b1_stress_focus_contrast"],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_23_scientific_popular_articles"],
        "communicativeFunctionsReviewed": ["comm_b2_18_critiquing_artistic_exhibitions"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b1_media_digital_society"],
        "previousVocabularyReused": ["радио нэвтрүүлэг", "исгэлт", "хөрөнгө", "биотехнологи", "эрүүл мэнд"],
        "readingObjective": "",
        "listeningObjective": "Listen to a 3.5-minute radio broadcast and log 3 scientific benefits of traditional lactic acid bacteria explained by the biochemist.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "public broadcast journalism",
        "pragmaticTarget": "broadcast science comprehension",
        "prerequisiteLessonIds": ["les_b2_196_02_science_feature_article_writing"],
        "reviewsLessonIds": ["les_b2_181_03_ancient_court_musicology_interview_listening"],
        "reviewsUnitIds": ["unit_b2_181_epistemic_stance_presumption_the_ma"],
        "reviewReason": "Extends cultural radio interviews to fast-paced popular science broadcasting comprehension.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide authentic public radio audio featuring narrator voice, field recordings, and scientist soundbites.",
        "successCriteria": [
            "Transcribes exact popular analogies used to describe microscopic bacterial communities",
            "Identifies transitions between audio narrative segments and laboratory expert commentary"
        ],
        "masteryEvidence": "Produces an executive radio feature summary detailing the science narrative structure.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "stance_identification"]
    },
    {
        "lessonId": "les_b2_196_04_popular_science_tv_interview_speech",
        "unitId": "unit_b2_196_popularizing_scientific_discoveries",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 4,
        "title": "Spoken Oratory: Live Television Interview Explaining Complex Scientific Breakthroughs",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver an engaging 3.5-minute live television studio interview explaining astronomical discoveries made at the Khurel Togoot Observatory to a mass audience.",
        "communicativeOutcome": "Deliver an articulate, charismatic broadcast interview translating complex astrophysics into compelling public knowledge.",
        "objectivesIntroduced": ["obj_b2_196_04_deliver_science_tv_interview"],
        "objectivesPracticed": ["obj_b2_196_01_read_popular_science", "obj_b2_196_02_write_popular_science_column"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_modal_complex_obligation_uchirtai", "gram_b2_voice_stacking_causative_passive"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_formal_presentation_cadence", "phono_b2_topic_prominence_intonation"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_23_scientific_popular_articles"],
        "communicativeFunctionsReviewed": ["comm_b2_07_delivering_prepared_presentations"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 4,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_b1_media_digital_society"],
        "previousVocabularyReused": ["телевиз", "ярилцлага", "од орон", "дуран", "ертөнц", "сонирхуулах"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Deliver a 3.5-minute television interview explaining recent asteroid tracking breakthroughs without jargon.",
        "registerTarget": "broadcast media interview",
        "pragmaticTarget": "charismatic popular science communication",
        "prerequisiteLessonIds": ["les_b2_196_03_radio_science_broadcasting_listening"],
        "reviewsLessonIds": ["les_b2_193_03_spontaneous_qa_rebuttal_speech"],
        "reviewsUnitIds": ["unit_b2_193_handling_rigorous_academic_q_a_sess"],
        "reviewReason": "Transforms academic Q&A rebuttal poise into charismatic broadcast television communication.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide benchmark recording of scientist giving captivating live television interview.",
        "successCriteria": [
            "Uses vivid mental analogies and natural vocal modulation to maintain viewer fascination",
            "Communicates scientific wonder while maintaining strict empirical integrity"
        ],
        "masteryEvidence": "Speech recording reflects consummate broadcast charisma, exceptional diction, and effortless fluency.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
    }
])

# UNIT 197: B2 Vantage Capstone: Academic Symposium Abstract & Speech (6 lessons)
# Budget: PL=28, RL=25, PE=11, RE=7
sec04_lessons.extend([
    {
        "lessonId": "les_b2_197_01_plenary_symposium_dossier_reading",
        "unitId": "unit_b2_197_b2_vantage_capstone_academic_sympos",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 1,
        "title": "Capstone Reading: Multi-Disciplinary Symposium Dossier & Keynote Monograph",
        "lessonType": "reading",
        "primaryPurpose": "Parse an extensive 430-word academic symposium dossier integrating philology, legal jurisprudence, environmental economics, and mass communication.",
        "communicativeOutcome": "Synthesize multi-disciplinary academic theses, competing methodological paradigms, and strategic recommendations across 430 words of complex prose.",
        "objectivesIntroduced": ["obj_b2_197_01_parse_symposium_dossier"],
        "objectivesPracticed": [],
        "objectivesReviewed": ["obj_b2_192_01_read_presentation_guidelines", "obj_b2_194_01_parse_commercial_contracts"],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_a2_possessive_third_person_enclitic_ni", "gram_b2_voice_double_causative_delegated"],
        "grammarReviewed": ["gram_b2_participle_relative_subject_genitive_alternation"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": ["comm_b2_25_strategic_consultation"],
        "communicativeFunctionsPracticed": ["comm_b2_21_academic_abstract_formulation"],
        "communicativeFunctionsReviewed": ["comm_b2_07_delivering_prepared_presentations"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 8,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 3,
        "lexicalDomains": ["lex_c1_academic_philology_mongolistics"],
        "previousVocabularyReused": ["эрдэм шинжилгээний хурал", "нэгдсэн дүгнэлт", "салбар дундын", "илтгэл", "шинэ зуун"],
        "readingObjective": "Read a 430-word multidisciplinary symposium dossier synthesizing cultural, legal, and environmental research priorities.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "academic multi-disciplinary",
        "pragmaticTarget": "comprehensive scholarly synthesis",
        "prerequisiteLessonIds": ["les_b2_196_04_popular_science_tv_interview_speech"],
        "reviewsLessonIds": ["les_b2_187_01_research_methodology_epistemology_reading"],
        "reviewsUnitIds": ["unit_b2_187_scholarly_research_methodology_hypo"],
        "reviewReason": "Synthesizes initial epistemology reading into a comprehensive multi-disciplinary symposium dossier.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Extracts cross-cutting themes linking pastoral legal systems to sustainable ecological management",
            "Identifies enclitic possessive markers (-нь) establishing nuanced topical cohesion"
        ],
        "masteryEvidence": "Produces an executive symposium brief evaluating the interdisciplinary convergence across 4 papers.",
        "recommendedExerciseModalities": ["source_comparison", "claim_evidence_matching"]
    },
    {
        "lessonId": "les_b2_197_02_presidential_symposium_keynote_listening",
        "unitId": "unit_b2_197_b2_vantage_capstone_academic_sympos",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 2,
        "title": "Capstone Listening: Opening Plenary Address at World Congress of Mongolists",
        "lessonType": "listening",
        "primaryPurpose": "Listen to a 4-minute opening plenary address delivered by the President of the Mongolian Academy of Sciences, surveying a century of research and future directions.",
        "communicativeOutcome": "Comprehend elevated academic-oratorical discourse, visionary policy propositions, and historical synthesis in live plenary audio (155 wpm).",
        "objectivesIntroduced": ["obj_b2_197_02_comprehend_plenary_keynote"],
        "objectivesPracticed": ["obj_b2_197_01_parse_symposium_dossier"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_voice_double_causative_delegated", "gram_b2_participle_relative_subject_genitive_alternation"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_formal_presentation_cadence", "phono_b2_topic_prominence_intonation"],
        "phonologyReviewed": ["phono_b1_stress_focus_contrast"],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_07_delivering_prepared_presentations"],
        "communicativeFunctionsReviewed": ["comm_b2_25_strategic_consultation"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_academic_philology_mongolistics"],
        "previousVocabularyReused": ["ерөнхийлөгч", "нээлтийн үг", "зуун жил", "ирээдүй", "эрхэм эрдэмтэд"],
        "readingObjective": "",
        "listeningObjective": "Listen to a 4-minute plenary address and log 3 strategic research directives emphasized by the Academy President.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "plenary academic oratorical",
        "pragmaticTarget": "visionary academic comprehension",
        "prerequisiteLessonIds": ["les_b2_197_01_plenary_symposium_dossier_reading"],
        "reviewsLessonIds": ["les_b2_192_02_keynote_conference_presentation_listening"],
        "reviewsUnitIds": ["unit_b2_192_delivering_prepared_academic_confer"],
        "reviewReason": "Elevates regular conference keynote listening to the opening plenary address of the World Congress.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide authentic plenary hall acoustic recording of Academy President addressing international assembly.",
        "successCriteria": [
            "Transcribes exact strategic vision phrasing and double-causative constructions without error",
            "Identifies visionary policy shifts toward open-access digital Mongolistics infrastructure"
        ],
        "masteryEvidence": "Produces an executive briefing document outlining the centenary research strategy.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "stance_identification"]
    },
    {
        "lessonId": "les_b2_197_03_authoring_definitive_symposium_abstract_writing",
        "unitId": "unit_b2_197_b2_vantage_capstone_academic_sympos",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 3,
        "title": "Advisory Composition: Definitive Peer-Reviewed Symposium Abstract in Mongolistics",
        "lessonType": "writing",
        "primaryPurpose": "Author a definitive 260-word peer-reviewed symposium abstract summarizing groundbreaking research across linguistics, governance, or pastoral ecology.",
        "communicativeOutcome": "Author a pristine, high-density academic abstract demonstrating consummate mastery of all B2 Vantage grammatical and lexical competencies.",
        "objectivesIntroduced": ["obj_b2_197_03_author_definitive_abstract"],
        "objectivesPracticed": ["obj_b2_197_01_parse_symposium_dossier", "obj_b2_197_02_comprehend_plenary_keynote"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_participle_relative_subject_genitive_alternation", "gram_b2_purposive_distinctions_gej_khaar_tuld"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_21_academic_abstract_formulation"],
        "communicativeFunctionsReviewed": ["comm_b2_02_academic_essay_concessions"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 4,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_academic_philology_mongolistics"],
        "previousVocabularyReused": ["эрдэм шинжилгээний хураангуй", "шинэ үзэл баримтлал", "үр дүн", "ач холбогдол"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Author a 260-word definitive academic symposium abstract synthesizing archival research and theoretical modeling.",
        "spokenProductionObjective": "",
        "registerTarget": "academic abstract",
        "pragmaticTarget": "scholarly excellence",
        "prerequisiteLessonIds": ["les_b2_197_02_presidential_symposium_keynote_listening"],
        "reviewsLessonIds": ["les_b2_191_03_scholarly_dissertation_abstract_writing"],
        "reviewsUnitIds": ["unit_b2_191_relative_clause_subject_genitive_no"],
        "reviewReason": "Elevates dissertation abstract drafting to a definitive, publishable international symposium abstract.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Weaves complex relative clauses with genitive subjects into an effortlessly cohesive paragraph",
            "Synthesizes problem, hypothesis, methodology, evidence, and broader significance flawlessly"
        ],
        "masteryEvidence": "Produces an abstract judged as an exemplary benchmark for international conference acceptance.",
        "recommendedExerciseModalities": ["summary_writing", "paragraph_reconstruction"]
    },
    {
        "lessonId": "les_b2_197_04_strategic_academic_consultation_brief_writing",
        "unitId": "unit_b2_197_b2_vantage_capstone_academic_sympos",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 4,
        "title": "Advisory Composition: Strategic Policy Consultation Brief for State Academic Council",
        "lessonType": "writing",
        "primaryPurpose": "Draft a 270-word strategic advisory brief for the Prime Minister's Academic Advisory Board, recommending legislative reforms to protect intellectual property and funding.",
        "communicativeOutcome": "Author an authoritative, high-level policy advisory document translating academic research into concrete statutory recommendations.",
        "objectivesIntroduced": ["obj_b2_197_04_draft_strategic_consultation_brief"],
        "objectivesPracticed": ["obj_b2_197_03_author_definitive_abstract"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_modal_complex_obligation_uchirtai", "gram_b2_conditionals_hypothetical_present"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_25_strategic_consultation"],
        "communicativeFunctionsReviewed": ["comm_b2_06_evaluating_public_policies"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 4,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_academic_philology_mongolistics"],
        "previousVocabularyReused": ["бодлогын зөвлөмж", "стратеги", "шинэчлэл", "санхүүжилт", "урт хугацааны"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Author a 270-word strategic policy brief outlining reforms to strengthen scientific research infrastructure.",
        "spokenProductionObjective": "",
        "registerTarget": "executive strategic consultation",
        "pragmaticTarget": "actionable executive policy leadership",
        "prerequisiteLessonIds": ["les_b2_197_03_authoring_definitive_symposium_abstract_writing"],
        "reviewsLessonIds": ["les_b2_186_04_unesco_safeguarding_strategy_dossier_writing"],
        "reviewsUnitIds": ["unit_b2_186_performing_arts_capstone_musicologi"],
        "reviewReason": "Synthesizes cultural safeguarding strategy writing into national academic science policy drafting.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Deploys complex modal obligation ('-х учиртай') and hypothetical framing to urge decisive state action",
            "Structures recommendations with executive clarity, specific agency assignments, and quantifiable KPIs"
        ],
        "masteryEvidence": "Produces an advisory brief evaluated as meeting ministerial cabinet submission standards.",
        "recommendedExerciseModalities": ["summary_writing", "paragraph_reconstruction"]
    },
    {
        "lessonId": "les_b2_197_05_world_congress_plenary_speech",
        "unitId": "unit_b2_197_b2_vantage_capstone_academic_sympos",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 5,
        "title": "Spoken Oratory: Keynote Plenary Oration at the World Congress of Mongolists",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver an inspiring 4-minute plenary keynote address before 500 international scholars, articulating the enduring relevance of Mongolian civilization to global ecological and ethical challenges.",
        "communicativeOutcome": "Deliver a 4-minute commanding plenary address uniting deep academic scholarship, poetic rhetoric, and global visionary leadership.",
        "objectivesIntroduced": ["obj_b2_197_05_deliver_world_congress_plenary"],
        "objectivesPracticed": ["obj_b2_197_03_author_definitive_abstract", "obj_b2_197_04_draft_strategic_consultation_brief"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_a2_possessive_third_person_enclitic_ni", "gram_b2_participle_relative_subject_genitive_alternation"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_formal_presentation_cadence", "phono_b2_topic_prominence_intonation"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_07_delivering_prepared_presentations", "comm_b2_25_strategic_consultation"],
        "communicativeFunctionsReviewed": ["comm_b2_21_academic_abstract_formulation"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 3,
        "newProductiveExpressionTarget": 3,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_academic_philology_mongolistics"],
        "previousVocabularyReused": ["дэлхийн монголч эрдэмтэд", "чуулга уулзалт", "соёл иргэншил", "дэлхийн дахинд"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Deliver a 4-minute plenary keynote address inspiring international delegates on the ecological wisdom of nomadic civilization.",
        "registerTarget": "formal plenary oratorical",
        "pragmaticTarget": "inspirational intellectual leadership",
        "prerequisiteLessonIds": ["les_b2_197_04_strategic_academic_consultation_brief_writing"],
        "reviewsLessonIds": ["les_b2_186_05_symposium_keynote_oration_speech"],
        "reviewsUnitIds": ["unit_b2_186_performing_arts_capstone_musicologi"],
        "reviewReason": "Transforms musicology gala keynote oratory into the ultimate World Congress plenary address.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide benchmark recording of senior statesman and academician delivering World Congress plenary address.",
        "successCriteria": [
            "Integrates elevated classical proverbs and rigorous scientific data with majestic oratorical cadence",
            "Maintains unbroken emotional and intellectual connection with a global scholarly audience"
        ],
        "masteryEvidence": "Speech recording reflects consummate plenary eloquence, breathtaking prosodic control, and intellectual authority.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
    },
    {
        "lessonId": "les_b2_197_06_b2_vantage_culminating_academic_capstone",
        "unitId": "unit_b2_197_b2_vantage_capstone_academic_sympos",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 6,
        "title": "Culminating Capstone: Comprehensive B2 Vantage Level Synthesis & Defense",
        "lessonType": "synthesis_capstone",
        "primaryPurpose": "Synthesize all 42 Units and four broad domains of CEFR B2 Vantage—democratic governance, environmental resilience, material/performing arts culture, and academic synthesis—in a culminating multi-phase symposium simulation without introducing new vocabulary.",
        "communicativeOutcome": "Demonstrate complete, uncompromised CEFR B2 Vantage mastery across reading, listening, writing, and spoken performance across all 24 grammar structures.",
        "objectivesIntroduced": ["obj_b2_197_06_master_b2_vantage_capstone"],
        "objectivesPracticed": [
            "obj_b2_197_01_parse_symposium_dossier",
            "obj_b2_197_02_comprehend_plenary_keynote",
            "obj_b2_197_03_author_definitive_abstract",
            "obj_b2_197_04_draft_strategic_consultation_brief",
            "obj_b2_197_05_deliver_world_congress_plenary"
        ],
        "objectivesReviewed": [
            "obj_b2_156_01_master_converb_chaining",
            "obj_b2_166_06_master_public_policy_capstone",
            "obj_b2_176_06_b2_sec02_culminating_resilience_capstone",
            "obj_b2_186_06_master_performing_arts_capstone",
            "obj_b2_188_01_master_purposive_distinctions",
            "obj_b2_189_01_master_hypothetical_conditionals",
            "obj_b2_190_01_master_modal_obligation_uchirtai",
            "obj_b2_191_01_master_relative_subject_alternation"
        ],
        "grammarIntroduced": [],
        "grammarPracticed": [
            "gram_b2_purposive_distinctions_gej_khaar_tuld",
            "gram_b2_conditionals_hypothetical_present",
            "gram_b2_modal_complex_obligation_uchirtai",
            "gram_b2_participle_relative_subject_genitive_alternation"
        ],
        "grammarReviewed": [
            "gram_b2_converb_chaining_discourse",
            "gram_b2_converb_chaining_switch_reference",
            "gram_b2_discourse_connectors_rhetorical",
            "gram_b2_discourse_causal_consequence_uuden_ulmaar",
            "gram_b2_particles_emphatic_nuance",
            "gram_b2_voice_stacking_causative_passive",
            "gram_b2_voice_double_causative_delegated",
            "gram_b2_conditionals_counterfactual_past",
            "gram_b2_concessive_contrast_vch_gesen",
            "gram_b2_epistemic_stance_biz_baih",
            "gram_b2_epistemic_appearance_shig_baiana_yanzytai",
            "gram_b2_indirect_discourse_framing_verbs",
            "gram_b2_limiting_scalar_particles_buu_khel"
        ],
        "phonologyIntroduced": [],
        "phonologyPracticed": [
            "phono_b2_formal_presentation_cadence",
            "phono_b2_topic_prominence_intonation",
            "phono_b2_concessive_contrast_pitch",
            "phono_b2_epistemic_doubt_pitch",
            "phono_b2_complex_causal_contour"
        ],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": [
            "comm_b2_07_delivering_prepared_presentations",
            "comm_b2_08_handling_qa_sessions",
            "comm_b2_21_academic_abstract_formulation",
            "comm_b2_25_strategic_consultation"
        ],
        "communicativeFunctionsReviewed": [
            "comm_b2_01_participating_formal_debates",
            "comm_b2_02_academic_essay_concessions",
            "comm_b2_06_evaluating_public_policies",
            "comm_b2_11_summarizing_complex_articles",
            "comm_b2_16_legal_contract_comprehension",
            "comm_b2_17_cross_cultural_comparisons",
            "comm_b2_18_critiquing_artistic_exhibitions",
            "comm_b2_19_conflict_mediation_peers"
        ],
        "newProductiveLemmaTarget": 0,
        "newReceptiveLemmaTarget": 0,
        "newProductiveExpressionTarget": 0,
        "newReceptiveExpressionTarget": 0,
        "lexicalDomains": ["lex_c1_academic_philology_mongolistics"],
        "previousVocabularyReused": [
            "төрийн байгуулал", "экологийн тэнцвэр", "өв соёл", "эрдэм шинжилгээ", "хөгжил", "бодлого", "шинжлэх ухаан", "үнэ цэнэ"
        ],
        "readingObjective": "Read a comprehensive 450-word capstone dossier integrating governance, ecology, culture, and academic methodology.",
        "listeningObjective": "Listen to a composite 4-minute international congress audio stream featuring keynote presentation and rigorous audience Q&A.",
        "writingObjective": "Author a culminating 320-word Comprehensive Academic Symposium & Policy Synthesis Dossier combining abstract, legal-ethical declaration, and strategic consultation.",
        "spokenProductionObjective": "Deliver a 4.5-minute culminating plenary keynote speech followed by handling 2 simulated audience challenges with diplomatic poise and authoritative evidence.",
        "registerTarget": "academic executive plenary",
        "pragmaticTarget": "definitive B2 Vantage mastery",
        "prerequisiteLessonIds": ["les_b2_197_05_world_congress_plenary_speech"],
        "reviewsLessonIds": [
            "les_b2_166_06_b2_sec01_culminating_policy_capstone",
            "les_b2_176_06_b2_sec02_culminating_resilience_capstone",
            "les_b2_186_06_b2_sec03_culminating_musicological_capstone"
        ],
        "reviewsUnitIds": [
            "unit_b2_166_public_policy_capstone_deliber",
            "unit_b2_176_ecological_resilience_capstone_cris",
            "unit_b2_186_performing_arts_capstone_musicologi"
        ],
        "reviewReason": "Integrates all three previous Section capstones (Policy, Ecology, Arts) into the ultimate CEFR B2 Vantage level certification capstone.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide multi-track capstone audio recording with full conference hall reverberation, plenary keynote delivery, and audience Q&A exchanges.",
        "successCriteria": [
            "Effortlessly integrates all 24 authoritative B2 grammar structures in written synthesis and spoken plenary delivery",
            "Demonstrates complete operational fluency, academic precision, and diplomatic maturity at the full CEFR B2 Vantage level"
        ],
        "masteryEvidence": "Produces an exemplary 320-word academic dossier and delivers a 4.5-minute keynote address earning unanimous certification from the B2 Examination Board.",
        "recommendedExerciseModalities": [
            "oral_presentation_planning",
            "summary_writing",
            "rebuttal_transformation",
            "extended_listening_comprehension"
        ]
    }
])

print(f"Total Section 04 lessons authored: {len(sec04_lessons)}")

# Verify all 11 units in Section 04
with open("curriculum/blueprint/units/b2.json") as f:
    b2_units = {u["unitId"]: u for u in json.load(f)}

unit_sums = {}
for l in sec04_lessons:
    uid = l["unitId"]
    if uid not in unit_sums:
        unit_sums[uid] = {"PL": 0, "RL": 0, "PE": 0, "RE": 0, "count": 0}
    unit_sums[uid]["PL"] += l["newProductiveLemmaTarget"]
    unit_sums[uid]["RL"] += l["newReceptiveLemmaTarget"]
    unit_sums[uid]["PE"] += l["newProductiveExpressionTarget"]
    unit_sums[uid]["RE"] += l["newReceptiveExpressionTarget"]
    unit_sums[uid]["count"] += 1

mismatches = 0
for uid, sums in sorted(unit_sums.items()):
    u = b2_units[uid]
    exp = (u["newProductiveCoreLemmas"], u["newReceptiveCoreLemmas"], u["newProductiveExpressions"], u["newReceptiveExpressions"])
    act = (sums["PL"], sums["RL"], sums["PE"], sums["RE"])
    if exp != act:
        print(f"MISMATCH in {uid}: Expected {exp}, got {act}")
        mismatches += 1
    else:
        print(f"OK Unit {u['sequencePosition']}: {uid} ({sums['count']} lessons) -> {act}")

if mismatches == 0:
    print("ALL 11 UNITS IN SECTION 04 RECONCILED PERFECTLY!")
    with open("curriculum/lesson_blueprints/b2_section_04.json", "w", encoding="utf-8") as f:
        json.dump(sec04_lessons, f, indent=2, ensure_ascii=False)
    print("SAVED curriculum/lesson_blueprints/b2_section_04.json")
else:
    print(f"FAIL: Found {mismatches} mismatches.")
