# -*- coding: utf-8 -*-
"""Authoring Units 187-191 of Section 04."""
import json

sec04_lessons = []

# UNIT 187: Scholarly Research Methodology & Hypothesis Formulation (4 lessons)
# Budget: PL=24, RL=21, PE=8, RE=5
sec04_lessons.extend([
    {
        "lessonId": "les_b2_187_01_research_methodology_epistemology_reading",
        "unitId": "unit_b2_187_scholarly_research_methodology_hypo",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 1,
        "title": "Academic Reading: Epistemological Frameworks & Methodological Rigor in Mongolistics",
        "lessonType": "reading",
        "primaryPurpose": "Parse a 390-word foundational monograph on philological and historical methodology, examining qualitative archival inquiry versus quantitative corpus linguistics.",
        "communicativeOutcome": "Extract research hypotheses, epistemological assumptions, and methodological boundaries from an academic treatise.",
        "objectivesIntroduced": ["obj_b2_187_01_read_methodology_monographs"],
        "objectivesPracticed": [],
        "objectivesReviewed": ["obj_b2_186_01_parse_exhibition_catalogue"],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_a1_case_comitative_accompaniment", "gram_b1_noun_derivation_abstract_dal_laga"],
        "grammarReviewed": ["gram_b2_epistemic_stance_biz_baih"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": ["comm_b2_21_academic_abstract_formulation"],
        "communicativeFunctionsPracticed": [],
        "communicativeFunctionsReviewed": ["comm_b2_11_summarizing_complex_articles"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 8,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c1_academic_philology_mongolistics"],
        "previousVocabularyReused": ["арга зүй", "таамаглал", "судалгаа", "эх сурвалж", "шинжлэх ухаан", "зарчим"],
        "readingObjective": "Read a 390-word treatise and extract 3 core methodological criteria for validating 14th-century Mongolian manuscript transcriptions.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "academic epistemological",
        "pragmaticTarget": "scholarly methodological precision",
        "prerequisiteLessonIds": ["les_b2_186_06_b2_sec03_culminating_musicological_capstone"],
        "reviewsLessonIds": ["les_b2_186_01_comprehensive_exhibition_catalogue_reading"],
        "reviewsUnitIds": ["unit_b2_186_performing_arts_capstone_musicologi"],
        "reviewReason": "Bridges Section 03 musicological curatorial synthesis into Section 04 academic research methodology.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Differentiates empirical data gathering from interpretive theoretical frameworks",
            "Identifies abstract derivational nouns (-дал/-дэл, -лага/-лэгэ) used in scientific definitions"
        ],
        "masteryEvidence": "Completes a methodological paradigm matrix matching research questions to appropriate empirical approaches.",
        "recommendedExerciseModalities": ["source_comparison", "claim_evidence_matching"]
    },
    {
        "lessonId": "les_b2_187_02_hypothesis_formulation_abstract_writing",
        "unitId": "unit_b2_187_scholarly_research_methodology_hypo",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 2,
        "title": "Academic Writing: Formulating Scholarly Hypotheses & Problem Statements",
        "lessonType": "writing",
        "primaryPurpose": "Draft the introductory problem statement and core hypothesis of a research prospectus using precise academic hedging and formal abstract terminology.",
        "communicativeOutcome": "Author a 250-word research problem statement formulating a testable hypothesis regarding vowel harmony shifts in Middle Mongolian.",
        "objectivesIntroduced": ["obj_b2_187_02_formulate_research_hypotheses"],
        "objectivesPracticed": ["obj_b2_187_01_read_methodology_monographs"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b1_nominalization_participles_cases", "gram_b2_particles_emphatic_nuance"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_21_academic_abstract_formulation"],
        "communicativeFunctionsReviewed": ["comm_b2_02_academic_essay_concessions"],
        "newProductiveLemmaTarget": 7,
        "newReceptiveLemmaTarget": 4,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_academic_philology_mongolistics"],
        "previousVocabularyReused": ["дэвшүүлэх", "зорилго", "зорилт", "үндэслэл", "хүрээ", "асуудал"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Author a 250-word research problem statement establishing an innovative hypothesis on Middle Mongolian epigraphy.",
        "spokenProductionObjective": "",
        "registerTarget": "academic prospectus",
        "pragmaticTarget": "formal hypothesis framing",
        "prerequisiteLessonIds": ["les_b2_187_01_research_methodology_epistemology_reading"],
        "reviewsLessonIds": ["les_b2_183_03_musicological_literature_review_writing"],
        "reviewsUnitIds": ["unit_b2_183_indirect_discourse_framing_verbs_"],
        "reviewReason": "Transforms literature review synthesis into independent academic research hypothesis formulation.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Deploys nominalized participles with case markers to build tightly subordinated academic problem definitions",
            "Articulates a clear research gap and unambiguous predictive hypothesis"
        ],
        "masteryEvidence": "Produces an abstract problem statement meeting standard criteria for National University of Mongolia research grants.",
        "recommendedExerciseModalities": ["summary_writing", "paragraph_reconstruction"]
    },
    {
        "lessonId": "les_b2_187_03_methodological_defense_colloquium_speech",
        "unitId": "unit_b2_187_scholarly_research_methodology_hypo",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 3,
        "title": "Spoken Oratory: Defending Research Methodology at Graduate Doctoral Colloquium",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver an oral defense of a chosen research methodology before an academic faculty committee, justifying data collection limits and analytical frameworks.",
        "communicativeOutcome": "Deliver a 3-minute academic defense justifying methodological choices against anticipated faculty skepticism.",
        "objectivesIntroduced": ["obj_b2_187_03_defend_research_methodology"],
        "objectivesPracticed": ["obj_b2_187_01_read_methodology_monographs", "obj_b2_187_02_formulate_research_hypotheses"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_a2_adverbial_comparative_shig_adil_met", "gram_b2_limiting_scalar_particles_buu_khel"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_formal_presentation_cadence", "phono_b2_topic_prominence_intonation"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_21_academic_abstract_formulation"],
        "communicativeFunctionsReviewed": ["comm_b2_07_delivering_prepared_presentations"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 4,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_academic_philology_mongolistics"],
        "previousVocabularyReused": ["хамгаалах", "шүүмжлэл", "сонголт", "хязгаарлалт", "нотолгоо", "илтгэх"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Deliver a 3-minute oral defense of a corpus linguistics methodology for analyzing 17th-century legal codes.",
        "registerTarget": "academic doctoral defense",
        "pragmaticTarget": "confident academic justification",
        "prerequisiteLessonIds": ["les_b2_187_02_hypothesis_formulation_abstract_writing"],
        "reviewsLessonIds": ["les_b2_181_04_defending_historical_performance_speech"],
        "reviewsUnitIds": ["unit_b2_181_epistemic_stance_presumption_the_ma"],
        "reviewReason": "Synthesizes historical hypothesis defense with rigorous doctoral colloquium methodology defense.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide benchmark recording of doctoral candidate defending research methods before academic council.",
        "successCriteria": [
            "Deploys comparative adverbials ('адил', 'мэт') and limiting particles to delineate methodological scope",
            "Maintains poised, collegial demeanor without defensive agitation"
        ],
        "masteryEvidence": "Speech recording reflects superior academic diction, clear logical framing, and formidable intellectual authority.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
    },
    {
        "lessonId": "les_b2_187_04_peer_review_methodological_critique_listening",
        "unitId": "unit_b2_187_scholarly_research_methodology_hypo",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 4,
        "title": "Acoustic Dissection: Peer Review Evaluation & Methodological Critique Dialogue",
        "lessonType": "listening",
        "primaryPurpose": "Listen to a recording of two senior academics rigorously dissecting a newly submitted research grant application, critiquing sample sizes and interpretive leaps.",
        "communicativeOutcome": "Comprehend subtle academic criticism, constructive recommendations, and institutional evaluation standards in spoken academic dialogue (150 wpm).",
        "objectivesIntroduced": ["obj_b2_187_04_comprehend_peer_review"],
        "objectivesPracticed": ["obj_b2_187_01_read_methodology_monographs"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_a2_converb_terminative_tal", "gram_b2_epistemic_stance_biz_baih"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_topic_prominence_intonation"],
        "phonologyReviewed": ["phono_b1_stress_focus_contrast"],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_21_academic_abstract_formulation"],
        "communicativeFunctionsReviewed": ["comm_b2_18_critiquing_artistic_exhibitions"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_academic_philology_mongolistics"],
        "previousVocabularyReused": ["магадлан", "үнэлэгч", "хянах", "дутагдалтай", "зөвлөх", "сайжруулах"],
        "readingObjective": "",
        "listeningObjective": "Listen to a 3-minute peer review discussion and log 3 specific methodological flaws identified by the senior reviewer.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "academic peer critique",
        "pragmaticTarget": "incisive evaluative scrutiny",
        "prerequisiteLessonIds": ["les_b2_187_03_methodological_defense_colloquium_speech"],
        "reviewsLessonIds": ["les_b2_186_02_curator_performer_walkthrough_listening"],
        "reviewsUnitIds": ["unit_b2_186_performing_arts_capstone_musicologi"],
        "reviewReason": "Translates museum gallery walk-through dialogue to high-level academic peer review discussions.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide authentic spoken dialogue between senior university scholars assessing grant proposals.",
        "successCriteria": [
            "Transcribes nuanced academic critiques delivered with indirect or polite hedging",
            "Identifies specific terminative converb clauses ('-тал/-тэл') framing duration and boundary conditions"
        ],
        "masteryEvidence": "Produces an accurate peer-review summary report outlining required revisions for grant approval.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "stance_identification"]
    }
])

# UNIT 188: Purposive Clausal Distinctions: Гэж vs -хаар vs Тулд (5 lessons)
# Budget: PL=26, RL=22, PE=8, RE=5
sec04_lessons.extend([
    {
        "lessonId": "les_b2_188_01_purposive_distinctions_syntax_intro",
        "unitId": "unit_b2_188_purposive_clausal_distinctions_vs_v",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 1,
        "title": "Morphosyntax: Purposive Clausal Triad 'Гэж', '-хаар/хээр' & 'Тулд/Тухайд'",
        "lessonType": "grammar_introduction",
        "primaryPurpose": "Introduce the syntactic scope, subject coreference constraints, and register distinctions governing the purposive markers: intentional 'гэж' (same/different subject), converb '-хаар' (same-subject direct teleology), and formal postposition 'тулд' (high-register telic justification).",
        "communicativeOutcome": "Select and construct grammatically flawless purposive clauses calibrated precisely to formal academic register and coreference constraints.",
        "objectivesIntroduced": ["obj_b2_188_01_master_purposive_distinctions"],
        "objectivesPracticed": [],
        "objectivesReviewed": ["obj_b2_187_01_read_methodology_monographs"],
        "grammarIntroduced": ["gram_b2_purposive_distinctions_gej_khaar_tuld"],
        "grammarPracticed": ["gram_a1_verb_volitional_intention_ya", "gram_b1_subordinate_subject_marking_genitive"],
        "grammarReviewed": ["gram_b2_epistemic_appearance_shig_baiana_yanzytai"],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_discourse_chunking_cadence"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_21_academic_abstract_formulation"],
        "communicativeFunctionsReviewed": ["comm_b2_02_academic_essay_concessions"],
        "newProductiveLemmaTarget": 7,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_academic_philology_mongolistics"],
        "previousVocabularyReused": ["тулд", "гэж", "хээр", "зорилгоор", "үүднээс", "хэрэгжүүлэх"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Draft 6 sentences distinguishing intention ('гэж'), direct physical purpose ('-хаар'), and institutional justification ('тулд') in academic research plans.",
        "spokenProductionObjective": "",
        "registerTarget": "academic formal",
        "pragmaticTarget": "purposive precision",
        "prerequisiteLessonIds": ["les_b2_187_04_peer_review_methodological_critique_listening"],
        "reviewsLessonIds": ["les_b2_178_01_urtyn_duu_vocal_ornamentation_reading"],
        "reviewsUnitIds": ["unit_b2_178_urtyn_duu_long_song_vocal_melisma_g"],
        "reviewReason": "Deepens earlier purposive converb knowledge into a comprehensive tripartite grammatical distinction.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Distinguishes between subject-identical '-хаар' and switch-reference permitted 'тулд' / 'гэж'",
            "Avoids colloquial 'гэж' in high-level institutional and statutory academic contexts"
        ],
        "masteryEvidence": "Correctly executes 8 sentence completion and error-detection items involving purposive clausal selection.",
        "recommendedExerciseModalities": ["word_transformation", "sentence_reordering"]
    },
    {
        "lessonId": "les_b2_188_02_institutional_grant_proposals_reading",
        "unitId": "unit_b2_188_purposive_clausal_distinctions_vs_v",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 2,
        "title": "Academic Reading: Teleological Framing in National Science Foundation Research Proposals",
        "lessonType": "reading",
        "primaryPurpose": "Parse a 370-word research grant application analyzing how project objectives, societal impacts, and methodological steps are framed using distinct purposive constructions.",
        "communicativeOutcome": "Differentiate between proximate methodological aims and long-term societal goals in an academic grant proposal.",
        "objectivesIntroduced": ["obj_b2_188_02_read_grant_proposals"],
        "objectivesPracticed": ["obj_b2_188_01_master_purposive_distinctions"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_purposive_distinctions_gej_khaar_tuld", "gram_b1_subordinate_subject_marking_genitive"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_21_academic_abstract_formulation"],
        "communicativeFunctionsReviewed": ["comm_b2_11_summarizing_complex_articles"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 7,
        "newProductiveExpressionTarget": 1,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c1_academic_philology_mongolistics"],
        "previousVocabularyReused": ["төсөл", "санхүүжилт", "үр шим", "нийгмийн нөлөө", "хөгжүүлэх"],
        "readingObjective": "Read a 370-word grant application and categorize 5 purposive clauses into immediate activities versus strategic outcomes.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "academic institutional",
        "pragmaticTarget": "teleological analysis",
        "prerequisiteLessonIds": ["les_b2_188_01_purposive_distinctions_syntax_intro"],
        "reviewsLessonIds": ["les_b2_187_01_research_methodology_epistemology_reading"],
        "reviewsUnitIds": ["unit_b2_187_scholarly_research_methodology_hypo"],
        "reviewReason": "Connects epistemological methodology reading with concrete grant proposal text parsing.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Identifies how 'тулд' introduces macro-level national benefits while '-хаар' specifies laboratory steps",
            "Recognizes genitive subjects inside complex purposive clauses"
        ],
        "masteryEvidence": "Completes a teleological structural diagram organizing grant aims hierarchically.",
        "recommendedExerciseModalities": ["source_comparison", "claim_evidence_matching"]
    },
    {
        "lessonId": "les_b2_188_03_research_grant_rationale_writing",
        "unitId": "unit_b2_188_purposive_clausal_distinctions_vs_v",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 3,
        "title": "Academic Writing: Formulating Multi-Tiered Project Rationale & Justifications",
        "lessonType": "writing",
        "primaryPurpose": "Draft the justification section of a 260-word research grant proposal, contrasting short-term data gathering aims with long-term theoretical contributions.",
        "communicativeOutcome": "Author a 260-word research rationale deploying 'тулд', '-хаар', and 'зорилгоор' with stylistic variety and syntactic perfection.",
        "objectivesIntroduced": ["obj_b2_188_03_write_grant_rationale"],
        "objectivesPracticed": ["obj_b2_188_01_master_purposive_distinctions", "obj_b2_188_02_read_grant_proposals"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_purposive_distinctions_gej_khaar_tuld", "gram_b1_verb_derivation_denominal_lakh"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_21_academic_abstract_formulation"],
        "communicativeFunctionsReviewed": ["comm_b2_02_academic_essay_concessions"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 4,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_academic_philology_mongolistics"],
        "previousVocabularyReused": ["үндэслэл", "шаардлага", "үр дүн", "боловсруулах", "дэмжих"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Author a 260-word research grant rationale detailing institutional justification for archiving endangered Turkic-Mongolic manuscripts.",
        "spokenProductionObjective": "",
        "registerTarget": "academic grant proposal",
        "pragmaticTarget": "compelling telic justification",
        "prerequisiteLessonIds": ["les_b2_188_02_institutional_grant_proposals_reading"],
        "reviewsLessonIds": ["les_b2_187_02_hypothesis_formulation_abstract_writing"],
        "reviewsUnitIds": ["unit_b2_187_scholarly_research_methodology_hypo"],
        "reviewReason": "Synthesizes hypothesis framing with multi-tiered purposive grant justification drafting.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
            "Employs 'тулд' and '-хаар' without grammatical error or clausal redundancy",
            "Structures rationale so each methodological step ties directly to stated theoretical goals"
        ],
        "masteryEvidence": "Produces a proposal section meeting high-level funding review committee evaluation rubrics.",
        "recommendedExerciseModalities": ["summary_writing", "paragraph_reconstruction"]
    },
    {
        "lessonId": "les_b2_188_04_oral_pitch_academic_grant_defense_speech",
        "unitId": "unit_b2_188_purposive_clausal_distinctions_vs_v",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 4,
        "title": "Spoken Oratory: Three-Minute Project Pitch to Research Grant Allocation Board",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver a concise 3-minute oral project pitch to an academic endowment board, outlining why the project was designed and how funds will be deployed.",
        "communicativeOutcome": "Deliver an articulate 3-minute spoken project pitch maintaining clear purposive clausal hierarchy under strict time constraints.",
        "objectivesIntroduced": ["obj_b2_188_04_deliver_grant_pitch"],
        "objectivesPracticed": ["obj_b2_188_01_master_purposive_distinctions", "obj_b2_188_03_write_grant_rationale"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_purposive_distinctions_gej_khaar_tuld", "gram_a1_verb_tense_future_prospective_na"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_formal_presentation_cadence", "phono_b2_topic_prominence_intonation"],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_21_academic_abstract_formulation"],
        "communicativeFunctionsReviewed": ["comm_b2_07_delivering_prepared_presentations"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 3,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_academic_philology_mongolistics"],
        "previousVocabularyReused": ["төсөл танилцуулга", "сангийн зөвлөл", "хэрэгжилт", "амлалт", "үр ашиг"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Deliver a 3-minute spoken pitch explaining why substantial funding is required to preserve fragile birch-bark scriptures.",
        "registerTarget": "executive academic",
        "pragmaticTarget": "persuasive teleological pitch",
        "prerequisiteLessonIds": ["les_b2_188_03_research_grant_rationale_writing"],
        "reviewsLessonIds": ["les_b2_187_03_methodological_defense_colloquium_speech"],
        "reviewsUnitIds": ["unit_b2_187_scholarly_research_methodology_hypo"],
        "reviewReason": "Elevates doctoral colloquium defense into high-stakes executive grant pitching.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide model recording of research director pitching grant proposal to endowment trustees.",
        "successCriteria": [
            "Deploys purposive markers ('тулд', '-хаар') with crisp intonational boundaries",
            "Maintains high persuasive impact without sacrificing scholarly dignity"
        ],
        "masteryEvidence": "Speech recording confirms exceptional spoken clarity and commanding control of telic discourse structures.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
    },
    {
        "lessonId": "les_b2_188_05_grant_deliberation_committee_listening",
        "unitId": "unit_b2_188_purposive_clausal_distinctions_vs_v",
        "cefrLevel": "B2",
        "sequenceWithinUnit": 5,
        "title": "Acoustic Dissection: Endowment Board Closed-Door Allocation Deliberation",
        "lessonType": "listening",
        "primaryPurpose": "Listen to a behind-the-scenes recording of an academic grant evaluation committee debating whether applicants justified their proposed field expeditions.",
        "communicativeOutcome": "Identify committee consensus, funding conditions, and evaluative skepticism regarding stated project goals (150 wpm).",
        "objectivesIntroduced": ["obj_b2_188_05_comprehend_grant_deliberations"],
        "objectivesPracticed": ["obj_b2_188_01_master_purposive_distinctions"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_b2_purposive_distinctions_gej_khaar_tuld", "gram_a2_indefinite_pronouns_negation"],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": ["phono_b2_topic_prominence_intonation"],
        "phonologyReviewed": ["phono_b1_stress_focus_contrast"],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_b2_21_academic_abstract_formulation"],
        "communicativeFunctionsReviewed": ["comm_b2_09_moderating_group_discussions"],
        "newProductiveLemmaTarget": 4,
        "newReceptiveLemmaTarget": 3,
        "newProductiveExpressionTarget": 1,
        "newReceptiveExpressionTarget": 0,
        "lexicalDomains": ["lex_c1_academic_philology_mongolistics"],
        "previousVocabularyReused": ["зөвлөлдөх", "шийдвэр", "батлах", "татгалзах", "хэмнэх", "магадлах"],
        "readingObjective": "",
        "listeningObjective": "Listen to a 3-minute committee deliberation and log 3 specific conditions attached to the approval of field survey funding.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "evaluative institutional",
        "pragmaticTarget": "institutional decision comprehension",
        "prerequisiteLessonIds": ["les_b2_188_04_oral_pitch_academic_grant_defense_speech"],
        "reviewsLessonIds": ["les_b2_187_04_peer_review_methodological_critique_listening"],
        "reviewsUnitIds": ["unit_b2_187_scholarly_research_methodology_hypo"],
        "reviewReason": "Translates peer review listening comprehension to closed-door financial allocation committee discussions.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide multi-speaker audio of institutional committee assessing grant applications with natural conversational overlaps.",
        "successCriteria": [
            "Accurately pinpoints the decisive argument that tipped the board toward funding approval",
            "Identifies how purposive clausal nuances affected the reviewers' evaluation of feasibility"
        ],
        "masteryEvidence": "Produces an executive minutes summary accurately capturing the committee's final funding resolution.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "stance_identification"]
    }
])

print(f"Added Units 187-188. Total Section 04 lessons: {len(sec04_lessons)}")
