# -*- coding: utf-8 -*-
"""Author Section 02 of CEFR C1: Macroeconomics, Mining & International Trade.
Units 208 to 217 (10 units, 47 lessons).
"""
import json

def get_section_02_lessons():
    lessons = []

    # ----------------------------------------------------
    # UNIT 208: Macroeconomic Stabilization & Monetary Policy (PL=24, RL=27, PE=8, RE=6) (5 lessons)
    # ----------------------------------------------------
    lessons.extend([
      {
        "lessonId": "les_c1_208_01_academic_nominalization_frames_syntax_intro",
        "unitId": "unit_c1_208_macroeconomic_stabilization_monetar",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 1,
        "title": "Morphosyntax: Academic Nominalization Frames in Macroeconomic Analysis",
        "lessonType": "grammar_introduction",
        "primaryPurpose": "Introduce the syntactic formation and cognitive condensing functions of high-register academic nominalization frames (e.g. '...-х явдал нь', '...-х хандлага ажиглагдаж байгаа нь', '...-х үйл явц') structuring macroeconomic policy discourse.",
        "communicativeOutcome": "Package complex economic causation chains into dense academic nominal frames, enabling detached, evidence-based policy formulation.",
        "objectivesIntroduced": ["obj_c1_208_01_master_nominalization_frames"],
        "objectivesPracticed": [],
        "objectivesReviewed": ["obj_c1_207_06_master_sec01_culminating_synthesis"],
        "grammarIntroduced": ["gram_c1_academic_nominalization_frames"],
        "grammarPracticed": ["gram_c1_administrative_chancellery_syntax"],
        "grammarReviewed": ["gram_b2_participle_relative_subject_genitive_alternation"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": ["comm_c1_09_high_level_policy_briefs"],
        "communicativeFunctionsPracticed": [],
        "communicativeFunctionsReviewed": ["comm_b2_13_scholarly_synthesis"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_macroeconomics_trade_finance"],
        "previousVocabularyReused": ["мөнгөний бодлого", "төв банк", "инфляци", "хүүгийн түвшин", "эдийн засгийн өсөлт"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "academic macroeconomic analytical",
        "pragmaticTarget": "scholarly detached argumentation",
        "prerequisiteLessonIds": ["les_c1_207_06_c1_sec01_culminating_constitutional_capstone"],
        "reviewsLessonIds": ["les_c1_198_01_administrative_chancellery_syntax_intro"],
        "reviewsUnitIds": ["unit_c1_198_the_1992_democratic_constitution_of"],
        "reviewReason": "Extends Section 01 statutory nominal syntax into academic macroeconomic framing matrices.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Embeds multi-clause causal propositions inside academic topic-comment frames without grammatical breakdown",
          "Distinguishes between descriptive process nominalizations and evaluative analytical stance frames"
        ],
        "masteryEvidence": "Converts 5 loose journalistic economic descriptions into rigorous academic macroeconomic nominal formulations.",
        "recommendedExerciseModalities": ["stylistic_transformation", "discourse_analysis"]
      },
      {
        "lessonId": "les_c1_208_02_central_bank_monetary_policy_report_reading",
        "unitId": "unit_c1_208_macroeconomic_stabilization_monetar",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 2,
        "title": "Macroeconomic Reading: Central Bank Monetary Policy & Inflation Targeting Reports",
        "lessonType": "reading",
        "primaryPurpose": "Parse a 520-word excerpt from the Bank of Mongolia Monetary Policy Report (Монголбанкны Мөнгөний бодлогын тайлан), evaluating foreign exchange reserves, policy rate adjustments, and inflationary transmission channels.",
        "communicativeOutcome": "Extract monetary policy signals, econometric forecasts, and systemic risk assessments from central bank publications.",
        "objectivesIntroduced": ["obj_c1_208_02_parse_monetary_policy_reports"],
        "objectivesPracticed": ["obj_c1_208_01_master_nominalization_frames"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_academic_nominalization_frames"],
        "grammarReviewed": ["gram_c1_administrative_chancellery_syntax"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c1_09_high_level_policy_briefs"],
        "communicativeFunctionsReviewed": ["comm_b2_13_scholarly_synthesis"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_macroeconomics_trade_finance"],
        "previousVocabularyReused": ["бодлогын хүү", "ханш", "валютын нөөц", "төгрөг", "эдийн засаг"],
        "readingObjective": "Critique complex econometric analyses explaining central bank policy rate interventions and reserve asset management.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "central bank institutional technical",
        "pragmaticTarget": "monetary policy exegesis",
        "prerequisiteLessonIds": ["les_c1_208_01_academic_nominalization_frames_syntax_intro"],
        "reviewsLessonIds": ["les_c1_207_01_supreme_court_dossier_analysis_reading"],
        "reviewsUnitIds": ["unit_c1_207_constitutional_jurisprudence_capsto"],
        "reviewReason": "Bridges supreme court judicial dossier analysis into central bank institutional macroeconomic reports.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Identifies the precise macroeconomic transmission mechanism linking policy rate hikes to domestic consumer inflation cooling",
          "Interprets econometric forward guidance statements without confusing projected baseline scenarios with downside risks"
        ],
        "masteryEvidence": "Answers 4 complex analytical queries comparing Mongolian monetary tightening cycles against external commodity price shocks.",
        "recommendedExerciseModalities": ["source_comparison", "claim_evidence_matching"]
      },
      {
        "lessonId": "les_c1_208_03_monetary_policy_committee_briefing_listening",
        "unitId": "unit_c1_208_macroeconomic_stabilization_monetar",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 3,
        "title": "Acoustic Dissection: Bank of Mongolia Monetary Policy Committee Press Conference",
        "lessonType": "listening",
        "primaryPurpose": "Listen to a 4.5-minute unedited broadcast of the Governor of the Bank of Mongolia announcing the Monetary Policy Committee's quarterly rate decision and fielding financial journalists' inquiries.",
        "communicativeOutcome": "Process high-speed technical financial speech (155-175 wpm), discerning subtle central bank forward guidance nuances and monetary policy stance shifts.",
        "objectivesIntroduced": ["obj_c1_208_03_comprehend_central_bank_briefings"],
        "objectivesPracticed": ["obj_c1_208_01_master_nominalization_frames"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_academic_nominalization_frames"],
        "grammarReviewed": ["gram_c1_administrative_chancellery_syntax"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c1_09_high_level_policy_briefs"],
        "communicativeFunctionsReviewed": ["comm_b2_02_parliamentary_interpellation"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c1_macroeconomics_trade_finance"],
        "previousVocabularyReused": ["хэвлэлийн бага хурал", "мөнгөний нийлүүлэлт", "зээлийн өсөлт", "эрсдэл"],
        "readingObjective": "",
        "listeningObjective": "Decipher spoken econometric statements and official policy justifications delivered under live press conference conditions.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "central bank monetary press",
        "pragmaticTarget": "forward guidance interpretation",
        "prerequisiteLessonIds": ["les_c1_208_02_central_bank_monetary_policy_report_reading"],
        "reviewsLessonIds": ["les_c1_206_03_cabinet_press_secretary_decree_announcement_listening"],
        "reviewsUnitIds": ["unit_c1_206_drafting_executive_ministerial_decr"],
        "reviewReason": "Extends cabinet press conference listening to specialized central bank macroeconomic rate announcements.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide authentic broadcast recording of Central Bank Governor delivering Monetary Policy Statement with financial press Q&A.",
        "successCriteria": [
          "Transcribes the specific percentage adjustment to the benchmark policy rate and reserve requirements without error",
          "Detects whether the Governor's tone on future inflation expectations is hawkish, dovish, or neutral based on subtle linguistic markers"
        ],
        "masteryEvidence": "Produces an analytical financial market summary detailing the policy decision, key risk assumptions, and market forward guidance.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "stance_identification"]
      },
      {
        "lessonId": "les_c1_208_04_macroeconomic_policy_brief_writing",
        "unitId": "unit_c1_208_macroeconomic_stabilization_monetar",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 4,
        "title": "Academic Writing: High-Level Macroeconomic Stabilization Policy Brief",
        "lessonType": "writing",
        "primaryPurpose": "Author a 440-word formal Policy Advisory Brief ('Эдийн засгийн тогтворжуулалтын бодлогын зөвлөмж') for the Ministry of Economy and Development, evaluating fiscal-monetary policy coordination and sovereign debt sustainability.",
        "communicativeOutcome": "Produce high-level macroeconomic policy documentation adhering to international international financial institution (IMF/WB) standards.",
        "objectivesIntroduced": ["obj_c1_208_04_author_macroeconomic_briefs"],
        "objectivesPracticed": ["obj_c1_208_01_master_nominalization_frames"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_academic_nominalization_frames"],
        "grammarReviewed": ["gram_c1_administrative_chancellery_syntax"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c1_09_high_level_policy_briefs"],
        "communicativeFunctionsReviewed": ["comm_b2_09_formal_policy_recommendations"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 1,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_macroeconomics_trade_finance"],
        "previousVocabularyReused": ["төсвийн бодлого", "өр төлбөр", "тогтворжуулалт", "тэнцвэр", "зөвлөмж"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Draft an authoritative policy brief proposing counter-cyclical fiscal adjustments and foreign exchange reserve replenishment strategies.",
        "spokenProductionObjective": "",
        "registerTarget": "academic economic consultative",
        "pragmaticTarget": "strategic policy formulation",
        "prerequisiteLessonIds": ["les_c1_208_03_monetary_policy_committee_briefing_listening"],
        "reviewsLessonIds": ["les_c1_207_04_constitutional_remedies_amicus_brief_writing"],
        "reviewsUnitIds": ["unit_c1_207_constitutional_jurisprudence_capsto"],
        "reviewReason": "Synthesizes amicus advisory writing into high-level macroeconomic stabilization policy drafting.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Deploys at least 5 varied academic nominalization frames ('...-х явдал нь', '...-х хандлага нь') to express structural causation",
          "Structures recommendations into executive summary, empirical diagnosis, risk matrix, and actionable policy measures"
        ],
        "masteryEvidence": "Submits a compliant 440-word macroeconomic policy brief ready for ministerial presentation.",
        "recommendedExerciseModalities": ["statutory_clause_drafting", "summary_writing"]
      },
      {
        "lessonId": "les_c1_208_05_parliamentary_budget_inquiry_spoken",
        "unitId": "unit_c1_208_macroeconomic_stabilization_monetar",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 5,
        "title": "Deliberative Speaking: Defending Monetary-Fiscal Policy at Parliamentary Hearing",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver an unscripted 4-minute verbal testimony before the Parliamentary Standing Committee on Economy, defending monetary policy decisions against inflation critiques from lawmakers.",
        "communicativeOutcome": "Articulate complex monetary mechanisms orally with authoritative fluency, defusing political accusations using measured economic logic.",
        "objectivesIntroduced": ["obj_c1_208_05_testify_on_economic_policy_orally"],
        "objectivesPracticed": ["obj_c1_208_01_master_nominalization_frames"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_academic_nominalization_frames"],
        "grammarReviewed": ["gram_c1_administrative_chancellery_syntax"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c1_09_high_level_policy_briefs"],
        "communicativeFunctionsReviewed": ["comm_b2_10_high_stakes_negotiation"],
        "newProductiveLemmaTarget": 4,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 1,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_macroeconomics_trade_finance"],
        "previousVocabularyReused": ["эдийн засгийн байнгын хороо", "тайлбарлах", "хариуцлага", "дүн шинжилгээ"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Argue convincingly before parliamentarians, articulating the economic trade-offs between rate hikes and industrial credit availability.",
        "registerTarget": "formal parliamentary consultative",
        "pragmaticTarget": "authoritative institutional defense",
        "prerequisiteLessonIds": ["les_c1_208_04_macroeconomic_policy_brief_writing"],
        "reviewsLessonIds": ["les_c1_207_05_supreme_court_en_banc_oral_argument_spoken"],
        "reviewsUnitIds": ["unit_c1_207_constitutional_jurisprudence_capsto"],
        "reviewReason": "Bridges supreme court oral pleading skills into parliamentary economic committee testimony.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide benchmark audio of senior central banker testifying before parliamentary committee.",
        "successCriteria": [
          "Responds to populist parliamentary critiques with calm, empirical econometric arguments without defensive irritation",
          "Maintains formal consultative address protocols while clarifying technical monetary concepts"
        ],
        "masteryEvidence": "Successfully navigates a 4-minute simulated legislative hearing defending anti-inflation interest rate adjustments.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
      }
    ])

    return lessons

if __name__ == '__main__':
    ls = get_section_02_lessons()
    print(f"Unit 208 lessons: {len(ls)}")
