# -*- coding: utf-8 -*-
import json

def get_units_198_202():
    # Return lessons for units 198, 199, 200, 201, 202 (25 lessons)
    lessons = []
    
    # Unit 198: The 1992 Democratic Constitution of Mongolia (PL=24, RL=27, PE=8, RE=6)
    lessons.extend([
      {
        "lessonId": "les_c1_198_01_administrative_chancellery_syntax_intro",
        "unitId": "unit_c1_198_the_1992_democratic_constitution_of",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 1,
        "title": "Morphosyntax: Administrative Chancellery Architecture & Complex Nominal Embeddings",
        "lessonType": "grammar_introduction",
        "primaryPurpose": "Introduce the syntactic architecture of formal state chancellery Mongolian, characterized by multi-tiered participial nominalizations, genitive agent embeddings, and preposed non-finite clausal modifiers preceding statutory head nouns.",
        "communicativeOutcome": "Deconstruct and parse high-register legal sentences exceeding 40 words, isolating the main statutory predicate from nested institutional subordinate clauses without ambiguity.",
        "objectivesIntroduced": ["obj_c1_198_01_parse_chancellery_nominalizations"],
        "objectivesPracticed": [],
        "objectivesReviewed": ["obj_b2_191_01_identify_genitive_subject_alternation"],
        "grammarIntroduced": ["gram_c1_administrative_chancellery_syntax"],
        "grammarPracticed": ["gram_b2_participle_relative_subject_genitive_alternation"],
        "grammarReviewed": ["gram_b1_reported_speech_indirect_tense_shift"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": ["comm_c1_04_statutory_legislative_drafting"],
        "communicativeFunctionsPracticed": [],
        "communicativeFunctionsReviewed": ["comm_b2_09_formal_policy_recommendations"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": ["үндсэн хууль", "төрийн байгуулал", "бүрэн эрх", "засаглал", "хууль тогтоох", "шүүх засаглал"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "state chancellery statutory",
        "pragmaticTarget": "institutional legal authority",
        "prerequisiteLessonIds": ["les_b2_197_06_b2_vantage_culminating_academic_capstone"],
        "reviewsLessonIds": ["les_b2_191_01_relative_subject_case_alternation_syntax_intro"],
        "reviewsUnitIds": ["unit_b2_191_relative_clause_subject_genitive_no"],
        "reviewReason": "Extends B2 genitive-nominative relative clause subject alternation directly into complex state constitutional syntax.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Accurately maps the dependency hierarchy in statutory clauses containing triple-nested participial modifiers",
          "Distinguishes the governing judicial predicate from descriptive subordinate criteria in constitutional articles"
        ],
        "masteryEvidence": "Diagrams and translates the syntactic structure of a 45-word constitutional article into plain analytical discourse without losing deontic force.",
        "recommendedExerciseModalities": ["discourse_analysis", "sentence_reordering"]
      },
      {
        "lessonId": "les_c1_198_02_constitutional_articles_parsing_reading",
        "unitId": "unit_c1_198_the_1992_democratic_constitution_of",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 2,
        "title": "Statutory Reading: Sovereign Rights & Constitutional Separation of Powers",
        "lessonType": "reading",
        "primaryPurpose": "Parse an unabridged 520-word excerpt from Chapter 1 and Chapter 3 of the 1992 Democratic Constitution of Mongolia, examining sovereign rights declarations, parliamentary prerogatives, and executive checks.",
        "communicativeOutcome": "Extract precise institutional boundaries, statutory caveats, and legislative checks from authoritative constitutional articles.",
        "objectivesIntroduced": ["obj_c1_198_02_interpret_constitutional_declarations"],
        "objectivesPracticed": ["obj_c1_198_01_parse_chancellery_nominalizations"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_administrative_chancellery_syntax"],
        "grammarReviewed": ["gram_b2_modal_complex_obligation_uchirtai"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c1_04_statutory_legislative_drafting"],
        "communicativeFunctionsReviewed": ["comm_b2_02_parliamentary_interpellation"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": ["төрийн тэргүүн", "парламент", "хууль зүйн хороо", "халдашгүй дархан байдал"],
        "readingObjective": "Analyze complex constitutional provisions detailing the division of executive, legislative, and judicial sovereignty.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "constitutional judicial",
        "pragmaticTarget": "statutory exegesis",
        "prerequisiteLessonIds": ["les_c1_198_01_administrative_chancellery_syntax_intro"],
        "reviewsLessonIds": ["les_b2_190_01_complex_obligation_uchirtai_syntax_intro"],
        "reviewsUnitIds": ["unit_b2_190_complex_modal_obligation_the_modal_"],
        "reviewReason": "Synthesizes teleological obligation markers with constitutional mandate formulations.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Identifies the precise constitutional conditions under which the President may veto parliamentary statutes",
          "Extracts the legal distinction between supreme state power and delegated executive administration"
        ],
        "masteryEvidence": "Answers 4 complex analytical queries comparing Mongolian separation of powers against semi-presidential systems based on text citations.",
        "recommendedExerciseModalities": ["source_comparison", "claim_evidence_matching"]
      },
      {
        "lessonId": "les_c1_198_03_sovereign_rights_commentary_writing",
        "unitId": "unit_c1_198_the_1992_democratic_constitution_of",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 3,
        "title": "Legal Commentary Writing: Jurisprudential Analysis of Article 16 Fundamental Rights",
        "lessonType": "writing",
        "primaryPurpose": "Author a 420-word scholarly legal commentary analyzing the scope and limitations of citizen fundamental rights under Article 16 of the Constitution, deploying state chancellery syntax.",
        "communicativeOutcome": "Produce rigorous juristic prose evaluating how constitutional rights are balanced against public security and statutory limitations.",
        "objectivesIntroduced": ["obj_c1_198_03_author_juristic_commentary"],
        "objectivesPracticed": ["obj_c1_198_01_parse_chancellery_nominalizations"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_administrative_chancellery_syntax"],
        "grammarReviewed": ["gram_b2_voice_stacking_causative_passive"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c1_04_statutory_legislative_drafting"],
        "communicativeFunctionsReviewed": ["comm_b2_13_scholarly_synthesis"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": ["иргэний эрх", "эрх чөлөө", "үндэсний аюулгүй байдал", "хязгаарлалт", "хууль дээдлэх"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Draft an authoritative legal commentary structuring constitutional arguments with multi-tiered nominalizations and formal syntactic connectors.",
        "spokenProductionObjective": "",
        "registerTarget": "academic juristic chancellery",
        "pragmaticTarget": "principled constitutional reasoning",
        "prerequisiteLessonIds": ["les_c1_198_02_constitutional_articles_parsing_reading"],
        "reviewsLessonIds": ["les_b2_197_04_strategic_academic_consultation_brief_writing"],
        "reviewsUnitIds": ["unit_b2_197_b2_vantage_capstone_academic_sympos"],
        "reviewReason": "Bridges B2 strategic consultation brief composition into formal constitutional law commentary.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Structures arguments with clear distinction between unalienable rights and statutory regulatory reservations",
          "Deploys at least 4 complex participial nominalization constructions without syntactic breakdown"
        ],
        "masteryEvidence": "Submits a 420-word legal analysis of property rights and mineral wealth ownership under Article 6 adhering to chancellery style.",
        "recommendedExerciseModalities": ["summary_writing", "paragraph_reconstruction"]
      },
      {
        "lessonId": "les_c1_198_04_constitutional_order_deliberation_spoken",
        "unitId": "unit_c1_198_the_1992_democratic_constitution_of",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 4,
        "title": "Deliberative Speaking: Defending Constitutional Balances in Judicial Reform",
        "lessonType": "spoken_production",
        "primaryPurpose": "Engage in an advanced 4-minute spoken juristic defense of constitutional checks and balances during proposed amendments to the Law on Courts.",
        "communicativeOutcome": "Articulate nuanced constitutional principles orally, refuting unconstitutional executive encroachment with measured diplomatic authority.",
        "objectivesIntroduced": ["obj_c1_198_04_defend_constitutional_integrity_orally"],
        "objectivesPracticed": ["obj_c1_198_01_parse_chancellery_nominalizations"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_administrative_chancellery_syntax"],
        "grammarReviewed": ["gram_b2_conditionals_hypothetical_present"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c1_04_statutory_legislative_drafting"],
        "communicativeFunctionsReviewed": ["comm_b2_10_high_stakes_negotiation"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 1,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": ["шүүхийн хараат бус байдал", "шүүгчийн халдашгүй эрх", "хууль зүйн үр дагавар"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Deliver an unscripted, authoritative oral argumentation analyzing the constitutional validity of proposed judicial oversight reforms.",
        "registerTarget": "formal parliamentary judicial",
        "pragmaticTarget": "firm diplomatic contestation",
        "prerequisiteLessonIds": ["les_c1_198_03_sovereign_rights_commentary_writing"],
        "reviewsLessonIds": ["les_b2_189_01_hypothetical_conditionals_syntax_intro"],
        "reviewsUnitIds": ["unit_b2_189_hypothetical_conditionals_in_academ"],
        "reviewReason": "Applies B2 hypothetical conditionals (-вал... болохсон) to test constitutional counterfactuals during oral argumentation.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide high-register courtroom oral argumentation model demonstrating judicial pacing and controlled oratorical pauses.",
        "successCriteria": [
          "Refutes executive overreach proposals by directly citing constitutional sovereignty articles without colloquialisms",
          "Maintains controlled oratorical cadence (130-150 wpm) with precise juristic vocabulary"
        ],
        "masteryEvidence": "Performs a 4-minute simulated testimony before the Parliamentary Legal Standing Committee defending judicial independence.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
      },
      {
        "lessonId": "les_c1_198_05_parliamentary_debates_on_basic_law_listening",
        "unitId": "unit_c1_198_the_1992_democratic_constitution_of",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 5,
        "title": "Acoustic Dissection: Authentic 1991–1992 Constitutional Drafting Debates",
        "lessonType": "listening",
        "primaryPurpose": "Listen to a 4-minute historical audio recording of the People's Great Khural (Ардын Их Хурал) plenary session debating the balance between state symbols, human rights, and the presidency.",
        "communicativeOutcome": "Comprehend elevated historical political oratory delivered at natural speed (155-175 wpm), tracking diverging philosophies on state sovereignty.",
        "objectivesIntroduced": ["obj_c1_198_05_comprehend_historical_parliamentary_debates"],
        "objectivesPracticed": ["obj_c1_198_01_parse_chancellery_nominalizations"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_administrative_chancellery_syntax"],
        "grammarReviewed": ["gram_b2_discourse_focus_particles_l_ch"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c1_04_statutory_legislative_drafting"],
        "communicativeFunctionsReviewed": ["comm_b2_02_parliamentary_interpellation"],
        "newProductiveLemmaTarget": 4,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 1,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": ["ардын их хурал", "депутат", "төрийн сүлд", "түүхэн уламжлал", "тусгаар тогтнол"],
        "readingObjective": "",
        "listeningObjective": "Extract competing constitutional drafting positions, ideological premises, and rhetorical appeals from archival parliamentary debates.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "historical oratorical parliamentary",
        "pragmaticTarget": "historical debate exegesis",
        "prerequisiteLessonIds": ["les_c1_198_02_constitutional_articles_parsing_reading"],
        "reviewsLessonIds": ["les_b2_184_01_limiting_scalar_particles_syntax_intro"],
        "reviewsUnitIds": ["unit_b2_184_focus_particles_and_scalar_pragmati"],
        "reviewReason": "Scrutinizes how scalar particles (ч, л) alter political stance during intense historical legislative votes.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide authentic uncleaned historical plenary recording with acoustic background resonance of the Government House chamber.",
        "successCriteria": [
          "Identifies the precise ideological divergence between advocates of a parliamentary system versus a strong presidential model",
          "Transcribes nuanced archaic and formal legislative expressions spoken under emotional debate conditions"
        ],
        "masteryEvidence": "Synthesizes the core points of dispute from three distinct deputy speeches and charts their final resolution into the adopted text.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "stance_identification"]
      }
    ])
    
    # Unit 199: Archaic & Classical Jussives: -сугай/-сүгэй & -тугай/-түгэй (PL=24, RL=27, PE=8, RE=6)
    lessons.extend([
      {
        "lessonId": "les_c1_199_01_archaic_jussive_syntax_intro",
        "unitId": "unit_c1_199_archaic_classical_jussives_suffixes",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 1,
        "title": "Morphosyntax: Archaic & Classical Jussive Suffixes -сугай/-сүгэй & -тугай/-түгэй",
        "lessonType": "grammar_introduction",
        "primaryPurpose": "Introduce the syntactic formation, archaic morphological conditioning, and sovereign performative force of 1st person (-сугай/-сүгэй 'I/we shall hereby') and 3rd person (-тугай/-түгэй 'let it be / may it be enacted') classical jussive suffixes.",
        "communicativeOutcome": "Deploy formulaic classical jussive suffixes correctly in formal legislative enactments, decree promulgations, and state ceremonial resolutions.",
        "objectivesIntroduced": ["obj_c1_199_01_master_classical_jussives"],
        "objectivesPracticed": [],
        "objectivesReviewed": ["obj_c1_198_01_parse_chancellery_nominalizations"],
        "grammarIntroduced": ["gram_c1_archaic_jussive_sugai_tugai"],
        "grammarPracticed": ["gram_c1_administrative_chancellery_syntax"],
        "grammarReviewed": ["gram_b2_modal_complex_obligation_uchirtai"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": ["comm_c1_04_statutory_legislative_drafting"],
        "communicativeFunctionsPracticed": [],
        "communicativeFunctionsReviewed": ["comm_b2_09_formal_policy_recommendations"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": ["зарлиг", "тогтоол", "батлах", "хэрэгжүүлэх", "мөрдөх"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "classical state chancellery",
        "pragmaticTarget": "sovereign promulgation",
        "prerequisiteLessonIds": ["les_c1_198_03_sovereign_rights_commentary_writing"],
        "reviewsLessonIds": ["les_c1_198_01_administrative_chancellery_syntax_intro"],
        "reviewsUnitIds": ["unit_c1_198_the_1992_democratic_constitution_of"],
        "reviewReason": "Integrates archaic jussive modal heads into state administrative chancellery sentences.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Applies vowel harmony correctly to attach -сугай/-сүгэй and -тугай/-түгэй to diverse verb stems",
          "Distinguishes performative legal enactments ('тогтоосугай') from descriptive future obligations ('тогтооно')"
        ],
        "masteryEvidence": "Converts 5 modern administrative commands into authoritative classical decree enactments without error.",
        "recommendedExerciseModalities": ["stylistic_transformation", "discourse_analysis"]
      },
      {
        "lessonId": "les_c1_199_02_presidential_decree_preambles_reading",
        "unitId": "unit_c1_199_archaic_classical_jussives_suffixes",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 2,
        "title": "Chancellery Reading: Presidential Decrees & Classical Promulgation Preambles",
        "lessonType": "reading",
        "primaryPurpose": "Parse an authentic 480-word Presidential Decree (Монгол Улсын Ерөнхийлөгчийн Зарлиг) conferring state honors and enacting national directives using classical jussives.",
        "communicativeOutcome": "Comprehend state ceremonial decrees, analyzing how constitutional justification preambles transition into binding jussive operative clauses.",
        "objectivesIntroduced": ["obj_c1_199_02_parse_presidential_decrees"],
        "objectivesPracticed": ["obj_c1_199_01_master_classical_jussives"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_archaic_jussive_sugai_tugai"],
        "grammarReviewed": ["gram_c1_administrative_chancellery_syntax"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c1_04_statutory_legislative_drafting"],
        "communicativeFunctionsReviewed": ["comm_b2_09_formal_policy_recommendations"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": ["шагнал", "цол", "соёрхох", "үндэслэл", "хүчин төгөлдөр"],
        "readingObjective": "Analyze the formulaic rhetorical architecture of state decrees linking constitutional authorizations to operative commands.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "presidential ceremonial chancellery",
        "pragmaticTarget": "formal state validation",
        "prerequisiteLessonIds": ["les_c1_199_01_archaic_jussive_syntax_intro"],
        "reviewsLessonIds": ["les_c1_198_02_constitutional_articles_parsing_reading"],
        "reviewsUnitIds": ["unit_c1_198_the_1992_democratic_constitution_of"],
        "reviewReason": "Traces constitutional authority clauses directly into executive presidential decree formulations.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Extracts the constitutional statutory basis authorizing the decree from the preamble participial clause",
          "Identifies the exact legal duties assigned to executive agencies in the operative jussive clauses"
        ],
        "masteryEvidence": "Summarizes the legal scope and ministerial duties established by a 480-word presidential decree with complete accuracy.",
        "recommendedExerciseModalities": ["source_comparison", "claim_evidence_matching"]
      },
      {
        "lessonId": "les_c1_199_03_drafting_statutory_enactments_writing",
        "unitId": "unit_c1_199_archaic_classical_jussives_suffixes",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 3,
        "title": "Legislative Drafting: Operative Clauses & Formal Enactment Decrees",
        "lessonType": "writing",
        "primaryPurpose": "Author a 400-word formal Government Resolution (Засгийн газрын тогтоол) or statutory enactment deploying classical jussives ('тушаасугай', 'даалгасугай', 'мөрдсүгэй').",
        "communicativeOutcome": "Produce legally binding chancellery text matching official Mongolian Government gazette publishing standards.",
        "objectivesIntroduced": ["obj_c1_199_03_draft_binding_enactments"],
        "objectivesPracticed": ["obj_c1_199_01_master_classical_jussives"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_archaic_jussive_sugai_tugai"],
        "grammarReviewed": ["gram_c1_administrative_chancellery_syntax"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c1_04_statutory_legislative_drafting"],
        "communicativeFunctionsReviewed": ["comm_b2_09_formal_policy_recommendations"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 1,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": ["захирамж", "үүрэг болгох", "хяналт тавих", "төсөв хуваарилах"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Draft a multi-clause administrative resolution specifying enforcement timelines, responsible ministers, and audit criteria.",
        "spokenProductionObjective": "",
        "registerTarget": "state legislative chancellery",
        "pragmaticTarget": "deontic legislative mandate",
        "prerequisiteLessonIds": ["les_c1_199_02_presidential_decree_preambles_reading"],
        "reviewsLessonIds": ["les_c1_198_03_sovereign_rights_commentary_writing"],
        "reviewsUnitIds": ["unit_c1_198_the_1992_democratic_constitution_of"],
        "reviewReason": "Synthesizes constitutional commentary principles into operative legislative decree drafting.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Constructs a four-article resolution with flawless preamble citations and operative jussive predicates",
          "Avoids colloquial imperative or conversational modal structures throughout the drafting"
        ],
        "masteryEvidence": "Submits a compliant Government resolution establishing a state conservation agency adhering to official Gazette protocol.",
        "recommendedExerciseModalities": ["statutory_clause_drafting", "summary_writing"]
      },
      {
        "lessonId": "les_c1_199_04_state_ceremonial_proclamations_spoken",
        "unitId": "unit_c1_199_archaic_classical_jussives_suffixes",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 4,
        "title": "Ceremonial Oratory: Delivering State Proclamations & Investiture Decrees",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver a 3.5-minute formal oral proclamation of a state decree conferring national honors or promulgating a solemn public statute.",
        "communicativeOutcome": "Execute solemn, measured ceremonial oratory adhering to state protocol cadence (120-140 wpm) with impeccable phonological phrasing.",
        "objectivesIntroduced": ["obj_c1_199_04_recite_state_proclamations"],
        "objectivesPracticed": ["obj_c1_199_01_master_classical_jussives"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_archaic_jussive_sugai_tugai"],
        "grammarReviewed": ["gram_c1_administrative_chancellery_syntax"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c1_04_statutory_legislative_drafting"],
        "communicativeFunctionsReviewed": ["comm_b2_13_scholarly_synthesis"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": ["хүндэтгэл", "ёслол", "уншиж сонсгох", "төрийн дуулал"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Recite a state ceremonial investiture proclamation with gravitas, precise vowel quantities, and authoritative terminal falling intonation.",
        "registerTarget": "state ceremonial oratorical",
        "pragmaticTarget": "solemn investiture",
        "prerequisiteLessonIds": ["les_c1_199_03_drafting_statutory_enactments_writing"],
        "reviewsLessonIds": ["les_b2_197_05_world_congress_plenary_speech"],
        "reviewsUnitIds": ["unit_b2_197_b2_vantage_capstone_academic_sympos"],
        "reviewReason": "Bridges B2 academic plenary oration into solemn C1 state ceremonial proclamation cadence.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide benchmark recording of Chief of Staff of the President reading state awards decree at the State Ceremonial Hall.",
        "successCriteria": [
          "Articulates archaic suffixes (-сугай/-сүгэй, -тугай/-түгэй) with resonant solemnity without stumbling",
          "Executes deliberate pauses separating preamble grounds from operational mandates"
        ],
        "masteryEvidence": "Records a flawless 3-minute oral delivery of a national proclamation broadcast simulation.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "reformulation"]
      },
      {
        "lessonId": "les_c1_199_05_oath_taking_and_promulgation_listening",
        "unitId": "unit_c1_199_archaic_classical_jussives_suffixes",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 5,
        "title": "Acoustic Dissection: Presidential Inauguration Oath & Promulgation Ceremonies",
        "lessonType": "listening",
        "primaryPurpose": "Listen to a 4-minute unedited broadcast of the Presidential Inauguration Ceremony in the State Great Khural, analyzing the solemn oath of office and decree promulgations.",
        "communicativeOutcome": "Process highly stylized archaic and formal juristic vows delivered in ceremonial acoustics with 100% conceptual precision.",
        "objectivesIntroduced": ["obj_c1_199_05_comprehend_state_oaths"],
        "objectivesPracticed": ["obj_c1_199_01_master_classical_jussives"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_archaic_jussive_sugai_tugai"],
        "grammarReviewed": ["gram_b2_indirect_discourse_framing_verbs"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c1_04_statutory_legislative_drafting"],
        "communicativeFunctionsReviewed": ["comm_b2_02_parliamentary_interpellation"],
        "newProductiveLemmaTarget": 4,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 1,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": ["тангараг өргөх", "төрийн далбаа", "адислах", "үнэнч байх"],
        "readingObjective": "",
        "listeningObjective": "Comprehend formulaic constitutional vows and formal presidential pledges spoken under live ceremonial conditions.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "state ceremonial constitutional",
        "pragmaticTarget": "sacred public commitment",
        "prerequisiteLessonIds": ["les_c1_199_02_presidential_decree_preambles_reading"],
        "reviewsLessonIds": ["les_c1_198_05_parliamentary_debates_on_basic_law_listening"],
        "reviewsUnitIds": ["unit_c1_198_the_1992_democratic_constitution_of"],
        "reviewReason": "Links parliamentary debate listening into solemn constitutional investiture ceremonies.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide live broadcast recording of the oath-taking ceremony in the Great Hall of the State Great Khural.",
        "successCriteria": [
          "Transcribes the exact phrasing of the presidential constitutional oath without missing archaic legal formulas",
          "Identifies the ceremonial turn transitions between the Speaker of Parliament and the President-elect"
        ],
        "masteryEvidence": "Analyzes and contrasts the archaic rhetorical formulas in the oath with standard contemporary legal prose.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "discourse_analysis"]
      }
    ])
    
    # Unit 200: Statutory Drafting & Legal Framing Formulations (PL=24, RL=27, PE=8, RE=6)
    lessons.extend([
      {
        "lessonId": "les_c1_200_01_legal_statutory_framing_syntax_intro",
        "unitId": "unit_c1_200_statutory_drafting_legal_framing_fo",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 1,
        "title": "Morphosyntax: Statutory Framing Formulations & Deontic Legislative Modifiers",
        "lessonType": "grammar_introduction",
        "primaryPurpose": "Introduce the specialized morphosyntactic framing conventions of Mongolian statutory drafting: obligation predicates ('үүрэг хүлээнэ', 'үүрэгтэй'), entitlement formulas ('эрх эдэлнэ', 'эрхтэй'), prohibitive prohibitions ('хориглоно', 'үл зөвшөөрнө'), and conditional scope boundaries.",
        "communicativeOutcome": "Distinguish and deploy rigorous deontic legislative formulas that establish enforceable legal rights and duties without semantic ambiguity.",
        "objectivesIntroduced": ["obj_c1_200_01_master_statutory_framing"],
        "objectivesPracticed": [],
        "objectivesReviewed": ["obj_c1_199_01_master_classical_jussives"],
        "grammarIntroduced": ["gram_c1_legal_statutory_framing"],
        "grammarPracticed": ["gram_c1_administrative_chancellery_syntax"],
        "grammarReviewed": ["gram_b2_modal_complex_obligation_uchirtai"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": ["comm_c1_04_statutory_legislative_drafting"],
        "communicativeFunctionsPracticed": [],
        "communicativeFunctionsReviewed": ["comm_b2_09_formal_policy_recommendations"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": ["хуулийн заалт", "хэм хэмжээ", "зохицуулалт", "хариуцлага", "зөрчил"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "statutory codification",
        "pragmaticTarget": "normative legal precision",
        "prerequisiteLessonIds": ["les_c1_199_03_drafting_statutory_enactments_writing"],
        "reviewsLessonIds": ["les_c1_198_01_administrative_chancellery_syntax_intro"],
        "reviewsUnitIds": ["unit_c1_198_the_1992_democratic_constitution_of"],
        "reviewReason": "Consolidates chancellery syntax into precise normative statutory article framing formulas.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Differentiates between mandatory obligations ('үүрэгтэй'), discretionary permissions ('эрхтэй'), and strict statutory prohibitions ('хориглоно')",
          "Structures conditional statutory sub-clauses with clear scope demarcation"
        ],
        "masteryEvidence": "Drafts 5 distinct statutory provisions correctly assigning rights, duties, and penal triggers according to Mongolian legislative standards.",
        "recommendedExerciseModalities": ["statutory_clause_drafting", "discourse_analysis"]
      },
      {
        "lessonId": "les_c1_200_02_statutory_articles_subclauses_reading",
        "unitId": "unit_c1_200_statutory_drafting_legal_framing_fo",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 2,
        "title": "Statutory Reading: Legislative Code Architecture & Penalty Clauses",
        "lessonType": "reading",
        "primaryPurpose": "Parse a 500-word extract from the Mongolian Civil Code and Law on Administrative Infractions, scrutinizing definitions, general provisions, exceptions, and sanctions.",
        "communicativeOutcome": "Trace cross-references, exclusionary clauses, and administrative sanction mechanisms across interwoven statutory articles.",
        "objectivesIntroduced": ["obj_c1_200_02_parse_statutory_codes"],
        "objectivesPracticed": ["obj_c1_200_01_master_statutory_framing"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_legal_statutory_framing"],
        "grammarReviewed": ["gram_c1_administrative_chancellery_syntax"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c1_04_statutory_legislative_drafting"],
        "communicativeFunctionsReviewed": ["comm_b2_09_formal_policy_recommendations"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 1,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": ["иргэний хууль", "зөрчлийн хууль", "торгууль", "шийтгэл", "нөхөн төлбөр"],
        "readingObjective": "Navigate multi-tiered statutory codes, evaluating how exceptions ('энэ хуулийн ...-д зааснаас бусад тохиолдолд') modify default norms.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "statutory codification",
        "pragmaticTarget": "statutory boundary demarcation",
        "prerequisiteLessonIds": ["les_c1_200_01_legal_statutory_framing_syntax_intro"],
        "reviewsLessonIds": ["les_c1_198_02_constitutional_articles_parsing_reading"],
        "reviewsUnitIds": ["unit_c1_198_the_1992_democratic_constitution_of"],
        "reviewReason": "Extends constitutional rights reading into subordinate statutory code structure and penal enforcement.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Identifies how statutory exclusions qualify primary legal duties in contested liability cases",
          "Maps legal consequences tied to breach of specific subclauses without misinterpreting statutory references"
        ],
        "masteryEvidence": "Solves a complex legal scenario problem by applying 3 interrelated articles of the Civil Code accurately.",
        "recommendedExerciseModalities": ["claim_evidence_matching", "source_comparison"]
      },
      {
        "lessonId": "les_c1_200_03_statutory_amendment_provisions_writing",
        "unitId": "unit_c1_200_statutory_drafting_legal_framing_fo",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 3,
        "title": "Legislative Drafting: Statutory Amendment Bill & Transitional Provisions",
        "lessonType": "writing",
        "primaryPurpose": "Draft a 420-word formal legislative amendment bill ('Хуульд нэмэлт, өөрчлөлт оруулах тухай хуулийн төсөл') complete with enacting formulas, amended clauses, and transitional enforcement timelines.",
        "communicativeOutcome": "Author legislative text adhering strictly to the Law on Legislation of Mongolia (Хууль тогтоомжийн тухай хууль).",
        "objectivesIntroduced": ["obj_c1_200_03_author_statutory_bills"],
        "objectivesPracticed": ["obj_c1_200_01_master_statutory_framing"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_legal_statutory_framing"],
        "grammarReviewed": ["gram_c1_administrative_chancellery_syntax"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c1_04_statutory_legislative_drafting"],
        "communicativeFunctionsReviewed": ["comm_b2_09_formal_policy_recommendations"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": ["төсөл", "нэмэлт өөрчлөлт", "хүчингүй болгох", "дагаж мөрдөх журам"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Draft an official parliamentary amendment bill introducing specific regulatory modifications with flawless statutory phrasing.",
        "spokenProductionObjective": "",
        "registerTarget": "statutory legislative",
        "pragmaticTarget": "formal lawmaking enactment",
        "prerequisiteLessonIds": ["les_c1_200_02_statutory_articles_subclauses_reading"],
        "reviewsLessonIds": ["les_c1_199_03_drafting_statutory_enactments_writing"],
        "reviewsUnitIds": ["unit_c1_199_archaic_classical_jussives_suffixes"],
        "reviewReason": "Builds upon government decree drafting to master full parliamentary statutory amendment bills.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Formats amendment articles ('... хуулийн ... дүгээр зүйлийн ... дахь хэсгийг доор дурдсанаар өөрчлөн найруулсугай') flawlessly",
          "Includes precise transitional enforcement provisions ensuring legal continuity"
        ],
        "masteryEvidence": "Submits a complete 3-article draft amendment bill revising renewable energy concessions conforming to ministry submission standards.",
        "recommendedExerciseModalities": ["statutory_clause_drafting", "paragraph_reconstruction"]
      },
      {
        "lessonId": "les_c1_200_04_legislative_drafting_defense_spoken",
        "unitId": "unit_c1_200_statutory_drafting_legal_framing_fo",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 4,
        "title": "Legislative Advocacy: Defending Bill Provisions in Standing Committee Hearings",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver a 4-minute spoken defense of a draft statutory amendment before the Parliamentary Standing Committee on Legal Affairs, justifying legal necessity and regulatory coherence.",
        "communicativeOutcome": "Present and defend legislative definitions and legal remedies against skepticism from committee MPs with precision and composure.",
        "objectivesIntroduced": ["obj_c1_200_04_defend_bill_provisions_orally"],
        "objectivesPracticed": ["obj_c1_200_01_master_statutory_framing"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_legal_statutory_framing"],
        "grammarReviewed": ["gram_b2_conditionals_hypothetical_present"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c1_04_statutory_legislative_drafting"],
        "communicativeFunctionsReviewed": ["comm_b2_02_parliamentary_interpellation"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": ["байнгын хороо", "хэлэлцүүлэг", "үзэл баримтлал", "үр нөлөө"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Argue persuasively for the adoption of legislative articles, articulating statutory rationale and fielding critical parliamentary queries.",
        "registerTarget": "parliamentary legislative formal",
        "pragmaticTarget": "persuasive statutory justification",
        "prerequisiteLessonIds": ["les_c1_200_03_statutory_amendment_provisions_writing"],
        "reviewsLessonIds": ["les_c1_198_04_constitutional_order_deliberation_spoken"],
        "reviewsUnitIds": ["unit_c1_198_the_1992_democratic_constitution_of"],
        "reviewReason": "Deepens oral constitutional defense into granular statutory clause justification.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide parliamentary standing committee testimony model featuring structured clause defense and MP questioning.",
        "successCriteria": [
          "Articulates legal necessity using statutory framing terminology without colloquial approximations",
          "Responds directly to procedural challenges citing specific articles of the Law on Legislation"
        ],
        "masteryEvidence": "Defends a controversial amendment during a simulated 4-minute committee debate with rigorous juristic rationale.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
      },
      {
        "lessonId": "les_c1_200_05_standing_committee_statutory_debate_listening",
        "unitId": "unit_c1_200_statutory_drafting_legal_framing_fo",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 5,
        "title": "Acoustic Dissection: Parliamentary Committee Clause-by-Clause Review Session",
        "lessonType": "listening",
        "primaryPurpose": "Listen to a 4-minute authentic audio recording of a parliamentary standing committee conducting a clause-by-clause reading of a commercial statute.",
        "communicativeOutcome": "Comprehend technical legislative amendments proposed on the fly by lawmakers speaking rapidly (150-170 wpm) amidst parliamentary cross-talk.",
        "objectivesIntroduced": ["obj_c1_200_05_comprehend_clause_review_debates"],
        "objectivesPracticed": ["obj_c1_200_01_master_statutory_framing"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_legal_statutory_framing"],
        "grammarReviewed": ["gram_c1_administrative_chancellery_syntax"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c1_04_statutory_legislative_drafting"],
        "communicativeFunctionsReviewed": ["comm_b2_02_parliamentary_interpellation"],
        "newProductiveLemmaTarget": 4,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 1,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": ["зарчмын зөрүүтэй санал", "санал хураалт", "дэмжих", "татгалзах"],
        "readingObjective": "",
        "listeningObjective": "Track fast-paced parliamentary drafting exchanges, identifying textual alterations, vote calls, and committee chair rulings.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "parliamentary technical legislative",
        "pragmaticTarget": "procedural debate tracking",
        "prerequisiteLessonIds": ["les_c1_200_02_statutory_articles_subclauses_reading"],
        "reviewsLessonIds": ["les_c1_198_05_parliamentary_debates_on_basic_law_listening"],
        "reviewsUnitIds": ["unit_c1_198_the_1992_democratic_constitution_of"],
        "reviewReason": "Transitions from plenary constitutional debates to technical clause-by-clause legislative drafting reviews.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide live committee room recording containing rapid procedural exchanges, microphone rustle, and technical amendments.",
        "successCriteria": [
          "Transcribes the exact wording of a proposed substantive amendment ('зарчмын зөрүүтэй санал') amidst noisy audio",
          "Determines whether the committee vote approved or rejected the amended phrasing"
        ],
        "masteryEvidence": "Produces an accurate legislative markup tracking 3 specific wording modifications adopted during the committee session.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "stance_identification"]
      }
    ])
    
    # Unit 201: Appositive Titles, Epithets & Chancellery Preambles (PL=24, RL=27, PE=8, RE=6)
    lessons.extend([
      {
        "lessonId": "les_c1_201_01_complex_appositive_titles_syntax_intro",
        "unitId": "unit_c1_201_appositive_titles_epithets_chancell",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 1,
        "title": "Morphosyntax: Elaborate Appositive Titles, Diplomatic Epithets & Chancellery Preambles",
        "lessonType": "grammar_introduction",
        "primaryPurpose": "Introduce the syntactic mechanics of multi-word appositive titles, state honorific epithets ('Онц бөгөөд Бүрэн эрхт', 'Эрхэмсэг ноён/хатагтай'), and chancellery preambular framing preceding diplomatic and state correspondence.",
        "communicativeOutcome": "Construct and parse elaborate chancellery titles, ensuring grammatical agreement and protocol precedence across multi-nominal apposition chains.",
        "objectivesIntroduced": ["obj_c1_201_01_master_appositive_titles"],
        "objectivesPracticed": [],
        "objectivesReviewed": ["obj_c1_200_01_master_statutory_framing"],
        "grammarIntroduced": ["gram_c1_complex_appositive_titles_and_epithets"],
        "grammarPracticed": ["gram_c1_administrative_chancellery_syntax"],
        "grammarReviewed": ["gram_b2_discourse_connectors_rhetorical"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": ["comm_c1_02_diplomatic_official_receptions"],
        "communicativeFunctionsPracticed": [],
        "communicativeFunctionsReviewed": ["comm_b2_09_formal_policy_recommendations"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law", "lex_c1_diplomacy_geopolitics_foreign_policy"],
        "previousVocabularyReused": ["элчин сайд", "ноён", "хатагтай", "төлөөлөгч", "хүндэт"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "diplomatic state protocol",
        "pragmaticTarget": "protocolary deference and hierarchy",
        "prerequisiteLessonIds": ["les_c1_200_03_statutory_amendment_provisions_writing"],
        "reviewsLessonIds": ["les_c1_198_01_administrative_chancellery_syntax_intro"],
        "reviewsUnitIds": ["unit_c1_198_the_1992_democratic_constitution_of"],
        "reviewReason": "Incorporates complex honorific nominal appositions into formal administrative chancellery sentences.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Correctly assigns case inflection only to the terminal element in long multi-word appositive title chains",
          "Orders diplomatic ranks, institutional offices, and state honorific epithets in accordance with state protocol"
        ],
        "masteryEvidence": "Constructs 5 flawless diplomatic salutation strings and preambular titles for visiting foreign dignitaries.",
        "recommendedExerciseModalities": ["discourse_analysis", "stylistic_transformation"]
      },
      {
        "lessonId": "les_c1_201_02_historical_diplomatic_and_state_treaties_reading",
        "unitId": "unit_c1_201_appositive_titles_epithets_chancell",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 2,
        "title": "Historical & Diplomatic Reading: State Treaties & Diplomatic Credential Preambles",
        "lessonType": "reading",
        "primaryPurpose": "Parse an authentic 480-word diplomatic instrument: a Letter of Credence (Итгэмжлэх жуух бичиг) and bilateral treaty preamble incorporating elaborate state titles and archaic honorific epithets.",
        "communicativeOutcome": "Deconstruct high-level protocol texts, analyzing how sovereign titles establish diplomatic reciprocity and legal validity between states.",
        "objectivesIntroduced": ["obj_c1_201_02_parse_diplomatic_instruments"],
        "objectivesPracticed": ["obj_c1_201_01_master_appositive_titles"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_complex_appositive_titles_and_epithets"],
        "grammarReviewed": ["gram_c1_archaic_jussive_sugai_tugai"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c1_02_diplomatic_official_receptions"],
        "communicativeFunctionsReviewed": ["comm_b2_13_scholarly_synthesis"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law", "lex_c1_diplomacy_geopolitics_foreign_policy"],
        "previousVocabularyReused": ["итгэмжлэх жуух бичиг", "гэрээ", "батламж жуух", "харилцаа"],
        "readingObjective": "Analyze complex diplomatic instruments, decoding nested titular preambles, sovereign affirmations, and plenipotentiary authority grants.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "diplomatic protocolary high",
        "pragmaticTarget": "sovereign mutual recognition",
        "prerequisiteLessonIds": ["les_c1_201_01_complex_appositive_titles_syntax_intro"],
        "reviewsLessonIds": ["les_c1_199_02_presidential_decree_preambles_reading"],
        "reviewsUnitIds": ["unit_c1_199_archaic_classical_jussives_suffixes"],
        "reviewReason": "Contrasts domestic presidential decrees with bilateral international treaty instruments.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Identifies the plenipotentiary authority delegated to the ambassador from the titular preamble",
          "Interprets archaic epistolary formulaic expressions of mutual esteem and state sovereign friendship"
        ],
        "masteryEvidence": "Analyzes a 480-word diplomatic treaty preamble and maps the exact protocolary hierarchy of signatories.",
        "recommendedExerciseModalities": ["source_comparison", "claim_evidence_matching"]
      },
      {
        "lessonId": "les_c1_201_03_formal_chancellery_dispatch_writing",
        "unitId": "unit_c1_201_appositive_titles_epithets_chancell",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 3,
        "title": "Chancellery Writing: Diplomatic Note Verbale & Official State Dispatches",
        "lessonType": "writing",
        "primaryPurpose": "Author a 400-word formal Diplomatic Note (Ноот бичиг) from the Ministry of Foreign Affairs to a foreign embassy, deploying complex appositive titles and ceremonial formulas.",
        "communicativeOutcome": "Produce impeccable diplomatic correspondence conforming to Vienna Convention norms and Mongolian state chancellery style.",
        "objectivesIntroduced": ["obj_c1_201_03_author_diplomatic_notes"],
        "objectivesPracticed": ["obj_c1_201_01_master_appositive_titles"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_complex_appositive_titles_and_epithets"],
        "grammarReviewed": ["gram_c1_administrative_chancellery_syntax"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c1_02_diplomatic_official_receptions"],
        "communicativeFunctionsReviewed": ["comm_b2_09_formal_policy_recommendations"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law", "lex_c1_diplomacy_geopolitics_foreign_policy"],
        "previousVocabularyReused": ["ноот бичиг", "гадаад харилцааны яам", "гүнээ хүндэтгэх", "мэдэгдэх"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Draft an official Diplomatic Note regarding border transit arrangements, utilizing standard third-person opening and closing protocol formulas.",
        "spokenProductionObjective": "",
        "registerTarget": "diplomatic chancellery",
        "pragmaticTarget": "rigorous diplomatic courtesy",
        "prerequisiteLessonIds": ["les_c1_201_02_historical_diplomatic_and_state_treaties_reading"],
        "reviewsLessonIds": ["les_c1_200_03_statutory_amendment_provisions_writing"],
        "reviewsUnitIds": ["unit_c1_200_statutory_drafting_legal_framing_fo"],
        "reviewReason": "Synthesizes statutory drafting precision with diplomatic epistolary etiquette.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Opens with the mandatory formulaic courtesy ('Монгол Улсын Гадаад харилцааны яам нь ... Элчин сайдын яаманд гүнээ хүндэтгэлээ илэрхийлэхийн сацуу...') flawlessly",
          "Maintains formal third-person distancing throughout the substantive transit communication"
        ],
        "masteryEvidence": "Submits a formal diplomatic note requesting bilateral consular consultations compliant with ministry protocol.",
        "recommendedExerciseModalities": ["statutory_clause_drafting", "summary_writing"]
      },
      {
        "lessonId": "les_c1_201_04_protocolary_state_introductions_spoken",
        "unitId": "unit_c1_201_appositive_titles_epithets_chancell",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 4,
        "title": "Protocolary Speaking: Introducing Dignitaries at State Banquets & Bilateral Summits",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver formal spoken introductions and protocol toasts (3.5 minutes) introducing visiting heads of state and ambassadorial delegations at an official state reception.",
        "communicativeOutcome": "Announce foreign and domestic dignitaries orally with dignified presence, correct epithet stacking, and flawless prosodic timing.",
        "objectivesIntroduced": ["obj_c1_201_04_deliver_protocolary_introductions"],
        "objectivesPracticed": ["obj_c1_201_01_master_appositive_titles"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_complex_appositive_titles_and_epithets"],
        "grammarReviewed": ["gram_c1_archaic_jussive_sugai_tugai"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c1_02_diplomatic_official_receptions"],
        "communicativeFunctionsReviewed": ["comm_b2_13_scholarly_synthesis"],
        "newProductiveLemmaTarget": 4,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 1,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law", "lex_c1_diplomacy_geopolitics_foreign_policy"],
        "previousVocabularyReused": ["төрийн хүндэтгэлийн зоог", "хундага өргөх", "төлөөлөгчид", "найрсаг харилцаа"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Execute ceremonial toast and dignitary announcements adhering to state protocol etiquette and pitch-accent prominence.",
        "registerTarget": "state diplomatic oratorical",
        "pragmaticTarget": "ceremonial hospitality and deference",
        "prerequisiteLessonIds": ["les_c1_201_03_formal_chancellery_dispatch_writing"],
        "reviewsLessonIds": ["les_c1_199_04_state_ceremonial_proclamations_spoken"],
        "reviewsUnitIds": ["unit_c1_199_archaic_classical_jussives_suffixes"],
        "reviewReason": "Extends presidential proclamation recitation into international diplomatic banquet toasts.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide model recording of Chief of Protocol introducing visiting delegations at the State Ceremonial Complex.",
        "successCriteria": [
          "Recites full official titles without stumbling or colloquial shortening of titles",
          "Executes appropriate ceremonial pacing (125-140 wpm) and vocal projection"
        ],
        "masteryEvidence": "Delivers an unscripted 3-minute toast opening a high-level bilateral trade summit adhering to protocol guidelines.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "reformulation"]
      },
      {
        "lessonId": "les_c1_201_05_state_chancellery_protocol_briefing_listening",
        "unitId": "unit_c1_201_appositive_titles_epithets_chancell",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 5,
        "title": "Acoustic Dissection: State Protocol Briefing on Diplomatic Precedence & Credentials",
        "lessonType": "listening",
        "primaryPurpose": "Listen to a 4-minute operational briefing by the Director of State Protocol detailing diplomatic precedence, seating orders, and credential presentation etiquette.",
        "communicativeOutcome": "Comprehend complex protocol instructions, detecting subtle distinctions between order of arrival, ambassadorial seniority, and ceremonial exemptions.",
        "objectivesIntroduced": ["obj_c1_201_05_comprehend_protocol_briefings"],
        "objectivesPracticed": ["obj_c1_201_01_master_appositive_titles"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_complex_appositive_titles_and_epithets"],
        "grammarReviewed": ["gram_c1_legal_statutory_framing"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c1_02_diplomatic_official_receptions"],
        "communicativeFunctionsReviewed": ["comm_b2_02_parliamentary_interpellation"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 1,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law", "lex_c1_diplomacy_geopolitics_foreign_policy"],
        "previousVocabularyReused": ["протокол", "эгнээ", "суудал хуваарилалт", "ёслолын алба"],
        "readingObjective": "",
        "listeningObjective": "Extract detailed operational protocol instructions from fast spoken administrative speech regarding high-level state visits.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "state protocol administrative",
        "pragmaticTarget": "operational procedural clarity",
        "prerequisiteLessonIds": ["les_c1_201_02_historical_diplomatic_and_state_treaties_reading"],
        "reviewsLessonIds": ["les_c1_200_05_standing_committee_statutory_debate_listening"],
        "reviewsUnitIds": ["unit_c1_200_statutory_drafting_legal_framing_fo"],
        "reviewReason": "Bridges parliamentary debate listening into executive diplomatic protocol briefing analysis.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide authentic administrative audio of a protocol briefing covering seating hierarchies and title conventions.",
        "successCriteria": [
          "Identifies the exact diplomatic rank order and protocol seating arrangement described by the speaker",
          "Distinguishes between mandatory ceremonial requirements and discretionary embassy courtesies"
        ],
        "masteryEvidence": "Produces an accurate protocol run-down and seating chart for a 12-member delegation based solely on the audio briefing.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "discourse_analysis"]
      }
    ])
    
    # Unit 202: Causative Nominalizations in Institutional Governance (PL=24, RL=27, PE=8, RE=6)
    lessons.extend([
      {
        "lessonId": "les_c1_202_01_causative_nominalization_syntax_intro",
        "unitId": "unit_c1_202_causative_nominalizations_in_instit",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 1,
        "title": "Morphosyntax: Causative Nominalizations (-уулалт/-үүлэлт) in State Governance",
        "lessonType": "grammar_introduction",
        "primaryPurpose": "Introduce the morphosyntactic formation, agentive demotion, and institutional semantic force of causative nominalization suffixes (-уулалт/-үүлэлт, -лгалт/-лгэлт) derived from double causatives in governance discourse.",
        "communicativeOutcome": "Formulate and parse abstract governance processes (e.g. 'хэрэгжүүлэлт' implementation, 'сайжруулалт' upgrading, 'батлуулалт' securing ratification) expressing institutional delegation.",
        "objectivesIntroduced": ["obj_c1_202_01_master_causative_nominalizations"],
        "objectivesPracticed": [],
        "objectivesReviewed": ["obj_c1_201_01_master_appositive_titles"],
        "grammarIntroduced": ["gram_c1_causative_nominalizations_in_governance"],
        "grammarPracticed": ["gram_c1_administrative_chancellery_syntax"],
        "grammarReviewed": ["gram_b2_voice_double_causative_delegated"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": ["comm_c1_09_high_level_policy_briefs"],
        "communicativeFunctionsPracticed": [],
        "communicativeFunctionsReviewed": ["comm_b2_09_formal_policy_recommendations"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": ["хэрэгжүүлэх", "гүйцэтгэл", "зохион байгуулалт", "үр дүн", "бодлого"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "institutional administrative policy",
        "pragmaticTarget": "institutional agency and accountability",
        "prerequisiteLessonIds": ["les_c1_201_03_formal_chancellery_dispatch_writing"],
        "reviewsLessonIds": ["les_b2_172_01_double_causative_syntax_intro"],
        "reviewsUnitIds": ["unit_b2_172_pastoral_water_management_double_c"],
        "reviewReason": "Extends B2 double causative verb morphology into abstract institutional nominalizations.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Attaches causative nominalizing suffixes (-уулалт/-үүлэлт) to complex verbal bases without morphophonological error",
          "Distinguishes between process nominalizations ('хэрэгжүүлэлт') and stative result nominals ('гүйцэтгэл')"
        ],
        "masteryEvidence": "Transforms 6 active administrative directive clauses into abstract governance nominal phrases suitable for cabinet reports.",
        "recommendedExerciseModalities": ["stylistic_transformation", "discourse_analysis"]
      },
      {
        "lessonId": "les_c1_202_02_ministerial_mandates_and_orders_reading",
        "unitId": "unit_c1_202_causative_nominalizations_in_instit",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 2,
        "title": "Administrative Reading: Ministerial Accountability Audits & Implementation Mandates",
        "lessonType": "reading",
        "primaryPurpose": "Parse a 510-word ministerial performance audit report assessing agency implementation ('хэрэгжүүлэлтийн шат дараах тайлан') of national development targets.",
        "communicativeOutcome": "Analyze bureaucratic audit metrics, identifying where causative nominalizations shift responsibility between policy initiators, executive agencies, and contractors.",
        "objectivesIntroduced": ["obj_c1_202_02_parse_accountability_audits"],
        "objectivesPracticed": ["obj_c1_202_01_master_causative_nominalizations"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_causative_nominalizations_in_governance"],
        "grammarReviewed": ["gram_c1_administrative_chancellery_syntax"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c1_09_high_level_policy_briefs"],
        "communicativeFunctionsReviewed": ["comm_b2_09_formal_policy_recommendations"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": ["аудит", "хяналт шалгалт", "үнэлгээ", "шалгуур үзүүлэлт", "төлөвлөгөө"],
        "readingObjective": "Critique an institutional accountability audit, detecting bureaucratic obfuscation and tracking causative delegated mandates.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "state administrative audit",
        "pragmaticTarget": "critical administrative evaluation",
        "prerequisiteLessonIds": ["les_c1_202_01_causative_nominalization_syntax_intro"],
        "reviewsLessonIds": ["les_c1_200_02_statutory_articles_subclauses_reading"],
        "reviewsUnitIds": ["unit_c1_200_statutory_drafting_legal_framing_fo"],
        "reviewReason": "Examines statutory enforcement clauses in action within ministerial implementation reports.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Identifies the precise failure points in delegated procurement implementation ('худалдан авалтын зохион байгуулалт')",
          "Extracts ministerial corrective deadlines from complex administrative prose"
        ],
        "masteryEvidence": "Synthesizes an executive critique of agency underperformance based on the 510-word ministerial audit text.",
        "recommendedExerciseModalities": ["source_comparison", "claim_evidence_matching"]
      },
      {
        "lessonId": "les_c1_202_03_administrative_directive_drafting_writing",
        "unitId": "unit_c1_202_causative_nominalizations_in_instit",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 3,
        "title": "Executive Writing: Inter-Agency Action Plan Directives & Governance Memos",
        "lessonType": "writing",
        "primaryPurpose": "Author a 430-word inter-agency operational directive ('Хэрэгжүүлэх арга хэмжээний төлөвлөгөөний удирдамж') assigning delegated tasks across four ministries using causative nominalizations.",
        "communicativeOutcome": "Produce high-level executive directives coordinating cross-sectoral actions with institutional clarity.",
        "objectivesIntroduced": ["obj_c1_202_03_author_executive_directives"],
        "objectivesPracticed": ["obj_c1_202_01_master_causative_nominalizations"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_causative_nominalizations_in_governance"],
        "grammarReviewed": ["gram_c1_legal_statutory_framing"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c1_09_high_level_policy_briefs"],
        "communicativeFunctionsReviewed": ["comm_b2_09_formal_policy_recommendations"],
        "newProductiveLemmaTarget": 4,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 1,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": ["салбар хоорондын уялдаа", "ажлын хэсэг", "үүрэг даалгавар", "тайлагнах хугацаа"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Draft a structured inter-agency directive assigning specific implementation, monitoring, and sanction powers.",
        "spokenProductionObjective": "",
        "registerTarget": "executive administrative governance",
        "pragmaticTarget": "authoritative task delegation",
        "prerequisiteLessonIds": ["les_c1_202_02_ministerial_mandates_and_orders_reading"],
        "reviewsLessonIds": ["les_c1_201_03_formal_chancellery_dispatch_writing"],
        "reviewsUnitIds": ["unit_c1_201_appositive_titles_epithets_chancell"],
        "reviewReason": "Transitions from external diplomatic dispatches into internal inter-ministerial executive directives.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Deploys at least 5 varied causative nominalization constructions ('батлуулалт', 'хэрэгжүүлэлт', 'сайжруулалт') naturally",
          "Clearly delimits supervisory roles versus implementing agency duties"
        ],
        "masteryEvidence": "Submits an executive directive establishing an inter-agency anti-corruption monitoring task force.",
        "recommendedExerciseModalities": ["statutory_clause_drafting", "summary_writing"]
      },
      {
        "lessonId": "les_c1_202_04_inter_ministerial_coordination_briefing_spoken",
        "unitId": "unit_c1_202_causative_nominalizations_in_instit",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 4,
        "title": "Executive Briefing: Inter-Agency Task Force Operational Deliberation",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver an unscripted 4-minute executive verbal briefing coordinating multiple ministerial state secretaries during a national infrastructure crisis.",
        "communicativeOutcome": "Negotiate jurisdictional boundaries, demand accountability, and issue delegated orders using authoritative institutional spoken discourse.",
        "objectivesIntroduced": ["obj_c1_202_04_lead_executive_briefings"],
        "objectivesPracticed": ["obj_c1_202_01_master_causative_nominalizations"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_causative_nominalizations_in_governance"],
        "grammarReviewed": ["gram_c1_administrative_chancellery_syntax"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c1_09_high_level_policy_briefs"],
        "communicativeFunctionsReviewed": ["comm_b2_10_high_stakes_negotiation"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 5,
        "newProductiveExpressionTarget": 1,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": ["төрийн нарийн бичгийн дарга", "шуурхай хуралдаан", "зохицуулалт", "үүрэг өгөх"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Lead an executive task force coordination session, fielding inter-agency jurisdictional objections with decisive command.",
        "registerTarget": "executive administrative consultative",
        "pragmaticTarget": "firm institutional coordination",
        "prerequisiteLessonIds": ["les_c1_202_03_administrative_directive_drafting_writing"],
        "reviewsLessonIds": ["les_c1_200_04_legislative_drafting_defense_spoken"],
        "reviewsUnitIds": ["unit_c1_200_statutory_drafting_legal_framing_fo"],
        "reviewReason": "Bridges parliamentary legislative defense into executive crisis task force coordination speaking.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide model audio of Cabinet Secretariat State Secretary chairing an emergency inter-agency coordination meeting.",
        "successCriteria": [
          "Addresses ministerial peers with appropriate professional deference while asserting central government mandates",
          "Resolves overlapping agency responsibilities by establishing explicit delivery deadlines"
        ],
        "masteryEvidence": "Chairs a 4-minute simulated inter-agency crisis session managing conflicting logistics directives without communication breakdown.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
      },
      {
        "lessonId": "les_c1_202_05_administrative_enforcement_hearing_listening",
        "unitId": "unit_c1_202_causative_nominalizations_in_instit",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 5,
        "title": "Acoustic Dissection: State Inspection Agency Enforcement & Sanction Hearing",
        "lessonType": "listening",
        "primaryPurpose": "Listen to a 4.5-minute unscripted audio recording of a State Specialized Inspection Agency (МХЕГ) formal enforcement hearing addressing severe environmental compliance breaches.",
        "communicativeOutcome": "Comprehend adversarial administrative hearings, dissecting defense appeals, technical inspector citations, and binding closure orders.",
        "objectivesIntroduced": ["obj_c1_202_05_comprehend_enforcement_hearings"],
        "objectivesPracticed": ["obj_c1_202_01_master_causative_nominalizations"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_causative_nominalizations_in_governance"],
        "grammarReviewed": ["gram_c1_legal_statutory_framing"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c1_09_high_level_policy_briefs"],
        "communicativeFunctionsReviewed": ["comm_b2_02_parliamentary_interpellation"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": ["улсын байцаагч", "дүгнэлт", "акт тавих", "үйл ажиллагааг зогсоох", "гомдол"],
        "readingObjective": "",
        "listeningObjective": "Decipher high-speed adversarial dialogue between chief state inspectors and corporate defense lawyers debating regulatory sanctions.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "administrative regulatory adversarial",
        "pragmaticTarget": "regulatory sanction determination",
        "prerequisiteLessonIds": ["les_c1_202_02_ministerial_mandates_and_orders_reading"],
        "reviewsLessonIds": ["les_c1_201_05_state_chancellery_protocol_briefing_listening"],
        "reviewsUnitIds": ["unit_c1_201_appositive_titles_epithets_chancell"],
        "reviewReason": "Transitions from diplomatic protocol listening to high-stakes administrative enforcement hearings.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide live hearing recording featuring overlapping legal objections, document citations, and formal inspector verdicts.",
        "successCriteria": [
          "Transcribes the legal articles cited by the inspector as grounds for halting mining activities",
          "Identifies the procedural flaws claimed by the corporate defense counsel"
        ],
        "masteryEvidence": "Produces an accurate hearing summary detailing the regulatory infractions, penalties assessed, and remediation timeline.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "stance_identification"]
      }
    ])

    return lessons

if __name__ == '__main__':
    ls = get_units_198_202()
    print(f"Units 198-202 total lessons: {len(ls)}")
