# -*- coding: utf-8 -*-
"""Part 2 of Section 01: Units 203 to 207 (22 lessons)."""

def get_units_203_207():
    lessons = []

    # ----------------------------------------------------
    # UNIT 203: Courtroom Argumentation: Prosecutor & Defense Appeals (PL=22, RL=26, PE=8, RE=6)
    # ----------------------------------------------------
    lessons.extend([
      {
        "lessonId": "les_c1_203_01_appellate_court_briefs_reading",
        "unitId": "unit_c1_203_courtroom_argumentation_prosecutor_",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 1,
        "title": "Judicial Reading: Appellate Court Briefs & Evidentiary Rebuttals",
        "lessonType": "reading",
        "primaryPurpose": "Parse a 520-word appellate court defense memorial challenging prosecutorial indictments under the Criminal Procedure Code of Mongolia, identifying evidentiary admissibility arguments.",
        "communicativeOutcome": "Extract contested legal doctrines, procedural violation claims, and evidentiary exclusions from sophisticated juristic court pleadings.",
        "objectivesIntroduced": ["obj_c1_203_01_parse_appellate_briefs"],
        "objectivesPracticed": ["obj_c1_200_01_master_statutory_framing"],
        "objectivesReviewed": ["obj_c1_198_01_parse_chancellery_nominalizations"],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_legal_statutory_framing"],
        "grammarReviewed": ["gram_c1_administrative_chancellery_syntax"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": ["comm_c1_04_statutory_legislative_drafting"],
        "communicativeFunctionsPracticed": [],
        "communicativeFunctionsReviewed": ["comm_b2_09_formal_policy_recommendations"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 7,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": ["давж заалдах", "прокурор", "өмгөөлөгч", "нотлох баримт", "шүүхийн тогтоол"],
        "readingObjective": "Critique complex juristic arguments asserting constitutional due process breaches in lower court trial records.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "courtroom appellate juristic",
        "pragmaticTarget": "adversarial judicial challenge",
        "prerequisiteLessonIds": ["les_c1_202_03_administrative_directive_drafting_writing"],
        "reviewsLessonIds": ["les_c1_200_02_statutory_articles_subclauses_reading"],
        "reviewsUnitIds": ["unit_c1_200_statutory_drafting_legal_framing_fo"],
        "reviewReason": "Applies statutory code reading directly to appellate criminal and civil litigation pleadings.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Identifies the precise procedural violation invoked to demand the suppression of unlawfully obtained evidence",
          "Distinguishes between substantive statutory defenses and procedural jurisdictional objections"
        ],
        "masteryEvidence": "Constructs an evidence admissibility chart contrasting prosecutorial claims with defense rebuttals based on the text.",
        "recommendedExerciseModalities": ["argument_mapping", "source_comparison"]
      },
      {
        "lessonId": "les_c1_203_02_judicial_hearing_prosecutorial_summation_listening",
        "unitId": "unit_c1_203_courtroom_argumentation_prosecutor_",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 2,
        "title": "Acoustic Dissection: Live Courtroom Trial — State Prosecutor Closing Summation",
        "lessonType": "listening",
        "primaryPurpose": "Listen to a 4.5-minute unedited audio recording of a state prosecutor delivering closing summations in a high-profile corruption trial before the Capital City Court of Appeals.",
        "communicativeOutcome": "Process rapid (155-175 wpm) oratorical courtroom argumentation, tracking statutory charge stacking and evidentiary burden formulas.",
        "objectivesIntroduced": ["obj_c1_203_02_comprehend_courtroom_summations"],
        "objectivesPracticed": ["obj_c1_203_01_parse_appellate_briefs"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_administrative_chancellery_syntax"],
        "grammarReviewed": ["gram_c1_legal_statutory_framing"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c1_04_statutory_legislative_drafting"],
        "communicativeFunctionsReviewed": ["comm_b2_02_parliamentary_interpellation"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 7,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": ["улсын яллагч", "ял дүгнэлт", "гэм буруу", "шийтгэл ногдуулах"],
        "readingObjective": "",
        "listeningObjective": "Decipher spoken prosecutorial rhetoric combining rigorous statutory citations with emotive societal appeals.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "courtroom judicial adversarial",
        "pragmaticTarget": "prosecutorial indictment",
        "prerequisiteLessonIds": ["les_c1_203_01_appellate_court_briefs_reading"],
        "reviewsLessonIds": ["les_c1_202_05_administrative_enforcement_hearing_listening"],
        "reviewsUnitIds": ["unit_c1_202_causative_nominalizations_in_instit"],
        "reviewReason": "Extends administrative enforcement hearing comprehension into formal criminal appellate court hearings.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide authentic courtroom acoustics featuring judge interjections, prosecutor pacing, and formal legal cadences.",
        "successCriteria": [
          "Transcribes the precise statutory criminal article provisions and requested sentencing terms without error",
          "Identifies how the prosecutor establishes intent and causal nexus through syntactic subordination"
        ],
        "masteryEvidence": "Summarizes the prosecutor's 3 primary evidentiary pillars and proposed sentence from the oral testimony.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "stance_identification"]
      },
      {
        "lessonId": "les_c1_203_03_appellate_oral_pleading_defense_spoken",
        "unitId": "unit_c1_203_courtroom_argumentation_prosecutor_",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 3,
        "title": "Adversarial Advocacy: Defense Counsel Oral Pleading & Motion Practice",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver an unscripted 4-minute defense oral pleading before a 3-judge appellate panel, rebutting prosecutorial charges and motioning for complete dismissal.",
        "communicativeOutcome": "Present persuasive courtroom arguments with judicial gravitas, handling judicial bench interruptions with rapid legal agility.",
        "objectivesIntroduced": ["obj_c1_203_03_deliver_courtroom_oral_pleadings"],
        "objectivesPracticed": ["obj_c1_203_01_parse_appellate_briefs"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_administrative_chancellery_syntax"],
        "grammarReviewed": ["gram_c1_legal_statutory_framing"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c1_04_statutory_legislative_drafting"],
        "communicativeFunctionsReviewed": ["comm_b2_10_high_stakes_negotiation"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": ["хэрэгсэхгүй болгох", "цагаатгах", "өмгөөллийн үг", "шүүх бүрэлдэхүүн"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Execute an authoritative courtroom defense summation, refuting statutory misapplications with persuasive juristic rhetoric.",
        "registerTarget": "courtroom judicial advocacy",
        "pragmaticTarget": "persuasive legal refutation",
        "prerequisiteLessonIds": ["les_c1_203_02_judicial_hearing_prosecutorial_summation_listening"],
        "reviewsLessonIds": ["les_c1_202_04_inter_ministerial_coordination_briefing_spoken"],
        "reviewsUnitIds": ["unit_c1_202_causative_nominalizations_in_instit"],
        "reviewReason": "Bridges executive task force advocacy into courtroom judicial defense oral pleading.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide benchmark audio of senior advocate delivering oral defense pleading before the Court of Appeals.",
        "successCriteria": [
          "Addresses the judicial panel using mandatory court honorifics ('Хүндэт шүүх бүрэлдэхүүн') appropriately",
          "Dismantles prosecutorial evidentiary claims citing specific statutory infractions without hesitation"
        ],
        "masteryEvidence": "Performs a 4-minute simulated appellate court argument responding successfully to 2 aggressive bench questions.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
      },
      {
        "lessonId": "les_c1_203_04_drafting_grounds_for_appeal_writing",
        "unitId": "unit_c1_203_courtroom_argumentation_prosecutor_",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 4,
        "title": "Juristic Writing: Formal Notice of Appeal & Assignment of Errors",
        "lessonType": "writing",
        "primaryPurpose": "Draft a 420-word formal Notice of Appeal ('Давж заалдах гомдол') for submission to the High Court, articulating specific errors in statutory interpretation committed by the trial court.",
        "communicativeOutcome": "Produce legally binding appellate petitions satisfying all procedural requirements of the Civil or Criminal Procedure Code.",
        "objectivesIntroduced": ["obj_c1_203_04_draft_appellate_petitions"],
        "objectivesPracticed": ["obj_c1_203_01_parse_appellate_briefs"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_legal_statutory_framing"],
        "grammarReviewed": ["gram_c1_administrative_chancellery_syntax"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c1_04_statutory_legislative_drafting"],
        "communicativeFunctionsReviewed": ["comm_b2_09_formal_policy_recommendations"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": ["гомдлын шаардлага", "анхан шатны шүүх", "буруу хэрэглэсэн", "өөрчлөлт оруулах"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Draft an appellate brief demonstrating that the trial court erroneously interpreted or misapplied substantive statutory provisions.",
        "spokenProductionObjective": "",
        "registerTarget": "courtroom judicial chancellery",
        "pragmaticTarget": "formal appellate remedy petition",
        "prerequisiteLessonIds": ["les_c1_203_03_appellate_oral_pleading_defense_spoken"],
        "reviewsLessonIds": ["les_c1_200_03_statutory_amendment_provisions_writing"],
        "reviewsUnitIds": ["unit_c1_200_statutory_drafting_legal_framing_fo"],
        "reviewReason": "Synthesizes statutory drafting discipline into formal appellate judicial pleading drafting.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Articulates three distinct grounds for appeal citing specific sub-articles of the relevant code",
          "Structures the prayer for relief ('Гомдлын шаардлага') with complete procedural correctness"
        ],
        "masteryEvidence": "Submits a compliant 420-word appellate complaint petition seeking overturning of a civil commercial judgment.",
        "recommendedExerciseModalities": ["statutory_clause_drafting", "summary_writing"]
      }
    ])

    # ----------------------------------------------------
    # UNIT 204: Constitutional Court Jurisprudence (PL=22, RL=26, PE=8, RE=6)
    # ----------------------------------------------------
    lessons.extend([
      {
        "lessonId": "les_c1_204_01_tsets_verdicts_and_conclusions_reading",
        "unitId": "unit_c1_204_constitutional_court_jurisprudence_",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 1,
        "title": "Constitutional Reading: Tsets Conclusions (Дүгнэлт) & Plenary Resolutions (Тогтоол)",
        "lessonType": "reading",
        "primaryPurpose": "Parse a 520-word formal Conclusion of the Constitutional Court of Mongolia (Үндсэн хуулийн цэцийн дүгнэлт) striking down an unconstitutional parliamentary statute.",
        "communicativeOutcome": "Analyze constitutional jurisprudence reasoning, parsing constitutional balancing tests, supra-statutory norms, and judicial review doctrines.",
        "objectivesIntroduced": ["obj_c1_204_01_parse_tsets_jurisprudence"],
        "objectivesPracticed": ["obj_c1_198_01_parse_chancellery_nominalizations"],
        "objectivesReviewed": ["obj_c1_200_01_master_statutory_framing"],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_administrative_chancellery_syntax"],
        "grammarReviewed": ["gram_c1_legal_statutory_framing"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": ["comm_c1_04_statutory_legislative_drafting"],
        "communicativeFunctionsPracticed": [],
        "communicativeFunctionsReviewed": ["comm_b2_09_formal_policy_recommendations"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 7,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": ["үндсэн хуулийн цэц", "дүгнэлт", "хүчингүй болгох", "зөрчсөн", "маргаан"],
        "readingObjective": "Examine judicial review reasoning that invalidates parliamentary legislation on grounds of constitutional inconsistency.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "constitutional high judicial",
        "pragmaticTarget": "constitutional judicial review",
        "prerequisiteLessonIds": ["les_c1_203_04_drafting_grounds_for_appeal_writing"],
        "reviewsLessonIds": ["les_c1_198_02_constitutional_articles_parsing_reading"],
        "reviewsUnitIds": ["unit_c1_198_the_1992_democratic_constitution_of"],
        "reviewReason": "Deepens constitutional article analysis into Constitutional Court adjudicatory rulings.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Identifies the precise constitutional conflict between statutory legislation and supreme constitutional principles",
          "Distinguishes between a mid-tier Tsets Conclusion (Дүгнэлт) and a final Plenary Resolution (Тогтоол)"
        ],
        "masteryEvidence": "Constructs an analytical breakdown of a Tsets judicial decision evaluating rationale and legal effects.",
        "recommendedExerciseModalities": ["argument_mapping", "source_comparison"]
      },
      {
        "lessonId": "les_c1_204_02_tsets_plenary_session_deliberation_listening",
        "unitId": "unit_c1_204_constitutional_court_jurisprudence_",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 2,
        "title": "Acoustic Dissection: Constitutional Court Open Hearing Oral Arguments",
        "lessonType": "listening",
        "primaryPurpose": "Listen to a 4.5-minute authentic recording of a Constitutional Court open session where petitioner citizen representatives and parliamentary authorized representatives clash.",
        "communicativeOutcome": "Process highly abstract, dense constitutional debate delivered under formal court protocol at native oratorical tempo (150-170 wpm).",
        "objectivesIntroduced": ["obj_c1_204_02_comprehend_tsets_hearings"],
        "objectivesPracticed": ["obj_c1_204_01_parse_tsets_jurisprudence"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_administrative_chancellery_syntax"],
        "grammarReviewed": ["gram_c1_legal_statutory_framing"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c1_04_statutory_legislative_drafting"],
        "communicativeFunctionsReviewed": ["comm_b2_02_parliamentary_interpellation"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": ["итгэмжлэгдсэн төлөөлөгч", "цэцийн гишүүн", "мэтгэлцээн", "асуулт хариулт"],
        "readingObjective": "",
        "listeningObjective": "Extract nuanced legal interpretations during live Constitutional Court oral arguments between petitioning advocates and State Great Khural delegates.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "constitutional judicial deliberative",
        "pragmaticTarget": "supreme judicial contestation",
        "prerequisiteLessonIds": ["les_c1_204_01_tsets_verdicts_and_conclusions_reading"],
        "reviewsLessonIds": ["les_c1_203_02_judicial_hearing_prosecutorial_summation_listening"],
        "reviewsUnitIds": ["unit_c1_203_courtroom_argumentation_prosecutor_"],
        "reviewReason": "Elevates courtroom listening skills to Constitutional Court plenary hearings.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide live hearing audio featuring formal judicial protocol, solemn judge questions, and impassioned legal defense.",
        "successCriteria": [
          "Identifies the core constitutional contention regarding voter representation parity",
          "Follows multi-step judicial questioning testing the legislative intent behind the challenged statute"
        ],
        "masteryEvidence": "Produces a forensic debate summary mapping out the points of agreement, irreconcilable conflicts, and judicial interrogations.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "stance_identification"]
      },
      {
        "lessonId": "les_c1_204_03_constitutional_dispute_argumentation_spoken",
        "unitId": "unit_c1_204_constitutional_court_jurisprudence_",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 3,
        "title": "Constitutional Advocacy: Arguing Before the Bench of the Constitutional Court",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver an unscripted 4-minute constitutional oral argument representing an aggrieved citizen group before the Constitutional Court, demonstrating that a government decree violates fundamental rights.",
        "communicativeOutcome": "Present rigorous constitutional jurisprudence orally, weaving constitutional text, precedent conclusions, and human rights principles into a compelling plea.",
        "objectivesIntroduced": ["obj_c1_204_03_argue_constitutional_cases_orally"],
        "objectivesPracticed": ["obj_c1_204_01_parse_tsets_jurisprudence"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_administrative_chancellery_syntax"],
        "grammarReviewed": ["gram_c1_legal_statutory_framing"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c1_04_statutory_legislative_drafting"],
        "communicativeFunctionsReviewed": ["comm_b2_10_high_stakes_negotiation"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 7,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": ["үндсэн эрх", "зөрчигдсөн", "цэцийн их суудлын хуралдаан", "нотолгоо"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Argue persuasively before the Tsets bench, balancing statutory critique with foundational constitutional norms.",
        "registerTarget": "constitutional high judicial oral",
        "pragmaticTarget": "principled constitutional vindication",
        "prerequisiteLessonIds": ["les_c1_204_02_tsets_plenary_session_deliberation_listening"],
        "reviewsLessonIds": ["les_c1_203_03_appellate_oral_pleading_defense_spoken"],
        "reviewsUnitIds": ["unit_c1_203_courtroom_argumentation_prosecutor_"],
        "reviewReason": "Bridges appellate defense pleading into constitutional court judicial review advocacy.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide benchmark audio of constitutional scholar presenting amicus curiae oral argument before the Tsets.",
        "successCriteria": [
          "Frames arguments strictly within constitutional competence without relitigating factual evidentiary disputes",
          "Fields questions from the bench with respectful, legally grounded immediate answers"
        ],
        "masteryEvidence": "Delivers a 4-minute simulated constitutional oral defense proving the unconstitutionality of an administrative search regulation.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
      },
      {
        "lessonId": "les_c1_204_04_petition_to_constitutional_court_writing",
        "unitId": "unit_c1_204_constitutional_court_jurisprudence_",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 4,
        "title": "Juristic Writing: Drafting a Formal Petition (Өргөдөл, Мэдээлэл) to the Constitutional Court",
        "lessonType": "writing",
        "primaryPurpose": "Author a 450-word formal citizen petition ('Үндсэн хуулийн цэцэд гаргах мэдээлэл') requesting judicial review of a parliamentary tax statute alleged to violate property rights.",
        "communicativeOutcome": "Produce high-level constitutional litigation briefs adhering strictly to the Law on Constitutional Court Procedure.",
        "objectivesIntroduced": ["obj_c1_204_04_author_constitutional_petitions"],
        "objectivesPracticed": ["obj_c1_204_01_parse_tsets_jurisprudence"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_administrative_chancellery_syntax"],
        "grammarReviewed": ["gram_c1_legal_statutory_framing"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c1_04_statutory_legislative_drafting"],
        "communicativeFunctionsReviewed": ["comm_b2_09_formal_policy_recommendations"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": ["мэдээлэл гаргагч", "маргаан үүсгэх", "үндсэн хуулийн зөрчил", "хүсэлт"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Draft a formal constitutional petition detailing statutory inconsistency, factual background, and legal grounds for nullification.",
        "spokenProductionObjective": "",
        "registerTarget": "constitutional judicial chancellery",
        "pragmaticTarget": "formal constitutional petitioning",
        "prerequisiteLessonIds": ["les_c1_204_03_constitutional_dispute_argumentation_spoken"],
        "reviewsLessonIds": ["les_c1_203_04_drafting_grounds_for_appeal_writing"],
        "reviewsUnitIds": ["unit_c1_203_courtroom_argumentation_prosecutor_"],
        "reviewReason": "Extends appellate judicial pleading drafting into constitutional petition formulation.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Constructs a four-part petition containing jurisdictional basis, factual narrative, constitutional analysis, and specific prayers",
          "Demonstrates direct causal infringement between the challenged statutory article and constitutional articles"
        ],
        "masteryEvidence": "Submits a compliant 450-word petition to the Constitutional Court challenging an unconstitutional executive licensing fee.",
        "recommendedExerciseModalities": ["statutory_clause_drafting", "summary_writing"]
      }
    ])

    # ----------------------------------------------------
    # UNIT 205: Bilateral Concession Contracts & Investment Disputes (PL=22, RL=26, PE=8, RE=6)
    # ----------------------------------------------------
    lessons.extend([
      {
        "lessonId": "les_c1_205_01_concession_agreements_arbitration_clauses_reading",
        "unitId": "unit_c1_205_bilateral_concession_contracts_inve",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 1,
        "title": "Commercial Reading: Mineral Concession Contracts & International Arbitration Clauses",
        "lessonType": "reading",
        "primaryPurpose": "Parse an authentic 510-word excerpt from a public-private partnership concession agreement (Концессын гэрээ), examining stabilization clauses, sovereign immunity waivers, and arbitration clauses.",
        "communicativeOutcome": "Deconstruct complex international commercial contracts in Mongolian, identifying risks, dispute escalation tiers, and choice-of-law provisions.",
        "objectivesIntroduced": ["obj_c1_205_01_parse_concession_contracts"],
        "objectivesPracticed": ["obj_c1_200_01_master_statutory_framing"],
        "objectivesReviewed": ["obj_c1_198_01_parse_chancellery_nominalizations"],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_legal_statutory_framing"],
        "grammarReviewed": ["gram_c1_administrative_chancellery_syntax"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": ["comm_c1_04_statutory_legislative_drafting"],
        "communicativeFunctionsPracticed": [],
        "communicativeFunctionsReviewed": ["comm_b2_10_high_stakes_negotiation"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law", "lex_c1_macroeconomics_trade_finance"],
        "previousVocabularyReused": ["концесс", "арбитрын шүүх", "тогтворжуулах гэрээ", "маргаан шийдвэрлэх"],
        "readingObjective": "Analyze complex commercial concession terms, decoding arbitration triggers, damages calculation formulas, and force majeure exclusions.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "international commercial legal",
        "pragmaticTarget": "contractual risk assessment",
        "prerequisiteLessonIds": ["les_c1_204_04_petition_to_constitutional_court_writing"],
        "reviewsLessonIds": ["les_c1_200_02_statutory_articles_subclauses_reading"],
        "reviewsUnitIds": ["unit_c1_200_statutory_drafting_legal_framing_fo"],
        "reviewReason": "Applies statutory code analysis to international commercial concession agreements.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Identifies the specific institutional rules (e.g. UNCITRAL vs MIAC) designated for dispute resolution",
          "Extracts how stabilization clauses insulate foreign concessionaires from domestic regulatory changes"
        ],
        "masteryEvidence": "Drafts an executive risk audit highlighting 3 ambiguous liability clauses in a 510-word concession contract.",
        "recommendedExerciseModalities": ["source_comparison", "claim_evidence_matching"]
      },
      {
        "lessonId": "les_c1_205_02_commercial_arbitration_tribunal_listening",
        "unitId": "unit_c1_205_bilateral_concession_contracts_inve",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 2,
        "title": "Acoustic Dissection: International Commercial Arbitration Tribunal Hearing",
        "lessonType": "listening",
        "primaryPurpose": "Listen to a 4.5-minute audio simulation of an international commercial arbitration hearing at the Mongolian International Arbitration Center (МҮХАҮТ-ын дэргэдэх Монголын Олон Улсын Арбитр) concerning breach of a mining concession.",
        "communicativeOutcome": "Comprehend technical commercial dispute testimonies, cross-examinations of valuation experts, and tribunal president rulings.",
        "objectivesIntroduced": ["obj_c1_205_02_comprehend_arbitration_hearings"],
        "objectivesPracticed": ["obj_c1_205_01_parse_concession_contracts"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_legal_statutory_framing"],
        "grammarReviewed": ["gram_c1_administrative_chancellery_syntax"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c1_04_statutory_legislative_drafting"],
        "communicativeFunctionsReviewed": ["comm_b2_02_parliamentary_interpellation"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 7,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law", "lex_c1_macroeconomics_trade_finance"],
        "previousVocabularyReused": ["арбитрч", "нэхэмжлэгч", "хариуцагч", "гэрээний үүрэг", "хохирол"],
        "readingObjective": "",
        "listeningObjective": "Decipher rapid commercial cross-examination regarding contract fulfillment, royalty payment schedules, and expropriation claims.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "international commercial arbitration",
        "pragmaticTarget": "arbitral dispute resolution",
        "prerequisiteLessonIds": ["les_c1_205_01_concession_agreements_arbitration_clauses_reading"],
        "reviewsLessonIds": ["les_c1_203_02_judicial_hearing_prosecutorial_summation_listening"],
        "reviewsUnitIds": ["unit_c1_203_courtroom_argumentation_prosecutor_"],
        "reviewReason": "Bridges courtroom judicial trial listening into commercial arbitration tribunal hearings.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide authentic arbitral chamber audio featuring multi-party cross-examination and legal evidentiary objections.",
        "successCriteria": [
          "Transcribes the exact financial claim and interest penalty sought by claimant counsel",
          "Distinguishes between undisputed facts and contested valuation methodology"
        ],
        "masteryEvidence": "Produces an arbitral bench briefing detailing claimant demands, defense rebuttals, and key tribunal questions.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "discourse_analysis"]
      },
      {
        "lessonId": "les_c1_205_03_arbitration_memorial_claim_drafting_writing",
        "unitId": "unit_c1_205_bilateral_concession_contracts_inve",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 3,
        "title": "Commercial Writing: Statement of Claim (Нэхэмжлэлийн шаардлага) in Arbitration",
        "lessonType": "writing",
        "primaryPurpose": "Author a 440-word formal Statement of Claim for submission to an international arbitration tribunal, pleading expropriation and breach of a bilateral investment treaty (Хоёр талын хөрөнгө оруулалтын гэрээ).",
        "communicativeOutcome": "Produce high-stakes commercial arbitration pleadings with precise contractual citations and liquidated damages claims.",
        "objectivesIntroduced": ["obj_c1_205_03_author_arbitration_claims"],
        "objectivesPracticed": ["obj_c1_205_01_parse_concession_contracts"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_legal_statutory_framing"],
        "grammarReviewed": ["gram_c1_administrative_chancellery_syntax"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c1_04_statutory_legislative_drafting"],
        "communicativeFunctionsReviewed": ["comm_b2_09_formal_policy_recommendations"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law", "lex_c1_macroeconomics_trade_finance"],
        "previousVocabularyReused": ["нэхэмжлэл", "нөхөн олговор", "хөрөнгө хураах", "гэрээ цуцлах"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Draft a formal commercial arbitration memorial setting out jurisdiction, facts, legal breach, and quantified damages.",
        "spokenProductionObjective": "",
        "registerTarget": "commercial legal arbitration",
        "pragmaticTarget": "formal arbitral claim enforcement",
        "prerequisiteLessonIds": ["les_c1_205_02_commercial_arbitration_tribunal_listening"],
        "reviewsLessonIds": ["les_c1_204_04_petition_to_constitutional_court_writing"],
        "reviewsUnitIds": ["unit_c1_204_constitutional_court_jurisprudence_"],
        "reviewReason": "Synthesizes constitutional petition drafting into international commercial arbitration memorial writing.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Structures the memorial with immaculate procedural sections: jurisdiction, merits, and quantum of damages",
          "Deploys legal statutory framing formulas ('үүрэг хүлээнэ', 'нөхөн төлөх үүрэгтэй') without ambiguity"
        ],
        "masteryEvidence": "Submits a 440-word arbitration memorial demanding restitution for unlawful concession cancellation.",
        "recommendedExerciseModalities": ["statutory_clause_drafting", "summary_writing"]
      },
      {
        "lessonId": "les_c1_205_04_settlement_negotiation_dispute_advocacy_spoken",
        "unitId": "unit_c1_205_bilateral_concession_contracts_inve",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 4,
        "title": "Commercial Advocacy: High-Stakes Investor-State Dispute Settlement Negotiation",
        "lessonType": "spoken_production",
        "primaryPurpose": "Conduct an unscripted 4-minute bilateral negotiation representing the Ministry of Justice opposite foreign investor counsel, seeking an amicable settlement before arbitration awards are formalized.",
        "communicativeOutcome": "Negotiate multi-million dollar contractual concessions orally, balancing sovereign interests against international treaty liabilities.",
        "objectivesIntroduced": ["obj_c1_205_04_negotiate_investment_settlements"],
        "objectivesPracticed": ["obj_c1_205_01_parse_concession_contracts"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_legal_statutory_framing"],
        "grammarReviewed": ["gram_c1_administrative_chancellery_syntax"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c1_04_statutory_legislative_drafting"],
        "communicativeFunctionsReviewed": ["comm_b2_10_high_stakes_negotiation"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 7,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law", "lex_c1_macroeconomics_trade_finance"],
        "previousVocabularyReused": ["эвлэрлийн гэрээ", "буулт хийх", "нөхцөл тохиролцох", "эрсдэл бууруулах"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Argue commercial and sovereign positions with tactical flexibility, countering punitive penalty demands with structured compromises.",
        "registerTarget": "diplomatic commercial consultative",
        "pragmaticTarget": "strategic settlement compromise",
        "prerequisiteLessonIds": ["les_c1_205_03_arbitration_memorial_claim_drafting_writing"],
        "reviewsLessonIds": ["les_c1_204_03_constitutional_dispute_argumentation_spoken"],
        "reviewsUnitIds": ["unit_c1_204_constitutional_court_jurisprudence_"],
        "reviewReason": "Bridges constitutional court advocacy into bilateral investor-state contract negotiations.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide model dialogue of senior legal counsel negotiating a settlement in a concession dispute.",
        "successCriteria": [
          "Maintains calm diplomatic firmness while rejecting punitive claims",
          "Formulates concrete restructuring proposals using precise commercial legal syntax"
        ],
        "masteryEvidence": "Successfully negotiates a restructuring agreement across a 4-minute recorded bilateral simulation.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
      }
    ])

    # ----------------------------------------------------
    # UNIT 206: Drafting Executive & Ministerial Decrees (PL=22, RL=26, PE=8, RE=6)
    # ----------------------------------------------------
    lessons.extend([
      {
        "lessonId": "les_c1_206_01_cabinet_resolution_structures_reading",
        "unitId": "unit_c1_206_drafting_executive_ministerial_decr",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 1,
        "title": "Administrative Reading: Cabinet Resolutions & Subordinate Regulatory Decrees",
        "lessonType": "reading",
        "primaryPurpose": "Parse a 500-word comprehensive Cabinet Resolution (Засгийн газрын тогтоол) approving national public procurement regulations and delegation matrices.",
        "communicativeOutcome": "Deconstruct administrative regulatory instruments, analyzing enabling statute citations, operative mandates, appendices, and oversight mechanisms.",
        "objectivesIntroduced": ["obj_c1_206_01_parse_cabinet_resolutions"],
        "objectivesPracticed": ["obj_c1_202_01_master_causative_nominalizations"],
        "objectivesReviewed": ["obj_c1_199_01_master_classical_jussives"],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_causative_nominalizations_in_governance"],
        "grammarReviewed": ["gram_c1_archaic_jussive_sugai_tugai"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": ["comm_c1_04_statutory_legislative_drafting"],
        "communicativeFunctionsPracticed": [],
        "communicativeFunctionsReviewed": ["comm_b2_09_formal_policy_recommendations"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 7,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": ["засгийн газрын тогтоол", "журам батлах", "хэрэгжилтэд хяналт тавих", "хавсралт"],
        "readingObjective": "Critique complex secondary legislation instruments, assessing whether executive regulations exceed statutory parliamentary mandates.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "executive administrative regulatory",
        "pragmaticTarget": "regulatory compliance analysis",
        "prerequisiteLessonIds": ["les_c1_205_04_settlement_negotiation_dispute_advocacy_spoken"],
        "reviewsLessonIds": ["les_c1_199_02_presidential_decree_preambles_reading"],
        "reviewsUnitIds": ["unit_c1_199_archaic_classical_jussives_suffixes"],
        "reviewReason": "Compares presidential decree architectures with executive cabinet regulatory resolutions.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Identifies the parent statute and specific authorizing article in the preamble",
          "Distinguishes between binding regulatory commands and hortatory guidance in the resolution annex"
        ],
        "masteryEvidence": "Evaluates the legal validity and intra vires status of an executive decree based on the authorizing statutory text.",
        "recommendedExerciseModalities": ["source_comparison", "claim_evidence_matching"]
      },
      {
        "lessonId": "les_c1_206_02_drafting_ministerial_decree_statutory_rationale_writing",
        "unitId": "unit_c1_206_drafting_executive_ministerial_decr",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 2,
        "title": "Chancellery Writing: Drafting Ministerial Orders (Сайдын тушаал) & Regulatory Procedures",
        "lessonType": "writing",
        "primaryPurpose": "Author a 430-word Ministerial Order with accompanying procedural regulation ('Журам батлах тухай сайдын тушаал') implementing national digital data security standards.",
        "communicativeOutcome": "Produce legally airtight ministerial orders and administrative regulations adhering strictly to the General Administrative Law of Mongolia.",
        "objectivesIntroduced": ["obj_c1_206_02_draft_ministerial_orders"],
        "objectivesPracticed": ["obj_c1_206_01_parse_cabinet_resolutions"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_administrative_chancellery_syntax"],
        "grammarReviewed": ["gram_c1_archaic_jussive_sugai_tugai"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c1_04_statutory_legislative_drafting"],
        "communicativeFunctionsReviewed": ["comm_b2_09_formal_policy_recommendations"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": ["сайдын тушаал", "тушаах нь", "мөрдөх", "бүртгэл", "хууль зүйн яам"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Draft an official ministerial order containing preambular authorizations, operative provisions ('Тушаасугай'), and multi-article regulations.",
        "spokenProductionObjective": "",
        "registerTarget": "ministerial chancellery regulatory",
        "pragmaticTarget": "administrative regulatory enactment",
        "prerequisiteLessonIds": ["les_c1_206_01_cabinet_resolution_structures_reading"],
        "reviewsLessonIds": ["les_c1_199_03_drafting_statutory_enactments_writing"],
        "reviewsUnitIds": ["unit_c1_199_archaic_classical_jussives_suffixes"],
        "reviewReason": "Synthesizes classical jussives into contemporary ministerial decree drafting.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Incorporates formulaic enacting jussives ('тушаасугай', 'даалгасугай') in accordance with ministry drafting manuals",
          "Avoids ultra vires expansion of ministry authority beyond the statutory delegation"
        ],
        "masteryEvidence": "Submits a complete draft ministerial order and annex establishing data governance protocols ready for Ministry of Justice state registration.",
        "recommendedExerciseModalities": ["statutory_clause_drafting", "summary_writing"]
      },
      {
        "lessonId": "les_c1_206_03_cabinet_press_secretary_decree_announcement_listening",
        "unitId": "unit_c1_206_drafting_executive_ministerial_decr",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 3,
        "title": "Acoustic Dissection: Government Press Briefing on Major Executive Resolutions",
        "lessonType": "listening",
        "primaryPurpose": "Listen to a 4-minute live press briefing by the Cabinet Press Secretary and Minister of Justice explaining newly adopted government decrees regarding emergency economic measures.",
        "communicativeOutcome": "Process fast-paced institutional press announcements (155-180 wpm), separating official policy rationale from journalist inquiries.",
        "objectivesIntroduced": ["obj_c1_206_03_comprehend_cabinet_briefings"],
        "objectivesPracticed": ["obj_c1_206_01_parse_cabinet_resolutions"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_causative_nominalizations_in_governance"],
        "grammarReviewed": ["gram_c1_administrative_chancellery_syntax"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c1_04_statutory_legislative_drafting"],
        "communicativeFunctionsReviewed": ["comm_b2_02_parliamentary_interpellation"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": ["хэвлэлийн хурал", "мэдээлэл хийх", "засгийн газрын хуралдаан", "сэтгүүлчдийн асуулт"],
        "readingObjective": "",
        "listeningObjective": "Comprehend rapid-fire government press conference speech, tracking policy declarations, implementation timelines, and spontaneous ministerial rebuttals.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "institutional government press",
        "pragmaticTarget": "official policy clarification",
        "prerequisiteLessonIds": ["les_c1_206_01_cabinet_resolution_structures_reading"],
        "reviewsLessonIds": ["les_c1_202_05_administrative_enforcement_hearing_listening"],
        "reviewsUnitIds": ["unit_c1_202_causative_nominalizations_in_instit"],
        "reviewReason": "Transitions from administrative hearing audio to live cabinet press conference broadcasts.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide authentic press conference recording with rapid journalistic questions and official spokesperson cadences.",
        "successCriteria": [
          "Identifies the precise effective date and financial scope of the emergency economic decree",
          "Distinguishes between mandatory decree provisions and voluntary industry recommendations"
        ],
        "masteryEvidence": "Produces an executive summary of the press conference clarifying 3 controversial policy questions.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "stance_identification"]
      },
      {
        "lessonId": "les_c1_206_04_executive_order_regulatory_defense_spoken",
        "unitId": "unit_c1_206_drafting_executive_ministerial_decr",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 4,
        "title": "Executive Advocacy: Defending Ministerial Regulations Against Administrative Challenge",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver an unscripted 4-minute defense of a controversial ministerial order before the Administrative Court or Public Scrutiny Council, proving compliance with the General Administrative Law.",
        "communicativeOutcome": "Articulate executive legal authority, administrative necessity, and procedural proportionality with consummate professional composure.",
        "objectivesIntroduced": ["obj_c1_206_04_defend_regulations_orally"],
        "objectivesPracticed": ["obj_c1_206_01_parse_cabinet_resolutions"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_causative_nominalizations_in_governance"],
        "grammarReviewed": ["gram_c1_administrative_chancellery_syntax"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c1_04_statutory_legislative_drafting"],
        "communicativeFunctionsReviewed": ["comm_b2_10_high_stakes_negotiation"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 7,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": ["захиргааны хэрэг", "хууль ёсны ашиг сонирхол", "зохицуулалт", "нийтийн эрх ашиг"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Argue persuasively in defense of executive regulations, demonstrating procedural compliance and public interest balance.",
        "registerTarget": "administrative judicial defensive",
        "pragmaticTarget": "institutional regulatory defense",
        "prerequisiteLessonIds": ["les_c1_206_02_drafting_ministerial_decree_statutory_rationale_writing"],
        "reviewsLessonIds": ["les_c1_202_04_inter_ministerial_coordination_briefing_spoken"],
        "reviewsUnitIds": ["unit_c1_202_causative_nominalizations_in_instit"],
        "reviewReason": "Elevates internal administrative coordination into public and judicial defense of ministerial regulations.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide benchmark audio of ministry legal department director defending regulatory procedures before administrative hearing.",
        "successCriteria": [
          "Deploys formal administrative terms ('сонсох ажиллагаа', 'эрх мэдлийн хязгаар') accurately",
          "Rebuts allegations of administrative overreach citing statutory authorizations without delay"
        ],
        "masteryEvidence": "Defends a contentious environmental regulation across a 4-minute simulated hearing against aggressive industry cross-examination.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
      }
    ])

    # ----------------------------------------------------
    # UNIT 207: Constitutional Jurisprudence Capstone: Supreme Court Appeal (PL=26, RL=30, PE=11, RE=8)
    # ----------------------------------------------------
    lessons.extend([
      {
        "lessonId": "les_c1_207_01_supreme_court_dossier_analysis_reading",
        "unitId": "unit_c1_207_constitutional_jurisprudence_capsto",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 1,
        "title": "Capstone Jurisprudential Reading: Supreme Court En Banc Landmark Case Dossier",
        "lessonType": "reading",
        "primaryPurpose": "Parse a comprehensive 560-word case file and judicial opinion from the Supreme Court of Mongolia (Улсын Дээд Шүүхийн Хяналтын Шатны Тогтоол) resolving conflicting lower court interpretations of constitutional property guarantees.",
        "communicativeOutcome": "Dissect the ultimate appellate judicial reasoning in Mongolia, tracing statutory construction canons, constitutional harmonization, and binding judicial precedent formulations.",
        "objectivesIntroduced": ["obj_c1_207_01_master_supreme_court_dossiers"],
        "objectivesPracticed": ["obj_c1_198_01_parse_chancellery_nominalizations", "obj_c1_204_01_parse_tsets_jurisprudence"],
        "objectivesReviewed": ["obj_c1_200_01_master_statutory_framing"],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_administrative_chancellery_syntax"],
        "grammarReviewed": ["gram_c1_legal_statutory_framing", "gram_c1_causative_nominalizations_in_governance"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": ["comm_c1_04_statutory_legislative_drafting"],
        "communicativeFunctionsPracticed": [],
        "communicativeFunctionsReviewed": ["comm_b2_13_scholarly_synthesis"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": ["улсын дээд шүүх", "хяналтын шат", "тайлбарлах", "нэг мөр хэрэглэх", "эцсийн шийдвэр"],
        "readingObjective": "Critique complex en banc Supreme Court rulings that establish definitive statutory interpretations binding across the judiciary.",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "supreme judicial precedent",
        "pragmaticTarget": "definitive judicial interpretation",
        "prerequisiteLessonIds": ["les_c1_206_04_executive_order_regulatory_defense_spoken"],
        "reviewsLessonIds": ["les_c1_204_01_tsets_verdicts_and_conclusions_reading"],
        "reviewsUnitIds": ["unit_c1_204_constitutional_court_jurisprudence_"],
        "reviewReason": "Synthesizes Constitutional Court jurisprudence with Supreme Court statutory interpretation precedents.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Extracts the core rule of law ('хууль хэрэглээний нэгдмэл байдал') established by the Supreme Court bench",
          "Distinguishes obiter dicta commentary from binding ratio decidendi precedents"
        ],
        "masteryEvidence": "Constructs an authoritative 350-word juristic analysis summarizing the judicial doctrine established in the landmark case.",
        "recommendedExerciseModalities": ["argument_mapping", "source_comparison"]
      },
      {
        "lessonId": "les_c1_207_02_full_bench_judicial_interrogation_listening",
        "unitId": "unit_c1_207_constitutional_jurisprudence_capsto",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 2,
        "title": "Acoustic Dissection: Supreme Court Full Chamber (Хяналтын шат) Oral Interrogation",
        "lessonType": "listening",
        "primaryPurpose": "Listen to a 5-minute unedited recording of a Supreme Court cassation hearing where five Supreme Court justices rigorously interrogate appellate counsel regarding statutory conflicts.",
        "communicativeOutcome": "Comprehend the pinnacle of Mongolian judicial speech, processing rapid multi-judge questioning (160-185 wpm) delivered in reverberant court acoustics.",
        "objectivesIntroduced": ["obj_c1_207_02_comprehend_supreme_court_interrogation"],
        "objectivesPracticed": ["obj_c1_207_01_master_supreme_court_dossiers"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_administrative_chancellery_syntax"],
        "grammarReviewed": ["gram_c1_legal_statutory_framing"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c1_04_statutory_legislative_drafting"],
        "communicativeFunctionsReviewed": ["comm_b2_02_parliamentary_interpellation"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": ["хяналтын шатны шүүх хуралдаан", "шүүгчийн асуулт", "хариулт", "тайлбар"],
        "readingObjective": "",
        "listeningObjective": "Decipher fast-paced judicial cross-interrogation dissecting complex statutory doctrines and legislative intent.",
        "writingObjective": "",
        "spokenProductionObjective": "",
        "registerTarget": "supreme judicial deliberative",
        "pragmaticTarget": "apex judicial interrogation",
        "prerequisiteLessonIds": ["les_c1_207_01_supreme_court_dossier_analysis_reading"],
        "reviewsLessonIds": ["les_c1_204_02_tsets_plenary_session_deliberation_listening"],
        "reviewsUnitIds": ["unit_c1_204_constitutional_court_jurisprudence_"],
        "reviewReason": "Consolidates constitutional oral hearing comprehension into supreme appellate judicial chamber interrogations.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide live courtroom audio of Supreme Court Chamber proceedings with multi-speaker judicial questioning and counsel responses.",
        "successCriteria": [
          "Transcribes the legal hypothesis and statutory contradiction posed by the presiding judge accurately",
          "Evaluates whether the arguing advocate's oral answer resolved or deepened the judicial panel's doubts"
        ],
        "masteryEvidence": "Produces an exhaustive judicial colloquy transcript and analytical breakdown from the 5-minute recording.",
        "recommendedExerciseModalities": ["extended_listening_comprehension", "discourse_analysis"]
      },
      {
        "lessonId": "les_c1_207_03_appellate_memorandum_of_law_writing",
        "unitId": "unit_c1_207_constitutional_jurisprudence_capsto",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 3,
        "title": "Capstone Writing: Comprehensive Cassation Petition (Хяналтын журмаар гаргах гомдол)",
        "lessonType": "writing",
        "primaryPurpose": "Author a 460-word authoritative Cassation Petition to the Supreme Court of Mongolia, synthesizing chancellery syntax, statutory framing, and constitutional doctrines.",
        "communicativeOutcome": "Produce an exemplary appellate legal brief satisfying all formal requirements for Supreme Court review under the Civil or Administrative Procedure Code.",
        "objectivesIntroduced": ["obj_c1_207_03_author_cassation_petitions"],
        "objectivesPracticed": ["obj_c1_207_01_master_supreme_court_dossiers"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_administrative_chancellery_syntax"],
        "grammarReviewed": ["gram_c1_legal_statutory_framing", "gram_c1_causative_nominalizations_in_governance"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c1_04_statutory_legislative_drafting"],
        "communicativeFunctionsReviewed": ["comm_b2_09_formal_policy_recommendations"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": ["хяналтын гомдол", "хууль буруу тайлбарласан", "шийдвэрийг хүчингүй болгох"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Draft a master-level cassation appeal detailing lower court misinterpretations and demonstrating that the appeal raises an issue of nationwide jurisprudence.",
        "spokenProductionObjective": "",
        "registerTarget": "supreme judicial chancellery",
        "pragmaticTarget": "formal cassation advocacy",
        "prerequisiteLessonIds": ["les_c1_207_02_full_bench_judicial_interrogation_listening"],
        "reviewsLessonIds": ["les_c1_203_04_drafting_grounds_for_appeal_writing"],
        "reviewsUnitIds": ["unit_c1_203_courtroom_argumentation_prosecutor_"],
        "reviewReason": "Extends intermediate appellate notice of appeal drafting into supreme court cassation brief composition.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Demonstrates that lower court rulings created conflicting jurisprudence across appellate circuits",
          "Applies sophisticated participial nominalizations and deontic statutory modifiers without flaw"
        ],
        "masteryEvidence": "Submits a compliant 460-word Cassation Petition requesting full reversal of an appellate court judgment.",
        "recommendedExerciseModalities": ["statutory_clause_drafting", "summary_writing"]
      },
      {
        "lessonId": "les_c1_207_04_constitutional_remedies_amicus_brief_writing",
        "unitId": "unit_c1_207_constitutional_jurisprudence_capsto",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 4,
        "title": "Capstone Writing: Amicus Curiae Jurisprudential Advisory Opinion",
        "lessonType": "writing",
        "primaryPurpose": "Author a 450-word Amicus Curiae brief submitted by the National Human Rights Commission or Bar Association to the Supreme Court En Banc regarding statutory harmony and civil liberties.",
        "communicativeOutcome": "Produce high-register impartial juristic counsel evaluating broad public policy implications and international treaty compliance.",
        "objectivesIntroduced": ["obj_c1_207_04_author_amicus_opinions"],
        "objectivesPracticed": ["obj_c1_207_01_master_supreme_court_dossiers"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_administrative_chancellery_syntax"],
        "grammarReviewed": ["gram_c1_legal_statutory_framing", "gram_c1_causative_nominalizations_in_governance"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c1_04_statutory_legislative_drafting"],
        "communicativeFunctionsReviewed": ["comm_b2_13_scholarly_synthesis"],
        "newProductiveLemmaTarget": 5,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 2,
        "newReceptiveExpressionTarget": 2,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": ["хөндлөнгийн дүгнэлт", "хүний эрхийн үндэсний комисс", "олон улсын гэрээ конвенц"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "Author an amicus curiae memorandum analyzing constitutional rights doctrines and recommending systemic statutory harmonization.",
        "spokenProductionObjective": "",
        "registerTarget": "academic judicial advisory",
        "pragmaticTarget": "disinterested juristic counsel",
        "prerequisiteLessonIds": ["les_c1_207_03_appellate_memorandum_of_law_writing"],
        "reviewsLessonIds": ["les_c1_198_03_sovereign_rights_commentary_writing"],
        "reviewsUnitIds": ["unit_c1_198_the_1992_democratic_constitution_of"],
        "reviewReason": "Synthesizes constitutional commentary writing into high-level amicus curiae legal brief formulation.",
        "audioSuitability": "none",
        "audioPurpose": None,
        "successCriteria": [
          "Balances domestic constitutional norms against ratified international human rights covenants",
          "Adopts an objective, authoritative advisory tone avoiding partisan litigant bias"
        ],
        "masteryEvidence": "Submits a 450-word Amicus brief guiding the Supreme Court on privacy rights in digital communications surveillance.",
        "recommendedExerciseModalities": ["statutory_clause_drafting", "summary_writing"]
      },
      {
        "lessonId": "les_c1_207_05_supreme_court_en_banc_oral_argument_spoken",
        "unitId": "unit_c1_207_constitutional_jurisprudence_capsto",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 5,
        "title": "Capstone Advocacy: Supreme Court En Banc Oral Pleading & Judicial Defense",
        "lessonType": "spoken_production",
        "primaryPurpose": "Deliver an unscripted 4.5-minute oral pleading before the Full Bench of the Supreme Court of Mongolia, defending a cassation petition and fielding demanding judicial scrutiny.",
        "communicativeOutcome": "Demonstrate pinnacle C1 spoken courtroom mastery, responding spontaneously to theoretical legal inquiries with effortless linguistic precision.",
        "objectivesIntroduced": ["obj_c1_207_05_deliver_supreme_court_oral_pleadings"],
        "objectivesPracticed": ["obj_c1_207_01_master_supreme_court_dossiers"],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": ["gram_c1_administrative_chancellery_syntax"],
        "grammarReviewed": ["gram_c1_legal_statutory_framing", "gram_c1_causative_nominalizations_in_governance"],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c1_04_statutory_legislative_drafting"],
        "communicativeFunctionsReviewed": ["comm_b2_10_high_stakes_negotiation"],
        "newProductiveLemmaTarget": 6,
        "newReceptiveLemmaTarget": 6,
        "newProductiveExpressionTarget": 3,
        "newReceptiveExpressionTarget": 1,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": ["хяналтын шатны шүүх", "өмгөөллийн үндэслэл", "хууль хэрэглээ", "эцсийн тайлбар"],
        "readingObjective": "",
        "listeningObjective": "",
        "writingObjective": "",
        "spokenProductionObjective": "Argue an advanced constitutional cassation petition orally before the Supreme Court justices, handling complex hypothetical counter-arguments with authority.",
        "registerTarget": "supreme judicial oratorical",
        "pragmaticTarget": "authoritative judicial persuasion",
        "prerequisiteLessonIds": ["les_c1_207_04_constitutional_remedies_amicus_brief_writing"],
        "reviewsLessonIds": ["les_c1_204_03_constitutional_dispute_argumentation_spoken"],
        "reviewsUnitIds": ["unit_c1_204_constitutional_court_jurisprudence_"],
        "reviewReason": "Culminates oral advocacy across Constitutional Court disputes into supreme appellate oral pleading mastery.",
        "audioSuitability": "native_speaker_preferred",
        "audioPurpose": "Provide benchmark audio of distinguished appellate advocate presenting oral arguments to the Supreme Court En Banc.",
        "successCriteria": [
          "Maintains impeccable judicial decorum and oratorical presence throughout the 4.5-minute plea",
          "Resolves judicial hypotheticals by citing statutory coherence and supreme constitutional principles without pause"
        ],
        "masteryEvidence": "Delivers an unscripted 4.5-minute oral defense before a simulated Supreme Court panel securing acceptance of the petition.",
        "recommendedExerciseModalities": ["oral_presentation_planning", "rebuttal_transformation"]
      },
      {
        "lessonId": "les_c1_207_06_c1_sec01_culminating_constitutional_capstone",
        "unitId": "unit_c1_207_constitutional_jurisprudence_capsto",
        "cefrLevel": "C1",
        "sequenceWithinUnit": 6,
        "title": "Culminating Synthesis Capstone: Section 01 Mastery Defense & Constitutional Dossier",
        "lessonType": "synthesis_capstone",
        "primaryPurpose": "Execute a comprehensive multi-stage Section 01 capstone synthesis integrating chancellery syntax, classical jussives, statutory framing, appositive titles, causative nominalizations, and judicial argumentation across a simulated national constitutional dispute.",
        "communicativeOutcome": "Demonstrate complete operational proficiency in Mongolian constitutional, statutory, and judicial discourse across all four communicative modalities.",
        "objectivesIntroduced": ["obj_c1_207_06_master_sec01_culminating_synthesis"],
        "objectivesPracticed": [
          "obj_c1_198_01_parse_chancellery_nominalizations",
          "obj_c1_199_01_master_classical_jussives",
          "obj_c1_200_01_master_statutory_framing",
          "obj_c1_201_01_master_appositive_titles",
          "obj_c1_202_01_master_causative_nominalizations"
        ],
        "objectivesReviewed": [],
        "grammarIntroduced": [],
        "grammarPracticed": [
          "gram_c1_administrative_chancellery_syntax",
          "gram_c1_archaic_jussive_sugai_tugai",
          "gram_c1_legal_statutory_framing",
          "gram_c1_complex_appositive_titles_and_epithets",
          "gram_c1_causative_nominalizations_in_governance"
        ],
        "grammarReviewed": [],
        "phonologyIntroduced": [],
        "phonologyPracticed": [],
        "phonologyReviewed": [],
        "communicativeFunctionsIntroduced": [],
        "communicativeFunctionsPracticed": ["comm_c1_04_statutory_legislative_drafting"],
        "communicativeFunctionsReviewed": ["comm_b2_13_scholarly_synthesis"],
        "newProductiveLemmaTarget": 0,
        "newReceptiveLemmaTarget": 0,
        "newProductiveExpressionTarget": 0,
        "newReceptiveExpressionTarget": 0,
        "lexicalDomains": ["lex_c1_jurisprudence_constitutional_law"],
        "previousVocabularyReused": [
          "үндсэн хууль", "цэц", "улсын дээд шүүх", "тогтоол", "зарлиг", "тушаал", "гомдол", "нэхэмжлэл"
        ],
        "readingObjective": "Synthesize multiple legal dossiers containing contradictory statutory interpretations, executive orders, and citizen claims.",
        "listeningObjective": "Extract legal points of contention from complex multi-party judicial hearings delivered at natural native pace.",
        "writingObjective": "Draft an authoritative, multi-section judicial opinion or comprehensive legal brief resolving the constitutional dispute.",
        "spokenProductionObjective": "Deliver an unscripted oral defense of the legal resolution before a panel of legal experts, fielding technical counter-arguments.",
        "registerTarget": "comprehensive state chancellery & judicial",
        "pragmaticTarget": "definitive juristic mastery and resolution",
        "prerequisiteLessonIds": [
          "les_c1_207_03_appellate_memorandum_of_law_writing",
          "les_c1_207_05_supreme_court_en_banc_oral_argument_spoken"
        ],
        "reviewsLessonIds": [
          "les_c1_198_01_administrative_chancellery_syntax_intro",
          "les_c1_199_01_archaic_jussive_syntax_intro",
          "les_c1_200_01_legal_statutory_framing_syntax_intro",
          "les_c1_201_01_complex_appositive_titles_syntax_intro",
          "les_c1_202_01_causative_nominalization_syntax_intro"
        ],
        "reviewsUnitIds": [
          "unit_c1_198_the_1992_democratic_constitution_of",
          "unit_c1_199_archaic_classical_jussives_suffixes",
          "unit_c1_200_statutory_drafting_legal_framing_fo",
          "unit_c1_201_appositive_titles_epithets_chancell",
          "unit_c1_202_causative_nominalizations_in_instit"
        ],
        "reviewReason": "Comprehensive culmination of all Section 01 grammar, lexical domains, and communicative functions.",
        "audioSuitability": "native_speaker_required",
        "audioPurpose": "Provide multi-speaker judicial deliberation recording representing the apex of formal Mongolian oratorical argumentation.",
        "successCriteria": [
          "Executes all 5 Section 01 grammatical structures flawlessly across written and oral tasks",
          "Resolves complex constitutional controversies demonstrating deep institutional comprehension",
          "Switches between state chancellery, statutory drafting, and oral adversarial registers without code confusion"
        ],
        "masteryEvidence": "Successfully defends an unabridged constitutional dossier comprising a 450-word written brief and a 4.5-minute oral defense before an expert panel.",
        "recommendedExerciseModalities": [
          "argument_mapping",
          "statutory_clause_drafting",
          "rebuttal_transformation"
        ]
      }
    ])

    return lessons
